### ISSUE TITLE
[core] EXIF JPG support

### ISSUE THREAD

**Issue by ArnautDaniel** [raysan5/raylib#1008]
I noticed that the library Raylib uses for image loading, stb_image, does not include support for opening jpgs made from digital cameras.

The project I'm currently working will need this functionality however.  

Has anyone tried expanding Raylib with a full jpeg library?  I'm considering trying to hack in [NanoJpg](https://keyj.emphy.de/nanojpeg/) for at least my own personal use.

I suppose this is more of a tangential issue of Raylib, but is there any goal on the timeline that includes adding more robust support for image loading?  And, if anyone is kind enough, are there any pointers for swapping out the jpg backend?

**Comment by raysan5** [comment]
Hello @ArnautDaniel, 

exif support is out of scope for raylib... but you can use [easyexif](https://github.com/mayanklahiri/easyexif) or [TinyEXIF](https://github.com/cdcseacave/TinyEXIF).
