### ISSUE TITLE
[examples]Error building script file 

### ISSUE THREAD

**Issue by MynameisBI** [raysan5/raylib#1020]
I followed [this guide](https://github.com/raysan5/raylib/wiki/Working-on-Raspberry-Pi/1bd32d300b9d9e76c5f66f3d6955495058992eda) to install raylib for my Raspberry Pi 3 B and compiled it successfully
But when I tried running a [simple script](https://drive.google.com/open?id=1BTdVDGoElIw5PSxC6rEUzzfEXOOHP73z) I got an error saying 'undefined reference to...'
Here's the script I used (I copied this from the [raylib examples: basic window](https://www.raylib.com/examples.html)) :

    #include "raylib.h"

    int main(void)
    {
        const int screenWidth = 800;
        const int screenHeight = 450;
        InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");
        SetTargetFPS(60);

        {
            BeginDrawing();

            ClearBackground(RAYWHITE);

            DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);

            EndDrawing();
        }

        CloseWindow();      

        return 0;
    }

Here's the error I got :

    gcc -Wall -o "nháp" "nháp.c" (in directory: /home/pi/Desktop)
    /usr/bin/ld: /tmp/ccbKLhup.o: in function `main':
    nháp.c:(.text+0x28): undefined reference to `InitWindow'
    /usr/bin/ld: nháp.c:(.text+0x30): undefined reference to `SetTargetFPS'
    /usr/bin/ld: nháp.c:(.text+0x34): undefined reference to `BeginDrawing'
    /usr/bin/ld: nháp.c:(.text+0x48): undefined reference to `ClearBackground'
    /usr/bin/ld: nháp.c:(.text+0x70): undefined reference to `DrawText'
    /usr/bin/ld: nháp.c:(.text+0x74): undefined reference to `EndDrawing'
    /usr/bin/ld: nháp.c:(.text+0x78): undefined reference to `CloseWindow'
    collect2: error: ld returned 1 exit status
    Compilation failed.

**Comment by hbiblia** [comment]
Aun le falta linkear la librería al compilador: 
(Windows) -lraylib -lopengl32 -lgdi32 -lwinmm 
(Linux) -lraylib -lGL -lm -lpthread -ldl -lrt

**Comment by MynameisBI** [comment]
So I linked the following library -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl and I got new errors saying that

    /usr/bin/ld: cannot find -lbcm_host
    /usr/bin/ld: cannot find -lbrcmEGL
    /usr/bin/ld: cannot find -lbrcmGLESv2
    collect2: error: ld returned 1 exit status
    Compilation failed.

Turn out those library is in /opt/vc/lib so I have to move those 3 library to /usr/lib
And it worked! I can compile and run the examples

**Comment by jubalh** [comment]
Its not a script
