### ISSUE TITLE
[models] glTF material colours?

### ISSUE THREAD

**Issue by electronstudio** [raysan5/raylib#1025]
Create object in Blender with material base colour set to red:

![image](https://user-images.githubusercontent.com/7192452/69494558-0f7de600-0eb5-11ea-9c09-a33d486e9f2c.png)

Export to glTF: 
[coloured.gltf.zip](https://github.com/raysan5/raylib/files/3883539/coloured.gltf.zip)

This how the material shows up in glTF file:

```
"materials" : [
        {
            "doubleSided" : true,
            "name" : "Material",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.8000000715255737,
                    0,
                    0.00022257522505242378,
                    1
                ],
                "metallicFactor" : 0,
                "roughnessFactor" : 0.4000000059604645
            }
        }
    ],
```

Raylib displays this model as white (if no texture is applied).

![image](https://user-images.githubusercontent.com/7192452/69494861-794bbf00-0eb8-11ea-81c1-3c202171b575.png)

The colour data is loaded, but it is into model.materials.maps[MAP_ROUGHNESS ] rather than model.materials.maps[MAP_DIFFUSE]. 

Should I be using a shader to get it to display the colour?

**Comment by electronstudio** [comment]
@Gamerfiend

**Comment by Gamerfiend** [comment]
So the color data is loaded into Raylib? But it's in the wrong map? Hmm.. I can take a look at the code and see if I can repro.

**Comment by raysan5** [comment]
@electronstudio @Gamerfiend glTF support still requires some work.

**Comment by electronstudio** [comment]
Any progress on this?  I don't really understand why it was closed if it still requires work?

**Comment by raysan5** [comment]
@electronstudio I think nobody is working on this issue, no intention to work on it from my part. I'm reopening it, feel free to contribute.

**Comment by electronstudio** [comment]
I understand that it's an open source community project so people will only work on what they need, and if I had time I would like to help, and if I had money I would like to donate... but I'm still confused by the model loading issues.

I think people are using Raylib to make games?  And doesn't every game require the ability to import models?  It seems like this should break the workflow of everyone who uses Raylib?

Sorry for complaining when I have no right to complain!

**Comment by raysan5** [comment]
@raysan5 raylib was primary intended for education, on a second place intended for small-medium 2D games (that do not require 3D models), never intended to be a full featured 3D engine, for that kind of projects I recommend professional engines like Unity or Unreal.

**Comment by electronstudio** [comment]
Well for my course I ended up using Godot, but it is more complicated.  maybe if I have time before next year's course I will try to improve the glTF import so I can use Raylib :-)

**Comment by chriscamacho** [comment]
@electronstudio wavefront OBJ (and other) loaders work just fine....

**Comment by electronstudio** [comment]
I tried the OBJ format initially.  It didn't work, and when I reported the problem on Discord I was told that glTF was better / more likely to be fixed.

**Comment by chriscamacho** [comment]
the only issues I've had with the OBJ importer were blender export issues, didn't work is a bit vague, if you can pin down a specific issue with the OBJ loader you should submit an issue...!

**Comment by Gamerfiend** [comment]
If anyone could test this, or I might be able to.. I am fairly sure it's fixed in the latest commits.

**Comment by chriscamacho** [comment]
I had a look at some of the "official" gltf models - buggy looks like it might have the right material colours, but its hard to tell as all the sub mesh positions and orientations are wrong...

**Comment by Gamerfiend** [comment]
The official models are horrible lol And for raylib, all transforms must be applied in Blender/Maya first.

**Comment by raysan5** [comment]
@Gamerfiend thank you very much for working on this issue! 😄
