### ISSUE TITLE
[rlgl] Build fails with OpenGL 1.1

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#1027]
I didn't tried to build C example, but it should be the same, with raylib-go:

        # go build -tags opengl11
        # github.com/gen2brain/raylib-go/raylib
        In file included from core.c:128:
        rlgl.h: In function 'rlTextureParameters':
        rlgl.h:1302:21: error: 'texMirrorClampSupported' undeclared (first use in this function)
         1302 |                 if (texMirrorClampSupported) glTexParameteri(GL_TEXTURE_2D, param, value);
              |                     ^~~~~~~~~~~~~~~~~~~~~~~
        rlgl.h:1302:21: note: each undeclared identifier is reported only once for each function it appears in

**Comment by raysan5** [comment]
@gen2brain thanks for reporting! Corrected! :D
