### ISSUE TITLE
[textures] Add more draw functions to ImageDraw*()

### ISSUE THREAD

**Issue by zaher** [raysan5/raylib#1028]
If that possible would you please add more drawing functions to image as like functions exists for texture, 
```
    ImageClearBackground
    ImgaeDrawPixel
    ImgaeDrawLine
    ImageDrawLineEx
    ImageDrawCircle
    ImageDrawPoly
etc
```
or any idea allow me more drawing on Image

**Comment by raysan5** [comment]
@zaher that's a good idea but low priority... what is your use case? why not use the hardware accelerated version directly?

**Comment by zaher** [comment]
No problem I can wait, 
I noticed Image is easy shared between threads, I tested it yeasterday, by using imagedrawtext.

I am working on old style like of graphical programming for kids, not a real game, I want to run Lua, BASIC, in another thread (hard to run it in main thread), with drawing functions like old ventage computers but with high quality images (modern languages), also allow some functions for this language to load image, and create sprites objects and control it in easy way.

this example for my old project when i used love2d, 
https://github.com/parmaja/love2d-tyro/blob/master/demos/sin.lua

I used coroutines, to run main script

now I moved to use raylib
https://github.com/parmaja/tyro

**Comment by raysan5** [comment]
@zaher Ok, I see, yeah, `Image` struct resides in RAM, no GPU required for `Image*()` functionality, actually, I created it for basic 2d software rendering in embedded platforms with no GPU... but keep in mind that it's very inefficient compared to hardware-accelerated rendering, I mean, probably the benefits you get multi-threading drawing with `Image*()` are slower than hardware rendering in a single thread.

One solution that pops into my mind is storing required shapes-textures drawing commands in second thread fom Lua/BASIC but actually perform the hardware-rendering in main thread iterating along drawing list... well, maybe over-engineering for your use case...

In any case, I'll try to add some of those functions in a future... also, code contributions are welcome... ;)

**Comment by zaher** [comment]
I did that queue/pool, creating objects in second thread, then pass it to main thread to execute it, [code](https://github.com/parmaja/tyro/blob/master/src/TyroClasses.pas#L526)
it is work fine, until I found my self need to probe color from canvas, (that need some functions too to get color from image, I had plan to ask  it later :P ) 

for image, I will optimize it by adding `changed` flag before need to convert it to texture, and this kind of project no need to be fast at this point, I will add object for sprites and background that will draw in main thread.

**Comment by raysan5** [comment]
Reviewing proposed image functions:

 - [x] `ImageClearBackground()`  -> It could be accomplished with `ImageDrawRectangle()`
 - [x] `ImageDrawPixel()` -> It could be accomplished with `ImageDrawRectangle()`
 - [ ] `ImageDrawLineEx()` -> TODO.
 - [ ] `ImageDrawCircle()` -> TODO.
 - `ImageDrawPoly()` -> Out of scope.

In any case, I'm don't plan to work on that. Just listed it here for possible contributors.

**Comment by raysan5** [comment]
Implemented on PR https://github.com/raysan5/raylib/pull/1138
