### ISSUE TITLE
[build] Update "Working for Android" wiki pages

### ISSUE THREAD

**Issue by malyutinegor** [raysan5/raylib#1030]
Hello!

[Working for Android](https://github.com/raysan5/raylib/wiki/Working-for-Android), [Working for Android (on Linux)](https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux)) and [Working for Android (on macOS)](https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-macOS)) wiki pages look really outdated. If it's possible, can someone update them, please?

**Comment by raysan5** [comment]
@malyutinegor feel free to edit them. They are open for editing.

**Comment by malyutinegor** [comment]
@raysan5 How can I edit them if I don't know how to build my game for Android? :D

**Comment by raysan5** [comment]
@malyutinegor yeah, that's a good point... I'll try to review it myself at some point...

**Comment by raysan5** [comment]
Closing this issue for now.
