### ISSUE TITLE
[text] Add option to load all glyph of a font instead of just the range between 32...126

### ISSUE THREAD

**Issue by holywyvern** [raysan5/raylib#1031]
Please, before submitting a new issue verify and check:

- [x] I tested it on latest raylib version from master branch
- [x] I checked there is no similar issue already reported
- [x] My code has no errors or misuse of raylib

### Issue description

Maybe, when a TTF file is loaded with default parameters, instead of specifically asking which glyphs the font should load, it should load the entire glyph collection by default.
IF someone actually loads a giant font collection I know it may crash, but that's another problem.

This come, from the neccesity of giving my user, for example, a name input, and I would like to see names like "Noël" widhtout me to knowing how many glyphs I should load beforehand.

Maybe giving -1 to the size of the `LoadFontEx` could do that.

### Environment

The platform it's not really a bug, as it is the current expected behaviour.
However, I'm using 2.5.0 and tested it in both windows and mac osx mojave.

### Code Example

Instead of:

```c
LoadFontEx(name, size, NULL, SOME_ARBITRARY_BIG_NUMBER);
```

it could be swapped by:

```c
LoadFontEx(name, size, NULL, -1); // This checks how many glyphs on the fonts are there and automatically adds all glyphs
```

If not a new function like `LoadFontPro` or `LoadCompleteFont(name, size)`, could be cool too:

```c
LoadFontPro(name, size);
```

**Comment by SolarLune** [comment]
What happens if you try the maximum size an int could possibly have to load as the `charsCount`? Does that make the function crash?

**Comment by raysan5** [comment]
I'm afraid that's not the best approach to font loading. `LoadFontEx()` already allows a *custom set of codepoints* (3rd parameter of the function) defined by user:
```c
int codepoints[5] = { 32, 45, (int)'A', 4567, 96 };   // Define required codepoints
Font font = LoadFontEx("resources/myfont.ttf", 32, codepoints, 5);  // Load required codepoints glyphs from font
```

User is responsible of providing the right font and loading the required glyphs. Also, `DrawText()` will draw a `?` if the required glyph is not available in the loaded font.
