### ISSUE TITLE
[build] Support GitHub Actions to build raylib on multiple platforms

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1033]
I'm considering replacing Travis and AppVeyor by GitHub Actions. It could be nice to use Actions for CI and CD.

Any expert on the room? :D

**Comment by raysan5** [comment]
I've just been working on this for  a couple of days, GitHub Actions is quite interesting, still learning how things work... but I already got sources and examples compilation on Windows, Linux and macOS, at least the basic configuration.

I decided to start with AppVeyor replacement. It just covers Windows platform and script seems easier to port than Travis one. I created a configuration matrix for MinGW/MSVC 32/64 bit.

MinGW 32bit compilation fails on CMake project generation. It's quite weird because MinGW 64bit compilation works like a charm. I'm attaching the output logs for reference:

[mingw_32bit_cmake_project_generation_errors.txt](https://github.com/raysan5/raylib/files/4046587/mingw_32bit_cmake_project_generation_errors.txt)
[mingw_64bit_cmake_project_generation_works.txt](https://github.com/raysan5/raylib/files/4046588/mingw_64bit_cmake_project_generation_works.txt)

@a3f please, could you take a look to this issue? I'm not an expert on CI, probably I'm missing something.

**Comment by raysan5** [comment]
After some investigation it seems there is some problem with CMake and MinGW on the first launch, second launch (the x64 version) works fine. As a temporal solution, I just skipped CMake for MinGW and used directly raylib Makefile, despite output directory is not properly set...

**Comment by raysan5** [comment]
GitHub Actions have been implemented for CI on Windows, Linux and macOS. Still way for improvement but closing issue for now.

**Comment by a3f** [comment]
Sorry for the late reply. Glad you got it working.
