### ISSUE TITLE
[core] SetWindowMonitor does nothing.

### ISSUE THREAD

**Issue by DropsOfSerenity** [raysan5/raylib#1035]
The current code for `SetWindowMonitor` only `TraceLog`'s out some stuff, why are we not using `glfwSetWindowMonitor`? It seems to be commented out.

The minimal implementation imo would be, if we are setting monitor to a different screen, obtain the screen mode/resolution, and pass them into `glfwSetWindowMonitor`.

E.g something like...

```c
const GLFWvidmode* mode = glfwGetVideoMode(monitors[monitor]);
glfwSetWindowMonitor(window, monitors[monitor], 0, 0, mode->width, mode->height, mode->refreshRate);

```

**Comment by raysan5** [comment]
@DropsOfSerenity Ouch! Good catch! I probably left it commented because it was not working properly and I forgot about it...

**Comment by raysan5** [comment]
@DropsOfSerenity Feel free to send a PR if you want

**Comment by DropsOfSerenity** [comment]
Will do @raysan5 my custom raylib build currently works for me on linux, but I'll want to test it on windows as well later today.

**Comment by DropsOfSerenity** [comment]
Pull request #1036 merged, closing issue.
