### ISSUE TITLE
[BUG] void rlClearScreenBuffers not working

### ISSUE THREAD

**Issue by Andonium500** [raysan5/raylib#1037]
Hi!

In my computer this void rlClearScreenBuffers not working, because the screen not delete anything in new frames. 

I try the lesson 4 and the next ones, and never delete the past texture in the image, like player. 

I think thats is a problem with my computer, but I need some advice about what can reproduce it?

Someone know something?

I tried to compile with npp and vs code

Thanks

regards

**Comment by raysan5** [comment]
Please, can you paste the code that fails?

**Comment by Andonium500** [comment]
Hi!

I attach the file
[Dungeon2D.txt](https://github.com/raysan5/raylib/files/3944612/Dungeon2D.txt)

thanks for all!

regards

**Comment by raysan5** [comment]
Tested the code and it crashes. Commenting Image loading and related code works as expected, so, the issue is not on `rlClearScreenBuffers()` but probably on `LoadImage()` function, on user code. Not an issue with raylib or rlgl.
