### ISSUE TITLE
Please support switch, xbox and ps4

### ISSUE THREAD

**Issue by Shadowblitz16** [raysan5/raylib#1038]
people making games are going to want to port them to consoles to make money,
can we get a port to the latest game consoles?

**Comment by Softizo** [comment]
Well IIRC Xbox is supported through UWP, for PS4 and Switch you can either get the devkits or you can try porting the games with the open-source PS4-SDK or Switch Homebrew (Which only work on devices that can run homebrew games).

**Comment by Shadowblitz16** [comment]
I'm not sure if nintendo or sony support dev kits for this though.

**Comment by Gamerfiend** [comment]
It's entirely possible to have this working on game consoles, however it requires a heavy lift and resources, which isn't something an open source project typically has. Xbox is currently supported as Softizo, but that was brought through community contribution and many hours of work. If you need the switch or ps4, you'll have to acquire a dev kit and work on it with others in the same situation as those require you to sign an NDA not allowing source code for an engine or framework that connects with them to be public. As always, community contributions are welcome :)

**Comment by Shadowblitz16** [comment]
@Gamerfiend @raysan5   So this is never going to be added?
the console stuff could be addon libraries that are kept closed source.

**Comment by gideongrinberg** [comment]
@Shadowblitz16 it's can't be, it's not possible. Xbox is supported via UWP. PS4 and Switch both support OpenGL _to some extent_. There's also the option to use Raylib on Homebrew consoles. I once saw a game jam where someone submitted a Raylib game running on Switch, Vista, and some other consoles.

(I can't really go into detail about the official APIs, since they are under NDA)

**Comment by GreenThunder245** [comment]
> 
> 
> @Shadowblitz16 it can't be, it's not possible to use these APIs in an Open Source project. However, Xbox is supported via UWP. PS4 and Switch both support OpenGL _to some extent_. There's also the option to use Raylib on Homebrew consoles. I once saw a game jam where someone submitted a Raylib game running on Switch, Vista, and some other consoles.
> 
> (I can't really go into detail about the official APIs, since they are under NDA)

That gamejam where someone submitted a raylib game on switch actually used SDL2

**Comment by SplaatSites** [comment]
I want raylib to be on xbox 360.
