### ISSUE TITLE
[texture] how to display webcam images?

### ISSUE THREAD

**Issue by copark86** [raysan5/raylib#1042]
Hi,
I have a video stream from a webcam and need to draw it on a box on the screen. So, there are other parts such as gui and 3d drawings and I need to add a small box that display a live stream of the image.

What would be the best way to do this job?

I have tried the image loading example but I have no idea how to deal with the update of the texture.

**Comment by copark86** [comment]
I found a solution. UpdateTexture works well.

**Comment by TheBricktop** [comment]
Mind sharing your experience?

**Comment by dakota72** [comment]
Can you share your solution?
