### ISSUE TITLE
[audio] Make querying whether audio is playing on a null buffer a warning, rather than an error

### ISSUE THREAD

**Issue by illegalinstruction** [raysan5/raylib#1044]
### Rationale: 

There are some cases where it might be useful to check if music is playing, and if so, slowly reduce the volume to 0 before loading and playing the next song, but to skip the fade-out logic if no music is playing; with this in mind, it might be helpful for `IsAudioBufferPlaying()` to warn and return false if the buffer it's called on is null, since, by definition, a null audio buffer _can't_ be playing, and the calling code may not care that it's null at the moment.

**Comment by raysan5** [comment]
Reviewed in commit https://github.com/raysan5/raylib/commit/f46fcb8307775b34ff2e4db94c5e5504b6252dc4
