### ISSUE TITLE
[Text] Text module functions share some function names with Windows API function and macro names.

### ISSUE THREAD

**Issue by Shylie** [raysan5/raylib#1046]
### Issue checks
- [✔] Tested it on latest raylib version from master branch
- [✔] Checked that there are no similar issues already reported
- [✔] My code has no errors or misuse of raylib

### Issue description

Text module functions share some function names with Windows API function and macro names. 

### Environment

64-bit Windows 10

### Code Example

```cpp
#include "raylib.h"
#include <Windows.h>

const int WINDOW_WIDTH = 400;
const int WINDOW_HEIGHT = 400;

int main(int, char**)
{
	InitWindow(WINDOW_WIDTH, WINDOW_HEIGHT, "Raylib Demo");

	SetTargetFPS(60);

	while (!WindowShouldClose())
	{
		// -- Draw --
		BeginDrawing();

		ClearBackground(RAYWHITE);

		DrawText("THIS DOESN'T COMPILE", 40, 40, 20, DARKGREEN);

		EndDrawing();
	}

	CloseWindow();

	return 0;
}

**Comment by raysan5** [comment]
There are some possible solutions to this issue, like embedding `windows.h` on its own unit module or just declaring the required functions from `windows.h` instead of including the full library.

No plans to change raylib naming for the moment.
