### ISSUE TITLE
[shapes] Support ellipses drawing in 2d and 3d space

### ISSUE THREAD

**Issue by Shadowblitz16** [raysan5/raylib#1047]
Please, before submitting a new issue verify and check:

 - [ x] I tested it on latest raylib version from master branch
 - [ x] I checked there is no similar issue already reported
 - [ x] My code has no errors or misuse of raylib

### Issue description

basically I would like to see a set of functions for drawing 2d and 3d ellipses including functions for collision.

basically these would just be circles that have both a x and y radius and z for 3d i guess.

I know how to use cos and sin to draw 2d ellipses with polygons however I wouldn't know how to do 3d versions or collision functions for them.

### Environment
- Windows 10 Pro Education 64 bit.
- OpenGL version is unknown
- Language C# .Net Framework 4.7.2

### Notes
Note I am using C# and raylib-cs however I do believe this would be the correct place to suggest it since raylib-cs is only a wrapper.

**Comment by raysan5** [comment]
@Shadowblitz16 Despite low priority, this could be a nice addition. Contributions are welcome.
