### ISSUE TITLE
[shapes] Support polygons drawing and SAT collisions

### ISSUE THREAD

**Issue by Shadowblitz16** [raysan5/raylib#1048]
- [ x] I tested it on latest raylib version from master branch
 - [ x] I checked there is no similar issue already reported
 - [ x] My code has no errors or misuse of raylib

### Issue description

Please implement 2d and 3d versions of variable point/vector polygon drawing and collision.
basically 2d versions would accept a array of xy points or vector2 
and 3d versions would accept a or a array of xyz points or vector3

I would personally make it so that..
- uncompleted points draw lines or just a point if it is 1 vertex
- uncompleted points can have a thickness (including if it only has 1 point)
- allow for optional fill color
- allow for optional outline color or outline color array

this would be really useful for making our own shapes and collisions by just passing in points of floats 

it could be called draw_shapable() or draw_shape() and check_shapeable() or check_shape()

### Environment
Windows 10 Pro Education 64 bit
OpenGL version unknown
Language C# .net framework 4.7.2

**Comment by raysan5** [comment]
@Shadowblitz16 that could be a nice feature for the future. Contributions are welcome!

RELATED: https://github.com/MarcMDE/satcollision

**Comment by raysan5** [comment]
About random polygon shapes drawing, it can be done with:
```c
void DrawLineStrip(Vector2 *points, int numPoints, Color color);
void DrawTriangleFan(Vector2 *points, int numPoints, Color color);
void DrawTriangleStrip(Vector2 *points, int pointsCount, Color color);
void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color);
void DrawPolyLines(Vector2 center, int sides, float radius, float rotation, Color color);
```
About SAT collisions I considered it's out of scope.

**Comment by Shadowblitz16** [comment]
@raysan5 can DrawLineStrip take a optional fill parameter?
basically it would try to fill it when it overlaps itself

**Comment by raysan5** [comment]
@Shadowblitz16 sorry, that's not a trivial implementation, no plans to implement it for the moment.
