### ISSUE TITLE
error building raylib under windows

### ISSUE THREAD

**Issue by Est83** [raysan5/raylib#1049]
I am not able to build raylib using the MAKE tool under windows
I have downloaded the windows installer: [raylib_installer_2.5.mingw.exe]
When i try to build raylib using mingw32-make i get these compiling errors:

C:\raylib\raylib\src>mingw32-make PLATFORM=PLATFORM_DESKTOP
gcc -c rglfw.c -O1 -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=
pointer-arith -fno-strict-aliasing -Werror=implicit-function-declaration  -I. -I
external/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_A
PI_OPENGL_33
In file included from rglfw.c:64:0:
external/glfw/src/win32_monitor.c: In function 'monitorCallback':
external/glfw/src/win32_monitor.c:50:13: error: implicit declaration of function
 'wcscmp' [-Werror=implicit-function-declaration]
         if (wcscmp(mi.szDevice, monitor->win32.adapterName) == 0)
             ^~~~~~
external/glfw/src/win32_monitor.c: In function 'createMonitor':
external/glfw/src/win32_monitor.c:101:5: error: implicit declaration of function
 'wcscpy' [-Werror=implicit-function-declaration]
     wcscpy(monitor->win32.adapterName, adapter->DeviceName);
     ^~~~~~
In file included from rglfw.c:67:0:
external/glfw/src/win32_window.c: In function 'updateCursorImage':
external/glfw/src/win32_window.c:248:41: warning: passing argument 2 of 'LoadCur
sorW' from incompatible pointer type [-Wincompatible-pointer-types]
             SetCursor(LoadCursorW(NULL, IDC_ARROW));
                                         ^~~~~~~~~
In file included from c:\mingw\include\windows.h:48:0,
                 from external/glfw/src/win32_platform.h:68,
                 from external/glfw/src/internal.h:185,
                 from external/glfw/src/context.c:28,
                 from rglfw.c:54:
c:\mingw\include\winuser.h:3999:27: note: expected 'LPCWSTR {aka const short uns
igned int *}' but argument is of type 'CHAR * {aka char *}'
 WINUSERAPI HCURSOR WINAPI LoadCursorW (HINSTANCE, LPCWSTR);
                           ^~~~~~~~~~~
In file included from rglfw.c:67:0:
external/glfw/src/win32_window.c: In function '_glfwRegisterWindowClassWin32':
external/glfw/src/win32_window.c:1334:42: warning: passing argument 2 of 'LoadCu
rsorW' from incompatible pointer type [-Wincompatible-pointer-types]
     wc.hCursor       = LoadCursorW(NULL, IDC_ARROW);
                                          ^~~~~~~~~
In file included from c:\mingw\include\windows.h:48:0,
                 from external/glfw/src/win32_platform.h:68,
                 from external/glfw/src/internal.h:185,
                 from external/glfw/src/context.c:28,
                 from rglfw.c:54:
c:\mingw\include\winuser.h:3999:27: note: expected 'LPCWSTR {aka const short uns
igned int *}' but argument is of type 'CHAR * {aka char *}'
 WINUSERAPI HCURSOR WINAPI LoadCursorW (HINSTANCE, LPCWSTR);
                           ^~~~~~~~~~~
In file included from rglfw.c:67:0:
external/glfw/src/win32_window.c:1345:31: warning: passing argument 2 of 'LoadIm
ageW' from incompatible pointer type [-Wincompatible-pointer-types]
                               IDI_APPLICATION, IMAGE_ICON,
                               ^~~~~~~~~~~~~~~
In file included from c:\mingw\include\windows.h:48:0,
                 from external/glfw/src/win32_platform.h:68,
                 from external/glfw/src/internal.h:185,
                 from external/glfw/src/context.c:28,
                 from rglfw.c:54:
c:\mingw\include\winuser.h:4011:26: note: expected 'LPCWSTR {aka const short uns
igned int *}' but argument is of type 'CHAR * {aka char *}'
 WINUSERAPI HANDLE WINAPI LoadImageW (HINSTANCE, LPCWSTR, UINT, int, int, UINT);
                          ^~~~~~~~~~
cc1.exe: some warnings being treated as errors
Makefile:504: recipe for target 'rglfw.o' failed
mingw32-make: *** [rglfw.o] Error 1

**Comment by yxor** [comment]
I have the same issue, apparently the installer is quite outdated, VSCode template from installer could also be broken.

You should try to use latest raylib from GitHub.

**Comment by raysan5** [comment]
Try with latest github master branch. It should build.
