### ISSUE TITLE
raylib dosnt work on win 7 32bit laptop

### ISSUE THREAD

**Issue by yoel123** [raysan5/raylib#1050]
system: win7 (laptop).

installed:

raylib 2.5 Windows Installer (with MinGW compiler)

i try to run Basic window.c the default project.

i get exit code:

Process finished (PID=2408). (Exit code -1073741819)

tried compatibility mod win7 didnt work, tried compiling with opengl.1 (i did google research before posting this).

removed : -Wl,--subsystem,windows

and then returned it (as this didnt help).

**Comment by raysan5** [comment]
Try using latest raylib from github master branch.
