### ISSUE TITLE
[core] Allow configurable frustrum far clip distance

### ISSUE THREAD

**Issue by seanrekrap** [raysan5/raylib#1051]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

User would like to be able to set arbitrary frustrum far plane distance. Currently hard-coded to 1000.0 in rlgl.h and core.c.

### Environment

Linux Ubuntu

### Code Example

Changes I made to allow me to do this:
1) rlgl.h
  a) ~line 65: 
                  #define DEFAULT_FAR_CULL_DISTANCE       (1.0e3)
  b) Line 857:
                  static double frustrumFarDistance = DEFAULT_FAR_CULL_DISTANCE;
  c) line 1044:
                 // Set clipping distance for frustrum far pane
                 void rlSetFrustrumFarClip(double dist) 
                 {
                       frustrumFarDistance = dist;
                 }
  d) Many places, such as line 3284, 3362, calls to MatrixPerspective(), 
                replace "1000.0" with "frustrumFarDistance"

2) core.c
    a) Many places such as line 1456, calls to MatrixPerspective() and MatrixOrtho(), rlFrustum(), rlOrtho():
                replace "1000.0" with "frustrumFarDistance"

3) In my user code, since I'm modeling the star field:
                rlSetFrustrumFarClip(1.0e20);

**Comment by chriscamacho** [comment]
while having the farclip plane >1000 or user definable would be nice, you should be careful using such large numbers as you have done (1.0e20) for example the depth buffer is only so many bits wide and large distances will make it inaccurate, it can also have impact on rendering too depending on the GL implementation. You'd be better setting to say 10,000 or 100,000 and scaling your objects...

**Comment by seanrekrap** [comment]
chriscamacho - can you point me to some other reference on web that may discuss this issue - I'd love to learn more - I'm a gl novice. Thanks.

**Comment by chriscamacho** [comment]
http://dev.theomader.com/depth-precision/ should illustrate the issue....
I happened to stumble on this issue years ago when making my own 3d space shooter type game, strange things were happening like spherical shapes having ragged edges....
basically make experiments and try as hard as you can to break things!

**Comment by seanrekrap** [comment]
chriscamacho - awesome - thanks!
At the distances I'm taking about I'm simply adding individual triangles to represent stars - so that they'd appear simply as "points of light" when GL draws them with perspective. I've successfully loaded the Hipparcos star catalog (118K stars) putting them at a distance of 1e16, and everything seems to work just fine. I'm certainly not expecting to see any particular shape for the stars, just a few pixels for each, as they would be in the FOV. Here's a screen shot...
![stars](https://user-images.githubusercontent.com/46874924/71562099-ac9be380-2a4c-11ea-8410-8cce8888d6f9.png)

**Comment by seanrekrap** [comment]
Would someone like me take a stab? Need perms to commit...

**Comment by raysan5** [comment]
I prefered to allow this option at compile time only.
