### ISSUE TITLE
[core] Camera offset movement not proportional

### ISSUE THREAD

**Issue by nathanielhudson** [raysan5/raylib#1054]
Please, before submitting a new issue verify and check:

 - [check] I tested it on latest raylib version from master branch
 - [check] I checked there is no similar issue already reported
 - [check] My code has no errors or misuse of raylib

### Issue description

I get different, but still wrong, behaviour depending on whether I build from source or use the 2.5 release.

**Raylib 2.5:**
Camera.target appears to have no effect whatsoever. Zoom and rotation work. Offset appears to only have half the effect it should (I believe - I switched to building from master, and haven't gone back to double-check this). Taking code verbatim from the example at https://www.raylib.com/examples/web/core/loader.html?name=core_2d_camera and compiling on my machine the square can be moved off the left or right sides of the screen, and the camera does not follow at all.

**Latest raylib built from master:**
Camera.target appears to have **half** the effect it is supposed to. Zoom and rotation do work. Offset works, but also appears to have only half the effect it should. Taking code verbatim from the example at https://www.raylib.com/examples/web/core/loader.html?name=core_2d_camera and compiling on my machine the square can be moved off the left or right sides of the screen, with the camera following at a slowed rate. If the code is modified to double the camera.target.x and camera.target.y values the square stays in a fixed position onscreen, but is no longer centred. If offset.x and offset.y are doubled as well, the square is now centered.

### Environment

MacBook Pro (Retina, 15-inch, Mid 2014)
OS X Catalina 10.15.2 (19C57)
Intel Iris Pro 1536 MB graphics
According to https://support.apple.com/en-us/HT202823 this machine uses OpenGL 4.1 - I don't know if there's a better way to verify that for sure.

### Issue Screenshot

<img width="848" alt="Screen Shot 2019-12-28 at 10 03 01 PM" src="https://user-images.githubusercontent.com/2744848/71551848-87609400-29be-11ea-9507-c77fb92811fc.png">

Note that the square has moved off the centre of the screen and the camera has not followed.

### Code Example

Code is verbatim from https://www.raylib.com/examples/web/core/loader.html?name=core_2d_camera

Modified example code that doubles offset and target values to stay centered is at https://gist.github.com/nathanielhudson/3813624c02b1e3b736ef685ba5ba76f4

**Comment by raysan5** [comment]
yes, that's probably related to HighDPI (https://github.com/raysan5/raylib/issues/837).

You can try recompiling raylib uncommenting [this line in config.h]( https://github.com/raysan5/raylib/blob/master/src/config.h#L58). Let me know if it solves the issue (it could add other issues).

**Comment by nathanielhudson** [comment]
`#define SUPPORT_HIGH_DPI` has no effect I'm afraid.

**Comment by nathanielhudson** [comment]
enabling `#define SUPPORT_HIGH_DPI` has no effect I'm afraid. Behaviour appears to be the same as what I saw building from master before.

**Comment by raysan5** [comment]
`funding needed`: I don't have a macOS device to work on this issue, if someone could provide one it would be great.
