### ISSUE TITLE
[models] Support BeginShaderMode() for 3d objects

### ISSUE THREAD

**Issue by redstonedash** [raysan5/raylib#1055]
Currently, if you have some shader, typically shaders that do something technical like drawing normals to a texture, calculating lighting in screen space, you need to use a shader other than what is assigned to the material of that object. in order to do this you need to store the current shader into a temporary value, set the new shader for every 3d object you want to draw this why, then revert them after you draw. this becomes even more difficult (and slow) if your models have multiple materials, in this cases you must backup every shader into an array, then assign the shader to each model, and then go through the array again to reassign it.; or make a second model. To solve this we need some sort of override that can be set, similar to beginShaderMode(), it could be combined into the same function, or we could make a beginShaderMode3d() or a beginShaderModeOverride(), it would overide all shaders being used on 3d draw calls.

how it is now (C++)

```cpp
BeginTextureMode(renderTextures[i]);
        DrawText("Top", 100, 100, 12, LIME);
        ClearBackground(randomColor);
        BeginMode3D({ {topWindowOffset.x,1,topWindowOffset.y}, {topWindowOffset.x,0,topWindowOffset.y}, {0,0,1}, topWindowZoom, CAMERA_ORTHOGRAPHIC });
            DrawGrid(10, 1);
                for (std::vector<Model>::iterator j = models.begin(); j != models.end(); j++) {
                    Shader temp = (*j).materials[0].shader;
                    (*j).materials[0].shader = orthoGraphic;
                    DrawModelWires(*j, { 0,0,0 }, 1, SKYBLUE);
                    (*j).materials[0].shader = temp;
                }
            EndMode3D();
    EndTextureMode();
``` 

how it should be 

```cpp
BeginTextureMode(renderTextures[i]);
        DrawText("Top", 100, 100, 12, LIME);
        ClearBackground(randomColor);
        BeginMode3D({ {topWindowOffset.x,1,topWindowOffset.y}, {topWindowOffset.x,0,topWindowOffset.y}, {0,0,1}, topWindowZoom, CAMERA_ORTHOGRAPHIC });
            DrawGrid(10, 1);
            beginShaderMode3D(orthoGraphic);
                for (std::vector<Model>::iterator j = models.begin(); j != models.end(); j++) {
                    DrawModelWires(*j, { 0,0,0 }, 1, SKYBLUE);
                }
            endShaderMode3d();
            EndMode3D();
    EndTextureMode();
```

now this is a simple case, but this currently does not support multiple materials, i can not think of an efficient way to do the same thing with multiple materials.

**Comment by raysan5** [comment]
This issue is tricky, I decided to keep it as design for the moment. Current approximation, despite not being the best one, works as expected.
