### ISSUE TITLE
GTk3 + RayLib

### ISSUE THREAD

**Issue by hbiblia** [raysan5/raylib#1061]
Hi

I am doing a 2.5D engine using Gtk3 and raylib to render.

To integrate raylib, create gtk-raylib.c and gtk-raylib.h, clone core.c now called raylib-core.c, remove GLFW3 and everything related to non-Desktop platforms, since it is not necessary within GTK3.

GLAD inside rlgl.h place a conditional macro for when I am using epoxy.h which is what I am using in GTk3 and is the one "recommended" for GtkGLArea.

gtk-raylib.c handles the render as GLFW3 does and allows you to use "gtk_raylib_embed_new" which in turn uses gtk_gl_area ...

![Captura de pantalla (23)](https://user-images.githubusercontent.com/1939353/72175733-3899fd80-33b3-11ea-88a9-a54a1a89a523.png)

I still don't have support for any kind of input, but I hope to complete it and make the web examples work.

When this is complete I will share gtk-raylib-2.5

**Comment by raysan5** [comment]
@hbiblia Very nice work! Congrats! :D 

Just let me know when the repo is ready to add a link to it!

**Comment by raysan5** [comment]
I'm closing this issue for now. Hope to hear more about this project! :D

**Comment by hbiblia** [comment]
Algunos ejemplos ya están funcionando.  Ahora estoy utilizando RL3.0.

![Captura de pantalla (174)](https://user-images.githubusercontent.com/1939353/77979827-b9da9f80-72d3-11ea-97f6-317012a32760.png)

**Comment by chriscamacho** [comment]
I like it!

**Comment by raysan5** [comment]
@hbiblia very nice! :D

**Comment by hbiblia** [comment]
Pueden probar: https://github.com/hbiblia/gtk-raylib

No soy nada bueno en Makefile, para compilar utilice un script .sh. :(
