### ISSUE TITLE
I think I've fixed x64 static linking

### ISSUE THREAD

**Issue by spec-chum** [raysan5/raylib#1062]
All I've done, essentially, is put `raylib.lib` before everything else in the linker input options and pointed VS to it.

Technically, the `/FS` flag isn't needed but if you build the whole solution both examples output to same dir which causes a lock on the pdb file; `/FS` allows it not to be locked.

The `.sln` file is from VS2019, so for VS2017 you might need to change the version manually.  It was `15.0.27130.2024` and is now `16.0.29609.76`

To do this, change:
`# Visual Studio Version 16`
`VisualStudioVersion = 16.0.29609.76`

to:
`# Visual Studio Version 15`
`VisualStudioVersion = 15.0.27130.2024`

In `raylib.sln`

[rl.zip](https://github.com/raysan5/raylib/files/4048381/rl.zip)

**Comment by raysan5** [comment]
@spec-chum Thanks for the fix! Reviewed in commit https://github.com/raysan5/raylib/commit/a748c3bf2535dccee5e75d383646d44d070b483d.
