### ISSUE TITLE
I'm trying to build raylib simple demo using Archlinux I got this message

### ISSUE THREAD

**Issue by gerardogc2378** [raysan5/raylib#1064]
make PLATFORM=PLATFORM_ANDROID
make -f Makefile.Android 
make[1]: Entering directory '/home/gerardo/repos/raylib/templates/simple_game'
Makefile.Android:144: *** missing separator.  Stop.
make[1]: Leaving directory '/home/gerardo/repos/raylib/templates/simple_game'
make: *** [Makefile:360: all] Error 2

**Comment by AregevDev** [comment]
https://stackoverflow.com/questions/16931770/makefile4-missing-separator-stop
This might help you?
Is this your own makefile?

**Comment by gerardogc2378** [comment]
It happens on this directory /home/gerardo/repos/raylib/templates/simple_game

simple_game $ tree
.
├── Makefile
├── Makefile.Android
├── Makefile.Android.linux
└── simple_game.c

It's not my own makefile

OUTPUT:

simple_game $ make PLATFORM=PLATFORM_ANDROID
make -f Makefile.Android 
make[1]: Entering directory '/home/gerardo/repos/raylib/templates/simple_game'
if not exist android.simple_game mkdir android.simple_game
/bin/sh: -c: line 1: syntax error: unexpected end of file
make[1]: *** [Makefile.Android:144: create_temp_project_dirs] Error 1
make[1]: Leaving directory '/home/gerardo/repos/raylib/templates/simple_game'
make: *** [Makefile:361: all] Error 2

Makefile.Android content line 144:
create_temp_project_dirs:
  if not exist $(PROJECT_BUILD_PATH) mkdir $(PROJECT_BUILD_PATH)
  if not exist $(PROJECT_BUILD_PATH)\obj mkdir $(PROJECT_BUILD_PATH)\obj
  if not exist $(PROJECT_BUILD_PATH)\src mkdir $(PROJECT_BUILD_PATH)\src
  if not exist $(PROJECT_BUILD_PATH)\src\com mkdir $(PROJECT_BUILD_PATH)\src\com
  if not exist $(PROJECT_BUILD_PATH)\src\com\$(APP_COMPANY_NAME) mkdir $(PROJECT_BUILD_PATH)\src\com\$(APP_COMPANY_NAME)
  if not exist $(PROJECT_BUILD_PATH)\src\com\$(APP_COMPANY_NAME)\$(APP_PRODUCT_NAME) mkdir $(PROJECT_BUILD_PATH)\src\com\$(APP_COMPANY_NAME)\$(APP_PRODUCT_NAME)
  if not exist $(PROJECT_BUILD_PATH)\lib mkdir $(PROJECT_BUILD_PATH)\lib
  if not exist $(PROJECT_BUILD_PATH)\lib\$(ANDROID_ARCH_NAME) mkdir $(PROJECT_BUILD_PATH)\lib\$(ANDROID_ARCH_NAME)
  if not exist $(PROJECT_BUILD_PATH)\bin mkdir $(PROJECT_BUILD_PATH)\bin
  if not exist $(PROJECT_BUILD_PATH)\res mkdir $(PROJECT_BUILD_PATH)\res
  if not exist $(PROJECT_BUILD_PATH)\res\drawable-ldpi mkdir $(PROJECT_BUILD_PATH)\res\drawable-ldpi
  if not exist $(PROJECT_BUILD_PATH)\res\drawable-mdpi mkdir $(PROJECT_BUILD_PATH)\res\drawable-mdpi
  if not exist $(PROJECT_BUILD_PATH)\res\drawable-hdpi mkdir $(PROJECT_BUILD_PATH)\res\drawable-hdpi
  if not exist $(PROJECT_BUILD_PATH)\res\values mkdir $(PROJECT_BUILD_PATH)\res\values
  if not exist $(PROJECT_BUILD_PATH)\assets mkdir $(PROJECT_BUILD_PATH)\assets
  if not exist $(PROJECT_BUILD_PATH)\assets\$(PROJECT_RESOURCES_PATH) mkdir $(PROJECT_BUILD_PATH)\assets\$(PROJECT_RESOURCES_PATH)
  if not exist $(PROJECT_BUILD_PATH)\obj\screens mkdir $(PROJECT_BUILD_PATH)\obj\screens
  $(foreach dir, $(PROJECT_SOURCE_DIRS), $(call create_dir, $(dir)))


What is wrong here

**Comment by gerardogc2378** [comment]
![issue_line_144](https://user-images.githubusercontent.com/24534/72211316-dd3d3d80-348e-11ea-9c25-c15ca18b74ba.png)

**Comment by gerardogc2378** [comment]
Here the files

[files.zip](https://github.com/raysan5/raylib/files/4049995/files.zip)

**Comment by raysan5** [comment]
Hi @gerardogc2378! Unfortunately at this moment Android Makefile only works on Windows host, some of the command-line functions called are Windows-only. 

Supporting Linux requires rewriting some parts of that Makefile.

**Comment by gerardogc2378** [comment]
Hey @raysan5 I am trying to understand this output:

/home/gerardo/android_home/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android29-clang -o android.simple_game/lib/arm64-v8a/libmain.so  android.simple_game/obj/simple_game.o -shared -I. -I/home/gerardo/repos/raylib/src -I/home/gerardo/repos/raylib/src/external/android/native_app_glue -Wl,-soname,libmain.so -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -u ANativeActivity_onCreate -L. -Landroid.simple_game/obj -Landroid.simple_game/lib/arm64-v8a -L/home/gerardo/android_home/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//sysroot/usr/lib/aarch64-linux-android -lm -lc -lraylib -llog -landroid -lEGL -lGLESv2 -lOpenSLES -ldl
/home/gerardo/android_home/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible android.simple_game/lib/arm64-v8a/libraylib.so when searching for -lraylib
/home/gerardo/android_home/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: android.simple_game/lib/arm64-v8a/libraylib.a(core.c.o): unable to initialize decompress status for section .debug_info
/home/gerardo/android_home/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: android.simple_game/lib/arm64-v8a/libraylib.a(core.c.o): unable to initialize decompress status for section .debug_info
android.simple_game/lib/arm64-v8a/libraylib.a: error adding symbols: File format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile.Android:347: compile_project_code] Error 1
make[1]: Leaving directory '/home/gerardo/repos/raylib/templates/simple_game'
make: *** [Makefile:360: all] Error 2


The issue is with this line:

/home/gerardo/android_home/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android29-clang -o android.simple_game/lib/arm64-v8a/libmain.so  android.simple_game/obj/simple_game.o -shared -I. -I/home/gerardo/repos/raylib/src -I/home/gerardo/repos/raylib/src/external/android/native_app_glue -Wl,-soname,libmain.so -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -u ANativeActivity_onCreate -L. -Landroid.simple_game/obj -Landroid.simple_game/lib/arm64-v8a -L/home/gerardo/android_home/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//sysroot/usr/lib/aarch64-linux-android -lm -lc -lraylib -llog -landroid -lEGL -lGLESv2 -lOpenSLES -ldl

**Comment by gerardogc2378** [comment]
@raysan5 I am using:

Path                 | Version      | Description                | Location             
  -------              | -------      | -------                    | -------              
  build-tools;29.0.0   | 29.0.0       | Android SDK Build-Tools 29 | build-tools/29.0.0/  
  ndk-bundle           | 20.1.5948944 | NDK                        | ndk-bundle/          
  patcher;v4           | 1            | SDK Patch Applier v4       | patcher/v4/          
  platform-tools       | 29.0.5       | Android SDK Platform-Tools | platform-tools/      
  platforms;android-29 | 4            | Android SDK Platform 29    | platforms/android-29/
  tools                | 26.1.1       | Android SDK Tools 26.1.1   | tools/

**Comment by raysan5** [comment]
> android.simple_game/lib/arm64-v8a/libraylib.a: error adding symbols: File format not recognized

It seems you are trying to link with a wrong version of `libraylib.a`, maybe it's not x64.

**Comment by jubalh** [comment]
So happy that Arch users always mention that they use arch in the issue title ;p

**Comment by ha11owed** [comment]
@raysan5 Is there any plan to switch to CMake or extend the Makefile to work on Linux?

**Comment by chriscamacho** [comment]
@ha11owed I use Linux almost exclusively, the Makefile supplied works really well ! 

no need to automagically create Makefiles 1,000's of lines (what could possibly go wrong....), but the CmakeList.txt file is already there, if you must!

most of my projects on bedroomcoders.co.uk use a boiler plate Makefile to compile the project, you just have to modify the Makefile to point at your pre-compiled raylib.... (it automatically detects sources in the src folder and compiles them into your application...)

**Comment by ha11owed** [comment]
@chriscamacho I agree that compiling raylib to android works well. Only the 3 projects from the templates folder have issues compiling on android from Linux due to the use of windows only commands or command parameters (copy \Y, xcopy, if not exist, del /f /s /q, rmdir /s /q)

But I guess you are right, its easier to create an Android project in Android Studio and create a makefile from scratch.
