### ISSUE TITLE
Review logging system

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1065]
Current logging system needs several improvements.

 - [x] `TraceLog()` messages should be properly categorized and unified, they need to be standardized in some way:
```
> DEVICE INIT/CLOSE + INFO ---> Window, Graphics, Audio, Network
> DATA LOADING CPU/GPU -------> Image, Texture, Font, Mesh, Shader, Sound, Music
> Internal Processes ---------> Shader compilation, VBO overflow...
```
 - [x] Current system is designed in a way that messages are ALWAYS stored inside the binary. It would be interesting to review this design... probably using macros.

**Comment by raysan5** [comment]
To address second point, I've been analyzing all modules issuing `printf()`/`puts()` calls and consequently storing its message data in the binary. I'd like to avoid unneeded information on release builds.

| module           | type     | comment on calls                                     | state |
|------------------|----------|------------------------------------------------------|-------|
| par_shapes.h     | external | par_shapes_export()                                  | ✔️    |
| par_shapes.h     | external | 2 debug calls + 1 printf() call + 1 puts()           | ❗️    |
| tinyobj_loader.c | external | 2 printf() for error messages (stderr)               | ❗️    |
| miniaudio.h      | external | multiple printf() calls on `#define MA_DEBUG_OUTPUT` | ✔️    |
| utils.c          | src      | TraceLog() implementation                            | ✔️    |
| rlgl.h           | src      | TraceLog() implementation (standalone)               | ✔️    |
| textures.c       | src      | ExportImageAsCode()                                  | ✔️    |
| models.c         | src      | ExportMesh() [OBJ export]                            | ✔️    |
| raudio.c         | src      | ExportWaveAsCode()                                   | ✔️    |
| raudio.c         | src      | TraceLog() implementation (standalone)               | ✔️    |
| physac.h         | src      | multiple printf() calls                              | ❗️    |
| rnet.c           | src      | multiple printf() calls                              | ❗️    |

Proposed solution implies replacing all `TraceLog()` calls by a macro: `TRACELOG`: 
```c
#if defined(SUPPORT_TRACELOG_OUTPUT)
    #define TRACELOG(level, ...) TraceLog(level, __VA_ARGS__)
#else
    #define TRACELOG(level, ...) {}
#endif
```

**Comment by a3f** [comment]
> Proposed solution implies replacing all TraceLog() calls by a macro: TRACELOG:
> ```
>#if defined(SUPPORT_TRACELOG_OUTPUT)
>    #define TRACELOG(level, ...) TraceLog(level, __VA_ARGS__)
> #else
>    #define TRACELOG(level, ...) {}
> #endif
>```

Two Suggestions:

- The `#else` clause should be `void(0)`, otherwise you run into problems with statements:
`if (cond) TRACELOG("WARN: foo bar baz\n"); else do_something();` becomes `if (cond) {} ; else { }`, which is a compile error

- Being able to set a log level at runtime and compiletime, is often useful. Former for debugging, latter for reducing application size. e.g.

```
#if TRACE_LOG_LEVEL >= TRACE_DEBUG
#define TraceLogDebug(...) TraceLog(TRACE_DEBUG, __VA_ARGS__)
#else
#define TraceLogDebug(...) (void)0
#endif

static enum loglevel max_level;
void TraceLog(enum loglevel level)
{
    if (level > level_max)
       return;
}
```

**Comment by raysan5** [comment]
@a3f thank you very much for the review! I implemented both suggestions in https://github.com/raysan5/raylib/commit/1f53fc3b678d27e80ed42d59c24845e89ae55e6f.

**Comment by raysan5** [comment]
Replaced `TraceLog()` function call by `TRACELOG` macro on commit https://github.com/raysan5/raylib/commit/cde26c743c382abea56ea5cd9c88d36970a61eea.

**Comment by raysan5** [comment]
TraceLog messages have been reviewed in multiple commits: 
https://github.com/raysan5/raylib/commit/28da2522fe2055f23a48ba0c15f00e9c3684f94a, https://github.com/raysan5/raylib/commit/b9dd459d5a88dd7236db8cc937b0886d0696a599, https://github.com/raysan5/raylib/commit/bc2c6251f84aae256559e3af675bc7520b035e3f, https://github.com/raysan5/raylib/commit/0c6c4215082bce3447207c33252abc66e8134a3b, https://github.com/raysan5/raylib/commit/7e2b1b4ff0536a6b0fe76fcba90d2efc44f70be2, https://github.com/raysan5/raylib/commit/70ed975b995dafa029561731c1e35c7348cde4a2, https://github.com/raysan5/raylib/commit/c7e9951795db9efe67e0fe49a411c3e882c4338a.

Messages have been categorized in multiple ways:
```
by libs:       GLFW, GLAD, GL
by platform:   ANDROID, RPI, UWP, WEB
by system:     DISPLAY, INPUT, FILEIO, TIMER, SYSTEM, RLGL, AUDIO
by data type:  
               IMAGE, TEXTURE, FONT
               SHADER, FBO, VAO, VBO
               MODEL, MESH, MATERIAL
               WAVE, SOUND, STREAM
```

Probably these categories and the messages will be reviewed in the future but here we go!
