### ISSUE TITLE
[Question] Spritebatches

### ISSUE THREAD

**Issue by uSources** [raysan5/raylib#1066]
Hi, I just wanted to ask if when you use the DrawTexture() function , does use internally spritebatches?.

If so, is there any way to create spritebatches manually?

**Comment by raysan5** [comment]
@uSources yes, there is an automatic batching system, all DrawTexture() using same image and one after the other are batched. At the moment there is no way to create batches manually.

**Comment by uSources** [comment]
Thanks, nice lib too, i like it. Im using C# bindings. 

Compared with LOVE2D, I get around 3000 bunnies more than in raylib, with the same framerate, do Do you know why it can happen?

**Comment by raysan5** [comment]
@uSources I understand that you're talking about `raylib-cs`, there is some overhead due to the C# language and the bindings.
