### ISSUE TITLE
[rparticle] Proposal particle system for raylib

### ISSUE THREAD

**Issue by uSources** [raysan5/raylib#1068]
Even if nothing stops you to make our particle system, maybe is a good idea to have a module who bring you a simple but effective way to make particles and particle Emitters. Using GPU particles for better performance.

Libraries like Libgdx, Monogame or LOVE2D has very interestin particle system

https://github.com/libgdx/libgdx/wiki/2D-ParticleEffects

http://rbwhitaker.wikidot.com/2d-particle-engine-3

https://love2d.org/wiki/ParticleSystem

What do yo think?

**Comment by raysan5** [comment]
@uSources raylib also has one: https://github.com/dbriemann/libpartikel 😜

**Comment by uSources** [comment]
Yes, I saw yesterday, but its on Alpha stage and seen discontinued, the last commit is at 31 May 2019.
