### ISSUE TITLE
[core] Keyboard input: Some keys not working in Kubuntu

### ISSUE THREAD

**Issue by tpanj** [raysan5/raylib#1069]
When running some eamples (./textures_particles_blending;  ./core_2d_camera) I exeperienced that none of input keys did not work. I tried keys <kbd>Esc</kbd>,  <kbd>Left</kbd> and <kbd>Right</kbd>.

### Environment

Kubuntu 19.10
INFO: Initializing raylib 2.6-dev (tested also on test5 branch)
INFO: Display device initialized successfully
INFO: Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: OpenGL 3.3 Core profile supported
INFO: GPU: Vendor:   NVIDIA Corporation
INFO: GPU: Renderer: GeForce GTX 1050/PCIe/SSE2
INFO: GPU: Version:  3.3.0 NVIDIA 435.21
INFO: GPU: GLSL:     3.30 NVIDIA via Cg compiler

**Comment by raysan5** [comment]
@tpanj What kind of keyboard do you have? It should work ok on Linux...

**Comment by tpanj** [comment]
Wired keyboard works just fine if I checkout 2.5.0 on the same computer. 
I test on the same computer several times. There is something different in 2.6-dev and test5.
Inside vmware, same configuration works but I did not use same computer for vmware host.

**Comment by tpanj** [comment]
I did try on host computer in both cases and if I use master branch there was problem.

**The latest working source was:**
clone -b 2.5.0  --single-branch https://github.com/raysan5/raylib.git branch-2.5.0

Then I tried several things, including updating my UEFI BIOS. Those operations solved my issue.
So I am closing issue due problem was my local computer only.
