### ISSUE TITLE
[core] How to Get the resources in macOS Application bundle

### ISSUE THREAD

**Issue by Yunoinsky** [raysan5/raylib#1072]
There is some problem for macOS high DPI support so the scissors mode and camera mode will only work after doing an affine transformation to the coordinate. But I just find out that, if i manually pack the executable file in an mac application bundle with a simple plist, this problem will be solved (Don't know why, but it just works (:<)

 And then comes the real problem : I can't find reach the resources file packed in the app bundle (under the `MyApp.app/res/`) through a pure c method. The only way i know is to use swift or Objective-C , such as `CFBundleCopyResourceURL()`. But i really want to do this job in pure c.

Now i just put all my resources under `/Users/Shared/MyApp/`, it works well, but looks ugly. Are there any c api which can get the absolute path for resource directory under the .app directory? Could anybody familliar with macOS help me?

PS: I don't know which module tag to use so i just put it under [core], maybe [build] is better ?

**Comment by Yunoinsky** [comment]
I try to use ` _NSGetExecutablePath(path, &size)` to get the executable path, it works well, and now i can put my resources in the parent directory of app. But using `fopen` for the file inside the app still returns NULL.

**Comment by raysan5** [comment]
Hi @Yunoinsky! Thanks for the info, unfortunately I've never had a macOS and I don't have much idea how compilation-packing process works. I'm afraid I can not help... but let's see if some users of the community can help! :)

PS: Either [core] or [build] tags are good for this issue.
