### ISSUE TITLE
[Question] Has raylib Content Pipeline?

### ISSUE THREAD

**Issue by uSources** [raysan5/raylib#1073]
Hi everyone,

Just only for curious , has raylib any tool for packagin images, music, textures etc.. into a package.

Such as monogame or XNA with its content pipelines?

Thansk you all!

**Comment by raysan5** [comment]
@uSources not at this moment. I developed a resource-packaging program in the past but I decided to review the output format and it's not finished yet:  https://github.com/raysan5/rres

A part from that, raylib does not include a content manager like XNA, it's up to the user to create one... but probably it would be a good sample to include with raylib...

**Comment by uSources** [comment]
Yes @raysan5 , Would be great!

Thanks!
