### ISSUE TITLE
Support origin in DrawTextureEx()

### ISSUE THREAD

**Issue by uSources** [raysan5/raylib#1076]
Now a days, **DrawTextureEx(Texture2D texture, Vector2 position, float rotation, float scale, Color tint)** doesn't support custom origin, for example for rotation, you need to user DrawTexturePro() and generete Rectangles for make this functionality.

It would be great if u want to rotate a one sprite image can set custom origin.

Thanks!!

**Comment by raysan5** [comment]
@uSources Actually `DrawTexturePro()` is the version to use. You can just define the rectangles on the go with:

```c
DrawTexturePro(tex, (Rectangle){ 0, 0, tex.width, tex.height }, (Rectangle){ 0, 0, tex.width, tex.heigh }, ...
```

Alternatively you can create your own function in user code.

**Comment by uSources** [comment]
Yes im saying that for maybe future releases if u like it. With DrawTextureEx() u dont need to set up Rectangles, maybe for newbie user like me is a little bit confussing

**Comment by vinidotruan** [comment]
> angles, maybe for newbie user like me is a little bit confussing

I agree with @uSources cuz, DrawTexturePro, sometimes is maybe an overkill for just use the origin thing.
