### ISSUE TITLE
[Question] Support JPG fileformat using Makefile

### ISSUE THREAD

**Issue by uSources** [raysan5/raylib#1078]
Hi all, im trying to load a jpg file to my raylib proyect, i know by default isnt supported, using CMAKE you can change in CMAKEOPTIONS, but im using Makefile provided by @raysan5 , how i can add support for jpg file format using Makefile.

I tried to add -DSUPPORT_FILEFORMAT_JPG=ON on makeFile flags, but nothing happens.
Also i tried to add #define SUPPORT_FILEFORMAT_JPG 1 to my main.c proyect but doesnt work

**Comment by SolarLune** [comment]
You can build Raylib with support for JPG by changing the properties in `config.h` directly, right? Does that not work for your purposes?

**Comment by uSources** [comment]
Yeeees!!!! That works thanks !!!!
