### ISSUE TITLE
raylib integration with other libs

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1079]
There are multiple users asking for raylib integration with other engines/libraries/tools. Here it is a list of desirable examples, some are already available as external repos.

 - [x] raylib + sokol_app -> [rayfork](https://github.com/SasLuca/rayfork)
 - [ ] raylib + spritesheet/atlas
 - [x] raylib + Tiled -> [raylib_tiled_import_with_tmx](https://github.com/OnACoffeeBreak/raylib_tiled_import_with_tmx), [libtmx docs](https://libtmx.readthedocs.io/en/latest/renderer-from-scratch.html)
 - [x] raylib + Nuklear -> [raylib-nuklear](https://github.com/tcfunk/raylib-nuklear), [3d-gui-with-raylib](http://bedroomcoders.co.uk/implementing-a-3d-gui-with-raylib)
 - [x] raylib + imgui -> [raylib-cimgui](https://github.com/WEREMSOFT/c99-raylib-cimgui-template)
 - [x] raylib + Gtk3 -> [gtk-raylib](https://github.com/hbiblia/gtk-raylib)
 - [x] raylib + Spine -> [spine-raylib](https://github.com/WEREMSOFT/spine-raylib-runtimes)
 - [x] raylib + Unity -> [using-raylib-dll-in-unity](https://unitycoder.com/blog/2019/12/09/using-raylib-dll-in-unity/)
 - [x] raylib + Assimp -> [raylib-3D](https://github.com/Gamerfiend/raylib-3D)
 - [x] raylib + physics/maths -> [ProfJski Examples](https://github.com/ProfJski/RayLib-Examples)
 - [x] raylib + enet -> [NetDynamics](https://github.com/nxrighthere/NetDynamics)
 - [x] raylib + ECS -> [Using raylib with an ECS](https://github.com/chriscamacho/ecsRoids)
 - [x] raylib + Entitas Lite (ECS) -> [mmGame-Engine](https://github.com/bayganik/mmGame-Engine-Raylib-ECS)
 - [x] raylib + mpeg1 -> [textures_video_playing.c.txt](https://github.com/raysan5/raylib/files/4201940/textures_video_playing.c.txt)
 - [x] raylib + libmpeg2 -> [article + code](http://bedroomcoders.co.uk/using-libmpeg2-with-raylib/)
 - [x] raylib + pyTorch C++ -> [TorchRayLib](https://github.com/QuantScientist/TorchRayLib)
 - [x] raylib + ProceduralGen -> [ProcGen](https://github.com/Pakz001/Raylib-Examples/tree/master/ProcGen)
 - [x] raygui + tigr -> [raygui-tigr](https://github.com/edomin/Raygui_Helloworld)

Please, feel free to reply this issue with other interesting integrations to be listed here!

**Comment by JulienPlanchetCoineo** [comment]
Where is the raylib + mpeg1 repository ?
Thanks

**Comment by chriscamacho** [comment]
@raysan5 would this be suitable as an example https://github.com/soulfoam/ecs
I could fairly quickly raylib-ify the given example...

**Comment by raysan5** [comment]
@chriscamacho A raylib ECS applied example would be nice, maybe with an asteroids game?

**Comment by raysan5** [comment]
@JulienPlanchetCoineo No repo for raylib + mpeg example but I uploaded the example here: https://github.com/phoboslab/pl_mpeg/issues/7

**Comment by chriscamacho** [comment]
http://bedroomcoders.co.uk/using-raylib-with-an-ecs/

**Comment by chriscamacho** [comment]
http://bedroomcoders.co.uk/sprite-sheets-with-raylib/

**Comment by raysan5** [comment]
I foun this, not sure if it works: https://github.com/oswjk/raylib-imgui-template

**Comment by oswjk** [comment]
> 
> 
> I found this, not sure if it works: https://github.com/oswjk/raylib-imgui-template

It should work, I've done some simple UI's with it. It might not be optimal, but it's a nice example at least and should give pointers on how to integrate the two projects.

**Comment by Gamerfiend** [comment]
@raysan5 could you add my library for raylib + assimp? https://github.com/Gamerfiend/raylib-3D

**Comment by raysan5** [comment]
@Gamerfiend Sure! Added! :)

**Comment by hbiblia** [comment]
Pueden agregar Gtk3-raylib? https://github.com/hbiblia/gtk-raylib

**Comment by raysan5** [comment]
Moved this information to [Wiki](https://github.com/raysan5/raylib/wiki/raylib-integration-with-other-libraries).
