### ISSUE TITLE
[build] Getting Error "The syntax of command is incorrect" when building Android APK

### ISSUE THREAD

**Issue by titus-shoats** [raysan5/raylib#1080]
Whenever I build for android to get a APK I get a error like below, can anyone assist me in this? 
Thanks

`  
C:\Users\..\Downloads\raylib-master\raylib-master\templates\simple_game>mingw3
2-make PLATFORM=PLATFORM_ANDROID

mingw32-make -f Makefile.Android
mingw32-make[1]: Entering directory 'C:/Users/cmax/Downloads/raylib-master/rayli
b-master/templates/simple_game'
if not exist android.simple_game mkdir android.simple_game
if not exist android.simple_game\obj mkdir android.simple_game\obj
if not exist android.simple_game\src mkdir android.simple_game\src
if not exist android.simple_game\src\com mkdir android.simple_game\src\com
if not exist android.simple_game\src\com\raylib mkdir android.simple_game\src\co
m\raylib
if not exist android.simple_game\src\com\raylib\rgame mkdir android.simple_game\
src\com\raylib\rgame
if not exist android.simple_game\lib mkdir android.simple_game\lib
if not exist android.simple_game\lib\armeabi-v7a mkdir android.simple_game\lib\a
rmeabi-v7a
if not exist android.simple_game\bin mkdir android.simple_game\bin
if not exist android.simple_game\res mkdir android.simple_game\res
if not exist android.simple_game\res\drawable-ldpi mkdir android.simple_game\res
\drawable-ldpi
if not exist android.simple_game\res\drawable-mdpi mkdir android.simple_game\res
\drawable-mdpi
if not exist android.simple_game\res\drawable-hdpi mkdir android.simple_game\res
\drawable-hdpi
if not exist android.simple_game\res\values mkdir android.simple_game\res\values
if not exist android.simple_game\assets mkdir android.simple_game\assets
if not exist android.simple_game\assets\resources mkdir android.simple_game\asse
ts\resources
if not exist android.simple_game\obj\screens mkdir android.simple_game\obj\scree
ns if not exist android.simple_game\obj\ ./ mkdir android.simple_game\obj\ ./
copy /Y C:/raylib/raylib\src\libraylib.a android.simple_game\lib\armeabi-v7a\lib
raylib.a
The syntax of the command is incorrect.
Makefile.Android:174: recipe for target 'copy_project_required_libs' failed
mingw32-make[1]: *** [copy_project_required_libs] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/cmax/Downloads/raylib-master/raylib
-master/templates/simple_game'
Makefile:365: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

`

**Comment by raysan5** [comment]
@titus-shoats Are you on Windows? What version? Are you building from MSYS? Are you using MinGW from raylib installation?

**Comment by titus-shoats** [comment]
Hey, yes im on windows,  i'm not sure which version but I recently downloaded the github repo a few days ago. Yes im using MinGW from raylib installation

**Comment by titus-shoats** [comment]
@raysan5 is this a command syntax  or Issue that can be fixed or modified within the library?

**Comment by raysan5** [comment]
@titus-shoats problem is that below command is not correct:
```
copy /Y C:/raylib/raylib\src\libraylib.a android.simple_game\lib\armeabi-v7a\libraylib.a
The syntax of the command is incorrect.
```
`$(PROJECT_BUILD_PATH)` is set to `android.simple_game`. It should work.

Try removing the `/Y` parameter from copy, maybe on your Window version it does not work...

**Comment by raysan5** [comment]
@titus-shoats I got an idea. Is there any space character on your full path? It could be related. Try placing `raylib-master` directly in `C:/`.

**Comment by raysan5** [comment]
This specific problem seems not directly raylib related, I'll close the issue but feel free to comment or open another issue if required.
