### ISSUE TITLE
Vector2Multiply MIA

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1081]
You have Vector3Multiply and MultiplyV versions but for Vector2 only MultiplyV ....

**Comment by raysan5** [comment]
@chriscamacho Oh! I seems that's a naming inconsistency, we have `Vector2Scale()`, maybe it should be renamed to `Vector2Multiply()`? Or maybe rename `Vector3Scale()`?

**Comment by chriscamacho** [comment]
good point, lol I've actually used vector2Scale elsewhere...

maybe scale should be for float and multiply for vector that way MultiplyV can be dumped ?

**Comment by raysan5** [comment]
@chriscamacho yeah, agree... I'm breaking the API... again...

**Comment by chriscamacho** [comment]
I was joking about API breakage! its a good thing really, better to break things on a major version change, and have a better API than live with something that doesn't quite make sense because that's how we started out.....

**Comment by raysan5** [comment]
Reviewed on commits https://github.com/raysan5/raylib/commit/d10ff78822f8a726c6c8e45f43bfd90a9d1cd8bf and https://github.com/raysan5/raylib/commit/fa0d5bbf9e6b37f5436a4f540571ad3347d531ae
