### ISSUE TITLE
loading sound from memory

### ISSUE THREAD

**Issue by codz01** [raysan5/raylib#1082]
Hi
how to load wav sound from memory ?
thanks

**Comment by raysan5** [comment]
Fill a `Wave` struct with data and use `LoadSoundFromWave();`.

There is a related example: `examples/audio/audio_raw_stream.c`

**Comment by codz01** [comment]
i expect it much simpler than that 
so i have to read the wave file manually in memory and extract its data , freq, length ... and then pass it to raylib . why not just LoadSoundFromMemory(void* ptr, int length)  just like other library did !

**Comment by raysan5** [comment]
@codz01 It's designed this way, in any case it's just 3-4 lines of code.
