### ISSUE TITLE
[build] Makefile clean target fails in examples if nothing to clean

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1087]
find -type f -executable | xargs file -i | grep -E 'x-object|x-archive|x-sharedlib|x-executable|x-pie-executable' | rev | cut -d ':' -f 2- | rev | xargs rm -fv
    Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding]
                [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
                [-m <magicfiles>] [-P <parameter=value>] <file> ...
           file -C [-m <magicfiles>]
           file [--help]
    Cleaning done

**Comment by chriscamacho** [comment]
NB only happens when there is nothing to clean - issue ?

**Comment by raysan5** [comment]
@chriscamacho is there a simple tweak for this? could you send a PR?

**Comment by chriscamacho** [comment]
I'll have a look tonight if I get chance....

**Comment by chriscamacho** [comment]
have a look at the raspberry PI clean rule, seems to work just fine...

**Comment by raysan5** [comment]
Replaced clean target, actually it looks more comprehensive to me...
