### ISSUE TITLE
[models] GenMeshCylinder() caps not aligned

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1088]
to see it easily make a cylinder with 3 or 5 "slices"
You will notice the top isn't aligned with the sides...

(I was wanting a wedge shape!)

**Comment by raysan5** [comment]
@chriscamacho Good catch! Feel free to send a PR if you take a look to the function! :)

**Comment by chriscamacho** [comment]
after the first par_shapes_rotate, add an additional rotation

`    par_shapes_rotate(cylinder, PI/2.0f, (float[]){ 0, 1, 0});`
