### ISSUE TITLE
[examples] Issues with RPI4

### ISSUE THREAD

**Issue by o3o** [raysan5/raylib#1090]
First of all, thank you for your great work.

So, I've Raspberry Pi 4 Model B, with [Archlinux ARM](https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-4), and I would like to use raylib in native mode
So, my raylib version
```
$ cd ~/raylib
$ git  log
commit 9ce2331cc19082134441adb0610b9cce5a84e13f (HEAD -> master, origin/master, origin/HEAD)
Author: Ray <raysan5@gmail.com>
Date:   Thu Jan 30 13:47:39 2020 +0100
```

then:
```
$ cd ~/raylib/src
make PLATFORM=PLATFORM_RPI
...
raylib static library generated (libraylib.a) in ../src!

$ sudo make install PLATFORM=PLATFORM_RPI
...
cp --update --verbose ../src/libraylib.a /usr/local/lib/libraylib.a
'../src/libraylib.a' -> '/usr/local/lib/libraylib.a'
cp --update raylib.h /usr/local/include/raylib.h
cp --update raymath.h /usr/local/include/raymath.h
cp --update rlgl.h /usr/local/include/rlgl.h
cp --update physac.h /usr/local/include/physac.h
raylib development files installed/updated!
```

Finally
```
$ cd ~/raylib/examples
$ make core/core_basic_window PLATFORM=PLATFORM_RPI
$ ./core/core_basic_window 
INFO: before init
INFO: Initializing raylib 2.6-dev
```
no window appears!. Same if I use:
```
$sudo ./core/core_basic_window 
```

I followed [Redirect raylib output to Framebuffer 1](https://github.com/raysan5/raylib/wiki/Redirect-raylib-output-to-Framebuffer-1)

but I do not have, fb1
```
$ ls -l /dev/fb*           
crw-rw---- 1 root video 29, 0 Dec 17 12:44 /dev/fb0
```
can you give me some suggestions?

Thank you very much

**Comment by raysan5** [comment]
Hi @o3o! I was working on it some days ago. Here all the related info: https://github.com/raysan5/raylib/issues/1041

**Comment by o3o** [comment]
Thank you very much for your fast reply.

I tried again with arch, no way.
So, I will try with Raspbian Buster Lite, or Raspbian Buster Desktop.

Thank you again
(fun fact, I would like to visit Barcelona next month :)  )

**Comment by raysan5** [comment]
@o3o nice! Barcelona is a beautiful city! Just let me know if you want to have a coffee! :)

**Comment by o3o** [comment]
:) grazie
