### ISSUE TITLE
[build] android_main: error: undefined reference to 'main'

### ISSUE THREAD

**Issue by titus-shoats** [raysan5/raylib#1093]
Hello im in the process of compiling a simple game using the "Working for Android" tutorial on wiki. But for some reason im getting an issue when I run the command below. My error that im getting is also below.

Error:
/home/ace/project/lib/armeabi-v7a/libraylib.a(core.o):core.c:function android_main: error: undefined reference to 'main'
clang90: error: linker command failed with exit code 1 (use -v to see invocation)

Command:
/home/ace/Downloads/android-ndk/build/tools/android_toolchain_ARM_API22/bin/arm-linux-androideabi-gcc -o /home/ace/project/lib/armeabi-v7a/libproject.so /home/ace/project/obj/project.o -shared -I. -I /home/ace/raylib/release/include -I /home/ace/raylib/src/external/android/native_app_glue -Wl,-soname,libproject.so -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -u ANativeActivity_onCreate -L. -Lobj -L /home/ace/project/lib/armeabi-v7a -lraylib -lnative_app_glue -llog -landroid -lEGL -lGLESv2 -lOpenSLES -latomic -lc -lm -ldl

Any help or advice? Thanks

**Comment by raysan5** [comment]
@titus-shoats are you using provided Makefiles? To compile `libraylib.a` you should use `raylib/src/Makefile`; to compile raylib example/template you should use `raylib/examples/Makefile` and `raylib/templates/simple_game/Makefile` respectively. What is the output when using those Makefiles?

**Comment by titus-shoats** [comment]
@raysan5 Hey ray, sorry im creating a demo game, not the simple game in the templates folder. Im working through the tutorial "Working for Android on Linux" https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux), and im on the "Build Scripts" part of the tutorial. Im executing the below command below using my own paths..

# Requires: project.c
# Creates: obj/project.o

/home/ace/Downloads/android-ndk/build/tools/android_toolchain_ARM_API22/bin/arm-linux-androideabi-gcc -o /home/ace/project/lib/armeabi-v7a/libproject.so /home/ace/project/obj/project.o -shared -I. -I /home/ace/raylib/release/include -I /home/ace/raylib/src/external/android/native_app_glue -Wl,-soname,libproject.so -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -u ANativeActivity_onCreate -L. -Lobj -L /home/ace/project/lib/armeabi-v7a -lraylib -lnative_app_glue -llog -landroid -lEGL -lGLESv2 -lOpenSLES -latomic -lc -lm -ldl

**Comment by raysan5** [comment]
@titus-shoats oh, sorry, no idea, that page was created by an user, I work on Windows.

**Comment by titus-shoats** [comment]
no problem, theres another Android & Linux tutorial that i'll check out. Thanks!
