### ISSUE TITLE
No output from printf

### ISSUE THREAD

**Issue by HenningCode** [raysan5/raylib#1094]
Hello!

I am creating a simple game with raylib and for debug purposes I wanted to output what `GetKeyPressed()` was reading, because a switch statement I created with that didnt work at all.

This is my input function. 

```
void input(){

    int key = 0;

    key = GetKeyPressed();
    switch(key){
        case KEY_DOWN:
            printf("DOWN");
            break;
        case KEY_UP:
            printf("UP");
            break;
        case KEY_LEFT:
            printf("LEFT");
            break;
        case KEY_RIGHT:
            printf("RIGHT");
            break;
    }

}
```

And I am getting no output or anything at. I am running macOs and I am compiling with cmake. That all works fine. I am just double clicking the created executable but I am getting no outputs. Why is that? I even tried to place a `printf("%d",key);` aasigen the key but that doesn't work either. 

Any help would be appreciated.

**Comment by a3f** [comment]
`printf` can buffer output to reduce calls into the operating system. Try appending `\n` to your format strings. This will cause the line to be flushed if your stdout is line-buffered. Note that this isn't a raylib issue.

**Comment by chriscamacho** [comment]
@HenningCode take a look at raylib's TraceLog function
    TraceLog(LOG_INFO," Key code pressed %i ", key);
this doesn't buffer and doesn't need \n
