### ISSUE TITLE
[All] more cppcheck error hunt

### ISSUE THREAD

**Issue by jotac0** [raysan5/raylib#1098]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported ( there is, this is the 2nd )
 - [ ] My code has no errors or misuse of raylib (i don't have code :o! )

### Issue description
This time, is not many, and not too dangerous :+1:  :) 

i have run Cppcheck on raylib, this are the errors:

at src/core.c line 3999
Uninitialized struct member: gestureEvent.touchAction

at src/text.c line 1461
Common realloc mistake: 'text' nulled but not freed upon failure

Warnings:
at src/raudio.c lines 794 to 797
%i is for int (not unsigned int :P)

**Comment by raysan5** [comment]
Issues should be corrected.
