### ISSUE TITLE
[core] IsMouseButtonPressed() returns true even if the button is not pressed

### ISSUE THREAD

**Issue by codekrot** [raysan5/raylib#1100]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When **only** the left mouse button is pressed, the `IsMouseButtonPressed` function returns `true` for **both** `MOUSE_LEFT_BUTTON` and `MOUSE_RIGHT_BUTTON` for some reason, but after releasing it `IsMouseButtonReleased` returns `true` for `MOUSE_LEFT_BUTTON` and `false` for `MOUSE_RIGHT_BUTTON` as expected.

This issue exists for me on raylib 2.6 from releases page and on latest version from master branch, but version 2.5 from releases works correctly.

Is there something wrong with my code or is this a bug?

### Environment

uname -a
`Linux krot 5.4.18-1-MANJARO #1 SMP PREEMPT Thu Feb 6 11:41:30 UTC 2020 x86_64 GNU/Linux`

Also tested on Arch machine with raylib 2.6 installed from Arch repository and I get same output.

### Code Example

```
#include <raylib.h>
#include <stdio.h>

int main() {
    InitWindow(800, 450, "");
    SetTargetFPS(60);

    while (!WindowShouldClose()) {
        BeginDrawing();

        ClearBackground(WHITE);

        bool pressed_l = IsMouseButtonPressed(MOUSE_LEFT_BUTTON);
        bool pressed_r = IsMouseButtonPressed(MOUSE_RIGHT_BUTTON);
        bool released_l = IsMouseButtonReleased(MOUSE_LEFT_BUTTON);
        bool released_r = IsMouseButtonReleased(MOUSE_RIGHT_BUTTON);

        if (pressed_l || pressed_r || released_l || released_r) {
            printf("%d %d %d %d\n",
                    pressed_l,
                    pressed_r,
                    released_l,
                    released_r);
        }

        EndDrawing();
    }

    CloseWindow();

    return 0;
}
```

Output:
```
1 1 0 0        // LMB pressed
0 0 1 0        // LMB released
```

Expected output is:
```
1 0 0 0        // LMB pressed
0 0 1 0        // LMB released
```

**Comment by WonkySpecs** [comment]
I also had an issue similar to this. On the first frame after pressing the left mouse button, IsMouseDown returns true for the left button, and the expected values for the right and middle buttons. From the next frame onwards, until the left mouse button is released, IsMouseDown returns true for left, right, and middle mouse buttons, regardless of whether the right/middle buttons are pressed.

**Comment by raysan5** [comment]
@codekrot @WonkySpecs yes, I messed it up lately when trying to map touch inputs with mouse inputs... because touch inputs are already mapped to mouse inputs in another side of the code...

Reverted changes in commit https://github.com/raysan5/raylib/commit/946a6cb2809883f9b287ac889beb835deca0f571. Please, could you verify it works as expected now?

**Comment by codekrot** [comment]
Yep, everything works as expected for me. Thank you for fixing it.

**Comment by WonkySpecs** [comment]
Same here, thanks :+1:
