### ISSUE TITLE
Wrong version 

### ISSUE THREAD

**Issue by o3o** [raysan5/raylib#1102]
Your last tag is:
```
git describe --tags
2.6.0-53-g39e73ccc
```
but inside Makefile
```
RAYLIB_VERSION     = 2.5.0
RAYLIB_API_VERSION = 251
```

(this is a problem in order to bind your great library)

Thank you

**Comment by raysan5** [comment]
Reviewed for upcoming `raylib 3.0` in commit https://github.com/raysan5/raylib/commit/7d789763d6be00cda49a8da352e3d8c0326b9845
