### ISSUE TITLE
[examples] models_rlgl_solar_system crashes

### ISSUE THREAD

**Issue by Guevara-chan** [raysan5/raylib#1105]
While translating your samples for my own Nim [wrapper](https://github.com/Guevara-chan/Raylib-Forever), I found some _strange_ problems with `models_rlgl_solar_system.c`

Say, I compiled `rlgl.h` to DLL with `gcc -c -DBUILD_LIBTYPE_SHARED -DRLGL_STANDALONE -DRLGL_SUPPORT_TRACELOG -DRLGL_IMPLEMENTATION` and linked my code to it. I guess it's supported, right ?

Now, there are 3 problems with aforementioned sample:
1. It crashes on first `rlPushMatrix()` (invalid memory access)
2. If I add, say `rlMatrixMode(RL_PROJECTION)` before it, it crashes on `rlBegin(RL_TRIANGLES)`
3. If I add `rlglInit(screenWidth, screenHeight)` before everything, it crashes on calling it.

So. What could be done ? Is given sample up-to-date ? Probably I missed something ?

**Comment by raysan5** [comment]
@Guevara-chan I just tried it and it works ok on Windows desktop, but I just compiled the example, not created a dynamic library.

Note that raylib already includes all `rlgl` symbols so maybe there is some symbols conflicts id provided by `rlgl.dll` and `raylib.dll`... also note that your code should be compiled with `-DUSE_LIBTYPE_SHARED` when using `rlgl.dll`.

**Comment by Guevara-chan** [comment]
> Note that raylib already includes all rlgl symbols

Wait, it does ? All better then: I guess, I will just link existing headers to `libraylib` instead of compiling up custom ones.

**Comment by Guevara-chan** [comment]
OK: all works now as intended. Many thanks !
