### ISSUE TITLE
[build] Provide annoted tag version

### ISSUE THREAD

**Issue by o3o** [raysan5/raylib#1106]
I'm working on a [D binding](https://github.com/o3o/bindbc-raylib) of your great library.

In order to write my code I need an _annoted tag_ of version (for example) 2.6.0 or whatever you prefer.

Could you please (annoted) tagging  a release ? 
For example:
```
$ git  tag -a v2.6.1 36bf8a60d8e45f757
```

So, I can see exactly which commit I work on:
```
$ git log
...
commit 36bf8a60d8e45f757852d121c159c14a8f9b2fb4 (tag: v2.6.1)
Author: o3o <orfeo@fastmail.com>
Date:   Tue Feb 18 23:19:30 2020 +0100

    Fix #1103 (#1104)
    
    Fix 1102
```
or  with gitg:

![image](https://user-images.githubusercontent.com/155032/74875408-78fd7b80-5362-11ea-88c7-d0c0b816a792.png)

Thank you very much!

**Comment by raysan5** [comment]
@o3o I'm working on `raylib 3.0` release right now, I expect to have it ready soon. I'll tag it properly. In the meantime you can use `2.6.0` tag, in terms of API there are almost no changes.

**Comment by o3o** [comment]
Thank you... I'm waiting for  release 3.0.0!

**Comment by raysan5** [comment]
It will come with next release. Closing it, not really a library issue.
