### ISSUE TITLE
[build] libraylib not linked when compiling for Android on Linux host platform

### ISSUE THREAD

**Issue by hagna** [raysan5/raylib#1107]
(This is the fourth step for producing project.o from the wiki https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux))

demo@demo:~/project$ ../android_toolchain_ARM_API22/bin/arm-linux-androideabi-gcc -o lib/armeabi-v7a/libproject.so obj/project.o -shared -I. -I../raylib/release/include -I../raylib/src/external/android/native_app_glue -Wl,-soname,libproject.so -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -u ANativeActivity_onCreate -L. -Lobj -Llib/armeabi-v7a -lraylib -lnative_app_glue -llog -landroid -lEGL -lGLESv2 -lOpenSLES -latomic -lc -lm -ldl
obj/project.o:project.c:function main: error: undefined reference to 'GetRandomValue'
obj/project.o:project.c:function main: error: undefined reference to 'InitWindow'
obj/project.o:project.c:function main: error: undefined reference to 'SetTargetFPS'
obj/project.o:project.c:function main: error: undefined reference to 'WindowShouldClose'
obj/project.o:project.c:function main: error: undefined reference to 'IsKeyPressed'
obj/project.o:project.c:function main: error: undefined reference to 'TraceLog'
obj/project.o:project.c:function main: error: undefined reference to 'BeginDrawing'
obj/project.o:project.c:function main: error: undefined reference to 'TraceLog'
obj/project.o:project.c:function main: error: undefined reference to 'DrawRectangle'
obj/project.o:project.c:function main: error: undefined reference to 'DrawRectangle'
obj/project.o:project.c:function main: error: undefined reference to 'TextFormat'
obj/project.o:project.c:function main: error: undefined reference to 'DrawText'
obj/project.o:project.c:function main: error: undefined reference to 'DrawRectangle'
obj/project.o:project.c:function main: error: undefined reference to 'TextFormat'
obj/project.o:project.c:function main: error: undefined reference to 'DrawText'
obj/project.o:project.c:function main: error: undefined reference to 'EndDrawing'
obj/project.o:project.c:function main: error: undefined reference to 'TraceLog'
obj/project.o:project.c:function main: error: undefined reference to 'TraceLog'
obj/project.o:project.c:function main: error: undefined reference to 'CloseWindow'
./libraylib.a(android_native_app_glue.o):android_native_app_glue.c:function android_app_entry: error: undefined reference to 'android_main'
clang80: error: linker command failed with exit code 1 (use -v to see invocation)

demo@demo:~/project$ nm libraylib.a | grep TextFormat
                 U TextFormat
0000000000008f90 T TextFormat
                 U TextFormat

**Comment by raysan5** [comment]
@hagna actually I haven't tried compiling for Android on Linux, you probably need to add `libraylib.a` path to compile line: `-L<libraylib_path>`

**Comment by hagna** [comment]
The linker command includes -L. -Lobj -Llib/armeabi-v7a.  I put libraylib.a in all those places.

**Comment by hagna** [comment]
Ok the problem is mine. libraylib was probably not generated properly. I rebuilt raylib with make PLATFORM=PLATFORM_ANDROID just now and using that libraylib.a the linker succeeds.
