### ISSUE TITLE
[examples] shaders_pallete_switch crashes

### ISSUE THREAD

**Issue by Guevara-chan** [raysan5/raylib#1109]
While translating standard samples to Nim, I stumbled upon something strange when dealing with `LoadShader` (namely `LoadShader(nil, TextFormat("resources/shaders/glsl%i/palette_switch.fs", GLSL_VERSION))`):

> INFO: Initializing raylib 2.6-dev
> INFO: Display device initialized successfully
> INFO: Display size: 1280 x 1024
> INFO: Render size: 800 x 450
> INFO: Screen size: 800 x 450
> INFO: Viewport offsets: 0, 0
> INFO: GLAD: OpenGL extensions loaded successfully
> INFO: OpenGL 3.3 Core profile supported
> INFO: GPU: Vendor:   ATI Technologies Inc.
> INFO: GPU: Renderer: AMD Radeon R5 235
> INFO: GPU: Version:  3.3.13401 Core Profile Context 15.201.1301.0
> INFO: GPU: GLSL:     4.40
> INFO: Number of supported extensions: 265
> INFO: [EXTENSION] DXT compressed textures supported
> INFO: [EXTENSION] ETC2/EAC compressed textures supported
> INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
> INFO: [EXTENSION] Mirror clamp wrap texture mode supported
> INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
> INFO: [TEX ID 1] Base white texture loaded successfully
> INFO: [SHDR ID 1] Shader compiled successfully
> INFO: [SHDR ID 2] Shader compiled successfully
> INFO: [SHDR ID 3] Shader program loaded successfully
> INFO: [SHDR ID 3] Default shader loaded successfully
> INFO: Internal buffers initialized successfully (CPU)
> INFO: Internal buffers uploaded successfully (GPU)
> INFO: OpenGL default states initialized successfully
> INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
> INFO: [TEX ID 2] Default font loaded successfully
> WARNING: [] Text file could not be opened
> INFO: [SHDR ID 4] Shader compiled successfully
> INFO: [SHDR ID 5] Shader program loaded successfully
> Traceback (most recent call last)
> C:\Utils\[multilang]\Raylib Forever\examples\shaders\palette_switch.nim(87) palette_switch
> SIGSEGV: Illegal storage access. (Attempt to read from nil?)

What could it be ? Given shader are reported as successfully parsed, yet load operation always ends with sigsegv.

**Comment by raysan5** [comment]
It seems `TextFormat()` is not returning the expected formatted string:
```
WARNING: [] Text file could not be opened
```
between the brackets there should be:
```
[resources/shaders/glsl330/palette_switch.fs]
```

**Comment by raysan5** [comment]
@Guevara-chan try updating to latest raylib from github master branch.

**Comment by Guevara-chan** [comment]
Hm... If I will change this line to... say... LoadShader(nil, TextFormat("resources/shaders/glsl%i/palette_switch.fs_", GLSL_VERSION)), this will ensue:
`WARNING: [resources/shaders/glsl330/palette_switch.fs_] Text file could not be opened
WARNING: [] Text file could not be opened`

**Comment by Guevara-chan** [comment]
Wanna see some more strange stuff ? Here, let's use `LoadShaderCode(nil, ($TextFormat("resources/shaders/glsl%i/palette_switch.fs", GLSL_VERSION)).readFile)`. Now, my code fails with different message:
> INFO: [SHDR ID 4] Shader compiled successfully
> WARNING: [SHDR ID 5] Failed to compile shader...
> INFO: Fragment shader failed to compile with the following errors:
> ERROR: 0:1: error(#132) Syntax error: "<" parse error
> ERROR: error(#273) 1 compilation errors.  No code generated
> 
> 
> WARNING: [SHDR ID 6] Failed to link shader program...
> INFO: Fragment shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
> 
> WARNING: Custom shader could not be loaded
> Traceback (most recent call last)
> C:\Utils\[multilang]\Raylib Forever\examples\shaders\palette_switch.nim(87) palette_switch
> SIGSEGV: Illegal storage access. (Attempt to read from nil?)
>

**Comment by raysan5** [comment]
@Guevara-chan Could you try again with latest commit?

**Comment by Guevara-chan** [comment]
Just tried it without TextFormat:
> WARNING: [��] Text file could not be opened
> INFO: [SHDR ID 4] Shader compiled successfully
> INFO: [SHDR ID 5] Shader program loaded successfully
> Traceback (most recent call last)
> C:\Utils\[multilang]\Raylib Forever\examples\shaders\palette_switch.nim(87) palette_switch
> SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by raysan5** [comment]
@Guevara-chan Did you try all the other shader examples that use similar code? I'm afraid issue could be in the Nim binding...

**Comment by Guevara-chan** [comment]
That's strange, because all other string-related functions works like a charm. Textures/music/models - you name it.

I'm gonna try other samples later.

**Comment by raysan5** [comment]
@Guevara-chan I just reviewed `LoadShader()` and `LoadText()` on `rlgl` module and I can't see any issue with them...

**Comment by raysan5** [comment]
@Guevara-chan what platform are you in? I think it can be related to `LoadText()` function but it works in most platforms.

**Comment by Guevara-chan** [comment]
> @Guevara-chan what platform are you in? I think it can be related to `LoadText()` function but it works in most platforms.

Windows 10 x64.

**Comment by raysan5** [comment]
> I'm gonna try other shader samples later.

@Guevara-chan did you try with other shader samples?

**Comment by Guevara-chan** [comment]
Oh, right ! Tried raymarching example recently. Was almost my favorite so far:

> SIGSEGV: Illegal storage access. (Attempt to read from nil?)
> INFO: Initializing raylib 2.6-dev
> INFO: Display device initialized successfully
> INFO: Display size: 1280 x 1024
> INFO: Render size: 800 x 450
> INFO: Screen size: 800 x 450
> INFO: Viewport offsets: 0, 0
> INFO: GLAD: OpenGL extensions loaded successfully
> INFO: OpenGL 3.3 Core profile supported
> INFO: GPU: Vendor:   ATI Technologies Inc.
> INFO: GPU: Renderer: AMD Radeon R5 235
> INFO: GPU: Version:  3.3.13401 Core Profile Context 15.201.1301.0
> INFO: GPU: GLSL:     4.40
> INFO: Number of supported extensions: 265
> INFO: [EXTENSION] DXT compressed textures supported
> INFO: [EXTENSION] ETC2/EAC compressed textures supported
> INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
> INFO: [EXTENSION] Mirror clamp wrap texture mode supported
> INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
> INFO: [TEX ID 1] Base white texture loaded successfully
> INFO: [SHDR ID 1] Shader compiled successfully
> INFO: [SHDR ID 2] Shader compiled successfully
> INFO: [SHDR ID 3] Shader program loaded successfully
> INFO: [SHDR ID 3] Default shader loaded successfully
> INFO: Internal buffers initialized successfully (CPU)
> INFO: Internal buffers uploaded successfully (GPU)
> INFO: OpenGL default states initialized successfully
> INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
> INFO: [TEX ID 2] Default font loaded successfully
> WARNING: [] Text file could not be opened
> WARNING: [SHDR ID 4] Failed to compile shader...
> INFO: Vertex shader failed to compile with the following errors:
> ERROR: 0:323: error(#143) Undeclared identifier: fwidth
> ERROR: 0:323: error(#202) No matching overloaded function found: fwidth
> ERROR: 0:323: error(#160) Cannot convert from: "const float" to: "highp 2-component vector of vec2"
> ERROR: 0:403: error(#143) Undeclared identifier: gl_FragCoord
> ERROR: 0:403: error(#216) Vector field selection out of range "xy"
> ERROR: error(#273) 5 compilation errors.  No code generated
> 
> 
> WARNING: [SHDR ID 5] Failed to link shader program...
> INFO: Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 
> 
> WARNING: Custom shader could not be loaded

**Comment by raysan5** [comment]
@Guevara-chan Just uploaded some changes that can be related on commit https://github.com/raysan5/raylib/commit/f2247c6f0a2c200937f40c09d829e48360d42df7, please try with latest master branch.

**Comment by Guevara-chan** [comment]
> @Guevara-chan Just uploaded some changes that can be related on commit [f2247c6](https://github.com/raysan5/raylib/commit/f2247c6f0a2c200937f40c09d829e48360d42df7), please try with latest master branch.

Recompiling `raylib` on Windows gonna be a pain, right ?

**Comment by raysan5** [comment]
it shouldn't be...

**Comment by Guevara-chan** [comment]
You sure ?
> C:\1EXE\raylib\src>mingw32-make PLATFORM=PLATFORM_DESKTOP
> cc -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
> process_begin: CreateProcess(NULL, cc -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33, ...) failed.
> make (e=2): ═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы.
> Makefile:543: recipe for target 'core.o' failed
> mingw32-make: *** [core.o] Error 2

**Comment by raysan5** [comment]
It seems an issue with the compiler not found... try adding `CC=gcc` to makefile call.

**Comment by Guevara-chan** [comment]
Same thing.
> C:\1EXE\raylib\src>mingw32-make PLATFORM=PLATFORM_DESKTOP CC=gc
> gc -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
> process_begin: CreateProcess(NULL, gc -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mi
> ngw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33, ...) failed.
> make (e=2): ═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы.
> Makefile:543: recipe for target 'core.o' failed
> mingw32-make: *** [core.o] Error 2

**Comment by raysan5** [comment]
@Guevara-chan per your output, it seems you wrote `CC=gc` instead of `CC=gcc`

**Comment by Guevara-chan** [comment]
I guess, it's `mingw32-make PLATFORM=PLATFORM_DESKTOP CC=gcc SHARED=ON` then ?

**Comment by raysan5** [comment]
Just `mingw32-make PLATFORM=PLATFORM_DESKTOP CC=gcc`.

**Comment by Guevara-chan** [comment]
Ah, right. Done, Now I need some .dll, I guess.

**Comment by raysan5** [comment]
@Guevara-chan `mingw32-make PLATFORM=PLATFORM_DESKTOP CC=gcc RAYLIB_LIBTYPE=SHARED`

**Comment by Guevara-chan** [comment]
Well, just tried it. Exactly nothing got changed, though.

**Comment by raysan5** [comment]
@Guevara-chan no more ideas, it seems it could be related to Nim binding, I tried in desktop and web platforms with original raylib and it works ok.

**Comment by raysan5** [comment]
It seems this issue could be related to Nim bindings, actually this raylib functionality has not been reported in any supported platform. Closing the issue.
