### ISSUE TITLE
GetKeyPressed() only reading one char and not resetting 

### ISSUE THREAD

**Issue by HenningCode** [raysan5/raylib#1110]
I am creating a Game and wanted to get the Name of the Player via a text input field. I tried to replicate the example with the text input field, but as soon as I call GetKeyPressed I end up in a endless loop and the one key I pressed is read all the time, so it never gets reset. I thought I made a mistake so I just copied the example into my main.cpp and tried it again. Same behavior the key I am pressing first gets read and lopped through the whole time. Should I just manually reset it the key variable? But this isn't the intended behavior or?
I am using MacOs and CLion/CMake to build the project if that matters.

**Comment by Dallion3K** [comment]
int GetKeyPressed() returns the last key pressed anytime its called. The Player may not have typed anything so nothing is returned. But as soon as a key is pressed it will always get that key.
Try something like:

if IsKeyPressed(GetKeyPressed()) //Checks if the key that was last pressed is currently input.
{
//Your code adding it to a string.
}

This in theory should return false and ignore any other inputs until the player hits another key.

**Comment by HenningCode** [comment]
But the example code on the website works. I don’t understand why it isn’t working for me. They are not handling it like that. I understand that if a key from a GetKeyPressed is called the key gets deleted from the queue.

**Comment by raysan5** [comment]
@HenningCode that's weird, it should work ok. Are you calling `GetKeyPressed()` in your game loop?

**Comment by HenningCode** [comment]
Yes I did that, but that didn't work, so I just copied the whole example into my main.cpp and tried to run it. 
Now I build a new main.c with cmake and without any IDE. This doesnt work either. As soon as I type  a char i get stuck inside the loop and the game "crashes"

`cmake_minimum_required(VERSION 3.1.0)
project(Example)

set(CMAKE_CXX_STANDARD 11)

find_package(raylib REQUIRED)
include_directories(${raylib_INCLUDE_DIR})

add_executable(Example main.c)

target_link_libraries(Example ${raylib_LIBRARIES})
`

I am building like this with clang version 9.0.1 and cmake version 3.16.3 and I am on macOS Catalina 10.15.3.

**Comment by raysan5** [comment]
@HenningCode did you try the example provided directly?

**Comment by HenningCode** [comment]
Yes I just fully copy and pasted it. I didn't change anything.

**Comment by raysan5** [comment]
@HenningCode I imagine you are using latest raylib from github master branch, right?

**Comment by HenningCode** [comment]
I was using 2.5.0 installed with brew and now I updated to 2.6.0. I kind of works not but It feels really slow and the backspace is often not recognized. But the main Problem seems to be solved.

**Comment by raysan5** [comment]
@HenningCode ok, master branch is `raylib 3.0` but not released yet. If it feels slow it can be related to FPS. I'll close the issue for now.

**Comment by HenningCode** [comment]
Thats fine. Is the brew installed library not always up to date?

**Comment by raysan5** [comment]
@HenningCode I'm afraid it's quite outdated... raylib is changing almost daily.
