### ISSUE TITLE
[text] DrawText() function outputs blurry

### ISSUE THREAD

**Issue by HenningCode** [raysan5/raylib#1111]
Hello again.. 

Today I updated via brew to raylib 2.6.0 and now the `DrawText()` function outputs really blurry Text. It wasn't like this with raylib 2.5.0.
<img width="396" alt="Bildschirmfoto 2020-02-24 um 22 15 09" src="https://user-images.githubusercontent.com/57907680/75191920-9318ce80-5753-11ea-8ef4-880c25614594.png">

Grettings

**Comment by raysan5** [comment]
@HenningCode That could be related to HighDPI display... but yoyu can just do:
```c
SetTextureFilter(GetFontDefault().texture, FILTER_POINT);
```

**Comment by HenningCode** [comment]
Solved. That did the trick.
