### ISSUE TITLE
understanding sleep time between frames

### ISSUE THREAD

**Issue by gezzuzz** [raysan5/raylib#1112]
Im building a graphical interface for the RPI.. Raylib works great but i have to do other comm related things. How does Raylib the sleep between frames.. seams to me if i set FPS to 1.. the main loop runs only one time per sec.. my target is 30 FPS... after i draw a frame i would like to do other things before i start the next frame.. 

thank you

**Comment by gezzuzz** [comment]
im guessing i should just run a separate thread..

**Comment by raysan5** [comment]
@gezzuzz loop just wait for the target fps, you can do other things in the update section of the loop. If frames drop, you should move some logic to a second thread.

**Comment by gezzuzz** [comment]
> @gezzuzz loop just wait for the target fps, you can do other things in the update section of the loop. If frames drop, you should move some logic to a second thread.

how can i calculate how much time it takes to draw a frame? i would like to know how much time of the frame time window i am using?

**Comment by raysan5** [comment]
It depends on `SetTargetFPS()`, time = 1000ms/fps, for example 60 fps are 16.6ms aprox. You can also use `GetFrameTime()`.
