### ISSUE TITLE
[models] glTF Fails to load mesh for apparent no reason

### ISSUE THREAD

**Issue by kaori-komi** [raysan5/raylib#1114]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Try to load a model in .glb, 3/4 of the model loads, only a sphere turns into the default cube. The same model in .iqm loads fine, so I don't think I'm using it a wrong way. Snippet that loads the model:

```c
	Obj* obj = malloc(sizeof(Obj));
	obj->model = LoadModel(model_path);
	obj->texture = LoadTexture(texture_path);
	obj->model.materials[0].maps[MAP_DIFFUSE].texture = obj->texture;
	obj->model.transform = MatrixMultiply(obj->model.transform, MatrixRotateX(1.57f));
```
Import the .glb on Blender returns a correct model.

### Environment

Win 10, GL 3.3, GTX 1050

### Issue Screenshot

https://i.imgur.com/xGLbT3Q.png << model failing to load centre sphere (ignore rotation and scale, since I'm working with IQM while glTF doesn't work I didn't adjust).

https://i.imgur.com/2Da8Wvo.png << Correctly loaded (the things on the sides load without problem in the other screenshot, they just didn't appear in the camera).

### Model
[models.zip](https://github.com/raysan5/raylib/files/4268510/models.zip)

**Comment by raysan5** [comment]
@kaori-komi thanks for the detailed issue. :)

**Comment by Gamerfiend** [comment]
@kaori-komi Please try this model file


[load_test2.zip](https://github.com/raysan5/raylib/files/4269777/load_test2.zip)

**Comment by kaori-komi** [comment]
This loads fine... So I guess the culprit are the exporters/converters?

**Comment by Gamerfiend** [comment]
Always make sure to apply all transforms to a model before exporting, you can find out how to do this by looking here :) https://docs.blender.org/manual/en/latest/scene_layout/object/editing/transform/clear_apply.html

**Comment by raysan5** [comment]
@Gamerfiend thanks for the review! 😄
