### ISSUE TITLE
[core] Function IsKeyDown() only seems to be working for the first second or two

### ISSUE THREAD

**Issue by Colday96** [raysan5/raylib#1119]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch 
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Pressing the key leads to no output after 1/2 seconds. I have tor elease the key and press it againf ro it to work. I made sure to use IsKeyDown() and not 
IsKeyPressed()

### Environment

I am running linux, using OpenGL version 3.3 with an intel hd 515

### Code

void update()
{
    player.init_vel.y = player.init_vel.y + player.acceleration.y;

    player.pos.y = player.pos.y + player.init_vel.y;
    

    if (player.pos.y > WinHeight - player.size.y)
    {
        player.pos.y = WinHeight - player.size.y;
        player.init_vel.y = 0;
    }

    if (IsKeyPressed(KEY_SPACE))
    {
        player.init_vel.y -= 30;
    }

    if (IsKeyPressed(KEY_A))
    {
        player.pos.x = player.pos.x - player.init_vel.x;
    }

    if (IsKeyDown(KEY_D))
    {
        player.pos.x = player.pos.x + player.init_vel.x;
    }

}

**Comment by twjanes** [comment]
I also see this behaviour on Ubuntu 18.04 and the supplied example core_input_keys.

**Comment by raysan5** [comment]
@twjanes I confirm the issue! This is really weird! I need to check it! :(

**Comment by raysan5** [comment]
@twjanes I found the issue and I corrected it, it was a tricky want... It should work now.

**Comment by chriscamacho** [comment]
I tried to replicate this on Void Linux, but was unable to. (gl3v3 intel gpu)
@Colday96 @twjanes are you able to replicate this with for example a very simple GLFW test

`#include <GLFW/glfw3.h>
#include <stdlib.h>
#include <stdio.h>

static void error_callback(int error, const char* description)
{
    fprintf(stderr, "Error: %s\n", description);
}
 
static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
        glfwSetWindowShouldClose(window, GLFW_TRUE);
    
    if (key == GLFW_KEY_F9) {
		if ( action == GLFW_PRESS ) printf("f9 Pressed\n");
		if ( action == GLFW_REPEAT ) printf("f9 Repeat\n");
		if ( action == GLFW_RELEASE) printf("f9 Released\n");
	}
}
 
int main(void)
{
    GLFWwindow* window;

    glfwSetErrorCallback(error_callback);
 
    if (!glfwInit())
        exit(EXIT_FAILURE);
 
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
 
    window = glfwCreateWindow(640, 480, "Simple example", NULL, NULL);
    if (!window)
    {
        glfwTerminate();
        exit(EXIT_FAILURE);
    }
 
    glfwSetKeyCallback(window, key_callback);
    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);

    while (!glfwWindowShouldClose(window))
    {
        glfwSwapBuffers(window);
        glfwPollEvents();
    }
 
    glfwDestroyWindow(window);
 
    glfwTerminate();
    exit(EXIT_SUCCESS);
}`

**Comment by twjanes** [comment]
Thanks Ray, Now all working

**Comment by raysan5** [comment]
@chriscamacho it was a raylib issue, I recently changed how key states were processed and I forgot to consider GLFW_REPEAT state as `PRESSED`. All solved now.

**Comment by chriscamacho** [comment]
That's Trinary for you!
