### ISSUE TITLE
[core] SetExitKey() bug (with fix)

### ISSUE THREAD

**Issue by TakUnderhand** [raysan5/raylib#1125]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch **(I checked master and it has the same bug)** [core.c line 4641](https://github.com/raysan5/raylib/blob/master/src/core.c)
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

SetExitKey() didn't work for me: I wanted to disable KEY_ESCAPE.
So I fixed it:
In core.c, function ProcessKeyboard(), the value 256 is used for checking for exit in one place, where it should use CORE.Input.Keyboard.exitKey.

Current code:
`if (bufferByteCount == 1) CORE.Input.Keyboard.currentKeyState[256] = 1;> //raylib key: KEY_ESCAPE`
Fixed code:
`if (bufferByteCount == 1) CORE.Input.Keyboard.currentKeyState[CORE.Input.Keyboard.exitKey] = 1; // default raylib key: KEY_ESCAPE`

### Environment

I'm cross developing on MacOS/Linux/Window (MSYS).  Although I only tested this bug fix on MacOS so far.

### Issue Screenshot

Not applicable

### Code Example

See above

**Comment by raysan5** [comment]
@TakUnderhand thanks! fixed!

**Comment by TakUnderhand** [comment]
You're welcome!
Thanks for the amazing API of raylib :)
