### ISSUE TITLE
[build] msvc15 releases are debug only

### ISSUE THREAD

**Issue by sergio-ic** [raysan5/raylib#1128]
Builds provided for MSVC15 (Win32 and Win64) are a great asset for people starting with raylib. I teach with them and I appreciate that you provide them on every new release.

However, I have found out that the libraries provided are only debug version. If someone wants to build a game on release mode to distribute a version for final users, raylib.dll (for instance, to mention the dynamic library) depends on debug libraries (screenshot):

![debug](https://user-images.githubusercontent.com/17152612/76219285-5db0be00-61f4-11ea-97a7-5b8e71ec000f.png)

So end users without development environments installed are unable to run games linked with those debug libs.

When building raylib from the projects provided for VS2017 you have already set up the option for debug and release builds (besides static/dynamic and x86/x64 flavours). This is the result of such a build (dll built with release dynamic x86 option in VS):

![build](https://user-images.githubusercontent.com/17152612/76219580-cdbf4400-61f4-11ea-86d1-95b5e816c61e.png)

So, since people starting game dev may have trouble finding out why a developed game throws a dll error (for not having vcruntime140d.dll or ucrtbased.dll) and doesn't work on the player's machine, maybe on raylib's next release the _raylib-X.X.X-Win32-msvc15.zip_ and _raylib-X.X.X-Win64-msvc15.zip_ could come with debug and release versions, such as other libs do. For example:

Option 1: two folders for debug and release (debug and release folders under lib and bin folders)
Option 2: raylib_d.dll / raylibd.dll / raylib_debug.dll in the same folder as raylib.dll (so with .lib's)

Thank you very much.

**Comment by raysan5** [comment]
@sergio-ic generated build depend on the current AppVeyor build system, I didn't setup it. Maybe @a3f can take a look to this issue...

I already started working on a GitHub Actions build system but that's a lot of work, feel free to contribute if you want.

**Comment by a3f** [comment]
> Option 1: two folders for debug and release (debug and release folders under lib and bin folders)
Option 2: raylib_d.dll / raylibd.dll / raylib_debug.dll in the same folder as raylib.dll (so with .lib's)

Is it that useful to have debug configurations, when you can just build the project yourself? I can switch the packages msvc15.zips to release instead. Would that work for you?

**Comment by raysan5** [comment]
@a3f personally I think releasing `release` versions only should be enough.

**Comment by sergio-ic** [comment]
Thanks @raysan5 @a3f 

I think having both configurations available inside the zip would be great. Let me explain why so that you can evaluate if you find it appropiate for the project and if it is possible for you to configure it at this moment (if not, I will try investigate and make a pull request with the suggested change).

Some of the students I teach start developing games for the first time with raylib. They do not have a lot of experience with cloning repositories, configuring a development environment and building projects, nor they know much about different build configurations. When they start, they learn the basics of including and linking to use external libraries and some of the exercises I give them is making small games and apps with simple yet great libs such as SDL, Allegro and, of course, raylib.

Linking the appropriate library for the debug or release configuration is easy to learn and useful for beginners, so I would believe this would be helpful for many. However, if release versions of raylib work well in apps built with debug configuration then I guess there would be no need to have the debug versions in the package.

Thanks for your time and effort.

**Comment by raysan5** [comment]
> Is it that useful to have debug configurations, when you can just build the project yourself?

@a3f I think providing only release configuration is the most logical option. Could you implement it please?

@sergio-ic As stated, you can build the library yourself in debug mode if required, Visual Studio projects are provided just for that situation.

**Comment by a3f** [comment]
raylib v3.0 should have Release-With-Debug-Info packages uploaded from AppVeyor.

**Comment by raysan5** [comment]
@a3f ok, nice! thanks! :)
