### ISSUE TITLE
[text] TextToUpper() method doesn't cover diacritics

### ISSUE THREAD

**Issue by JasonNumberThirteen** [raysan5/raylib#1129]
I would like to report that using the "_TextToUpper_" method **doesn't cover UTF-8**.

Using this:

`LoadFontEx("shPinscher.ttf", fontSize(), 0, FONT_TOTAL_CHARS);`

where **FONT_TOTAL_CHARS = 381** (to include all Polish letters) and this:

`TextToUpper("Wybór profilu")`

I have all capital letters instead of "ó" (fourth character) which belongs to Polish diacritics:
![TextToUpper effect](https://user-images.githubusercontent.com/40078536/76510924-ad8cc080-6452-11ea-9fb4-077cb833cfd8.PNG)

Should be:
![Proper effect](https://user-images.githubusercontent.com/40078536/76510991-c4331780-6452-11ea-8fd0-3ce3c690dcd1.PNG)

I understand you might not want to modify entire method however, could you give any potential tips how to fix this instead of setting this manually? Maybe using methods operating on codepoints or an array containing all Polish letters?

**Comment by raysan5** [comment]
Hi @JasonNumberThirteen, thanks for reporting! Actually, this is a tricky issue, no easy solution, neither the standard C `toupper()`/`tolower()` functions support UTF8.

I think easier solution would be implementing a custom `TextToUpperUTF8()` method supporting utf8, raylib includes a couple of functions useful to convert between `Codepoints <-> Utf8`.
```c
RLAPI int GetNextCodepoint(const char *text, int *bytesProcessed);    // Returns next codepoint in a UTF8 encoded string; 0x3f('?') is returned on failure
RLAPI const char *CodepointToUtf8(int codepoint, int *byteLength);    // Encode codepoint into utf8 text (char array length returned as parameter)
```
I added a code not on commit https://github.com/raysan5/raylib/commit/7fa12844eda0348fee3ddf8f2799074796050ddd to keep that in mind.

**Comment by JasonNumberThirteen** [comment]
Alright, thanks for your response. I'll try to make something with this.

Besides, it's a very great framework for C/C++ game development, but it needs a little more documentation, in my opinion. To be able to see those diacritics at all, I had to understand this "charsCount", how it works and what exact value I have to type (all of this took me a couple of days). I have been forced to even install "FontForge" and open this font to identify this value and avoid guessing. To be honest, I try to understand every difficult task analysing issues placed right here by community (I'm beginner in C) due to lack of articles and clear explanations like for newbies.

**Comment by brankoku** [comment]
@raysan5 You may want to incorporate this into `raylib` (it's a single-header library): https://github.com/sheredom/utf8.h
@JasonNumberThirteen If the `utf8.h` project linked above doesn't yet support Polish characters, this would be a great opportunity to add them. Doing so would improve both projects. Much better than reinventing the wheel. :+1:

**Comment by raysan5** [comment]
@brankoku I've been following this library for some time, no plans to incorporate it to raylib for the moment... maybe in the future...

**Comment by JasonNumberThirteen** [comment]
@brankoku Thanks for giving a link, I'll try this if I won't be able to fix this without using "utf.h".
@raysan5 Could you give some examples how to use both methods? I tried to find in "unicode" example, but there are no usage of these functions.

**Comment by raysan5** [comment]
@brankoku here it is the implementation, not tested

```c
char message[128] = "some unicode text to convert to uppercase\0";

int cpCount = 0;
int *cpMessage = GetCodepoints(message, &cpCount);  // Get unicode equivalent of utf8 string

for (int i = 0; i < cpCount; i++)
{
    // Check character between à and ö, and convert to uppercase.
    // NOTE: Some other character ranges could be required, check unicode tables!
    if ((cpMessage[i] >224) && (cpMessage[i] <246)) cpMessage[i] -= 32;
}

char *resultMessage = TextToUtf8(cpMessage, cpCount);  // Convert from unicode to utf8 again

// Draw text or use string in any way...

free(resultMessage);  // Remember to free returned string, allocated inside TextToUtf8()!
```
