### ISSUE TITLE
[examples] Examples crash on OSX 10.11.4 when GRAPHICS = GRAPHICS_API_OPENGL_33

### ISSUE THREAD

**Issue by cHemingway** [raysan5/raylib#113]
After fixing some paths to get the examples to build, running shapes_basic_shapes gives the following output. This example runs fine with the standard `GRAPHICS=GRAPHICS_API_OPENGL_11`
 I have attached the standard OSX error report: [error_report.txt](https://github.com/raysan5/raylib/files/264137/error_report.txt).

```
INFO: Initializing raylib (v1.5.0)
WARNING: [GLFW3 Error] Code: 65543 Decription: NSGL: The targeted version of OS X only supports forward-compatible contexts for OpenGL 3.2 and above
fish: './shapes_basic_shapes' terminated by signal SIGSEGV (Address boundary error)
```

This also happens when running examples that need OpenGL 3.3, such as shaders_custom_uniform:
```
INFO: Initializing raylib (v1.5.0)
INFO: Trying to enable MSAA x4
WARNING: [GLFW3 Error] Code: 65543 Decription: NSGL: The targeted version of OS X only supports forward-compatible contexts for OpenGL 3.2 and above
fish: './shaders_custom_uniform' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by cHemingway** [comment]
This is apparently a [known issue](http://www.glfw.org/faq.html#how-do-i-create-an-opengl-30-context) with glfw on OSX.

If I change [line 1450 of core.c](https://github.com/raysan5/raylib/blob/develop/src/core.c#L1450) to  `glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);` then examples run without segfaulting. A pull request is in the works to do this on OSX only.

The shaders for shaders_custom_uniform and shaders_postprocessing don't seem to be loaded properly by the driver so they don't look like the reference images, but shaders_shapes_textures works fine:
![screenshot 2016-05-14 00 48 08](https://cloud.githubusercontent.com/assets/3956920/15264676/e7e6e03c-196d-11e6-8fff-eddef368214e.png)

**Comment by cHemingway** [comment]
Closed by #114, cheers!

**Comment by raysan5** [comment]
Hi @cHemingway! Thank you very much for the update on OSX! Pull request https://github.com/raysan5/raylib/pull/114 already merged!

About the shaders not loaded properly on `shaders_custom_uniform` and `shaders_postprocessing`, please, could you provide the raylib output log? If they are not compiled/linked properly by the driver a message should appear...

**Comment by cHemingway** [comment]
Of course, here is a gist with logs for both:
https://gist.github.com/cHemingway/f9cfdfa278723ac2de7379bbdb31ce1f

Here are some screenshots, which seem to show no effects being performed:
![shaders_custom_uniform](http://i.imgur.com/dK5hldB.png)
![shaders_postprocessing](http://i.imgur.com/E9fiapT.png)

Would you like me to move this to a new issue?

**Comment by raysan5** [comment]
Ok, I see the error. Just renamed `texture2D()` to `texture()`. First version is deprecated since GLSL 130, despite it should work... it seem not all drivers think the same...

Solved on commit https://github.com/raysan5/raylib/commit/0e29aa2951fe11e9d0fabec2182ed6309fce37bb

**Comment by cHemingway** [comment]
And fixed! Fantastic! 👍 

![shaders_custom_uniform](http://i.imgur.com/KGMZy0j.png)
![shaders_postprocessing](http://i.imgur.com/7nG06v3.png)

**Comment by raysan5** [comment]
Great! :D
