### ISSUE TITLE
[textures] Add line-break support to ImageText()

### ISSUE THREAD

**Issue by louisgjohnson** [raysan5/raylib#1131]
Similar to https://github.com/raysan5/raylib/issues/44

When drawing text to an image, it will be very useful to be able to add line-breaks \n.

Related functions [textures.c]:
```
void ImageDrawTextEx(Image *dst, Vector2 position, Font font, const char *text, float fontSize, float spacing, Color color);
```

**Comment by raysan5** [comment]
@louisgjohnson function reviewed! just read commit notes for a warning about spacing!

**Comment by louisgjohnson** [comment]
Thanks @raysan5 that was super quick!
