### ISSUE TITLE
[text] LoadFontData() failure missing info and continues execution

### ISSUE THREAD

**Issue by fctr** [raysan5/raylib#1135]
When loading certain TTF fonts using "LoadFontData", I'll get a log entry "WARNING: Failed to init font!", but no other indication of the failure.

Also, the code in text.c seem to keep going even after the failure is reported, when in reality the function should drop out and return nullptr.

text.c Line 509: `if (!stbtt_InitFont(&fontInfo, fileData, 0)) TRACELOG(LOG_WARNING, "Failed to init font!");`

**Comment by raysan5** [comment]
@fctr yeah, thanks for reporting, I'll look into it.

**Comment by fctr** [comment]
You're the wind beneath my wings, sir.

Also, I've created a whole enhanced framework (using raygui) with C++ that is pretty easy to use and mimics standard GUI frameworks, including touchscreen usage. I'd be happy to share, if you'd like.

**Comment by raysan5** [comment]
@fctr hi! sure! I'd love to see it! :D

I'm not closing the issue yet because I'm planning to review all TraceLog messages soon.

**Comment by fctr** [comment]
Still perfecting it, as it's not quite ready for primetime. May I recommend putting all of RayLib in it's own namespace, as I've done?

**Comment by raysan5** [comment]
@fctr Unfortunately no namespace in C. :)

**Comment by fctr** [comment]
I know, but I put the following at the top: 
`#if defined(__cplusplus)
namespace RayLib
{
#endif`
and at the end:
`#if defined(__cplusplus)
}
#endif`

**Comment by raysan5** [comment]
@fctr I prefer to avoid C++ specific code, raylib is a C library.
