### ISSUE TITLE
Working on GNU Linux guide possibly missing a required library for compilation

### ISSUE THREAD

**Issue by jouko-kelomaki** [raysan5/raylib#1139]
Compilation with a rather fresh ubuntu 19.10 failed after following the guide at:
https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux

Executing the following commands:

```
git clone https://github.com/raysan5/raylib.git raylib
cd raylib/src/
make PLATFORM=PLATFORM_DESKTOP # To make the static version.
```

ran into the following problem:

```
make PLATFORM=PLATFORM_DESKTOP

...

In file included from external/glfw/src/internal.h:188,
                 from external/glfw/src/context.c:30,
                 from rglfw.c:54:
external/glfw/src/x11_platform.h:36:10: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
   36 | #include <X11/Xcursor/Xcursor.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:546: rglfw.o] Error 1

```

Fixed this by installing something that supposedly contains everything that I could be missing:

```
sudo apt install xorg-dev
```

After this, compilation works like a charm.

**Comment by chriscamacho** [comment]
from: https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux

> Install required libraries
> You need to install some required libraries; ALSA for audio, Mesa for OpenGL accelerated graphics and X11 for windowing system.
> sudo apt install ..... xorg-dev .....
(where ... is numerous other libs!)

**Comment by raysan5** [comment]
@chriscamacho that's it.
