### ISSUE TITLE
[examples] Some examples not working on RPi Zero / OpenGL ES 2.0

### ISSUE THREAD

**Issue by JeffCalwood** [raysan5/raylib#1141]
I found several examples don't work on a RPi Zero with OpenGL ES 2.0 :
At least the fog example, and the examples/models/models_material_pbr doesn't .
I notices that the shaders in resources/shaders/glsl100 all use
#version 330
I changed those to #version 100 (should I ?) because the logs indicated version conflicts. But then it complains about another issue in line 12 of a shader (but doesn't say which file). Ultimately, the example quits with a segmentation fault.
Is this fixable, or is OpenGL ES 2.0 not capable of running the pbr shaders ? Ultimately, I was trying to learn how to add lights to my scene ...

**Comment by raysan5** [comment]
Hi @JeffCalwood, some examples are not adapted to work on OpenGL ES 2.0 (`models_material_pbr`, `shaders_raymarching`, `models_skybox`).

`shaders_fog` should work, just use latest raylib version from github master branch, I updated it two weeks ago.

Technically, `models_material_pbr` can run on the RPI but posting all the related shaders could take some works and maybe even raylib requires some tweak...

**Comment by JeffCalwood** [comment]
Thanks, Ray. Do you have any pointers for me to get one lightsource into my scene under OpenGL ES 2.0 ?

**Comment by chriscamacho** [comment]
When I wrote the lighting & fog examples I did mean to get them to work with GLES 2.0
Guess what I have some time on my hands !

@JeffCalwood bare with me, I'll see about getting raylib and GLES 2.0 working on my desktop and hopefully should be able to submit a PR...

**Comment by chriscamacho** [comment]
@JeffCalwood fancy a spot of testing ? 
https://github.com/chriscamacho/raylib
(theres a pending PR - but testing would be useful)
alas I'm isolated from my PI :scream: !

**Comment by raysan5** [comment]
@chriscamacho Note that I ported `shaders_basig_lighting`, `shaders_fog`, `shaders_alpha_mask` examples to OpenGL ES 2.0 in commit https://github.com/raysan5/raylib/commit/485787059a00e54287f465464ce6e430fe9488c6#diff-0ceab060edf65f6a5dcc7659b11454ff.

**Comment by chriscamacho** [comment]
ok for some reason I thought GLES2.0 was GLSL 120.... :/

    GLSL Version      OpenGL Version
    1.10              2.0
    1.20              2.1
    1.30              3.0
    1.40              3.1
    1.50              3.2
    3.30              3.3

Looks like we're both wrong?, shouldn't it be GLSL 110 ?? (for pi)

**Comment by JeffCalwood** [comment]
I am minutes away from testing it. I was working from the release 2.6.0 and just now saw that raysan5 updated the shaders since then.

**Comment by raysan5** [comment]
@chriscamacho That table illustrates **desktop** OpenGL -> GLSL versions, OpenGL **ES** 2.0 uses GLSL 100.

**Comment by chriscamacho** [comment]
hang I think i see my confusing
OpenGL 2.0 is GLSL vestion 110 
where as
GLES 2.0 is *based* on GLSL version 120

I guess it needs testing on the "bare" metal is whats the highest #version you can use in a shader,

**Comment by raysan5** [comment]
@chriscamacho On RPI bare metal, right version is `GLSL 100`.

But note you can use _desktop_ OpenGL on Raspbian desktop, up to OpenGL 2.1, that means `GLSL 120`.

**Comment by chriscamacho** [comment]
*sigh* what did khronos think they were doing with version numbers ... what a mess!
turns out its not even GLSL 100 but GLSL-ES 100, just for extra confusion

**Comment by JeffCalwood** [comment]
I tested @chriscamacho 's branch on the RPi Zero (aka "bare" metal above), but looking at the commit and little confusion the tests would apply to @raysan5 state as well:
shaders_fog - works
shaders_basic_lighting - works (graphics fluent but keyboard input sluggish)
models_materials_pbr - does not work (see logs)
shaders_raymarching - empty white screen (see logs)

[shaders_raymarching.log](https://github.com/raysan5/raylib/files/4371654/shaders_raymarching.log)
[models_material_pbr.log](https://github.com/raysan5/raylib/files/4371655/models_material_pbr.log)

**Comment by JeffCalwood** [comment]
Addendum re: models_materials_pbr example
I see that all the shaders in resources/ still use #version 330. I replaced all by #version 100 (not knowing what I am doing...) but still it terminates with a segmentation fault. I guess that is why the logs are truncated. New log attached.

[models_material_pbr.log](https://github.com/raysan5/raylib/files/4371732/models_material_pbr.log)

**Comment by raysan5** [comment]
@JeffCalwood all the shaders have to be reviewed for `#version 100`, changing first line it's not enough, it requires some more hours work to get it working.

**Comment by JeffCalwood** [comment]
Don't want to be rude or demanding, but should the issue be closed if the shaders still need review ? At a minimum, should the shaders not be deleted from the GLSL100 folder and the examples marked as "platform xyz only" ?

**Comment by raysan5** [comment]
@JeffCalwood Added a note on commit https://github.com/raysan5/raylib/commit/6bab884d1de8b1aadd89e79c26d6294eb22eaece.

No plans to implement it for the moment.

**Comment by chriscamacho** [comment]
@JeffCalwood could i ask a little favour, if you're using the github master (as opposed to 2.6) can you check out my new example shaders_spotlight, I don't have a RPI to hand at the moment, I *think* the shader should work but its been tested on desktop, it really needs testing on the "bare metal"

**Comment by JeffCalwood** [comment]
Yes, it works.

**Comment by raysan5** [comment]
@chriscamacho @JeffCalwood just reviewed it to work 1 hour ago...

**Comment by chriscamacho** [comment]
@JeffCalwood  thanks!
@raysan5 webgl != rpi in some cases a v100 shader on desktop (even webgl) can cheat...!
