### ISSUE TITLE
[core] missing bool IsWindowFullscreen()

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1150]
not really worth a PR this one!!

    bool IsWindowFullscreen() {
        return CORE.Window.fullscreen;
    }

keep finding I'm having to keep track of this manually...

**Comment by chriscamacho** [comment]
usually because I'm wanting to change resolution between the modes...

**Comment by raysan5** [comment]
Added in commit https://github.com/raysan5/raylib/commit/96005f2566091e8d009ee101a6f9d75b7e8f6428.

**Comment by chriscamacho** [comment]
cool, thanks.
