### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by vondarkness** [raysan5/raylib#1153]
Please, before submitting a new issue verify and check:

 - [v] I tested it on latest raylib version from master branch
 - [v] I checked there is no similar issue already reported
 - [v] My code has no errors or misuse of raylib

### Issue description

Trying to compile the code using static library that I have been make using CMake, then it got error with message like this one:

gcc -o 001-RaylibHello.exe 001-RaylibWindow.o -static -lm -LC:/Users/Marcell/Documents/Libraries/C/raylib/lib -lraylib_static
C:/Users/Marcell/Documents/Libraries/C/raylib/lib\libraylib_static.a(core.c.obj):core.c:(.text+0x20070): undefined reference to `timeBeginPeriod'
C:/Users/Marcell/Documents/Libraries/C/raylib/lib\libraylib_static.a(core.c.obj):core.c:(.text+0x203fe): undefined reference to `timeEndPeriod'
c:/winbuild/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/Marcell/Documents/Libraries/C/raylib/lib\libraylib_static.a(core.c.obj): bad reloc address 0x3f9c in section `.rdata'
c:/winbuild/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: final link failed: Invalid operation
collect2.exe: error: ld returned 1 exit status

Am I really need OpenGL? Since you said in your website that this library doesn't need any external dependencies

### Environment

Win10
MinGW 64-bit (using WinBuild)

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example

Trying to build RaylibWindow example from your website

**Comment by raysan5** [comment]
@vondarkness raylib does not require external dependencies to be installed but it requires some system libraries, usually provided by the platform you compile to.

For example, in Windows, you need to link with several system libraries, provided Notepad++ script already consider all those libraries on the compilation script. In any case required libraries are:
`-static -lraylib -lopengl32 -lgdi32 -lwinmm`.

More info on raylib Wiki: https://github.com/raysan5/raylib/wiki/raylib-dependencies

**Comment by vondarkness** [comment]
already installed FreeGLUT and compiled it with FreeGLUT libraries, still got the same error

**Comment by jamesl-github** [comment]
freeglut doesn't have anything to do with raylib                       
raylib uses glfw instead of freeglut 
glfw and freeglut provide a generic way to create windows and receive mouse and keyboard events on mac, windows and linux 
https://www.opengl.org/resources/libraries/windowtoolkits/ 
both freeglut and glfw provide a way of creating a window but neither have a way of drawing inside the window -- that's what opengl is for 
but both of them rely on opengl to draw inside the window and communicate with the graphics card 
raylib is a wrapper around glfw so it still needs opengl to draw inside the window  
raylib comes with glfw built in 
it uses the opengl that comes with your operating system and graphics card driver -- so opengl is not really an external library since it comes with your graphics card driver

**Comment by chriscamacho** [comment]
Freeglut is not required, raylib comes with its own dependencies (in external folder) and they are automatically compiled in...
The only thing you need to verify is that you compiler has the proper system libraries installed 

[ opengl32 gdi32 winmm ]

Compiling in windows can be problematic (like most things in windows) I'd recommend using Linux On Windows Subsystem.

and introduction to how this works can be seen here http://bedroomcoders.co.uk/creating-a-64-bit-executable-with-raylib-on-windows/

**Comment by vondarkness** [comment]
> 
> 
> Freeglut is not required, raylib comes with its own dependencies (in external folder) and they are automatically compiled in...
> The only thing you need to verify is that you compiler has the proper system development libraries installed
> 
> [ opengl32 gdi32 winmm ]
> 
> Compiling in windows can be problematic (like most things in windows) I'd recommend using Linux On Windows Subsystem.
> 
> and introduction to how this works can be seen here http://bedroomcoders.co.uk/creating-a-64-bit-executable-with-raylib-on-windows/

I really wanna avoid Linux On Windows Subsystem at the beginning. I know compiling will gonna be so damn hard in Windows.

Anyway, will try to read the info from that URL.

**Comment by vondarkness** [comment]
> 
> 
> freeglut doesn't have anything to do with raylib
> raylib uses glfw instead of freeglut
> glfw and freeglut provide a generic way to create windows and receive mouse and keyboard events on mac, windows and linux
> https://www.opengl.org/resources/libraries/windowtoolkits/
> both freeglut and glfw provide a way of creating a window but neither have a way of drawing inside the window -- that's what opengl is for
> both of them rely on opengl to draw inside the window and communicate with the graphics card
> 
> raylib is a wrapper around glfw so it still needs opengl to draw inside the window
> 
> raylib comes with glfw built in
> 
> it uses the opengl that comes with your operating system and graphics card driver -- so opengl is not really an external library since it comes with your graphics card driver

already build GLFW libraries, but still got same error. so confusing.

gcc -o 001-RaylibHello.exe 001-RaylibWindow.o -static -lm  -LC:/Users/Marcell/Documents/Libraries/C/glfw/lib -lglfw3 -LC:/Users/Marcell/Documents/Libraries/C/raylib/lib -lraylib_static    
C:/Users/Marcell/Documents/Libraries/C/raylib/lib\libraylib_static.a(core.c.obj):core.c:(.text+0x20070): undefined reference to `timeBeginPeriod'
C:/Users/Marcell/Documents/Libraries/C/raylib/lib\libraylib_static.a(core.c.obj):core.c:(.text+0x203fe): undefined reference to `timeEndPeriod'
c:/winbuild/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/Marcell/Documents/Libraries/C/raylib/lib\libraylib_static.a(core.c.obj): bad reloc address 0x3f9c in section `.rdata'
c:/winbuild/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: final link failed: Invalid operation
collect2.exe: error: ld returned 1 exit status

**Comment by raysan5** [comment]
@vondarkness why not you start with the raylib Windows Installer provided and doing some tests with Notepad++?

**Comment by vondarkness** [comment]
> 
> 
> @vondarkness why not you start with the raylib Windows Installer provided and doing some tests with Notepad++?
> 
> Note that you neither need GLFW3, it's already included with raylib.

is there any EXE installer?? since I didn't found it in your website

**Comment by jamesl-github** [comment]
one of your errors is "undefined reference to timeBeginPeriod'"

timeBeginPeriod is a MS Windows function 
https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod
so you have to link all the correct MS Windows libs or dlls              
and GLFW does not include opengl           
opengl comes with your graphics card driver and operating system          
 so you have to link to it

**Comment by maxphilippov** [comment]
I got this dialog box when I compile core_basic_window.c from notepad 'raylib_compile_execute' 3.0.0-tcc (got it from itch.io):
---------------------------
core_basic_window.exe - Entry Point Not Found
---------------------------
The procedure entry point timeEndPeriod could not be located in the dynamic link library kernel32.dll. 
---------------------------
OK   
---------------------------

But Microsoft docs say it belongs to winmm.dll:
https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod

That's the only issue mentioning timeEndPeriod, so I decided to comment here, or should I open a new one or try installing from github?

**Comment by raysan5** [comment]
@maxphilippov are you on `Windows 7`?

**Comment by maxphilippov** [comment]
> @maxphilippov are you on `Windows 7`?
Yes, sorry, forgot to mention

**Comment by raysan5** [comment]
That's the issue, `WinMM` is not available on early versions of `Windows 7`. 

You can avoid `WinMM` library by enabling `SUPPORT_BUSY_WAIT_LOOP` instead of `SUPPORT_HALFBUSY_WAIT_LOOP` on `raylib/src/config.h` and recompiling the library.

**Comment by maxphilippov** [comment]
> You can avoid `WinMM` library by enabling `SUPPORT_BUSY_WAIT_LOOP` instead of `SUPPORT_HALFBUSY_WAIT_LOOP` on `raylib/src/config.h` and recompiling the library.

Worked like a charm, thank you! Amazing bundle by the way.

**Comment by raysan5** [comment]
@maxphilippov nice! 👍 😄
