### ISSUE TITLE
[textures] Have ImageDraw* methods match method arguments of Draw*

### ISSUE THREAD

**Issue by RobLoach** [raysan5/raylib#1155]
The new `ImageDraw*` methods added in https://github.com/raysan5/raylib/commit/574c689ff7377d11f087ed1f3cd29365b7ba304c are great, but I think we could go one step further to provide matching methods to those that are `DrawPixel()`, `DrawPixelV()`, etc.

**Comment by raysan5** [comment]
@RobLoach It was not on the planning for raylib 3.0 but this is a nice addition... it's a step towards a complete software 2d renderer for raylib, those functions are a mapping of hardware equivalents to `Image`... it could be interesting to explore it further...

I would just ask you for some extra help if you don't mind, adding this functions in raylib base library also imply:
 - [ ] Add/modify the functions in [raylib.com cheatsheet](https://github.com/raysan5/raylib.com/blob/master/cheatsheet/raylib_textures.c).
 - [ ] Add/modify the functions in [Notepad++ intellisense](https://github.com/raysan5/raylib/blob/master/projects/Notepad%2B%2B/c_raylib.xml).
 - [ ] Maybe update some image-related example in `raylib/examples/textures`.

**Comment by RobLoach** [comment]
Thanks! Updated at https://github.com/raysan5/raylib/pull/1156 and https://github.com/raysan5/raylib.com/pull/9
