### ISSUE TITLE
[build] malloc/free incompatibility with bindings

### ISSUE THREAD

**Issue by vtereshkov** [raysan5/raylib#1157]
### Issue description

The Raylib API has some functions that allocate data in the heap and return a pointer to them. How should this memory be freed? There is a well-known problem of incompatible `malloc()`’s when interacting with a DLL. 

For example, I cannot deallocate the animations allocated by `LoadModelAnimations()`. The standard Pascal version of `free()` causes an access violation exception. The Free Pascal example imports a rather tricky `CMem` unit (which I don’t have in my compiler) with a strange comment:

> It seems that using the CMem unit makes Free Pascal use the C Runtime Memory management. Allowing us to correctly free memory allocated by raylib. (Hope this is correct).
 
Don’t you consider adding a simple wrapper for the `free()` function to your API, so it would call your native version of `free()` inside your DLL? 

### Environment

Windows 7, Free Pascal/XD Pascal, Raylib 2.6.0.

**Comment by raysan5** [comment]
@vtereshkov raylib uses macros `RL_MALLOC`/`RL_FREE` and similar for all allocations, you can just redefine those macros on raylib compilation to use your custom allocators.

**Comment by vtereshkov** [comment]
@raysan5 OK. But can I use `UnloadModelAnimation()` to deallocate everything allocated by `LoadModelAnimations()`?

**Comment by raysan5** [comment]
> can I use UnloadModelAnimation() to deallocate everything allocated by LoadModelAnimations()?

@vtereshkov I think so, or it should be.

**Comment by vtereshkov** [comment]
@raysan5 Hmm... I'm afraid that's not right, because you first call `UnloadModelAnimation()` for each animation and then `RL_FREE(anims)`.

https://github.com/raysan5/raylib/blob/master/examples/models/models_animation.c#L103

**Comment by raysan5** [comment]
@vtereshkov oh, ok, I see... `UnloadAnimation()` only deallocates individual animations but not the array...

So, can you use `RL_MALLOC`/`RL_FREE` macros to map custom allocators?

Did you find any other function presenting the same problem?

**Comment by vtereshkov** [comment]
@raysan5 I'm currently using a pre-built version of `raysan.dll`. Probably I can try experimenting with custom allocators. But I think a cleaner way is to have `RL_FREE` as a wrapper function exported by the DLL rather than a macro.

**Comment by raysan5** [comment]
No plans for the moment to add a malloc/free wrapper function, RL_MALLOC/RL_FREE should be enough to hook allocation. Also consider that most of the libraries used by raylib neither offer custom malloc/free wrapers but the same macros-based mechanism (already hooked to RL_MALLOC/RL_FREE).

I'm closing this issue for now.
