### ISSUE TITLE
fabsf in tcc compiler broken

### ISSUE THREAD

**Issue by rogerd007** [raysan5/raylib#1159]
### Issue description

The fabsf function in the TCC compiler library appears to be broken (always returns 0.0f), which breaks many functions in shapes.c. Version 2.5 of raylib works fine, as it used fabs instead of fabsf.

### Environment

Windows 10, raylib with TCC installed using package on itch.io. raylib replaced with master from github.

### Code Example

//test.c
#include <stdio.h>
#include <math.h>

int main() {
	float num1 = 3.5f;
	float num2 = 2.0f;
	float result = fabsf(num1 - num2);
	printf("Result: %f", result);
}

C:\raylib\temp>..\tcc\tcc -o test.exe test.c
C:\raylib\temp>test
Result: 0.000000

**Comment by raysan5** [comment]
oh! weird... any proposed solution?

**Comment by chriscamacho** [comment]
I had a look at "hijacking" the function pointer to fabsf (you could do this in a #ifdef A_TCC_FLAG_TO_DETECT_TCC somewhere in raylib) however I couldn't get the function signature correct as its obscured by some odd macro...

**Comment by raysan5** [comment]
@rogerd007 please, can you check `tcc/include/math.h` file and uncomment `line 246`:
```c
//_asm__ ("fabs;" : "=t" (res) : "0" (x));
```
I already edited that header for TCC (check `line 170`).

**Comment by chriscamacho** [comment]
and after posting that it occured to me you could have an FABS define like malloc and friends

**Comment by raysan5** [comment]
@chriscamacho yeah, I though about that and so I listed ALL `libc` functions dependencies on raylib and tried to limit usage with some custom implementations... maybe in a future...

**Comment by rogerd007** [comment]
I get "math.h:246: error: unknown constraint 't'" when line 246 is uncommented. I notice there was a message on the TCC mailing list regarding this a few years ago. Perhaps commenting it out was their "solution"!

https://lists.nongnu.org/archive/html/tinycc-devel/2017-03/msg00015.html

**Comment by raysan5** [comment]
@rogerd007 thanks for trying! ok, so it seems the solution will be just mapping `fabsf()` to `(float)fabs()`.

**Comment by rogerd007** [comment]
Yup, I think that's going to be the easiest option.

**Comment by raysan5** [comment]
Ok, proposed solution works, just listing it here for reference. It would be included in next raylib-tcc installer. The following file was modified: `tcc/include/math.h`

`line 168`:
```c
    //float __cdecl fabsf(float _X);            // @raysan5: Moved below

// @raysan5: TCC does not support inline functions, default behaviour on Windows 32bit
#if defined(__TINYC__) && defined(__i386__)
    static float fabsf(float _X) { return ((float)fabs((double)_X)); }     // @raysan5: added
```

`line 243`:
```c
#if !defined (__ia64__)
// @raysan5: Commented
/*
  __CRT_INLINE float __cdecl fabsf (float x)
  {
    float res;
    //__asm__ ("fabs;" : "=t" (res) : "0" (x));
    return res;
  }
*/
  __CRT_INLINE float __cdecl ldexpf (float x, int expn) { return (float) ldexp (x, expn); }
#endif
```
