### ISSUE TITLE
Add vcpkg installation instructions 

### ISSUE THREAD

**Issue by NancyLi1013** [raysan5/raylib#1161]
`raylib `is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `raylib `and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `raylib`, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/raylib/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

I'm trying to add vcpkg installation instructions but I couldn't find the related docs in code item except for on Wiki page.

Could you please help add the following contents to this port?

```
Installing and building raylib via vcpkg

You can download and install raylib using the [vcpkg](https://github.com/Microsoft/vcpkg) dependency manager:

      git clone https://github.com/Microsoft/vcpkg.git
      cd vcpkg
      ./bootstrap-vcpkg.sh
      ./vcpkg integrate install
      vcpkg install raylib

The raylib port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.
```
The similar pull request like this lz4/lz4#825.

Thanks,
Nancy

**Comment by raysan5** [comment]
@NancyLi1013 Sure! Added info to README in commit https://github.com/raysan5/raylib/commit/c47ba58494c1320c7d5d0f4f54dbed69c9ff213b.

**Comment by NancyLi1013** [comment]
@raysan5  Thanks for your efforts.
