### ISSUE TITLE
raylib so versioning with 3.0.0 release

### ISSUE THREAD

**Issue by jubalh** [raysan5/raylib#1163]
You are naming the shared objects files:

```
/usr/lib64/libraylib.so.2.6.0
/usr/lib64/libraylib.so.261
```

Are you sure about this for the 3.0.0 release?

**Comment by raysan5** [comment]
@jubalh yeah, I know, I have to re-release it...

**Comment by raysan5** [comment]
re-released! :)

**Comment by jubalh** [comment]
Should that really be `/usr/lib64/libraylib.so.301`?
Before we had:

```
libraylib.so.2                                                                                                                                                                
libraylib.so.2.5.0
```

Which looks good to me. Like any other project I'm aware of does it too. But not sure why we would want 301 instead of 3.

**Comment by raysan5** [comment]
@jubalh actually that's how it was configured in CMake by @a3f.

I can remember the logic behind it right now...

**Comment by jubalh** [comment]
It would be good if you do not remove the 3.0 tag once you tagged it and apply it to another commit.
People pull from that tag, create tarballs for distribution and try to include it in Linux distros.
They will end up with different states in such a case.

If you realize something needs to be fixed it would be good to create a new tag and release then. So 3.0.1, 3.0.2 etc.
Otherwise all systems that depend on you will get confused.

**Comment by raysan5** [comment]
@jubalh Oh, sorry, there are problems with `raylib.dll` on Windows and I'm working on them to release a fully working 3.0. Is it possible to wait for a while before pulling tags? Or it is an automatic process?

**Comment by jubalh** [comment]
Yes I stopped the pulling. But it would be better practise to just tag it as beta release or increase the last number :)
Since it might be that others rely on the tag too (from who we don't know and who maybe don't check the bug tracker).

**Comment by raysan5** [comment]
@jubalh is it ok if I keep the release but I update the attachments? It's a problem with the DLL building...

**Comment by jubalh** [comment]
Well just do as you like :)
Please ping me here once everything is finished, then I'll update :)

**Comment by raysan5** [comment]
@jubalh Current `raylib 3.0` is final, I'm not deleting or re-tagging it. 

Just note that `raylib-3.0.0-Win64-mingw.zip` attachment dll is not working properly and I'll try to re-upload that attachment at some point.

**Comment by jubalh** [comment]
Okay but in case you change anything, for exmaple the so name. Please create a new tag and dont remove/add the 3.0.0 one. Because I will submit to official repos now.

**Comment by raysan5** [comment]
@jubalh ok, no worries.

**Comment by a3f** [comment]
> Should that really be /usr/lib64/libraylib.so.301?

It should be `libraylib.so.300` for the release and after the tagging, it should be `libraylib.so.301`, so binaries linked against the release raylib aren't [accidentally paired with a development or later released raylib this may be incompatible](https://github.com/raysan5/raylib/pull/862).

> Like any other project I'm aware of does it too. But not sure why we would want 301 instead of 3.

Every raylib release adds breaking changes, so we will be incrementing the number on every release anyway.

 Instead of counting up and ending up with `raylib.so.16` for `raylib.so.4.2`, I decided just multiplying by 100 is the most readable, because it can be easily mapped to the official release versions.

**Comment by jubalh** [comment]
> Every raylib release adds breaking changes, so we will be incrementing the number on every release anyway.

If this is the case then it makes sense.

**Comment by jubalh** [comment]
BTW are the API breaking changes documented somewhere? This would make it much easier for developers to migragte from one raylib version to the next.

**Comment by raysan5** [comment]
@jubalh CHANGELOG details all the functions added, removed or reviewed
