### ISSUE TITLE
[build] raylib v3.0 release dlls compiled with DEBUG data

### ISSUE THREAD

**Issue by Guevara-chan** [raysan5/raylib#1164]
Got following on some Win10 (all x64) systems when updating my project to latest version of raylib:
 ![image](https://user-images.githubusercontent.com/8768470/78045129-3de96180-737e-11ea-8922-91395bf06d61.png)

Project itself is here if it matters: https://github.com/Guevara-chan/Midday-Commander
No issues with old 2.6.0. What could it be ?

**Comment by raysan5** [comment]
@Guevara-chan are you getting those problems with DLL downloaded from release 3.0? only with 64 bit version? mingw or msvc compilation? debug or release version? did you try compiling library yourself from master branch?

**Comment by Guevara-chan** [comment]
Windows, x64, MinGW. Release. I got no such problems at all (!), but three of my users\testers did.

**Comment by raysan5** [comment]
@Guevara-chan I'm trying to verify it right now but I'd need more info... also library name should be `raylib.dll` instead of `libraylib.dll` I think.

**Comment by Guevara-chan** [comment]
Actually, it *is* `libraylib.dll` in *your* MinGW distro.

**Comment by raysan5** [comment]
@Guevara-chan yes, sorry, I was confused... I didn't setup the automatic build pipeline for the attachments.

In any case, it works for me and also asked on raylib Discord and one user tested and veryfied both libraries work ok on Windows 10 64bit (MinGW, MSVC). Not sure what it could be related to...

Did you try building the library yourself?

**Comment by Guevara-chan** [comment]
I have an idea. Could your testers test this version of my app (raylib 3.0 powered) ? [Midday Commander.zip](https://github.com/raysan5/raylib/files/4410993/Midday.Commander.zip)
Once again: it works for me, but not my users (testers).

> Did you try building the library yourself?
Not yet. I prefer stable releases.

**Comment by raysan5** [comment]
@Guevara-chan program doesn't work in my computer neither.

I checked multiple DLLs with `dumpbin` tool:

`libraylib.dll v2.6 64bit MinGW`

```
Dump of file C:\Midday.Commander\libraylib.260.mingw.dll

File Type: DLL

  Summary

        1000 .CRT
       22000 .bss
        5000 .data
        6000 .debug_abbrev
        1000 .debug_aranges
       1D000 .debug_frame
      157000 .debug_info
       2D000 .debug_line
        2000 .debug_ranges
        A000 .debug_str
       15000 .edata
        3000 .idata
        9000 .pdata
       33000 .rdata
        1000 .reloc
      133000 .text
        1000 .tls
        9000 .xdata
```
`libraylib.dll v3.0 64bit MinGW`

```
Dump of file C:\Midday.Commander\libraylib.300.mingw.dll

File Type: DLL

  Summary

        1000 .CRT
        A000 .bss
        9000 .data
        8000 .debug_abbrev
        1000 .debug_aranges
       1C000 .debug_frame
      1C4000 .debug_info
       2C000 .debug_line
      18B000 .debug_loc
       3E000 .debug_ranges
        C000 .debug_str
       11000 .edata
        3000 .idata
        6000 .pdata
       31000 .rdata
        1000 .reloc
       C7000 .text
        1000 .tls
        7000 .xdata
```
`libraylib.dll v3.0 64bit MSVC`
```
Dump of file C:\Midday.Commander\libraylib.300.msvc.dll

File Type: DLL

  Summary

        1000 .00cfg
       6D000 .data
        1000 .gfids
        3000 .idata
        A000 .pdata
       40000 .rdata
        4000 .reloc
        1000 .rsrc
      19F000 .text
        1000 .tls

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin>
```

It seems MinGW DLLs are compiled with DEBUG information on it, compilation was reviewed by @a3f some days ago for a related issue https://github.com/raysan5/raylib/issues/1128, despite it referes to MSVC.

We need to review this behaviour to compile RELEASE DLL versions for `libraylib.dll`.

In the meantime, you can use DLL provided for MSVC 64bit, just rename it to `libraylib.dll`, I tested it and it works ok.

**Comment by raysan5** [comment]
It seems problem resides here:

![raylib_dll_issue](https://user-images.githubusercontent.com/5766837/78124178-9a489180-740f-11ea-8b01-6f4594c1138f.PNG)

For some reason `libraylib.dll` 64bit is generated with that MinGW dependency. I'm looking how to remove it... but it could take some time. Use MSVC library in the meantime.

**Comment by TSnake41** [comment]
You can use `-static` to remove the dependency of any library that are statically available.
This is the way raylua is built on MinGW.

**Comment by raysan5** [comment]
@TSnake41 yeah, thanks, I know, I do it with my plain `Makefile` but Release attachments are generated through CMake and AppVeyor CI build system and I'm not an expert on that...

Anyway, I manually updated the following libraries:

 - raylib-3.0.0-Win32-mingw
 - raylib-3.0.0-Win32-msvc15
 - raylib-3.0.0-Win64-msvc15

I'll try to also review `raylib-3.0.0-Win64-mingw` at some point but I need time to investigate it...

**Comment by a3f** [comment]
The debugging info is expected. It's optimized for release, but still contains debugging symbols in separate sections for use by a debugger. The issue shown by Dependency Walker seems to be the culprit. I have no idea what to do about it though. Haven't been doing Windows development for quite a while.

**Comment by codz01** [comment]
also seems you didn't strip the dll 
try : strip libraylib.dll , this will remove 300kb !

**Comment by raysan5** [comment]
This issue is already on track, it should be corrected with the new CD system.
