### ISSUE TITLE
[raylib] dll names should be standardized

### ISSUE THREAD

**Issue by rishavs** [raysan5/raylib#1166]
### Issue description

the mingw build has the `libraylib.dll` in the bin folder.
However, for msvc build, the name is `raylib.dll`

while this is a tiny inconvenience, it means that folks who use the dlls only (with some other language bindings) have to manual edit the dll name if they are switching the build variants.

My recommendation is to use the same name `libraylib.dll` for all build variants.

**Comment by raysan5** [comment]
@rishavs It seems those naming conventions come defined by the compiler and so are generated. 

Personally I don't like `libraylib.dll`, on my world only exist `raylib.dll`.

**Comment by a3f** [comment]
MSVC uses raylib.lib for static libraries. MinGW uses libraylib.a. Shoudl these be unified too? I see the different naming as a perk. You can readily see, what toolchain something was compiled with..
