### ISSUE TITLE
[core] Double input when calling GetKeyPressed() on RPI

### ISSUE THREAD

**Issue by gezzuzz** [raysan5/raylib#1167]
Im writing a program to run on RPI.
I made a custom linux build using buildroot (10 sec boot)
I boot into command prompt and run my program.
Raylib works great without a window environment.
I develop on windows then cross compile to the RPI

Everything crosses over from windows platform to RPI perfectly
The only issue i have is with GetKeyPressed  on the RPI.

If i type  'a' i get 'A' then  'a'
if i type '1' i get '1' then '1'
if i type '!' i get '1' then '!'

its like i get the primary function of the key.. then the key i pressed.

if i hold down 'a'.. i get 'A' 'a' -pause- 'a' 'a' 'a' 'a' 'a' 'a' 'a'
so the repeat key is working fine.

when i type 'a' i get 'A' 'a' 85% of the time
i get 'a' correctly about 10% of the time
and i only get 'A' around 5%.

Im only calling GetKeyPressed once per frame (30fps)

if i was getting the same key twice ('a' 'a') it would make since i need to de-bounce.
how its getting the 'A' when im typing 'a' baffles me. 

When using the text_box_input example i get the same thing.

today i complied the latest version and it still happens.

have you seen anything like this before? 
Thank you

**Comment by gezzuzz** [comment]
seems to me that key presses are being handled twice.. in PollInputEvents and ProcessKeyboard

both adds key the keyPressedQueue..

going to look more into it tomorrow

**Comment by raysan5** [comment]
@gezzuzz that's possible... I think `ProcessKeyboard()` was called on `PollInputEvents()` but later moved to own thread... not sure but...

**Comment by gezzuzz** [comment]
in EventThread of core.c @ line 5066 there is a block of code that was commented out and replace code that adds key to the queue. If i comment out line 5078-5083 it eliminates the double key issue. it seems its not needed.

**Comment by chriscamacho** [comment]
sorry to bust in with something not directly related to the issue but I couldn't find any contact info for @gezzuzz 

I not you are using buildroot, did you know can make a read only OS with it (something that it can be hard to configure regular distros to do)

This means you can just pull the power at any time and not hose you OS (found it to be robust too) this means a finished application like a clock or display, can be switched on / off by a none technical user without hosting it and will also survive power outages...

couple it with raylib it can make a great custom shop window display $$$ !

**Comment by raysan5** [comment]
@gezzuzz feel free to send a PR with the review. :)

@chriscamacho it would be very nice to see some tutorial/example on raylib-buildroot integration. :)

**Comment by gezzuzz** [comment]
> @gezzuzz feel free to send a PR with the review. :)
> 
> @chriscamacho it would be very nice to see some tutorial/example on raylib-buildroot integration. :)

i will do a PR when im convinced it fixed the issue and not cause another...

i was planning to do a start to finish build root setup for using raylib.. the first time took me days to build it right.. but once i got it to work its great.. you can boot into a raylib app in about 10-15secs..

**Comment by raysan5** [comment]
> i will do a PR when im convinced it fixed the issue and not cause another...

That's very nice! Thank you!

 > i was planning to do a start to finish build root setup for using raylib.. the first time took me days to build it right.. but once i got it to work its great.. you can boot into a raylib app in about 10-15secs..

Really waiting for that tutorial! :D

**Comment by danimartin82** [comment]
Also interested!! :-)

**Comment by raysan5** [comment]
@gezzuzz any progress on this issue?
