### ISSUE TITLE
[build] Error on compilation with VSCode on Linux

### ISSUE THREAD

**Issue by grevius5** [raysan5/raylib#1169]
I followed the instruction for make compilation and for VSCode IDE project, but when I try to start the debug I have this error:
`/game: error while loading shared libraries: libraylib.so.301: cannot open shared object file: No such file or directory`

The file is missing in the `raylib/src folder`. If I start the `raylib/projects/scripts/build-linux.sh` the compilation work and I can start the game. I don't understand what I'm missing.

**Comment by raysan5** [comment]
@grevius5 maybe libraries are not in the path for `game`?

**Comment by raysan5** [comment]
It seems a path configuration issue on the user side. Closing it.
