### ISSUE TITLE
[core] Assert in InitWindow()

### ISSUE THREAD

**Issue by danimartin82** [raysan5/raylib#1174]
Environment: Tested agains raylib 3.0 from master branch, commit:
```
commit 6a8b1079c13b7d5e1bddc0ecc86ad7e16fc2556d (HEAD -> master, tag: 3.0.0, upstream/master, origin/master, origin/HEAD)
Author: Ray <raysan5@gmail.com>
Date:   Mon Mar 30 23:42:17 2020 +0200
    Update project version for release
```

### Issue description
I'm still working on the tests of raylib functions. testing different arguments for this function:

`void InitWindow(int width, int height, const char *title)`

So far I found that this function generates asserts in `glfw/src/window.c`, for negative numbers of width or height, and for NULL titles.

Is assert the best reaction? Perhaps raylib coud check these parameters before passing them to glfw and change to a default values if they are not valid.

### Environment

Compiled for PLATFORM_DESKTOP, , WINDOWS, RELEASE mode, STATIC library using Min GW, OpenGL 3.3

### Issue Screenshot
![image](https://user-images.githubusercontent.com/32535596/78458679-79a06600-76b3-11ea-964b-97977f9d5539.png)

![image](https://user-images.githubusercontent.com/32535596/78458720-c71cd300-76b3-11ea-854c-5b4c74399d71.png)

### Code Example
This is the code in glfw that generate the asserts:

![image](https://user-images.githubusercontent.com/32535596/78458765-2aa70080-76b4-11ea-9f7c-d0e29d579037.png)

**Comment by louisgjohnson** [comment]
> Is assert the best reaction? Perhaps raylib coud check these parameters before passing them to glfw and change to a default values if they are not valid.

I think asserting when there's an error is important, helps prevent bugs down the line

**Comment by raysan5** [comment]
@danimartin82 @louisgjohnson I also prefer let GLFW warn the user about this problem. 

Actually, you will find in raylib many places were user can pass wrong data to the library, from my point of view, I can try to make life easier to the user but I'm not checking for all missuses of coding.

Like I teach to my students, they should be responsible of the data they manage. Crashing the app (or not) it's on their hands. **Watch your data!**
