### ISSUE TITLE
[audio] Please inform users what types can be opened as Music

### ISSUE THREAD

**Issue by PapyChacal** [raysan5/raylib#1175]
- [X] I tested it on latest raylib version from master branch
  Used both 3.0.0 and master.
 - [X] I checked there is no similar issue already reported
  I feel it could be related to #957 ?
 - [X] My code has no errors or misuse of raylib

### Issue description

  Okay, I was wondering why I can't open my WAV files as Music objects.
  After some searching, building this minimal example and everything, I checked for similar issues to be sure and found #48.
  It would be nice to inform the user of this specificity !
  Beyond that, your lib looks really nice, I'm using raudio only as I'm stuck with SDL2 for a student's project, but I'm looking forward to try the rest of it ! 

### Environment

  I'm using Ubuntu 18.04, GCC 7.5.0 targetting x86_64-linux-gnu
  I don't know what else is relevant to the issue ?

### Issue Screenshot
```
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:      miniaudio / PulseAudio
INFO:     > Format:       32-bit IEEE Floating Point -> 16-bit Signed Integer
INFO:     > Channels:     2 -> 2
INFO:     > Sample rate:  44100 -> 44100
INFO:     > Periods size: 1320
INFO: AUDIO: Multichannel pool size: 16

Try to open as a Sound
INFO: WAVE: [music.wav] File loaded successfully (44100 Hz, 16 bit, Stereo)
INFO: WAVE: Unloaded wave data from RAM
INFO: WAVE: Unloaded sound data from RAM

Try to open as a Music
WARNING: FILEIO: [music.wav] Music file could not be opened
INFO: STREAM: Unloaded audio stream data from RAM

Try to open as a Sound
INFO: WAVE: [shoot.wav] File loaded successfully (44100 Hz, 16 bit, Stereo)
INFO: WAVE: Unloaded wave data from RAM
INFO: WAVE: Unloaded sound data from RAM

Try to open as a Music
WARNING: FILEIO: [shoot.wav] Music file could not be opened
INFO: STREAM: Unloaded audio stream data from RAM
INFO: AUDIO: Device closed successfully
```

### Code Example

```
#include "stdio.h"
#include "raudio.h"

int main()
{
    InitAudioDevice();
    printf("\nTry to open as a Sound\n");
    Sound sound = LoadSound("music.wav");
    UnloadSound(sound);

    printf("\nTry to open as a Music\n");
    Music music = LoadMusicStream("music.wav");
    UnloadMusicStream(music);

    printf("\nTry to open as a Sound\n");
    Sound sound2 = LoadSound("shoot.wav");
    UnloadSound(sound2);

    printf("\nTry to open as a Music\n");
    Music music2 = LoadMusicStream("shoot.wav");
    UnloadMusicStream(music2);


    CloseAudioDevice();
    return 0;
}
```

**Comment by louisgjohnson** [comment]
Added a [PR](https://github.com/raysan5/raylib/pull/1176) for this to help throw a warning in the console

**Comment by PapyChacal** [comment]
Thanks ! I'd rather output what formats are actually supported though, but I get that it can be more complicated.

**Comment by raysan5** [comment]
@louisgjohnson Reviewed your PR formatting.

@PapyChacal Actually, it's on the list to support WAV as streaming file format...

**Comment by raysan5** [comment]
Comment added by @louisgjohnson
