### ISSUE TITLE
[textures] Text/shapes don't appear in RenderTexture unless rendered twice (new in 3.0)

### ISSUE THREAD

**Issue by Andrew-Maxwell** [raysan5/raylib#1179]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I was trying to render a large amount of text to a RenderTexture. In the original example, the first half of the text did not appear but the second half did. On the second attempt (after reloading the level) all of the text appeared.

In a minimal example, I tried to draw text and some rectangles. If I ran the code once, only the first letter of the text appeared. After running the code twice, everything appeared.

Downgrading to 2.6 resolved the issue.

### Environment

original issue mentioned: Replicated under Desktop, Windows 10 and Ubuntu, OpenGL 3.3, Intel HD 5500 + one friend also saw same issue under Windows.
minimal example: Replicated under Desktop, Ubuntu, OpenGL 3.3, intel HD 5500 + on one other person's PC

### Issue Screenshot

If rendered once:

![image](https://user-images.githubusercontent.com/8117119/78509562-a4d29600-7743-11ea-89c1-4a5320da5b01.png)

If rendered twice:

![image](https://user-images.githubusercontent.com/8117119/78509553-91bfc600-7743-11ea-8244-45f67568b452.png)

### Code Example

https://hastebin.com/odepogevoj.cpp

**Comment by louisgjohnson** [comment]
@Andrew-Maxwell the link to the code doesn't seem to load

**Comment by raysan5** [comment]
@Andrew-Maxwell please, could you provide a short code sample illustrating the issue? I tested `shaders_custom_uniform` and it seems to work ok.

**Comment by Andrew-Maxwell** [comment]
That's weird, I think it's an issue with Hastebin. Anyway, here's the code:

`#include <raylib.h>
#include <iostream>

using namespace std;

class textureTester {

    RenderTexture2D renderTex;

    public:

    void init(string text) {
        renderTex = LoadRenderTexture(300, 300);
        BeginTextureMode(renderTex);
        ClearBackground((Color){0, 0, 0, 0});
        DrawText(text.c_str(), 150, 150, 20, BLACK);
        DrawRectangle(0, 0, 10, 10, RED);
        DrawRectangle(0, 290, 10, 10, BLUE);
        DrawRectangle(290, 0, 10, 10, GREEN);
        DrawRectangle(290, 290, 10, 10, PURPLE);
        EndTextureMode();
    }

    textureTester(string text) {

        //If init is only called once, only the "h" in "hello world" displays.

        init(text);
        init(text);
    }

    void print() {
        DrawTexture(renderTex.texture, 300, 300, BLACK);
    }
};

int main(int argc, char** argv) {

    InitWindow(1600, 900, "Texture Test");
    SetTargetFPS(60);

    textureTester t("hello world");

    while(!WindowShouldClose()) {

        BeginDrawing();
        ClearBackground(WHITE);
        t.print();
        EndDrawing();
    }
}`

**Comment by raysan5** [comment]
Hi @Andrew-Maxwell, I verified the issue... very weird!

I created a simpler example that works ok:

```c
#include "raylib.h"

int main(void)
{
    InitWindow(800, 450, "raylib render texture issue");
    RenderTexture2D target = LoadRenderTexture(300, 300);

    // WARNING: Draw to texture does not work properly here!

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second

    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        BeginDrawing();
        
            // Drawing to texture works ok here
            BeginTextureMode(target);
                ClearBackground(BLANK);
                DrawText("Hello World!", 90, 150, 20, BLACK);
                DrawRectangle(0, 0, 10, 10, BLUE);
                DrawRectangle(0, 290, 10, 10, BLUE);
                DrawRectangle(290, 0, 10, 10, GREEN);
                DrawRectangle(290, 290, 10, 10, PURPLE);
            EndTextureMode();

            ClearBackground(RAYWHITE);
            DrawTexture(target.texture, 0, 0, WHITE);

        EndDrawing();
    }

    UnloadRenderTexture(target);
    CloseWindow();

    return 0;
}
```

I need to investigate it...

**Comment by raysan5** [comment]
Ok, found it and corrected the issue. 

This is tha kind of issue that can drive you crazy... no compile errors, everything apparently working... very weird result on drawing depite everything being correctly processed... it was hard...
