### ISSUE TITLE
[build] VS2017.UWP project not working

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1182]
UWP raylib project is not working (`PLATFORM_UWP`), it should be reviewed.

This project was interesting to develop with raylib for multiple Windows platforms, including `Xbox One`.

**Comment by raysan5** [comment]
I'm investigating this issue. Programs crashes on first `glGetString()` call on `rlglInit()`, it means OpenGL context is not properly created or bound to graphic device. Related function: `InitGraphicsDevice()`

**Comment by raysan5** [comment]
@Rover656 please, could you help with this issue? I tried debugging but it crashes on initialization, it seems issue is on `Windows::UI::Core::CoreWindow^ window` but I can't find it... Thanks! :)

**Comment by Rover656** [comment]
I shall investigate this issue and will get back to you! There's a couple other UWP things I'll also look into to try and polish it up a bit!

**Comment by raysan5** [comment]
@Rover656 Nice! Thank you very much! :D
