### ISSUE TITLE
Memory leak on intel gpu drivers

### ISSUE THREAD

**Issue by XZ02R** [raysan5/raylib#1185]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When testing my game on another system, I noticed that the memory usage was steadily increasing and discovered that there was a memory leak.

I then set up a minimal raylib example to check if the issue was with the game or raylib and discovered that raylib appears to be leaking on certain gpu drivers.

### Environment

The system where the issue occurs
>Compiler: gcc 9.3.0-1
Platform: x86_64 Linux
CPU: Intel i5-5200U (4) @ 2.700GHz
GPU: Intel HD Graphics 5500
Kernel: 5.6.2-arch1-2
Raylib: 3.0.0-1

>OpenGL Info:
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.4
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.4
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

The second system where the leak does not occur
>Compiler: gcc 9.3.0-1
Platform: x86_64 Linux
CPU: Intel i5-6600K (4) @ 4.300GHz
GPU: AMD ATI Radeon RX 480
Kernel: 5.6.2-arch1-2
Raylib: 3.0.0-1

>OpenGL Info:
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.36.0, 5.6.2-arch1-2, LLVM 9.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.4
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.4
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

### Issue Screenshot
Leak test on the problem system
```
$ g++ -fsanitize=address -fno-omit-frame-pointer -lraylib leak_test.cc -o leak_test
$ ./leak_test
INFO: Initializing raylib 3.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  640 x 480
INFO:     > Screen size:  640 x 480
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 20.0.4
INFO:     > GLSL:     4.60
INFO: GL: Supported extensions count: 208
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Internal vertex buffers uploaded successfully to VRAM (GPU)
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 1] Unloaded default texture data from VRAM (GPU)
INFO: Window closed successfully

=================================================================
==7329==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 2 object(s) allocated from:
    #0 0x7f860ca7bd48 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f8607f6d65c  (/usr/lib/dri/iris_dri.so+0xb8665c)

SUMMARY: AddressSanitizer: 128 byte(s) leaked in 2 allocation(s).
```

Same test on the second system

```
$ g++ -fsanitize=address -fno-omit-frame-pointer -lraylib leak_test.cc -o leak_test
$ ./leak_test
INFO: Initializing raylib 3.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  640 x 480
INFO:     > Screen size:  640 x 480
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   X.Org
INFO:     > Renderer: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.36.0, 5.6.2-arch1-2, LLVM 9.0.1)
INFO:     > Version:  4.6 (Core Profile) Mesa 20.0.4
INFO:     > GLSL:     4.60
INFO: GL: Supported extensions count: 221
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: GL: Mirror clamp wrap texture mode supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Internal vertex buffers uploaded successfully to VRAM (GPU)
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 1] Unloaded default texture data from VRAM (GPU)
INFO: Window closed successfully
```

### Code Example

```
#include "raylib.h"

int main()
{
         InitWindow(640, 480, "RayLib Dev");
         CloseWindow();
         return 0;
}
```

**Comment by chriscamacho** [comment]
I can't replicate this on my own Intel system (I even added a malloc without free to check asan was actually working!)

its not uncommon for some drivers to leak or at least *appear* to leak

are you using the old xf86-video-intel driver or the newer mode setting / glamor driver ?

as long as the leak is happening in iris_dri.so I don't see how this is an issue with raylib, you're likely to see the same issue with code directly accessing mesa (opengl)

**Comment by XZ02R** [comment]
I was using the xf86-video-intel drivers. I've just removed the drivers and cleared all files from /etc/X11/xorg.conf.d to switch to modesetting but the issue still persists.

**Comment by raysan5** [comment]
@XZ02R Would it be possible you test it on Windows to check if it also happens?

Is it possible to detect with more precission where the leaks happens?

**Comment by ibilon** [comment]
You can hide those unfixable "leaks" using the following env var when running your game:
```
LSAN_OPTIONS="suppressions=file.txt" ./mygame
```
and in file.txt:
```
leak:iris_dri.so
```

Keep in mind that ASAN only detects unfreed memory not necessarily leaks.

**Comment by chriscamacho** [comment]
@XZ02R are you seeing a continuous leak, or just 1 off unfree'd memory

for example if you sit in a loop monitoring memory usage, is it continuously increasing ?

do you always see the same amount of unfree'd memory with a number of different examples on exit?

**Comment by XZ02R** [comment]
[valgrind-out.txt](https://github.com/raysan5/raylib/files/4456496/valgrind-out.txt)
@raysan5 I don't have access to a windows machine at the moment. I'm not sure how to detect with more precision, but I've attached a valgrind log.

@chriscamacho After testing with all of the examples on raylib's site, it seems to be a one off leak. Is it fine to just ignore this and just dev away?

**Comment by ibilon** [comment]
If it's just a single allocation then it's fine, not much you can do about it anyway.

And that's not really a leak, the OS will get back every single bit of memory the application has requested, whether it freed it or not, so don't worry about it ;)

**Comment by chriscamacho** [comment]
@XZ02R its fine, the iris driver (modesetting / glamor) on my current hardware happens not to leak at all (I thought libasan had stopped working!) 

On a 5th gen laptop my previous laptop it always leaked exactly the same amount, regardless what I was doing (some 4000 or so bytes!!  )

however a modern OS like Linux is very good at releasing everything after an app has quit

You have an urgent issue if there is a leak every frame and the allocation is always increasing - sooner or later things will slooow to a crunch!

so yes if its a consistent amount regardless of run time - ignore - it code on - you have other things to fix! 

I find valgrind particularly unhelpful, do look at the gcc instrumentation - you can check for many other things and as @ibilon says you can suppress issues very easily - you can with valgrind but its a thundering pita !!!

I tend to use the following flags but you might find others useful

```
INSTR:= -fsanitize=address,leak,undefined,pointer-compare,pointer-subtract
INSTR+= -fno-omit-frame-pointer
```

I have a debug rule like so

```
.PHONY: debug release
debug: CFLAGS+= -g $(INSTR)
debug: LDFLAGS+= $(INSTR)

debug release: clean $(APPNAME)
```

**Comment by raysan5** [comment]
@ibilon @chriscamacho thanks for helping with this issue.

@XZ02R I'm closing it for now.
