### ISSUE TITLE
[core] No way to open a screen that matches display size automatically

### ISSUE THREAD

**Issue by alanbork** [raysan5/raylib#1186]
Please, before submitting a new issue verify and check:

 - [x ] I tested it on latest raylib version from master branch
 - [x ] I checked there is no similar issue already reported
 - [x ] My code has no errors or misuse of raylib

### Issue description

I can't figure out a way to open a screen that exactly matches the display size other than hard coding it. 

### Environment

Pi Zero

### Code Example

 InitWindow(GetMonitorWidth(0), GetMonitorHeight(0), "1 to 1 mapping");

**Comment by raysan5** [comment]
@alanbork Sorry, not sure if I understand the issue...

`GetMonitorWidth(0)` and `GetMonitorHeight(0)` require a previously initialized Window to work.

In any case if you use `InitWindow(0, 0, "title")`, it should use monitor display size automatically.

**Comment by alanbork** [comment]
That doesn't work either, though it would be the optimal way to provide the desired outcome.

This code:  InitWindow(0, 0, "raylib [core] example - generate random values");

The result:

INFO: Initializing raylib 3.0
INFO: DISPLAY: Upscaling required: Screen size (0x0) smaller than display size (1920x1200)
WARNING: DISPLAY: Failed to attach EGL rendering context to EGL surface
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 0] Unloaded default texture data from VRAM (GPU)
INFO: Window closed successfully

**Comment by chriscamacho** [comment]
try opening a nominal sized window, say 1024x768 or similar (something you know will work)
Then you can get the monitor size and call

SetWindowSize

You will need to allow space for tool bars and the window decoration (which using xlib is doable but a pain...) no idea how you'd get the info from windows or macos

What I tend to do for fullscreen mode is to render to a texture at half HD 1280x720 and then scale that to whatever resolution fullscreen happens to be (usually looks fine on a HD screen laptop right next to my face!)  see the example core_window_letterbox

**Comment by raysan5** [comment]
@alanbork Actually using the maximum display size when `InitWindow(0, 0, "title")` is the default behaviour on desktop. 

It seems an issue with Raspberry Pi code... are you running it without X11 (`PLATFORM_RPI`)?

**Comment by raysan5** [comment]
Ok, just reviewed it on commit https://github.com/raysan5/raylib/commit/d419602c99480a69aa3eef0b074bc15f2aa6e413. Please, @alanbork could you test it?

**Comment by alanbork** [comment]
Works like a charm now, thanks!

InitWindow(0, 0, "title")

NFO: Initializing raylib 3.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1200
INFO:     > Render size:  1920 x 1200
INFO:     > Screen size:  1920 x 1200
INFO:     > Viewport offsets: 0, 0
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: VideoCore IV HW
INFO:     > Version:  OpenGL ES 2.0
INFO:     > GLSL:     OpenGL ES GLSL ES 1.00

**Comment by pkeir** [comment]
I am working with a very high resolution screen, but my users have a much lower resolution. I would like us all to use a screen which fills the same proportion of the screen. Is it possible to open a window which is say half the width and height of the screen/monitor?

**Comment by justgo97** [comment]
> I am working with a very high resolution screen, but my users have a much lower resolution. I would like us all to use a screen which fills the same proportion of the screen. Is it possible to open a window which is say half the width and height of the screen/monitor?
you can do `InitWindow(0, 0, "title")` then `SetWindowSize(GetMonitorWidth(GetCurrentMonitor())/2, GetMonitorHeight(GetCurrentMonitor())/2);`

Not sure if currently there is any other way to do it in Raylib since `GetMonitorWidth` and `GetMonitorHeight` only work after calling `InitWindow`
