### ISSUE TITLE
[core] Measuring when vsync occurs and scannout starts 

### ISSUE THREAD

**Issue by alanbork** [raysan5/raylib#1187]
I'm working on a tool for measuring input lag on TVs and other display devices. I'd like to know when vsync has happened (or even access the current scanline, but I realize that might be well beyond the scope of raylib). My best guess from reading the sources is that vsync should occur close to when   EndDrawing(); returns. But in the source there's definitely some additional processing going on (reading the input devices, for instance), which would presumably mean endrawing returns post-vsync. But best i can determine on a display with known lag is that EndDrawing(); is returning well before vsync.  Is there any function, data structure (internal or otherwise) that I can access to determine when the last vsync occured? I'm not opposed to editing the source directly to get what I want though this seems like it could be useful for other users of raylib as well.

**Comment by danimartin82** [comment]
Hi there! As far as I know, Vsync and scanline are concepts more related to analog video, not sure how to apply in high level graphic library.... 
Anyway, you can try measure the time when the GPU outputs the frame. I'm not an expert in OpenGL....but I think It should be somewhere inside `rlglDraw()` function, that its called from `EndDrawing()`....

**Comment by alanbork** [comment]
hdmi, for instance, has both vsync and scanlines - it's the point in time that the data for the next frame is sent over the cable to the display, and what percentage of that data has been sent. opengl (full not es) includes a function for extracting it.

**Comment by raysan5** [comment]
@alanbork I think it's up to the graphic driver to manage that, as much as I con do through the API is trying to enable VSync using `FLAG_VSYNC_HINT` but even on that case is up to the driver to enable it or not.

What is the OpenGL function to get Vsync information?

**Comment by danimartin82** [comment]
I found this information, hope it's useful:
https://stackoverflow.com/questions/589064/how-to-enable-vertical-sync-in-opengl

**Comment by alanbork** [comment]
Here's one way determine what's going on with the vertical refresh.  I'm guessing the GLX prefix means it's only available if you use X, and there's no OpenGL ES equivalent?

 https://www.khronos.org/registry/OpenGL/extensions/OML/GLX_OML_sync_control.txt

Another option:

https://www.khronos.org/registry/OpenGL/extensions/SGI/GLX_SGI_video_sync.txt
(and people do use it: https://codereview.chromium.org/11359114/)

**Comment by raysan5** [comment]
@alanbork Those extensions are platform dependant  and belong to the platform libraries (`WGL/GLX/CGL/EGL`) that initialize the different display devices for the OpenGL context.

I investigated a bit and also exist `WGL_OML_sync_control` (Windows) and `EGL_CHROMIUM_sync_control` (HTML5, Chrome only). That functionality is very platform dependant and the extension is not always available... it seems a very specific user case.

Despite in raylib I'm checking extensions manually for some platforms and even initializing display device manually (`EGL` - RPI, HTML5, Android, UWP), I'm afraid supporting those extensions and exposing functionality it's out of scope for the library.

**Comment by alanbork** [comment]
Thanks for looking into it! 

FYI I managed to find a reasonable work-around. First, I needed to write my own custom enddrawing that returns immediately after swapbuffer (see below). This, plus the realization that swapbuffer has to be called twice before it blocks until vsync for the first buffer (because of pipelining). This raises an issue: there doesn't seem to be a header I can include such that I can get access to SwapBuffers() or CORE.Time.current in my own main(). I had to modify core.c directly, which makes it a real pain to stay synced with upstream on github. Or am I missing something?

void EndDrawingAR(void)
{
    rlglDraw();                     // Draw Buffers (Only OpenGL 3+ and ES2)

    PollInputEvents();              // Poll user events
    SwapBuffers();                  // Copy back buffer to front buffer - blocks until vsync at the end of drawing the front buffer

    // Frame time control system
    CORE.Time.current = GetTime();
    CORE.Time.draw = CORE.Time.current - CORE.Time.previous;
    CORE.Time.previous = CORE.Time.current;

    CORE.Time.frame = CORE.Time.update + CORE.Time.draw;

}
