### ISSUE TITLE
[CORE] nanovg - fill issue

### ISSUE THREAD

**Issue by AlbertoFrancoDD** [raysan5/raylib#1188]
### Integration with nanovg does not fill properly
I am trying to integrate nanovg with raylib, I am able to use the library to draw strokes but when it comes to filling it seems like the stencil buffer does not work properly. I manually enable stencil test before starting to render to my target framebuffer. Am I missing something? Is raylib changing some OpenGL state within the BeginTextureMode()? I looked for an example of integration but did not find any. 

```C++
   glEnable(GL_STENCIL_TEST);
    CHECK_ERROR();

    glViewport(0, 0, (GLsizei)Width, (GLsizei)Height);
    CHECK_ERROR();

    BeginTextureMode(m_renderTarget);
    float w = static_cast<float>(Width);
    float h = static_cast<float>(Height);

    glClearColor(1.0, 1.0, 1.0, 1.0);
    CHECK_ERROR();

    glClear(GL_COLOR_BUFFER_BIT | GL_STENCIL_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    CHECK_ERROR();


    nvgBeginFrame(m_context, w, h, w/h);
    CHECK_ERROR();
```
I am running on windows with a GTX 1050 and Intel i7.

**Comment by raysan5** [comment]
@AlbertoFrancoDD sorry, it's seems this issue is not directly related to raylib but nanovg.

**Comment by AlbertoFrancoDD** [comment]
I found out the problem. I was rendering to a FBO that has no stencil attachment (as per default), using the FBO infrastructure provided by nanovg worked fine.
