### ISSUE TITLE
raymath.h not found while it is actually there

### ISSUE THREAD

**Issue by acnologia000** [raysan5/raylib#1192]
Please, before submitting a new issue verify and check:

 - [no] I tested it on latest raylib version from master branch
 - [yes] I checked there is no similar issue already reported
 - [its compiling default example] My code has no errors or misuse of raylib

### Issue description

 i was trying to compile an example and compilation failed 

![image](https://user-images.githubusercontent.com/36767190/79037508-67608380-7bef-11ea-9b7f-ae6898553e7f.png)

with above message 

i did try looking for raymath.h and it is indeed present where raylib.h is but yet its being reported as not found while other examples that only use raylib.h are working as the should

### Environment

OS: windows 10
CPU : intel core i3 6100U
GPU :intel HD Graphics 520

![image](https://user-images.githubusercontent.com/36767190/79037418-4ea39e00-7bee-11ea-9a85-bc1661f9316f.png)

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example

shader_basic_lighting.c from examples

**Comment by raysan5** [comment]
@acnologia000 you can just copy `raymath.h` from `raylib/src` to the example directory.

**Comment by acnologia000** [comment]
thanks !
