### ISSUE TITLE
FF 75.0 on 64bit Linux: examples stop working after update

### ISSUE THREAD

**Issue by Toideng** [raysan5/raylib#1194]
Recently updated to a new version of Mozilla Firefox, and examples from the website stopped working (they used to work).

Console output:

![2020-04-11-140011_791x503_scrot](https://user-images.githubusercontent.com/37709930/79046157-bcf05c80-7bfe-11ea-96f5-f79eca1fbac1.png)

Console output in 'Safe mode' (restarted w/o extensions):

![2020-04-11-141455_792x208_scrot](https://user-images.githubusercontent.com/37709930/79046173-d5607700-7bfe-11ea-9082-95058764d3e8.png)

`about:config` search for `wasm` (in 'Safe mode'):

![2020-04-11-141148_637x515_scrot](https://user-images.githubusercontent.com/37709930/79046183-e1e4cf80-7bfe-11ea-86e0-bd4f47e0e6cf.png)

**Comment by ibilon** [comment]
I also have firefox 75 on linux, same wasm config, but for me the examples work.
To be sure does https://webglreport.com says that your browser support WebGL 1 & 2?

**Comment by chriscamacho** [comment]
I'm also running 75.0 on Linux 64bit too and its also working for me, if your using modesetting / glamor on newer hardware ensure you have the following environment variable set for webGL to work...

    export MESA_LOADER_DRIVER_OVERRIDE=iris

**Comment by Toideng** [comment]
> To be sure does https://webglreport.com says that your browser support WebGL 1 & 2?

Says "_This browser supports WebGL 2, but it is disabled or unavailable._"

Since it works for other FF 75.0 users, i'm closing issue --- it's probably just some random web stuff that will eventually go away

**Comment by ibilon** [comment]
Check in `about:config` that `webgl.enable-webgl2` somehow didn't set to `false`,
otherwise as @chriscamacho said it could be that your driver is blacklisted or something and disabling webgl2, I know chrome did that back when webgl2 was new.
