### ISSUE TITLE
[models] MeshTangents function crashes when used with GLTF or IQM models

### ISSUE THREAD

**Issue by GoldenThumbs** [raysan5/raylib#1200]
I've been encountering an issue on the latest version of RayLib where the function for generating mesh tangents (MeshTangents) crashes when called. The error I get in Visual Studio is "Critical error detected c0000374" which means that something (the mesh tangents in this case) is being written beyond the allocated memory (I believe this is called a heap corruption, please correct me if I'm wrong)

I'm on Windows 10 using Visual Studio 2019.
My GPU is a GTX 1660 TI and the OpenGL version is 3.3

Setting up any sort of basic 3D app in RayLib that loads models and calling MeshTangents should give this error. I've done it in the example code and gotten the error.

**Comment by raysan5** [comment]
@GoldenThumbs Just tried with `models_animation` example that loads an IQM file and it works perfectly. Please, could you provide a non-working example?

**Comment by GoldenThumbs** [comment]
@raysan5 So I just tried it with that model... And it worked... I'm going to check the blend file and see if it's set up differently. Someone should probably still see what's going on but feel free to either change the issue name or just close it altogether. I should also supply some screenshots and the whole debug output so there's a bit more information.

**Comment by raysan5** [comment]
@GoldenThumbs I'd need a non-working example to review it...

**Comment by raysan5** [comment]
As far as an example can not be provided I'm closing the issue.
