### ISSUE TITLE
[Question] modern VR/openxr

### ISSUE THREAD

**Issue by jeanahelver** [raysan5/raylib#1201]
VR seems to be no longer fully implemented apart from the core_vr_simulator example.
headsets have come a far way from the dk2
would it be possible to add functionality for openXR or openvr?

**Comment by raysan5** [comment]
@jeanahelver raylib does not support any specific VR technology, it just simulate VR stereo rendering with a pre-configures VR device parameters. You can provide any device parameters, by default it uses Oculus CV1 parameters.
