### ISSUE TITLE
[core] Invalid current key state in IsKeyDown() function

### ISSUE THREAD

**Issue by sikor666** [raysan5/raylib#1203]
When I press some key, IsKeyDown return false, because CORE.Input.Keyboard.currentKeyState[key] have value 2.

        // Update not work
        //----------------------------------------------------------------------------------
        if (IsKeyDown(KEY_D)) ballPosition.x += 2.0f;
        if (IsKeyDown(KEY_A)) ballPosition.x -= 2.0f;
        if (IsKeyDown(KEY_W)) ballPosition.y -= 2.0f;
        if (IsKeyDown(KEY_S)) ballPosition.y += 2.0f;
        //----------------------------------------------------------------------------------

// Detect if a key is being pressed (key held down)
bool IsKeyDown(int key)
{
    if (CORE.Input.Keyboard.currentKeyState[key] == 1) return true;
    else return false;
}

INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 1
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2
INFO:     > CORE.Input.Keyboard.currentKeyState[key]: 2

...

**Comment by raysan5** [comment]
@sikor666 that's very weird... key state should never be more than 1...

**Comment by sikor666** [comment]
@raysan5 I found in the documentation, it can be helpful:

https://www.kernel.org/doc/Documentation/input/input.txt

5. Event interface
~~~~~~~~~~~~~~~~~~

  'value' is the value the event carries. Either a relative change for
EV_REL, absolute new value for EV_ABS (joysticks ...), or 0 for EV_KEY for
release, 1 for keypress and 2 for autorepeat.

**Comment by raysan5** [comment]
@sikor666 Nice! Thank you very much for finding it! Actually I corrected the same issue for desktop a couple of weeks ago after a code tweak I did (changing `>=1` by `==1`). I didn't image issue will also pop-up on RPI side! Thanks! I'll review it asap!

**Comment by raysan5** [comment]
@sikor666 Reviewed. It should work know. Feel free to reopen if it does not.
