### ISSUE TITLE
raylib_source_compile  script?

### ISSUE THREAD

**Issue by Disflippant** [raysan5/raylib#1204]
I'm trying to compile raylib on windows following the instructions here:
https://github.com/raysan5/raylib/wiki/Working-on-Windows#build-example-using-notepad-script

Where do I get the raylib_source_compile script that needs to be run by NotePad++, as per the instruction?

**Comment by raysan5** [comment]
@Disflippant Whne you run a script with F6 in Notepad++, there is a dropdown box in the left-side corner where you can choose the script to run.

**Comment by Disflippant** [comment]
All it gives me is <temporary script>. No raylib_source_compile option. Are there additional plugin\files needed for NotePad++?

**Comment by raysan5** [comment]
@Disflippant did you use the raylib installer to install Notepad++?

**Comment by Disflippant** [comment]
No.  Windows is flagging it as having a virus (the same issue as https://github.com/raysan5/raylib/issues/1199). I've cloned the repo and was hoping to build from source.

**Comment by raysan5** [comment]
@Disflippant sorry, the scripts are setup on the Notepad++ version that comes with the installer. In that case you should build raylib manually using GitHub version. You can also use raylib/projects/VS2017 provided solution, it should work out of the box.

**Comment by Disflippant** [comment]
@raysan5 That's much easier! Thanks for the help.
