### ISSUE TITLE
[core] DrawTextureRec function

### ISSUE THREAD

**Issue by anatagawa** [raysan5/raylib#1206]
I use Raylib 3.0.

I would like to use **DrawTextureRec** , but have a problem , nothing is displayed at screen.

**Comment by raysan5** [comment]
hi @anatagawa, I just tried the function with latest master branch and it works ok on my side (Windows 10, MinGW). What is your configuration?

**Comment by anatagawa** [comment]
Oki, it's my fault, i compile the wrong raylib directory, sorry :D
