### ISSUE TITLE
[example] Wordwrap example doesn't work word wrap changes nothing

### ISSUE THREAD

**Issue by ZelCloud** [raysan5/raylib#1208]
The word wrap example doesn't seem to be working. Regardless if wordwrap is on or off word wrapping is always active within the red outlined textbox.

**Comment by raysan5** [comment]
Just tried it with latest raylib from github master and it works as expected.

**Comment by ZelCloud** [comment]
On the raylib web examples section word wrap "off" still does word wrapping on chrome at least.
https://www.raylib.com/examples/web/text/loader.html?name=text_rectangle_bounds
