### ISSUE TITLE
[core] Add GetKeyReleased() to mirror GetKeyPressed()

### ISSUE THREAD

**Issue by RobLoach** [raysan5/raylib#1209]
### Issue description

There is currently a `GetKeyPressed()` function which you can cycle through for all keys that were pressed. Would be great to have a `GetKeyReleased()` function to allow cycling through all keys that were released.

### Code Example
``` c
int key;
while (key = GetKeyReleased()) {
  TraceLog(LOG_INFO, "Key Released: %i, key);
}
```

**Comment by raysan5** [comment]
@RobLoach Actually that's a bit tricky... `GetKeyPressed()` stores up-to `MAX_CHARS_QUEUE` (16)  keys-down, it does not check for key state, should user should manage that part.

It means, you can get the keys down in a frame but you are responsible to check if they are still pressed on not in the next frame.

**Comment by RobLoach** [comment]
You're right, seems like it would be a tricky thing to get. Going to close this one for now and do more thinking.
