### ISSUE TITLE
[core] DrawLine() unexpected coord offsets in 32x32 compo

### ISSUE THREAD

**Issue by SemanticDevice** [raysan5/raylib#1213]
- [x] I tested it on latest raylib version from master branch
- [x] I checked there is no similar issue already reported
- [x] My code has no errors or misuse of raylib

### Issue description

DrawLine() starts and ends lines at unexpected coordinates. Furthermore, these coordinates are different between Linux and Windows build of the same test code.

Test code is using DrawLine() inside the texture drawing mode of the [raylib 32x32 compo template]( https://gist.github.com/chriscamacho/b5fefd42973d868bc2d8880351b7bf9f)

### Environment

- Linux Ubuntu 19.10 64-bit
- Windows 10 64-bit, built with mingw-w64 32-bit

### Issue Screenshot

Screenshots below are the result of the following code inside the texture drawing mode:

```C++
DrawLine(1, 1, 4, 1, WHITE);
DrawLine(3, 3, 3, 7, GREEN);
```
On Linux... Horizontal line starts at (1,1) but does not end at (4,1).  Vertical line does not start at (3,3), it is the correct length.

![Linux Screenshot](https://raw.githubusercontent.com/SemanticDevice/raylib_32x32_compo/master/line_test_linux.png)

On Windows... Horizontal line does not start at (1,1) and is not the right length. Vertical line starts at (3,3) but does not end at (3,7).

![Windows Screenshot](https://raw.githubusercontent.com/SemanticDevice/raylib_32x32_compo/master/line_test_windows.png)

### Code Example

https://github.com/SemanticDevice/raylib_32x32_compo/blob/master/line_test.c#L114

This repo pulls the latest raylib code as a git submodule. To test with the repo on Linux:

```shell
git clone https://github.com/SemanticDevice/raylib_32x32_compo.git
cd raylib_32x32_compo
git submodule update --init
cd submodules/raylib/src
make PLATFORM=PLATFORM_DESKTOP
cd ../../..
./build_line_test.sh
./line_test
```
On Windows, replace ```make``` with ```mingw32-make``` and ```build_line_test.sh``` with ```build_line_test.bat```.

**Comment by raysan5** [comment]
@SemanticDevice I'm afraid I can't do much here, it depends on the OpenGL graphic driver implementation... no easy solution, depending on the GPU and the OS behaviour will change.

**Comment by SemanticDevice** [comment]
I see. Thank you for the response. Closing the issue.
