### ISSUE TITLE
[textures] Optimize several Image*() functions

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1218]
Several `Image*()` functions are intended for image data transformation. Currently, most of those functions use `GetImageData()` to retrieve data from the `Image` to be transformed as an array of `Color` and after transformation use `LoadImageEx()` + `ImageFormat()` to reformat the data to the original image format. This is a simple solution but far from ideal, it's really costly!

Most of the following functions should deal directly with `image.data` and considering `image.format` (1-2-4-8 bytes per pixel) for the data movement/edit math:

**> Functions NOT REQUIRING color modification:**
 - [x] ImageFlipVertical()
 - [x] ImageFlipHorizontal()
 - [x] ImageRotateCW()
 - [x] ImageRotateCCW()
 - [x] ImageCrop()
 - [x] ImageAlphaCrop()
 - [x] ImageResizeCanvas()
 - [x] ImageToPOT()
 - [x] ExportImage()

**> Functions REQUIRING color modification:**
 - [x] **ImageDraw()**
 - ImageColorTint()
 - ImageColorInvert()
 - ImageColorContrast()
 - ImageColorBrightness()
 - ImageColorReplace()
 - ImageDither()
 - [x] ImageAlphaClear()
 - [x] ImageAlphaPremultiply()
 - ImageAlphaMask()

**> Functions with POSSIBLE color modification:**
 - ImageResize() -> not optimized
 - ImageResizeNN() -> not optimized

Some functions are ok using `GetImageData()` (at least for the moment):
 - GetImageAlphaBorder()
 - GetImagePalette()
 - ImageFormat()
 - *ImageTextExt()* -> ImageDraw()

This issue is just an internal improvement for the `Image` API, low priority.

**Comment by raysan5** [comment]
I did a quick test with a small image (512x285), adapting `ImageFlipVertical()`.

Current implementation took aprox. `7515 microseconds` while adapted version took `218 microseconds`, that's an speed improvement of `3447 %`. Not bad.

**Comment by raysan5** [comment]
Second test with `ImageFlipHorizontal()`, this time it was a bit more complex because moving image rows could be done by row-chunks but moving columns is more difficult because the memory layout.

First approximation was similar to `ImageFlipVertical()`, also using `memcpy()` calls:
```c
for (int y = 0; y < image->height; y++)
{
    for (int x = 0; x < image->width; x++)
    {
        memcpy(flippedData + (y*image->width + x)*bytesPerPixel, ((unsigned char *)image->data) + (y*image->width + (image->width - 1 - x))*bytesPerPixel, bytesPerPixel);
    }
}
```
Improvement was from `7713 us` to `2125 us`, that's about `3.5` times faster... but I imagine so many `memcpy()` calls have some overload, so I tried a second approximation:
```c
for (int y = 0; y < image->height; y++)
{
    for (int x = 0; x < image->width; x++)
    {
        for (int i = 0; i < bytesPerPixel; i++) flippedData[(y*image->width + x)*bytesPerPixel + i] = ((unsigned char *)image->data)[(y*image->width + (image->width - 1 - x))*bytesPerPixel + i];
    }
}
```
This time I'm moving bytes directly, this time it took `981 us`, almost 8 times faster!

Also want to note that after several executions of the program those times oscillate, I imagine it depends on the OS but I'd be nice to know the exact reason for that... I measure time the following way:
```c
double time = GetTime();    // Uses glfwGetTime()
ImageFlipHorizontal(&image);
printf("Function time: %f sec.\n", GetTime() - time);
```

**Comment by brankoku** [comment]
When optimizing the image flipping functions, here are two things to strive for:
1. Do the mirroring in place (avoiding unnecessary allocations)
2. Dedicated functions for each bit depth (creates more optimization opportunities)

I have created a working example for 32-bit image data, attached to this comment as a file. The only dependency is the C standard library, since I don't have raylib set up right now. In the example, `ImageFlipHorizontalSlow` is `ImageFlipHorizontal` pulled from the latest `textures.c`, with the changes you have described in your most recent comment applied. My new functions are `ImageFlipHorizontal` and `_ImageFlipHorizontal32`.

Here are the speeds from my testing on Linux:
```
gcc -o test -O2 -lm -Wall ImageFlipHorizontal.c && time ./test

new function speed (-O2)
real	0m0.002s
user	0m0.002s
sys	0m0.000s

old function speed (-O2)
real	0m0.004s
user	0m0.003s
sys	0m0.000s
```
```
gcc -o test -O3 -lm -Wall ImageFlipHorizontal.c && time ./test

new function speed (-O3)
real	0m0.002s
user	0m0.002s
sys	0m0.000s

old function speed (-O3)
real	0m0.005s
user	0m0.004s
sys	0m0.000s
```

`-O3` appears to optimize my new function equivalently to `-O2`. On my system, however, `-O3` causes the old raylib function to be ever so slightly slower.

Here are my new functions, for a quick reference:
```c
// Flip image horizontally (optimized for 32-bit formats)
static inline void _ImageFlipHorizontal32(Image *image)
{
    // Security check to avoid program crash
    if ((image->data == NULL) || (image->width == 0) || (image->height == 0))
        return;

    uint32_t *p = GetImageData(*image);

    for (int y = 0; y < image->height; y++)
    {
        for (int x = 0; x < image->width / 2; x++)
        {
            uint32_t backup = p[y*image->width + x];
            p[y*image->width + x] = p[y*image->width + (image->width - 1 - x)];
            p[y*image->width + (image->width - 1 - x)] = backup;
        }
    }
}

// Flip image horizontally
void ImageFlipHorizontal(Image *image)
{
    // Security check to avoid program crash
    if ((image->data == NULL) || (image->width == 0) || (image->height == 0))
        return;

    int bitsPerPixel = ImageBitsPerPixel(image);
    
    /* optimized/special handlers */
    switch (bitsPerPixel)
    {
        case 0:
            return;
        
        case 32:
            _ImageFlipHorizontal32(image);
            return;
        
        /* TODO: some generic handler */
        default:
            return;
    }
}
```
The use of `uint32_t` from `stdint.h` is important, so if you use this, please do not change that.

Mileage may vary across systems, and `time` isn't known for being precise. Please try these new functions under the same test conditions as the old ones and let us know if it has hurt or helped performance at all. :) @raysan5 

[Here's my source (ImageFlipHorizontal.c)](https://github.com/raysan5/raylib/files/4740760/ImageFlipHorizontal.txt)

**Comment by raysan5** [comment]
@brankoku Thanks for the implementation! I'll give it a try. Why `uint32_t` is important? I try to avoid `stdint.h` types on raylib...

**Comment by brankoku** [comment]
@raysan5 `uint32_t` is important because it is guaranteed to be 32 bits, and this optimized form treats every pixel as a 32-bit value. `stdint.h` was introduced in C99, and raylib is C99, so there should be no portability issues. If there are, however, an alternative to consider may be maintaining a `ray_u32` type, with a compile-time assertion to ensure it's the right size. `stb.h` accomplishes such assertions in this fashion:
```c

typedef char stb__testsize2_16[sizeof(stb_uint16)==2 ? 1 : -1];
typedef char stb__testsize2_32[sizeof(stb_uint32)==4 ? 1 : -1];
```

**Comment by raysan5** [comment]
@brankoku I tested your solution and indeed it's the fastest option. On my computer it gave me times of `~400us` to `~600us` on `-O2`, around two times faster than my latest implementation.

Despite that, I'm going for the byte-moving implementation, it's slower but more generic to be used in all Image manipulation functions. Also, performance improvement comparing to current implementation is several orders of magnitude.

**Comment by brankoku** [comment]
@raysan5 Thanks for testing it out for me, and well-done on these updates. :+1: I may still tweak and PR your new functions to eliminate unnecessary allocations in situations where we can get away with modifying the image data in-place (rotate/flip).

**Comment by raysan5** [comment]
After some more changes in commits https://github.com/raysan5/raylib/commit/82f7dd017ee3899ff09475c25222e995f70a80b8 and https://github.com/raysan5/raylib/commit/40bc6afdbd06d213a07a5e321f4f285d613a1fe5, a small recap on the changes:

 - *Functions NOT REQUIRING color modification* -> All those functions have been **REDESIGNED** with faster implementations.

 - *Functions REQUIRING color modification* ->Those functions already require color modifications, so the pattern of `GetImageData() -> edit data -> ImageFormat()` it's not that bad, a quick test give me execution times between `1-2 ms` for most of them (testing on `fudesumi.png` image, RGBA, 384x512).

 - `ImageDraw()` is left for optimization, in case of same image format for source/destination (RGB/RGBA), data can be directly copied with no additional memory allocations of `ImageFormat()` calls.

**Comment by raysan5** [comment]
Despite all the effort put on `ImageDraw()` optimization to avoid `ImageCrop()` calls and other data allocation and move bytes directly from source... it didn't perfom better than original implementation.

Dealing with alpha blending is complex, src and dst could have different pixel formats and to support all possible configurations the easiest way is formating data to a common format... 

Just left my optimization work code in case someone else decides to tweak with this function.

All desired optimizations have been implemented. Closing this issue for now. Feel free to reopen if you think it could be further improved.
