### ISSUE TITLE
Hide INFO Window

### ISSUE THREAD

**Issue by nicholassimon** [raysan5/raylib#1219]
Hi, I have been using Raylib with Go/Golang for a while now and first off just want to say good work, really easy to learn and am enjoying it.

One thing, I am trying to write/code a game and was wondering is there any way to hide the INFO window that pops up when you start a built application, as in the image below? I would very much like to be able to disable or hide this window in the final program though am not sure if this is possible. 

If it is possible how do I do this?

![Annotation 2020-04-24 134110](https://user-images.githubusercontent.com/33998213/80209045-9f28eb80-8631-11ea-8db8-a675a2ca45e1.png)

**Comment by gen2brain** [comment]
@nicholassimon just set `rl.SetTraceLog(rl.LogError)` before InitWindow.

**Comment by gen2brain** [comment]
Oh, for cmd window, you need to pass `-ldflags -H=windowsgui` when building, that is Windows thing.

**Comment by nicholassimon** [comment]
Thanks @gen2brain appreciate it will implement

**Comment by nicholassimon** [comment]
Works perfectly thanks just tested it
