### ISSUE TITLE
[module] Allow setting share_context parameter with eglCreateContext

### ISSUE THREAD

**Issue by wsxiaoys** [raysan5/raylib#1220]
### Issue description

A common use case for VR/AR scenario, is reusing textures from camera pipeline for rendering. It'll be great if we could set the share_context parameter to avoid texture copy across context.

**Comment by raysan5** [comment]
This is a good improvement... and actually I don't know how to do that... it seems GLFW already provides some mechanism: https://www.glfw.org/docs/3.3/context_guide.html#context_sharing

Contributions are welcome!

**Comment by wsxiaoys** [comment]
As I'm currently developing for android, here's a hacky patch i added to core.c to support this:
```
void SetEGLParentContext(void* value)
{
#if defined(PLATFORM_ANDROID)
  CORE.Window.context = (EGLContext)value;
  TRACELOG(LOG_INFO, "ParentContext is set to %d", value);
#endif
}
```

In `InitGraphicalDevices`
```
CORE.Window.context = eglCreateContext(CORE.Window.device, CORE.Window.config, CORE.Window.context, contextAttribs); 
```

As InitGraphicalDevices is currently not exported, would this be something better exported in InitWindow?

**Comment by raysan5** [comment]
It would be nice to find a general multi-platform solution that did not break the API. Keep in mind that this is a specific user-case.

**Comment by wsxiaoys** [comment]
So here's an PR demonstrate the change, it includes:
1. Support using raylib in Android by attaching to a SurfaceTexture, instead of using NativeActivity.
2. Support overriding eglCreateContext's shared context.

Is this something you'd like to merge? Let me know if there's better way to avoid the API break.

**Comment by raysan5** [comment]
@wsxiaoys I prefer not merging those changes, actually this feature would require some redesign for the API (to support all possible platforms and configurations) and I for the moment I recommend using a custom fork of raylib for it.

In any case, thanks for the PR with the implementation, it can be used for reference in a future.
