### ISSUE TITLE
[CORE] export ProcessKeyboard(), etc

### ISSUE THREAD

**Issue by alanbork** [raysan5/raylib#1221]
I'd like to be able to call some of the CORE raylib (src/core.c) from within my own code. But it seems like most of the functions in src/core.c are not exported, nor do they have any namespace as far as I can tell. Maybe I'm missing something basic!

The reason is I need to implement my own version of EndDrawing() for timing reasons related to low-level hardware stuff I'm doing on a raspberry pi.  I can easily add my own definition in src/core.c but that makes it a huge pain to merge any upstream changes back into my own code.

**Comment by raysan5** [comment]
Hello @alanbork, sorry, no plans to expose that function for the moment...

For advance users requiring more control over the code I recommend using `rlgl` module directly, you can check a usage example here: [rlgl_standalone](https://github.com/raysan5/raylib/blob/master/examples/others/rlgl_standalone.c).
