### ISSUE TITLE
[rlgl] DrawTriangleStrip has incorrect rlCheckBufferLimit, leading to overflow.

### ISSUE THREAD

**Issue by rogerallen** [raysan5/raylib#1223]
### Issue description

In `DrawTriangleStrip`, there is a check to see if you will overflow the vertex buffer during this call at https://github.com/raysan5/raylib/blob/master/src/shapes.c#L1301 via `rlCheckBufferLimit(pointsCount)` at https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L1800

The count compared is `RLGL.State.vertexData[RLGL.State.currentBuffer].vCounter + vCount) >= (MAX_BATCH_ELEMENTS*4)`.

The issue is that the number of vertices that will be added during the DrawTriangleStrip is not `pointsCount`, it is `3*(pointsCount - 2)`.  So, later in the DrawTriangleStrip routine, when adding some glVertex2f() it can overflow and fail the compare at https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L1179 and then die with `RLGL: Batch elements overflow (MAX_BATCH_ELEMENTS)`

### Environment

I'm on Windows 10
```
INFO: Initializing raylib 3.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 2560 x 1440
INFO:     > Render size:  2560 x 1440
INFO:     > Screen size:  2560 x 1440
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: GeForce RTX 2080/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 445.87
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: Supported extensions count: 397
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: GL: Mirror clamp wrap texture mode supported
```

### Code Example

I don't have a full minimal code example.  But, here is a snippet that shows how it fails for me:

```
std::vector<Vector2> points0, points1;
// put 8000 points into points0, put 4000 points into points1
DrawTriangleStrip(&(points0[0]), (int)points0.size(), RAYWHITE );
DrawTriangleStrip(&(points1[0]), (int)points1.size(), RAYWHITE );
```
          
During the 2nd `DrawTriangleStrip`, when it does the `rlCheckBufferLimit` it will compare `RLGL.State.vertexData[RLGL.State.currentBuffer].vCounter +  vCount` = 23994 + 4000 and find it less than 32k and continue on.  But during the process of drawing it will try to add 11994 points and fail.

### Suggested fix

I think if you change `if (rlCheckBufferLimit(pointsCount)) rlglDraw();` to `if (rlCheckBufferLimit(3*(pointsCount-2))) rlglDraw();` it will work.

**Comment by raysan5** [comment]
@rogerallen Thank you very much for such a detailed issue, I really appreciate it.

I update the check as proposed.

**Comment by rogerallen** [comment]
Thinking about this more, I am wondering why you don't have a RL_TRIANGLE_STRIP to avoid tripling the vertex buffer storage.  Is that a path you'd consider adding?  Or does something break because you've only got GL_LINES/TRIANGLES/QUADS in rlBegin()?

**Comment by raysan5** [comment]
@rogerallen Actually, the main reason is to avoid more complications with batching system. Right now all three modes share the same *indexed* batching buffers, data (and indices) offsets are calculated on drawing. Supporting `RL_TRIANGLE_STRIP` would just add more complexity to the system.
