### ISSUE TITLE
static lib problem

### ISSUE THREAD

**Issue by lokeb** [raysan5/raylib#1224]
I am using Cygwin, and CMake only creates static libs. After I install this library and use that in a project, it passes for FOUND, but then it complains of missing library `raylib-NOTFOUND` while linking. I set `(raylib_USE_STATIC_LIBS ON)` and it works. Why do I need to set this variable, when the project itself only creates static libs and there is no dynamic lib being created?

**Comment by raysan5** [comment]
Sorry, I don't support CMake, it was user contributed, use the plain Makefiles provided.
