### ISSUE TITLE
[Core] Inconsistent naming of WindowShouldClose and IsWindow... functions

### ISSUE THREAD

**Issue by matej-zajacik** [raysan5/raylib#1226]
There are quite a few functions that return some state of the window, and they all start with `Is` (e. g. `IsWindowReady()`, `IsWindowFullscreen()`), but then there is one function that does not follow the same word order, `WindowShouldClose()`.

I think it should be `ShouldWindowClose()`, or all other functions should follow the latter word order (e. g. `WindowIsReady()`, `WindowIsFullscreen()`).

https://github.com/raysan5/raylib/blob/master/src/raylib.h#L873
https://github.com/raysan5/raylib/blob/master/src/raylib.h#L875

**Comment by jamesl-github** [comment]
raylib is based on glfw   
and glfw uses glfwWindowShouldClose          
https://www.glfw.org/documentation.html           
so he probably just copied that          
doubt if he'll change it to ShouldWindowClose now because that would break all the existing code

**Comment by raysan5** [comment]
@matej-zajacik thanks for noticing it, actually I always try to avoid this kind of inconsistencies but @jamesl-github is right, in this case I'm doing an exception.
