### ISSUE TITLE
[examples] Review examples assets licenses

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1230]
There are +115 code examples provided with raylib, some of them contributed by several authors. 

There could be some assets used on the examples that lack a license file (sometimes because it was just not available or not provided by the author). It should be reviewed.

All assets used in raylib examples should include a license and it should be a permissive license (free to use/distribute).

**Comment by peppemas** [comment]
Hi! 

Another note about the examples. Many of them cannot be compiled with Notepad++ due to include errors. Just modify the script and add the -I option to fix it

SET CFLAGS=$(RAYLIB_PATH)\src\raylib.rc.data -s -static -Os -std=c99 -Wall -Iexternal -DPLATFORM_DESKTOP -I C:\raylib\raylib\src

**Comment by raysan5** [comment]
Here it is a table with the resources used by examples and their licences.

| module   | resource                       | author      | licence | notes |
| :------: | :----------------------------- | :---------: | :------ | :---- |
| core     | xbox.png             | @raysan5    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| core     | ps3.png              | @raysan5    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| textures | boom.wav             | @raysan5    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| textures | buttonfx.wav         | @raysan5    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| textures | button.png           | @raysan5    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| textures | spark_flame.png      | @raysan5    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     | [EffectTextureMaker](https://mebiusbox.github.io/contents/EffectTextureMaker/)
| textures | ninepatch_button.png | @overdev    | ❔     |
| textures | explosion.png        | [Unity Labs Paris](https://blogs.unity3d.com/2016/11/28/free-vfx-image-sequences-flipbooks/) | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)
| textures | parrots.png          | [Kodak set](http://r0k.us/graphics/kodak/)           | ❔       | Original name: `kodim23.png`
| textures | cat.png              | ❔         | ❔     |
| textures | wabbit_alpha.png     | ❔         | ❔     |
| text     | alpha_beta.png | Brian Kent (AEnigma) | [License](https://www.dafont.com/es/alpha-beta.font)  |  Font: `Alpha Beta`  | 
| text     | setback.png | Brian Kent (AEnigma) | [License](https://www.dafont.com/es/setback.font)  |  Font: `Setback`  | 
| text     | jupiter_crash.png | Brian Kent (AEnigma) | [License](https://www.dafont.com/es/jupiter-crash.font)  |  Font: `Jupiter Crash`  | 
| text     | alagard.png | Hewett Tsoi | [License](https://www.dafont.com/es/alagard.font)  |  Font: `Alagard`  | 
| text     | romulus.png | Hewett Tsoi | [License](https://www.dafont.com/es/romulus.font)  |  Font: `Romulus`  | 
| text     | mecha.png |Captain Falcon | [License](https://www.dafont.com/es/mecha-cf.font)  |  Font: `Mecha`  | 
| text     | pixelplay.png | Aleksander Shevchuk | [License](https://www.dafont.com/es/pixelplay.fon)  |  Font: `PixelPlay`  | 
| text     | pixantiqua.ttf  | Gerhard Großmann | [License](https://www.dafont.com/es/pixantiqua.font)  |  Font: `PixAntiqua`  | 
| text     | KAISG.ttf | Dieter Steffmann | [License](https://www.dafont.com/es/kaiserzeit-gotisch.font)  |  Font: `Kaiserzeit Gotisch`      |
| text     | noto_cjk.fnt | Google Fonts | [License](https://www.google.com/get/noto/help/cjk/) | Font: `Noto CJK`  |
| text     | anonymous_pro_bold.ttf | Mark Simonson | [License](https://fonts.google.com/specimen/Anonymous+Pro) | Font: `Anonymous Pro` |
| text     | dejavu.png | DejaVu Fonts | [License](https://dejavu-fonts.github.io/) | Font: `DejaVu` |
| text     | symbola.fnt | George Douros | [License](https://fontlibrary.org/en/font/symbola) | Font: `Symbola` |
| models   | angle_gauge.png                | ❔           | ❔       | Used only by: [`models_yaw_pitch_roll.c`](https://github.com/raysan5/raylib/blob/master/examples/models/models_yaw_pitch_roll.c)
| models   | background.png                 | ❔          | ❔       | Used only by: [`models_yaw_pitch_roll.c`](https://github.com/raysan5/raylib/blob/master/examples/models/models_yaw_pitch_roll.c)
| models   | pitch.png                      | ❔           | ❔       | Used only by: [`models_yaw_pitch_roll.c`](https://github.com/raysan5/raylib/blob/master/examples/models/models_yaw_pitch_roll.c)
| models   | plane.obj                      | ❔           | ❔       | Used only by: [`models_yaw_pitch_roll.c`](https://github.com/raysan5/raylib/blob/master/examples/models/models_yaw_pitch_roll.c)
| models   | plane.png                      | ❔           | ❔       | Used only by: [`models_yaw_pitch_roll.c`](https://github.com/raysan5/raylib/blob/master/examples/models/models_yaw_pitch_roll.c)
| models   | plane_diffuse.png              | ❔           | ❔       | Used only by: [`models_yaw_pitch_roll.c`](https://github.com/raysan5/raylib/blob/master/examples/models/models_yaw_pitch_roll.c)
| models   | billboard.png                  | [@emegeme](https://github.com/emegeme)    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| models   | cubicmap_atlas.png             | [@emegeme](https://github.com/emegeme)    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| models   | heightmap.png                  | [@raysan5](https://github.com/raysan5)    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| models   | dresden_square.hdr             | [HDRIHaven](https://hdrihaven.com/hdri/?h=dresden_square) | [CC0](https://hdrihaven.com/p/license.php) |
| models   | **guy/...**                | @culacant   | ❔     |
| models   | **pbr/trooper...**        | ❔          | ❔       | 
| shaders  | fudesumi.png         | Eiden       | CC4     |
| shaders  | mask.png             | ❔          | ❔       |
| shaders  | plasma.png           | ❔           | ❔       |
| shaders  | raysan.png           | [@raysan5](https://github.com/raysan5)    | [CC0](https://creativecommons.org/publicdomain/zero/1.0/)     |
| shaders  | space.png            | ❔           | ❔       |
| shaders  | texel_checker.png    | ❔           | ❔       |
| audio    | country.mp3          | [@emegeme](https://github.com/emegeme) | [CC0](https://creativecommons.org/publicdomain/zero/1.0/) | Originally created for "DART that TARGET" game |
| audio    | target.ogg           | [@emegeme](https://github.com/emegeme) | [CC0](https://creativecommons.org/publicdomain/zero/1.0/) | Originally created for "DART that TARGET" game |
| audio    | target.flac          | [@emegeme](https://github.com/emegeme) | [CC0](https://creativecommons.org/publicdomain/zero/1.0/) | Originally created for "DART that TARGET" game |
| audio    | coin.wav             | [@raysan5](https://github.com/raysan5) | [CC0](https://creativecommons.org/publicdomain/zero/1.0/) | Created using [rFXGen](https://raylibtech.itch.io/rfxgen) |
| audio    | sound.wav            | [@raysan5](https://github.com/raysan5) | [CC0](https://creativecommons.org/publicdomain/zero/1.0/) | Created using [rFXGen](https://raylibtech.itch.io/rfxgen) |
| audio    | spring.wav           | [@raysan5](https://github.com/raysan5) | [CC0](https://creativecommons.org/publicdomain/zero/1.0/) | Created using [rFXGen](https://raylibtech.itch.io/rfxgen) |
| audio    | weird.wav            | [@raysan5](https://github.com/raysan5) | [CC0](https://creativecommons.org/publicdomain/zero/1.0/) | Created using [rFXGen](https://raylibtech.itch.io/rfxgen) |
| audio    | mini1111.xm          | [tPORt](https://modarchive.org/index.php?request=view_by_moduleid&query=51891) | [Mod Archive](https://modarchive.org/index.php?terms-upload) | - |

**Comment by raysan5** [comment]
Updated several assets that license was not clear.
