### ISSUE TITLE
[build] cmake PLATFORM_WEB fails to build for vs 2019 community

### ISSUE THREAD

**Issue by ZelCloud** [raysan5/raylib#1234]
If I try to use the cmake gui to generate the project everything works fine, but when I change platform from desktop (PLATFORM_DESKTOP) to web (PLATFORM_WEB). I get error in configuration process, project files may be invalid. 

CMake Error at examples/CMakeLists.txt:93 (string):
  string sub-command REPLACE requires at least four arguments.

Line 93 from CMakeLists.txt
  string(REPLACE "-rdynamic" "" CMAKE_SHARED_LIBRARY_LINK_C_FLAGS ${CMAKE_SHARED_LIBRARY_LINK_C_FLAGS})

**Comment by raysan5** [comment]
@a3f please, could you take a look to this issue?

**Comment by a3f** [comment]
No idea without digging deeper. I guess we don't really support reconfiguring on the fly. For best results, please create a different build directory for each `PLATFORM`. Of course, patches to fix this issue are welcome.
