### ISSUE TITLE
[core] Replace deprecated usleep() to nanosleep()

### ISSUE THREAD

**Issue by armageddon421** [raysan5/raylib#1235]
https://github.com/raysan5/raylib/blob/51c3bef4972047dc9927643fd1f1826970203f7d/src/core.c#L5060

twice in this file. Further up, it says 

> // NOTE: Use nanosleep() on Unix platforms... usleep() it's deprecated.

May be half of this problem: https://github.com/raysan5/raylib/pull/1229#discussion_r420372243

**Comment by a3f** [comment]
Good catch, `usleep`'s behavior around `SIGALRM` and other timer function is unspecified and was removed altogether in POSIX.1-2008. We should not use it when other, better, options are available.

**Comment by raysan5** [comment]
@armageddon421 @a3f thanks for detecting this! Actually it was a user contributed code not properly reviewed... updated in commit https://github.com/raysan5/raylib/commit/526c85773f805c39a593eb348624e4327b106fa3
