### ISSUE TITLE
New d language binding

### ISSUE THREAD

**Issue by o3o** [raysan5/raylib#1237]
Dear Ramon,
thank you for new version of your great library.
I would like to report a new D language binding,  that provides both [static (WIP) and dynamic bindings to the raylib](https://github.com/o3o/bindbc-raylib),  updated to raylib version 3..0.0
Thank you again

**Comment by raysan5** [comment]
Hi @o3o! Thank you very much for letting me know!

I added the link to bindings list: https://github.com/raysan5/raylib/commit/9a1e934621b6098093d709ceb149f1bb995c15cc
