### ISSUE TITLE
[models] Change mesh.indices from unsigned short to unsigned int

### ISSUE THREAD

**Issue by AlbertoFrancoDD** [raysan5/raylib#1239]
Would be great to have unsigned int for indexing a mesh rather than unsigned short. The amount of vertices that a mesh can have with a ushort is pretty limited. Should be an easy change, right?

**Comment by raysan5** [comment]
@AlbertoFrancoDD unsigned int it's not supported on OpenGL ES 2.0, this change would break compatibility between platforms.
