### ISSUE TITLE
[core] Support dynamic context loading?

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1240]
Lately I moved all global variables in raylib modules to a global struct context and I just defined a global variable for the context data:
```c
// Core global state context data
typedef struct CoreData {
 ...
} CoreData;

static CoreData CORE = { 0 };
```
This static variable is automatically created at program initialization and expected to be stored at `.data` segment (or maybe `.bss` segment depending on compiler).

Now I'm considering supporting a second approach through a flag, just in case:
```c
#if defined(SUPPORT_DYNAMIC_CORE_CONTEXT_LOADING)
    static CoreData *CORE = NULL;
#else
    static CoreData coreData = { 0 };
    static CoreData *CORE = &coreData;
#endif
```

In case `#define SUPPORT_DYNAMIC_CORE_CONTEXT_LOADING`, `CORE` is dynamically allocated/deallocated at `InitWindow()`/`CloseWindow()` respectively.

In this second case, global variable is stored in the heap.

Is it really useful to allow this option? does it have any benefit? maybe I'm just complicating the code and introducing possible future bugs? what do you think?

**Comment by raysan5** [comment]
As pointed on Handmade Network discord, using a pointer for data instead of an object adds one indirection acces level (at least one more assembly instruction for every CORE data access).

**Comment by raysan5** [comment]
So... it seems nobody is interested on this feature and it neither seems to have benefits for the project.

**Comment by istvanfedak** [comment]
Having the CORE defined in the heap would be useful when you wan't to multithread the application

**Comment by orcmid** [comment]
> @istvanfedak  Having the CORE defined in the heap would be useful when you want to multithread the application

It is rather startling to realize that raylib works with a CORE that is static and global.  On the other hand, it makes for easy working at the C/C++ level, and with other-language bindings.

If we are going to use heap allocation, it becomes time to go to COM, even for in-process instantiation, and deal with all of that.  I don't think the extra indirection and lifecycle management are that problematic, it is handled in serious implementations and in Windows APIs.   There is more impact on code footprint than performance, and the advantage of encapsulation plus run-time binding are well-known.  The provision for multi-threading and asynchronous processes follows.

That is a very different model and I think it abandons the simplicity and directness that seems to permeate the raylib approach.  This would not be our grandfather's raylib. :)

**Comment by raysan5** [comment]
@istvanfedak Sorry, I can't see a common use case for that, also note that OpenGL is single threaded by default.

In any case, you can implement it for your custom use-case, I think most users won't benefit of this change.
