### ISSUE TITLE
[core] ToggleFullscreen() on Web

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1241]
Today I've been struggling for hours trying to support `ToggleFullscreen()` on Web, it seems emscripten/browsers mechanisms changed and the previous `Module.requestFullscreen(false, false)` call does not automatically strech the image to fullscreen...

I tried to use the Emscripten provided calls for this:
```c
emscripten_request_fullscreen("#canvas", false);
emscripten_request_fullscreen_strategy("#canvas", false, &strategy);
emscripten_enter_soft_fullscreen("#canvas", &strategy);
```
but despite trying multiple `EmscriptenFullscreenStrategy` parameters... it doesn't work properly... maybe I can't understand how configuration works or it just does not work as expected... I don't know...

I'm going to label this issue asking for help... but the truth is that I don't expect anybody helping with this... it took me hours... long hours on a horrible printf-debug console-web environment... trying to figure out how things work... and getting no result... who could be ready for that?

**Comment by hbiblia** [comment]
In which browsers did you try?

**Comment by object71** [comment]
On web the request fullscreen function is not guaranteed to succeed. It needs to be in response to a UI event directly (not polled at some point).

**Comment by raysan5** [comment]
@object71 Thanks for your answer! Yeah, that's it... I'll try to give it another go...

**Comment by object71** [comment]
Glad I could help. Wasn't sure what your test setup is as in the raylib examples the button was outside the canvas. I am just guessing as this could be the most obvious problem :)

**Comment by raysan5** [comment]
I've been doing some more test and it seems it works on some situation... it really seems browser dependant... I'll investigate it further after raylib 3.5 release...

**Comment by object71** [comment]
I would suggest to drop the feature in raylib itself and leave up to the developers to do it themselves in the browser. You may implement soft fullscreen where you expand the html canvas to full width and height with a high 3nough z index.

**Comment by funcelot** [comment]
> I would suggest to drop the feature in raylib itself and leave up to the developers to do it themselves in the browser. You may implement soft fullscreen where you expand the html canvas to full width and height with a high 3nough z index.

better approach is to warn in console log mechanism as Chrome does.

**Comment by funcelot** [comment]
> I would suggest to drop the feature in raylib itself and leave up to the developers to do it themselves in the browser. You may implement soft fullscreen where you expand the html canvas to full width and height with a high 3nough z index.

probably, it is better to make a placeholder, cause chrome and other browsers are changing too much, one day they decide to add fullscreen support in webgl, other day, don't. it is unpredicatable, can we support or not this feature in the future or not, i think it is related even to different chrome versions
