### ISSUE TITLE
[gestures] GetGestureDetected() returns always GESTURE_SWIPE_LEFT

### ISSUE THREAD

**Issue by o3o** [raysan5/raylib#1245]
### Issue description
Regardless of the direction in which I swipe `GetGestureDetected()`  returns `GESTURE_SWIPE_LEFT`

### Environment
Raspberrry Pi3B, raylib rel. 3.0.0 native mode.
```
$ uname -a 
Linux alarmPi 4.19.102-1-ARCH 
```

### Issue Screenshot
![image](https://user-images.githubusercontent.com/155032/81649675-f8b25800-9430-11ea-877c-7879513ba976.png)

### Code Example
See `examples/core/core_input_gestures.c`

Thank you

**Comment by raysan5** [comment]
I looked at the related code but I can not find the issue, it works ok on Windows desktop.

Are you trying it in native mode? Or Linux desktop?
Are you using a touch screen or just with the mouse?

**Comment by o3o** [comment]
Actually it's strange, it works also in Linux desktop.

I'm trying on Raspberrry Pi3B with [7" touchscreen display](https://www.raspberrypi.org/products/raspberry-pi-touch-display/) and raylib rel. 3.0.0 in native native mode 
If I use a mouse, it works well, if I swipe on touchscreen GetGestureDetected() returns always GESTURE_SWIPE_LEFT. 
I think  issue is on to touchscreen

Thank you

**Comment by raysan5** [comment]
Closing the issue...
