### ISSUE TITLE
[audio] Music loops forever regardless of setting

### ISSUE THREAD

**Issue by MikeDX** [raysan5/raylib#1249]
- [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Playing music always loops, regardless of loopCount setting

### Environment

All

### Issue Screenshot

N/A
### Code Example

```c
Music myMusic = LoadMusicStream(filename);
PlayMusicStream(myMusic);
// Does this need to be set before or after PlayMusic(?) Doesn't seem to matter since myMusic is passed by value so doesnt change locally
SetMusicLoopCount(myMusic, 1);
```

Watch and listen how music plays forever!

**Comment by Not-Nik** [comment]
Have you actually tried using `SetMusicLoopCount` before `PlayMusicStream`? The Music struct does contain a pointer to a context data which will take effect in all copies of the struct instance regardless of it being passed by value or reference.

**Comment by raysan5** [comment]
Yes, this is an issue. Music struct changed from a pointer to value recently but `UpdateMusicStream()` still updates the loop count on the local copy of the struct (that is never returned). Actually this should be redesigned. 

After redesign, `loopCount` has been converted to `bool looping` and let the user enable/disable it on their side. `SetMusicLoopCount()` has been removed.

This is a BREAKING CHANGE, implemented in commit https://github.com/raysan5/raylib/commit/257f232d418cd0e8dc6aef409a16defca044fa1a
