### ISSUE TITLE
[textures] GetScreenData() is very slow

### ISSUE THREAD

**Issue by sparkskapil** [raysan5/raylib#1250]
I am writing a CLR wrapper on Raylib to use it with WPF.

This requires calling GetScreenData method. 
While using it seems that GetScreenData method is much slower. 
In a normal scenario I get 60 fps when I do not call GetScreenData method.
But when I call the method the fps drops to 15-30 fps. 

Need an efficient way to fetch the frame buffer and create a C# bitmap or D3D image which can be shown on WPF window.

**System Specs are as follows:**
Intel I7 8th gen cpu
NVidia GTX 1060 6GB Graphics card
16 GB Ram

**Comment by raysan5** [comment]
`GetScreenData()` is very slow, not many options here, it just copies data from VRAM to RAM, this is a very slow process, it's a limitation imposed by the OpenGL driver.

I imagine there could be some option to directly share graphics buffer but I don't know how...

**Comment by raysan5** [comment]
Some possible references after a quick search:

https://www.codeproject.com/Articles/265903/Using-OpenGL-in-a-WPF-Application
https://community.khronos.org/t/wpf-and-opengl/59433/12
