### ISSUE TITLE
[models] Application crashes when loading .obj model

### ISSUE THREAD

**Issue by peppemas** [raysan5/raylib#1256]
### Issue description

I attached a simple sphere object (change extension .txt to .obj) that breaks the application when you use LoadModel() function.
After the following log the application exit: 

INFO: FILEIO: [resources/shaders/skydome/skydome.obj] Text file loaded successfully
INFO: MODEL: [resources/shaders/skydome/skydome.obj] OBJ data loaded successfully: 1 meshes / 0 materials

### Environment

Operating System Windows 10

INFO: Initializing raylib 3.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  1920 x 1080
INFO:     > Screen size:  1920 x 1080
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: GeForce GTX 1060/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 442.94
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: Supported extensions count: 388
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example

[skydome.txt](https://github.com/raysan5/raylib/files/4642002/skydome.txt)

int main(int argc, char** argv)
{
    const int screenWidth = 1920;
    const int screenHeight = 1080;
    InitWindow(screenWidth, screenHeight, "Test");
    ToggleFullscreen();

    Model skydome = LoadModel("skydome.obj");

    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        BeginDrawing();
            ClearBackground(BLACK);
            DrawFPS(10, 10);
        EndDrawing();
    }

    CloseWindow();        // Close window and OpenGL context
    return 0;
}

**Comment by Not-Nik** [comment]
Can reproduce with the `models_loading` example on MacOS 10.15.4

**Comment by raysan5** [comment]
@peppemas it works ok for me, did you try with latest raylib master branch?

**Comment by peppemas** [comment]
I try to download the master repo and recompile it.

**Comment by peppemas** [comment]
@raysan5  sorry for the delay I tried to investigate, 

The application crash when execute the followin for...loop (models.c)

static Model LoadOBJ(const char *fileName) {
...
...
          for (int v = 0; v < 3; v++) { mesh.normals[vnCount + v] = attrib.normals[idx0.vn_idx*3 + v]; } vnCount +=3;
...
...
}

Now I'm using the master branch

**Comment by raysan5** [comment]
@peppemas raylib expects to find texcoords and normals on the .obj model... but they do no exist in your case... updated in commit https://github.com/raysan5/raylib/commit/b3eea3d322df136b8b53019c4258893a56f3d395.

Please, let me know if it works.

**Comment by peppemas** [comment]
@raysan5 yep now it works!
