### ISSUE TITLE
[raudio] Multichannel sound crash

### ISSUE THREAD

**Issue by Slihfer** [raysan5/raylib#1258]
When attempting to use multichannel sounds, CloseAudioDevice seems to crash the application. Running my project in Visual Studio's Debug mode, gave me an access violation exception in CloseAudioBufferPool on line 1814: "RL_FREE(AUDIO.MultiChannel.pool[i]);". This was on a Windows 10 64bit PC.
Further testing showed that the multichannel sound example that comes with raylib also crashes most of the time (I ran it from n++ in the raylib itch.io version). Tested on the aforementioned system as well as another Windows 10 64bit PC.
Playing around with the example, "sound.wav" can be played without issue, but playing "tanatana.ogg" once causes the crash. Not calling UnloadSound on the .ogg file will allow it to be played exactly once without crashing. Converting it to .wav made no difference.
Not sure if it means anything, but the exit code was consistently -1073741819

**Comment by raysan5** [comment]
Issue corrected on commit https://github.com/raysan5/raylib/commit/a2955bc5b3dc5319ed44f89ddca939d33fcd58cd.

In any case, I don't like current multichannel system... it should be redesigned...

**Comment by Slihfer** [comment]
Thanks a lot!
