### ISSUE TITLE
[raudio] Queue an Audio Buffer

### ISSUE THREAD

**Issue by RobLoach** [raysan5/raylib#1260]
### Issue description

Been working on getting a libretro frontend working in raylib, and ran into issues on the audio buffer. libretro passes a data buffer to play.
https://github.com/RobLoach/raylib-libretro/blob/master/include/rlibretro.h#L522-L529

Tried manipulating the audio stream with `UpdateAudioStream`, but to no avail.

### Environment

- Linux
- OpenGL

### Issue Screenshot

-

### Code Example

``` c
static size_t LibretroAudioWrite(const int16_t *data, size_t frames) {
    // TODO: Fix Audio being choppy since it doesn't append to the buffer.
    if (IsAudioStreamProcessed(LibretroCore.audioStream)) {
        UpdateAudioStream(LibretroCore.audioStream, data, sizeof(*data) * frames);
    }

    return frames;
}
```

Tried a number of different methods on this, including creating a Wave, and then playing the sound. Or even creating a new Sound from the data stream, and manipulating the internal buffer, but no worky.

Is it that we'd need to expose more of the rAudio internals to allow queueing an audio buffer? Thanks!

**Comment by raysan5** [comment]
@RobLoach I took a look at this issue, please, could you try this:

```c
const int SAMPLE_BATCH_SIZE 512

static void LibretroInitAudio()
{
    // Create a new audio stream

    // TODO: Set internal audio buffer for streaming to match samples batch size!
    SetAudioStreamBufferSizeDefault(SAMPLE_BATCH_SIZE);
    LibretroCore.audioStream = InitAudioStream(LibretroCore.sampleRate, 16, 2);
    PlayAudioStream(LibretroCore.audioStream);
    return;
}

static size_t LibretroAudioWrite(const int16_t *data, size_t frames)
{
    while (IsAudioStreamProcessed(LibretroCore.audioStream))
    {
        // QUESTION: frames refer to individual samples or 2-channel-samples?
        // frames batch should match SAMPLE_BATCH_SIZE
        UpdateAudioStream(LibretroCore.audioStream, data, sizeof(*data)*frames);   // Maybe x2 if stereo
    }

    return frames;
}
```

**Comment by raysan5** [comment]
@RobLoach Did you take a look to this issue?

**Comment by RobLoach** [comment]
I haven't checked it out yet, no! Will definitely try it out this weekend :smile: Thanks so much for the help.

**Comment by RobLoach** [comment]
I don't want to jam up the raylib issue queue, so going to close this for now and try it out over at https://github.com/RobLoach/raylib-libretro/issues/2 .

I'll report back! Thanks so much.

**Comment by raysan5** [comment]
thanks @RobLoach, please, keep me updated about it.
