### ISSUE TITLE
[models] Application crash when you try to access mesh indices[]

### ISSUE THREAD

**Issue by peppemas** [raysan5/raylib#1265]
Hi @raysan5 ,

When you create a Mesh with GenMeshXXX (that use par_shapes.h) you do not update the indices anymore.
When you try to access them with the following code the application crash: 

for (int i = 0; i < mesh->triangleCount; i+=3) {
      mesh->indices[i] = xxx;
}
rlUpdateMesh(*mesh, 6, mesh->triangleCount);

Is there another way to access the triangle list of the mesh ?

**Comment by raysan5** [comment]
@peppemas Yeah, that's because indices are not used. Triangles are just defined by the vertex order.

**Comment by raysan5** [comment]
I can do much about this issue, mesh data is directly exposed so it's up to the user to check pointers are valid...

**Comment by peppemas** [comment]
Hi @raysan5 , 

I added the ability to invert the normals of the sphere and hemisphere because it could be useful to draw inside the model.  (In the screenshot you can see an example, where I project an atmospheric scattering shader inside the sphere)
![atmo_scattering](https://user-images.githubusercontent.com/666841/83631430-cdd5a280-a59d-11ea-95e0-14a574ada7f7.png)


Mesh GenMeshSphereEx(float radius, int rings, int slices, bool InvertNormals)
{
    Mesh mesh = { 0 };
    mesh.vboId = (unsigned int *)RL_CALLOC(DEFAULT_MESH_VERTEX_BUFFERS, sizeof(unsigned int));

    par_shapes_mesh *sphere = par_shapes_create_parametric_sphere(slices, rings);
    par_shapes_scale(sphere, radius, radius, radius);
    // NOTE: Soft normals are computed internally

	if (InvertNormals) {
		par_shapes_invert(sphere, 0, 0);
	}

    mesh.vertices = (float *)RL_MALLOC(sphere->ntriangles*3*3*sizeof(float));
    mesh.texcoords = (float *)RL_MALLOC(sphere->ntriangles*3*2*sizeof(float));
    mesh.normals = (float *)RL_MALLOC(sphere->ntriangles*3*3*sizeof(float));

    mesh.vertexCount = sphere->ntriangles*3;
    mesh.triangleCount = sphere->ntriangles;

    for (int k = 0; k < mesh.vertexCount; k++)
    {
        mesh.vertices[k*3] = sphere->points[sphere->triangles[k]*3];
        mesh.vertices[k*3 + 1] = sphere->points[sphere->triangles[k]*3 + 1];
        mesh.vertices[k*3 + 2] = sphere->points[sphere->triangles[k]*3 + 2];

        mesh.normals[k*3] = sphere->normals[sphere->triangles[k]*3];
        mesh.normals[k*3 + 1] = sphere->normals[sphere->triangles[k]*3 + 1];
        mesh.normals[k*3 + 2] = sphere->normals[sphere->triangles[k]*3 + 2];

        mesh.texcoords[k*2] = sphere->tcoords[sphere->triangles[k]*2];
        mesh.texcoords[k*2 + 1] = sphere->tcoords[sphere->triangles[k]*2 + 1];
    }

    par_shapes_free_mesh(sphere);

    // Upload vertex data to GPU (static mesh)
    rlLoadMesh(&mesh, false);

    return mesh;
}

RLAPI Mesh GenMeshSphereEx(float radius, int rings, int slices)
{
         return GenMeshSphereEx(radius, rings, slices, false);
}
