### ISSUE TITLE
BeginDraw & EndDraw Question

### ISSUE THREAD

**Issue by cf-isys** [raysan5/raylib#1266]
I don't want use a infinite cycle, how to you show in your examples. I want only show a line and for this I use this:

```
SetConfigFlags( FLAG_WINDOW_UNDECORATED );
InitWindow( 1024, 600, "Test Application" );
SetTargetFPS( 0 );
BeginDrawing( );
ClearBackground( BLACK );
DrawLine( 0, 0, 1024, 600, WHITE);
EndDrawing( );
```

If I make only this nothing happened! for see the line I have to repeat twice:

```
SetConfigFlags( FLAG_WINDOW_UNDECORATED );
InitWindow( 1024, 600, "Test Application" );
SetTargetFPS( 0 );
// 1 Step 
BeginDrawing( );
ClearBackground( BLACK );
DrawLine( 0, 0, 1024, 600, WHITE);
EndDrawing( );
// 2 Step for show 
BeginDrawing( );
ClearBackground( BLACK );
DrawLine( 0, 0, 1024, 600, WHITE);
EndDrawing( );
```

Why is this?

I use the last version on windows and compile using visual studio 2019

I wait for your answer, Thank so much!!!

**Comment by raysan5** [comment]
@cf-isys Everything is actually processed and drawn in `EndDrawing()`, if you finish the program after first `EndDrawing()` you have no time to see the result.

In any case, a game always use the loop and keeps updating the screen at a fixed framerate.

**Comment by cf-isys** [comment]
befor the endDrawing I not exit of my program, I put a pause. 

SetConfigFlags( FLAG_WINDOW_UNDECORATED );
InitWindow( 1024, 600, "Test Application" );
SetTargetFPS( 0 );
// 1 Step 
BeginDrawing( );
ClearBackground( BLACK );
DrawLine( 0, 0, 1024, 600, WHITE);
EndDrawing( );
// 2 Step for show 
BeginDrawing( );
ClearBackground( BLACK );
DrawLine( 0, 0, 1024, 600, WHITE);
EndDrawing( );
getch();

**Comment by cf-isys** [comment]
Después del EndDrawing no saldo del programa yo tengo una pausa….



Saludos/Regards

[cid:image003.png@01D639E5.705B8B70]
Carlos A. Fernández

Director, Integrisys S.A.



M
+54.9.261.5136.993
P
+54.11.5252.4446


W
www.integri-sys.com<http://www.integri-sys.com/>
A
Pringles 432, C1183AEH, Bs. As., Argentina





De: Ray <notifications@github.com>
Enviado el: miércoles, 3 de junio de 2020 20:03
Para: raysan5/raylib <raylib@noreply.github.com>
CC: Carlos A. Fernández <carlos.fernandez@integri-sys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [raysan5/raylib] BeginDraw & EndDraw Question (#1266)


@cf-isys<https://github.com/cf-isys> Everything is actually processed and drawn in EndDrawing(), if you finish the program after first EndDrawing() you have no time to see the result.

In any case, a game always use the loop and keeps updating the screen at a fixed framerate.

**Comment by raysan5** [comment]
@cf-isys are you using latest raylib version from github master branch?

**Comment by cf-isys** [comment]
Yes, I download the last 3.0, but this problema happened with old version too.

Saludos/Regards

[cid:image003.png@01D639E7.13A13950]
Carlos A. Fernández

Director, Integrisys S.A.



M
+54.9.261.5136.993
P
+54.11.5252.4446


W
www.integri-sys.com<http://www.integri-sys.com/>
A
Pringles 432, C1183AEH, Bs. As., Argentina





De: Ray <notifications@github.com>
Enviado el: miércoles, 3 de junio de 2020 20:37
Para: raysan5/raylib <raylib@noreply.github.com>
CC: Carlos A. Fernández <carlos.fernandez@integri-sys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [raysan5/raylib] BeginDraw & EndDraw Question (#1266)


@cf-isys<https://github.com/cf-isys> are you using latest raylib version from github master branch?

**Comment by cf-isys** [comment]
Ray,

I download the last master from github and now the problem is fixed.

Thanks
