### ISSUE TITLE
Draw Rectangule with Transparency

### ISSUE THREAD

**Issue by cf-isys** [raysan5/raylib#1267]
Is possible make a box and fill with a transparency color? If is possible how to make this?

Thanks,

**Comment by cf-isys** [comment]
I have a picture of background and I want to make a rectangle with less bright for show a text

**Comment by raysan5** [comment]
@cf-isys you can draw a half-transparent white rectangle.

By the way, for questions better use raylib Discord forum, GitHub is more intended for bugs, actually, there is a template for that.
