### ISSUE TITLE
[models] Buffer overrun fix

### ISSUE THREAD

**Issue by frithrah** [raysan5/raylib#1268]
There's a buffer overrun on the vertices array in GenMeshPoly when using certain numbers of sides - 11 or 50 are good examples.

And here's a patch that fixes the issue. :)

[GenMeshPoly-buffer-overrun-fix.txt](https://github.com/raysan5/raylib/files/4735746/GenMeshPoly-buffer-overrun-fix.txt)

Fixed vertices buffer overrun by restricting to vertexCount. Changed degree plotting to floats in order to close the poly accurately. Added check for invalid number of sides.

**Comment by raysan5** [comment]
@frithrah please, could you send a PR with the improvement?

**Comment by frithrah** [comment]
Certainly. Done. First PR!
