### ISSUE TITLE
Macros needed for MinGW for compilation

### ISSUE THREAD

**Issue by shawnpringle** [raysan5/raylib#1273]
It wont compile because of conflicting function names between winuser.h and its own function.

Unable to compile on MinGW/32, I added these lines to one of your C files around #include <windows.h> to get it to compile:  
#define CloseWindow CloseWindowDontUse
#define ShowCursor ShowCursorDontUse
#define UnhideWindow UnHideWindowDontUse
#include <windows.h>
#undef UnhideWindow
#undef ShowCursor
#undef CloseWindow

For the record, I tried this on revision: ec09fea29aa404d578486a91ddc3663b61d95939

**Comment by raysan5** [comment]
Closing the issue. Already discussing it in the PR.
