### ISSUE TITLE
[UWP] GetFPS() always return 0

### ISSUE THREAD

**Issue by peppemas** [raysan5/raylib#1276]
Hi @raysan5,

With PLATFORM_UWP GetFPS() function always return 0. 

in core.c: 

    // Frame time control system
    CORE.Time.current = GetTime();
    CORE.Time.draw = CORE.Time.current - CORE.Time.previous;
    CORE.Time.previous = CORE.Time.current;

CORE.Time.current is correct (successfully call the callback function in App.cpp and increase) 
*BUT* CORE.Time.draw is always 0

**Comment by raysan5** [comment]
@peppemas thanks for reporting. Unfortunately I can't maintain UWP implementation, it was a contribution. Feel free to send a PR if you find a solution.

**Comment by Rover656** [comment]
I'll take a little lookie at this...

**Comment by Rover656** [comment]
I am pushing a fix to the example project, however for the OP I shall share the solution as it needs to be worked into their own solution.

The original Query Time function I added in the rework PR had a precision problem, where if say 4.21345 seconds had passed, it'd return 4, causing some very obvious problems. This function I am attaching fixes this issue. Dropping this in should fix your problems. This fix will also be posted as a PR momentarily.

![image](https://user-images.githubusercontent.com/20544390/85208849-75d3c580-b32b-11ea-81c3-6ede06f0ab95.png)

Or, for copy-pasting sakes:
```
static auto timeStart = std::chrono::high_resolution_clock::now();
std::chrono::duration<double> time_span = std::chrono::duration_cast<std::chrono::duration<double>>(std::chrono::high_resolution_clock::now() - timeStart);
return time_span.count();
```
