### ISSUE TITLE
[textures] New Fade() macro breaks examples (and probably other stuff)

### ISSUE THREAD

**Issue by mkarr** [raysan5/raylib#1277]
The commit ad954dc7abd854030791fcdbc64b32af592b3834 refactors and renames color functions. As part of this, the macro Fade() was implemented to point to the new replacement ColorAlpha(). This macro breaks uses if Fade() in existing code, including the examples. A sample error output from the compilation is included below:

```
In file included from shapes/shapes_draw_ring.c:14:
/home/michael/raylib/src/raylib.h:161: note: macro "Fade" defined here
  161 | #define Fade(c, a)  ColorAlpha(c, a)
      | 
In file included from shapes/shapes_draw_ring.c:17:
shapes/raygui.h:3832:424: error: macro "Fade" passed 5 arguments, but takes just 2
 3832 | OR_PADDING), Fade(RAYGUI_CLITERAL(Color){ 255,0,255,255 }, guiAlpha), Fade(RAYGUI_CLITERAL(Color){ 255,0,0,255 }, guiAlpha));
      |                                                                                                                           ^
```

Replacing all the instances of Fade() with ones to ColorAlpha() fixes compilation, however there are likely other examples of code out in the wild that this change will break too.

**Comment by raysan5** [comment]
@mkarr Yeap... I see. I re-added Fade() in commit https://github.com/raysan5/raylib/commit/afcc584fb6f865de88a1f560d59aeb92b4afd818.
