### ISSUE TITLE
[core] Implementing zoom to point with Camera2D

### ISSUE THREAD

**Issue by sparkskapil** [raysan5/raylib#1278]
I wanted to implement zoom to mouse position using Camera2D.
I tried setting the camera target to the mouse position (screentoworld coordinates).
This moves the complete viewport. 
I already have panning implemented but I am facing difficulty implementing the point zoom. 
The viewport should scale with respect to the mouse position.

For now I have zoom to fixed target is working fine.
Can you please help me?

**Current code**
```
bool ViewPort::onMouseScrolled(MouseScrolledEvent& event)
{
	const float MAX_ZOOM = 3;
	auto factor = event.GetYOffset() * 0.01f;
	auto zoom = camera.zoom + factor;

	if (zoom > MAX_ZOOM)
		return false;
	if (zoom < 1)
		return false;
	camera.zoom = zoom;
	return false;
}
```

**Comment by raysan5** [comment]
This is an implementation issue, not an issue with raylib. You need to animate the zoom value.
