### ISSUE TITLE
[build] Cannot build for Android due to missing "logo" image files

### ISSUE THREAD

**Issue by JasonNumberThirteen** [raysan5/raylib#1279]
### Issue description

Trying to build an APK file for the Android system tracking instructions given here: https://github.com/raysan5/raylib/wiki/Working-for-Android

I cannot successfully compile it due to **error consisting of missing some "_logo_" files** (I'm stuck after the step 1 of the "_Compiling a raylib game for Android_"). I even tried to add some junk images manually, but still with no success... I was using also "_xcopy_" command as it was suggested and even looking at Discord discussion, but I haven't found any solution. May I ask for any attention?

### Environment

Compilation for Android on Windows 10 64-bit operating system. Using "_raylib_" v. 3.0 taken from the official installer.

### Issue Screenshot

![androidBuildError](https://user-images.githubusercontent.com/40078536/84823339-75cb8100-b01e-11ea-8283-adcba410f0b5.PNG)

**Comment by raysan5** [comment]
@JasonNumberThirteen It seems the issue is related to logo images not installed by the default raylib installer, you can find them in GitHub raylib/logo.

Also note that Makefile should be reviewed to point to your Android SDK/NDK paths and API version.

**Comment by JasonNumberThirteen** [comment]
@raysan5 Thanks for your answer. Indeed, adding the "_logo_" directory solved the problem, but after all it should be provided by main installer. It's only my suggestion.
