### ISSUE TITLE
[textures] ImageDraw() cannot crop if source image is larger than destination

### ISSUE THREAD

**Issue by 0r33** [raysan5/raylib#1283]
There’s a problem in the current master branch when trying to crop using ImageDraw().
If you’re trying to draw image2 on top of image1 then if image2 is longer in any dimension than image1 or if it’s positioned in such a way that any part of it will be drawn outside of image1 then the source rectangle provided will be ignored and the image2 will be drawn to the edge of image1 even if the source rectangle provided is smaller.
The following code tries to crop a 101x10 pixel red image down to 10x10 pixels and draw it on top of a 100x100 pixel white image. Because the red image is 1 pixel longer it will not crop.
```c
#include <stdlib.h>
#include <raylib.h>

int main() 
{
	InitWindow( 100, 100, "" );
	SetTargetFPS( 30 );

	//Create a 100x100 white image to draw on
	Color *basePixels = malloc( sizeof( Color ) * 100 * 100 );
	Image base = LoadImageEx( basePixels, 100, 100 );
	ImageDrawRectangle( &base, 0, 0, 100, 100, WHITE );

	//Create a 101x10 pixel red image to be drawn onto the white one
	Color *overlayPixels = malloc( sizeof( Color ) * 101 * 10 );
	Image overlay = LoadImageEx( overlayPixels, 101, 10 );
	ImageDrawRectangle( &overlay, 0, 0, 101, 10, RED );

	//Draw the red image and crop it down to 10x10 pixels. 
	//Because the red image has a width that is 1 pixel longer than the white one
	//the cropping will fail and a 100x10 red rectangle will be draw instead 
	//because it uses the width of the white image.
	ImageDraw( &base, overlay, ( Rectangle ) { 0, 0, 10, overlay.height }, ( Rectangle ) { 0, 0, 10, overlay.height }, WHITE );

	Texture2D baseTex = LoadTextureFromImage( base );

	UnloadImage( base );
	UnloadImage( overlay );
	free( basePixels );
	free( overlayPixels );

	while( !WindowShouldClose() ) {
		BeginDrawing();
		DrawTexture( baseTex, 0, 0, WHITE );
		EndDrawing();
	}
}
```
The problem is in the DrawImage() function in textures.c in the “//Destination rectangle out-of-bounds security check” segment.
There are two else if statements where it uses the srcPtr width instead of the srcRec width. So if you change these two:
`else if ((dstRec.x + srcPtr->width) > dst->width) srcRec.width = dst->width – dstRec.x;`
`else if ((dstRec.y + srcPtr->height) > dst->height) srcRec.height = dst->height – dstRec.y;`
To
`else if ((dstRec.x + srcRec.width) > dst->width) srcRec.width = dst->width – dstRec.x;`
`else if ((dstRec.y + srcRec.height) > dst->height) srcRec.height = dst->height - dstRec.y;`
It will work.

**Comment by raysan5** [comment]
Also noted another possible issue with negative source offsets.
