### ISSUE TITLE
[core] rpi4 branch places the window top below the top of the screen

### ISSUE THREAD

**Issue by alanbork** [raysan5/raylib#1285]
I've been testing out the rpi4 branch (https://github.com/jonlidgard/raylib/tree/rpi4) and it almost works - to the point that it runs and displays textures, responds to input, etc. BUT there's one huge issue: the rendering is always shifted down somewhat relative to the top of the screen, even when the window resolution exactly matches the screen resolution. In 720p 0,0 is only about 20 pixels below the top of the screen. In 480p, however, it's closer to 200 pixels down.  It seems like it must be a bug in core.c in the rpi4 branch but I can't see anything that would cause this. 

hardware: raspberry pi 4 in CLI (non x11) mode.

This is true with any of the examples, but here's a simple test case below.

```
int main()
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 1280;
    const int screenHeight = 720;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");
    SetTargetFPS(60);

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);

           DrawText("Congrats! You created your first window!", 0, 0, 20, LIGHTGRAY);  // Example

        EndDrawing();

    }
    CloseWindow();        // Close window and OpenGL context


    return 0;
}
```

output:

root@raspberrypi:~/raylib-rpi4/examples# examples_template
INFO: Initializing raylib 3.0
INFO: DRM: Using /dev/dri/card1
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1280 x 720
INFO:     > Render size:  1280 x 720
INFO:     > Screen size:  1280 x 720
INFO:     > Viewport offsets: 0, 0
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: V3D 4.2
INFO:     > Version:  2.1 Mesa 19.3.2
INFO:     > GLSL:     1.20
INFO: GL: Supported extensions count: 195
WARNING: GL: VAO extension not found, VAO usage not supported
WARNING: GL: NPOT textures extension not found, limited NPOT support (no-mipmaps                                                                                                                                               , no-repeat)
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
WARNING: RPI: Failed to open Gamepad device, no gamepad available
WARNING: RPI: Failed to change keyboard mode (SSH keyboard?)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 1] Unloaded default texture data from VRAM (GPU)
INFO: CLEANUP
INFO: Window closed successfully

**Comment by raysan5** [comment]
@alanbork I'm afraid you should open this issue on raylib RPI4 fork, not in raylib... Actually, current raylib does not support RPI4.
