### ISSUE TITLE
[core] ToggleFullscreen() can't exit fullscreen mode

### ISSUE THREAD

**Issue by Andrew-Maxwell** [raysan5/raylib#1287]
- [*] I tested it on latest raylib version from master branch
 - [*] I checked there is no similar issue already reported
 - [*] My code has no errors or misuse of raylib

### Issue description
Raylib launches in windowed mode. Calling ToggleFullscreen() once causes it to enter fullscreen mode, but it fails to return to windowed mode on subsequent calls.
### Environment

Platform: Desktop, Ubuntu 20.04 (bug reproduced in both regolith/i3 and gnome)
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 20.0.4
INFO:     > GLSL:     4.60

### Code Example
```
#include <raylib.h>

using namespace std;

int main() {
    SetConfigFlags(FLAG_WINDOW_RESIZABLE);
    InitWindow(GetMonitorWidth(0), GetMonitorHeight(0), "Fullscreen Test");
    SetTargetFPS(60);
    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(RED);
        EndDrawing();
        if (IsKeyPressed(KEY_SPACE)) {
            ToggleFullscreen();
        }
    }
}
```

**Comment by raysan5** [comment]
@Andrew-Maxwell It should be addressed on latest commit.

**Comment by Andrew-Maxwell** [comment]
Yep, looks like it's working now. Thanks again!
