### ISSUE TITLE
[rlgl] GRAPHICS_API_OPENGL_21 can leave some OpenGL functions undefined.

### ISSUE THREAD

**Issue by TSnake41** [raysan5/raylib#1290]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Framebuffer/RenderTexture2D functions may cause crashes if GRAPHICS_API_OPENGL_21 is used.
https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L124 makes some `GRAPHICS_API_OPENGL_33` parts used including [framebuffer parts](https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L1383) even if `glBindFramebuffer` doesn't exist on target platform (like platforms not supporting framebuffer).

A solution may be to either check for [framebuffer support](https://www.khronos.org/opengl/wiki/Framebuffer_Object) and/or making these functions doing nothing if unsupported.

### Environment

Arch Linux ARM
Lima on Mali MP400 (OpenGL 2.1, no framebuffer support)

### Issue Screenshot

*crash*

### Code Example

https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_postprocessing.c

**Comment by raysan5** [comment]
I'm trying to find a good solution but it actually implies some redesign... the easy solution would be just comment fbo support for OpenGL 2.1, despite most platforms support it. The correct solution would be detect the extension it OpenGL 2.1 case and enable the functions when available...

**Comment by raysan5** [comment]
The current approach is not the best one because highly popular platforms like RaspberryPi with FBO support by default on OpenGL 2.1 become painfully affected, so, I implemented a better (simple) solution.
