### ISSUE TITLE
[raudio] Audio distortion in Chromium

### ISSUE THREAD

**Issue by RandomErrorMessage** [raysan5/raylib#1299]
### Issue description

Chromium seems to do a poor job at updating it's audio stream. Under heavier load than the raudio examples it becomes extremely choppy and distorted. I was able to resolve this issue by increasing the miniaudio config.periodSizeInMilliseconds to about 30 (instead of the default 10). There is an issue on this https://github.com/dr-soft/miniaudio/issues/150

Note that "heavier load" does not imply low framerate, just that the issue does not arise from the stock examples.

In addition, Brave Browser seems to be very affected by this to the point where even the examples on raylib.com cause the issue. The config.periodSizeInMilliseconds fix works for this as well. I have opened an issue with the Brave browser since their issue is divergent from Chromium's behavior (which plays the examples fine): https://github.com/brave/brave-browser/issues/10619

### Environment

* Linux, Chromium

**Comment by raysan5** [comment]
@RandomErrorMessage Thanks for reporting, I added a review to your PR.
