### ISSUE TITLE
[rlgl] Memory leaks in rlgl.h

### ISSUE THREAD

**Issue by Mloren** [raysan5/raylib#1301]
### Issue description

rlgl.h contains several memory leaks which I noticed using the memory leak tracker in crtdbg.h. 
I wrote some code to find the exact line, logging every allocation and deallocation:
```
Leak in rlgl.h, at line 3937
Leak in rlgl.h, at line 4088
Leak in rlgl.h, at line 4089
Leak in rlgl.h, at line 4090
Leak in rlgl.h, at line 4092

```
### Environment

Windows 10
VS 2017
raylib 3.0

### Code Example

I used a minimal project and you can get a print out of the leaks to the output window using this code:

```
#include <crtdbg.h>
#include "raylib.h"
int main()
{
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
	InitWindow(640, 480, "Hello, world!");
	CloseWindow();

	return 0;
}
```

Other users on discord have confirmed these on linux as well.

**Comment by raysan5** [comment]
This issue should be solved with @terrehbyte PR. Many thanks for reporting it!

A side note, `RenderBatch` is a recent addition, so this leak shouldn't be present in `raylib 3.0` release.
