### ISSUE TITLE
[rlgl] Windows and OpenGL1.1: compiling core with tcc and mingw-gcc fails

### ISSUE THREAD

**Issue by chrissyan0** [raysan5/raylib#1303]
Thank you for providing raylib.
I need to compile raylib core with SET GRAPHIC_API=GRAPHICS_API_OPENGL_11 in raylib_source_compile (using npp).
In file included from core.c:136:
rlgl.h:1742: error: 'RLGL' undeclared
In fact, RLGL is referenced in a few functions throughout rlgl.h though obviously not used with OPENGL 1.1

Thank you!

**Comment by raysan5** [comment]
@chrissyan0 Did you try with latest raylib from GitHub master branch? This issue should be already solved...

Please, feel free to reopen if issue still persist.
