### ISSUE TITLE
[models] Truly custom mesh generation, sub data updatable...

### ISSUE THREAD

**Issue by Werelien** [raysan5/raylib#1307]
Whilst I can 'fake' a model to do this, and I can change/extend underlying code as well, it would be nice to have a dynamic updateable mesh standard in raylib for all , where verts, uvs etc can be locked, regionally changed, and then unlocked.

**Comment by raysan5** [comment]
@Werelien Actually, you can use the Mesh structure directly and the low-level `rlgl` function `rlUpdateMesh()`, what is the problem with that approach?

**Comment by Werelien** [comment]
Yeah, sorry, I wasn't clear. I was messing around with that. It's just I wondered if that will always work and not break on future versions of raylib, as it seemed an 'unofficial' way, since not in cheat sheet. Cool lib BTW. 🙂

**Comment by raysan5** [comment]
@Werelien Thanks, no plans for the moment to change that part of the API so it will probably remain in time.
