### ISSUE TITLE
[core] detect current display refresh rate

### ISSUE THREAD

**Issue by alanbork** [raysan5/raylib#1308]
It would be nice if there was a function that would return the current refresh rate (either in hz or fraction of a second). I realize that it's possible to estimate this empirically by using tight loop that just swaps buffers without drawing and measuring the timing, but it seems like a waste to do that when this information must be stored somewhere already, presumably where raylib can get access to it. Right now I just assume 60hz but it would be great to support higher refresh rates automatically. 

PS I'm using the raspberry pi, but of course a cross platform solution would be best.

**Comment by raysan5** [comment]
@alanbork Actually, there is. It was added some weeks ago:
```c
int GetMonitorRefreshRate(int monitor);
```

**Comment by alanbork** [comment]
Awesome! needs to be added to the cheat sheet!
