### ISSUE TITLE
[core] Display screen not displaying on Raspberry Pi native mode

### ISSUE THREAD

**Issue by dlpnet** [raysan5/raylib#1314]
### Issue description

There was a change introduced in:
https://github.com/raysan5/raylib/commit/8d51ad567fb2968d4df582bbe71ebd157dde1d85

in particular these 2 lines:
core.c: 3225
CORE.Window.render.width = CORE.Window.display.width;
CORE.Window.render.height = CORE.Window.display.height;

That causes the display to stay blank (background color) with the given examples.

Removing the 2 lines seems to fix the issue but I don't know if it's the correct fix.

### Environment

Raspberry Pi zero W, Raspian OS lite (05/2020), Native mode
Compilation: make PLATFORM=PLATFORM_RPI

**Comment by raysan5** [comment]
@dlpnet Thank you very much for reporting and taking the time to track this issue origin, actually this issue also affected Android platform.

Corrected in attached commit. Please, let me know if it works now.

**Comment by dlpnet** [comment]
from my quick test, all good !! thanks for the quick turn around.
