### ISSUE TITLE
[core] LoadIQM triangle vertex order

### ISSUE THREAD

**Issue by seanpringle** [raysan5/raylib#1315]
While implementing model loading for STL meshes and checking my triangle vertex order, I noticed this comment in the `LoadIQM` code saying that raylib "sets opengl to clockwise drawing":

https://github.com/raysan5/raylib/blob/bdd253a66ad4944b07d29a8533b795fd214c33fd/src/models.c#L3246

That code does appear to go on and deliberately reverse IQM triangle vertex order, so the comment is not an orphan.

But in `rlgl.h` raylib sets the OpenGL default counter-clockwise order:

https://github.com/raysan5/raylib/blob/bdd253a66ad4944b07d29a8533b795fd214c33fd/src/rlgl.h#L1750

For STL the triangle vertex order follows the right hand rule and is counter-clockwise, and so I simply load vertices into a `Mesh` without changing the order. The code appears to work fine and models render properly with good normals and face culling.

Furthermore the LoadOBJ code also apparently loads vertices counter-clockwise, and the `DrawTriangle*` functions also mention counter-clockwise order.

Is the LoadIQM comment wrong, or should I be worried that my code is only working accidentally for some other reason :-) ?

**Comment by raysan5** [comment]
@seanpringle Thanks for pointing that out, raylib follows the standard counter-clockwise convention, I didn't notice that comment. Actually, `LoadIQM()` was contributed by a raylib user.

Looking at the code it reverses triangles _indexes_, raylib expects vertex data provided in counter-clockwise order but triangles indexes are processed in linear order (this is the expected way), so the reversing.

I reviewed the comment for clarification.

**Comment by seanpringle** [comment]
@raysan5 thanks, that makes more sense! I confused the index and vertex ordering.
