### ISSUE TITLE
[shapes] DrawTriangleFan() not drawing

### ISSUE THREAD

**Issue by wtjcn** [raysan5/raylib#1316]
DrawTriangleFan Draw nothing, while DrawLineStrip with the same data draw as expected, and DrawPoly is OK. 
I compare DrawTriangleFan and DrawPoly, and make sure they both use SUPPORT_QUADS_DRAW_MODE branch, 
they are so like, but I realy can not fix it.
I use ubuntu 18.04 system.  I use the latest git version of raylib.

**Comment by wtjcn** [comment]
maybe it's about clockwise and counterclockwise

**Comment by raysan5** [comment]
@wtjcn Please, could you share your sample code? It could be related to vertex order definition...

**Comment by wtjcn** [comment]
DrawTriangle dose the same way. demo code:
		Vector2 v1 = { 100,100 };
		Vector2 v2 = { 200,100 };
		Vector2 v3 = { 200,200 };
		BeginDrawing();
		ClearBackground(RAYWHITE);
		DrawTriangle(v1, v2, v3, RED);// will not show
		DrawTriangle(v1, v3, v2, RED);// will show
		EndDrawing();

if found in rlgl.h Line 1752:
            glFrontFace(GL_CCW);                                    // Front face are defined counter clockwise (default)

this maybe the reason.
I think this should be documented.

**Comment by raysan5** [comment]
@wtjcn Actually, `DrawTriangle()` has a comment on the function code, added another comment on `DrawTriangleFan()`.

I also attach a working example for future reference:

```c
#include "raylib.h"

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [shapes] example - DrawTriangleFan()");
    
    Vector2 points[6] = {
        { 200, 200 },
        { 100, 100 },
        { 100, 300 },
        { 300, 300 },
        { 300, 100 },
        { 100, 100 }
    };

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        BeginDrawing();

            ClearBackground(RAYWHITE);
            
            DrawTriangleFan(points, 6, RED);   // It draws a RED square shape (4 triangles)

        EndDrawing();
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```
