### ISSUE TITLE
[Core] Empty Title string crash game

### ISSUE THREAD

**Issue by anatagawa** [raysan5/raylib#1323]
If you put an empty string like this :

```c
InitWindow( 800, 450, "" );
```

game crash immediately.

To resolve this problem, need to add into **Core.c**

```c
if(strlen(title) == 0) CORE.Window.title = "Raylib";
else CORE.Window.title = title;
```
or

 ```c
if(title[0] == 0) CORE.Window.title = "Raylib";
else CORE.Window.title = title;
```

to add a default string.

**Comment by raysan5** [comment]
@anatagawa I tested it and empty string `""` works ok on Windows, does it crash on Linux?

I prefer not assigning a default title, maybe the user just wants to keep the Window with no title...

**Comment by anatagawa** [comment]
Trying with last source from github , and no problem with empty Title into windows or linux.

Maybe a problem with first Raylib 3.0 release
