### ISSUE TITLE
Instruction on installing prebuilt in Linux

### ISSUE THREAD

**Issue by aberba** [raysan5/raylib#1325]
Its not immediately obvious what to do with **prebuilt binaries** in release so it would be more helpful if an **INSTALLATION** file with instructions in the zip file. 

```sh
cd raylib-3.0.0-Linux-amd64
sudo cp lib/libraylib.** /usr/local/lib/
sudo cp include/raylib.h /usr/local/include/
ln -s libraylib.so.3.0.0 libraylib.so.301 
ln -s libraylib.so.301 libraylib.so
sudo ldconfig
```

**Comment by raysan5** [comment]
Hi @aberba, actually that information should probably be contained in [raylib Wiki](https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux). Feel free to edit it if you find some missing information.

Adding the installation instructions in every release would imply adding different instructions for every release in an automatic way and maintaining those files. Also, multiple Linux distributions and side cases should be considered... 

Unfortunately I don't have the resources to do that, so, I prefer to keep the codumentation centralized in the Wiki.

**Comment by aberba** [comment]
@raysan5 well I'm too lazy to do that
