### ISSUE TITLE
❗ made with raylib showcase

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1326]
Hi! I open this issue to allow users to share their raylib projects!

Actually, [raylib Discord](https://discord.com/invite/VkzNHUE) has a `#madewithraylib` specific channel but the showcased projects get lost in the thread.

You can post: 
 - **A small description** (1-3 lines) of the project
 - **A screenshot (or better a gif)** of the project
 - GitHub project link (if open source)

Waiting for your projects! 😄

**Comment by Skytrias** [comment]
[Todolib](https://github.com/Skytrias/todolib) a tiny, fast and infinite todo editor that I made because of my frustrations with other todo apps / styles like kanban. 
Pretty rough and new project but enough for my usage already.

![preview](https://user-images.githubusercontent.com/22886746/88711337-57c26780-d118-11ea-9857-2a6c4ecfb1a5.gif)

source: https://github.com/Skytrias/todolib

**Comment by edubart** [comment]
2048 game made with Raylib in [Nelua](https://github.com/edubart/nelua-lang) programming language, playable on the browser at https://edubart.github.io/nelua-game2048/
![](https://raw.githubusercontent.com/edubart/nelua-game2048/master/screenshot.gif)
source: https://github.com/edubart/nelua-game2048

**Comment by fr3fou** [comment]
[flappy-go](https://github.com/fr3fou/flappy-go) and [flappy-ai](https://github.com/fr3fou/flappy-ai) are made in go with raylib, all built from scratch, including the neural network and genetic algorithm that power flappy-ai!

You can read more about how the AI was integrated with the game on [simo.sh/projects/flappy-ai](https://simo.sh/projects/flappy-ai)!

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/1344906/88917919-43de4900-d271-11ea-9f87-3128ab35f313.gif)

###### ^ this is the AI playing!

here's the full [video](https://twitter.com/fr3fou/status/1254417434343333888)!

**Comment by DunkUK** [comment]
Waste of Space is a spaceship building game with crafting, automation, exploration and combat.
Built in C++ with Raylib, it uses ENet with a custom deterministic rollback system for it's online coop.
![GIF169](https://user-images.githubusercontent.com/30832665/88922086-89961400-d267-11ea-8831-fc8badb992f1.gif)

**Comment by Rabios** [comment]
raytaiko

A custom simple game engine for the japanese rhythm game Taiko no Tatsujin,Improved with implemented controls,Supports customization and modding via LuaJIT

<img src="https://raw.githubusercontent.com/Rabios/raytaiko/master/Screenshot%20(201).png">
<br>

[Source code on my GitHub account](https://github.com/Rabios/raytaiko)

**Comment by xdrie** [comment]
Wanted to add my in progress game engine!

project page: [rengfx](https://github.com/xdrie/rengfx)

![demo gif](https://raw.githubusercontent.com/wiki/xdrie/rengfx/img/rec-2020-07-30_17.17.12.gif)

[source](https://github.com/xdrie/rengfx/blob/v0.3.4/demo/blocks/source/play.d) for the scene

**Comment by SolarLune** [comment]
I'm working on [MasterPlan](https://solarlune.itch.io/masterplan), a to-do list and ideaboard, written in Go with the raylib-go port of Raylib. I've been working on it for the past few months, and it's really shaping up.

![MasterPlan](https://user-images.githubusercontent.com/4733521/89059243-b1dc4c00-d315-11ea-9970-43f637826fc8.gif)

![MasterPlanScreenshot](https://user-images.githubusercontent.com/4733521/89059277-c1f42b80-d315-11ea-8d63-ec77946ec058.png)

![screenshot3](https://user-images.githubusercontent.com/4733521/89059302-cc162a00-d315-11ea-94b7-2bf6ad2b0115.png)

![screenshot1](https://user-images.githubusercontent.com/4733521/89059348-df28fa00-d315-11ea-894b-117837690f42.png)

**Comment by edubart** [comment]
Clone of Tetris game in [Nelua](https://github.com/edubart/nelua-lang) programming language using Raylib. Play on the browser [here](https://edubart.github.io/nelua-tetris/).
I've used rFXGen to create the sound effects and LMMS to create the music.
![](https://raw.githubusercontent.com/edubart/nelua-tetris/master/screenshot.gif)
source: https://github.com/edubart/nelua-tetris

**Comment by firststef** [comment]
My 2 cents: A work in progress ECS library for games: [ECSlib](https://github.com/firststef/ECSlib). I tried developing a fighting game with it: [Ciopillis](https://github.com/firststef/Ciopillis) but only managed to do some basic stuff 😅😅😅. Still, thank you Raylib!

![Game](https://user-images.githubusercontent.com/38469823/89121300-62894d80-d4c6-11ea-835f-5febc84cbeed.PNG)

**Comment by powerc9000** [comment]
[Cute Asset Pipeline](https://powerc9000.itch.io/cute-asset-pipeline) a PSD asset manager/exporter for gamedev. Export PSDs to PNG.

![Screen Shot 2020-08-05 at 9 41 00 PM](https://user-images.githubusercontent.com/1013528/89488113-663a0000-d764-11ea-8d12-1dc32ebf369c.png)

**Comment by Rabios** [comment]
Autocompletion for raylib lua bindings (ZeroBrane Studio), Get it [here!](https://github.com/Rabios/raylua/blob/master/zerobrane/README.md)

<img src="https://github.com/Rabios/raylua/blob/master/zerobrane/demo.gif">

List of supported bindings:

1. [Alexander Matz's FFI bindings (raylib.lua)](https://gist.github.com/alexander-matz/f8ee4eb9fdf676203d70c1e5e329a6ec)
2. [My bindings (raylua)](https://github.com/Rabios/raylua)
3. [TSnake41's bindings (raylib-lua)](https://github.com/TSnake41/raylib-lua)
4. [darltrash's bindings (Based on Alexander Matz's FFI bindings)](https://github.com/darltrash/raylib-luajit)

**Comment by Kienyew** [comment]
Music Tiles
[Github project](https://github.com/Kienyew/MusicTiles)
A simple Piano Tiles like desktop game created using raylib !
![screenshot](https://raw.githubusercontent.com/Kienyew/MusicTiles/master/screenshot.gif)

**Comment by WEREMSOFT** [comment]
I created a car simulation inspired on the game “art of rally” using #raylib. All physics are hand made. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/808249/93712002-d05f0680-fb52-11ea-8b0c-8d0a4ec5089c.gif)
Source code: https://github.com/WEREMSOFT/c99-raylib-car-physics
online demo: https://weremsoft.github.io/c99-raylib-car-physics/

**Comment by Ilya3point999K** [comment]
[Crusher](https://github.com/Ilya3point999K/Crusher) is a fancy inifinite-srolling breakout clone in 3D
![Demo](https://user-images.githubusercontent.com/55090478/93769571-6e76cd80-fc34-11ea-98d2-43a668b3512e.gif)

**Comment by WEREMSOFT** [comment]
Shadowmapping for raylib. Uses smokes and mirrors. Don't expect anything very advanced.

Code: https://github.com/WEREMSOFT/c99-raylib-shadowmap
Online Demo:  https://weremsoft.github.io/c99-raylib-shadowmap/

![Screenshot from 2020-09-22 19-38-07](https://user-images.githubusercontent.com/808249/93918253-5b373100-fd0c-11ea-8a86-66f26c913612.png)

**Comment by chriscamacho** [comment]
@WEREMSOFT nicely done!

**Comment by Leinnan** [comment]
My old project made with raylib, entt and imgui, currently on hold:
![Image of editor](https://i.imgur.com/uF2vUTq.jpg)
Link to repo: https://git.sr.ht/~leinnan/raylibGame

**Comment by QuantScientist** [comment]
TorchRayLib++: A CMake based integration of the RayLib GUI library and the Libtorch C++ Deep Learning Library.
https://github.com/QuantScientist/TorchRayLib

https://github.com/QuantScientist/TorchRayLib/raw/master/asstes/torch_core_random_values.gif?raw=true

**Comment by trikko** [comment]
A simple blob editor using D and raylib.
https://github.com/trikko/BlobEditor

![output](https://user-images.githubusercontent.com/647157/97924922-be32d380-1d60-11eb-80b2-64848d6d25d2.gif)

**Comment by jdeokkim** [comment]
leko-demo: A block puzzle game inspired by the game 'blox forever', made with raylib and raygui. Only the gameplay screen and the settings window have been implemented so far. (https://github.com/jdeokkim/leko-demo)

![leko-demo](https://raw.githubusercontent.com/jdeokkim/leko-demo/main/leko-demo.gif)

**Comment by object71** [comment]
Check out my simple Pong game:

Itch.io page: https://object71.itch.io/pong
Source: https://github.com/object71/Pong

<img src="https://img.itch.zone/aW1nLzQ3Mjg4NTIucG5n/347x500/zHGtux.png" alt="Pong window" />
