### ISSUE TITLE
[rmem] Using custom memory allocator with a mem pool

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1329]
Following a conversation on Discord, here it is a usage example or `rmem` to use a custom memory pool for all raylib internal allocations:

First, `raylib.h` needs to redefine the allocation macros. `rmem.h` needs to be splitted into `rmem.c` to be compiled along raylib.

```c
// Add below code to raylib.h and recompile raylib including rmem module
#include "rmem.h"

// Allow custom memory allocators
extern MemPool g_pool;
#ifndef RL_MALLOC
    #define RL_MALLOC(sz)       MemPoolAlloc(&g_pool,sz)
#endif
#ifndef RL_CALLOC
    #define RL_CALLOC(n,sz)     MemPoolAlloc(&g_pool, n*sz)
#endif
#ifndef RL_REALLOC
    #define RL_REALLOC(ptr,sz)  MemPoolRealloc(&g_pool,ptr,sz)
#endif
#ifndef RL_FREE
    #define RL_FREE(ptr)        MemPoolFree(&g_pool,ptr)
#endif
```

raylib example using custom memory allocator:

```c
#include "raylib.h"

#define MEMORY_POOL_SIZE  1048576      // 1MB
MemPool g_pool;

int main(void)
{
    const int screenWidth = 800;
    const int screenHeight = 450;

    g_pool = CreateMemPool(MEMORY_POOL_SIZE);

    InitWindow(screenWidth, screenHeight, "game");
    
    printf("mem pool remaining: %zu\n", GetMemPoolFreeMemory(g_pool));

    SetTargetFPS(60);

    while( !WindowShouldClose() ) 
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);
        EndDrawing();
    }

    CloseWindow();
    DestroyMemPool(&g_pool);
}
```

Actually this example approach requires some internal raylib tweak, maybe this mechanism should be redesigned to avoid raylib recompiling; that would imply replacing `RL_*ALLOC` macros by function pointers to hook custom memory allocators.

**Comment by raysan5** [comment]
This issue could be somewhat related to #1440. One possible solution would be exposing `MemAlloc()`/`MemFree()` callbacks for the user to hook.
```c
void *(*MemAlloc)(unsigned int size);
void (*MemFree)(void *ptr);
```
And then define in `utils` module:
```c
void *(*MemAllocCurrent)(unsigned int size) = NULL;
void (*MemFreeCurrent)(void *ptr) = NULL;

void *MemAllocDefault(unsigned int size) { return RL_MALLOC(size); }
void MemFreeDefault(void *ptr) { RL_FREE(ptr); }
```
At raylib initialization, we make sure to get valid callbacks:
```c
MemAllocCurrent = MemAlloc? MemAlloc : &MemAllocDefault;
MemFreeCurrent = MemFree? MemFree : &MemFreeDefault;
```
With this implementation, users have two options to use custom memory control:

 1. Redefine `RL_MALLOC`/`RL_FREE` and recompile raylib.
 2. Implement `MemAlloc`/`MemFree` callbacks at runtime, before raylib initialization.

Not sure if there is an easier implementation to avoid that many functions...

**Comment by assyrianic** [comment]
[rmem.zip](https://github.com/raysan5/raylib/files/5735975/rmem.zip)

I have split up rmem into rmem.h and rmem.c
To use it for a project, rmem.h has to be used for both raylib and the host app so that `MemPool` or the other allocators can be defined as global variables.

**Comment by raysan5** [comment]
After analyzing the addition of custom callbacks for memory allocators, they won't be added (https://github.com/raysan5/raylib/discussions/1631).

Advance users can just hook the custom allocators redefining raylib macros `RL_MALLOC`, `RL_FREE`... and re-compiling sources.
