### ISSUE TITLE
[core] can not input chinese on linux

### ISSUE THREAD

**Issue by wtjcn** [raysan5/raylib#1331]
on ubuntu 18.04, use fcitx class IME, raylib with both internal and external glfw,(external glfw 3.3.2), 
raylib can not get chinese input from in callback of glfwSetCharCallback.
My another program use the same external libglfw, on the same computer, it can receive chinese input.

**Comment by raysan5** [comment]
@wtjcn Are you using latest raylib from GitHub master branch? That was reviewed a while ago.

Also, please, could you share some code sample and screenshot showing the issue?

**Comment by wtjcn** [comment]
It maybe glfw's fault, I see the problem in simplest glfw program. please close this.
