### ISSUE TITLE
[textures] Alpha blending when drawing in RenderTexture vs screen

### ISSUE THREAD

**Issue by creutzerb** [raysan5/raylib#1334]
Hello, I'm experiencing an unexpected behavior.
It looks like drawing on a render texture overrides previous drawing.

### Issue description
drawing on a render texture behaves differently to drawing directly 

### Environment
Manjaro linux
raylib github version

### Issue Screenshot

![opacity_override](https://user-images.githubusercontent.com/10078731/89238718-505afc80-d5f7-11ea-8448-0fb4d2fc746a.png)

Drawing two squares, one on top of the other, with opacity sliders.
left side : using render texture
Supposedly, since I'm drawing on the render texture every frame, the left side should get opaque over time.

### Code Example
minimal project
`

	// Initialisation
	//--------------------------------------------------------------------------------------
	const int screenWidth = 1366;
	const int screenHeight = 768;

	InitWindow(screenWidth, screenHeight, "raylib texture mode example");

	SetTargetFPS(60); // Set our game to run at 60 frames-per-second
	//--------------------------------------------------------------------------------------

	RenderTexture2D target;
	target = LoadRenderTexture(screenWidth, screenHeight);
	BeginTextureMode(target);
	ClearBackground(BLANK);
	EndTextureMode();

	Color color = RED;
	unsigned short opacityA = 255;
	unsigned short opacityB = 255;

	GuiSetStyle(DEFAULT, TEXT_SIZE, 22);

	// Main game loop
	while (!WindowShouldClose()) // Detect window close button or ESC key
	{

		// Update
		//----------------------------------------------------------------------------------
		// drawing in a texture
		BeginTextureMode(target);
		DrawRectangle(200, 400, 300, 300, (Color){ color.r, color.g, color.b, opacityA });
		DrawRectangle(300, 500, 100, 100, (Color){ color.r, color.g, color.b, opacityB });
		EndTextureMode();

		// Draw
		//----------------------------------------------------------------------------------
		BeginDrawing();

		ClearBackground(LIGHTGRAY);

		// draw the texure modified in texture mode on screen
		DrawTexture(target.texture, 260, 50, WHITE);

		// drawing directly on screen
		DrawRectangle(800, 118, 300, 300, (Color){ color.r, color.g, color.b, opacityA });
		DrawRectangle(900, 218, 100, 100, (Color){ color.r, color.g, color.b, opacityB });

		color = GuiColorPicker((Rectangle){ 20, 200, 200, 200 }, color);
		opacityA = GuiSlider((Rectangle){ 300, 510, 120, 30 }, "Large rectangle", "", opacityA, 0, 255);
		opacityB = GuiSlider((Rectangle){ 300, 560, 120, 30 }, "Small Rectangle", "", opacityB, 0, 255);

		EndDrawing();
		//----------------------------------------------------------------------------------
	}

	// De-Initialization
	//--------------------------------------------------------------------------------------
	UnloadRenderTexture(target);
	CloseWindow(); // Close window and OpenGL context
	//--------------------------------------------------------------------------------------

	return 0;
`

**Comment by raysan5** [comment]
@creutzerb This is a tricky issue: https://github.com/raysan5/raylib/issues/1121
