### ISSUE TITLE
[input] Key position based GetKeyPressed for use in keybinding menus

### ISSUE THREAD

**Issue by sorenbug** [raysan5/raylib#1336]
This is slightly related to #1077.

glfw provides [`glfwGetKeyName`](https://github.com/raysan5/raylib/blob/master/src/external/glfw/src/input.c#L597), [`glfwGetKeyScancode`](https://github.com/raysan5/raylib/blob/master/src/external/glfw/src/input.c#L616), and [`glfwGetKey`](https://github.com/raysan5/raylib/blob/master/src/external/glfw/src/input.c#L629) functions which can abstract over layouts.

Raylib's `GetKeyPressed` only returns codepoints, and not actual scancodes or key IDs. This makes it impossible to implement dynamic keybindings that may need to use non-text keys, like the function keys, arrow keys, or modifier keys.

A `GetKeyPressed` that returns a key ID instead of a codepoint, and a `GetKeyName` that returns the stringified name of said key ID would be very helpful for implementing dynamic keybinds.

**Comment by raysan5** [comment]
Hi @sorenbug! Yeah, this is a required improvement, adding it to the TODO list!
