### ISSUE TITLE
[build] Buggy raylib-config.cmake for mingw

### ISSUE THREAD

**Issue by legends2k** [raysan5/raylib#1337]
### Issue description

On Windows, I downloaded the release archive [raylib-3.0.0-Win64-mingw.zip](https://github.com/raysan5/raylib/releases/download/3.0.0/raylib-3.0.0-Win64-mingw.zip) and extracted this to `D:/libs`.  Doing this seems to work

```
cmake -DCMAKE_PREFIX_PATH=D:/libs/raylib-3.0.0-Win64-mingw -G 'Ninja' ..
-- Found raylib: D:/libs/raylib-3.0.0-Win64-mingw/lib/libraylib.dll.a (Required is at least version "3.0")
-- raylib_FOUND: TRUE
-- raylib_INCLUDE_DIRS: D:/libs/raylib-3.0.0-Win64-mingw/include
-- raylib_LIBRARIES: D:/libs/raylib-3.0.0-Win64-mingw/lib/libraylib.dll.a
-- raylib_LDFLAGS: -LC:/Program Files (x86)/Project/lib -lraylib -lwinmm -lgdi32
-- raylib_DEFINITIONS: Files;(x86)/Project/include;-IC:/Program
```

But I noticed that it has malformed paths and I didn't have any of my files in `C:/Program Files (x86)` yet I see them.  Going ahead with the build lead to this:

```
ninja: error: 'raylib-NOTFOUND', needed by '../test.exe', missing and no known rule to make it
```

### Environment

Platform: Windows 10
OpenGL: 4.5
GPU: Nvidia Quadro 450
Compiler: MinGW

Here's my `src/CMakeLists.txt`

```
find_package(raylib 3.0 REQUIRED)
target_link_libraries(${PROJECT_NAME} raylib)
```

**Comment by raysan5** [comment]
@legends2k Please, could you try with latest raylib from github master branch?

**Comment by legends2k** [comment]
@raysan5 I built raylib from `master` using CMake on Windows with MinGW.  Once built, I made a dist package using `cpack` and it gave me `raylib-3.0.0.tar`.  Here's its extracted dir hierarchy

```
.                                          
├── include                                
│   └── raylib.h                           
└── lib                                    
    ├── cmake                              
    │   └── raylib                         
    │       ├── raylib-config.cmake        
    │       └── raylib-config-version.cmake
    ├── libraylib_static.a                 
    └── pkgconfig                          
        └── raylib.pc                      
```

Trying to use this leads to

```
> cmake -DCMAKE_PREFIX_PATH=D:/libs/raylib-3.0.0 -Draylib_VERBOSE=ON -Draylib_USE_STATIC_LIBS=ON -G 'Ninja' ..
...
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find raylib (missing: raylib_LIBRARY) (Required is at least
  version "3.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  D:/libs/raylib-3.0.0/lib/cmake/raylib/raylib-config.cmake:48 (find_package_handle_standard_args)
  src/CMakeLists.txt:22 (find_package)
```

I checked `d:\libs\raylib-3.0.0\lib\cmake\raylib\raylib-config.cmake` and saw that the script expects `libraylib.a` while the directory listing above shows the static library's name is actually `libraylib_static.a`.  I even changed that in the script and running it lead to the original issue I report in the first message:

```
-- Found raylib: D:/libs/raylib-3.0.0/lib/libraylib_static.a (Required is at least version "3.0")
-- raylib_FOUND: TRUE
-- raylib_INCLUDE_DIRS: D:/libs/raylib-3.0.0/include
-- raylib_LIBRARIES: D:/libs/raylib-3.0.0/lib/libraylib_static.a
-- raylib_LDFLAGS: -LC:/Program Files (x86)/Project/lib -lraylib -lwinmm -lgdi32 -lwinmm -lgdi32
-- raylib_DEFINITIONS: Files;(x86)/Project/include;-IC:/Program
```
I've nothing interesting in `C:/Program Files (x86)` while the script seems to put that somehow.  Now giving `make` gives

```
c++.exe: error: Files: No such file or directory
c++.exe: error: (x86)/Project/include: No such file or directory
```

So two issues now:

1. Static library is named `libraylib_static.a` while `lib\cmake\raylib\raylib-config.cmake` expects `libraylib.a`
2. A plain raylib-3.0.0.zip Windows MinGW binary download containing just the headers, `.dll`, cmake and pkg-config settings file doesn't work for a project doing `find_package(raylib 3.0 REQUIRED)`

**Aside**: When I build and cpack I get a static library (`lib/libraylib_static.a`) while what I get from Releases for [raylib-3.0.0-Win64-mingw](https://github.com/raysan5/raylib/releases/download/3.0.0/raylib-3.0.0-Win64-mingw.zip) has a dynamic `bin/libraylib.dll`.

**Comment by raysan5** [comment]
@legends2k Unfortunately I don't maintain the CMake build system, maybe @a3f can take a look to this issue.

**Comment by a3f** [comment]
> Static library is named libraylib_static.a while lib\cmake\raylib\raylib-config.cmake expects libraylib.a

Ye, for MinGW we can drop the _static.

 >  A plain raylib-3.0.0.zip Windows MinGW binary download containing just the headers, .dll, cmake and pkg-config settings file doesn't work for a project doing find_package(raylib 3.0 REQUIRED)

We can fix support for space in `CMAKE_INSTALL_PREFIX`. That's where the `C:\Program Files (x86)\` bit comes from, because that's the CMake default on Windows.

Additionally, it needs the correct prefix in `raylib.pc`. I'd have assumed it works because of [`--enable-define-prefix` apparently being the default on Windows.](https://stackoverflow.com/questions/52440511/why-pkg-config-overrides-prefix-with-another-default-one). I have no MinGW system to debug this. Patches are welcome.

> Aside: When I build and cpack I get a static library (lib/libraylib_static.a) while what I get from Releases for raylib-3.0.0-Win64-mingw has a dynamic bin/libraylib.dll. Of course, I ran cpack without any arguments; it might have an effect on the variant of the distributable archive generated.

CI uses different parameters than the default when packaging releases. Check the `appveyor.yml` for details.

**Comment by raysan5** [comment]
@a3f thank you very much for reviewing the issue! 👍
