### ISSUE TITLE
Failed to load material data, default to white material

### ISSUE THREAD

**Issue by IFixedI** [raysan5/raylib#1338]
![Capture2](https://user-images.githubusercontent.com/69256648/89437007-b064b680-d74f-11ea-973d-46f1111278a0.PNG)
HI a am using raylib with golang and I encountered a problem loading material for a 3d model here my code:
 package main

import (
	rl "github.com/gen2brain/raylib-go/raylib"
)

func main() {
	screenWidth := int32(800)
	screenHeight := int32(450)

	rl.InitWindow(screenWidth, screenHeight, "raylib [models] example - obj model loading")

	camera := rl.Camera{}
	camera.Position = rl.NewVector3(3.0, 3.0, 3.0)
	camera.Target = rl.NewVector3(0.0, 1.5, 0.0)
	camera.Up = rl.NewVector3(0.0, 1.0, 0.0)
	camera.Fovy = 45.0
	camera.Type = rl.CameraPerspective

	texture := rl.LoadTexture("dwarf_diffuse.png") // Load model texture
	dwarf := rl.LoadModel("dwarf.obj")             // Load OBJ model

	dwarf.Materials = make([]rl.Material, 1)
	dwarf.Materials[0].Maps[rl.MapDiffuse].Texture = texture // Set dwarf model diffuse texture

	position := rl.NewVector3(0.0, 0.0, 0.0) // Set model position

	rl.SetCameraMode(camera, rl.CameraFree) // Set a first person camera mode

	rl.SetTargetFPS(60)

	for !rl.WindowShouldClose() {
		rl.UpdateCamera(&camera) // Update camera
		rl.BeginDrawing()

		rl.ClearBackground(rl.Black)

		rl.BeginMode3D(camera)

		rl.DrawModel(dwarf, position, 2, rl.White) // Draw 3d model with texture

		rl.DrawGrid(10, 1.0) // Draw a grid

		rl.DrawGizmo(position) // Draw gizmo

		rl.EndMode3D()

		rl.DrawText("(c) Dwarf 3D model by David Moreno", screenWidth-200, screenHeight-20, 10, rl.Gray)

		rl.EndDrawing()
	}

	rl.UnloadTexture(texture) // Unload texture
	rl.UnloadModel(dwarf)     // Unload model

	rl.CloseWindow()
}

that's what I get:
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Internal vertex buffers uploaded successfully to VRAM (GPU)
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: FILEIO: [dwarf_diffuse.png] File loaded successfully
INFO: IMAGE: [dwarf_diffuse.png] Data loaded successfully (2048x2048)
INFO: TEXTURE: [ID 3] Texture created successfully (2048x2048 - 1 mipmaps)
INFO: FILEIO: [dwarf.obj] Text file loaded successfully
INFO: MODEL: [dwarf.obj] OBJ data loaded successfully: 1 meshes / 0 materials
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
WARNING: MATERIAL: [dwarf.obj] Failed to load material data, default to white material
INFO: TIMER: Target time per frame: 16.667 milliseconds

everything works the model loads, but instead of the texture it just puts a white color,I don't understand what the problem is,I will be very grateful if you help.Thank you in advance)
![Capture](https://user-images.githubusercontent.com/69256648/89436899-8dd29d80-d74f-11ea-8f2f-67dff23da77d.PNG)

**Comment by raysan5** [comment]
@IFixedI Are you using latest raylib version from github?

Did you try `examples/models/models_loading.c` example? It works ok for me.
```c
    Model model = LoadModel("resources/models/castle.obj");                 // Load model
    Texture2D texture = LoadTexture("resources/models/castle_diffuse.png"); // Load model texture
    model.materials[0].maps[MAP_DIFFUSE].texture = texture;                 // Set map diffuse texture
```

It seems issue could be related to `raylib-go`, not raylib itself.

**Comment by IFixedI** [comment]
Yes I'm using the latest version from github.Yes I tried examples/models/models_loading.c example in C in Notepad everything works fine,but it doesn't work on golang.Most likely, you are right and this is due to raylib-go
