### ISSUE TITLE
[core] Allow user to cancel WindowShouldClose()

### ISSUE THREAD

**Issue by powerc9000** [raysan5/raylib#1339]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Raylib already uses the function `glfwSetWindowShouldClose` internally. It would be nice if there was an interface around it, similar to the existing `WindowShouldClose`. 
My use case is I am making a GUI app for editing things. If the user hasn't saved I want to prompt them to do so. Most programs give you the option to save, dont save, or cancel. Currently without a way to cancel WindowShouldClose this isn't possible, at least not in a clean way.

**Comment by raysan5** [comment]
@powerc9000 Added a small change to allow user control. Here a usage example:
```
#include "raylib.h"

int main()
{
    InitWindow(800, 450, "Window should close?");

    SetExitKey(0);   // Disable ESC for exit
    bool exitWindow = false;

    while (!exitWindow && !IsKeyPressed(KEY_SPACE))
    {
        exitWindow = WindowShouldClose();  // Get exit required and reset exit flag

        if (exitWindow)
        {
            // Enable save data window
            exitWindow = false;
        }
        
        BeginDrawing();
            ClearBackground(RED);
            // Draw save data window
        EndDrawing();
    }

    CloseWindow();
}
```

It should work, please let me know.
