### ISSUE TITLE
[Build] Cannot get raylib dll to work for OpenGL 2.1

### ISSUE THREAD

**Issue by pupiraresdi** [raysan5/raylib#1342]
I am using the dll from the msvc15 raylib release in bin, but it only supports OpenGL 3.3 and my pc only has OpenGL 2.1 please help

**Comment by raysan5** [comment]
Hi @pupiraresdi, I'm afraid you should recompile raylib yourself to enable OpenGL 2.1. Here some info: https://github.com/raysan5/raylib/wiki/Working-on-Windows
