### ISSUE TITLE
[core] Compound literals issues with Clang C++ compiler on macOS

### ISSUE THREAD

**Issue by alexanderwanyoike** [raysan5/raylib#1343]
Hey I have been expiriementing with your library and I really like the minimalistic design plus the code base is understandable. I have although found an issue when trying to use Color constants in c++ 

```
 error: expected '(' for function-style cast or type construction
            ClearBackground(RAYWHITE);
```

Debug the issue lead me to this.

https://github.com/raysan5/raylib/blob/959d0d259146c943fe3db61fd1664169303c6394/src/raylib.h#L118

I noticed the reason as to why I was expiriencing this was due to the CLITERAL definition. I saw the comment above the conditional definition check and noticed that it will use the first case even if the compiler is not MSC C++ (ie clang/gcc) in order to fix this I changed the line 118 to read as follows

```
#if defined(__cplusplus) && defined(_WIN32)
``` 

Im not an expert in c++ or compilers Im assuming that the MSC C++ compiler only works in windows and that there will not be any compilation with MSC in OSX I could be wrong. However that fixed issue and im back on track expirimenting with raylib.

**Comment by raysan5** [comment]
Hi @alexanderwanyoike, actually this issue is trickier than it seems... compound-literals support are a C99 feature and depending on the compiler, they are supported or not in C++ but also they could behave differently.

The proposed solution:
```c
#if defined(__cplusplus) && defined(_WIN32)
```
would restrict it to Window but there could be some compiler in another platform that does not support compound-literals on C++. Actually, it seems they should be supported from MSVC 2013 (`_MSC_VER == 1800`).

I investigated a bit and it seems GCC supports them through a GNU-extension, automatic enabled and [Clang support](https://stackoverflow.com/questions/27734247/clang-and-gcc-different-behavior-with-compound-literal) is limited...

Not sure what would be the right way to consider all possible cases... probably a per-compiler + per-version check would be required in some cases.

**Comment by raysan5** [comment]
Investigating [a bit further](https://stackoverflow.com/questions/27734247/clang-and-gcc-different-behavior-with-compound-literal), compound literals are not part of C++ so proposed `defined(__cplusplus)` should work with any C++ compiler.

**Comment by JimmyDeemo** [comment]
Sorry to resurrect this thread but I have hit this same issue and would like to know what the correct compiler flags are to build the 'basic window' sample. Right now I have;

`clang++ -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL lib/raylib.a raylib_game.cpp -o build/raylib_game`

Taken from the Wor[king with MacOS](https://github.com/raysan5/raylib/wiki/Working-on-macOS) page. This results in the following output.

```
+ clang++ -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL lib/raylib.a raylib_game.cpp -o build/raylib_game
raylib_game.cpp:27:25: error: expected '(' for function-style cast or type construction
        ClearBackground(RAYWHITE);
                        ^~~~~~~~
/usr/local/include/raylib.h:152:35: note: expanded from macro 'RAYWHITE'
#define RAYWHITE   CLITERAL(Color){ 245, 245, 245, 255 }   // My own White (raylib logo)
                            ~~~~~ ^
raylib_game.cpp:29:76: error: expected '(' for function-style cast or type construction
        DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);
                                                                           ^~~~~~~~~
/usr/local/include/raylib.h:126:35: note: expanded from macro 'LIGHTGRAY'
#define LIGHTGRAY  CLITERAL(Color){ 200, 200, 200, 255 }   // Light Gray
```

I would like to compile in C++ to use some features from it.

**Comment by raysan5** [comment]
@JimmyDeemo Afaik, it should work... 🤔

**Comment by JimmyDeemo** [comment]
Thank you. This error seems strangly familiar...perhaps it is environmental. I'll try and get eyes on the Discord myself.

**Comment by JimmyDeemo** [comment]
Found it! Looks like you need to tell clang to compile in C++11 mode by adding `-std=c++11` to the arguments. Meaning that the following works for me;
`clang++ -std=c++11 -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL lib/raylib.a raylib_game.cpp -o build/raylib_game`

**Comment by raysan5** [comment]
@JimmyDeemo Thank you very for investigating this issue and reporting the solution here! It would be helpful for future users! 👍

**Comment by JimmyDeemo** [comment]
No worries @raysan5 , i've added a note here too; https://github.com/raysan5/raylib/wiki/Working-on-macOS. Hope that's formatted okay.
