### ISSUE TITLE
Problem : Raylib with Dietpi (* failed to add service – already in use?)

### ISSUE THREAD

**Issue by Ggcpp** [raysan5/raylib#1345]
I have compile raylib on dietpi in native mode on my raspberry pi 3b+ by following this wiki (https://github.com/raysan5/raylib/wiki/Working-on-Raspberry-Pi). There were just few warnings while running the "make PLATFORM=PLATFORM_RPI" command in "raylib/src/" folder. Then I compile the examples by the same command (make PLATFORM=PLATFORM_RPI) in the "raylib/examples/" folder. Up to here everything was ok but when I try to run some examples, the output is always ->
"INFO: Initializing raylib 3.1-dev
* failed to add service – already in use?"

I don't find any way to run an exemple without this error.

Does anybody have an idea on this?

P.S. Sorry for my bad english >.<

**Comment by Ggcpp** [comment]
It is ok I have now find a solution. I had just to disable vc4-kms-v3.

**Comment by raysan5** [comment]
@Ggcpp Oh! You find it fast! :D 

Just note that you can also use raylib on Linux desktop with PLATFORM_DESKTOP.

**Comment by Ggcpp** [comment]
@raysan5 Thanks for your reply and thanks for all your work on raylib, I really enjoy it ! ^o^
