### ISSUE TITLE
[shapes] drawing functions are not consistant

### ISSUE THREAD

**Issue by Shadowblitz16** [raysan5/raylib#1349]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [ ] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
drawing functions seems to use different types and signatures depending on the shape and seem to lack some features for some shapes.

for example...
- DrawRectangleLinesEx takes a rectangle while DrawRectangle takes ints
- DrawLineEx takes Vector2s while DrawLine takes ints 
- DrawEllipseLines has no Ex version
- 3d Drawing functions has no Ex versions
- Rectangles take size while Ellipse's take radius
- Ellipses have no 3d equivalent 

what I would recommend for both 2d and 3d drawing functions..
- sticking ints or floats for all versions.
- getting rid of lines and ex signatures and just allowing us to pass lineColor and lineThickness.
- possibility supplying (x1,y1,x2,y2),(x,y,w,h) and (cx,cy,rx,ry) versions.
- all versions should have rotation

### Code Example
```
void draw_line(int x1, int y1, int x2, int y2, float r, Color fillColor, Color lineColor, int lineBorder);
void draw_line_size(int x, int y, int w, int h,  float r, Color fillColor, Color lineColor, int lineBorder);
void draw_line_radius(int cx, int cy, int rx, int ry,  float r, Color fillColor, Color lineColor, int lineBorder);
void draw_rectangle(int x1, int y1, int x2, int y2, float r, Color fillColor, Color lineColor, int lineBorder);
void draw_rectangle_size(int x, int y, int w, int h,  float r, Color fillColor, Color lineColor, int lineBorder);
void draw_rectangle_radius(int cx, int cy, int rx, int ry,  float r, Color fillColor, Color lineColor, int lineBorder);
void draw_ellipse(int x1, int y1, int x2, int y2, float r, Color fillColor, Color lineColor, int lineBorder);
void draw_ellipse_size(int x, int y, int w, int h,  float r, Color fillColor, Color lineColor, int lineBorder);
void draw_ellipse_radius(int cx, int cy, int rx, int ry,  float r, Color fillColor, Color lineColor, int lineBorder);
```

**Comment by raysan5** [comment]
@Shadowblitz16 I agree there could be a lack of consitency between some shapes functions but I prefer to keep it like it is.

Most of the differences are related to having a novel-user-intended function vs having an advance-user-intended function. Actually, raylib was initially designed for teaching pourposes, so it's very useful to start using a basic data type like `int` to later move to more advance data types like `structs`.

Advance shapes with configurable fill-line colors, it's up to the user to implement them.

**Comment by Shadowblitz16** [comment]
@raysan5 so what what about the usability aspect of it?

```
DrawEllipseLines has no Ex version
3d Drawing functions has no Ex versions
Ellipses have no 3d equivalent
```

most of these are missing because there isn't consistency when new drawing functions are added.

**Comment by raysan5** [comment]
In regards to usability, I think hardly any raylib user uses DrawEllipse() function, that actually was a user contribution.

I prefer to keep a small set of basic functions that try to add lots of functions with lots of options.

In terms of 3D, raylib is more than enough to start playing, for any serious 3D development I recommend an engine like Unity and Unreal.
