### ISSUE TITLE
[text] .fnt files exported from Hiero/BMFont fail to load

### ISSUE THREAD

**Issue by tomc1998** [raysan5/raylib#1351]
### Issue description

Loading a BMFont file (.fnt) exported from Hiero or BMFont (Angelcode) results in an error.

### Environment

Linux, RTX 2070, GL 3.3 Core Profile

### Issue Screenshot

No point screenshotting, here are the logs though:

```
INFO: FILEIO: [hack-12.fnt] Text file loaded successfully
WARNING: IMAGE: [hack-12.fnt] Fileformat not supported
WARNING: IMAGE: [hack-12.fnt] Failed to load data
WARNING: IMAGE: Data is not valid to load texture
WARNING: FONT: [hack-12.fnt] Failed to load texture, reverted to default font
```

### Code Example

After window initialisation: 

```
LoadFont("hack-12.fnt");
```

hack-12.png and hack-12.fnt are in the current working directory when executing the binary, the binary is also in this directory.

Here is hack.png:

![hack-12](https://user-images.githubusercontent.com/7818129/90147711-6052a900-dd7a-11ea-936f-1bede2008096.png)

Here is hack.fnt: (I couldn't attach a .fnt file for whatever reason)

https://pastebin.com/mwLWETPZ

**Comment by raysan5** [comment]
Issue was related to placing the .fnt in the .exe path instead of an assets directory, relative path for image was wrongly calculated. Now it should work.

![screenshot000](https://user-images.githubusercontent.com/5766837/90309365-5c449980-dee8-11ea-90e2-5b1de304283d.png)
