### ISSUE TITLE
HTML 5: Uncaught type error when loading textures

### ISSUE THREAD

**Issue by leigh966** [raysan5/raylib#1352]
Attached images show reproduction code, the accompanying error messages and my build line.
I am using the latest emcc upstream package, Raylib 3.0.0 and testing on a python localhost http server using Google Chrome
**Note: the exception is only thrown when the texture is loaded successfully.**

![error](https://user-images.githubusercontent.com/56688635/90263308-6bbfd600-de47-11ea-9b67-5e72423d99ad.png)
![error2](https://user-images.githubusercontent.com/56688635/90263311-6cf10300-de47-11ea-99cf-50a430effcac.png)
![build](https://user-images.githubusercontent.com/56688635/90263454-99a51a80-de47-11ea-9e33-ef530a00d1ff.png)

**Comment by raysan5** [comment]
Textures must be loaded always after InitWindow().
