### ISSUE TITLE
[core] 3d camera smooth zoom not work on macos

### ISSUE THREAD

**Issue by chunqian** [raysan5/raylib#1355]
## Issue description
build and run, examples/core/core_3d_camera_free.c
3d camera smooth zoom not work
## Environment
osx 10.14.6
raylib master

**Comment by raysan5** [comment]
Ok, that's right, because it requires `CTRL` key... you should redefine that key with `SetCameraSmoothZoomControl()`.

In any case, I'd recommend using a custom camera implementation. Provided camera modes are quite limited...

**Comment by chunqian** [comment]
Thanks for your reply and thanks for all your work on raylib, I enjoy raylib!
I made new golang binding for raylib, it called go-raylib.
[https://github.com/chunqian/go-raylib](url)
