### ISSUE TITLE
[core] FixedUpdate Loop

### ISSUE THREAD

**Issue by muevoid** [raysan5/raylib#1356]
### Fixed Update
I propose having possibly having two functions in the raylib api that would be quite useful to game developers and I believe wouldnt add much complexity. Having an update function and a fixed update function. This way people could render in the update function and do game logic in fixed update. 

There is a few ways to do this I believe. Possiblly something like this:

```
BeginUpdate();
    BeginDrawing();
      //Render Here
    EndDrawing();
EndUpdate()

BeginFixedUpdate(int fps);
     //Game logic 
EndFixedUpdate();
```

**Comment by raysan5** [comment]
@muevoid that's not easy to implement, `EndDrawing()` waits for the `SetTargetFPS()`... I prefer leave that option to the user (for example using threads) instead of being provided by raylib.

**Comment by muevoid** [comment]
Understandable. Thank you!
