### ISSUE TITLE
Ability to draw a texture warped.

### ISSUE THREAD

**Issue by powerc9000** [raysan5/raylib#1358]
It would be nice to be able to warp a 2d texture with control points like this image.

<img width="796" alt="Screen Shot 2020-08-19 at 11 14 06 AM" src="https://user-images.githubusercontent.com/1013528/90675986-7ba93280-e218-11ea-9856-f04e9102fe85.png">

It is technically possible with shaders I understand but they can be a bit daunting to figure out and set up for beginners and warping a texture like this can be fun for effects in a 2D game.

**Comment by raysan5** [comment]
Hi @powerc9000! Actually, a function to do that could be a bit user specific... but you can use `rlgl` directly to accomplish that on raylib:
```c
        rlEnableTexture(texture.id);

        rlPushMatrix();
            rlBegin(RL_QUADS);
                rlColor4ub(tint.r, tint.g, tint.b, tint.a);
                rlNormal3f(0.0f, 0.0f, 1.0f);                          // Normal vector pointing towards viewer

                // Bottom-left corner for texture and quad
                rlTexCoord2f(0.0f, 0.0f);
                rlVertex2f(0.0f, 0.0f);

                // Bottom-right corner for texture and quad
                rlTexCoord2f(0.0f, 1.0f);
                rlVertex2f(0.0f, texture.height);

                // Top-right corner for texture and quad
                rlTexCoord2f(1.0f, 1.0f);
                rlVertex2f(texture.width, texture.height);

                // Top-left corner for texture and quad
                rlTexCoord2f(1.0f, 0.0f);
                rlVertex2f(texture.width, 0.0f);
            rlEnd();
        rlPopMatrix();

        rlDisableTexture();
```
Changing `rlVertex2f()` positions you can do the warping effects. Just need to `#include "rlgl.h"` that you will find in raylib/src and you can use this functionality.

**Comment by powerc9000** [comment]
Awesome! This should be great thanks!
