### ISSUE TITLE
[module] Uncompressed grayscale format updating broken on GLES2

### ISSUE THREAD

**Issue by creikey** [raysan5/raylib#1360]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/VkzNHUE) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [ yes] I tested it on latest raylib version from master branch
 - [yes] I checked there is no similar issue already reported
 - [yes] My code has no errors or misuse of raylib

### Issue description

*Briefly describe the issue you are experiencing (or the feature you want to see added to raylib). Tell us what you were trying to do and what happened instead. Remember, this is not the best place to ask questions. For questions, go to [raylib Discord server](https://discord.gg/VkzNHUE).*

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*
x86, Linux, GLES2, gtx 1060
### Issue Screenshot
![image](https://user-images.githubusercontent.com/28424206/91409814-d46d6200-e7fa-11ea-906e-b9e1c86fd519.png)

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example
```c
#include "raylib.h"

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 512;
    const int screenHeight = 2048;

    InitWindow(screenWidth, screenHeight, "raylib [textures] example - texture loading and drawing");
    SetTargetFPS(60);

    Image image = LoadImage("Mountain.png");
    ImageFormat(&image, UNCOMPRESSED_GRAYSCALE);
    Color *image_data = GetImageData(image);

    // Loads image into GPU, needs GL context given by InitWindow
    Texture texture = LoadTextureFromImage(image);
    texture.format = UNCOMPRESSED_GRAYSCALE; // just to make sure

    // Main loop
    while (!WindowShouldClose()) // Detect window close button or ESC key
    {
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

        ClearBackground(RAYWHITE);

        UpdateTexture(texture, image_data); // this is what's broken
        DrawTexture(texture, screenWidth / 2 - texture.width / 2, screenHeight / 2 - texture.height / 2, WHITE); // draw to the center
        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadTexture(texture); // Texture unloading
    UnloadImage(image);

    CloseWindow(); // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by raysan5** [comment]
@creikey Actually, that's the expected behaviour.

`GetImageData()` always return data as `Color` (RGBA), independently of the `Image` format.

It's up to the user to provide valid data to `UpdateTexture()` with the same format as `texture.format`.

Also, note that:
```c
texture.format = UNCOMPRESSED_GRAYSCALE; // just to make sure
```
shouldn't be done because `texture.format` just takes same format as `image.format`.
