### ISSUE TITLE
[core] New Window state configuration API

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1367]
This issue is related to the recently merged PR: https://github.com/raysan5/raylib/pull/1357

Some additional Window configuration functions were proposed and merged, they are useful to control some Window state properties after Window initialization (some were only configurable with `SetConfigFlags()`).

One idea is replacing some of those `*Window()` functions by something like `SetWindowState(FLAG_WINDOW_MAXIMIZED)` to allow changing Window state/properties after `InitWindow()`. Functions that could be replaced:
```c
ToggleFullscreen(void);      -> SetWindowState(WINDOW_FULLSCREEN)
UnhideWindow(void);          -> SetWindowState(WINDOW_HIDDEN)
HideWindow(void);            -> SetWindowState(WINDOW_VISIBLE)
DecorateWindow(void);        -> SetWindowState(WINDOW_DECORATED)
UndecorateWindow(void);      -> SetWindowState(WINDOW_UNDECORATED) 
MaximizeWindow(void);        -> SetWindowState(WINDOW_MAXIMIZED) 
RestoreWindow(void);         -> SetWindowState(WINDOW_DEFAULT)     // VISIBLE, WINDOWED, DECORATED
```
This approach will also reduce the API size (that is something that I like) and will also allow things like:
```c
SetWindowState(WINDOW_MAXIMIZED | WINDOW_UNDECORATED);
```
It could use same flags as the `SetConfigFlags()`.

**Comment by raysan5** [comment]
Still thinking about it... maybe no new function required, just review internals to support `SetConfigFlags()` after `InitWindow()`. 

But in this case, `SetConfigFlags()` is probably not the best name for the function... I like `SetWindowState()`, it's very descriptive, but some flags do not refer to a *Window*...

I can also keep individual functions available but I like the API reduction...

As a side note, there is one configurations flag that can not be enabled after `InitWindow()`: `FLAG_MSAA_4X_HINT` but it won't be a big problem...

What do you think? Opinions?

**Comment by juan-medina** [comment]
I like the idea of having a `SetWindowState` and `SetConfigFlags` separated, for example platforms that may not have a window they can not use `SetWindowState`.

In this it will have a small API for different things.

`FLAG_FULLSCREEN` may be a general flag but `WINDOW_DECORATED` only apply to Desktop platforms that have a window.

Of course, that means that some flags may need to be moved to a `WINDOW_` value such `FLAG_WINDOW_RESIZABLE` that should be `WINDOW_RESIZABLE` and to be used in `SetWindowState`

**Comment by chriscamacho** [comment]
I have an idea about how to add multiple windows (only for PLATFORM_DESKTOP) which would work as normal ecxept with a few extra API functions

... InitAdditionalWindow(,,,)
SwitchWindow(,,,) 

so windows would have a raylib "id" where 0 is the window created by InitWindow and raylib will supply id's you can use with SwitchWindow, when you do switch windows all raylib functions operate on that specific window until another call to switch window

This might not be 100% workable but could be a little involved so would be better done after SetWindowState, and if there is a GetWindowState they could be used instead of new API functions....

**Comment by raysan5** [comment]
@chriscamacho multiple windows is unrelated to this issue and no plans to support it but here you have some docs on a possible implementation: https://github.com/raysan5/raylib/wiki/Use-multiple-windows

**Comment by kernelkinetic** [comment]
@raysan5 Raylib doesn't support multiple windows so if you want to merge some window-related state options and some non-window-related state options you could maybe call it just `SetState(...)` or `SetConfig(...)` and keep different flag sets for the different topics like `WINDOW_HIDDEN` and `CONFIG_FULLSCREEN`.

**Comment by raysan5** [comment]
@kernelkinetic yeah... still thinking about it...

**Comment by raysan5** [comment]
Working on this issue, just some notes:

```c
typedef enum {
    FLAG_RESERVED           = 1,    // Reserved
    FLAG_FULLSCREEN_MODE    = 2,    // Set to run program in fullscreen
    //WINDOW_FULLSCREEN
    FLAG_WINDOW_RESIZABLE   = 4,    // Set to allow resizable window
    //WINDOW_DECORATED
    FLAG_WINDOW_UNDECORATED = 8,    // Set to disable window decoration (frame and buttons)
    FLAG_WINDOW_TRANSPARENT = 16,   // Set to allow transparent window
    FLAG_WINDOW_HIDDEN      = 128,  // Set to create the window initially hidden
    //WINDOW_VISIBLE
    //WINDOW_MINIMIZED
    //WINDOW_MAXIMIZED
    //WINDOW_DEFAULT
    FLAG_WINDOW_ALWAYS_RUN  = 256,  // Set to allow windows running while minimized
    FLAG_MSAA_4X_HINT       = 32,   // Set to try enabling MSAA 4X
    FLAG_VSYNC_HINT         = 64,   // Set to try enabling V-Sync on GPU
    FLAG_INTERLACED_HINT    = 512   // Set to try enabling interlaced video format (for V3D)
    //WINDOW_DISABLED   // It can not receive inputs
    //WINDOW_POPUP      // Window style
    //WINDOW_FOCUSED  // Get window focus
    //WINDOW_TOPMOST    // GLFW_FLOATING
} ConfigFlag;
```
Above list shows multiple Window config flags, some of those options could be enabled or disabled, so, managing them with flags could be a bit confusing...

Possible functions to manage Window config:

```c
RLAPI void SetWindowState(unsigned int flags);      // Set window state with flags
RLAPI bool CheckWindowState(unsigned int flag);     // Check window state value
// SetWindowState(WINDOW_VISIBLE, true);            // I don't like this...
```

Following functions should also be reviewed, do we need all them? are they consistent?
```c
RLAPI void ToggleFullscreen(void);        // Toggle fullscreen mode (only PLATFORM_DESKTOP)
RLAPI void UnhideWindow(void);            // Show the window
RLAPI void HideWindow(void);              // Hide the window
RLAPI void DecorateWindow(void);          // Decorate the window (only PLATFORM_DESKTOP)
RLAPI void UndecorateWindow(void);        // Undecorate the window (only PLATFORM_DESKTOP)
RLAPI void MaximizeWindow(void);          // Maximize the window, if resizable (only PLATFORM_DESKTOP)
//RLAPI void MinimizeWindow(void);          // Minimize the window, if resizable (only PLATFORM_DESKTOP)
RLAPI void RestoreWindow(void);           // Restore the window, if resizable (only PLATFORM_DESKTOP), is it needed?
```

**Comment by raysan5** [comment]
Implemented on commit https://github.com/raysan5/raylib/commit/3d1ae3500c731aa37d8f887cd165db480c4890eb.

Still under testing, some flags do not work as expected.
