### ISSUE TITLE
[core] CPU usage when idle - SUPPORT_EVENTS_WAITING

### ISSUE THREAD

**Issue by frithrah** [raysan5/raylib#1368]
I'm using raylib for a desktop app - it's going well. One issue is CPU and GPU usage when idle. I'm looking for very low power usage when the app is inactive and the full 60fps when in use.

I just tried compiling with SUPPORT_EVENTS_WAITING. It's good for low power usage - less than 1% for CPU and GPU when idle. And it wakes up nicely when input events come in. The problem with this mode is the render loop depends on events to keep ticking so the FPS is never high enough when active.

I'm thinking about a hybrid approach where glfwWaitEvents is used when idle and glfwPollEvents when active. Is this feasible? Is there a better idea? How to know when the window is inactive is one immediate question.

By the way, I'm using SUPPORT_HALFBUSY_WAIT_LOOP for all tests.

**Comment by raysan5** [comment]
Hi @frithrah, I think this option is only possible if being controlled by user, enabling/disabling active mode when required.

raylib does not expose this option at the moment and, actually, events waiting is only available on desktop platform...

No plans to change this but you can check `core.c -> PollInputEvents()` implementation, probably it can be tweaked in some way.

**Comment by frithrah** [comment]
Aye. I will play with this. Expect a pull request one day.
