### ISSUE TITLE
[core] core.c is too unwieldy! 

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1373]
Due in no small part to the amazingly wide range of platforms for raylib, there are a LOT of #IFDEFS add in that won't be too long before its >6k lines then when trying to look through the code, and work out an execution path can be difficult, requiring multiple views on the same source, adding significant time to debugging in core.c, I'm sure I can't be the first to notice, but it does look a big task!

anyhow there are a number of options

have a separate core_platform_XXX.c for each platform the makefile will need to check PLATFORM and switch in the appropriate source PROS easy to follow execution path through source CONS the same functions on different platform might tend to drift in their behaviour

create an internal "driver" API where raylib talks to a platform agnostic API provided by "plugins" glibs gmodules would be good for this but probably won't work on some platforms like web, and could be fragile at runtime. oops wheres my plugin gone...

do something more elegant that the above that doesn't occur to me at the moment

at the very least all the stuff that does various graphic initialisation and shutdown should be moved into its own unit

this will take a lot of load off core.c and might give a clearer indication of what to do with the remainder.

**Comment by raysan5** [comment]
@chriscamacho I'm aware of this situation but no plans to change it for the moment.

**Comment by chriscamacho** [comment]
if I can figure out how to drive a make rule from a define I could split out a core.c for each platform, the makefile would then compile in either say core_android.c or core_drm.c as apropriate

This is a fair bit of work! but I think would be very beneficial, if I were to undertake this work, would I be wasting my time?
