### ISSUE TITLE
[cmake] Incorrect CMake paths

### ISSUE THREAD

**Issue by adamlwgriffiths** [raysan5/raylib#1380]
I'm trying to package Raylib for NixOS and am running into some troubles with the pkgconfig.

I'm not well versed with CMake nor NixOS and so cannot provide much detail here. Suffice to say, I'm seeing a duplication of paths in the pkconfig output.

Here are two examples or the output:
From [contributor](https://github.com/NixOS/nixpkgs/pull/98030#pullrequestreview-488765959)
```
prefix=/nix/store/kxlh5s1p5ld9bxk22wrl1zpglx493apw-raylib-3.0.0
exec_prefix=${prefix}
libdir=${exec_prefix}//nix/store/kxlh5s1p5ld9bxk22wrl1zpglx493apw-raylib-3.0.0/lib
includedir=${prefix}//nix/store/kxlh5s1p5ld9bxk22wrl1zpglx493apw-raylib-3.0.0/include
```
My own workspace
```
prefix=/nix/store/zz0arpkbn47268lxllzq1rqsgp470d9b-raylib-3.0.0
exec_prefix=${prefix}
libdir=${exec_prefix}//home/adam/Workspace/nixpkgs-temp/raylib/out/lib
includedir=${prefix}//home/adam/Workspace/nixpkgs-temp/raylib/out/include
```

Effectively what I think I'm seeing is something like this:
```
prefix=/A
exec_prefix=/A
libdir=$prefix/A -> /A//A
includedir=$prefix/A -> /A//A
```

[Comments suggest](https://github.com/NixOS/nixpkgs/pull/98030#issuecomment-694765789) that this is actually an upstream issue and not actually Nix related (although it is being exposed by it).
It appears that the raylib.pc.in paths are incorrectly specified.

**Comment by raysan5** [comment]
I @adamlwgriffiths, I'm not an expert on CMake, maybe @a3f can take a look to this issue.

**Comment by a3f** [comment]
Huh, there is both `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_FULL_LIBDIR`,  so I'd have assumed the first is relative and the second is absolute. Seems that is not so.

Do you want to send a patch? Basically the same that https://github.com/fmtlib/fmt/pull/1657/files is doing.

**Comment by adamlwgriffiths** [comment]
I'm trying to get to grips with how Nix does things, so it may take me a while.

**Comment by a3f** [comment]
This is issue has nothing to do with NIx. We have an assumption in the CMake code that doesn't always hold true apparently, you can fix it our CMake script.

**Comment by adamlwgriffiths** [comment]
I understand that, but I'm running Nix and am just getting to grips with the basics. Ie, getting a cmake environment.

**Comment by adamlwgriffiths** [comment]
I've got a branch with this fix: https://github.com/adamlwgriffiths/raylib/tree/1380_cmake_paths
It appears to fix the issue when building using the Nix package manager.
```
prefix=/nix/store/52d9z0jp3wih5kah78px8zny8wcd8d9c-raylib-de67ae3f8be10799c085ca4669c31a7f15ac45b3
exec_prefix=/nix/store/52d9z0jp3wih5kah78px8zny8wcd8d9c-raylib-de67ae3f8be10799c085ca4669c31a7f15ac45b3
libdir=/home/adam/Workspace/nixpkgs-temp/raylib-head/out/lib
includedir=/home/adam/Workspace/nixpkgs-temp/raylib-head/out/include

```

However, I get some strange paths when I build it inside a self contained environment.
```
prefix=/var/empty/local
exec_prefix=/var/empty/local
libdir=${exec_prefix}/lib64
includedir=${prefix}/include
```

I'm not sure if this is an artifact of nix or an error in the change.
