### ISSUE TITLE
[example] models_material_png broken, ‘GenTextureCubemap()’ changed

### ISSUE THREAD

**Issue by ianpan870102** [raysan5/raylib#1384]
When building the given examples, I encountered this error:  too few arguments to function ‘**GenTextureCubemap**’.

Upon investigation, it seems that the function **GenTextureCubemap** is declared to have 4 arguments, when in **models/models_skybox.c** and **models/models_material_pbr.c**, only 3 were passed in when calling the function.

**Comment by raysan5** [comment]
@ianpan870102 good catch! actually that function was changed yesterday... in any case `models_material_pbr.c` doesn't work properly at this point

**Comment by ianpan870102** [comment]
@raysan5 Thanks Ray, I see. Guess I'll keep this issue for a while till it's solved? 👍

**Comment by ianpan870102** [comment]
Speaking of, do you have plans on producing a stable branch for people to download directly with git? Or perhaps have current unstable development live in a dev branch? Just thinking out loud.
Anyways, thanks for maintaining this project, I came across this yesterday and it's very inspiring!

**Comment by chriscamacho** [comment]
personally I always use the "dev" branch, it's only occasionally an example stays broke sometimes just a few hours...

too many versions kicking about - confusion !

**Comment by raysan5** [comment]
@ianpan870102 I used to have a `develop` branch but after CI system addition I switched to one main branch. raylib is usually stable.

**Comment by raysan5** [comment]
I'm closing this issue for now, `models_material_pbr` will be reviewed in the future...
