### ISSUE TITLE
[core] unable to enable GIF recording

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1385]
setting

#define SUPPORT_GIF_RECORDING       1

in config.h has no effect for me on Linux

even putting deliberate error in ifdefined blocks allows compiling to complete!

is something wiping out SUPPORT_GIF_RECORDING is so I can't see what!

**Comment by raysan5** [comment]
@chriscamacho I verified it neither works on Windows... I will review it...

**Comment by chriscamacho** [comment]
Thanks, just be working for some? Seen the gif's !  Can't understand what's killing the define for me???

**Comment by raysan5** [comment]
@chriscamacho I tried it again and now it works, I'm afraid I was testing/linking against the wrong `libraylib.a` version.

Verify that you are compiling the modified version and the define is properly considered.

**Comment by chriscamacho** [comment]
I placed

    slkjfghldgh

inside one of the #if defined(SUPPORT_GIF_RECORDING) in core.c

all compiles fine without error ??!!??

will delete working copy of raylib and try again....

**Comment by chriscamacho** [comment]
okay got it to compile ! (dunno what was going on there!!) :facepalm: 

however there is a linux / glfw issue GLFW doesn't see CTRL-F12 because by default it bound to switching workspaces in a number of window managers, as I don't use workspaces, I was able to unbind the key combo to get it working

When supporting a platform other than windows it would be nice if default key bindings used in that platform were respected the ctrl-f12 yes is a little unusual however....!

the use of the ALT key by the camera - is a right PITA especially if you forget about it

please do consider a different default key to use other than ALT

**Comment by raysan5** [comment]
@chriscamacho Actually, raylib auto-gif-recording functionality should be redesigned... `rgif` is extremely slow and it should be replaced/reviewed. I'm considering `[msf_gif](https://github.com/notnullnotvoid/msf_gif)` a great candidate.

**Comment by raysan5** [comment]
@chriscamacho ALT key is the default control for camera on most 3D softwares, so I used it as default. It can be changed using `SetCameraAltControl()`.

**Comment by chriscamacho** [comment]
would you like me to look at implementing msf_gif ?

**Comment by raysan5** [comment]
@chriscamacho feel free, actually replacement should be straight fordward, API is almost the same
