### ISSUE TITLE
[texture] rendering even or odd frame only rendered

### ISSUE THREAD

**Issue by jagorochi** [raysan5/raylib#1386]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Issue creation requested by @raysan5  after report on discord
Raylib only render even or odd frames
sample code provided and screenshot

### Environment

laptop Acer Aspire A715-73G
Processor Intel Core i7-8705G CPU @ 3.10GHz
RAM : 8Go
OS : Win10 64bits
GPU :  AMD Radeon RX Vega M GL Graphics (integrated GPU)
OpenGL® API Version  4.5

### Issue Screenshot
in the sample code and provided example the `ClearBackground(RAYWHITE)` function is commented to show more clearly that only even or odd frame is redrawn.
![image](https://user-images.githubusercontent.com/17936869/93930426-a443b100-fd1d-11ea-9f86-67f2744a98e9.png)

### video example

https://streamable.com/exru3v
at 5 fps, with  `ClearBackground(RAYWHITE)` we can clearly see the redrawing problem 

### Code Example

```C

#include "raylib.h"

#define MAX_FRAME_SPEED     15
#define MIN_FRAME_SPEED      1

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib - debug");

    // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)
    Texture2D texture = LoadTexture("resources/tx_TAP_Display_White_old.png");        // Texture loading

    Vector2 position = { 350.0f, 280.0f };
    Rectangle redBlockRec = { 8.0f, 0.0f, 8.0f, 8.0f };
    float xPos = 0;
    float yPos = 100;
    int step = 0;
    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        step++;
        xPos = step * 8;
        Vector2 position = {xPos,yPos};
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
            //ClearBackground(RAYWHITE);
            DrawTextureRec(texture, redBlockRec, position, WHITE);
        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadTexture(texture);       // Texture unloading

    CloseWindow();                // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by jagorochi** [comment]
![tx_TAP_Display_White_old](https://user-images.githubusercontent.com/17936869/93932656-d1459300-fd20-11ea-9bea-f941d58dd66f.png)
the png file used

**Comment by chriscamacho** [comment]
can't replicate on Linux I'm seeing a *solid* line

**Comment by raysan5** [comment]
@jagorochi I reviewed the example. First, you should call ClearBackground() between frames. I can see the square correctly moving one step every time. Here the reviewed code:
```c
#include "raylib.h"

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib - debug");

    // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)
    Texture2D texture = LoadTexture("even_odd.png");        // Texture loading

    Rectangle redBlockRec = { 8.0f, 0.0f, 8.0f, 8.0f };
    float xPos = 0;
    float yPos = 100;
    int step = 0;
    
    SetTargetFPS(1);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        step++;
        xPos = step * 8;
        Vector2 position = {xPos,yPos};
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawTextureRec(texture, redBlockRec, position, WHITE);
            
            for (int i = 0; i < 100; i++) DrawRectangle(8*i, 0, 1, GetScreenHeight(), SKYBLUE);
            
        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadTexture(texture);       // Texture unloading

    CloseWindow();                // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by jagorochi** [comment]
Hi, 
@raysan5  i just ran your code and it's what i see : 
https://streamable.com/0qpkqg

i don't think this issue is closed :)

**Comment by jagorochi** [comment]
here is a more demonstrative example than a moving cube where i just alternatively display even/odd text from this png respectively on left/right side of the windows  :
![even_odd](https://user-images.githubusercontent.com/17936869/94375112-8d340300-0111-11eb-8e74-81b0ea309681.png)

**i only see "odd" displayed. Even is never visible.**

```C
#include "raylib.h"

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 256;
    const int screenHeight = 128;

    InitWindow(screenWidth, screenHeight, "raylib - debug");

    // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)
    Texture2D texture = LoadTexture("even_odd.png");        // Texture loading
    bool side =  1;
    
    SetTargetFPS(1);
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        side = !side;
        Rectangle drawRect = {128.0f * side, 0.0f, 128.0f, 128.0f};
        Vector2 position = { 128 * side, 0};
        
        //----------------------------------------------------------------------------------
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawTextureRec(texture, drawRect, position, WHITE);
        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadTexture(texture);       // Texture unloading
    CloseWindow();                // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
    return 0;
}

```

**Comment by raysan5** [comment]
Very weird... 🤔

**Comment by chriscamacho** [comment]
can't replicate Linux 64 bit, just see odd even flashing every second...

**Comment by jagorochi** [comment]
INFO: Initializing raylib 3.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  256 x 128
INFO:     > Screen size:  256 x 128
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Intel(R) HD Graphics 630
INFO:     > Version:  3.3.0 - Build 25.20.100.6374
INFO:     > GLSL:     3.30 - Build 25.20.100.6374
INFO: GL: Supported extensions count: 224
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: ASTC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Internal vertex buffers uploaded successfully to VRAM (GPU)
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: FILEIO: [even_odd.png] File loaded successfully
INFO: IMAGE: [even_odd.png] Data loaded successfully (256x128)
INFO: TEXTURE: [ID 3] Texture created successfully (256x128 - 1 mipmaps)
INFO: TIMER: Target time per frame: 1000.000 milliseconds
INFO: TEXTURE: [ID 3] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 1] Unloaded default texture data from VRAM (GPU)
INFO: Window closed successfully

**Comment by raysan5** [comment]
@jagorochi please, could you try with latest raylib from github main branch? it is raylib 3.1-dev

**Comment by jagorochi** [comment]
i just downloaded raylib-master this morning (didn't find a 3.1-dev branch or tag), compiled it with npp (F6:raylib_source_compile) and it's still the same

**Comment by jagorochi** [comment]
this issue can be closed.
Intel released a driver update last week that solved the issue : 
https://downloadcenter.intel.com/fr/product/136865/Carte-graphique-RX-Vega-M-GL-de-Radeon-

**Comment by raysan5** [comment]
@jagorochi nice to know it was a driver issue!
