### ISSUE TITLE
[core] Support user-defined floating-point type

### ISSUE THREAD

**Issue by mosujiba** [raysan5/raylib#1387]
It would be convenient if the user could customize the floating-point type used by raylib without having to edit the source code. Right now the API almost exclusively uses float, but some users might want to use double, etc. One way to achieve this customizability would be to have raylib use a common alias whose concrete type can be defined at compile time.

```c
#ifndef RL_FLOAT
  #define RL_FLOAT float
#endif
typedef RL_FLOAT rayfloat;

typedef struct Vector2 {
  rayfloat x;
  rayfloat y;
} Vector2;
// ...
```

**Comment by chriscamacho** [comment]
You might want to profile some code, casting all doubles to floats to pass to opengl has a cost, additionally some structures just won't fit and will need recreating into structs with floats, not as straight forward as a define for the floating point type.

**Comment by raysan5** [comment]
@mosujiba that change would imply lot of redesign, no plans for now.

**Comment by raysan5** [comment]
@bart9h This is a very specific user need. You should implement it in your fork if really required for your project needs.

**Comment by orcmid** [comment]
@mosujiba having `rayfloat` will not work through APIs unless raylib is always compiled along with the application.  So where `float`/`double` are specifically required in raylib there then has to be a caste even though it might not be needed.   This becomes a nightmare.  

@bart9h won't the casts of doubles to float parameter type and float structure element type happen automatically?  Too many warnings?
