### ISSUE TITLE
Is there support for std++14/17? 

### ISSUE THREAD

**Issue by QuantScientist** [raysan5/raylib#1389]
### Issue description
Dear team,
My existing CMake project relies on std++17, could I mix and match it with raylib, given that your CMake states:
`set(CMAKE_C_FLAGS "-std=gnu99 ${CMAKE_C_FLAGS}")`
`set(CMAKE_C_STANDARD 11)`

Whereas mine:
`LANGUAGES CXX C`
and: 
```
set_target_properties(${EXAMPLE_001_EXE} PROPERTIES
        CXX_STANDARD 17
        CXX_STANDARD_REQUIRED YES)

```
### Environment

Windows 10, VC 19, Clion + CMake. 

### Code Example

Provided above, this is a compilation / cmake question. 

Thanks,

**Comment by QuantScientist** [comment]
Made some progress, I can compile link and execute my code.

**Comment by QuantScientist** [comment]
Thanks for your response! I moved from NanoUI to RayLib after endless issues with CMake. 
So far so good, I shall keep you posted: 
https://github.com/QuantScientist/TorchRayLib

**Comment by raysan5** [comment]
@QuantScientist Nice! I'll close this issue for now. Great project by the way! :D
