### ISSUE TITLE
[model] billboard doesn't discard alpha fragments...

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1399]
add to billboard example

    Vector3 billPosition2 = { 0.0f, 2.0f, 1.0f }; 
     
     ...
         
           DrawBillboard(camera, bill, billPosition2, 2.0f, WHITE);

the transparent areas obscures other billboards...

**Comment by raysan5** [comment]
@chriscamacho To discard fragments it would require a custom shader, raylib default shader doesn't do that, it's setup for standard alpha blending. The best option here is controlling the drawing order of elements each frame depending on camera distance.

**Comment by chriscamacho** [comment]
which is not always possible, why not have a default billboard shader that
does discard alpha fragments?

as is, it's usefulness is limited where they should really be first class
3d citizens really what you have is something that is NOT beginner
friendly, manual Z sorting of billboards just shouldn't be needed

**Comment by raysan5** [comment]
A billboard specific shader is an extra that only some specific users will require, I prefer to avoid it...

**Comment by chriscamacho** [comment]
sorry not being difficult here (honest!) but a default billboard shader is
very simple and would be transparent to the end user.  To a new coder this
should just work and not require manual Z sorting which is a steep learning
curve for a new programmer...

**Comment by raysan5** [comment]
Not planned for the moment, not a priority, maybe in another moment.

**Comment by ramAdam** [comment]
> which is not always possible, why not have a default billboard shader that does discard alpha fragments? as is, it's usefulness is limited where they should really be first class 3d citizens really what you have is something that is NOT beginner friendly, manual Z sorting of billboards just shouldn't be needed

Hi Chris,
Did you solve this problem ?

**Comment by chriscamacho** [comment]
@ramAdam copy and paste is beyond you ? *all* the code is there on the article...
