### ISSUE TITLE
[core] DrawGrid causes "Batch elements overflow (MAX_BATCH_ELEMENTS)" or just messes up the camera view

### ISSUE THREAD

**Issue by Tkap1** [raysan5/raylib#1401]
### Issue description
Some values of **DrawGrid** **slices** param in combination with specific amount of calls to **DrawCube** cause raylib to either close with the error above or mess with the view. Here is GIF showing it in action: https://i.imgur.com/aIsk01O.gif

It is very consistent. It always happens when **draw_count** (the number of times I call **DrawCube**) is 890. If I start **draw_count** higher 890, it takes longer to happen (i.e. it happens at another value that I haven't printed)
But all of this **never** happens if I remove the **DrawGrid** call.

### Environment
Windows 7
Latest raylib version
Default OpenGL (3.3 I think, right?)
Nvidia GTX 650

### Issue Screenshot
https://i.imgur.com/aIsk01O.gif

### Code Example

This is the whole program. Note that setting the parameters of the camera and the **// draw player** are only necessary to be able to visualize the view being totally wrong.

```

#include "..\raylib.h"

int main(void)
{
	
    const int screenWidth = 800;
    const int screenHeight = 600;
	
	SetTraceLogLevel(LOG_ALL);

    InitWindow(screenWidth, screenHeight, "raylib");
	
    Camera camera = {0};
	
	// This is only to visualize the incorrect view
	camera.position = (Vector3){0, 5, 3};
	camera.up = (Vector3){0, 1, 0};
	camera.fovy = 45;

    SetTargetFPS(60);
	
    while (!WindowShouldClose())
    {
		
		BeginDrawing();
		ClearBackground(RAYWHITE);
		BeginMode3D(camera);

		// Draw player (This is only to visualize the incorrect view)
		DrawCube((Vector3){0,0,0}, 2,2,2, GREEN);
		
		static int draw_count = 890;
		draw_count++;
		for(int i = 0; i < draw_count; i++)
		{
			DrawCube((Vector3){0,0,0}, 0, 0, 0, BLANK);
		}
		
		DrawGrid(100, 4.0f);

		EndMode3D();
        EndDrawing();
    }

    return 0;
}
```

Here is the whole project
[raylib_bug.zip](https://github.com/raysan5/raylib/files/5322893/raylib_bug.zip)

**Comment by AlbertoFrancoDD** [comment]
I believe this is a problem with the fact that you are never drawing the elements. To keep the batch small the limit is at 8192 elements but you can increase it (say to 64K) and then you will be able to draw more elements in the same draw call. An alternative would be to call `rlglDraw()` in your loop.

**Comment by raysan5** [comment]
@Tkap1 I tried your example with 890 and it works ok for me. Are you using latest raylib from GitHub master branch?

This issue should be solved.

**Comment by raysan5** [comment]
@Tkap1 Checking your GIF, you are using raylib 3.0, please, could you try with latest raylib from GitHub? This issue should be resolved by now.

Feel free to reopen the issue if problem persists.
