### ISSUE TITLE
UWP compiling problem

### ISSUE THREAD

**Issue by bosoni** [raysan5/raylib#1402]
UWP doesnt compile because of miniaudio.h. There is now issue so when it is fixed, miniaudio.h should be updated.
https://github.com/mackron/miniaudio/issues/199

**Comment by bosoni** [comment]
Fix is in miniaudio dev branch and it works. It will be in the next miniaudio master version.

**Comment by raysan5** [comment]
ok, nice

**Comment by bosoni** [comment]
miniaudio is now version 0.10.20 so you can update raylib's miniaudio and close this issue.
