### ISSUE TITLE
[raymath] compile issue

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1403]
In file included from src/main.c:27:
    ../raylib/src/raymath.h: In function 'QuaternionFromMatrix':
    ../raylib/src/raymath.h:1331:5: error: missing initializer for field 'y' of 'Quaternion' {aka 'struct Vector4'} [-Werror=missing-field-initializers]
     1331 |     Quaternion result = { 0.0f };
          |     ^~~~~~~~~~
    compilation terminated due to -Wfatal-errors.
    cc1: all warnings being treated as errors
    make: *** [Makefile:23: obj/main.o] Error 1

Line 1331 should of course read

    Quaternion result = { 0 };

**Comment by raysan5** [comment]
@chriscamacho Wow! Good catch! Actually I didn't understand properly the aggregate initializations! C language still surprises me! :D

**Comment by chriscamacho** [comment]
yeah for a "simple" language the details can be fun!

I think in this specific case its not much more than a theoretical issue as all members of result are always overwritten.

I can see it potentially causing a difficult to track error though, you think you are initialising every member but only the first one actually is. urgh!  its interesting that I only actually caught this with -Wextra (you'd thiink -Wall would be all!)  

Now - the reason I use 

   -Wfatal-errors -pedantic -Wall -Wextra -Werror -std=c99

is just so I can catch these corner cases in my own code, I do wonder if these flags might be a good idea for the raylib as it should catch the really difficult to find bugs. (and you never know it might encourage new coders to actually read and understand compiler warnings!)

The main issue would be with the externals, this could be mitigated by upstream PR's or if really needed applying patches on updating individual externals (which I know if far from ideal)

Another solution would be to have strict flags for the raylib itself and different ones for externals

anyhow just worth thinking about, could save lots of debugging time !
