### ISSUE TITLE
[wiki] Minor issue with the Home page.

### ISSUE THREAD

**Issue by carlsmith** [raysan5/raylib#1404]
I just lightly edited [the Home page of the wiki][1] and am having trouble with the second bullet point (my emphasis):

+ The second section ... includes information about library compilation on different platforms, and *library usage on games/apps/tools development*.

What does *library usage on games/apps/tools development* mean? The second section of the wiki only seems to include docs on building raylib across platforms, so the last part of the sentence seems redundant (as well as unclear).

[1]: https://github.com/raysan5/raylib/wiki

**Comment by raysan5** [comment]
@carlsmith that page was written with a bit of rush, I'm neither a native English speaker so there could be issues... feel free to edit it.

**Comment by carlsmith** [comment]
Thank you, @raysan5. Will do.

It's well written. I haven't needed to rewrite anything. I'm just editing little things as I read through it.

**Comment by chriscamacho** [comment]
@carlsmith please do keep up with the wiki edits, should you have specific technical questions about raylib I would be happy to take some load off Ray - you can contact me via my github profile homepage link.
