### ISSUE TITLE
[models] OBJ loader diffuse colour issue

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1406]
This can be seen when attempting to use assets (from the highly recommended) kenney.nl - many other artists use this method for material handling, as you can have good simple looking low poly models without the need of extra texture resources.

Looking at a sample material file

    # Created by Kenney (www.kenney.nl)

    newmtl crystal
    Kd 0.1862318 0.8773585 0.5934362

    newmtl metal
    Kd 0.8431373 0.8705882 0.9098039

    newmtl metalRed
    Kd 1 0.6285242 0.2028302

    newmtl metalDark
    Kd 0.6750623 0.7100219 0.7735849

    newmtl dark
    Kd 0.2745098 0.2980392 0.3411765

so all the materials are simply *different* diffuse colours

However when loaded the model is just a single colour. rather than showing different material colours.

I'm posting this before looking into it, but not sure if I will get chance, if you see an easy fix, do let me know!

**Comment by chriscamacho** [comment]
okay, this one escapes me, first of all I modified LoadObj to show me the materials

    INFO: MODEL: [alien.obj] OBJ data loaded successfully: 6 meshes / 5 materials
    INFO: Kd = 0.186232 0.877358 0.593436 0.000000
    INFO: material 0 diffuse 47 223 151 255
    INFO: Kd = 0.843137 0.870588 0.909804 0.000000
    INFO: material 1 diffuse 215 221 232 255
    INFO: Kd = 1.000000 0.628524 0.202830 0.000000
    INFO: material 2 diffuse 255 160 51 255
    INFO: Kd = 0.675062 0.710022 0.773585 0.000000
    INFO: material 3 diffuse 172 181 197 255
    INFO: Kd = 0.274510 0.298039 0.341177 0.000000
    INFO: material 4 diffuse 69 75 87 255
    INFO: VAO: [ID 4] Mesh uploaded successfully to VRAM (GPU)
    INFO: after loading material 0 diffuse 47 223 151 255
    INFO: after loading material 1 diffuse 215 221 232 255
    INFO: after loading material 2 diffuse 255 160 51 255
    INFO: after loading material 3 diffuse 172 181 197 255
    INFO: after loading material 4 diffuse 69 75 87 255

so the model actually *does* have the correct diffuse colours in the materials....

(I'm using the default shader btw but also tried basic lighting shader)

I commented out the diffuse / tint mixing in DrawModelEx

    for (int i = 0; i < model.meshCount; i++)
    {
        // TODO: Review color + tint premultiplication mechanism
        //Color color = model.materials[model.meshMaterial[i]].maps[MAP_DIFFUSE].color;

        //Color colorTint = WHITE;
        //colorTint.r = (unsigned char)((((float)color.r/255.0)*((float)tint.r/255.0))*255.0f);
        //colorTint.g = (unsigned char)((((float)color.g/255.0)*((float)tint.g/255.0))*255.0f);
        //colorTint.b = (unsigned char)((((float)color.b/255.0)*((float)tint.b/255.0))*255.0f);
        //colorTint.a = (unsigned char)((((float)color.a/255.0)*((float)tint.a/255.0))*255.0f);

        //model.materials[model.meshMaterial[i]].maps[MAP_DIFFUSE].color = colorTint;
        
        rlDrawMesh(model.meshes[i], model.materials[model.meshMaterial[i]], model.transform);
        //model.materials[model.meshMaterial[i]].maps[MAP_DIFFUSE].color = color;
    }

Now with all that butchery I would expect that I'm FORCING it to use the diffuse colour, but no *every* material is rendered the same colour...

I have NO clue what the issue is here!

**Comment by chriscamacho** [comment]
BTW the colour that's used on all the materials is material zero's diffuse colour....

**Comment by chriscamacho** [comment]
okay its just dawned on me I see the issue now!

for (int i = 0; i < model.meshCount; i++)
{
    // TODO: Review color + tint premultiplication mechanism
    
    ...
    
    rlDrawMesh(model.meshes[i], model.materials[model.meshMaterial[i]], model.transform);

this is assuming that mesh[i] uses material[i]

The obj loader needs to handle multiple sub meshes as provided my tinyobjloader so each mesh can have its own material....

**Comment by chriscamacho** [comment]
I have the multiple meshes loaded in a single model, however it looks like attrib.material_ids[m] is always returning -1

... I'm close!

**Comment by chriscamacho** [comment]
Have I hit the hashmap issue....? AFAICT this issue is with tinyobjloader, its just NOT giving any material ID's for the meshes, they are always all -1 !!!

**Comment by chriscamacho** [comment]
okay fixed the broken hashmap lookup.... but then realised materials are per face not just per mesh DOH!

so I need to think about the best way to change the model not into the OBJ sub meshes but into a sub meshes grouped by material ID....

**Comment by chriscamacho** [comment]
cracked it !!!

![obj-loader](https://user-images.githubusercontent.com/716361/95302169-7ad86880-0879-11eb-90cd-d46c522d9ba5.png)

this is an UNtextured OBJ with basic lighting shader and a bluish tint (drawModel colour)
its has a separate sub mesh per material, the meshes are picked out of the single blob of faces you get from the obj loader,  OBJ sub mesh's are not split out per material...! 

I need to ahem, do some tidying I'll probably get to doing a PR later today....

**Comment by raysan5** [comment]
@chriscamacho Very nice work, looks good.

**Comment by chriscamacho** [comment]
closing this as I fixed the issue, see PR #1408
