### ISSUE TITLE
[core] Segmentation fault during DIFFUSE_MAP texture assignment to Heightmap Model

### ISSUE THREAD

**Issue by Hairein** [raysan5/raylib#1409]
### Issue description

I've got a problem with the current GitHub Raylib version (master,8thOct2020) usage of materials with the height map generation, it causes a segmentation fault during DIFFUSE_MAP texture assignment. I've made a small Linux sample project (main.c, makefile, heightmap.png) to show the problem with the online heightmap example code adapted. 
Older version of Raylib on another computer works fine.

### Environment

OS: Linux Mint 19.3 Tricia x86_64 
Kernel: 5.4.0-47-generic 
Shell: bash 4.4.20 
Resolution: 1920x1080 
DE: Cinnamon 4.4.8 
WM: Mutter (Muffin) 
CPU: Intel i5-4210U (4) @ 2.700GHz 
GPU: Intel Integrated Graphics 
GPU: NVIDIA GeForce 940M 
Memory: 3117MiB / 7887MiB 

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce 940M/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 435.21
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 435.21
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 435.21
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

### Issue Screenshot

Command line exception only, no screenshot.

### Code Example

```
Image image = LoadImage("./heightmap.png");             
Texture2D texture = LoadTextureFromImage(image);                
Mesh mesh = GenMeshHeightmap(image, (Vector3){ 16, 8, 16 });    
Model model = LoadModelFromMesh(mesh);                          
model.materials[0].maps[MAP_DIFFUSE].texture = texture;  // Exception on assignment to model.materials[0]

```
Small sample project (main.c,makefile, heightmap.png): [example gcc makefile project](https://www.micahkoleoso.de/generic_data/RaylibMaterialProblem.zip)

**Comment by chriscamacho** [comment]
hi, 

can you check with the very latest version of raylib from github, I'm unable to replicate this on Linux

**Comment by kernelkinetic** [comment]
@Hairein You could also run your project using a debugger like `gdb` to hopefully get more information about the possible source of error.

**Comment by Hairein** [comment]
Hi there, I just did this and this is what I get with the example project (listed the whole process done below, deleted the ./example before make start):
'Speicherzugriffsfehler' is the access violation error in German.

mkoleoso@AspireE5:~/GitHub/raylib$ git pull
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 5), reused 2 (delta 2), pack-reused 0
Entpacke Objekte: 100% (6/6), Fertig.
Von https://github.com/raysan5/raylib
   41192c6d..6ebf6b4e  master     -> origin/master
Aktualisiere 41192c6d..6ebf6b4e
Fast-forward
 src/external/tinyobj_loader_c.h |  40 ++++++--
 src/models.c                    | 209 ++++++++++++++++++++--------------------
 2 files changed, 136 insertions(+), 113 deletions(-)

mkoleoso@AspireE5:~/GitHub/raylib$ cd src
mkoleoso@AspireE5:~/GitHub/raylib/src$ make PLATFORM=PLATFORM_DESKTOP
gcc -c models.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -fPIC -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
models.c: In function ‘LoadOBJ’:
models.c:2973:9: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
         chdir(GetDirectoryPath(fileName));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
models.c:3114:9: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
         chdir(currentDir);
         ^~~~~~~~~~~~~~~~~
ar rcs /home/mkoleoso/GitHub/raylib/libraylib.a core.o shapes.o textures.o text.o utils.o rglfw.o models.o raudio.o
raylib static library generated (libraylib.a) in /home/mkoleoso/GitHub/raylib!

mkoleoso@AspireE5:~/GitHub/raylib/src$ sudo make install
[sudo] Passwort für mkoleoso:         
mkdir --parents --verbose /usr/local/lib
mkdir --parents --verbose /usr/local/include
cp --update --verbose /home/mkoleoso/GitHub/raylib/libraylib.a /usr/local/lib/libraylib.a
'/home/mkoleoso/GitHub/raylib/libraylib.a' -> '/usr/local/lib/libraylib.a'
cp --update raylib.h /usr/local/include/raylib.h
cp --update raymath.h /usr/local/include/raymath.h
cp --update rlgl.h /usr/local/include/rlgl.h
cp --update physac.h /usr/local/include/physac.h
raylib development files installed/updated!
mkoleoso@AspireE5:~/GitHub/RaylibMaterialProblem$ ls
heightmap.png  main.c  Makefile
mkoleoso@AspireE5:~/GitHub/RaylibMaterialProblem$ make
gcc -g -Wall -o example main.c -I/usr/local/include -L/usr/local/lib -lraylib -lGL -lpthread -ldl -lrt -lX11 -lm 

mkoleoso@AspireE5:~/GitHub/RaylibMaterialProblem$ ./example 
INFO: Initializing raylib 3.1-dev
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: GeForce 940M/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 435.21
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: Supported extensions count: 353
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: GL: Mirror clamp wrap texture mode supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: FILEIO: [./heightmap.png] File loaded successfully
INFO: IMAGE: [./heightmap.png] Data loaded successfully (128x128)
INFO: TEXTURE: [ID 3] Texture created successfully (128x128 - 1 mipmaps)
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
Speicherzugriffsfehler (Speicherabzug geschrieben)
mkoleoso@AspireE5:~/GitHub/RaylibMaterialProblem$

**Comment by kernelkinetic** [comment]
@Hairein You can run your example program using gdb debugger with `gdb example`, which should show you a `Program received signal SIGSEGV, Segmentation fault.` after a time and then you can input `backtrace` and hit enter to get more information _where_ the problem occurs.

**Comment by Hairein** [comment]
Hi again, running the example with "ddd ./example" to debug gives this output:
main.c:35 is the line: model.materials[0].maps[MAP_DIFFUSE].texture = texture; 

---------------------------------------------------------------------------------------------
GNU DDD 3.3.12 (x86_64-pc-linux-gnu), by Dorothea LRegistered pretty printers for UE4 classes
Reading symbols from ./example...fertig.
(gdb) run
Starting program: /home/mkoleoso/GitHub/RaylibMaterialProblem/example 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
INFO: Initializing raylib 3.1-dev
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: GeForce 940M/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 435.21
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: Supported extensions count: 353
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: GL: Mirror clamp wrap texture mode supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: FILEIO: [./heightmap.png] File loaded successfully
INFO: IMAGE: [./heightmap.png] Data loaded successfully (128x128)
INFO: TEXTURE: [ID 3] Texture created successfully (128x128 - 1 mipmaps)
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)

Program received signal SIGSEGV, Segmentation fault.
0x000055555555505c in main () at main.c:35
(gdb)

**Comment by kernelkinetic** [comment]
@Hairein Nice, someone who uses `ddd` 👍 😀  So thanks for the output, maybe @chriscamacho got now an additional hint.

**Comment by chriscamacho** [comment]
@Hairein this is going to sound like it won't work! but I had a very similar issue....

*completely* delete the raylib directory

re-clone from raysan5/raylib (make sure you're not using a fork !)

recompile raylib *then* recompile your test...


when getting a back trace you need to....

RAYLIB_BUILD_MODE=DEBUG make -j8

you need to add -g flag to your test project

**Comment by Hairein** [comment]
Yes, thanks, that worked for me this time! 
I saw that although I had  previously performed "sudo make uninstall", some raylib libraries did remain in "/usr/local/lib", which I deleted manually before doing the steps you stated above.

So, I'm OK now and this issue can be closed. 
Many thanks and regards,
Hairein

**Comment by raysan5** [comment]
@Hairein nice! 👍😄

**Comment by chriscamacho** [comment]
@raysan5  would love to know what that actually was, being as I think i hit it too.... (odd!) ah well!
