### ISSUE TITLE
[core] raylib.h clashes with Windows.h

### ISSUE THREAD

**Issue by AlbertoFrancoDD** [raysan5/raylib#1414]
### Issue description
When including windows.h alongside with raylib.h there are function clashes because of no namespacing in raylib. This happens with other libraries too (e.g. eigen with Matrix) 

### Code Example
Easy enough to reproduce with the following code in windows

```C++
#include <Windows.h> 
#include <raylib.h> 
```

**Comment by CodingCor** [comment]
I didn't even need to include a Windows Library by myself. When i tried to build the example Project in Windows using CMake just a few Minutes ago the same error occured.

**Comment by jamesl-github** [comment]
which example project ?           
I've built raylib many times on MS Windows 10 and mingw64-w64 version  x86_64-7.3.0-posix-seh-rt_v5-rev0 
never had a problem

**Comment by CodingCor** [comment]
The one provided in the CMake Tutorial. When compiling MinGW tries to include winuser.h somewhere, with that include the function name clashes are raised.

**Comment by raysan5** [comment]
Yes, `windows.h` symbol collisions is an known issue. Here it is a workaround: https://github.com/raysan5/raylib/issues/1217
