### ISSUE TITLE
[rlgl] Batch elements overflow (MAX_BATCH_ELEMENTS)

### ISSUE THREAD

**Issue by Tkap1** [raysan5/raylib#1417]
https://github.com/raysan5/raylib/issues/1401
I don't think I can reopen an issue that someone else closed, so I am creating a new one.

I've updated to the latest version, and the problem still happens for me.

Just in case I'm doing something wrong, this is the whole process that I went through:
1) git clone https://github.com/raysan5/raylib
2) go into raylib\projects\VS2017 and open raylib.sln
3) Rebuild (tried both Release.DLL and DEBUG.DLL)
4) Copy the generated raylib.lib and raylib.dll into my project folder
5) Paste the code from the previous issue
6) Compile my code (/W4, 0 warnings, 0 errors)

Here is the updated GIF: https://gfycat.com/keenfoolishheterodontosaurus

Also, while playing around in a real project, I got the view messing up thing to happen even without using DrawGrid. It seems to happen at an arbitrary amount of draw calls.

**Comment by raysan5** [comment]
@Tkap1 why are you doing this?
```c
    static int draw_count = 890;
    draw_count++;
    for(int i = 0; i < draw_count; i++)
    {
        DrawCube((Vector3){0,0,0}, 0, 0, 0, BLANK);
    }
```
You are incrementing the cubes to draw 890 + 60*frame, that's too much, my GPU just freezes while testing.

Could you provide another example with a fixed number of cubes with the same result, I can not test it properly with those lines. When using just 890 cubes, it works perfectly, so, I have no way to find a solution.

**Comment by Tkap1** [comment]
@raysan5 

>  Is this a real use case?

This drawing approach is just to illustrate my problem, not a real use case. It came up in a real project while drawing around 1000 small cubes, so I stripped my project down to the bare minimum that could reproduce the bug.

> Additionally, that drawing approach does not seem the best one to me, why are you incrementing 60 cubes each frame? 

I'm not incrementing 60 cubes per frame, I'm incrementing 1 cube per frame.

> Could you provide another example with a fixed number of cubes with the same result, I can not test it properly with those lines.

Yes. 

```
static int draw_count = 898;
for(int i = 0; i < draw_count; i++)
{
	DrawCube((Vector3){0,0,0}, 0, 0, 0, BLANK);
}
```
https://gfycat.com/HonoredHatefulBass
I'm guessing this is somehow GPU related and hard to reproduce for others without the same card.

Also, don't know if it matters, but I compiled raylib (didn't make any changes) and my project as x64

**Comment by raysan5** [comment]
@Tkap1 Sorry, I meant 60 frames per second, not per frame.

Ok, trying with 898 cubes I can reproduce the issue! Now I can look into it! :D
