### ISSUE TITLE
[camera] Rename Camera3D.type to Camera3D.projection

### ISSUE THREAD

**Issue by GoldenThumbs** [raysan5/raylib#1418]
Currently in raylib the setting/property relating to camera projection is called `type`. I feel that is very confusing, especially with all the camera *mode* stuff. A beginner could very easily get confused by this naming convention, so my suggestion is to rename the `Camera3D` property from `type` to `projection`. 
I'd also like to propose changing `CAMERA_PERSPECTIVE` and `CAMERA_ORTHOGRAPHIC` to `PROJECTION_PERSPECTIVE` and `PROJECTION_ORTHOGRAPHIC`.

Thoughts on these changes? They are minor API changes that would break existing examples, but I feel they are worth it for simplifying the naming convention.
A thought that occurs is that it could be a change in the next major release instead of a minor release.

**Comment by jamesl-github** [comment]
> They are minor API changes that would break existing example      
could you stick a #define in there somewhere so PROJECTION_ORTHOGRAPHIC would "overwrite" CAMERA_ORTHOGRAPHIC

**Comment by GoldenThumbs** [comment]
@jamesl-github not a fan of that solution. Kind of seems like a bad way to handle that. Still, would be nice so it doesn't break compatibility.... IDK, to me this seems like the kind of thing that shouldn't *have* a define that changes it. One or the other, not both.

**Comment by raysan5** [comment]
I won't apply this change for the moment, it would break lots of things... maybe for 4.0...
