### ISSUE TITLE
[core] Cursor/window position offset issue

### ISSUE THREAD

**Issue by Zizap5** [raysan5/raylib#1419]
When creating a window it is not at the intended position. This only happens when the height matches the monitor height (which is in my case 1080). The screen position no longer matches the cursor position.

Example code:

```c
#include "raylib.h"

int main(void){
    InitWindow(1920, 1080, "");
    //this one works: InitWindow(1920, 1050, "");
    SetTargetFPS(60);
    while(!WindowShouldClose()){
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawCircleV(GetMousePosition(), 5, RED);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```

Edit:
UndecorateWindow is not the problem as I first thought. However, windowed mode (decorated or not) is. In fullscreen mode this works fine.

**Comment by Zizap5** [comment]
Finally found a reasonable workaround:

````c
#include "raylib.h"

int main(void){
    SetConfigFlags(FLAG_WINDOW_UNDECORATED);  // <--- :-)
    InitWindow(1920, 1080, "");
    SetTargetFPS(60);
    while(!WindowShouldClose()){
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawCircleV(GetMousePosition(), 5, RED);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
````

**Comment by raysan5** [comment]
raylib has some security checks to avoid placing the Window outside of the display area.

Using `FLAG_WINDOW_UNDECORATED` is the best option.
