### ISSUE TITLE
[models] MeshNormalsSmooth() is not efficient and probably wrong

### ISSUE THREAD

**Issue by trikko** [raysan5/raylib#1421]
```MeshNormalSmooth()``` takes a vertex and iterates all the others, looking for vertices with a distance < epsilon.
Then it calculates their normals and sums it.

That's not a good idea, IMO:
- Two close vertices can be not physically linked, I don't think summing normals makes sense.
- It's quadratic.

A simpler and faster way to smooth a model could be:
- Iterating through each triangle
- Summing the three vertex normals
- Adding the sum to an accumulator for each triangle's vertex

You must check for vertex duplicates: each vertex must accumulate normals from all triangles it belongs to.
Then you should iterate through all vertices and set each normal using the normalized version of the sum accumulated.

[Here](https://gist.github.com/trikko/730fba00cef7ecebf4b7221f9a2d9182) a quick&dirty implementation in D by me. Its syntax is close to C, but C doesn't include hashmap (I use a hashmap to keep track of duplicates). So translation is not easy.

[A video showing the smoothing result in D](https://www.youtube.com/watch?v=RIVDdXV6D-A). Running @ 60fps. ```MeshNormalSmooth()``` gives me a worse result and it runs at 7fps.

**Comment by raysan5** [comment]
Just copying the D solution for convenience:
```d
void Smooth(Mesh *mesh, bool enabled=true)
{
    Vector3[Vector3] linkedNormals;
    size_t idx = 0;

    foreach(tri; mesh.vertices[0..mesh.vertexCount*3].chunks(9))
    {
        Vector3 v1 = Vector3(tri[0], tri[1], tri[2]);
        Vector3 v2 = Vector3(tri[3], tri[4], tri[5]);
        Vector3 v3 = Vector3(tri[6], tri[7], tri[8]);

        Vector3 normalV1 = Vector3CrossProduct(Vector3Diff(v2,v1), Vector3Diff(v3,v1));
        Vector3 normalV2 = Vector3CrossProduct(Vector3Diff(v3,v2), Vector3Diff(v1,v2));
        Vector3 normalV3 = Vector3CrossProduct(Vector3Diff(v1,v3), Vector3Diff(v2,v3));

        Vector3 sum = Vector3Add(Vector3Add(normalV1, normalV2), normalV3);
        
        if (enabled)
        {            
            if (v1 !in linkedNormals) linkedNormals[v1] = Vector3Zero;
            if (v2 !in linkedNormals) linkedNormals[v2] = Vector3Zero;
            if (v3 !in linkedNormals) linkedNormals[v3] = Vector3Zero;

            linkedNormals[v1] = Vector3Add(linkedNormals[v1], sum);
            linkedNormals[v2] = Vector3Add(linkedNormals[v2], sum);
            linkedNormals[v3] = Vector3Add(linkedNormals[v3], sum);
        }
        else 
        {
            Vector3 nor = Vector3Normalize(sum);

            foreach(k;0..3)
            {
                mesh.normals[idx + k*3 + 0] = nor.x;
                mesh.normals[idx + k*3 + 1] = nor.y;
                mesh.normals[idx + k*3 + 2] = nor.z;
            }
            
        }

        idx+=9;
    }

    if(enabled)
    {
        idx = 0;
        foreach(v; mesh.vertices[0..mesh.vertexCount*3].chunks(3))
        {
            Vector3 cur = Vector3(v[0], v[1], v[2]);
            Vector3 nor = Vector3Normalize(linkedNormals[cur]);

            mesh.normals[idx + 0] = nor.x;
            mesh.normals[idx + 1] = nor.y;
            mesh.normals[idx + 2] = nor.z;
            
            idx += 3;
        }    
    }

    rlUpdateMesh(*mesh, 2, mesh.vertexCount);
}
```

**Comment by raysan5** [comment]
Current implementation is probably wrong and it should be reimplemented from scratch.
In the meantime, I prefer to remove the function.

**Comment by raysan5** [comment]
I'm closing this issue. At this point, it's up to the user that owns the mesh to smooth it or use an external software for it.
