### ISSUE TITLE
[models] should check and warn for untriangulated OBJ's

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1426]
I have a small OBJ that used to load but now doesn't causing the above issue (and abort)

Will attach zipped OBJ

**Comment by chriscamacho** [comment]
[rocket.zip](https://github.com/raysan5/raylib/files/5482334/rocket.zip)

OBJ that causes the issue

**Comment by chriscamacho** [comment]
other single mesh single materials obj's load including ones exported from blender

**Comment by chriscamacho** [comment]
got a 404 first time i posted didn't realise it had worked...

**Comment by Skabunkel** [comment]
What version of raylib are you using?

**Comment by chriscamacho** [comment]
turns out the model had quads in it, but I could have sworn it was working previously!

at any rhate, whats the best way to detect if the model isn't triangulated...?

rather than a random memory corruption(!) There should be some sensible failure message - title of this bug maybe needs changing!

**Comment by chriscamacho** [comment]
I was very suspicious it could have been my past commit to split the meshes into material meshes that broke something !

**Comment by chriscamacho** [comment]
removing the trianglation flag when loading OBJ stops it crashing, but obviously messes up the model..

not sure exactly whats going on, but splitting meshes up by material still isn't out of the woods yet.

any thoughts about how you'd like to handle this ?

**Comment by raysan5** [comment]
@chriscamacho technically, triangulation of quads should not influence splitting meshes... maybe an issue with tinyobjloader-c?

**Comment by chriscamacho** [comment]
maybe not updatiing mesh offsets or something, I dunno, it *should* just work, tiny obj has all the verts in one blob with the meshes haviing aa length and offset. adding extra verts seems to be messing with it but I can see how

**Comment by chriscamacho** [comment]
@raysan5 can you look at updating the external (tiny obj loader) I looked but not having a great deal of look with new loader callback...

**Comment by chriscamacho** [comment]
@raysan5  can I suggest you roll back to before my materials mesh PR, it might make issues easier to find, even trying with the latest version of tiny_obj_loader I'm seeing lockup issues with larger OBJ's 

I'm still not seeing what is happening when on the fly triangulation is happening.

**Comment by chriscamacho** [comment]
discovered a few more OBJ's that lock up the loader, again I think this is another hashmap issue, but I can't see exactly what it is, is it worth me writing an OBJ loader from scratch... ?

**Comment by raysan5** [comment]
It seems at this point LoadOBJ() stopped working... :(   #1434

**Comment by raysan5** [comment]
`LoadOBJ()` requires a full review. I put it on my TODO list. Closing this issue for now.
