### ISSUE TITLE
Why not call it a media library?

### ISSUE THREAD

**Issue by danger89** [raysan5/raylib#1436]
Consider renaming it from 'gaming library' to media library. Just like SDL and SFML.

I mean, its not really a full-blown game library or engine, but that is the strength I think.

I will try to use raylib of creating an actual desktop application. I think that would also be possible right? If so, try to include this somewhere in your README, and brother the scope of the use of raylib 👍🏽 .

Regards,
Melroy van den Berg

**Comment by assyrianic** [comment]
Because the intent of Raylib is for the creation of games as opposed to other forms of media. Most of the API and the general library architecture is geared towards game development.

**Comment by danger89** [comment]
I know, but it doesn't need to be. In fact there is already a whole [raygui](https://github.com/raysan5/raygui) project.

I just want to say you may want to extend the usage of raylib. Why not? Promote also application development on the website.

**Comment by assyrianic** [comment]
but that's the overall purpose of Raylib. If you wish to use it for purposes that aren't gaming, there's nothing stopping you, but the intent for raylib is to provide an easy-to-use pure C API for quicker game development.

**Comment by jamesl-github** [comment]
this is funny because people on the SFML forums are always asking why do you call it SFML "Simple and Fast Multimedia Library" when most people use it to make games -- why don't you call it a game library

**Comment by danger89** [comment]
> this is funny because people on the SFML forums are always asking why do you call it SFML "Simple and Fast Multimedia Library" when most people use it to make games -- why don't you call it a game library

LOL, yeah true, it's because people don't know what they are talking about. And don't know the differences.

**Comment by raysan5** [comment]
@danger89 raylib started as a videogames library to teach my students and I like to keep the original description, actually, that's probably the most common use for the library, learn (and enjoy) videogames programming.

And yes, raylb can be sued to create desktop/web applications, I use it for that: https://raylibtech.itch.io/
