### ISSUE TITLE
[raymath] MatrixLookAt Performance

### ISSUE THREAD

**Issue by RandomErrorMessage** [raysan5/raylib#1439]
The MatrixLookAt calls the rather costly InvertMatrix function, I found this odd since every other implementation of a LookAt function I've seen does not do this. Eg. https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/lookat-function

Am I missing something? Should this be refactored?

**Comment by raysan5** [comment]
@RandomErrorMessage This function was implemented long time ago, maybe it could be refactored... Just take into account that raylib matrices are right-handed, column major.
