### ISSUE TITLE
[core] Several functions allocate memory inside raylib but do not provide functions to deallocate it

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib#1440]
Functions like GetImageData allocate memory inside Raylib but do not provide any functions to deallocate the memory.
Currently the only options are to leak the memory, or free it from within the client code.
On Windows when using Raylib as a dll calling free from the client code will cause a debug assert because the memory was allocated from the DLL module and must be deallocated in the same module. There needs to be a function that causes raylib to free the memory from within the module itself.

This is only a problem on Windows (Visual Studio 2019) when using raylib as a DLL. Static linking does not have this problem, but static linking is not viable in a real windows subssytem application because of name conflicts with some raylib functions (CloseWindow, ShowCursor, etc...)

The specific assert is 
**
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 996

Expression: __acrt_first_block == header
**

### Code Example
The simplest way to see the problem is to build an application that links raylib as Debug.DLL and call code similar to this.

Color* imageData = GetImageData(imagePath);
// read image data or whatever.
free(imageData)

**Comment by raysan5** [comment]
I reviewed all raylib functions and here it is a list with the functions allocating memory:

| Function with MEM_ALLOC | Function to MEM_FREE | Possible solutions |
| :--------- | :----- | :--------- |
| LoadFileData() | ❗ | IDEA: UnloadFileData() / MemFree() |
| LoadFileText() | ❗ | IDEA: UnloadFileData() / MemFree() |
| GetDirectoryFiles() | ✔️ ClearDirectoryFiles() | Using `Get/Clear` convention |
| GetDroppedFiles() | ✔️ ClearDroppedFiles() | Using `Get/Clear` convention |
| CompressData() | ❗ | USE: MemFree()? |
| DecompressData() | ❗ | USE: MemFree()? |
| GetImageData() | ❗ | IDEA: LoadImageColors() / UnloadImageColors()? |
| GetImagePalette() | ❗ | IDEA: LoadImagePalette() / UnloadImagePalette()? |
| _GetImageDataNormalized()_ | _not any more_ | REMOVED: https://github.com/raysan5/raylib/commit/d6f4f3ee88a1eaa77acba4ae9aab7ed2e52049bf |
| LoadFontData() | ✔️ UnloadFontData() | ADDED: https://github.com/raysan5/raylib/commit/14c1ee268107b2de727c2820e56a333b85ebc500 |
| TextReplace() | ❗ | IDEA: TextFree() / MemFree() |
| TextInsert() | ❗ | IDEA: TextFree() / MemFree() |
| TextToUtf8() | ❗ | IDEA: TextFree() / MemFree() |
| GetWaveData() | ❗ |  IDEA: LoadWaveSamples()/UnloadWaveSamples()? |

It seems for most cases providing a `MemFree()` function should be enough but in that case it's up to the user to do a right use of the function over the raylib internal-allocated memory. Adding some TRACELOG info message could be useful in some cases...

Alternatively, providing a `Load*()/Unload*()` functions pairs could seem more intuitive to novel users.

**Comment by JeffM2501** [comment]
In my option keeping parity with load/unload would be best, it is excessive, but consistency in the API is better for users in this case.

**Comment by raysan5** [comment]
Two additional functions have been exposed (`MemAlloc()` / `MemFree()`) for advance users requiring access to the library internal allocation mechanisms.
