### ISSUE TITLE
[model] missing RL_FREE

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1446]
around line 3100 (near end of LoadOBJ) there is an RL_FREE missing (commented out??), also the material counts haven't been freed

    //RL_FREE(fileData);

should be

    RL_FREE(fileData);
    RL_FREE(matFaces);

untriangulated meshes are still causing seg faults, no idea what's happening there...

**Comment by chriscamacho** [comment]
also notice diffuse colour doesn't seem to be working, works okay with my OBJ loader, so its not rlgl ... quite a puzzle!

**Comment by raysan5** [comment]
I'll try to review `LoadOBJ()` more carefully when I have time...
