### ISSUE TITLE
[question] Linking issue with raylib as external dependency.

### ISSUE THREAD

**Issue by CyVlBel** [raysan5/raylib#1447]
### Issue description

Cannot link with prebuilt binary raylib_static.lib in my project. 

### Environment

I'm using Windows, Microsoft Visual Studio 2019, C++17, glfw3 latest raylib (from repository)

### Issue Screenshot
![изображение](https://user-images.githubusercontent.com/43202094/100765272-5f688480-3408-11eb-8830-8c059db2ff53.png)
This is my project properties
![изображение](https://user-images.githubusercontent.com/43202094/100765798-f2a1ba00-3408-11eb-94b7-b7c6effcc505.png)
![изображение](https://user-images.githubusercontent.com/43202094/100765829-fdf4e580-3408-11eb-868a-08a4f2669c01.png)

### Code Example

I've tried to run code of some example (just copy&paste it in my entry point). 
```C++
#include <iostream>
#include "raylib/raylib.h" 


int main(void)
{
    // Initialization
//--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - mouse input");

    Vector2 ballPosition = { -100.0f, -100.0f };
    Color ballColor = DARKBLUE;

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //---------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        ballPosition = GetMousePosition();

        if (IsMouseButtonPressed(MOUSE_LEFT_BUTTON)) ballColor = MAROON;
        else if (IsMouseButtonPressed(MOUSE_MIDDLE_BUTTON)) ballColor = LIME;
        else if (IsMouseButtonPressed(MOUSE_RIGHT_BUTTON)) ballColor = DARKBLUE;
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

        ClearBackground(RAYWHITE);

        DrawCircleV(ballPosition, 40, ballColor);

        DrawText("move ball with mouse and click mouse button to change color", 10, 10, 20, DARKGRAY);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by terrehbyte** [comment]
You might be missing some additional external dependencies that are specific for Windows. Check the table in the [wiki](https://github.com/raysan5/raylib/wiki/raylib-dependencies) for `DESKTOP:Windows` and make sure that you're adding them to your Additional Dependencies property.

In this specific case, your LNK2019 errors in the output in your screenshot suggest that you need to additionally link with `winmm.lib`.

**Comment by CyVlBel** [comment]
> the

many thanx! This solved my problem.
