### ISSUE TITLE
[models] GenMeshHemiSphere seg faults if rings or slices < 3

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1454]
basically as title, I'd suggest simply checking the parameters and setting them to 3 if they are less than three, possibly with a warning to the tracelog...

**Comment by raysan5** [comment]
@chriscamacho Oh, nice catch! Feel free to send a PR with the fix.

**Comment by chriscamacho** [comment]
you do realise that doing a PR for simple things is a PITA? its 30 seconds for you but by the time I've forked, cloned, done the fix and submitted the PR itself, I've probably lost more than 1/2hr for a 30 second fix, worth doing it for a major feature but github is a pita for submitting quick simple fixes, then again I could be holding it wrong...

**Comment by raysan5** [comment]
@chriscamacho Believe me, it's not 30 seconds for me. But ok, I'll check it carefully when I will have time and I could focus on this.
