### ISSUE TITLE
[examples] text_input_box.c writes out of array bounds

### ISSUE THREAD

**Issue by Buhlean** [raysan5/raylib#1455]
### Issue description

In https://github.com/raysan5/raylib/blob/master/examples/text/text_input_box.c ,
this code:

```
if (IsKeyPressed(KEY_BACKSPACE))
{
  letterCount--;
  name[letterCount] = '\0';

  if (letterCount < 0) letterCount = 0;
}
```

writes at position -1 if we started with a letterCount of 0 (which is the default value). That is tested for, but only after we already wrote there.

### Environment

WIN64

### Issue Screenshot

Unnecessary.

### Code Example

https://github.com/raysan5/raylib/blob/master/examples/text/text_input_box.c
LINE 65

### Fix

Swap IF and array access (line 68 and 70)

**Comment by raysan5** [comment]
@Buhlean Good catch! Feel free to send a PR with the fix! :)

**Comment by Buhlean** [comment]
I had several gripes and nitpicks with this example, but this is the first real error. If you want I could prepare a pull request!

For that case, a couple questions: 

- There is a function at the end of the file that is never called. It is marginally helpful, but doesn't show off any real raylib functionality. Should it stay?
- The FPS are set unusually low and don't match their comment. Which should be adjusted? The cursor blinking animation uses a frame_counter, which complicates matters slightly.
- A Do-While loop for reading in characters would fit perfectly here. Objections?

**Comment by Buhlean** [comment]
I decided to 
- delete the function, 
- keep the loop (for clearer comments and easier control flow) and
- adjust the comment since frame time animations need a certain framerate to work.

**Comment by raysan5** [comment]
@Buhlean Excuse my late responses:

1. That function has been left there on pourpose, to be a reference for some users that requested it on the past.
2. Using a higher framerate would complicate the example a bit so I chose a fast and easy solution.
3. I never use do-while loop, sorry, I don't like that kind of structure.

**Comment by Buhlean** [comment]
Readded the function, it's only the fix and the comment adjustment now.
