### ISSUE TITLE
[example]  Image processing example does not work

### ISSUE THREAD

**Issue by copark86** [raysan5/raylib#1465]
The buttons in the image processing example do not respond at all.

I have tried the WebGL example on the official homepage on Edge, Chrome, iPhone and it didn't show any response to the buttons. I also confirmed it does not work too when compiled on Raspberry Pi.

I remember it was working well previously.

**Comment by raysan5** [comment]
@copark86 Actually, I'm afraid mouse never worked on that example, you can check the source code... but I'll update it to support mouse.
