### ISSUE TITLE
[raymath] raymath isn't bundled in the prebuilt tarballs

### ISSUE THREAD

**Issue by Jack-Ji** [raysan5/raylib#1469]
### Issue description

First, congrats on 3.5 release! What a great achievement!
I just downloaded the prebuilt tarball from github, seems to me raymath is missing.
Is it on purpose?

EDIT: turns out "additional" modules like raymath/rlgl are all missing in the tarball,
and the same problem exists in v3.0 either.

### Environment

NA

### Issue Screenshot

NA

### Code Example

NA

**Comment by edubart** [comment]
I miss `raymath.h` in the tarball, I have to manually search Raylib release tag in GitHub and download it every Raylib release.

**Comment by Not-Nik** [comment]
Same for other API exposing headers, like `rlgl.h` and `rnet.h`. Imo all headers should be installed by default, so that you can easily access them. This also makes updating via a package manager easier.

**Comment by raysan5** [comment]
yeah, I'm aware of that. I like to keep the library with just the minimum required header, for users starting on coding. Advance users can just pick the required headers from the sources or just fork the repo.

**Comment by Jack-Ji** [comment]
I'm definitely a rookie in gamedev (not a rookie in programming however), but I still hope all api are immediately available
after downloaded the tarball, all I need should be just make utility, compiler, a decent editor and the prebuilt tarball, nothing more.

**Comment by raysan5** [comment]
@Jack-Ji Actually all API is immediately available in `raylib.h`. Auxiliar libraries like `raymath` or `rlgl` are used internally by raylib. 

Maybe `raymath` would be the only header that some advance users could require for some 3d math...

**Comment by Jack-Ji** [comment]
I see that you want to keep tarball minimum, though the statements in the feature list is really misleading:

```
Unique OpenGL abstraction layer (usable as standalone module): rlgl
Powerful math module for Vector, Matrix and Quaternion operations: raymath
```

**Comment by raysan5** [comment]
Those statements list some internal features of the library, no intention to confuse anyone. In any case, those headers could be grab directly from the repo if anyone requires them.
