### ISSUE TITLE
[models] LoadMeshes is empty is release 3.5

### ISSUE THREAD

**Issue by zzador** [raysan5/raylib#1491]
In the current release 3.5 the implementation of "LoadMeshes" in "models.c" at line 840 it reads:

```
// Load meshes from model file
Mesh *LoadMeshes(const char *fileName, int *meshCount)
{
    Mesh *meshes = NULL;
    int count = 0;

    // TODO: Load meshes from file (OBJ, IQM, GLTF)

    *meshCount = count;
    return meshes;
}
```

Is that known & wanted?

**Comment by raysan5** [comment]
@zzador Oh, yes... I kept it to remember... but I probably I should have just removed that function...
