### ISSUE TITLE
[core] 1/4 screen (half size) when using retina display on osx

### ISSUE THREAD

**Issue by MikeDX** [raysan5/raylib#1510]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

On OSX with a retina display, rendertextures show only in the lower 1/4 of the window. This can be seen in the julia fractal shader demo.

Commit https://github.com/raysan5/raylib/commit/468a0bedd844586e7b6836b3dcbafda5c20d3595 is the breaking commit. Everything up until that point can be resolved by forcing 

```c
#if defined(__APPLE__)
    #define SUPPORT_HIGH_DPI   1 // Force HighDPI support on macOS
#endif
```

in src/core.c (this is purely used to hack/prove working commits and track down the breaking commit and not suggested as a solution)

There are a few issues open related to this. This issue is here purely to document my investigation and hopefully to provide a PR in the future.

**Comment by raysan5** [comment]
This issue could (maybe) be solved by https://github.com/raysan5/raylib/pull/1512

**Comment by Guddler** [comment]
Hi just so you know - I tested this with pr #1512 and saw no difference in behaviour at all. This is on macOS and the same project as @MikeDX

If I start the application on my iPad screen (a retina screen used as second display) then the whole application renders to the bottom left quad of the application window. If I drag the window to a non-retina screen the rendering is correct.

**Comment by funcelot** [comment]
@MikeDX Did you try to set screeen scale matrix to MatrixScale(2.0f,2.0f,1.0f) instead of MatrixIdentity, and double the size of a screen parameters?

**Comment by Guddler** [comment]
I just took another look at #1512 and spotted that all the changes were wrapped in defines that effectively comment them out on macOS. Oops, small wonder it did nothing.

So with a very quick and dirty hack to add the changes to macOS, render is correct when I drag the Window to a HiDPI screen (my iPad) but not at all correct when the screen starts off on a standard DPI screen. Looks like a starting point though.

**Comment by Nv7-GitHub** [comment]
I am having this issue, are there any quick fixes to this?

**Comment by Guddler** [comment]
Nothing quick that I am aware of as yet

**Comment by dbampersand** [comment]
The quick fix I've been using is to use SetWindowPosition after you've initialized the window:

`InitWindow(screenWidth,screenHeight,"aaaa");
SetWindowPosition(100,100);`

and when you change the window size:

`if (IsWindowResized())
{
    SetWindowPosition(GetWindowPosition().x+1,GetWindowPosition().y+1);
}`

This, for whatever reason, seems to fix it.

**Comment by Nv7-GitHub** [comment]
When I did that, It made everything twice as big, although it did move it from the bottom left to the top left. Are there any fixes for the twice as big thing?

**Comment by chances** [comment]
I'm experiencing this issue _after_ I resize my app's window in macOS Catalina 10.15

**Comment by raysan5** [comment]
This issue should be fixed by now... Please, feel free to reopen if it still fails.
