### ISSUE TITLE
[core] Add Gamepad Vibration functionality

### ISSUE THREAD

**Issue by alexandervrs** [raysan5/raylib#1511]
### Issue description

I wish there was some functionality to vibrate the gamepad with raylib for some enhanced haptics experience. Xbox and PS gamepads support this out of the box for desktop & consoles, HTML5's Gamepad API still doesn't have any functionality for this, but in that platform the method would just not do anything.

I propose there would be 2 methods:

### Code Example

```c
bool IsGamepadVibrationSupported(int gamepad);   // checks whether target gamepad device supports vibration
void SetGamepadVibration(int gamepad, float leftMotor, float rightMotor);  // sets the vibration strength for the gamepad motors, 0 to 1
```

**Comment by raysan5** [comment]
This features depends on GLFW, at least for `PLATFORM_DESKTOP`. Related to https://github.com/glfw/glfw/issues/57

**Comment by raysan5** [comment]
About gamepad vibration for web, some info: 

- https://developer.mozilla.org/en-US/docs/Web/API/GamepadHapticActuator
- https://www.w3.org/TR/vibration/
- https://github.com/w3c/gamepad/issues/19

**Comment by OkiStuff** [comment]
has anyone added Gamepad Vibration for web yet?

**Comment by raysan5** [comment]
@OkiStuff I'm afraid not.

**Comment by raysan5** [comment]
As this issue depends on an external library, I'm closing it. Feel free to open the issue on the specific repo that should implement it or just send a PR for review.
