### ISSUE TITLE
[core] Mouse disappears when project is compiled for web

### ISSUE THREAD

**Issue by Andrew-Maxwell** [raysan5/raylib#1513]
- [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

When Raylib projects are compiled for web, the cursor is hidden when interacting with them. At first, the cursor is visible, but after clicking, the browser says something like "xyz has control of your pointer. Press esc to release your pointer" and the cursor becomes invisible.

### Environment

Reproduced on Firefox under Ubuntu and also Firefox, Chrome, and Safari on Mac OS Catalina.

### Issue Screenshot

![Screenshot from 2021-01-04 14-47-51](https://user-images.githubusercontent.com/8117119/103587341-eabbb680-4e9b-11eb-9df8-b6007230222d.png)

### Code Example
```
#include <raylib.h>
#include <emscripten.h>

static void mainLoop() {
    BeginDrawing();
    ClearBackground(BLACK);
    EndDrawing();
}

int main() {

    InitWindow(640, 480, "test");

#if defined(PLATFORM_WEB)
    ShowCursor(); EnableCursor();;
    emscripten_set_main_loop(mainLoop, 60, 1);
#else
    SetTargetFPS(60);
    while (!WindowShouldClose()) {
        everything.mainLoop();
    }
#endif
}
```

**Comment by raysan5** [comment]
This "issue" is actually a "feature" added for convenience on web... but it was probably not a good idea... 

Related code is just a single line in `core.c` -> `EmscriptenMouseCallback()` -> `emscripten_request_pointerlock()`

I'll review it... maybe adding a custom flag to support it automatically or not?

**Comment by Andrew-Maxwell** [comment]
Ah, OK. That clarifies things, thanks. IMO the best way to do it would be to have a Raylib function which you can call to lock/unlock the pointer, but I don't how how easy to implement that would be. Anyway, thank you for telling me how to change it - that resolves the issue for me.

**Comment by raysan5** [comment]
Removed the automatic pointer lock on mouse-click, now it's up to the user to enable/disable it using `EnableCursor()`/`DisableCursor()`.
