### ISSUE TITLE
[raudio] Error When Playing Sounds (Windows 10, Notepad++, C, TCC)

### ISSUE THREAD

**Issue by pJotoro** [raysan5/raylib#1518]
### Issue description
I get this error when I try to play sounds:
`tcc: error: undefined symbol '__sync_synchronize'
tcc: error: undefined symbol '__sync_lock_test_and_set'
tcc: error: undefined symbol '__sync_val_compare_and_swap'`

### Environment
As the title states, I'm using Windows 10, Notepad++, C, and TCC.

### Code
`#include "raylib.h"

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    InitAudioDevice();
    Sound some_sound = LoadSound("some_sound.wav");

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        // TODO: Update your variables here
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

        ClearBackground(RAYWHITE);

        DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadSound(some_sound);
    CloseAudioDevice();
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}`

**Comment by raysan5** [comment]
@helloguysmaster It seems this issue could be a regression of https://github.com/raysan5/raylib/issues/435#issuecomment-380386426.

It seems a starting point for investigation...

**Comment by gen2brain** [comment]
Raylib uses miniaudio v0.10.25, changelog for v0.10.26 says `  - Fix compilation with TCC.`

**Comment by raysan5** [comment]
Updated to latest miniaudio. Please, could you test it?

**Comment by prilcool** [comment]
I downloaded the default  installer ran notepad and executed the compile command 
 It executed 

` tcc -o audio_sound_loading.exe audio_sound_loading.c C:\raylib\raylib\src\raylib.rc.data -Os -std=c99 -Wall -Iexternal -DPLATFORM_DESKTOP -lmsvcrt -lraylib -lopengl32 -lgdi32 -lwinmm -lkernel32 -lshell32 -luser32 -Wl,-subsystem=gui`

than it gave me the error

```
Process started (PID=1548) >>>
tcc: error: undefined symbol '__sync_synchronize'
tcc: error: undefined symbol '__sync_lock_test_and_set'
tcc: error: undefined symbol '__sync_val_compare_and_swap'
```

This error comes for all the examples in the audio folder  
I'm on windows 10 64 bit .  can you advise any help

**Comment by raysan5** [comment]
@prilcool Please, could you open a new issue?

**Comment by raysan5** [comment]
@prilcool Just updated raylib to latest `miniaudio v0.11.8`. Please, could you check if this issue persists?
