### ISSUE TITLE
Example code only renders blank screen of various colours - Raspberry Pi 3B+ Raspberry Pi OS Lite latest version

### ISSUE THREAD

**Issue by Heliosphan** [raysan5/raylib#1519]
Using RayLib v3.5 fresh download, have a Raspberry Pi 3B+, standard Raspberry Pi OS **Lite**, fresh download.

Git Cloned the RayLib sources. Then compiled the libraries as per the RasPi instructions on the Wiki (PLATFORM=PLATFORM_RPI). Then I compiled all the examples in the same way as per instructions.

Many of the examples render just blank screens - depending upon the screen blanking colour set in code (eg. **ClearBackground(RAYWHITE);**), that's all that can be seen. A lot are white, some are grey, one showed up in blue.

I've tried the core samples, the shapes samples, only the random one works here or there but very few do anything.

The console output seems to show all good stuff, successes. No warnings apart from a "DISPLAY: Failed to get renderer name" warning near the top. 

I'm plugged into a standard monitor via HDMI and I've assigned 256MB memory to the VideoCore.

Oddly the shaders samples I've had more luck with, many show visuals but some of these are also blank.

Is this a bug in 3.5? Can anybody help?

Thanks

**Comment by chrisws** [comment]
I noticed that as well. It seems to be caused by fix #1517

I tried jumping back to the prior commit with `git checkout 33ed14230608667c18b7d28d2f03722354e1c1a2` and it now displays correctly.

**Comment by Heliosphan** [comment]
Awesome, thanks chrisws, I recompiled the lot with this commit in place and boom - the first demo that failed before now works just fine.
Thanks for your assistance!
I guess there's still a bug though...

**Comment by raysan5** [comment]
Change reverted in commit https://github.com/raysan5/raylib/commit/bbc09288bd1732611ebd930eaf28d43f1310b784
