### ISSUE TITLE
how to add other library like wiring pi in raspberry??? 

### ISSUE THREAD

**Issue by raspbiamantes** [raysan5/raylib#1522]
hello, pleas sorry for my bad english .
 i want to compile a code in c++ with raylib and wiringpi to use the gpio ports but to complie a code with raylib i use 
for example:

make core/core_basic_window PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_21

in wich part i can add -lwiringPi to use this library???

**Comment by raysan5** [comment]
@raspbiamantes You should locate in  `src/Makefile` the place where the libraries are included, it's called `LDLIBS` and you should add `-lwiringPi` there. Feel free to join [raylib Discord](https://discord.gg/VkzNHUE) for questions of this type.
