### ISSUE TITLE
[raylib] raudio.c, raylib.h, and windows.h connflicting types

### ISSUE THREAD

**Issue by EvanGrimes** [raysan5/raylib#1524]
### Issue description

Raylib.h, raudio.c and windows.h all have conflicting types against each other, making it not able to compile

### Environment

CLion, Windows 10

### Issue Screenshot

https://imgur.com/a/kXVYEbT

**Comment by raysan5** [comment]
This issue has already been listed before: https://github.com/raysan5/raylib/issues/1217#issuecomment-618428626
