### ISSUE TITLE
[physac] MSVC compiler cannot compile this file correctly

### ISSUE THREAD

**Issue by object71** [raysan5/raylib#1525]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When compiling with MSVC (generated projects with CMake) I and include physac.h I get the following errors:

`D:\Projects\raylib-cpp\vendor\raylib\src\physac.h(410): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax`

When any of these initializers are met: `(Vector2){ 0.0f, 0.0f }`

This is already solved in raylib.h by the following code

```cpp
#if defined(__cplusplus)
    #define CLITERAL(type)      type
#else
    #define CLITERAL(type)      (type)
#endif

// ...

CLITERAL(Vector2){ 0.0f, 0.0f }
```

### Environment

Happening on windows with VS2019 tools installed. Projects generated in cmake and also while trying to build raylib-cpp with all examples - but it is failing on raylib side not on the language port.

### Code Example

Just clone raylib-cpp and build with examples without tests.

**Comment by raysan5** [comment]
@object71 Yeah, `physac` library requires some review... Feel free to send a PR with this improvement.

**Comment by raysan5** [comment]
@object71 Reviewed physac library, please, let me know if it works.

**Comment by object71** [comment]
@raysan5 It is fine now
