### ISSUE TITLE
[models] Expose Mesh GPU uploading (rlLoadMesh()) in raylib

### ISSUE THREAD

**Issue by Hecatonecles** [raysan5/raylib#1529]
Hey there i can manipulate al the mesh data but cant update the mesh without rlgl.h.
But rlgl isnt avaiable on my programming language (FreeBASIC) :/
So i think a simple raylib intern UpdateMeshData function where nice.

I also think Raylib is a nice piece of code.

salute and keep it up :)

**Comment by raysan5** [comment]
done.
