### ISSUE TITLE
[core] 8bitdo M30 controller state mismatch

### ISSUE THREAD

**Issue by pmprog** [raysan5/raylib#1531]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/VkzNHUE) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

When the M30 controller is connected as an 8bitdo device (instead of being configured as an XInput), it seems that buttons aren't correctly mapped, even based on index, rather than the consts defined.
My code was reporting that the L1 button was constantly down, even though I wasn't touching the controller. The input example also reports button 9 being depressed when it starts (see first screenshot)

So then I went to check a few other bits using the Windows joystick information, and the Raylib input tester, it seems that:

- The "Z" button (which represents button 7 within the Windows driver) is matching button 11 in Raylib. 
- The "C" button (which represents button 8 in the Windows driver) does not even register on the Raylib example
- "L" and "R" (Windows buttons 9 and 10) also do not register within Raylib
- Axis 4 is always leaning to -0.01 (but this bit doesn't really bother me)

### Environment

Windows 10 x64, 8bitdo M30 controller

### Issue Screenshot

![image](https://user-images.githubusercontent.com/1705629/104566947-26960f00-5646-11eb-8090-6b41c2fba1cd.png)
![image](https://user-images.githubusercontent.com/1705629/104566214-382ae700-5645-11eb-8ca3-c52b431976b1.png)

### Code Example

Just run the Raylib core example "core_input_gamepad" with an M30 controller attached

**Comment by raysan5** [comment]
@pmprog Did you try with latest version from GitHub? Gamepad DB was updated some days ago, actually, you can check that controller [configuration on the DB](https://github.com/raysan5/raylib/blob/master/src/external/glfw/src/mappings.h#L69).

**Comment by pmprog** [comment]
Yes, I did a pull to refresh the repo. 
I cannot remember if I even deleted and recloned, but I'll try that again in case something hadn't gone right

**Comment by pmprog** [comment]
I have just deleted and recloned the repo; and it's still reporting the same

**Comment by pmprog** [comment]
Ah, managed to find out the problem

The controller is reporting as "8BitDo M30 gamepad", but with an identifer of "03000000c82d00000650000000000000". Where-as in your mapping file, it's got an identifier of "03000000c82d00005106000000000000"

The actual identifier of "03000000c82d00000650000000000000" belongs to "8BitDo M30" on the row above; however, this is configured differently.

I switched the identifiers around, just to test, and the controller buttons work fine now.

I'm not sure where these identifiers came from, or what else they affect, so I've not applied a pull request

**Comment by raysan5** [comment]
@pmprog Thanks for the investigation and report. It seems it could be an issue in the database... In any case, it is external to raylib so closing this issue.
