### ISSUE TITLE
[build] CMake build error on Linux, including "src/external/dirent.h" instead of system's

### ISSUE THREAD

**Issue by gilzoide** [raysan5/raylib#1533]
Building with CMake on Linux errors with the following message:
```
/media/dados/prog/raylib/src/external/dirent.h:83:10: fatal error: io.h: No such file or directory
   83 | #include <io.h>         // _findfirst and _findnext set errno iff they return -1
      |          ^~~~~~
```

The build is including `src/external/dirent.h` instead of the system's default `dirent.h`, it seems the problem is adding `src/external` to import path here: https://github.com/raysan5/raylib/blob/master/src/CMakeLists.txt#L108.

**Comment by raysan5** [comment]
@object71 Please, could you take a look to this issue?

**Comment by object71** [comment]
Yes, that adds a bit more info on the issue that @RobLoach had. @raysan5 I will take a look

**Comment by gilzoide** [comment]
I'm looking more closely at this, seems every `#include` to any `src/external/*.h` headers is in the form `#include "external/*.h"`, so it seems to me it's safe to just remove this line (I'm not that familiarized with the source code, so can't say for sure at the moment).

Also, no mentions to `src/external` in Makefile, so...

**Comment by gilzoide** [comment]
The only places I found references to `src/external` were on examples/projects/templates Makefiles, I guess they are not even required there if all these projects use only the raylib API

**Comment by raysan5** [comment]
@gilzoide Thanks for checking it, yeah, probably not required... I can't remember now why it's there...

**Comment by object71** [comment]
I will submit a pull request later today. I just need to test it again because something was not compiling on windows when I initially submitted the change
