### ISSUE TITLE
[Wiki] Default Vscode folder doesnt work

### ISSUE THREAD

**Issue by nonunknown** [raysan5/raylib#1537]
### Issue description

Followed the WIKI for how to use VSCode, configured as it demands, got an error!

### Environment

Windows 10 x64
Intel HD Graphics 3000

### Issue Screenshot

![image](https://user-images.githubusercontent.com/58845030/104815727-08224600-57f5-11eb-86c9-757fc930b96b.png)

### Code Example
N/A

**Comment by dylan-conway** [comment]
You copied the VSCode project directory from the raylib/projects directory? What was your method of installing the library?

**Comment by nonunknown** [comment]
from itchio mingw version

**Comment by raysan5** [comment]
Just tried it and it works ok for me. Feel free to edit Wiki if there is some part that is not clear.
