### ISSUE TITLE
[core] F12 can never be used as a key, even if screenshot is disabled

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib#1540]
### Issue description
The F12 key is always captured by the KeyCallback in core.c even if screenshot is disabled. This prevents any client code from ever being able to use or detect that key as a key press. The configuration define of SUPPORT_SCREEN_CAPTURE and SUPPORT_GIF_RECORDING all happen inside the     else if (key == GLFW_KEY_F12 && action == GLFW_PRESS) and the regular system key capture is done in the else case, thus even if no capture hapens, F12 never gets into the core keymap.

### Environment
All desktop

### Issue Screenshot
![image](https://user-images.githubusercontent.com/322174/104964928-5a4c9e00-5992-11eb-8a0d-0c5794458b77.png)

**Comment by raysan5** [comment]
Solved.
