### ISSUE TITLE
[models] Multiple meshes not working correctly

### ISSUE THREAD

**Issue by muevoid** [raysan5/raylib#1541]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Loading a gltf model with multiple meshes isn't working for me as you can see here: 
![blender](https://user-images.githubusercontent.com/38061852/105371175-3f7d6200-5bfc-11eb-9c05-143f79766bf1.png)
![raylib](https://user-images.githubusercontent.com/38061852/105371207-45734300-5bfc-11eb-8222-f159c627919d.png)

I may of done something wrong but I don't believe so.

all i did was in a relevant snippet of code:

```
Model player = LoadModel("model.gltf");

while(!WindowShouldClose()) {
     UpdateCamera(&camera);

    BeginDrawing();
    ClearBackground(WHITE);
    BeginMode3D(camera);
        DrawModel(player, (Vector3) { 0.0f, 0.0f, 0.0f }, GRAY);
        DrawModelWires(player, (Vector3) { 0.0f, 0.0f, 0.0f }, GRAY);
    EndMode3D();
EndDrawing();
}
```

When exporting from blender I used the following options under Geometry:

Apply Modifiers - Off
UVs - On
Normals - On
Tangents - On
Vertex Colors - Off
Materials - Off

### Environment

Void linux, glibc, wayland,  Opengl 3.3

**Comment by raysan5** [comment]
@muevoid please, could you provide the tested gltf model?

**Comment by muevoid** [comment]
I believe it meets all of the restrictions for sure no hierarchies but not sure exactly about transforms I cleared parent on all the meshes in blender so I don't think so but I'm not 100% sure. Here's the 3 model files the glb, gltf, and the blend file https://github.com/muevoid/Vinox/tree/main/resources. They are all in that folder.

**Comment by raysan5** [comment]
@muevoid Checking file `mc.gltf` with a text editor it seems every Cube node defines `rotation` and `translation` transformations so I'm afraid that can be the issue. Those transformations are not applied to loaded vertex. You should export the model with the transformations already applied to the mesh vertex data. A quick Google check [gave me this link](https://blender.stackexchange.com/questions/3646/how-to-apply-transformations-directly-on-mesh-data).

**Comment by muevoid** [comment]
That worked! Thank you I had tried to search for the restrictions previously but could not figure it out I appreciate the help!
