### ISSUE TITLE
[core.c] Add option to set / change the screenshot key

### ISSUE THREAD

**Issue by jmorel33** [raysan5/raylib#1547]
These changes were tested and work as expected.

### in raylib.h
`RLAPI void SetScreenshotKey(int key);                         // Set a custom key for screenshots (default is F12)`

### in core.c

_**add container for screenshot key in keyboard;**_
`       struct {`
`            int exitKey;                    // Default exit key`
`            int screenshotKey;              // Default screenshot key`
`            char currentKeyState[512];      // Registers current frame key state`
`            char previousKeyState[512];     // Registers previous frame key state`

`            int keyPressedQueue[MAX_KEY_PRESSED_QUEUE];     // Input keys queue`
`            int keyPressedQueueCount;       // Input keys queue count`

`            int charPressedQueue[MAX_CHAR_PRESSED_QUEUE];   // Input characters queue`
`            int charPressedQueueCount;      // Input characters queue count`

`#if defined(PLATFORM_RPI) || defined(PLATFORM_DRM)`
`            int defaultMode;                // Default keyboard mode`
`            struct termios defaultSettings; // Default keyboard settings`
`            int fd;                         // File descriptor for the evdev keyboard`
`#endif`
`        } Keyboard;`

_**Set default value in container;**_
`// Initialize window and OpenGL context`
`// NOTE: data parameter could be used to pass any kind of required data to the initialization`
`void InitWindow(int width, int height, const char *title)`
`{`
`#if defined(PLATFORM_UWP)`
`    if (!UWPIsConfigured())`
    {
`        TRACELOG(LOG_ERROR, "UWP Functions have not been set yet, please set these before initializing raylib!");`
`        return;`
`    }`
`#endif`

`    TRACELOG(LOG_INFO, "Initializing raylib %s", RAYLIB_VERSION);`

`    if ((title != NULL) && (title[0] != 0)) CORE.Window.title = title;`

`    // Initialize required global values different than 0`
`    CORE.Input.Keyboard.exitKey = KEY_ESCAPE;`
`    CORE.Input.Keyboard.screenshotKey = KEY_F12;`
`    CORE.Input.Mouse.scale = (Vector2){ 1.0f, 1.0f };`

_**Add functionality to change the keycode;**_
`// Set a custom key to take a screenshot`
`// NOTE: default screenshotKey is F12`
`void SetScreenshotKey(int key)`
`{`
`#if !defined(PLATFORM_ANDROID)`
`    CORE.Input.Keyboard.screenshotKey = key;`
`#endif`
`}`

_**change all references to key binding F12 or 301;**_
`#if defined(SUPPORT_SCREEN_CAPTURE)`
`    // Check screen capture key (raylib key: KEY_F12)`
`    if (CORE.Input.Keyboard.currentKeyState[CORE.Input.Keyboard.screenshotKey] == 1)`
`    {`
`        TakeScreenshot(TextFormat("screenshot%03i.png", screenshotCounter));`
`        screenshotCounter++;`
`    }`
`#endif`

` void UWPKeyDownEvent(int key, bool down, bool controlKey)`
`{`
`    if (key == CORE.Input.Keyboard.exitKey && down)`
`    {`
`        // Time to close the window.`
`        CORE.Window.shouldClose = true;`
`    }`
`    else if (key == CORE.Input.Keyboard.screenshotKey && down)`
`    {`
`#if defined(SUPPORT_GIF_RECORDING) `

And finally;
`// GLFW3 Keyboard Callback, runs on key pressed`
`static void KeyCallback(GLFWwindow *window, int key, int scancode, int action, int mods)`
`{`
`    //TRACELOG(LOG_DEBUG, "Key Callback: KEY:%i(%c) - SCANCODE:%i (STATE:%i)", key, key, scancode, action);`

 `   if (key == CORE.Input.Keyboard.exitKey && action == GLFW_PRESS)`
 `   {`
 `       glfwSetWindowShouldClose(CORE.Window.handle, GLFW_TRUE);`

 `       // NOTE: Before closing window, while loop must be left!`
 `   }`
 `   else if (key == CORE.Input.Keyboard.screenshotKey && action == GLFW_PRESS)`
 `   {`
`#if defined(SUPPORT_GIF_RECORDING)`

**Comment by raysan5** [comment]
@jmorel33 Sorry, no plans to add that option. To use a custom key, just do it on user code:
```c 
if (IsKeyPressed(KEY_S)) TakeScreenshot("myscreenshot.png");
```

**Comment by jmorel33** [comment]
How nice of Raysan5 ...

**Comment by RemySzpuuk** [comment]
Well there isn't really a point in adding something which is already possible.

**Comment by jmorel33** [comment]
It is *NOT* possible at all, it's all hardcoded to the F12 key making F12 useless.

**Comment by jmorel33** [comment]
I just opened up the screenshot capability to be able to change the key to anything or disable, just like the Escape to exit.

**Comment by RemySzpuuk** [comment]
Oh I see what you mean. You want the F12 key to be usable and not just stuck to screenshots! You didn't describe what you wanted very well so I didn't understand. I would definitely be in support for this change.

**Comment by raysan5** [comment]
You can just comment `SUPPORT_SCREEN_CAPTURE` on `config.h` to free F12 and use any custom screenshot mechanism, like, i.e. two gamepad buttons.

**Comment by jmorel33** [comment]
My change is to free the F12 key as well as being able to assign screenshot within the core, which is the elegant and clean way to do it.

**Comment by hexmaster111** [comment]
Its pretty cool googling how to remap the F12 key comes to "just change the pre-compiled lib and then recompile it..."

Really if we are fallowing @raysan5 logic, we should get rid of the `SetExitKey` method too. The user can just recompile the lib for such a tiny tweak....
