### ISSUE TITLE
[raudio] InitAudioDevice and CloseAudioDevice inconsistent when called multiple times

### ISSUE THREAD

**Issue by ChrisDill** [raysan5/raylib#1548]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I found a bug when calling `InitAudioDevice` and `CloseAudioDevice` multiple times. I found this in Raylib-cs since examples are in the same project.

Expected: Audio device to be created and destroyed multiple times with no difference in the output.

Actual: Output varies. Most of the time no sound plays and sometimes it segfaults. Using a debug build I tracked the segfault to: https://github.com/raysan5/raylib/blob/f3ce3a6f741fdf02eb602e2d7df7b14951f4aa65/src/raudio.c#L1826

### Environment

Platform: PLATFORM_DESKTOP
Operating System: Arch Linux
OpenGL version: 3.3
GPU: RX 580

### Code Example

```c
#include "raylib.h"

int main()
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "audio-device1");

    // Testing: Init then close then init
    InitAudioDevice();
    CloseAudioDevice();
    InitAudioDevice();

    Music music = LoadMusicStream("resources/mini1111.xm");
    PlayMusicStream(music);
    SetMusicPitch(music, 1.0f);

    SetTargetFPS(60);
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        UpdateMusicStream(music);      // Update music buffer with new stream data
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
        ClearBackground(RAYWHITE);

        DrawFPS(10, 10);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadMusicStream(music);          // Unload music stream buffers from RAM
    
    CloseAudioDevice();
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by raysan5** [comment]
@ChrisDill This issue should be solved with latest commit. Multichannel buffers were not properly unloaded.

**Comment by ChrisDill** [comment]
I have tested the fix with the code example and my C# examples and it fixes the initial issue. However it also causes a crash in audio_multichannel_sound. If you play fxWav or fxOgg using `PlaySoundMulti` then close the program it will crash in `CloseAudioDevice`.

I tracked the crash to `UnloadAudioBuffer` here:
https://github.com/raysan5/raylib/blob/0f309b9b16c7986c5bda65ff002b7a5b432642d4/src/raudio.c#L572

**Comment by raysan5** [comment]
Ouch! I never liked that multichannel implementation... actually, it's on the raylib 3.6 roadmap to review/remove it... now it seems there is a reason for that...

**Comment by raysan5** [comment]
@ChrisDill Just pushed a quick solution, it should work now but it requires a better design...

**Comment by ChrisDill** [comment]
Tested the latest version and audio_multichannel_sound now works in C and C#!

**Comment by raysan5** [comment]
It still requires a better approach to the problem... but closing this issue for now...
