### ISSUE TITLE
[compiling] cannot compile using RPI 3 

### ISSUE THREAD

**Issue by Ted-bissada** [raysan5/raylib#155]
I attempted to compile this following instructions as stated on the wiki and on the first attempt it ran for a while outputting many lines before reaching this error

```
ar rcs ../release/rpi/libraylib.a text.o core.o gestures.o audio.o rlgl.o camera.o shapes.o models.o testures.o utils.o external/stb_vorbis.o
ar: ../release/rpi/libraylib.a: No such file or directory
Makefile:163: recipie for target 'raylib' failed
make: *** [raylib] Error 1

```
on subsequent attempts this error is reached instantly
attempting to create this directory and  an empty file of this name via terminal changes the error slightly to 

```
ar rcs ../release/rpi/libraylib.a text.o core.o gestures.o audio.o rlgl.o camera.o shapes.o models.o testures.o utils.o external/stb_vorbis.o
ar: ../release/rpi/libraylib.a: File format not recognised
Makefile:163: recipie for target 'raylib' failed
make: *** [raylib] Error 1
```

renaming the android or linux folders in release to rpi both output 

```
ar rcs ../release/rpi/libraylib.a text.o core.o gestures.o audio.o rlgl.o camera.o shapes.o models.o testures.o utils.o external/stb_vorbis.o
libraylib.a generated (static library)!
```

but upon attempting to make any of the examples libraylib is not found

**Comment by raysan5** [comment]
Thanks for the issue report, I'll review those folder conflicts... it was a last-hour change...

**Comment by Ted-bissada** [comment]
Ok thanks for the help i am really excited to try this library out after reading about it

**Comment by raysan5** [comment]
Ok, solved on commit https://github.com/raysan5/raylib/commit/c604b53f78adc2c96d5f0ee6cd1becb3429c778a on develop branch. As it is a breaking issue I'll integrate it into master branch soon.

**Comment by Ted-bissada** [comment]
Thanks for the help I will try compiling that commit tonight
