### ISSUE TITLE
[core] eglGetConfigs() usage could be redundant or no obvious

### ISSUE THREAD

**Issue by nitrologic** [raysan5/raylib#1550]
It is not obvious why eglGetConfigs is being called here 

https://github.com/raysan5/raylib/blob/88a6f16c9a552ebb8c39fff57cf16cfce7c88913/src/core.c#L3869

when several lines further on eglChooseConfig is called making the results of the eglGetConfigs seemingly redundant?

Apologies if I have missed something obvious in this code.

Simon

**Comment by object71** [comment]
Based on what I see around that code it is probably mostly for better error messaging - having frame buffer configurations VS having frame buffer configurations that match the attributes specified in framebufferAttribs

**Comment by raysan5** [comment]
Actually that code was recently contributed by @kernelkinetic to support `PLATFORM_DRM`, probably he can provide more details about that.

**Comment by kernelkinetic** [comment]
@nitrologic Without checking this in a compiler I would say you're right 👍  https://github.com/raysan5/raylib/blob/88a6f16c9a552ebb8c39fff57cf16cfce7c88913/src/core.c#L3853 could be replaced by an appropriate call to `eglChooseConfig` and https://github.com/raysan5/raylib/blob/88a6f16c9a552ebb8c39fff57cf16cfce7c88913/src/core.c#L3869 could be removed. This line is a relict of a previous version of the configuration selection.

If I would be @raysan5 I would say "Feel free to send a pull request!" 😀

**Comment by raysan5** [comment]
@kernelkinetic @nitrologic Feel free to send a pull request! :D

**Comment by nitrologic** [comment]
Thanks all for the comments. I am on a PowerVR embedded platform where EGL_NATIVE_VISUAL_ID always returns 0 effectively making it unsupported by current implementation. 

Also I am more keen on using best practical config per platform so after reading notes for [eglChooseConfig](https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglChooseConfig.xhtml) 

> EGL implementors are strongly discouraged, but not proscribed, from changing the selection algorithm used by eglChooseConfig. Therefore, selections may change from release to release of the client-side library.


I will be testing the #else block that follows for my DRM experiments.

**Comment by kernelkinetic** [comment]
@nitrologic `eglChooseConfig` returns you a list of matching configurations and it's up to you to select one from this list. Using `EGL_NATIVE_VISUAL_ID` is just one of several ways to choose. From my experiences this doesn't work on every platform and you added that this also doesn't work on your PowerVR. You can retrieve other attributes by calling `eglGetConfigAttrib()` near https://github.com/raysan5/raylib/blob/88a6f16c9a552ebb8c39fff57cf16cfce7c88913/src/core.c#L3890, also for several attributes, and compare them to your needs to select an appropriate configuration.

**Comment by raysan5** [comment]
@nitrologic @kernelkinetic could this issue be closed?

**Comment by kernelkinetic** [comment]
@raysan5 It can be closed for all I care.

@nitrologic I'm also available on raylib's discord server if there are further questions 🙂
