### ISSUE TITLE
[models] Add functions to interpolate between animation poses

### ISSUE THREAD

**Issue by object71** [raysan5/raylib#1552]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

3D models currently don't support interpolation between pose transforms. I believe it would be benefitial to add to the API.

**Comment by chriscamacho** [comment]
Wouldn't it be better doing this in the vertex shader ?

Once there is the basic pose mesh, and the bone info, the shader can work this out on the fly, allowing for smooth animations as bones are interpolated between key frames.

**Comment by CODESOLE** [comment]
+1
Yeah, i really want that feature as well. I think my biggest wish right now.

**Comment by chriscamacho** [comment]
AFICT the GLTF loader is still not loading the animation data correctly, at least viewing it as an animated mesh with bones drawn as spheres (try a simple animation like the GLTF example models cesiumMan)

I'd like to implement a vertex shader for this but I am currently unable to...

**Comment by raysan5** [comment]
At this point there are several issues with glTF animations, I prefer to close this advance feature until animations are properly working.
