### ISSUE TITLE
[models][gltf] Similar to IQM on model loading interpolate a const set of poses

### ISSUE THREAD

**Issue by object71** [raysan5/raylib#1553]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Currently when loading a model (look at gltf animation example) you would only get two poses. This is not the correct mapping for the current version of raylib which expects a set of poses targeting 30/60 FPS. 

So it will be good if for each transformation we interpolate the position for a set number of frames.

**Comment by raysan5** [comment]
@object71 Agree.
