### ISSUE TITLE
[core] First frame hiccup on Linux when compiling raylib with embedded GLFW

### ISSUE THREAD

**Issue by gilzoide** [raysan5/raylib#1554]
Hi! I'm on a x86_64 Manjaro Linux on X11 and everytime I build raylib + some project, it gives this super long first frame.
![raylib-first-frame](https://user-images.githubusercontent.com/4603360/106160969-2bd67c00-6165-11eb-932d-53b390563404.gif)

I tracked down that this problem doesn't occur when linking with the raylib installed in my system, which uses external GLFW (https://github.com/archlinux/svntogit-community/blob/packages/raylib/trunk/PKGBUILD#L19-L31), and neither when compiling with external GLFW. Here is how it goes:
![raylib-first-frame-ext-glfw](https://user-images.githubusercontent.com/4603360/106160983-309b3000-6165-11eb-91ef-b7ff7449dff9.gif)

I checked that the GLFW version installed here is 3.3.2 and that raylib's bundled version says 3.4.0, but this by itself doesn't seem to be the problem, I built a minimal GLFW window example linking to raylib's GLFW and the problem doesn't arise.
![glfw-first-frame](https://user-images.githubusercontent.com/4603360/106161001-35f87a80-6165-11eb-995f-872cc8ad6906.gif)

I'm building with CMake, but the same happens when building raylib and the examples using `make`.
![raylib-physics](https://user-images.githubusercontent.com/4603360/106161997-61c83000-6166-11eb-86a2-60ae342227a7.gif)

**Comment by raysan5** [comment]
@gilzoide this is very weird...

**Comment by gilzoide** [comment]
I know, right? Don't know if anyone had this problem before, maybe it's just my build environment making something unexpected...

I'd say this is not a big problem, because it's just me and I guess building executables linking with external GLFW is fine, Linux distributions have good package managers, maybe most users will have GLFW installed already.

**Comment by gilzoide** [comment]
I just now tried rolling back to 3.5.0 and building the physics example again, same problem.
3.0.0, 2.6.0, same thing.
2.5.0 worked! =O

I'll use `git bisect` later to find out what the hell is happening, this is really bugging me out!

**Comment by gilzoide** [comment]
Just FYI, after bisecting, first bad commit is 83916bd3c271d45fd60431b66fca0560cd0c2f93, regarding a GLFW update.
It's a big commit, I'll not go into it today, but will later. I'll keep in touch if I discover more about it.

**Comment by raysan5** [comment]
@gilzoide Did you investigate this issue a bit further?

**Comment by gilzoide** [comment]
I was participating on GGJ, so only had some time to try finding anything yesterday, after resting from my laptop.
I read some parts of the diff, but couldn't get anything yet.
By the symptom, I would guess it is tied to some change in X11 windowing, but I don't know any specifics about how X11 works (well, at least not yet) =P
May also be some blocking IO taking too long, maybe in event handling.

I thought of also trying to revert changes one by one until it starts working as expect. This will take a while though...

**Comment by gilzoide** [comment]
Ok, so I was trying to revert some changes here and was lucky enough to find the offending change in one of my first tries, it lies in `src/external/glfw/src/input.c` (https://github.com/raysan5/raylib/commit/83916bd3c271d45fd60431b66fca0560cd0c2f93#diff-3d2c96f50499add372ed6bec2a6ac275934c46378bd7b02093ab8e44f423aa57)

I noticed this little delay is present on the build without the first long frame, but before the window appears, so it seems initializing joysticks takes a while, at least on my system, and the problem I'm experiencing is that this initialization is deferred to after the first draw is called.

I think raylib calls to joystick related functions in `EndDrawing` are triggering this deferred initialization after my first frame is drawn, thus the noticeable delay =/

**Comment by raysan5** [comment]
@gilzoide Wow! Nice investigation! Thanks for the time and the detailed explanation! It seems not much can be done in raylib side, I'll close the issue. Hopefully it will be a good reference for anyone facing the same issue! Thanks! :D

**Comment by gilzoide** [comment]
@raysan5 Well, actually, there could be a call to any joystick related function before creating the window to force the initialization routine, rolling the behaviour back to before upgrading GLFW.
A simple `glfwSetJoystickCallback(NULL);` is sufficient.
It seems GLFW joystick functionality is used only on Desktop platforms when `MAX_GAMEPADS > 0`, it could even be called only on those.

I know this might be noticeable only in some systems, like mine, that has 24 file descriptors named `/dev/input/event*` that GLFW scans, but I think avoiding running this initialization inside the main loop right after drawing the first frame might just benefit everybody.

May I open a PR with it?

**Comment by raysan5** [comment]
@gilzoide oh! nice! feel free to open a PR.

**Comment by Smiley98** [comment]
I'm still experiencing this error but under a different case -- when I'm running raylib on x64 Windows 11 it takes 5-10 seconds to get through glfwSetJoystickCallback(NULL) *only when I have screen recording software like Zoom or OBS open*. Otherwise raylib initializes in under 1 second as expected.
