### ISSUE TITLE
[raudio] Error on InitAudioDevice() closes the app automatically

### ISSUE THREAD

**Issue by kolyan666** [raysan5/raylib#1562]
Platform: Windows (miniaudio)

Steps to reproduce:
- call InitAudioDevice()
- wait for a number of users to report the app failing on startup without an error message

So far, 2 of my friends were unable to run my game.
One didn't have his headphones plugged in, another one had that happen with "Generic USB audio" as the default device.

Console output in both cases:
``` ERROR: miniaudio: [WASAPI] Failed to find suitable device format for device info retrieval. ```

Expected behaviour:
Sound commands are bypassed after a single warning. (in my case there weren't any, just init)

**Comment by raysan5** [comment]
@kolyan666 Actually the error message is displayed in the console output and closing the app is the expected behaviour...

@mackron Does exist some fallback mechanism for those cases? Is it possible to support/enable some? I mean, to just let the program run with no audio...

**Comment by mackron** [comment]
That error is not be critical and should not be causing initialization of audio to fail. Specifically, the error is getting thrown when retrieving the exclusive mode device format. I can see that each error case in `InitAudioDevice()` has an trace message labelled with "AUDIO: ". Which one of those is getting thrown?

I'm going to change that error message to a warning.

**Comment by mackron** [comment]
I've pushed a change to the dev branch to change the wording of that message from an error to a warning, but I don't expect it'll fix anything with your issue. You should post the full log so we can see more details.

**Comment by raysan5** [comment]
Updated miniaudio to dev branch and reviewed logging as warnings instead of errors. Program should work now. Feel free to re-open if any issue persist.
