### ISSUE TITLE
[rlgl] Valgrind reports memory leak in raylib

### ISSUE THREAD

**Issue by DavidGRX** [raysan5/raylib#1563]
I've made a simple program using raylib and got valgrind errors. I reduce the program to the following: 
#include "raylib.h"

int main(void)
{
    const int screenWidth = 1200;
    const int screenHeight = 650;
    InitWindow(screenWidth, screenHeight, "raylib [shapes] example - bouncing ball");
    CloseWindow();        // Close window and OpenGL context
    return 0;
}

Compiled it with g++ minimo.cpp -o kk -g -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
and checked with 
valgrind --leak-check=full ./kk 

The errors came from the InitWindow function. The trace lead in some cases to libX11 (so, not a raylib problem) but other pointed to LoadShaderProgram 

In any case, I should say that my full program runs fine!

**Comment by raysan5** [comment]
@DavidGRX Thanks for reporting. I think the memory leak (if any) could be outside raylib but, just in case, I reviewed `LoadShaderProgram()` to avoid some ugly code.

Please, let me know if it works now.

Also, maybe related to https://github.com/raysan5/raylib/issues/1185

**Comment by DavidGRX** [comment]
@raysan5, valgrind still shows some warnings but ends up with 

==1781== 
==1781== HEAP SUMMARY:
==1781==     in use at exit: 145,025 bytes in 2,780 blocks
==1781==   total heap usage: 78,500 allocs, 75,720 frees, 60,078,179 bytes allocated
==1781== 
==1781== Searching for pointers to 2,780 not-freed blocks
==1781== Checked 2,391,324 bytes
==1781== 
==1781== LEAK SUMMARY:
==1781==    definitely lost: 5,564 bytes in 266 blocks
==1781==    indirectly lost: 912 bytes in 34 blocks
==1781==      possibly lost: 0 bytes in 0 blocks
==1781==    still reachable: 138,549 bytes in 2,480 blocks
==1781==         suppressed: 0 bytes in 0 blocks
==1781== Rerun with --leak-check=full to see details of leaked memory
==1781== 
==1781== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

I'm almost sure that there are no problems with raylib so the issue can be closed. 

Thanks for your help!!
