### ISSUE TITLE
RAYLIB EXAMPLES on rpi

### ISSUE THREAD

**Issue by piderking** [raysan5/raylib#1565]
when every I use ./ to run the compiled program it?

I followed the steps for raspberry pi 0-3. Not the desktop. I already restarted. Thanks!
Error below, I don't know if this is a easy problem.

INFO: Initializing raylib 3.5
* failed to add service - already in use?

**Comment by raysan5** [comment]
@piderking that's because you are compiling with `PLATFORM_RPI`, that's intended to run from outside the desktop interface. To run in a desktop window, just compile using `PLATFORM_DESKTOP`.

**Comment by piderking** [comment]
Thank you! That helped a lot.
