### ISSUE TITLE
High-DPI support

### ISSUE THREAD

**Issue by paezao** [raysan5/raylib#157]
Hello,

I'm setting my window size as 800x600 and Im getting this:

http://screencloud.net/v/w7qU

I think this probably has to do with my laptop having a high dpi display. I know GLFW supports it, does raylib at this moment?

Edit: I just realized it gets fixed when I move the window..thats interesting.

Cheers

**Comment by paezao** [comment]
Just an update.

I managed to make it work by getting the correct framebuffer size using glfwGetFramebufferSize and then passing that to rlViewport.

I don't know exactly how you want to handle this but there's also a FramebufferSize callback that should probably be used. glfwSetFramebufferSizeCallback

**Comment by raysan5** [comment]
Ok, are you using a Mac? are you working on OSX? I think that's an known issue... check NOTES at the end of the tutorial: https://github.com/raysan5/raylib/wiki/Compile-for-OSX

**Comment by paezao** [comment]
Hello @raysan5!

Yes I am working on OSX.

It should be a simple fix though, you just need to use that function to determine the real framebuffer size and maybe handle the callback. Since I just got here (and dont know the lib intimately yet) I rather not submit a pull request for that.

Gracias :)

**Comment by raysan5** [comment]
That's great @paezao! 

I'll just keep the issue open until implementing your solution (I'll try to update code tomorrow)!

By the way, could you help with this issue: https://github.com/raysan5/raylib/issues/158?

**Comment by paezao** [comment]
I will definitely try and help @raysan5. Im working on vim and compiling via the terminal though.

**Comment by raysan5** [comment]
Updated code on commit https://github.com/raysan5/raylib/commit/07a375e2d626428f5a1b9f02907120a4b3b3a08a

Just updated `InitGraphicsDevice()` function on `core` module, actually, I already had `glfwGetFramebufferSize()` there but commented... I'd be great to talk with myself of the past to ask why I left that function there... can't remember... :P

If you test it, please, use develop branch.

**Comment by paezao** [comment]
It didn't work here. 

Also, I think you probably shouldn't use that for apple only because there may be other high dpi displays.

**Comment by paezao** [comment]
If you want to do real time testing or give me some pointers so I can submit a PR I'm in IRC #raylib @ freenode.net

**Comment by raysan5** [comment]
Ok, that's great, just out for lunch right now but Ill be there in about an
hour.

**Comment by raysan5** [comment]
Issue solved on commit https://github.com/raysan5/raylib/commit/a422e394925e68ab687ef70527c3e207234d8bd7

**Comment by hholst80** [comment]
@raysan5 has this been tested to work with Wayland on Linux? I see that the display size is reported as 1280x720 which is the virtual size of my 2560x1440 display.  TBH I am not sure how to best solve this but I think right now the window is just upscaled. In the best of worlds my application would have the full display buffer and be aware of the intended scaling parameter. Perhaps some parts of the drawing will use upscaling and others should use other methods like font rendering. Anyway, if the MacOS people are happy with their solution I am more than glad to try it out (I take it that they are picky about their desktop look;)

The whole scaling thing is quite broken but the alternative is worse, to not support it at all.
