### ISSUE TITLE
[models] PBR system not considering environment maps properly?

### ISSUE THREAD

**Issue by kororro** [raysan5/raylib#1571]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

PBR-example doesnt look like this https://raw.githubusercontent.com/raysan5/raylib/master/examples/models/models_material_pbr.png

### Environment

Windows 10 x64, OpenGL 4.5 (using 3.3)

### Issue Screenshot

![helmet](https://user-images.githubusercontent.com/42260382/107145975-e462a380-694d-11eb-98e5-eb4163fb276c.png)

Output log:
https://pastebin.com/y4AwrYT4

**Comment by raysan5** [comment]
PBR system requires a complete review. That requires some work, not a priority at this moment.

**Comment by kororro** [comment]
Yes, checked closely, seems environment map is missing (there are some warnings in the log).
Tested couple of examples and these works fine when exiting, but that pbr example throws exception when pressing ESC (or clicking X) on models.c UnloadModel(Model model)  function at line 802 (  RL_FREE(model.materials[i].params);  ).

**Comment by raysan5** [comment]
After a quick check, it seems the texture `irradiance cubemap` is not properly generated, also not sure about the `prefilter map`.

Probably related to some big changes introduced while working on #721. It requires some more investigation.

**Comment by raysan5** [comment]
Closing this issue, example need a complete rewrite...
