### ISSUE TITLE
running on mac brings pain. or at least does not work in xcode with paths set

### ISSUE THREAD

**Issue by lewislepton** [raysan5/raylib#158]
howdy,

rather than post an email to you, someone else may have got this as well on mac.
so...

ive done the set up, just translated the spanish wiki for doing it with mac, and whilst making things like glfw3 work and compile, and have also setup the location of raylib.h by clicking and dragging in the location to the `Search paths > header search paths/library search paths` it brings up an error. screenshot shows error.

<img width="912" alt="screen shot 2016-07-25 at 21 56 21" src="https://cloud.githubusercontent.com/assets/11299322/17117115/a5e1a07c-52b2-11e6-8a92-b328d90b2fbd.png">

now i have tried again and again. but no dice, same message

xcode version is 7.3.1, plus used cmake to do the generation, and all that worked. so dont know whats up.

raylib looks interesting, a break away from my more bigger things ;)

**Comment by lewislepton** [comment]
also my other settings, for the library settings & the search paths. screenshots given

<img width="1166" alt="screen shot 2016-07-25 at 22 14 06" src="https://cloud.githubusercontent.com/assets/11299322/17117683/30bd2336-52b5-11e6-9519-c935f75a6d5d.png">

<img width="1173" alt="screen shot 2016-07-25 at 22 14 21" src="https://cloud.githubusercontent.com/assets/11299322/17117697/3cccb038-52b5-11e6-9527-b056810d2921.png">

**Comment by raysan5** [comment]
Hi lewislepton, just for record, you have tried adding to Library Search Paths: `"/Users/lepton/Developer/raylib/RAYLIBGLFW/../../../Downloads/raylib-master/release/osx"`?

**Comment by lewislepton** [comment]
yeah, that also does not work

**Comment by raysan5** [comment]
Just reviewed tutorial and translated to english: https://github.com/raysan5/raylib/wiki/Compile-for-OSX

Tomorrow I'll try to check it on a Mac...

**Comment by paezao** [comment]
Do you have a libraylib.a on the release/osx folder of the library source code?

**Comment by paezao** [comment]
Do you have a libraylib.a on the release/osx folder of the library source code?

**Comment by lewislepton** [comment]
this is the setup with the library, which is right, also did compile etc. though i will move raylib to my developer folder just so it doesnt get lost in my downloads ;)

![screen shot 2016-07-26 at 19 20 53](https://cloud.githubusercontent.com/assets/11299322/17150127/261a83d6-5366-11e6-89a7-dc6213dd6935.png)

**Comment by lewislepton** [comment]
ok. so i have tried the latest update to the tutorial to build with mac, plus have tried the develop version, just to see. but the same problem happens.
but did notice that a `raylib.h` has compiled when i compiled the release/osx. before that did not happen

![screen shot 2016-07-26 at 20 11 35](https://cloud.githubusercontent.com/assets/11299322/17151888/4273dda0-536d-11e6-9125-946f5a4a74d6.png)

**Comment by lewislepton** [comment]
ah ha. noticed the error message is actually now saying that GLFW3 can not be found. which is weird, since i went through the same process. very odd

**Comment by lewislepton** [comment]
but everything is set up right. followed everything well and to the point. very strange. even the master is not building, does come up with the `cant find glfw3` the same as the develop version, but master does not generate a raylib.h inside the `release/osx` folder

**Comment by lewislepton** [comment]
here is the project im working, with xcode
[RAYLIBGLFW.zip](https://github.com/raysan5/raylib/files/384836/RAYLIBGLFW.zip)

**Comment by lewislepton** [comment]
its set up with raylib just above the project folder, which was pointed to it

**Comment by raysan5** [comment]
Hi @lewislepton, not sure what's the problem, it seems related to paths, it should work ok; actually @paezao is developing on OSX with raylib and it works fine... Maybe he can give you some feedback on your issue...

**Comment by lewislepton** [comment]
ok. so after some folling, did do a new project. everything works now. dont know why it did. because everything was the same settings, even c was used

here is the new, working project
[RAYRAY.zip](https://github.com/raysan5/raylib/files/384907/RAYRAY.zip)

**Comment by paezao** [comment]
Nice! Im glad it worked!
