### ISSUE TITLE
[templates] template makefiles not building on RPI 3

### ISSUE THREAD

**Issue by npisanti** [raysan5/raylib#1580]
Hi, i was trying to compile one of my projects on a Raspberry Pi 3 starting from the included makefiles, but there is a bug in them:

if i do `make PLATFORM=PLATFORM_RPI` it complains about `mingw32-make: Command not found`, aborting the compilation. 

Probably the error is in this line:
https://github.com/raysan5/raylib/blob/master/templates/simple_game/Makefile#L192
which sets `MAKE` to `make` for the linux OS, but only for `PLATFORM_DESKTOP`.  

I manually changed the default make to `make` to fix it for myself, but i wanted to report this bug to have it working for everyone, if you want i can make a PR.

Thank you for all the work on raylib, i'm using it with my own lua bindings and it has been effortless to use so far =)

**Comment by raysan5** [comment]
@npisanti fixed.
