### ISSUE TITLE
Building with CLion/CMake/Emscripten for Web - [Success Story]

### ISSUE THREAD

**Issue by royalstream** [raysan5/raylib#1584]
To get it to work, I had to deviate slightly from whats recommended [in the wiki](https://github.com/raysan5/raylib/wiki/Working-for-Web-(HTML5)), so this could help some other newcomer (like me!) with a similar setup.

I used the following **CMake options** (find them under **CLion > Preferences > Build,Execution,Deployment > CMake**)

```
-DCMAKE_TOOLCHAIN_FILE=<YOUR PATH HERE>/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
-DPLATFORM=Web
```

I did not use the **-S, -H, -B** options mentioned in the wiki because they were getting in the way. **-B build** in particular was preventing **CLion** from finding the generated files (because it was creating an additional build directory inside CLion's own directory).

I still included this snippet at the top of CMakeLists.txt, with no changes whatsoever:

```
if (EMSCRIPTEN)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -s USE_GLFW=3 -s ASSERTIONS=1 -s WASM=1 -s ASYNCIFY")
  set(CMAKE_EXECUTABLE_SUFFIX ".html") # This line is used to set your executable to build with the emscripten html template so taht you can directly open it.
endif ()
```

This was tested under both **macOS Catalina 10.15.7** and **Windows 10** with **CLion 2020.2** and **Emscripten 2.0.13**

**Comment by raysan5** [comment]
@royalstream Thanks! Added this piece of information [to the Wiki!](https://github.com/raysan5/raylib/wiki/Working-for-Web-(HTML5)#building-with-clioncmakeemscripten-for-web)
