### ISSUE TITLE
[models] IQM bone transform not following parent

### ISSUE THREAD

**Issue by nonunknown** [raysan5/raylib#1587]
### Issue description

Followed the animation at model module example, but the animation is messed!

### Environment
Windows 10 x64
* OpenGL 3.3
* AMD R7 200 series

### Issue Screenshot

https://user-images.githubusercontent.com/58845030/107877003-51bf8880-6ea8-11eb-96bb-b0335632476a.mp4

### Project Files

[ray.zip](https://github.com/raysan5/raylib/files/5977692/ray.zip)

**Comment by chriscamacho** [comment]
does the loader provide all the bone data?

I'd have a stab at making a vertex shader to do this if ....

A) I had 2-3 different examples of bone animation IQM's
b) The loader does in fact provide all the relevant bone data
C) I've I have the time (I've started a new job) fatigue is an issue!

**Comment by chriscamacho** [comment]
I looked at animations with GLTF as well, there is a definite issue there too, so possibly related, as well as messed up transforms there is an issue with missing bones and the anim length

**Comment by raysan5** [comment]
It seems this issue could be solved by previous PR (not tested), I'm closing it. Please, feel free to reopen it if you test it and it does not work yet.
