### ISSUE TITLE
[display detection] on RPI 3  all examples fail to start

### ISSUE THREAD

**Issue by Ted-bissada** [raysan5/raylib#159]
I was able to compile the library and all examples after downloading from the develop branch but upon starting any of the examples this error occurs

```
INFO: Initializing raylib (v1.5.0)
WARNING: DOWNSCALING: Required screen size (800x450) is bigger than display size (0x0)
WARNING: downscale matrix generated, content will be rendered at 0x0
ERROR: Unable to attach EGL rendering content to EGL surface
```

i am not ssh'ing my RPI 3 and have a monitor connected via HDMI with resolution greater than the required 

attempting to open examples from within startx yields the same result

**Comment by raysan5** [comment]
It seems it's not able to connect o display device. Are you trying to run examples from a Terminal after initializing XWindow system?

raylib is prepared to work natively, not under XWindows...

**Comment by raysan5** [comment]
Hi @Ted-bissada, just closed the issue while I was writting... did you solve it? Did you find the problem? Please, let me know!

**Comment by Ted-bissada** [comment]
it was a problem on my end for whatever reason start x would start but $DISPLAY was not set when i used echo $DISPLAY i got a blank line i am still trying to figure it out but it is not an issue with the library

**Comment by raysan5** [comment]
Ok, thank you very much for the feedback! :)
