### ISSUE TITLE
[build] CMake configuration problem on Ubuntu

### ISSUE THREAD

**Issue by pauljurczak** [raysan5/raylib#1590]
I'm using Ubuntu 20.04 with gcc 9.3.0. I have built the shared library from newest source from github following instructions at https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux. The process went fine, examples built and work fine too. I used `cmake-gui` to set some parameters though, because the command line version produced this:
```
paul@extra-kde:~/raylib/build$ cmake -DSHARED=ON -DSTATIC=ON ..
.....
CMake Warning:
  Manually-specified variables were not used by the project:

    SHARED
    STATIC
```
In order to produce shared library, I checked `BUILD_SHARED_LIBS` or run:
```
paul@extra-kde:~/raylib/build$ cmake -DBUILD_SHARED_LIBS=ON ..
```

**Comment by raysan5** [comment]
Hi @pauljurczak, thanks for reporting. I don't maintain the CMake build system, let's see if some other user can send a PR with a fix...

**Comment by object71** [comment]
@raysan5 We just need to update the documentation after the refactorings.
@pauljurczak This was refactored recently and the documentation is just not updated - there no logner is SHARED and STATIC (as you cannot use both at the same time) and there is only one BUILD_SHARED_LIBS

**Comment by object71** [comment]
@raysan5 I updated the documentation - you could close this issue.

**Comment by raysan5** [comment]
@object71 thank you very much!
