### ISSUE TITLE
Please Create an Macosx Installer for RayLib3.5

### ISSUE THREAD

**Issue by FaSasoftware** [raysan5/raylib#1592]
Hi, it's very difficult to install and make an example with Raylib3.5 for MacOS X Big Sur...I'm trying to develop games with Netbeans 12.1 , but without success...Can you make an installer to make our life easier??? Or better with Netbeans 12 and Raylib 3.0 it worked quite easy.... now you have added libraylib.a  ...but how I can set up Netbeans??? I'm very near to success but I don't have the right track.  I have successfully installed it with homebrew but I can't go on...Please I need help as soon as possible..Thanks, A lot, Lestroso

**Comment by raysan5** [comment]
Sorry, no plans for that, I never had a mac.
