### ISSUE TITLE
[models] GLTF loading issues

### ISSUE THREAD

**Issue by homeless-schizo-retard** [raysan5/raylib#1593]
Didn't see any duplicate issues.

### Environment
I'm using the latest Raylib version from master branch on ubuntu 20.10, gcc with very modern hardware. Models exported with blender 2.91.2

### First issue
Loading any GLTF file I've tried using the LoadModel() function causes a segmentation fault roughly half of the time, the problem gets much worse when loading multiple files. Sometimes it works but mostly it crashes at launch of the program.

**Compiling with the following command, all code is in a single .cpp file:** 
g++ *.cpp -w -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o test

**Some potentially relevant info from the terminal when it crashes:**
```
INFO: FILEIO: [resources/models/characters/wehrmacht_soldier.glb] File loaded successfully
INFO: MODEL: [resources/models/characters/wehrmacht_soldier.glb] glTF meshes (glb) count: 3
INFO: MODEL: [resources/models/characters/wehrmacht_soldier.glb] glTF materials (glb) count: 1
Segmentation fault (core dumped)
```

**Output when I run the program through gdb:**
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555cdbfc in LoadGLTF (
    fileName=0x55555563a0c0 "resources/models/characters/wehrmacht_soldier.glb") at /home/schizo/raylib/src/models.c:3845
3845    /home/schizo/raylib/src/models.c: No such file or directory.
(gdb)
```

**Secondary issue**
loaded GLTF models don't have applied textures when exported from blender. This is likely due to blender encoding it as .jpg but I haven't been able to load textures without explicitly loading the texture and applying it to the material regardless of export settings.

```
#include <stdio.h>
#include <stdlib.h>
#include <vector>
#include <math.h>
#include "raylib.h"
#include "raymath.h"
#define RAYGUI_IMPLEMENTATION
#define RAYGUI_SUPPORT_ICONS
#include "lib/raygui.h"
#undef RAYGUI_IMPLEMENTATION

typedef struct {
    Model m_model;
    Texture2D m_texture;    
    Transform m_transform;
} Soldier;

Soldier* SpawnSoldier(const char* model_path, const char* tex_path)
{
    Soldier* soldier = (Soldier*)malloc(sizeof(Soldier));

    soldier->m_model = LoadModel(model_path);
    soldier->m_texture = LoadTexture(tex_path);
    for(int i=0;i<soldier->m_model.materialCount;++i)
        soldier->m_model.materials[i].maps[MAP_DIFFUSE].texture = soldier->m_texture;

    soldier->m_transform.translation = (Vector3){0,0,0};

    return soldier;
}
void DestroySoldier(Soldier* soldier)
{
    UnloadTexture(soldier->m_texture);
    UnloadModel(soldier->m_model);
    free(soldier);
}

int main()
{
    SetConfigFlags(FLAG_WINDOW_RESIZABLE);
	InitWindow(1280,720, "Raylib");
	SetTargetFPS(60);

    Camera camera = { 0 };
    camera.position = (Vector3){ 10, 1.8f, 10 };
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
    camera.fovy = 60.0f;
    camera.type = CAMERA_PERSPECTIVE;
    SetCameraMode(camera, CAMERA_FREE);

    Soldier* wehrmacht_guy = SpawnSoldier("resources/models/characters/wehrmacht_soldier.glb", "resources/models/characters/wehrmacht_d.png");
    Soldier* soviet_guy = SpawnSoldier("resources/models/characters/soviet_soldier.glb", "resources/models/characters/soviet_d.png");

    wehrmacht_guy->m_transform.translation = (Vector3){-2,0,0};
    soviet_guy->m_transform.translation = (Vector3){2,0,0};

    while (!WindowShouldClose())
    {
        UpdateCamera(&camera);

        BeginDrawing();
            ClearBackground(RAYWHITE);

            BeginMode3D(camera);
            DrawGrid(50, 10.0f);
            DrawPlane((Vector3){0,-0.05f,0}, (Vector2){500,500}, DARKGREEN);
            DrawCube((Vector3){4,1,0},1,2,0.5f,GOLD);

            DrawModel(wehrmacht_guy->m_model, wehrmacht_guy->m_transform.translation, 1, WHITE);
            DrawModel(soviet_guy->m_model, soviet_guy->m_transform.translation, 1, WHITE);

            EndMode3D();

        EndDrawing();
    }

    DestroySoldier(wehrmacht_guy);
    DestroySoldier(soviet_guy);
    CloseWindow();
	return 0;
} 
```

### Screenshot from when it doesn't crash
![image](https://user-images.githubusercontent.com/50094833/108007668-4310d700-704a-11eb-83b6-af3b3a525e95.png)

**Comment by nezvers** [comment]
I haven't done any 3D importing with Raylib, but have some experience working with Godot. Have you tried Gltf Embedded?

**Comment by object71** [comment]
@homeless-schizo-retard Do you have a problem sharing your glb model? I can see that there is some warning there "glTF bones in unexpected format" and we can further investigate that.

**Comment by homeless-schizo-retard** [comment]
> @homeless-schizo-retard Do you have a problem sharing your glb model? I can see that there is some warning there "glTF bones in unexpected format" and we can further investigate that.

Well the problem also persists with any gltf file I've tried downloading from the net or exporting with blender. I've treid glb, gltf + bin and gltf as well as different export settings.

**Comment by raysan5** [comment]
@homeless-schizo-retard Please, could you provide some sample file you verified that does not work properly?

**Comment by homeless-schizo-retard** [comment]
@raysan5 Here is an archive of a couple that I've tried working with [character 7z files](https://files.catbox.moe/4iaip7.7z)

**Comment by rennurb3000** [comment]
Hi i also wanted to confirm, that i also cannot load gltf (and even obj files) on ubuntu 20.04 (master branch).
Even the examples wont work and default to the cube

**Comment by rennurb3000** [comment]
3.0.0 was ok

**Comment by object71** [comment]
@rennurb3000 I fixed the last issue with the cube

**Comment by object71** [comment]
I didn't have a problem loading the models you provided. One of the models doesn't have an embedded texture but otherwise all worked as expected on my side. I compile on windows using cmake and visual studio though so I guess someone with a linux environment could be more helpful.

**Comment by homeless-schizo-retard** [comment]
> I didn't have a problem loading the models you provided. One of the models doesn't have an embedded texture but otherwise all worked as expected on my side. I compile on windows using cmake and visual studio though so I guess someone with a linux environment could be more helpful.

For me sometimes it works and sometimes it segfaults. If you try and load multiple it's way more likely to segfault

**Comment by object71** [comment]
@homeless-schizo-retard I'm sorry I just cannot reproduce. I can spin up a virtual machine at some point to test it under linux but I couldn't reproduce the segfault even 1 out of 20 times. I also tried both Visual C++ and MinGW on windows. This crash is most probably some linux or build setup issue.
