### ISSUE TITLE
Milestones and connected Issues

### ISSUE THREAD

**Issue by paezao** [raysan5/raylib#160]
Hello @raysan5 

Can we have a milestone toward the next version and maybe the issues to get to those milestones?

That would be really helpful to those willing to contribute :D

**Comment by raysan5** [comment]
Hi @paezao, just set next milestone for some of the issues Iisted. 

Still reviewing additional features and improvements before adding them to the list. I prefer to keep it under control and not overloaded...

**Comment by paezao** [comment]
Awesome, thanks @raysan5 !
