### ISSUE TITLE
[rlgl] Memory leak regarding meshes

### ISSUE THREAD

**Issue by Crydsch** [raysan5/raylib#1603]
In `models.h` all `GenMesh*` methods allocate memory for `mesh.vboId`. But in `rlgl.h` in the method `rlUnloadMesh()` there is no `RL_FREE(mesh.vboId)`.

**Comment by Crydsch** [comment]
I just found this function in `model.h`, so there its taken care of, but i guess it should be in `rlgl.h`.
```C
// Unload mesh from memory (RAM and/or VRAM)
void UnloadMesh(Mesh mesh)
{
    rlUnloadMesh(mesh);
    RL_FREE(mesh.vboId);
}
```

**Comment by raysan5** [comment]
Reviewed on latest commit, now every module (`rlgl`, `models`) takes care of the corresponding loaded data. `models` takes care of loading/unloading vertex data and `rlgl` takes cares of OpenGL related data.
