### ISSUE TITLE
TUI

### ISSUE THREAD

**Issue by jjacenty** [raysan5/raylib#1607]
Hello, 

How to adapt raylib to a text environment, I mean [TUI](https://en.wikipedia.org/wiki/Text-based_user_interface)
Is there a plan to make a TUI module? Or simulating in this graphical environment, a text-based environment.

**Comment by raysan5** [comment]
raylib is a primary a games programming library and it's expected to work with a graphic canvas but you can create text-style tools like [Midday Commander](https://github.com/Guevara-chan/Midday-Commander).
