### ISSUE TITLE
[compiling] could ios be a future addition?

### ISSUE THREAD

**Issue by lewislepton** [raysan5/raylib#161]
as the title suggests, was more wondering if this could be a future thing with raylib?

i know you personally dont have a mac, but really a thought on if it could become a thing would be nice since android is possible

cheers

**Comment by raysan5** [comment]
It shouldn't be complicated but I don't have and iOS device to test and that's a handicap...

**Comment by paezao** [comment]
I'm sure we can get something going soon.

**Comment by lewislepton** [comment]
all those words i like - except for the no device thing. but all the other words, i like ;)

**Comment by raysan5** [comment]
I've reviewed some old notes on making raylib work on iOS and it's more complicated than expected... Additionally, Apple has already bet for its new graphics API Metal and not sure how long OpenGL ES will be supported...

**Comment by raysan5** [comment]
So, for the moment, no plans to support iOS. If someone feels brave enough to deal with hell, feel free.
