### ISSUE TITLE
[models] Loading a mesh after an unload fails, giving a warning on re-loading a mesh

### ISSUE THREAD

**Issue by coochewgames** [raysan5/raylib#1615]
Entering the following steps:

```
mesh = GenMeshPlane(10, 10, 4, 4);
rlUnloadMesh(&mesh, false);
rlLoadMesh(&mesh, false);
```
or
```
mesh = GenMeshPlane(10, 10, 4, 4);
UnloadMesh(mesh);
UploadMesh(&mesh);
```

gives the following output:

```
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 2] Unloaded vertex data from VRAM (GPU)
WARNING: VAO: [ID 2] Trying to re-load an already loaded mesh
```
and the second load mesh fails.

**Comment by raysan5** [comment]
I'm afraid solving this issue would require a big redesign of the API. raylib current Model/Mesh API is designed to be simple, dealing with structs directly like all the other raylib functions but in this situation, it would require to a complete redesign of Model/Mesh API to use pointers instead, so, it could be properly checked if a Model/Mesh has been loaded/unloaded.

**Comment by coochewgames** [comment]
Thanks for such a detailed explanation; does this entail that a mesh cannot ever be unloaded from the GPU?

**Comment by raysan5** [comment]
> does this entail that a mesh cannot ever be unloaded from the GPU?

@coochewgames nope, it is perfectly unloaded but it's not possible to reset the mesh id to know it was unloaded for future checks because raylib deals with a copy of the object instead of a reference. So, mesh is unloaded from gpu using its internal id but the id can not be reseted to 0 or -1.

**Comment by coochewgames** [comment]
Thanks again for the explanation; will just keep track of the mesh ids to make sure they are not re-used :-)

Is a big relief as I will be creating and removing a lot of meshes for the landscape.

**Comment by ssoher** [comment]
@raysan5 sorry for necro posting on this ancient issue but better than creating a new one.

I'm having trouble with this. I have to unload a mesh and immediately after that, allocate new space for the unloaded mesh, re-generate it and upload it to the gpu. What is the correct way of doing this on my side if Raylib still doesn't offer a way to do this for I'm also getting the "Trying to re-load an already loaded mesh"?
