### ISSUE TITLE
glfwPostEmptyEvent

### ISSUE THREAD

**Issue by paveb85394** [raysan5/raylib#1617]
Is there anyway to call glfwPostEmptyEvent from a thread to force my render loop to render after waiting for events.

**Comment by raysan5** [comment]
raylib provides the compilation flag `SUPPORT_EVENTS_WAITING` to allow stopping the main loop until an event is received, it uses internally `glfwWaitEvents()` but raylib does not expose `glfwPostEmptyEvent()`.

In any case, GLFW is linked with raylib by default, so, you can just declare `glfwPostEmptyEvent()` function or include `glfw.h` to use it in your code.
