### ISSUE TITLE
[core] Everything runs too fast on FreeBSD, SetTargetFPS(60) not working

### ISSUE THREAD

**Issue by thedaemon** [raysan5/raylib#1618]
FreeBSD 13. This was also an issue on FreeBSD 12.2 for me. Anything that I have compiled from the examples (lots of them) run too fast. I'm talking like 3000+ FPS even though

   SetTargetFPS(60);

It does nothing. changing this to anything, doesn't do anything on FreeBSD. Suggestions?

**Comment by raysan5** [comment]
@thedaemon Are you running it on Desktop? raylib uses internally GLFW library and `glfwGetTime()` for time measurement and framerate limitations. It seems function may not be working properly...

**Comment by thedaemon** [comment]
I am running it on a Desktop. Ryzen 2700X, 16GB, Nvidia 960GTX with Nvidia binary drivers. Tested with FreeBSD 12.2 and 13. I can see if I can figure out how to test the glfwGetTime() code on my system if you need me to?

**Comment by raysan5** [comment]
@thedaemon I took a closer look and it seems issue can be in `Wait()` function [used here](https://github.com/raysan5/raylib/blob/master/src/core.c#L1861). 

Just noticed this piece of code on `Wait()`:
```c
    #if defined(_WIN32)
        Sleep((unsigned int)ms);
    #elif defined(__linux__) || defined(PLATFORM_WEB)
        struct timespec req = { 0 };
        time_t sec = (int)(ms/1000.0f);
        ms -= (sec*1000);
        req.tv_sec = sec;
        req.tv_nsec = ms*1000000L;

        // NOTE: Use nanosleep() on Unix platforms... usleep() it's deprecated.
        while (nanosleep(&req, &req) == -1) continue;
    #elif defined(__APPLE__)
        usleep(ms*1000.0f);
    #endif
```

Probably `__FreeBSD__` should also be checked, could you try it?

**Comment by raysan5** [comment]
@thedaemon I pushed a possible fix, please let me know if it works.

**Comment by thedaemon** [comment]
I am having issues compiling.
make              ✔  08:16:24 AM 
-- Testing if -Werror=pointer-arith can be used -- compiles
-- Testing if -Werror=implicit-function-declaration can be used -- compiles
-- Testing if -fno-strict-aliasing can be used -- compiles
-- Using raylib's GLFW
-- Using X11 for window creation
-- Audio Backend: miniaudio
CMake Warning (dev) at /usr/local/share/cmake/Modules/FindOpenGL.cmake:293 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/local/lib/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/local/lib/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/local/lib/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  cmake/LibraryConfigurations.cmake:20 (find_package)
  src/CMakeLists.txt:56 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Building raylib static library
-- Generated build type: Debug
-- Compiling with the flags:
--   PLATFORM=PLATFORM_DESKTOP
--   GRAPHICS=GRAPHICS_API_OPENGL_33
-- Building examples is enabled
-- Testing if -std=c11 can be used -- compiles
-- Configuring done
-- Generating done
-- Build files have been written to: /home/thedaemon/src/raylib/raylib-master/build
[  1%] Building C object raylib/external/glfw/src/CMakeFiles/glfw_objlib.dir/posix_time.c.o
/home/thedaemon/src/raylib/raylib-master/src/external/glfw/src/posix_time.c:81:9: error: implicit declaration of function 'gettimeofday' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        gettimeofday(&tv, NULL);
        ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/thedaemon/src/raylib/raylib-master/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/thedaemon/src/raylib/raylib-master/build
*** Error code 1

Stop.
make: stopped in /usr/home/thedaemon/src/raylib/raylib-master/build

**Comment by raysan5** [comment]
@thedaemon It seems this issue is related to GLFW of FreeBSD libraries... no idea... I've found [this bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210856), maybe related.

**Comment by raysan5** [comment]
Feel free to reopen if issue persist.

**Comment by julienXX** [comment]
@thedaemon use `-DUSE_EXTERNAL_GLFW=ON` option to cmake (and pkg install glfw)

Otherwise I have the same issue under FreeBSD 13 and raylib master.
