### ISSUE TITLE
[shapes] A little error in the function of the collision between lines

### ISSUE THREAD

**Issue by AngelJumbo** [raysan5/raylib#1620]
In the function CheckCollisionLines(....) I found this bit of code:
`const float xi = ((startPos2.x - startPos2.x)*(startPos1.x*endPos1.y - startPos1.y*endPos1.x) - (startPos1.x - endPos1.x)*(startPos2.x*endPos2.y - startPos2.y*endPos2.x))/div;`

"startPos2.x - startPos2.x" is always 0.

**Comment by raysan5** [comment]
Reviewed in commit https://github.com/raysan5/raylib/commit/3f6a08535fab019512f7c4560878d76fee77f83a.
