### ISSUE TITLE
[Models] GLTF import issues

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib#1623]
I have identified a few problems with the GLTF file reader that cause problems when loading animations.

It appears that bone IDs are only assigned when a mesh primitive has the cgltf_attribute_type_joints attribute.
In this file, the primitives do not have this attribute, but instead each node in the bone tree directly references a specific mesh ID.
[PrototypePete.zip](https://github.com/raysan5/raylib/files/6058927/PrototypePete.zip)

The animation system also assumes that all mesh vertices are pre-transformed to align with the binding pose. In this model this is also not true. The meshes are at the origin and are expecting to be transformed by the bone that references them.

Given these assumptions, this means that no bones are ever assigned to the models, nothing is transformed, and the mesh is drawn incorrectly.

A Raylib rendering of a similar model
![image](https://user-images.githubusercontent.com/322174/109447699-1d47e280-79f9-11eb-890d-0609543a1100.png)

A GLTF Viewer image for reference
![image](https://user-images.githubusercontent.com/322174/109447719-2769e100-79f9-11eb-8b8f-712882a31311.png)

I do not know a lot about the animation system, but it seems that there needs to be a pass during read that assigns bones and transforms vertices of the meshes that the bones directly reference.

I was able to confirm my suspicions by doing a test.
First I added a quick and dirty bone assignment after each primitive is read in, checking to see if it has no bones, and if a bone references it. I don't believe this is the correct fix, but it at least gets me valid bone IDs for this file.

    if (model.meshes[primitiveIndex].boneIds == NULL && data->nodes_count > 0) 
                    {  
                        for (int nodeId = 0; nodeId < data->nodes_count; nodeId++)  
                        {  
                            if (data->nodes[nodeId].mesh == &(data->meshes[i]))  
                            {  
                                model.meshes[primitiveIndex].boneIds  = RL_CALLOC(4 * model.meshes[primitiveIndex].vertexCount, sizeof(int));  
                            model.meshes[primitiveIndex].boneWeights = RL_CALLOC(4 * model.meshes[primitiveIndex].vertexCount, sizeof(float));  
                            for (int b = 0; b < 4 * model.meshes[primitiveIndex].vertexCount; b += 4)  
                            {  
                                model.meshes[primitiveIndex].boneIds[b] = nodeId;  
                                model.meshes[primitiveIndex].boneWeights[b] = 1.0f;  
                            }  
                        }  
                    }  
                }  

Next I created a fake animation frame that is a copy of the bind pose, and then I cleared the bind pose transformatio, so the bind pose is only applied once.

    Model character = LoadModel("resources/PrototypePete.gltf");
    int animCount = 0;
    ModelAnimation anim;
    anim.boneCount = character.boneCount;
    anim.bones = character.bones;
    anim.frameCount = 1;
    anim.framePoses = MemAlloc(1 * sizeof(Transform*));
    anim.framePoses[0] = MemAlloc(1 * character.boneCount * sizeof(Transform));
    for (int i = 0; i < character.boneCount; i++)
    {
        anim.framePoses[0][i].translation = character.bindPose[i].translation;
        anim.framePoses[0][i].rotation = character.bindPose[i].rotation;
        anim.framePoses[0][i].scale = character.bindPose[i].scale;
        character.bindPose[i].translation = Vector3Zero();
        character.bindPose[i].rotation = QuaternionIdentity();
     //   character.bindPose[i].scale = Vector3Zero();
    }
    UpdateModelAnimation(character, anim, 0);

With this in place, the model does render correctly, so I believe that I have at least identified where the problem is.
![image](https://user-images.githubusercontent.com/322174/109448398-baefe180-79fa-11eb-8707-4038adb73b6d.png)

**Comment by raysan5** [comment]
@JeffM2501 Wow! Very nice! Please, feel free to send a PR with the review.

**Comment by JeffM2501** [comment]
Well that's part of the problem and the reason I wanted to open this issue for discussion. I don't know the correct fix. 
I do not know enough about the format to know if there will be cases where mesh primitives will have cgltf_attribute_type_joints  and bone nodes that directly reference meshes. In this case should the primitives' geometry still be transformed? Should they get a bone entry?

**Comment by raysan5** [comment]
Mmmh... yeah, I see... I'm afraid I neither know enough about the format to answer those questions... maybe @object71 can help with it?

**Comment by object71** [comment]
I am not proficient enough either, last time I just researched (I own a book). I will check it out at some point

**Comment by JeffM2501** [comment]
I've done a little more research and tried a different gltf library.
https://github.com/syoyo/tinygltf

It includes a gltf viewer, and it does display my files correctly
![image](https://user-images.githubusercontent.com/322174/109838897-6e272900-7bfb-11eb-99b5-c7bf5bb6b8b4.png)

So hopefully when I have time I can go through what this library does for these elements and see what the right way to transform them is.

**Comment by object71** [comment]
@JeffM2501 Your solution looks good enough to me I will implement it (though in the for loop that assigns the bones I am also putting default values for the other 3 bones and their weights to 0. I am still considering what would be a good place to bind to the initial pose provided in gtlf.

**Comment by object71** [comment]
https://github.com/object71/raylib/tree/gltf-model-and-animations-exploring-problems I have this branch for the solution you initially proposed for loading the bones into the mesh. If you ifnd a better solution in tinygltf please post it here

**Comment by JeffM2501** [comment]
> https://github.com/object71/raylib/tree/gltf-model-and-animations-exploring-problems I have this branch for the solution you initially proposed for loading the bones into the mesh. If you ifnd a better solution in tinygltf please post it here

This does solve the issue of the model not crashing when drawing because it does have bone IDs, I think it is the correct fix for this part of the problem given how raylib stores animation.

The larger part of the issue is still the transform part, as your branch doesn't crash, but also does not draw the models correctly. I'm moving this weekend so I won't have time to look into the other lib for a bit.

**Comment by object71** [comment]
Okay I will then look into loading the models into the initial bound pose.

**Comment by JeffM2501** [comment]
I've done some digging into how tinyGLTF works. It renders and stores animations in a completely different way from raylib. It starts drawing from the bone tree first, always pushing the current bone transformation before drawing the mesh.  This is actually much more efficient since you don't have to re-upload vertices that are only attached to one bone since the bone transform will take care of it.

So I think that the assumption that all verts are in the root bone position is not true for GLTF and all verts associated with a mesh on a bone must be transformed. It may be best to apply this transformation to the GLTF models right after they are read, before trying to split them up by material and copy them to raylib structures.
