### ISSUE TITLE
compile error when using it with boost

### ISSUE THREAD

**Issue by repane4229** [raysan5/raylib#1625]
I am trying one of the examples and when i try and include #include <boost/beast/ssl.hpp>
i a am usinf visual studio 2019 and using the vcpkg verson on ray lib

i get compile errors
error C2733: 'CloseWindow': you cannot overload a function with 'extern "C"' linkage
message : see declaration of 'CloseWindow'
error C2733: 'ShowCursor': you cannot overload a function with 'extern "C"' linkage
message : see declaration of 'ShowCursor'
error C2664: 'int DrawTextW(HDC,LPCWSTR,int,LPRECT,UINT)': cannot convert argument 1 from 'const char [40]' to 'HDC'
message : see declaration of 'DrawTextW'

**Comment by raysan5** [comment]
@repane4229 This issue is related to `windows.h` duplicate symbols, here it is a proposed solution https://github.com/raysan5/raylib/issues/1217.
