### ISSUE TITLE
[camera] Camera look initial mouse position

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1628]
- [ X ] I tested it on latest raylib version from master branch
 - [ X ] I checked there is no similar issue already reported
 - [ ? ] My code has no errors or misuse of raylib

### Issue description

If the mouse position is set to the centre of the screen before the main loop starts, I would expect that
the 3d camera view would be looking down the Z axis

I believe this to be caused by the fact that the previous mouse position is initialised to 0,0 not the centre of the screen. (UpdateCamera)

Having said that using SetMousePosition followed by UpdateCamera several times before the main loop does not work...

### Environment

Multiple Linux distros, multiple GL versions on different GPU's

### Issue Screenshot

TODO insert picture of camera view looking at an odd angle

### Code Example

TODO there's probably an existing raylib example i can add SetMousePosition to just before the main loop

NB in a rush will do the TODO's later if they are really needed...

**Comment by raysan5** [comment]
Current camera system implementation should be redone from scratch.

**Comment by chriscamacho** [comment]
from memory I think you've said this before, to be honest as it is such a fundemental I think it needs to be properly spec'd out before any work starts

exactly how should it behave ?, what should and should be parametrised etc

**Comment by raysan5** [comment]
I'm linking this issue to #1143 and closing, they are related.

About the initial mouse position, yes, that's an issue with `UpdateCamera()`, it's not considering initial camera parameters properly.
