### ISSUE TITLE
[core] potential fix for stuttering on Linux

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1634]
I know this is a bug bear of an issue...

I was experiencing really bad stuttering when experimenting with my TMX loader and parallax scrolling layers.  (oddly never noticed this with 3D ???)

in the end in config.h I commented out the BUSY WAIT and HALF BUSY WAIT defines

and in my application
    SetWindowState(FLAG_VSYNC_HINT + FLAG_MSAA_4X_HINT);
    SetTargetFPS(100000);

obviously as you are relying on glfw's sync which is dependant on whatever GPU/monitor is connected, then you need to use larger movement vectors multiplied by GetFrameTime()

**Comment by chriscamacho** [comment]
nah, while it is better its still stuttering, it NOT under high load according to GetTime() the entire update / render loop is taking at worst less than 0.5 millisecond (and often much less .02 milliseconds at best! no busy loop, busy loop 1/2 busy loop look very similar in timings, when looking from outside the Begin/EndDrawing section)

so the main render loop isn't the cause here, I've tried with GPU sync on/off, compositing on/off and multiple combinations

**Comment by raysan5** [comment]
@chriscamacho Actually, this issue was also noted in the past and it seems highly platform dependent.

**Comment by chriscamacho** [comment]
ok I think I have it!

    //with SUPPORT_HALFBUSY_WAIT_LOOP in config.h
    SetWindowState(FLAG_VSYNC_HINT + FLAG_MSAA_4X_HINT);
    SetTargetFPS(100000);

seems to work really well, it obviously noticable

with
    SetTargetFPS(60)

it sometimes looks okish and then will have bouts of looking really very horrible, tearing partway down the screen and bad stuttering.

I did try with clock_nanotime but that seems to have no impact at all

**Comment by raysan5** [comment]
@chriscamacho Actually, just enabling `SetWindowState(FLAG_VSYNC_HINT)` and omitting `SetTargetFPS()` should have the same result.

**Comment by chriscamacho** [comment]
using my test code using just glfw and GL 3v3 (under more load) which doesn't use any kind of wait timer just relying on glfwSwapInterval, it runs butter smooth in comparison, this is definitely and issue with Raylib

It would be nice to see a flag that removes all waits completely, just relying swap interval, however there must be some other issue here, as when I commented out all the wait code, there were still issues.

**Comment by chriscamacho** [comment]
commenting out the joystick section of poll inputs and commenting out SUPPORT_BUSY_WAIT_LOOP and SUPPORT_HALFBUSY_WAIT_LOOP makes a significant difference

after triple! checking, the game pad section of poll inputs seems to be causing an issue - could glfw events be handled in a separate thread ?

btw I don't have any joystick plugged into my system, so this could be part of the problem?

the sleep code (which isn't actually needed - save for badly configured systems) does contribute, but at least they can be config'd away....

**Comment by chriscamacho** [comment]
something very odd happening, I'm not seeing this AT ALL with 3D !

Even running with 1000's 3D physics objects, spheres for example roll smoothly all the time...

**Comment by raysan5** [comment]
Mmmh... joystick event just uses GLFW3 mechanism... maybe there is some issue there...

A part from that, no idea.

**Comment by chriscamacho** [comment]
it probably isn't the issue, doesn't happen at all with 3D

**Comment by chriscamacho** [comment]
After extensive hacking! I discovered if I give the GPU enough to do the issue goes away, so I'm closing this

Theres more info on Raylibs sub reddit
