### ISSUE TITLE
[core] High CPU usage on Linux (Ubuntu)

### ISSUE THREAD

**Issue by ZaneL** [raysan5/raylib#1640]
Hello,

I've packaged a raylib example (core_2d_camera) into a snap image and I noticed that it had a relatively high CPU usage on my linux laptop (~27%). I went ahead and built this same example normally to see if the snap image was the culprit, but it still maintained a CPU usage of ~27%.

When building and running this same example on my windows desktop PC (which is admittedly faster) it gets ~2% CPU usage. Below is the output from the snap version of this example. It does appear to be working, but it's definitely a little "stuttery" (so is the normal linux version). I guess I'm just wondering if this seems correct to you? It's such a simple 2D application that it almost seems like something isn't working quite right on this linux build...

```
INFO: Initializing raylib 3.5
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: Quadro K1000M/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 390.141
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: Supported extensions count: 340
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: GL: Mirror clamp wrap texture mode supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 1] Unloaded default texture data from VRAM (GPU)
INFO: Window closed successfully
```

**Comment by raysan5** [comment]
Probably related issues: #415 #217

The CPU usage shown is probably related to the `SUPPORT_HALF_BUSY_WAIT_LOOP` option enabled by default to sync framerate, my recommendation is that you try enabling VSync.

**Comment by ZaneL** [comment]
I did a few experiments.

I left everything how it was, added SetConfigFlags(FLAG_VSYNC_HINT) and the CPU usage didn't change. I then removed that flag and defined `SUPPORT_BUSY_WAIT_LOOP` to core.c, recompiled everything and the CPU usage was 100%.

I then reverted everything to the default settings and even after running callgrind on the app to profile it, I can't see anything that sticks out. The functions that are taking up the most total time are:

DrawText()
DrawRectanglePro()
DrawTexturePro()

When I change the FPS from 60 to 30 the CPU usage drops in half. I can't figure out if it's just an nvidia driver issue? I'm using their latest proprietary driver, so idk...

**Comment by chriscamacho** [comment]
@ZaneL  did you remember to remove SetTargetFPS, something I keep forgetting about!

**Comment by ZaneL** [comment]
I'm an idiot. The problem is that using the "top" command on linux to display the CPU usage displays the load based on one core. When you look at the windows resource monitor it calculates the CPU usage based on all cores. Long story short, when using the system monitor tool in ubuntu( which calculates the CPU usage the same way as windows), it actually performs better for me on Linux when compared to Windows - 3% vs 5%.

**Comment by chriscamacho** [comment]
don't feel too bad unless you sync to frame and DON'T use SetTargetFPS there really is an issue (see this profile dump https://github.com/raysan5/raylib/files/6117750/profile-with.txt)

**Comment by oziris78** [comment]
SetTargetFPS(60) worked for me, thanks!
