### ISSUE TITLE
[Math] MatrixRotateZYX

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1642]
When I first contributed MatrixRotateZYX, (I think some time ago now) I struggled to get it right ! In the end using three calculated X,Y & Z matrices multiplied together which isn't ideal ! I did assume someone would look at this, shake their head, and do it right by now...

In the course of doing my matrix chain sandbox project, I ended up looking again at this, the project came in handy to test this as I was able to put different formula in for each axis and have a key toggle between the old and new versions, happily they have the same result !

```C
Matrix MyMatrixRotateZYX(Vector3 ang)
{
    Matrix result;

    float cz = cosf(ang.z);
    float sz = sinf(ang.z);
    float cy = cosf(ang.y);
    float sy = sinf(ang.y);
    float cx = cosf(ang.x);
    float sx = sinf(ang.x);

    result.m0  = cz * cy;
    result.m1  = (cz * sy * sx) - (cx * sz);
    result.m2  = (sz * sx) + cz * cx * sy;
    result.m3  = 0; 

    result.m4  = cy * sz;
    result.m5  = (cz * cx) + (sz * sy * sx);
    result.m6  = cx * sz * sy - cz * sx;
    result.m7  = 0;

    result.m8  = -sy;
    result.m9  = (cy * sx);
    result.m10 = cy * cx;
    result.m11 = 0;
    
    result.m12 = result.m13 = result.m14 = 0;
    result.m15 = 1;
    
    return result;
}
```
Looks like such a trivial piece of code...

**Comment by raysan5** [comment]
implemented!
