### ISSUE TITLE
[models] Procedural Mesh generation

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#165]
Some time ago I started creating a bunch of functions to support some procedural Mesh generation, I thought it could be interesting for education and also useful at some point. The functions proposed are:

``` c
Mesh GenMeshPlane(float width, float length, int resX, int resZ);
Mesh GenMeshCuboid(float width, float height, float length);
Mesh GenMeshSphere(float radius, int rings, int slices);
Mesh GenMeshCylinder(float radiusTop, float radiusBottom, float height, int slices);
Mesh GenMeshTorus(float radius1, float radius2, int radSeg, int sides);
Mesh GenMeshTube(float radius1, float radius2, float height, int sides);
```

The idea was generating quite complete meshes, at least including texcoords and normals for texturing and lighting.

Unfortunately I left some implementations incomplete... Just attaching here my sample code if someone wants to take a look, test it or continue with it.

[gen_models_mesh.zip](https://github.com/raysan5/raylib/files/386327/gen_models_mesh.zip)

**Comment by paezao** [comment]
Would that be useful for voxel games?

**Comment by raysan5** [comment]
not really, it would be useful for fast 3d prototyping, to define basic level volumes or to create simple 3d games.

**Comment by zwparchman** [comment]
These sound great and would solve a problem I currently have. Mesh union would also be nice to have to create meshes with a few of these primitives.

**Comment by raysan5** [comment]
As long as Image procedural generation fucntionality (#164) has been added, support for some mesh generation functions would be very useful on next raylib version.

**Comment by raysan5** [comment]
After some work on this feature, I found [par_shapes](http://github.prideout.net/shapes), a great header-only C library to generate some mesh shapes. I'll be using it, unfortunately some things doesn't work the way I would like, some texture coordinates are not generated for some shapes, no cone shape, no tube, no pyramid...

Also checking some other interesting references: 

https://gamedev.stackexchange.com/questions/56045/procedural-geometry-generation
https://en.wikipedia.org/wiki/Torus#Geometry
**https://github.com/ilmola/generator**

For raylib 1.8, I'm adding following functions:
```c
// Mesh generation functions
Mesh GenMeshPlane(float width, float length, int resX, int resZ);      // Generate plane mesh (with subdivisions)
Mesh GenMeshCube(float width, float height, float length);             // Generate cuboid mesh
Mesh GenMeshSphere(float radius, int rings, int slices);               // Generate sphere mesh (standard sphere)
Mesh GenMeshHemiSphere(float radius, int rings, int slices);           // Generate half-sphere mesh (no bottom cap)
Mesh GenMeshCylinder(float radius, float height, int slices);          // Generate cylinder mesh
Mesh GenMeshTorus(float radius, float size, int radSeg, int sides);    // Generate torus mesh
Mesh GenMeshKnot(float radius, float size, int radSeg, int sides);     // Generate trefoil knot mesh
```
Implemented in commit https://github.com/raysan5/raylib/commit/20968830c0a8721c2a2d94719da5fe2cd753c114
