### ISSUE TITLE
[raymath] QuaternionFromEuler params mis labeled 

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1651]
the parameters are named in order Roll Pitch Yaw, which struck me as odd (ZXY !)

if you put an X axis rotation value into roll, a Y in pitch and a Z axis into yaw:

it behaves exactly as MatrixRotateZYX  ! (params specified as xyz, it's the rotation order that's ZYX !)

in any case the roll parameter is definitely effecting the X axis (X axis is pitch) 
the pitch (param) is effecting the Y axis (yaw axis)
and the yaw parameter is effecting the Z axis (roll)  

The names of the sine / cosine variables reinforce this confusion

While the routine is exactly correct in behaviour as xyz angles rotated in the ZYX order (the "correct" order for Euler rotation - contentious...!) the mislabelling of the axes is very confusing, I happened to spot it quickly but then I've been doing three different projects with complex matrix operations just recently - spare a thought for the poor newbie to 3D maths ! 

I'd recommend relabelling the parameters and internal variables and adding a comment that the rotation order is ZYX  so as not to confuse

and don't even start talking about intrinsic v's extrinsic rotations :stuck_out_tongue_winking_eye: !!!

**Comment by raysan5** [comment]
@chriscamacho Feel free to send a PR with the relabelling.

**Comment by chriscamacho** [comment]
I'd be much more inclined if the examples were in a different repo, I'm at the end of a slow unreliable connection currently, I'll post a new version of the function here.

**Comment by raysan5** [comment]
@chriscamacho Just reviewed the function with a more descriptive naming and comment, please could you verify it is correct now?

**Comment by chriscamacho** [comment]
roapy connection permitting I will do so later today

**Comment by chriscamacho** [comment]
QuaternionFromEuler(float yaw, float pitch, float roll)

is still confusing

if I use it like this
QuaternionFromEuler( angleY, angleX, angleZ)

like the parameters suggest it won't work as expected !

**Comment by chriscamacho** [comment]
you have changed the behaviour of this function and broken any existing code relying on it

the previous behavior was correct if you ignored the parameter names and used it like this

QuaternionFromEuler( angleX, angleY, angleZ)

It applied the rotations in ZYX order which is "normal" behaviour for euler to Quat (or Matrix)

**Comment by raysan5** [comment]
@chriscamacho how should it be? could you provide the right implementation?

**Comment by chriscamacho** [comment]
```C
// Returns the quaternion equivalent to Euler angles
// NOTE: Rotation order is ZYX
RMDEF Quaternion QuaternionFromEuler(float pitch, float yaw, float roll)
{
    Quaternion q = { 0 };

    float x0 = cosf(pitch*0.5f);
    float x1 = sinf(pitch*0.5f);
    float y0 = cosf(yaw*0.5f);
    float y1 = sinf(yaw*0.5f);
    float z0 = cosf(roll*0.5f);
    float z1 = sinf(roll*0.5f);

    q.x = x1*y0*z0 - x0*y1*z1;
    q.y = x0*y1*z0 + x1*y0*z1;
    q.z = x0*y0*z1 - x1*y1*z0;
    q.w = x0*y0*z0 + x1*y1*z1;
    
    return q;
}
```

This is previous and I believe correct behaviour, I note that without changing the internal names that they are consistent once the parameters are correctly labelled

the code posted here does not break existing code bases, and works the same a MatrixRotateZYX

**Comment by chriscamacho** [comment]
oh quick test my GUI template uses MRxyz MRzyx and QfE you can graphically see the rotated body stays the same with 2 of them but changes with MRxyz (as expected)

**Comment by raysan5** [comment]
Reviewed.
