### ISSUE TITLE
[examples] All of the examples appear to capture the mouse cursor, and some examples seem not to work at all.

### ISSUE THREAD

**Issue by BigZaphod** [raysan5/raylib#1652]
I'm not sure if these belong as an issue or not, so I apologize up front if this is actually the wrong place for this.

I just ran across this library today and its super cool! I was exploring the examples page in my browser (Safari 14.1 on macOS Big Sur 11.3 beta on a 13" M1 MacBook Pro) and just wanted to note a couple of bits of feedback about them:

* The main thing that prompted me to post an issue is that the examples seem to all be capturing the mouse cursor even if it doesn't seem like they really have to. For example, many of them happily track the mouse movements just fine in the browser but as soon as I click within the example's viewport suddenly I cannot easily control the example anymore because my cursor has now disappeared as it has entered captured mode. Safari also pushes the page down slightly when I do that (which adds confusion in the moment) with a banner noting that the cursor is now captured and I have to hit Esc twice to get it back. IMO this makes it hard to quickly mess around with a demo and then scroll down to check the sample code. Perhaps this is something more specific to how Safari does things and other browsers do not suffer this - I'm not sure.

* I noticed that the unicode example with the talking emoji doesn't appear to have any right-to-left languages such as Arabic (unless I missed them). I don't know if that's actually supported, but it might be worth showing off if there is indeed support for it.

* None of the sound examples appear to play any sound for me. I noticed on the example games page that there was a suspend/resume button for audio and the audio did work there after pressing that button, so I assume there's probably some browser permission things going on here (again, maybe this is only in Safari/macOS)?

* I cannot get the SDF font example to work - I'm presented with a blank example viewport almost as if something has failed to load properly.

* Likewise, the final 5 physics demos at the very end of the list also do not appear to be working for me. Example: 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/453721/111223693-7d1ebb80-85ab-11eb-8423-0777612663bd.png">

**Comment by raysan5** [comment]
@BigZaphod Thanks for reporting, here me answers:

 > The main thing that prompted me to post an issue is that the examples seem to all be capturing the mouse cursor even if it doesn't seem like they really have to.

It has already been corrected for next release, mouse is not captured anymore.

 > I noticed that the unicode example with the talking emoji doesn't appear to have any right-to-left languages such as Arabic (unless I missed them). 

Sorry, not supported for the moment. It would require not only right-to-left support but also specific characters ligatures. No plans for the moment.

 > None of the sound examples appear to play any sound for me. I noticed on the example games page that there was a suspend/resume button for audio and the audio did work there after pressing that button, so I assume there's probably some browser permission things going on here (again, maybe this is only in Safari/macOS)?

Yes, that's a browser related permissions issue. In Chrome they work when clicked from the examples page and a new iframe is opened, other browsers could be more restrictive. Actually, if you keep pressing the mouse button while reloading the page it should work.

 > I cannot get the SDF font example to work - I'm presented with a blank example viewport almost as if something has failed to load properly.

Oh, it used to work! Just took a quick look and it seems there is some issue with the shader, I'll review it.

 > Likewise, the final 5 physics demos at the very end of the list also do not appear to be working for me.

Yeah, multi-threaded wasm support is still changing between browsers and versions, they work on Chrome but maybe not on other browsers. I'll check state for next release.

Regards.

**Comment by raysan5** [comment]
Yesterday I just reviewed most of those issues.
