### ISSUE TITLE
build simple_game for android failed

### ISSUE THREAD

**Issue by ejamshidiasl** [raysan5/raylib#1661]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

i followed [this](https://github.com/raysan5/raylib/wiki/Working-for-Android) tutorial for build android game with raylib. i made libraylib.a without any problem then i changed Makefile.Android content for my system (sdk,ndk,...) but when i run https://github.com/raysan5/raylib/wiki/Working-for-Android command it will shows errors:
```
process_begin: CreateProcess(NULL, uname, ...) failed.
process_begin: CreateProcess(NULL, uname, ...) failed.
make -f Makefile.Android
process_begin: CreateProcess(NULL, make -f Makefile.Android, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:413: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

### Environment

OS: windows 10 latest update (x64)
RayLib: cloned repo (2 hours age)
c++ compiler: TDM-GCC-32 (TDM-GCC-64 tested too)
jdk: openjdk13 (jdk8 tested too)
ndk: ndk21e (latest 21)
sdk: latest anything...

### Code Example

[this project](https://github.com/raysan5/raylib/tree/master/templates/simple_game) without any change in .c file

**Comment by chriscamacho** [comment]
any spaces in your path to the project folder ? (just a thought!)

**Comment by ejamshidiasl** [comment]
no
`C:\Users\Arman\Documents\git\raylib\templates\simple_game`

**Comment by chriscamacho** [comment]
ah well, was worth a try

is make in your command path, ie if you open up cmd and type make (could be make.exe depending on sdk) does it work. Similarly as G++ gcc ld cpp et al all working from any path.

if you have Windows Subsystem for Linux installed you might try with that, make gcc etc all come from that side of things so its less forcing a square peg through a round hole, the script seem to be wanting to run uname as well, such things will definitely work in WSL and also I seem to remember msys was quite good too. If you have a spare partition or usb stick you might want to try Linux or even a "live" OS on a usb device

**Comment by raysan5** [comment]
@ejamshidiasl Updated Makefile to use `mingw32-make` while compiling on Windows. Also added a comment on the Wiki.

Compilation should work now.
