### ISSUE TITLE
[examples] Standard shader not working properly on RPI

### ISSUE THREAD

**Issue by Ted-bissada** [raysan5/raylib#167]
ok im back i now have this working on my pi 3 and all examples can compile and function other than 
audio_module_playing
audio_music_stream
physics_basic_rigidbody
physics_forces

all of them return a variation on this error

```
make PLATFORM=PLATFORM_RPI physics_forces
gvv -02 -Wall -std=gnu99 -fgnu89-inline   physics_forces.c   -o physics_forces
physics_forces.c:17:20: fatal error: raylib.h: No such file or directory
 #include "raylib.h"
                               ^
compilation terminated.
<builtin>: recipe for target 'physics_forces' failed
make: *** [physics_forces] Error 1
```

im sorry i keep posting here but im not really experienced enough to figure out what is going on here, as a side note for some reason the mouse wheel cannot control the camera zoom as it is supposed to. 
I really appreciate the help so far in getting this to work at all for me

**Comment by raysan5** [comment]
Hi @Ted-bissada, thanks for the feedback! I didn't try raylib on a Raspberry Pi 3. I just tested it on Raspberry Pi 1.

About the failing examples:

  - **audio_module_playing**: It should work, just tested it last week... are you linking with OpenAL library? Actually, right now I'm completely reviewing raylib audio module and those examples are going to change soon...
  - **audio_music_stream**: Same as above.
  - **physics_basic_body**: physics examples are not listed in Makefile, need to add them... But, like audio module, this module is also being reviewed right now by @victorfisac.
  - **physics_forces**: Same as above.
  - **core_mouse_wheel**: Mouse wheel is not supported by default by Linux kernel libs, need to configure it manually. That's a side issue of reading all inputs in pure raw mode.

Just out of curiosity, does **shaders_standard_lighting** example work on Raspberry Pi 3? Not working properly on Raspberry Pi 1 but compiles and run with no errors... I think it could be related to memory usage...

**Comment by Ted-bissada** [comment]
ok thanks for the info and no shaders_standard_lighting compiles and runs but the screen shows what might be the correct image for a fraction of a second before screwing up (screen half grey half coloured squares looks like somewat like gpu failure), the fps counter shows but is frozen as well as the model acknowledgment.  

(with 128 mb vram will edit post with attempt at 512 mb vram in a bit)

The examples 
shaders_custom_uniform
shaders_postprocessing
shaders_model_shader

all function at 128 mb vram

**Comment by raysan5** [comment]
Wow! Thank you very much for the detailed information! On Raspberry Pi 1 I only got a white screen! 

Could you upload some screenshot of the issue? Just run the example and press F12, a screenshot should be automatically generated in same folder with name `screenshot001.png`.

Definitely is an issue with the shader...

Thank you very much for your feedback!

**Comment by Ted-bissada** [comment]
![screenshot000](https://cloud.githubusercontent.com/assets/20605185/17296554/d546bf9c-57cf-11e6-9000-08b8e4febbca.png)

i previously stated the fps was frozen when in fact it started at zero and moved to 7 after several seconds then froze there

**Comment by raysan5** [comment]
Wow! Amazing screenshot! Thank you very much for sharing!

In the image we can see the Videocore IV tiled rendering mechanism, rendering 32x32 pixels tiles to generate the 800x450 pixels image...

No idea what's the issue but the image is great! :D

**Comment by Ted-bissada** [comment]
Thanks for the info thats pretty cool as a look into what's happening in the hardware rendering systems

**Comment by raysan5** [comment]
Just for reference, I reviewed standard shader for issue https://github.com/raysan5/raylib/issues/139

I think it's not related... i bet RPI issue is more a matter of memory... but I should try updated shader to verify...

**Comment by raysan5** [comment]
After quite a lot of testing, I found the problem... well, kind of...

If the following piece of code from shader... :
```c
for (int i = 0; i < 3; i++)
{
    // Check if light is enabled
    if (lights[i].enabled == 1)
    {
        // Calculate lighting based on light type
        if (lights[i].type == 0) lighting += ComputeLightPoint(lights[i], n, v, spec);
        else if (lights[i].type == 1) lighting += ComputeLightDirectional(lights[i], n, v, spec);
        else if (lights[i].type == 2) lighting += ComputeLightSpot(lights[i], n, v, spec);
    }
 }
```
...is replaced by a simplified version... :
```c
if ((lights[0].enabled == 1) && (lights[0].type == 0)) lighting += ComputeLightPoint(lights[0], n, v, spec);
if ((lights[1].enabled == 1) && (lights[1].type == 1)) lighting += ComputeLightDirectional(lights[1], n, v, spec);
if ((lights[2].enabled == 1) && (lights[2].type == 2)) lighting += ComputeLightSpot(lights[2], n, v, spec);
```
... it works perfectly!

Investigating a bit about `for` loops and branches in GLSL shaders I found that all those structures  (specially `for` loops) are really discouraged to use due to potential silent-failing errors.

Here it is a good reference I found: http://bitiotic.com/blog/2013/09/24/opengl-es-shading-language-potholes-and-problems/ (check `GLSL Language "Flexibility" Potholes` section)

It seems that graphic driver unrolls the `for` loop on compilation and tries to simplify it... I imagine it fails silently on that process.

One solution is trying to do that unroll/simplification process manually... I tried but, beside the direct light interpretation listed above that works perfectly, I couldn't find a light-generic solution...

Just for reference, here there are some of my failing tests on unrolling:
```c
// TEST 01: Check every light independently, outside for loop > FAIL
if ((lights[0].enabled == 1) && (lights[0].type == 0)) lighting += ComputeLightPoint(lights[0], n, v, spec);
else if ((lights[0].enabled == 1) && (lights[0].type == 1)) lighting += ComputeLightDirectional(lights[0], n, v, spec);
else if ((lights[0].enabled == 1) && (lights[0].type == 2)) lighting += ComputeLightSpot(lights[0], n, v, spec);

if ((lights[1].enabled == 1) && (lights[1].type == 0)) lighting += ComputeLightPoint(lights[1], n, v, spec);
else if ((lights[1].enabled == 1) && (lights[1].type == 1)) lighting += ComputeLightDirectional(lights[1], n, v, spec);
else if ((lights[1].enabled == 1) && (lights[1].type == 2)) lighting += ComputeLightSpot(lights[1], n, v, spec);
...

// TEST 02: Move light enabled check inside functions, just return vec3(0.0) if not enabled -> WORKS for NON-GENERIC solution, FAILS for multiple lights
if (lights[0].type == 0) lighting += ComputeLightPoint(lights[0], n, v, spec);
else if (lights[0].type == 1) lighting += ComputeLightDirectional(lights[0], n, v, spec);
else if (lights[0].type == 2) lighting += ComputeLightSpot(lights[0], n, v, spec);

if (lights[1].type == 0) lighting += ComputeLightPoint(lights[1], n, v, spec);
else if (lights[1].type == 1) lighting += ComputeLightDirectional(lights[1], n, v, spec);
else if (lights[1].type == 2) lighting += ComputeLightSpot(lights[1], n, v, spec); 
...

// TEST 03: Remove branches! -> FAILS
lighting += (ComputeLightPoint(lights[0], n, v, spec)*((lights[0].type == 0) ? 1.0:0.0) +
             ComputeLightDirectional(lights[0], n, v, spec)*((lights[0].type == 1) ? 1.0:0.0) +
             ComputeLightSpot(lights[0], n, v, spec)*((lights[0].type == 2) ? 1.0:0.0));

lighting += (ComputeLightPoint(lights[1], n, v, spec)*((lights[1].type == 0) ? 1.0:0.0) +
             ComputeLightDirectional(lights[1], n, v, spec)*((lights[1].type == 1) ? 1.0:0.0) +
             ComputeLightSpot(lights[1], n, v, spec)*((lights[1].type == 2) ? 1.0:0.0));
...
```
It seems this shader should be redesigned, maybe unifying lighting in only one compute function... Right now a lights-custom shader is the only proved solution for this issue.

**Comment by raysan5** [comment]
Conclusion after further testing (and reading about shaders design and performance): Standard Shader needs to be redesigned (simplified) together with raylib lighting-materials system.

Branching should be avoided as much as possible and shader operations must be kept simpler despite being repetitive. Probably light types should be managed in a different way.

**Comment by raysan5** [comment]
Just closing this issue because current standard shader raylib implementation will change and it will be moved to custom example. Lighting won't be included in raylib internals.
