### ISSUE TITLE
Raylib UWP App doesnt compile

### ISSUE THREAD

**Issue by kororro** [raysan5/raylib#1681]
https://github.com/raysan5/raylib/blob/master/projects/VS2017.UWP/raylib.App.UWP/App.cpp

    posX += GetGamepadAxisMovement(GAMEPAD_PLAYER1, GAMEPAD_AXIS_LEFT_X) * 5;
    posY += GetGamepadAxisMovement(GAMEPAD_PLAYER1, GAMEPAD_AXIS_LEFT_Y) * -5;

Error:
'GAMEPAD_PLAYER1': undeclared identifier  (line 197)

**Comment by raysan5** [comment]
reviewed!
