### ISSUE TITLE
GLTF (raylib_32x32.glb) testfile problem

### ISSUE THREAD

**Issue by kororro** [raysan5/raylib#1682]
resources/gltf/raylib_32x32.glb
does not load when testing models_gltf_model.c

Imported  raylib_32x32.glb  to blender, exported  raylib_32x32.glb  and then it works somehow.

**Comment by chriscamacho** [comment]
it would be helpful if you could detail the original source of the asset and if possible include it here for testing...

**Comment by kororro** [comment]
Ah my bad.
Deleted build/ dir and created projects again using cmake, now it works.
