### ISSUE TITLE
[BUG] GLFW not found in install path [mac]

### ISSUE THREAD

**Issue by lewislepton** [raysan5/raylib#169]
something i have found after you have made GLFW, placed in the required path in `usr/local/lib/lib`, even though it is located in that folder, raylib still looks for it in the path of which it was made in.

so if i build it in my downloads folder its looked for it in that. so i have to keep it there as well as using the `usr/local/lib/lib` folder.
very strange

**Comment by raysan5** [comment]
Hi @lewislepton, it seems related to XCode configuration, it seems other user don't have this problem.

Please, @jamiltron, could you confirm this issue? Did you have the same problem?

**Comment by jamiltron** [comment]
I did not have that issue, but I compile from the command line and do not use XCode.

I installed glfw3 via homebrew, which (on my machine) installs to /usr/local/Cellar/glfw3/$VERSION/libs, but it should register with pkg-config no matter how you install it, I think. So you should be able to include it via `pkg-config --libs glfw3`

**Comment by jamiltron** [comment]
So I just pointed XCode to glfw3.dylib, which was installed via homebrew, and raylib.a which I built from source and it ran just fine.

Are you using XCode @lewislepton?

**Comment by raysan5** [comment]
Just closing this issue. Seems more related to a configuration problem than an issue with raylib.

Please, feel free to reopen if thinking is a raylib issue.
