### ISSUE TITLE
[core] Can only load shaders from file

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1690]
since LoadShaderCode has been moved into rlgl there is no way to load a shader except from a file

while rlLoadShaderCode can be used this only passes back an id, and you then have to manually add in the "default" shader locations, which is a bunch of needless boiler plate and code that should only be in one place (in case it later changes)

putting back an ability to load from memory shader code, also means the code can be loaded in any manner and you have the opportunity to pre-process the shader code (for example you might want to add debug code to a shader temporarily, without needing to hack your shaders)

also means you have to include "config.h" for some defines, which doesn't seem right!

**Comment by raysan5** [comment]
@chriscamacho Good point! Added function!

**Comment by chriscamacho** [comment]
thx :+1:
