### ISSUE TITLE
[models] Normal matrix recalculated every vertex

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1691]
A number of shaders requiring normals, such as the simple lighting shader, recalculate the normal matrix each vertex:

abstract from typical vertex shader.
```GLSL
    mat3 normalMatrix = transpose(inverse(mat3(matModel)));
    fragNormal = normalize(normalMatrix*vertexNormal);
```

it would be more efficient to calculate the normal matrix at the same time the mvp / matModel matrix are being calculated and pass it to the vertex shader as a uniform, doing it just once for the whole model rather than each vertex

**Comment by raysan5** [comment]
@chriscamacho Mmmh, yeah, this could be a nice improvement. WIP

**Comment by chriscamacho** [comment]
nice! :+1: :smile:
