### ISSUE TITLE
[shapes] CheckCollisionPointTriangle() - one ampersand symbol missing in logical AND operator

### ISSUE THREAD

**Issue by mkupiec1** [raysan5/raylib#1692]
https://github.com/raysan5/raylib/blob/b5aaf33058df329963c8d7825d58131bebd13647/src/shapes.c#L1471

is:
if ((alpha > 0) && (beta > 0) & (gamma > 0)) collision = true;

should be:
if ((alpha > 0) && (beta > 0) && (gamma > 0)) collision = true;

**Comment by raysan5** [comment]
@mkupiec1 Oh! Good catch! Feel free to send a PR!

**Comment by mkupiec1** [comment]
Done. Thanks a lot!
