### ISSUE TITLE
[models] DrawGizmo is in the docs but removed from code

### ISSUE THREAD

**Issue by Saikyun** [raysan5/raylib#1706]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

DrawGizmo is in the docs (e.g. https://www.raylib.com/cheatsheet/cheatsheet.html), but not in the code.
I'm not missing it, but it should probably be removed from the docs if it isn't available anymore. :)

**Comment by raysan5** [comment]
@Saikyun Yeap, I'm aware of that, just removed it for `raylib 3.7`, I'm in the process of updating everything for the new release.

**Comment by raysan5** [comment]
Updated cheatsheet for raylib 3.7.
