### ISSUE TITLE
[rlgl] Application crashes on Raspberry PI when using GRAPHICS_API_OPENGL_21

### ISSUE THREAD

**Issue by Delvix000** [raysan5/raylib#1708]
There is an issue running the latest raylib version on a Raspberry PI 3B equipped with the latest Raspbian OS. Both raylib and the examples compile fine, but when trying to run any of them, they crash because it seems that GLAD is trying to load OpenGL 3.3 which is not supported on the PI. I compile both raylib and the examples with the default building method for the PI with X11
`make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_21`
When I try to run, this log is printed to the terminal:

```
INFO: Initializing raylib 3.7
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 2.1 profile supported
ERROR: GL: OpenGL 3.3 Core profile not supported
```
I'm attaching some information on my raspberry hardware and software, if can be useful.
[hardinfo_report.txt](https://github.com/raysan5/raylib/files/6265255/hardinfo_report.txt)

**Comment by raysan5** [comment]
@Delvix000 Please, could you try if it works now?
