### ISSUE TITLE
[rlgl] Expose OpenGL extensions supported

### ISSUE THREAD

**Issue by Crydsch** [raysan5/raylib#1709]
I am currently writing a little extension for rlgl (support for texture arrays).
For this is need to query `ExtSupported` texture formats.

Would it be possible to make `rlglData RLGL` accessible from the outside?
In order to prohibit external manipulation, just pass a copy?
Something like:
```c
rlglData GetCurrentConfiguration() {
    rlglData copy;
    copy = RLGL;
    return copy;
}
```
Maybe just return `RLGL.ExtSupported` ?

**Comment by raysan5** [comment]
@Crydsch No plans to expose the full `RLGL` data but maybe `ExtSupported` in some way.

**Comment by Crydsch** [comment]
Sound fine to me. That would be great!

**Comment by raysan5** [comment]
@Crydsch In any case, do not expect it for next release. Maybe for the following ones. No priority to review that part, neither to add textures arrays support.

**Comment by Crydsch** [comment]
No worries. I just came across this trying to write a little extension to make texture arrays work.
Would be great to be able to query supported formats like the `rlLoadTexture(..)` function.

**Comment by chriscamacho** [comment]
My immediate reaction, would be yeah great for advanced user, but exposing what amounts to internal global variables is probably not a great idea!

For the future, it might be nice if an end user could (somehow?) request access to specific GL extensions, obviously this would be for advanced users....

**Comment by jmorel33** [comment]
The problem is, when you want to program on a framework like OpenGL, you need to know what you are doing...  So you can't just hide stuff from developers in the hopes they never ask about it, because they will...  Or they spent the time to do it themselves, or they quit altogether...

**Comment by raysan5** [comment]
Just redesigned `rlLoadExtensions()` to expose supported OpenGL extensions if `SUPPORT_GL_DETAILS_INFO` is enabled on `config.h`. If an advance user requires to check for specific extensions to implement specific OpenGL functionality, it can be done using GLAD directly.
