### ISSUE TITLE
[rlua] Review, update and testing

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#171]
I open this new issue to discuss rlua development on a fresh thread. Please, @ghassanpl and @JaredSartin, feel free to join.

**Comment by ghassanpl** [comment]
The GAMEPAD enum is registered twice.

**Comment by ghassanpl** [comment]
lua_CalculateBoundingBox, lua_IsAudioDeviceReady and lua_LoadMusicStream all return 0 when they should return 1.

**Comment by raysan5** [comment]
Thanks! Just copied it to expose XBOX gamepad enum but still thinking the better way to do that.

Wow! So fast finding issues! I'm on it! :D

**Comment by raysan5** [comment]
By the way, how could I manage (void *) data?

**Comment by ghassanpl** [comment]
Lua strings are technically binary blobs, and manipulating them as such is easy thanks to string.pack/unpack ([Lua 5.3](https://www.lua.org/manual/5.3/manual.html#6.4.2)) so I'd recommend getting those arguments as strings (using lua_tolstring).

**Comment by raysan5** [comment]
I've just ported all raylib examples to Lua: https://github.com/raysan5/raylib/tree/develop/examples

I've been testing them (https://github.com/raysan5/raylib/blob/develop/examples/rlua_execute_file.c) and most of them fail with the error:
```
ERROR: Lua Error: attempt to index a number value
```
Most of the times related to structs `Camera` and `Camera2D`, Probably I'm doing something wrong when defining them in `rlua.h` module.

Please, @ghassanpl, could you take a look? Many thanks! :)

**Comment by ghassanpl** [comment]
There a couple of bugs, both in the lua examples, as well as (my) bugs in the rlua.h file. I'm working on them right now, but I'm not sure how to get the changes to you :) I'll try using git but who knows how that'll work :P

**Comment by raysan5** [comment]
Hi @ghassanpl! Many thanks for your help!

I just did a commit a while ago and no plan to commit anything else in, at least one day. You can sync to latest raylib develop branch and work there or, if you prefer, just send me the changed files and I will update my files and do the commit.

**Comment by raysan5** [comment]
Hi @ghassanpl! Just reviewed your commit! Most of the examples already work! AMAZING!

Here it is a list with the functions that do not work properly on its Lua version:
```c
char **GetDroppedFiles(int *count);
Image LoadImageEx(Color *pixels, int width, int height);
Color *GetImageData(Image image);
void UpdateTexture(Texture2D texture, void *pixels);
void SetShaderValue(Shader shader, int uniformLoc, float *value, int size);
void UpdateAudioStream(AudioStream stream, void *data, int numSamples);

Light CreateLight(int type, Vector3 position, Color diffuse);
bool CheckCollisionRayBox(Ray ray, BoundingBox box);
```
It seems most of the issues are related to pointed data...

About the last two functions:
  - `CreateLight()` in C returns a pointer to struct and fields are accessed with `->`. In Lua that's not possible so I can return a Light object, but that's not the same as C *Light... don't know how to manage that...
  - `CheckCollisionRayBox()` works in C but for some reason it doesn't work properly in Lua. If clicking in the middle of the box, it gets selected but not in the sides, it seems related to some values rounding issue in the Lua side...

**Comment by ghassanpl** [comment]
The problem with LoadImageEx, GetImageData, UpdateTexture and UpdateAudioStream is that they require Lua to create/hold/update large arrays or binary buffers. Lua tables are not well suited for that purpose unfortunately. Creating a 1024x1024 "array" in Lua is EXTREMELY costly.

There is no real solution to this problem. If you have any ideas, let me know.

As to the rest of the functions, I'm working on them now and should have something withing the hour.

**Comment by raysan5** [comment]
Hi @ghassanpl! What a quick response! Thanks for clarifying the issue with those functions, no problem, don't worry, if that functionality can not be added, it's ok.

Again, many thanks for your help and for the celerity on your answers! I'm extremely grateful.

**Comment by raysan5** [comment]
I will close this issue for now, I will open independent [rlua] issues for anything related that could arise...
