### ISSUE TITLE
[core] GetKeyPressed only returns non-zero when releasing the key

### ISSUE THREAD

**Issue by Saikyun** [raysan5/raylib#1712]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When calling `GetKeyPressed()` it only returns non-zero when releasing the key. Before (v3.0) it returned non-zero when depressing the key.

### Environment

MacOS Catalina

### Code Example

The print happens when releasing the key.

```
#include "raylib.h"
#include <stdio.h>

int main(void)
{
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - keyboard input");
    
    SetTargetFPS(60);
    
    while (!WindowShouldClose())
    {
        int k = GetKeyPressed();
        if (k != 0) {
	    printf("k: %d\n", k);
        }
	
	BeginDrawing();

            ClearBackground(RAYWHITE);
	    
        EndDrawing();
    }

    CloseWindow();
    
    return 0;
}
```

**Comment by Saikyun** [comment]
Okay, so found the reason now, on this line it only puts keys on the queue on release: https://github.com/raysan5/raylib/blob/b3f75b91ff6859f5c19c4b1e6b17c78b5e66530f/src/core.c#L5034

Is this intended? Afaik it is more common to trigger on key press, something like this:
```
        if ((CORE.Input.Keyboard.keyPressedQueueCount < MAX_KEY_PRESSED_QUEUE) && (action == GLFW_PRESS))
```

I can make a PR but I'm not sure what your intention is @raysan5. :)

**Comment by Saikyun** [comment]
FWIW I noticed GetCharPressed uses `GLFW_PRESS`.

**Comment by raysan5** [comment]
@Saikyun Thanks for reporting! I've been investigating with it was using `GLFW_RELEASE` instead of `GLFW_PRESS` but I couldn't find the answer... I just pushed your proposed change.

**Comment by Saikyun** [comment]
Thank you. :)

Skickat från min iPhone
