### ISSUE TITLE
[core] Cannot draw more than 16383 lines

### ISSUE THREAD

**Issue by BogdanTheGeek** [raysan5/raylib#1721]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I am working on a gcode simulator and whenever I have to draw more than 16383-ish 3D lines in a frame, I get a white screen. This looks to me like the max value of a signed short.
I have already tested the storage part of my code and its not a that, its always the 16383rd-ish DrawLine3D() call that makes the window only show white.
The framerate with one less element is locked at 60.

### Environment

Fedora 33, kenel 5.11.11-200.fc33.x86_64, master branch, NVIDIA GeForce GTX 1070 on 460.67, opengl 3.3.0 GLSL 3.30

### Issue Screenshot
its just a white window :)
### Code Example
Works:
```
for(int i=0; i< 16381; i++){
DrawLine3D((Vector3){i, i, i}, (Vector3){0,i,0}, GREEN);
}
```
Doesn't:
```
for(int i=0; i< 16382; i++){
DrawLine3D((Vector3){i, i, i}, (Vector3){0,i,0}, GREEN);
}
```

**Comment by raysan5** [comment]
@BogdanTheGeek Just pushed a possible fix, please let me know if it works now.

**Comment by BogdanTheGeek** [comment]
Hi @raysan5 That was the quickest response I have ever seen :)). I tried it, but the same symptoms persist.
Just to be sure:
I have pulled, make, make install and then recompiled my program.

**Comment by raysan5** [comment]
@BogdanTheGeek Nah, I've been quicker with other responses... :P 

Mmmh... could you try changing the line I changed in the PR for testing?
```c
    // WARNING: Be careful with internal buffer vertex alignment
    // when using RL_LINES or RL_TRIANGLES, data is aligned to fit
    // lines-triangles-quads in the same indexed buffers!!!
    rlCheckRenderBatchLimit(4);
```
Try increasing the value for RenderBatch limits from 4 to 8, 16 or bigger... I'm confident the issue is there but it could be a bit tricky...

**Comment by BogdanTheGeek** [comment]
Let me have a go at it, will let you know soon.

**Comment by BogdanTheGeek** [comment]
looks like 8 did the trick. Is there a way to know the maximum value of lines that I can draw for each of these values?

**Comment by raysan5** [comment]
@BogdanTheGeek Actually, when you check the proper limits for internal batch resetting you should be able to draw as many lines as you want. Every time the buffers are full, a draw call happens and they are refilled.

**Comment by BogdanTheGeek** [comment]
Not really sure what you mean, I've only been working with raylib for 2 days :). Can you share some code?
Also, off topic, there is this [https://github.com/WEREMSOFT/stl-loader-for-raylib](url) very neat implementation of stl loading that I think could be worth merging. It only works with binary STLs though.

**Comment by raysan5** [comment]
@BogdanTheGeek I mean that after that change in source code you should be able to draw as many 3d lines as you want.

About STL, yeah, I saw it, no plans to add it to raylib for the moment, maybe in a future...

**Comment by BogdanTheGeek** [comment]
Great, thanks again. Awesome work, this is one of the best projects I've seen.

**Comment by raysan5** [comment]
@BogdanTheGeek thanks! :D
