### ISSUE TITLE
[core] RPI4/DRM: Checking file handle isn't good enough to determine if right device is opened

### ISSUE THREAD

**Issue by alanbork** [raysan5/raylib#1723]
in core.c (https://github.com/raysan5/raylib/blob/3cdac3e11e86a2038df395a12e85b0e63e93b326/src/core.c#L3819) you currently just check the file handle to make sure that the proper card (0,1) is opened. But as it turns out you can get a valid file handle but not be able to use it because you've chosen the wrong device. To determine the device is correct, you also need to call drmModeGetResources, as follows:

 ```
TRACELOG(LOG_INFO, "DISPLAY: no graphic card set, trying card1");
        CORE.Window.fd = open("/dev/dri/card1", O_RDWR); // VideoCore VI (Raspberry Pi 4)
        if ((-1 == CORE.Window.fd) || (drmModeGetResources(CORE.Window.fd) == NULL)) // fd can be valid on the wrong card, but drmModeGetResources fails
        {
            TRACELOG(LOG_INFO, "DISPLAY: failed to open graphic card1, trying card0");
            CORE.Window.fd = open("/dev/dri/card0", O_RDWR); // VideoCore IV (Raspberry Pi 1-3)
        }
```

sorry this isn't a proper pull request, just wanted to log it for anybody else needing the same fix. possible this is a pi4 only implementation issue

**Comment by raysan5** [comment]
@alanbork Feel free to send a PR with this improvement.

**Comment by kernelkinetic** [comment]
@alanbork Thanks for finding this issue. Maybe it's a good idea to iterate over all dri "cards" to find the suitable one?

Back then when I wrote this insufficient code I found no information how to find the right dri "card". Did you find your solution by trial and error or do you have some documentation or such?

**Comment by alanbork** [comment]
Trial and error. As is my proposed change is a huge improvement in
reliability, but it is possible that it could be done more correctly.

**Comment by alanbork** [comment]
ps: this isn't about pi4 vs p0..3: pi4 can randomly select card0 or card1 as the required drm device to open.

**Comment by raysan5** [comment]
@alanbork @kernelkinetic are you sending a PR with this improvement?

**Comment by kernelkinetic** [comment]
I can send a pull request the next days if @alanbork doesn't want to do it, but I cannot test very much at the moment.

**Comment by alanbork** [comment]
the code snippet is well tested on my box but not outside of that context.

**Comment by kernelkinetic** [comment]
@alanbork So you could contribute your code by sending a pull request and everyone is happy 😄

**Comment by alanbork** [comment]
my code is significantly diverged from the base distribution, which is why
I only sent the relevant lines.

**Comment by raysan5** [comment]
@alanbork Ok, I'm implementing those lines myself.
