### ISSUE TITLE
[core] Expose timing and input functions from core.c to allow custom game loops and tweaks

### ISSUE THREAD

**Issue by moliad** [raysan5/raylib#1729]
### Request for Enhancement

I realized that many/most of the Input and timing code is declared static within core.c (ex: `PollInputEvents()` )  

Would it be possible to consider making some/most? of those functions non-static?  A lot of the code there is really clean (like improved `Wait()` vs abysmal win32 `Sleep()`, etc.)  it would be nice to have access to that stuff if we want to implement our own game loops or add little tweaks to default ones.  `core.c` is so clean, it's a shame more of it is not available as part of the official API.

For example, in my case, I was  trying to improve input event resolution without switching to event sleep model, as well as adding a pause/unpause rendering mechanism.

Without increasing rendering frame rate and mangling the render loop, this was currently impossible.  With just two functions made global again, I was able to add some extra little code in my game loop.  The code in core.c is really nice, it's a shame more of it is not available as part of the official API.

### Environment

This is for all platforms

### Code Example

One thing we might do is add a switch through a `#define`, similar to how `SUPPORT_SCREEN_CAPTURE` is done which allows the extra functionality, when building the library.  This `#define` would be setup in raylib.h and toggle the `static` keyword of the functions we decide to expose.  This identifies the functions as advanced playground, and would be off by default.  It would also enable extra declarations in `raylib.h` for those functions.

Since this isn't a bug there is nothing to reproduce, but I'd be willing to build the PR with above implementation completed.

**Comment by raysan5** [comment]
I can consider this option to allow advance users to customize the game-loop experience. Just for completion to this issue, here it is a list of the internal functions involved in the process:
```c
static bool InitGraphicsDevice(int width, int height);  // Initialize graphics device
static void SetupFramebuffer(int width, int height);    // Setup main framebuffer
static void SetupViewport(int width, int height);       // Set viewport for a provided width and height
static void SwapBuffers(void);                          // Copy back buffer to front buffer
static void InitTimer(void);                            // Initialize timer
static void Wait(float ms);                             // Wait for some milliseconds (stop program execution)
static void PollInputEvents(void);                      // Register user events
```

 - `InitGraphicsDevice()` is called by `InitWindow()` and initializes the display, the OpenGL context, checks extensions and setups basic OpenGL state.

 - `SetupFramebuffer()` tries to set a proper framebuffer to fit in the device display, considering desired screen size and applying offsets (black-bars) to render if required. Used only for full-screen display (`PLATFORM_DESKTOP` (fullscreen), `PLATFORM_ANDROID`, `PLATFORM_RPI` (native), `PLATFORM_DRM` (native)). I'm not specially happy with this function, I considered removing it and just let the user manage screen scaling and black-bars using a `RenderTexture`.

 - `InitTimer()` just gets the base measure for a hi-resolution timer if available. It also initializes the random seed for `GetRandomValue()`.

 - `Wait()` just implements a delay for a number of milliseconds trying to be as much accurate as possible. The way it does it depends on several configuration flags.

 - `PollInputEvents()` process different types of events (mostly input related) for the different platforms available. Input events processed in a direct or indirect (callback-based) way: Keyboard, Mouse, Gamepad, Touch, Gestures. On `PLATFORM_ANDROID` it also polls App state events.

**Comment by raysan5** [comment]
@moliad Actually, I didn't commented on `SetupViewport()` and `SwapBuffers()` because they are quite simple functions.

**Comment by moliad** [comment]
doh, I just re-read your original reply and I saw they where in the list at top... doh... sorry... hehe.

**Comment by alanbork** [comment]
I agree that access to more of the core functions would be good - I have to patch every raylib release I download to fix EndDrawing() so that it calls swapbuffers()  after doing all the housekeeping events.

**Comment by raysan5** [comment]
Some functions have been exposed, now frame processes can be manually controlled by advance users that desire to have full control.

No plans to expose more functions.

**Comment by moliad** [comment]
cool  :-)
