### ISSUE TITLE
[Android] Handling different Android screen sizes

### ISSUE THREAD

**Issue by itarato** [raysan5/raylib#1731]
### "Problem"

Not a problem per-say - when developing for Android platform, the `InitWindow` call  sets up a "virtual" window size with the provided width+height and then it's upscaled/downscaled (or kept as is) depending on the actual screen size.

What I'm trying to see how would a dev optimize a project for any Android screen size to be 1:1 exact? I'm more looking for directions on how would the raylib framework is designed and would implement such a feature - and as such I would like to help making a prototype - if there is a reasonable implementation for this.

### Strategies

Looking at the API I see no option in the current state to get the screen size for Android platform.

- `GetScreenWidth` gets the virtual width
- `GetMonitorWidth` is not implemented for Android
- other screen related functions are not strictly pixel-size related (eg `GetWindowScaleDPI`)

Also I can see that screen and frame buffer sizes are the virtual ones: https://github.com/raysan5/raylib/blob/master/src/core.c#L678-L681

I see `CORE` knows about real screen size eventually - after the `CORE.Android.app->onAppCmd = AndroidCommandCallback;` callback in https://github.com/raysan5/raylib/blob/master/src/core.c#L711 has been called - which makes:

```c
CORE.Window.display.width  = ANativeWindow_getWidth(CORE.Android.app->window);
CORE.Window.display.height = ANativeWindow_getHeight(CORE.Android.app->window);
```

in https://github.com/raysan5/raylib/blob/master/src/core.c#L5189-L5190 .

I've no clue what graphics engine requires, so my naive approaches would be the following:

#### a) Provide access the real display size

There could be a getter for `CORE.Window.display` size - and with that a client could just use `SetWindowSize` to adjust the window after load. it's not super elegant - since I don't think the framework has convenient events (eg `onScreenInitialized`) - so that would be best effort - at best.

Example:

```c
InitWindow(800, 460, "Some title");
// ... some more code later when we know the app is fully initialized
SetWindowSize(GetDisplayWidht(), GetDisplayHeight());
```

#### b) Always adjust window size on Android to 1:1

The framework could potentially just "autocorrect" the screen size once the app has initialized. This would be the lightest to ta client as it requires no action. However it has the dangerous assumption that all apps would be fine if they are auto-resized.

#### c) Use a window state flag for auto-resize

Based on the previous option - auto-resizing the screen, but only when a window state flag is provided.

Example:

```c
SetWindowState(FLAG_AUTO_RESIZE_SCREEN_MODE);
InitWindow(800, 460, "Some title");
```

---

Personally I think option `c` would work best - flexibility (and decision) is to the client but execution is on the framework. What do you think?

**Comment by raysan5** [comment]
@itarato You can `InitWindow(0, 0, "test")` to get the full display resolution.

**Comment by itarato** [comment]
That was easy :D Thanks so much!

**Comment by raysan5** [comment]
@itarato Just for completion on this topic, when dealing with full-screen displays, raylib calls the internal function `SetupFramebuffer()` [core.c] that tries to adjust, in the best possible way, the desired resolution (the one provided to `InitWindow()`) to the current display; it tries to get the closer resolution from the display, it keeps desired resolution aspect-ratio and it adds black bars up-down or right-left if required. To allow that, multiple internal variables are used:

 - `Screen size`: Desired resolution (the one provided on `InitWindow()`
 - `Display size`: Display closer resolution available (I think in Android it's the main one)
 - `Render size`: Framebuffer resolution to fit screen size and black bars if required
 - `Render offset`: Drawing offset of the render size when using black bars.

This function works better in some platforms than others (for full-screen modes) but is out-of-control for users that desire to manage those factors by themselves. For those situations, it's highly-recommended to use a different approach: a `RenderTexture`, like in [`core_window_letterbox`](https://github.com/raysan5/raylib/blob/master/examples/core/core_window_letterbox.c) example.

**Comment by itarato** [comment]
@raysan5 Thanks so much for the extra details ;)

**Comment by seprab** [comment]
Thank you @raysan5 it works.
Is there any reason this isn't documented?
