### ISSUE TITLE
[OpenGL] Raylib 3.7 will no longer build with GRAPHICS_API_OPENGL_11 defined

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib#1732]
Defining GRAPHICS_API_OPENGL_11 (in the config.h file on Visual Studio) no longer builds a valid raylib binary. There are unresolved externals from what looks like the rlExtensions feature that was just added.

11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glBegin referenced in function rlBegin
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glBindTexture referenced in function rlDisableTexture
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glBlendFunc referenced in function rlglInit
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glClear referenced in function rlClearScreenBuffers
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glClearColor referenced in function rlClearColor
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glClearDepth referenced in function rlglInit
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glColor3f referenced in function rlColor3f
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glColor4f referenced in function rlColor4f
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glColor4ub referenced in function rlColor4ub
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glColorPointer referenced in function rlEnableStatePointer
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glCullFace referenced in function rlglInit
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glDeleteTextures referenced in function rlUnloadTexture
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glDepthFunc referenced in function rlglInit
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glDepthMask referenced in function rlDisableDepthMask
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glDisable referenced in function rlDisableBackfaceCulling
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glDisableClientState referenced in function rlDisableStatePointer
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glDrawArrays referenced in function rlDrawVertexArray
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glDrawElements referenced in function rlDrawVertexArrayElements
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glEnable referenced in function rlEnableBackfaceCulling
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glEnableClientState referenced in function rlEnableStatePointer
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glEnd referenced in function rlEnd
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glFrontFace referenced in function rlglInit
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glFrustum referenced in function rlFrustum
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glGenTextures referenced in function rlLoadTexture
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glGetFloatv referenced in function rlGetLineWidth
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glGetString referenced in function rlglInit
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glGetTexImage referenced in function rlReadTexturePixels
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glHint referenced in function rlglInit
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glLineWidth referenced in function rlSetLineWidth
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glLoadIdentity referenced in function rlLoadIdentity
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glMatrixMode referenced in function rlMatrixMode
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glMultMatrixf referenced in function rlMultMatrixf
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glNormal3f referenced in function rlNormal3f
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glNormalPointer referenced in function rlEnableStatePointer
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glOrtho referenced in function rlOrtho
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glPixelStorei referenced in function rlLoadTexture
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glPolygonMode referenced in function rlDisableWireMode
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glPopMatrix referenced in function rlPopMatrix
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glPushMatrix referenced in function rlPushMatrix
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glReadPixels referenced in function rlReadScreenPixels
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glRotatef referenced in function rlRotatef
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glScalef referenced in function rlScalef
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glScissor referenced in function rlScissor
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glShadeModel referenced in function rlglInit
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glTexCoord2f referenced in function rlTexCoord2f
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glTexCoordPointer referenced in function rlEnableStatePointer
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glTexImage2D referenced in function rlGenerateMipmaps
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glTexParameteri referenced in function rlLoadTexture
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glTexSubImage2D referenced in function rlUpdateTexture
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glTranslatef referenced in function rlTranslatef
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glVertex2f referenced in function rlVertex2f
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glVertex2i referenced in function rlVertex2i
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glVertex3f referenced in function rlVertex3f
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glVertexPointer referenced in function rlEnableStatePointer
11>raylib.lib(core.obj) : error LNK2019: unresolved external symbol __imp_glViewport referenced in function rlViewport
11>C:\Users\jeffm\Desktop\raylib_fixes\projects\VS2019\\build\core_2d_camera\bin\x64\Debug\core_2d_camera.exe : fatal error LNK1120: 55 unresolved externals
11>Done building project "core_2d_camera.vcxproj" -- FAILED.
18>------ Build started: Project: core_drop_files, Configuration: Debug x64 ------
19>------ Build started: Project: core_input_gamepad, Configuration: Debug x64 ------
20>------ Build started: Project: core_input_gestures, Configuration: Debug x64 ------

**Comment by raysan5** [comment]
@JeffM2501 Corrected the issue with OpenGL 1.1 and I tested it using MinGW-w64 and it works.

Visual Studio issue is because `opengl32.lib` is not added on linkage. Here the weird thing is... why it works when compiling for OpenGL 3.3???
