### ISSUE TITLE
problem compiling & running raylib 1.5 on windows (8)

### ISSUE THREAD

**Issue by DanIsraelMalta** [raysan5/raylib#174]
Hello,

I have a problem.
Upon perssing "raylib_compile_execute" in notepad++, I recive the following errors:
"
...ccaQNGnS.o:core_basic_window.c(.text+0x36): undefined reference to 'InitWindow'
...ccaQNGnS.o:core_basic_window.c(.text+0x36): undefined reference to 'SetTargetFPS'
collect2.exe:error: ld returned 1 exit status
"
can anyone help?

**Comment by raysan5** [comment]
Make sure raylib is installed in `C:\raylib` folder and that the following files exist:

raylib.h - `C:\raylib\raylib\src\raylib.h`
raylib.h - `C:\raylib\raylib\release\win32\raylib.h`
libraylib.a - `C:\raylib\raylib\release\win32\libraylib.a`

Did you choose any option while installing?

**Comment by DanIsraelMalta** [comment]
All the files are in the appropriate locations.
No. I performed the standard install.
