### ISSUE TITLE
[physac.h]ResetPhysics crash

### ISSUE THREAD

**Issue by zipxing** [raysan5/raylib#1742]
PHYSACDEF void ResetPhysics(void)
{
    if (physicsBodiesCount > 0)
    {
        // Unitialize physics bodies dynamic memory allocations
        for (unsigned int i = physicsBodiesCount - 1; i >= 0; i--)           <-----line:852    unsigned int ??? endless loop!!!
        {
            PhysicsBody body = bodies[i];

**Comment by raysan5** [comment]
🤔

**Comment by raysan5** [comment]
@zipxing Reviewed! Thanks!

**Comment by zipxing** [comment]
PHYSACDEF void ClosePhysics(void) LINE894,901
{
    // Unitialize physics manifolds dynamic memory allocations
    if (physicsManifoldsCount > 0)
    {
        for (unsigned int i = physicsManifoldsCount - 1; i >= 0; i--)
            DestroyPhysicsManifold(contacts[i]);
    }
    
    // Unitialize physics bodies dynamic memory allocations
    if (physicsBodiesCount > 0)
    {
        for (unsigned int i = physicsBodiesCount - 1; i >= 0; i--)
            DestroyPhysicsBody(bodies[i]);
    }
