### ISSUE TITLE
[core] Multitouch: ABS_X and ABS_Y overwrite negative values set by ABS_MT_TRACKING_ID

### ISSUE THREAD

**Issue by DominikStarke** [raysan5/raylib#1745]
This happens on a Raspberry Pi 3b with a 7" waveshare display with SUPPORT_GESTURES_SYSTEM and SUPPORT_MOUSE_GESTURES both disabled:

If you happen to have two fingers on the display and remove the finger that touched the screen first, then GetTouchPosition(0) will report the last known position instead of -1, -1. This makes it hard to detect if the number of touches changed. GetTouchPointsCount() will also report the wrong number if  SUPPORT_GESTURES_SYSTEM is enabled.

This seems to happen because in core.c starting at line 6018:
```
                if (event.code == ABS_X)
                {
                    CORE.Input.Mouse.position.x    = (event.value - worker->absRange.x)*CORE.Window.screen.width/worker->absRange.width;   // Scale acording to absRange
                    CORE.Input.Touch.position[0].x = (event.value - worker->absRange.x)*CORE.Window.screen.width/worker->absRange.width;   // Scale acording to absRange

                    #if defined(SUPPORT_GESTURES_SYSTEM)
                        touchAction = TOUCH_MOVE;
                        gestureUpdate = true;
                    #endif
                }

                if (event.code == ABS_Y)
                {
                    CORE.Input.Mouse.position.y    = (event.value - worker->absRange.y)*CORE.Window.screen.height/worker->absRange.height; // Scale acording to absRange
                    CORE.Input.Touch.position[0].y = (event.value - worker->absRange.y)*CORE.Window.screen.height/worker->absRange.height; // Scale acording to absRange

                    #if defined(SUPPORT_GESTURES_SYSTEM)
                        touchAction = TOUCH_MOVE;
                        gestureUpdate = true;
                    #endif
                }
```

take precedence over

```
                if (event.code == ABS_MT_TRACKING_ID)
                {
                    if ((event.value < 0) && (worker->touchSlot < MAX_TOUCH_POINTS))
                    {
                        // Touch has ended for this point
                        CORE.Input.Touch.position[worker->touchSlot].x = -1;
                        CORE.Input.Touch.position[worker->touchSlot].y = -1;
                    }
                }
```

starting on line  6053.

Unfortunately I have no idea how to fix this besides in my case commenting out the lines containing CORE.Input.Touch.position[0].y = yyy and CORE.Input.Touch.position[0].x = xxx

**Comment by raysan5** [comment]
@DominikStarke I've been checking this piece of code but I don't know how to solve it right now, I didn't write it and the contributor is not maintaining it anymore so, I'll close this issue with the proposed solution. Hopefully someone else facing the same problem will find this issue or even provide a PR to solve it.
