### ISSUE TITLE
RAYLIB_VERSION

### ISSUE THREAD

**Issue by pauljurczak** [raysan5/raylib#1747]
`RAYLIB_VERSION` is defined in two source files:
```
#define RAYLIB_VERSION  "3.7"
```
but I can't access it directly by including `raylib.h`. Is there another way to find the current version at compile time? Can you add `RAYLIB_VERSION` definition to `raylib.h`?

**Comment by raysan5** [comment]
@pauljurczak Actually, it was not in `raylib.h` for some reason I can't remember now... In any case, I just moved it to `raylib.h`.
