### ISSUE TITLE
[build] Cannot Compile library using make in Linux (VSCode)

### ISSUE THREAD

**Issue by the-gremlin** [raysan5/raylib#1750]
### Issue description

I am trying to compile raylib with make but have encountered a number of errors (2):
First of all, the GRAPHICS variable in the makefile does not have a value when the platform is  `PLATFORM_DESKTOP`
i fixed it by skipping the if statement and just having graphics as `GRAPHICS_API_OPENGL_33`
However after fixing that and re-attempting to compile, I get the following error
```
core.c: In function ‘InitGraphicsDevice’:
core.c:4358:22: error: ‘eglGetProcAddress’ undeclared (first use in this function)
 4358 |     rlLoadExtensions(eglGetProcAddress);
      |                      ^~~~~~~~~~~~~~~~~
```
I have not touched the source code in any way outside of fixing the problem with the makefile.
### Environment

VSCode, Linux Ubuntu 20.04
OpenGL version (using`glxinfo | grep "OpenGL version"`)
```
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.3 - kisak-mesa PPA```

**Comment by RobLoach** [comment]
How are you attempting to build it? What is the build command you've used?

Also, you shouldn't have to specifically declare a `GRAPHICS`, as it should detect it for you. Could you push up a branch with your change? It's difficult to parse what you're suggesting through words, a diff is easier.

**Comment by the-gremlin** [comment]
@RobLoach  
first of all i wouldnt call what i did a fix, its more of a hack to get things working on my end
as for the build, im building it using make, specifically 
`make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED` as my build commans (taken straight from the wiki)

**Comment by RobLoach** [comment]
On Linux here too. I've actually had more success with cmake than the makefiles. Don't need to change any of the libtype or platform...

https://github.com/raysan5/raylib/blob/master/projects/CMake/CMakeLists.txt

```
cd projects/CMake
mkdir build
cd build
cmake ..
make
./example
```

**Comment by chriscamacho** [comment]
for me (on Linux too!) I usually just run make on its own, but then I prefer static lib for raylib. But adding vars (like for shared) just works. I'm intregued as to what the difference might be, I've always found the hand rolled makefile to be robust on a number of different platforms and configurations...

**Comment by raysan5** [comment]
I'm afraid there is not enough information about the process and environment conditions to track it properly.

**Comment by the-gremlin** [comment]
oof i kinda forgot about this...
