### ISSUE TITLE
[raymath] Vector3RotateByQuaternion() not working as expected

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1765]
initially I was using

    Matrix f = QuaternionToMatrix(boids[i].heading);
    boids[i].side = Vector3Transform((Vector3){-1,0,0}, f);

To get a vector pointing at right angles to direction of travel, which worked exactly as expected, later realising there was a rotV3byQ function I changed to

    boids[i].side = Vector3RotateByQuaternion((Vector3){-1,0,0}, boids[i].heading);

However this gave incorrect results (the code looks lifted from a site I've had problems with before!)

I ended up using this

    boids[i].side = V3MultQ((Vector3){-1,0,0}, boids[i].heading);

here's the function that behaves the same as converting to matrix and transforming the vector by the matrix...

    Vector3 V3MultQ(Vector3 v, Quaternion q)
    {
        Vector3 r, qv, uv, uuv;
        
        qv.x = q.x;
        qv.y = q.y;
        qv.z = q.z;
        
        uv = Vector3CrossProduct(v, qv);
        uuv = Vector3CrossProduct(uv, qv);    

        uv = Vector3Scale(uv, 2.f*q.w);
        uuv = Vector3Scale(uuv, 2.0f);
        
        r = Vector3Add(v, uv);
        r = Vector3Add(r, uuv);
        
        return r;
    }

**Comment by chriscamacho** [comment]
```C
#include "raylib.h"
#include "rlgl.h" // just to change line width
#include "raymath.h"

#define windowWidth 1280
#define windowHeight 720

Vector3 Vector3MultiplyQuaternion(Vector3 v, Quaternion q)
{
    Vector3 r, qv, uv, uuv;
    
    qv.x = q.x;
    qv.y = q.y;
    qv.z = q.z;
    
    uv = Vector3CrossProduct(v, qv);
    uuv = Vector3CrossProduct(uv, qv);    

    uv = Vector3Scale(uv, 2.f*q.w);
    uuv = Vector3Scale(uuv, 2.0f);
    
    r = Vector3Add(v, uv);
    r = Vector3Add(r, uuv);
    
    return r;
}

int main(void)
{
    SetTraceLogLevel( LOG_ALL );
    SetConfigFlags( FLAG_VSYNC_HINT | FLAG_MSAA_4X_HINT );
    InitWindow( windowWidth, windowHeight, "Raylib - template" );

    Camera camera = { 0 };
    camera.position = (Vector3){ 0.0f, 1.0f, 4.0f };
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
    camera.fovy = 45.0f;
    camera.projection = CAMERA_PERSPECTIVE;

    Vector3 ang = { 0 };
    Vector3 qv = { 0 };
    Vector3 mv = { 0 };
    Vector3 bv = { 0 };
    Quaternion q;

    float dT = 0;

    rlSetLineWidth(4);
    while ( !WindowShouldClose() )
    {
        dT = GetFrameTime();

        ang.x += .7f * dT;
        ang.y += .55 * dT;
        ang.z -= 2.75 * dT;
        
        q = QuaternionFromEuler(ang.x, ang.y, ang.z);
        qv = Vector3MultiplyQuaternion((Vector3){0,0,1}, q);
        
        Matrix m = QuaternionToMatrix(q);
        mv = Vector3Transform((Vector3){0,0,1},m);
        
        bv = Vector3RotateByQuaternion((Vector3){0,0,1}, q);
 
        BeginDrawing();
        ClearBackground( (Color){64,128,255,255} );
        
        BeginMode3D( camera );
        DrawLine3D((Vector3){0,0,0}, qv, GREEN);
        DrawLine3D((Vector3){-.1,0,0}, mv, YELLOW);
        DrawLine3D((Vector3){.1,0,0}, bv, RED);

        DrawGrid( 10, 1.0f );

        EndMode3D();

        EndDrawing();
    }

    CloseWindow();
    return 0;
}
```

**Comment by chriscamacho** [comment]
I understand what this issue is with the existing function:
```c
        q = QuaternionFromEuler(ang.x, ang.y, ang.z);
        qv = Vector3MultiplyQuaternion((Vector3){0,0,1}, q);
        
        m = QuaternionToMatrix(q);
        mv = Vector3Transform((Vector3){0,0,1},m);
        
        bv = Vector3RotateByQuaternion((Vector3){0,0,1}, q);
 
        m = MatrixTranspose(m);
        q = QuaternionFromMatrix(m);
        bv2 = Vector3RotateByQuaternion((Vector3){0,0,1}, q);
```
bv2 is transformed as expected if the quat is made from a transposed matrix, major row/column issue...


If you're waiting for a PR, its unlikely to happen!

I have no intention of following github's new policy for "security" just a pita for only perceived gain.

**Comment by raysan5** [comment]
@chriscamacho thank you very much for reviewing this issue! No worries, I'll apply the patch myself.

**Comment by chriscamacho** [comment]
Thx, see the above code, for confirmation (do run it)

**Comment by raysan5** [comment]
It would take a bit longer to apply this patch, several functions from models animation system depend on `Vector3RotateByQuaternion()`, so they should also be reviewed. `model.c` functions to review: 
```c
void UpdateModelAnimation(Model model, ModelAnimation anim, int frame);
static Model LoadIQM(const char *fileName);
static ModelAnimation* LoadIQMModelAnimations(const char* fileName, int* animCount);
static void InitGLTFBones(Model* model, const cgltf_data* data);
static void BindGLTFPrimitiveToBones(Model* model, const cgltf_data* data, int primitiveIndex);
static ModelAnimation *LoadGLTFModelAnimations(const char *fileName, int *animCount);
```

**Comment by chriscamacho** [comment]
ha! maybe that's why loading animations is broke !

**Comment by object71** [comment]
@chriscamacho What do you mean by "loading animations is broke"? 
I investigated your proposed function modification. Thank you for noticing that something is wrong but you got it the other way around. It is not ```Vector3RotateByQuaternion``` which is wrong but ```QuaternionToMatrix```.

In this function, you proposed you got the cross product calculation incorrectly:

```cpp
Vector3 V3MultQ(Vector3 v, Quaternion q)
{
    Vector3 r, qv, uv, uuv;
    
    qv.x = q.x;
    qv.y = q.y;
    qv.z = q.z;
    
    uv = Vector3CrossProduct(v, qv); // This should actually be QV x V and not V x QV
    uuv = Vector3CrossProduct(uv, qv);  // This should actually be QV x UV and not UV x QV

    uv = Vector3Scale(uv, 2.f*q.w);
    uuv = Vector3Scale(uuv, 2.0f);
    
    r = Vector3Add(v, uv);
    r = Vector3Add(r, uuv);
    
    return r;
}
```

I will have a pull request shortly to fix QuaternionToMatrix which provided the wrong results (and when transposed would provide the correct results).

@raysan5 I compared Raylib's math library with the well-known [glm library](https://github.com/g-truc/glm/blob/master/glm/gtc/quaternion.inl#L47) to confirm what the correct formulas are. ```Vector3RotateByQuaternion``` is absolutely on point. ```QuaternionToMatrix``` on the other hand has some small differences which I guess cause it to miscalculate the values.

**Comment by chriscamacho** [comment]
@object71 I came to the same conclusion in the end but havent had any time for testing or coding.

it's not too diffucult to export an animation from blender via gltf where the rotations are all messed up, the only animated model I've managed to load and have it work is the cesium man walk cycle from the khronous example models...

**Comment by object71** [comment]
@chriscamacho Ok, I will try to do a sample model with animation to see if I can reproduce the said problem. 

If you have one that you're willing to share you can open an issue about the animation being broken and I can take a look.

**Comment by chriscamacho** [comment]
@object71 please see #1800

**Comment by object71** [comment]
@chriscamacho Yeah I already tested it and opened #1799 with my own model done in blender.

**Comment by chriscamacho** [comment]
#1799 is closed ? issue still exists...

**Comment by raysan5** [comment]
@chriscamacho #1799 is not closed
