### ISSUE TITLE
[EXAMPLES] Website is using older examples for input.

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib#1773]
input examples on the website are using MOUSE_BUTTON_LEFT enums not MOUSE_LEFT_BUTTON from the current header. This causes people who use the website to fail to compile with the current installer, causing confusion.

**Comment by raysan5** [comment]
This issue should probably be reported in https://github.com/raysan5/raylib.com repo but it's ok.

Examples are [manually ported to web](https://github.com/raysan5/raylib.com/tree/master/examples/web) to avoid webassembly `ASYNCIFY`. Some of them could be not updated after being updated in raylib main repo.

It requires some time... I'll review them asap.

**Comment by raysan5** [comment]
Actually, it should work the same, raylib defines:
```c
// Add backwards compatibility support for deprecated names
#define MOUSE_LEFT_BUTTON   MOUSE_BUTTON_LEFT
#define MOUSE_RIGHT_BUTTON  MOUSE_BUTTON_RIGHT
#define MOUSE_MIDDLE_BUTTON MOUSE_BUTTON_MIDDLE
```
