### ISSUE TITLE
[Examples] Error when trying to execute the advance_game template from raylib/templates 

### ISSUE THREAD

**Issue by the-gremlin** [raysan5/raylib#1775]
### Issue description
I'm trying to execute the advance_game template which has been compiled using the provided Makefile, but when I try to run the resulting executable i get the error `./advance_game: error while loading shared libraries: libraylib.so.370: cannot open shared object file: No such file or directory`
### Environment
Platform: PC
OS: Manjaro with i3wm
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.3 (taken from `glxinfo | grep "OpenGL version"`)
*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*

Reproduction:
Install Raylib using Make, go to raylib/templates/advance_game
compile using `make`
run the resulting executable

**Comment by raysan5** [comment]
You should build raylib library first.

**Comment by the-gremlin** [comment]
but i did?
