### ISSUE TITLE
[texture] Black line appears for a single frame when moving a transparent texture slowly

### ISSUE THREAD

**Issue by olafurw** [raysan5/raylib#1777]
### Issue description

A black line appears occasionally when moving a transparent object slowly down the screen. It seems to be the top part of the image wrapping around. If I remove pixels from the top line it reflects in how the bottom line looks like

### Environment

Windows 10. 1080. Not sure on the opengl version.

### Issue Screenshot

![raylib_black_line](https://user-images.githubusercontent.com/103783/118539882-405c7580-b750-11eb-9d14-ea26b4cc0262.gif)

Image used is a 16x16 transparent png. I tried different ways of saving it, all same results.

![image](https://user-images.githubusercontent.com/103783/118540113-8ca7b580-b750-11eb-9ead-66a441fea2a7.png)

### Code Example

```cpp
#include "raylib.h"

int main()
{
    const int windowWidth = 800;
    const int windowHeight = 600;
    InitWindow(windowWidth, windowHeight, "bug-repro");

    SetTargetFPS(60);

    Vector2 pos = { 128.0f, 128.0f };
    Texture2D item = LoadTexture("../../../img/wtop.png");

    while (!WindowShouldClose())
    {
        pos.y += 0.025f;

        BeginDrawing();
        {
            ClearBackground(RAYWHITE);

            DrawTextureEx(item, pos, 0.0f, 4.0f, WHITE);
        }
        EndDrawing();
    }

    CloseWindow();

    return 0;
}
```

**Comment by nobytesgiven** [comment]
AMD Radeon RX 5700 XT
GLSL:     4.60
I can not see any problem

**Comment by raysan5** [comment]
As comnented on Discord, the issue is related to texture wrap mode. There is some pixel bleeding when using `TEXTURE_WRAP_REPEAT` (default mode). One solution is just using `TEXTURE_WRAP_CLAMP`.

**Comment by olafurw** [comment]
Putting 

```cpp
SetTextureWrap(item, TEXTURE_WRAP_CLAMP);
```

Fixes the issue on my end.
