### ISSUE TITLE
[examples] models/models_skybox HDR not working

### ISSUE THREAD

**Issue by creutzerb** [raysan5/raylib#1778]
### Issue description

In the Example project `models skybox` with `bool useHDR = true;` in `models_skybox.c`
All I see is a plain light grey instead of the skybox.
The Web version is working as expected on my computer.

### Environment
Manjaro Linux
Raylib Master branch

LOGS seem ok :
```
INFO: Initializing raylib 3.7
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 397
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: GeForce RTX 2060/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 460.73.01
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
INFO: FILEIO: [resources/shaders/glsl330/skybox.vs] Text file loaded successfully
INFO: FILEIO: [resources/shaders/glsl330/skybox.fs] Text file loaded successfully
INFO: SHADER: [ID 4] Vertex shader compiled successfully
INFO: SHADER: [ID 5] Fragment shader compiled successfully
INFO: SHADER: [ID 6] Program shader loaded successfully
INFO: SHADER: [ID 6] Shader attribute (vertexPosition) set at location: 0
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexTexCoord
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexTexCoord2
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexNormal
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexTangent
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexColor
WARNING: SHADER: [ID 6] Failed to find shader uniform: mvp
INFO: SHADER: [ID 6] Shader uniform (view) set at location: 4
INFO: SHADER: [ID 6] Shader uniform (projection) set at location: 2
WARNING: SHADER: [ID 6] Failed to find shader uniform: matNormal
WARNING: SHADER: [ID 6] Failed to find shader uniform: colDiffuse
WARNING: SHADER: [ID 6] Failed to find shader uniform: texture0
WARNING: SHADER: [ID 6] Failed to find shader uniform: texture1
WARNING: SHADER: [ID 6] Failed to find shader uniform: texture2
INFO: SHADER: [ID 6] Shader uniform (environmentMap) set at location: 1
INFO: SHADER: [ID 6] Shader uniform (doGamma) set at location: 0
INFO: SHADER: [ID 6] Shader uniform (vflipped) set at location: 3
INFO: FILEIO: [resources/shaders/glsl330/cubemap.vs] Text file loaded successfully
INFO: FILEIO: [resources/shaders/glsl330/cubemap.fs] Text file loaded successfully
INFO: SHADER: [ID 4] Vertex shader compiled successfully
INFO: SHADER: [ID 5] Fragment shader compiled successfully
INFO: SHADER: [ID 7] Program shader loaded successfully
INFO: SHADER: [ID 7] Shader attribute (vertexPosition) set at location: 0
WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexTexCoord
WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexTexCoord2
WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexNormal
WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexTangent
WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexColor
WARNING: SHADER: [ID 7] Failed to find shader uniform: mvp
INFO: SHADER: [ID 7] Shader uniform (view) set at location: 2
INFO: SHADER: [ID 7] Shader uniform (projection) set at location: 1
WARNING: SHADER: [ID 7] Failed to find shader uniform: matNormal
WARNING: SHADER: [ID 7] Failed to find shader uniform: colDiffuse
WARNING: SHADER: [ID 7] Failed to find shader uniform: texture0
WARNING: SHADER: [ID 7] Failed to find shader uniform: texture1
WARNING: SHADER: [ID 7] Failed to find shader uniform: texture2
INFO: SHADER: [ID 7] Shader uniform (equirectangularMap) set at location: 0
INFO: FILEIO: [resources/dresden_square_2k.hdr] File loaded successfully
INFO: IMAGE: [resources/dresden_square_2k.hdr] Data loaded successfully (2048x1024)
INFO: TEXTURE: [ID 3] Texture loaded successfully (2048x1024 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Depth renderbuffer loaded successfully (32 bits)
INFO: TEXTURE: [ID 4] Cubemap texture loaded successfully (1024x1024)
INFO: FBO: [ID 1] Framebuffer object created successfully
INFO: FBO: [ID 1] Unloaded framebuffer from VRAM (GPU)
INFO: TEXTURE: [ID 3] Unloaded texture data from VRAM (GPU)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: SHADER: [ID 6] Unloaded shader program data from VRAM (GPU)
INFO: TEXTURE: [ID 4] Unloaded texture data from VRAM (GPU)
INFO: VAO: [ID 2] Unloaded vertex array data from VRAM (GPU)
INFO: MODEL: Unloaded model (and meshes) from RAM and VRAM
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
```
![image](https://user-images.githubusercontent.com/10078731/118706458-ac56e080-b819-11eb-86e8-783ed1271e29.png)

**Comment by chriscamacho** [comment]
I see this too both nvidia desktop and intel laptop gpu's

On Tuesday, 18 May 2021, creutzerb ***@***.***> wrote:
> Issue description
>
> In the Example project models skybox with bool useHDR = true; in
models_skybox.c
> All I see is a plain light grey instead of the skybox.
> The Web version is working as expected on my computer.
>
> Environment
>
> Manjaro Linux
> Raylib Master branch
>
> LOGS seem ok :
>
> INFO: Initializing raylib 3.7
> INFO: DISPLAY: Device initialized successfully
> INFO: > Display size: 1920 x 1080
> INFO: > Render size: 800 x 450
> INFO: > Screen size: 800 x 450
> INFO: > Viewport offsets: 0, 0
> INFO: GLAD: OpenGL extensions loaded successfully
> INFO: GL: Supported extensions count: 397
> INFO: GL: OpenGL device information:
> INFO: > Vendor: NVIDIA Corporation
> INFO: > Renderer: GeForce RTX 2060/PCIe/SSE2
> INFO: > Version: 3.3.0 NVIDIA 460.73.01
> INFO: > GLSL: 3.30 NVIDIA via Cg compiler
> INFO: GL: DXT compressed textures supported
> INFO: GL: ETC2/EAC compressed textures supported
> INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 - 1 mipmaps)
> INFO: TEXTURE: [ID 1] Default texture loaded successfully
> INFO: SHADER: [ID 1] Vertex shader compiled successfully
> INFO: SHADER: [ID 2] Fragment shader compiled successfully
> INFO: SHADER: [ID 3] Program shader loaded successfully
> INFO: SHADER: [ID 3] Default shader loaded successfully
> INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
> INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
> INFO: RLGL: Default OpenGL state initialized successfully
> INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 - 1 mipmaps)
> INFO: FONT: Default font loaded successfully
> INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
> INFO: FILEIO: [resources/shaders/glsl330/skybox.vs] Text file loaded
successfully
> INFO: FILEIO: [resources/shaders/glsl330/skybox.fs] Text file loaded
successfully
> INFO: SHADER: [ID 4] Vertex shader compiled successfully
> INFO: SHADER: [ID 5] Fragment shader compiled successfully
> INFO: SHADER: [ID 6] Program shader loaded successfully
> INFO: SHADER: [ID 6] Shader attribute (vertexPosition) set at location: 0
> WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexTexCoord
> WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexTexCoord2
> WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexNormal
> WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexTangent
> WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexColor
> WARNING: SHADER: [ID 6] Failed to find shader uniform: mvp
> INFO: SHADER: [ID 6] Shader uniform (view) set at location: 4
> INFO: SHADER: [ID 6] Shader uniform (projection) set at location: 2
> WARNING: SHADER: [ID 6] Failed to find shader uniform: matNormal
> WARNING: SHADER: [ID 6] Failed to find shader uniform: colDiffuse
> WARNING: SHADER: [ID 6] Failed to find shader uniform: texture0
> WARNING: SHADER: [ID 6] Failed to find shader uniform: texture1
> WARNING: SHADER: [ID 6] Failed to find shader uniform: texture2
> INFO: SHADER: [ID 6] Shader uniform (environmentMap) set at location: 1
> INFO: SHADER: [ID 6] Shader uniform (doGamma) set at location: 0
> INFO: SHADER: [ID 6] Shader uniform (vflipped) set at location: 3
> INFO: FILEIO: [resources/shaders/glsl330/cubemap.vs] Text file loaded
successfully
> INFO: FILEIO: [resources/shaders/glsl330/cubemap.fs] Text file loaded
successfully
> INFO: SHADER: [ID 4] Vertex shader compiled successfully
> INFO: SHADER: [ID 5] Fragment shader compiled successfully
> INFO: SHADER: [ID 7] Program shader loaded successfully
> INFO: SHADER: [ID 7] Shader attribute (vertexPosition) set at location: 0
> WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexTexCoord
> WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexTexCoord2
> WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexNormal
> WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexTangent
> WARNING: SHADER: [ID 7] Failed to find shader attribute: vertexColor
> WARNING: SHADER: [ID 7] Failed to find shader uniform: mvp
> INFO: SHADER: [ID 7] Shader uniform (view) set at location: 2
> INFO: SHADER: [ID 7] Shader uniform (projection) set at location: 1
> WARNING: SHADER: [ID 7] Failed to find shader uniform: matNormal
> WARNING: SHADER: [ID 7] Failed to find shader uniform: colDiffuse
> WARNING: SHADER: [ID 7] Failed to find shader uniform: texture0
> WARNING: SHADER: [ID 7] Failed to find shader uniform: texture1
> WARNING: SHADER: [ID 7] Failed to find shader uniform: texture2
> INFO: SHADER: [ID 7] Shader uniform (equirectangularMap) set at location:
0
> INFO: FILEIO: [resources/dresden_square_2k.hdr] File loaded successfully
> INFO: IMAGE: [resources/dresden_square_2k.hdr] Data loaded successfully
(2048x1024)
> INFO: TEXTURE: [ID 3] Texture loaded successfully (2048x1024 - 1 mipmaps)
> INFO: TEXTURE: [ID 1] Depth renderbuffer loaded successfully (32 bits)
> INFO: TEXTURE: [ID 4] Cubemap texture loaded successfully (1024x1024)
> INFO: FBO: [ID 1] Framebuffer object created successfully
> INFO: FBO: [ID 1] Unloaded framebuffer from VRAM (GPU)
> INFO: TEXTURE: [ID 3] Unloaded texture data from VRAM (GPU)
> INFO: TIMER: Target time per frame: 16.667 milliseconds
> INFO: SHADER: [ID 6] Unloaded shader program data from VRAM (GPU)
> INFO: TEXTURE: [ID 4] Unloaded texture data from VRAM (GPU)
> INFO: VAO: [ID 2] Unloaded vertex array data from VRAM (GPU)
> INFO: MODEL: Unloaded model (and meshes) from RAM and VRAM
> INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
> INFO: SHADER: [ID 3] Default shader unloaded successfully
> INFO: TEXTURE: [ID 1] Default texture unloaded successfully
> INFO: Window closed successfully
>
> <
https://ci6.googleusercontent.com/proxy/PmgQq7d42H3g5vdwR27NFOdu4uDvKJZyfwzkmLCfmTB_GQo0XsoYv7SRexQ-0aqe7O_VEWN8hTvDk1Y2P0UIQ4GAvATaL2bvJiQSNDP8AikhuaK99ZEwpLrm2IflISPJct20tf-B-qb90pv_nYqNZuQLUjrzWp5g=s0-d-e1-ft#https://user-images.githubusercontent.com/10078731/118706458-ac56e080-b819-11eb-86e8-783ed1271e29.png
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/dKMi0dKXkkbGB_GknyxK92HfqmX2s6CNv58KpB7RifvqTRFx3_ft5EbcNwmDyjSlpGoHLUtQrYA2nfi7PnQmcP1MQmEQ14Tisn8MQO-ZAKIZ3d4FsSWhNvdF5NB0IH2hSPZaDMMK8aA4QfbciWfPrkxirIXQ8KirAuB2seWHg-CpYnixiO9KZJk7EHrRjgPSPUvoaus3frFZ8r_8GsZ4n71UO7c=s0-d-e1-ft#https://github.com/notifications/beacon/AAFO4SM6ACQDKMPWWIOEHS3TOKYSPA5CNFSM45DCNPAKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4NKTUEQQ.gif
>

-- 

blog bedroomcoders.co.uk <http://bedroomcoders.co.uk>
Free source code and tutorials!


Disclaimer:
By sending an email to ANY of my addresses you are agreeing that:

   1. I am by definition, "the intended recipient"

   2. All information in the email is mine to do with as I see fit and make
such financial profit, political mileage, or good joke as it lends itself
to. In particular, I may quote it where I please.

   3. I may take the contents as representing the views of your company.

   4. This overrides any disclaimer or statement of confidentiality that
may be included on your message.
