### ISSUE TITLE
[texture] ExportImage does not use SaveFileData callback for most image formats

### ISSUE THREAD

**Issue by holmesmr** [raysan5/raylib#1779]
Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
   - Code on master fairly evidently has this issue anyway
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When using ExportImage, Formats for which STBI is supported just use STBI directly to do file IO, bypassing any callbacks configured in raylib for e.g. VFS implementations. Affects all export formats except KTX and RAW.

Should be fixable by replacing the STBI writes with their *_to_func variants.

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*

Platform: Desktop
OS: Windows 10 20H2 (April update)
OpenGL version: 3.3
GPU: NVIDIA RTX 3080

### Issue Screenshot
N/A

### Code Example

```c
#include <raylib.h>

bool MySaveFileDataCallback(const char* fileName, void* data, unsigned int bytesToWrite) {
    TraceLog(LOG_WARNING, "MySaveFileDataCallback: Skipping saving file %s", fileName);
    return true;
}

int main(void) {
    SetSaveFileDataCallback(MySaveFileDataCallback);
    Image im = GenImageColor(640, 480, RED);
    ExportImage(im, "red.png");
    ExportImage(im, "red.raw");
}
```

Saving RAW stops file save and logs message, PNG does not.

**Comment by raysan5** [comment]
@holmesmr thanks! yeah, this needs to be reviewed!

**Comment by raysan5** [comment]
@holmesmr I reviewed the funtion but I'm afraid `stbi_image_write` do not have similar memory functions for TGA, BMP or JPG...

**Comment by MikeDX** [comment]
@raysan5 is there a cross platform memory fopen we can utilise as a buffer for those formats?

**Comment by holmesmr** [comment]
My apologies for this; I thought it wouldn't be too hard as I didn't quite realise the "to_func" variants required `fwrite()`-esque semantics.

**Comment by raysan5** [comment]
@MikeDX @holmesmr I'm afraid there is no option for the moment. I'm closing this issue.
