### ISSUE TITLE
[models] All collision methods should return RayHitInfo

### ISSUE THREAD

**Issue by Crydsch** [raysan5/raylib#1781]
Currently only these methods return `RayHitInfo`:
- `GetCollisionRayMesh(..)`
- `GetCollisionRayModel(..)`
- `GetCollisionRayTriangle(..)`
- `GetCollisionRayGround(..)`

These don't:
- `CheckCollisionRaySphere(..)`
- `CheckCollisionRaySphereEx(..)`
- `CheckCollisionRayBox(..)`

It would be beneficial (for consistency), if all collision methods would return `RayHitInfo`.

Further, `RayHitInfo` includes not only `hit` and `distance`, but the point of `collision` and `normal` as well.
This additional information may require additional computation.
It may be of interest to only return only `hit` (and `distance` ?) for performance reasons?
And have another `*CollisionEx(..)` method which returns the full `RayHitInfo`?
On other hand raylib is meant to be easy not necessarily fast, so just return everything?

If you agree on changes I'd like to work on this :)

**Comment by raysan5** [comment]
@Crydsch Thanks for noticing that! Those functions were added recently and I didn't notice those consistency issues at that point. Actually, I think all the implementation should be redesigned...

First, I'd consider renaming `RayHitInfo` to `RayCollision` or `RayCollisionInfo` for consistency with the functions.

About the function, I'd return all the information for every collision, despite the computational cost, it's the simpler approach for the user. I'd also rename the functions for consistency:

 - `bool CheckCollisionRaySphere()`  -> `RayCollision GetCollisionRaySphere()`
 - `bool CheckCollisionRaySphereEx()` -> REMOVED
 - `bool CheckCollisionRayBox()` -> `RayCollision GetCollisionRayBox()`

Also, another function I think should be reviewed:

 - `RayHitInfo GetCollisionRayGround()` -> `RayCollision GetCollisionRayQuad(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 p4)`

What do you think?

**Comment by Crydsch** [comment]
Sounds reasonable to me. I'll get right to work and send a pull request when done.

While were at it .. A while ago I wrote a method `GetCollisionRayOrientedBox(Ray, Box, Matrix)` which, as the name implies, allows for oriented bounding boxes instead of just axis aligned ones. 
If you want, i can add this too.

**Comment by raysan5** [comment]
@Crydsch I'd call the method `GetCollisionRayBoxEx(Ray, Box, Matrix)` as an extended version of `GetCollisionRayBox()`.

For the moment I prefer to avoid adding new data types... actually, I believe some types should probably belong to a higher level engine instead of raylib...

**Comment by chriscamacho** [comment]
An option to include (only if needed?) barycentric coords would be useful (in effect texture UV) see https://bedroomcoders.co.uk/implementing-a-3d-gui-with-raylib/ and https://bedroomcoders.co.uk/painting-on-a-3d-mesh-with-raylib/

**Comment by Crydsch** [comment]
@raysan5 Your're right, this is probably better suited to be outside of raylib.

@chriscamacho I think this is a rather special use case and is not usefull to most raylib users. Other than that it only makes sense for triangles. What would do for quads, spheres, boxes?

**Comment by chriscamacho** [comment]
@Crydsch quads, spheres, boxes... can all be created with triangles, its no drama to triangulate media and often exactly what I do for targetable meshes.

**Comment by Crydsch** [comment]
@chriscamacho Sure, we can triangulate them, but the problem I see is that if we return only the barycentric coords, it will not be particularly useful to the user. They would have to triangulate it in the exact same way we do internally, or the barycentric coords are wrong.
The models_mesh_picking example uses Vector3Barycenter(..) to calculate these coords. Key is though, that the user decides how the triangle winding is to be interpreted.

**Comment by Crydsch** [comment]
Sorry, i have been busy lately, but i got some work done on this. I can send a pull request by the weekend.

**Comment by raysan5** [comment]
@Crydsch Ok, no worries, just changed the signatures of the functions, internal code still needs some review to return all required RayCollision data.

**Comment by Crydsch** [comment]
@raysan5 I was able to finish this one today. Some improvements in `GetRayCollisionBox()` and I adjusted the mesh picking example accordingly.
Just one question remaining; we wanted to replace `GetRayCollisionGround()` with `GetRayCollisionQuad()`, and i thought of jsut splitting the quad into two triangles. But then we either assume a specific winding (like we do with triangles) or we would need to "sort" the given points upfront. Both variants seem strange to me. Maybe it's best to just let the user triangulate their quad?

**Comment by raysan5** [comment]
@Crydsch Yeah, about `GetRayCollisionQuad()` I also though about the winding, I'd would assume counter-clock-wise, it's the winding assumed by raylib by default. So, user should provide the vertex in the right order.

**Comment by Crydsch** [comment]
Alright! I'll add this and send a PR.

**Comment by raysan5** [comment]
@Crydsch I'm closing this issue because it has already been redesigned, just merging the PR is left...
