### ISSUE TITLE
[build] Configurations issue without image format support

### ISSUE THREAD

**Issue by pfirsich** [raysan5/raylib#1784]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib (none of my code involved)

### Issue description

When building raylib without any image format support (with the purpose of only using procedural images and textures), I get a compilation error:
```
../src/textures.c:473:19: error: implicitly declaring library function 'sprintf' with type 'int (char *, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
    bytesCount += sprintf(txtData + bytesCount, "////////////////////////////////////////////////////////////////////////////////////////\n");
                  ^
../src/textures.c:473:19: note: include the header <stdio.h> or explicitly provide a declaration for 'sprintf'
```
I think stdio, which is used in `ExportImageAsCode` (the function with the compilation error) is only included through `stb_image.h` and `stb_image_write.h`, which don't get included if `SUPPORT_FILEFORMAT_BMP`, `SUPPORT_FILEFORMAT_PNG`, `SUPPORT_FILEFORMAT_TGA`, `SUPPORT_FILEFORMAT_JPG`, `SUPPORT_FILEFORMAT_PSD`, `SUPPORT_FILEFORMAT_GIF`, `SUPPORT_FILEFORMAT_PIC`, `SUPPORT_FILEFORMAT_HDR`, `SUPPORT_IMAGE_EXPORT`, `SUPPORT_COMPRESSION_API` are all disabled.

I would have created a PR, but I am not sure if the proper fix is to remove `ExportImageAsCode` with `SUPPORT_IMAGE_EXPORT` or simply add an include if `SUPPORT_STANDARD_FILEIO` is set (and remove `ExportImageAsCode` if it is not I guess?).

### Environment

* clang 11.0.0-2 on Ubuntu 20

**Comment by pfirsich** [comment]
Also it seems that you can't use DrawText without `SUPPORT_IMAGE_MANIPULATION`. I am not sure if that is intentional. I can create another issue for this too.

**Comment by raysan5** [comment]
@pfirsich Oh, good catch... `SUPPORT_IMAGE_EXPORT` should also consider `ExportImageAsCode()`.

`DrawText()` shouldn't depend on `SUPPORT_IMAGE_MANIPULATION`, do you mean `ImageDrawText()`? It depends on `ImageTextEx()` that requires `SUPPORT_IMAGE_MANIPULATION`. In that case it's intentional.
