### ISSUE TITLE
[raudio] Play/StopAudioBuffer should be locked by a mutex

### ISSUE THREAD

**Issue by jojolatina** [raysan5/raylib#1789]
In the raudio module, the functions that modify an AudioBuffer (PlayAudioBuffer/StopAudioBuffer,...) are not locked, but the audio mixing thread accesses the data in the audio buffer. I think there should be locks inside these functions to prevent any race condition.

**Comment by raysan5** [comment]
@jojolatina Good catch! Feel free to send a PR if you can...

**Comment by raysan5** [comment]
I'm not an expert on threading but, checking this issue carefully, it seem very unprovable to be problematic, function `TrackAudioBuffer(AudioBuffer *buffer)` already uses a mutex. I'm closing it.
