### ISSUE TITLE
Application crashes after calling TraceLog(LOG_ERROR)

### ISSUE THREAD

**Issue by colesnicov** [raysan5/raylib#1796]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [ ] My code has no errors or misuse of raylib

### Issue description

Hello. I am trying this framework, and I came across one for me not quite understandable Matura.
When I call:
`TraceLog (LOG_ERROR, ...); `- application crashes with the **return 1**.

But when I call:
`TraceLog (LOG_FATAL, ...); `- program runs on as if nothing happened.

Maybe I'm wrong, but shouldn't it be the other way around?

### Environment

Ubuntu 20 (LTS)

**Comment by raysan5** [comment]
@colesnicov LOG_FATAL level was added later on so `exit()` was on LOG_ERROR, in any case, just reviewed it to exit() on LOG_FATAL.
