### ISSUE TITLE
Update GLFW to 3.1?

### ISSUE THREAD

**Issue by procedural** [raysan5/raylib#18]
New GLFW version was released this week. I see raylib uses 3.0.4, which is a year old now.

**Comment by raysan5** [comment]
Thanks procedural, I already uploaded new GLFW version 3.1 to develop branch. It will be integrated into master branch in  next release (hopefully, in a couple of weeks).

**Comment by raysan5** [comment]
It seems that there are linking problems with new version with MinGW (32bit) under Windows 8.1 (64bit). I have to take a look at this issue: : undefined reference to `__ms_vsnprintf'

**Comment by procedural** [comment]
Yea, your libs define these symbols:
```bash
In glfw3.dll:

6e5ccd60 T ___ms_vsnprintf
6e5cd7b8 T __vsnprintf
6e5d33e4 I __imp___vsnprintf

In libglfw3.a:

         U ___ms_vsnprintf
```

And here I've compiled GLFW 3.1 today with mingw32 compiler on Windows 7:
```
In glfw3.dll:

6cc0b030 T ___mingw_vsnprintf
6cc0b030 T _vsnprintf

In libglfw3.a:

         U _vsnprintf
```
Try them and if they work for you, you can use them for raylib:
https://mega.co.nz/#F!5J4F0Z4L!rP8BtygpB5pAIV5gI6clJA

**Comment by raysan5** [comment]
Thank you very much! It works for me! I integrate it into develop branch.

**Comment by procedural** [comment]
Glad to help, @raysan5!

**Comment by Yassine49** [comment]
Thank you @procedural u save me from a looot o more searching

**Comment by On2iTAaryn** [comment]
Cheers @procedural finally got to compile.
