### ISSUE TITLE
[models] gltf animation not animating correctly

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1800]
here's the model 
[walk.glb.tar.gz](https://github.com/raysan5/raylib/files/6568819/walk.glb.tar.gz)

basically loaded and displayed as per examples/models/models_gltf_animation.c

It looks like the rotations are messed up somehow?

This was originally a download from cgtrader as a blend file which I then exported to gltf, I'm going to relook in blender as it could be just a case of some setting their...

**Comment by chriscamacho** [comment]
i also took a walk cycle from mixamo.com exported as dfx and dea without luck :(

**Comment by raysan5** [comment]
This issue seems a duplicate of #1799. I'm closing it.
