### ISSUE TITLE
Can't Compile Raylib for android

### ISSUE THREAD

**Issue by hero2002** [raysan5/raylib#1807]
- [ ] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
I can't compile raylib for android using 
`mingw32-make PLATFORM=PLATFORM_ANDROID`
### Environment
Win 10 

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*
`C:\raylib\raylib\src>mingw32-make PLATFORM=PLATFORM_ANDROID
C:/NDK/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi29-clang -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -O2 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -ffunction-sections -funwind-tables -fstack-protector-strong -fPIE -fPIC -Wa,--noexecstack -Wformat -no-canonical-prefixes -DANDROID -DPLATFORM_ANDROID -D__ANDROID_API__=29 -DMAL_NO_OSS -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -IC:/NDK/sources/android/native_app_glue -IC:/NDK/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -IC:/NDK/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/arm-linux-androideabi -DPLATFORM_ANDROID -DGRAPHICS_API_OPENGL_ES2
core.c:4357:22: error: use of undeclared identifier 'glfwGetProcAddress'; did you mean 'eglGetProcAddress'?
    rlLoadExtensions(glfwGetProcAddress);
                     ^~~~~~~~~~~~~~~~~~
                     eglGetProcAddress
C:/NDK/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include\EGL/egl.h:135:61: note: 'eglGetProcAddress' declared
      here
EGLAPI __eglMustCastToProperFunctionPointerType EGLAPIENTRY eglGetProcAddress (const char *procname);
                                                            ^
1 error generated.
mingw32-make: *** [Makefile:561: core.o] Error 1`

**Comment by hero2002** [comment]
using the latest src fixed the issue
but for those who have the same problem you should copy new source to raylib/src to work correctly

**Comment by raysan5** [comment]
@hero2002 Ok, just tested it right now and it worked...

**Comment by hero2002** [comment]
@raysan5 
I think you should mention it to avoid confuse new comers that the official 3.7v android will not work

**Comment by 3xtant** [comment]
Yes, @raysan5 please add a note in the releases page. I just spent a couple of hours trying to build raylib on a raspberry pi zero. I had downloaded the source from the releases page instead of the repo.
