### ISSUE TITLE
[build] Compiling fails after OS X command line tools update

### ISSUE THREAD

**Issue by Bambofy** [raysan5/raylib#1808]
After updating to the latest OS X version from 11.3 to 11.4, building a project using raylib causes asan errors. The 11.3 to 11.4 did include an update to the OS X command line tools.

### Environment
- OS X 11.4
- CLion
- C++
- Raylib installed via vcpkg "raylib[core,use-audio]:x64-osx"

```

====================[ Build | Harvestor | Debug ]===============================
"/Users/x/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7442.42/CLion.app/Contents/bin/cmake/mac/bin/cmake" --build /Users/x/Documents/GitHub/Harvestor/cmake-build-debug --target Harvestor -- -j 3
[ 50%] Building CXX object CMakeFiles/Harvestor.dir/source/main.cpp.o
[100%] Linking CXX executable Harvestor
Undefined symbols for architecture x86_64:
  "___asan_version_mismatch_check_apple_clang_1200", referenced from:
      _asan.module_ctor in libraylib.a(core.c.o)
      _asan.module_ctor in libraylib.a(shapes.c.o)
      _asan.module_ctor in libraylib.a(text.c.o)
      _asan.module_ctor in libraylib.a(textures.c.o)
      _asan.module_ctor in libraylib.a(utils.c.o)
      _asan.module_ctor in libraylib.a(window.c.o)
      _asan.module_ctor in libraylib.a(input.c.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Harvestor] Error 1
make[2]: *** [CMakeFiles/Harvestor.dir/all] Error 2
make[1]: *** [CMakeFiles/Harvestor.dir/rule] Error 2
make: *** [Harvestor] Error 2

```

Here is the CMake file.

```
cmake_minimum_required(VERSION 3.17)
project(Harvestor CXX)
enable_testing()

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address")
set(CMAKE_CXX_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=address")

file(GLOB_RECURSE SRC ${PROJECT_SOURCE_DIR}/source/*.c*)
file(GLOB_RECURSE HEADER ${PROJECT_SOURCE_DIR}/source/*.h*)

add_executable(Harvestor ${SRC} ${HEADER})

##########################
# Add the raylib library #
##########################
find_package(raylib REQUIRED)
target_include_directories(Harvestor PUBLIC ${raylib_INCLUDE_DIRS})
target_link_libraries(Harvestor ${raylib_LIBRARIES})

```

**Comment by raysan5** [comment]
Quick search about the issue [here](https://stackoverflow.com/questions/46900598/macos-clang-address-sanitizer-fails-to-link). It seems that _"Apple Clang (the one that comes with Xcode) not supports fsanitize"_.

**Comment by Bambofy** [comment]
I installed the latest llvm brew package and tried to compile it again. When compiling with clang version 12.0.0 the error ""___asan_version_mismatch_check_apple_clang_1200", referenced from:" still appears.

**Comment by Bambofy** [comment]
Here is the compiler information:

x@x ~ % clang++ -v 
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by benbeshara** [comment]
This seems to be an issue with the vcpkg port rather than raylib, someone fixed the same issue on MinGW [here](https://github.com/microsoft/vcpkg/pull/18362/files), I'm assuming a flag for macOS can be added to the same check but as I do not use vcpkg I don't want to make changes to it I can't reliably test.

Checking out from github and building manually works for me (arm64 on 11.1)

**Comment by raysan5** [comment]
@benbeshara thanks for reporting! I neither use the vcpkg system...

@Bambofy Could you try the proposed patch and see if it works?
