### ISSUE TITLE
[rlgl] Disable backface culling in 2D mode?

### ISSUE THREAD

**Issue by ghassanpl** [raysan5/raylib#181]
I think backface culling should be disabled in 2D mode. It's not really necessary and would simplify rendering of triangles/quads for users.

**Comment by raysan5** [comment]
Hi @ghassanpl, backface culling is enabled by default for two reasons:

1. Minimize state changes in the main loop: Even rendering 2D or 3D or both (let's thing of 3D with some HUD), we keep that state untouchable. I don't know exactly the performance impact of enabling/disabling  culling state, probably is negligible but I try to change the minimum OpenGL required states in the loop.
2. The only user-exposed functions where backface culling is relevant are `DrawTriangle()` and `DrawPolyEx()` and I usually use those functions with my students to explain normals, backface culling concepts and how important is to be organized while defining vertices.

In what case do you prefer backface culling disabled for 2D?

**Comment by ghassanpl** [comment]
Those are both good points. I wanted to draw some custom polygons using rlgl, it's where it came up, but I guess the core library doesn't need it.

**Comment by raysan5** [comment]
Actually, if using `rlgl` module directly you can just enable/disable it on user code...
