### ISSUE TITLE
[textures] High GPU usage on `textures_image_loading` example

### ISSUE THREAD

**Issue by nagy** [raysan5/raylib#1816]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib ( i just used the examples )

### Issue description

When starting the example `textures_image_loading` I see about 100% GPU usage. Every other example that I tested worked fine with almost 0% of GPU usage.

### Environment

platform: linux
os: nixos-unstable
opengl-version: ??
GPU details: 
```sh
$ lspci | grep VGA
02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7)
```
the gpu driver is `amdgpu`. To be specific, my GPU is Radeon RX 580.

### Issue Screenshot
I see this with `radeontop`

![radeontop](https://user-images.githubusercontent.com/692274/121234524-16e8c280-c894-11eb-98f2-e01240639580.png)

### Code Example

I just executed the example `textures_image_loading` on the todays master branch.

I am happy to provide any more information.

**Comment by nagy** [comment]
Upon investigating this further, i found that the example was just missing a  `SetTargetFPS(60);`. It works fine now.

Sorry for the noise. I can make a pull request for this.

**Comment by raysan5** [comment]
@nagy Ok, feel free to send a PR
