### ISSUE TITLE
[core] GLFW Error on Mac M1

### ISSUE THREAD

**Issue by undersquire** [raysan5/raylib#1817]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Raylib crashes with a GLFW error when initalizing window.

`INFO: Initializing raylib 3.8-dev
WARNING: GLFW: Error: 65544 Description: Cocoa: Failed to find service port for display`

### Environment

Platform: Macbook Air
Operating System: MacOS Big Sur 11.4
OpenGL version: 2.1
GPU Details: M1 Chip

### Code Example

Just call InitWindow with any parameters.

EDIT: Im leaving this open even though there was a similar issue reported (https://github.com/raysan5/raylib/issues/1787) as the latest raylib still has this issue.

**Comment by raysan5** [comment]
@undersquire It looks like a GLFW issue. Could you try using [latest GLFW](https://github.com/glfw/glfw) directly to verify?

**Comment by raysan5** [comment]
@undersquire ok, thanks for checking!

**Comment by undersquire** [comment]
No problem!

**Comment by raysan5** [comment]
@undersquire Updated GLFW to latest version from github master branch, please could you verify if it works?

**Comment by undersquire** [comment]
Interesting. So It does not throw that GLFW error anymore, however now when raylib gets to the point `INFO: Initializing raylib 3.8-dev` it just hangs forever. Is this a GLFW problem?

**Comment by raysan5** [comment]
@undersquire are you compiling raylib for OpenGL 3.3 or 2.1?

**Comment by undersquire** [comment]
I am compiling it without setting any flags other than shared library. How do I check which OpenGL it's compiling for by default?

**Comment by raysan5** [comment]
It's a compile flag, defined in Makefile.

**Comment by undersquire** [comment]
The Makefile is targetting OpenGL 3.3 by default. I will test OpenGL 2.1 and 1.1 to see if that makes a difference.

**Comment by undersquire** [comment]
It still hangs forever even when targeting OpenGL 1.1 or 2.1.

**Comment by raysan5** [comment]
@undersquire I'm afraid you should debug source code on `InitWindow()` step by step to find the exact issue but it seems realted to GLFW.

**Comment by undersquire** [comment]
I will try debugging raylib's source for InitWindow, as raylib just crashes as soon as InitWindow is called in my application.

**Comment by undersquire** [comment]
Ok I found the line causing the issue in raylib
`if (!glfwInit())` (core.c, line 3525) is where GLFW just hangs forever. I think I may open an issue on GLFW's repository as this seems to be a direct issue with GLFW.

**Comment by raysan5** [comment]
@undersquire I see. Latest raylib from github master branch is using latest glfw from master branch, I updated it two days ago because of this issue.
