### ISSUE TITLE
[examples] audio_raw_stream.c won't play audio on Windows

### ISSUE THREAD

**Issue by lucastakejame** [raysan5/raylib#1819]
- [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Compiled raylib from source with this cmake config
![image](https://user-images.githubusercontent.com/3236287/121469702-5518db80-c993-11eb-8bf7-e1b1f267ecc1.png)

Tried to run audio_raw_stream.c example, got no audio and this message being spammed:
`WARNING: STREAM: Attempting to write too many frames to buffer `

### Environment

Windows 10
AMD Ryzen 7 3800X
OPENGL 3.3
RTX 2060

### Issue Screenshot

![image](https://user-images.githubusercontent.com/3236287/121469536-0e2ae600-c993-11eb-9cd4-e919086cbcc8.png)

### Code Example

Unaltered code from audio_raw_stream.c

**Comment by raysan5** [comment]
It seems this issue could be a duplicate or highly related to #1770
