### ISSUE TITLE
[Question] Resize window

### ISSUE THREAD

**Issue by Giacom** [raysan5/raylib#182]
Not sure if this is a potential feature request, I might have missed it, but I noticed that there is no way to resize windows. It would be really handy if there was without having to close and reopen the window.

Also this library is really great and easy to use, it is definitely helping me learn C more. Thanks.

**Comment by raysan5** [comment]
Hello @Giacom, window resizing is not enabled by default to avoid problems... 

Actually, what I saw with my students was that, when scaling the window, they expected an adaptative scaling of the screen (including drawn textures), that doesn't work that way, scaled window size just expands the canvas to draw on but drawn textures are not scaled.

On the other side, when enabling full screen mode, canvas is not scaled but it's shown to full screen.

It was quite confusing for my students so I decided to lock it.

But I can enable window resizing with a flag... Why do you need it?

**Comment by Giacom** [comment]
Oh that's a reasonable explanation. I didn't exactly need it, I was able to with around it by re-initialising the window, but I wanted to use it since I was experimenting with GetDroppedFiles() and wanted to resize the window to match any images being opened.

It is probably not worth doing just for that, though I am glad it is not just hidden and am missing it. 

Cheers

**Comment by raysan5** [comment]
oh, it makes sense... but you have a couple of options for your problem:

1. Just lock window to a reasonable standard size (i.e. 1280x720) and add scrolling bars if loaded image is bigger than display area; it requires some work but solution is quite elegant.
2. Once you get image path, load `Image`, check size and, if a bigger window is required, just break while loop, `CloseWindow()` and `InitWindow()` again with the required size. Note that you must `LoadTextureFromImage()` after creating the second window.

I'm not closing that issue but, I'll think about exposing this functionality to raylib users in some way.

**Comment by raysan5** [comment]
Just added a new flag (`FLAG_RESIZABLE_WINDOW`) to allow resizable window. 

Implemented on commit https://github.com/raysan5/raylib/commit/db6538859cd2fabb44f1f29cd87f5b498ca0c2c8.
