### ISSUE TITLE
undefined refrence to '_imp___wassert'

### ISSUE THREAD

**Issue by pointThink** [raysan5/raylib#1828]
Whenever i compile the program using this command
`g++ -std=c++11 main.cpp -lraylib -lopengl32 -lgdi32 -lwinmm`

I get these messages from the compiler
`C:/Users/User/Crap/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libraylib.a(rglfw.o):rglfw.c:(.text+0x2cd1): undefined reference to '_imp___wassert'
C:/Users/User/Crap/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libraylib.a(rglfw.o):rglfw.c:(.text+0x2e76): undefined reference to '_imp___wassert'
C:/Users/User/Crap/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libraylib.a(rglfw.o):rglfw.c:(.text+0x2ec1): undefined reference to '_imp___wassert'
C:/Users/User/Crap/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libraylib.a(rglfw.o):rglfw.c:(.text+0x2f53): undefined reference to '_imp___wassert'
C:/Users/User/Crap/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libraylib.a(rglfw.o):rglfw.c:(.text+0x2f93): undefined reference to '_imp___wassert'
C:/Users/User/Crap/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libraylib.a(rglfw.o):rglfw.c:(.text+0x38af): more undefined references to '_imp___wassert' follow
collect2.exe: error: ld returned 1 exit status`

What could be causing the issue?
I use mingw i686 8.1.0 posix dwarf rt_v6 rev0
The compiler provided with the installer works just fine with the command i used

**Comment by raysan5** [comment]
@pointThink No idea... but it seems this issue could be related to this: https://github.com/rust-lang/rust/issues/60912 In any case, it does not seem an issue with raylib but with the MinGW-w64 compiler.

**Comment by darzaccaro** [comment]
FWIW, I had this same issue when using the pre-compiled binary, but everything works fine when building from source.
