### ISSUE TITLE
Android: compile error

### ISSUE THREAD

**Issue by Bethleem** [raysan5/raylib#1829]
### Issue description

I followed the steps form the eiki and get this error at trying to compile raylib:

core.c:4357:22: error: use of undeclared identifier 'glfwGetProcAddress'; did you mean 'eglGetProcAddress'?
    rlLoadExtensions(glfwGetProcAddress);
                     ^~~~~~~~~~~~~~~~~~
                     eglGetProcAddress

egl.h:135:61: note:
      'eglGetProcAddress' declared here
EGLAPI __eglMustCastToProperFunctionPointerType EGLAPIENTRY eglGetProcAddress (const char *procname);
                                                            ^
1 error generated.
mingw32-make: *** [Makefile:561: core.o] Error 1

### Environment

Working in Windows 10, all sdk and ndk well installed becasuse they work with other engines.

**Comment by raysan5** [comment]
This issue should be already corrected in latest github master branch.
