### ISSUE TITLE
[build] Templates Makefile.Android build process review

### ISSUE THREAD

**Issue by hero2002** [raysan5/raylib#1834]
In Makefile.Android in Line 291
`$(ANDROID_BUILD_TOOLS)/zipalign -f 4 $(PROJECT_BUILD_PATH)/bin/$(PROJECT_NAME).signed.apk $(PROJECT_NAME).apk`

It should be 

`$(ANDROID_BUILD_TOOLS)/zipalign -f 4 $(PROJECT_BUILD_PATH)/bin/$(PROJECT_NAME).unsigned.apk $(PROJECT_NAME).apk`

or else it gives error that $(PROJECT_NAME).signed.apk cannot be opened as zip

**Comment by raysan5** [comment]
@hero2002 Actually the process is correct, signed apk is the one that should be aligned later on, if it does not work then there could be some issue with the signing process.

**Comment by hero2002** [comment]
> @hero2002 Actually the process is correct, signed apk is the one that should be aligned later on, if it does not work then there could be some issue with the signing process.

I don't know It didn't work unless I did the change
