### ISSUE TITLE
A game I made with Raylib

### ISSUE THREAD

**Issue by nicholasimon** [raysan5/raylib#1837]
Just wanted to say thank-you for making a very easy to use game development library. I finally made a mini game using Raylib, it is not amazing though just wanted to share it. 

YouTube - https://www.youtube.com/watch?v=ovN4NAODOEw&t=4s
itch.io - https://nicholasimon.itch.io/snyk

![jBM5iK](https://user-images.githubusercontent.com/65644353/122590437-d6daca00-d061-11eb-9f0d-85e0653f0a76.png)

**Comment by raysan5** [comment]
@nicholasimon Wow! Very nice game! It's a great twist of the classic Snake! 👍😄

You should publish it in https://github.com/raysan5/raylib/discussions/1326
