### ISSUE TITLE
[core] Expose `glfwSetWindowSize` on web (or equivalent)

### ISSUE THREAD

**Issue by nikki93** [raysan5/raylib#1838]
### Issue description

`SetWindowSize` currently [`#if`s-out the call to `glfwSetWindowSize` on web](https://github.com/raysan5/raylib/blob/28093c46a8d264206936d2eb534c56173346020b/src/core.c#L1549-L1555), which makes it hard to create a resizable canvas on web that remains high dpi and unscaled at all sizes. If I remove the `#if` and call it on web it is actually successful at resizing the canvas.

### Environment

Web -- mostly tested on Chrome. Building from Linux, Windows or macOS.

### Issue Screenshot

This is the canvas with the `#if` in place as it is currently in raylib -- you can see all of the rendering getting blurry due to web-level re-scaling:
![raylib-web-resize-orig](https://user-images.githubusercontent.com/49151/122654368-b82b1080-d0ff-11eb-9aa7-96dc01e6a983.gif)

Example of a resizable canvas after I remove the `#if` and add the code from the next section -- the lines and font remain at the same size while the scene itself zooms, with the canvas maintaining dynamic layout vs. the web elements surrounding it:
![raylib-web-resize](https://user-images.githubusercontent.com/49151/122654121-fcb5ac80-d0fd-11eb-8822-dc0e83cbe604.gif)

### Code Example

To achieve the above resizability this is what happens on each frame:
```c
  Vector2 windowSize = { float(GetScreenWidth()), float(GetScreenHeight()) };
  {
#ifdef __EMSCRIPTEN__
    Vector2 canvasSize = {
      float(int(EM_ASM_DOUBLE({
        return window.devicePixelRatio
            * document.querySelector("#canvas").getBoundingClientRect().width;
      }))),
      float(int(EM_ASM_DOUBLE({
        return window.devicePixelRatio
            * document.querySelector("#canvas").getBoundingClientRect().height;
      }))),
    };
    if (windowSize.x != canvasSize.x || windowSize.y != canvasSize.y) {
      SetWindowSize(int(canvasSize.x), int(canvasSize.y));
    }
#endif
  }
  camera.offset = Vector2Scale(windowSize, 0.5);
  camera.zoom = float(windowSize.x) / 800;
```
So -- the scene drawn through `camera` acts as if the screen is 800 units wide at all times. The text is drawn outside camera mode and the line width is divided by the zoom. Exposing `glfwSetWindowSize` allows creating such a dynamically resizable yet non-blurry window.

It's possible this is achievable with the existing raylib API -- but as far as I can tell there isn't a way. `SetConfigFlags(FLAG_WINDOW_RESIZABLE)` didn't lead to any automatic resizing behavior.

**Comment by skylersaleh** [comment]
I filed this pull request since I was running into a similar issue. 

https://github.com/raysan5/raylib/pull/1840

I think it might work for your use case too.

**Comment by raysan5** [comment]
@nikki93 thank you very much for the detailed report and thanks @skylersaleh for the PR. I need some time to review this issue and PR. It could also be related to https://github.com/raysan5/raylib/issues/1241

**Comment by nikki93** [comment]
Thank you both for taking a look!

@raysan5 -- This was the entire diff I needed to then be able to implement resizable windows in web from the app code:
```diff
diff --git a/src/core.c b/src/core.c
index f4bd6acc..eb63fa11 100644
--- a/src/core.c
+++ b/src/core.c
@@ -1444,7 +1444,7 @@ void SetWindowMinSize(int width, int height)
 // TODO: Issues on HighDPI scaling
 void SetWindowSize(int width, int height)
 {
-#if defined(PLATFORM_DESKTOP)
+#if defined(PLATFORM_DESKTOP) || defined(PLATFORM_WEB)
     glfwSetWindowSize(CORE.Window.handle, width, height);
 #endif
 #if defined(PLATFORM_WEB)
```
But I understand if there is a need for some more consistent solution that takes the rest of the API's design into account. @skylersaleh's automatic resizing also would work as long as it uses (or has the option of using) `window.devicePixelRatio` to handle high-dpi cases.

Right now to work around this I have to change the library's code; it would be nice if raylib had a function that exposed the GLFW window handle as a `void *` pointer so user code could use it along with GLFW declarations, if only to temporarily work around such issues until they are addressed upstream.

**Comment by raysan5** [comment]
@nikki93 thanks again for reporting and sending the PR! Is it enough with this PR to let you manage the resizing? If it's enough we can close the issue.

About this:
> Right now to work around this I have to change the library's code; it would be nice if raylib had a function that exposed the GLFW window handle as a void * pointer so user code could use it along with GLFW declarations, if only to temporarily work around such issues until they are addressed upstream.

I exposed (despite uncomplete) `GetWindowHandle()` to get the native Window handle for the current platform, unfortunately I can't expose the GLFW Window because several platforms do not rely on GLFW and I try to keep the API consistent between all platforms.

**Comment by nikki93** [comment]
@raysan5 Sorry for the late response -- yup that PR gives me what I need. And makes sense re: `GetWindowHandle()`. Thank you!
