### ISSUE TITLE
Raylib defaults to integrated graphics, gives worse performance

### ISSUE THREAD

**Issue by bcrooks4** [raysan5/raylib#1844]
Realised performance isn't what it should be for my laptop, then saw this:

INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Intel(R) UHD Graphics 630
INFO:     > Version:  3.3.0 - Build 30.0.100.9670
INFO:     > GLSL:     3.30 - Build 30.0.100.9670

I have an Nvidea card that isn't been used

**Comment by raysan5** [comment]
I'm afraid that's an OS configuration option, external to raylib. It depends on the graphics driver of your OS.

**Comment by bcrooks4** [comment]
Huh sorry about opening this, thankyou for letting me know
