### ISSUE TITLE
[raymath] Feature request for matrix decomposition

### ISSUE THREAD

**Issue by object71** [raysan5/raylib#1850]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I would like to request matrix decomposition function in raylib that would take a single Matrix parameter and return a Transform struct with the rotation, translation and scale of the matrix.

This is a requirement to fix an issue with GLTF animation.

### Code Example

```
RLDEF Transform MatrixDecompose(Matrix value);
```

**Comment by raysan5** [comment]
Hi @object71, function can be added but unfortunately, `Transform` struct is not available in `raymath`, so the function should be something like:
```c
RLDEF void MatrixDecompose(Matrix value, Vector3 *position, Quaternion *rotation, Vector3 *scale);
```
I investigated a bit this issue and it seems getting those parameters is not always possible from a given Matrix. 
Here some related references:

https://docs.microsoft.com/en-us/dotnet/api/system.numerics.matrix4x4.decompose?view=net-5.0
https://stackoverflow.com/questions/27655885/get-position-rotation-and-scale-from-matrix-in-opengl
https://docs.unity3d.com/ScriptReference/Matrix4x4.html
https://gamedev.stackexchange.com/questions/187090/how-to-decompose-a-4x4-trs-transformation-matrix-with-negative-scale
https://pixel.engineer/posts/matrix-decomposition-unity/

**Comment by object71** [comment]
Hmm, well I will need to think of some other way of applying the inverse bone matrix for gltf then :/
I am not that good at math so I decided to request the MatrixDecompose function first.

**Comment by raysan5** [comment]
@object71 I think the best option is using the inverse-transform-matrix: `MatrixInvert()` should work for that.

I'm closing this request for now.
