### ISSUE TITLE
[core] Force Maximized Window with NO Windows Taskbar visible

### ISSUE THREAD

**Issue by nicholasimon** [raysan5/raylib#1852]
When I run a window (not in FullScreen mode) on some systems the Raylib window does not display over the Windows taskbar. I was wondering how to correct this, ie. to force the window to open maximized (on top of everything else) in X:0 and Y:0 position (top left corner) displaying over the Windows taskbar. It is an odd issue as on my usual desktop it works fine and the Raylib window opens on top of (hiding) the taskbar however on my laptop this is not the case and for some reason the Windows Taskbar displays. 

If you have any ideas please let me know

Windows 10

**Comment by raysan5** [comment]
@nicholasimon I have no idea... it seems an OS dependant behaviour...

**Comment by raysan5** [comment]
I'm closing this issue. I'm afraid it's out of raylib control.

**Comment by DiarrheaMcgee** [comment]
Very cool! 🥇
