### ISSUE TITLE
Printing pointer instead of pointer value

### ISSUE THREAD

**Issue by masterex1000** [raysan5/raylib#1854]
In `CompressData()` it looks like a pointer is getting printed instead of the pointer's value. 

Function header:
https://github.com/raysan5/raylib/blob/6f30a19dd7d03a68fc3e39f00e8cd2de0fba95f2/src/core.c#L3023

and a bit later in the function....
https://github.com/raysan5/raylib/blob/6f30a19dd7d03a68fc3e39f00e8cd2de0fba95f2/src/core.c#L3036

Note no `*` in front of `compDataLength`

**Comment by raysan5** [comment]
@masterex1000 Good catch! Feel free to send a PR! 👍😄

**Comment by raysan5** [comment]
Just reviewed it.
