### ISSUE TITLE
[build] Error in templates/simple_game/Makefile.Android

### ISSUE THREAD

**Issue by Azecy** [raysan5/raylib#1855]
I think there is an error in templates/simple_game/Makefile.Android. It looks like "compile_native_app_glue \" should be between line 153 & 154. I barely know what I'm doing, so I apologize if I'm wrong.

**Comment by raysan5** [comment]
@Azecy Mmmh... you are right... but it seems it still works without that target execution... I'll review it...

**Comment by raysan5** [comment]
This file does not exist anymore.
