### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by voloshchu** [raysan5/raylib#1857]
![image](https://user-images.githubusercontent.com/79337911/124029848-40fa5400-d9fe-11eb-912a-58d7b3b3c4af.jpeg)
Hello. Thank you for the lib, but I have some errors.
I'm going to use lib on rpi zero, but this version has install error. 
When I install like 1.9.7 it was without any errors. 
I do everything with your instruction. 
OS raspbian 32, OpenGL is on.

**Comment by mandar1jn** [comment]
It seems like some glfw functions hasn’t been found

**Comment by raysan5** [comment]
Issue not properly checked.
