### ISSUE TITLE
ClosePhysics() function broken in included physac.h file

### ISSUE THREAD

**Issue by cophfe** [raysan5/raylib#1861]
This issue only occurs in the version of physac.h that was modified by raysan5, aka the current version on github.
When testing physac, I noticed using the ClosePhysics function threw an access violation exception. I checked to see what was wrong, and the problem stems from line 894. The same issue happens again on line 901.
Here is the part that causes the exception:
```c++
for (unsigned int i = physicsManifoldsCount - 1; i >= 0; i--)
            DestroyPhysicsManifold(contacts[i]);
```
The problem is the use of an unsigned int. In tandem with the use of >= 0, it means the for loop should go on forever (or until it runs into an error) since an unsigned int can never have a value under 0. i is set to 4294967295 when it should have been set to -1, and the program attempts to access some ram it shouldn't be. 

This will be a problem whenever there is a physics body and ClosePhysics() is used. I just used a (very, very slightly) modified version of the example code here:
https://www.raylib.com/examples/web/physics/loader.html?name=physics_demo

![image](https://user-images.githubusercontent.com/50863062/124377710-a85f1f00-dcf0-11eb-8ff0-095bb8427e0f.png)

**Comment by raysan5** [comment]
@cophfe thanks for reporting! Just pushed a commit to fix it! I was convinced this issue was already solved... maybe I solved it in some other place...
