### ISSUE TITLE
[textures] ImageDrawLine only covers one octant

### ISSUE THREAD

**Issue by Buhlean** [raysan5/raylib#1873]
### Issue description

ImageDrawLine only covers the octant where `dx > dy && dx > 0 && dy > 0`.

### Environment

Win32 (issue is platform agnostic)

### Issue Screenshot

![graph](https://user-images.githubusercontent.com/63983202/125533699-00ea2af5-0c26-41e8-a6cf-64f1714dae96.png)

### Code Example

This code only draws three of the 16 lines tested for.
 (tests 1 for each octant + 1 for each dividing line)
```
#include "raylib.h"
const int size = 121, mid = 60, quart = 30;
void DrawFromMidToHere(Image* image, int x, int y){
    ImageDrawLine(image, mid, mid, x, y, BLACK); 
}
int main(){
    Image im = GenImageColor(size, size, WHITE);
    DrawFromMidToHere(&im,size-1,size-1);
    DrawFromMidToHere(&im,size-1,0);
    DrawFromMidToHere(&im,0,0);
    DrawFromMidToHere(&im,0,size-1);
    for(int i = 0; i<2; i++){
        DrawFromMidToHere(&im,i*size, mid - quart);
        DrawFromMidToHere(&im,i*size, mid);
        DrawFromMidToHere(&im,i*size, mid + quart);
    }
    for(int i = 0; i<2; i++){
        DrawFromMidToHere(&im,mid - quart, i*size);
        DrawFromMidToHere(&im,mid,         i*size);
        DrawFromMidToHere(&im,mid + quart, i*size);
    }
    ExportImage(im, "./graph.png");
    return 0;
}
```

**Comment by raysan5** [comment]
@Buhlean As far as we are drawing into an Image, won't it be easier to just recalculate required origin-destination to fit in first quadrant?
