### ISSUE TITLE
[module] Unresolved External Symbol timeBeginPeriod

### ISSUE THREAD

**Issue by bardiabahrampour** [raysan5/raylib#1875]
### Issue description

so I downloaded the 64 bit version of raylib and added it to my visual studio project, when i tried to build it , it gave me a linking error "Unresolved External Symbol timeBeginPeriod"
it only built successfully when i used the x86 version, apparently linking "winmm.lib" fixes the issue but this is not mentioned anywhere in the examples 

### Environment
Windows 10,Visual Studio 2019, GTX 1050 ti
### Code Example

`#include <raylib>
int main(){
    int width{800};
    int height{600};
     InitWindow(width,height,"test");
     SetTargetFPS(60);
     while(!WindowShouldClose()){
     BeginDrawing();
     ClearBackground(RAYWHITE);
      DrawText("hello");
     EndDrawing();
}
CloseWindow();
return 0;
}`

**Comment by raysan5** [comment]
This requirement is listed on [raylib Wiki dependencies](https://github.com/raysan5/raylib/wiki/raylib-dependencies) and also on Makefile. `WinMM` is a system library.
