### ISSUE TITLE
[core] FPS hard set to 60 when VSYNC turned back on

### ISSUE THREAD

**Issue by jmorel33** [raysan5/raylib#1893]
I develop on monitors with a refresh rate of 75 fps, and might not be the only one not at 60 fps.

That said, when I launch my app with VSYNC on, it shows an FPS of 75, which is perfect.
If I turn VSYNC off, the fps goes pass the thousand, as is expected.

Now when I turn VSYNC back on, what happens is, the screen goes black for about a second or so, then shows up again, my app continues normally, but now the the screen is sync'd to 60 fps..

What I suspect is happening is that it did not remember my monitor fps of 75 and went back to a RayLib default fps of 60, and this is why the screen went black as it literally changed the display settings to 60 fps.

Ideally turning VSYNC back on should leave the FPS at the same value as what the monitor screen resolution is.

Also note the subsequent times I turn VSYNC off and back on, the screen will not go black, and the fps will still switch between 1000+ then back to 60 at VSYNC on.

**Comment by jmorel33** [comment]
After some observation , the issue seems to be buried in glfw, if anyone could confirm.

**Comment by jmorel33** [comment]
`05723: *
05724: * @remark Some GPU drivers do not honor the requested swap interval, either
05725: * because of a user setting that overrides the application's request or due to
05726: * bugs in the driver.
05727: *
`

I'd have a hard time believing the GTX1070 latest Nvidia drivers on a Windows 10 platform are at fault...

**Comment by raysan5** [comment]
@jmorel33 I'm afraid this issue is out of control of raylib, as you investigated, it sounds like a driver/OS specific issue.

**Comment by jmorel33** [comment]
> @jmorel33 I'm afraid this issue is out of control of raylib, as you investigated, it sounds like a driver/OS specific issue.

I am unsure if it is driver / os or glfw....  It could be GLFW, but I know it is not RayLib
