### ISSUE TITLE
Compile fails on Visual Studio

### ISSUE THREAD

**Issue by KraXarN** [raysan5/raylib#190]
Firstly, it fails to compile due to `invalid numeric argument '/Wno-missing-braces'` and when removing it, it compiles with a lot of errors instead.
Running VS 2015.
Thanks! 😄 

```
Error   C2133   'extList': unknown size rlgl.c  1059    
Error   C2371   'IsAudioDeviceReady': redefinition; different basic types   audio.c 236 
Error   C2371   'IsMusicPlaying': redefinition; different basic types   audio.c 1058    
Error   C2371   'IsSoundPlaying': redefinition; different basic types   audio.c 799 
Error   C2133   'log': unknown size rlgl.c  2888    
Error   C2133   'log': unknown size rlgl.c  2909    
Error   C2133   'log': unknown size rlgl.c  2947    
Error   C2466   cannot allocate an array of constant size 0 rlgl.c  1059    
Error   C2466   cannot allocate an array of constant size 0 rlgl.c  2888    
Error   C2466   cannot allocate an array of constant size 0 rlgl.c  2909    
Error   C2466   cannot allocate an array of constant size 0 rlgl.c  2947    
Error   C2057   expected constant expression    rlgl.c  1059    
Error   C2057   expected constant expression    rlgl.c  2888    
Error   C2057   expected constant expression    rlgl.c  2909    
Error   C2057   expected constant expression    rlgl.c  2947    
Error   C2059   syntax error: ')'   jar_xm.h    1438    
Error   C2059   syntax error: ','   jar_xm.h    1438    
Error   C2059   syntax error: ';'   jar_xm.h    1438    
Error   C2061   syntax error: identifier 'a'    jar_xm.h    1438    
Error   C2146   syntax error: missing ')' before identifier 'a' jar_xm.h    1438
```

**Comment by raysan5** [comment]
Hi @KraXarN!

Which version are you trying to compile? Did you try with latest [develop branch](https://github.com/raysan5/raylib/tree/develop)?

I just tried the included `project/vs2015/raylib.sln`  it compiles ok...

Please, let me know if it works! :)

**Comment by KraXarN** [comment]
Downloaded the version from the releases page which did not not include the project file. The master file works fine, but the Release version won't compile.

**Comment by raysan5** [comment]
Thanks for the feedback @KraXarN! I'm working on version 1.6 to be released next month, I'll make sure it works with Visual Studio 2015. :)

**Comment by KraXarN** [comment]
Thanks! 😹

**Comment by KraXarN** [comment]
Update since I noticed 1.6 is out. Now compiles just fine 😺

**Comment by raysan5** [comment]
Hey @KraXarN! Actually raylib 1.6 is not published officially yet, I just updated the github master branch but still some things to do... I'm also working in the raylib Windows installer, webpage update, new examples, etc.

About rREM, it's very outdated, need to completely review that tool; fortunately, it's planned with high priority for next raylib version... I think right now it's not prepared to deal with XM files, sorry... just added a bug to track it: https://github.com/raysan5/raylib/issues/193

**Comment by KraXarN** [comment]
Alright, would be nice to get some lua examples as well. I know the code examples were ported over, but how to actually use them would be nice.

About rREM, compression on .xm files isn't really necessary, since they are so small anyway, but still. Also, to get a Linux version would also be nice.
