### ISSUE TITLE
[build] vcpkg instructions seem wrong

### ISSUE THREAD

**Issue by mandar1jn** [raysan5/raylib#1902]
I tried using the instructions to install raylib using vcpkg. The clone and calling the sh file go fine. After that it just says vcpkg is not a file or folder

**Comment by raysan5** [comment]
@mandar1jn Unfortunately I don't maintain that build/package system. Let's see if some user could help with that.

**Comment by ApianbelleDev** [comment]
follow these instructions https://gamefromscratch.com/vcpkg-cpp-easy-mode-step-by-step-tutorial/

@raysan5 if OP has success with this method, have the person who maintains it add these as the build instructions, or just link this tutorial.

**Comment by raysan5** [comment]
@ApianbelleDev Thanks for the link. I don't know who is maintaining `vcpck` but if it doesn't work I will just remove it.

**Comment by cajun-code** [comment]
@raysan5 I checked the VCPKG install process and project config and all works fine.  
@mandar1jn It looks like you are trying to run the VCPKG command from your project directory. You need to add it to the path before you can use it that way.  If you can please post the steps you were using I can provide more information.

**Comment by mandar1jn** [comment]
@cajun-code I’ll send them once I’m behind my pc. Github doesn’t like mobile at the moment. Also, I wasn’t trying to run it from the project directory. I used cd to navigate into the vcpkg directory and tried to run it from there

**Comment by mandar1jn** [comment]
@raysan5 @cajun-code The command run by the workflow is:
``git clone Microsoft/vcpkg.git && cd vcpkg && ./bootstrap-vcpkg.sh && vcpkg integrate install && vcpkg install raylib``. I get the same result when placing ./ before vcpkg integrate install

**Comment by mandar1jn** [comment]
`Cloning into 'vcpkg'...
Updating files:  15% (1230/7906)
Updating files:  16% (1265/7906)
Updating files:  17% (1345/7906)
Updating files:  18% (1424/7906)
Updating files:  19% (1503/7906)
Updating files:  20% (1582/7906)
Updating files:  21% (1661/7906)
Updating files:  22% (1740/7906)
Updating files:  23% (1819/7906)
Updating files:  24% (1898/7906)
Updating files:  25% (1977/7906)
Updating files:  26% (2056/7906)
Updating files:  27% (2135/7906)
Updating files:  28% (2214/7906)
Updating files:  29% (2293/7906)
Updating files:  30% (2372/7906)
Updating files:  31% (2451/7906)
Updating files:  31% (2512/7906)
Updating files:  32% (2530/7906)
Updating files:  33% (2609/7906)
Updating files:  34% (2689/7906)
Updating files:  35% (2768/7906)
Updating files:  36% (2847/7906)
Updating files:  37% (2926/7906)
Updating files:  38% (3005/7906)
Updating files:  39% (3084/7906)
Updating files:  40% (3163/7906)
Updating files:  41% (3242/7906)
Updating files:  42% (3321/7906)
Updating files:  43% (3400/7906)
Updating files:  44% (3479/7906)
Updating files:  45% (3558/7906)
Updating files:  46% (3637/7906)
Updating files:  47% (3716/7906)
Updating files:  47% (3786/7906)
Updating files:  48% (3795/7906)
Updating files:  49% (3874/7906)
Updating files:  50% (3953/7906)
Updating files:  51% (4033/7906)
Updating files:  52% (4112/7906)
Updating files:  53% (4191/7906)
Updating files:  54% (4270/7906)
Updating files:  55% (4349/7906)
Updating files:  56% (4428/7906)
Updating files:  57% (4507/7906)
Updating files:  58% (4586/7906)
Updating files:  59% (4665/7906)
Updating files:  60% (4744/7906)
Updating files:  61% (4823/7906)
Updating files:  62% (4902/7906)
Updating files:  62% (4922/7906)
Updating files:  63% (4981/7906)
Updating files:  64% (5060/7906)
Updating files:  65% (5139/7906)
Updating files:  66% (5218/7906)
Updating files:  67% (5298/7906)
Updating files:  68% (5377/7906)
Updating files:  69% (5456/7906)
Updating files:  70% (5535/7906)
Updating files:  71% (5614/7906)
Updating files:  72% (5693/7906)
Updating files:  73% (5772/7906)
Updating files:  74% (5851/7906)
Updating files:  75% (5930/7906)
Updating files:  76% (6009/7906)
Updating files:  77% (6088/7906)
Updating files:  77% (6154/7906)
Updating files:  78% (6167/7906)
Updating files:  79% (6246/7906)
Updating files:  80% (6325/7906)
Updating files:  81% (6404/7906)
Updating files:  82% (6483/7906)
Updating files:  83% (6562/7906)
Updating files:  84% (6642/7906)
Updating files:  85% (6721/7906)
Updating files:  86% (6800/7906)
Updating files:  87% (6879/7906)
Updating files:  88% (6958/7906)
Updating files:  89% (7037/7906)
Updating files:  90% (7116/7906)
Updating files:  91% (7195/7906)
Updating files:  92% (7274/7906)
Updating files:  93% (7353/7906)
Updating files:  94% (7432/7906)
Updating files:  95% (7511/7906)
Updating files:  96% (7590/7906)
Updating files:  96% (7632/7906)
Updating files:  97% (7669/7906)
Updating files:  98% (7748/7906)
Updating files:  99% (7827/7906)
Updating files: 100% (7906/7906)
Updating files: 100% (7906/7906), done.
Microsoft Windows [Version 10.0.17763.2061]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\a\_temp\5fb9264f-1c05-49ad-97d2-7b9f1a599919: line 1: vcpkg: command not found
D:\a\Terri-Fried\Terri-Fried\vcpkg>
Error: Process completed with exit code 127.`

**Comment by mandar1jn** [comment]
@raysan5 I’m not able to. This is running in a windows-latest github workflow. After every run statement it returns to the root directory. Also something that I forgot to add: all this code is ram via msys. I just realised that I might need to run the bat file using cmd instead

**Comment by raysan5** [comment]
@mandar1jn It seems the issue could be related to your environment conditions and not `vcpck` itself. I'm closing this issue for now.
