### ISSUE TITLE
[raylib] add support for msys/mingw in makefile

### ISSUE THREAD

**Issue by mandar1jn** [raysan5/raylib#1905]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [ ] My code has no errors or misuse of raylib

### Issue description

The comments in the makefile say that uname is not a command in msys, but I tried it and does exist.

### Environment

Latest windows version and most recent version of msys/mingw (fresh install)

**Comment by mandar1jn** [comment]
I tried to get it to work myself but I'm not so good with Makefiles and failed horribly

**Comment by orcmid** [comment]
@mandar1jn, out of curiosity:

 1. Are you using `msys/mingw` for other purposes than relying on raylib?

 2. Do you have an IDE in mind (e.g., VS Code)? 

I'm asking because using the `raylib_installer...mingw.exe` might be easier to use for a clean setup.

**Comment by mandar1jn** [comment]
@orcmid I don't have a big integrated ssd in my laptop so I installed msys on an external drive. While using the installer I can't select an install path. I also want to use the default makefile. So installing it on windows on an external drive isn't possible

**Comment by raysan5** [comment]
@orcmid The installed folder is completely portable and self-contained, you can just cut-paste the `C:/raylib` directory wherever you want. You will need to change paths anyway to point to your installation folder.

**Comment by orcmid** [comment]
> @orcmid The installed folder is completely portable and self-contained, you can just cut-paste the `C:/raylib` directory wherever you want. You will need to change paths anyway to point to your installation folder.

I need to try that.  In the course, there were warnings about that breaking templates supplied in the course.  I am not so certain about that.  I did put `c:\raylib\mingw\bin` in my search path but don't know that was necessary for the course.  I will move it and do both, then see if VSCode Terminal Configure Build finds the `g++.exe` that they seem to want students to use.
