### ISSUE TITLE
[models] LoadMaterial (LoadMTL) SIGSEGV - sscanf to NULL

### ISSUE THREAD

**Issue by marcin648** [raysan5/raylib#191]
In LoadMTL function variable mapFileName is initialized to NULL
`char *mapFileName = NULL;`

The next function sscanf is executed
`sscanf(buffer, "newmtl %s", mapFileName);`

And generate SIGSEGV

RayLib v1.6.0 build on TDM-GCC-32 5.1.0 (Windows)

**Comment by raysan5** [comment]
Hi @marcin648! Thank you very much for pointing this issue! I'll take care of it ASAP.

**Comment by raysan5** [comment]
Corrected on commit https://github.com/raysan5/raylib/commit/42452378925e3b1d407a33084cd8cf0495632ee8

By the way, `LoadOBJ()` and `LoadMTL()` need further review and testing, specially `LoadMTL()`...
