### ISSUE TITLE
[rlgl] Batch elements overflow

### ISSUE THREAD

**Issue by dginu85** [raysan5/raylib#1910]
Hello after update RayLib my program not work.

INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
WARNING: TEXTURE: Failed to load texture
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
WARNING: TEXTURE: Failed to load texture
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
WARNING: TEXTURE: Failed to load texture
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
WARNING: TEXTURE: Failed to load texture
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
WARNING: TEXTURE: Failed to load texture
INFO: Initializing raylib 3.5
INFO: DISPLAY: No graphic card set, trying card1
INFO: DISPLAY: Selected DRM connector mode FIXED_MODE (800x480p@60)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 800 x 480
INFO:     > Render size:  800 x 480
INFO:     > Screen size:  800 x 480
INFO:     > Viewport offsets: 0, 0
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: V3D 4.2
INFO:     > Version:  OpenGL ES 3.1 Mesa 19.3.2
INFO:     > GLSL:     OpenGL ES GLSL ES 3.10
INFO: GL: Supported extensions count: 76
INFO: GL: VAO extension detected, VAO functions initialized successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: ETC1 compressed textures supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: RPI: Opening input device: /dev/input/event0 (multitouch touchscreen )
WARNING: RPI: Failed to open Gamepad device, no gamepad available
WARNING: RPI: Failed to change keyboard mode (SSH keyboard?)
INFO: TIMER: Target time per frame: 16.667 milliseconds
'lo': 127.0.0.1
'eth0': 192.168.0.190
UI TEST 
Load From File Assets/img/cruscotto.png
INFO: FILEIO: [Assets/img/cruscotto.png] File loaded successfully
INFO: IMAGE: [Assets/img/cruscotto.png] Data loaded successfully (800x480)
INFO: TEXTURE: [ID 3] Texture created successfully (800x480 - 1 mipmaps)
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
INFO: TEXTURE: [ID 4] Texture created successfully (256x256 - 1 mipmaps)
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
INFO: TEXTURE: [ID 5] Texture created successfully (256x256 - 1 mipmaps)
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
INFO: TEXTURE: [ID 6] Texture created successfully (1024x1024 - 1 mipmaps)
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
INFO: TEXTURE: [ID 7] Texture created successfully (512x512 - 1 mipmaps)
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
INFO: TEXTURE: [ID 8] Texture created successfully (512x512 - 1 mipmaps)
INFO: FILEIO: [Assets/font/DejaVuSansMono.ttf] File loaded successfully
INFO: TEXTURE: [ID 9] Texture created successfully (512x512 - 1 mipmaps)
ERROR: RLGL: Batch elements overflow

**Comment by dginu85** [comment]
I find cause **DrawRing**.

**Comment by raysan5** [comment]
@dginu85 Please, could you provide a minimal example illustrating the issue?

**Comment by dginu85** [comment]
Platform RPI4 DRM
```
BeginDrawing();
DrawRing({400, 400}, /*INTERNO*/ 190, /*ESTERNO*/270, /*PAR*/map(VAL, 0, 100, 270, 90), 270, 100, Fade({0, 139, 240}, 0.9));
EndDrawing();
```

**Comment by raysan5** [comment]
@dginu85 Please, could you provide a complete example file to test? That line seems to be using some custom functions.

**Comment by dginu85** [comment]
BeginDrawing();
DrawRing({400, 400}, 190,270, 100, 270, 100,  Fade(MAROON, 0.3));
EndDrawing();

**Comment by raysan5** [comment]
@dginu85 that piece of code does not work in C99, are you using C++?

**Comment by dginu85** [comment]
YES

**Comment by raysan5** [comment]
@dginu85 That piece of code works ok for me. I can't reproduce.

**Comment by raysan5** [comment]
You can try review `rlCheckRenderBatchLimit(4*segments);` on `DrawRing()` on `shapes.c` and increase that value, just to make sure the issue is on the buffer limits for that draw call.

**Comment by dginu85** [comment]
have you tried on raspbery?

**Comment by raysan5** [comment]
@dginu85 I tried on desktop using RPI batch limits configuration. If it fails only on RPI DRM, that function is probably not the issue.

**Comment by dginu85** [comment]
Hello @raysan5 today i compile raylib in my desktop.
**I try to start my application**
external/glfw/src/input.c:516: glfwSetInputMode: Assertion `window != NULL' failed

**To understand where I was wrong, I decided to build examples**
make: *** [Makefile:525: shapes/shapes_draw_ring] Errore 1
linuxstation:~/Scrivania/Librerie/raylib/examples$

**Comment by raysan5** [comment]
@dginu85 first issue is related to GLFW library but without more context it's very difficult to know the reason.

Examples issue is related to some changes I did to raygui yesterday.
