### ISSUE TITLE
[rMem] Seg fault after free operations

### ISSUE THREAD

**Issue by graducan** [raysan5/raylib#1913]
In the below function there is a case when head is the same with the tail, therefore this loop won't end if `node->size < byte`

```
static MemNode *__FindMemNode(AllocList *const list, const size_t bytes)
{
    for (MemNode *node = list->head; node != NULL; node = node->next)
    {
        if (node->size < bytes) continue;
        // close in size - reduce fragmentation by not splitting.
        else if (node->size <= bytes + MEM_SPLIT_THRESHOLD) return __RemoveMemNode(list, node);
        else return __SplitMemNode(node, bytes);
    }
    return NULL;
}
```

**Comment by graducan** [comment]
@assyrianic @raysan5

**Comment by assyrianic** [comment]
how true is that when the the freelist isn't circular?

**Comment by graducan** [comment]
@assyrianic actually node is the same with node->next. What is the point of tail if the list is not circular?

**Comment by raysan5** [comment]
@assyrianic @graducan could this issue be closed?

**Comment by graducan** [comment]
@raysan5 @assyrianic Not yet please, maybe I'll find a small scenario to reproduce this..give me 1 more week

**Comment by raysan5** [comment]
@graducan Ok, no problem, take your time.

**Comment by graducan** [comment]
I think the infinite loop might be the result of a wrong usage from my side..But managed to find a seg fault.

```
            if (( uintptr_t )iter == mempool->arena.offs)
            {
                mempool->arena.offs += iter->size;
                __RemoveMemNode(list, iter);
                iter = list->head;
            }
```

1. After removing a memory node the `list->head` may become `NULL`, so we need a check there to get rid of the seg fault.
2. @assyrianic please help me understand why in the `MemPoolFree` function we call `__InsertMemNode` to remove the node and not `__RemoveMemNode`? It is a bit confusing and hackish IMHO..

**Comment by assyrianic** [comment]
Because in `MemPoolFree`, when a node cannot be merged back into the memory buffer or coalesced with another node, it has to be placed into a free list, either a bucket or large memory freelist.
`__RemoveMemNode` is used when we found a way to coalesce nodes together or merge a node back into the memory buffer.

**Comment by graducan** [comment]
#1925
