### ISSUE TITLE
[models] `DrawGrid()` limitations / Improvements

### ISSUE THREAD

**Issue by 630Studios** [raysan5/raylib#1916]
### Issue description

DrawAxis only draws a grid on the X/Z plane (Y axis facing), which is not entirely useful if your vertical (up/down world axis) is not the default Y axis. Even if Y is your default Up/Down axis, there are plenty of scenarios where you may wish to draw a grid on one of the other axis.

Additionally DrawGrid provides no color options for the grid itself, which can again limit the usefulness of the function depending on the background color of your scene.

Proposing DrawGrid is changed to DrawYAxisGrid, as well as the following functions to be added. Ex variants, following the RayLib paradigm, extend the parameters and allow the user to specify the color

DrawYAxisGrid
DrawYAxisGridEx
DrawXAxisGrid
DrawXAxisGridEx
DrawZAxisGrid
DrawZAxisGridEx

I have these functions done, if this is something that is wanted I will put in a PR.

**Comment by raysan5** [comment]
@630Studios Sorry, no plans to add those extra functions, `DrawGrid()` is just a quick refernce for most users, for specific use-case users can implement their custom versions using `DrawLine3D()`.

**Comment by 630Studios** [comment]
Then why have DrawGrid in the first place, especially when it assumes a specific "Up" axis?

Your decisions on what to include, and not include seem entirely arbitrary.

**Comment by raysan5** [comment]
@630Studios Yes, it's my decision.

**Comment by 630Studios** [comment]
Yes, it is, but it doesn't mean I cant wonder what your reasoning is or if it is grounded in some sort of actual logic.

**Comment by raysan5** [comment]
> DrawGrid() is just a quick reference for most users, for specific use-case users can implement their custom versions using DrawLine3D().

**Comment by raysan5** [comment]
> DrawGrid() is just a quick reference for most user

It makes sense for me, I'm afraid you don't share my same point of view but it's ok.

**Comment by 630Studios** [comment]
By that logic, shouldn't it then be an example, and not part of RayLib?
