### ISSUE TITLE
[Raylib] GetPixelDataSize

### ISSUE THREAD

**Issue by 630Studios** [raysan5/raylib#1932]
### Issue description

GetPixelDataSize Does not calculate a proper data size for compressed texture formats where the per pixel data size is < 1 byte.

**Comment by raysan5** [comment]
This issue has already been discussed on Discord, no plans to review it for the moment.

Just for clarification for anyone finding this issue:

`GetPixelDataSize()` could report wrong values in case a **compressed texture format is used** and the textures are not power-of-two squared in size.
