### ISSUE TITLE
Conflicting use of CharInfo in raygui.h

### ISSUE THREAD

**Issue by orcmid** [raysan5/raylib#1939]
### Discussed in https://github.com/raysan5/raylib/discussions/1938

<div type='discussions-op-text'>

<sup>Originally posted by **Boxstop** August 19, 2021</sup>
`/raylib/src/extras/raygui.h:2893:31: error: ‘CharInfo’ undeclared (first use in this function); did you mean ‘BoneInfo’?
                 font.chars = (CharInfo *)RAYGUI_CALLOC(font.charsCount, sizeof(CharInfo));
                               ^~~~~~~~
                               BoneInfo
`
it says change the Charinfo into a Bone info for some odd reason</div>

It's a guess, not a suggestion.

INITIAL ANALYSIS:

`CharInfo` is a **struct** type that is only defined if `RAYGUI_STANDALONE` is set. (Found by searching `raygui.h` for `CharInfo` occurrences.)

There is no `CharInfo` defined or used in `raylib.h` on the current master branch , although there are a variety of *Info thingies, including `BoneInfo`. It looks like this should be treated as a bug because of that contradiction. Ramon's comments are concerning :).  This smells a lot like the `Font.GlyphInfo` in raylib.h` though.

**Comment by raysan5** [comment]
@orcmid thanks for reporting! yeah, that struct was renamed some days ago for consistency with internal data, I'll review it asap!

**Comment by raysan5** [comment]
@orcmid `raygui` was already reviewed in https://github.com/raysan5/raygui, I also updated it on raylib/src/extras
