### ISSUE TITLE
[text] DrawTextRec() could not be found

### ISSUE THREAD

**Issue by ashtencodes** [raysan5/raylib#1942]
Please, before submitting a new issue verify and check:

[X ] I tested it on latest raylib version from master branch
[X ] I checked there is no similar issue already reported
[X ] My code has no errors or misuse of raylib

### Issue description

When building the raylib library with cmake, and error is generated halting the build. The error declares DrawTexRec as an implicitly declared function within the raygui.h file.

### Environment

Issue experienced on Ubuntu 20.04 VM running on VirtualBox. OpenGL version: 3.1 Mesa 21.0.3 GPU: RX580

### Issue Screenshot

![unknown](https://user-images.githubusercontent.com/82536552/130312061-5c5a06dc-4cd2-4acd-bb54-db94f253289c.png)

### Code Example

Error occurs when following the Linux Cmake installation [guide](https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux).

git clone https://github.com/raysan5/raylib.git raylib
cd raylib
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make 
sudo make install

**Comment by raysan5** [comment]
@ashtencodes thanks for reporting! this is a known issue, that function was removed some days ago.

**Comment by raysan5** [comment]
I'm closing this issue. It will be updated with a `raygui` update.
