### ISSUE TITLE
[core] [macOS] Can't get scroll wheel value while shift is held

### ISSUE THREAD

**Issue by Paperdomo101** [raysan5/raylib#1948]
### Issue description
`GetMouseWheelMove()` returns 0 when scrolling if the Shift key is held down. This is likely because MacOS interprets shift+scroll as horizontal scrolling. 
 
### Environment
MacOS 10.14 Mojave 

### Code Example
```C
float scroll = GetMouseWheelMove();
// if shift is held, 'scroll' will be zero even if the mousewheel is being moved
```

### Possible Solutions
1) Detect if a horizontal scroll is being performed and return that instead of the standard vertical scroll
2) Add a `GetMouseWheelMoveV()` function that returns a Vector2 including vertical and horizontal scrolling.

**Comment by raysan5** [comment]
@Paperdomo101 Solution `1.` applied in latest commit. Feel free to check if it works.

**Comment by Paperdomo101** [comment]
@raysan5 Works like a charm, thanks a million Ray!
