### ISSUE TITLE
[examples] Several examples fail to compile.

### ISSUE THREAD

**Issue by juniper-dusk** [raysan5/raylib#1951]
### Issue description

Tried to compile raylib with cmake on Linux from the latest master branch. It appears the most recent commit is broken. Attached below is one example that failed to compile.

### Environment

Platform: Linux
OS: Ubuntu 20.04
OpenGL: 3.1 Mesa 20.0.8
GPU: RTX 2070 Super

### Issue Screenshot

![image](https://user-images.githubusercontent.com/87779548/130671707-ef52720c-f7d9-4916-ad87-4bc96a81ad3d.png)

### Code Example

From core.c. Appears one of the two (core/examples) is out of date.

```
// Wave, audio wave data
typedef struct Wave {
    unsigned int frameCount;    // Total number of frames (considering channels)
    unsigned int sampleRate;    // Frequency (samples per second)
    unsigned int sampleSize;    // Bit depth (bits per sample): 8, 16, 32 (24 not supported)
    unsigned int channels;      // Number of channels (1-mono, 2-stereo, ...)
    void *data;                 // Buffer data pointer
} Wave;
```

**Comment by raysan5** [comment]
@juniper-dusk thanks for reporting! yeah, some latest changes broke some examples, I'll review them asap!

**Comment by raysan5** [comment]
Updated example, it should work now.
