### ISSUE TITLE
[core] Multitouch doesn't support more than two touch points

### ISSUE THREAD

**Issue by skylersaleh** [raysan5/raylib#1960]
Please, before submitting a new issue verify and check:

 - [Y] I tested it on latest raylib version from master branch
 - [Y] I checked there is no similar issue already reported
 - [Y] My code has no errors or misuse of raylib

### Issue description

The web build of RayLib doesn't seem to be tracking multitouch for more than two touch points correctly. Touch points beyond the second are not tracked, and when you tap a third finger it acts like you are tapping on the first touchpoint (interrupting the tracking of it). 

This is problematic in my GameBoy emulator use case because some games require pressing multiple buttons (such as A+B+Start+Select to save in LoZ Links Awakening), which can not be input with only two touch points on the on screen controller. 

### Environment

Reproducible on both the latest iOS and Android OS. 

### Code Example

This can be reproduced on the multitouch example on https://www.raylib.com/examples/web/core/loader.html?name=core_input_multitouch

**Comment by raysan5** [comment]
@skylersaleh It should work know, please report if it still fails.
