### ISSUE TITLE
[gestures] Pinch In and Pinch Out are messy

### ISSUE THREAD

**Issue by SAOMDVN** [raysan5/raylib#1963]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

[Input Gestures Example](https://github.com/raysan5/raylib/blob/master/examples/core/core_input_gestures.c) failed to recognise Pinch in and Pinch out, in some cases one appear instead of the expected other results, in other cases both are logged even when only one action was performed

### Environment

Happened on HTML5, Safari, iPhone X, iOS 14.4
OpenGL ES 2.0

**Comment by raysan5** [comment]
I don't have the required hardware/environment to solve this issue. Feel free to send me the required hardware. Closing for now.

**Comment by raysan5** [comment]
@ubkp thank you very much for taking care of this issue!

**Comment by SAOMDVN** [comment]
@ubkp Thank you a lot!
