### ISSUE TITLE
[core] CLI Window launching with built exe - VS2019

### ISSUE THREAD

**Issue by killkong1211** [raysan5/raylib#1965]
Hey this is probably something really simple I'm overlooking but can't see it mentioned elsewhere.
Using VS2019, have built the core_basic_window.c example, and when I launch it I'm getting a CLI window appear showing the below code.
Just wondering how I prevent that CLI window from appearing.

```INFO: Initializing raylib 4.0-dev
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 2560 x 1440
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 399
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 471.11
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: [ID 2] Default font texture loaded successfully
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

**Comment by MrDiver** [comment]
So the Log you are seeing is just the information printed by several `TRACELOG` calls in raylib. You can set the log level for your application with `SetTraceLogLevel(LOG LEVEL)` where the log level can be one of the options presented in this enum
https://github.com/raysan5/raylib/blob/68bcfa119243e716eaf00ffe521d0358c084b74f/src/raylib.h#L505-L514

As for deactivating your console window, it's specific to Visual Studio and you should be able to deactivate it if you really wanted to. But normally you want to have the console window to see the standard output of your application.

If you launch the application itself (the executable located in the build folder after building it with VS) then you shouldn't get the terminal as far as I know.

**Comment by killkong1211** [comment]
The odd part is that I was running the executable in the build folder independent of VS, I even tried moving it out of the build folder thinking the location may have been coupling it to VS, but it still called the log window.

**Comment by MrDiver** [comment]
Have you compiled the application in release mode? Visual Studio automatically adds the terminal if you compile in debug mode. Just search in your project settings for the build mode or use the dropdown on the compile menu. But this only related to Visual Studio. You should check the project settings to make sure everything is the way you want it to.

**Comment by killkong1211** [comment]
Yep I can confirm it was compiled as release
Couldn't compile in debug when I tried so I built as release

**Comment by raysan5** [comment]
Here more info: https://stackoverflow.com/questions/2139637/hide-console-of-windows-application
