### ISSUE TITLE
[module] Calling LoadModule with a directory seg faults

### ISSUE THREAD

**Issue by xavierzwirtz** [raysan5/raylib#1971]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [ ] My code has no errors or misuse of raylib

### Issue description

Calling `LoadModel` with a directory path segfaults without a good error message. 

### Environment

NixOS, raylib git commit 9ff8ad853c77453768c59b5f9ae5206ec63f1bdb

### Code Example

```
LoadModel("dir")
```

**Comment by xavierzwirtz** [comment]
Actually not sure this is the issue now, closing till I have a better report.

**Comment by MrDiver** [comment]
There are some issues with file loading, I might take a look at it later. But I think it is not to do with `LoadModel` itself and lies deeper in the code.

**Comment by xavierzwirtz** [comment]
I am now thinking this might have to do with the fact that I am calling out to raylib from chez scheme, I would ignore this issue.
