### ISSUE TITLE
[core] Support for AMotionEvent_getPointerId

### ISSUE THREAD

**Issue by rmn20** [raysan5/raylib#1972]
I checked the raylib source code and it looks like there are no alternatives for this function, although this function is necessary for some control schemes. For example, you can't create a control scheme in which pointer pressed on the left side of the screen would move the player, while pointer pressed on the right side of the screen would rotate the camera.

**Comment by MrDiver** [comment]
Well, it is possible to make that. If you have looked at the [Multitouch example](https://github.com/raysan5/raylib/blob/master/examples/core/core_input_multitouch.c), you can just get the position and iterate over the inputs.
https://github.com/raysan5/raylib/blob/master/src/core.c#L3532

Just be a little creative with how you use the functions provided.

**Comment by rmn20** [comment]
I think you are confusing the id and the index of the pointer. Read more here: stackoverflow.com/questions/22434036/pointerindex-versus-id-in-android

You can't create this control scheme without pointer IDs, since you need to know the position of the pointer press and the previous position of the pointer, but the pointer indexes change every time the pointers is pressed or released so you can't store these positions. You can emulate pointer IDs, but it won't be accurate, and anyway, its weird to do this when you have a specific function for this in the api.

**Comment by raysan5** [comment]
> For example, you can't create a control scheme in which pointer pressed on the left side of the screen would move the player, while pointer pressed on the right side of the screen would rotate the camera.

Is it possible to just check the touch position to do that?

**Comment by rmn20** [comment]
Checking the current touch position is not a valid option, because the main idea of this control scheme is that you can move the pointer to any place on the screen, and this will not change its functionality.

To be honest, I think that pointer identifiers are mandatory functionality for any device or api with multitouch screen support, and this is definitely not an exclusive android functionality. I just checked developer.apple, and for each touch their pointers in memory remain the same, because objects are used, so that pointers IDs are not needed at all. There was even such a functionality in j2me, and although there is no multitouch support in midp 2, there are at least 2 multitouch implementations from nokia and one from Samsung, and all of these implementations use identifiers.

**Comment by rmn20** [comment]
I can show you the links if you are interested.

**Comment by raysan5** [comment]
@rmn20 I keep this issue open for a future review, not a priority for the moment.
