### ISSUE TITLE
Cannot compile raylib for Android target

### ISSUE THREAD

**Issue by ArnaudValensi** [raysan5/raylib#1997]
### Issue description

I cannot compile raylib for Android target.

I get the following error:

```shell
$ mingw32-make PLATFORM=PLATFORM_ANDROID
...
core.c:5306:9: error: use of undeclared identifier 'gestureEvent'
        gestureEvent.position[i].x /= (float)GetScreenWidth();
        ^
core.c:5307:9: error: use of undeclared identifier 'gestureEvent'
        gestureEvent.position[i].y /= (float)GetScreenHeight();
        ^
```

I think this is caused by the changes made on this commit: https://github.com/raysan5/raylib/commit/803094f41f887c43852a09870d8d0e05ee5f687f

### Environment

- Windows 10

**Comment by Kronka** [comment]
This is an easy fix, I did this:
At the beginning of the "static int32_t AndroidInputCallback(struct android_app *app, AInputEvent *event)" function, put GestureEvent gestureEvent = { 0 };
And on line 5317, this line was deleted.
Good!

**Comment by raysan5** [comment]
@ArnaudValensi @Kronka Just reviewed it!
