### ISSUE TITLE
a usage error about stbi_load_gif_from_memory

### ISSUE THREAD

**Issue by Mr-JingShi** [raysan5/raylib#2005]
Hello, I am also using stb for gif decoding work, so I found raylib as a reference。

I found stbi_load_gif_from_memory has a usage error, I think it should be like this：
```
int *delays = NULL;
stbi_load_gif_from_memory(fileData, dataSize, &delays, &image.width, &image.height, &frameCount, &comp, 4);
RL_FREE(delays); 
```
Sorry my english is so bad。

Can you reply me。

**Comment by GithubPrankster** [comment]
(NOTE: Your english is ok!)
Where exactly is the point where the usage is incorrect? Why is it incorrect too?

**Comment by raysan5** [comment]
@Mr-JingShi Good catch! Thanks for the fix!

**Comment by Mr-JingShi** [comment]
> @Mr-JingShi Good catch! Thanks for the fix!

Thank you for replying to me.

**Comment by Mr-JingShi** [comment]
Thank you for replying to me.
