### ISSUE TITLE
[rcore] "Fail to get DRM Resources" on headless RPI4

### ISSUE THREAD

**Issue by tomarigr** [raysan5/raylib#2015]
Hi this is a sneaky bug, it wont always happen.

on RPI4 and especially on CM4 /dev/dri/card1 is NOT always the correct graphics card to use.
The load ordering is NOT guaranteed and you might end up with /dev/dri/card0 being the correct one.

in /src/rcore.c line 3914:
CORE.Window.fd = open("/dev/dri/card1", O_RDWR); // VideoCore VI (Raspberry Pi 4)
must change to : 
CORE.Window.fd = open("/dev/dri/by-path/platform-gpu-card", O_RDWR); // VideoCore VI (Raspberry Pi 4)

as the operating system is probing the cards and assigns the correct card to this link.

the built in fallback to card0 wont work because there actually is a graphics card there, just not the correct one. So  
if ((-1 == CORE.Window.fd) || (drmModeGetResources(CORE.Window.fd) == NULL))
CORE.Window.fd will never be neither -1 nor NULL on rpi4 and
line 3928 if (!res) will fire instead.

the proposed change fixes this problem on RPI4 and CM4 while still keeping fallback for RPI3

the solution is tested and works.

**Comment by raysan5** [comment]
@tomarigr I have a concern about this issue, that change would still work on embedded platform other than RaspberryPi?

**Comment by tomarigr** [comment]
Hi @raysan5 not sure about that, I thought this line is specific to RPI4 as there is a // VideoCore VI (Raspberry Pi 4) comment, but if this is not the case why not add one more if statement then?:
1st try on /dev/dri/by-path/platform-gpu-card for RPI4
2nd try on /dev/dri/card1 for other embedded platform
3rd try on /dev/dir/card0 for pi1-3 
note, if you try first on card0 on a pi4, even if card0 is not the correct graphics card, this if statement wont fail because CORE.Window.fd wont get -1 or NULL value, so this order is critical.

**Comment by raysan5** [comment]
@tomarigr It sounds good to me, feel free to send a PR.

**Comment by tomarigr** [comment]
Hi @raysan5, tried to do a PR but I think I've broken everything! :)
sorry, first commit on GitHub ever... can you have a look ?

**Comment by raysan5** [comment]
@tomarigr No worries, you have to sync to latest raylib master branch before doing your changes and sending the PR.

I'm just closing that PR and waiting for a new one!

**Comment by tomarigr** [comment]
@raysan5 I think I got it this time :)

**Comment by raysan5** [comment]
@tomarigr Merged!
