### ISSUE TITLE
Add GetImagePixelColor function

### ISSUE THREAD

**Issue by schveiguy** [raysan5/raylib#2024]
### Issue description

If you have an `Image` struct, then using `GetPixelColor` on it is quite difficult. It takes a `void*` and an image format. However many image formats are not supported (some don't even have pixels aligned to 8-bit values, which are not representable with a pointer).

I suggest a function:

```c
Color GetImagePixelColor(Image image, int x, int y);
```

Which uses the included format and width and height to return the proper color based on the format. This is implementable regardless of the image format I think, and would save a lot of headaches, as pointer math is not always easy, and especially `void *` math is tricky.

As some background, I worked for a while  via discord with a newer developer to debug his project where he was trying to implement a 2.5d demonstration. His function for getting the pixel color had a lot of issues, mostly around pointer math and image format, and it was really difficult to decipher information about the image.

As this is an enhancement request, I didn't fill out the full template, as most of it doesn't apply.

If needed, I can probably code up a PR at some point, but I wanted to at least stick this issue in the system so it's not forgotten.

**Comment by raysan5** [comment]
@schveiguy Yeap, I agree it could be useful for some users. Just added it. Please, let me know if it works as expected (I did not test it).

**Comment by schveiguy** [comment]
Nice! Thanks @raysan5 

it looks pretty good, I haven’t tested but having recently digested how image data is stored it looks solid.

I might add the other compressed formats if I get a chance.

ping @realdoigt
