### ISSUE TITLE
Not Playing Audio on Collision

### ISSUE THREAD

**Issue by wwderw** [raysan5/raylib#2039]
Using the latest version of 4.0 Raylib from this repo (maybe an hour old on both Linux and Windows), I have been following the audio loading/playing example.

Before the loop, I init the audio device, load the wav file below that and in the loop, I have a collision that triggers the audio and finally outside the loop, above CloseWindow(), I unload the audio and close the audio device.

When I run it via the terminal, I notice that the wav file is actually being unloaded from RAM even before the program is fully up and running.  This happens with or without the unload audio function (I was thinking maybe I had the wrong spot, so I thought I would rule that out).

I don't know if there was changes between 3.7 and 4.0 that would cause the example to be outdated or (and probably more likely), something that I am doing.  The collision itself is correctly setup as I did use another action to confirm that the collision is correct.

Thoughts?

**Comment by raysan5** [comment]
@wwderw please, could you paste the output log info?

**Comment by wwderw** [comment]
That's all that I'm getting.  It appears to load the sound and immediately unload it from RAM.  Not getting any error when I do the "button" click or anything.

![output](https://user-images.githubusercontent.com/24878362/136676130-ba53e9fe-4723-4aaf-b584-4a1f1ce088e0.png)

**Comment by catmanl** [comment]
Just wanted to mention I had seen this pattern even before 4.0-dev. However sounds worked just fine.

What *is* weird to me is that you're not unloading the sound, yet the log outputs as if you did.
Something may be wrong inside the code but I can't say anything for sure.

**Comment by wwderw** [comment]
That was just a truncated file, I didn't want to have all 440 or so lines of code to shift though.

I was using the audio loading example as my template.

I pulled the coin.wav from that and inserted that into my code, changing nothing else and everything worked as expected.  My question now is, are there bitrates or other parameters that aren't acceptable for playback in raylib?  That's the only thing that I can think of since all I did was swap out the file I was using for the one that you had in the resources folder for the audio examples (yes, I did have the correct file path for the original sound file that I was running).

**Comment by raysan5** [comment]
@wwderw raylib uses internally `dr_wav` library for wav format loading, in some cases it could happen a file is not supported for some reason... I recommend using 8bit or 32bit bit-size for the samples but afaik other bit-rates should also work.

**Comment by wwderw** [comment]
Just to play it safe, I'll probably stick with those as well.  That's easy enough to follow that schema.  

Thanks!
