### ISSUE TITLE
[rlgl] Size of quad in rlLoadDrawQuad does not match description.

### ISSUE THREAD

**Issue by hexaflex** [raysan5/raylib#2058]
This concerns: https://github.com/raysan5/raylib/blob/2a6bd973bdfe92e9f8506feb766d3351c0802d94/src/rlgl.h#L3831

The documentation on `rlLoadDrawQuad` mentions the quad is drawn with size 1x1.
However, the vertices defined [here](https://github.com/raysan5/raylib/blob/2a6bd973bdfe92e9f8506feb766d3351c0802d94/src/rlgl.h#L3837) run from -1 to +1. That makes for a 2x2 quad.

The same goes `rlLoadDrawCube` at: https://github.com/raysan5/raylib/blob/2a6bd973bdfe92e9f8506feb766d3351c0802d94/src/rlgl.h#L3872

**Comment by raysan5** [comment]
@hexaflex thanks! reviewed!
