### ISSUE TITLE
can i use the raylib library to create a close source game engine

### ISSUE THREAD

**Issue by Abdelilah-Majid** [raysan5/raylib#2078]
Please, before submitting a new issue verify and check:

 - [+] I tested it on latest raylib version from master branch
 - [+ ] I checked there is no similar issue already reported
 - [ +] My code has no errors or misuse of raylib

### Issue description
hey devs;
so i am working on this new game engine called gabriel and recently i thought what if the MIT license doesnt allow for using the code which is licensed under it(MIT) to be used in a close source  project;
i know that most games that are built with raylib are also close source but i just want to verify 
so can i use the raylib library to build my own close source game engine
and is the raylib project is going to use another license in the future
### Environment
x86_64, fedora linux, opengl 2.1, intel graphics;

**Comment by orcmid** [comment]
1. This is not an issue and you might consider moving  it to discussions as a Question.

 2. On the other hand, there is nothing in the license at  that requires you to make your product open-source
 
3. There is a request for acknowledgment.  Is that burdensome for you?

4. Licenses are not revocable.  If there were a different license in the future, that would not impact your use of code that is published under the current license.

And I am not a lawyer.  

PS: It is not the MIT License, though you could treat such code the same way.

I'm still not a lawyer.
