### ISSUE TITLE
[rmodels] `GetRayCollisionBox()` occasionally returns incorrect collision information

### ISSUE THREAD

**Issue by MatthewOwens** [raysan5/raylib#2086]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

`GetRayCollisionBox()` may be producing slightly incorrect results, as can be seen in the screenshots. I've verified this behavior with raylib's CAMERA_FREE mode, custom cameras, bounding boxes being output from `GetMeshBoundingBox()`, and bounding boxes manually generated as in the example.

I'd expect `GetRayCollisionBox()` to return `RayCollision`s where `hit == true` only when ray collides with the bounding box, and for it to never return true when the ray does not intersect a bounding box. I am seeing both, depending on where the ray is fired into the scene.
*Briefly describe the issue you are experiencing (or the feature you want to see added to raylib). Tell us what you were trying to do and what happened instead. Remember, this is not the best place to ask questions. For questions, go to [raylib Discord server](https://discord.gg/raylib).*

### Environment

Platform: PC
OS: Arch Linux
OpenGL version:
$ glxinfo | grep "OpenGL version"
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.4

GPU Details:
  *-display
       description: VGA compatible controller
       product: Vega 10 XL/XT [Radeon RX Vega 56/64]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]

### Issue Screenshot
![screenshot](https://i.imgur.com/FlVkBhH.png)
![screenshot2](https://i.imgur.com/AD7V74M.png)

### Code Example

Example can be found at https://github.com/AbyssalThistle/bbox-example, master branch has a minimal single-camera example whereas the feat/two-cameras branch contains a second camera that can be toggled to with 'r' to make viewing the issue a bit easier.
Once a ray is fired into the scene, affected BoundingBoxes are rendered in Red, and the closest is rendered in Green.

### Replication

The function not returning a collision where `hit==true` where it should can be reliably be replicated by clicking where the box closest to the camera intersects with both it's adjacent neighbor and the box diagonally-behind it.

The function returning `hit==true` can be replicated by clicking below the BoundingBox closest to the camera.

**Comment by MatthewOwens** [comment]
Hey, cheers for taking the time to look into this. A small example can be found [here](https://github.com/AbyssalThistle/bbox-example/blob/master/src/main.c), and a video that better highlights the issue can be seen here: 

https://user-images.githubusercontent.com/5711298/139672419-8b8ccacf-68a4-45a1-b429-1e11b10a0291.mp4

**Comment by raysan5** [comment]
@MatthewOwens It seems the issue is related to the bounds you are checking vs the cubes drawing, you are using bbounds.min to draw the cube but that the draw position should refer to the center of the cube, so you are checking the collision against offseted cubes. I reviewed your example, now it works:
```c
#include "raylib.h"
#include "raymath.h"

#define WIDTH 5
#define HEIGHT 5

BoundingBox bboxes[WIDTH * HEIGHT];
bool indicesAffected[WIDTH * HEIGHT];
Ray ray = {0};
int collisionIndex = -1;

Camera3D camera = { 0 };

void ClearAffectedIndices()
{
    for(int i = 0; i < WIDTH*HEIGHT; ++i) { indicesAffected[i] = false; }
}

void CameraInit()
{
    // Define the camera to look into our 3d world
    camera.position = (Vector3){ 10.0f, 10.0f, 10.0f }; // Camera position
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };      // Camera looking at point
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };          // Camera up vector (rotation towards target)
    camera.fovy = 45.0f;                                // Camera field-of-view Y
    camera.projection = CAMERA_PERSPECTIVE;             // Camera mode type

    SetCameraMode(camera, CAMERA_FREE);
}

Vector3 getBBSize(BoundingBox b)
{
    return Vector3Subtract(b.max, b.min);
}

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;
    const float OFFSET = .1f;

    InitWindow(screenWidth, screenHeight, "raylib");
    
    CameraInit();

    for(int i = 0; i < WIDTH; ++i) {
        for(int j = 0; j < HEIGHT; ++j) {
            bboxes[i*HEIGHT + j] = (BoundingBox){
                (Vector3){i + OFFSET*i, 0, j + OFFSET*j},
                    (Vector3){i + 1 + OFFSET*i, 1, j + 1 + OFFSET*j}
            };
        }
    }

    SetTargetFPS(60);                   // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())        // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------

        UpdateCamera(&camera);

        if(IsMouseButtonPressed(MOUSE_BUTTON_LEFT)) {
            ClearAffectedIndices();
            ray = GetMouseRay(GetMousePosition(), camera);
            RayCollision cinfo = {0};
            float minDistance = 99999.f;
            collisionIndex = -1;

            for(int i = 0; i < WIDTH * HEIGHT; ++i) {
                cinfo = GetRayCollisionBox(ray, bboxes[i]);
                if(cinfo.hit) {
                    indicesAffected[i] = true;
                    if(cinfo.distance < minDistance) {
                        minDistance = cinfo.distance;
                        collisionIndex = i;
                    }
                }
            }
        }

        //----------------------------------------------------------------------------------
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(DARKGRAY);

            BeginMode3D(camera);
            
                for (int i = 0; i < WIDTH*HEIGHT; ++i)
                {
                    DrawCubeWiresV(Vector3Subtract(bboxes[i].min, (Vector3){ -0.5f, -0.5f, -0.5f }), getBBSize(bboxes[i]), indicesAffected[i]? RED : WHITE);
                }
                
                DrawRay(ray, SKYBLUE);
                
                if (collisionIndex != -1) DrawCubeWiresV(Vector3Subtract(bboxes[collisionIndex].min, (Vector3){ -0.5f, -0.5f, -0.5f }), getBBSize(bboxes[collisionIndex]), GREEN);

            EndMode3D();

            DrawRectangle( 10, 10, 320, 80, Fade(SKYBLUE, 0.5f));
            DrawRectangleLines( 10, 10, 320, 80, BLUE);

            DrawText("Controls:", 20, 20, 10, BLACK);
            DrawText("- Left Click to fire a ray", 40, 40, 10, DARKGRAY);
            DrawText("- Standard free camera controls", 40, 60, 10, DARKGRAY);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by MatthewOwens** [comment]
Hey Ray, thanks again for your help! And sorry I didn't catch that earlier, cheers

**Comment by raysan5** [comment]
@MatthewOwens No worries! It's easy to get confused with current `BoundingBox` type, I never liked that implementation with `min` and `max` points.
