### ISSUE TITLE
[rtext] Valgrind complains about memory errors

### ISSUE THREAD

**Issue by Teashrock** [raysan5/raylib#2089]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I'm using Raylib in my own game engine, and I want the latter to be as bug free as possible. After once again refactoring of my code, I'd ran Valgrind to check for memory errors. In the screenshot below, one can clearly see that it complains about memory loss in ``GenImageFontAtlas`` and ``LoadFontData``. ``malloc`` is called somewhere and causes this.

### Environment

Gentoo Linux 5.10.52-gentoo x86_64, OpenGL 3.3 (I think?), Radeon Vega 11 with AMDGPU drivers.

### Issue Screenshot

![2021-10-30_14:23:03](https://user-images.githubusercontent.com/12483854/139531003-5fe355ef-434a-4add-a590-26abf1be30d6.png)

### Code Example

```C
Font* CreateFont(unsigned char* fontSource, unsigned int sourceSize, int baseSize, int charsCount, FontCreationMethod method)
{
    Font* font = (Font*)malloc(sizeof(Font));
    AllocError(font, "Failed to allocate pointer!");

    *font = (Font){0};
    font->baseSize   = baseSize;
    charsCount = (charsCount > 0) ? charsCount : 95;
    font->glyphCount = charsCount;
    unsigned char* font_data;
    switch (method)
    {
    case FONT_CREATION_METHOD_TTF:
        font->glyphPadding = 0; // FONT_TTF_DEFAULT_CHARS_PADDING
        font_data = LoadFileData((char*)fontSource, &sourceSize);
        break;
    case FONT_CREATION_METHOD_IMAGE:
        
        break;
    case FONT_CREATION_METHOD_RAW:
        font_data = fontSource;
        font->glyphPadding = 4;
        break;
    default:
        break;
    }
    font->glyphs = LoadFontData(font_data, sourceSize, font->baseSize, 0, font->glyphCount, FONT_DEFAULT);
    if (method != FONT_CREATION_METHOD_RAW)
        free(font_data);
    Image atlas = GenImageFontAtlas(font->glyphs, &(font->recs), font->glyphCount, font->baseSize, font->glyphPadding, 0);
    font->texture = LoadTextureFromImage(atlas);
    
    // Update chars[i].image to use alpha, required to be used on ImageDrawText()
    for (int i = 0; i < font->glyphCount; i++)
    {
        UnloadImage(font->glyphs[i].image);
        font->glyphs[i].image = ImageFromImage(atlas, font->recs[i]);
    }
    
    UnloadImage(atlas);

    //if (type == FONT_SDF)
    SetTextureFilter(font->texture, TEXTURE_FILTER_BILINEAR);
    AddFreeable(font);
    return font;
}
```

**Comment by raysan5** [comment]
I did a quick check of `LoadFontData()` and `GenImageFontAtlas()` and the `malloc()` calls look correct to me:
```c
// LoadFontData() malloc calls (2):
fontChars = (int *)RL_MALLOC(glyphCount*sizeof(int));
chars = (GlyphInfo *)RL_MALLOC(glyphCount*sizeof(GlyphInfo));
```
```c
// GenImageFontAtlas() malloc calls (5):
Rectangle *recs = (Rectangle *)RL_MALLOC(glyphCount*sizeof(Rectangle));
stbrp_context *context = (stbrp_context *)RL_MALLOC(sizeof(*context));
stbrp_node *nodes = (stbrp_node *)RL_MALLOC(glyphCount*sizeof(*nodes));
stbrp_rect *rects = (stbrp_rect *)RL_MALLOC(glyphCount*sizeof(stbrp_rect));
unsigned char *dataGrayAlpha = (unsigned char *)RL_MALLOC(atlas.width*atlas.height*sizeof(unsigned char)*2);
```
It could be a false-positive but someone with more experience than me should review it, I could be missing some point...

`GlyphInfo` is a complex struct and there could be some memory alignment concern, it should be tested on a 32bit OS to verify if that could be the issue.

**Comment by Teashrock** [comment]
@raysan5 
Somebody in Raylib Discord channel suspected that these ``malloc``s could be forgotten to be ``free``d.

**Comment by raysan5** [comment]
@Teashrock I double checked the functions and all required `free()` are called, are you calling `UnloadFont()` in your code?

**Comment by Teashrock** [comment]
@raysan5 
No, but I've written my own freeing system, which frees everything marked when the program closes.

**Comment by Teashrock** [comment]
**UPDATE**: The same screenshot, but with numbers of the problem lines in Raylib.
![2021-10-30_14:23:03](https://user-images.githubusercontent.com/12483854/139531003-5fe355ef-434a-4add-a590-26abf1be30d6.png)

**Comment by raysan5** [comment]
@Teashrock You must call it when the font is not required any more, usually at the end of the program execution. Keep it mind that you must use `UnloadFont()` to match the same allocator used to load it (the one internally used by raylib). Using your own `free()` call over the data could be using a different library allocator. Actually, `MemFree()` is provided for those cases.

**Comment by chriscamacho** [comment]
it would be of great help to provide a simple example replicating any issue, you're using your own memory freeing system which could well be the issue, valgrind can and does have false positives, especially with GPU drivers (libGL) and X11 for example...

**Comment by Teashrock** [comment]
@chriscamacho 
![2021-10-30_14:29:04](https://user-images.githubusercontent.com/12483854/139531150-7c650ea8-8356-4a3b-a1cf-1284615b4e5b.png)
![2021-10-30_14:28:50](https://user-images.githubusercontent.com/12483854/139531151-cad34f0f-e2e1-484a-a25e-e8a81fdc3095.png)

**Comment by raysan5** [comment]
@Teashrock Actually, checking the problematic lines specifically, in both cases refer to data allocated internally by raylib that is returned and should be freed by the user. That could be related to the allocators used: internal malloc() vs external free()

**Comment by Teashrock** [comment]
@raysan5 
If this is really the case, then I should rewrite my memory handling system. This issue is frozen until further info, then.

**Comment by raysan5** [comment]
@Teashrock I would recommend trying a quick test using `MemFree()` or `RL_FREE()` directly in your code to unload the Font data returned by `LoadFontData()` and `GenImageFontAtlas()`.

**Comment by chriscamacho** [comment]
screenshots are of limited use, can you please provide a simple self contained source that demonstrates the issue. thanks.

**Comment by chriscamacho** [comment]
your freeable will not free allocated items inside structs, you should really have some kind of type field and based on that call the raylib unload function before releasing the memory that the whole structure uses.

**Comment by raysan5** [comment]
@Teashrock I'm closing this issue as it seems user-related, I can't find any issue on raylib sources in the mentioned code points.

As a side note, `UnloadFontData()` is provided by raylib to make sure data loaded by its allocators is unloaded by the same allocators. In the case of data allocated with `GenImageFontAtlas()` it should be de-allocated using `UnloadImage()`.
