### ISSUE TITLE
[raudio] `GetMusicTimePlayed()` reports incorrect value after the stream is restarted for XM audio

### ISSUE THREAD

**Issue by Peter0x44** [raysan5/raylib#2092]
This issue can be reproduced on this example: https://www.raylib.com/examples/audio/loader.html?name=audio_module_playing
The progress bar does not reset upon pressing space, which stops and starts the stream.

This seems to be an issue exclusive to XM, as https://www.raylib.com/examples/audio/loader.html?name=audio_music_stream works correctly, and the progress bar resets when space is pressed.

**Comment by raysan5** [comment]
This is a known issue, it requires some debugging...

**Comment by ptarabbia** [comment]
Just sent a PR fixing this.
