### ISSUE TITLE
[rglfw] Undefined references issues when using latest GLFW (3.4-master)

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#2093]
When updating `raylib/src/external/glfw` with latest GLFW from their [GitHub master branch](https://github.com/glfw/glfw), `raylib` could not compile and examples fail with `undefined references` to GLFW symbols.

That happens if using `raylib/src/Makefile` that compiles the `rglfw.c` module. CMake avoids `rglfw` and compiles GLFW as a separate library automatically, so, it works ok with CMake.

**[`rglfw.c`](https://github.com/raysan5/raylib/blob/master/src/rglfw.c) module should be reviewed to define and include the proper GLFW modules depending on the platform.**

EDIT: In case anyone test it, `glfw3native.h` requires a small tweak for raylib to avoid some `windows.h` symbols collisions:
```c
//#include <windows.h>
 typedef void *PVOID;
 typedef PVOID HANDLE;
 typedef HANDLE HWND;
```

**Comment by AKDev21** [comment]
Credit - tjammer#9869
When using the ``3.3.5 zip version`` of glfw, raylib and examples compiles and runs normally.
When using the ``master branch`` of glfw which is the same as the 3.3.5 zip version, there are undefined references when compiling examples.

**Comment by raysan5** [comment]
@AKDev21 Afaik, `master branch` is actually `3.4.0`, despite no official release yet.

**Comment by gen2brain** [comment]
This is related to https://github.com/glfw/glfw/commit/56a4cb0a3a2c7a44a2fd8ab3335adf915e19d30c added 20 days ago. A lot has changed, this should also fix the need to have a separate binary for X11 and Wayland https://github.com/glfw/glfw/issues/1655.

**Comment by raysan5** [comment]
@gen2brain Yeah! Thanks for pointing it out! Actually it was commented on raylib Discord, some users investigated it.

Unfortunately, we were not able to get it working for [`rglfw.c`](https://github.com/raysan5/raylib/blob/master/src/rglfw.c) raylib module. Actually it was the only library not updated for `raylib 4.0`, last update was for `raylib 3.7`.

In any case, there is not an official `GLFW 3.4.0` release yet so I'll wait for it before updating raylib.

**Comment by raysan5** [comment]
Waiting for an official release.
