### ISSUE TITLE
Issue with core_custom_frame_control example

### ISSUE THREAD

**Issue by Otaka** [raysan5/raylib#2117]
Just cloned latest master (https://github.com/raysan5/raylib/commit/42f5903b913e93e6010e32b5cc2e89bb97c7a826)

Executed **cmake -G "Unix Makefiles" .**
And then **mingw32-make PLATFORM=PLATFORM_DESKTOP**
After that just start looking examples. And find out, that example **core_custom_frame_control** not working as expected. The screen is flickering, and mostly black
![Issue](https://user-images.githubusercontent.com/936986/140664760-75485c21-a76d-4141-9f4e-e762259f7cbb.gif)

I have made the test on **Windows 10** with some mingw version that were on my machine(x86_64-8.1.0-posix-seh-rt_v6-rev0)
The same test I have made on my **Macbook Pro** with the latest OSX(also followed build instructions from github: cmake...  make PLATFORM=PLATFORM_DESKTOP) and I saw the same flickering

**Comment by raysan5** [comment]
```
...flag SUPPORT_CUSTOM_FRAME_CONTROL can be enabled in
*   config.h (it requires recompiling raylib). This way those steps are up to the user.
```
Did you enable the required flad and recompiled raylib?

**Comment by Otaka** [comment]
yes, my fault. It is working after I enabled this flag

**Comment by WildRackoon** [comment]
I think this should be stated more explicitly in the example / [the examples markdown page](https://github.com/raysan5/raylib/tree/master/examples)

For CMake I will work on a MR using [add_compile_definitions](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html) to do it on its own
