### ISSUE TITLE
[examples] core_input_gamepad crashes with EXC_BAD_ACCESS (SIGSEGV)

### ISSUE THREAD

**Issue by lukekras** [raysan5/raylib#2122]
### Issue description

Running [example/core/core_input_gamepad](https://github.com/raysan5/raylib/blob/master/examples/core/core_input_gamepad.c) example program crashes with a EXC_BAD_ACCESS (SIGSEGV) when one disconnects the USB cable. This is mostly due to minimal error checking in the core_input_gamepad example code. Disconnecting the gamepad  is a reasonable thing to do, and there is an opportunity in raylib to avoid this scenario (see PR #2121 that I've put a fix in).

### Environment

Macbook Pro, macOS Big Sur Version 11.6 Intel, OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Plus Graphics 650

### Issue Screenshot

[sigsegv.pdf](https://github.com/raysan5/raylib/files/7504070/sigsegv.pdf)

### Code Example

I've raised a PR #2121 with a fix.

**Comment by raysan5** [comment]
@lukekras Merged and reviewed!
