### ISSUE TITLE
Why I using the command "mingw32-make PLATFORM=PLATFORM_DESKTOP" error?

### ISSUE THREAD

**Issue by quang1k92** [raysan5/raylib#2128]
Why I use the command "mingw32-make PLATFORM=PLATFORM_DESKTOP" error?
![z2924641990659_bcf70383cbb704afc79291ccca08ef27](https://user-images.githubusercontent.com/88482156/141238438-a1c4d9f0-342a-4bc9-ab3b-227784f339c9.jpg)
![z2924641990585_8ab1c92c3402d48850bad17e3892b1c7](https://user-images.githubusercontent.com/88482156/141238452-82601da0-c1d3-43c7-b881-31cc994bf8d7.jpg)
![z2924641990653_cfb6ec905cdd1b9384d710fed94d26a3](https://user-images.githubusercontent.com/88482156/141238446-2176a766-f96f-4b7b-b109-71ae33ec89e3.jpg)

Please help meeeeee

**Comment by raysan5** [comment]
Probably because you are using an old version of MinGW. Try using the one that comes with raylib installer, it's updated.

**Comment by quang1k92** [comment]
Thanks
