### ISSUE TITLE
[rcore] Build fails when building simple example in Visual Studio 2019

### ISSUE THREAD

**Issue by Bart-Luyckx** [raysan5/raylib#2132]
I downloaded the latest raylib master from github and built raylib.lib with VS2019 (Debug x64) using the solution file C:\raylib\projects\VS2019\raylib.sln

This gives me C:\raylib\projects\VS2019\build\raylib\bin\x64\Debug\raylib.lib

I now try to build this simple example in VS2019 -> https://www.raylib.com/examples/core/loader.html?name=core_basic_window

> Rebuild started...
> 1>------ Rebuild All started: Project: Racecar, Configuration: Debug x64 ------
> 1>Racecar.cpp
> 1>raylib.lib(**rcore.obj**) : error LNK2019: unresolved external symbol **timeBeginPeriod** referenced in function InitTimer
> 1>raylib.lib(**rcore.obj**) : error LNK2019: unresolved external symbol **timeEndPeriod** referenced in function CloseWindow
> 1>X:\_BART\DEVELOPMENT\CPP\Racecar\x64\Debug\Racecar.exe : fatal error LNK1120: 2 unresolved externals
> 1>Done building project "Racecar.vcxproj" -- FAILED.
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

From what I can see inside C:\raylib\src\rcore.c
```
    // Support retrieving native window handlers
    #if defined(_WIN32)
        #define GLFW_EXPOSE_NATIVE_WIN32
        #include "GLFW/glfw3native.h"       // WARNING: It requires customization to avoid windows.h inclusion!

        #if defined(SUPPORT_WINMM_HIGHRES_TIMER) && !defined(SUPPORT_BUSY_WAIT_LOOP)
            // NOTE: Those functions require linking with winmm library
            unsigned int __stdcall timeBeginPeriod(unsigned int uPeriod);
            unsigned int __stdcall timeEndPeriod(unsigned int uPeriod);
        #endif
    #endif

```

It's basically the same issue as this one -> [#[build] Building VS2017 solution from master fails #831](https://github.com/raysan5/raylib/issues/831)

Might be worthwhile to mention somewhere that even the simplest of examples need this **winmm.lib** dependency added
to Visual Studio's Project Property Pages -> Linker -> Input -> Additional Dependencies -> raylib.lib;winmm.lib

Regards,
Bart

**Comment by raysan5** [comment]
It is mentioned here: https://github.com/raysan5/raylib/wiki/raylib-dependencies#platform-specific-dependency-notes

**Comment by Bart-Luyckx** [comment]
Ok, fair enough. I only just started looking into your library.
Cheers,
Bart
