### ISSUE TITLE
How to set raylib window icon?

### ISSUE THREAD

**Issue by quang2k11** [raysan5/raylib#2134]
How to set raylib window icon?
![z2928700094584_309dbb9fa9b4c3bff51931e2243769e1](https://user-images.githubusercontent.com/94168510/141451585-2f5caf31-1aa0-4844-8224-920d657de438.jpg)
Please help me, I want to finish my game.

**Comment by hero2002** [comment]
I think replacing the icon in the raylib/src would be enough

**Comment by raysan5** [comment]
@quang2k11 Probably the easier option is using `SetWindowIcon(Image image)` but if you need to also set the executable icon and metadata you should use a custom resource file and compile it with `windres`.

**Comment by quang2k11** [comment]
thanks

**Comment by quang2k11** [comment]
But can you give me some example code, @raysan5 ?

**Comment by raysan5** [comment]
@quang2k11 You need to create a resource file (you can check `raylib/src/raylib.rc` for reference and compile it with:
```
windres raylib.rc -o raylib.rc.data --target=pe-x86-64
```

If you are compiling for 32bit, you should use `--target=pe-i386`

**Comment by quang2k11** [comment]
Why I set the raylib 24x24 logo my program have a error:
![image](https://user-images.githubusercontent.com/94168510/141921911-d1a6412b-a03f-4a46-a054-724b2cb4b495.png)

**Comment by TheAngriestCrusader** [comment]
Your file is definitely an .ico file and not a .png file, right?

**Comment by notcl4y14** [comment]
> Why I set the raylib 24x24 logo my program have a error: ![image](https://user-images.githubusercontent.com/94168510/141921911-d1a6412b-a03f-4a46-a054-724b2cb4b495.png) Help me, @raysan5 !

I've had the same error, but fixed it after resaving the image with 32-bit

**Comment by SpartaVR12** [comment]
Image myImage = LoadImage("myimage.png"); /* or LoadImage("Assets/Images/myimage.png");  */
SetWindowIcon(myImage);
