### ISSUE TITLE
[parser] Matrix fields do not adhere to the expected format

### ISSUE THREAD

**Issue by kurinoku** [raysan5/raylib#2135]
You can see [here](https://github.com/raysan5/raylib/blob/864e3ee9f3da2e0f9dc128eeea58873cd75ff55a/parser/raylib_api.lua#L71) that what's supposed to be each one field of its own, it's interpreted as a single field with a name of the list of variables as it appears in source.

So [Matrix](https://github.com/raysan5/raylib/blob/864e3ee9f3da2e0f9dc128eeea58873cd75ff55a/parser/raylib_api.lua#L71) should be changed.

**Comment by raysan5** [comment]
@kurinoku I'm aware of that case and it's an exception. No plans to change it.
