### ISSUE TITLE
[core] core_scissor_test not working properly on high DPI screen

### ISSUE THREAD

**Issue by lukekras** [raysan5/raylib#2142]
- [ x] I tested it on latest raylib version from master branch
 - [ x] I checked there is no similar issue already reported
 - [ x] My code has no errors or misuse of raylib

### Issue description

I was running the [core_scissor_test](https://github.com/raysan5/raylib/blob/master/examples/core/core_scissor_test.c) example program and it wasn't working on a high DPI MacBook Pro. The scissor red box was out of alignment to the mouse outline box.

### Environment

macOS Big Sur Intel MacBook Pro

INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel Inc.
INFO:     > Renderer: Intel(R) Iris(TM) Plus Graphics 650
INFO:     > Version:  4.1 INTEL-16.5.2
INFO:     > GLSL:     4.10

### Issue Screenshot
<img width="912" alt="Screen Shot 2021-11-14 at 10 22 19 pm" src="https://user-images.githubusercontent.com/1853946/141682682-3abdf343-8ad5-4122-bb86-b588289a8e8a.png">

### Code Example

I've submitted a PR #2141

**Comment by raysan5** [comment]
Related: https://github.com/raysan5/raylib/issues/1982 and https://github.com/raysan5/raylib/pull/1987

**Comment by lukekras** [comment]
Closed PR #2141 and created PR #2160 with refactored code.

**Comment by raysan5** [comment]
@ArnaudValensi pushed a big commit related, maybe he can look into this issue?

**Comment by lukekras** [comment]
@raysan5 @ArnaudValensi 
I've checked out `Fix scissor on macos` #2170 and confirm that it fixes this problem. From my point of view this issue can be closed.

PR #2170 makes PR `Fix scissor mode for high DPI screens (refactored)` #2160 redundant.

**Comment by raysan5** [comment]
@ArnaudValensi @lukekras thanks to you both for working on this issue and the reviews!

**Comment by lukekras** [comment]
No problem @raysan5, happy to help where I can. Cheers.
