### ISSUE TITLE
Linking error on android

### ISSUE THREAD

**Issue by WilledgeR** [raysan5/raylib#2144]
platform: Windows
target: Android

I followed wiki to make and android example apk using `raylib-game-template` here is the error:

`android.raylib_game/lib/arm64-v8a\libraylib.a: error adding symbols: File format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
mingw32-make[1]: *** [Makefile.Android:262: compile_project_code] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/Mahdi/Desktop/raylib-game-template/src'
mingw32-make: *** [Makefile:397: all] Error 2`

here is what Makefile tries to do:

```C:\Users\Mahdi\AppData\Local\Android\Sdk\ndk\21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android29-clang -o android.raylib_game/lib/arm64-v8a/libmain.so  android.raylib_game/obj/raylib_game.o  android.raylib_game/obj/screen_logo.o  android.raylib_game/obj/screen_title.o  android.raylib_game/obj/screen_options.o  android.raylib_game/obj/screen_gameplay.o  android.raylib_game/obj/screen_ending.o -shared -I. -IC:\Users\Mahdi\Desktop\raylib-master/src -IC:\Users\Mahdi\AppData\Local\Android\Sdk\ndk\21.4.7075529/sources/android/native_app_glue -Wl,-soname,libmain.so -Wl,--exclude-libs,libatomic.a  -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings  -u ANativeActivity_onCreate -L. -Landroid.raylib_game/obj -Landroid.raylib_game/lib/arm64-v8a -LC:\Users\Mahdi\AppData\Local\Android\Sdk\ndk\21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64\sysroot\usr\lib -lm -lc -lraylib -llog -landroid -lEGL -lGLESv2 -lOpenSLES -ldl```

**Comment by raysan5** [comment]
@WilledgeR `make clean` is intended for that
