### ISSUE TITLE
[build] `make install` doesn't work on RPI3

### ISSUE THREAD

**Issue by trikko** [raysan5/raylib#2147]
### Issue description

```make PLATFORM=PLATFORM_RPI ```

result:

```
ar rcs ../src/libraylib.a rcore.o rshapes.o rtextures.o rtext.o utils.o rmodels.o raudio.o
raylib static library generated (libraylib.a) in ../src!
```

```sudo make install```

result:

```
mkdir --parents --verbose /usr/local/lib
mkdir --parents --verbose /usr/local/include
cp --update --verbose /home/pi/src/raylib/libraylib.a /usr/local/lib/libraylib.a
cp: impossibile eseguire stat di '/home/pi/src/raylib/libraylib.a': File o directory non esistente
make: *** [Makefile:629: install] Error 1
```

It tries to copy ```/home/pi/src/raylib/libraylib.a``` instead of ```/home/pi/src/raylib/src/libraylib.a```

### Environment

rpi3

**Comment by raysan5** [comment]
This is very weird, I'm looking at the `Makefile` and I can't find the issue. `libraylib.a` is actually generated in `$(RAYLIB_RELEASE_PATH)/libraylib.a`, so, the path should be correct. The only way to modify it is defining a custom `RAYLIB_RELEASE_PATH`...

**Comment by raysan5** [comment]
Just noted this code in line 150:
```make
# RAYLIB_SRC_PATH adjustment for different platforms.
# If using GNU make, we can get the full path to the top of the tree. Windows? BSD?
# Required for ldconfig or other tools that do not perform path expansion.
ifeq ($(PLATFORM),PLATFORM_DESKTOP)
    ifeq ($(PLATFORM_OS),LINUX)
        RAYLIB_PREFIX  ?= ..
        RAYLIB_SRC_PATH = $(realpath $(RAYLIB_PREFIX))
    endif
endif
```
Could it, maybe, be executed before assigning `RAYLIB_RELEASE_PATH  ?= $(RAYLIB_SRC_PATH)`???

**Comment by colesnicov** [comment]
RPI 2 Model B
OS: RapiOS (Buster)
GL Driver: FULL_KMS

I followed the wiki instructions:
cd src && make PLATFORM = PLATFORM_RPI
and i have same errors:
```
sudo make install
mkdir --parents --verbose /usr/local/lib
mkdir --parents --verbose /usr/local/include
cp --update --verbose /home/pi/raylib/libraylib.a /usr/local/lib/libraylib.a
cp: cannot stat '/home/pi/raylib/libraylib.a': No such file or directory
make: *** [Makefile:635: install] Error 1
```

**Comment by colesnicov** [comment]
> 

NO, it is bad too.

> Just noted this code in line 150:
> 
> ```makefile
> # RAYLIB_SRC_PATH adjustment for different platforms.
> # If using GNU make, we can get the full path to the top of the tree. Windows? BSD?
> # Required for ldconfig or other tools that do not perform path expansion.
> ifeq ($(PLATFORM),PLATFORM_DESKTOP)
>     ifeq ($(PLATFORM_OS),LINUX)
>         RAYLIB_PREFIX  ?= ..
>         RAYLIB_SRC_PATH = $(realpath $(RAYLIB_PREFIX))
>     endif
> endif
> ```
> 
> Could it, maybe, be executed before assigning `RAYLIB_RELEASE_PATH ?= $(RAYLIB_SRC_PATH)`???
> 
> **EDIT: If that's the case, then the issue is platform dependant and probably this code should be removed...**

NO, it is bad too.

**Comment by raysan5** [comment]
Any Linux expert in the room?

**Comment by wereii** [comment]
So, the problem is in that the setting `PLATFORM=PLATFORM_RPI` will cause [this ifeq branch](https://github.com/raysan5/raylib/blob/55d310fcc3aa0d6212c2a24518349a6d45459feb/src/Makefile#L150) to not be taken and the `RAYLIB_PREFIX` and `RAYLIB_SRC_PATH` are not changed thru the `realpath` as would happen on other non-rpi Linux.

What this causes is that when running build `make PLATFORM=PLATFORM_RPI` the paths will be different then when running `make install` without the platform setting.

The proposed PR of mine would fix this so the paths are same both for RPi and Linux.
