### ISSUE TITLE
OpenGL ES2 on Linux

### ISSUE THREAD

**Issue by dmalves** [raysan5/raylib#215]
Hello,

AFAIK OpenGL ES2 on RayLib is used by default on Android and Web versions. How can I compile RayLib to use OpenGL ES2 on Linux? I want to code on Linux and port shaders to Android, so maybe work with the same OpenGL version could help.

thx.

**Comment by raysan5** [comment]
Hi @dmalves,

OpenGL ES is intended for Embedded Systems, on desktop you should use OpenGL, actually, OpenGL ES 2.0 is [equivalent to OpenGL 3.x](http://stackoverflow.com/questions/9629897/opengl-es-2-0-vs-opengl-3-similarities-and-differences) in lot of functionality.

raylib uses OpenGL ES 2.0 for Android and Raspberry PI; for HTML5 raylib uses WebGL (it is directly translated from OpenGL ES 2.0 using [emscripten](http://kripken.github.io/emscripten-site/)). On Linux you should use OpenGL... there are some ways to enable OpenGL ES through emulation libraries (Mesa, ARM emulator, PowerVR emulator...) but it's not the expected use.

Here there are some links with additional information on this subject:

https://forum.openframeworks.cc/t/gles-opengl-es-on-desktop-linux-customeglwindowsettings/21925
http://stackoverflow.com/questions/12045488/any-gles-examples-in-c-on-x86-linux
http://stackoverflow.com/questions/3809236/how-to-develop-opengl-es-gles-2-0-applications-on-linux

**Comment by raysan5** [comment]
About shaders porting... I recommend you to use GLSL 120 on desktop platform, it could work with OpenGL 2.1 or even 3.3 and it's quite similar to GLSL ES 100, the shader language used on OpenGL ES 2.0.
