### ISSUE TITLE
[raymath] Angle returned by `Vector2Angle()` isn't correct

### ISSUE THREAD

**Issue by Knose1** [raysan5/raylib#2172]
Like [this](https://githubmemory.com/repo/gen2brain/raylib-go/issues/42) post say, the angle isn't correct.  
I used to multiply one of the vectors by 1000 when calling the function to avoid that problem.   
The problem came back with `Vector2Angle({0,1}, {0,1000})` the result shall be 0 but the returned value is 90
  
I fixed it by replacing this line  
https://github.com/raysan5/raylib/blob/49a5547386a354fc1ca4c6fb6a4c850615b25038/src/raymath.h#L284  
  
By this one in the raymath.h of my project  
```cpp
float result = atan2(v2.y, v2.x) - atan2(v1.y, v1.x) * (180.0f / PI);
```

**Comment by schveiguy** [comment]
This should be closed now.

**Comment by leowribeiro** [comment]
I discovered that if you want to calculate the angle between vectors A and B you can use
Vector2Angle(A, A-B) - 180

**Comment by raysan5** [comment]
@leowribeiro Note that `Vector2Angle()` returns angle in radians so you can not operate with `-180` directly.

**Comment by leowribeiro** [comment]
Ok, I'm confused. I'm using raylib-cpp, in my code I put this code
targetTh = j.Angle(j-v) + 270;
And is working... when I checked the Angle method from Vector2.hpp, it is just a call to Vector2Angle(), look

float Angle(const ::Vector2& vector2) const {
       return Vector2Angle(*this, vector2);
}

My working perfectly, I'm sure.

**Comment by raysan5** [comment]
@leowribeiro that's because you are using an old version of raylib. That was an issue that was fixed some time ago. Now `Vector2Angle()` return radians, not degrees.

**Comment by leowribeiro** [comment]
Understood, thank you.
