### ISSUE TITLE
[textures] `DrawTextureTiled()` goes into infinite loop when source size is 0

### ISSUE THREAD

**Issue by Shadowblitz16** [raysan5/raylib#2173]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
I am trying to draw custom 9 patches with DrawTextureTiled however it seems that if the source Size is zero on either axis it goes into a infinite loop.

What should happen is it samples in between the two pixels.

I'm not sure if it happens with destination size but that's less of a issue.

### Environment
Kubuntu 20.04
GL: OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.3

### Issue Screenshot
![image](https://user-images.githubusercontent.com/2453707/143515540-8fa067fc-8c99-4d05-b933-4b96a2b4cf52.png)
![image](https://user-images.githubusercontent.com/2453707/143515563-228b4db1-922f-44eb-8d80-87921189cbd0.png)

### Code Example
I am using raylib-cs and am still working on the code but its easy to reproduce if you make the source size to 0.

**Comment by Shadowblitz16** [comment]
Maybe sampling between the two pixels is the wrong phrase.
I mean it should probably clamp it to a minimum of 1x1 pixel

**Comment by raysan5** [comment]
Just added a security test but I'm afraid this function could be removed at some point.

  > What should happen is it samples in between the two pixels.

I'm afraid it requires shaders, this function is not intended to work that way.
