### ISSUE TITLE
[core] `GetMouseDelta()` does not work on `PLATFORM_WEB` running on mobile browser

### ISSUE THREAD

**Issue by trikko** [raysan5/raylib#2174]
```GetMouseDelta()``` does not work with smartphone touch using ```PLATFORM=PLATFORM_WEB```

I replaced it with a difference between the current and previous position returned by ```GetMousePosition()```

**Comment by raysan5** [comment]
@trikko Just reviewed the code and I can't find the issue, all looks correct to me...

**Comment by raysan5** [comment]
I'm closing this issue as out-of-scope, too many systems involved for proper review.
