### ISSUE TITLE
[camera] First person camera initialization issue

### ISSUE THREAD

**Issue by iomeone** [raysan5/raylib#2176]
https://github.com/raysan5/raylib/blob/d1b8d4f2c7867f1c673c0a44925b59f6a012f8ba/examples/core/core_3d_camera_free.c#L33

In this example, I change CAMERA_FREE to CAMERA_FIRST_PERSON,  I should see the box when I run the example, right? 

But in CAMERA_FIRST_PERSON mode ,  you'll never see the box  unless you rotate it in some degree by your mouse!

I want to know If there's a way to show the box at the start of the example,  
because in the example we set the camera to (10, 10, 10),  set the target to  (0, 0, 0), set the cube position to (0, 0, 0)  
Then we should see the box  when start the application,  because we look at (0, 0, 0) from (10, 10, 10), right?

**Comment by raysan5** [comment]
@iomeone I'm afraid the full raylib camera module should be reviewed...
