### ISSUE TITLE
[build] `GenImageCellular()` generates a blank image using TCC compiler

### ISSUE THREAD

**Issue by gpc91** [raysan5/raylib#2178]
**GenImageCellular()** fails to generate an image when using the tcc compiler. Using MinGW it works as expected.

###TCC
![image](https://user-images.githubusercontent.com/2610380/144219321-9bc8c7bf-e213-4d52-939a-a8ebaac2b153.png)

###MinGW
![image](https://user-images.githubusercontent.com/2610380/144219369-2b168043-27b0-4c7c-abee-b0c3e39a1915.png)

**Comment by orcmid** [comment]
The two programs are not identical.  What happens when the tcc one is the same as the MingW one?

**Comment by gpc91** [comment]
> The two programs are not identical.  What happens when the tcc one is the same as the MingW one?

They most certainly are - I changed the cell-size argument from 32 to 16 because 16 looks better when rendered. It doesn't matter what cell size you use, the TCC compiler renders a black screen image, regardless of Image width, height, or cellsize. The MinGW compiler works as intended.

**Comment by RandomErrorMessage** [comment]
I feel like this is a bug report for TCC and outside the scope of raylib. I don't see any warnings related to this, even with pedantic flag. I would not be surprised if this was a bug in TCC itself. Someone would really need to dive into this function and the machine code to see what's happening.

Just curious, are you distributing code compiled by TCC?

**Comment by gpc91** [comment]
> I feel like this is a bug report for TCC and outside the scope of raylib. I don't see any warnings related to this, even with pedantic flag. I would not be surprised if this was a bug in TCC itself. Someone would really need to dive into this function and the machine code to see what's happening.

I agree fully, but was asked by @raysan5 to submit the issue. 

> Just curious, are you distributing code compiled by TCC?

I am not, no

**Comment by raysan5** [comment]
@gpc91 This is a weird but interesting issue that worth some investigation. I'd like to keep track of it.

**Comment by raysan5** [comment]
@gpc91 Please, could you try again with latest update? I reviewed a possible undefined behaviour in the function.
