### ISSUE TITLE
[examples] `rlgl_compute_shader` SSBO buffers not cleared

### ISSUE THREAD

**Issue by fluix-dev** [raysan5/raylib#2185]
### Issue description

1. Run the [`others/rlgl_compute_shader` example](https://github.com/raysan5/raylib/blob/48d4806e531e721d73995d61bfceaaeb955fd526/examples/others/rlgl_compute_shader.c).
2. Draw some lines so the screen is not empty (i.e. there are remaining white pixels on screen).
3. Exit.
4. Run again.

*Often* (personally >50% of the time), some or all of the white pixels on screen before are **still present**.

### Environment

Compiled with `GRAPHICS=GRAPHICS_API_OPENGL_43` and using `USE_WAYLAND_DISPLAY=TRUE` on Arch Linux `5.15.2-arch1-1`. Relevant GL log from running the example below:

```
INFO: Initializing raylib 4.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Screen size:  768 x 768
INFO:     > Render size:  768 x 768
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 229
INFO: GL: OpenGL device information:
INFO:     > Vendor:   AMD
INFO:     > Renderer: AMD Radeon RX Vega (VEGA10, DRM 3.42.0, 5.15.2-arch1-1, LLVM 13.0.0)
INFO:     > Version:  4.6 (Core Profile) Mesa 21.2.5
INFO:     > GLSL:     4.60
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Compute shaders supported
INFO: GL: Shader storage buffer objects supported
```

### Cause & Solution

My guess is that the [calls to `rlLoadShaderBuffer`](https://github.com/raysan5/raylib/blob/48d4806e531e721d73995d61bfceaaeb955fd526/examples/others/rlgl_compute_shader.c#L69) return a buffer but **do not clear it**. Adding the line below (alongside an `#include "glad.h"`) fixes the issue:

```c
glClearNamedBufferData(ssboA, GL_R8UI, GL_RED_INTEGER, GL_UNSIGNED_BYTE, 0);
```

The parameters are taken [from here](https://stackoverflow.com/questions/37642570/clearing-shader-storage-buffer-efficiently/37642796#37642796), and effectively clear the buffer, but there may be more *correct* ones instead.

**Edit**: I'm also not sure whether it would be correct to clear both buffers or not (only `ssboA` seems to work). Feel free to suggest the correct one and I can make a PR.

**Comment by fluix-dev** [comment]
**Correction**: it appears you do need to clear *both* the `ssboA` and `ssboB` buffers.

**Comment by raysan5** [comment]
@fluix-dev It seems it could be a GPU driver-dependant issue, when a buffer is unloaded with `rlUnloadShaderBuffer()` it should probably be cleared... but I couldn't find that info on the OpenGL specs. The GPU driver takes that decision.

In any case, I'm reviewing `rlLoadShaderBuffer()` to clear the SSBO on creation. Just note that `glClearNamedBufferData()` can not be used, it was added on OpenGL 4.5 but raylib only supports up to OpenGL 4.3; `glClearBufferData()` must be used instead.

**Comment by fluix-dev** [comment]
Understood. Thanks for the quick fix!
