### ISSUE TITLE
[models] failed load vox model

### ISSUE THREAD

**Issue by chengchingwen** [raysan5/raylib#2186]
### Issue description

I'm trying the loading_vox example and get a list of warning about failed to load vox file, like this:
```
...
WARNING: MATERIAL: [resources/models/vox/chr_knight.vox] Failed to load material data, default to white material
WARNING: [resources/models/vox/chr_knight.vox] File loaded in 0.098 ms
WARNING: FILEIO: [resources/models/vox/chr_sword.vox] Failed to open file
WARNING: MODEL: [resources/models/vox/chr_sword.vox] Failed to load VOX file
WARNING: MESH: [resources/models/vox/chr_sword.vox] Failed to load mesh data, default to cube mesh
INFO: VAO: [ID 3] Mesh uploaded successfully to VRAM (GPU)
WARNING: MATERIAL: [resources/models/vox/chr_sword.vox] Failed to load material data, default to white material
WARNING: [resources/models/vox/chr_sword.vox] File loaded in 0.019 ms
WARNING: FILEIO: [resources/models/vox/monu9.vox] Failed to open file
WARNING: MODEL: [resources/models/vox/monu9.vox] Failed to load VOX file
WARNING: MESH: [resources/models/vox/monu9.vox] Failed to load mesh data, default to cube mesh
INFO: VAO: [ID 4] Mesh uploaded successfully to VRAM (GPU)
WARNING: MATERIAL: [resources/models/vox/monu9.vox] Failed to load material data, default to white material
WARNING: [resources/models/vox/monu9.vox] File loaded in 0.023 ms
...
```

I also try to manually load the file with `Vox_LoadFromMemory` which return `VOX_ERROR_INVALID_FORMAT`, but the file does start with 'VOX '. 

It might be due to using `unsigned long`(which is 8 bytes) when parsing the signature (`0x20584F56` is 4 bytes).

https://github.com/raysan5/raylib/blob/d47d7c000146ed90a3270ba507e4769cf80c86af/src/external/vox_loader.h#L545

### Environment

linux, ubuntu 18.04

### Code Example

https://github.com/raysan5/raylib/blob/master/examples/models/models_loading_vox.c

**Comment by raysan5** [comment]
@chengchingwen Thanks for reporting, just reviewed the loader, please could you retest it?

**Comment by chengchingwen** [comment]
Thanks, building with master seems to work fine.
