### ISSUE TITLE
[wiki] Working for Android (on Linux) uses an old NDK version

### ISSUE THREAD

**Issue by przemykomo** [raysan5/raylib#2188]
[The guide](https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux)) says to make a standalone toolchain with:
`python make_standalone_toolchain.py --arch arm --api 22 --install-dir=android_toolchain_ARM_API22`

Which on the newest android NDK (r23b installed from [aur](https://aur.archlinux.org/packages/android-ndk/)) gives an output:
```
WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm --api 22 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi22-clang++ src.cpp
```
Later in the build script section it says to use `arm-linux-androideabi-gcc` and `arm-linux-androideabi-ar` which don't exist in the `$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/` directory.
Blindly using `armv7a-linux-androideabi22-clang` and `llvm-ar` instead only got me to the point, where I'm supposed to create `lib/armeabi-v7a/libproject.so` and then gave errors:
```
ld: error: lib/armeabi-v7a/libraylib.a(rcore.o) is incompatible with armelf_linux_eabi
ld: error: lib/armeabi-v7a/libraylib.a(rshapes.o) is incompatible with armelf_linux_eabi
ld: error: lib/armeabi-v7a/libraylib.a(rtext.o) is incompatible with armelf_linux_eabi
ld: error: lib/armeabi-v7a/libraylib.a(android_native_app_glue.o) is incompatible with armelf_linux_eabi
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by raysan5** [comment]
@przemykomo feel free to update it

**Comment by przemykomo** [comment]
I have no idea on how to get raylib on android to work. I posted this issue hoping that somebody who knows could update the wiki.

**Comment by raysan5** [comment]
Wiki is under a review process by some users.
