### ISSUE TITLE
log2 is not available on Android

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#219]
https://github.com/raysan5/raylib/blob/master/src/rlgl.c#L1779

I solved it with log(MAX(texture->width, texture->height))/log(2) , not sure if this is correct? 
Also, I don't understand why I was able to compile plain C lib and example for android without errors. When I am using my Go bindings (https://github.com/gen2brain/raylib-go) I get undefined reference to log2.

**Comment by raysan5** [comment]
Hi @gen2brain!

This issue is already solved in [develop branch]( https://github.com/raysan5/raylib/blob/develop/src/rlgl.c#L1781), I usually work on that branch and it's quite ahead of `master`.

Probably it worked because you used `develop` branch... :P

**Comment by gen2brain** [comment]
Yes, sorry about that. And I thought I checked develop branch. Closing.
