### ISSUE TITLE
Error :65544

### ISSUE THREAD

**Issue by Lucas-Marcel** [raysan5/raylib#2197]
I'm trying to run a hello world application, but it fails  giving me this error

INFO: initializing raylib 4.0 WARNING GLFW: Error : 65544 Description: GLX: Failed to retrieve Visual for GLXFBConfig WARNING: GLFW: Failed to initialize Window FATAL : Failed to initialize Graphic Device

**Comment by raysan5** [comment]
This issue is related to GLFW library and it's usually related to outdated graphics drivers or a very old GPU not supporting OpenGL 3.3.

**Comment by Lucas-Marcel** [comment]
i fixed my issue, it was my video boarder driver, i compiled it, installed in my os and things are working now.
