### ISSUE TITLE
[rmodels] No support for gltf animation

### ISSUE THREAD

**Issue by TokyoSU** [raysan5/raylib#2204]
### Issue description
There is not support for gltf animation, but loading models is working fine.
There no LoadModelAnimationGLTF() defined but cgltf support animations loading.

### Environment
Compiled: Static with GRAPHICS_API_OPENGL_43
OS: Windows

### Issue Screenshot
None

### Code Example
[rmodels.c](https://github.com/raysan5/raylib/blob/20f4d8c147993b85b1ad1fc1f0b069aca0339544/src/rmodels.c#L1809)

### Other
I know you are busy but this feature is really required, blender iqm is really a pain to use, you cant export multi animation is one file !
Also blender iqm dont rotate the model when export (+Y) so in my raylib project, the model is looking at -Y.
I support the code would be pretty the same as IQM but using cgltf instead.

**Comment by raysan5** [comment]
@TokyoSU this feature is out-of-scope for the moment. Feel free to implement it yourself and send a PR for review.
