### ISSUE TITLE
[core] TakeScreenshot capturing outside display bounds

### ISSUE THREAD

**Issue by monkeybird** [raysan5/raylib#221]
The function `TakeScreenshot` at line 2174 in core.c, captures screen shots of a fixed size, even if the window is partially off screen. The result is that the off screen part of the resulting screen shot is completely black. For examples, see these screen shots I made using the current code:

* [image 1](https://cloud.githubusercontent.com/assets/19928139/22405575/3c78918c-e645-11e6-9ae7-32569a13213f.png):  Here the window is entirely in view. The screen shot looks as intended.
* [image 2](https://cloud.githubusercontent.com/assets/19928139/22405576/3c793e5c-e645-11e6-9e93-91d601ee2e98.png):  Here the window is partially off screen to the right.
* [image 3](https://cloud.githubusercontent.com/assets/19928139/22405574/3c75dad2-e645-11e6-886d-a20a8a6f2034.png):   Here the window is partially off screen at the bottom.

```c
 unsigned char *imgData = rlglReadScreenPixels(renderWidth, renderHeight)
```

This code can be fixed by clamping `renderWidth` and `renderHeight` to the size of the window actually visible on screen. This will result in smaller screen shot files for these cases.

**Comment by raysan5** [comment]
Hi @monkeybird, it seems this issue is GPU dependant, on my Surface Pro 3 with Intel graphics it works ok; if a part of the window is out of the screen, it captures the full render area... I'll try in other computers... which GPU and OS are you using?

Despite that fact, the expected behavior is capturing the full render area, independently of the visible part and independently of the GPU behaviour.

**Comment by monkeybird** [comment]
I hadn't considered the GPU dependence.

* OS: lubuntu 16.04
* GPU: GeForce GTX 750 Ti (proprietary 367.57 driver)

**Comment by raysan5** [comment]
Tested on NVIDIA Quadro 600 on Windows 10 64bit, it captures full render area independently of the visible part.

**Comment by monkeybird** [comment]
Well, if it works as intended, then I guess this issue can be closed. I'm am mostly concerned about the bits of garbage in the unfilled areas of the screen shots. It is a stretch, but this could contain sensitive information.

I dug a little deeper and found that this happens in the `rlglReadScreenPixels` call in `rlgl.c`:

```c
// Read screen pixel data (color buffer)
unsigned char *rlglReadScreenPixels(int width, int height)
{
    unsigned char *screenData = (unsigned char *)malloc(width*height*sizeof(unsigned char)*4);
    ...
```

This buffer is never zeroed out before being passed into `glReadPixels`.
A `memset` call on the buffer consistently gets rid of the garbage appearing in the screen shots.

```c
// Read screen pixel data (color buffer)
unsigned char *rlglReadScreenPixels(int width, int height)
{
    size_t size = width*height*sizeof(unsigned char)*4;

    unsigned char *screenData = (unsigned char *)malloc(size);
    memset (screenData, 0, size);

    // NOTE: glReadPixels returns image flipped vertically -> (0,0) is the bottom left corner of the framebuffer
    glReadPixels(0, 0, width, height, GL_RGBA, GL_UNSIGNED_BYTE, screenData);
    ...
```

**Comment by raysan5** [comment]
Hi @monkeybird, I can consider that point... actually, memory zeroing can be archive with:
```c
unsigned char *screenData = (unsigned char *)calloc(width*height*4, sizeof(unsigned char));
```
`calloc()` zeroes reserved memory, with a small performance impact, but considering image y-flipping it's acceptable.

Please, let me know if it works and I'll implement that change.

**Comment by monkeybird** [comment]
Yup, that works. Thanks.

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/raylib/commit/a08117155da1a0a439239ad8801a58b85f528014.
