### ISSUE TITLE
[models] get cant instancing working on vox model

### ISSUE THREAD

**Issue by SushilRagoonath** [raysan5/raylib#2211]
### Issue description

I'm using a vox model, I setup an instanced vs shader and set the SHADER_LOC_MATRIX_MODEL to instancedTransform(image below). it seems that the matrices arent being bound properly because according to renderdoc the color of the vertex is not bound. However one of the columns of the matrix is actually the color since it is R8G8B8A8 format.
This warning is relevant but I'm unsure how to resolve it.
INFO: SHADER: [ID 6] Shader attribute (vertexPosition) set at location: 0
INFO: SHADER: [ID 6] Shader attribute (vertexTexCoord) set at location: 1
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexTexCoord2
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexNormal
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexTangent
WARNING: SHADER: [ID 6] Failed to find shader attribute: vertexColor
INFO: SHADER: [ID 6] Shader uniform (mvp) set at location: 1
### Environment
Windows 10 visual studio 2022
c++
### Issue Screenshot

![Screenshot_4](https://user-images.githubusercontent.com/48589447/146230565-d94f8e58-a899-433c-8304-a611c5ab80fe.png)
![Screenshot_5](https://user-images.githubusercontent.com/48589447/146230583-1888916e-14a5-49fb-ad15-5d88be5a8a92.png)
this is the vs in, so the model is intact
![Screenshot_3](https://user-images.githubusercontent.com/48589447/146230950-4e6e7c85-db7d-41cd-8b3e-199ee5a66b6d.png)

### Code Example
  std::vector<Matrix> transforms;
  Material instanced;
   the material
    instanced = LoadMaterialDefault();
    instanced.shader = LoadShader("shaders/instanced.vs", "shaders/base.fs");
    instanced.shader.locs[SHADER_LOC_VERTEX_COLOR] = GetShaderLocationAttrib(instanced.shader, "vertexColor");
    instanced.shader.locs[SHADER_LOC_MATRIX_MODEL] = GetShaderLocationAttrib(instanced.shader, "instancedTransform");
    the draw 
    DrawMeshInstanced(vox1.meshes[0],instanced, &transforms[0], transforms.size());

**Comment by raysan5** [comment]
I reviewed it and I found a possible issue... but I don't know if it could be it. Please, could you give it a try? If does not work yet I'm afraid it would require debugging the code to see the values inside `DrawMeshInstanced()`.

**Comment by SushilRagoonath** [comment]
Not working yet, stepping trough DrawMeshInstanced it does not reach the inside of material.shader.locs[SHADER_LOC_VERTEX_COLOR] , I don't think it is finding vertexColor as an attribute. maybe the problem is caused earlier? I also have raylib source setup in my project so debugging is simple. let me know where to test

**Comment by raysan5** [comment]
@SushilRagoonath You should check `LoadShaderFromMemory()` function, locations are set there automatically on shader loading.

**Comment by SushilRagoonath** [comment]
Got it working, that fix you did is required also the base.fs in shader example does not use fragColor so it got optimized out. Thanks for the help
![Screenshot_6](https://user-images.githubusercontent.com/48589447/146370682-d32ece42-e393-44b6-9222-8ade44d70045.png)
.

**Comment by raysan5** [comment]
@SushilRagoonath Nice. Yeah, not used variables are optimized by the shader compiler.
