### ISSUE TITLE
Gestures enumerated type different in gestures.h and raylib.h

### ISSUE THREAD

**Issue by AudioMorphology** [raysan5/raylib#222]
This had me confused for ages, as SetGesturesEnabled() wasn't doing what I expected - I was looking at the type definition in gestures.h rather than raylib.h !

I'm not sure which is the better typedef. The one in gestures.h is a correct bitfield, though having GESTURE_NONE = 0 may be quite convenient. For this reason I haven't changed it myself and issued a PR, as I am not certain what dependencies there may be on GESTURE_NONE == 0;

in raylib.h

typedef enum {
    GESTURE_NONE        = 0,
    GESTURE_TAP         = 1,
    GESTURE_DOUBLETAP   = 2,
    GESTURE_HOLD        = 4,
    GESTURE_DRAG        = 8,
    GESTURE_SWIPE_RIGHT = 16,
    GESTURE_SWIPE_LEFT  = 32,
    GESTURE_SWIPE_UP    = 64,
    GESTURE_SWIPE_DOWN  = 128,
    GESTURE_PINCH_IN    = 256,
    GESTURE_PINCH_OUT   = 512
} Gestures;

in gestures.h

typedef enum {
        GESTURE_NONE        = 1,
        GESTURE_TAP         = 2,
        GESTURE_DOUBLETAP   = 4,
        GESTURE_HOLD        = 8,
        GESTURE_DRAG        = 16,
        GESTURE_SWIPE_RIGHT = 32,
        GESTURE_SWIPE_LEFT  = 64,
        GESTURE_SWIPE_UP    = 128,
        GESTURE_SWIPE_DOWN  = 256,
        GESTURE_PINCH_IN    = 512,
        GESTURE_PINCH_OUT   = 1024
    } Gestures;

**Comment by raysan5** [comment]
Ouch! Thanks for pointing this out @AudioMorphology! 

Actually, the good one is `raylib.h`, also notice that `gestures.h` enum is only in case you're using `gestures.h` as a standalone library (independently of raylib) to process touch events into gestures...

Anyway, updated in commit https://github.com/raysan5/raylib/commit/30bb24aa6e80fe8ecc9eddc4efd008ecc89b60f4
