### ISSUE TITLE
[models] ExportMesh exports broken cube

### ISSUE THREAD

**Issue by siwekm** [raysan5/raylib#2220]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description
ExportMesh() exports broken cube (see pic.). Blender cant even open the file.

After changing the indexing of the faces from 0 to 1:
`for (int i = 1; i <= mesh.triangleCount; i++)`
the obj file can be opened in blender, but still produces the same broken cube.

### Environment
OS: Manjaro 5.13
INFO:     > Vendor:   AMD
INFO:     > Renderer: AMD RENOIR (DRM 3.41.0, 5.13.19-2-MANJARO, LLVM 11.1.0)
INFO:     > Version:  4.6 (Core Profile) Mesa 21.1.7 
INFO:     > GLSL:     4.60

### Issue Screenshot
![2021-12-17_10-20](https://user-images.githubusercontent.com/22203991/146521488-88630089-6427-4395-ba5c-a315c4760bb2.png)

### Code Example
`Mesh meshCube = GenMeshCube(2, 2, 2);`
`std::cout<<ExportMesh(meshCube, "cube.obj")<<std::endl;`

**Comment by raysan5** [comment]
Reviewed, it should work now.
