### ISSUE TITLE
[textures] `ImageDraw()` and `ExportImage()` (.png) does not support f32bit per channel image data

### ISSUE THREAD

**Issue by rmn20** [raysan5/raylib#2222]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I created PIXELFORMAT_UNCOMPRESSED_R32 format images, tried to combine them into one large image and export, but for some reason the image file was empty and rendering was broken. I replaced ImageDraw with memcpy and it helped fix the rendering with texture created from these images, but export was still broken.

### Environment

Windows 8.1 64x
ATI Technologies Inc.
AMD Radeon HD 8330
GLSL 4.60

**Comment by raysan5** [comment]
@rmn20 You are right, `ImageDraw()` does not support f32bit format images at this moment.

Afaik, PNG only supports up to [16bit per channel](http://www.libpng.org/pub/png/spec/1.1/PNG-Chunks.html) but `stb_image_export` only supports up to 8bit per channel image export.
