### ISSUE TITLE
[textures] LoadTextureCubemap unloads image (there is no indication anywhere that it should)

### ISSUE THREAD

**Issue by rmn20** [raysan5/raylib#2223]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Since LoadTextureFromImage doesn't unload the image after creating the texture, I expected similar behavior from LoadTextureCubemap, because it wasn't specified otherwise anywhere. But for some reason my app was crashing when I tried to unload the image after calling LoadTextureCubemap. Removing UnloadImage call helped to fix this problem.

### Environment

Windows 8.1 64x
ATI Technologies Inc.
AMD Radeon HD 8330
GLSL 4.60

**Comment by raysan5** [comment]
@rmn20 Reviewed! In case of `CUBEMAP_LAYOUT_LINE_VERTICAL` the input image was directly assigned to internal image, now we are doing a copy, so original image.data is not unloaded by the function.
