### ISSUE TITLE
[textures] LoadTextureCubemap doesn't work with CUBEMAP_LAYOUT_LINE_VERTICAL

### ISSUE THREAD

**Issue by rmn20** [raysan5/raylib#2224]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Honestly I don't understand what's going on here. I was creating a vertical cubemap using RenderTexture2D, I was able to export it in .png image and it looked fine and was VERTICAL, but for some reason the texture was pure black when I tried to render it. Replacing CUBEMAP_LAYOUT_LINE_VERTICAL with CUBEMAP_LAYOUT_AUTO_DETECT fixed this issue...

### Environment

Windows 8.1 64x
ATI Technologies Inc.
AMD Radeon HD 8330
GLSL 4.60

Windows 7 64x
NVIDIA GeForce GT 710

**Comment by raysan5** [comment]
@rmn20 Reviewed code should work now... Please note that `LoadTextureCubemap()` is not completely implemented (`CUBEMAP_LAYOUT_PANORAMA` not supported yet) and it was barely tested.
