### ISSUE TITLE
[rmodels] Wrongly rotated top cap in cylinder mesh

### ISSUE THREAD

**Issue by siwekm** [raysan5/raylib#2225]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Cylinder mesh generated by `GenMeshCylinder()` have wrongly turned top cap.

### Environment

OS: Manjaro 5.13
INFO: > Vendor: AMD
INFO: > Renderer: AMD RENOIR (DRM 3.41.0, 5.13.19-2-MANJARO, LLVM 11.1.0)
INFO: > Version: 4.6 (Core Profile) Mesa 21.1.7
INFO: > GLSL: 4.60

### Issue Screenshot

![2021-12-18_17-23](https://user-images.githubusercontent.com/22203991/146648540-51f82f66-65cc-429b-b796-c6556705471b.png)

![2021-12-18_17-23_1](https://user-images.githubusercontent.com/22203991/146648543-1b4ebb82-08f8-4834-9dc3-21772c716c14.png)

**Comment by siwekm** [comment]
`par_shapes_rotate(capTop, PI, (float[]){ 0, 1, 0 });`

seems to fix the issue

**Comment by raysan5** [comment]
@siwekm Reviewed. It should work ok now.
