### ISSUE TITLE
[rlgl] Alpha blending not working as expected for RenderTexture

### ISSUE THREAD

**Issue by rmn20** [raysan5/raylib#2227]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

The current alpha blending is broken, while the RGB channels are fine, the alpha channel results are incorrect.
Here's how it's implemented now:
`case RL_BLEND_ALPHA: glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA); glBlendEquation(GL_FUNC_ADD); break;`

For example, if you have an src alpha 0.5 and dest alpha 1.0, the resulting alpha will be equal to this:
`0.5 * 0.5 + 1.0 * (1.0 - 0.5) = 0.75`
Which is obviously incorrect.

I think proper blending should be implemented like this:
`glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ONE, GL_ONE_MINUS_SRC_ALPHA)`

### Environment

Windows 8.1 64x
ATI Technologies Inc.
AMD Radeon HD 8330
GLSL 4.60

### Issue Screenshot

I tried to draw a semi-transparent texture on RenderTexture2D cleaned with #463136FF and then draw this RenderTexture2D on screen cleaned with RAYWHITE.
![image](https://user-images.githubusercontent.com/33938415/146649921-e6ebae5d-10a7-4e00-a0c0-354e721de22f.png)
I exported my RenderTexture2D to a .png image and those white pixels were transparent.
![image](https://user-images.githubusercontent.com/33938415/146649999-f1f1dcef-1f1d-4f21-92d9-ef1efc5edf3a.png)

**Comment by GoldenThumbs** [comment]
Can I download the image you're using? To *me* this looks like a problem with your image and not necessarily raylib, but I would like to check to make sure this is the case.

**Comment by rmn20** [comment]
I can't provide you this image at the moment, but this problem has been reproducted by another user on discord. This happens with any semitransparent image actually.

**Comment by raysan5** [comment]
@rmn20 I'm afraid `glBlendFuncSeparate()` requires OpenGL 4.0 and raylib uses OpenGL 3.3 by default or even older versions.

Could this issue be related to https://github.com/raysan5/raylib/issues/1121?

**Comment by rmn20** [comment]
![image](https://user-images.githubusercontent.com/33938415/147121688-92ccbd08-ed9b-4d3d-9e00-4e9d4c6b1c1a.png)
I believe glBlendFuncSeparate is available since OpenGL 1.4 :)
I think this is the same problem as in 1121.

**Comment by raysan5** [comment]
@rmn20 You are right, it seems it was added into core on OpenGL 2.0, I confused it with `glBlendFuncSeparatei()` while looking at the [official specs](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendFuncSeparate.xhtml).

In any case, did you try the solution proposed in [#1121](https://github.com/raysan5/raylib/issues/1121)?

**Comment by rmn20** [comment]
I haven't tried it yet, but it should work fine in my program, I don't need an alpha channel here.
