### ISSUE TITLE
[audio] `PlaySoundMulti()` does not use correct pitch

### ISSUE THREAD

**Issue by dbechrd** [raysan5/raylib#2231]
### Issue description

`PlaySoundMulti` does not respect the pitch value set by `SetSoundPitch`.

The reason is this line:

https://github.com/raysan5/raylib/blob/5499388a4c2623176e1f7aa8e07236a72b3a7fe5/src/raudio.c#L1042

Which should be changed to:

    SetAudioBufferPitch(AUDIO.MultiChannel.pool[index], sound.stream.buffer->pitch);

This is because `SetAudioBufferPitch` does more than just an assignment to pitch internally; it also sets the sample rate of the `ma_data_converter` via `ma_data_converter_set_rate(...)`.

You may also want to change the line above that to use `SetAudioBufferVolume` instead of `volume = ` in case additional logic gets added to the `SetAudioBufferVolume` setter in the future.

**Comment by raysan5** [comment]
@dbechrd Thanks for the improvement! Reviewed!
