### ISSUE TITLE
[audio] Feature request: sound looping

### ISSUE THREAD

**Issue by cyberic99** [raysan5/raylib#2245]
I would be useful to have an option to loop sounds, forever or a specific number of times

For now it seems that only music streams can loop

**Comment by raysan5** [comment]
@cyberic99 This feature is out of scope for now. If you need a looping sound you can use a Music instead or manage the looping manually replaying the Sound when finished (`IsSoundPlaying()`).

**Comment by cyberic99** [comment]
OK @raysan5 , I understand. For my project I need to loop very short wave files, in a gapless way. I still think it could be useful for some users, but I'll try to implement it in my own fork, then.

thanks

**Comment by objarni** [comment]
For what it's worth, I stumbled upon this today too. Use case: small airplane game with engine sounds 'on repeat' - want to change frequency to indicate speed / shut off when stalling. While some engine folks might call it 'music', it sure feels weird. But I'll go for it today, not a commercial game :)
