### ISSUE TITLE
[Renederer] raylib doesnt draw modules when using multithreading(pthread) with DrawModulesEX

### ISSUE THREAD

**Issue by Abdelilah-Majid** [raysan5/raylib#2247]
Please, before submitting a new issue verify and check:

 - [ x ] I tested it on latest raylib version from master branch
 - [ x ] I checked there is no similar issue already reported
 - [ x ] My code has no errors or misuse of raylib

### Issue description
i am working on a game engine and i want to use multithreading with my Renderer3D in the DrawModulesEX becoz when drawing a lot of modules on a single thread the linux gpu driver has a big overhead coz it consume all of the thread resurces so i want to use multithreading with pthread to get rid of that overhead; this is not very true in modern hardware and drivers but with my 12 year old integrated graphics card and becoz i am planing to target old low end hardware with the games made with this game engine that gpu driver overhead is my biggest enemy right now;

so i have multithreaded the DrawModulesEX with pthread and the results wore unpleasant;
when using the main thread everything is being drawn but with multithreading nothing is drawn

first i thought it is coz i need to have beginDrawing() and beginMode3D() in each thread so i did just that and i removed then from main() and it gave me a black screen;

i dont know what is happening or what i should do, it seems like every thread is independent of the main thread where the real game world and graphics is, like every thread has its own screen that it draw to and i cant see that screen   
### Environment

pc, fedora linux x64, opengl 2.1, an old integrated intel graphics card(12 year old or so by now)

### Issue Screenshot

this is single threaded

![Cheese_Sun-26Dec21_15 52](https://user-images.githubusercontent.com/50689412/147411831-30ee7ef1-2250-47d0-a3b1-037f84707fed.png)
![Cheese_Sun-26Dec21_15 53](https://user-images.githubusercontent.com/50689412/147411833-b953ef02-a05c-4f66-b26e-f103f0851d19.png)

this is multithreaded

![Cheese_Sun-26Dec21_15 55](https://user-images.githubusercontent.com/50689412/147411891-8885c771-49e9-4eec-b48d-8cb64a273e9f.png)
![Cheese_Sun-26Dec21_15 55_000](https://user-images.githubusercontent.com/50689412/147411893-129aec77-7c7a-4e6c-9c0c-1a66091a6715.png)

this is multithreaded with beginDraw and beginMode3D in the Renderer3D and also i end them there and they are not in the main while or the main thread

![Cheese_Sun-26Dec21_15 58](https://user-images.githubusercontent.com/50689412/147411975-c02fb27b-55b3-4b2b-8af4-112a0f9bf366.png)
![Cheese_Sun-26Dec21_15 58_000](https://user-images.githubusercontent.com/50689412/147411977-e8e8eb41-4907-4bed-b32e-0aae2cbe2b73.png)

### Code Example

this is the renderer3D_main with the multithreaded code

```
void Renderer3D_main(Gabriel *gabriel, Renderer3D *renderer3D)
{

	unsigned int *rnederer3D_draw_start = malloc(sizeof(unsigned int) * gabriel->number_of_threads);
	unsigned int *rnederer3D_draw_end = malloc(sizeof(unsigned int) * gabriel->number_of_threads);

	bool is_this_the_draw_threads_start_end_int = true;

			unsigned int amount = renderer3D->number_of_existing_modules/gabriel->number_of_threads;
			unsigned int amount_scaler = gabriel->number_of_threads-1;

	for(unsigned int i=0; i < gabriel->number_of_threads; i++)
		{
			if(is_this_the_draw_threads_start_end_int){
				rnederer3D_draw_start[i] = 0;
				rnederer3D_draw_end[i] = renderer3D->number_of_existing_modules-(amount*amount_scaler);

				//printf("i: %d, rnederer3D_draw_start[i]: %d, rnederer3D_draw_end[i]: %d\n",
							// i, rnederer3D_draw_start[i], rnederer3D_draw_end[i]);

				amount_scaler--;
				is_this_the_draw_threads_start_end_int = false;
			}else{
				rnederer3D_draw_start[i] = rnederer3D_draw_end[i-1];
				rnederer3D_draw_end[i] = renderer3D->number_of_existing_modules - amount*amount_scaler;


				//printf("i: %d, rnederer3D_draw_start[i]: %d, rnederer3D_draw_end[i]: %d\n",
							// i, rnederer3D_draw_start[i], rnederer3D_draw_end[i]);
				amount_scaler--;
			}

		}



	Renderer3D_LOD_gen(renderer3D);
	Renderer3D_View_calling_main(gabriel, renderer3D);

	for(unsigned int i=0; i < gabriel->number_of_threads; i++)
		{
			intptr_t *args = malloc(sizeof(intptr_t)*4);

			args[0] = (intptr_t)gabriel;
			args[1] = (intptr_t)renderer3D;
			args[2] = (intptr_t)&rnederer3D_draw_start[i];
			args[3] = (intptr_t)&rnederer3D_draw_end[i];

			pthread_create(&gabriel->threads_arr[i], NULL, &Renderer3D_draw, args);

		}

	for(unsigned int i=0; i < gabriel->number_of_threads; i++)
		{

			pthread_join(gabriel->threads_arr[i], NULL);

		}
}
```

and this is the renderer3D_draw

```
void *Renderer3D_draw(void *ptr_args)
{
	Gabriel * gabriel = (Gabriel*)(((intptr_t*)ptr_args)[0]);

	Renderer3D * renderer3D = (Renderer3D*)(((intptr_t*)ptr_args)[1]);

	unsigned int start = *(unsigned int *)(((intptr_t*)ptr_args)[2]);

	unsigned int end = *(unsigned int*)(((intptr_t*)ptr_args)[3]);



	unsigned int drawn_models = 0;

	//BeginDrawing(); //this is enabled in the last screenshot 
		//ClearBackground(WHITE); //this is enabled in the last screenshot 
		//BeginMode3D(*renderer3D->View_calling_optimizer.camera_3D); //this is enabled in the last screenshot 
		//DrawGrid(100, 1.0f);
	for (unsigned long long int i = start; i < end; i++) {
			if (renderer3D->Modules[i].visible_by_engine) {
				if (renderer3D->Modules[i].visible) {
					DrawModelEx(renderer3D->Modules[i].model,
						    renderer3D->Modules[i].pos,
						    renderer3D->Modules[i].rotation_axis,
						    renderer3D->Modules[i].rotation_angle,
						    renderer3D->Modules[i].scale,
						    renderer3D->Modules[i].color);

					//if(i>80)
						//printf("shit, what hapened");

					//gabriel->Console->number_of_drawn_meshes++;
					drawn_models++;
				}
			}
	}


		//EndMode3D(); //this is enabled in the last screenshot 

	//EndDrawing(); //this is enabled in the last screenshot 
	printf("drawn models = %d\n", drawn_models);

	return NULL;
}

```
NOTE: when i do printf("drawn models = %d\n", drawn_models); it prints that there are some models bieng drawn

**Comment by raysan5** [comment]
@Abdelilah-Majid I'm afraid OpenGL does not support multithreading.

**Comment by Abdelilah-Majid** [comment]
okay

**Comment by Abdelilah-Majid** [comment]
that is sad

**Comment by Abdelilah-Majid** [comment]
but thank you
