### ISSUE TITLE
[textures] LoadImageRaw is broken

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#225]
textures_raw_data example is broken after commit 14cdd7f

    int bytes = fread(image.data, size, 1, rawFile);

Return value here will always be 1, number of elements. I fixed it by changing order of size and 1, but that is probably not efficient?

**Comment by raysan5** [comment]
Hey @gen2brain! Good catch! I'll review all `fread()` calls around the code...

**Comment by raysan5** [comment]
Corrected in commit https://github.com/raysan5/raylib/commit/afcd748fdf2d4f379f7a3be1706c1d6cd2ff504d

I also reviewed all other `fread()` around the code (just in case), it seems that `fread()` usage is a bit ambiguous and implementation dependant...

Some references I checked:
http://stackoverflow.com/questions/8589425/how-does-fread-really-work
http://stackoverflow.com/questions/295994/what-is-the-rationale-for-fread-fwrite-taking-size-and-count-as-arguments
