### ISSUE TITLE
[core] Wayland support?

### ISSUE THREAD

**Issue by colesnicov** [raysan5/raylib#2252]
### Issue description

Hello.
I'm sorry **it's not BUG**, but it's probably _not worth writing on REDDIT_, **it's a question directly to the author of RAYLIB**.

Raylib creates windows. Are you using GLFW to create windows, do you plan to implement support for wayland / weston in the future? 
PS. **Wayland exists for almost all platforms** except the WEB.

**Comment by raysan5** [comment]
@colesnicov Wayland support is already implemented in raylib, just compile it the proper flag: `USE_WAYLAND_DISPLAY` (defined in Makefile).

**Comment by colesnicov** [comment]
@colesnicov https://github.com/raysan5/raylib/issues/1376

**Comment by colesnicov** [comment]
https://github.com/raysan5/raylib/issues/4648
