### ISSUE TITLE
[build] Use system OpenAL on OS X

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#226]
OpenAL installed with brew on OS X is "keg only", it doesn't link includes and libs to not conflict with system libs.

In Go bindings I fixed it like this https://github.com/gen2brain/raylib-go/commit/e56840b91ea03755e395bb097b0862f3ba2d9bf5 

I also removed stdbool type in that commit so clang doesn't complain and build now works (affects also Android build with newer ndk where clang is default). In bindings I need bool as either integer or _Bool type but I cannot use both.

**Comment by raysan5** [comment]
Thank you very much for the patch! Implemented in commit https://github.com/raysan5/raylib/commit/05f039f85fb43f9ae4598747a4d9c6770ec5774b

Unfortunately, I don't have an OS X to test it but hopefully it will be all right.

Thanks also for pointing the stdbool type issue; personally, never liked to include that header...
