### ISSUE TITLE
[core] Support monitor selection on fullscreen

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#227]
Some users require raylib window in a different monitor when turning to fullscreen mode. Some option to choose target monitor could be useful.

**Comment by OdnetninI** [comment]
Glfw give us some help :)
http://www.glfw.org/docs/3.0/monitor.html

**Comment by raysan5** [comment]
Added a couple of functions on commit https://github.com/raysan5/raylib/commit/9cfaa81a7e7741f03db1f9579aa0b49bee42cdd7
