### ISSUE TITLE
[text] Function request: Draw codepoints array

### ISSUE THREAD

**Issue by wtjcn** [raysan5/raylib#2275]
I need a function to Draw Array of Codepoint, maybe:

void DrawCodepointArray(Font font, int *codepoint, int len, Vector2 position, float fontSize, Color tint);

**Comment by catmanl** [comment]
Do *others* need this function? If not, think of how you would implement it

**Comment by raysan5** [comment]
@wtjcn I see the point of that function and I'm considering adding it.

**Comment by raysan5** [comment]
Here a code snippet for convenience:
```c
void DrawTextCodepoints(Font font, int *codepoints, int count, Vector2 position, float fontSize, Color tint)
{
    for (int i = 0; i < count; i++) 
    {
        DrawTextCodepoint(font, codepoints[i], position + offset, fontSize, tint);
        // TODO: Compute next unicode codepoint position offset
    }
}
```

**Comment by siddharthroy12** [comment]
I've submitted a pull request adding this function
#2308

**Comment by raysan5** [comment]
@siddharthroy12 thanks for the improvement, I'm merging it but keep in mind that it could change the name or parameters, this function is still on design phase.
