### ISSUE TITLE
[feature] add xml read write

### ISSUE THREAD

**Issue by annopnod** [raysan5/raylib#2279]
add xml read write to save/load game
and 3d support dae file COLLADA

**Comment by raysan5** [comment]
@annopnod I'm afraid those two features are out-of-scope for raylib. About XML, here there are some [XML loading libraries](https://github.com/nothings/single_file_libs#miscellaneous) and about COLLADA, the fileformat is HUGE, only supporting it will imply the same amount of code that ALL raylib has at this moment.
