### ISSUE TITLE
[raudio] Very glitchy web audio on examples site with brave browser

### ISSUE THREAD

**Issue by creikey** [raysan5/raylib#2292]
### Issue description

Sound is very glitchy and slow, maybe because the framerate is bad? I get 60 on the examples with an fps counter on the website though. Task manager also showed the cpu was not pegged completely by another application or anything like that. 

### Environment

Windows 11 i5 10th gen integrated graphics

### Issue Screenshot

https://user-images.githubusercontent.com/28424206/149930335-cc532202-7b66-4370-8efa-370333fe0d25.mp4

### Code Example

The example on the website

**Comment by creikey** [comment]
This problem does not exist on Edge

**Comment by raysan5** [comment]
@creikey I neither have this problem with Chrome, it seems it could be browser-specific. In that case is difficult to track the reasons...

**Comment by Peter0x44** [comment]
Not a problem in both Firefox and Chrome for me, seems like a browser issue if anything.

**Comment by creikey** [comment]
https://github.com/brave/brave-browser/issues/10619 did some digging and this issue about it has been open for two years! Guess it's just a brave problem...
