### ISSUE TITLE
[raygui] cannot change textbox color

### ISSUE THREAD

**Issue by annopnod** [raysan5/raylib#2295]
raygui cannot change textbox color
 
<img width="960" alt="github" src="https://user-images.githubusercontent.com/6957642/150280275-f3d05da6-5dc2-4329-8c8a-ace4b01976d0.png">

see code::
my project is harvest moon clone enable modding using lua script
https://github.com/diy-powercircuitandsoftware/MyHarvest

**Comment by raysan5** [comment]
@annopnod It seems this issue belongs to https://github.com/raysan5/raygui. In any case, `GuiTextBox()` style can be customized using `GuiSetStyle(int control, int property, int value)` function:
```
GuiSetStyle(TEXTBOX, BASE_COLOR_PRESSED, 0xff0000ff);   // Set the base color when control in pressed state to red
```
