### ISSUE TITLE
[core] No way to read html5 available max resolution

### ISSUE THREAD

**Issue by nezvers** [raysan5/raylib#2301]
### Issue description
Since Raylib 5K jam is happening in HTML5 form on the itch.io platform, it shows a lack of functionality when it comes to reading the given embed area resolution.
I have a pixel art adaptive scaling solution but I can't utilize it on itch.io, because ScreenWidth shows only initially set window size. `IsWindowResized()` also doesn't seem to work even when enabling itch's fullscreen.
`IsWindowFullscreen()` also doesn't react to enabling fullscreen but that might be impossible to know.

### Environment

HTML5 on itch.io

### Issue Screenshot
Itch page was set for 1280x720 resolution but the game 640x360.
![image](https://user-images.githubusercontent.com/26794315/150521238-cc988f65-2281-41ed-bbb4-76d41da3f38a.png)

### Code Example

```C
void DrawScene(){
    const char* scr = TextFormat("Screen: %d, %d", GetScreenWidth(), GetScreenHeight());
    const char* rend = TextFormat("Render: %d, %d", GetRenderWidth(), GetRenderHeight());
    const char* mon = TextFormat("Monitor: %d, %d", GetMonitorWidth(GetCurrentMonitor()), GetMonitorHeight(GetCurrentMonitor()));
    const char* full = TextFormat("Is fullscreen: %s", IsWindowFullscreen() ? "true" : "false");
    
    DrawText(scr, 2, 2, 8, GRAY);
    DrawText(rend, 2, 12, 8, GRAY);
    DrawText(mon, 2, 22, 8, GRAY);
    DrawText(full, 2, 32, 8, GRAY);
}
```

**Comment by raysan5** [comment]
Yeap, I'm aware of those limitations. Actually, itchio embeds the game into an iframe so it's even more difficult to control resize/fullscreen from the low-level C code. For those specific use cases, higher-level JS code would be required. That's out of the scope of raylib.

Still, you can set a framebuffer size in raylib, render to a RenderTexture at desired size and scale to default framebuffer, it will be displayed at that size in the itchio page.

**Comment by nezvers** [comment]
I don't know how to use the framebuffer, but I'm utilizing Rendertexture for scaling.
```C
static void Update(void){
    UpdateMusicStream(music);
    if (IsWindowResized()){
        screenWidth = GetScreenWidth();
        screenHeight = GetScreenHeight();
        colID = (colID +1) % 2;
        col = colID ? YELLOW : WHITE;
        UpdateResolution();
    }
    Draw();
}

static void Draw(void){
    const Vector2 orig = (Vector2){0.0f, 0.0f};
    // Viewport
    BeginTextureMode(viewport);
        DrawScene();
    EndTextureMode();

    // Window
    BeginDrawing();
        ClearBackground(col);
        DrawTexturePro(viewport.texture, *(Rectangle*)&viewRect, *(Rectangle*)&screenRect, orig, 0.0f, WHITE);
    EndDrawing();
}
```
