### ISSUE TITLE
Unable to build examples on Linux

### ISSUE THREAD

**Issue by kewp** [raysan5/raylib#231]
I'm getting reference errors when building the examples

> 
> karl@karl-cerecam:~/tst/raylib/examples$ make PLATFORM=PLATFORM_DESKTOP
> gcc -o core_basic_window core_basic_window.c -O2 -s -Wall -std=c99 -I. -I../src -I../src/external -I../release/linux -I/usr/local/include/raylib/ -L. -L../src -L../release/linux -lraylib -lglfw3 -lGL -lopenal -lm -lpthread -ldl -DPLATFORM_DESKTOP 
> ../release/linux/libraylib.a(core.o): In function `ShowCursor':
> core.c:(.text+0x3d7d): undefined reference to `XUndefineCursor'
> ../release/linux/libraylib.a(core.o): In function `HideCursor':
> core.c:(.text+0x3dd3): undefined reference to `XCreateBitmapFromData'
> core.c:(.text+0x3dfb): undefined reference to `XCreatePixmapCursor'
> core.c:(.text+0x3e20): undefined reference to `XDefineCursor'
> core.c:(.text+0x3e30): undefined reference to `XFreeCursor'

**Comment by kewp** [comment]
Fixed by uncommenting line 150 in Makefile (why do I need to do this?)

> # on XWindow could require also below libraries, just uncomment
> LIBS += -lX11 -lXrandr -lXinerama -lXi -lXxf86vm -lXcursor

**Comment by gen2brain** [comment]
That line is required on all Linux distros. I tried in Ubuntu, Fedora and Gentoo. Maybe the only case where it would not be required is if Wayland is used instead of X, I think glfw has some support for wayland.

I don't know of any Linux distro that works only with wayland and without X support.

**Comment by raysan5** [comment]
Hi @gen2brain, thank you very much for the info!

Uncommented by default on commit https://github.com/raysan5/raylib/commit/2ac956208db4e0fcde5081a03a8fc3ba2dedff9b

**Comment by OdnetninI** [comment]
@raysan5 @gen2brain I tried to compile it with only wayland, and it requires Xorg libraries. Probably system's libraries need an update to remove dependencies. And with XOrg, is also needed (obiously).
