### ISSUE TITLE
[rcore] Colour changing square not rendering

### ISSUE THREAD

**Issue by 1234CoderLoader56789** [raysan5/raylib#2310]
Hello! I was trying to make a game in raylib when I stumbled upon a problem.

The problem was about making a colour changing square. 

I have this code:

```cpp
#include "raylib.h" // Base file

int main()
{
    InitWindow(1080, 720, "Window");

    SetTargetFPS(60);

    while(!WindowShouldClose())
    {
    ClearBackground(BLACK)
        DrawRectangle(0, 0, 100, 100,
 (Color)  {(unsigned char) GetTime(), (unsigned char) GetTime(),
       (unsigned char) GetTime(), (unsigned char) GetTime()}); // Should make a square changing color from black to white. 
    }
}

```

**Comment by DasLixou** [comment]
Oh yeah I see the problem. You should use 255 in the 4. slot of color (for the alpha). And then, if it still doesn’t work, try to print the GetTime() and see if it changes so fast as you expected and think how you can clamp the GetTime() between 0 and 255

**Comment by 1234CoderLoader56789** [comment]
Thank you so much @DasLixou! I didn't see that!

**Comment by DelinWorks** [comment]
Sorry to bother but does setting the color of anything wrap to 0 255 like when using fmod function you can pass something like 260 and it will be 5, because i think time only goes forward or am i missing something?

**Comment by raysan5** [comment]
It seeems BeginDrawing() and EndDrawing() are missing in your code...
