### ISSUE TITLE
[core] `GetMouseDelta()` X and Y don't work correctly on web

### ISSUE THREAD

**Issue by mandar1jn** [raysan5/raylib#2314]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Looking at the source code, it is clear that platform web is not supported by the functions mentioned above. I noticed this while working on my gamejam project. I might create a pr tomorrow. Note that the problem is not the mouse, but when using touch. I get there are the GetTouchX and Y functions, but touch doesn't give an option for when touch is released. If this would be used as a counter argument, then there is no reason why GetMousePosition does work.

### Environment

Building for the web

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example
Can't currently provide one

**Comment by raysan5** [comment]
@mandar1jn Are you sending a PR to solve this issue?
