### ISSUE TITLE
[rmodels] Being able to load one animation at a time

### ISSUE THREAD

**Issue by TokyoSU** [raysan5/raylib#2320]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

The exporter: https://github.com/lsalzman/iqm are able to export many animation (manually writing the anim name), but my models have 300+ animation, i cant export it manually (i reported this on the iqm git to allow export all animations), so if the iqm exporter wont give this feature (its what i through) then i can only accept it and export it one at a time, but raylib only accept one file (with all anims) because it return an array, and i dont want to mess with it :(
can you provide some workaround like returning only the animation, then i could use std::vector to store it instead.
I dont want to create a importer just to deal with this issue, and it can profit the other later if someone is blocked like me.

### Environment

Windows 10 (X64)

### Issue Screenshot

None

### Code Example

Maybe ModelAnimation LoadAnimation(const char* filename) or bool LoadAnimation(const char* filename, ModelAnimation* anim) ?

**Comment by raysan5** [comment]
@TokyoSU It shouldn't be a problem if your file only has one animation, despite the function returns an array you can just use the first one (`animations[0]`). Adding extra functionality to load only one animation implies additional problems to solve and the cost will be similar to loading all of them.
