### ISSUE TITLE
[Wiki] Update VS Code instructions for those using Windows Subsystem for Linux

### ISSUE THREAD

**Issue by msanatan** [raysan5/raylib#2321]
- [ ] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [ ] My code has no errors or misuse of raylib

### Issue description

I use Windows Terminal and the Windows Subsystem for Linux by default, makes my programming life easier for most things I do. However, the VS Code files don't work out of the box when WSL is the default shell.

### Environment

Windows 11, VS Code 1.63.2

### Issue Screenshot

Error when trying to debug

![raylib-debug-error-with-wsl-default](https://user-images.githubusercontent.com/2119378/151700549-adff859f-e8f0-4e89-9927-8e6837708781.png)

### Code Example

To fix we need to change one property twice in `.vscode/launch.json`: `"externalConsole": true,`. 

I've updated the Wiki in my fork, you can copy it to update the main one: https://github.com/msanatan/raylib/wiki/Using-raylib-in-VSCode

**Comment by raysan5** [comment]
@msanatan raylib Wiki is open for editing, feel free to update it.

**Comment by msanatan** [comment]
I got an error when I tried to at first, but I was able to edit now without a problem. It was probably something else. Thanks!
