### ISSUE TITLE
[raymath] Lerp Color

### ISSUE THREAD

**Issue by CrezyDud** [raysan5/raylib#2322]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I tried lerping color with this:
```
Color lerp_color(Color color, Color Goal, float speed)
{
    color.r = Lerp(color.r, Goal.r, down_time*speed/2000);
    color.g = Lerp(color.g, Goal.g, down_time*speed/2000);
    color.b = Lerp(color.b, Goal.b, down_time*speed/2000);
    color.a = Lerp(color.a, Goal.a, down_time*speed/2000);

    return color;
}
```
but it can't lerp back to white

### Environment

Linux, 4.6

**Comment by raysan5** [comment]
sorry, I can't see how this issue is related to raylib functionality

**Comment by CrezyDud** [comment]
it's a feature request
