### ISSUE TITLE
[raymath] Lerp Color

### ISSUE THREAD

**Issue by CrezyDud** [raysan5/raylib#2323]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Add functionality for lerping color to raymath

(feature request)

### Environment

Linux, GL 4.6

**Comment by raysan5** [comment]
Sorry, no plans to add this functionality for the moment, it can be implemented on user side.
