### ISSUE TITLE
[raygui] Word Wrapping in GuiDrawText from text_rectangle_bounds example

### ISSUE THREAD

**Issue by CrezyDud** [raysan5/raylib#2325]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Implement word wrapping to raygui, this would help with popup animations and generally for less manual text formatting.

### Code Example

[rectangle bounds example](https://github.com/raysan5/raylib/blob/master/examples/text/text_rectangle_bounds.c)

**Comment by raysan5** [comment]
@CrezyDud Sorry, no plans for the moment. Actually, it was removed from it some time ago.
