### ISSUE TITLE
[raygui] Option to not show GuiWindowBox's close button (+ gray out sperate option maybe)

### ISSUE THREAD

**Issue by CrezyDud** [raysan5/raylib#2326]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

To not show an x button when making a GuiWindowBox(for GuiMessageBox)

### Code Example

Just as an argument

**Comment by raysan5** [comment]
@CrezyDud Feel free to edit the function for your needs, no plans to change it.
