### ISSUE TITLE
[rcore] Segfault during Initialization of Raylib (Mesa 21.3.4)

### ISSUE THREAD

**Issue by wilsonHodgson** [raysan5/raylib#2327]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
I'm not sure if this is an issue with Raylib or with Mesa, but my project stopped running after installing updates on Manjaro Linux.
After some searching I found out the package that broke it was an update to Mesa, which went from 21.3.2 to 21.3.4

The issue resolves when I downgrade mesa back to 21.3.2.

There is apparently a bugfix release that hasn't been packaged for my system yet, so perhaps this is just an issue for specifically 21.3.4

I will update this issue after attempting to update mesa manually.

### Environment
Manjaro 
Linux Kernel 5.11.22-2
Mesa 21.3.4

### Output
```
INFO: Initializing raylib 4.1-dev
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Screen size:  1920 x 1080
INFO:     > Render size:  1920 x 1080
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 225
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 21.3.4
INFO:     > GLSL:     4.60
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
Segmentation fault (core dumped)
```

**Comment by wilsonHodgson** [comment]
### Update
mesa-21.3.5 still gives a segmentation fault, but doesn't print out any initialization logs.
```
LD_LIBRARY_PATH="/home/wilson/Projects/mesa/mesa-21.3.5/install/lib" ./duck
INFO: Initializing raylib 4.0
Segmentation fault (core dumped)
```

and just this month another mesa update was released,  22.0.0
```
LD_LIBRARY_PATH="/home/wilson/Projects/mesa/mesa-22.0.0-rc1/install/lib" ./duck
INFO: Initializing raylib 4.0
Segmentation fault (core dumped)
```

So this seems to definitely still be an issue.

**Comment by wilsonHodgson** [comment]
I did test this on the master branch, and 4.0, same error. In the log it says 4.1-dev which I assume is how the logs behaves on the master branch.

I also tried debugging, but GDB said the error was coming a symbol called "flock()" which is strange because I'm writing a flocking simulator and I only have a variable named flock, not a function.

Also when I stepped through, I only made it to the InitWindow function from Raylib core before that error was thrown with "flock".
So I suppose it could be an issue with my code, but It worked fine before I updated Mesa.

Those are all most details I have for now.
Thanks for investigating the issue.

**P.S. I'll rerun gdb later and share the output here**
**P.P.S happy valentines day**

**Comment by chriscamacho** [comment]
flock is a function to add an advisory lock to a file (this could be a device file)

Looking at the log, it shows shader handles so you're way past window init by the time you're hitting the GPU for shader handles...

**Comment by wilsonHodgson** [comment]
So no update yet, still have this issue after just updating the same system today.

Here's the GDB output in case anyone cares to look at it, but I'm going to look around in manjaro, and in mesa communities.
I'd like to have a better understanding of the issue soon.

**Thread 2**

```Thread 2 "duck_fl:disk$0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffec7ad640 (LWP 7171)]
0x000055555555b1a0 in flock ()
(gdb) bt
#0  0x000055555555b1a0 in flock ()
#1  0x00007ffff5849587 in ?? () from /usr/lib/dri/iris_dri.so
#2  0x00007ffff583d5fc in ?? () from /usr/lib/dri/iris_dri.so
#3  0x00007ffff583658c in ?? () from /usr/lib/dri/iris_dri.so
#4  0x00007ffff7bbe5c2 in start_thread () from /usr/lib/libc.so.6
#5  0x00007ffff7c43584 in clone () from /usr/lib/libc.so.6
(gdb) 
```

**Thread 1**
```
(gdb) thread 1
[Switching to thread 1 (Thread 0x7ffff7941100 (LWP 7167))]
#0  0x00007ffff7c3ca9d in syscall () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7c3ca9d in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff5841066 in ?? () from /usr/lib/dri/iris_dri.so
#2  0x00007ffff6495ef0 in ?? () from /usr/lib/dri/iris_dri.so
#3  0x00007ffff69c551c in ?? () from /usr/lib/dri/iris_dri.so
#4  0x00007ffff58becdb in ?? () from /usr/lib/dri/iris_dri.so
#5  0x00007ffff58d1724 in ?? () from /usr/lib/dri/iris_dri.so
#6  0x00007ffff58d232d in ?? () from /usr/lib/dri/iris_dri.so
#7  0x00007ffff58f023b in ?? () from /usr/lib/dri/iris_dri.so
#8  0x00007ffff591725e in ?? () from /usr/lib/dri/iris_dri.so
#9  0x00007ffff5a29fcf in ?? () from /usr/lib/dri/iris_dri.so
#10 0x00007ffff7e6556e in rlLoadShaderProgram () from /usr/lib/libraylib.so.400
#11 0x00007ffff7e677d8 in rlglInit () from /usr/lib/libraylib.so.400
#12 0x00007ffff7e7643f in InitWindow () from /usr/lib/libraylib.so.400
#13 0x00005555555563fc in main () at /home/wilson/Projects/duck_flock/main.c:14
```

**Comment by wilsonHodgson** [comment]
I just learned that mesa is deprecating the use of the intel driver. And I am using an intel cpu.
They recommend using the modesetting driver instead.

I will post once I get this fixed on my distro.
