### ISSUE TITLE
[cmake] Error when building with Cmake

### ISSUE THREAD

**Issue by TheAwesomeGem** [raysan5/raylib#2328]
### Issue description

I am getting this error when installing raylib through Cmake.

```
CMake Error in CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "raylib" configuration "Debug"`
```

Here is what my CmakeList.txt looks like

```
cmake_minimum_required(VERSION 3.21)
project(GameDev)

set(CMAKE_CXX_STANDARD 20)

find_package(raylib CONFIG REQUIRED)

add_executable(GameDev src/main.cpp)

target_link_libraries(GameDev PRIVATE raylib)
```

### Environment

Windows: 10
Clion: 2021.3.3
vcpkg: 2022-02-01-c76e0def147898591d9c35113b95e0b3f2eaa4d4
Triplet: x64-mingw-dynamic 

### Code Example

Install raylib through vcpkg and setup the Cmakelists.

**Comment by TheAwesomeGem** [comment]
It works fine if I write this

`target_include_directories(GameDev PRIVATE ${raylib_INCLUDE_DIRS})
target_link_libraries(GameDev PRIVATE ${raylib_LIBRARIES})`

But official docs didn't state I had to use the macros.

**Comment by raysan5** [comment]
@TheAwesomeGem I'm afraid I'm not maintaining the Cmake build system, it was user-contributed, feel free to join raylib Discord and ask in the specific CMake channel or wait in case some user can contribute to this issue.

**Comment by TheAwesomeGem** [comment]
Sounds good. Perhaps you can update the documentation in the meantime incase someone in the future might be having the same issue.

**Comment by raysan5** [comment]
@TheAwesomeGem Feel free to send a PR.

**Comment by Ezbob** [comment]
For other confused people coming here, the information when installing through VCPKG states you should include raylib with the statements:
```
    find_package(raylib CONFIG REQUIRED)
    target_link_libraries(main PRIVATE raylib)
```
But the raylib target does not expose the library paths or headers. So do what @TheAwesomeGem did and you should be alright. 
Also, depending the version of vcpkg you are using, you might need to use the upper-case RAYLIB_INCLUDE_DIRS and RAYLIB_LIBRARIES variables instead.
