### ISSUE TITLE
[raylib] Fix raylib misses header files

### ISSUE THREAD

**Issue by JonLiu1993** [raysan5/raylib#2335]
### Issue description

It seems that the current raylib package in vcpkg (version 4.0.0#2) misses something with raylib extras, like physac.h, raygui.h, etc. Those headers are included in "extras/... .h" folder and I've checked vcpkg include and there's no "extras", only raylib.h, raymath.h, rlgl.h and probably raudio.h. I think it should be also included into the include directory which is origin under the raylib / src / extras.

### Environment

Windows: 10
vcpkg: 2022-02-01-c76e0def147898591d9c35113b95e0b3f2eaa4d4
Triplet: x64-windows
raylib version: 4.0.0#2

### Issue Screenshot

![image](https://user-images.githubusercontent.com/63675417/153132898-a382abc0-ced7-4cd4-91d8-29a63092b504.png)

### Code Example

I fixed a user's issue in vcpkg, and submitted a pr to copy the .h file in the raylib/src/extras/ path of the source to the include directory of the package folder. I want to know if it is possible to do so
````
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index c96f4f5..938c93a 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -26,7 +26,11 @@ set(raylib_public_headers
     rlgl.h
     raymath.h
     raudio.h
-    )
+    extras/easings.h
+    extras/physac.h
+    extras/raygui.h
+    extras/rmem.h    
+)
 
 # Sources to be compiled
 set(raylib_sources

````

**Comment by raysan5** [comment]
@JonLiu1993 It seems this issue is related to `vcpkg` package system and not raylib, actually I don't maintain that system.

**Comment by JackBoosY** [comment]
@raysan5 Thanks for reply.
vcpkg uses raylib's cmake configure files to configure and build raylib itself. And we received an issue about the missing headers, see https://github.com/microsoft/vcpkg/issues/22935.

Can you please help us to confirm that?

Thanks.

**Comment by JackBoosY** [comment]
So I think we can accept install them in vcpkg side.
