### ISSUE TITLE
[rlgl] avoid malloc'ing on rlReadTexturePixels

### ISSUE THREAD

**Issue by trikko** [raysan5/raylib#2336]
This function:
```void *rlReadTexturePixels(unsigned int id, int width, int height, int format)```

returns pixels we have to free using RL_FREE().

Can we have an overload where we pass the pointer to fill with pixels, to avoid the malloc/free cycle so I can reuse the same pointer for every call?

**Comment by raysan5** [comment]
@trikko An alternative function to avoid the allocations will break raylib consistency, afaik there is no raylib function that receives a preallocated buffer for filling, that mechanism is very prone to errors and potentially unsecure...

I recommend that you call directly `glGetTexImage(GL_TEXTURE_2D, 0, glFormat, glType, pixels);` for that use case.

For completion, some info:

There are only 2 functions on `rlgl` that allocate (and return) the buffers for user management:

 - `rlReadTexturePixels()` - Buffer is returned for user management
 - `rlReadScreenPixels()` - Buffer is returned for user management

There are 3 more functions that actually require data allocations:

 - `rlLoadRenderBatch()`- Buffer managed internally
 - `rlGenTextureMipmapsData()` - Buffer managed internally, only on `GRAPHICS_API_OPENGL_11`
 - `rlGenNextMipmapData()` - Buffer managed internally, only on `GRAPHICS_API_OPENGL_11`

**Comment by ariankordi** [comment]
Can we re-investigate this? I would find it really useful for the utility I implemented: https://gist.github.com/ariankordi/c80f4f025973c0b7247f5146b3f42b37#file-rlbmputility-hpp-L70
To make a BMP image it copies the pixel data directly after the header into a pre-allocated buffer, making another malloc a waste.
For images that are e.g. 8 MB in size, double the memory is allocated which grows the heap to be larger than intended for environments like Emscripten.

The problem with calling an OpenGL function directly is that just defining it won't work on all platforms, e.g. on Linux where I see an error like `ld.lld: error: undefined reference: glReadPixels` - some platforms use GLAD and some don't.
