### ISSUE TITLE
Is the vcpkg version updated?

### ISSUE THREAD

**Issue by LedLoaf** [raysan5/raylib#2351]
Hello,

I'm learning about raylib and doing each example one by one. Unfortunately, The 3D cube picking example where you select the 3D cube with the mouse doesn't work. 

RayCollision isn't found.

Any help would be appreciated.

PS: Also once you hit the 3D examples it says to use 
camera.projection = CAMERA_PERSPECTIVE;					// camera mode type

This didn't work in my case, so after quickly seeing what there was to offer I used camera.type and it worked.

**Comment by LedLoaf** [comment]
Yes, it is apparently.

I downloaded it and did it manually and it worked just fine.

**Comment by raysan5** [comment]
It could be outdated, I'm afraid I don't maintain it.
