### ISSUE TITLE
[rtext] Pixelated text

### ISSUE THREAD

**Issue by terminalMaster** [raysan5/raylib#2355]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Fonts get blurry when using DrawTextureEx();

### Environment

Windows 10

### Issue Screenshot

![glitch](https://user-images.githubusercontent.com/85799662/155249341-c9cd9a60-c732-48ec-97a7-205c2195cc96.png)

**Comment by raysan5** [comment]
@terminalMaster I'm afraid that's the expected behaviour. raylib uses stb_truetype for text rasterization and it does not support ClearType rasterization. One possible solution is just `LoadFontEx()` with a higher font size and then draw it smaller, it will improve visual quality.
