### ISSUE TITLE
Change "License" to "Licence" when not used as a verb

### ISSUE THREAD

**Issue by CastimierDev** [raysan5/raylib#2357]
In American English the only correct spelling is "License", but in other forms of English the verb form is "License" as in "Licensed" but the noun form is "Licence" and in British English "Licence" is also acceptable as the verb form. 
This isn't really an important change but I thought this might be a thing to look into.

The definitive authority, The Oxford Dictionary, states:

"Usage—Note that in British English licence is the correct spelling for the noun and is also an acceptable variant spelling of the verb. In US English, both noun and verb are spelled license."

**Comment by raysan5** [comment]
Thanks for the detail. Good to know.
