### ISSUE TITLE
[textures] Load texture directly from pixel data

### ISSUE THREAD

**Issue by aaeberharter** [raysan5/raylib#2372]
Raylib itself does not support the direct creation of generic textures even tough the low level API `rlgl` supports it. At the moment I am doing

``` 
Texture2D texture;
texture.width = 100;
texture.height = 100;
texture.format = PIXELFORMAT_UNCOMPRESSED_R8G8B8;
texture.mipmaps = 1;
unsigned char* pixel_data = ...
texture.id = rlLoadTexture(pixel_data, texture.width, texture.height, texture.format, texture.mipmaps);
```

It would be nice to have a high level function in `raylib.h` which could handle this case.

**Comment by raysan5** [comment]
@aaeberharter I'm afraid this is an advance functionality that most users do not need. You can use the current process with `rlgl` to generate it.
