### ISSUE TITLE
[raymath] Vector2/Vector3 Division by Value.

### ISSUE THREAD

**Issue by AnilBK** [raysan5/raylib#2382]
### Issue description

Add Vector2/Vector3 Division by a Value.
Something like `Vector2DivideValue()`

Multiplication by value is already implemented as:
https://github.com/raysan5/raylib/blob/cda1324e87e0e3b3c1f488ac93a928d1b1b3d50b/src/raymath.h#L297-L303
(This can be used as an alternative to Vector2DivideValue() though.)

And, so are addition and subtraction by value.
https://github.com/raysan5/raylib/blob/cda1324e87e0e3b3c1f488ac93a928d1b1b3d50b/src/raymath.h#L226
https://github.com/raysan5/raylib/blob/cda1324e87e0e3b3c1f488ac93a928d1b1b3d50b/src/raymath.h#L242

Also  raylib-cpp already implements Division by value.
https://github.com/RobLoach/raylib-cpp/blob/c2900f60fa6785531a7e428e87962e77e28aa044/include/Vector2.hpp#L88-L94

### Issue Screenshot
Now:
![image](https://user-images.githubusercontent.com/17506575/157811065-f3b8b3e9-aef8-4ebd-a381-c28bd75c70ec.png)

To:
![image](https://user-images.githubusercontent.com/17506575/157810926-8ea48ce7-8070-4dd9-b089-bf26e9137e41.png)

**I can create a PR, asking here in case it is considered bloat, or if there's any plans on adding it.**

**Comment by planetis-m** [comment]
Have you considered just multiplying by 1/value?

**Comment by raysan5** [comment]
@planetis-m Actually, that solution was proposed some time ago and I think it's the best solution instead of adding to additional functions.
