### ISSUE TITLE
[build] `raylib_game_template` Makefile.Android issues when compiling on Windows with Sh shell

### ISSUE THREAD

**Issue by Arohas** [raysan5/raylib#2388]
### Issue description

I'm trying to compile an Android example using the "Working for Android" guide on windows 10.
At the stage "Compiling a raylib game for Android (using a project template)" I get the following error (console out): 

C:\raylib\raylib-game-template\src>mingw32-make PLATFORM=PLATFORM_ANDROID
mingw32-make -f Makefile.Android
make[1]: Entering directory 'C:/raylib/raylib-game-template/src'
if not exist android.raylib_game mkdir android.raylib_game
sh: syntax error: unexpected end of file (expecting "then")
make[1]: *** [Makefile.Android:163: create_temp_project_dirs] Error 2
make[1]: Leaving directory 'C:/raylib/raylib-game-template/src'
make: *** [Makefile:401: all] Error 2

**Comment by raysan5** [comment]
@Arohas I'm afraid that Makefile is only for Windows CMD, the error message suggests you are executing the Makefile under SH shell.

**Comment by Arohas** [comment]
Thank for your reply.
I obviously didn't install any additional terminals on my system. Those, i downloaded the Railib archive with MinGV and the resources for android that are listed in the manual. So I don't know what to do next with this "sh" and where it came from. Moreover, the library itself was compiled successfully for me and I got "raillib.a", but can't compile an example from a template.

![nameless](https://user-images.githubusercontent.com/47819050/158796807-0fe1ff15-e773-4d2e-bbb8-901f52ef0a31.png)

**Comment by Peter0x44** [comment]
You can force make to use a specific shell, try
mingw32-make SHELL=cmd PLATFORM=PLATFORM_ANDROID

By default, if an sh.exe is present in your PATH, make will prefer to use it over anything else
See GNU Make's README.W32 for more info on how this works

Really, if the makefile is only intended to be used with cmd, there should probably be SHELL=cmd somewhere in the makefile itself.

**Comment by raysan5** [comment]
@Peter0x44 Yeap, added `SHELL=cmd`.
