### ISSUE TITLE
[core] Couldn't load fonts from Android's internal storage

### ISSUE THREAD

**Issue by masrur10rahman** [raysan5/raylib#2389]
How can I load fonts from android's internal storage ?
---

 - [x] I tested it on latest raylib version from latest release.
 - [x] I checked there is no similar issue already reported.
 - [x] My code has no errors or misuse of raylib.

### Issue description
While making an android app, I wanted to load fonts from /sdcard (Internal storage).
But it didn't load the font from that directory. If I run that executable from X11, it properly loads the font.

### Environment
**Platform : Android 11**
**OS : Android 11 ( *Inside [Termux](https://github.com/termux/termux)  app* )**
**OpenGL : ES2.0**

### Issue Screenshot
![Screenshot_20220314-192202_Termux](https://user-images.githubusercontent.com/80337027/158184424-74b0b54a-01a5-4cde-88b0-ac59fc223090.png)
![Screenshot_20220314-192222_Termux](https://user-images.githubusercontent.com/80337027/158184435-91fefff9-a794-47c7-8151-e59cb7bfda1f.png)
![Screenshot_20220314-192307](https://user-images.githubusercontent.com/80337027/158184440-89ad94e7-e8db-40d6-ba80-81e724418a13.png)
![Screenshot_20220314-195338_VNC Viewer](https://user-images.githubusercontent.com/80337027/158186841-b90811aa-4f4e-4f23-9c58-51beddbe8155.png)

**Comment by raysan5** [comment]
@masrur10rahman raylib uses Android NDK provided AAssetManager that only grants access to the apk assets directory. I think it's possible to also access external SDCard memory but that funtionality is not implemented at this moment.

**Comment by masrur10rahman** [comment]
Actually, the raylib wiki doesn't provide enough information for working on platforms other than desktop.

**Comment by raysan5** [comment]
@masrur10rahman Kind reminder that raylib is an open source project maintained for free. Wiki is open for everyone to be edit, you can contribute to the project improving the missing bits of information.

**Comment by raysan5** [comment]
This is a missing feature of the library, feel free to add it with a PR.
