### ISSUE TITLE
[build] Compile on Linux with no library installation

### ISSUE THREAD

**Issue by flavio7co** [raysan5/raylib#2394]
Hello. Thanks for the amazing project.

I'm trying to implement a project using raylib to teaching programming. I don't have access to super user mode in the labs. I would like to compile the codes without needing to install the libraries on the system. I would like to include the .so files in the command line when compiling applications (like: cc example.c libraylib.so -o example). Could this be possible? 

Thanks!!

**Comment by raysan5** [comment]
@flavio7co Sure, that's how I use raylib all the time, you can compile raylib statically as libraylib.a and just provide the when compiling your program:
```
gcc -o game game.c path_to_lib/libraylib.a -no-pie -D_DEFAULT_SOURCE -lGL -lm -lpthread -ldl -lrt -lX11
```
