### ISSUE TITLE
how to make the window fit browser page in PLATFORM_WEB

### ISSUE THREAD

**Issue by wtjcn** [raysan5/raylib#2397]
MaximizeWindow dose not do the work. SetWindowSize can change window size, but can not get web page size.

**Comment by raysan5** [comment]
@wtjcn I'm afraid multiple technologies are involved in this process. raylib can build the program to be embedded in a webpage but how it is displayed by the browser and the webpage depends on the canvas element and DOM. That's out of scope for raylib and belongs to web development domain.

**Comment by wtjcn** [comment]
I did it.

reference:
https://github.com/floooh/cimgui-sokol-starterkit
https://stackoverflow.com/questions/53752243/how-to-retrieve-in-browser-size-of-emscripten-canvas

base on raylib-game-template

1. modify  minshell.html
        canvas.emscripten {
            position: absolute;
            top: 0px;
            left: 0px;
            margin: 0px;
            border: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            display: block;
            image-rendering: optimizeSpeed;
            image-rendering: -moz-crisp-edges;
            image-rendering: -o-crisp-edges;
            image-rendering: -webkit-optimize-contrast;
            image-rendering: optimize-contrast;
            image-rendering: crisp-edges;
            image-rendering: pixelated;
            -ms-interpolation-mode: nearest-neighbor;
        }

2. in raylib_game.c
#if defined(PLATFORM_WEB)
#include <emscripten/emscripten.h>

EM_JS(int, canvas_get_width, (), {
  return document.getElementById('canvas').clientWidth;
});

EM_JS(int, canvas_get_height, (), {
  return document.getElementById('canvas').clientHeight;
});
#endif

This will get page size


3. in raylib_game.c draw loop

static int old_w=0,old_h=0;

 int w = canvas_get_width();
 int h = canvas_get_height();
 if(w!=old_w || h!=old_h){
    SetWindowSize(w,h);
 }
