### ISSUE TITLE
Error while compiling raylib

### ISSUE THREAD

**Issue by dtrhrg** [raysan5/raylib#2404]
when i compile raylib, i get an error mesage saying 
cc1.exe: some warnings being treated as errors
Makefile:576: recipe for target 'rmodels.o' failed
mingw32-make: *** [rmodels.o] Error 1

the full message is
gcc -c rmodels.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
In file included from rmodels.c:72:0:
external/cgltf.h: In function 'cgltf_default_file_read':
external/cgltf.h:951:20: error: implicit declaration of function '_ftelli64' [-Werror=implicit-function-declaration]
   __int64 length = _ftelli64(file);
                    ^~~~~~~~~
cc1.exe: some warnings being treated as errors
Makefile:576: recipe for target 'rmodels.o' failed
mingw32-make: *** [rmodels.o] Error 1

please help I am taking a 20 dollar C++ course and I need raylib to countinue

**Comment by raysan5** [comment]
This issue is related to using an old version of mingw and gcc, you should use latest mingw/gcc provided by [w64devkit](https://github.com/skeeto/w64devkit/releases/tag/v1.11.0). Actually it's the version provided by raylib Windows Installer.

**Comment by dtrhrg** [comment]
I have set up w64devkit and still says this error, I've installed it and everything, is there something I'm missing?

**Comment by raysan5** [comment]
@dtrhrg you probably have multiple mingw versions installed and it's not called the right one. This same issue has happened to several users. Feel free to join raylib Discord and ask in raylib-setup channel, communication is faster than on github.
