### ISSUE TITLE
Linker cant find the obj

### ISSUE THREAD

**Issue by dtrhrg** [raysan5/raylib#2407]
I've been having a lot of issues setting up raylib, and i feel like this is the final issue i have to come across its a linker error, i will send the image here 

![Screenshot 2022-03-23 125840](https://user-images.githubusercontent.com/84113746/159785269-fd021a66-d5c1-4f7b-9a00-9124fabc2d46.png)

**Comment by raysan5** [comment]
@dtrhrg Please, join raylib Discord for issues with setup. raylib GitHub issues are intended for issues with the library, not the environment configuration.
