### ISSUE TITLE
[raymath] Matrix normalization

### ISSUE THREAD

**Issue by soegaard** [raysan5/raylib#2412]
The function `MatrixNormalize` currently takes a 4x4 matrix `mat` as input
and returns the matrix `1/D*mat` where D is the determinant of the matrix.

If the goal of `MatrixNormalize` is to normalize the determinant to `,
then instead of multiplying with 1/D one needs to multiply with 1/d
where d is the fourth root of D.

Note: The comment doesn't say which type of matrix normalization `MatrixNormalize`
is intended to compute.

Note: The function `MatrixNormalize` is not called by other functions in `raymath`.

https://github.com/raysan5/raylib/blob/418a595b6fc8d2edd43940de7fba46877a6d9323/src/raymath.h#L959

**Comment by raysan5** [comment]
@soegaard Thanks for reporting this issue! I think it was a poor Matrix implementation of another normalization functions... Afair, I never used this function. Feel free to update the function and send a PR.

 > Note: The function MatrixNormalize is not called by other functions in raymath.

There is no function in `raymath` called by any other function, all [functions are self-contained](https://github.com/raysan5/raylib/blob/418a595b6fc8d2edd43940de7fba46877a6d9323/src/raymath.h#L18).

**Comment by soegaard** [comment]
If MatrixNormalize isn't used, maybe it makes more sense to simply remove it?

**Comment by raysan5** [comment]
@soegaard Agree. Removed.
