### ISSUE TITLE
mingw32-make PLATFORM=PLATFORM_DESKTOP won't work

### ISSUE THREAD

**Issue by CreshFreamer** [raysan5/raylib#2413]
### Discussed in https://github.com/raysan5/raylib/discussions/2411

<div type='discussions-op-text'>

<sup>Originally posted by **CreshFreamer** March 25, 2022</sup>
When I use the mingw32-make PLATFORM=PLATFORM_DESKTOP on the src folder of the raylib folders, I get spammed with these errors: Error: invalid instruction suffix for `push' Can anyone help? I'll give more details if needed</div>

**Comment by CreshFreamer** [comment]
Why did this get closed? I need help because im shaking and crying rn

**Comment by orcmid** [comment]
> Why did this get closed? I need help because im shaking and crying rn

Sorry @CreshFreamer , you are not reporting an identifiable defect.  You seem to be asking for help, which is different.  You could create a question on the DIscussion Forum.  raysan5 generally suggests use of the forum on Discord for these kinds of problems.  There folks would ask you for more details and also want to understand your level of knowledge using mingw, gcc, and the C Language.  

As the author of #2413, you might be able to change it to a Discussion.  Otherwise, start over :).

**Comment by CreshFreamer** [comment]
> > Why did this get closed? I need help because im shaking and crying rn
> 
> Sorry @CreshFreamer , you are not reporting an identifiable defect. You seem to be asking for help, which is different. You could create a question on the DIscussion Forum. raysan5 generally suggests use of the forum on Discord for these kinds of problems. There folks would ask you for more details and also want to understand your level of knowledge using mingw, gcc, and the C Language.
> 
> As the author of #2413, you might be able to change it to a Discussion. Otherwise, start over :).

Me not has discord 😆

**Comment by zekovic** [comment]
I had suffix for `push' error also, it was something about i686 which is gcc that comes with Raylib. Gcc worked good with -stc=c99 from Notepad++, but there was problem with g++. 
You can try to open Notepad++, press F6, select option raylib_source_compile, then replace compiler path to you standard x86-64 gcc path, for example SET COMPILER_PATH=C:\Program Files\CodeBlocks\MinGW\bin , and replace RELEASE_PATH for example with: SET RELEASE_PATH=C:\raylib\mingw64 , create folders C:\raylib\mingw64\lib and C:\raylib\mingw64\include, then click OK in that Notepad++ window, then it should work, 
Also you can create 64bit version of rc file to match, with for example:
windres C:\raylib\raylib\src\raylib.rc -o core_basic_window.rc.data --target=pe-x86-64

Than final command to build cpp can be like:

g++ main.cpp core_basic_window.rc.data -s -static -Os -std=c++11 -Wall -IC:\raylib\raylib\src -Iexternal -DPLATFORM_DESKTOP -LC:\raylib\mingw64\lib -lraylib -lopengl32 -lgdi32 -lwinmm -mwindows -o exe_name.exe
