### ISSUE TITLE
[build] Issue building with zig on MacOS

### ISSUE THREAD

**Issue by danjrauch** [raysan5/raylib#2414]
### Issue description

In order to build ray lib in a Zig project on macOS I needed to add a few framework links to the ray lib build.zig file. I'm not positive why some devs don't need these links to build but it could have something to do with me wanting to build raylib from source in my project. 

I deduced the needs for these links by referencing issue [#1168.](https://github.com/raysan5/raylib/issues/1168)

### Environment

macOS Monterey version 12.0.1 with an M1 chip

### Code Example

```
        .macos => {
            // On macos rglfw.c include Objective-C files.
            const raylib_flags_extra_macos = &[_][]const u8{
                "-ObjC",
            };
            raylib.addCSourceFiles(
                &.{srcdir ++ "/rglfw.c"},
                raylib_flags ++ raylib_flags_extra_macos,
            );
            raylib.linkFramework("Foundation");
            /* Additions start here */
            raylib.linkFramework("CoreFoundation");
            raylib.linkFramework("CoreAudio");
            raylib.linkFramework("CoreVideo");
            raylib.linkFramework("IOKit");
            raylib.linkFramework("Cocoa");
            raylib.linkFramework("OpenGL");
        },
```

**Comment by UC101** [comment]
Every raylib-zig example I've seen has had those library include directives in the build script. This seems normal?

**Comment by raysan5** [comment]
I'm afraid I don't understand the issue... those libraries are required on building? Does it work for other users without those libraries included?

Feel free to send a PR if required.
