### ISSUE TITLE
[core] ToggleFullscreen() does not work on linux

### ISSUE THREAD

**Issue by moonburnt** [raysan5/raylib#2415]
### Issue description

Long story short - ToggleFullscreen() does not seem to work correctly (or at least on my setup). Attempting to run game in windowed mode and then switch to fullscreen cause screen (not game's, but whole monitor's) resolution to get messy for a second, then it goes back to normal and window loses focus. Any attempts to bring window back cause the bug to repeat.
At first I thought its my own fault, coz I did not change window's resolution to screen's resolution before calling ToggleFullscreen(). So I did that and then... it didn't work again. I went to google and found this example: https://gist.github.com/JeffM2501/6e4630a0e34c0c7dddf066f7192e342d which seems legit. But attempts to toggle fullscreen in third party code cause said bug to appear too.

### Environment

Manjaro linux, Cinnamon desktop environment, Intel 4700HQ CPU.
GPU/OpenGL info from raylib's log:
```
Vendor:   Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
Version:  4.5 (Core Profile) Mesa 21.3.7
GLSL:     4.50
```

### Issue Screenshot

I don't think its possible to screenshot this issue, but I've tried to record a video. But its buggy due to resolution switch shenanigans and thus may not work properly
https://user-images.githubusercontent.com/52989889/160263006-72ddc997-9dd5-40a3-92c2-4c5bc8e976f8.mp4

### Code Example
```cpp
#include "raylib.h"

int main() {
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "test");

    SetTargetFPS(60);

    while (!WindowShouldClose()) {
        if (IsKeyPressed(KEY_ENTER) && (IsKeyDown(KEY_LEFT_ALT) || IsKeyDown(KEY_RIGHT_ALT))) {
            int display = GetCurrentMonitor();
 
            if (IsWindowFullscreen()) {
                SetWindowSize(screenWidth, screenHeight);
            }
            else {
                SetWindowSize(GetMonitorWidth(display), GetMonitorHeight(display));
            }

            ToggleFullscreen();
        }

        BeginDrawing();
        ClearBackground(RAYWHITE);
        DrawText("Press Alt + Enter to Toggle full screen!", 190, 200, 20, LIGHTGRAY);
        EndDrawing();
    }

    CloseWindow();
    return 0;
}
```

**Comment by JeffM2501** [comment]
I think the problem is that when you go from fullscreen back to windowed, you are changing the screen resolution while still in fullscreen. You should do that after you toggle out of fullscreen. SetWindowSize should always be in the non-fullscreen state.
This code works for me
```c
#include "raylib.h"

int main ()
{
    const int screenWidth = 800;
    const int screenHeight = 450;

	InitWindow(screenWidth, screenHeight,"Example");

	while (!WindowShouldClose())
	{
		if (IsKeyPressed(KEY_SPACE))
		{
			if (IsWindowFullscreen())
			{
				ToggleFullscreen();
				SetWindowSize(screenWidth, screenHeight);
			}
			else
			{
				int monitor = GetCurrentMonitor();
				SetWindowSize(GetMonitorWidth(monitor), GetMonitorHeight(monitor));
				ToggleFullscreen();
			}
		}

		BeginDrawing();
		ClearBackground(BLACK);
		DrawText("Press space to Toggle full screen!", 190, 200, 20, LIGHTGRAY);
		EndDrawing();
	}
	CloseWindow();
	return 0;
}

```

**Comment by moonburnt** [comment]
Actually its even more interesting:
- To begin with, the only working solution for me was reverse from what you posted. E.g if window should be changed to fullscreen - first call ToggleFullscreen(), and then SetWindowSize(). And when fullscreen window should be switched back to windowed mode - first switch resolution and then use ToggleFullscreen().
E.g:
```cpp
        // Some code omitted. toggle_fullscreen is a bool
        if (toggle_fullscreen) {
            if (!IsWindowFullscreen()) {
                const int current_screen = GetCurrentMonitor();
                ToggleFullscreen();
                SetWindowSize(
                    GetMonitorWidth(current_screen),
                    GetMonitorHeight(current_screen));
            };
        }
        else {
            if (IsWindowFullscreen()) {
                SetWindowSize(1280, 720);
                ToggleFullscreen();
            };
        }
```

- Secondly - GetScreenWidth() and GetScreenHeight() break if resolution has been switched together with ToggleFullscreen(). Their values simply don't get updated, ever - not if you ask for width and height the very moment you've switched, nor if you do that somewhere down the line (say, by pressing some button many frames later) - values simply remain the same they were before such call.

**Comment by fluxrider** [comment]
I'm new to raylib since this morning and ran into this problem too. ToggleFullscreen() triggers my monitor to lose input for a second, and doesn't stretch the window as I would expect.  My solution is to bypass ToggleFullscreen and disable decoration instead. GetScreenWidth/Height works (though in all honesty should be called GetWindowWidth/Height).

```

bool fullscreen = false;
Vector2 stored_window_position;
Vector2 stored_window_size;

if(IsKeyPressed(KEY_F)) {
  if(fullscreen = !fullscreen) {
    stored_window_position = GetWindowPosition();
    stored_window_size = (Vector2){GetScreenWidth(),GetScreenHeight()};
    SetWindowState(FLAG_WINDOW_UNDECORATED);
    SetWindowSize(GetMonitorWidth(GetCurrentMonitor()), GetMonitorHeight(GetCurrentMonitor()));
  }
  else {
    ClearWindowState(FLAG_WINDOW_UNDECORATED);
    SetWindowPosition(stored_window_position.x, stored_window_position.y);
    SetWindowSize(stored_window_size.x, stored_window_size.y);
  }
}
```

My setup is very minimal x11/openbox.
Linux rpi400manjaro 5.15.28-1-MANJARO-ARM-RPI #1 SMP PREEMPT Tue Mar 15 15:22:54 UTC 2022 aarch64 GNU/Linux

**Comment by JeffM2501** [comment]
> I'm new to raylib since this morning and ran into this problem too. ToggleFullscreen() triggers my monitor to lose input for a second, and doesn't stretch the window as I would expect. My solution is to bypass ToggleFullscreen and disable decoration instead. GetScreenWidth/Height works (though in all honesty should be called GetWindowWidth/Height).
> My setup is very minimal x11/openbox. Linux rpi400manjaro 5.15.28-1-MANJARO-ARM-RPI #1 SMP PREEMPT Tue Mar 15 15:22:54 UTC 2022 aarch64 GNU/Linux

Well, ToggleFullscreen does not change the window size, it changes the monitor resolution to match the window. This is why your monitor 'looses input' for a bit, it's changing resolutions. To raylib the window size is locked, and the monitor changes around it. You would still need to do what you are doing with the window size in addition to calling ToggleFullscreen.

**Comment by fluxrider** [comment]
Ah yes, I've been confused with "Borderless Windowed" in most video games, that I had forgotten what fullscreen meant. Thanks for clarifying.

I should mention that my posted code only works for me in openbox because I don't have a taskbar. I can't test in my setup, but it seems ok, i.e. I dont lose input on my tv, when calling ToggleFullscreen() when setting the window size to my desktop resolution. Cheers.

**Comment by raysan5** [comment]
It seems this issue is related to the way fullscreen toggle actually works and it works as expected.

**Comment by moonburnt** [comment]
> It seems this issue is related to the way fullscreen toggle actually works and it works as expected.

does "works as expected" include the breakage of GetScreenWidth() and GetScreenHeight() calls?

**Comment by raysan5** [comment]
@moonburnt GetScreenWidth() and GetScreenHeight() return the user set width and height that is usually the framebuffer size. ToggleFullscreen() does not change (or should not change) the framebuffer size.

**Comment by moonburnt** [comment]
@raysan5 thats... not as obvious as it could've been. 
So, is there any alternative that would work for both windowed and fullscreen modes? Because every single interface in my game rely on it (either for positioning or to calculate width/height of elements)

**Comment by chriscamacho** [comment]
ideally you should not be dealing with absolute positioning, fractions of screen size are a lot more useful as the app will look and behave very similarly regardless of platform and available maximum size, just look better where the resolution can be higher.

another alternative is to render to an off screen buffer that is always the same size and then scale that to the current window/screen height as needed (this might be the easier way to go...)

I've just re-released my GUI and not GUI templates on my website (https://bedroomcoders.co.uk/updated-raylib-templates/)

**Comment by raysan5** [comment]
@moonburnt I'm afraid switching to fullscreen is a complex topic, it depends on display supported resolutions, OS configuration, active monitor, graphic driver, framebuffer size, black-bars requirements...

raylib uses GLFW on desktop platforms and just calls `glfwSetWindowMonitor()` to set the fullscreen mode for current monitor, raylib has not much control how the process is done internally by GLFW.

**Comment by moonburnt** [comment]
for the time being, I've solved it for myself with following wrapper calls instead of directly using GetScreenSomething. Seems to work fine, at least on my single-monitor setup.

```cpp
int get_window_width() {
    if (IsWindowFullscreen()) {
        return GetMonitorWidth(GetCurrentMonitor());
    }
    else {
        return GetScreenWidth();
    }
}

int get_window_height() {
    if (IsWindowFullscreen()) {
        return GetMonitorHeight(GetCurrentMonitor());
    }
    else {
        return GetScreenHeight();
    }
}
```

**Comment by TirtharajPramanik** [comment]
```c
IsWindowFullscreen() 
    ? (ToggleFullscreen(), SetWindowSize(GetMonitorWidth(GetCurrentMonitor()), GetMonitorHeight(GetCurrentMonitor())))
    : (SetWindowSize(800, 800), ToggleFullscreen());
```
this code works for me

**Comment by TirtharajPramanik** [comment]
```
IsWindowFullscreen() ? (ToggleFullscreen(), SetWindowSize(gameWidth, gameHeight))
                             : (SetWindowSize(GetMonitorWidth(GetCurrentMonitor()), GetMonitorHeight(GetCurrentMonitor())), ToggleFullscreen());
```
