### ISSUE TITLE
[module] Running Raylib with CL.exe (MSVC compiler)

### ISSUE THREAD

**Issue by st3ph4nnn** [raysan5/raylib#2417]
i want to compile main.cpp using CL.exe which is the compiler visual studio uses.

I simply run:
**cl.exe /I "..\include\." /std:c++17 /EHsc ../main.cpp /link /LIBPATH:"..\lib\." /out:game.exe**
but i get the normal unreferenced errors.

**main.obj : error LNK2019: unresolved external symbol _SetConfigFlags referenced in function _main
main.obj : error LNK2019: unresolved external symbol _SetTraceLogLevel referenced in function _main
main.obj : error LNK2019: unresolved external symbol _LoadFileText referenced in function _GuiLoadStyle
main.obj : error LNK2019: unresolved external symbol _GetDirectoryPath referenced in function _GuiLoadStyle
main.obj : error LNK2019: unresolved external symbol _IsKeyPressed referenced in function _GuiValueBox
main.obj : error LNK2019: unresolved external symbol _IsKeyDown referenced in function _GuiScrollPanel
main.obj : error LNK2019: unresolved external symbol _GetCharPressed referenced in function _GuiValueBox
main.obj : error LNK2019: unresolved external symbol _IsMouseButtonPressed referenced in function _GuiComboBox
main.obj : error LNK2019: unresolved external symbol _IsMouseButtonDown referenced in function _GuiScrollPanel
main.obj : error LNK2019: unresolved external symbol _IsMouseButtonReleased referenced in function _GuiButton
main.obj : error LNK2019: unresolved external symbol _GetMousePosition referenced in function _GuiScrollPanel
main.obj : error LNK2019: unresolved external symbol _GetMouseWheelMove referenced in function _GuiScrollPanel
main.obj : error LNK2019: unresolved external symbol _SetShapesTexture referenced in function _GuiLoadStyle**

/link /LIBPATH:"..\lib\." is where my libraylib.a file is but i dont think i should be using that..
how could i compile raylib from source using CL and use that?

**Comment by raysan5** [comment]
@st3ph4nnn It does not seem to be an issue with raylib but with your compilation line, you are not linking with required libraries. You need to link (at least) with: 
 - `raylib.lib`
 - `opengl32.lib`
 - `kernel32.lib`
 - `user32.lib`
 - `gdi32.lib`
 - `winmm.lib`

**Comment by orcmid** [comment]
I don't understand where you are trying to do the compile.  

I suggest you perform the example at `raylib/projects/scripts/build-windows.bat` after copying the `*.bat` and the `*.c` file to a folder of your choice where you can produce compilation materials.  

You will need to operate in the Visual Studio C/C++ build environment to compile.  You do that using one of the shortcuts that is put on the start page by recent Visual Studio or Visual Studio Build Tools installs.  I prefer the
`x64 Native Tools Command Prompt for VS 2022` one.  

When you run `build-windows.bat` from within that command session, it should all work.  Notice that you need to edit the `build-windows.bat` script to locate some things first.

I have a customization of that arrangement that works as described in the GitHub repository location [orcmid/raylab/projects/scripts/rawVC/](https://github.com/orcmid/rayLab/tree/main/projects/scripts/rawVC).

Note that this does not require any `raylib.lib` or other `*.lib` files not part of the Windows SDK.  The raylib `*.obj` files are compiled from raylib source and cached for reuse in subsequent builds.  That's fast enough and it avoids problems of incompatibility between `*.lib` builds and the settings for compiling your own parts.

I am making [VCrayApp](https://github.com/orcmid/nfoTools/tree/master/devKits/WinDev/VCrayApp/dev), inspired by ray's approach,  that is more general-purpose (and simpler) for building raylib apps using Visual Studio Build Tools.  It it is not ready for prime-time.   I promise to clean it up and make it
available in a Zip for reuse.

**Comment by stevehb** [comment]
For those who end up here from searching those error messages: 
You need to link the libraries listed [above](https://github.com/raysan5/raylib/issues/2417#issuecomment-1080807931), plus `shell32.lib`.

The full MSVC command that ended up working for me for x64 builds:
```
cl main.c /I"raylib-5.0_win64_msvc16/include/" /MD /link /MACHINE:X64 /OUT:"main.exe" "raylib-5.0_win64_msvc16/lib/raylib.lib" opengl32.lib kernel32.lib user32.lib shell32.lib gdi32.lib winmm.lib msvcrt.lib
```

**Comment by girng** [comment]
@stevehb omg you are a lifesaver, thank you
