### ISSUE TITLE
[core] SWIPE_LEFT is the only swipe gesture triggered

### ISSUE THREAD

**Issue by cjwagenius** [raysan5/raylib#2418]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
 - [ ] I checked there is no similar issue already reported
 - [ ] My code has no errors or misuse of raylib

### Issue description

*Briefly describe the issue you are experiencing (or the feature you want to see added to raylib). Tell us what you were trying to do and what happened instead. Remember, this is not the best place to ask questions. For questions, go to [raylib Discord server](https://discord.gg/raylib).*

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example

*Provide minimal reproduction code to test the issue. Please, format the code properly and try to keep it as simple as possible, just focusing on the experienced issue.*

**Comment by cjwagenius** [comment]
When using a Android 11 smartphone and running the 'input gestures'. No matter which direction you swipe. I've tried with latest raylib & emscripten.

**Comment by SAOMDVN** [comment]
Possibly related to #1963

**Comment by raysan5** [comment]
I'm afraid this issue is out-of-scope for the moment, many systems involved to take care of it.
