### ISSUE TITLE
[models] Automatic ordering for billboards

### ISSUE THREAD

**Issue by CrezyDud** [raysan5/raylib#2421]
### Issue description

The billboards don't order themselves like 3d cubes or models.

### Environment

Linux, GL 4.6, mesa

### Issue Screenshot

![image](https://user-images.githubusercontent.com/84625713/161039168-95fb0754-4aa7-431d-aef7-87c07f45aab0.png)

**Comment by CrezyDud** [comment]
i cant find any documentation online (because i also need ordering for rotation)
it's just supposed to work
with transparency

**Comment by chriscamacho** [comment]
this is one possible solution, which works without sorting...

https://bedroomcoders.co.uk/raylib-billboards-advanced-use/
