### ISSUE TITLE
[build] Unable to make raylib on windows with mingw32

### ISSUE THREAD

**Issue by dechire20** [raysan5/raylib#2430]
C:\Users\Ersum\Desktop\raylib-master\src>mingw32-make PLATFORM=PLATFORM_DESKTOP
gcc -c rmodels.c -Wall -D_DEFAULT_SOURCE -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing  -std=c99 -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw
In file included from rmodels.c:76:0:
external/cgltf.h: In function 'cgltf_default_file_read':
external/cgltf.h:954:21: error: implicit declaration of function '_ftelli64' [-Werror=implicit-function-declaration]
    __int64 length = _ftelli64(file);
                     ^~~~~~~~~
cc1.exe: some warnings being treated as errors
Makefile:655: recipe for target 'rmodels.o' failed
mingw32-make: *** [rmodels.o] Error 1

**Comment by raysan5** [comment]
@dechire20 I'm afraid you are using an old version of MinGW.

**Comment by raysan5** [comment]
raylib Windows Installer contains an updated MinGW version but you can download it from here: https://github.com/skeeto/w64devkit/releases

**Comment by dechire20** [comment]
> raylib Windows Installer contains an updated MinGW version but you can download it from here: https://github.com/skeeto/w64devkit/releases

thanks, it worked!

**Comment by Jadixd** [comment]
Do you have a video explaining how to do the update?
