### ISSUE TITLE
[raudio] Cheatsheet calls "InitAudioStream," instead of actual "LoadAudioStream."

### ISSUE THREAD

**Issue by FatalSleep** [raysan5/raylib#2433]
---

Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch

### Issue description

RAudio contains a function "LoadAudioStream," however the Cheatsheet labels this as "InitAudioStream."

**Comment by FatalSleep** [comment]
Same issue for UnloadAudioStream.

**Comment by raysan5** [comment]
@FatalSleep Cheatsheet will be updated with next raylib release.
