### ISSUE TITLE
[raudio] (https://github.com/raysan5/raylib/commit/709ec1663da66815e8818e8c6b2fc3025374e1eb) potentially broke music

### ISSUE THREAD

**Issue by CrezyDud** [raysan5/raylib#2436]
playing music always crashes

**Comment by chriscamacho** [comment]
there's a template for a good reason ! take a look at this https://www.browserstack.com/guide/how-to-write-a-bug-report

without at least some clue as to how to replicate the issue, much less what the actual issue really is or even what platform it effects, how can you expect that this report might help developers improve Raylib ?
