### ISSUE TITLE
[build] Issue when building raylib example with VSCode, undefined reference to `__mingw_opendir`

### ISSUE THREAD

**Issue by CreshFreamer** [raysan5/raylib#2440]
I used mingw32-make to create the exe file for main.c for the VScode IDE folder in the raylib installer version.
![image](https://user-images.githubusercontent.com/79119586/165181523-0d5f61e1-dd19-497d-be92-3dea3b5225a0.png)
-Windows 10
-Definetely not ram problem. (Im watching you, steam users)
-IM USING THE MINGW32 VERSION IN THE RAYLIB INSTALLER!!!!
How to reproduce:
1-Setup raylib. (on the installer version) (finally)
2-Go to VSCode folder.
3-Copy files and paste it into your desired folder.
4-Run code realizing you need an exe first and the way to make it is using mingw32-make.
5-Open cmd on the folder and running "mingw32-make"
6-Get the error im getting.
_**Seriously, if you need more details just ask me, don't close this**_

**Comment by raysan5** [comment]
@CreshFreamer It looks like you are using an old version of MinGW. Please, use the one that comes with raylib installer.

**Comment by CreshFreamer** [comment]
> @CreshFreamer It looks like you are using an old version of MinGW. Please, use the one that comes with raylib installer.

I AM using the one that comes with raylib

**Comment by CreshFreamer** [comment]
> @CreshFreamer It looks like you are using an old version of MinGW. Please, use the one that comes with raylib installer.

Just edited the post just to clarify something

**Comment by raysan5** [comment]
@CreshFreamer Ok, I see, I have no idea about the origin of this issue. It works perfectly on my computer with the same configuration. Do you have multiple versions of MinGW installed?

**Comment by raysan5** [comment]
@CreshFreamer I'm afraid I don't know what is the issue. Let's see if any other user had the same issue. Feel free to join raylib Discord and ask in some of the help channels.

**Comment by CreshFreamer** [comment]
> @CreshFreamer I'm afraid I don't know what is the issue. Let's see if any other user had the same issue. Feel free to join raylib Discord and ask in some of the help channels.

I don't have discord tho

**Comment by raysan5** [comment]
@CreshFreamer Just asked in raylib Discord, it seems the solution is adding `-lkernel32` library to compilation line.

**Comment by CreshFreamer** [comment]
> @CreshFreamer Just asked in raylib Discord, it seems the solution is adding `-lkernel32` library to compilation line.

Where is the compilation line tho?

**Comment by raysan5** [comment]
@CreshFreamer It should be in the same place where `-lgdi32 -lwinmm` are added.

**Comment by CreshFreamer** [comment]
> @CreshFreamer Just asked in raylib Discord, it seems the solution is adding `-lkernel32` library to compilation line.

![image](https://user-images.githubusercontent.com/79119586/165346860-c239b1a1-8c47-4bf2-9b7b-b4a913df3ddc.png)

**Comment by CreshFreamer** [comment]
> @CreshFreamer It should be in the same place where `-lgdi32 -lwinmm` are added.

![image](https://user-images.githubusercontent.com/79119586/165347690-88dd47de-0569-445b-a050-bde0954de3ea.png)

**Comment by CreshFreamer** [comment]
> @CreshFreamer Ok, now the issue is related to raylib.rc.data resource file not found. You can just remove that file from compilation script. It's just used to add the window icon.


> @CreshFreamer Ok, now the issue is related to raylib.rc.data resource file not found. You can just remove that file from compilation script. It's just used to add the window icon.

![image](https://user-images.githubusercontent.com/79119586/165348720-ebd819f7-8358-4810-974a-eb4221952abe.png)

**Comment by raysan5** [comment]
@CreshFreamer Ok, now the issue is related to raylib.rc.data resource file not found. You can just remove that file from compilation script. It's just used to add the window icon.

**Comment by raysan5** [comment]
@CreshFreamer Sorry, this is my last message, I can't waste more time with that build issue. I recommend that you learn how build systems work or join raylib Discord to ask this kind of questions. Issues are intended for raylib issues, not problems with build system due to a lack of knowledge on configuration.

**Comment by CreshFreamer** [comment]
> @CreshFreamer Sorry, this is my last message, I can't waste more time with that build issue. I recommend that you learn how build systems work or join raylib Discord to ask this kind of questions. Issues are intended for raylib issues, not problems with build system due to a lack of knowledge on configuration.

Found the solution, just take the SRC folder from raylib and paste it into my project!!
