### ISSUE TITLE
Embed using objcopy

### ISSUE THREAD

**Issue by wwderw** [raysan5/raylib#2443]
I was trying to experiment with using objcopy, create an object file out of that and embed that into my binary.  Is it possible for raylib to interact with object files in this manor?

I created an o file fine.  Did a hexdump to make sure that I was using the correct name for the extern.  After that is where it may get wonky.

Above main function I did:
`extern char _binary_logo_png_start;`
`extern char _binary_logo_png_end;`

Inside main: 

`Image logo = LoadImage(&_binary_logo_png_start);` 

after my FPS line I did:

` SetWindowIcon(logo);` 

Everything compiles, no errors using this for Linux:

` cc main.cpp logo.o -o game -lraylib -lGL -lm -lpthread -ldl -lrt -lX11` 

Nothing displays for the window icon, outside of the usual xorg symbol.  I'm sure I'm missing something.  When I do internet searches, those just talk about header file embedding, which for something like this would add too much overhead, so I was hoping that I could get it to work using objcopy.

**Comment by raysan5** [comment]
@wwderw Try with `LoadImageFromMemory()`.

**Comment by wwderw** [comment]
I tried looking for examples for LoadImageFromMemory(), but I couldn't find any, so I'm winging this based on what I could glean from the compiler errors.  Probably way off base, I know enough (and that is even debatable) just to cause damage.

When I originally tried to do
`LoadImageFromMemory("binary", _binary_logo_png_start, _binary_logo_png_size)`

I was getting a signed versus unsigned conversion error, so I tried this:

`unsigned const char logoPic = reinterprete_case<const unsigned char>(_binary_logo_png_start)`

Afterwards my final LoadImageFromMemory() is:

`Image logo = LoadImageFromMemory("binary", logoPic,_binary_logo_png_size)`

And that results in no compiler errors, but still the standard xorg window bar icon.

**Comment by raysan5** [comment]
@wwderw Afair, it should be:
```c
LoadImageFromMemory(".png", _binary_logo_png_start, _binary_logo_png_size)
```
I'm closing this issue because it's not a raylib issue but a specific user use case. Feel free to join Discord and ask this kind of questions there.

**Comment by wwderw** [comment]
@raysan5 just in case someone finds this thread. 

externs used:

`extern  char _binary_logo_png_start;
extern  char _binary_logo_png_end;

extern char _binary_intro_wav_start;
extern char _binary_intro_wav_end;
`

created a couple of macros:

`#define MYLOGO_DATA ((unsigned char *) &_binary_logo_png_start)
#define MYLOGO_SIZE ((size_t) (&_binary_logo_png_end - &_binary_logo_png_start))

#define INTRO_DATA ((unsigned char *) &_binary_intro_wav_start) 
#define INTRO_SIZE ((size_t) (&_binary_intro_wav_end - &_binary_intro_wav_start))
`

From there, used the load functions:

`Image logo = LoadImageFromMemory(".png", MYLOGO_DATA, MYLOGO_SIZE);
 Wave intro = LoadWaveFromMemory(".wav", INTRO_DATA, INTRO_SIZE);
`

After that, everything seemed to work just like it was supposed to.  Noticed that my binary was the appropriate size for both of those files embedded.

**Comment by raysan5** [comment]
@wwderw thank you very much for sharing the solution, it will be useful for other users! :)
