### ISSUE TITLE
[shapes] Polygon triangulation support

### ISSUE THREAD

**Issue by istvanfedak** [raysan5/raylib#2445]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Could we add a polygon triangulation function to draw concave polygons with no holes similar to:
```c
void DrawTexturePoly(Texture2D texture, Vector2 center, Vector2 *points, Vector2 *texcoords, int pointsCount, Color tint);
```

The function could look like this:
```c
void DrawTriangulatedPoly(Vector2 *points, int pointsCount, Color color);
```
- `*points` would make up the polygon and the last point would be linked to the first point if its not the same as the first point.

I'm aware that you can create a concave shape by aggregating several shapes together. The reason I ask is because we're trying to replace the graphics programming library used by the University of Miami, since the current library is outdated [library.h](http://rabbit.eng.miami.edu/class/library/index.html). We use `library.h` in an introduction to programming course and teach programming to college students. Some of the labs require polygon triangulation to create basic shapes [lab2](http://rabbit.eng.miami.edu/class/een118/labs/lab_02f_flag.pdf). 

We were planning on using `raylib.h` and creating a wrapper library that translates the function calls from `library.h` to `raylib.h` function calls. This would make all the labs compatible with `raylib.h`. If help is needed to build this feature, a professor and I are more than happy to help out.

We would also be more than happy to provide a copy of the `library.h` wrapper library in the event that you would want to add it to the list of `raylib extra libraries` and license it under the same license as `raylib.h`. Here's the [detailed documentation](http://rabbit.eng.miami.edu/class/library/v10/documentation.pdf) for `library.h`. It was built with simplicity and intuition in mind and it sacrifices performance. 

### Environment

We would want this function to work for Windows, MacOS and Linux. Other operating environments are more than welcome. 

### Issue Screenshot

Please view [lab2](http://rabbit.eng.miami.edu/class/een118/labs/lab_02f_flag.pdf) for the programming style we're trying to re-create. Note this lab uses `library.h` and we would have a wrapper library (`library.h`) translating the function calls to `raylib.h` function calls.

### Code Example
```c
#define MAX_POINTS  6
...
    Vector2 points[MAX_POINTS] = {
        (Vector2){ 10.0f, 10.0f },
        (Vector2){ 70.0f, 10.0f },
        (Vector2){ 35.0f, 35.0f },
        (Vector2){ 70.0f, 70.0f },
        (Vector2){ 10.0f, 70.0f},
        (Vector2){ 10.0f, 10.0f}  // Close the poly
    };
    DrawTriangulatedPoly(points, MAX_POINTS, DARKBLUE);
...
```

**Comment by raysan5** [comment]
Hello @istvanfedak!

raylib already provides several functions that maybe could work for your use case:

```c
RLAPI void DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color);    // Draw a color-filled triangle (vertex in counter-clockwise order!)
RLAPI void DrawTriangleFan(Vector2 *points, int pointCount, Color color);    // Draw a triangle fan defined by points (first vertex is the center)
RLAPI void DrawTriangleStrip(Vector2 *points, int pointCount, Color color);  // Draw a triangle strip defined by points
RLAPI void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color);    // Draw a regular polygon (Vector version)
```

Glad to know you are considering raylib for teaching in your University. :D

**Comment by joseph-montanez** [comment]
If you look at the code DrawTexturePoly, its rather simple. Nothing RayLib has built-in can handle all kinds of polygons. LibTess/LibTess2 which is used in the Skia renderer (Chrome/Flutter) will tessellate polygons into Triangle fans, and strips. If you use C++ there is also CGal (GPL3 / Commercial License).

However that's way overkill for your Lab2, which can be resolved by Raylib's DrawPoly / DrawTriangle methods and a little bit of math.

**Comment by istvanfedak** [comment]
Thank you for your responses! I'll take a look at LibTess2.

**Comment by istvanfedak** [comment]
Hi @raysan5 , I know this isn't a support forum so feel free to leave this question unanswered.

Do you know if its possible to bypass the `while (!WindowShouldClose())` loop? One way I thought about tackling the problem is having two threads with a shared pixel buffer. The worker thread would continuously push the pixel buffer to the graphics card and the main thread would handle converting the source code into pixels and pushing them to the shared pixel buffer.

**Comment by raysan5** [comment]
Hi @istvanfedak, OpenGL by default is single-thread and usually trying to combine it with multi-threaded process gives more problems than solutions.
About the loop, you can control it completely, just issuing an Update-Draw frame when required. If you need more fine-grained control over frame timming you can uncomment `SUPPORT_CUSTOM_FRAME_CONTROL` in `raylib/src/config.h` and recompile raylib, there is an usage example in `examples/core/core_custom_frame_control.c`.
