### ISSUE TITLE
[build] ld error: undefined reference to `__atomic_*'

### ISSUE THREAD

**Issue by Jason23347** [raysan5/raylib#2452]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

*Briefly describe the issue you are experiencing (or the feature you want to see added to raylib). Tell us what you were trying to do and what happened instead. Remember, this is not the best place to ask questions. For questions, go to [raylib Discord server](https://discord.gg/raylib).*

When I was building examples on RaspberryPi 3 with command `make PLATFORM=PLATFORM_RPI`, errors occurred:
```shell
$ make PLATFORM=PLATFORM_RPI
gcc -o textures/textures_sprite_button textures/textures_sprite_button.c -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Wunused-result -s -O1 -std=gnu99 -I. -I../src -I../src/external -I../src/extras -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../src -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl  -DPLATFORM_RPI
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_job_queue_post':
raudio.c:(.text+0x4538): undefined reference to `__atomic_load_8'
/usr/bin/ld: raudio.c:(.text+0x4570): undefined reference to `__atomic_load_8'
/usr/bin/ld: raudio.c:(.text+0x45ec): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_job_queue_next':
raudio.c:(.text+0x47d4): undefined reference to `__atomic_load_8'
/usr/bin/ld: raudio.c:(.text+0x47f4): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o):raudio.c:(.text+0x482c): more undefined references to `__atomic_load_8' follow
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_resource_manager_data_stream_set_absolute_cursor':
raudio.c:(.text+0x528a0): undefined reference to `__atomic_exchange_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_resource_manager_data_stream_unmap':
raudio.c:(.text+0x53668): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_resource_manager_data_stream_get_cursor_in_pcm_frames':
raudio.c:(.text+0x53db4): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_node_set_state_time':
raudio.c:(.text+0x592f8): undefined reference to `__atomic_exchange_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_node_get_state_time':
raudio.c:(.text+0x59378): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_node_get_time':
raudio.c:(.text+0x594b8): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_node_set_time':
raudio.c:(.text+0x59514): undefined reference to `__atomic_exchange_8'
/usr/bin/ld: ../src/libraylib.a(raudio.o): in function `ma_node_read_pcm_frames':
raudio.c:(.text+0x5a170): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make: *** [Makefile:527: textures/textures_sprite_button] Error 1
```

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*
Operating System:
```shell
$ uname -a
Linux raspberrypi 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux
```

GCC:
```shell
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
```

### Code Example

*Provide minimal reproduction code to test the issue. Please, format the code properly and try to keep it as simple as possible, just focusing on the experienced issue.*

This is caused by not linking `atomic`, so there is a hotfix: adding `-latomic` to `examples/Makefile` here: https://github.com/raysan5/raylib/blob/f169530d8f106a8175e3c0953b3af5cb4bce8ed9/examples/Makefile#L352

**Comment by raysan5** [comment]
@Jason23347 That's weird, it worked for me with no need for that library... did you try with latest raylib from GitHub master branch? Could you try with raylib 4.0 release? What version of Raspbian are you using? Is it Buster or Bullseye?

**Comment by Jason23347** [comment]
> Did you try with latest raylib from GitHub master branch?

Yes, I do. I tried with master branch til this commit: f169530d8f106a8175e3c0953b3af5cb4bce8ed9.

> Could you try with raylib 4.0 release?

Yes, of course.

I just tried with the 4.0.0 release, and no errors occurred.

Part of the logs:

```
gcc -o core/core_basic_window core/core_basic_window.c -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Wunused-result -s -O1 -std=gnu99 -I. -I../src -I../src/external -I../src/extras -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../src -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
```

The compile commands were the same.

> What version of Raspbian are you using? Is it Buster or Bullseye?

It is Buster.

```shell
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by raysan5** [comment]
@Jason23347 Thanks for testing! It seems `atomic` library dependency was added to miniaudio recently... @mackron please, could you confirm that?
Still, last week I built latest raylib for RPI OS Bullseye with PLATFORM_DRM and that library was not required... 🤔

**Comment by mackron** [comment]
That is correct. You need to link to `atomic` when compiling for 32-bit ARM. More generally, you need to link to `atomic` whenever the target architecture does not have built-in support for 64-bit atomics at the instruction level (which is the case for 32-bit ARM).

With your RPI OS Bullseye build, I suspect you were testing the 64-bit build which does not require linking to `atomic`.
