### ISSUE TITLE
make[1]: *** No rule to make target 'main.c', needed by 'game'.  Stop.

### ISSUE THREAD

**Issue by CreshFreamer** [raysan5/raylib#2457]
Im trying to make a game (learn to) and I got this issue after using `mingw32-make`, on some other line of the error it says this: `make: *** [Makefile:374: all] Error 2` Im using the VSCode template  (with some changes on it) Here's some images of the hierarchy 
![image](https://user-images.githubusercontent.com/79119586/166390224-7951bdcc-c44e-4534-b7b8-6b7a8ef582d6.png)
![image](https://user-images.githubusercontent.com/79119586/166390251-c82ea8a9-4b8c-4285-b64e-9b6f43a390c7.png)
![image](https://user-images.githubusercontent.com/79119586/166390279-5e22eedc-91a5-4676-ace2-697d527f8ea6.png)
![image](https://user-images.githubusercontent.com/79119586/166390298-3baf2e6d-68d3-4671-b6ef-8ff194834d7a.png)

**Comment by raysan5** [comment]
@CreshFreamer It looks like an issue with your build configuration and not with raylib, afaik it works for other users. I recommend joining raylib Discord and asking in help-setup channel.

**Comment by CreshFreamer** [comment]
> @CreshFreamer It looks like an issue with your build configuration and not with raylib, afaik it works for other users. I recommend joining raylib Discord and asking in help-setup channel.

Is the makefile in raylib (Like the really long one) necessary to make a full game? Or can I use another makefile?

**Comment by orcmid** [comment]
@CreshFreamer Take a look at `raylib/projects` for a variety of alternatives, and `raylib/projects/scripts` for very simple ways to build apps.  This will also get you simple ways to do command-line builds that don't get snarled in VSCode settings that may be your problem.  I'm uncertain about the resource compiler, but you should be able to add that in. 

Bonus: If you are using a recent version of Visual Studio, or of Visual Studio Build tools, you need to start the Command Prompt for your target and then run VSCode from inside the command-line session (it is command `code`).  This will get VSCode to detect the Windows SDK header files and provide Intellisense (and also let you know which ones it doesn't find.  The paths to the compiler and other tools are also set automatically by the Command Prompt startup.  Of course, if you are not using the Microsoft tools, move along :).

**Comment by WizardPlatypus** [comment]
For anybody else coming here with a similar issue:
If you are using a hotkey(default is F5) to start debuging in VSCode, make sure that the current opened file _**is the source file**_ you are trying to run. If you attempt to do so with any other file present int the template(for example, tasks.json), the error will occur exactly as described.
Just spent 10 minutes trying to figure out what I was doing wrong, decided to come back here and post a comment.
