### ISSUE TITLE
[feature] User-type for Vector2, Vector3, etc

### ISSUE THREAD

**Issue by Eren121** [raysan5/raylib#2458]
It would be nice to be able to use custom types for the Vector2, Vector3, etc types. Something like disabling them by surrounding the definition like it:

```c
#ifndef RL_USERTYPE_VECTOR2
    // Vector2, 2 components
    typedef struct Vector2 {
        float x;                // Vector x component
        float y;                // Vector y component
    } Vector2;
#endif
```

The concrete case is integration with `glm`.

**Comment by raysan5** [comment]
@Eren121 I'm afraid that's not possible, raylib require internally the raylib defined types, if types were externally defined they could break many internal parts of raylib.

`raymath` library should provide mostly the same functionality than `glm` but in C, actually I remembert some user porting some `glm`-based code to `raymath` and aligning both libraries.

**Comment by Eren121** [comment]
I mean it would be possible of course if the raylib is compiled from sources, using the custom type. I have also done this and this works pretty well.

**Comment by raysan5** [comment]
@Eren121 Well, it will only be possible if Vector2 in the second implementation was 2 floats but it could be 2 integers or 2 shorts or maybe multiple decomposed values. In all those cases it would break raylib.

**Comment by Eren121** [comment]
Most of the time it will work, because there are no padding even this it is technically not guaranteed (the layout is the same).

But I see what you mean, this would make `glm` thightly coupled to the library and could not be guaranteed with any other math library. I  was just wondering this because ImGUI allow something similar.
