### ISSUE TITLE
[core] `SetMousePosition()` delayed by one frame on X11 systems

### ISSUE THREAD

**Issue by hkva** [raysan5/raylib#2459]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

*Copied from my Discord message - HK#2413*

I'm having an issue where calls to `SetMousePosition` are effectively delayed by 1 frame and I have no idea why. I'm in the process of writing my own first-person mouse look function but every time I try to reset the cursor to the middle of the screen, `GetMousePosition` reports the old position for an extra frame.

### Environment

Arch Linux (X11 + dwm), OpenGL 4.6, AMD Radeon RX 580 **Bug reproduced consistently**

Windows 10 virtual machine, OpenGL 4.6, Nvidia GTX 960 **Could not reproduce bug**

### Code Example

```c
#include "raylib.h"

int main() {
    InitWindow(800, 600, "Mouse issue demo");
    SetTargetFPS(60);

    while (!WindowShouldClose()) {
        // If the mouse x position is > 100, reset it back to 5
        Vector2 mouse = GetMousePosition();
        TraceLog(LOG_INFO, "Mouse x: %f", mouse.x);
        if (mouse.x > 100) {
            TraceLog(LOG_INFO, "Mouse is > 100, resetting");
            SetMousePosition(5, mouse.y);
        }

        BeginDrawing();
            ClearBackground(BLACK);
            DrawLine(mouse.x, 0, mouse.x, 600, GREEN);
            DrawLine(100, 0, 100, 600, RED);
        EndDrawing();
    }

    CloseWindow();
}
```

If you move the mouse right at a medium speed, you can see the issue in the debug messages

```
INFO: Mouse x: 92.000000
INFO: Mouse x: 99.000000
INFO: Mouse x: 106.000000
INFO: Mouse is > 100, resetting                <- SetMousePosition called here
INFO: Mouse x: 115.000000                      <- Next frame, mouse hasn't moved
INFO: Mouse is > 100, resetting
INFO: Mouse x: 13.000000
INFO: Mouse x: 12.000000
INFO: Mouse x: 19.000000
```

**Comment by hkva** [comment]
I looked into the issue some more and I think I've found the problem. It seems to be caused by how Xorg buffers window events. In the above code example, here's what's going on:

1. The user moves the mouse, generating Xorg mouse move events that are buffered by GLFW
2. `SetMousePosition`: Modifies `CORE.Input.Mouse.currentPosition` and calls `glfwSetCursorPos`
3. `EndDrawing`: Calls `PollInputEvents` which calls `glfwPollEvents`
4. `glfwPollEvents` calls `MouseCursorPosCallback`, which overwrites `CORE.Input.Mouse.currentPosition`. The mouse move event generated by `glfwSetCursorPos` is **not** processed until the next frame.

In effect, this delays `SetMousePosition` by one frame.

You can work around this by using custom frame control, or simply by calling `PollInputEvents()` at the top of the game loop (before `SetMousePosition`).

**Comment by hkva** [comment]
Calling `glfwGetCursorPos` instead of `glfwSetCursorPosCallback` seems to fix this

**Comment by CrezyDud** [comment]
you can use glfwSetCursorPos() as long as when you use camera, you set cursor mode to DISABLED
then it's totally fine they say

**Comment by raysan5** [comment]
I'm afraid this issue is out of raylib domain, it depends on GLFW and probably X11 windowing system. Trying to implement a path in raylib side will only make the code more complex and probably generate future issues.

I'm closing this issue.

**Comment by jestarray** [comment]
I just wanna add that I ran into this same issue. Seems like the solutions listed here are to use `glfwGetCursorPos()`. We can also use SDL backend now which might solve it. Ultimately has this issue been reported to glfw?
