### ISSUE TITLE
Review updates to rlgl.h

### ISSUE THREAD

**Issue by RDR8** [raysan5/raylib#247]
`gcc -c rlgl.c -O1 -Wall -std=gnu99 -fgnu89-inline -Wno-missing-braces -I. -Iexternal -Iexternal/glfw3/include -Iexternal/openal_soft/include -DGRAPHICS_API_OPENGL_33
rlgl.c:254:8: error: unknown type name ‘DrawMode’
 static DrawMode currentDrawMode;
        ^
Makefile:301: recipe for target 'rlgl.o' failed
make: *** [rlgl.o] Error 1
`

**Comment by RDR8** [comment]
src/rlgl.h:134 was removed in recent commit "Review some comments"

**Comment by raysan5** [comment]
Corrected on commit https://github.com/raysan5/raylib/commit/974a6d4031edbe9f4cfafed0c9bc5ed362d51a2a
