### ISSUE TITLE
[rshapes] 2d raycast

### ISSUE THREAD

**Issue by CrezyDud** [raysan5/raylib#2474]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

raycasting in 2d space!

### Code Example

like the 3d raycast, but 2 dimensional

**Comment by raysan5** [comment]
I can't see the real use-case for 2d raycasting, actually I don't understand what it means exactly. Probably most user dont' need that.
