### ISSUE TITLE
Semmle/lgtm code-analysis warnings

### ISSUE THREAD

**Issue by Crydsch** [raysan5/raylib#2476]
Semmle is a code-analysis platform for finding security issues and automated code review.
It found a few warnings for raylib. They can be seen on their website [lgtm.com](https://lgtm.com/projects/g/raysan5/raylib/alerts/?mode=list&severity=error%2Crecommendation%2Cwarning&id=cpp%2Fconstant-comparison%2Ccpp%2Fempty-block%2Ccpp%2Flarge-parameter)

There are no severe problems! :D
But a few warnings.

I will open a PR accompanying this issue, were I already fixed some warnings and can add further fixes if wanted.

1. One Warning signals that a few functions pass very big arguments by value.
(Note: Semmle considers all paramter of size 64 bytes and above as too big.)
This increases the cost of calling the function, especially if it is called every frame!
The alternative would be to just pass pointers.

Now, I know though that you put special care into the function naming and overall API - so i didn't change any of this.
If you want to pass just a pointer, I'll update the PR.

This is of course mainly a performance issue and may not be so relevant, as raylib favors simplicity over perfomance.
Still I thought you would like to know.

This applies to the following functions (ranked by severity):

function | parameter size | severity (calls per frame)
-- | -- | --
void DrawModel(..) | sizeof(Model) == 120 | multiple times per frame
void DrawModelWires(..) | sizeof(Model) == 120 | multiple times per frame
void DrawModelWiresEx(..) | sizeof(Model) == 120 | multiple times per frame
void DrawMesh(..) | sizeof(Mesh) == 112 | multiple times per frame
void DrawMeshInstanced(..) | sizeof(Mesh) == 112 | multiple times per frame
RayCollision GetRayCollisionMesh(..) | sizeof(Mesh) == 112 | multiple times per frame
void ProcessGestureEvent(..) | sizeof(GestureEvent) == 104 | multiple times per frame
void BeginVrStereoMode(..) | sizeof(VrStereoConfig) == 304 | once per frame
void UnloadVrStereoConfig(..) | sizeof(VrStereoConfig) == 304 | called occasionally/seldom
void UpdateModelAnimation(..) | sizeof(Model) == 120 | called occasionally/seldom
bool IsModelAnimationValid(..) | sizeof(Model) == 120 | called occasionally/seldom
void UnloadModel(..) | sizeof(Model) == 120 | called occasionally/seldom
void UnloadModelKeepMeshes(..) | sizeof(Model) == 120 | called occasionally/seldom
BoundingBox GetModelBoundingBox(..) | sizeof(Model) == 120 | called occasionally/seldom
Model LoadModelFromMesh(..) | sizeof(Mesh) == 112 | called occasionally/seldom
void UpdateMeshBuffer(..) | sizeof(Mesh) == 112 | called occasionally/seldom
bool ExportMesh(..) | sizeof(Mesh) == 112 | called occasionally/seldom
void UnloadMesh(..) | sizeof(Mesh) == 112 | called occasionally/seldom
BoundingBox GetMeshBoundingBox(..) | sizeof(Mesh) == 112 | called occasionally/seldom

2. The maxHue comparison in `raygui.h` line 2880 is always false, because hue is set to -1 in the line above.
I am not sure what this function accomplishes, I assume this is a bug and requires review.
Otherwise the logic can be greatly simplified.

**Comment by raysan5** [comment]
@Crydsch Thank you very much for testing it and for the detailed report!

I'm aware of the size of the structures passed by value to those functions, basically `Model` and `Mesh` structures. Worth noting that those values are for `64 bit` compilation, for `32 bit` they are smaller. More info on the Wiki: https://github.com/raysan5/raylib/wiki/raylib-data-structures

The `VrStereoConfig` one is an special case, I'm still thinking what to do with it. Actually, raylib defines:
```c
// VR stereo config functions for VR simulator
RLAPI VrStereoConfig LoadVrStereoConfig(VrDeviceInfo device);     // Load VR stereo config for VR simulator device parameters
RLAPI void UnloadVrStereoConfig(VrStereoConfig config);           // Unload VR stereo config
```
 to allow improving the memory usage for those types.

About the `ragui.h` issue, it looks like a bug. It should be reviewed on raygui repo.

**Comment by Crydsch** [comment]
I was not aware of the wiki entry.
There will be no changes necessary then, so I marked the PR ready for review.

I will also open an issue on the raygui repo.
