### ISSUE TITLE
Linker throws a lot of errors when compiling programs with raylib.h using OpenGL 1.1

### ISSUE THREAD

**Issue by AidenIsik** [raysan5/raylib#2479]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I attempted to compile raylib with OpenGL 1.1, however unlike compiling for 2.1 and 3.3, whenever I try to compile a program using raylib the linker spits out a whole lot of "undefined reference" errors. This does not happen on the other 2 OpenGL versions.

### Environment

- Operating System(s): Arch Linux, Trisquel GNU/Linux-Libre
- OpenGL Version: Max supported versions 4.6 and 2.1 respectively, attempting to compile raylib with OpenGL 1.1 support

### Issue Screenshot

[Screenshot](https://raw.githubusercontent.com/AidenIsik/AidenIsik/main/halp.png)

### Code Example

```
#include <stdio.h>
#include <stdlib.h>
#include <raylib.h>
#include <stdbool.h>

int main()
{
        InitWindow(1280, 720, "Hello, Raylib!");

        while(WindowShouldClose() == false)
        {
                BeginDrawing();
                ClearBackground(RAYWHITE);
                DrawText("oh hi", 190, 200, 20, BLACK);
                EndDrawing();
        }

        CloseWindow();
}
```

**Comment by raysan5** [comment]
It seems you are not linking with OpenGL properly.

**Comment by AidenIsik** [comment]
So there is a different way to do link with OpenGL 1.1 vs using OpenGL 3.3 or OpenGL 2.1 and this isn't a bug?

In which case, sorry for opening this issue on GitHub, I'll ask on Reddit or something.

**Comment by raysan5** [comment]
@AidenIsik Excuse me, I probably closed it too fast, I didn't see it was about OpenGL 1.1. I'm double testing it.

**Comment by raysan5** [comment]
@AidenIsik I just tested it on Windows, compiling with latest MinGW-w64, for OpenGL 1.1 (`GRAPHICS_API_OPENGL_11`). It works ok for me, no problems. Maybe there is an issue with your OpenGL link library.

I can't do much more with the information provided.

**Comment by AidenIsik** [comment]
Thanks anyways. I'll ask on Reddit.
