### ISSUE TITLE
[core] Provide a function to get wheel movement on x and y, for trackpad-based input devices

### ISSUE THREAD

**Issue by schveiguy** [raysan5/raylib#2480]
### Issue description

On my Mac, the trackpad scroll provides a blend of both the X and Y scroll. This was "fixed" recently via #2437, but in a way that still only provides one value. So writing, for instance, a GUI which has both horizontal and vertical scrollbars is impossible.

However, looking [at the code](https://github.com/raysan5/raylib/blob/020e90319388fb6e0975d2bb502d4824d369aece/src/rcore.c#L5403-L5407), openGL is providing both x and y scrolling. Raylib also has many functions that are repeated for both X/Y and Vector2 overloads. So it would make logical sense to provide a `GetMouseWheelMoveV` function that returns a `Vector2` with both x and y components, instead of picking the largest amplitude. I'll also note that for whatever reason the x scroll scale is much bigger on the trackpad (that is, the x value seems to be larger than the y value based on similar movements on my trackpad when scrolling).

I actually have a working version of this function, and can submit a PR, but I have not explored all the ramifications, and don't want to move further unless it's agreed such a function can be added.

### Environment

MacOS Monterey 12.3.1, Apple M1 Pro ARM, magic trackpad.

### Code Example

Simple D program that writes a scroll position with movement of the text on the screen:

```d
import raylib;

void main()
{
    InitWindow(500, 500, "raylibtest");
    SetTargetFPS(60);

    float pos = 0;
    while(!WindowShouldClose())
    {
        float mwm = GetMouseWheelMove();
        pos = pos + mwm;
        auto drawpos = pos;
        if(drawpos < 0) drawpos = 0;
        BeginDrawing();
        ClearBackground(Colors.WHITE);
        DrawText(TextFormat("%f", pos), 10, cast(int)drawpos, 20, Colors.BLACK);
        EndDrawing();
    }
}
```

**Comment by raysan5** [comment]
@schveiguy Feel free to send a PR with a new function. :)
