### ISSUE TITLE
[models] Calling DrawTriangle3D() more than 10906 times results in blank window.

### ISSUE THREAD

**Issue by rich-1170** [raysan5/raylib#2489]
- [X] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Attempting to run DrawGrid() followed by 10907 or more DrawTriangle3D() results in a blank window. Drawing 10906 or fewer triangles works just fine. Code example is trivial, with all triangles being drawn in the same place. Originally discovered while using raylib-guile; recreated with C and compiled with premake.

Issue seems similar to [ https://github.com/raysan5/raylib/issues/1721 ](url)

I've only been using Raylib for a few days now, but I really like it (other than this small issue of course). Sure beats straight OpenGL; I probably would have given up on what I'm working on if it wasn't for this library.

### Environment

- Operating system: Debian 11
- OpenGL version: 3.3 (I think)
- GPU: AMD CAICOS

### Issue Screenshot

Drawing 10906 triangles:
![triangle-test-10906](https://user-images.githubusercontent.com/101468737/169886625-17d548ae-7b0a-4cbf-8d73-a8a31b9f2749.png)

Drawing 10907 triangles:
![triangle-test-10907](https://user-images.githubusercontent.com/101468737/169886709-281eebcc-fecd-486d-8071-9442772308f8.png)

### Code Example
```
#include "raylib.h"

int main(void)
{
    static const int screenWidth = 800;
    static const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "triangle-test");

    Camera3D camera = { 0 };
    camera.position = (Vector3){ 10.0f, 10.0f, 10.0f };
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
    camera.fovy = 45.0f;
    camera.projection = CAMERA_PERSPECTIVE;
    SetCameraMode(camera, CAMERA_FREE);

    SetTargetFPS(60);

    while (!WindowShouldClose()) {
        UpdateCamera(&camera);
        BeginDrawing();
            ClearBackground(RAYWHITE);

            BeginMode3D(camera);
                DrawGrid(10, 1.0f);
                for (int i = 0; i < 10907; i++)           // 10907 fails, 10906 works
                    DrawTriangle3D((Vector3){ 1, 0, 0 },
                                   (Vector3){ 0, 1, 0 },
                                   (Vector3){ 0, 0, 1 },
                                   BLUE);
            EndMode3D();

        EndDrawing();
    }

    CloseWindow();
    return 0;
}
```

**Comment by rich-1170** [comment]
It looks like if I call 
'''
rlCheckRenderBatchLimit(6)
'''
(no less than 6) after the first 10906 triangles, I can draw more triangles. The following works correctly:
'''
               DrawGrid(10, 1.0f);
                for (int i = 0; i < 10906; i++)
                    DrawTriangle3D((Vector3){ 1, 0, 0 },
                                   (Vector3){ 0, 1, 0 },
                                   (Vector3){ 0, 0, 1 },
                                   BLUE);
                rlCheckRenderBatchLimit(6);
                for (int i = 0; i < 10906; i++)
                    DrawTriangle3D((Vector3){ 1, 0, 0 },
                                   (Vector3){ 0, 1, 0 },
                                   (Vector3){ 0, 0, 1 },
                                   BLUE);
'''

**Comment by rich-1170** [comment]
I've been digging through the source code a bit.

- DrawGrid(10, 1.0f) draws 22 lines, with 2 vertices each: 44 vertices.
- DrawTriangle(...) draws 3 vertices, times 10906 triangles: 32718 vertices.
- rlCheckRenderBatchLimit() will only force a new batch when called with at least 6: 6 vertices.
- 44 + 32718 + 6 = 32768
- RL_DEFAULT_BATCH_BUFFER_ELEMENTS is defined as 8192. 8192*4 (each element is a quad; I don't know what the significance of the vertices being in groups of 4 is) = 32768 vertices

Attempting to use the last 6 (or 5 or 4, I suppose) vertices in the batch is causing the render to fail for some unknown reason.

**Comment by raysan5** [comment]
@rich-1170 @noodlecollie Just reviewed batch limit check for `DrawTriangle3D()`, now it should work.

**Comment by raysan5** [comment]
I'm closing the issue. Feel free to comment if problem persists.
