### ISSUE TITLE
[models] sizeRatio seems to have x, y coordinates reversed.

### ISSUE THREAD

**Issue by gravicappa** [raysan5/raylib#2494]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 
### Issue description

X and Y components are seem to be reversed on [this line](https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L3338):
```
Vector2 sizeRatio = { size.y, size.x*(float)source.height/source.width };
```
I think it should be
```
Vector2 sizeRatio = { size.x*(float)source.height/source.width, size.y };
```

**Comment by raysan5** [comment]
@gravicappa Did you test it with an actual example? It could be an issue but I'm thinking about the different coordinates system used for 2d drawing between 2d (x-y) and 3d (x-z).

**Comment by gravicappa** [comment]
I tried to draw a billboard with size `{ 2.0, 1.0 }` and it becomes taller instead of wider.

**Comment by raysan5** [comment]
@gravicappa Thanks! Reviewed!
