### ISSUE TITLE
Issues running program

### ISSUE THREAD

**Issue by pokeruler** [raysan5/raylib#2501]
I'm currently having issues running my program from the Visual Studio local windows debugger. Once it launches, it brings up the debug console:
![pic11](https://user-images.githubusercontent.com/16297274/171576026-b367afdb-cfc9-40dc-89b0-fd13fe614a5b.PNG)

And then the main window where the game is supposed to be popping up for a second and then immediately disappears.
Here is the only code I have written (main.cpp) :

`

        
   #include <raylib.h>

     int main() {

	InitWindow(800, 400, "Pong Game");

	while (!WindowShouldClose) {

		BeginDrawing();
		ClearBackground(BLACK);

		DrawCircle(GetScreenWidth() / 2, GetScreenHeight() / 2, 3, WHITE);

		DrawFPS(10, 10);
		EndDrawing();
	}

	CloseWindow();

	return 0;
        }
`

**Comment by raysan5** [comment]
@pokeruler I'm afraid it's impossible to guess the problem with the provided info. Provided code looks ok. Feel free to join raylib Discord for further discussion.

**Comment by orcmid** [comment]
Try `!WindowShouldClose( )` 

Tip1: It is best to ask for help like this either in Discussions or on Discord.  

Tip2: You'll get it, don't worry.  We've all been down this road.

**Comment by pokeruler** [comment]
@orcmid THANK YOU SO MUCH, THAT GOT IT WORKING!!!!!
