### ISSUE TITLE
[audio] Distortion/echo produced when multiple sounds are loaded

### ISSUE THREAD

**Issue by stefandd** [raysan5/raylib#2510]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Playing a short wave form leads to a distorted, time-delayed, very high-pitch "echo" of the sound being played after the sound.
This happens when another (or more?) sound samples happen to also have been loaded by `LoadSound`. If the problematic sound is the only one that is being loaded by `LoadSound`, the echo/distortion does not occur and the sound is played fine.

The example code below is a very slightly modified version of the official Multichannel sound playing example. When it is run and [ENTER] is pressed to play the fxWav2 sound, it produces the high-pitched echo a short time after the actual sound has finished. If however fxWav2 is the only sound that is being loaded by `LoadSound`, i.e. if the lines for `fxWav` are commented out, the fxWav2 produces no such echo, i.e. the sound plays fine!

### Environment
Windows 10, official Raylib+MingW, version 4.0 release
binary was compiled with:

`gcc raytest.c -lraylib -lgdi32 -luser32 -lshell32 -lwinmm -o raytest.exe`

EDIT: Bug also exists in `HEAD` 4.2-dev

### Code Example (raytest.c)
This is a marginally modified version of the official Multichannel sound playing example:
```C
/*******************************************************************************************
*
*   raylib [audio] example - Multichannel sound playing
*
*   This example has been created using raylib 2.6 (www.raylib.com)
*   raylib is licensed under an unmodified zlib/libpng license (View raylib.h for details)
*
*   Example contributed by Chris Camacho (@chriscamacho) and reviewed by Ramon Santamaria (@raysan5)
*
*   Copyright (c) 2019 Chris Camacho (@chriscamacho) and Ramon Santamaria (@raysan5)
*
********************************************************************************************/

#include "raylib.h"

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [audio] example - Multichannel sound playing");

    InitAudioDevice();      // Initialize audio device

    Sound fxWav = LoadSound("resources/328715__robinhood76__06098-short-jump-swoosh.wav");         // Load WAV audio file
    Sound fxWav2 = LoadSound("resources/273578__n-audioman__flame04.wav");        // Load OGG audio file

    SetSoundVolume(fxWav, 0.2f);

    SetTargetFPS(60);       // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        if (IsKeyPressed(KEY_SPACE)) PlaySoundMulti(fxWav);     // Play a new ogg sound instance
        if (IsKeyPressed(KEY_ENTER)) PlaySoundMulti(fxWav2);     // Play a new wav sound instance
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            DrawText("MULTICHANNEL SOUND PLAYING", 20, 20, 20, GRAY);
            DrawText("Press SPACE to play new wav instance!", 200, 120, 20, LIGHTGRAY);
            DrawText("Press ENTER to play new wav2 instance!", 200, 180, 20, LIGHTGRAY);

            DrawText(TextFormat("CONCURRENT SOUNDS PLAYING: %02i", GetSoundsPlaying()), 220, 280, 20, RED);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    StopSoundMulti();       // We must stop the buffer pool before unloading

    UnloadSound(fxWav);     // Unload sound data
    UnloadSound(fxWav2);     // Unload sound data

    CloseAudioDevice();     // Close audio device

    CloseWindow();          // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```
The two wave forms are un-edited downloads of:

"328715__robinhood76__06098-short-jump-swoosh.wav", <https://freesound.org/people/Robinhood76/sounds/328715/>

"273578__n-audioman__flame04.wav", <https://freesound.org/people/n_audioman/sounds/273578/>

**Comment by chriscamacho** [comment]
not sure what you mean by loaded together and loaded alone?

do you mean you hear the "echo" when both are loaded but only one is played?

**Comment by stefandd** [comment]
> not sure what you mean by loaded together and loaded alone?

Sorry, if that was confusing. As I tried to describe: if both sounds are loaded using the LoadSound function, then, even when fxWav2 ( "...flame04.wav") is played alone (by pressing just ENTER), there is a strange high-pitched "echo" by which I mean a high-pitched sound that is produced past! the duration of fxWav2, after the actual fxWav2 sound has already finished.
However, when you comment out the loading of fxWav, i.e. fxWav2 is the only sound that is being loaded, it plays fine and no such echo is produced.

**Comment by stefandd** [comment]
It might be helpful to point out that if the exact waveform is compressed to `.ogg`, the problem goes away!

**Comment by raysan5** [comment]
@stefandd This issue is really weird... does it only happen when using `PlaySoundMulti()`? Did you try using just `PlaySound()`?

**Comment by stefandd** [comment]
@raysan5 

I tested with HEAD and cannot any longer reproduce. I suspect the comment from 16 days ago (.wav/.ogg) may have been after this somehow got fixed, since I only tested .ogg but did not re-test for the bug with .wav.

Anyhow, can close this.
