### ISSUE TITLE
[core] Mouse pass through implementation.

### ISSUE THREAD

**Issue by RivaTesu** [raysan5/raylib#2516]
The GLFW_MOUSE_PASSTHROUGH flag was not implemented in the "SetConfigFlags". There is another way to define it or any way to do the same function without combining the EX_LAYERED and EX_TRANSPARENT styles?

**Comment by raysan5** [comment]
@RivaTesu Implemented. Please, could you verify it works as expected?

**Comment by gulrak** [comment]
The flag value seems to be wrong: `0x2000d` would make `FLAG_WINDOW_RESIZABLE` or `FLAG_WINDOW_UNDECORATED` also trigger `GLFW_MOUSE_PASSTHROUGH`. Shouldn't it only have one bit set?

**Comment by raysan5** [comment]
@gulrak Yes, you are right. It should be reviewed.

**Comment by RivaTesu** [comment]
> @RivaTesu Implemented. Please, could you verify it works as expected?

It's working, but still combining the EX_LAYERED and EX_TRANSPARENT styles, should it really work like that?

![Screenshot_25](https://user-images.githubusercontent.com/45327377/173209027-06f6d8f8-2d71-4006-97fc-01817844dc67.png)

**Comment by raysan5** [comment]
@RivaTesu It looks ok to me, I think that's the expected behaviour. What did you expect?

**Comment by RivaTesu** [comment]
@raysan5 I thought it would be a different method (without relying on the windows API), but this is how it really works.
