### ISSUE TITLE
[text] Loading Arabic codepoints from Font

### ISSUE THREAD

**Issue by Alirezareis** [raysan5/raylib#2520]
### Issue description

I was trying to load a persian font in raylib but when using it i got random errors and instead of the text i got these blank boxes.
(Honestly i thought that raylib doesn't support persian or any rtl language at first and was about to give up but after rummaging in issues related to text i saw some arabic text in one of the issues so i presume raylib supports persian and/or arabic)
I'm loading the text with
LoadFontEx("persianfont.ttf",20,0,255);
and the image below is result of drawing the font texture.
(numbers are shown without a problem)
I tried 3 different fonts but got the same result.

Tnx

### Environment
I installed raylib 4
I'm using raylib-cpp
Windows
Nvidia gt 820m
### Issue Screenshot

![Capture4_۰۱۲۴۱۴](https://user-images.githubusercontent.com/81704787/173317590-e2b1e64d-76ce-4705-8852-4dd9b957dfba.PNG)

**Comment by raysan5** [comment]
@Alirezareis raylib should support persian but youa re not loading the required glyphs properly from the font file. 

The last two parameters provided to `LoadFontEx()` are not correct. You should provide an array of codepoints with the desired persian codepoints and the total number of values in the provided array. 

A similar issue was solved for cyrillic characters just recently: https://github.com/raysan5/raylib/discussions/2499#discussioncomment-2882703

Looking at Unicode table, it seems [this is the Arabic alphabet](https://unicode-table.com/en/alphabets/arab/), it goes from codepoint `0xfe8e` to `0xfeed` (96 codepoints), not sure if this is the one you are looking for.

**Comment by Alirezareis** [comment]
oh i get it .i need to make an array that includes every characters code point.(i hope I'm not wrong)
Thank you
but although arabic and persian look similar they have different characters (they are different languages with fairly similar alphabet) so the unicode is different for a lot of their characters.
I will find it on my own but i have a question :
Lets say i made the said array and loaded my font properly , would there be any difference between using Persian and English ? 
like in strings , inputting data etc

**Comment by raysan5** [comment]
@Alirezareis You should also add to the array including persian codepoints the standard latin codepoints (codepoints values: 32 to 127). That way you will be able to use English/Persian glyphs.

Also important to note, raylib uses UTF8 encoded text so, make sure your .c/.cpp text file is saved as UTF8 encoding if it contains Persian strings.
