### ISSUE TITLE
[shapes] Shape Drawing Functions are missing ...LinesEx variants with a line thickness parameter.

### ISSUE THREAD

**Issue by SoloByte** [raysan5/raylib#2527]
### Issue description

I am basically missing some function variants for drawing shapes with lines with a custom line thickness. All of the following functions do not exist yet but I actually need a lot of them because setting the line thickness is pretty important for the visual style of my game. All of the basic functions already exist so I hope making the line thickness a parameter is not too much trouble :) 

It's ordered by importance for me, so the "DrawCircleLinesEx" is the function I would need the most. (But I pretty much need all of them ^^)

- DrawCircleLinesEx
- DrawLineStripEx
- DrawTriangleLinesEx
- DrawCircleSectorLinesEx
- DrawRingLinesEx
- DrawEllipseLinesEx

**Comment by raysan5** [comment]
@SoloByte I'm afraid those functions are out-of-scope for raylib but feel free to implement them for your specific use case.

**Comment by SoloByte** [comment]
Can I ask why they are out of scope? All of those already exist, it is just not possible to change the line thickness... Being able to draw rectangles and lines with line thickness but not circles and line strips is odd (at least for me). I don´t want to annoy you but Raylib basically checks all the boxes for what I need except those few functions.

I don't think I can implement them myself because I am using the c# bindings (Raylib CsLo) of raylib. 
I am already using my own c# functions for drawing line strips and triangles with line thickness by just using DrawLineEx but I can´t really do that (efficiently) for circles and rings...

Anyway thanks for taking the time to answer ;)

**Comment by SoloByte** [comment]
Okay I understand, I will figure something out ;) Thanks for answering and keep up the great work!

**Comment by chriscamacho** [comment]
GL_LINES are problematic especially width wise which had different maximums and often quite small depending on implementation to implementation...

In the end when I needed draw thick wires between nodes I used a cylinder model with a length of 1

I made a lookat matrix between the start and end points and inverted it, then made a scale matrix along the axis of the model to scale the length of the model between the start and end points

Munge those matrices together and you get a nice fat wire between the two points, simpler than it sounds and it worked first time...

`
            Vector3 hw = Vector3Subtract(from,to);
            hw.x = (hw.x / 2) + to.x;
            hw.y = (hw.y / 2) + to.y;
            hw.z = (hw.z / 2) + to.z;

            // angled between the input and output and scaled to length...
            Matrix wla = MatrixLookAt(from, to, (Vector3){0,1,0});
            wla = MatrixInvert(wla);
            wire.transform = MatrixMultiply(MatrixScale(1,1,Vector3Distance(from,to)),wla);
            DrawModel(wire,(Vector3){0,0,0},1,WHITE);
`
and et voilà

**Comment by M0JXD** [comment]
I'm new to raylib but quickly ran in to this.
For the ones that can be changed using rlSetLineWidth() is there any reason why they can't be added in the simple manner below for completion's sake?

```
void DrawCircleLinesEx(int centerX, int centerY, float radius, float lineThick, Color color)
{
    float oldLineWidth = rlGetLineWidth();
    rlSetLineWidth(oldLineWidth * lineThick);
    DrawCircleLines(centerX, centerY, radius, color);
    rlSetLineWidth(oldLineWidth);
}
```
