### ISSUE TITLE
[core] GetMonitorWidth/Height functions return wrong values on some monitors

### ISSUE THREAD

**Issue by SoloByte** [raysan5/raylib#2528]
### Issue description

Using GetMonitorWidth/Height functions is not reliable right now because they return the max available resolution of the monitor instead of the native resolution. I have tested some monitors and I have one 1920x1080 monitor where GetMonitorWidth/Height is returning 2560/1440 for width/height. 

I know that technically the function is doing the right thing and that my monitor is being weird but the point is I can't really use GetMonitorWidth/Height because that could happen with other monitors too. 

Using InitWindow with 0 for width and height sets the screen to the correct resolution, so InitWindow knows the native resolution of my monitor. (See code example below) It would be nice to have 2 different functions for getting the native monitor width/height and the max monitor width/height. 

### Environment

Windows 10 (I am using Raylib CsLo on Visual Studio 2022)

### Code Example

InitWindow(0, 0, "Window Title");
monitorWidth = GetMonitorWidth(0); //monitorWidth = 2560
monitorHeight = GetMonitorHeight(0); //monitorHeight = 1440
width = GetScreenWidth(); // width = 1920
height = GetScreenHeight(); //height = 1080

**Comment by raysan5** [comment]
@SoloByte Are you using latest raylib version from GitHub master branch? Those functions were reviewed some days ago.

**Comment by SoloByte** [comment]
I am not but I just looked at the pull request and it looks like the fix I needed. Sorry for opening an issue, I only checked the closed issues not the pull request.
