### ISSUE TITLE
[rtexture] Improvement of LoadImage feature

### ISSUE THREAD

**Issue by cos1110** [raysan5/raylib#2531]
This is not a BUG, but is more of a usability case.

Initially I would try to load an image in a C# application, but it would not work. But since wrappers and versioning are "ambiguous", I was not sure about it. Then I switched to a C++ and tried again to load an image. But still it would not work. I would then start to experiment with different sizes (just in case 3K images do not work), and different exporters (one exported from Krita, other exported from MsPaint) just in case something would mess the file's headers.

No more no less after spending three hours or so, I just figured out that only PNG images are supported. Everything worked fine and I would just try to load a JPG image.

So the outcome of my use case, is to consider two possible options:
* As you have mentioned before in some forums, that JPG images are not the best choice for applications. But still since we have hundreds of JPG files on our computer, is good to use some for quick testing purposes. Allowing JPG is not a bad idea, considering as well that there can be WASM applications running on the WEB, or perhaps building advanced applications with Raylib as a backend. Is a much more positive experience.
* The alternative way, if you really need to exclude JPG support entirely. At least, better than nothing, it would be to have a warning message appear on the console log, that would say "Warning: Only PNG images supported". So at least the user can compromise and create a PNG in a snap.

Thanks for the support. :)

**Comment by raysan5** [comment]
@cos1110 Supported file-formats can be configured just [uncommenting those lines](https://github.com/raysan5/raylib/blob/master/src/config.h#L148) and recompiling raylib.
