### ISSUE TITLE
[core/shape] Grid doesn't show through transparent shapes

### ISSUE THREAD

**Issue by computermouth** [raysan5/raylib#2533]
### Issue description

Description pretty much says it. Drawing a transparent cube on top of the grid won't show the grid through the shape. I looked through a few related tickets, I suspect this may be a known wont-fix. Just thought I'd throw it up here in case.

Otherwise, I've been loving the library, it's been a dream just picking up and playing around. Thanks for your work!

### Environment (linux, debian 11)
```
INFO: Initializing raylib 4.2-dev
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Screen size:  640 x 480
INFO:     > Render size:  640 x 480
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 223
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 20.3.5
INFO:     > GLSL:     4.60
```

### Issue Screenshot

![output](https://user-images.githubusercontent.com/7377029/174891375-1bf28990-c843-47e9-a082-335c09ec0950.gif)

**Comment by raysan5** [comment]
@computermouth I'm afraid this is out of scope for raylib, engines usually sort objects for drawing, front-to-back for opaque objects and back-to-front for transparent objects (with depth testing enabled). With raylib objects sorting is up to the user.

It should work as expected if you draw grid first and the transparent objects after it.

 > Otherwise, I've been loving the library, it's been a dream just picking up and playing around. Thanks for your work!

Glad you like it! :D
