### ISSUE TITLE
[build] Add -D _POSIX_C_SOURCE=200809L to CFLAGS

### ISSUE THREAD

**Issue by sanderboer** [raysan5/raylib#254]
Hi,

I'm just starting out with raylib, the emscripten layer is what interests me.
When building raylib, make fails on an implicit function declaration. I can't seem to be able to use nanosleep() (or usleep() ) without this error popping up. 
Apparently, the _POSIX_C_SOURCE macro must be defined with an appropriate value for the POSIX extensions to be available:

`ifeq ($(PLATFORM),PLATFORM_WEB)
    CFLAGS = -D _POSIX_C_SOURCE=200809L -O1 -Wall -std=c99 -s USE_GLFW=3 -s ASSERTIONS=1 --preload-file resources
    #-s ALLOW_MEMORY_GROWTH=1   # to allow memory resizing
    #-s TOTAL_MEMORY=16777216   # to specify heap memory size (default = 16MB)
endif
`

**Comment by raysan5** [comment]
Hi @sanderboer, this part was changed just some days ago... Are you using develop branch?

Maybe @RDR8 could give us some feedback, it was reviewed in PR https://github.com/raysan5/raylib/pull/248

**Comment by sanderboer** [comment]
Hi @raysan5 ,
I just checked out the master branch...

S

**Comment by RDR8** [comment]
Since you're using c99, use _DEFAULT_SOURCE is the flag you, as when compiling PLATFORM=PLATFORM_DESKTOP on Linux.

**Comment by RDR8** [comment]
No idea what is actually going on here. @sanderboer is right, master is broken but the changes made to the development branch at 44de97e are working for me "as is" on Linux. That is, without any _SOURCE type flags. Maybe --profilng CFLAG is the diff.

**Comment by RDR8** [comment]
@sanderboer If that code snippet above is in your makefile, check the syntax of -D_POSIX_C_SOURCE=200809L

**Comment by RDR8** [comment]
@sanderboer If that code snippet above is in your makefile, check the syntax of -D_POSIX_C_SOURCE=200809L

**Comment by sanderboer** [comment]
That code snippet is in my makefile, I added the -D_POSIX_C_SOURCE=200809L for it to compile.
Or do you mean, I'd try it with -D_DEFAULT_SOURCE instead of -D_POSIX_C_SOURCE=200809L ?

**Comment by sanderboer** [comment]
Wait, 
I forgot to mention, I'm building PLATFORM_WEB here, I needed to add -D_POSIX_C_SOURCE=200809L for the emscripten build.

btw. I double checked. 
On the master branch I can't build PLATFORM_WEB, unless I add -D_DEFAULT_SOURCE or -D_POSIX_C_SOURCE_200809L to the CFLAGS in the Makefile.

**Comment by raysan5** [comment]
Hi! Just integrated develop branch into master, it should be ok now, tried compiling for Windows and PLATFORM_WEB using Notepad++ script and it worked ok.

**Comment by RDR8** [comment]
@sanderboer understand about the platform.  I only mention Linux because I encountered a similiar issue there and made changes to the Makefiles recently. I think this is more of a c99 vs gnu99 issue, with each needing relevant CFLAGS. I'll update the Makefiles with options in the comments if @raysan5 already hasn't

I ask about the snippet because it has a typo. Just "no stone unturned' etc.. (^;

**Comment by RDR8** [comment]
This may help. #260

**Comment by raysan5** [comment]
Reviewed in commit https://github.com/raysan5/raylib/commit/82c54449bf4f472d2b46413288c0343e31eae8dc
