### ISSUE TITLE
[core] `PLATFORM_RPI` doesn't compile on Raspberry Pi OS Bullseye

### ISSUE THREAD

**Issue by electronstudio** [raysan5/raylib#2547]
I fixed some errors, but got stuck on this:

```
make PLATFORM=PLATFORM_RPI
gcc -c rcore.c -Wall -D_DEFAULT_SOURCE -DPLATFORM_RPI -DGRAPHICS_API_OPENGL_ES2 -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing  -std=c99 -fPIC -DEGL_NO_X11 -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads
rcore.c:377:9: error: unknown type name ‘EGL_DISPMANX_WINDOW_T’
  377 |         EGL_DISPMANX_WINDOW_T handle;       // Native window handle (graphic device)
```

The problem is the same as this: https://forums.raspberrypi.com/viewtopic.php?t=311687

The answer given there is that Bullseye no longer supports this GL stack, and that DRM should be used instead.  So if this is never going to work with any future versions, should PLATFORM_RPI be removed or marked as depreciated from Raylib?

**Comment by electronstudio** [comment]
I'm not running the experimental 64-bit Raspberry Pi OS, just the standard 32-bit, but still my `usr/include/EGL/eglplatform.h` doesn't include EGL_DISPMANX_WINDOW_T and `/opt/vc/include/EGL/eglplatform.h` doesn't exist, so it seems they have removed it from all versions (?)

**Comment by electronstudio** [comment]
PLATFORM_DRM works on the Pi 3.

**Comment by raysan5** [comment]
`PLATFORM_RPI` requires Dispmanx libraries and they have been removed on RPI OS Bullseye. This is a known issue.

`PLATFORM_RPI` is left for RPI OS Buster users, that still use Dispmanx. Maybe it will be removed in the future.

This issue has been commented in https://github.com/raysan5/raylib/issues/2229, also mentioned in raylib Discord many times...

It probably needs to be better documented in `rcore.c`, in `Makefile` and the raylib Wiki.

**Comment by electronstudio** [comment]
Yeah I think the wiki page should make it clear that if you're on Bullseye you should use PLATFORM_DRM, regardless of what model Pi you have.

**Comment by electronstudio** [comment]
I updated wiki a little.

**Comment by raysan5** [comment]
I further reviewed the Wiki: https://github.com/raysan5/raylib/wiki/Working-on-Raspberry-Pi

Probably `PLATFORM_RPI` will be removed in the future.
