### ISSUE TITLE
[examples] Broken mouse input and other examples issues

### ISSUE THREAD

**Issue by sanderboer** [raysan5/raylib#255]
Hi,

I am on a manjaro Linux machine and I noticed that the core_3d_camera_free example on the raylib website observed different mouseclicks than adverstised, i.e. the left-mouse button instead of the middle mouse button/wheel.
To make matters worse, when I built the example myself, no button worked. That is a real bummer.

It is probably a glfw3 matter, as raylib and emscripten come with their own version, maybe there is a conflict ? 
I am using emscripten 1.37.9 64 bits. Installed using `emsdk install sdk-1.37.9-64bit`

Any tips on how to approach this ?
Thanks,

Sander

**Comment by raysan5** [comment]
Hi @sanderboer, thanks for the feedback.

I've been just working on the web examples this week, not finished yet, I'm using latest raylib v1.7 from develop branch and just updated to `emsdk 1.37.9 64bit`. Before I was using `emsdk 1.35.0`, so, some things could have changed...

I'll try to address all the related issues and make sure all examples work.

**Comment by raysan5** [comment]
Status report on web examples (compiled with latest raylib develop branch and emsdk 1.37.9), only listing examples that doesn't work or have some issues:

 - [ ] `core_3d_camera_first_person`: Mouse lock not supported on web yet, needs to be implemented.
 - [ ] `core_input_gamepad`: Gamepad support on web has been added recently. Port example. 
 - [ ] `core_vr_simulator`: NEW example. Need to be adapted for web.
 - [ ] `text_rbmf_fonts`: Use .rbmf fonts, this custom fileformat is not supported anymore.
 - [ ] `text_font_selection`: Use .rbmf fonts, this custom fileformat is not supported anymore.
 - [ ] `text_sprite_fonts`: Color issues on spritefont texture (only on OpenGL ES 2.0).
 - [ ] `textures_raw_data`: Color issues with the checked board texture generation (only on OpenGL ES 2.0)
 - [ ] `textures_to_image`: Issues on getting image data from texture (GPU -> CPU), incorrect format.
 - [ ] `textures_formats_loading`: This example is being redesigned...
 - [ ] `textures_particles_trail_blending`: Color issues on particle texture (only OpenGL ES 2.0)
 - [ ] `shapes_lines_bezier`: NEW example. Need to be adapted for web
 - [ ] `shaders_basic_lighting`: Redesigned example, lighting shader needs to be reviewed for Web.

Some examples are not added yet to the web, should be there soon...

**Comment by raysan5** [comment]
Update 1: Color issues seem to have been solved after recompiling...

**Comment by sanderboer** [comment]
fwiw, there is a nice write-up of touch on multiplatform:
http://flohofwoe.blogspot.nl/2014/10/cross-platform-multitouch-input.html

**Comment by raysan5** [comment]
hey @sanderboer, thanks for the info! good reference! 

Actually that stuff was already implemented in raylib gestures system, here it is an example: http://www.raylib.com/examples/web/loader.html?name=core_gestures_detection

Additionally, raylib can process mouse inputs as touches to detect gestures (and the other way round). That's specially useful if you create a game for desktop platform and then you recompile it for Android.

**Comment by raysan5** [comment]
All the examples have been reviewed, some details still pending but I'm closing this issue.
