### ISSUE TITLE
[rtext] `LoadFontEx()` fails to package some specified codepoints 

### ISSUE THREAD

**Issue by iikare** [raysan5/raylib#2550]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I am using the SMuFL specification and a SMuFL-compatible font to render music symbols using raylib through codepoints in Unicode range `0xE000`-`0xED5F`. However, only the first 8 codepoints I specify are rendered by raylib (ref: first screenshot). I attempted to use a different SMuFL font (i.e. Bravura), and had the same issue. 

Changing the order of the vector defining the codepoints allows different glyphs to be rendered, but the limit of 8 total
characters remains (ref: second screenshot).

Interestingly, the debug output shows the following:

```
INFO: FILEIO: [leland.otf] File loaded successfully
WARNING: FONT: Failed to package character (8)
WARNING: FONT: Failed to package character (9)
WARNING: FONT: Failed to package character (10)
WARNING: FONT: Failed to package character (11)
WARNING: FONT: Failed to package character (12)
WARNING: FONT: Failed to package character (13)
INFO: TEXTURE: [ID 3] Texture loaded successfully (256x256 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Data loaded successfully (200 pixel size | 14 glyphs)
```

### Environment

Issue reproduced on both raylib 4.0 and 4.2-dev. 

Desktop/Arch Linux, OpenGL 4.6/3.3, Comet Lake GT2/GTX1070

Compiled via:
`clang++ test.cc -lraylib -o test && ./test`

### Issue Screenshot

The remainder of the codepoints should render next to the 8th codepoint "4". The red text is my commentary.

![image](https://user-images.githubusercontent.com/13582030/175478961-3d27340a-1a31-4ab6-bf93-f23d1254ae22.png)

![image](https://user-images.githubusercontent.com/13582030/175480855-def17832-5d81-4d70-bdc9-ffe6d6e4c7fb.png)

### Code Example

The font provided is from this repository: https://github.com/MuseScoreFonts/Leland

I reproduced this issue with the below minimal working example.

```C++
#include "raylib.h"
//#include "../../src/agh/leland.h"

#include <vector>

using std::vector;

vector<int> codepointSet = {
  0xE000,  0xE050,  0xE062,  0xE080,  0xE081,  0xE082,  0xE083,  0xE084,  0xE085,  0xE086,  0xE087,  0xE088,  0xE089,  0xE0A2,
};

int main(void) {
  InitWindow(800,450 , "raylib [core] example - basic window");
  SetExitKey(KEY_F7);
  const int fSize = 200;

  //Font f = LoadFontFromMemory(".otf", __data_font_leland_otf, __data_font_leland_otf_len, 
                              //fSize, codepointSet.data(), codepointSet.size());
  Font f2 = LoadFontEx("leland.otf", fSize, codepointSet.data(), codepointSet.size());

  while (!WindowShouldClose()) {
    BeginDrawing();
      ClearBackground(RAYWHITE);
      for (auto i = 0; i < codepointSet.size(); ++i) {
        //DrawTextCodepoint(f, codepointSet[i], {static_cast<float>(90+40*i),100}, fSize, LIGHTGRAY);
        DrawTextCodepoint(f2, codepointSet[i], {static_cast<float>(90+40*i),200}, fSize, LIGHTGRAY);
      }
    EndDrawing();
  }

  CloseWindow();

  return 0;
}
```

**Comment by raysan5** [comment]
@iikare I'm afraid this is a complex issue. It fails to package some characters into the atlas because the atlas size is estimated depending on the font and provided codepoints.

The easiest solution is to add some codepoints to the list and problably the estimated package size will get bigger and all of them will fit in there.

Atlas size estimation has already been reviewed many times but there is always some font/situation where it does not work as expected.
