### ISSUE TITLE
[projects] Still trying to compile physics project

### ISSUE THREAD

**Issue by TokyoSU** [raysan5/raylib#2551]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description
Probably all the projects in the projects folder try to compile the physics examples but since they dont exists anymore it just fail to compile it, it dont impact raylib compilation.

### Environment
Windows 8.1 X64, Raylib 4.2-Dev from Master, VS2019 project

### Issue Screenshot
None

### Code Example
None

**Comment by raysan5** [comment]
Just removed all physac/physics references I found in projects.
