### ISSUE TITLE
Packages for various linux distributions

### ISSUE THREAD

**Issue by angushall-spot** [raysan5/raylib#2571]
I'm not sure about how others feel about this but for developers on linux, not having a package for C(++) libraries is a huge pain in the butt because you have to compile them, but that's not a huge problem. 

What is a problem though is that after that, you have some random C libraries floating around in your system, not tracked by your package manager, and each with their own unique locations and properties and ways to be uninstalled. 

This is not a fault of raylib, it's a fault of how C(++) works, but for linux there is a way to solve this and that is by having packages that users on  linux can install with their package managers. You don't even necessarily need to maintain repositories, you can just have package files that users can download, and then at least they'll be tracked by their package managers, and as such can easily be updated and removed,

I'm sure many developing on linux would appreciate this!

**Comment by chriscamacho** [comment]
nah, I really don't see the point of this, its not like you have to "install" raylib, I simply have a git clone of master and all my projects statically link to the compiled raylib (which is a trivial build).  If I did want it as a shared library for some reason, there's no reason why a single symbolic link couldn't be used. No installing, uninstalling, no need for random anything "floating" around

**Comment by raysan5** [comment]
@angushall-spot I'm afraid this is out of scope for raylib, it requires an extra maintenance work that I can no assume.
