### ISSUE TITLE
Bug: The runtime halts at `void ImageResize()`

### ISSUE THREAD

**Issue by zzxoto** [raysan5/raylib#2572]
https://github.com/raysan5/raylib/blob/05dc300296e32e1f005d10ded9473d0b0387ae95/src/rtextures.c#L1417

The line number posted above might be a bug which is causing the following issue:

The runtime halts at `void ImageResize(Image *image, int newWidth, int newHeight)` function with the following error: `Critical error detected c0000374`. Also right at this moment, the callstack explodes with bunch of `ntdll.dll` function calls.

I came across this bug when doing an `void ImageDraw(Image *dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint)` call. I'll attach the screenshot of the precise parameters.
![debug_screenshot](https://user-images.githubusercontent.com/24535070/178137055-9a4dacb3-b7b3-4763-9cbb-9135b848e555.PNG)

Library installation info:
```
Package: raylib
Version: 4.0.0
Depends: vcpkg-cmake, vcpkg-cmake-config
Architecture: x64-windows
```

**Comment by raysan5** [comment]
@zzxoto Just reviewed `ImageResize()`, please, could you test the changes? Feel free to reopen the issue if problem persists.

**Comment by zzxoto** [comment]
The commit didn't fix the issue. This is reproducable. Try below. Also I have attached the image I have used during testing.

```
#include "stdio.h"
#include "raylib.h"
#include "stdlib.h"

int screenW = 800;
int screenH = 800;

void draw(Image &src, Image &dst)
{
  Rectangle srcRec = { 89.99992, 89.999969, 320.0003, 320.0003 };
  Rectangle dstRec = { 0, 0, 600, 600 };

  ImageDraw(&dst, src, srcRec, dstRec, WHITE);
}

int main(void)
{
  InitWindow(screenW, screenH, "Pleasant paint program");

  Image src = LoadImage("image2_png.png");
  Image dst = ImageCopy(src);
  ImageResize(&dst, 600, 600);

  SetTargetFPS(60);

  while (!WindowShouldClose())
  {
    BeginDrawing();

    ClearBackground(ORANGE);

    draw(src, dst);

    EndDrawing();
  }

  CloseWindow();

  return 0;
}
```

Image: 
https://user-images.githubusercontent.com/24535070/178372387-5e88ea0d-e9de-4fe6-862e-70e1aeaf29e0.png

Library installation info
```
CRTLinkage: dynamic
LibraryLinkage: dynamic
Version: 3ebfee5dbc1d0de5555105f4989954cd4547bafd
```

I am getting error at `void ImageResize(Image *image, int newWidth, int newHeight)
` at line `unsigned char *output = (unsigned char *)RL_MALLOC(newWidth*newHeight*bytesPerPixel);
` and line `RL_FREE(image->data);` following the ` ImageDraw(&dst, src, srcRec, dstRec, WHITE);` call.

Error
```
Critical error detected c0000374

HEAP[main.exe]: Heap block at 000001733BC65180 modified at 000001733BCC91C4 past requested size of 64034
```

**Comment by orcmid** [comment]
> @zzxoto : I came across this bug when doing an `void ImageDraw(Image *dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint)` call.

The problem seems to be in your `void draw(Image &src, Image &dst)` 
which should probably be `void draw(Image src, Image *pdst)`

and then the internal IMageDraw should be
   `ImageDraw(pdst, src, srcRec, dstRec, WHITE);1

You can avoid the possible extra copy of `src`, but see if this works first.

**Comment by zzxoto** [comment]
@orcmid I have deleted the old commend and posted a new issue at https://github.com/raysan5/raylib/issues/2577 .

I tried what you suggested but it didn't work.
