### ISSUE TITLE
[core] LoadDirectoryFiles() returns files list unsorted on linux

### ISSUE THREAD

**Issue by npisanti** [raysan5/raylib#2578]
Is it normal for linux to return files unsorted, libs like [tinydir](https://github.com/cxong/tinydir) have specific functions to return an explicitly sorted list, but i think it having an alphabetically sorted list should be the expected behavior for `LoadDirectoryFiles()` and `LoadDirectoryFilesEx()`, right?  

test app with input directories from argv:

```c
#include <math.h>
#include "raylib.h"
#include "stdio.h"

int main( int argc, char ** argv ) {
	int screenWidth = 400;
	int screenHeight = 200;

	InitWindow(screenWidth, screenHeight, "raylib");

	for( int i=0; i<argc; ++i ){
		if( DirectoryExists( argv[i] ) ){
			printf( "arg %s is a directory\n", argv[i] );
			FilePathList files = LoadDirectoryFiles( argv[i] );
			for( int j=0; j<files.count; ++j ){
				printf( "file %d = %s\n", j, files.paths[j] );
			}
		}
	}

	SetTargetFPS(60);
	while (!WindowShouldClose()) {
		BeginDrawing();
		ClearBackground( (Color){40, 0, 0, 255} );
		DrawText("press esc to quit", 10, 40, 20, WHITE);
		EndDrawing();
	}
	CloseWindow();
	return 0;
}
```

**Comment by the-gremlin** [comment]
The files being returned unordered is default linux behaviour, as `LoadDirectoryFiles` uses the `readdir` function, which states explicitly that it is unlikely that the files are going to be sorted in any way, as the way they are ordered depends on the filesystem implementation. So the sorting would have to be done inside of `LoadDirectoryFiles`

**Comment by raysan5** [comment]
@npisanti that funtion just returns the list as provided by the system libraries, probably that's good for most users, no need for extra unneeded overhead. It's up to the users requiring it to sort the strings properly if they need it.

**Comment by orcmid** [comment]
> @raysan5 @npisanti ... It's up to the users requiring it to sort the strings properly if they need it.

I concur.  This avoids all manner of issues with respect to character sets, internationalization, and different ideas about what sorted sequences are.

**Comment by npisanti** [comment]
> @npisanti that function just returns the list as provided by the system libraries, probably that's good for most users, no need for extra unneeded overhead. It's up to the users requiring it to sort the strings properly if they need it.

@raysan5 that's fine, i needed the files in order as they were different frames of an animation so having them unordered would scramble the animation. It would be nice to have it stated in the documentation that the returned files are unsorted.

thanks anyway!

**Comment by orcmid** [comment]
@npisanti 1. Try moving them into a fresh directory in the order you want them to be retrieved in.  That *might* work.  It will depend very much on the file system though.  2. Alternatively, give them simple numerical names so you can easily retrieve them by generated names.  That would work on any platform. 3. Make them resources included in your executable.  That might not be ideal depending on sizes and quantity.

There are probably other techniques that would work, such as using a manifest file that names your desired files in the order you want them to be used in.  

None of these require you to sort a list of filenames on the fly.

**Comment by npisanti** [comment]
@orcmid i was building my own (cli) atlas packer, so sorting the filenames is the best option for this as all the other would add friction to the workflow. 2 could work as i acquire hand drawn frames with the webcam and so i save them in order, but sometimes they are not an animation and i delete some frames and that will screw up the loading. 

In the final executable many animation will just share the same atlas so file ordering won't be a problem
