### ISSUE TITLE
[example] text_draw_3d missing in VS2022

### ISSUE THREAD

**Issue by Crydsch** [raysan5/raylib#2580]
I noticed the text_draw_3d example is missing from the VS2022 project.
Not sure if this wanted or just an oversight.
It does build on linux using the Makefile - that is how I noticed.

I am not too familiar with the solutions structure and this is probably an easy fix for those who are.

**Comment by raysan5** [comment]
@Crydsch Yeah, actually there are probably some missing examples in the VS2022 solution, the ones added recently... I will review it.
