### ISSUE TITLE
Incorrect Vector3ClampValue return

### ISSUE THREAD

**Issue by Timofffee** [raysan5/raylib#2584]
Returns a zero vector if value is within range. The same goes with Vector2ClampValue.
https://github.com/raysan5/raylib/blob/4a9391ae83757afd86b6f1cccae4335c611b5b41/src/raymath.h#L954

**Comment by TokyoSU** [comment]
it could be `result = v` and later be `result.x *= scale`, it would be more simple this way (same for Vector2ClampValue)

**Comment by raysan5** [comment]
@Timofffee @TokyoSU thanks for pointing the issue! feel free to send a PR with the fix!
