### ISSUE TITLE
Visual Studio examples wrong relative path

### ISSUE THREAD

**Issue by Effer** [raysan5/raylib#259]
Hi,
first of all great job @raysan5 . 
I think last refactor of code example broke the link in the VS2015 project:
it's:
..\..\..\examples\core_basic_window.c
it should be
 ..\..\..\examples\core\core_basic_window.c

Both in master and develop branch. It's an easy fix and will help newcomers.

**Comment by raysan5** [comment]
Hey @Effer! Thanks for pointing this issue!

I'm doing some work with examples (add, remove, modify), trying to update collection a bit...

Issue corrected in commit https://github.com/raysan5/raylib/commit/74255b6eb2584c272ff647cfbac1cdceceb1965f

**Comment by Effer** [comment]
Hi @raysan5 , tested and works perfectly.
Debug on VS is very comfortable, thanks for share the solution.

Do you plan to write a book? I would be very interested in learn game programming from you, but come to your country and follow your course could be cumbersome :)

**Comment by raysan5** [comment]
Hey @Effer! You're welcome!

I would really like to write a book about game development, it's been 5 years now teaching games dev (programming, data management, optimization, graphics, projects organization...) and I really got a lot of knowledge to share from an educational point of view (knowing common student errors, concepts that are more difficult to understand, best ways to share specific knowledge...). 

Unfortunately, right know, I don't have enough time, my job takes me lot of effort (teaching up to 8 different subjects) and raylib takes most of my spare time... but maybe in a future... ;)
