### ISSUE TITLE
vscode-template-main 386 architecture of input file `C:/dev/my/raylib/raylib_git/raylib-4.0.0/src/raylib.rc.data' is incompatible with i386:x86-64 output

### ISSUE THREAD

**Issue by meiry** [raysan5/raylib#2593]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
 - [ ] I checked there is no similar issue already reported
 - [ ] My code has no errors or misuse of raylib

### Issue description

*using the tamplate vscode-template-main  when compiling getting this link error .*
```
vscode-template-main 386 architecture of input file `C:/dev/my/raylib/raylib_git/raylib-4.0.0/src/raylib.rc.data' is incompatible with i386:x86-64 output
````

I compiled the raylib using the w64devkit 

### Environment

windows 10 

### Issue Screenshot

![image](https://user-images.githubusercontent.com/1107316/181072598-0c709a1b-4f7e-4124-8134-3567e1f94333.png)

 
**BUT** when comment out the line in the makefile all workes  
![image](https://user-images.githubusercontent.com/1107316/181072746-d5c6c47c-7509-4c90-9ab0-88bedc3e3645.png)

**Comment by raysan5** [comment]
answered in the Wiki FAQ
