### ISSUE TITLE
[raymath] Result of MatrixRotate() and MatrixRotateX/Y/Z differs

### ISSUE THREAD

**Issue by GoodNike** [raysan5/raylib#2595]
### Issue description

Resulting matrix of MatrixRotate() and MatrixRotateX/Y/Z differs, watch example code below.

### Code Example

```
Matrix mat1 = MatrixRotate({1, 0 , 0}, PI/4);    /* Rotate around X. */
Matrix mat2 = MatrixRotateX(PI/4);
```

The mat1 matrix is correct. The mat2 matrix fields m6 and m9 have a wrong sign. Same goes to MatrixRotateY() (m2 and m8), MatrixRotateZ() (m1 and m4).

**Comment by raysan5** [comment]
@GoodNike Thanks for reporting this issue! Feel free to send a PR with the fix!

**Comment by chriscamacho** [comment]
isn't -m6 m9 vs m6 -m9 equivalent once converted back to eular rotations ?

there are multiple matrix (and quats) that can result from the same eular angles, depending on method of calculation, comparing matrices is likely to not work very well under different circumstances and probably not great for checking if an orientation is within a specific range.

**Comment by GoodNike** [comment]
@chriscamacho thanks for reply! MatrixRotate rotates counter-clockwise, MatrixRotateX/Y/Z rotates clockwise

We could:
1. do nothing, consider it correct
2. fix it to get same result
3. live a comment explaining things

If those functions intend to simplify MatrixRotate we should do 2.

@raysan5 what do you think?

**Comment by raysan5** [comment]
@GoodNike Agree with **2** and also **3**. I think the rotation should be **clockwise**, it's the most intuitive for raylib users.

The issue now is not only updating `MatrixRotate()` but also check **all the other rotation functions** to make sure they stick to the same convention!

**Comment by orcmid** [comment]
I think "natural" sense of rotation depends on how the coordinate system is anchored.  If the origin is considered upper-left corner, then yes.  If lower-left, (positive ordinates to the right and also up) than anti-clockwise is traditional, at least when I was learning trigonometry :).  

On the other hand, when sailing and looking at a compass, the degrees grow clockwise.  (90 is East, 180 is South, etc.)

I suspect how transformations work should be decisive.  (I am being lazy.)

**Comment by raysan5** [comment]
Afaik, the following functions are the only ones implementing some kind of rotation:
```c
Vector2 Vector2Rotate(Vector2 v, float angle)
Vector3 Vector3RotateByQuaternion(Vector3 v, Quaternion q)
Vector3 Vector3RotateByAxisAngle(Vector3 v, Vector3 axis, float angle)
Matrix MatrixRotate(Vector3 axis, float angle)
Matrix MatrixRotateX(float angle)
Matrix MatrixRotateY(float angle)
Matrix MatrixRotateZ(float angle)
Matrix MatrixRotateXYZ(Vector3 angle)
Matrix MatrixRotateZYX(Vector3 angle)
```

**Comment by GoodNike** [comment]
Sorry, i messed it up: MatrixRotate rotates clockwise, MatrixRotateX/Y/Z rotates counter-clockwise.

@orcmid as far as i can see in 3D on this topic clockwise rotation is a standard. For example, [https://learnopengl.com/Getting-started/Transformations](https://learnopengl.com/Getting-started/Transformations), section "Rotation", OpenGL deprecated function [glRotate](https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glRotate.xml), glm [rotate()](https://github.com/g-truc/glm/blob/master/glm/ext/matrix_transform.inl)

**Comment by raysan5** [comment]
@GoodNike Nice! It makes more sense to me, I implemented `MatrixRotate()` long time ago and I imagined it would follow the most intuitive convention: clockwise.

Feel free to send a PR to fix any of the other functions if you want, you are welcome.

**Comment by orcmid** [comment]
@GoodNike It is clear that GLM considers rotation about the Z axis to be clockwise.  But https://en.wikipedia.org/wiki/Rotation_matrix

We should be careful about the use of "standard."  Notice that the Wikipedia article is specific about applying in case of a right-handed coordinate systems (Y axis vertical and increasing upward, X axis horizontal and increasing rightward).  I agree that whatever the chosen convention is, it should be consistent with a given API.  It is also why I asked about the coordinate system.

**Comment by raysan5** [comment]
@orcmid Thanks for the note. raylib actually uses OpenGL default coordinate system for 3d, with Y axis increasing upwards. For 2D the coordinate system is configured to follow most common convention of Y in the top-left corner increasing downward (following the old TV tracing beams).

**Comment by orcmid** [comment]
@raysan5 I too have favored the flipped (y increasing downward) principal quadrant 2D coordinate system. - it has the advantage of raster drawing and also line printing sometimes.  In that case, clockwise in the principal quadrant becomes counter-clockwise in the flipped view.  It's all a matter of perspective.  :).

**Comment by chriscamacho** [comment]
Well spotted, my suggestion would be 2 as well...

On Thursday, 28 July 2022, Nikolay Krasheninnikov ***@***.***>
wrote:
> @chriscamacho thanks for reply! MatrixRotate rotates counter-clockwise,
MatrixRotateX/Y/Z rotates clockwise
>
> We could:
>
> do nothing, consider it correct
> fix it to get same result
> live a comment explaining things
>
> If those functions intend to simplify MatrixRotate we should do 2.
>
> @raysan5 what do you think?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/proxy/Vh31TI-Wm6o0ayRIS2yjWXHXNvoE83jy8t53EC6Phiuo4_qdcn9SMw5801Chi6OxiKKJJcID0Cd2TI1hbWfWXCG1D20X-oTV_3RXxsAIyOQZJLpNzVr-skrCG6OCqJdrHbV8S0Q0_saISvO0XRFTTdtgwrkfqNiNpl799LJItuJ6l7CYtmQVLmVr6UlYKvRErKA3emyrff6Af4ja4eblEbF3CP4i4MIEWZ8M52QejQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAFO4SKH3KIE7K7DZGSHQOLVWI2NZA5CNFSM54YWXVBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOI5SK45A.gif>Message
ID: ***@***.***>

-- 

blog bedroomcoders.co.uk <http://bedroomcoders.co.uk>
Free source code and tutorials!


Disclaimer:
By sending an email to ANY of my addresses you are agreeing that:

   1. I am by definition, "the intended recipient"

   2. All information in the email is mine to do with as I see fit and make
such financial profit, political mileage, or good joke as it lends itself
to. In particular, I may quote it where I please.

   3. I may take the contents as representing the views of your company.

   4. This overrides any disclaimer or statement of confidentiality that
may be included on your message.
