### ISSUE TITLE
[module] Following the tutorial, I can't compile to android.

### ISSUE THREAD

**Issue by lichanghaix** [raysan5/raylib#2597]
https://github.com/raysan5/raylib/wiki/Working-for-Android

I followed every step of this tutorial but can't compile to android.
And prompt the following errors.

or: undefined reference to 'TextSubtext'
android.raylib_game/obj/screen_logo.o:screen_logo.c:function DrawLogoScreen: err
or: undefined reference to 'GetScreenWidth'
android.raylib_game/obj/screen_logo.o:screen_logo.c:function DrawLogoScreen: err
or: undefined reference to 'GetScreenHeight'
android.raylib_game/obj/screen_logo.o:screen_logo.c:function DrawLogoScreen: err
or: undefined reference to 'DrawText'
android.raylib_game/obj/screen_logo.o:screen_logo.c:function DrawLogoScreen: err
or: undefined reference to 'DrawText'
android.raylib_game/obj/screen_title.o:screen_title.c:function UpdateTitleScreen
: error: undefined reference to 'IsKeyPressed'
android.raylib_game/obj/screen_title.o:screen_title.c:function UpdateTitleScreen
: error: undefined reference to 'IsGestureDetected'
android.raylib_game/obj/screen_title.o:screen_title.c:function UpdateTitleScreen
: error: undefined reference to 'PlaySound'
android.raylib_game/obj/screen_title.o:screen_title.c:function DrawTitleScreen:
error: undefined reference to 'DrawTextEx'
android.raylib_game/obj/screen_title.o:screen_title.c:function DrawTitleScreen:
error: undefined reference to 'DrawText'
android.raylib_game/obj/screen_gameplay.o:screen_gameplay.c:function UpdateGamep
layScreen: error: undefined reference to 'IsKeyPressed'
android.raylib_game/obj/screen_gameplay.o:screen_gameplay.c:function UpdateGamep
layScreen: error: undefined reference to 'IsGestureDetected'
android.raylib_game/obj/screen_gameplay.o:screen_gameplay.c:function UpdateGamep
layScreen: error: undefined reference to 'PlaySound'
android.raylib_game/obj/screen_gameplay.o:screen_gameplay.c:function DrawGamepla
yScreen: error: undefined reference to 'DrawTextEx'
android.raylib_game/obj/screen_gameplay.o:screen_gameplay.c:function DrawGamepla
yScreen: error: undefined reference to 'DrawText'
android.raylib_game/obj/screen_ending.o:screen_ending.c:function UpdateEndingScr
een: error: undefined reference to 'IsKeyPressed'
android.raylib_game/obj/screen_ending.o:screen_ending.c:function UpdateEndingScr
een: error: undefined reference to 'IsGestureDetected'
android.raylib_game/obj/screen_ending.o:screen_ending.c:function UpdateEndingScr
een: error: undefined reference to 'PlaySound'
android.raylib_game/obj/screen_ending.o:screen_ending.c:function DrawEndingScree
n: error: undefined reference to 'DrawTextEx'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile.Android:264: compile_project_code] Error 1
make[1]: Leaving directory 'D:/raylib_proj/src'
make: *** [Makefile:401: all] Error 2

**Comment by raysan5** [comment]
@lichanghaix this issue seems related to a wrong raylib library compilation and linkage, not an issue with raylib library. Afaik other users are using raylib on Android with no problems. I recommend you join raylib Discord to ask for help, there is a specific channel for raylib building issues.

**Comment by lichanghaix** [comment]
> @lichanghaix这个问题似乎与错误的 raylib 库编译和链接有关，而不是 raylib 库的问题。Afaik 其他用户在 Android 上使用 raylib 没有问题。我建议你加入 raylib Discord 寻求帮助，raylib 构建问题有一个特定的渠道。

I posted this question on discard.
Someone helped me but couldn't solve it.
Can you help think of a way?
