### ISSUE TITLE
Document howto build for wayland

### ISSUE THREAD

**Issue by yujiri8** [raysan5/raylib#2600]
### Issue description

I don't see it documented how to build for wayland. I found some old github issues saying that it's done by setting USE_WAYLAND_DISPLAY in the make step, but I set that to TRUE in my environment and still got a build for X. By looking at the alpine linux package for raylib-wayland, I learned that the solution is to pass -DUSE_WAYLAND=ON in the cmake step, and that worked for me.

Shouldn't this be in the README or Wiki?

### Environment

Alpine Linux edge, x86-64, OpenGL 4.6

**Comment by raysan5** [comment]
@yujiri8 Added required information to raylib Wiki: https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux#wayland
