### ISSUE TITLE
How to display chinese character?

### ISSUE THREAD

**Issue by yangyagami** [raysan5/raylib#2609]
I try to use **LoadFontFromMemory** but it can't display chinese character.

**Comment by raysan5** [comment]
@yangyagami A new example was added recently to illustrate codepoints loading: https://www.raylib.com/examples/text/loader.html?name=text_codepoints_loading

**Comment by yangyagami** [comment]
> @yangyagami A new example was added recently to illustrate codepoints loading: https://www.raylib.com/examples/text/loader.html?name=text_codepoints_loading

> 

When I try to display "您好", It only one character be displayed.


`#include "raylib.h"

#include <stdlib.h>         // Required for: calloc(), realloc(), free()
#include <string.h>         // Required for: memcpy()

// Text to be displayed, must be UTF-8 (save this code file as UTF-8)
// NOTE: It can contain all the required text for the game,
// this text will be scanned to get all the required codepoints
static char *text = "您好";

// Remove codepoint duplicates if requested
static int *CodepointRemoveDuplicates(int *codepoints, int codepointCount, int *codepointResultCount);


//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [text] example - codepoints loading");

    // Get codepoints from text
    int codepointCount = 0;
    int *codepoints = LoadCodepoints(text, &codepointCount);

    // Removed duplicate codepoints to generate smaller font atlas
    int codepointsNoDupsCount = 0;
    int *codepointsNoDups = CodepointRemoveDuplicates(codepoints, codepointCount, &codepointsNoDupsCount);
    UnloadCodepoints(codepoints);

    // Load font containing all the provided codepoint glyphs
    // A texture font atlas is automatically generated
    Font font = LoadFontEx("assets/test.ttf", 36, codepointsNoDups, codepointsNoDupsCount);

    // Set bilinear scale filter for better font scaling
    SetTextureFilter(font.texture, TEXTURE_FILTER_BILINEAR);

    // Free codepoints, atlas has already been generated
    free(codepointsNoDups);

    bool showFontAtlas = false;

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        if (IsKeyPressed(KEY_SPACE)) showFontAtlas = !showFontAtlas;
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            DrawRectangle(0, 0, GetScreenWidth(), 70, BLACK);
            DrawText(TextFormat("Total codepoints contained in provided text: %i", codepointCount), 10, 10, 20, GREEN);
            DrawText(TextFormat("Total codepoints required for font atlas (duplicates excluded): %i", codepointsNoDupsCount), 10, 40, 20, GREEN);

            if (showFontAtlas)
            {
                // Draw generated font texture atlas containing provided codepoints
                DrawTexture(font.texture, 150, 100, BLACK);
                DrawRectangleLines(150, 100, font.texture.width, font.texture.height, BLACK);
            }
            else
            {
                // Draw provided text with laoded font, containing all required codepoint glyphs
                DrawTextEx(font, text, (Vector2) { 160, 110 }, 48, 5, BLACK);
            }

            DrawText("Press SPACE to toggle font atlas view!", 10, GetScreenHeight() - 30, 20, GRAY);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadFont(font);     // Unload font

    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}

// Remove codepoint duplicates if requested
// WARNING: This process could be a bit slow if there text to process is very long
static int *CodepointRemoveDuplicates(int *codepoints, int codepointCount, int *codepointsResultCount)
{
    int codepointsNoDupsCount = codepointCount;
    int *codepointsNoDups = (int *)calloc(codepointCount, sizeof(int));
    memcpy(codepointsNoDups, codepoints, codepointCount*sizeof(int));

    // Remove duplicates
    for (int i = 0; i < codepointsNoDupsCount; i++)
    {
        for (int j = i + 1; j < codepointsNoDupsCount; j++)
        {
            if (codepointsNoDups[i] == codepointsNoDups[j])
            {
                for (int k = j; k < codepointsNoDupsCount; k++) codepointsNoDups[k] = codepointsNoDups[k + 1];

                codepointsNoDupsCount--;
                j--;
            }
        }
    }

    // NOTE: The size of codepointsNoDups is the same as original array but
    // only required positions are filled (codepointsNoDupsCount)

    *codepointsResultCount = codepointsNoDupsCount;
    return codepointsNoDups;
}
`

![image](https://user-images.githubusercontent.com/45322657/182542192-1f176091-82df-48fe-af21-62d0aaf477ec.png)

**Comment by raysan5** [comment]
@yangyagami this could be because the font provided does not contain the second glyph.

**Comment by yangyagami** [comment]
> @yangyagami this could be because the font provided does not contain the second glyph.
> 
> You can try drawing the `font.texture` to see the contained glyphs.
![image](https://user-images.githubusercontent.com/45322657/182569266-dad92aed-c21d-40d7-a174-6ca542a415a8.png)
If the string is "您好啊" it can be display. But the string "您好" only display firsh character.

**Comment by yangyagami** [comment]
> @yangyagami this could be because the font provided does not contain the second glyph.
> 
> You can try drawing the `font.texture` to see the contained glyphs.

![image](https://user-images.githubusercontent.com/45322657/182570532-2797f444-a917-4912-b924-76df081d4eac.png)

**Comment by raysan5** [comment]
@yangyagami this is weird, maybe a bug. Could you share the font used or link to it for testing?

**Comment by yangyagami** [comment]
> @yangyagami this is weird, maybe a bug. Could you share the font used or link to it for testing?

https://zf.sc.chinaz.com/Files/DownLoad/font/xmfont3762.rar

**Comment by raysan5** [comment]
@yangyagami Just tested it and it works as expected on my device:

![image](https://user-images.githubusercontent.com/5766837/183072818-2364d3c8-2d31-4ab1-b6ac-9cf2fc39602d.png)

I think it can be related to the code file, it should be saved as UTF-8. Probably Visual Studio saves it with another text encoding.

**Comment by yangyagami** [comment]
> @yangyagami Just tested it and it works as expected on my device:
> 
> ![image](https://user-images.githubusercontent.com/5766837/183072818-2364d3c8-2d31-4ab1-b6ac-9cf2fc39602d.png)
> 
> I think it can be related to the code file, it should be saved as UTF-8. Probably Visual Studio saves it with another text encoding.

I tested it on the Linux. I had set the code file as UTF-8. It doesn't work.

**Comment by raysan5** [comment]
@yangyagami Could you debug it to see where is the issue? I'm afraid I can't do more on my side...

**Comment by yangyagami** [comment]
> @yangyagami Could you debug it to see where is the issue? I'm afraid I can't do more on my side...

I set the text as "好好". It can be displayed.
![image](https://user-images.githubusercontent.com/45322657/183227115-e9aaee09-cc6d-4769-bc07-d0f793dcf0c9.png)
When i toggle font atlas view 
![image](https://user-images.githubusercontent.com/45322657/183227130-46291bbd-3959-48ac-827c-e6a43951e37f.png)
Then I set the text as "您好好". It doesn't work again.
![image](https://user-images.githubusercontent.com/45322657/183227275-c059a5f7-81eb-455e-b94f-c550fc4d939e.png)
If I set the test as "您好好啊". 
![image](https://user-images.githubusercontent.com/45322657/183227338-951ae49c-3b60-4445-a73b-2aad24d97cc3.png)
![image](https://user-images.githubusercontent.com/45322657/183227384-64b8152f-1701-43f1-91e4-d339661054c2.png)

**Comment by yangyagami** [comment]
> @yangyagami Could you debug it to see where is the issue? I'm afraid I can't do more on my side...

I just adjust the font size. It worked.
![image](https://user-images.githubusercontent.com/45322657/183227622-51bba1e1-35fc-45eb-a89b-57812aa406c9.png)
**Font size : 36** Don't work.
![image](https://user-images.githubusercontent.com/45322657/183227657-db85f363-7919-4fe3-a7dc-1f88ed05219e.png)

**Comment by raysan5** [comment]
@yangyagami are you using latest raylib from github master branch? I think the issue could be on atlas size estimation and it was reviewed some days ago

**Comment by yangyagami** [comment]
> @yangyagami are you using latest raylib from github master branch? I think the issue could be on atlas size estimation and it was reviewed some days ago

Thanks! It worked!

**Comment by yangyagami** [comment]
I test it on the linux. I had set my code file as UTF-8. It doesn't work.



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/05/2022 19:59 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [raysan5/raylib] How to display chinese character? (Issue #2609) |

@yangyagami Just tested it and it works as expected on my device:

I think it can be related to the code file, it should be saved as UTF-8. Probably Visual Studio saves it with another text encoding.
