### ISSUE TITLE
[rmodel] DrawSphere  -  ERROR: RLGL: Batch elements overflow

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#2633]
I note the checkRenderBatchLimit has been commented out ?

render much more than 20-40 spheres and I'm seeing a batch overflow

**Comment by raysan5** [comment]
@chriscamacho are you using latest raylib from github master branch? that change shouldn't be in the release...

**Comment by raysan5** [comment]
fixed

**Comment by chriscamacho** [comment]
😁 👍 cheers!

On Saturday, 13 August 2022, Ray ***@***.***> wrote:
> fixed
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/proxy/jnlaknRlgi8Tr2BAUYwLV3jUDn3UPoxlRbrSzn85TenMYys-FdYSGJ2z9gT3aK27qTgooI29V4WaIT8O_gVHOX9P_8usL1EOMbtwGtbEJJhfTaWd-5lOGraKOx0KyrBQbZIgM_oM1Sc7X8wHurYz3H-pbLG3YbXaKn5pJ2Q8K36PtChSpeu8VXREcan5MLjda6fSJjYQLG3zI9ZJyi1-EX2QIaCa7_Tl6X1SFCnp5Q=s0-d-e1-ft#https://github.com/notifications/beacon/AAFO4SNGQZ7WRTJKKXIKSSTVZAFT7A5CNFSM56LP2DJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOJBPZGWY.gif>Message
ID: ***@***.***>

-- 

blog bedroomcoders.co.uk <http://bedroomcoders.co.uk>
Free source code and tutorials!


Disclaimer:
By sending an email to ANY of my addresses you are agreeing that:

   1. I am by definition, "the intended recipient"

   2. All information in the email is mine to do with as I see fit and make
such financial profit, political mileage, or good joke as it lends itself
to. In particular, I may quote it where I please.

   3. I may take the contents as representing the views of your company.

   4. This overrides any disclaimer or statement of confidentiality that
may be included on your message.
