### ISSUE TITLE
[build] VSCode instead of Npp?

### ISSUE THREAD

**Issue by Triangle345** [raysan5/raylib#265]
For a few years now I've been using Visual Studio Code (NOT VISUAL STUDIO - they are different). VSCode is an open source, cross platform, general purpose editor built on Electron framework. 

For c++ i found  VSCode to be great because it has code completion, jump to definition, build/test tasks, debugger, code minimap (like sublime).

Not only can VSCode do what Npp does, but it is also cross platform. So you can essentially distribute the same editor for every system.  

I'm not a MS fan, but I have come to love using this tool. The fact that it is open source makes it safe choice without having to worry about MS gimmicks.

Take a look, let me know what you guys think.

https://github.com/Microsoft/vscode

**Comment by raysan5** [comment]
Yes, I know VSCode, it's amazing, it would be great to configure raylib for VSCode, or at least provide required configuration tasks to integrate with raylib and MinGW, actually, it's on the roadmap...

The point is that it requires some work and Notepad++ is already preconfigured for raylib (compiling scripts, intellisense help, program configuration...).

Undoubtely is an editor to consider for the future. Any help on that task is welcome! :)

**Comment by raysan5** [comment]
Just a reference in case someone wants to compile C from VSCode: http://stackoverflow.com/questions/39998471/how-to-build-and-run-c-code-in-visual-studio-code

**Comment by Gamerfiend** [comment]
Hey there! Not to sound like a total noob, but I use VScode for c and compile using the built in terminal. Couldn't I just place the files of raylib in my folder and compile my code just fine?

**Comment by raysan5** [comment]
Hi @Gamerfiend, which C compiler are you using with VSCode?

raylib provides several Makefiles to compile sources and also examples, I think they could be just called from terminal but it would be great to provide pre-configured VSCode tasks.

It shouldn't be difficult to implement it, actually, one user [is already working on that](https://github.com/JanduSoft/raylib/commit/d0426cfe53491dd7babea9413b70725e9c3cd7fa)..

**Comment by Gamerfiend** [comment]
@raysan5  How is that coming along? I currently have mingw installed, which from command line I just type "gcc test1.c" to compile something, then "a.exe" to run it :)

**Comment by raysan5** [comment]
with raylib is a bit more complicate, it requires linking with several libraries and it could also require compiling raylib library itself. Current required line for code compilation using MinGW:
```
gcc -o $(NAME_PART).exe $(FILE_NAME) -s $(RAYLIB_DIR)\raylib\raylib_icon -Iexternal -lraylib -lopengl32 -lgdi32 -std=c99
```
But paths to raylib dir and MinGW tools must be defined.

**Comment by Gamerfiend** [comment]
Currently I have the PATH variable in my environment variables defined to mingw bin folder, which works perfectly. For raylib, should i create a environment variable defined as RAYLIB_DIR pointing to the raylib directory? or in your code should I replace $(VARIABLE) with my own words, such as gcc -o mygame.exe /gameout -s C:\raylib\raylib\raylib_icon, like that?

**Comment by raysan5** [comment]
@Gamerfiend those `$(VARIABLE)` come from Notepad++, you should replace them by your own and make sure that paths for libraries are set in the Environment Variables (by default raylib installation is prepared to work as standalone, it doesn't touch the Environment Variables, so paths are required in Notepad++ script).
Example:
```
gcc -o mygame.exe mygame.c -s C:\raylib\raylib_icon -IC:\raylib\raylib\src\external -lraylib -lopengl32 -lgdi32 -std=c99
```
