### ISSUE TITLE
[rtext] Add support for multi-page BMFont

### ISSUE THREAD

**Issue by BohongHuang** [raysan5/raylib#2655]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I'm working on the Unicode font display in my pixel-style game. However, aware that texture size limitation exists on some platforms, I generate a large BMFont with multiple pages (each page has the size of 512x512) included, but it seems like raylib cannot handle this kind of font correctly. The font is uploaded as an attachment. Any plan for supporting multi-page BMFont?

[simsunbb.zip](https://github.com/raysan5/raylib/files/9392567/simsunbb.zip)

**Comment by raysan5** [comment]
@BohongHuang I'm afraid supporting `BMFont` multipages is out of scope, it's a specific file-format provided by an external tool and despite raylib supports its basic form, it's not something I consider should belong to raylib.

In those cases, unicode font should be loaded directly from .ttf file and managed by user in case of requiring multiple atlas.

**Comment by BohongHuang** [comment]
> @BohongHuang I'm afraid supporting `BMFont` multipages is out of scope, it's a specific file-format provided by an external tool and despite raylib supports its basic form, it's not something I consider should belong to raylib.
> 
> In those cases, unicode font should be loaded directly from .ttf file and managed by user in case of requiring multiple atlas.

All right. Thanks for the reply.
