### ISSUE TITLE
[audio] Audio doesn't play on `PLATFORM_DRM` or `PLATFORM_RPI`

### ISSUE THREAD

**Issue by Trithilon** [raysan5/raylib#2656]
Please, before submitting a new issue verify and check:

 - [ Y ] I tested it on latest raylib version from master branch
 - [ Y ] I checked there is no similar issue already reported
 - [ Y ] My code has no errors or misuse of raylib

### Issue description
Audio examples do not play sound of a Raspberry Pi Zero 2 W.

### Environment

Replicated on RPI02W piCore CLI - with and without DRM.

### Code Example

Just run "make PLATFORM=PLATFORM_RPI" or "make PLATFORM=PLATFORM_DRM" against Raylib 4.2.0 and its examples on piCore (It works on Debian Buster Lite). Audio won't playback via HDMI. (Playback happens when using Desktop mode)

**Comment by TSnake41** [comment]
Probably related to pulseaudio/whatever not being active.

**Comment by polarvoid** [comment]
Hey, I could try and take a look into this. Could you provide some more context? I see a lot of issues particularly regarding RPis and Audio/Middle Mouse Button here.

**Comment by raysan5** [comment]
@polarvoid Actually Raspberry Pi requires some more testing, afaik audio/gamepad worked ok in previous version.

**Comment by polarvoid** [comment]
If y'all need any help with that, I can take a look. I have a few Pis that I can test on.

**Comment by Trithilon** [comment]
I just received my new RPi 4 and 3B+ - so happy to test stuff out as well.

**Comment by polarvoid** [comment]
One can never have too many of em XD.

**Comment by JupiterRider** [comment]
I had **no issues** on Raspberry Pi OS Lite (64-bit, Debian 11 bullseye).

I used raylib 4.2 PLATFORM_DRM and played a .wav file using the audio jack.

Its a Raspberry Pi 3B+

**Comment by Trithilon** [comment]
@JupiterRider : I was using RPI Zero 2 W, so there was no headphone jack. There was no HDMI sound.
I'll check this at my end as well tomorrow now that I just got my RPI 4 and 3B+

**Comment by raysan5** [comment]
I think this issue is related to OS configuration, raylib is proven to work in similar platforms.
