### ISSUE TITLE
[audio] Audio playback stops randomly for audio examples on Raspberry Pi `PLATFORM_DESKTOP`

### ISSUE THREAD

**Issue by Trithilon** [raysan5/raylib#2657]
Please, before submitting a new issue verify and check:

 - [ Y ] I tested it on latest raylib version from master branch
 - [ Y ] I checked there is no similar issue already reported
 - [ Y ] My code has no errors or misuse of raylib

### Issue description

audio_module_playing example stops playing audio after 30 seconds and keeps seeking through the whole track.

### Environment

Have a computer monitor with built-in speakers connected via HDMI. Music playback through browser or other apps happens normally. RPi0 2W on Bullseye Desktop (32 Bit) with KMS Drivers.

### Issue video

https://user-images.githubusercontent.com/7444189/185926596-4a69b4bb-ffe6-4246-a7b2-1b7b1e7016d8.mov

### Code Example

Just run "make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_21" against Raylib 4.2.0 and its examples on Debian Buster Desktop (32 bit). Audio will start playing with a bit of delay (0.5-1 sec) and may stop playing anywhere between 5-30 seconds of playback. No unusual errors or logs are observed in the terminal output.

**Comment by raysan5** [comment]
It's difficult to track this kind of issue, it could be related to the audio driver used or miniaudio (the underlying audio library used by raylib) or the raudio module (that actually would require some review).

**Comment by raysan5** [comment]
`miniaudio` was updated to latest version for `raylib 4.5` release, hopefully it will address this issue... I'm closing it because there is not much else I can do. Feel free to comment if issue persists.
