### ISSUE TITLE
[core] Mouse orientation not working on FPS camera examples in `PLATFORM_RPI` or `PLATFORM_DRM`

### ISSUE THREAD

**Issue by Trithilon** [raysan5/raylib#2661]
-+Please, before submitting a new issue verify and check:

 - [Y] I tested it on latest raylib version from master branch
 - [Y] I checked there is no similar issue already reported
 - [Y] My code has no errors or misuse of raylib

### Issue description

Any example with mouse look (for instance, core_3d_camera_first_person ) will instantly start spinning on RPI or DRM environments. This does not happen in X11/Desktop mode. I am not sure if its just the example that is broken OR if the way raylib is handling input is not correct.

### Environment

Raspbian Buster Lite running on RPI02W with OR without KMS drivers and DRM.

### Issue Video

https://user-images.githubusercontent.com/7444189/186026675-cabceddb-4a6b-4ac5-88e8-00a5d1146bf5.mov

### Code Example

Just run the example core_3d_camera_first_person in a non X11 environment to reproduce this.

**Comment by raysan5** [comment]
This issue is probably related to the missing `DisableCursor()` implementation for `PLATFORM_RPI`/`PLATFORM_DRM`. That function locks cursor inside the window returning only relative movements.
