### ISSUE TITLE
[core] Mouse panning and rotation not working in `PLATFORM_RPI` and `PLATFORM_DRM`

### ISSUE THREAD

**Issue by Trithilon** [raysan5/raylib#2662]
Please, before submitting a new issue verify and check:

 - [Y] I tested it on latest raylib version from master branch
 - [Y] I checked there is no similar issue already reported
 - [Y] My code has no errors or misuse of raylib

### Issue description
This issue only happens in examples (eg. models_mesh_picking) which have mouse middle button based pan and orbit.
It has two problems-
1. Clicking the middle button to pan the camera is sending camera in the left direction at very high speeds.
2. Clicking ALT and then middle button to allow orbit camera around an object will spin your camera at Y axis infinitely.

### Environment

Raspbian buster (32bit) running on RPI02W.

### Issue videos

1. Camera pan away problem:
(No video, couldn't click the buttons and take the video) But it reproduces 100%

2. Spinning problem:
https://user-images.githubusercontent.com/7444189/186029419-1775fd6a-3422-4d93-ada5-cabd4885df81.mov

### Code Example

Just run make with PLATFORM_RPI or PLATFORM_DRM and pick any example which allows you to use the middle mouse button to pan around and rotate/orbit the camera around that object. I tried with different mice - bluetooth and wired - same result.

**Comment by raysan5** [comment]
Probably related to not reading `MOUSE_MIDDLE_BUTTON` on `PLATFORM_RPI`/`PLATFORM_DRM`.

**Comment by raysan5** [comment]
Camera system has been reimplemented from scratch.
