### ISSUE TITLE
[core] Building for Wayland instead of X11 on Ubuntu 22.04 produces compile error in GLFW lib

### ISSUE THREAD

**Issue by defce74** [raysan5/raylib#2666]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Building for Wayland instead of X11 on Ubuntu 22.04 produces compile error in GLFW lib

`external/glfw/src/wl_platform.h:57:10: fatal error: wayland-xdg-shell-client-protocol.h: No such file or directory`

in `raylib/src/Makefile`: `USE_WAYLAND_DISPLAY ?= TRUE`

This #include was removed in this glfw commit: <https://github.com/glfw/glfw/commit/dffe203c178ecea44a0c3d52a7b62c45a6615944#diff-a236f7eff7f0908ab273256af30863eb4023c4d5b28feb5e5fe1b20eee43fdc1>

Using an external install of GLFW (latest master branch build <https://github.com/glfw/glfw> as of 28/8/2022) is working, therefore suggested that the Raylib GLFW version gets an update

in `raylib/src/Makefile`: `USE_EXTERNAL_GLFW ?= TRUE`

#### Environment

* raylib 4.2 (latest master branch build as of 27/8/2022)
* OS: Ubuntu 22.04 Wayland, Linux 5.18.15-051815-generic 
* OpenGL version: 4.6 (Core Profile) Mesa 22.0.5
* GPU: AMD Radeon Vega 10 Graphics - raven, LLVM 13.0.1, DRM 3.46

**Comment by raysan5** [comment]
GLFW has been updated to latest version lately but it seems Wayland compilation requires some previous step to generate some wayland specific code files. 

I don't know how those files should be generated, help is welcome.

In the meantime, you can use CMake to build GLFW and generate the files automatically.

**Comment by gen2brain** [comment]
There is a script in raylib-go that I am using occasionally, on the update, to generate needed Wayland files https://github.com/gen2brain/raylib-go/blob/master/raylib/external/scripts/glfw-generate-wayland.sh.

From the next major GLFW release both X and Wayland should be compiled together and detected and used on runtime.

**Comment by raysan5** [comment]
@gen2brain Thanks for the info! I didn't know Wayland compilation required those shenanigans...

 > From the next major GLFW release both X and Wayland should be compiled together and detected and used on runtime.

Does it mean this wayland-specific-files generation process won't be needed after GLFW 3.4 official release?

**Comment by gen2brain** [comment]
Not sure if it will be needed, in that GLFW commit that is referenced above it seems it will not be needed.

**Comment by defce74** [comment]
@raysan5 Why not just state in the wiki, that if you wish to build for Wayland, that at this stage cmake is the preferred (or only) option? It works and the glfw website itself certainly encourages using cmake <https://www.glfw.org/docs/latest/compile.html> .. it also states in the manual compilation section that use of the Wayland API is "experimental and incomplete".. might be worth waiting for the next glfw major release as @gen2brain has mentioned ?

also Wayland is still a bit of an edge case, most window managers/desktops in Linux still use X11.. I just saw that the option was there and as I'm running gnome 42 (which uses wayland) thought I would use it but theres nothing stopping me or anyone from using x11 which was working perfectly :)

**Comment by defce74** [comment]
@raysan5 update: this may be a separate issue but testing both make and cmake builds, I'm getting ~60fps using a make build but only ~45fps with a cmake build.. this is reproducible as I tried different raylib commits with the same result.. definite slowdown with cmake builds. not sure if this is just linux or relevant to windows also ?

**Comment by raysan5** [comment]
Information has been added to the Wiki: https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux#wayland

@defce74 The framerate issue you mention is a separate one and I have no idea why that happens but it seems it is more related to OS or compilation than raylib, the raylib code is the same in both cases.

**Comment by defce74** [comment]
@raysan5 ok would you like me to open a separate issue for this?

**Comment by raysan5** [comment]
@defce74 Feel free to open a separate issue if you think it is related to raylib sources but it's needed more info to investigate it and, personally, I'm not investigating it. Let's see if someone is up for that task.

**Comment by defce74** [comment]
@raysan5 ok, so before opening this as an issue, when I get some time, I'll look into it a bit myself as (correct me if I'm wrong) its probably some build settings in the Cmake config? I'll go back and look at some previous commits and see if I can find a build where cmake and make were comparable in terms of performance. 

fyi as a test I am making 320,000 calls to DrawPixel per frame plus a few other bits like text and update logic..  I am getting up to 70fps using a make build or the official release build.. Cmake is only ~45fps
