### ISSUE TITLE
[rmodels] Animation not smooth

### ISSUE THREAD

**Issue by TokyoSU** [raysan5/raylib#2668]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

When using UpdateModelAnimation(), the frame argument is int but it cause some animation which is using 1 or 2 frame to play super fast, using a float cast instead and parsing a value like 0.5f fix that but it's not linear and the animation look like image per image.

### Environment

Windows 8.1 X64 using Raylib 4.2 from master

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example

Using float everywhere for animation would be great and more useful than using int which is not really recommanded for playing animation

**Comment by raysan5** [comment]
@TokyoSU I'm afraid that raylib does not implement any interpolation mechanism. So frames can only be int.
