### ISSUE TITLE
[audio] SIGSEGV Segmentation fault with pipewire / pulseaudio / wireplumber

### ISSUE THREAD

**Issue by tejohnso** [raysan5/raylib#2669]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

After initial boot, a raylib process calling *InitAudioDevice* results in a segmentation fault.

This is similar to https://github.com/raysan5/raylib/issues/2315 in that it only occurs if the audio device has not been used yet. After the crash, if I run the same raylib process again, the crash does not reoccur.

### Environment

Arch Linux (5.19.4)

### Details

I've reproduced this with a debug build and found the issue seems to be a null pointer dereference at miniaudio.h:28175

>  *pInfoOut = *pInfo;

The backtrace shows:

> 0x00005555555e2f43 in ma_device_sink_info_callback (pPulseContext=0x5555562ab840, pInfo=0x0, endOfList=-1, pUserData=0x7fffffffd7b0) at ...miniaudio.h:28175

And the prior frame has no source as it is in `libpulse.so`.

**Comment by tejohnso** [comment]
My systemd journal shows a *lot* of activity at `10:39:24` when I started the raylib process. The segfault is on line 46.

Perhaps the initialization takes a circuitous route that miniaudio doesn't expect. 

[journalctl.txt](https://github.com/raysan5/raylib/files/9439889/journalctl.txt)

**Comment by tejohnso** [comment]
> Perhaps the initialization takes a circuitous route that miniaudio doesn't expect.

If I step through the process up to raudio.c:421 calling `ma_context_init`, and then step over that, I get all the same wireplumber messages as before (eg: failed to activate item: Object activation aborted: proxy destroyed) but there is no segfault. Then if I allow execution to continue, the program runs without error. 

So without an artificial pause, `ma_context_init` is returning MA_SUCCESS even though it doesn't seem to be in quite the right state.

**Comment by tejohnso** [comment]
Closing here as I believe this is more of a miniaudio issue than a raylib issue.

**Comment by raysan5** [comment]
@tejohnso thanks, still I will let @mackron know about it.
