### ISSUE TITLE
[build] raylib 4.2.0 release, some zip files do not contain the expected libraries

### ISSUE THREAD

**Issue by hiddenfrog** [raysan5/raylib#2670]
raylib-4.2.0_win32_mingw-w64.zip
empty lib directory, there are no libs and dll files

raylib-4.2.0_win64_mingw-w64.zip
missing dll in lib

**Comment by raysan5** [comment]
@hiddenfrog `raylib-4.2.0_win32_mingw-w64` has been removed from the build sytem, the compiler provided is 64bit and no 32bit libs are available to generate the 32bit raylib versions.

`raylib-4.2.0_win64_mingw-w64` has been reviewed. It's working again.

Changes will be reflected in next release.
