### ISSUE TITLE
[build] raylib 4.2.0 release, windows msvc16 dll and lib, `raylibVersion` symbol is not exposed

### ISSUE THREAD

**Issue by hiddenfrog** [raysan5/raylib#2671]
there is no export of "raylibVersion" in raylibdll.lib, only in the static lib raylib.lib

(in the linux dynamic lib "raylibVersion" is exported)

so "raylibVersion" can not be found ie. with the d lang binding "raylib-d" (https://github.com/schveiguy/raylib-d) when you dynamic link to raylib in windows

(tested with the libs in raylib-4.2.0_win64_msvc16.zip and also with self compiled versions in vs2022)

**Comment by raysan5** [comment]
@hiddenfrog No idea why this happens, `raylibVersion` symbol is defined as a global, non-static variable in `rcore.c` as:
```c
const char *raylibVersion = RAYLIB_VERSION; // raylib version symbol, it could be required for some bindings
```
Help is welcome.

**Comment by raysan5** [comment]
Fixed. Next release will include the symbol in the DLL.
