### ISSUE TITLE
[rtextures] Support for GL_TEXTURE_LOD_BIAS

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [raysan5/raylib#2674]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

GL_TEXTURE_LOD_BIAS is a parameter of a texture that changes which level of mipmap would be used for rendering, changing this value would control how sharp a texture looks when rendered at a small size. Currently the only way to change this parameter is to build raylib against an OpenGL version that supports this, and then call `glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_LOD_BIAS, bias);`. Would be convenient if there's a function like `SetTextureLODBias(Texture2D texture, float bias)`. Don't know how feasible that would be since LOD bias is only supported on OpenGL 3.0 and up.

### Environment

GL_TEXTURE_LOD_BIAS does not seem to be a thing on GL ES 2.0, 3.0 and GL 2.0 according to docs.gl.

### Code Example
```
glBindTexture(GL_TEXTURE_2D, texture_id);
glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_LOD_BIAS, -0.5f);
glBindTexture(GL_TEXTURE_2D, 0);
```

**Comment by raysan5** [comment]
@Ataraxia-Mechanica Just added `RL_TEXTURE_MIPMAP_BIAS_RATIO` support to `rlTextureParameters()` for OpenGL 3.3 only, it's expects as parameter a integer percentage value.

`rlgl` is intended for adavance users, so the function is not directly exposed in raylib.
