### ISSUE TITLE
[rmodels] Memory leak when loading iqm

### ISSUE THREAD

**Issue by TokyoSU** [raysan5/raylib#2676]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Found that color array is not free at the end of LoadIQM() unlike the other array being free.

- Where it is defined:
https://github.com/raysan5/raylib/blob/4b76aa09dd342b32979df6a0926cf309c406532e/src/rmodels.c#L4229
- Where RL_FREE(color) should be called:
https://github.com/raysan5/raylib/blob/4b76aa09dd342b32979df6a0926cf309c406532e/src/rmodels.c#L4295

### Environment

Windows 8.1 X64 Raylib 4.2 (Master)

### Issue Screenshot

None

### Code Example

RL_FREE(color) at the end of the LoadIQM() function.

**Comment by raysan5** [comment]
@TokyoSU Thanks for reporting, implemented proposed fix.
