### ISSUE TITLE
[build] webassembly build doesn't use USE_GLFW=3

### ISSUE THREAD

**Issue by disketteman** [raysan5/raylib#2679]
Recently I downloaded the [raylib build](https://github.com/raysan5/raylib/releases/download/4.2.0/raylib-4.2.0_webassembly.zip) from the GitHub Releases but I got some GLFW related linker errors (sorry, I don't have the project on this computer so I can't provide the errors at the moment). I noticed that the build doesn't have `USE_GLFW=3` mentioned in the [docs here](https://github.com/raysan5/raylib/tree/master/projects/CMake#web).

Specifically this one:
```
-DCMAKE_EXE_LINKER_FLAGS="-s USE_GLFW=3"
```

Is that alright? Shouldn't it be part of the [definition](https://github.com/raysan5/raylib/blob/master/.github/workflows/webassembly.yml) as well? Or better implicitly set if `PLATFORM_WEB` is set?

Sorry for not providing the logs, I don't have the project on this computer.

**Comment by disketteman** [comment]
Looks like [it's done](https://github.com/raysan5/raylib/blob/64cca24526d8d2f82e87039a1d492dcbe07b994d/examples/CMakeLists.txt#L99) already for cmake, but in the build definition cmake is not used if I understand correctly.

**Comment by Peter0x44** [comment]
yeah, adding it to CMAKE_C_FLAGS does nothing but create warnings.
I did try editing this to put it in CMAKE_EXE_LINKER_FLAGS but I remember it also didn't work for reasons I don't remember.

**Comment by raysan5** [comment]
@disketteman afaik `-s USE_GLFW=3` is only required at wasm program linkage, not when raylib library is generated. Actually, if that flag is added at sources compilation it shows a warning with that info.
