### ISSUE TITLE
[core] Improve Drag&Drop support

### ISSUE THREAD

**Issue by JoaoSilveira** [raysan5/raylib#2680]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I'm having a great time with raylib, but I wish I could do these two things:

1. Know if the user is currently dragging something over the window
2. Know what the user is currently dragging

These 2 things could provide a better user experience by letting them know if they can drop the current item where they're currently hovering.

### Environment

Windows 10 21h1 (19043.18889)
Raylib version 4.2

### Things I've tried

I tried to use `IsWindowFocused` to know if the user dragged something over, if the window gains focus and the left mouse button is pressed, they're probably dragging right?. But the window does not gain focus.

Then I tried to use `IsCursorOnScreen` to do the same, if the pointer enters the window with the left button pressed they're very likely to be dragging something. But windows captures the mouse when dragging, so `IsCursorOnScreen` will only return true when the user drops.

Tracking the mouse position also does not help much, because the position doesn't change when the pointer is outside the window.

### The solution I imagine

I imagine it working almost identically to the drop, a function `IsFileDragging` to tell if the user is dragging something, and a `LoadDraggingFiles` and its `Unload` counterpart to know what the user is dragging.

**Comment by raysan5** [comment]
@JoaoSilveira raylib uses GLFW to process the drag & drop events and I'm not sure if that functionality is exposed, I think it is not. In any case, the dropped files can be just ignored if not required by the program.
