### ISSUE TITLE
[core] `GetTouchPosition()` never indicates no touch

### ISSUE THREAD

**Issue by tejohnso** [raysan5/raylib#2683]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

GetTouchPosition seems to retain the previous position that was touched. It does not return to {0,0}

### Environment

Android  7

### Code Example

Set up a simple loop similar to

    loop {
      BeginDrawing()
      ClearBackground(WHITE)
      DrawText(GetTouchPosition(0).x)
      EndDrawing()
    }

Notice the touch position shown never zeroes out after the first touch, suggesting there is *always* a touch present even if the screen is not touched.

**Comment by tejohnso** [comment]
I guess it is meant to be used with GetTouchPointCount but that also fails to indicate no touch since after the first touch it also does not go back to 0.

**Comment by Shpendicus** [comment]
> I guess it is meant to be used with GetTouchPointCount but that also fails to indicate no touch since after the first touch it also does not go back to _0_. It'll even show _2_ when two fingers are touching, but then when they are removed it goes back to _1_.

Is this in the newest release 4.2 ?

**Comment by tejohnso** [comment]
Yes. I ended up using gestures, not realizing "tap" was considered a gesture. Enabling both tab and double-tap and then checking with `GetGestureDetected`.

**Comment by Shpendicus** [comment]
> Yes. I ended up using gestures, not realizing "tap" was considered a gesture. Enabling both tab and double-tap and then checking with `GetGestureDetected`.

So it works now that way?

**Comment by tejohnso** [comment]
Yes. 
So depending on how GetTouchPosition is *supposed* to be used, this issue can possibly be closed. If it's supposed to be usable outside of the gestures paradigm, then I'm not so sure.

**Comment by Shpendicus** [comment]
> Yes. So depending on how GetTouchPosition is _supposed_ to be used, this issue can possibly be closed. If it's supposed to be usable outside of the gestures paradigm, then I'm not so sure.

But isnt a TAP _(2x clicks in short period behind each other)_ also a Gesture? just by logic I mean. Or am I wrong

**Comment by tejohnso** [comment]
Tap is a gesture.
And if GetTouchPosition is meant only to be used along with gestures, then no problem. 

Personally, I didn't think a tap or double tap would be considered gestures. I thought they'd be things like swiping, double finger expand, shrink motions, four finger dragging, that kind of thing. And I wasn't interested in that level of interaction so I wasn't looking at gestures.
