### ISSUE TITLE
Raylib android makefile "compile_project_class_dex" Error 1

### ISSUE THREAD

**Issue by MrRedux** [raysan5/raylib#2686]
![image](https://user-images.githubusercontent.com/112194829/188274848-38da6551-542b-4e57-885a-de1792d5111b.png)

First of all i do not know if this is a bug. Maybe its something caused by my computer. If that's the case, i'm truly sorry for wasting your time.
----

https://github.com/raysan5/raylib/wiki/Working-for-Android

I installed everything according to this page.

I'm currently at this page:
![image](https://user-images.githubusercontent.com/112194829/188274939-f1c67b1c-49d7-4092-a15f-52496d4b4e0b.png)

Everything in Makefile and "makefile. Android" is correct. However, I am getting this error:
![image](https://user-images.githubusercontent.com/112194829/188274980-94bc488f-a2cb-4180-a4ea-e09f2f1a9fd7.png)
(The parts i covered with red is my name)

Again i don't know if this is a bug or a error caused by me or my pc.
If it is and i waste your time, i'm very sorry.

**Comment by raysan5** [comment]
@MrRedux Did you solve the issue?

**Comment by MrRedux** [comment]
Yes. Sorry for taking your time. I changed from build tool 33.0.0 to 30.0.3
