### ISSUE TITLE
SIGSEGV, Segmentation fault on Raspberry PI 3B+

### ISSUE THREAD

**Issue by saarbastler** [raysan5/raylib#2689]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Segmentation fault with all examples on a Raspberry PI 3B+ with a 5inch DSI LCD. 

I tried raylib release 4.2 and the master branch, I tested with 16/32/64 GByte GPU Ram.

### Environment

Raspberry PI 3B+,  Raspberry PI OS Lite Bullseye (Console),

raylib and examples compiled with make PLATFORM=PLATFORM_DRM

### Issue Screenshot

This happens to each example:
```
INFO: Initializing raylib 4.2 +
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
INFO: DISPLAY: Selected DRM connector mode 800x480 (800x480p@60)
Segmentation fault
```

If I add ` SetTraceLogLevel(LOG_TRACE);` to basic_window.c:
```
INFO: Initializing raylib 4.2
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
TRACE: DISPLAY: Connectors found: 2
TRACE: DISPLAY: Connector index 0
TRACE: DISPLAY: Connector modes detected: 0
TRACE: DISPLAY: DRM mode NOT connected (deleting)
TRACE: DISPLAY: Connector index 1
TRACE: DISPLAY: Connector modes detected: 1
TRACE: DISPLAY: DRM mode connected
TRACE: DISPLAY: Searching exact connector mode for 800x450@60, selecting an interlaced mode is allowed: no
TRACE: DISPLAY: DRM Mode 0 800x480@60 progressive
TRACE: DISPLAY: No DRM exact matching mode found
TRACE: DISPLAY: Searching nearest connector mode for 800x450@60, selecting an interlaced mode is allowed: no
TRACE: DISPLAY: DRM mode: 0 800x480@60 progressive
INFO: DISPLAY: Selected DRM connector mode 800x480 (800x480p@60)
Segmentation fault
```

If I use GDB:

```
Program received signal SIGSEGV, Segmentation fault.
0x76fdb34c in _dl_map_object_deps (map=map@entry=0xb1c50, preloads=preloads@entry=0x0, npreloads=npreloads@entry=0, trace_mode=trace_mode@entry=0,
    open_mode=<optimized out>, open_mode@entry=-2147483648) at dl-deps.c:226
226     dl-deps.c: No such file or directory.
```

**Comment by raysan5** [comment]
@saarbastler what driver did you enable with `raspi-config`? It's probably an issue with the display configuration...

**Comment by saarbastler** [comment]
![grafik](https://user-images.githubusercontent.com/10219421/188327165-92f88092-cddf-4e8b-bd7f-f3232b6facb3.png)

see screenshot

**Comment by raysan5** [comment]
@saarbastler I see. No idea about the issue, it works fine with HDMI output. Feel free tosend a PR if you investigate it and find some fix.

**Comment by saarbastler** [comment]
It doesn't work with HDMI with my setup. I just unplugged the display and connected to an HDMI monitor.

It lists a lot of screen resolutions, but at the end there is still a Segmentation Fault at the and (cannot take a screenshot)

Do you have any idea, how to investigate this ?

**Comment by raysan5** [comment]
@saarbastler Sorry, not much idea... I think it can be related to some driver or system configuration, not raylib itself...

**Comment by bztsrc** [comment]
> I think it can be related to some driver or system configuration, not raylib itself...

Yeah, I agree. But if possible I think raylib should return gracefully in this case too, returning an error code if possible (depends if the error happens in the driver itself, or if it returns an invalid value and therefore in raylib trying to use that invalid value).

> Do you have any idea, how to investigate this ?

First, remove all existing object files and recompile with debug information. To do that, go to the `src` directory, and run
```
RAYLIB_BUILD_MODE=DEBUG make clean all
```
and then in the `examples` directory run
```
BUILD_MODE=DEBUG make clean all
```
After that install [valgrind](https://packages.debian.org/stable/valgrind), and run the basic window example through it.
```
sudo apt-get install valgrind
valgrind ./examples/core/core_basic_window
```
This won't solve your issue, but at least it will tell you in which source file and at which line the segfault happens with a backtrace.

For example (here I've deliberately put a NULL dereference in the code to demonstrate):
```
$ valgrind ./examples/core/core_basic_window
==24534== Memcheck, a memory error detector
==24534== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==24534== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==24534== Command: ./examples/core/core_basic_window
==24534== 
INFO: Initializing raylib 4.2
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
    (...lot of more output, removed for simplicity...)
==24534== 
==24534== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==24534==  Access not within mapped region at address 0x0
==24534==    at 0x185A0C: TextLength (rtext.c:1280)
==24534==    by 0x184B05: DrawTextEx (rtext.c:1035)
==24534==    by 0x184A9A: DrawText (rtext.c:1025)
==24534==    by 0x10E97A: main (core_basic_window.c:55)
==24534==  If you believe this happened as a result of a stack
==24534==  overflow in your program's main thread (unlikely but
    (...lot of more output, removed for simplicity...)
```
This also saves a memory dump file (called `vgcore.(pid)` in this case `vgcore.24534`) which you can load with `gdb` for further examination, but I usually just delete that file, as I've found that compiling with debug info and seeing the source backtrace is more useful.

Now if you see that the segfault happens at an address without source filename and line, then it is as raysan5 suspected, the error happens in a driver, out of the scope of raylib. If it has a source file, then maybe raylib could return with an error code instead of crashing.

Hope this helps,
bzt

**Comment by bztsrc** [comment]
Ah, why I've mentioned the memory dump file: if you're not going to use it with gdb, then delete it immediately, because it can be *HUGE*. Hundreds of megabytes or even gigabytes, so get rid of it as soon as possible, otherwise those files will fill up your SDCard within a blink of an eye.

**Comment by saarbastler** [comment]
Thanky you all four your help !

First I build in Debug and started whith valgrind, the output is (last few lines)

```
==1642== Use of uninitialised value of size 4
==1642==    at 0x4A05480: index (in /usr/lib/arm-linux-gnueabihf/libc-2.31.so)
==1642== 
==1642== Use of uninitialised value of size 4
==1642==    at 0x4B60DFC: dlopen@@GLIBC_2.4 (in /usr/lib/arm-linux-gnueabihf/libdl-2.31.so)
==1642== 
--1642-- WARNING: Serious error when reading debug info
--1642-- When reading debug info from /usr/lib/arm-linux-gnueabihf/librt-2.31.so:
--1642-- Ignoring non-Dwarf2/3/4 block in .debug_info
--1642-- WARNING: Serious error when reading debug info
--1642-- When reading debug info from /usr/lib/arm-linux-gnueabihf/librt-2.31.so:
--1642-- Last block truncated in .debug_info; ignoring
--1642-- WARNING: Serious error when reading debug info
--1642-- When reading debug info from /usr/lib/arm-linux-gnueabihf/libz3.so.4:
--1642-- Invalid ELF Section Header String Table
==1642== Invalid read of size 4
==1642==    at 0x400F34C: _dl_map_object_deps (in /usr/lib/arm-linux-gnueabihf/ld-2.31.so)
==1642==  Address 0x4 is not stack'd, malloc'd or (recently) free'd
==1642== 
==1642== 
==1642== Process terminating with default action of signal 11 (SIGSEGV)
==1642==  Access not within mapped region at address 0x4
==1642==    at 0x400F34C: _dl_map_object_deps (in /usr/lib/arm-linux-gnueabihf/ld-2.31.so)
==1642==  If you believe this happened as a result of a stack
==1642==  overflow in your program's main thread (unlikely but
==1642==  possible), you can try to increase the size of the
==1642==  main thread stack using the --main-stacksize= flag.
==1642==  The main thread stack size used in this run was 8388608.
==1642== Use of uninitialised value of size 4
==1642==    at 0x4AA9DB0: free_mem (in /usr/lib/arm-linux-gnueabihf/libc-2.31.so)
==1642== 
==1642== Use of uninitialised value of size 4
==1642==    at 0x4AA9CD4: free_slotinfo (in /usr/lib/arm-linux-gnueabihf/libc-2.31.so)
==1642== 
==1642== Use of uninitialised value of size 4
==1642==    at 0x48C2204: pthread_getspecific (pthread_getspecific.c:30)
==1642==    by 0x4B61B07: __dlerror_main_freeres (in /usr/lib/arm-linux-gnueabihf/libdl-2.31.so)
==1642== 
==1642== Use of uninitialised value of size 4
==1642==    at 0x48C228C: pthread_setspecific (pthread_setspecific.c:33)
==1642==    by 0x4AA98DF: __libc_freeres (in /usr/lib/arm-linux-gnueabihf/libc-2.31.so)
==1642== 
==1642== 
==1642== HEAP SUMMARY:
==1642==     in use at exit: 24,045 bytes in 129 blocks
==1642==   total heap usage: 312 allocs, 183 frees, 149,422 bytes allocated
==1642== 
==1642== LEAK SUMMARY:
==1642==    definitely lost: 0 bytes in 0 blocks
==1642==    indirectly lost: 0 bytes in 0 blocks
==1642==      possibly lost: 0 bytes in 0 blocks
==1642==    still reachable: 24,045 bytes in 129 blocks
==1642==         suppressed: 0 bytes in 0 blocks
==1642== Rerun with --leak-check=full to see details of leaked memory
==1642== 
==1642== For counts of detected and suppressed errors, rerun with: -v
==1642== Use --track-origins=yes to see where uninitialised values come from
==1642== ERROR SUMMARY: 54729 errors from 288 contexts (suppressed: 580 from 1)
```

**Comment by saarbastler** [comment]
I had another idea:

I setup another SD Card, connected the PI only by HDMI and compiled raylib and the examples. 

It worked as expected!

After that, I disconnected HDMI and connected the DSI LCD. And It also worked with the DSI LCD.

I don't understand the reason, but its reproducible, with the first SD card I have the Segmentation Fault.

Not sure how to continue with this issue.

**Comment by bztsrc** [comment]
> After that, I disconnected HDMI and connected the DSI LCD. And It also worked with the DSI LCD.

That's irrelevant in this case.

> I don't understand the reason, but its reproducible, with the first SD card I have the Segmentation Fault.

They key is, you have recompiled raylib on the second SDCard. According to the valgrind output, the problem was in your first SDCard's libc (and in libdl), so this has nothing to do with raylib, just as raysan5 suspected. Either you had a buggy installation on the first card, or you have used a libdl library which wasn't compiled for that specific version of libc. In both cases, this was a libc and libdl incompatibility issue.

> Not sure how to continue with this issue.

I think you should close it, this isn't raylib related at all.

Cheers,
bzt

**Comment by saarbastler** [comment]
Thanky a lot.

**Comment by raysan5** [comment]
@saarbastler glad you get it working! :)

@bztsrc thanks for the help with the issue!
