### ISSUE TITLE
Problem compiling raylib program in code blocks

### ISSUE THREAD

**Issue by TiagoARAlves** [raysan5/raylib#2690]
I am adding the raylib library in code blocks but I don't know what is going on, because I get this error:
`-------------- Build: Debug in testefinal (compiler: GNU GCC Compiler)---------------

g++.exe -LC:\Users\tiago\Documents\raylib\lib -o bin\Debug\testefinal.exe obj\Debug\main.o   C:\Users\tiago\Documents\raylib\lib\libraylib.a
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rcore.o):rcore.c:(.text+0x16914): undefined reference to `timeEndPeriod@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rcore.o):rcore.c:(.text+0x1c615): undefined reference to `timeBeginPeriod@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x18e3): undefined reference to `_imp__CreateRectRgn@16'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x1927): undefined reference to `_imp__DeleteObject@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x198c): undefined reference to `_imp__SwapBuffers@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x246b): undefined reference to `_imp__GetDeviceCaps@8'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x2b48): undefined reference to `_imp__CreateDCW@16'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x2b5e): undefined reference to `_imp__GetDeviceGammaRamp@8'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x2b6a): undefined reference to `_imp__DeleteDC@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x65b6): undefined reference to `_imp__CreateDCW@16'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x65ef): undefined reference to `_imp__GetDeviceCaps@8'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x661d): undefined reference to `_imp__DeleteDC@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x67bf): undefined reference to `_imp__GetDeviceCaps@8'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x6a69): undefined reference to `_imp__CreateDIBSection@24'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x6ab4): undefined reference to `_imp__CreateBitmap@20'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x6b4e): undefined reference to `_imp__DeleteObject@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x6ba1): undefined reference to `_imp__DeleteObject@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x857e): undefined reference to `_imp__CreateDCW@16'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x8590): undefined reference to `_imp__SetDeviceGammaRamp@8'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0x859c): undefined reference to `_imp__DeleteDC@4'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0xe95d): undefined reference to `_imp__ChoosePixelFormat@8'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0xe971): undefined reference to `_imp__SetPixelFormat@12'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0xee08): undefined reference to `_imp__DescribePixelFormat@16'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0xeefb): undefined reference to `_imp__DescribePixelFormat@16'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0xf315): undefined reference to `_imp__DescribePixelFormat@16'
C:\MinGW\bin/ld.exe: C:\Users\tiago\Documents\raylib\lib\libraylib.a(rglfw.o):rglfw.c:(.text+0xf340): undefined reference to `_imp__SetPixelFormat@12'
collect2.exe: error: ld returned 1 exit status
Process terminated with status 1 (0 minute(s), 0 second(s))
27 error(s), 0 warning(s) (0 minute(s), 0 second(s))
`

By coincidence, nobody adds the library to the code blocks. Raylib provides a compiler with the library installed to be used in code blocks. But I don't want to be constantly changing compilers.

**Comment by raysan5** [comment]
@TiagoARAlves It seems there is some missing libraries on linkage, probably winmm and gdi32.

In any case, this is a build configuration issue, not an issue with raylib itself.

You can join raylib Discord for build configuration issues.
