### ISSUE TITLE
[examples] Minor fix in the comment

### ISSUE THREAD

**Issue by bztsrc** [raysan5/raylib#2691]
Hi,

This is really really a very small thing, does not influence behaviour at all. In `models_loading_m3d.c` the comment says
```diff
*     - Bender M3D exported: https://gitlab.com/bztsrc/model3d/-/tree/master/blender
-*       WARNING: Make sure to add "(action)" markers to the timeline if you want multiple animations.
*   
```
This warning should be removed, because thanks to @TokyoSU and others, I've implemented `bpy.data.actions` in the Blender exporter. Using timeline markers is just a fallback option from now on, no more needed to have multiple animations in one model file. It's enough to use the standard Blender's actions, those are now handled properly.

Cheers,
bzt

**Comment by raysan5** [comment]
@bztsrc Reviewed! :)
