### ISSUE TITLE
DrawText crashes raylib

### ISSUE THREAD

**Issue by milen-prg** [raysan5/raylib#2693]
### Issue description

*If include windows.h, the DrawText crashes. Other works good, for example DrawFPS or DrawCircle*

### Environment

*Windows 10 Pro 64bit, OpenGL 3.3, msys2/mingw64 g++*

### Code Example

```
#include <windows.h>
namespace rl {
    #include "raylib.h"
}


int main(int, char**) {    
    rl::InitWindow(800, 500, "Proba");

    while (!rl::WindowShouldClose()){
        rl::BeginDrawing();

        rl::ClearBackground(rl::BLACK);

        rl::DrawText("proba", 100, 100, 20, rl::YELLOW);

        rl::EndDrawing();
    }
    rl::CloseWindow();
    return 0;
}

```

**Comment by raysan5** [comment]
@milen-prg windows.h should be moved to a separate translation unit than raylib.
