### ISSUE TITLE
[rlgl] rlLoadExtensions makes possibly wrong assumptions about existing extensions

### ISSUE THREAD

**Issue by Not-Nik** [raysan5/raylib#2695]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

`rlLoadExtensions` always marks certain extensions as supported even on systems that might not have them. If `GRAPHICS_API_OPENGL_33` is defined, it assumes all of its core features exist, but defining `GRAPHICS_API_OPENGL_21` in turn also defines `GRAPHICS_API_OPENGL_33`. Extensions like `GL_ARB_vertex_array_object`, might not be supported on OpenGL 2.1, since it only has been in core OGL since version 3.0.

The best way to handle this, would be to use the corresponding `GLAD` macros to check if the extensions are supported, but I currently don't have a dev environment that uses `GLAD`, so I can't fix it myself.

### Environment

Any environments using OpenGL 2.1 would be affected.

**Comment by raysan5** [comment]
@Not-Nik Good catch! Feel free to send a PR with the GLAD checks for the specific cases.
