### ISSUE TITLE
[build] `raylib-4.2.0_win32_mingw-w64.zip` missing libs

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib#2698]
The Raylib-4.2.0_win32_mingw-w64.zip package is missing the premade library (.a files).
![image](https://user-images.githubusercontent.com/322174/190506872-0e0c6458-cc8e-4161-b1e5-33e6f399f6ae.png)

The 64 bit package has them, and the 32 bit package should be consistent.

**Comment by raysan5** [comment]
@JeffM2501 I'm aware of this issue but it seems GitHub Actions Host system only includes MinGW-w64 64bit libraries, 32bit libraries were removed or moved at some point.

Maybe the script could be reviewed to setup a proper environment but I'm not sure if it could work (I already tried in the past)

**Comment by raysan5** [comment]
One possible solution to this issue could be downloading and using [`w64devkit`](https://github.com/skeeto/w64devkit/releases/tag/v1.16.1) 32bit package to compile the library.

Help implementing this solution is welcome.

**Comment by chriscamacho** [comment]
my far the easiest way to make a windows executable is with Linux (no really! it just works) I've also used Window Subsystem for Linux to do this... I make a tutorial for this sometime ago
https://bedroomcoders.co.uk/looking-again-at-compiling-a-windows-raylib-app/
you can easily adapt for 32bit if you're using last centuries hardware... seriously does anyone still run windows on 32bit hardware anymore ?

**Comment by raysan5** [comment]
Just half-fixed this issue, now raylib 32bit library is generated... but only static version of the library. Unfortunately it seems it's not possible to generate the dynamic version with the GitHub Actions host-runners provided MinGW-w64 version (because 32bit linkage libraries are not included).
