### ISSUE TITLE
[core] Listing files recursively not working (raylib 4.2.0)

### ISSUE THREAD

**Issue by gordonshamway23** [raysan5/raylib#2704]
Hello everyone.

When calling LoadDirectoryFilesEx with scanSubdirs=true only files in the top level directory ("basePath") are listed.
I had a quick look in the in the sources and found the issue.
The first line in the ScanDirectoryFilesRecursively function:

`
static char path[MAX_FILEPATH_LENGTH] = {0};
`

must be wrong. Actually it should be:

`
char path[MAX_FILEPATH_LENGTH] = {0};
`

In order to work. Else the path is set instantly to an empty string in every recursive call of ScanDirectoryFilesRecursively.

`else ScanDirectoryFilesRecursively(path, files, filter);`

and therefore no files of subdirectories and sub-subdirectories etc are listed.

Have a nice day.

**Comment by raysan5** [comment]
@gordonshamway23 Thanks for the review!
