### ISSUE TITLE
real time tracelog

### ISSUE THREAD

**Issue by Triangle345** [raysan5/raylib#271]
Is it possible to do tracelog real time at the moment you execute it.  Currently it seems the messages are buffered and displayed at the end. Real time tracelog is useful for debugging issues that would otherwise be hard to do in a debugger. I'm not sure if there is a macro or some switch to make it real time?

**Comment by raysan5** [comment]
Actually, `TraceLog()` messages are sent to console output in real time; if youy execute the program from command line you will see those messages as soon as they occur.

Maybe you refer to Notepad++ output console? It seems they are not displayed until program is closed...

**Comment by Triangle345** [comment]
you are correct.  All though i'm using VSCode output console. However; it displays fine on command line.  These plugins probably open a new process and try to read the buffer output.  Thus they get buffered until exit.
