### ISSUE TITLE
[models] `GenMeshHeightmap()` scaling error

### ISSUE THREAD

**Issue by Grobnar** [raysan5/raylib#2716]
I discovered an issue while trying to tile heightmaps as map pieces where gaps would appear between the tiles.
Weirder still, when testing I found that the size of the gap would change based on the resolution of the heightmap used.

The issue turned out to be with the scaleFactor value in GenMeshHeightmap.
It essentially scales the heightmap image up to the desired scale of the mesh.
Then it creates a vertex for each pixel of the heightmap, as though placing a vertex in the center of each pixel.

So the issue ends up being that 1/2 a pixel's worth of space ends up being lost from the desired scale on each side of the XZ axis.
Or more accurately 1 scaleFactor is lost along the X and Z axis.

Here's the original line:
Vector3 scaleFactor = { size.x/mapX, size.y/255.0f, size.z/mapZ };

Here's my proposed alternative:
Vector3 scaleFactor = { size.x/(mapX-1), size.y/255.0f, size.z/(mapZ-1) };

In my tests of a simple 2x2 grid of 32x32 mat gray heightmaps, this solved the issue of gaps, appearing to now scale the generated mesh to the desired scale.

**Comment by Grobnar** [comment]
Sorry, first time submitting an issue and I didn't read the contributing guidelines first.
This is in the rmodels.c file.

**Comment by raysan5** [comment]
@Grobnar Thanks for the improvement! Function reviewed! :)
