### ISSUE TITLE
[core] `GetGamepadAxisMovement()` is not returning expected value

### ISSUE THREAD

**Issue by Shadowblitz16** [raysan5/raylib#2725]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

GetGamepadAxisMovement is not returning correct values.
They should be returning a unit circle for x and y but seem to be returning a 1 and a 0.5 when I hold diagonally,
It also doesn't seem to be able to represent more then 8 directional movement.

### Environment

OS: KDE neon 5.25
Processors: 16 x AMD Ryzen 7 5700G with Radeon Graphics
Graphics Procceser: AMD RENOIR
Rock Candy Xbox 360 controller

### Issue Screenshot
This is me holding diagonally down left
![image](https://user-images.githubusercontent.com/2453707/192687351-bc951418-e533-4b42-b0ab-d94fc06907d1.png)

### Code Example

```
velocity.X = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_X) * speed;
velocity.Y = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_Y) * speed;
position.X += velocity.X;
position.Y += velocity.Y;
```

**Comment by raysan5** [comment]
@Shadowblitz16 I'm afraid this issue could be related to the gamepad mapping, not detecting the correct Gamepad.

Just updated to latest [GamecControllerDB](https://github.com/gabomdq/SDL_GameControllerDB).

**Comment by Shadowblitz16** [comment]
> @Shadowblitz16 I'm afraid this issue could be related to the gamepad mapping, not detecting the correct Gamepad.
> 
> Just updated to latest [GamecControllerDB](https://github.com/gabomdq/SDL_GameControllerDB).

How do I do that? 
I use the C# version of raylib.

rock candy xbox 360 controllers are kinda old too.

**Comment by raysan5** [comment]
@Shadowblitz16 you should test the C gamepad example

**Comment by Shadowblitz16** [comment]
> @Shadowblitz16 you should test the C gamepad example
I did twice.
The first time I thought it was raylib only, but the second time a noticed in the gamepad example that my axes were things like... ```1, 0.5```
and 
```1, -1``` when pressing diagonal, and my movement was only going in 8 directions and not 360.
Also the devs of raylib-cs said it was a problem with c raylib.

**Comment by Shadowblitz16** [comment]
@raysan5
