### ISSUE TITLE
[core] Window is opened on a secondary monitor on Linux/X11

### ISSUE THREAD

**Issue by darthdeus** [raysan5/raylib#2728]
### Issue description

The "hello world" of raylib opens the window on a wrong (secondary) monitor on Linux/X11. The same does not happen when using raw glFW or SDL2, or any other program tested on the same machine.

### Environment

Arch Linux x86_64, OpenGL 4.6.0, NVidia driver 515.65.01, GPU RTX 3060.

### Issue Screenshot

N/A

### Code Example

Any raylib example reproduces this, e.g.

```c
#include "raylib.h"

int main(void) {
  InitWindow(800, 450, "raylib [core] example - basic window");

  while (!WindowShouldClose()) {
    BeginDrawing();

    ClearBackground(RAYWHITE);
    DrawText("Congrats! You created your first window!", 190, 200, 20,
             LIGHTGRAY);

    EndDrawing();
  }

  CloseWindow();

  return 0;
}
```

Calling `SetWindowMonitor(0)` (or `1`) does print `INFO: GLFW: Selected fullscreen monitor: [1] XXX` where `XXX` changes as expected, but the window remains fullscreen on the secondary monitor.

Calling `SetWindowPosition(...)` does work to offset the window, but of course this isn't desirable for anything but development.

Since Raylib uses glFW I tried to reproduce this with raw glfw, but I could not, as even the most trivial glfw program such as the following opens the window on the correct monitor.

```c
#include <GLFW/glfw3.h>

#include <stdio.h>
#include <stdlib.h>

static void error_callback(int error, const char *description) {
  fprintf(stderr, "Error: %s\n", description);
}

static void key_callback(GLFWwindow *window, int key, int scancode, int action,
                         int mods) {
  if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
    glfwSetWindowShouldClose(window, GLFW_TRUE);
}

int main(void) {
  GLFWwindow *window;

  glfwSetErrorCallback(error_callback);

  if (!glfwInit())
    exit(EXIT_FAILURE);

  window = glfwCreateWindow(640, 480, "FLOAT", NULL, NULL);
  if (!window) {
    glfwTerminate();
    exit(EXIT_FAILURE);
  }

  glfwSetKeyCallback(window, key_callback);

  glfwMakeContextCurrent(window);

  while (!glfwWindowShouldClose(window)) {
    glfwSwapBuffers(window);
    glfwPollEvents();
  }

  glfwDestroyWindow(window);

  glfwTerminate();
  exit(EXIT_SUCCESS);
}
```

I had the same result with SDL2 that also opens windows on the correct desktop, though this is not particularly relevant, but maybe worth mentioning. I also checked a few different applications that use glfw that also open their windows on the correct monitor.

This leads me to believe that it must be a bug in raylib itself.

**Comment by raysan5** [comment]
@darthdeus That's weird... I checked the code at `InitGraphicsDevice()` in `rcore`, where the window is created and actually, it does mostly the same than your GLFW3 implementation.

I reviewed some function calls order but it shouldn't change anything... I'm afraid this issue should be debugged carefully on the target platform, unfortunately I'm not using Linux. Is your monitor the primary monitor?

**Comment by RandomErrorMessage** [comment]
The glfwSetWindowPos to "center the window" is what causes it. In my configuration my primary monitor is on the right, and my secondary is on the left. Meaning position 0x0 is the top-left corner of my secondary monitor.

https://github.com/raysan5/raylib/blob/45da03df236db2090ac9a53aac572b0b91278a64/src/rcore.c#L4118

**Comment by raysan5** [comment]
Last commit should fix this issue.
