### ISSUE TITLE
[shapes] `DrawLineBezier*()` functions redesign

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#2735]
As stated in this PR (https://github.com/raysan5/raylib/pull/2721), `DrawLineBezier*()` functions do not work as expected, leaving gaps between the lines. Solution requires a redesign of those functions using triangle-strip.

`DrawLineBezier()` calls `DrawLineEx()` that calls `DrawTriangleStrip()`. That last function should actually manage the gaps properly because it's a triangle strip. 

`DrawLineBezier()` shouldn't use `DrawLineEx()` to draw the bezier in small pieces but use a custom `DrawTriangleStrip()` implementation to define all required points while drawing the triangles connection between them.

**Comment by kgpjay** [comment]
hi @raysan5, please assign me this issue, I would can work on this.

**Comment by raysan5** [comment]
@kgpjay You got the issue assigned, feel free to ask if you have any question. Remember to check the required [coding conventions](https://github.com/raysan5/raylib/blob/master/CONVENTIONS.md).

**Comment by raysan5** [comment]
@kgpjay Are you working on this feature? Any progress?

**Comment by nobytesgiven** [comment]
Working on this, will open a pull request soon.
