### ISSUE TITLE
[audio] Audio examples don't work when compiled with the latest version of Emscripten

### ISSUE THREAD

**Issue by rileyocall** [raysan5/raylib#2739]
### Issue description

Emscripten update 3.1.21 makes "ccall" a legacy function which is not available with the default compiler flags (those in the raylib makefile). The audio examples compiled with the latest version of Emscripten don't produce sound in the browser and there is an error in the javascript console due to a missing reference to "ccall".

A working solution to the problem is to add the compiler flag -sLEGACY_RUNTIME=1 when compiling with Emscripten. 

I added this line to my makefile:

<img width="452" alt="Screen Shot 2022-10-02 at 9 59 21 PM" src="https://user-images.githubusercontent.com/12059659/193505089-150d9f00-822f-481a-b0f1-5310a2f86271.png">

That should help unblock anyone who runs into this. The long term fix will require finding an alternative to "ccall". Feel free to close this whenever. I just wanted to spread awareness!

**Comment by raysan5** [comment]
@rileyocall I compiled `rFXGen` some days ago with emscripten 3.1.23 and I think audio worked for me in local execution... but I could be confused...
```c
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.23 (5ae63ce7dd955df449cb419bfe5afc51d1bd57f2)
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
```
The uploaded version is compiled with GitHub Action using 3.1.0 and [it works ok](https://raylibtech.itch.io/rfxgen).

In any case, is it possible to avoid the `ccall()`?

**Comment by Peter0x44** [comment]
`-s EXPORTED_RUNTIME_METHODS=ccall` also works for me.
Using the latest emscripten, it is required to work.
I don't know if avoiding the ccall is possible or what replacements exist.

**Comment by raysan5** [comment]
@Peter0x44 Just opened a related issue on `miniaudio` project. For now, I think your solution is the optimus one, feel free to send a PR with that addition. Thanks!

**Comment by mackron** [comment]
I've pushed a potential fix for this to the miniaudio dev branch. Is someone able to give that a try just to confirm it's working?

**Comment by raysan5** [comment]
@rileyocall Please, could you verify this fix works for you?

**Comment by raysan5** [comment]
I tested it and it works.
