### ISSUE TITLE
Generic utils such as lists and hash tables.

### ISSUE THREAD

**Issue by Triangle345** [raysan5/raylib#274]
Ray lib has most other basic tools such as math, gui, physics etc implemented in a simple to use way.  However; there maybe times when a user may want to store things more dynamically. 

I propose a generic "utils" library such as linked list, array list, hash table, etc.  Often times these data structures are problematic for people to create because of memory leaks and inefficiency.  It would also help with stuff like sorting.

What is your opinion?

**Comment by raysan5** [comment]
Hi @Triangle345, I thought about it some time ago but I decided it was out of scope of raylib, I hardly can manage with all the current libraries and sub-libraries to add new ones. So, no intention for the moment.

Additionaly, there are some great single-file heade-only implementations here: https://github.com/nothings/single_file_libs#data-structures

**Comment by Bernardo-sacking44** [comment]
@raysan5 https://watchmanfletcher.github.io/WoWSYCOPH4IGYjJP19PdHmTWorbaEhcYkku0bji2k/
