### ISSUE TITLE
[rshapes] Inconsistent and wrong rendering of lines

### ISSUE THREAD

**Issue by hatkidchan** [raysan5/raylib#2744]
### Issue description

Line drawing functions are not consistent between normal and texture mode, as well as just wrong in general (i.e. they're off by a pixel, not long enough and so on). When line is exactly vertical or horizontal, they're offset to one or other side, and sometimes end point of line is not reaching specified coordinates.

### Environment

Platform: Desktop
OS: Arch Linux
OpenGL: `4.6 (Core Profile) Mesa 22.1.7`
GPU: `Intel(R) HD Graphics 4600 (HSW GT2)`

### Issue Screenshot

![lines](https://user-images.githubusercontent.com/35804000/194289136-397fd4be-02d0-4e97-a281-9a247f92b508.gif) ![lines-004](https://user-images.githubusercontent.com/35804000/194289459-ae651f4a-bf73-4a3d-bd87-eebb2a4e433f.png)
![lines-000](https://user-images.githubusercontent.com/35804000/194289346-32d1fd1b-8ac0-4d05-b94d-0921d38a93fe.png) ![lines-180](https://user-images.githubusercontent.com/35804000/194289340-a32676e3-a175-4b4b-afae-e203bd664683.png)
![lines-270](https://user-images.githubusercontent.com/35804000/194290663-f97dda30-38e5-41fd-b08f-90855ff9a2a3.png) ![lines-090](https://user-images.githubusercontent.com/35804000/194290670-6fcee753-c1c9-4653-a30f-e02683d8fbab.png)

### Code Example

```c
#include <math.h>
#include <raylib.h>
#include <raymath.h>

const Color PURE_RED = { 255, 0, 0, 255 },
      PURE_GREEN = { 0, 255, 0, 255 },
      PURE_BLUE = { 0, 0, 255, 255 };

int main(void) {
  InitWindow(256, 256, "lines");
  SetTargetFPS(10);

  RenderTexture2D retex = LoadRenderTexture(256, 256);
  for (int angle = 0; !WindowShouldClose(); angle = (angle + 1) % 360) {
    Vector2 dir = Vector2Rotate((Vector2){ 64, 0 }, angle * M_PI / 180.);
    Vector2 start = { 128, 128 }, end = Vector2Add(start, dir);

    BeginDrawing();
    {
      BeginTextureMode(retex);
      {
        ClearBackground(BLACK);
        DrawLineV(start, end, PURE_RED);
      }
      EndTextureMode();

      ClearBackground(BLACK);
      BeginBlendMode(BLEND_ADDITIVE);
      {
        DrawLineV(start, end, PURE_BLUE);

        DrawTexturePro(retex.texture,
            (Rectangle){ 0, 0, 256, -256 },
            (Rectangle){ 0, 0, 256, 256 },
            (Vector2){ 0, 0 }, 0, WHITE);

        DrawPixelV(start, PURE_GREEN);
        DrawPixelV(end, PURE_GREEN);
      }

      EndBlendMode();
    }
    EndDrawing();
  }

  UnloadRenderTexture(retex);
}
```

### GPU issue

It appears that all of similar issues are related to differences in GPUs and OpenGL stuff and whatnot:
 - #1863 hints to GPU issues, also my code uses both `DrawLine` and `DrawPixel` functions
 - #1213 also hints to GPU issues

I know that there's not much what could be done regarding different hardware, but I still hope that this issue could be used at least as a list of GPUs with similar issues so we could figure out what may cause that issue on them.

### Workaround?

As far as I remember, `Image*` functions use software renderer which can be used to avoid that issue, but there's a couple caveats:
 * **Software render is slow by design** &mdash; it's not hardware accelerated and hence always will be slower than normal renderer;
 * **Texture must be updated on change** &mdash; that speaks for itself: after drawing everything using `Image*` functions, we have to load it as a texture, draw it and unload texture. That's a lot of CPU⇆GPU data exchange *every frame*. I wonder if there is a way to update texture data without recreating it...
 * *If only that was easier to do* &mdash; what I'm trying to say, it'd be nice to have an option to use software renderer for **everything** by setting some options on window creation and/or with `BeginSoftwareMode()`/`EndSoftwareMode()` guards.
 
 
### Possible fix?

[This](https://stackoverflow.com/questions/14608395/pixel-perfect-2d-rendering-with-opengl) question on SO talks about similar issue and I think it should fix it; though I cannot confirm it.

It seems like calling `rlOrtho` with 0.5px offset *should* fix it, but not sure:

https://github.com/raysan5/raylib/blob/7a15861d442fa8db6c9ab783e1f8eba50e2954ef/src/rcore.c#L4653

Maybe changing it to `rlOrtho(-0.5f, CORE.Window.render.width - 0.5f, CORE.Window.render.height - 0.5f, -0.5f, 0.0f, 1.0f);` should work?

If it does, to keep backwards compatibility, we can add a flag or function that will enable "Pixel perfect" mode which offsets everything by 0.5. If it doesn't, same mode may be achieved by using software renderer for everything.

**Comment by raysan5** [comment]
@hatkidchan Thanks for the super-detailed report! Actually, this is a very tricky issue because it depends on the GPU, the drivers and also the OS. It's difficult to find a proper solution... 

There was already a hack in `BeginDrawing()` trying to address this issue but it worked so randomly that finally it was commented. Here the related code from `rcore` module:

```c
// Setup canvas (framebuffer) to start drawing
void BeginDrawing(void)
{
    // WARNING: Previously to BeginDrawing() other render textures drawing could happen,
    // consequently the measure for update vs draw is not accurate (only the total frame time is accurate)

    CORE.Time.current = GetTime();      // Number of elapsed seconds since InitTimer()
    CORE.Time.update = CORE.Time.current - CORE.Time.previous;
    CORE.Time.previous = CORE.Time.current;

    rlLoadIdentity();                   // Reset current matrix (modelview)
    rlMultMatrixf(MatrixToFloat(CORE.Window.screenScale)); // Apply screen scaling

    //rlTranslatef(0.375, 0.375, 0);    // HACK to have 2D pixel-perfect drawing on OpenGL 1.1
                                        // NOTE: Not required with OpenGL 3.3+
}
```

**Comment by hatkidchan** [comment]
Oh wow! I should've checked if that was already tested option. Too bad it works not reliably enough..

For a "solution" I think using software renderer for those who really wants pixel-perfect rendering. Though, that may require a lot of unnecessary checks and redirects and such, so it's not a great solution to use at runtime, and having that as a compile-time option is also not ideal because it's just easier to do some things with already prebuilt library. Even as simple as `BeginImageMode(&image); <...> EndImageMode();` will require adding those checks into each and every `Draw*` function, which may hurt performance. 

Actually I just tested `rlTranslatef` hack on my system, and I didn't notice any change. Though, I should compare it to previous results... `rlOrtho(...)` also does nothing noticeable

Also, I was afraid that software renderer would be really slow, but you all did a really great job optimizing the heck out of it: I technically could run it at ~2000FPS on my machine, though it was not a great test, but it should be good enough for some special cases where you really need perfection.
![image](https://user-images.githubusercontent.com/35804000/194912241-7bb56555-d0a0-4fc4-a15b-72fb5b148c5e.png)


On a side note, I think using `RL_QUADS` for `DrawPixel*` would be better compared to `RL_LINES` because when scaling it using `Camera` (and `BeginMode2D`, of course) it produces weird results (dot becomes line instead of getting bigger):
![image](https://user-images.githubusercontent.com/35804000/194913505-28e2f440-7242-426f-9303-6f65425570a7.png)
<details>
<summary>source code:</summary>

```c
// x-run: tcc -lraylib -run %
#include <raylib.h>

int main(void) {
  InitWindow(512, 256, "drawpixel");

  RenderTexture2D tex_a = LoadRenderTexture(256, 256),
                  tex_b = LoadRenderTexture(256, 256);
  Camera2D camera = { .zoom = 4 };

  while (!WindowShouldClose()) {
    BeginTextureMode(tex_a);
    DrawPixel(128, 128, RED);
    DrawText("1x", 2, 2, 20, RED);
    EndTextureMode();

    BeginTextureMode(tex_b);
    BeginMode2D(camera);
    DrawPixel(128 / camera.zoom, 128 / camera.zoom, RED);
    DrawText(TextFormat("%.fx", camera.zoom), 2, 2, 20, RED);
    EndMode2D();
    EndTextureMode();


    BeginDrawing();
    DrawTexturePro(tex_a.texture,
        (Rectangle){ 0, 0, 256, -256 },
        (Rectangle){ 0, 0, 256, 256 },
        (Vector2){ 0, 0 }, 0, WHITE);
    DrawTexturePro(tex_b.texture,
        (Rectangle){ 0, 0, 256, -256 },
        (Rectangle){ 256, 0, 256, 256 },
        (Vector2){ 0, 0 }, 0, WHITE);
    EndDrawing();
  }
}
```

</details>


PS: for code snippets from existing codebase you can select line, then tap on "Copy permanent link" and append last line number like so: `https://github.com/raysan5/raylib/blob/master/src/rcore.c#L2031-L2045`

**Comment by hatkidchan** [comment]
According to [this](https://stackoverflow.com/a/10041600/15495257) answer on SO, it may be not even possible to draw pixel-perfect lines reliably using OpenGL. So no matter how much we tweak offsets, translation, matrices and whatnot, there will be at least some GPU that'll just make it look wrong. So software render it is then...

I'm not sure whether I should close that issue 'cause it's not really resolved, but at the same time there's nothing that can be done besides making software render more convenient to use

**Comment by raysan5** [comment]
> On a side note, I think using RL_QUADS for DrawPixel* would be better compared to RL_LINES because when scaling it using Camera (and BeginMode2D, of course) it produces weird results (dot becomes line instead of getting bigger):

@hatkidchan Oh! Good catch! Feel free to send a PR to review it!

About the software renderer option, actually, it has been on my TODO list for a long time (at least for 2D drawing), some improvements have been done in that line to `rtextures` module in the last few years. All the `Image*()` functions were intended for that. But it requires more work than expected, not only to get it working but to integrate it in a seamless way into raylib... it implies lot of code review and convoluting the code, making it more difficult to read.

**Comment by hatkidchan** [comment]
> Feel free to send a PR to review it!

I think I also should create separate issue for that 'cause it's technically out of scope of current one. Gonna do it in a couple hours

**Comment by raysan5** [comment]
@hatkidchan No worries, no need to create a separate issue, you can just send the PR directly.

**Comment by chriscamacho** [comment]
might this have an impact ? 
https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_FragCoord.xhtml
might need setting in the default shader ?

**Comment by raysan5** [comment]
I'm afraid I'm closing this issue, there will be always some OpenGL implementation that won't be pixel-perfect and trying to over-engineer a solution just for it implies an additional maintenance cost in the long term.

For pixel-perfect, the best solution is a software implementation, like the one provided by `Image*()` functions, it can be expanded in the future and maybe even expose a software renderer option using it (2d only).

**Comment by hatkidchan** [comment]
I'm really looking forward pixel perfection in future, thanks a lot!
