### ISSUE TITLE
[rcore] Rename GetScreenWidth/GetScreenHeight to GetWindowWidth/GetWindowHeight

### ISSUE THREAD

**Issue by JojoPlusPlus** [raysan5/raylib#2759]
`GetScreenWidth()` and `GetScreenHeight()` might be a bit misleading. I did not find out about that they return the **window** width/height until just now. This made me search for ways of getting the window size in a few projects in the past, and I was actually about to start making a pull request for making the functions before I found out they existed with a different name.

Long story short, I think that renaming `GetScreenWidth()` and `GetScreenHeight()` to `GetWindowWidth()` and `GetWindowHeight()` will be way better, especially because all other window-related functions have "Window" in them. Users might not know if these functions are directed towards the window or monitor (one can also call a monitor a screen).

**Comment by raysan5** [comment]
@JojoPlusPlus Those functions return the screen framebuffer size that could the same as window or not. Also, it's a multiplatform function, Android or Web have no window.

**Comment by orcmid** [comment]
@raysan5 
> @JojoPlusPlus ... Also, it's a multiplatform function, Android or Web have no window.

I think `InitWindow` sort of sets the raylib model, independent of how that maps on different platforms.  One can rename the parameters for free of course, using a prototype like

'''C
void InitWindow(winWidth int, winHeight int)
```

Since it doesn't force any kind of renaming.  that would clean things up a bit.  

Renaming setters and getters is more complicated.  It might also be less complicated to introduce 

```C
void InitScreen(screenWidth int, screenHeight int)
```

And either way, there is some explaining to be done, including with respect to platform differences.

I do think it would be devilish to explain

```C
void InitScreenBuffer(screenWidth int, screenHeight int)
```

From my distance, it seems like a choose-your-poison kind of thing.  I'm not for breaking things though.
