### ISSUE TITLE
[audio] SetAudioStreamBufferSizeDefault does not set the buffer size

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#2769]
This can be confirmed with the `audio_raw_stream.c` example, it sets the buffer size to 4096, but the buffer size is always `1024*3 (3072)`:

```
INFO: [ALSA]
INFO:    (Playback)
INFO:     Format:      32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO:     Channels:    2 -> 2
INFO:     Sample Rate: 48000 -> 48000
INFO:     Buffer Size: 1024*3 (3072)
INFO:     Conversion:
INFO:       Pre Format Conversion:  NO
INFO:       Post Format Conversion: NO
INFO:       Channel Routing:        NO
INFO:       Resampling:             NO
INFO:       Passthrough:            YES
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / ALSA
INFO:     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   48000 -> 48000
INFO:     > Periods size:  3072
INFO: STREAM: Initialized successfully (44100 Hz, 16 bit, Mono)
```

**Comment by mackron** [comment]
The number you quoted is the size of the buffer used internally by miniaudio, but `SetAudioStreamBufferSizeDefault()` relates to the size of the buffer of the raylib `AudioStream` object. They're two entirely independent buffers.

**Comment by gen2brain** [comment]
Thanks, and sorry for the issue.  I am trying to create examples for my `pl_mpeg` port to Go, audio works in SDL, WEB, etc. but I have issues with raylib, I thought this was my problem.
