### ISSUE TITLE
[rtextures] inverse premultiply function (FEATURE REQUEST)

### ISSUE THREAD

**Issue by nobytesgiven** [raysan5/raylib#2771]
I suggest a new function: `void ImageAlphaInversePremultiply(Image *image)` 
This function makes sense since `void ImageAlphaPremultiply(Image *image)` exists.
I needed such function in #2770 to avoid the black edges when blurring and I assume it will be useful elsewhere too.

I can make a quick pr if needed, most of the code will remain the same with `ImageAlphaPremultiply`

**Comment by raysan5** [comment]
@nobytesgiven It seems a very specific function to me, personally I never required it. I prefer to avoid it for the moment, we are already adding several new functions to raylib and it increases maintenance cost.
