### ISSUE TITLE
[build] __ANDROID_API__ version is hardcoded to value incompatible with most of the recent android targets

### ISSUE THREAD

**Issue by johnnikolay** [raysan5/raylib#2772]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

raylib is seemed to be hardcoding android api version to 21 which is pretty old and incompatible with build targets above 23 ( which is most of the devices out there ).
The value is specified in LibraryConfigurations.cmake.

### Environment

Build for android on windows.

### Issue Screenshot

C:/Users/serge/source/myproject/build_android/arm64-v8a/_deps/raylib-src/src/external/tinyobj_loader_c.h:751:13: error: '__sF' is unavailable: obsoleted in Android 23
    fprintf(stderr, "TINYOBJ: Error reading file '%s': %s (%d)\n", filename, strerror(errno), errno);
            ^
C:/Users/serge/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdio.h:76:18: note: expanded from macro 'stderr'
#define stderr (&__sF[2])
                 ^
C:/Users/serge/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdio.h:72:13: note: '__sF' has been explicitly marked unavailable here
extern FILE __sF[] __REMOVED_IN(23);
            ^
In file included from C:/Users/serge/source/myproject/build_android/arm64-v8a/_deps/raylib-src/src/rmodels.c:69:
C:/Users/serge/source/myproject/build_android/arm64-v8a/_deps/raylib-src/src/external/tinyobj_loader_c.h:1326:15: error: '__sF' is unavailable: obsoleted in Android 23
      fprintf(stderr, "TINYOBJ: Failed to parse material file '%s': %d\n", filename, ret);

**Comment by raysan5** [comment]
@johnnikolay Where is `__ANDROID_API__` hardcoded in raylib source code? Afaik is a configuration option of the build system...

**Comment by johnnikolay** [comment]
https://github.com/raysan5/raylib/blob/master/cmake/LibraryConfigurations.cmake#L48

**Comment by raysan5** [comment]
@johnnikolay I'm afraid I don't know CMake, that build system was user contributed. Still, it looks like a build config option to me, could it be changed? Feel free to send a PR with the review if required.

**Comment by johnnikolay** [comment]
Author: Sergey Solovyev <sergeysol@tencent.com>
Date:   Mon Oct 24 15:14:38 2022 +0100

    Update api version to 23

diff --git a/cmake/LibraryConfigurations.cmake b/cmake/LibraryConfigurations.cmake
index 1e60e828..80813505 100644
--- a/cmake/LibraryConfigurations.cmake
+++ b/cmake/LibraryConfigurations.cmake
@@ -45,7 +45,7 @@ elseif (${PLATFORM} MATCHES "Android")
     set(GRAPHICS "GRAPHICS_API_OPENGL_ES2")
     set(CMAKE_POSITION_INDEPENDENT_CODE ON)
     list(APPEND raylib_sources ${ANDROID_NDK}/sources/android/native_app_glue/android_native_app_glue.c)
-    add_definitions(-DANDROID -D__ANDROID_API__=21)
+    add_definitions(-DANDROID -D__ANDROID_API__=31)
     include_directories(${ANDROID_NDK}/sources/android/native_app_glue)
     set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -u ANativeActivity_onCreate -Wl,-undefined,dynamic_lookup")

**Comment by raysan5** [comment]
@johnnikolay I'm afraid I don't use CMake and I'm not building for Android at this moment, probably other users should answer this question.

**Comment by johnnikolay** [comment]
`Feel free to send a PR with the review if required.
`
@raysan5  I do not have permissions to create branch in this repo and create PRs.

**Comment by raysan5** [comment]
@johnnikolay you have to create a fork, do the changes in your fork, test the changes if they work as expected and send a PR.

**Comment by anggape** [comment]
im building android project just fine even with __ANDROID_API__ harcoded into raylib cmake config

**Comment by anggape** [comment]
@raysan5 should i add android studio project to projects template?

**Comment by anggape** [comment]
@SergeySol84 https://github.com/anggape/raylib-2772

**Comment by johnnikolay** [comment]
@anggape  you need to use stderr in your program, for example
`DEBUG_ERR("Trigger compilation error");`

**Comment by anggape** [comment]
> @anggape  you need to use stderr in your program, for example
> `fprintf(stderr, "Trigger compilation error");`

https://github.com/anggape/raylib-2772/commit/7c3a52d02d87759d743156bae40fe3fc1d9dcd39
https://github.com/anggape/raylib-2772/actions/runs/3323365022/jobs/5493614050

no error still working

**Comment by SergeySol84** [comment]
@anggape  you also need to use windows toolchain where you will hit the following
```
#if __ANDROID_API__ >= 23
extern FILE* stdin __INTRODUCED_IN(23);
extern FILE* stdout __INTRODUCED_IN(23);
extern FILE* stderr __INTRODUCED_IN(23);

/* C99 and earlier plus current C++ standards say these must be macros. */
#define stdin stdin
#define stdout stdout
#define stderr stderr
#else
/* Before M the actual symbols for stdin and friends had different names. */
extern FILE __sF[] __REMOVED_IN(23);

#define stdin (&__sF[0])
#define stdout (&__sF[1])
#define stderr (&__sF[2])
#endif

```
Are you on windows or linux ? Also pleae check if  stdio.h in your ndk is containing the code above ? Maybe you are using old ndk.

**Comment by anggape** [comment]
building on windows still works fine https://github.com/anggape/raylib-2772/actions/runs/3325777901/jobs/5498817568

**Comment by anggape** [comment]
im curious what happen if we completely delete __ANDROID_API__ define on raylib config, does that break anything?

**Comment by johnnikolay** [comment]
Indeed, minsdk 21 works, thanks @1ethanonly.  I can compile raylib now. Should be good enough for me as I can still run my app which is using higher min target.

**Comment by anggape** [comment]
turn out we don't actually need to define -DANDROID and -D__ANDROID_API__ since its defined by android studio

https://github.com/anggape/raylib-2772/actions/runs/3327909276/jobs/5503283092
