### ISSUE TITLE
[camera] Zoom does not work with orthogonal projection

### ISSUE THREAD

**Issue by k-novak** [raysan5/raylib#2773]
Version: raylib 4.2.0 (11 August 2022)
IDE/Compiler: Visual Studio 2022 Community edition
Code example: core_3d_camera_free from examples

The program works fine, when `camera.projection = CAMERA_PERSPECTIVE;` Zoom/pan/rotation are all fine.
If `camera.projection` is changed to `CAMERA_ORTHOGRAPHIC`, zoom does not works anymore.
In raylib.h/`struct Camera3D` there is a comment: `float fovy;             // Camera field-of-view aperture in Y (degrees) in perspective, used as near plane width in orthographic`. But no code changes the this variable.

I made a quick and dirty solution: I just added the following code to the right branch of the switch in the `UpdateCamera` function, and it worked!

```
if (camera->projection == CAMERA_ORTHOGRAPHIC && mouseWheelMove < 0)
{
    camera->fovy -= 5.0f;
}
else if (camera->projection == CAMERA_ORTHOGRAPHIC && mouseWheelMove > 0)
    {
camera->fovy += 5.0f;
}
```

Is there any plan to implement this in the near future?

**Comment by raysan5** [comment]
@k-novak Camera system is being completely redesigned but feel free to send a PR with this addition for current implementation.

**Comment by raysan5** [comment]
No PR, no addition.
