### ISSUE TITLE
[core] Full Screen window opens but can not interact with mouse (RPI 3)

### ISSUE THREAD

**Issue by Zoarial94** [raysan5/raylib#279]
After compiling the core examples I opened the core_2d_camera executable, it opened in fullscreen however I am unable to see my mouse or use the keyboard. I was able to find out while using a VNC connection that when I run it in Terminal the terminal window appears on the VNC connection but the full screen is only on the monitor. If I have the terminal as my current window I am able to use the keyboard in the game but I still can't use the mouse. Is there anything I can do to fix this?

**Comment by raysan5** [comment]
Are you running it from XWindow interface? 
How did you compile it? Did you use `make PLATFORM=PLATFORM_RPI`? 

raylib is prepared by default to run in console mode (no XWindow graphic interface); in that mode it [reconfigures keyboard](https://github.com/raysan5/raylib/blob/develop/src/core.c#L2855) to read from standard input in raw mode, mouse is also read in raw mode (no XWindow processing).

**Comment by Zoarial94** [comment]
I'm not sure how to run it with XWindow, all I was double click the executable, I opened it regularly and in a terminal and got the same result both ways. I compiled it using `make PLATFORM=PLATFORM_RPI` and I used the master branch.

**Comment by raysan5** [comment]
ok, raylib it's prepared to run by default with no graphic desktop loaded, just the default command line that you get when you init the RPI, before entering in any kind of graphic interface... when a desktop is loaded (PIXEL/LXDE/XFCE...) usually XWindows libraries are loaded and inputs are remapped for that desktop... raylib is prepared to work with no XWindow, it means, before loading the graphic desktop, from just the command line...

Actually, haven't tried to use it from a graphic desktop... and that's a point to review... and the origin of your issue...

**Comment by raysan5** [comment]
Just for clarification, here it is a small diagram that shows how input interrupts are send through multiple system layers to be read from applications:

```
         +--------+          +----------+               +-------------+
-------->| kernel |--------->| X server |-------------->| application |
         +--------+          +----------+               +-------------+
interrupt          scancode                 keysym
                   =keycode                +modifiers
                      ^                        ^
            (raylib works here)        (you try to use here)
```

More info: https://unix.stackexchange.com/questions/116629/how-do-keyboard-input-and-text-output-work

I've been investigating how to support XServer processed inputs from raylib and it requires some work and redesign... I'm not implementing it for the moment.
