### ISSUE TITLE
[core] EGL_TRANSPARENT_RGB flag crash

### ISSUE THREAD

**Issue by dginu85** [raysan5/raylib#280]
Hi guys, I'm developing gui for rpi, but I need the background to be transparent ...

I tried to rebuild the library with this "**EGL_TRANSPARENT_RGB**" flag but it does not work, as soon as I start my application, the library is initialized correctly but can not get the surface information and subsequently generates a "SIGSEGV: Segmentation fault" error.

How can I create a transparent background?

**START INFO LOG:**
INFO: Initializing raylib (v1.7.0)
INFO: Display device initialized successfully
INFO: Display size: 800 x 480
INFO: Render size: 800 x 480
INFO: Screen size: 800 x 480
INFO: Viewport offsets: 0, 0
INFO: GPU: Vendor:   (null)
INFO: GPU: Renderer: (null)
INFO: GPU: Version:  (null)
INFO: GPU: GLSL:     (null)

**Comment by raysan5** [comment]
Hi @dginu85, I assume you set that flag on `core.c` -> `InitGraphicsDevice()` -> [framebufferAttribs](https://github.com/raysan5/raylib/blob/develop/src/core.c#L1822) this way:
```c
const EGLint framebufferAttribs[] =
{
    EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,     // Type of context support -> Required on RPI?
    EGL_RED_SIZE, 8,            // RED color bit depth (alternative: 5)
    EGL_GREEN_SIZE, 8,          // GREEN color bit depth (alternative: 6)
    EGL_BLUE_SIZE, 8,           // BLUE color bit depth (alternative: 5)
    EGL_ALPHA_SIZE, 8,        // ALPHA bit depth
    EGL_TRANSPARENT_TYPE, EGL_TRANSPARENT_RGB, // Request transparent framebuffer
    EGL_DEPTH_SIZE, 16,         // Depth buffer size (Required to use Depth testing!)
    EGL_SAMPLE_BUFFERS, sampleBuffer,    // Activate MSAA
    EGL_SAMPLES, samples,       // 4x Antialiasing if activated (Free on MALI GPUs)
    EGL_NONE
};
```
If it doesn't work that way, maybe it's not supported by the hardware...

**Comment by dginu85** [comment]
HI raysan5, Thanks for reply :-)

look here https://www.facebook.com/DavGiorgianni/videos/1297212513693209/
i try your code..

**Comment by dginu85** [comment]
@raysan5 :-(
INFO: Initializing raylib (v1.7.0)
INFO: Display device initialized successfully
INFO: Display size: 800 x 480
INFO: Render size: 800 x 480
INFO: Screen size: 800 x 480
INFO: Viewport offsets: 0, 0
INFO: GPU: Vendor:   (null)
INFO: GPU: Renderer: (null)
INFO: GPU: Version:  (null)
INFO: GPU: GLSL:     (null)

**Comment by raysan5** [comment]
mmm... don't know... maybe it's some config parameter missing? I saw the following params are also available:
```
EGL_TRANSPARENT_TYPE
EGL_TRANSPARENT_RED_VALUE
EGL_TRANSPARENT_GREEN_VALUE
EGL_TRANSPARENT_BLUE_VALUE
```
Can you build the GUI just using transparent textures, directy drawing on canvas?

Or maybe you can use a framebuffer object (RenderTexture2D) to do the drawing: https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_postprocessing.c

**Comment by dginu85** [comment]
not work ...
EGL_TRANSPARENT_TYPE
EGL_TRANSPARENT_RED_VALUE
EGL_TRANSPARENT_GREEN_VALUE
EGL_TRANSPARENT_BLUE_VALUE

This works fine, but it transforms everything.
VC_DISPMANX_ALPHA_T 
    alpha.flags = DISPMANX_FLAGS_ALPHA_FIXED_ALL_PIXELS;
    alpha.opacity = **255**; --> **125** ex
    alpha.mask = 0;

The transparency I need to play the video.

**Comment by raysan5** [comment]
If not using EGL_TRANSPARENT_TYPE config parameter, does it work (I mean with no transaparency)? Is OpenGL ES 2.0 context initialized?

**Comment by dginu85** [comment]
@raysan5 

not work
```
EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,     // Type of context support -> Required on RPI?
		EGL_RED_SIZE, 8,            // RED color bit depth (alternative: 5)
		EGL_GREEN_SIZE, 8,          // GREEN color bit depth (alternative: 6)
		EGL_BLUE_SIZE, 8,           // BLUE color bit depth (alternative: 5)
		EGL_ALPHA_SIZE, 8,        // ALPHA bit depth
		EGL_TRANSPARENT_TYPE,**EGL_TRANSPARENT_RGB**, // Request transparent framebuffer
		EGL_DEPTH_SIZE, 16,         // Depth buffer size (Required to use Depth testing!)
		EGL_SAMPLE_BUFFERS, sampleBuffer,    // Activate MSAA
		EGL_SAMPLES, samples,       // 4x Antialiasing if activated (Free on MALI GPUs)
		EGL_NONE
```
this work 

```
EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,     // Type of context support -> Required on RPI?
		EGL_RED_SIZE, 8,            // RED color bit depth (alternative: 5)
		EGL_GREEN_SIZE, 8,          // GREEN color bit depth (alternative: 6)
		EGL_BLUE_SIZE, 8,           // BLUE color bit depth (alternative: 5)
		EGL_ALPHA_SIZE, 8,        // ALPHA bit depth
		EGL_TRANSPARENT_TYPE,**EGL_NONE** // Request transparent framebuffer
		EGL_DEPTH_SIZE, 16,         // Depth buffer size (Required to use Depth testing!)
		EGL_SAMPLE_BUFFERS, sampleBuffer,    // Activate MSAA
		EGL_SAMPLES, samples,       // 4x Antialiasing if activated (Free on MALI GPUs)
		EGL_NONE
```

**Comment by raysan5** [comment]
Hi @dginu85! Thank you very much for the update and detecting this issue! 

Please, could you provide some small sample for this feature usage?

**Comment by dginu85** [comment]
Hi @raysan5 :-)

main.c
```
int main()
{
   InitWindow(screenWidth, screenHeight, "myapp");
   Init();
   while (isrun)
   {
	   Update();
   }
   return 0;
}
```
core.c

```
const EGLint framebufferAttribs[] =
	{
		EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,     // Type of context support -> Required on RPI?
		EGL_RED_SIZE, 8,            // RED color bit depth (alternative: 5)
		EGL_GREEN_SIZE, 8,          // GREEN color bit depth (alternative: 6)
		EGL_BLUE_SIZE, 8,           // BLUE color bit depth (alternative: 5)
		EGL_ALPHA_SIZE, 8,        // ALPHA bit depth
		EGL_TRANSPARENT_TYPE,EGL_NONE, // Request transparent framebuffer
		EGL_DEPTH_SIZE, 16,         // Depth buffer size (Required to use Depth testing!)
		EGL_SAMPLE_BUFFERS, sampleBuffer,    // Activate MSAA
		EGL_SAMPLES, samples,       // 4x Antialiasing if activated (Free on MALI GPUs)
		EGL_NONE
	};
```

**Comment by raysan5** [comment]
hehehe... thanks! :D 

I mean, what's the visual difference or direct application of having a transparent framebuffer? It was not clear to me just seeing the video you shared...

Could you share two comparison images if it's not a lot of trouble?

**Comment by dginu85** [comment]
I did not understand the question!

Do you want a screenshot with my application (constructed with raylib) with 125 transparency?

VC_DISPMANX_ALPHA_T
alpha.flags = DISPMANX_FLAGS_ALPHA_FIXED_ALL_PIXELS;
alpha.opacity = 255; --> 125 ex
alpha.mask = 0;

**Comment by raysan5** [comment]
no problem... yes, I mean an screenshot to see results.

**Comment by dginu85** [comment]
@raysan5 
![image](https://cloud.githubusercontent.com/assets/4887152/25859076/b1949ca4-34dd-11e7-99e5-25f8cf9454a7.png)

**Comment by raysan5** [comment]
ok! I see! You got a full-screen semi-transparent window and you can see the console in the back... very interesting! :)

Thank you very much for tracking this issue and finding a solution, just added some notes on commit https://github.com/raysan5/raylib/commit/321027a242e287e00ac0884387113db4b09ea065 for future adventurers (or a future implementation).
