### ISSUE TITLE
[linking] raylib linking issue on windows

### ISSUE THREAD

**Issue by diffproject** [raysan5/raylib#2806]
I am trying to compile an example from raylib examples. Here is my batch file to compile it (I am attaching a text file as Github is not parsing the batchscript correctly):

[New Text Document.txt](https://github.com/raysan5/raylib/files/10070908/New.Text.Document.txt)

But when I call the above batch script (runr.bat in my system) with a file, for example:
`.\runr.bat textures\textures_bunnymark.c`,

I get the following linking error:

`C:/raylib/w64devkit/bin/ld.exe: c:/raylib/w64devkit/bin/../lib/gcc/i686-w64-mingw32/12.1.0/../../../../i686-w64-mingw32/lib/../lib\libmingw32.a(lib32_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x37): undefined reference to 'WinMain@16'
collect2.exe: error: ld returned 1 exit status`.

But the example works fine when I launch it from npp for raylib using F6.

Can anybody please tell me what is going on? I really want to use my own editor instead of npp. Thanks in advance.

**Comment by orcmid** [comment]
The linker is attempting to find a program written for the Windows GUI with entry point WinMain.  

My question is about these two lines in your batch script:

```
::gcc -o %NAMEPART%.exe %FILE_NAME% %CFLAGS% %LDFLAGS%
gcc -o %NAMEPART%.exe %FILE_NAME% C:\raylib\raylib\src\raylib.rc.data -s -static -O2 -std=c99 -Wall -IC:\raylib\raylib\src -Iexternal -DPLATFORM_DESKTOP -lraylib -lopengl32 -lgdi32 -lwinmm
```

Why are you not simply removing the `::` from the first of these two and not using the second, manually-expanded one?

**Comment by diffproject** [comment]
The manually expanded line is the line from the console output of npp when you execute with F6. Since it was working there I thought I would try it out in the batch script.

**Comment by diffproject** [comment]
turns out there was a typo in the batch script, it should be FILENAME not FILE_NAME.
