### ISSUE TITLE
[text] TTF font: ascii extended char not visualized

### ISSUE THREAD

**Issue by TronicLabs** [raysan5/raylib#281]
``` c
int charList[256];
for (int i = 0; i < 255; i++) charList[i] = i; 
SpriteFont fontL = LoadSpriteFontEx("my_font.ttf", 24, 255, charList);
const char msg[256] = "ASCII extended characters:\n¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆ\nÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæ\nçèéêëìíîïðñòóôõö÷øùúûüýþÿ";

```
Even if you use the specific character range, extended characters are not displayed, or any other character after the 126th.
Where do I make a mistake?

**Comment by raysan5** [comment]
Weird... it should work, just checked the code... I'll test it again and let you know...

**Comment by TronicLabs** [comment]
I had forgotten to say that the problem is compiling it with Visual Studio 2015.
It is resolved by adding a cast here:
https://github.com/raysan5/raylib/blob/master/src/text.c#L446

from:
````c
else index = GetCharIndex(spriteFont, (int)text[i]);
````
to
```` c
else index = GetCharIndex(spriteFont, (unsigned char)text[i]);
````

**Comment by raysan5** [comment]
Wow! Good catch! Implemented in commit https://github.com/raysan5/raylib/commit/4c27412eff10f8ef633d97017dcb9e2faff4c4e1
