### ISSUE TITLE
railib is not even Build to

### ISSUE THREAD

**Issue by Staxcelrom** [raysan5/raylib#2811]
railiba is not even Build to Cmake.

```
CMake Error at CMakeLists.txt:118 (include):
  include could not find requested file:

    PackConfigurations


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by raysan5** [comment]
The name of the libary is `raylib`, not railib or railiba.

I don't maintain the CMake build system but afaik it works as expected. Feel free to ask in raylib Discord about build configuration.

**Comment by Staxcelrom** [comment]
why then do you write about Cmake in the description for the build under Windows ?

https://github.com/raysan5/raylib/wiki/Working-on-Windows

Raylib already comes with ready-to-use makefiles and **CMake** build system to compile source code, examples and templates. You can download the raylib [Windows Installer](https://github.com/raysan5/raylib/releases).

**Comment by raysan5** [comment]
@Staxcelrom Wiki was open for editing until last week, everyone can edit it. In any case, it does not imply I should maintain that build system.
