### ISSUE TITLE
[texture] LoadTexture call on nonexistent file suceed in empty texture

### ISSUE THREAD

**Issue by locriacyber** [raysan5/raylib#2812]
- [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

When `LoadTexture` tries to load something not there, the error is only displayed stdout/stderr.

### Environment

- Linux

### Issue Screenshot

![a](https://user-images.githubusercontent.com/74560659/204153412-ea6c970e-586f-4214-a5b8-eeccfad2cb90.png)

### Code Example

This is from the official example

```
cd raylib/examples # in this repo
make
textures/textures_bunnymark # run program
```

**Comment by orcmid** [comment]
What do you expect to happen?  

`LoadTexture` returns a `Texture2D`.  If the load fails, the `Texture2D` should be the initialized result `{0}`.

Can you inspect that to determine the texture was not loaded?

**Comment by raysan5** [comment]
Actually, the log output of raylib is the expected behaviour.

**Comment by locriacyber** [comment]
For example, if the games files are corrupted or missing, or the game is launched in incorrect working directory, then some sprites would simply be missing.



> What do you expect to happen?
> 
> `LoadTexture` returns a `Texture2D`. If the load fails, the `Texture2D` should be the initialized result `{0}`.
> 
> Can you inspect that to determine the texture was not loaded?

This worked! Thanks! What's the reliable way to detect this? `mipmaps == 0`, or `id == 0`?
