### ISSUE TITLE
You're an idiot ? You write in C without a namespace...

### ISSUE THREAD

**Issue by Staxcelrom** [raysan5/raylib#2813]
You're an idiot ? You write in C without a namespace... but you didn't even bother to do, for example, how to prefix functions in OpenGL - for example, rayliba__BeginDrawing, rayliba__CloseWindow ... to prevent function name conflicts!
You are a complete degenerate.

**Comment by raysan5** [comment]
@Staxcelrom Thank you very much for your feedback! Really appreciated! 👍🙂

**Comment by Alex-Janssen** [comment]
Kindness makes the world go round :|. I think whoever wrote this is quite clever.
