### ISSUE TITLE
billboards not rendering correctly

### ISSUE THREAD

**Issue by ramAdam** [raysan5/raylib#2823]
![Screenshot from 2022-12-08 12-30-50](https://user-images.githubusercontent.com/4009156/206522879-3e650e2a-a9be-4fda-8c9c-783908d1420c.png)
Transparent areas of billboard fully obscures other billboards.

i tried billboard in FPS example from raylib, transparent regions of the billboard fully hides the cube behind but shows the object behind the cube. 

Any plans to fix that?

**Comment by BugraAlptekinSari** [comment]
I think you need this
https://github.com/raylib-extras/examples-c/tree/main/unsorted_bilboards

**Comment by Zitara** [comment]
Still there for WEB?
