### ISSUE TITLE
Game Demos crashing after title screen

### ISSUE THREAD

**Issue by tazdij** [raysan5/raylib#283]
I don't have much details about the crash, however downloading a snapshot of the repo, placing it in the c:\raylib\raylib directory, then compiling the demo games "Skully Escape" and "Light My Ritual". They compile just fine using MinGW + MSYS. Once running, the raylib animation plays then the splash for the game loads, then it crashes, with no errors or debug output.

any suggestions?

**Comment by raysan5** [comment]
Hi @tazdij, just been working on raylib games some days ago and everything was fine.

Just tested "Skully Escape" and "Light My Ritual" right now and they work. Are you using latest raylib develop branch?

**Comment by tazdij** [comment]
I am using master branch. Maybe it has something to do with the version of
MinGW I am using?

I will do some more fiddling around with it and see if I can get the game
to run past the splash.

Thanks for verifying the demo games have not been left to ruins while the
main library is developed; as so many demos are with many other software
projects.

**Comment by raysan5** [comment]
Just for reference, I used `MinGW32` with `GCC 5.3.0` on Windows 10 Pro, no MSYS, compiled using:
```
mingw32-make PLATFORM=PLATFORM_DESKTOP -B
```
Actually I used Notepad++ provided script: `raylib_makefile`

About "Wave Collector", it is broken but it's a known error, I'm working on it (needs some redesign to also work on web).

 > Thanks for verifying the demo games have not been left to ruins while the
main library is developed; as so many demos are with many other software
projects.

raylib is primary intended for education so I try to care for examples and sample games (completely review for upcoming raylib v1.7). :)

**Comment by tazdij** [comment]
Alright Just checked all of my toolchain and I am running MinGW GCC 4.8.1 and I have tried as follows:

MinGW + MSYS: _(Which I think links in cygwin or something like that, I don't really know)_
`make PLATFORM=PLATFORM_DESKTOP -B`
This creates an exe with zero errors at compile time, however it crashes at the title screen.

MinGW32: _(Run from a windows PowerShell or Command Prompt)_
`mingw32-make PLATFORM=PLATFORM_DESKTOP -B`
Same outcome as MinGW + MSYS

Finally I created a VisualStudio project for the game and added it to the raylib vs2015 solution. This worked. The game compiled and runs. This leads me to believe that the issue is actually in the MinGW GCC 4.8.1 compiler I was using or possibly the stdlibc or libc which is bundled with that version.

When I get a chance to upgrade to GCC 5.3.0 I will try this all again, and see if the game still crashes.

Thank you for your help and the great library.

**Comment by raysan5** [comment]
Thanks for the report! :)

**Comment by tazdij** [comment]
Alright, I think I figured it out.

Looks like static libraries compiled with certain versions of GCC are incompatible with certain other versions og GCC. Since the static library is pre-compiled (I assume with 5.3.0) in the release folder, I had not compiled it with my current version of GCC (4.8.1)

By going to the src directory and running make, recompiling libraylib.a, I was able to get the games to run correctly 

I tested this with both MinGW32 + MSYS & just MinGW32 via mingw32-make and both worked.

**Comment by raysan5** [comment]
Hey @tazdij! Good catch! 

Just note that provided OpenAL Soft static version has also been compiled with GCC 5.3.0.

**Comment by tazdij** [comment]
I really am not trying to drag this conversation on, but would like to respond to the OpenAL comment.

> Just note that provided OpenAL Soft static version has also been compiled with GCC 5.3.0.

This shouldn't matter since OpenAL is dynamically linked. If we were to create a dll/so/dylib version of libraylib.a, the version of GCC used by the developer of either the game or raylib will no longer be as consequential.

Or might I suggest a possible solution? Not to store libraylib.a in the repo, and include it in the Makefiles for the games and examples. Allowing the developer's toolchain to build the static library the first time the developer runs make.
