### ISSUE TITLE
OpenGL Problem

### ISSUE THREAD

**Issue by akdhatAkshat** [raysan5/raylib#2833]
Bruh I have OpenGL 3.2 and the default OpenGL is 3.3.
I installed Raylib using vcpkg method. I cannot change the OpenGL version (I can't find it).
Please tell me how I can change the OpenGL version if I want to install raylib through vcpkg only.

**Comment by raysan5** [comment]
@akdhatAkshat I don't know how vcpkg works but you should rebuild raylib from sources to enable OpenGL 2.1.
