### ISSUE TITLE
Raylib crushes when I increase my code

### ISSUE THREAD

**Issue by NotDragon** [raysan5/raylib#2834]
This is a problem that is hard for me to give info on. In a nutshell though, my program runs fine, until I add more code. Right now if  I add anymore code (even a simple print statement), Raylib crushes without any error message. I am using g++ which also doesn't give me any error massages when I compile my file. Also note that I don't use any pointers, so it can't be a memory leak and I initialize everything
I am using the latest version of Raylib with windows 11.
If it is significant, to compile me code I use the following command:
`g++ ./main.cpp -o ./build/Endure.exe -O2 -Wall -Wextra -g -Wsign-conversion -Weffc++ -Wno-missing-braces -I ./include/ -L ./lib/ -lraylib -lopengl32 -lgdi32 -lwinmm`  IF anyone knows why this is happening please let me know.

**Comment by RobLoach** [comment]
If you add code, and then your application runs slow, it's likely the code you've added that causes the performance issues. What did you write that slowed it down?

**Comment by chriscamacho** [comment]
this could well be heap corruption, in the past I've found c++ memory issues of various types rather vexing, at least with C these things tend to a lot easier to deal with, once you really get to grips with C there's nothing you can't do with it that C++ can do.

While it may well not be a memory leak, this isn't the only memory issue it could be, so its worth running it through valgrind or similar, both at the stage where it works (just) and also doesn't - but again C++ memory issues can be complex to debug...

Just because you're not using pointers doesn't mean that the language itself isn't doing all manner of interesting things with memory once your code is compiled.

especially with C++ I wouldn't turn off any warnings (in fact treat them as errors that need fixing by changing your code)

**Comment by jamesl-github** [comment]
do you have have arrays that are abnormally large ?               
long pixels[1000000][1000000]

**Comment by NotDragon** [comment]
> If you add code, and then your application runs slow, it's likely the code you've added that causes the performance issues. What did you write that slowed it down?



> do you have have arrays that are abnormally large ? long pixels[1000000][1000000]

I do not use any arrays that are  larger then int arr[10][10]

**Comment by NotDragon** [comment]
> If you add code, and then your application runs slow, it's likely the code you've added that causes the performance issues. What did you write that slowed it down?

I don't believe is that, as the game runs stably at 60 fps with no lag spike, because it's so simple. And what ever I add, even if it's a simple operation like x - 1, crushes my program where x works fine

**Comment by NotDragon** [comment]
> this could well be heap corruption, in the past I've found c++ memory issues of various types rather vexing, at least with C these things tend to a lot easier to deal with, once you really get to grips with C there's nothing you can't do with it that C++ can do.
> 
> While it may well not be a memory leak, this isn't the only memory issue it could be, so its worth running it through valgrind or similar, both at the stage where it works (just) and also doesn't - but again C++ memory issues can be complex to debug...
> 
> Just because you're not using pointers doesn't mean that the language itself isn't doing all manner of interesting things with memory once your code is compiled.
> 
> especially with C++ I wouldn't turn off any warnings (in fact treat them as errors that need fixing by changing your code)

I run all the files used in my game using valgrind, but it didn't find any memory leaks. In case it's important the following in the summery of my main file
```
==1992==    definitely lost: 0 bytes in 0 blocks
==1992==    indirectly lost: 0 bytes in 0 blocks
==1992==      possibly lost: 0 bytes in 0 blocks
==1992==    still reachable: 1,164 bytes in 33 blocks
==1992==         suppressed: 0 bytes in 0 blocks
```
It's also worth noting that nothing changed between the version that crushes and the one that works fine

**Comment by raysan5** [comment]
@NotDragon I'm afraid it's imposdible to guess the isdue with the information provided. In any case it does not seem to be an issue related to raylib library but user code. Feel free to ask in raylib Discord servers or open a discussion for it.

**Comment by chriscamacho** [comment]
@NotDragon I wasn't talking about leaks, please read my post properly, as stated you don't provide enough information to actually let people help you. post a minimal example of code that will show this issue in action so people can reproduce it
