### ISSUE TITLE
[core]Texture load failed(-1073741819)

### ISSUE THREAD

**Issue by lucaiyu** [raysan5/raylib#2837]
When I load a texture from image by LoadTextureFromImage, it compiled successfully, but when I run it, it hanged for a short time and exited with error code(-1073741819)
> ====================[ build| all ]================================================
> mingw32-make.exe --jobs=6 all
> gcc src/main.c -c -o build/main.o
> gcc src/player.c -c -o build/player.o
> gcc build/main.o build/player.o build/resman.o -o main.exe -L lib/ -lraylib -lopengl32 -lgdi32 -lwinmm
> main.exe
> make: *** [Makefile:5: all] Error -1073741819
[source repo](https://github.com/lucaiyu/OpenSTG)

**Comment by raysan5** [comment]
@lucaiyu I'm afraid it's can't see the issue in the code, did you try debugging it?
Afaik that raylib function works as expected, just tested one example using it, so, issue could be in user code and not in raylib library.

**Comment by lucaiyu** [comment]
@raysan5 SORRY it's my code's fault.I loaded texture before window init.

**Comment by LievenPetersen** [comment]
Thanks for the hint, It wasn't obvious to me that the window had to be open to do texture operations ;)
