### ISSUE TITLE
DrawTexturePro requires rotation in degrees

### ISSUE THREAD

**Issue by DeexCoding** [raysan5/raylib#2842]
To my knowledge every function takes rotation in as radians and it is a design decision. (One that I absolutely love, because it makes stuff consistent).

However DrawTexturePro expects it to be in degrees and uses DEG2RAD in the function. Should be a pretty easy fix.

**Comment by raysan5** [comment]
All raylib functions take rotations in degrees while raymath functions use radians, that's the fhosen convention for the library.
