### ISSUE TITLE
[camera] Middle mouse based panning not accessible on macos laptops

### ISSUE THREAD

**Issue by nilsbecker** [raysan5/raylib#2843]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When using the `CAMERA_FREE` camera mode, panning and rotation are accessible by pressing the mouse wheel / the middle mouse button. While the modifier key for rotation can be reassigned, this does not appear to be the case for the mouse button to be pressed. On macos, there is no middle mouse button by default. 

I am using a macbook pro laptop with a trackpad. One can use third-party apps such as MiddleClick to generate mouse button 3 events. However, when the middle button is pressed using that method using three fingers, further x/y panning motions are not recognized, or are recognized as the mouse wheel, not the mouse pointer. 

As a result, I cannot pan nor rotate the 3D camera at all. I don't know of a workaround either.

### Environment

macos 12.6.2, macbook pro with touchpad.

### Issue Screenshot

n/a

### Code Example

This can be reproduced just by building and starting the `core_3d_camera_free` example on a macos laptop.

**Comment by raysan5** [comment]
I'm afraid this is a limitation of raylib internal camera, actually that camera system is fully redesigned on #2563

I recommend using a custom camera implementation instead of provided one, here it is a better camera system: https://github.com/JeffM2501/raylibExtras

**Comment by nilsbecker** [comment]
thanks. it may be a good idea to make sure the redesigned camera system gets configurable mouse buttons. i'll check and maybe comment there
