### ISSUE TITLE
[models] Segfault on OBJ model loading

### ISSUE THREAD

**Issue by bl-nero** [raysan5/raylib#2847]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I tried to load [this model](https://www.cgtrader.com/free-3d-models/aircraft/helicopter/cartoon-low-poly-helicopter) and LoadModel consistently segfaults here. First, there's been an assertion triggering that forbids faces with more than 5 sides; when I manually tweaked the model by simplifying the single offending face, it still barfs with a random segfault somewhere higher in the LoadModel function.

Now I would attribute that to my tinkering, but [a different model](https://www.cgtrader.com/free-3d-models/vehicle/other/helicopter-507f7882-f2c3-4660-80b6-d724571cdeec) also results with a segmentation fault, even if it doesn't trigger the assertion.

Unfortunately, it's really hard for me to check what exactly causes it, since when I build a debug version, the segfault doesn't happen, and if I'm trying to just add source information and keep all the optimizations, I find it really hard to attach an lldb in a way that makes it recognize the source code.

To clarify: I'm loading models in an OBJ format. The second model mentioned does not produce an assertion error, but still segfaults (it looks like file parsing goes well, and the code just errors out later).
### Environment

I'm working on MacOS Monterey, version 12.5.1, and the error is reproducible both through Rust bindings, as well as the original models_loading example. My compiler is Apple clang version 12.0.0 (clang-1200.0.32.21). Graphics: Intel Iris Plus Graphics 645 1536 MB. Not sure about the OpenGL version.

### Code Example

The code is taken directly from Raylib's own examples.

**Comment by raysan5** [comment]
@bl-nero did you make sure the model faces are triangulated? Please, could you attach the .obj file you are trying to load and the code to load it?

**Comment by raysan5** [comment]
I'm afraid there is not enough information provided to review this issue.
