### ISSUE TITLE
[rlgl] Expose glsl array texture uniforms

### ISSUE THREAD

**Issue by PencilAmazing** [raysan5/raylib#2848]
Currently there is no way to bind and use `sampler2dArray` uniforms in raylib 4.2. Is there a chance we can at least wrap the necessary functions in rlgl to make them available when using a language bindings like Raylib_cs?

**Comment by raysan5** [comment]
@PencilAmazing Sorry, I try to keep the library as simple as possible, it does not pretend to expose all functionality available by OpenGL. For the moment that feature is out of scope for rlgl.

**Comment by PencilAmazing** [comment]
@raysan5 It would be useful for implementing a GPU based tile map, as in https://blog.paavo.me/gpu-tilemap-rendering/#the-hottest-technology-of-2008-array-textures.
A lot of games developed with raylib are tile based and having this as an option - even if only as a basic API for advanced users - would be nice. I could try making a simple implementation and submit it as a PR.

**Comment by raysan5** [comment]
Sorry, new functions imply review, testing and maintenance. This functionality is out-of-scope for raylib.

**Comment by PencilAmazing** [comment]
@chriscamacho I'm using Raylib_cs on windows, so I'm not exactly sure how to pinvoke OpenGL 3+ functions. I'll give it a try and see what happens.

**Comment by chriscamacho** [comment]
@PencilAmazing ...well cs must have a C FFI (foreign function interface).... a quick leap on to duckduckgo shows this https://stackoverflow.com/questions/11425202/is-it-possible-to-call-a-c-function-from-c-net so if its just a few functions or so, just wrap them manually...
