### ISSUE TITLE
[raycamera] Should `Camera3D.type` also be renamed into `Camera3D.projection`, as it is done in `raylib.h`?

### ISSUE THREAD

**Issue by KOLANICH** [raysan5/raylib#2851]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

In `raylib.h` the field was renamed, in `raycamera.h` it wasn't.

**Comment by raysan5** [comment]
@KOLANICH Renamed that variable, note that rcamera module is being completely redesigned on #2563
