### ISSUE TITLE
[rtext] Support truetype font collections (.ttc)

### ISSUE THREAD

**Issue by rasa-silva** [raysan5/raylib#2854]
### Support loading TTC font files

Since `stb_truetype` supports loading such files, I think the change should be fairly simple... ?

Thank you for this wonderful software! 😉

**Comment by chriscamacho** [comment]
Sounds like you have given yourself an interesting and rewarding challenge - good luck!

**Comment by raysan5** [comment]
@rasa-silva I'm afraid this is not simple. raylib does not provide any mechanism to choose which font to load from a TTC collection, it will imply an API redesign. For the moment this is out of scope for raylib.
