### ISSUE TITLE
[models] M3D import does not load vertex colors correctly

### ISSUE THREAD

**Issue by GithubPrankster** [raysan5/raylib#2855]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Loading any `.m3d` correctly loads all data except vertex colors, which are left blank white instead. The model thus cannot match what was exported by the [official m3d blender exporter](https://gitlab.com/bztsrc/model3d/-/tree/master/blender).

### Environment

Desktop, Windows 10, OpenGL 3.3
```
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 527.56
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
```

### Issue Screenshot

![image](https://user-images.githubusercontent.com/33995085/212225727-d5146353-8145-47e8-871f-908cd887a5b4.png)
*Note the warped texturing is a stylistic choice rather than wrong behavior.*

![image](https://user-images.githubusercontent.com/33995085/212226275-efcc18e9-7e48-407f-b666-1ed885eabb3b.png)
*RenderDoc screenshot showing that all vertex colors are white.*

And original (in Blender 3.4.1):
![image](https://user-images.githubusercontent.com/33995085/212225841-71c98615-3b84-4454-9063-b0bbe413ba7b.png)

```
Color Map Chunk
  Magic:  CMAP
  Length: 32
  Data:   #ff0000c7 #ff00c7c7 #ffffffff #ffc700c7 #ffcccccc #ff7f7f7f
```
Output from the m3d [web validator](https://bztsrc.gitlab.io/model3d/validator/) confirming the colors were indeed stored.

### Code Example

```c
// Note the shader must be using `fragColor` for it to be visible.
Shader shader = LoadShader(0, "shader.fs");
...
Model model = LoadModel("path/to/cube.m3d");
model.materials[1].shader.id = shader.id;
...
DrawModel(model, position, 1.0f, WHITE);
```
Here's the cube itself.
[cube.zip](https://github.com/raysan5/raylib/files/10407749/cube.zip)

**Comment by GithubPrankster** [comment]
After some tinkering around, I managed to fix this by doing the following edits to `rmodels.c`:
At https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L5594-L5601, replace with:
```c
model.meshes[k].colors = RL_CALLOC(model.meshes[k].vertexCount*4, sizeof(unsigned char));
```
At https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L5625, remove this check entirely:
```c
if (mi == M3D_UNDEF)
````

I am confident there is probably a better way to handle what I did just now but it works perfectly with any exported model I throw at it. I'll make a PR once all is settled.

**Comment by raysan5** [comment]
@GithubPrankster Good catch!

@bztsrc could you take a look to this issue?
