### ISSUE TITLE
[core] Screen size origin issues, framebuffer offseted on Y axis from window

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib#2859]
If you create a window with a height that is larger than the available size on them monitor then the origin of the OpenGL context is offset by this difference.

A simple way to duplicate this is the following code (run on a 1080p display)

```
#include "raylib.h"

void main()
{
	InitWindow(2000, 1065, "test");
	SetTargetFPS(144);

	while (!WindowShouldClose())
	{
		Vector2 mousePos = GetMousePosition();

		BeginDrawing();
		ClearBackground(DARKGRAY);

		DrawRectangle(200, 0, 100, 5, RED);
		DrawRectangle(200, 5, 100, 5, BLUE);
		DrawFPS(0, 0);

		EndDrawing();
	}
	CloseWindow();
}
```
![image](https://user-images.githubusercontent.com/322174/212523940-d628cc1f-3170-42e3-8565-7e29de7f1215.png)

You can see  that the FPS counter is cut in half and the RED bar is not visible.

I'm not sure what is going on, but should raylib be even creating a window that is larger that the monitor?

This has been duplicated in windows Visual Studio 2022 with C.

I do not think this is a major issue, mostly I just wanted to get the steps for reproduction stored in an issue.

**Comment by ImazighenGhost** [comment]
Seems to work fine for me, what platform are you in?

![window bug](https://user-images.githubusercontent.com/122651011/212539404-cdb6978e-9728-4225-8576-ebb4c0691227.gif)

**Comment by JeffM2501** [comment]
This has happened on multiple Windows installs. I do believe it will be OS specific, possibly GLFW related.

**Comment by JeffM2501** [comment]
Also of note, I don't think it's driver related, as one report is on an intel chipset and I can duplicate it on an nvidia card.

**Comment by raysan5** [comment]
@JeffM2501 Wow! What an issue! Really weird... I tried with `1065` and it worked ok for me but I could reproduce it using `1080`.

It seems related to OS and the way window is created... it seems the framebuffer is offseted to fit in the window to fit in the display... quite weird behaviour...

**Comment by JeffM2501** [comment]
Yes it's very strange. I think the 1065 is due to the taskbar on windows (windows 11).
It may be a GLFW bug too and there is nothing we can do about it, I just don't know enough about how raylib creates the context to dig deeper.

Note that this is not blocking anything or causing any real problems. The one bit of code that had this issue (RPG example ) now has code to prevent creating a window that is too big.

**Comment by raysan5** [comment]
> I just don't know enough about how raylib creates the context to dig deeper.

Actually most of that work is not related to raylib but GLFW and the driver. raylib just calls `glfwCreateWindow()` with the framebuffer size to request it and afaik, no `glfwWindowHint()` has an influence on the window, only on the OpenGL capabilities.

**Comment by raysan5** [comment]
Just reviewed it again, actually some `glfwWindowHint()` have an influence on the window (borderless, top-most, mouse pass-through...) but I can't see anything related to the issue.

**Comment by raysan5** [comment]
@JeffM2501 I debugged this issue and it took me to the Win32 system call [`AdjustWindowRectEx()`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-adjustwindowrectex), from `User32.lib` Windows system library. The returned rectangle computes negative top-left corner values for provided inputs.

Call stack:
```c
InitWindow(int width, int height, const char * title)
    InitGraphicsDevice(int width, int height)
         glfwCreateWindow(int width, int height, const char * title, GLFWmonitor * monitor, GLFWwindow * share)
              _glfwCreateWindowWin32(_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
                   createNativeWindow(_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWfbconfig * fbconfig)
                       AdjustWindowRectEx(&rect, style, FALSE, exStyle);
```

I'm afraid this issue is out-of-scope of raylib, probably even out-of-scope for GLFW. I'm closing it.

Feel free to reopen it if required.
