### ISSUE TITLE
【Display without monitor】Run visualization program base raylib in docker.

### ISSUE THREAD

**Issue by Fin-Del-Mundo** [raysan5/raylib#2861]
I develop the visualization program base raylib and deploy it in armlinux(Xavier). Xavier is not connected to a monitor, so i use vnc viewer to show visual window. But when i run the program in docker, it reported a bug "GLFW not found the primary monitor". Unless i connected Xavier to a monitor, the visualization program can run seccess. Please give me solution that how to run raylib program without a monitor.

**Comment by Fin-Del-Mundo** [comment]
![image](https://user-images.githubusercontent.com/38023261/212639586-0f57131d-ea1a-4262-92bb-b07b1ca4ec09.png)

**Comment by raysan5** [comment]
raylib requires a GPU supporting OpenGL and afaik a display output connected to that GPU, so, I'm afraid it's not possible to use raylib without a display.
