### ISSUE TITLE
[rmodel] IQM Animations do not load joint names

### ISSUE THREAD

**Issue by PencilAmazing** [raysan5/raylib#2863]
### Issue description

I'm trying to search for bone transforms using bone name, but `LoadModelAnimationsIQM` discards joint names for some reason and just writes `"ANIMJOINTNAME"` to `BoneInfo.name`

### Code Example
https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L4504

**Comment by raysan5** [comment]
@PencilAmazing Does IQM provide joint names data? In any case, `BoneInfo.name` is only 32 bytes, I tried to keep the object small. Afaik in most situations bone names are not that useful and they can be better accessed by index.

**Comment by PencilAmazing** [comment]
My use case was to load custom models and allow the user to specify a bone by name then attach a model to it's transform. I could force the user to memorize a magic index number for the model and hope the bone order never changes, but the inbuilt raylib structure field is simply being left unused for no real reason.
And yes, my IQM file does have joint names data and already is being loaded for skeletal models. I would imagine that 32 bytes is enough for most bone names.

**Comment by raysan5** [comment]
@PencilAmazing ok, could you send a PR to fill name data?
