### ISSUE TITLE
[models] `LoadMaterials` not returning any materials

### ISSUE THREAD

**Issue by Anut-py** [raysan5/raylib#2869]
- [x] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

In the source code for `LoadMaterials`, `*materials` is set to `NULL`. There is also a TODO comment saying "TODO: Process materials to return". `LoadModel` properly loads materials from `.mtl` files, so I'm fairly sure that `LoadMaterials` was just overlooked. 

### Environment

Windows 11, OpenGL 3.3, AMD Radeon Graphics

### Code Example

```c
int num = 0;
Material* materials = LoadMaterials("./assets/Model.mtl", &num); // Model.mtl and Model.obj load properly with `LoadModel`

printf("Number of materials: %d\n", num); // Output: 3
printf("Materials pointer: %d\n", materials); // Output: 0
printf("First material param: %f\n", materials[0].params[0]); // Fails
```

**Comment by JeffM2501** [comment]
I have made a PR that fixes this (PR#2872), but I can also see reason to remove the function since it hasn't worked, thus nobody would be using it.

**Comment by raysan5** [comment]
@JeffM2501 I left that function there for the future in case some specific material file-format got popular, unfortunately, beside the old .mtl it seems no material file-formats are popular... not sure how useful is this function but thank you very much for the implementation.

**Comment by JeffM2501** [comment]
Yeah I had a feeling it was not super useful, we may want to just remove the function then.

**Comment by raysan5** [comment]
@JeffM2501 I think we can keep it for 4.5.
