### ISSUE TITLE
[raymath] Adding a new Vector2MultiplyValue function.

### ISSUE THREAD

**Issue by cos1110** [raysan5/raylib#2879]
This one is missing and I as I had to use it recently, I think that is a good idea to be included for consistency.
```
// Multiply vector and float value
RMAPI Vector2 Vector2MultiplyValue(Vector2 v, float mult) {
	Vector2 result = {v.x * mult, v.y * mult};
	return result;
}
```

**Comment by raysan5** [comment]
@cos1110 It already exists, it is named `Vector2Scale()`

**Comment by cos1110** [comment]
OK, it seems then that this issue is completed. Thanks.
