### ISSUE TITLE
[rcore] Graphic Artifacts with Camera2D

### ISSUE THREAD

**Issue by JupiterRider** [raysan5/raylib#2885]
Using these Camera2D settings `rl.Camera2D{Offset: rl.Vector2{X: 62, Y: 185}, Target: rl.Vector2{X: 15.5, Y: 46.25}, Zoom: 7}` results in:
![](https://i.imgur.com/LSufRak.png)

But using these doesn't `rl.Camera2D{Offset: rl.Vector2{X: 62, Y: 185}, Target: rl.Vector2{X: 15.55, Y: 46.25}, Zoom: 7}`:
![](https://i.imgur.com/ohnyTX1.png)

Here is the image (tile.png) I use: ![](https://i.imgur.com/Zq3XGFy.png)

An this is the Code written in go:
```golang
package main

import (
	rl "github.com/gen2brain/raylib-go/raylib"
)

const (
	cellSize  = 16
	mapHeight = 10
	mapWidth  = 10
)

func main() {
	rl.InitWindow(1280, 720, "My Game")
	defer rl.CloseWindow()

	texture := rl.LoadTexture("tile.png")
	defer rl.UnloadTexture(texture)

	cam := rl.Camera2D{Offset: rl.Vector2{X: 62, Y: 185}, Target: rl.Vector2{X: 15.5, Y: 46.25}, Zoom: 7}

	for !rl.WindowShouldClose() {

		rl.BeginDrawing()
		rl.ClearBackground(rl.White)
		rl.BeginMode2D(cam)

		for y := 0; y < mapHeight; y++ {
			for x := 0; x < mapWidth; x++ {
				var position rl.Vector2
				position.X = float32(x*cellSize/2 - y*cellSize/2)
				position.Y = float32(x*cellSize/4 + y*cellSize/4)
				rl.DrawTextureV(texture, position, rl.White)
			}
		}

		rl.EndMode2D()
		rl.EndDrawing()
	}
}

```

Background: My approach is to draw an isometric 2D map. I made the tile red and the background white, so you can see the "issue" better.
The camera will be controlled by the mouse, but I removed that part to make the code more clear.

**Comment by raysan5** [comment]
@JupiterRider I think this issue could be GPU/driver dependant or related to rounding issues on the drawing. I recommend:

 - Round to absolute values the float position
 - Change scaling filter for the texture to use point filter (use `SetTextureFilter()`)

If problem is not solved with those two options, I'm afraid it could be out the control of raylib.

**Comment by JupiterRider** [comment]
Thanks for your reply! I could get around this, avoiding odd numbers in the Camera2D zoom.
