### ISSUE TITLE
[raymath] `Vector2Angle()` gives unexpected results

### ISSUE THREAD

**Issue by Kabcorp** [raysan5/raylib#2887]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Vector2Angle() gives unexpected results.

### Environment

Windows 10 x86_64
Last RayMath

### Issue Screenshot

Here I represent angles in degrees for Vector2Angle() and a "fixed" version of it.
Red is the last Vector2Angle()
Blue is the fixed one
![vector2angle](https://user-images.githubusercontent.com/33150965/214544880-7f742e26-55c7-4b21-a029-2f4f7ba156ee.gif)

```c
#include <raylib.h>
#include <raymath.h>

float Vector2Angle_fixed(Vector2 v1, Vector2 v2)
{
  float result = atan2f(v2.y - v1.y, v2.x - v1.x);
  return result;
}

int main(void)
{
  InitWindow(256, 256, "Vector2Angle Issue");
  SetTargetFPS(60);
  
  while (!WindowShouldClose())
  {
    BeginDrawing();
    ClearBackground(BLACK);
    
    Vector2 Start={(int)(GetRenderWidth()/2),(int)(GetRenderHeight()/2)};
    Vector2 End={GetMouseX(),GetMouseY()};
    
    DrawLine(
      Start.x,
      Start.y,
      Start.x+(cosf(Vector2Angle(Start, End))*Vector2Distance(Start, End)),
      Start.y+(sinf(Vector2Angle(Start, End))*Vector2Distance(Start, End)),
      RED);
      
    DrawLine(
      Start.x,
      Start.y,
      Start.x+(cosf(Vector2Angle_fixed(Start, End))*Vector2Distance(Start, End)),
      Start.y+(sinf(Vector2Angle_fixed(Start, End))*Vector2Distance(Start, End)),
      BLUE);
      
    DrawText(TextFormat("Normal:%.01f°", Vector2Angle(Start, End)*RAD2DEG),       0,  0, 20, WHITE);
    DrawText(TextFormat("Fixed:%.01f°",   Vector2Angle_fixed(Start, End)*RAD2DEG), 0, 20, 20, WHITE);
    
    EndDrawing();
  }
  
  CloseWindow();
  return 0;
}
```

**Comment by chriscamacho** [comment]
off the top of my head, shouldn't it be a unit vector ?

**Comment by raysan5** [comment]
@Kabcorp Actually `Vector2Angle()` has been reviewed twice in the last months, in #2829 and #2832...

Sincerely, I don't know right now which one is the right approach to expected functionality... I should review it more carefully but your visual example is the most convincing expected result.

**Comment by JupiterRider** [comment]
@raysan5 Why not doing it like libGDX does:
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Vector2.java#L348

I think its nice to stick to convention and how other frameworks do it

**Comment by Kabcorp** [comment]
The function Vector2Angle_fixed() in the code is pretty fast and generic
And it results -180° to +180°

**Comment by raysan5** [comment]
@veins1 why `Vector2Angle()` assumes normalized vectors?

 > Some people assume this function gets the angle between two points in space represented by vectors.

I understand this function that way, I think this is the most intuitive understanding for most users.

**Comment by raysan5** [comment]
@veins1 Thinking about the most common use-cases for this function, I think using just `atan2f()` is probably the simplest approach and most users will be fine with it...

But, in what cases the direction approach is more useful? What is the approach on other gamedev math libraries?

**Comment by raysan5** [comment]
Asking in raylib Discord, it seems this function functionality could be missunderstood, two possible understandings:

 1. Get angle between two vectors 
 2. Compute the vector between two points, and then get the angle of that vector

My intention for the function was 1st approach, similar to Unity function [Vector2.Angle](https://docs.unity3d.com/ScriptReference/Vector2.Angle.html), I think it's the easier for most unexperienced users

In any case, a second function can be added: `Vector2LineAngle(Vector2 start, Vector2 end)`

**Comment by JeffM2501** [comment]
Vector2Angle gives you the angle between two vectors. It does not compute a vector between two points and compute the absolute angle of that new vector.

Vector2Angle is not broken, it just doesn't do what you expect.
It is not Vector TO angle, it is the angle between two vector2s.

The 'fixed' function is more like AngleOfLine and it takes a start point and and end point, not two vectors. Note that the arguments Vector2Angle are vectors, not points, yet in your code you call them start and end, clearly points, not vectors. While the data structure may be the same, the sense of the data stored in them is VERY different.

This is not a bug, simply a missunderstanding of what the function is meant to do. Changing it would break many things and remove the ability to find the angle between to vectors, used to know how far to turn to face a target.

You can use it to get the absolute angle of a vector, by simply computing a vector from your points and using a fixed 'zero' axis.

```
Vector2 delta = Vector2Subtract(End, Start);
float angle = Vector2Angle(delta, (Vector2){1,0});
```

**Comment by Kabcorp** [comment]
Ok thank you for the explanations it was confusing me because of the name "Vector2Angle"

**Comment by raysan5** [comment]
Reopened for verification.

**Comment by zlate42** [comment]
The implementation of Vector2Angle is wrong. The function Vector2Angle calculates the angle of the differential vector and not between the two vectors.
Look at https://stackoverflow.com/questions/21483999/using-atan2-to-find-angle-between-two-vectors

The correct way to calculate the angle between two vectors would be:
float result = atan2f(v2.y, v2.x) - atanf2(v1.y, v1.x);

**Comment by raysan5** [comment]
Reviewed.
