### ISSUE TITLE
[rshapes] Feature Request: Expose showCapLines in DrawCircleSectorLines

### ISSUE THREAD

**Issue by BerkUnver** [raysan5/raylib#2890]
In the source for DrawCircleSectorLines, there is a variable showCapLines that is always set to true that I believe controls whether the lines on the inside of the circle get drawn. It would be nice if this could get exposed to the end user (possibly as part of a separate function to prevent the api from breaking?)

**Comment by raysan5** [comment]
@BerkUnver I have my doubts about this feature, it requires a new function, with **7 input parameters** to support a specific use case of the function. I would recommend just copying the related function into user code and modify it.
