### ISSUE TITLE
[models] Segfault loading gltf from Godot

### ISSUE THREAD

**Issue by suncore** [raysan5/raylib#2906]
---

Please, before submitting a new issue verify and check:

 - [ x] I tested it on latest raylib version from master branch
 - [ x] I checked there is no similar issue already reported
 - [ x] My code has no errors or misuse of raylib

### Issue description

I built the latest raylib. Then I ran 

raylib/examples/models$ ./models_loading_gltf 

and it worked ok. Then I replaced robot.glb with a gltf I exported from Godot and I got a segfault:

raylib/examples/models$ ./models_loading_gltf 
INFO: Initializing raylib 4.5-dev
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 3440 x 1369
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 216
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Mesa/X.org
INFO:     > Renderer: llvmpipe (LLVM 15.0.2, 256 bits)
INFO:     > Version:  4.5 (Core Profile) Mesa 22.2.5
INFO:     > GLSL:     4.50
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: FILEIO: [resources/models/gltf/robot.glb] File loaded successfully
INFO: MODEL: [resources/models/gltf/robot.glb] Model basic data (glTF) loaded successfully
INFO:     > Meshes count: 1
INFO:     > Materials count: 1 (+1 default)
INFO: MODEL: [resources/models/gltf/robot.glb] Failed to load mesh/material buffers
Segmentation fault (core dumped)

The model is called ship.gltf and is available here: https://drive.google.com/drive/folders/1YaZDWm_5ZVnaf78jPEhaDrI76ZazCMLL?usp=sharing

The model is a text gltf and I am not sure text gltfs are supported in raylib but there is no mention it isn't so I thought I would bring this up.

### Environment

Linux X11, kubuntu 22.10.

### Issue Screenshot

-

### Code Example

Used one of the examples.

**Comment by raysan5** [comment]
@suncore Please, could you attach `ship.gltf` file for review? I can't access Google drive for security reasons.

**Comment by suncore** [comment]
Sure, attached file here. Thanks.
[ship.gltf.gz](https://github.com/raysan5/raylib/files/10609396/ship.gltf.gz)

**Comment by raysan5** [comment]
@suncore It seems the model you shared does not contain any vertex data, did you try opening it with some other 3d viewer?

**Comment by suncore** [comment]
No I have not tried that. I thought there was a bug in raylib since it segfaulted but I guess there is a bug in Godot...

**Comment by raysan5** [comment]
@suncore I'm afraid it could be the case...

**Comment by suncore** [comment]
Yes. It definitely seems Godot needs a bug report. I tested it at https://gltf-viewer.donmccurdy.com/ and got this validation report:

<html>
<body>
<h1 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Validation report</h1><ul style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li><b>Format:</b><span> </span>glTF 2.0</li><li><b>Generator:</b><span> </span>Godot Engine v4.0.beta14.official@28a24639c3c6a95b5b9828f5f02bf0dc2f5ce54b</li><li><b>Stats:</b><ul><li>1 draw calls</li><li>0 animations</li><li>1 materials</li><li>198 vertices</li><li>66 triangles</li></ul></li><li><b>Extensions:</b><span> </span>None</li></ul><hr style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Report generated by<span> </span><a href="https://github.com/KhronosGroup/glTF-Validator/">KhronosGroup/glTF-Validator</a><span> </span>2.0.0-dev.3.9.</p>

Error | Message | Pointer
-- | -- | --
IO_ERROR | Node Exception: TypeError: Failed to fetch | /buffers/0/uri


</body>
</html>Validation report
Format: glTF 2.0
Generator: Godot Engine v4.0.beta14.official@28a24639c3c6a95b5b9828f5f02bf0dc2f5ce54b
Stats:
1 draw calls
0 animations
1 materials
198 vertices
66 triangles
Extensions: None
Report generated by [KhronosGroup/glTF-Validator](https://github.com/KhronosGroup/glTF-Validator/) 2.0.0-dev.3.9.

Error	Message	Pointer
IO_ERROR	Node Exception: TypeError: Failed to fetch	/buffers/0/uri
Hint	Message	Pointer
BUFFER_VIEW_TARGET_MISSING	bufferView.target should be set for vertex or index data.	/meshes/0/primitives/0/attributes/NORMAL
BUFFER_VIEW_TARGET_MISSING	bufferView.target should be set for vertex or index data.	/meshes/0/primitives/0/attributes/POSITION
BUFFER_VIEW_TARGET_MISSING	bufferView.target should be set for vertex or index data.	/meshes/0/primitives/0/attributes/TANGENT
BUFFER_VIEW_TARGET_MISSING	bufferView.target should be set for vertex or index data.	/meshes/0/primitives/0/attributes/TEXCOORD_0
BUFFER_VIEW_TARGET_MISSING	bufferView.target should be set for vertex or index data.	/meshes/0/primitives/0/indices
Info	Message	Pointer
UNUSED_MESH_TANGENT	Tangents are not used because the material has no normal texture.	/meshes/0/primitives/0/attributes/TANGENT
UNUSED_OBJECT	This object may be unused.	/meshes/0/primitives/0/attributes/TEXCOORD_0
