### ISSUE TITLE
[rmodels] DrawMesh uses SHADER_LOC_COLOR_SPECULAR as a material map index

### ISSUE THREAD

**Issue by haved** [raysan5/raylib#2908]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

In `rmodels.c`, the `DrawMesh` function tries to upload the material's specular color, if the shader has a uniform in `shader.locs[SHADER_LOC_COLOR_SPECULAR]`. The problem is that the material map should be `material.maps[MATERIAL_MAP_SPECULAR]`, but `maps[SHADER_LOC_COLOR_SPECULAR]` is used instead, which isn't a real material map.

See the source code in question here:

https://github.com/raysan5/raylib/blob/589892af07e8ee7392f9ab7b8c9bb0f8263c4e48/src/rmodels.c#L1373-L1383

### Environment

Linux, OpenGL 3.3. The code in question is within
```c
#if defined(GRAPHICS_API_OPENGL_33) || defined(GRAPHICS_API_OPENGL_ES2)
```

### Issue Screenshot

I got random specular colors every time I ran my program, but didn't take screenshots

### Code Example

```c
Shader shader = LoadShader("res/model.vs", "res/model.fs");
shader.locs[SHADER_LOC_COLOR_SPECULAR] = GetShaderLocation(shader, "colSpecular");

Model model = LoadModel("res/model.glb");
model.materials[0].shader = shader;

// This line ends up doing nothing
model.materials[0].maps[MATERIAL_MAP_SPECULAR].color = {200, 200, 200};

// Within gameloop
DrawModel(model, {0, 0, 0}, 1.0f, WHITE);
```

**Comment by raysan5** [comment]
@haved Good catch! Thanks for the fix!
