### ISSUE TITLE
[raymath] VectorTransform implementation review

### ISSUE THREAD

**Issue by bugcaptor** [raysan5/raylib#291]
Transpose is required as written in the comment.
`v->x = mat.m0*x + mat.m1*y + mat.m2*z + mat.m3;`
`v->y = mat.m4*x + mat.m5*y + mat.m6*z + mat.m7;`
`v->z = mat.m8*x + mat.m9*y + mat.m10*z + mat.m11;`

**Comment by raysan5** [comment]
When implementing this function I had my doubts... Please, could you explain why it needs to be transposed? Have you used it independently from raylib? I'd like to understand it better...

Note that raylib Matrix implementation is:
```c
    // Matrix type (OpenGL style 4x4 - right handed, column major)
    typedef struct Matrix {
        float m0, m4, m8, m12;
        float m1, m5, m9, m13;
        float m2, m6, m10, m14;
        float m3, m7, m11, m15;
    } Matrix;
```

**Comment by bugcaptor** [comment]
As far as I know, multiplying the column major martix by a vector means multiplying each column vector. The first column vector of the opengl matrix is ​​m0, m1, m2, m3 of the raylib matrix. On the other hand, m3, m7, and m11 are translation components, so this implementation must be correct.

**Comment by raysan5** [comment]
Could I close this issue?

**Comment by bugcaptor** [comment]
I did not understand when I was looking at a single function but I took the time to see the whole code and understood. The use of matrices seems to be a mixture of the concept of column major and the concept of row major. In particular, multiplying a matrix by left to right is done when it is a row major matrix.

Somehow the result matrix is coming out, but if you correct some of the code properly with the concept of column major, you can reduce unnecessary matrix transpose calculations. The MatrixMultiply function needs to change the direction of multiplication, and it needs to swap the arguments left and right in the code that uses them. And the VectorTransform will also be the matrix related transpositions in rlgl.c.

The following link may help. http://www.mindcontrol.org/~hplus/graphics/matrix-layout.html

If I'm wrong, let me know.

And I am worried that the nuances are not inappropriate. My English skills are not a big problem to understand and understand sentences, but it seems that I can not control the nuances of writing. I have been helped by a recently improved Google Translator. ;)

**Comment by raysan5** [comment]
Hi @bugcaptor, I need to review this issue... It was done that way because memory alignment of Matrix struct: despite being defined as 'column major' convention, in memory it aligns as row major: 
```
m0, m4, m8, m12, m1, m5, m9, m13, m2, m6, m10, m14, m3, m7, m11, m15;
```
Probably it should be changed for consistency but it will require some changes all around the code...

**Comment by raysan5** [comment]
raymath (and consequently raylib math) has been completely reviewed for consistency. Now MatrixTranslate() generates the expected matrix and VectorTransform works as expected.

raymath is consistent with OpenGL matrix  math.
