### ISSUE TITLE
when use the raylib combine with the imgui, how can the imgui hook the raylibs mouse and key action?

### ISSUE THREAD

**Issue by aliule2020** [raysan5/raylib#2917]
when use the raylib combine with the imgui, how can the imgui hook the raylibs mouse and key action?
I not want the raylib to make action when i click the imgui item(for example, a imgui button), or say I want the imgui to hook the raylib action event, how should I do?

**Comment by raysan5** [comment]
@aliule2020 you can check this integration example: https://github.com/raylib-extras/rlImGui
