### ISSUE TITLE
Maybe I found a bug, when I use the raylib with the imgui.

### ISSUE THREAD

**Issue by aliule2020** [raysan5/raylib#2918]
please look at my code:

#include "raylib.h"
#include "raylib-cpp.hpp"

#include "imgui.h"
#include "rlImGui.h"

#include <iostream>
using namespace std;

class MainWin
{
 public:
     raylib::Window *w;
     int appstate;  //程序状态
     bool btn123active = true;

     MainWin(raylib::Window *ww)
     {
         w = ww;
     }
     void mainDraw()
     {
         BeginDrawing();
         w->ClearBackground(RAYWHITE);

         DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);
         DrawLineEx(Vector2{ 0,0 }, Vector2{ 500,500 }, 5, BLUE);

         if (mainGUI() == 0)
         {
             mainInput();
         }
         EndDrawing();
     }

private:
    void mainInput()
    {
        **//bug is here, when I use IsMouseButtonPressed than IsMouseButtonReleased, 
        //you will get both output "raylib_clc"  and "im_click" at the same time, besides raylib lacks a 
        // a api funtion to clear the state of mouse.**
        if (IsMouseButtonReleased (MOUSE_BUTTON_LEFT))  
        {
            cout << "raylib_clc" << endl;
        }
        
    }
     int mainGUI()
     {
         int MC = 0;  //to know if the imgui item actioned, 0 means nothing happened

         // start ImGui Conent
         rlImGuiBegin();

         ImGui::BeginMainMenuBar();
         ImGui::SetWindowFontScale(3);

         if (ImGui::BeginMenu("File"))
         {
             MC = 1;
             if (ImGui::MenuItem("Open..", "Ctrl+O")) { MC = 1;/* Do stuff */ }
             if (ImGui::MenuItem("Save", "Ctrl+S")) { MC = 1;/* Do stuff */ }
             if (ImGui::MenuItem("Close", "Ctrl+W")) { MC = 1;  }
             ImGui::EndMenu();
         }
         ImGui::EndMainMenuBar();

         if (ImGui::Begin("run", 0, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoResize))
         {
             ImGui::SetWindowPos("run", ImVec2{ 0,50 });
             ImGui::SetWindowFontScale(3);

             if (ImGui::Button("123", ImVec2{ 100,100 }))
             {
                 
                 cout << "im_click" << endl;
                 MC = 1;
             }

             ImGui::SameLine();
             ImGui::Button("456", ImVec2{ 100,100 });

             ImGui::End();
         }

         // end ImGui Content
         rlImGuiEnd();
         return MC;
     }
};

int main() {
    int screenWidth = 1800;
    int screenHeight =1000;

    raylib::Window w(screenWidth, screenHeight, "raylib-cpp - basic window");

    MainWin win(&w);

    w.SetTargetFPS(60);

    rlImGuiSetup(false);

    while (!w.ShouldClose())
    {
        win.mainDraw();
    }

    rlImGuiShutdown();

    return 0;
}

**Comment by raysan5** [comment]
Please, for this kind of questions I recommend you access the raylib Discord, there is a specific channel for questions. Issues is intended for tested and well documented issues and not "please look at my code" issues. Actually there is an `Issue Template` that should be read carefully.
