### ISSUE TITLE
Segfault when trying to run on Ubuntu Linux 16.04.1 LTS

### ISSUE THREAD

**Issue by define-private-public** [raysan5/raylib#292]
Hi.  I found RayLib and I think it's kind of neat.  I'm looking to write some Nim bindings for it, but first I want to be able to get the library running.  I built it using the commands provided on the wiki (shared library), then built the examples.

First off, for some reason, the executable weren't able to find `libraylib.so`, even though it was installed to the correct path.  I did an `export LD_LIBRARY_PATH=release/linux` to fix it.  Then I was able to start the examples without any linking issues.  but then I would get this:

```
ben@hostname:core$ ./core_2d_camera 
INFO: Initializing raylib (v1.7.0)
Segmentation fault (core dumped)
```

That's unfortunately not the best error message.  Is there anything I can fix this?

**Comment by define-private-public** [comment]
I did a little `printf()` debugging and it seems to be segfaulting at the `InitWindow()` call.

**Comment by raysan5** [comment]
Could you try building the static version?

What GPU are you using? Does it support OpenGL 3.3?

If OpenGL 3.3 is not supported you can compile the library to use OpenGL 1.1:
```
make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_11
```

**Comment by define-private-public** [comment]
I'm using a Radeon 7870 HD.  Here's what `glxinfo` reports:

```
ben@hostname:~$ glxinfo | grep OpenGL
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 7800 Series
OpenGL core profile version string: 4.5.13474 Core Profile Context 17.10.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.13474 Compatibility Profile Context 17.10.2
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: 4.5.13474 Compatibility Profile Context 17.10.2
OpenGL ES profile shading language version string: 4.50
OpenGL ES profile extensions:
```

I'll try the static method and report back what happens.

**Comment by define-private-public** [comment]
Static library also yielded the same results.  I tried running it through `gdb`, the segfault reported that something is happening at the AMD library level:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff07f78f4 in amdgpu_query_gpu_info ()
   from /opt/amdgpu-pro/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1
```

I'll try with OpenGL 1.1 next.

**Comment by raysan5** [comment]
It seems an issue related to GLFW3, are you using latest version?

https://github.com/wjakob/glfw/pull/1
https://github.com/glfw/glfw/issues/835

**Comment by define-private-public** [comment]
I used glfw 3.2 which was linked in the Wiki.  I'll go and try 3.2.1

**Comment by define-private-public** [comment]
GLFW 3.2.1 works.  It might be best to go and update the Wiki to use that instead of 3.2/

**Comment by raysan5** [comment]
Great! Thanks for the feedback! Just updated Wiki! :)

By the way, Wiki is open, everybody can edit it. ;)
