### ISSUE TITLE
[raudio/feature request] Audio stream processor for mixed output

### ISSUE THREAD

**Issue by hatkidchan** [raysan5/raylib#2928]
We already have 3 functions related to processing/generating sound programmatically:
```c
void SetAudioStreamCallback(AudioStream stream, AudioCallback callback);
void AttachAudioStreamProcessor(AudioStream stream, AudioCallback processor);
void DetachAudioStreamProcessor(AudioStream stream, AudioCallback processor);
```
but they work on separate audio streams, not the mixed audio that is being sent to underlying miniaudio library. It would be nice to have same functionality available for all sounds as a last step before sending samples to the sound hardware.

I see it as 2 functions that accept another function as a callback just before sending samples:
```c
void AttachAudioMixerProcessor(AudioCallback processor);
void DetachAudioMixerProcessor(AudioCallback processor);
```
that should work the same way as already existing functions, but instead of taking separate stream as their argument, they read/modify mixed output.

Use cases:
 * Global sound effects (such as lowering the volume when window is out of focus, low-pass filters, etc);
 * Visualization of sound being played (can be useful when creating applications/games that are heavily sound-bound)
 * Beat detection
 * Volume normalization
 * [ list goes on ]

---

Looking at the source of `OnSendAudioDataToDevice` it should be pretty trivial to implement, maybe right after `MixAudioFrames` call we could do the same as with each buffer?

I could try doing that, but I'm not sure if that addition would be welcome in the library

**Comment by hatkidchan** [comment]
Ooookay, deeply nested loop/conditional mess confused me and it appears that we call `MixAudioFrames` after processing each buffer, so calling it after that wouldn't really help.

Though, we could call it after all of those loops maybe...

**Comment by hatkidchan** [comment]
This seems to work, but far from ideal:

https://github.com/hatkidchan/raylib-patches/commit/085b59f8784b4a2ba8dc4f867081d4372b1130f3

Right now it appears to skip some frames, which causes sound to be choppy on writes.

But it seems work good enough for visualizations:
<details>
<summary>raudiotest.c</summary>

```c
// x-run: ~/scripts/runc.sh % libraylib.a -lm
#include "raylib.h"
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>

void audio_callback(float *_buf, unsigned int frames);

#define BUFFER_SIZE 2048

float audio_buffer[BUFFER_SIZE];
size_t buf_offset = 0;

const char *audio_path = "/mnt/windows/Users/user/Music/oscilloscope/Jerobeam Fenderson - Shrooms [19jv0HM92kw].mp3";

int main(void) {
  InitWindow(512, 512, "");
  InitAudioDevice();
  AttachAudioMixedProcessor((AudioCallback)audio_callback);
  SetTargetFPS(60);

  Music stream = LoadMusicStream(audio_path);
  PlayMusicStream(stream);

  ClearBackground(BLACK);
  while (!WindowShouldClose()) {
    UpdateMusicStream(stream);
    BeginDrawing();
    BeginBlendMode(BLEND_ALPHA);
    DrawRectangle(0, 0, 512, 512, Fade(BLACK, GetFrameTime() * 10.0));
    EndBlendMode();
    BeginBlendMode(BLEND_ADDITIVE);

    Vector2 oscilloscope[2][BUFFER_SIZE / 2];
    for (int i = 0; i < BUFFER_SIZE / 2; i++) {
      float left = audio_buffer[i * 2 + 0], right = audio_buffer[i * 2 + 1];
      Vector2 point = { 256 + left * 256, 256 - right * 256 };
      DrawPixelV(point, Fade(GREEN, 0.5));
      oscilloscope[0][i].x = i * 2.0;
      oscilloscope[0][i].y = 128 - left * 128;
      oscilloscope[1][i].x = i * 2.0;
      oscilloscope[1][i].y = 512 - 128 - right * 128;
    }
    DrawLineStrip(oscilloscope[0], BUFFER_SIZE / 2, Fade(BLUE, 0.1));
    DrawLineStrip(oscilloscope[1], BUFFER_SIZE / 2, Fade(RED, 0.1));
    EndBlendMode();
    EndDrawing();
  }
}

void audio_callback(float *_buf, unsigned int frames) {
  ssize_t can_write = BUFFER_SIZE - buf_offset;
  for (int i = 0; i < frames; i++) {
    _buf[i] *= 0.25;
  }
  if (frames > can_write) {
    memcpy(&audio_buffer[buf_offset], _buf, can_write * sizeof(float));
    memcpy(&audio_buffer[0], _buf + frames - can_write, frames - can_write);
    buf_offset = frames - can_write;
  } else {
    memcpy(&audio_buffer[buf_offset], _buf, frames * sizeof(float));
    buf_offset += frames;
  }
}
```
</details>

**Comment by hatkidchan** [comment]
Oh actually, my bad! It works as it should! I just missed the fact that we're in stereo world and number of samples is number of frames times two!

So it all works, I just have to clean things up a little, maybe..

**Comment by raysan5** [comment]
@hatkidchan Hi! Nice you find a solution! `raudio` is quite limited and requires some redesign to allow more features... It's on the TODO list but too many things are in that list...

**Comment by hatkidchan** [comment]
@raysan5 is there any changes I should made or I could close that issue with a PR that adds those functions?

Also, I noticed that when using `SetAudioStreamCallback` (the one that is already in the library), after some time (in my case around 200000 samples) pitch gets shifted a little, almost like the rate at which samples are requested changes... I've seen that behavior in OLCPixelGameEngine too, but there it was even worse and pitch shift was up to 2x in some cases... Maybe something with audio pipeline on Linux in general? I haven't tested it on Windows in all those years, or at least not like I remember it..

I'm saying that because it happens both in already existing function, as well as in the one I created, so should I really worry about it?

**Comment by hatkidchan** [comment]
> after some time (in my case around 200000 samples) pitch gets shifted a little,

Demo (warning, may be a bit loud/harsh on ears, but point is, tone is shifted up after a bit):

https://user-images.githubusercontent.com/35804000/219893019-6e22d66e-dd78-4027-b867-05a5d2714cf6.mp4

somewhere on 4.5 seconds mark it changes

source code for that generator: https://gist.github.com/hatkidchan/28e37d692cc533bb14f9d8b1a6df65e6
(the only change that was made adds counters of requested frames and draws them)

**Comment by raysan5** [comment]
@hatkidchan Excuse the late response and thanks for the addition!

**Comment by hatkidchan** [comment]
no problem!
