### ISSUE TITLE
[build] Use library versioning

### ISSUE THREAD

**Issue by jubalh** [raysan5/raylib#293]
Hi,

How about using [library versioning](https://autotools.io/libtool/version.html)?

Would be great.

**Comment by raysan5** [comment]
Well, I decided to keep it simple and just increase [version second number on every release](https://github.com/raysan5/raylib/blob/master/CHANGELOG). 

At the beginning I tried to be more accurate with versioning but I noticed I was changing a lot of things (API and ABI) from version to version, most of the time versions are not compatible and I don't like to keep *deprecated* functions around. Just decided to do it that way.

But if you have some proposal to improve that and want to work on that, let me know, we can discuss it.

**Comment by jubalh** [comment]
Thanks for the quick response @raysan5.

I like raylib, and think it should be more widely available. For this reason I package it for the openSUSE Linux distribution. To make it easily installable for more people.

Anyways, currently you ship a .so and .h file.
Which means that only one version of the library can be installed in `/usr/lib/` (for example). Library versioning would produce file like `raylib.so.1` etc. And a link in `/usr/lib/raylib.so` would link to such a version. Like this it would be possible to install multiple versions of a library on the same system.

Also with some tools we could detect when a ABI change occurs without a version bump of the library, which could lead to problems later on.

**Comment by raysan5** [comment]
Hi @jubalh, it sounds great to me to make raylib package available for openSUSE Linux distro!

I usually work on Windows OS so I focused raylib release and testing on that system but it would be great to make raylib more widely available to the Linux community, specially for education environments.

Any help on that direction is really welcomed! :)

**Comment by jubalh** [comment]
I think this issue can be closed as of  #299
