### ISSUE TITLE
[Windows] Black background when using transparency flag.

### ISSUE THREAD

**Issue by IagoBeuller** [raysan5/raylib#2932]
I'm using NimRaylibNow which is a wrapper for Raylib for Nim Lang, so not directly using this one, I can't tell if this is an issue with this lib or the wrapper, but acoording to the wrapper's owner, seems to be with raylib. This issue only happens when using Dedicated Graphics card, when using the onboard card it runs fine.

Wrapper's Owner declaration: https://github.com/greenfork/nimraylib_now/issues/77
Wrapper: https://github.com/greenfork/nimraylib_now

**Comment by raysan5** [comment]
@IagoBeuller Not enough information provided. It works ok for me on raylib C with Intel HD graphics.

**Comment by IagoBeuller** [comment]
> @IagoBeuller Not enough information provided. It works ok for me on raylib C with Intel HD graphics.

For me too in Nim, the problem is on using NVIDIA Graphics.

**Comment by IagoBeuller** [comment]
I tried the raylib in code blocks, my Graphics card is NVIDIA GeForce GTX 1650.
It didn't become transparent, but I found a NVIDIA setting for make it Works:

OpenGL GDI compability: Auto
![image](https://user-images.githubusercontent.com/46376262/220863797-67210287-e8a4-432d-87ba-6bab4f5936bb.png)

OpenGL GDI compability: Prefer compatible
![image](https://user-images.githubusercontent.com/46376262/220864597-88353557-d0a8-4d7f-99c4-1b3716cb0d98.png)

**Comment by IagoBeuller** [comment]
@raysan5 Yep, trying rTexViewer the transparency only works for me when I set the OpenGL GDI compatibility to "Prefer compatible". But this way for me it's ok.

**Comment by raysan5** [comment]
@IagoBeuller Wow, interesting issue. Everything points it's a driver thing...
