### ISSUE TITLE
[Android, core] No way to know if the application has been minimized/lost focus or not

### ISSUE THREAD

**Issue by DeexCoding** [raysan5/raylib#2935]
Most games pause if the app has lost its focus. Also delta time behaves weirdly without it.

Maybe a callback?

//A callback function that gets called by raylib.
void OnFocusChange(int gained)
{
    if (!gained) Pause();
}

Or just a function that returns a bool?

while (!WindowShouldClose())
{
    ...

    //In this case AppHasFocus() should be a function provided by raylib that returns a bool/int.
    if (!paused && !AppHasFocus()) Pause();

    ...
}

**Comment by raysan5** [comment]
raylib tries to abstract any platform-specific functionality. Android is a very specific platform, I recommend customizing raylib to user-needs.

**Comment by DeexCoding** [comment]
Maybe calling it AppHasFocus was a mistake. Maybe implement the functionality into IsWindowMinimized and IsWindowMaximized? If I understood and remember correctly raylib already stores a bool internally if the app has focus or not.

**Comment by raysan5** [comment]
@DeexCoding There is also `IsWindowFocused()`, I'm returning the App enabled flag in there.
