### ISSUE TITLE
[rcore/question] GetWindowHandle on Linux/X11?

### ISSUE THREAD

**Issue by hatkidchan** [raysan5/raylib#2938]
I'm doing some experiments with raylib and I kinda want to have raw handle of current window. We do have a function for that: `GetWindowHandle` that returns `void*`, but on Linux with X11 it just returns nothing. Seems like we do have relevant code here, but it's just commented out:

https://github.com/raysan5/raylib/blob/d5a31168ce768ef9c1e11fe4734285770a33aba4/src/rcore.c#L1716-L1721

Is there any specific reason to leave it this way? I know situation on Linux is kinda wonky with X11 being slowly thrown away in favor of new and shiny Wayland, ~~but we're returning glfw handle anyway, so it shouldn't be an issue?~~ oop, we don't, we're returning X11 window ID, but it's still not a big deal, since `void*` is the same size as `Window` anyways (`unsigned long` as far as I'm aware). Plus, we could just.. actually return glfw handle and leave it to the developer to figure out what they want to do with it

Sure, I could change it for myself, but it would make my code less portable, because it's not supported in "mainstream" version of library.

So, my question is: is there anything that we could do to make handle accessible on Linux? And if not, why can't we?

**Comment by raysan5** [comment]
@hatkidchan That code was written long time ago, I don't remember at the moment why no window-handle was returned in Linux, I think there was some issue, maybe some X11 symbol collision... in any case, if you implement it and it works, feel free to send a PR for integration.

**Comment by hatkidchan** [comment]
There *is* a collision of names when using X11 headers at the same time as raylib (for example, `Font` also exists in Xlib.h), but other than that, I don't see any problems. Plus, nothing stops developer from moving X11 part of their code to separate file and not include anything X11-related in headers. I'm still doing some testing regardless usefulness of it, but I think returning `(void*)CORE.Window.handle` should be more than enough for most cases?

**Comment by raysan5** [comment]
Implemented proposed solution. Not sure if it is the best approach but it's up to the user to manage it.
