### ISSUE TITLE
4.2.0 win32 mingw w64 is missing files in lib folder

### ISSUE THREAD

**Issue by DEF7** [raysan5/raylib#2941]
This file: [raylib-4.2.0_win32_mingw-w64.zip](https://github.com/raysan5/raylib/releases/download/4.2.0/raylib-4.2.0_win32_mingw-w64.zip)

The 'lib' folder is empty which isn't the case with the other files win32 and win64 releases.

**Comment by raysan5** [comment]
Yes, known issue and partially fixed. There is a duplicate issue around.
