### ISSUE TITLE
[general] Was 4.2.0 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [raysan5/raylib#2942]
Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [ ] My code has no errors or misuse of raylib

### Issue description

I tried to redownload Raylib to check the Homebrew download still works. The Homebrew package was updated on August 12th, and the hash of the current download does not match. The GitHub page also says the 4.2.0 release was done on the 13th.
The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do so I'd like to make sure the release isn't compromised.

### Environment

macOS 13.3

### Issue Screenshot
<img width="1441" alt="Screenshot 2023-02-24 at 09 16 49" src="https://user-images.githubusercontent.com/1484494/221127535-c5ffa2e1-885c-4ea8-926b-49b606b7f409.png">
https://github.com/Homebrew/homebrew-core/actions/runs/4258446794/jobs/7409748532

### Code Example

```
wget https://github.com/raysan5/raylib/archive/4.2.0.tar.gz
sha256sum 4.2.0.tar.gz
```
Then you'll notice the hash isn't `5fd2e7d825f345924800c38291f44423bcbcc036bd72fa2e3abedfc54e5b68b5` as Homebrew recorded it on the 12th of August.

**Comment by raysan5** [comment]
Yes, it was. I'll try to avoid "insane behaviours" in future releases.
