### ISSUE TITLE
[core] `core_drop_files` example not working

### ISSUE THREAD

**Issue by Lancelotbronner** [raysan5/raylib#2943]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch (latest commit: February 24, 2023 at 10:19:25 AM EST)
 - [x] I checked there is no similar issue already reported

### Issue description

Dropped files flash for a frame before disappearing, never actually keeping state.

The `IsFileDropped()` function returns `true` in the first frame, allowing `LoadDroppedFiles()` to fetch the file. It is however true for a second frame so the previous `FilePathList` is unloaded via `UnloadDroppedFiles` and we call `LoadDroppedFiles()` which this time returns an empty `FilePathList`, effectively preventing the *drop files* example to work. It is then `false` as expected on the third frame.

### Environment

Tested on the following platforms:
- macOS arm64 Safari 16.2
- macOS arm64 Firefox 109.0.1
- macOS arm64 Chrome 110.0.5481.177
- macOS arm64 built from source, latest `master` commit

### Code Example

See the drop files example.

**Comment by Lancelotbronner** [comment]
Sorry to bump this but I though the fix would be making IsFileDropped properly return false on the second frame.

I think this would make much more sense (since there are no files being dropped on that frame).

**Comment by raysan5** [comment]
@Lancelotbronner Actually, the redesign is the expected approach. `IsFileDropped()` returns false after the dropped files are being unloaded from memory.

**Comment by Lancelotbronner** [comment]
Of course, and that makes sense, I'm talking about the true which is returned on the frame after files are dropped, which is incorrect because there are no files being dropped, so loading dropped files returns an empty list.

**Comment by raysan5** [comment]
@Lancelotbronner Sorry, I'm afraid I don't understand the issue. `IsFileDropped()` returns true when there is some file dropped and it's reseted after calling `UnloadDroppedFiles()`, so, on the next frame it return `false` again because files have been already processed. I'm testing it on Windows 10.

Please, could you elaborate the issue with more detail?

**Comment by Lancelotbronner** [comment]
Maybe the issue doesn't happen on Windows, the issue is as follows:

- Frame 1: the files are dropped, true is returned, LoadDroppedFiles returns the filepaths
- Frame 2: no files are dropped, true is returned, LoadDroppedFiles returns an empty list of filepaths
- Frame 3 onward: no files are dropped, false is returned

The problem is Frame 2, where IsFileDropped wrongly returns true.

**Comment by raysan5** [comment]
@Lancelotbronner Ok, `Frame 2` does not happen on Windows. Are you calling `UnloadDroppedFiles()`? It sets `CORE.Window.dropFileCount` and consequently `IsFileDropped()` shouldn't return `true` on next frame.

In any case, it could be a system issue reporting an empty event, I added a code tweak, just in case, let me know if it solves the issue.

**Comment by raysan5** [comment]
@Lancelotbronner Could you try doing next lines?

```c
FilePathList files;

if (IsFileDropped())
{
    files = LoadDroppedFiles();

    // Copy files.paths as required

    UnloadDroppedFiles(files);
}
```

In any case, it seems a macOS system issue, probably the [`WindowDropCallback()`](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L5601) is called twice, I don't know why... 

It should be debugged carefully but I have no macOS...

**Comment by Lancelotbronner** [comment]
If on the copy I myself check if there are available paths to copy then I can workaround the issue easily, but I'll do the careful debugging to see where it goes wrong!

**Comment by Lancelotbronner** [comment]
So here's what I observed:
- `WindowDropCallback` is only called once
- `WindowDropCallback` frees previously allocated file paths
- `LoadDroppedFiles` doesn't load anything, it simply gets the currently loaded file paths

So what I was doing

```c
if (IsFileDropped()) { // only true on the frame the file is dropped
  if (files.paths)
    UnloadDroppedFiles(files); // Unload previously loaded files
  files = LoadDroppedFiles(); // Load new dropped files
}
```

was actually doing

```c
if (IsFileDropped()) { // always true once a file has been dropped
  if (files.paths)
    UnloadDroppedFiles(files); // Unload currently loaded files
  files = LoadDroppedFiles(); // Load empty files
}
```

On the first frame, since `files` was empty, it would load the current frame's paths. On the next frame `files` was no longer empty, unloading the files. On the third frame, `IsFileDropped` would return false until files were dropped again.

I see two issues which led me to assume the wrong behaviour for these methods
- `IsFileDropped` returns `true` once files have been dropped until you call `UnloadDroppedFiles` while I assumed it only returned `true` on the frame the files were dropped
- `LoadDroppedFiles` gets the currently loaded files while I assumed it loaded the files dropped this frame.

So the "correct" code is
```c
FilePathList files = {};

if (IsFileDropped()) // always true once a file has been dropped
  files = LoadDroppedFiles(); // Get the currently loaded files

// at de-initialization...
UnloadDroppedFiles(files) // unload (globally-tracked by raylib) dropped files if any
```

**Comment by Lancelotbronner** [comment]
I believe the "fix" to this should be to revise the API to be more in line with the actual behaviour and the assumptions made.

The solution I came up with, considering you strive for a simple API for education purpose, is to:
- Correct the behaviour of `bool IsFileDropped` to only return true on the frame files were loaded
- Remove `FilePathList LoadDroppedFiles()` and `UnloadDroppedFiles(FilePathList files)`
- Add `char** GetDroppedFiles()` and `unsigned int GetDroppedFilesCount()`
- Unload dropped files if any in `CloseWindow`

I believe this would be the best solution since raylib already does most of the dropped files memory management. This would just correct the API to reflect that and simplify things for the students. It's a very simple migration even on larger projects and could be made non-breaking easily (more on that further down).

Here's the drop files example with the new API, requiring only `raylib.h`.

```c
const int screenWidth = 800;
const int screenHeight = 450;

InitWindow(screenWidth, screenHeight, "raylib [core] example - drop files");
SetTargetFPS(60);

while (!WindowShouldClose()) {
    BeginDrawing();

    ClearBackground(RAYWHITE);

    if (GetDroppedFilesCount() == 0) 
        DrawText("Drop your files to this window!", 100, 40, 20, DARKGRAY);
    else {
        DrawText("Dropped files:", 100, 40, 20, DARKGRAY);

        for (unsigned int i = 0; i < GetDroppedFilesCount(); i++) {
            if (i%2 == 0) DrawRectangle(0, 85 + 40*i, screenWidth, 40, Fade(LIGHTGRAY, 0.5f));
            else DrawRectangle(0, 85 + 40*i, screenWidth, 40, Fade(LIGHTGRAY, 0.3f));

            DrawText(GetDroppedFiles()[i], 120, 100 + 40*i, 10, GRAY);
        }

        DrawText("Drop new files...", 100, 110 + 40*GetDroppedFilesCount(), 20, DARKGRAY);
    }

    EndDrawing();
}

CloseWindow();
```

If we wanted to make things non-breaking for the current release, the solution would instead be:
- Leave `bool IsFileDropped` as-is
- Leave `FilePathList LoadDroppedFiles()` and `UnloadDroppedFiles(FilePathList files)` as-is
- Add `char** GetDroppedFiles()` and `unsigned int GetDroppedFilesCount()`
- Unload dropped files if any in `CloseWindow`

What do you think of this?

**Comment by raysan5** [comment]
Dorry, current behaviour is the expected behaviour. It was already changed.
