### ISSUE TITLE
[rcore] Build failure for Android: no member named `handle`

### ISSUE THREAD

**Issue by e-ivkov** [raysan5/raylib#2950]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
I am closely following a [guide](https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux)) for building an apk for Android. And I am getting compiler errors for all architectures on [raylib compile step](https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux)#compile-raylib) except for `ANDROID_ARCH=arm64` - this architecture builds without errors.

Error for all other architectures is the same: `error: no member named 'handle' in 'struct CoreData::(unnamed at rcore.c:376:5)`

### Environment

Build machine:
- OS: Ubuntu 22.04.1 LTS x86_64
- Kernel: 5.15.0-33-generic
- CPU: AMD Ryzen 7 5700G with Radeon Graphics (16) @ 3.800GHz
- Memory: 27961MiB

### Issue Screenshot

```
egor@ivkov-pc:~/Projects/some_project/raylib/src$ make PLATFORM=PLATFORM_ANDROID ANDROID_NDK=../../android/ndk ANDROID_ARCH=x86_64 ANDROID_API_VERSION=29
../../android/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android29-clang -c rcore.c -Wall -D_GNU_SOURCE -DPLATFORM_ANDROID -DGRAPHICS_API_OPENGL_ES2 -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing  -std=c99 -O2 -march=x86-64 -ffunction-sections -funwind-tables -fstack-protector-strong -fPIE -fPIC -Wa,--noexecstack -Wformat -no-canonical-prefixes -D__ANDROID__ -DPLATFORM_ANDROID -D__ANDROID_API__=29 -DMAL_NO_OSS -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -I../../android/ndk/sources/android/native_app_glue -I../../android/ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I../../android/ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/x86_64-linux-android
In file included from <built-in>:368:
<command line>:6:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 29
        ^
<built-in>:361:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
rcore.c:1722:32: error: no member named 'handle' in 'struct CoreData::(unnamed at rcore.c:376:5)'
    return (void *)CORE.Window.handle;
                   ~~~~~~~~~~~ ^
1 warning and 1 error generated.
make: *** [Makefile:670: rcore.o] Error 1
egor@ivkov-pc:~/Projects/some_project/raylib/src$
```

### Code Example

1. Follow the steps from build for Android official guide on wiki
2. On compile step execute - `make PLATFORM=PLATFORM_ANDROID ANDROID_NDK=../../android/ndk ANDROID_ARCH=x86_64 ANDROID_API_VERSION=29`

**Comment by e-ivkov** [comment]
To be clear - I am already on recent master, which has this fix https://github.com/raysan5/raylib/commit/ab14ad5d754f7bbccbf8845b8062c8ece018b3e0

**Comment by raysan5** [comment]
@e-ivkov reviewed on latest commit.
