### ISSUE TITLE
This shit won't compile on Windows

### ISSUE THREAD

**Issue by RamyLebo** [raysan5/raylib#2959]
This shit won't compile on Windows:

![Raylib_error_1](https://user-images.githubusercontent.com/127967899/225357604-928dd5c4-13c0-40f1-a330-b62e1034e946.jpg)

![Raylib_error_2](https://user-images.githubusercontent.com/127967899/225357718-e9a28348-4ac1-4c8d-9f50-bdc9b70aceaf.jpg)

**Comment by RamyLebo** [comment]
![Raylib_error_3](https://user-images.githubusercontent.com/127967899/225364484-95bb6028-9449-49ae-a112-ef2c4b3b255b.jpg)

**Comment by kingofsponges** [comment]
here's a tip
next time provide the error(s) you have encountered when compiling

**Comment by serpatsama** [comment]
Skill issue
