### ISSUE TITLE
[raylib] PDF link to cheatsheet is broken

### ISSUE THREAD

**Issue by par5er** [raysan5/raylib#2969]
### Issue description

I hope this is the right place to ask this. The cheatsheet PDF link here is broken: https://www.raylib.com/cheatsheet/cheatsheet.html
Thanks!

### Environment

N/A

### Issue Screenshot

N/A

### Code Example

N/A

**Comment by raysan5** [comment]
@par5er Thanks for reporting! This issue belongs to `raysan5/raylib.com` repo, that contains the webpage.

In any case, I'm aware of the issue, I'll try to generate the PDF cheatsheet asap.
