### ISSUE TITLE
Need to comment out `LDFLAGS += $(RAYLIB_PATH)/src/raylib.rc.data` for examples to run on windows

### ISSUE THREAD

**Issue by lesleyrs** [raysan5/raylib#2978]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

As said in the title, examples didn't work until that line was commented out. Don't know what the problem is because that line is windows specific in the first place.

### Environment

Windows 10, mingw64 from w64devkit

### Issue Screenshot

```
i386 architecture of input file `../src/raylib.rc.data' is incompatible with i386:x86-64 output
```

https://raylib.handmade.network/forums/t/7074-examples_build_errors_on_windows_with_mingw

**Comment by orcmid** [comment]
This usually means that the rc.data file was compiled assuming one architecture (e.g., x86 32 bit), and the second linking stage is looking for x64-compatible material.  So this may be a compilation settings issue.

Which specific example are you attempting?

**Comment by lesleyrs** [comment]
>For getting started, the make files are too exotic and elaborate for learning simple compiles. They cover amazing ground, but troubleshooting them requires considerable understanding of what is going on. I think they may also require customization for actual situations.

Yea I'm not worried about understanding everything right now, just wanted to report this issue.

>With regard to the PLATFORM= parameter to mingw32-make, you'll see extensive conditional variation in the make file itself.

I was actually referring to `mingw32-make` compared to `make` not the parameter my bad, I figure if you compile raylib yourself it shouldn't make a difference? (this has nothing to do with the issue though)

Like I said I was able to compile all examples after commenting out that specific line in the makefile, but it should probably be fixed/changed.

**Comment by lesleyrs** [comment]
https://github.com/skeeto/w64devkit/releases/tag/v1.18.0 I downloaded the one at the top of the list here, below source.tar. Isn't that the x64 bit one? `w64devkit-1.18.0.zip`

**Comment by lesleyrs** [comment]
Yea it literally says 64 bit in the readme that came in the download, this should be re-opened.

**Comment by raysan5** [comment]
@lesleyrs Yeah, I checked it and fixed it. I don't know what happened because the resources shipped with the installer have the right architecture... In any case, I updated them.
