### ISSUE TITLE
[build] OSX build fails

### ISSUE THREAD

**Issue by IkonOne** [raysan5/raylib#298]
XCode Version 8.1 (8B62)
OSX Version 10.12.5 (16F73)

When building for OSX using the instructions provided in the wiki, I receive an 'Expected Identifier' error.

![screen shot 2017-06-07 at 4 39 13 pm](https://user-images.githubusercontent.com/1105646/26904595-e2af100c-4b9f-11e7-906e-68608408d48c.png)

Commenting out the line that causes the error allows for a successful build: https://github.com/raysan5/raylib/blob/master/src/raylib.h#L540

**Comment by raysan5** [comment]
Hi @IkonOne, thanks for pointing this out! Actually, I remember some user in the past also had problems with that symbol, I plan to rename all those names very soon to `LOG_DEBUG` and so.

Just keep this issue open in the meantime.

**Comment by IkonOne** [comment]
Will do.

Since when is DEBUG 'reserved'...

**Comment by raysan5** [comment]
Just some more days and I'll push an update to develop branch...

**Comment by raysan5** [comment]
`LogType` names changed in commit https://github.com/raysan5/raylib/commit/9f09f6f55023bf8f14a6889801520d80475d33be
