### ISSUE TITLE
[core] wrong raylib version in CMake (currently it's 4.2.0)

### ISSUE THREAD

**Issue by GoodNike** [raysan5/raylib#2985]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Current raylib version is set to 4.2.0, but current release is 4.5.0 (or current dev is 4.6.0).

https://github.com/raysan5/raylib/blob/master/src/CMakeLists.txt#L3

Installing current master as shared library leads to:
```
libraylib.so.4.2.0
libraylib.so.420
libraylib.so
```

**Comment by raysan5** [comment]
@GoodNike Thanks! Reviewed!
