### ISSUE TITLE
Raylib not compiling on Windows x64

### ISSUE THREAD

**Issue by JaydenSu** [raysan5/raylib#2987]
Hello,

Raylib not compiling on Windows x64.

To test I use this simple code:

```
#include <iostream>
extern "C"
{
      #include "raylib.h"
}



int main()
{

         SetTraceLogLevel(LOG_NONE); 

         //-----------------------------------------
         int screenWidth = 800;
         int screenHeight = 450;

         InitWindow(screenWidth, screenHeight, "taylib");
         SetTargetFPS(60);         
         //-----------------------------------------


         while (!WindowShouldClose())    // Detect window close button or ESC key
         {
             BeginDrawing();
             ClearBackground(RAYWHITE);
             EndDrawing();
             CloseWindow();      
         }
}
```

Errors:

```
Error LNK2005 CloseWindow is already defined in user32.lib(USER32.dll)
Error LNK1169 Multiple defined symbol encountered - one or more Raylib
```

No release, no debug version on Windows 64 - Not compiles.

On x32 windows it compiles without problems.

**Comment by raysan5** [comment]
You should link raylib.lib before other libraries.

**Comment by orcmid** [comment]
I think there are two things here.

First, `<iostream>` is a C++ library, not a C library.  There is no point to having it n that sample.  

Secondly, You don't  need the `extern "C"` around the use of `raylib.h`.  The `raylib.h` file is designed to be used properly from a C++ program and it provides any needed `extern "C" on detecting it is being included in a C++ compile.

Finally, what compiler are you using?

I compile all examples like yours using VC/C++ on a Windows x64 machine and targeting Windows x64 and it works just great.  I am not trying to pass you off with a "works for me."  I suggest the difference, if any, after fixing the source code is how you are doing the build.

**Comment by JaydenSu** [comment]
> You should link raylib.lib before other libraries.

This helped thanks. It's not clear why it worked on x32.

**Comment by JaydenSu** [comment]
> First, `<iostream>` is a C++ library, not a C library. There is no point to having it in that sample.

Why ? I need a standard C++ Iostream.
What difference does it make to you which header I connect?


> Secondly, You don't need the `extern "C"` around the use of `raylib.h`. The `raylib.h` file is designed to be used properly from a C++ program and it provides any needed `extern "C" on detecting it is being included in a C++ compile.

Indeed it works. Thank you.


> Finally, what compiler are you using? And what is the name of the file? Does it have a *.c name?
Visual Studio 2022.


> PS: Ditch the `SetTraceLogLevel()` and move the `CloseWindow();` outside the **while** loop :)
Oops, it's just a copy error. Actually CloseWindows is outside of the loop.

**Comment by orcmid** [comment]
@JaydenSu There was no need for `<iostream>` in the example.  And if it as a C Language program, `#include "stdio.h"` would have been a better choice.  But you didn't need that either.

I presume, because you are using VS 2022, that your program has a *.cpp name.
