### ISSUE TITLE
 SetConfigFlags(FLAG_WINDOW_TRANSPARENT) - dont work ?

### ISSUE THREAD

**Issue by JaydenSu** [raysan5/raylib#2990]
Hello,

My apologies - if I made a mistake and misunderstood something, but I have:

-Windows 10 x64

A window with the flag "FLAG_WINDOW_TRANSPARENT" set - is created by the usual - NOT transparent.

```
int main()
{
          SetConfigFlags(FLAG_WINDOW_TRANSPARENT);

          InitWindow(800, 600, "raylib");
          SetTargetFPS(60);

          while (!WindowShouldClose())
          {
              BeginDrawing();
              ClearBackground(RAYWHITE);
              EndDrawing();

          }
            CloseWindow();
}
```

**Comment by raysan5** [comment]
You should `ClearBackground(BLANK);` to see the transparency, instead of painting it `RAYWHITE` (not-transparent color).

But also note that transparency support could also be dependant on the GPU and the graphics drivers.

**Comment by dostoievsky** [comment]
How could we debug if the pc supports transparency or not? 
I did the correct config here and still it is not transparent.
