### ISSUE TITLE
[text] Feature Request - Text wrapping

### ISSUE THREAD

**Issue by CalSch** [raysan5/raylib#2995]
I think it would be nice to have a text wrapping function that would take the text, the font, the font size, and the max width, and return a new piece of text with newlines wherever necessary.  
  
I have tried to do this on my own, but I was unsuccessful because I don't really know much about C string manipulation or memory management.  
Here's some C-like pseudo-code of my algorithm:
```c
string TextWrap(string text, Font font, int fontSize, int maxWidth)
{
    string result = "";
    string currentString = "";
    for (int i = 0; i < TextLength(text); i++)
    {
        char c = result[i];
        string newStr = join(currentString, c);
        if (MeasureText(newStr) > maxWidth) // Overflow
        {
            result = join(result, currentString); // Add current line
            result = join(result, "\n"); // Add new line
            currentString=""; // Reset current line
        }
        currentString=newStr; // Add char
    }

    return result
}
```
(I haven't tested this code so it might not work)

**Comment by raysan5** [comment]
@CalSch raylib already includes an example with that functionality: https://github.com/raysan5/raylib/blob/master/examples/text/text_rectangle_bounds.c

**Comment by orcmid** [comment]
@CalSch Yes, when you send the text to a bounded box it should work just fine.

With regard to your example, the easy way (in a modifiable copy of the text), is, to peek ahead to the linewidth further character position and if there's a space there, replace it with '\n'.  If it's not a space, move backwards until there is one and put the '\n' there.  Now, starting from the place where you put the '\n', check ahead another line-width.  Stop when there are not line-width characters remaining (or to start with).

This assumes, of course, that you are using char-size string elements.  If you are using UTF8 it is trickier, in that the line-width in characters and the number of bytes taken in the string are often not the same, and you'll break the line too soon sometimes.  Counting bytes and counting characters are not the same thing.  There's still a way to accomplish that by scanning forward through the bytes, remembering the position of the last space character reached/passed while stepping through line-width codes for characters. 

There's no reason to have anything like this built into raylib.  And you can just use the bounded-box line-wrap provisions.

Note , this doesn't work in Unicode even if you convert everything to **long**.  Non-alphabetic languages have more complicated character-composition situations.  That's also true for some European languages with regard to special marks combined with characters.  There are Unicode libraries for dealing with all this.

If you're just using the "Roman" alphabet (i.e., the 95 ASCII graphic code points), you can get away with assuming one code-point per **char** and length of the string is the number of characters.

With all the language dependencies and character-set encodings to consider, it is understandable that this is not all built into raylib.
