### ISSUE TITLE
[IDEA] Tiled tmx support

### ISSUE THREAD

**Issue by jubalh** [raysan5/raylib#300]
I think [Tiled](http://www.mapeditor.org/) is a nice way to create levels for games.

There is a [C library](https://github.com/baylej/tmx)that is able to parse the tmx file format.
It has examples for its usage with allegro and sdl, maybe we should add an example with raylib?

[This](https://github.com/baylej/tmx/tree/master/examples) is their example folder.

I started doing this but I am not too much familiar with raylib yet, and thus its very hard for me. Maybe someone can help? :)

**Comment by jubalh** [comment]
Or would including that lib with some nicer wrapper functions or writing own raylib tmx parser be more appropriate?
I think Tiled is quite popular, and is also heavily used from Love2d people. This could be a good step towards making raylib more popular again?

**Comment by raysan5** [comment]
Hi @jubalh! 

I love Tiled but I think tmx support is out of scope of raylib, it would be more proper for a raylib code example. I prefer to keep the library with basic generic functionality for any kind of game; tmx is very game-type centric.

Creating a raylib example for TMX library shouldn't be difficult but it requires some time...

**Comment by jubalh** [comment]
Hi @raysan5 !
> Creating a raylib example for TMX library shouldn't be difficult but it requires some time...

Do you think you can find some time for doing this? It would be *awesome*.

I also created an [issue](https://github.com/baylej/tmx/issues/31) for it on the tmx c library.

**Comment by raysan5** [comment]
Hey @jubalh! 

It's on my list, really, but I'm a bit overloaded with several things in my daily work and I can't find the time to work in deep in most of the pending issues... just have some small time spots that don't give me enough concentration space to work on complex issues...

Could you setup a basic example with some .tmx map + required textures + expected result screenshot to start working with it? It would be easier for me to go straight to loading and drawing implementations.

**Comment by jubalh** [comment]
I totally understand. And I definitely don't want to push :)

I think https://github.com/baylej/tmx/blob/master/examples/sdl/sdl.c is a very good thing to look it. Basically it shows how to use the tmx library to get the content out of the .tmx file. It then uses SDL to draw the content. https://github.com/baylej/tmx/blob/master/examples/allegro/allegro.c shows the same for allegro.
As I see it, you could just use one of those, and adapt the SDL calls to the raylib calls. allegro and sdl usage of tmx are very similar they just use their respective APIs to draw unto a canvas and get the canvas it seems.

In https://github.com/baylej/tmx/tree/master/examples/data he also has example .tmx files.

I just looked through my harddisk and realized that I still have my attempt of writing the raylib example. I committed it now and pushed it to: https://github.com/jubalh/tmx/tree/master/examples/raylib

raylib.c was about taking the sdl example and changing it to use raylib calls.
raylib2.c was starting with a base raylib project and adding the tmx calls.

I didn't get very far. Also for time reasons, but even more so because I don't know enough about raylib and drawing things on the screen in general.

**Comment by jubalh** [comment]
Hi there,
I still think TMX support would be something worthwhile. Especially for people coming from love2d this would be a thing they would miss. It would attract more users of raylib I think. And one doesnt need to invent their own map format.

**Comment by raysan5** [comment]
ok, let's give it another opportunity...

**Comment by jubalh** [comment]
Raylib plays oggs. For me this is not much different and plans to do networking. For me this is not more out of scope.
It has to parse xml files and create structs for this which then can be displayed.

Love2D and others do it too.

I agree that adding an example to the tmx library would be an alternative.

But since raylib adds networking and so many non core game related things it could as well add a tmx module of itself. So that the syntax, usage and naming is closer to raylib than an external library like tmx.

**Comment by raysan5** [comment]
@jubalh networking is a feature that many games today could require, independently of the game style, same as ogg playing... but TMX map support is a very specific requirement for a specific kind of game and for maps created with a specific tool (Tiled).

Supporting that format on raylib is not that trivial, requires lot of work and despite being a possible addition, it's definetely very low priority for me. As always, I'm open to collaboration and accept PR requests.

Also consider that all external libraries included in raylib to support specific file-formats  are single-file header-only.

@terrehbyte Creating a raylib example seems a good alternative.

**Comment by sherjilozair** [comment]
This is probably too high-level to belong in ralylib, but it would be nice to have an example or perhaps an auxiliary repository. I'll take a crack at this, since I'm planning to use raylib API with tiled for a game idea.

**Comment by raysan5** [comment]
Just linking to a [TMX loading example](https://github.com/OnACoffeeBreak/raylib_tiled_import_with_tmx).

**Comment by jubalh** [comment]
Wow, supercool! Thanks!

**Comment by raysan5** [comment]
Avoid example shows a TMX implementation for raylib. No plans to add it to the library. Closing the issue.
