### ISSUE TITLE
Error compilation : rcore.c:282:14: fatal error: gbm.h: No such file or directory

### ISSUE THREAD

**Issue by reinhardkrakow** [raysan5/raylib#3001]
Hi,
I use :
- RPi 64bit
- the last raylib-master.zip file
- unzip raylib-master.zip
- cd raylib-master/src
- make PLATFORM=PLATFORM_DRM
On the first file compilation :
gcc -c rcore.c -Wall -D_GNU_SOURCE -DPLATFORM_DRM -DGRAPHICS_API_OPENGL_ES2 -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing  -std=c99 -fPIC -DEGL_NO_X11 -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -I/usr/include/libdrm

I receive the following error :
rcore.c:282:14: fatal error: gbm.h: No such file or directory

I use raylib since one year on RPi 32bit and it works fine. I try now to switch to Rpi 64bit

Kind regards,
Reinhard

**Comment by raysan5** [comment]
@reinhardkrakow Were you compiling raylib for `PLATFORM_RPI` instead of `PLATFORM_DRM`? In any case, it seems related to a missing library, make sure `libgbm-dev` is installed.

**Comment by reinhardkrakow** [comment]
Hi,
Sorry, I made probably an error on my install procedure. I redo an installation from scratch ans it works fine.
Thanks for your quick reply.
Kind regards,
Reinhard
