### ISSUE TITLE
Cannot load .WAV files from disk due to case-sensitive file extension comparison

### ISSUE THREAD

**Issue by ForNeVeR** [raysan5/raylib#3008]
> Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I am developing a remake of an old game that chose to store its sounds in WAV format. These files have a `.WAV` extension (in uppercase), and my game downloads the original files and uses them as-is.

Turns out `LoadWave` from `audio.c` is unable to load these files without renaming them from `.WAV` to `.wav`.

### Environment

My game is cross-platform across Windows, macOS and Linux, the latter is known for having a case-sensitive file system settings by default (and others don't, though these are just defaults and ar possible to change).

### Code Example

I expect this to work and load a `.WAV` file on any platform, but it doesn't do that.

```c
LoadWave("gameData/U95_0.WAV");
```

### Investigation

This line gets a file extension and passes it to `LoadWaveFromMemory`:
https://github.com/raysan5/raylib/blob/9aa71f04f2410319f7a8862a073bb9639939a4a3/src/raudio.c#L737

And then this line does a case-insensitive comparison:
https://github.com/raysan5/raylib/blob/9aa71f04f2410319f7a8862a073bb9639939a4a3/src/raudio.c#L752

Perhaps replacement of `strcmp` with `strcmpi` (or a similar standard function) would fix the issue.

### Workaround

Rename the files on disk (I would like to avoid that to not touch the original game data as it is), or load them into memory and then call `LoadWaveFromMemory` yourself.

### Discussion

Of course, you may argue that Raylib only supports `.wav` files and not `.WAV` ones, but it's hard to imagine that somebody passes a `.WAV` or `.Wav` file to `LoadWave` and expects it to do anything else than load the file as a `.wav`, either on a case-sensitive and case-insensitive file system.

**Comment by raysan5** [comment]
Actually, afair, there was some discussion in the past about making file-access case sensitive or not and supporting both options; also about considering the dot (`.`) or not...  

I can consider making internal files loading case insensitive, probably just using:
```c
 else if (strcmp(TextToLower(fileType), ".wav") == 0)
```
or just comparing both possible cases:
```c
 else if ((strcmp(fileType, ".wav") == 0) || (strcmp(fileType, ".WAV") == 0)) 
```
In this second case, the module coupling with `rtext` module is avoided.

This is a change that would affect all the file loaders in the library (all modules) so I have to review it carefully.

**Comment by ForNeVeR** [comment]
> ```c
>  else if ((strcmp(fileType, ".wav") == 0) || (strcmp(fileType, ".WAV") == 0)) 
> ```

That solution, while having an advantage of not coupling with `rtext` (is it practical to avoid that coupling, though?), would also have a disadvantage of not handling other examples such as `.Wav`. I have no examples of such files myself, but it's possible to imagine someone using this kind of naming 😅

**Comment by raysan5** [comment]
@ForNeVeR Just implemented second solution, I think those weird capital-lower-mixed extensions shouldn't be valid.
