### ISSUE TITLE
GetGlyphIndex and GetGlyphInfo - works incorrectly.

### ISSUE THREAD

**Issue by JaydenSu** [raysan5/raylib#3012]
I inform you that at the time of 03/14/2023, the raylib functions:
-GetGlyphIndex
-GetGlyphInfo

Works incorrectly and produces incorrect values

GetGlyphIndex - Returns information about a non-existent Unicode code point in the loaded file, as if it exists.

GetGlyphInfo - also returns information about a non-existing Unicode code point in the loaded file, as if it exists.

LoadFontEx was specifically called to load a guaranteed non-existent Unicode character, these two raylib functions show that it exists.

```
int codepoint = 99999999;
Font font_ = LoadFontEx("C:\\my_Fonts\\China.ttf", 36, &codepoint , 1);
```

**Comment by raysan5** [comment]
Those cases are out of scope of raylib. Most users won't hit those side cases ever.

**Comment by JaydenSu** [comment]
I was just informing the Users about the fact that the GetGlyphIndex and GetGlyphInfo functions are not working correctly and that's it.

**Comment by raysan5** [comment]
@JaydenSu thank you very much, any user facing that same problem will have this issue for reference.
