### ISSUE TITLE
[build] CMake config is insufficient 

### ISSUE THREAD

**Issue by MonicaLiu0311** [raysan5/raylib#3018]
The proper object files are not generated for cmake, this does not work correctly with vcpkg, and the target raylib export is not set correctly for all cases (debug/release).

Related issue: https://github.com/microsoft/vcpkg/issues/25249

**Comment by raysan5** [comment]
@MonicaLiu0311 Thanks for reporting. I'm afraid I don't maintain the CMake build system, it was user contributed.

Contributions and fixes are welcome.

**Comment by raysan5** [comment]
It seems this issue is not affecting many people and nobody is interested in fixing it, so, assuming no-issue.
