### ISSUE TITLE
Fails to build with clang due to bool definition in raylib.h

### ISSUE THREAD

**Issue by dallbee** [raysan5/raylib#302]
In clang's stdbool.h, it defines:

```c
#ifndef __STDBOOL_H
#define __STDBOOL_H
```
Raylib, however, checks for _STDBOOL_H (notice the single underscore). This check of course fails and then proceeds to try and define typedef enum { true, false } bool; 

This causes builds to fail:
```.sh
In file included from ../src/main.c:5:
/usr/local/include/raylib.h:300:24: error: expected identifier
        typedef enum { false, true } bool;
```

**Comment by raysan5** [comment]
Hi @dallbee,

Just added additional header check on commit https://github.com/raysan5/raylib/commit/5370fe18e08303afdffcb78b428b92e8205fbc76

Please, let me know if it works ok.

**Comment by dallbee** [comment]
That does the trick! Thank you. Really enjoying the library so far.
