### ISSUE TITLE
[rcore] Multitouch (example) not working on RPI4 (fixed with hacky solution)

### ISSUE THREAD

**Issue by wschopohl** [raysan5/raylib#3024]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Just realized that the `examples/core/core_input_multitouch` was not working in the latest release, although I was pretty sure it was working on the exact same hardware (RPI4, Waveshare 5.5 Amoled Screen) before. Also looking at `ts_test_mt` output I could confirm, that multitouch was working.

### Environment

Custom Buildroot Linux, Raspberry Pi 4, Waveshare 5.5inch HDMI AMOLED, Multitouch capable

### Code Example

When debugging the example I noticed, that `GetTouchPointCount()` in the example always stayed at zero. When debugging `rcore.c` afterwards (quite hastily though) I found that this function relied on `CORE.Input.Touch.pointCount` but nowhere in the code I could see it getting updated for the `PLATFORM_DRM` platform. I then introduced a pretty hacky solution, 1 line of code:

rcore.c, line 6745:

```
gestureEvent.position[3] = CORE.Input.Touch.position[3];

CORE.Input.Touch.pointCount = gestureEvent.pointCount;  // this is the new line

ProcessGestureEvent(gestureEvent);
```

And the `examples/core/core_input_multitouch` was working again as expected. I would have posted it as pull request, but I understand too little of the workings of raylib to know, if this is actually a good solution.

**Comment by raysan5** [comment]
@wschopohl Thanks for reporting, I reiewed the code and I pushed a possible solution. Please, could you verify it works as expected? Thanks!

**Comment by wschopohl** [comment]
Checked out master commit #ac2e9cd00f05bf820faea737bb9beba75dc90529 and can confirm `examples/core/core_input_multitouch` is working as expected again!
