### ISSUE TITLE
[examples] Mesh instancing and split screen examples are not working on Firefox

### ISSUE THREAD

**Issue by josator** [raysan5/raylib#3030]
I am not sure if this is the right place, but this example from the website is not working in my browser:

https://www.raylib.com/examples/shaders/loader.html?name=shaders_mesh_instancing

It remains blank, only fps counter goes down from 60 to 32, no objects appear.  I attach console output.

[consolelog.txt](https://github.com/raysan5/raylib/files/11328718/consolelog.txt)

Also found in this log that ANGLE is not properly detecting my graphics card, it says in the log:

INFO:     > Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0) loader.html:154:25

but it is a geforce GTX 1070

Regarding this example:

https://www.raylib.com/examples/core/loader.html?name=core_split_screen

When I press W or S with game focused (click on the window and "scroll disabled" message appears) I can not control that part of the game because the browser search bar appears and captures the keys pressed.

This warning also appears in browser console:

"Element.setCapture() obsolete. Use Element.setPointerCapture()"

My browser is Firefox 112.0.2 (64-bit) on windows, desktop machine with nvidia card.

**Comment by raysan5** [comment]
@josator Thanks for the report. 

About `core_split_screen`, example was mostly created for Desktop and compiled for Web so controls were not taken into consideration to avoid overlap with browser. Also note that it should be managed in html/js side of the project, not in the .wasm generated on compilation.

About `shaders_mesh_instancing`, sincerely, I don't know why it doesn't work. If you try compiling for web and running it locally, it works peerfectly but for very weird reason, when uploaded to GitHub host to be served on raylib webpage it does not work, shader text files are not loaded correctly. I'm still investigating it but help is welcome.

**Comment by josator** [comment]
I will build shaders mesh instancing on desktop to check if ANGLE detects my graphics card properly.

**Comment by josator** [comment]
Maybe it has to do with the emsdk version with which the examples where compiled when were uploaded to github?

**Comment by chriscamacho** [comment]
could this be a security issue with loading files, I can't remember the details but I seem to remember having to jump through some hoops to package a load files, it might be worth just embedding the shader text into the example source...

**Comment by raysan5** [comment]
> I can confirm the shaders mesh instancing example runs great when accessed from local python webserver, shader errors and warnings that appear on the log from the github webserver are not present.

I think it is related to some locale configuration, I already faced this same issue once... but I don't remember how I fixed it... Still it is very weird because it only happens with that specific example, it works ok with all other shader examples.

About the GPU missdetection, no idea... probably ANGLE is doing some magic internally...

**Comment by chriscamacho** [comment]
It was some time ago, but I think I ended up packaging the files to get round odd issues like this https://emscripten.org/docs/porting/files/packaging_files.html

**Comment by raysan5** [comment]
> Yes but If you look at the other examples browser console output there are many warnings that do not appear when tested on local webserver.

@josator That's because the WARNIN logs were removed very recently to avoid scaring the users about uniforms not found in the shaders, web examples are not updated to latest raylib 4.6-dev (master branch).

**Comment by raysan5** [comment]
I'm closing this issue because I think it's external to raylib.
