### ISSUE TITLE
[rmodel] Does raylib support the Draco compression of glb format?

### ISSUE THREAD

**Issue by AllenDang** [raysan5/raylib#3051]
### Issue description

As title states.

**Comment by raysan5** [comment]
raylib uses the outstanding [`cgltf`](https://github.com/jkuhlmann/cgltf) and as stated on its [README](https://github.com/jkuhlmann/cgltf#features), yes, it supports Draco mesh compression extension but...
```
KHR_draco_mesh_compression (requires a library like [Google's Draco](https://github.com/google/draco) for decompression though)
```

**Comment by AllenDang** [comment]
@raysan5 I checked cgltf lib, it didn't mention how to enable the draco support, I tried to define a header as `#define CGLTF_EXTENSION_FLAG_DRACO_MESH_COMPRESSION` and added google/draco, but still doesn't work.

**Comment by raysan5** [comment]
@AllenDang I'm afraid I have no idea, I never used it... I don't know if it requires calling some special function to load Draco meshes, as per my understanding, it should be internal to cgltf to process them... Maybe you can ask cgltf author for details?

I'm just updating the library on raylib with latest changes but I can't see anything related to Draco loading changes.

**Comment by raysan5** [comment]
@AllenDang Thanks for the info! It seems the integration should happen at `cgltf` side som I'm closing the related issue on `raylib`. https://github.com/raysan5/raylib/issues/3063
