### ISSUE TITLE
raylib additional libraries

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#306]
This issue is related to https://github.com/raysan5/raylib/issues/304

raylib sources include some header-only libraries that can be used as standalone libraries:

 - [`raymath`](https://github.com/raysan5/raylib/blob/develop/src/raymath.h): Vector2, Vector3, Matrix and Quaternion math; it could require some review as per #291 
 - [`camera`](https://github.com/raysan5/raylib/blob/develop/src/camera.h): 3D Camera system (free, orbital, 1st person, 3rd person, custom)
 - [`gestures`](https://github.com/raysan5/raylib/blob/develop/src/gestures.h): Touch gestures processing (Tap, DoubleTap, Swipe, Drag, Pinch)
 - [`easings`](https://github.com/raysan5/raylib/blob/develop/src/easings.h): Easing functions for animations (based on [Robert Penner](http://robertpenner.com/easing/) implementation)
 - [`physac`](https://github.com/victorfisac/Physac): 2D physics library (collision detection, resolution, dinamics...)
 - [`raygui`](https://github.com/raysan5/raygui): Simple IMGUI system with several controls for tools development

Libraries like `raymath.h`, `camera.h` and `gestures.h` are used internally by raylib, but they can also be used independently of raylib.

Libraries like `easings.h`, `physac.h` and `raygui.h` provide additional functionality to the library, in case it was required.

In latest raylib release, the installer just copied `raymath.h`, `easings.h`, `physac.h` in default MinGW include directory, just in case user required them... but I don't like that approach, I prefer the user to just copy the libraries they need in any case...

I open this issue as a discussion about what to do with those libraries.

**Comment by raysan5** [comment]
Just as a note, `raymath.h` has been reviewed as per: http://forum.raylib.com/index.php?p=/discussion/138/bug-in-raymath-h-raylib-1-7

**Comment by a3f** [comment]
I think all public headers should be made available to the user, especially with auto installations, e.g. Homebrew, expecting the user to mess with the installation script is too much to ask.

I wouldn't like a library to install a `camera.h` header though. Either add a `ray` in front or install all headers to a `raylib/` directory, so it becomes `<raylib/math.h>`, `<raylib/raylib.h>` and so on.

**Comment by ferreiradaselva** [comment]
Why don't you create a separated repository for each of those libraries (each in their own repo) and add them as git submodules? I'm doing that with my game framework and my math library and it works very well. The use will require to clone this repository with the `--recursive` option, that will make git download the other repos inside one folder of your desire (could be inside `src`). And you will have more control about their updates, since you can work on them separately, and in this repo you can define which commit of them this repo will use.

**Comment by raysan5** [comment]
@a3f `camera.h` and `gestures.h` are not exposed to the user right now, they are only used internally by `core` module, indeed they should be renamed to be exposed (like `raymath.h` and `raygui.h`).

@ferreiradaselva I already thought about that (move libraries to own repos), actually, [raygui](https://github.com/raysan5/raygui), [physac ](https://github.com/victorfisac/Physac)and [raylib-lua](https://github.com/raysan5/raylib-lua) are already on their own repo.

`camera.h` and `gestures.h` are quite tied to raylib to move them, actually, camera module should be completely reviewed to work with quaternions instead of Euler math (that module was created long time ago).

`raymath.h` is the module more prone to be moved to their own repo...

**Comment by gen2brain** [comment]
`<raylib/math.h>`, `<raylib/raylib.h>` etc. is a standard thing to do and something that I saw at many projects. Although some (most/all?) headers have support to be used standalone, if anyone wants to really do that, probably knows what is doing and what to do with them.

**Comment by raysan5** [comment]
Closing this issue. All libraries that required to be moved where already moved.
