### ISSUE TITLE
[core] Way to handle joysticks without custom gamepad mapping

### ISSUE THREAD

**Issue by al1-ce** [raysan5/raylib#3068]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
I have a joystick (namely VKBsim Gladiator NXT) and I wanted to create simple space sim demo project, however when I tried polling input it had nothing. 
Tested it with gamepad example on web, it worked, but didn't show all buttons working (which there are more then 20)
Then I dug deeper and found about SDL maps and I was only able to map 15 from 26 keys present. Though all 6 axis were mapped successfully 

Would there be a way to get lower level joystick handling (akin to SDL_Joystick where now raylib only allowing to use SDL_GameController)

### Environment
Windows 11 (haven't tested on linux yet, but will soon)

**Comment by raysan5** [comment]
Gamepad support for desktop and web comes again through GLFW library (despite GLFW web version is a custom JS implementation using browser capabilities). 

GLFW maps any recognized joystick buttons/axes to Xbox-style controller using [`SDL_GameControllerDB`](https://github.com/gabomdq/SDL_GameControllerDB). Mapping can be manually updated if required using [`glfwUpdateGamepadMappings`](https://www.glfw.org/docs/3.3/input_guide.html#gamepad_mapping).

raylib calls internally [`glfwGetGamepadState()`](https://www.glfw.org/docs/3.3/group__input.html#gadccddea8bce6113fa459de379ddaf051) that maps up to [**15 buttons**](https://www.glfw.org/docs/3.3/structGLFWgamepadstate.html) and **6 axis** using latest included `SDL_GameControllerDB`.

So, I'm afraid **15 buttons** support is a GLFW limitation at this moment...

**Comment by al1-ce** [comment]
I know, looked somewhat deeply into it to figure out how it works
All those issues really makes me dislike glfw tbh

Anyway, I'm kind of creating these issues as "trackers" of "would be really good to have" features and hope that they'll be resolved someday

**Comment by Kabcorp** [comment]
@al1-ce 
This can be done with these functions from GLFW:
```c
int glfwJoystickPresent(int gamepad);
char* glfwGetJoystickName(int gamepad);
const unsigned char* glfwGetJoystickButtons(int jid, int* count);
const float* glfwGetJoystickAxes(int jid, int* count);
const unsigned char* glfwGetJoystickHats(int jid, int* count);
```
With them, you can use 1:1 raw button mapping from any HID gamepad

**Comment by raysan5** [comment]
This specific (advanced?) request could be managed on user side with provided GLFW functions, implementing some solution inside raylib would imply an internal redesign, no plans for now.
