### ISSUE TITLE
[build] Error when compiling template_android

### ISSUE THREAD

**Issue by RafaelOliveira** [raysan5/raylib#307]
I installed the custom ndk toolchain, and created the libraylib.a in linux with make PLATFORM=PLATFORM_ANDROID. After that I copy the libraylib.a to the template and compiled with $ANDROID_NDK_ROOT/ndk-build, but I'm receing this message:

..jni/libs/libraylib.a: error adding symbols: Archive has no index; run ranlib to add one

I executed ranlib but this is very advanced and I don't know which option to choose. I'm on Linux Mint.

**Comment by RafaelOliveira** [comment]
I used this command to create the toolchain:
make_standalone_toolchain.py --arch arm --api 21 --install-dir /android-toolchain-path

**Comment by raysan5** [comment]
Hi @RafaelOliveira, thanks for pointing this issue... Android building needs to be reviewed...

**Comment by RafaelOliveira** [comment]
Also noted here https://github.com/raysan5/raylib/blob/master/src/Makefile#L102 the variable "ANDROID_NDK_HOME", but the wiki asks to create "ANDROID_NDK_ROOT" in the system. This seems to be used in the makefile to create the toolchain, I renamed and called: 
make toolchain PLATFORM=PLATFORM_ANDROID
but it's also showing a error:
HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=8
BUILD_NUM_CPUS=16
Auto-config: --arch=arm
ERROR: Failed to create toolchain.
Makefile:305: recipe for target 'toolchain' failed
make: *** [toolchain] Error 1
 
For create the toolchain the python command works (the makefile uses a sh version).

**Comment by raysan5** [comment]
Hi @RafaelOliveira, I'm working on a custom Android build system, Makefile based, more info here: https://github.com/raysan5/raylib/issues/278

So, I'm closing this issue.
