### ISSUE TITLE
[core] Add minimal pen tablet support

### ISSUE THREAD

**Issue by digitalsignalperson** [raysan5/raylib#3076]
Feature request: when pen/stylus support is added to GLFW, add it to raylib.

Issue and PR in glfw:
- https://github.com/glfw/glfw/issues/403
- https://github.com/glfw/glfw/pull/1445

Per the PR
- the pen support is for x, y, z, pressure, pitch, yaw, roll, cursor (pen, eraser etc) and proximity.
- works on Windows, X11 and macOS

**Comment by raysan5** [comment]
Waiting for next GLFW release including those features...

**Comment by raysan5** [comment]
This issue depends on an external library, not much can be done on raylib side at the moment.
