### ISSUE TITLE
[build] RaspberryPi examples building path

### ISSUE THREAD

**Issue by denadaisicari** [raysan5/raylib#308]
Hello! I've tried to post a comment on raylib.com forum, but without success. I have too much difficult to get the lib into raspberry pi. 

In fact, my last try was: download the lib for windows, copy the files into PI and try the make command. But I get too many errors. 

Can anyone help me? I'll really do a video tutorial after this.

Thanks. BR. 

DANILO SICARI
SAO PAULO/BRAZIL

**NEWS

I installed the git software on raspberry and clone your repository to a folder. Then i tried to "make", and I attached what i get.
[lib_issue.txt](https://github.com/raysan5/raylib/files/1093630/lib_issue.txt)

**Comment by raysan5** [comment]
Hi @denadaisicari,

Checking the log you share, raylib is compiled ok, you just get some warnings from external libraries.

The problem is when trying to compile the examples, raylib can not be found in the path defined in [Makefile](https://github.com/raysan5/raylib/blob/develop/examples/Makefile#L34)

Just try the following line on compilation (configures raylib path):
```c
make PLATFORM=PLATFORM_RPI -B RAYLIB_PATH=../..
```
But that's an issue and I'll review it.

**Comment by denadaisicari** [comment]
@raysan5 Thanks a lot for your response. I'm keeping trying to run your library into Raspberry Pi 3. I tried these commands (I also have copy the log into a text file for you [log06222017.txt](https://github.com/raysan5/raylib/files/1095240/log06222017.txt))

1 - In directory raylib/scr: **make PLATFORM=PLATFORM_RPI -B RAYLIB_PATH=../..**
 I got some errors

2 - In directory raylib/examples: **make PLATFORM=PLATFORM_RPI -B RAYLIB_PATH=../..**
 I got some errors, cannot find raylib.h

3 - In directory raylib/examples: **make PLATFORM=PLATFORM_RPI**
 I got some errors again, cannot find raylib.h

4 - In directory raylib/examples/text i tried to compile with cgg (even not knowing what I was doing): **gcc -o text_bmfont_ttf text_bmfont_ttf.c**
I got some erros, cannot find raylib.h

5 - In directory raylib/examples/text i open a file (.c): **nano text_bmfont_ttf.c** and wrote the path of lib: **#include <home/pi/raylib/src/raylib.h**
I compile it with gcc: **gcc -o text_bmfont_ttf text_bmfont_ttf.c**
And got same error, cannot find raylib.h

6 - In directory raylib/examples I altered the Makefile: **nano Makefile** and the arguments into it:

**#PLATFORM ?= PLATFORM_DESKTOP
PLATFORM ?= PLATFORM_RPI

#RAYLIB_PATH ?= C:/raylib
RAYLIB_PATH ?= /home/pi/raylib**

And give a command: **make**

So, I got some new different errors

6 - I gave a new: **make** and got some same erros, some differents...

**Comment by raysan5** [comment]
ok, just checked your log and it seems it worked ok, just some warnings and errors compiling physics examples. You can check the compiled examples, they are in the same folder as the source file.

**Comment by denadaisicari** [comment]
It worked! I put ./"example" and it worked great!

I will do a tutorial to contribute: how to install raylib on RPI!

Many thanks!!!

**Comment by raysan5** [comment]
Great to read it finally worked, I will review the Makefile to improve RPI examples building...

**Comment by raysan5** [comment]
Review RPI paths on commit https://github.com/raysan5/raylib/commit/bfa66f446a100eef4e04ffdfe2877feefe503754

Now it should work with: `make PLATFORM=PLATFORM_RPI`
