### ISSUE TITLE
[gpu] Mesh normals are not being passed to the shader

### ISSUE THREAD

**Issue by danemadsen** [raysan5/raylib#3087]
Not sure if ive setup the shader properly but as far as i can tell all GenMesh functions (GenCube, etc) are meant to generate normals automatically, and these normals are meant to be passed to the shaders automatically as 'vertexNormal'.

Apologies if i got this wrong.

![Screenshot from 2023-05-29 17-55-13](https://github.com/raysan5/raylib/assets/11537699/8250c799-0ac0-467f-a19a-fb8f31a96db5)

the cube in this image should be white if a normal is being passed.

[ShaderNormalsTest.zip](https://github.com/raysan5/raylib/files/11589795/ShaderNormalsTest.zip)

**Comment by raysan5** [comment]
@danemadsen Yes, that's right, default shader does not support normals. To use them a custom shader is required.

Default shader is mostly intended for batch system drawing or very simple models. When normals are involved, it's supposed user needs them for lighting so a custom shader is required.
