### ISSUE TITLE
[text] feature request: pass text size to DrawTextEx & ImageTextEx

### ISSUE THREAD

**Issue by actondev** [raysan5/raylib#3088]
Both `DrawTextEx` and `ImageTextEx` call `TextLength`. The call however could accept the text size in the first place.
This can support the following situations:
- When someone wants to draw only part of a bigger text
- When using raylib from another language that don't have null terminating strings, but rather slices (ie pointer + length)

ImGui uses a similar approach: you pass a second `char*` pointer, pointing to the desired `end` of the string (if it's `NULL`, `strlen` is used)

I see two ways of supporting this:
- either modifying the above functions (breaking change)
- creating another version of both functions that accept the extra size parameter

## Motivation
I'm using nim and I'm considering raylib for implementing a gui. Without this, I'd need (in every frame) to reconstruct a string (which is basically a `char*` plus a `length`) just to make it null terminated in order to call raylb.
If we were to be consistent possibly other functions should support this paradigm, but AFAIK these 2 functions seem to be the possible bottleneck when using raylib for a gui.

**Comment by raysan5** [comment]
@actondev I'm afraid I'm not implementing this change. As you mention it's a breaking change for existing functions but adding new functions supporting lengths will breaking library consistency.

**Comment by actondev** [comment]
I understand, and thanks for your quick reply!

**Comment by raysan5** [comment]
@Spiffyk Sorry but that was already proposed in the past and I'm not accepting thove variants, it will require reviewing all functions accepting strings for consistency.

**Comment by Spiffyk** [comment]
@raysan5 Understandable, thanks for the reply and sorry about the necro!
