### ISSUE TITLE
[core] Support OpenRaster format

### ISSUE THREAD

**Issue by Charadon** [raysan5/raylib#3094]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Support for OpenRaster standard would be nice. It's basically a zip file that contains information on things such as layers and other data so editors can use them independently of each other. In the zip archive, there's a file called `mergedimage.png` that is the "final product" so to speak. This is what the library should load when pointed to a .ora file. Currently, the only way to use these files is to make your build system extract these files at the Install Target.

As you can see, quite a few FOSS image editors support the format:
https://en.wikipedia.org/wiki/OpenRaster#Application_support

**Comment by raysan5** [comment]
@Charadon It seems the format is still in draft mode and it does not seem to be any C single-file header-only implementation to integrate it in raylib. For now it's out of scope, feel free to comment if such implementation gets available.

**Comment by Charadon** [comment]
> @Charadon It seems the format is still in draft mode and it does not seem to be any C single-file header-only implementation to integrate it in raylib. For now it's out of scope, feel free to comment if such implementation gets available.

Well, there shouldn't be a need for a ORA specific header file as ORA is *just* a zip file. Since raylib can already read PNG files, it's basically 95% the way there. You can use a single-header library such as miniz (https://github.com/richgel999/miniz) to read the zip file, and then load the PNG file normally.

**Comment by raysan5** [comment]
@Charadon Still, it requires that implementation and afaik, `miniz` is not single-file header-only.

**Comment by Charadon** [comment]
> @Charadon Still, it requires that implementation and afaik, `miniz` is not single-file header-only.

It's actually not hard to make miniz a single header library. You can use a tool like `quom` (https://github.com/Viatorus/quom) to make it one. Also, I can see about implementing an ORA loader into raylib. But I'd want to know if it'd get merged or not before I start.

**Comment by raysan5** [comment]
@Charadon thanks but no plans to add a big library like miniz only to support a format still in draft. It adds uneeded extra complexity and maintenance work to raylib for a feature that most users don't need.

**Comment by Charadon** [comment]
> @Charadon thanks but no plans to add a big library like miniz only to support a format still in draft. It adds uneeded extra complexity and maintenance work to raylib for a feature that most users don't need.

That's a shame. Thought it would be a good idea since apparently Photoshop's format is supported, that it'd be nice if the open standard alternative was too. As for miniz, I could always strip it down to what's needed to open a zip file.

Guess for now, i'm workaround of having `meson` use `unzip` at install target will do =(
