### ISSUE TITLE
[core] `GetTouchPointCount()` keeps returning 1 after the last touch is released

### ISSUE THREAD

**Issue by chemaguerra** [raysan5/raylib#3100]
### Issue description

In `PLATFORM_WEB` (Emscripten) raylib's `GetTouchPointCount()` insists in returning 1 after the last finger touch is released.

`GetTouchPointCount()` correctly returns 0 on start, and then correctly returns the number of fingers touching the screen. However, when the last finger is released, the function keeps returning 1 (instead of 0).

The problem seems to be that `CORE.Input.Touch.currentTouchState` is not used to zero out the touch count after the last `EmscriptenTouchCallback` is received.

As a matter of fact, `IsMouseButtonReleased()` (which makes use of `currentTouchState`) returns true when the last touch is released (which can be used as a cheap workaround).

### Environment

Reproducible on all the Android devices I have access to, using the most recent version of Chrome (=> `PLATFORM_WEB`).

Not happening if I compile/run my project as an .apk (=> Not happening on `PLATFORM_ANDROID`). I don't have any `PLATFORM_DESKTOP` devices with a touchscreen at my disposal to test, though.

### Issue Screenshot

![report](https://github.com/raysan5/raylib/assets/33331554/37fdcd32-6f63-47f4-86fc-169772eaa393)

Reproducible in raylib's multi-touch demo.

### Workaround

The workaround I opted for at the moment is to create a function to query `currentTouchState` and trim myself the list of touches I build with `GetTouchPointId/Position()`.

**Comment by raysan5** [comment]
@chemaguerra Thanks for reporting, I though that issue was already fixed... In any case, multi-touch improvements are required, afair, at this moment the specific touch ids are not read processed properly, required for some gesture events.

**Comment by raysan5** [comment]
@ubkp thanks for the detailed review of the issue and the fix provided! very professional!

**Comment by chemaguerra** [comment]
Awesome. I concur in thanking you. :-)
