### ISSUE TITLE
Examples are not loading on the website (jquery error)

### ISSUE THREAD

**Issue by joetifa2003** [raysan5/raylib#3101]
Please, before submitting a new issue verify and check:

 - [ NAN] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [NAN] My code has no errors or misuse of raylib

### Issue description

Examples are not loading in the website

### Environment

Chrome and firefox

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/62658783/414925f1-dab1-4c2d-b6e2-fce5c4920893)

### Code Example

NAN

**Comment by raysan5** [comment]
@joetifa2003 I'm afraid it could be a local issue. I tried it on my system and it works as expected:

Tested on Windows 10 with Google Chrome 114.0.5735.110 (Official Build) (64-bit)
