### ISSUE TITLE
[rlgl] `rlLoadShaderBuffer()` data clear just after data copying

### ISSUE THREAD

**Issue by Ka-lua** [raysan5/raylib#3104]
The buffer clearing is probably some debugging artifact? This line should be removed:

https://github.com/raysan5/raylib/blob/2e00d16f3d3808defe76d9af75df2dd714c66af2/src/rlgl.h#L4102

**Comment by raysan5** [comment]
@Ka-lua Afaik, that line makes sure the loaded buffer is filled with 0, in case a NULL data buffer is created (as used in the provided example).

That code was contributed so I don't know if that's the best approach, is there any reason we don't want that kind of initialization for the buffer? Could there be any issue if we avoid that kind of initialization?

**Comment by Ka-lua** [comment]
That's right, it clears the buffer to 0 which might be what you want, but that makes the `data` parameter useless. You could do this to only clear the buffer `data` is the null pointer:
```
glBufferData(GL_SHADER_STORAGE_BUFFER, size, data, usageHint? usageHint : RL_STREAM_COPY);
if (data == NULL)
    glClearBufferData(GL_SHADER_STORAGE_BUFFER, GL_R8UI, GL_RED_INTEGER, GL_UNSIGNED_BYTE, 0);
```
