### ISSUE TITLE
[rtextures] `ImageText()` scaling spacing incorrect

### ISSUE THREAD

**Issue by fctr** [raysan5/raylib#3105]
rtextures.c, Line 1243:
int spacing = fontSize/defaultFontSize;

As long as the fontSize is identical to the defaultFontSize, all is good. If you try to scale the font to, say, 4x the default size, the you get the spacing squared, so instead of 4 pixels between letters, you get 16.

The line should read:
int spacing = 1;

Code block at line 1303 already scales everything up, so no need to do it twice.

**Comment by raysan5** [comment]
@fctr Sorry, I don't understand the issue. If `fontSize = 40` and `defaultFontSize = 10`, then `spacing = 4` as expected...

**Comment by fctr** [comment]
MeasureText and DrawText don't match. Do a fontSize = 10 and defaultFontSize = 10, and DrawText("Hello World"). Then do a fontSize = 40 and defaultFontSize = 10, and DrawText("Hello World"). You'll notice for the second one, the spacing between the characters is wrong, and MeasureText returns what it SHOULD be, but not what it actually is.

**Comment by raysan5** [comment]
@fctr Please, could you provide some screenshot or sample code illustrating the issue?

**Comment by fctr** [comment]
`int main()`
`{`
`    InitWindow(640, 480, "RayLib Rocks");`
`    Image i = GenImageColor(640, 300, RED);`
`    ImageDrawText(&i, "This is a test", 1, 1, 10, WHITE);`
`    ImageDrawText(&i, "This is a test", 1, 31, 40, WHITE);`
`    SetTargetFPS(60);`
`    while (!WindowShouldClose())`
`    {`
`        Texture2D t = LoadTextureFromImage(i);`
`        BeginDrawing();`
`        DrawText("This is a test", 1, 1, 10, WHITE);`
`        DrawText("This is a test", 1, 51, 40, WHITE);`
`        DrawTexture(t, 0, 100, WHITE);`
`        EndDrawing();`
`        UnloadTexture(t);`
`    }`
`    UnloadImage(i);`
`    CloseWindow();`
`    return 0;`
`}`

**Comment by fctr** [comment]
Give that a whirl and you'll see what I mean. You'll need to change line 3158 in `rtextures.c` to:
`ImageDrawTextEx(dst, GetFontDefault(), text, position, (float)fontSize, (float)1.0f, color);   // WARNING: Module required: rtext`
and change line 1227 in `rtext.c` to:
`textSize.x = (tempTextWidth + (float)((tempByteCounter - 1) * spacing)) * scaleFactor; // Adds chars spacing to measure`

**Comment by fctr** [comment]
THANK YOU SO MUCH FOR EVERYTHING!

**Comment by raysan5** [comment]
@fctr I'm afraid the proposed change just broke `MeasureTextEx()`:

![image](https://github.com/raysan5/raylib/assets/5766837/684eade0-8b3b-4988-b942-4850fc68b6fd)

```c
            DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);
            DrawRectangle(190, 200, MeasureText("Congrats! You created your first window!", 20), 20, Fade(RED, 0.5f));
```

I'm reverting the change, please, send a PR with an update when reviewed.

**Comment by raysan5** [comment]
Reviewed it and it seems it works as expected
