### ISSUE TITLE
[core] 🌋 Vulkan Support

### ISSUE THREAD

**Issue by MrScautHD** [raysan5/raylib#3111]
Hello!
I would love to see if Raylib get a support for Vulkan, ik it is hard to do vulkan but it would awesome to see it!

Link to the API:
https://www.vulkan.org/

**Comment by raysan5** [comment]
@MrScautHD It has been discussed multiple times, no plans to create a custom backend for it. 

You can use ANGLE for a Vulkan/Metal/Direct3D backend, recently supported by raylib.

**Comment by Mi1ax** [comment]
> oh sry then!
> 
> Where can i find angle?

https://github.com/raysan5/raylib/discussions/2359
