### ISSUE TITLE
[core] Ability for Gamepad Haptics (gamepad vibration etc.)

### ISSUE THREAD

**Issue by LxeC** [raysan5/raylib#3122]
Could a method `GamepadSetVibration()` be added to raylib core?
Gamepad Haptics like vibration are very standard for games especially PC and console.

It would mainly work on the platforms/devices supported. For example on Windows it'd utilize XInput/DInput to vibrate the gamepad. In other unsupported platforms it should not do anything if used (until perhaps support gets better).

It would look like:
`GamepadSetVibration(int gamepad, float leftMotor, float rightMotor)`

leftMotor and rightMotor would be float values from 0.0 to 1.0
Setting leftMotor and rightMotor to 0 would stop vibration.

It could also perhaps be grouped under a `GamepadHaptics` category to make it more future proof. Say for example raylib could add Force Feedback support for Joysticks, Steering Wheels etc. or platform-specific gamepad features.

In that case it would look like:
`GamepadHapticsSetVibration(int gamepad, float leftMotor, float rightMotor)`

**Comment by raysan5** [comment]
@LxeC raylib uses GLFW library on desktop platforms for inputs management. Preferably, this functionality should be added to GLFW first to be exposed by raylib.

**Comment by raysan5** [comment]
This issue depends on an external library, not much can be done on raylib side at the moment.
