### ISSUE TITLE
[raudio] UnloadSound doesn't actually unload the Sound file and causes a memory leak.

### ISSUE THREAD

**Issue by volke0** [raysan5/raylib#3123]
Hi,

I found that loading a sound file via LoadSound() and then sub-sequentially using UnloadSound() doesn't unload the sound data from memory and causes a memory leak.  I found this via Visual Studio 2019 on the memory monitor using Raylib 4.5 in C++. 

This is pretty straightforward to reproduce:
First, simply load a sound file with LoadSound() into a Sound variable, e.g. Sound sfx = LoadSound(file_path.c_str()); .
Then use UnloadSound on sfx and loop the process and see the memory usage skyrocket.

**Comment by raysan5** [comment]
Mmh... It sounds strange, it was not reported before by any raylib user in the last 10 years... 

Did you try debugging to find the exact point where memory is leaked?

**Comment by wwderw** [comment]
I just wrote a little audio player using raylib and it was freeing up when calling unload just fine for that.  But I was using 4.6-dev.

**Comment by raysan5** [comment]
@wwderw Afaik, raudio has not changed much in the last two versions, only some feature additions and multi-channel removal...

**Comment by volke0** [comment]
@raysan5 Forgive me for I'm a bit of a beginner, but yes I noticed it when I tried click a button that would play an audio file, the memory kept going up on the memory monitor.  I then made it so that I loaded all sound files from the beginning of my program instead of loading them as needed.  After that restructure I found there was no more memory leak.

But, I tried to make sure I unloaded the sound variable every time before I loaded the file as needed and it just kept leaking memory.

**Comment by volke0** [comment]
Here is a sample of my sound player code that loads and unloads sound files on the fly:

void SoundPlayer::playSound(string sfx, float max_time)
{
	if (done == true)
	{
		unloadSFX();
		sound = LoadSound(game->sfx_database.SFX[sfx].c_str());
		PlaySound(sound);
		done = false;
	}
}

void SoundPlayer::unloadSFX()
{
	UnloadSound(sound);
}

The sound variable is declared in the header file.

**Comment by raysan5** [comment]
@volke0 Did you try with a simple C example avoiding classes and objects?

**Comment by raysan5** [comment]
I'm afraid I can't verify this issue, more info or sample code is required.
