### ISSUE TITLE
[rmodels] Obj models appear black when a texture is provided

### ISSUE THREAD

**Issue by mode777** [raysan5/raylib#3125]
When a obj model is loaded, it's corresponding mtl file is also loaded and raylib materials are provided. However, when a texture is provided in the mtl file the diffuse color attribute comes back from tinyobj as black. Consequently the model will appear black in the default shader as the diffuse color is multiplied with the texture color. This is hardly the behaviour the user expects. 

What would be the correct behaviour IMO is that the texture replaces the diffuse color. 

This could be implemented in a single line of code. I can submit a pull request if needed.

**BEFORE**
```c
if (materials[m].diffuse_texname != NULL) rayMaterials[m].maps[MATERIAL_MAP_DIFFUSE].texture = LoadTexture(materials[m].diffuse_texname);  //char *diffuse_texname; // map_Kd

rayMaterials[m].maps[MATERIAL_MAP_DIFFUSE].color = (Color){ (unsigned char)(materials[m].diffuse[0]*255.0f), (unsigned char)(materials[m].diffuse[1]*255.0f), (unsigned char)(materials[m].diffuse[2] * 255.0f), 255 }; //float diffuse[3];

```
![image](https://github.com/raysan5/raylib/assets/6848069/4699f860-32f0-4a6c-af02-aba7e4db494d)

**AFTER**
```c
if (materials[m].diffuse_texname != NULL) rayMaterials[m].maps[MATERIAL_MAP_DIFFUSE].texture = LoadTexture(materials[m].diffuse_texname);  //char *diffuse_texname; // map_Kd
else rayMaterials[m].maps[MATERIAL_MAP_DIFFUSE].color = (Color){ (unsigned char)(materials[m].diffuse[0]*255.0f), (unsigned char)(materials[m].diffuse[1]*255.0f), (unsigned char)(materials[m].diffuse[2] * 255.0f), 255 }; //float diffuse[3];
```
![image](https://github.com/raysan5/raylib/assets/6848069/0831fd66-d9fe-4a20-87d1-314cf2288b67)

**Comment by raysan5** [comment]
@mode777 Thanks for reporting! Feel free to send a PR for merging!

**Comment by raysan5** [comment]
Just reviewed it.

**Comment by mode777** [comment]
Wow, your were quicker than me. Thanks for the quick fix! :)
