### ISSUE TITLE
WISH: Add simple maintaince of multiple screens

### ISSUE THREAD

**Issue by milen-prg** [raysan5/raylib#3131]
Please, if can, add simple interface to using of multiple Raylib windows (as in csfml).

**Comment by Peter0x44** [comment]
Duplicate of #1989 , I don't believe there are any plans for it
Linked by ray there is also the section on the raylib wiki about it
https://github.com/raysan5/raylib/wiki/Use-multiple-windows

It does require a non-insignificant refactoring of how rcore works, it's not the most trivial thing to do.

**Comment by Peter0x44** [comment]
also related:
#2940

**Comment by raysan5** [comment]
@Peter0x44 is right on the answer.
