### ISSUE TITLE
[Feature] Better Custom Camera Support

### ISSUE THREAD

**Issue by MrScautHD** [raysan5/raylib#3133]
---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description
Hi, i worked with the Camera3D and saw it is very hard todo a custom camera, like get the rotation...
My idea is to do a abstract class so we can do our own Cameras, or maybe you can improve the camera that we has right now...

What ever i hope you can improve them a bit :)

**Comment by raysan5** [comment]
Camera was already completely redesigned for raylib 4.5. `UpdateCameraPro()` was added for advance users. `raylib-extras` provides several custom camera examples.
