### ISSUE TITLE
[Feature] Add Frustum to disable rendering things outside the Camera View

### ISSUE THREAD

**Issue by MrScautHD** [raysan5/raylib#3136]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Hi, i would like if you can add a Frustum for our Cameras to disable the drawing requets.

### Issue Screenshot

![grafik](https://github.com/raysan5/raylib/assets/65916181/ba00f6fe-e999-4bd0-bb6b-852851758e73)

**Comment by raysan5** [comment]
Frustum culling is up to the user, raylib does not provide a scenegraph to do it.
