### ISSUE TITLE
Key reporting sometimes incorrect on case...

### ISSUE THREAD

**Issue by Ranx0r0x** [raysan5/raylib#3140]
Even though "e" was pressed and not upper case "E" as shown in the print (used for exit in this case), I received an upper case. I've run this multiple times and there seems to be an issue about raylib being able to correctly report the case. It may be my code as well or the Go bindings.  This isn't a critical issue and may be at some other level but thought I'd at least report it. 

I'm creating an event driven front end to communicate with raylib and one of the events is a KeyListenerRegistrationEvent. It keeps a list of Key objects and in the raylib event loop I iterate and check to see if the keyPressed matches any of the keys I'm interested in.

I'd previously used rl.IsKeyPressed but that seemed even more problematic. I've also tried checking the other states. Again, this isn't critical and may be outside raylib itself. 

func (e *engine) sendKeyEvents() {
	keyPressed := rl.GetKeyPressed()
	if keyPressed != 0 {

		for _, key := range e.controller.GetKeysRegistrationEvent().GetKeys() {

			if key.EqualsAscii(keyPressed) {
				e.bus.SendKeyEvent(bus.NewKeyEvent(key))
			}
		}
	}
}

Codebase is at:
https://github.com/vorpalgame/vorpal

INFO: TEXTURE: [ID 4] Texture loaded successfully (2087x1159 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 5] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 5] Texture loaded successfully (2087x1159 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 4] Unloaded texture data from VRAM (GPU)
2023/06/28 13:36:31 E

**Comment by raysan5** [comment]
@Ranx0r0x I've never experienced this issue with the C library version. It's impossible to track this issue if a reproducible minimal C example is not provided.

**Comment by Ranx0r0x** [comment]
Not a problem. As you say, it may be in Golang bindings or may have some other source.
