### ISSUE TITLE
[core] All swipe gestures are being interpreted as `GESTURE_SWIPE_LEFT` on web browsers with Touch Screen.

### ISSUE THREAD

**Issue by ubkp** [raysan5/raylib#3141]
- [x] I tested it on latest raylib version from master branch.
 - [x] I checked and there was a similar issue [#2418](https://github.com/raysan5/raylib/issues/2418) already reported, but no solution was found at the time.
 - [x] My code has no errors or misuse of raylib.

### Issue description

All swipe gestures are being interpreted as `GESTURE_SWIPE_LEFT` on web browsers with Touch Screen:
- Firefox, on Android;
- Chrome, on Android;
- Firefox with `Responsive Design Mode` and `Touch Simulation` enabled, on Linux;
- Chrome with `Toogle Device Toolbar` enabled, on Linux;

After some investigation, it appears that the `event.position[0]` assigned to `GESTURES.Touch.downPositionA` at [rgestures.h#L286](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L286) is usually normalized. However, for some reason, on the Web (HTML5) build, when _Touch_ or _Touch Emulation_ are used, the value being passed to `GESTURES.Touch.downPositionA` is not normalized, therefore causing the `GESTURES.Drag.angle` calculation at [rgestures.h#L310](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L310) to get a wrong result.

The swipe gestures are correctly interpreted on Chrome or Firefox on Linux without _Touch Emulation_.

Probably not the best solution, but a workaround would be adding the following at [rgestures.h#L309](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L309):
```
#if defined( PLATFORM_WEB )
    if (GESTURES.Touch.downPositionA.x > 1.0f || GESTURES.Touch.downPositionA.y > 1.0f)
    {
        GESTURES.Touch.downPositionA.x = Normalize(GESTURES.Touch.downPositionA.x, 0.0f, GetScreenWidth());
        GESTURES.Touch.downPositionA.y = Normalize(GESTURES.Touch.downPositionA.y, 0.0f, GetScreenHeight());
    }
#endif
```
If there isn't any better solution, I can try to send a PR.

### Environment

Platform: _Linux (x86_64)_
Operating System: _Linux Mint 21.1_
OpenGL version: _3.1 Mesa 22.0.5_
GPU: _Intel HD Graphics 3000_

Platform: _Android_
Operating System: _Android 5.1.1_
OpenGL version: _OpenGL ES 1.1/2.0_
GPU: _Mali-400_

### Issue Screenshot

On Firefox (114.2.0) and Chrome (95.0.4638.74) for Android:
![img1](https://github.com/raysan5/raylib/assets/118854183/8355336c-b472-4f93-92a8-8de40944b652)

On Firefox (102.11.0esr 64-bit) for Linux:
![img2](https://github.com/raysan5/raylib/assets/118854183/8c2abb94-9dcb-4f32-a79c-120f43e77f63)

On Chrome (114.0.5735.106 64-bit) for Linux:
![img3](https://github.com/raysan5/raylib/assets/118854183/1202f83a-e201-42ce-b27d-ed702fe63b6f)

### Code Example

Minimal reproduction code to test the issue:
```
#include "raylib.h"

#if defined(PLATFORM_WEB)
    #include <emscripten/emscripten.h>
#endif

int lastSwipe = GESTURE_NONE;

void Update(void) {
    const int gesture = GetGestureDetected();
    if (gesture == GESTURE_SWIPE_UP || gesture == GESTURE_SWIPE_RIGHT || gesture == GESTURE_SWIPE_LEFT || gesture == GESTURE_SWIPE_DOWN) { lastSwipe = gesture; }

    BeginDrawing();
    ClearBackground(RAYWHITE);
    DrawRectangleLinesEx({0, 0, 400, 400}, 2.0f, BLACK);
    DrawText("Swipe on the screen.", 95, 195, 20, BLACK);
    DrawText("Last swipe:", 25, 20, 20, BLACK);
    DrawRectangle(70, 50, 20, 20, lastSwipe == GESTURE_SWIPE_UP    ? BLUE : LIGHTGRAY);
    DrawRectangle(50, 70, 20, 20, lastSwipe == GESTURE_SWIPE_LEFT  ? BLUE : LIGHTGRAY);
    DrawRectangle(90, 70, 20, 20, lastSwipe == GESTURE_SWIPE_RIGHT ? BLUE : LIGHTGRAY);
    DrawRectangle(70, 90, 20, 20, lastSwipe == GESTURE_SWIPE_DOWN  ? BLUE : LIGHTGRAY);
    EndDrawing();
}

int main(void) {
    InitWindow(400, 400, "Swipe Test");
    #if defined(PLATFORM_WEB)
        emscripten_set_main_loop(Update, 0, 1);
    #else
        SetTargetFPS(60);
        while (!WindowShouldClose()) { Update(); }
    #endif
    CloseWindow();
    return 0;
}
```

**Comment by SAOMDVN** [comment]
Hi @ubkp. Nice work on the PR! Do you experience incorrect Pinch behaviour on your devices too? (I mentioned it in #1963)
I hope you can take a look at this issue
