### ISSUE TITLE
[rcore] Missing focus window API

### ISSUE THREAD

**Issue by bztsrc** [raysan5/raylib#3142]
Hi,

I've just found out that the API for focusing the window is missing (not the same as clearing the unfocused flag).

In one of my projects, I have to open a native open file modal to allow users to select a file. When the file is selected and the modal is closed, the raylib window should become active again. This works on all platforms, except on Windows. There if the raylib window is fullscreen, then it gets iconified when the modal is opened, so I have to manually focus it after the modal is closed to workaround the problem and get the raylib window back.

The required modification is minimal:
```diff
diff --git a/src/raylib.h b/src/raylib.h
index cceaa210..be160f1e 100644
--- a/src/raylib.h
+++ b/src/raylib.h
@@ -958,6 +958,7 @@ RLAPI void SetWindowMonitor(int monitor);                         // Set monitor
 RLAPI void SetWindowMinSize(int width, int height);               // Set window minimum dimensions (for FLAG_WINDOW_RESIZABLE)
 RLAPI void SetWindowSize(int width, int height);                  // Set window dimensions
 RLAPI void SetWindowOpacity(float opacity);                       // Set window opacity [0.0f..1.0f] (only PLATFORM_DESKTOP)
+RLAPI void SetWindowFocused(void);                                // Set window focused (only PLATFORM_DESKTOP)
 RLAPI void *GetWindowHandle(void);                                // Get native window handle
 RLAPI int GetScreenWidth(void);                                   // Get current screen width
 RLAPI int GetScreenHeight(void);                                  // Get current screen height
diff --git a/src/rcore.c b/src/rcore.c
index d02ea2b9..7e1735cc 100644
--- a/src/rcore.c
+++ b/src/rcore.c
@@ -1705,6 +1705,14 @@ void SetWindowOpacity(float opacity)
 #endif
 }
 
+// Set window focused
+void SetWindowFocused(void)
+{
+#if defined(PLATFORM_DESKTOP)
+    glfwFocusWindow(CORE.Window.handle);
+#endif
+}
+
 // Get current screen width
 int GetScreenWidth(void)
 {
```
Hope this will be useful to others as well.

Cheers,
bzt

**Comment by raysan5** [comment]
@bztsrc Thanks for noticing it! Added proposed function!

**Comment by bztsrc** [comment]
Thank you very much @raysan5! Now my project's [raylib port is complete](https://gitlab.com/bztsrc/meg4/-/commit/bb176fdab10a69b31a17d64a250b505190aff9d5) :-)

I would like to say, that I have ported [MEG-4](https://bztsrc.gitlab.io/meg4/) to several backends, and anyone can see, the raylib backend's code is the smallest and simplest (18K, about 450 SLoc). It was by far the easiest to implement, took only a few hours, no more (in comparition, all the others took several days). This is thanks to your great API and very useful examples in the repo! I love it!

Cheers,
bzt

**Comment by raysan5** [comment]
@bztsrc Wow! MEG-4 is really impressive! Congratulations!

Glad to know raylib backend was easy to implement! 😄 

By the way, you have an amazing list of projects! Really inspiring!
