### ISSUE TITLE
[android] Can't change screen orientation

### ISSUE THREAD

**Issue by makimy** [raysan5/raylib#3145]
Hi !

Did I miss something or there is no `portrait` screen orientation support for android ? I've tried to change it in `AndroidManifest.xml` but it does not affect anything.

Also was trying to play with Camera2d options (rotation in particular) but it works differently on different devices so i don't bother with it anymore. 

Any ideas ?

**Comment by makimy** [comment]
idk what is the problem, simply hardcoded `AConfiguration_setOrientation(CORE.Android.app->config, ACONFIGURATION_ORIENTATION_PORT);` into initwindow().

**Comment by makimy** [comment]
Actually it happened because of this lines (yes, i made a 200x200 window):

```c
 // TODO: Automatic orientation doesn't seem to work
    if (width <= height)
    {
```

**Comment by 9912** [comment]
Also faced this issue, using [Raymob](https://github.com/Bigfoot71/Raymob), change in gradle.properties in android studio, in order to set **fixed** oreintation

**Comment by makimy** [comment]
You can try to play with these lines of code I mentioned above:

https://github.com/raysan5/raylib/blob/master/src/rcore.c#L814

It doesn't look it supports automatic changes, but it makes it either `landscape` or `portrait` right there.
