### ISSUE TITLE
v4.5 Windows exe installer won't run

### ISSUE THREAD

**Issue by macxcool** [raysan5/raylib#3146]
### Issue description

I'm testing the install of the 4.5 exe installer in a Windows 10 VM. The installer won't launch, either by clicking or from the command line. I think a window briefly opens, but is gone so quickly that I'm not sure.

I can install with the old 4.2.0 installer. The 4.5 installer works fine on my laptop, which is Windows 10 as well.

I'm preparing this to install on school computers in a computer lab, which won't be VMs, so if this is just a VM problem, I'm fine with that.

### Environment

I'm trying to install in a Windows 10 21H2 VM, so OpenGL is only v1.1.0. Is OpenGL relevant for the installer?

**Comment by raysan5** [comment]
@macxcool Actually, that's the issue. Latest installer has been created using raylib and using OpenGL 3.3.

**Comment by macxcool** [comment]
OK. That makes sense. And building your installer with your own library? That's kind of awesome!

Now that I know what's happening I can deal with it. The programming teacher I'm working with will be happy.

**Comment by macxcool** [comment]
Actually. This is still a problem. I tested, and when installed headless with the '/S' (silent) switch, it still fails. The reason why I consider this a problem is this:
1. Windows doesn't set up the console until a user logs in. That means that OpenGL capabilities, etc. aren't available to the system before login.
2. Installing as the 'System' user can be done, normally, when there is no user logged in
3. The '/S' switch is designed for such installations using the System user when no user is logged in
4. The previous version of the installer worked fine like this, so this could be considered a regression

We use Microsoft's System Centre to install software, and _it_ uses a System installation with, when possible, silent command line switches, as is supported by the Inno Setup framework that you're using. When we deploy this to a school lab, for instance, we don't sit down in front of each computer. All that is required is that the computer be on and talking to the network with Windows booted up.
If the installer requires OpenGL with the '/S' switch, this will not work at all, and it worked previously. Is there any way to specify that with '/S' OpenGL isn't required or the OpenGL check is skipped, since there's no graphical interface at all? I can't think of an example right now, but I know that other software installers do something like this.

**Comment by raysan5** [comment]
@macxcool `rInstallFriendly` uses the `-s` command-line-parameters convention (`--silent` also supported), instead of the `/S` Windows style command-line. On that mode, no window is open and so no OpenGL is required.

**Comment by macxcool** [comment]
Are you saying that rInstallFriendly is what you're using? I thought you were using the Inno Setup system. Did you switch to a different install system?

**Comment by raysan5** [comment]
Yes, I switched to `rInstallFriendly` tool for latest `raylib 4.5 Windows Installer`.

Just reviewed it and I'm afraid `raylib 4.5 Windows Installer` was created with an early version of `rInstallFriendly` and silent mode was not available yet. I will update it for next release.

Easies solution is just installing on a Windows machine manually and copy `C:/raylib` directory to all required machines. The installation is self-contained and portable.

**Comment by macxcool** [comment]
And I'm sorry about the '/S', I mean '/SP- /VERYSILENT /NORESTART'. '/S' was just meant to be a placeholder for Silent switches.

**Comment by macxcool** [comment]
Oh. OK. The switch to another installer framework is what threw me. I didn't realize because I couldn't get it to work at all.
I _will_ just zip up the raylib folder and deploy it that way. I wasn't completely sure about it being 'portable', although I suspected as much. Thanks.

**Comment by raysan5** [comment]
@macxcool FYI, this is how the new installer looks like (visual style is random at init):
 
![raylib_45_installer_package](https://github.com/raysan5/raylib/assets/5766837/82841ff0-c136-4b48-820f-21b7ef13b987)

**Comment by macxcool** [comment]
Very cool. I like it. ;-)

**Comment by macxcool** [comment]
Is this version 'portable' in a way that the previous one wasn't? I usually put applications in c:\Program Files\ or c:\Program Files (x86)\. Because of the reliance on MinGW, I had put raylib into c:\ProgramData\ so that there were no spaces in paths. I had to use a regular expression to find all the instances of c:\raylib in all the config/library/readme files etc. and replace it with c:\ProgramData\raylib. Is that going to be unnecessary now?

**Comment by raysan5** [comment]
Yes, it's the same, in both cases installer is just like an "unzipper" for the directory. Yeah, there could be some reference to C:/raylib in some of the compilation scripts, that's the default installation directory.

**Comment by macxcool** [comment]
OK. Cool. I'm good, then. I just 7-zipped the folder up and then I unzip it and create a shortcut. It all works fine. Portable is good.
Thanks
