### ISSUE TITLE
[raymath] Parameter names collide with windows.h macros

### ISSUE THREAD

**Issue by BerkUnver** [raysan5/raylib#3159]
### Issue description
I'm using raymath as a standalone math library without the rest of raylib.
windows.h defines "near" and "far" macros that collide with the parameter names of MatrixPerspective and MatrixOrtho. This causes confusing compiler errors if you include windows.h before raymath.h. It would be great if these parameters were to be renamed so you don't have to rely on header include order or undefs to avoid this.

### Environment
Windows 10, 2022 MSVC compiler.

**Comment by raysan5** [comment]
I'm usually very reticent with the infamous `windows.h` collisions but in this case I will review those parameters names in `raymath.h`.
