### ISSUE TITLE
[build] Proper MSVC Compiler support instead of mingw32

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib#316]
Can you properly support MSVC compiler for windows? 
Maybe make a .bat file with the commands?
Or fix the errors with jar_xm.h when building in MSVS. 
I tried all the things said in the wiki still not compiling. 
![capture](https://user-images.githubusercontent.com/20334207/27769411-3cff0a26-5f46-11e7-85e8-807501b32296.PNG)

**Comment by raysan5** [comment]
Have you tried the [VS2015 project provided](https://github.com/raysan5/raylib/tree/develop/project/vs2015)? It works ok on my side.

![image](https://user-images.githubusercontent.com/5766837/27769541-5b4bf792-5f2c-11e7-9817-9a7ede67ceb1.png)

Just in case, try using develop branch but master should work ok.

**Comment by msmshazan** [comment]
Yes,I'm using it.

**Comment by msmshazan** [comment]
But it doesn't work

**Comment by msmshazan** [comment]
It would be nice if it was a .bat file like how handmadehero does it.

**Comment by raysan5** [comment]
ok, it seems related to Release mode, please, could you try Debug mode?

**Comment by msmshazan** [comment]
Same issue

**Comment by msmshazan** [comment]
The error is in jar_xm.h 
The error states '__func__': undeclared identifier

**Comment by raysan5** [comment]
Could you also send me a .bat sample to see how it's done?

Command line parameters for compiler should be:
```
/GS /TC /analyze- /W3 /Zc:wchar_t /I"C:\GitHub\raylib\project\vs2015\..\..\src" /ZI /Gm /Od /Fd"Debug\vc140.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_DEBUG" /D "_CONSOLE" /D "PLATFORM_DESKTOP" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /Oy- /MDd /Fa"Debug\" /EHsc /nologo /Fo"Debug\" /Fp"Debug\core_basic_window.pch" 
```
Command line parameters for linker should be:
```
/OUT:"C:\GitHub\raylib\project\vs2015\Debug\core_basic_window.exe" /MANIFEST /NXCOMPAT /PDB:"C:\GitHub\raylib\project\vs2015\Debug\core_basic_window.pdb" /DYNAMICBASE "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" "glfw3.lib" "C:\GitHub\raylib\project\vs2015\Debug\raylib.lib" /DEBUG /MACHINE:X86 /INCREMENTAL /PGD:"C:\GitHub\raylib\project\vs2015\Debug\core_basic_window.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"Debug\core_basic_window.exe.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /LIBPATH:"C:\GitHub\raylib\project\vs2015\external\glfw3\lib\win32" /LIBPATH:"C:\GitHub\raylib\project\vs2015\external\openal_soft\lib\win32" /TLBID:1 
```

**Comment by msmshazan** [comment]
Here's my compiler flags ```/GS /TC /analyze- /W3 /Zc:wchar_t /I"E:\shazan\raylib-master\project\vs2015\..\..\src\external\openal_soft\include" /I"E:\shazan\raylib-master\project\vs2015\..\..\src\external\glfw3\include" /I"E:\shazan\raylib-master\project\vs2015\..\..\src\external" /ZI /Gm /Od /Fd"Debug\raylib.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_DEBUG" /D "_LIB" /D "_UNICODE" /D "UNICODE" /D "GRAPHICS_API_OPENGL_33" /D "PLATFORM_DESKTOP" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /Oy- /MDd /Fa"Debug\" /EHsc /nologo /Fo"Debug\" /Fp"Debug\raylib.pch" ```

**Comment by msmshazan** [comment]
@raysan5  I'm trying to compile the library not the example

**Comment by msmshazan** [comment]
@raysan5 I think you compiled the library already

**Comment by raysan5** [comment]
Just trying to reproduce the error but it works on my side...

I'm trying to clean and recompile, actually, I solved the issue with Release mode.

Don't know where is the problem...

**Comment by msmshazan** [comment]
It's in jar_xm.h the Debug macro does it

**Comment by raysan5** [comment]
Are you working on Windows 10? Visual Studio 2015?

Please, could you try [raylib develop branch](https://github.com/raysan5/raylib/tree/develop)?

**Comment by msmshazan** [comment]
Yes , Windows 10 ,VS 15

**Comment by msmshazan** [comment]
@raysan5  I would prefer if raylib had prebuilt binaries like SDL2 does

**Comment by msmshazan** [comment]
Still getting same errors

**Comment by msmshazan** [comment]
Its the identical same errors.

**Comment by msmshazan** [comment]
@raysan5 The errors are same as in the image i uploaded.

**Comment by msmshazan** [comment]
@raysan5 where did you get jar_xm.h

**Comment by raysan5** [comment]
Just uploaded a reviewed VS2015 project (https://github.com/raysan5/raylib/commit/65cf3080a5392ebef594c684ee75f9fa207dac77) with Debug and Release properly configured but it seems not related to this issue. :(

`jar_xm.h` was created by a user but it works ok on my side, it's just used to play XM module files on audio, you can just undefine `SUPPORT_FILEFORMAT_XM` in audio.c to avoid that file inclusion.

Just added VS2015 raylib compiled release files: https://github.com/raysan5/raylib/tree/develop/release/win32/msvc

**Comment by msmshazan** [comment]
@raysan 64bit binaries would be nice.

**Comment by msmshazan** [comment]
Can you tell me what does this mean ```__func__ undeclared identifier```

**Comment by raysan5** [comment]
The issue you get is related to `DEBUG(...)` macro defined at line 318, but it should be ok... maybe you have that macro defined somewhere else... Do you have any other IDE a part from VS2015 installed in your system? MonoDevelop? Code:Blocks? Other Visual Studio versions?

**Comment by raysan5** [comment]
Just try to commenting `DEBUG(...)` lines in the code (there are only 7 lines) to see if it works.

**Comment by msmshazan** [comment]
@raysan5 no need to comment DEBUG change ```#ifdef JAR_XM_DEBUG``` to```#if JAR_XM_DEBUG``` in line 311 in jar_xm.h

**Comment by msmshazan** [comment]
And in line 785 ```static inline void memcpy_pad(void* dst, size_t dst_len, const void* src, size_t src_len, size_t offset)``` to ```static void memcpy_pad(void* dst, size_t dst_len, const void* src, size_t src_len, size_t offset)```

**Comment by raysan5** [comment]
Does it work with those changes?

**Comment by msmshazan** [comment]
@raysan5  I made a .bat file script to build without opening visual studio just like makefiles.
Here it is,

```bat
@echo off
set Libraries=glfw3.lib raylib.lib user32.lib gdi32.lib shell32.lib
set CompilerFlags= /MD /Z7 /FC /nologo 
set LinkerFlags=-subsystem:Console 
set bits=x86
set LibraryLocation=..\deps\lib\%bits%\
for %%* in (.) do set CurrDirName=%%~nx*
mkdir build > NUL 2> NUL
pushd build
IF NOT DEFINED vcvars_called (
    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %bits%
    set vcvars_called=1
)
REM xcopy %LibraryLocation%glfw3.dll > NUL 2> NUL
ctime -begin %CurrDirName%.ctm
cl %CompilerFlags% ..\code\main.cpp /I..\deps\include   /link -incremental:no /LIBPATH:%LibraryLocation% %Libraries%  %LinkerFlags% -out:main.exe
set LastError=%ERRORLEVEL%
ctime -end %CurrDirName%.ctm
popd
```

**Comment by raysan5** [comment]
Implemented changes in commit https://github.com/raysan5/raylib/commit/53fbeeea718db5ab0a5ff16fc7971144588685cd

Added build.bat for reference in commit https://github.com/raysan5/raylib/commit/013f80f3a3b5875559f499694d1128ae36b7ba92
