### ISSUE TITLE
[rcamera] Incocsistent macro naming convention with rlights.h?

### ISSUE THREAD

**Issue by 9tin9tin9** [raysan5/raylib#3161]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

examples/shaders/rlights.h uses the macro `RLIGHTS_IMPLEMENTATION`. However the macros `CAMERA_IMPLEMENTATION` and `CAMERA_STANDALONE` in rcamera.h are not prefixed with `R`. Is this intentional?

**Comment by raysan5** [comment]
@9tin9tin9 that's a good catch... `camera.h` was renamed recently to `rcamera.h` but macro was kept as previous module name... same happens with `rgestures.h` module. I'm reviewing them.
