### ISSUE TITLE
[rmodels] Some faces of the gltf model are not rendered ?

### ISSUE THREAD

**Issue by nicklhy** [raysan5/raylib#3165]
### Issue description

I tried to load and render a gltf mesh model like below

```
Model model = LoadModel("/path/to/my/model.glb");

while (!WindowShouldClose()) {
    UpdateCamera(&camera, CAMERA_THIRD_PERSON);

    BeginDrawing();

    ClearBackground(RAYWHITE);

    BeginMode3D(camera);

    DrawModel(model, position, 1.0f, WHITE);  // Draw animated model
    DrawGrid(10, 1.0f);

    EndMode3D();

    EndDrawing();
}
```
The rendering result is like below.
![model_render](https://github.com/raysan5/raylib/assets/1146226/1cbc0d99-3b1e-4f15-a4d2-828d84242fed)

The model opened in blender is like below.
![blender_image](https://github.com/raysan5/raylib/assets/1146226/5ca32be3-c8d0-4a2a-af87-49295fc47461)

It looks like some faces of the mesh model are not rendered at all. And the color of other faces also looks quite different.

### Environment

OS：Ubuntu 20.04

**Comment by nicklhy** [comment]
raylib 4.5
INFO: GL: OpenGL device information:                                                                 
INFO:     > Vendor:   Intel                                                                          
INFO:     > Renderer: Mesa Intel(R) UHD Graphics (TGL GT1)                                           
INFO:     > Version:  4.6 (Core Profile) Mesa 21.2.6                                                 
INFO:     > GLSL:     4.60

**Comment by raysan5** [comment]
I think it could be related to the way the gltf is created. raylib uses cgltf library to load models.

**Comment by nicklhy** [comment]
I set the log level to debug and got this warning:
```
WARNING: MODEL: [asset/models/aircraft_carrier.glb] Indices data converted from u32 to u16, possible loss of data
WARNING: MODEL: [asset/models/aircraft_carrier.glb] Indices data converted from u32 to u16, possible loss of data
WARNING: MODEL: [asset/models/aircraft_carrier.glb] Indices data converted from u32 to u16, possible loss of data
WARNING: MODEL: [asset/models/aircraft_carrier.glb] Indices data converted from u32 to u16, possible loss of data
```

I also noticed that there is a restriction warning in `rmodels.c:LoadGLTF`,

```
- Vertex attibute types and formats supported:
    > Vertices (position): vec3: float
    > Normals: vec3: float
    > Texcoords: vec2: float
    > Colors: vec4: u8, u16, f32 (normalized)
    > Indices: u16, u32 (truncated to u16)
```

Does it mean raylib is only able to load mesh models with vertex number less than 65535 (max val of uint16_t) ?

**Comment by nicklhy** [comment]
> 

Great thanks for your detailed reply ! That helps a lot for me to understand the current design.
I just tried the obj format, but it seems the vertex/face number could still be a problem.
```
test_model_loading: /path/to/xxx-project/build/_deps/raylib-src/src/external/tinyobj_loader_c.h:1105: parseLine: Assertion `3 * num_f < TINYOBJ_MAX_FACES_PER_F_LINE' failed.
```
I guess it is necessary to compress my model (vertex/edge/face numbers) in blender before use it in raylib.

**Comment by raysan5** [comment]
This issue seems to be external to raylib, maybe related to `cgltf.h` library or how the model is exported from the 3d creation software. Please note that glTF format is a complex format with many export options and also several versions, not all possibilities are supported.

**Comment by kilometer3604** [comment]
It seems cgltf supports u32 vertices ([link](https://github.com/jkuhlmann/cgltf/issues/111)). I wonder if raylib can handle it by changing type of `Mesh.indices` from `unsigned short` to `unsigned int` (all related castings are needed to change as well).

**Comment by raysan5** [comment]
@whenov Nope, raylib supports multiple platforms and some of them use OpenGL ES 2.0 that does not support uint for indices, only ushort.
