### ISSUE TITLE
[question] Is there a way to prevent the game window from closing when pressing ESC?

### ISSUE THREAD

**Issue by Voxelstice** [raysan5/raylib#3171]
Couldn't find anything in the issues section about this, so i'm making a new issue.

The question is in the title. Without recompiling the library if possible.
I already looked at the library's code and it doesn't seem like you put anything to make it not close on ESC.
https://github.com/raysan5/raylib/blob/bc9c06325481c0b4b5a2db3b2a8281465569ba3e/src/rcore.c#L5482

**Comment by raysan5** [comment]
@Voxelstice Yes, use `SetExitKey(KEY_NULL)`.
