### ISSUE TITLE
[core] `GESTURE_DOUBLETAP` not working with Touch for web.

### ISSUE THREAD

**Issue by ubkp** [raysan5/raylib#3174]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

While testing, I noticed that `GESTURE_DOUBLETAP` wasn't working with Touch for web.

After https://github.com/raysan5/raylib/issues/3100 and https://github.com/raysan5/raylib/issues/3167, I spotted a somewhat similarity here.

Upon a long review, the problem appears to be that `ProcessGestureEvent()` is getting called multiple times for the same event for web:

1. When a touch starts, `MouseButtonCallback()` calls `ProcessGestureEvent()`;
2. `ProcessGestureEvent()` then handles that touch correctly;
3. But, since a touch happened, `EmscriptenTouchCallback()` also calls `ProcessGestureEvent()`;
4. `ProcessGestureEvent()` then also handles the touch correctly, but ends up moving further in its logic;
5. Then, the touch ends, causing `MouseButtonCallback()` to call `ProcessGestureEvent()`;
6. `ProcessGestureEvent()` again then handles that touch correctly, but ends even further in its logic;
7. And, again, since a touch ended, `EmscriptenTouchCallback()` also calls `ProcessGestureEvent()`;
8. `ProcessGestureEvent()` then handles that touch correctly yet again, ending even further in its logic.

In this scenario (Touch for web), `ProcessGestureEvent()` should only run twice (once for `EmscriptenTouchCallback()` `EMSCRIPTEN_EVENT_TOUCHSTART` and once for `EmscriptenTouchCallback()` `EMSCRIPTEN_EVENT_TOUCHEND`). However, `EmscriptenTouchCallback()` and `MouseButtonCallback()` run independently. And, complicating things, both `PLATFORM_DESKTOP` and `PLATFORM_WEB` share the same `MouseButtonCallback()` and also the same `SUPPORT_GESTURES_SYSTEM` and `SUPPORT_MOUSE_GESTURES` defines.

This problem is likely also the cause of many other gestures inconsistencies, but was more noticeable on `GESTURE_DOUBLETAP`.

### Proposed solution

The only way I found to solve this without major reworks was finding some criteria that was only present on Touch for web. After extensive testing, _Mouse Position_ was the best candidate. On Touch for web, its `Vector2` will be zero; elsewhere, _Cursor_ should be present, thus having some non-zero value.

That criteria can then be added with an `#if defined(PLATFORM_WEB)` to `MouseButtonCallback()` to stop it from calling `ProcessGestureEvent()`, leaving these touch events to be handled by `EmscriptenTouchCallback()`. This shouldn't break other platforms because Emscripten should be present only on `PLATFORM_WEB`.

Tested this solution successfully on Firefox (115.0.1) and Chrome (95.0.4638.74) for Android; Firefox (102.11.0esr 64-bit) and Chrome (114.0.5735.106 64-bit) with _Touch Emulation_ enabled for Linux; and native on Linux.

Will send a PR with the proposed changes shortly.

### Environment

Platform: _Linux_
Operating System: _Linux Mint 21.1 (x86_64)_
OpenGL version: _3.1 Mesa 22.0.5_
GPU: _Intel HD Graphics 3000_

Platform: _Android_
Operating System: _Android 5.1.1_
OpenGL version: _OpenGL ES 1.1/2.0_
GPU: _Mali-400_

### Issue Screenshot

![img](https://github.com/raysan5/raylib/assets/118854183/fd103a18-2cb1-4dff-b7e4-39e8a9efc05e)

### Code Example

Minimal reproduction code to test the issue:

```
#include "raylib.h"

#if defined(PLATFORM_WEB)
    #include <emscripten/emscripten.h>
#endif

#define GESTURE_LOG_SIZE 20
char gestureLog[GESTURE_LOG_SIZE][12] = { "" };
int gestureLogIndex = GESTURE_LOG_SIZE;
int previousGesture = 0;
char const *GetGestureName(int i) {
   switch (i) {
      case 0:   return "None";        break;
      case 1:   return "Tap";         break;
      case 2:   return "Double Tap";  break;
      case 4:   return "Hold";        break;
      case 8:   return "Drag";        break;
      case 16:  return "Swipe Right"; break;
      case 32:  return "Swipe Left";  break;
      case 64:  return "Swipe Up";    break;
      case 128: return "Swipe Down";  break;
      case 256: return "Pinch In";    break;
      case 512: return "Pinch Out";   break;
      default:  return "Unknown";     break;
   }
}
int logMode = 1;
Rectangle logButton1 = {53, 7, 48, 26};
Rectangle logButton2 = {108, 7, 36, 26};
Vector2 gestureLogPosition = {10, 10};

void Update(void) {
    // Handling:
    int i, ii;
    const int currentGesture = GetGestureDetected();
    if (IsMouseButtonReleased(MOUSE_BUTTON_LEFT)) {
        if (CheckCollisionPointRec(GetMousePosition(), logButton1)) {
            switch (logMode) {
              case 3:  logMode=2; break;
              case 2:  logMode=3; break;
              case 1:  logMode=0; break;
              default: logMode=1; break;
            }
        } else if (CheckCollisionPointRec(GetMousePosition(), logButton2)) {
            switch (logMode) {
              case 3:  logMode=1; break;
              case 2:  logMode=0; break;
              case 1:  logMode=3; break;
              default: logMode=2; break;
            }
        }
    }
    int fillLog = 0;
    if (currentGesture !=0) {
        if (logMode == 3) {        // 3 hides repeated events and hide hold events
            if ((currentGesture != 4 && currentGesture != previousGesture) || currentGesture < 3) { fillLog = 1; }
        } else if (logMode == 2) { // 2 shows repeated events but hide hold events
            if (currentGesture != 4) { fillLog = 1; }
        } else if (logMode == 1) { // 1 hides repeated events
            if (currentGesture != previousGesture) { fillLog = 1; }
        } else {                   // 0 shows repeated events
            fillLog = 1;
        }
    }
    if (fillLog) {
        previousGesture = currentGesture;
        if (gestureLogIndex <= 0) { gestureLogIndex = GESTURE_LOG_SIZE; }
        gestureLogIndex--;
        TextCopy(gestureLog[gestureLogIndex], GetGestureName(currentGesture));
    }

    // Drawing:
    BeginDrawing();
    ClearBackground(RAYWHITE);
    DrawText("Log", gestureLogPosition.x, gestureLogPosition.y, 20, BLACK);
    for (i = 0, ii = gestureLogIndex; i < GESTURE_LOG_SIZE; i++, ii = (ii + 1) % GESTURE_LOG_SIZE) {
        DrawText(gestureLog[ii], gestureLogPosition.x, gestureLogPosition.y + 410 - i*20, 20, (i == 0 ? MAROON : LIGHTGRAY));
    }
    Color logButton1Color, logButton2Color;
    switch (logMode) {
      case 3:  logButton1Color=MAROON; logButton2Color=MAROON; break;
      case 2:  logButton1Color=GRAY;   logButton2Color=MAROON; break;
      case 1:  logButton1Color=MAROON; logButton2Color=GRAY;   break;
      default: logButton1Color=GRAY;   logButton2Color=GRAY;   break;
    }
    DrawRectangleRec(logButton1, logButton1Color);
    DrawText("Hide", logButton1.x + 7, logButton1.y + 3, 10, WHITE);
    DrawText("Repeat", logButton1.x + 7, logButton1.y + 13, 10, WHITE);
    DrawRectangleRec(logButton2, logButton2Color);
    DrawText("Hide", logButton1.x + 62, logButton1.y + 3, 10, WHITE);
    DrawText("Hold", logButton1.x + 62, logButton1.y + 13, 10, WHITE);
    EndDrawing();
}

int main(void) {
    InitWindow(400, 450, "Doubletap test");
    #if defined(PLATFORM_WEB)
        emscripten_set_main_loop(Update, 0, 1);
    #else
        SetTargetFPS(60);
        while (!WindowShouldClose()) Update();
    #endif
    CloseWindow();
    return 0;
}
```

**Comment by raysan5** [comment]
@ubkp thank you very much for the detailed analisis and review! The criteria for web looks ok to me.
