### ISSUE TITLE
[rshapes] Drawing functions relating to circles have usage of sinf() and cosf() mixed up

### ISSUE THREAD

**Issue by RokasPuzonas** [raysan5/raylib#3180]
### Issue description

Currently when calling `DrawCircleSector`, when drawing a from angle 0° -> 30° you get a circle draw between the angles 270° -> 300°. Because when calculating a vertex position on the circle it is using this formula (gotten from [here](https://github.com/raysan5/raylib/blob/master/src/rshapes.c#L397C13-L397C102)):
```c
float circle_x = center.x + sinf(DEG2RAD*angle)*radius;
float circle_y = center.y + cosf(DEG2RAD*angle)*radius;
```
This results in the x and y coordinates being flipped.

When it should have been this:
```c
float circle_x = center.x + cosf(DEG2RAD*angle)*radius;
float circle_y = center.y + sinf(DEG2RAD*angle)*radius;
```

cosf() needs to be used with the x coordinate and sinf() needs to be used with the sinf coordinate.

Reading [rshapes.c](https://github.com/raysan5/raylib/blob/master/src/rshapes.c) I found 2 categories of affected functions by this bug:
* A - Functions were you can visibly see a difference between the drawn shape between the fixed and not fixed version.
* B - Functions were you can't see a difference between the fixed and not fixed version. This is because these kinds of functions draw things symmetricaly.

These are the functions affected by this bug by it's category:
* A -  `DrawCircleSector`, `DrawCircleSectorLines`, `DrawRing`, `DrawRingLines`, `DrawEllipse`, `DrawEllipseLines`.
* B - `DrawRectangleRoundedLines`, `DrawRectangleRounded`, `DrawPoly`, `DrawPolyLines`, `DrawPolyLinesEx`, `DrawCircleGradient`, `DrawCircleLines`.

I believe all functions from both categories need to be fixed, even if the difference is not noticeable in the B category. So this bug would not occur again in the future, when a function would be added and buggy code would be reused from one of the B category functions.  

### Environment

Platform: Desktop
Operating system: Linux 6.3.8-arch1-1 x86_64
OpenGL version: OpenGL ES 3.2
GPU: GeForce GTX 1660 super

### Issue Screenshot

How it currently looks:
![image](https://github.com/raysan5/raylib/assets/59289995/b30d26d7-7423-4583-aaed-2cfa2d9f2e4a)

How I expected it to look:
![image](https://github.com/raysan5/raylib/assets/59289995/bd88ed80-b0d0-43b8-abb2-441f4ff65bd7)

### Code Example

```c
#include <raylib.h>
#include <raymath.h>

int main() {
	InitWindow(800, 450, "Reproduction");
	SetTargetFPS(60);

	while (!WindowShouldClose())
	{
		BeginDrawing();
		ClearBackground(RAYWHITE);

		float angle = (int)(GetTime()*100) % 360;

		// Example 1.
		DrawCircleSector({ 150, 100 }, 50, 0, angle, 5, BLACK);
		DrawCircleLines(150, 100, 50, BLACK);

		// Example 2.
		DrawCircleSectorLines({ 300, 100 }, 50, 0, angle, 5, BLACK);
		DrawCircleLines(300, 100, 50, BLACK);

		// Example 3.
		DrawRing({ 450, 100 }, 25, 50, 0, angle, 5, BLACK);
		DrawCircleLines(450, 100, 50, BLACK);

		// Alternate implementation of example 2, to see how it should look
		DrawCircleLines(150, 250, 50, BLACK);
		Vector2 line_dir = { 50, 0 };
		DrawLine(150, 250, 150 + line_dir.x, 250 + line_dir.y, BLACK);
		line_dir = Vector2Rotate(line_dir, DEG2RAD*angle);
		DrawLine(150, 250, 150 + line_dir.x, 250 + line_dir.y, BLACK);

		EndDrawing();
	}

	CloseWindow();

	return 0;
}
```

**Comment by raysan5** [comment]
@RokasPuzonas Thanks for this detailed report, I agree with your point, feel free to send a PR to review all those functions.

**Comment by raysan5** [comment]
@RokasPuzonas Thank you very much for all the work put into this improvement! Certainly is a bit scary because it could break many things... I checked the PR and despite being lot of changes, they look ok to me. Just one question, do all the quads/tris drawing still follow the counter-clock-wise vertex definition convention? That's the main concert that could break things if not following the convention...

**Comment by raysan5** [comment]
> Is this the concern that if the vertexes were in clock-wise order the quad/triangle would be invisible, because then the back-face is being shown?

Yes.

 > If so, I did update the vertex order to be counter-clock-wise, so everything would be rendered correctly.

Perfect!

 > If you want to make sure yourself, I left an example program in the PR, which just renders all the shapes that were updated. And to test between quad/triangles I just changed the "#if defined(....)" to "#if 0 && defined(....)".

Nice!

Last review and merge!
