### ISSUE TITLE
[core] `GESTURE_DRAG` and `GESTURE_SWIPE_*` issues (mostly) for web.

### ISSUE THREAD

**Issue by ubkp** [raysan5/raylib#3182]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

After becoming aware that _Mouse Position_ was zero for mouse movement on Touch for web (https://github.com/raysan5/raylib/issues/3174), I suspected that it could be the cause of some problems on `GESTURE_DRAG` (and, to an extent, to `GESTURE_SWIPE_*`).

After a closer look, `GESTURE_DRAG` detection [(rgestures.h#L350-L355)](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L350-L355) on `ProcessGestureEvent()` [(rgestures.h#L265)](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L265) calculates the distance between `GESTURES.Touch.downPositionA` and `GESTURES.Touch.moveDownPositionA` to compare it with the `MINIMUM_DRAG` distance.

However, `GESTURES.Touch.moveDownPositionA` is always zero. So when it calculates the distance, it's calculating the distance from the `GESTURES.Touch.downPositionA` (which is wherever the touch was pressed down) to the `0,0` (top left) point on the screen.

This wasn't easily noticeable because `MINIMUM_DRAG` value was really small (`0.015f`) [(rgestures.h#L182)](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L182). But once that was changed to a higher value, it becomes very apparent. A `GESTURE_DRAG` that started near `0,0` would start on the correct distance from `MINIMUM_DRAG`, but a `GESTURE_DRAG` that started on the other corner (bottom right) would trigger instantly.

### Proposed solution

Since `GESTURES.Touch.downPositionA` is not available, it's not possible to reliably calculate the distance and an alternative check to detect `GESTURE_DRAG` is necessary. The best option I could find was using using time (subtracting the `GESTURES.Touch.eventTime` from `rgGetCurrentTime()` and comparing it to a new minimal `DRAG_TIMEOUT` define).

### Issue description

Albeit that solved the `GESTURE_DRAG`, it broke `GESTURE_SWIPE_*` for web.

Following the execution sequence of `ProcessGestureEvent()` I found that `GESTURE_SWIPE_*` usually happen after a `GESTURE_DRAG`. However, it can also happen after a `GESTURE_HOLD`. That's a rare occurance on `PLATFORM_DESKTOP`, but far more frequent on `PLATFORM_WEB` due to Emscripten's callbacks running independently.

### Proposed solution

To fix that, it's necessary to add `GESTURE_HOLD` to also update the `GESTURES.Touch.upPosition` at [rgestures.h#L300](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L300).

### Issue description

Finally, the last issue was that on Chrome for Android the sensitivity of a touch is very high internally on the web browser. High enough that a single physical touch could actually trigger multiple singular touches due to the curvature of the fingertip. Which, on its turn, would end up triggering multiple touch gestures that the user didn't actually intend to.

`ProcessGestureEvent()` was robust enough handle that, except for `GESTURE_SWIPE_*` because `FORCE_TO_SWIPE` value was way too small `0.0005f` [(rgestures.h#L181)](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L181), so any tap would end up triggering a `GESTURE_SWIPE_*`.

### Proposed solution

Increasing `FORCE_TO_SWIPE` to a higher value gave `GESTURE_SWIPE_*` a higher tolerance without losing functionality.

Tested these solutions successfully on Firefox (115.0.1) and Chrome (95.0.4638.74) for Android; Firefox (102.11.0esr 64-bit) and Chrome (114.0.5735.106 64-bit) with Touch Emulation enabled and disabled for Linux; and native on Linux.

I'll send a PR with the proposed changes (for the 3 parts, since they are somewhat interconnected) shortly.

I believe these were the last fixes necessary to fully reestablished functionality of touch for web.

### Environment

Platform: _Desktop_
Operating System: _Linux Mint 21.1 (x86_64)_
OpenGL version: _3.1 Mesa 22.0.5_
GPU: _Intel HD Graphics 3000_

Platform: _Mobile_
Operating System: _Android 5.1.1_
OpenGL version: _OpenGL ES 1.1/2.0_
GPU: _Mali-400_

### Issue Screenshot

![img](https://github.com/raysan5/raylib/assets/118854183/b11d6570-9554-4160-92f6-a2f56198b780)

### Code Example

Minimal reproduction code to test the issue: [examples/core/core_input_gestures_web.c](https://github.com/raysan5/raylib/blob/master/examples/core/core_input_gestures_web.c)

**Comment by raysan5** [comment]
@ubkp Thank you very much again for the improvement and the super-detailed and professional issue description.

As commented in the PR, trying the example on Windows (with mouse), I notice that HOLD is always issued after just a TAP, shouldn't it take some time to be detected?

**Comment by raysan5** [comment]
@ubkp thanks for the detailed explanation. About the proposed changes on the drag/hold mechanism, it sounds good to me.

**Comment by raysan5** [comment]
> Can I make the "time" method ([L355](https://github.com/raysan5/raylib/blob/master/src/rgestures.h#L355)) the standard way to detect the "drag" gesture?

@ubkp Yes, I think it's the best option.
