### ISSUE TITLE
[core] Wrong description for GetMonitorName

### ISSUE THREAD

**Issue by localwhale20** [raysan5/raylib#3184]
GetMonitorName(int monitor) have description: "Get the human-readable, UTF-8 encoded name of the **primary monitor**".
Why "primary monitor" if I can provide monitor number?

(this don't requires any platform, and it's [here](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L977))

**Comment by raysan5** [comment]
@localwhale20 good catch! feel free to send a PR with a review! :)
