### ISSUE TITLE
Changing opengl versions 

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib#319]
Since my laptop only supports upto opengl 3.1 any way to change opengl versions raylib currently defaults to opengl 3.3.

**Comment by raysan5** [comment]
Yes, if using Notepad++ script: https://github.com/raysan5/raylib/wiki/FAQ

In case you use VS2015, just change Preprocessor Definition `GRAPHICS_API_OPENGL_33` to `GRAPHICS_API_OPENGL_11` or `GRAPHICS_API_OPENGL_21`

**Comment by msmshazan** [comment]
Can you support opengl 3.1

**Comment by raysan5** [comment]
You can do mostly the same with OpenGL 2.1 than 3.1, do you need 3.1 for any specific feature?

Actually, my intention is removing old OpenGL versions in the future...

**Comment by msmshazan** [comment]
@raysan5 don't remove old opengl versions think about low end hardware. What if a developer doesn't have opengl 3.3 supported like me.

**Comment by raysan5** [comment]
> don't remove old opengl versions think about low end hardware.

That's the reason why I keep support for OpenGL 1.1 and 2.1 but supporting those versions means quite a lot of extra dirty code and missing great advance features of new OpenGL versions.

**Comment by FyreWolf99** [comment]
I'm trying to do the same thing, but I'm writing this in vim and just using a Makefile. How would i do this in that case?

**Comment by avelican** [comment]
Sorry for necroposting, but I stopped using RayLib after switching to older hardware for this reason (all my SDL projects still work fine, none of my RayLib projects work anymore). I'm quite new to graphics programming so I am curious what is the motivation for not supporting older OpenGL. If I recompile RayLib with an older version, which cool new features will I be missing?

**Comment by raysan5** [comment]
@avelican raylib still supports OpenGL 1.1 from 1992, you have to recompile raylib enabling it. Missing features on OpenGL 1.1: Shaders.

**Comment by Me2L** [comment]
> Yes, if using Notepad++ script: https://github.com/raysan5/raylib/wiki/FAQ
I am using raylib 3.0 with notepad++, so what should I do to change the openGL to 3.1 or an older version?
https://github.com/raysan5/raylib/wiki/FAQ This link is just to ask a new question.

**Comment by rudowect** [comment]
> > Yes, if using Notepad++ script: https://github.com/raysan5/raylib/wiki/FAQ
> 
> I am using raylib 3.0 with notepad++, so what should I do to change the openGL to 3.1 or an older version? https://github.com/raysan5/raylib/wiki/FAQ This link is just to ask a new question.

https://github.com/raysan5/raylib/wiki/Frequently-Asked-Questions#can-i-run-raylib-in-my-old-pc

**Comment by VioletGiraffe** [comment]
> Yes, if using Notepad++ script: https://github.com/raysan5/raylib/wiki/FAQ
> 
> In case you use VS2015, just change Preprocessor Definition `GRAPHICS_API_OPENGL_33` to `GRAPHICS_API_OPENGL_11` or `GRAPHICS_API_OPENGL_21`

The link is dead (I know it's an old issue, but I have the same question).

**Comment by asdqwe** [comment]
To compile raylib with a specific `GRAPHICS` support using `make`:
```
cd raylib/src/
make GRAPHICS=GRAPHICS_API_OPENGLES_33
```
Or with `cmake`:
```
mkdir raylib/build/
cd raylib/build/
cmake -DGRAPHICS=GRAPHICS_API_OPENGL_22 ..
cmake --build .
```
Supported options:
```
GRAPHICS_API_OPENGL_11
GRAPHICS_API_OPENGL_21
GRAPHICS_API_OPENGL_33
GRAPHICS_API_OPENGL_43
GRAPHICS_API_OPENGL_ES2
GRAPHICS_API_OPENGL_ES3
```

**Comment by VioletGiraffe** [comment]
Thank you.

But why no runtime switch? `vcpkg` doesn't expose these options.

**Comment by asdqwe** [comment]
Unless I'm mistaken, runtime OpenGL switching would require a (near complete) reimplementation of `rlgl`<sup>1</sup>.
That, I believe, is not in the plans.

Regarding `vcpkg`, don't know who added (or maintains) that package (ref: [see this answer](https://github.com/raysan5/raylib/issues/3873#issuecomment-2041424168)). 

<sup>1</sup> Which is what raylib uses for rendering.

**Comment by raysan5** [comment]
@asdqwe yeah, that's right. The only option available at the moment is recompiling the library for the selected OpenGL backend.

**Comment by VioletGiraffe** [comment]
To clarify, I didn't mean support for changing the OpenGL context more than once. Only for specifying what the client wants before creating the window. I understand it's not your focus, just want to voice this request.

**Comment by asdqwe** [comment]
A sizeable part of `rlgl`'s calls is sorted by preprocessor directives at compile time (as you can see, for example, [here](https://github.com/raysan5/raylib/blob/d0504800d2c5a5e722a65a9023ddadca17f930bc/src/rlgl.h#L2243-L2331)). That was necessary because OpenGL version vary greatly in features, availability and are often incompatible between each other.

What you're requesting would still require a (near complete) reimplementation of `rlgl` since, basically, would be the same changes necessary for adding runtime switching. Maybe one day, but I wouldn't expect that in the near future.

**Comment by Jussl** [comment]
All the links are dead. How do I force raylib 5.5 to use openGL 3.3?
