### ISSUE TITLE
[core] Only 1 GamePad is detected

### ISSUE THREAD

**Issue by kristianlm** [raysan5/raylib#3194]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch (295e8c2a2faa7b0c80a840695e37f3ed1740eb88)
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Only 1 of my 2 connected PS3 gamepads work. The second on is not detected, but it's motion sensor is. I'm running on Arch Linux and I've got 2 PS3 controllers connected through bluetooth. 

GLFW detects these controlles properly:

```c
 ➤ gcc -lglfw glfw_gamepad_enumerate.c -o glfw_gamepad_enumerate && ./glfw_gamepad_enumerate
GP  1: 1 'Lenovo TrackPoint Keyboard II'
GP  2: 1 'Sony PLAYSTATION(R)3 Controller'
GP  3: 1 'Sony PLAYSTATION(R)3 Controller'
GP  4: 1 'Telink Wireless Receiver Consumer Control'
GP  5: 0 '(null)'
GP  6: 0 '(null)'
GP  7: 0 '(null)'
GP  8: 0 '(null)'
 ➤ cat glfw_gamepad_enumerate.c

#include <stdio.h>
#include <GLFW/glfw3.h>

int main(void) {

  if (!glfwInit()) return 111;

  printf("GP  1: %d '%s'\n", glfwJoystickPresent(GLFW_JOYSTICK_1), glfwGetJoystickName(GLFW_JOYSTICK_1));
  printf("GP  2: %d '%s'\n", glfwJoystickPresent(GLFW_JOYSTICK_2), glfwGetJoystickName(GLFW_JOYSTICK_2));
  printf("GP  3: %d '%s'\n", glfwJoystickPresent(GLFW_JOYSTICK_3), glfwGetJoystickName(GLFW_JOYSTICK_3));
  printf("GP  4: %d '%s'\n", glfwJoystickPresent(GLFW_JOYSTICK_4), glfwGetJoystickName(GLFW_JOYSTICK_4));
  printf("GP  5: %d '%s'\n", glfwJoystickPresent(GLFW_JOYSTICK_5), glfwGetJoystickName(GLFW_JOYSTICK_5));
  printf("GP  6: %d '%s'\n", glfwJoystickPresent(GLFW_JOYSTICK_6), glfwGetJoystickName(GLFW_JOYSTICK_6));
  printf("GP  7: %d '%s'\n", glfwJoystickPresent(GLFW_JOYSTICK_7), glfwGetJoystickName(GLFW_JOYSTICK_7));
  printf("GP  8: %d '%s'\n", glfwJoystickPresent(GLFW_JOYSTICK_8), glfwGetJoystickName(GLFW_JOYSTICK_8));

  glfwTerminate();
  return 0;
}
```

I'm using glfw 3.3.8-1 and this works correctly. However, running a similar example with raylib yields a missing GamePad:

```c
klm@kc ~/o/r/e/core ➤ gcc core_input_gamepad_enumerate.c -o core_input_gamepad_enumerate -lraylib && ./core_input_gamepad_enumerate | grep ^GP
GP  0: Lenovo TrackPoint Keyboard II
GP  1: Sony PLAYSTATION(R)3 Controller Motion Sensors
GP  2: Sony PLAYSTATION(R)3 Controller
GP  3: Sony PLAYSTATION(R)3 Controller Motion Sensors
GP  4: not evailable
GP  5: not evailable
GP  6: not evailable
GP  7: not evailable
GP  8: not evailable
GP  9: not evailable
GP 10: not evailable
GP 11: not evailable
GP 12: not evailable
GP 13: not evailable
GP 14: not evailable
GP 15: not evailable
klm@kc ~/o/r/e/core ➤ cat core_input_gamepad_enumerate.c
#include "raylib.h"
#include <stdio.h>

int main() {
  InitWindow(100, 100, "raylib [core] example - gamepad input enumeration");
  SetTargetFPS(60);

  // workaround: gamepads aren't detected in first frame
  BeginDrawing(); EndDrawing();

  BeginDrawing();
  for(int gamepad = 0 ; gamepad < 16 ; gamepad++) {
    if (IsGamepadAvailable(gamepad)) {
      printf("GP %2d: %s\n", gamepad, GetGamepadName(gamepad));
    } else {
      printf("GP %2d: not evailable\n", gamepad);
    }
  }
  EndDrawing();

  CloseWindow();
  return 0;
}
```

Each gamepad has a "normal" variant and a motion sensor variant, reported separately. The motion sensor is used to get accelerometer input. GLFW reports there gamepads differently, but I don't think it matters. As you can see, raylib can find both motion sensors correctly, but only the first regular gamepad is detected.

The official core_input_gamepad example (latest build) also has this problem as I browse through the gamepads by pressing right-arrow.

### Environment

Arch Linux

```sh
 ➤ ldd core_input_gamepad
	linux-vdso.so.1 (0x00007ffd593f0000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f7b72ca0000)
	libOpenGL.so.0 => /usr/lib/libOpenGL.so.0 (0x00007f7b72c75000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f7b72c43000)
	libGLU.so.1 => /usr/lib/libGLU.so.1 (0x00007f7b72bed000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f7b72a03000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f7b72f05000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f7b7294b000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f7b72806000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f7b72400000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7b727e1000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f7b727b6000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f7b727b1000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f7b727a7000)
```

### Code Example

See snippets above.

**Comment by kristianlm** [comment]
That solves it, great suggestion! I had to change `config.h` too. I changed it to `16`, since [glfw supports up to 16 joysticks](https://www.glfw.org/docs/latest/input_guide.html#joystick).

```patch
diff --git a/src/config.h b/src/config.h
index 67c6060b..049cb2d3 100644
--- a/src/config.h
+++ b/src/config.h
@@ -81 +81 @@
-#define MAX_GAMEPADS                    4       // Maximum number of gamepads supported
+#define MAX_GAMEPADS                   16       // Maximum number of gamepads supported
diff --git a/src/rcore.c b/src/rcore.c
index 45495bb1..d7c1b88c 100644
--- a/src/rcore.c
+++ b/src/rcore.c
@@ -326 +326 @@
-    #define MAX_GAMEPADS                   4        // Maximum number of gamepads supported
+    #define MAX_GAMEPADS                   16        // Maximum number of gamepads supported
```

What's needed to get this upstream? Why is the default so low?

Thank you very much for looking into this.

**Comment by raysan5** [comment]
@kristianlm @ubkp I didn't expected anyone requiring more than 4 gamepad slots, that number was choosen to be optimus.

**Comment by kristianlm** [comment]
Hi and thanks for the quick response from both of you.

> A higher standard value would just keep gamepad loops needlessly running longer for most cases. If the program/game really plans on using more than that, it's just a matter of customizing its `MAX` defines.

I wish there was a better way. Of the 4 enumerated devices, only one of them is usable since it's also picking up silly things like a wireless receiver and the PS3 "motion sensor" on my machine. So in practice, "max 4 gamepads supported" is really "max 1 gamepad" on my machine which isn't great. This means I can't use my distro's raylib build which is what I prefer.

Here are some options as I see it:

1. Make the 4 `for`-loops in `PollInputEvent` more efficient and set` MAX_GAMEPADS` to 16 
2. Keep the `for`-loops in `PollInputEvent` as-is and set` MAX_GAMEPADS` to 16, 8 or 6
3. Make `MAX_GAMEPADS` runtime-configurable (or does that break some raylib philosophy?)
4. Filter away "goofy" gamepads like the wireless receiver. I don't know if that's possible though.

**Comment by raysan5** [comment]
@kristianlm Increasing the `MAX_GAMEPADS` number implies an increment in required memory to manage it internally, not required by most users (in 10 years it's the first time this issue was noticed). I think keeping it at 4 is a good balance, still, users requiring more than can configure it through the exposed flag, it's exposed for that reason.

@ubkp thank you very much for investigating this issue!

**Comment by raysan5** [comment]
No more actions expected on raylib side, closing the issue.

**Comment by kristianlm** [comment]
Thanks for taking a deep dive, @ubkp.

> I don't have any joystick/gamepad here to confirm this, so could you please provide the output of `ls -l /dev/input/by-id/` with joysticks/gamepads connected?

Sure:

```bash
➤ ls -l /dev/input/by-id/
total 0
lrwxrwxrwx 1 root root  9 Jul 23 10:01 usb-Lenovo_TrackPoint_Keyboard_II-event-kbd -> ../event8
lrwxrwxrwx 1 root root 10 Jul 23 10:01 usb-Lenovo_TrackPoint_Keyboard_II-if01-event-mouse -> ../event14
lrwxrwxrwx 1 root root  9 Jul 23 10:01 usb-Lenovo_TrackPoint_Keyboard_II-if01-mouse -> ../mouse0
lrwxrwxrwx 1 root root 10 Jul 23 10:01 usb-Telink_Wireless_Receiver-event-if00 -> ../event21
lrwxrwxrwx 1 root root 10 Jul 23 10:01 usb-Telink_Wireless_Receiver-event-mouse -> ../event20
lrwxrwxrwx 1 root root 10 Jul 23 10:01 usb-Telink_Wireless_Receiver-if01-event-kbd -> ../event23
lrwxrwxrwx 1 root root  9 Jul 23 10:01 usb-Telink_Wireless_Receiver-mouse -> ../mouse1
```

Very strange, where did they go? They've successfully connected:

```
[128971.452920] sony 0005:054C:0268.0010: unknown main item tag 0x0
[128971.946263] input: Sony PLAYSTATION(R)3 Controller Motion Sensors as /devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.0/bluetooth/hci0/hci0:21/0005:054C:0268.0010/input/input47
[128971.946813] input: Sony PLAYSTATION(R)3 Controller as /devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.0/bluetooth/hci0/hci0:21/0005:054C:0268.0010/input/input46
[128971.947132] sony 0005:054C:0268.0010: input,hidraw5: BLUETOOTH HID v80.00 Joystick [Sony PLAYSTATION(R)3 Controller] on 00:02:72:b1:3a:c1
[128991.910955] sony 0005:054C:0268.0011: unknown main item tag 0x0
[128992.446508] input: Sony PLAYSTATION(R)3 Controller Motion Sensors as /devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.0/bluetooth/hci0/hci0:22/0005:054C:0268.0011/input/input49
[128992.447228] input: Sony PLAYSTATION(R)3 Controller as /devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.0/bluetooth/hci0/hci0:22/0005:054C:0268.0011/input/input48
[128992.447731] sony 0005:054C:0268.0011: input,hidraw6: BLUETOOTH HID v80.00 Joystick [Sony PLAYSTATION(R)3 Controller] on 00:02:72:b1:3a:c1
```

They're definitely in my system:

```
➤ ls -l /dev/input/js*
crw-rw-r--+ 1 root input 13, 0 Jul 24 21:51 /dev/input/js0
crw-rw-r--+ 1 root input 13, 1 Jul 24 21:51 /dev/input/js1
```

What's strange if the vanilla GLFW snippet above in this issue is able to properly remove the `Sony PLAYSTATION(R)3 Controller Motion Sensors` variants. I was wondering why raylib's GLFW wasn't doing the same thing, so I compared the two `linux_joystick.c`'s: GLFW [version 3.3.8](https://github.com/glfw/glfw/blob/3.3.8/src/linux_joystick.c#L160) has introduced this change:

```patch
diff --git a/src/external/glfw/src/linux_joystick.c b/src/external/glfw/src/linux_joystick.c
index 366bda2d..fd5dabdf 100644
--- a/src/external/glfw/src/linux_joystick.c
+++ b/src/external/glfw/src/linux_joystick.c
@@ -160 +160 @@ static GLFWbool openJoystickDevice(const char* path)
-    if (!isBitSet(EV_ABS, evBits))
+    if (!isBitSet(EV_KEY, evBits) || !isBitSet(EV_ABS, evBits))
```

Which, when applied to raylib's GLFW yields the same results as `glfw_gamepad_enumerate` above in this issue:

```bash
➤ ./examples/core_input_gamepad_enumerate | grep ^GP
GP  0: Lenovo TrackPoint Keyboard II
GP  1: Sony PLAYSTATION(R)3 Controller
GP  2: Sony PLAYSTATION(R)3 Controller
GP  3: Telink Wireless Receiver Consumer Control
GP  4: not evailable
…
```

So from what I gather that means this will be fixed when raylib's GLFW is updated. Always good to clarify. Once again, thanks for investigating.

**Comment by raysan5** [comment]
@kristianlm thanks for the further investigation of this issue! raylib has been using the GLFW 3.4 branch, expecting a final release but it is taking quite long and I'm considering reverting to 3.3.8, it seems both branches are not aligned in some aspects...

**Comment by kristianlm** [comment]
> Now it's a matter of checking if the `PLAYSTATION(R)3 Controller` is using the `hid-sony` driver. @kristianlm could you please check that? `lsmod | grep sony` or `cat /proc/modules | grep sony` should show if it's being used.

Yes, it's used:
```
➤ lsmod | grep sony
hid_sony               40960  0
ff_memless             20480  1 hid_sony
usbhid                 77824  1 hid_sony
```

> I checked that change (that happened on [glfw/glfw@c424fe5](https://github.com/glfw/glfw/commit/c424fe55892e7ac7c849989b9ab5e143825fdd4e))

Nice catch! So the "fix" was reverted then and the motion sensors will reappear with an GLFW upgrade like you say. I could see if there is a `evdev` alternative to my PS3 controllers, but apart from this relatively small problem they're been stable so I'm not that keen on making changes.
