### ISSUE TITLE
[core] TOPMOST flag does not work with multiple monitors

### ISSUE THREAD

**Issue by Vessov** [raysan5/raylib#3198]
### Issue description

I use Python API for Raylib - [Raylib 4.5.0.0](https://pypi.org/project/raylib/). When setting up a window, if different than default monitor is selected via `set_window_monitor()`, the `FLAG_WINDOW_TOPMOST` is not working as intended -  even when flag is set, window will minimize when clicked anywhere on any other monitor - regardless of if the flag was set before setting the window monitor, or after. This occurs always when using the `set_window_monitor()`, even when the default monitor is selected.

### Environment

 + Windows 10 Pro 22H2 64 bit
 + Intel(R) HD Graphics 520
 + OpenGL 4.6
 + Python 3.11.3
 + Python Raylib 4.5.0.0

### Code Example

```python
import pyray as pr

pr.set_config_flags(pr.ConfigFlags.FLAG_WINDOW_TOPMOST)
pr.set_config_flags(pr.ConfigFlags.FLAG_WINDOW_UNDECORATED)
pr.init_window(500, 500, "FooBar")
pr.set_window_position(0, 0)
pr.set_target_fps(60)

monitor = 0
pr.set_window_size(pr.get_monitor_width(monitor), pr.get_monitor_height(monitor))
pr.set_window_monitor(monitor)

while not pr.window_should_close():
    pr.begin_drawing()
    pr.clear_background(pr.RAYWHITE)
    pr.end_drawing()

pr.close_window()
```

**Comment by raysan5** [comment]
@Vessov Please, try using `SetWindowState()` after `InitWindow()`, some flags are only functional after the window has been created. Here it is an usage example: https://github.com/raysan5/raylib/blob/master/examples/core/core_window_flags.c

**Comment by Vessov** [comment]
Still, error persists - even after adding `SetWindowState()` after `InitWindow()`, or even inside the event loop

**Comment by Vessov** [comment]
@ubkp @raysan5  I see. I wonder if there may be any workaround - since when window monitor isn't set via `SetWindowMonitor` (so, if I understand correctly, it defaults to `NULL`?), and window starts on the defaulft monitor, the issue doesn't occur - no matter if in fullscreen mode or otherwise, the window stays topmost.

After testing, I noticed another problem - it's impossible to make window drop the fullscreen mode while using `SetWindowMonitor`; changing the window size via `SetWindowSize` changes the resolution of the screen, but window stays fullscreen. I tried clearing the `FLAG_FULLSCREEN_MODE` with the `ClearWindowState` (both right after setting window monitor, as well as inside event loop), but it doesn't seem to have any affect.

Is it possible to design any workaround to keep window topsize when using `SetWindowMonitor` with the current library code, or add that functionality to the code, or would it be impossible due to GLWF constraints?

**Comment by Vessov** [comment]
@ubkp Thank you, your example works. I see you assumed that the second monitor is at the same level and to the right of the first one; I'm trying to implement it in a way that a monitor may be wherever. However, I'm not sure how to get a monitor position that could be correctly passed to `SetWindowPosition`; since `GetMonitorPosition` returns `Vector2`, which can't be unpacked into it's respective values, and I'm not sure if I understand how to correctly transform it to get the **X** and **Y** position to pass to `SetWindowPosition`. However, I'm not sure if that question is relevant to the issue at hand, so if I should go with it somwhere else (like Discord) and close this issue, let me know

**Comment by Vessov** [comment]
@ubkp Done it, it works, thank you very much. Since, as you pointed, the main primary issue was something beyond the scope of the library itself, and relates to the way GLFW handles it, I'll be closing the issue now

**Comment by raysan5** [comment]
> I can take a look at that.

@ubkp Sure! I'm opening a separate issue for further discussion #3207

 > should I also try to review SetWindowMonitor() so windows can be positioned without forcing fullscreen?

Of course.
