### ISSUE TITLE
Converting raylib compilation to unity build

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib#321]
Is it possible to convert raylib to a single compilation unit to reduce build times. Which means build one .c file and #include the rest.

**Comment by raysan5** [comment]
Not sure if I understand, do you mean converting all raylib modules to header-only with implementation?

raylib is already a very small library, only about 10 files, compilation time is not a problem. Embedding those 10 files in headers and compiling a single file will take same time or even longer.

**Comment by msmshazan** [comment]
I meant that only one .obj file shows up during compilation.

**Comment by raysan5** [comment]
It's better to organize it in multiple object files, at the end they are compiled into a single .lib library.
