### ISSUE TITLE
[rcore] Distorted pixels when drawing textures in Mode2D with certain zoom values

### ISSUE THREAD

**Issue by jkaup** [raysan5/raylib#3228]
### Issue description

Textures get distorted/warped pixels when using Camera2D / BeginMode2D with certain zoom values, for example `camera.zoom = 2.2f`. Screenshots provided help demonstrate the issues: Some lines get doubled width, some individual pixels get doubled in x or y or both.

### Environment
OS: Windows 10
raylib 4.6-dev
OpenGL device information:
Vendor:   NVIDIA Corporation
Renderer: NVIDIA GeForce RTX 2070 with Max-Q Design/PCIe/SSE2
Version:  3.3.0 NVIDIA 527.56
GLSL:     3.30 NVIDIA via Cg compiler

### Issue Screenshot
The following screenshot demonstrates the issue (this was generated with the example code below, with zoom = 2.2f). The pixels on the texture are warped, see for example the dark tile linings with doubled width, and the different sized darker corner pixels. (Compare to test.png and working.png)

![snippet](https://github.com/raysan5/raylib/assets/29462864/c8b6a5d7-02cc-4761-9739-62528b4bc381)

Below is shown a screenshot with zoom = 1.0f, where the textures look normal and uniform.
![working](https://github.com/raysan5/raylib/assets/29462864/3fe893a7-4c8a-4792-8971-80f6ebfb90ea)

### Code Example

```cpp
#include <stdint.h>
#include <stdio.h>
#include <string>

#include "raylib.h"

int main()
{
    const int screenWidth = 256;
    const int screenHeight = 256;

    InitWindow(screenWidth, screenHeight, "test");

    std::string path = ART_PATH + std::string("/test.png");
    Texture2D texture = LoadTexture(path.c_str());

    Camera2D camera;
    camera.target = (Vector2){ 0, 0 };
    camera.offset = (Vector2){ 0, 0 };
    camera.rotation = 0;
    camera.zoom = 2.2f;
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        BeginDrawing();
        if (!IsTextureReady(texture))
        {
            EndDrawing();
            continue;
        }
        ClearBackground(BLACK);

        BeginMode2D(camera);

        for (uint32_t i = 0; i < 16; i++)
        {
            for (uint32_t j = 0; j < 16; j++)
                DrawTexture(texture, 16 * i, 16 * j, WHITE);
        }

        EndMode2D();

        EndDrawing();
    }

    CloseWindow();
    return 0;
}
```

Attachment: test.png for the texture, compare with the screenshot of end result in Mode2D with zoom

![test](https://github.com/raysan5/raylib/assets/29462864/15d16921-840f-4bcb-95b5-e21237cf7daa)

**Comment by raysan5** [comment]
@jkaup I'm afraid that's the expected result, it depends on the texture scaling algorithm, it's possible to change it with `SetTextureFilter()` but then image will be blurred. Another solutions could be using a RenderTexture or a shader to control scaling mode or soft lines.

**Comment by jkaup** [comment]
Thanks for the hints. Texture filters didn't entirely solve the issue.

I'll try to see if I can find some satisfying solution with render textures and shaders.

**Comment by orcmid** [comment]
This may not be helpful, but out of curiosity, does the phenomenon also occur with Zoom values 2.0f and 2.5f.

**Comment by jkaup** [comment]
> This may not be helpful, but out of curiosity, does the phenomenon also occur with Zoom values 2.0f and 2.5f?

It occurs with Zoom value 2.5f, but 2.0f works fine. The phenomenon is to my understanding due to the scaling algorithm not being able to handle non-integer multiples of the texture sizes properly (or pixel perfectly). As far as I understand, the default filter (TEXTURE_FILTER_POINT) uses nearest neighbor algorithm for scaling, which is known to cause such undesirable effects on non-integer multiples. The linear filters cause blurring effects as mentioned by raysan.

I am currently experimenting with an approach mentioned in several sources, which is to reimplement the zoom-in effect by first upscaling the texture to the next integer multiple using nearest neighbor (or TEXTURE_FILTER_POINT in this case) and then downscaling the view to the desired resolution with a linear texture filter.

That is, if I want 1.5x zoom, I'd first upscale to 2.0x size with nearest neighbor, then downscale from 2.0x to 1.5x using e.g bilinear filter. So far the results seem satisfying to me, however I'll continue testing. If this seems to be a working solution, I'll post a code example here.

**Comment by raysan5** [comment]
@jkaup I'm afraid there is no easy solution, you can just find solutions that work better or worse but with a non-integer scaling there is not many options, you are trying to create pixels at unexpected positions and that's very difficult.

**Comment by jkaup** [comment]
FWIW, the method of upscaling to next integer using nearest neighbor and then downscaling to desired size with bilinear filter turned out fairly decent, there's a gif showing seamless zooming using that approach below. There's some slight flickering, but I think that may have been caused by the GIF encoder.

I'm however likely not going to go with this approach as it produces more pain with regards to managing the camera, world coordinates, performance hits etc. than what I'd gain from this. 

I'll give the FXAA shader a go once I have time, but I'm leaning towards just using fixed zoom steps resulting in integer scaling rather than going for the seamless zooming, as I'll want to go the route of least pain and still maintaining crisp pixel art graphics.

![upscale_nearest_downscale_bilinear](https://github.com/raysan5/raylib/assets/29462864/034f6cd6-34e8-4dea-ba69-7d3abb2330f9)

**Comment by raysan5** [comment]
@jkaup thanks for testing and reporting the results, it could be very useful for other users attempting this approach.
