### ISSUE TITLE
[text] TTF fonts rendering issue

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib#323]
I created a sample example with loading ttf fonts but it seems the font rendering is odd using liberationmono plus is there a way to make fonts bold italic or underlined.

```cpp
#include <stdio.h>
#include <raylib.h>
#include <stdlib.h>
#define GB_STRING_IMPLEMENTATION
#include "gb_string.h"

int main()
{
    // Initialization
    int screenWidth = 800;
    int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "Game Window");

    Texture2D Art = LoadTexture("assets/art.png");
    SpriteFont Font = LoadSpriteFont("assets/LiberationMono.ttf");
    SetTargetFPS(61);

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        if(IsKeyPressed(KEY_F12)){
                TakeScreenshot("Screenshot");
        }
        // Update
      
        // Draw
        BeginDrawing();
        {
            ClearBackground(WHITE);
            //DrawTexture(Art,0,0,WHITE);
            DrawFPS(0,0);
            DrawTextEx(Font,"Sample Text",Vector2{190, 200},20, 0, BLACK);
        }
        EndDrawing();
    }
    CloseWindow();        // Close window and OpenGL context
    
    return 0;
}
```
![capture](https://user-images.githubusercontent.com/20334207/27894700-6a8ad76c-622b-11e7-9cfa-039b19d496f9.PNG)

**Comment by nounoursheureux** [comment]
This happens because raylib is internally pre-rendering the font at a size of 32px (the default) and then drawing it at a size of 20px and some pixels are lost in the process. To work around this you can tell raylib to load the font with a size of 20px: replace this line:
```C
SpriteFont Font = LoadSpriteFont("assets/LiberationMono.ttf");
```
with this line:
```C
SpriteFont Font = LoadSpriteFontEx("assets/LiberationMono.ttf", 20, 0, NULL);
```

@raysan5 I don't know much about font rendering, do you think there is a way to have font rendering that works better when the scale factor isn't an integer ?

**Comment by raysan5** [comment]
Hi @nounoursheureux, you're right on your explanation. raylib internally generates a texture atlas for TTF font at 32px height per character, that can be changed as you stated with `LoadSpriteFontEx()`.

When you draw text at a different size than the internal font base size (`font.baseSize`), texture is scaled, using by default an approximation scaling (the way pixels are calculated on scaling)... but [you can change the scaling algorythm](http://www.raylib.com/examples/web/text/loader.html?name=text_ttf_loading)!

As seen in the example you can improve internal scaling algorythm for any texture with:
```c
void SetTextureFilter(Texture2D texture, int filterMode);    // Set texture scaling filter mode

// Usage example
SetTextureFilter(font.texture, FILTER_BILINEAR);   // FILTER_TRILINEAR requires generated mipmaps
```
There are some new interesting text rendering techniques out there like [Signed Distant Fields](https://www.youtube.com/watch?v=CGZRHJvJYIg) but they are not supported by raylib right now. 

Current raylib text rendering method is used by most of the games out there, SDF would become very handy for next generation games at FullHD and 4K.

Some reference links on SDF:
http://wdobbie.com/post/gpu-text-rendering-with-vector-textures/
https://crimild.wordpress.com/2013/09/01/improving-text-rendering-with-signed-distance-fields/
https://blog.mapbox.com/drawing-text-with-signed-distance-fields-in-mapbox-gl-b0933af6f817

Even better, multi-channel SDF:
https://github.com/Chlumsky/msdfgen

**Comment by nounoursheureux** [comment]
Nice I missed that function !

Yep I have already heard of SDF and it looks interesting but is a bit more involved than just prerendering the whole thing (requires specific shaders, etc.)
