### ISSUE TITLE
[raudio] Feature Request -- Add the ability to seek a Sound to a position

### ISSUE THREAD

**Issue by matej-zajacik** [raysan5/raylib#3238]
Right now, we can use `SeekMusicStream(Music music, float position)` for music, but there's nothing like that for sounds. Something like `SeekSound(Sound sound, float position)`. Of course, this means we need to be able to read a Sound's position as well.

The use case is a game with a full-save system where you can "quick-save" the whole state at any point and reload that state at any point as well. I need to save sounds' positions and then later play them from those exact positions when you load the save.

Thank you!

**Comment by raysan5** [comment]
@matej-zajacik Sounds are intended for short audios, that's the reason I decided to not implement a seek function for them, if an audio needs to be seek, I recommend using a music stream.

 > The use case is a game with a full-save system where you can "quick-save" the whole state at any point and reload that state at any point as well. I need to save sounds' positions and then later play them from those exact positions when you load the save.

A sound shouldn't be used for that, a sound is intended for a few seconds audios or less, keep in mind that they are fully loaded in memory at loading at that could be a high cost (3 sec. @ 44100Hz, Stereo, 32bit = ~1MB).

**Comment by matej-zajacik** [comment]
@raysan5

> A sound shouldn't be used for that, a sound is intended for a few seconds audios or less, keep in mind that they are fully loaded in memory at loading at that could be a high cost (3 sec. @ 44100Hz, Stereo, 32bit = ~1MB).

In a game with a full-save system, even a short sound (say a 3-second explosion) should get to the exact state where it was when the save was made. It's not okay to let these sounds finish playing (or stop playing them, but not re-playing them from where they were). That's basically a bug. In essence, the length of the sound has nothing to do with it, because it's really hard to say at what length the player wouldn't even notice, and at what length it would be perceived as a bug.

But okay, I understand your point. So apart from some really one-shot sounds like UI clicks and such, I'll use music streams for sounds that need the ability to be reset to an exact state or play in a loop.

Thank you for the answer!
