### ISSUE TITLE
Undefined reference to `__imp__wassert` when linking statically against raylib 4.5 on Windows

### ISSUE THREAD

**Issue by vtereshkov** [raysan5/raylib#3243]
### Issue description
When I link my project statically against raylib 4.5 (`libraylib.a`), I get a bunch of errors:
```
C:\Users\vtere\Desktop\umplot>gcc -O3 -DUMKA_STATIC umplot.c -o umplot_windows.umi -shared -Wl,--dll -static-libgcc -static -lumka_static -lraylib -L. -lkernel32 -luser32 -lgdi32 -lwinmm
.\libraylib.a(rglfw.o):rglfw.c:(.text+0x160b): undefined reference to `__imp__wassert'
.\libraylib.a(rglfw.o):rglfw.c:(.text+0x1982): undefined reference to `__imp__wassert'
.\libraylib.a(rglfw.o):rglfw.c:(.text+0x19d9): undefined reference to `__imp__wassert'
.\libraylib.a(rglfw.o):rglfw.c:(.text+0x19f5): undefined reference to `__imp__wassert'
.\libraylib.a(rglfw.o):rglfw.c:(.text+0x1a11): undefined reference to `__imp__wassert'
.\libraylib.a(rglfw.o):rglfw.c:(.text+0x1a5d): more undefined references to `__imp__wassert' follow
collect2.exe: error: ld returned 1 exit status
```
The problem doesn't happen with raylib 4.0.

### Environment

Windows 10, MinGW 64-bit, `raylib-4.5.0_win64_mingw-w64.zip` build

**Comment by Peter0x44** [comment]
How did you obtain your "MinGW"? I'm quite certain the issue does not lie with raylib
Having the output of `gcc --version` would be useful too.

**Comment by Peter0x44** [comment]
The best way to ensure a library will work is to build it yourself

**Comment by ubkp** [comment]
@vtereshkov `GCC 10` [fliped some defaults](https://gcc.gnu.org/gcc-10/changes.html) ([specially](https://gcc.gnu.org/gcc-10/porting_to.html) `-fcommon` to `-fno-common`). That caused some problems on another project I was working on when I upgraded to `GCC 10`. Perhaps it could be the case here.

**Comment by raysan5** [comment]
It seems a compiler-related issue other than raylib itself, I'm closing this issue.
