### ISSUE TITLE
[Text] (Web-based showcase) Emoji example "text_unicode" freezes up after enough emojis are clicked

### ISSUE THREAD

**Issue by evanrinehart** [raysan5/raylib#3249]
This issue is for the web-hosted emoji example on the raylib website. I could not trigger it on desktop builds of the example.

Click many different emojis and eventually the program stops responding. The number of tries and position of final triggering emoji seems to be random, which makes sense because the program is randomized.

Clicking the same set of working emojis over and over doesn't seem to trigger it. Every time it happens, it was a click on an emoji that was not clicked before. If nothing on the first set of emojis triggers the freeze, press space and try the second set.

I was able to reproduce it on Chrome on OSX, and on Firefox on Ubuntu. The two computers have very different specs so I would be surprised if it was a resource exhaustion issue.

In the screenshot of the frozen program I tried to click on the blue emoji.

![image](https://github.com/raysan5/raylib/assets/1022635/ddf334fe-cda8-41dd-a0c8-0400b3c98779)

**Comment by ubkp** [comment]
Was able to reproduce the issue:

![img](https://github.com/raysan5/raylib/assets/118854183/827bede7-f64a-43d8-b26d-035c0bb6e8ce)

Apparently there's an unescaped line break somewhere on [examples/text/text_unicode.c](https://github.com/raysan5/raylib/blob/master/examples/text/text_unicode.c).

**Comment by raysan5** [comment]
@evanrinehart @ubkp I reproduced it on web and tried to reproduce it on desktop but not possible. This is a compelx example provided by a contributor long time ago. I'm afraid the cost to review it to find the platfomr-dependant issue could be considerable and sincerely I think it does not work it, it's just an example to be used as a reference.

If anyone is ready for that task, I'll keep this issue open for a while but if not, I'm closing it.

**Comment by ubkp** [comment]
@raysan5 I'm working on https://github.com/raysan5/raylib/issues/3231, but, if you don't mind keeping this open for a few days, I can take a look at it after that.

**Comment by raysan5** [comment]
@ubkp Ok, thank you very much, just take it easy, it could be tricky and the work required for this platform-specific issue probably does not worth the time invested.
