### ISSUE TITLE
[camera] Change movement speed of camera

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib#325]
How to change movement speed of camera. Maybe pass some extra parameters to updatecamera function.

**Comment by raysan5** [comment]
Right now camera system is pre-configured internally in raylib (https://github.com/raysan5/raylib/blob/master/src/camera.h#L144).

If you change some parameter, you need to recompile the library.

The original idea was making the camera system a external library but at the end I included it in raylib. Despite it works ok, camera system needs to be improved (ported to quaternions), I couldn't find time to do that.

**Comment by msmshazan** [comment]
How about something like updatecameraex

**Comment by raysan5** [comment]
No plans to add new functions on camera at the moment, actually, camera system should be redesigned using quaternions... it would be extremely simplified and improved...

Better solution for the moment is just editing `camera.h` config flags and recompile the library. Just closing this issue.
