### ISSUE TITLE
[camera] Allow the user to update camera manually

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib#326]
Update camera is nice but it would be nice if you can create functions like lookup,look left,look at like functions not a engine expert but it would be nice to update api to provide user access to camera movement than using a single update camera function.

**Comment by raysan5** [comment]
Actually, users can just use Camera struct (with position, target, up, fov) and modify its values with `IsKeyDown()`, `IsMouseButtonPressed()`...

I mean, raylib includes a simple module to just have a simple camera system out-of-the-box but users can also create their own camera system, using Camera struct and inputs. I don't see the necessity of intermediate functions between those two levels of abstraction... but maybe there is.

Which functions do you think could be useful?

**Comment by raysan5** [comment]
Just closing this issue...
