### ISSUE TITLE
[rmodels] billboard backside wont properly do alpha-blending

### ISSUE THREAD

**Issue by lvlrk** [raysan5/raylib#3274]
- tested on raylib 4.5
- no errors
- proper use of raylib

when drawing multiple billboards close together, the backside wont properly do alpha blending

On desktop, arch linux, OpenGL v4.6

`for(int i = 0; i < 16; i++) DrawBillboard(cam, texture, {i * 0.2, 0, 0}, size, WHITE);`

**Comment by chriscamacho** [comment]
neither will the front side !

You'll have to sort by camera distance, or if the alpha value is binary 0/1 then you could use a discard shader...
https://bedroomcoders.co.uk/posts/198

**Comment by raysan5** [comment]
@lvlrk billboards sorting is up to the user, raylib does not sort them.
