### ISSUE TITLE
zig build instructions for windows need to be improved

### ISSUE THREAD

**Issue by Triangle345** [raysan5/raylib#3281]
### Issue description

*Briefly describe the issue you are experiencing (or the feature you want to see added to raylib). Tell us what you were trying to do and what happened instead. Remember, this is not the best place to ask questions. For questions, go to [raylib Discord server](https://discord.gg/raylib).*

The issue with zig build is it does not build the required glfw libraries for windows. You need the .lib file and the dll which are currently located from the glfw binary (from glfw website). One then needs to link with glfw as I will demonstrate below.
Furthermore , one also needs to link to several windows standard libraries to remedy undefined symbols.
The root raylib zig build worked and I was able to produce raylib.lib which I used in the build process (see example below).

### Environment

Windows 11

### Code Example
I was able to build my sample hello raylib application with the following command. Note all the stuff I needed to link. We should update raylib documentation to account for this or create a build.zig template under projects which accounts for different OSs.

```
~/Downloads\\zig-windows-x86_64-0.12.0-dev.167+dd6a9caea\zig.exe build-exe .\hello.zig -lraylib -Lzig-out/lib  -Izig-out/include -Izig-out/include/GLFW -lc -lglfw3 -lgdi32 -lwinmm
```

hello.zig
```
const ray = @cImport({
    @cInclude("raylib.h");
});

pub fn main() void {
    const screenWidth = 800;
    const screenHeight = 450;

    ray.InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");
    defer ray.CloseWindow();

    ray.SetTargetFPS(60);

    while (!ray.WindowShouldClose()) {
        ray.BeginDrawing();
        defer ray.EndDrawing();

        ray.ClearBackground(ray.RAYWHITE);
        ray.DrawText("Hello, World!", 190, 200, 20, ray.LIGHTGRAY);
    }
}
```

I want to add that the latest version of zig (12 development) failed to build for all the examples. So I had to figure all this out manually.

**Comment by raysan5** [comment]
@Triangle345 raylib does not require linking with glfw library because it is embedded in the library, also note that raylib-zig is a separate project than raylib, it should be probably reported to Zig community.
