### ISSUE TITLE
[rtextures] Uninitialized thread-locals in stbi

### ISSUE THREAD

**Issue by jbarthelmes** [raysan5/raylib#3282]
### Issue description
- I had an issue where textures were loaded upside-down.
- As it turns out, stb_image has thread-local variables to make an image be flipped after loading [here](https://github.com/raysan5/raylib/blob/ec6d3bb688ae8c137152eca7cdef9885badd9bee/src/external/stb_image.h#L1119-L1133).
- With `-O3`, these variables are not initialized and contain garbage. With `-O0` they are zeroed apparently.
- As a result, they evaluate to `true` and the STBI image loading code took the branch (`if (stbi__vertically_flip_on_load)`) to vertically flip the image.

### Environment

`clang 16.0.6` (from `zig 0.12.0-dev.252+5dc2db805`), mingw64, `-O3` (`-Doptimize=ReleaseFast`)

### Code Example
`examples/textures/textures_image_loading.c`

### Suggested Fix
1. Either the thread-locals are kept and initialized with `stbi_set_flip_vertically_on_load_thread` before being used, or
2. I prefer disabling them with `#define STBI_NO_THREAD_LOCALS` in `rtextures.c` (1-line PR will follow)

**Comment by raysan5** [comment]
@jbarthelmes good catch! thanks for the review!
