### ISSUE TITLE
[build] `make clean` should delete `raygui.c`

### ISSUE THREAD

**Issue by SuperUserNameMan** [raysan5/raylib#3288]
Hello,

**Compiling Raylib 4.5.0 + Raygui 3.6 on Linux :**

The `#include` path in `raygui.c` is not updated if the value of `RAYLIB_MODULE_RAYGUI_PATH` is changed on a next compilation attempt.
And `make clean` does not delete `raygui.c`.

Same issue might happens with `RAYLIB_MODULE_PHYSAC_PATH`. (untested)

**First attempt :**
`make RAYLIB_LIBTYPE=SHARED RAYLIB_MODULE_RAYGUI=TRUE`
- `raygui.c` is created with default path.
- compilation might fail because expected default raygui path did not match cruel reality.

**Second attempt :**
`make clean`
`make RAYLIB_LIBTYPE=SHARED RAYLIB_MODULE_RAYGUI=TRUE  RAYLIB_MODULE_RAYGUI_PATH=../../raylib-3.6/src`
- compilation fails because `raygui.c` was neither updated nor cleaned.

**Comment by raysan5** [comment]
@SuperUserNameMan Feel free to send a PR with the review.

**Comment by SuperUserNameMan** [comment]
ok, done, but could not test under Windows.
