### ISSUE TITLE
[examples] split screen for 2D camera

### ISSUE THREAD

**Issue by gabrielssanches** [raysan5/raylib#3294]
I see that there is a 3D splitscreen example (examples/core/core_split_screen.c)

Is there an example for a 2D split screen?

**Comment by raysan5** [comment]
@gabrielssanches Feel free to send this new example if you want.

**Comment by gabrielssanches** [comment]
Thanks @raysan5 for the example code, I've added camera tracking to the players and a grid for the visuals
