### ISSUE TITLE
[rcore] SUPPORT_TOUCH_AS_MOUSE mentioned in rcore.c top comment has no effect

### ISSUE THREAD

**Issue by bognarit80** [raysan5/raylib#3297]
https://github.com/raysan5/raylib/blob/d55527953a9cce50c844caa266fe30fbf9b88d44/src/rcore.c#L52-L53

The top comment in rcore.c mentions a #define SUPPORT_TOUCH_AS_MOUSE that is never used.
The Mouse functions mostly do check for touch inputs, but some of them only do so on specific platforms, like PLATFORM_ANDROID or PLATFORM_WEB, or both.

**Comment by raysan5** [comment]
Removed.
