### ISSUE TITLE
[build] Try to support iOS platform

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#330]
A user is trying to add support for iOS to raylib, just opening this issue to keep track on progress and help if possible.

**Comment by define-private-public** [comment]
Might be able to do this easily with CMake.  Just sayin'

**Comment by tazdij** [comment]
Psh, CMake :stuck_out_tongue_winking_eye: Makefile is where all the fun is. I am setting up a fresh iOS dev environment on my Mac this week, and will start working on a fork to support iOS.

I am planning on modifying the Makefile further to support building for iOS allowing the developer to not need to manage an XCode project, and a Makefile. Utilizing `xcrun` from the XCode Command Line tools, this should be simple enough .

I already created a Makefile based on the Skully-Escape game, to support creating App Bundles for Mac from make direclty. It can be viewed here: https://bitbucket.org/midgetviking/raylib-project/src/c275fa4491e6d19d8f2f7daa9b88907896371f91/Makefile?at=default&fileviewer=file-view-default

Any ideas or thoughts on this would be great. I am really new to Mac development. My goal though is to allow for building for any platform (not cross-compiling) from cli using make.

**Comment by raysan5** [comment]
@tazdij, Any progress on iOS support?

**Comment by tazdij** [comment]
@raysan5, No not really, I haven't, sorry. Life has been super busy this last month. I have done more research on the topic and hopefully, I can set aside some time the first week of Sept. to make some progress on this. I have successfully compiled and linked the App for iOS, however it crashes immediately. This is where I left off.

One of my goals here, is to use Make for 100% of the build process. I don't want to load different build tools for each environment. But Apple loves making people use GUIs for everything. I suspect that I am somehow missing something in the linking process.

**Comment by raysan5** [comment]
Hi @tazdij! Thank you very much for the update! It has been a busy month also for me, that's life... You actually get so far, that's great! 

Completely agree on using Make for the build process, that's the approach I prefer.

**Comment by tazdij** [comment]
It has been a while since I have given you an update. Unfortunately, due to some family situations, I have made zero progress on the iOS development. Hopefully in January I will have a few days to work on this. Sorry I brought this up, and then completely failed to deliver for you.

**Comment by raysan5** [comment]
Hey Donald! 

No worries at all! No problem! I can understand it perfectly! Family is way more important than a few lines of code... don't feel forced to work on this!

Hope everything is all right! :)
