### ISSUE TITLE
[rcore] Feature request: message boxes

### ISSUE THREAD

**Issue by M374LX** [raysan5/raylib#3308]
SDL offers the functions ``SDL_ShowMessageBox()`` and ``SDL_ShowSimpleMessageBox()``, which can be called even before ``SDL_Init()``.

It would be nice if raylib offered similar message box functions.

**Comment by jamesl-github** [comment]
I believe raylib uses GLFW                     
and I don't think GLFW doesn't implement message boxes                
https://www.glfw.org/faq#27---will-message-box-support-be-added-to-glfw

but it does expose native windows handles          
https://www.glfw.org/docs/latest/group__native.html              
https://www.glfw.org/docs/latest/glfw3native_8h.html             
so you might be able to call the native OS message box              

but I don't think you'd be able to call it before init

**Comment by raysan5** [comment]
@M374LX OS-specific message boxes is out of scope for raylib, considering that some of the target platforms do not have that kind of functionality (Raspberry Pi native). You can use [tinyfiledialogs](https://sourceforge.net/projects/tinyfiledialogs/) or [raygui](https://github.com/raysan5/raygui) for that functionality.
