### ISSUE TITLE
[rmodels] DrawMeshInstanced() is not working

### ISSUE THREAD

**Issue by Steelsmasher** [raysan5/raylib#3315]
I can't get DrawMeshInstanced() to display anything, I just get a black screen. Same issue as #2707.
The Mesh Instancing web example `examples/shaders/shaders_mesh_instancing` doesn't work regardless of which browser I use.

**Comment by ubkp** [comment]
Was able to confirm it's no longer working. Actually, by chance, I tested it on the start of the month and it was working. So some recent change must have broken it.

**Comment by Steelsmasher** [comment]
Are shaders necessary to use DrawMeshInstanced? I was hoping to draw a large number of instances but I haven't got the handle of shaders yet.

**Comment by raysan5** [comment]
I just tried the example on desktop and web (locally) and it works as expected with latest raylib at this same moment.

Attaching my local compilation: [shaders_mesh_instancing.zip](https://github.com/raysan5/raylib/files/12620822/shaders_mesh_instancing.zip)

I vaguely remember I already faced this issue in the past but it's really weird, it works ok locally but once uploaded to GitHub it just stops working, issue is related to shader line-breaks (`LF` vs `CR LF`) but I don't know why it only fails for the specific shaders used in this example.

**Comment by raysan5** [comment]
> Are shaders necessary to use `DrawMeshInstanced()`? I was hoping to draw a large number of instances but I haven't got the handle of shaders yet.

@Steelsmasher yes, they are needed. Make sure they are properly loaded, that could be your issue on desktop.

**Comment by ubkp** [comment]
@Steelsmasher When you run the `shaders_mesh_instancing` example, does the logs show any warnings or errors?

**Comment by Steelsmasher** [comment]
When I run `shaders_mesh_instancing` from example folder with raylibs notepad++ everything runs fine. When I tried @raysan5's local compilation I got a blank screen as below:
![image](https://github.com/raysan5/raylib/assets/18646376/8682302e-d514-4f01-bfdf-2a6ee4aab0fe)

**Comment by raysan5** [comment]
@Steelsmasher the log say that shaders can not be loaded, are you copying them in the right path?

**Comment by ubkp** [comment]
I got that error too if I executed the example from some other dir other than inside `examples/shaders/`, e.g.:
```
~/test/raylib-master/examples$ ./shaders/shaders_mesh_instancing 
[...]
WARNING: FILEIO: [resources/shaders/glsl330/lighting_instancing.vs] Failed to open text file
WARNING: FILEIO: [resources/shaders/glsl330/lighting.fs] Failed to open text file
[...]
```
Which doesn't happen if executed from inside the `examples/shaders/` dir, e.g.:
```
~/test/raylib-master/examples/shaders$ ./shaders_mesh_instancing 
[...]
```
That's why I assumed the problem was the path not considering the application directory. I think that doesn't happen when compiling for `PLATFORM_WEB` because `emcc` packs the assets on the `.data` file.

**Comment by Steelsmasher** [comment]
@raysan5 I didn't, I simply ran the exe from your zip folder as is. Copying the resources folder into it fixed it, thanks.

I noticed raylib.zig compiles the executable into a folder without the shaders, so that's probably my issue.
