### ISSUE TITLE
[new feature] Please have support for a simple Serial por comunication over USB because it could open raylib to all DIY community.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [raysan5/raylib#3320]
Hello,

I would like to ask the developers of raylib to have a minimal support for serial communication, literally every micro-controller uses standard serial communication and many time is necessary to make a Art installation or a student project that has a PC interface to the micro-controller, a serial port interface that would be portable between different Systems would be a must have for raylib.

And would bring all the makers, all the DIY, all the hardware hackers and digital artists to raylib .

Best regards,
João Carvalho

**Comment by ubkp** [comment]
@joaocarvalhoopen Take a look at https://github.com/pololu/libusbp, it shouldn't be too hard to integrate it in your project.

**Comment by raysan5** [comment]
@joaocarvalhoopen I'm afraid this is out of scope for raylib, I recommend using an external library like the one proposed by @ubkp.
