### ISSUE TITLE
[rcore] Duplicated code on `EventThread()`

### ISSUE THREAD

**Issue by AndrewCapon** [raysan5/raylib#3323]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Raspberry code (and maybe all linux?) only supporting 4 touches.

### Code Example

Currently in rcore.c, EventThread() there is code like this:

```
if (CORE.Input.Touch.position[0].x >= 0) CORE.Input.Touch.pointCount++;
if (CORE.Input.Touch.position[1].x >= 0) CORE.Input.Touch.pointCount++;
if (CORE.Input.Touch.position[2].x >= 0) CORE.Input.Touch.pointCount++;
if (CORE.Input.Touch.position[3].x >= 0) CORE.Input.Touch.pointCount++;
```

Rather than:
```
for(int iTp = 0; iTp < MAX_TOUCH_POINTS; iTp++)
              if (CORE.Input.Touch.position[iTp].x >= 0) CORE.Input.Touch.pointCount++;
```

I have changed this code and the relevant code for gestures and now I get MAX_TOUCH_POINTS touches and all is good.

Is there a reason for this code?

If not I will put in a PR for the changes.

Cheers

Andy

**Comment by raysan5** [comment]
@AndrewCapon Good catch! Just reviewed it! Thanks!

**Comment by AndrewCapon** [comment]
Hi @raysan5 

There is another bit of code a bit lower as well:

```
gestureEvent.pointId[0] = 0;	                
gestureEvent.pointId[1] = 1;	                
gestureEvent.pointId[2] = 2;	
gestureEvent.pointId[3] = 3;

gestureEvent.position[0] = CORE.Input.Touch.position[0];	
gestureEvent.position[1] = CORE.Input.Touch.position[1];	
gestureEvent.position[2] = CORE.Input.Touch.position[2];	
gestureEvent.position[3] = CORE.Input.Touch.position[3];
```

**Comment by raysan5** [comment]
@AndrewCapon reviewed!
