### ISSUE TITLE
[core] Methods to return PersistentAppStorage, Temp, Desktop system folders

### ISSUE THREAD

**Issue by LxeC** [raysan5/raylib#3327]
We have methods like `GetApplicationDirectory()` and `GetWorkingDirectory()`, but it would be really useful to have a few more system folders that'd be useful for games and apps in a cross-platform manner. I'd like to suggest at least these folders "PersistentAppStorage", "Temp", "Desktop".

**PersistentAppStorage**
A folder like `C://Users/<user>/AppData/LocalLow/` or `C://Users/<user>/AppData/Roaming/` on Windows, `~/Library/Application Support/` on Mac, `$XDG_CONFIG_HOME/` or `$HOME/.config/` on Linux, `/storage/emulated/<userid>/Android/data/<packagename>/files` on Android, `/var/mobile/Containers/Data/Application/<guid>/Documents` on iOS.
Why? A lot of programs and games use those folders to save persistent files such as savefiles or app configurations in their own subfolder.

**Temp**
A folder like `C://Users/<user>/AppData/Local/Temp/` on Windows.
Why? We can use the temporary directory to store and load temporary files needed by our application. They will be cleared by the OS later on.

**Desktop**
A folder like `C://Users/<user>/Desktop/` on Windows.
Why? We can use this folder for storing immediately visible data to the user. Also could be used as a default/initial saving location.

These would be the proposed functions:
```c
const char *GetPersistentAppStorageDirectory(void);
const char *GetTempDirectory(void);
const char *GetDesktopDirectory(void);
```
or as a single method with a flag
```c
const char *GetSystemDirectory(int flag); // SYSTEM_DIRECTORY_TEMP, SYSTEM_DIRECTORY_APPSTORAGE, SYSTEM_DIRECTORY_DESKTOP
```
This way could be more condensed and future proof if Raylib decides to include more system folders (e.g. HOME, DOCUMENTS, MUSIC, VIDEOS, FONTS).

*What should happen if the target platform doesn't have e.g. a Desktop interface/folder?**
In that case, the methods could fall back and try to return the value from `GetApplicationDirectory()`.

**Comment by ubkp** [comment]
IMHO, there are so many possible env vars that their use is very situational. If you know what you want to use, probably could just do something like this instead:

```
#include "raylib.h"
#include <stdlib.h>

int main(void) {
    InitWindow(800, 450, "getenv test");
    SetTargetFPS(60);

    #if defined (PLATFORM_DESKTOP)
        #if defined(_WIN32)
            const char *str = getenv("APPDATA");
        #elif defined(__linux__)
            const char *str = getenv("XDG_CONFIG_HOME");
        #elif defined(__APPLE__)
            const char *str = getenv("SOMETHING");
        #endif
    #elif defined(PLATFOM_ANDROID)
            const char *str = getenv("SOMETHING");
    #endif

    TraceLog(LOG_INFO, "str: %s", str);

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(RAYWHITE);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```

**Comment by Peter0x44** [comment]
I think this is well outside raylib's scope, and those directories and paths aren't even analogous/existing on every platform
It's situational and something a user should manage for himself

**Comment by Peter0x44** [comment]
I think it should work well in raylib-extras, as more specific helper functions
See https://github.com/raylib-extras/extras-c

**Comment by raysan5** [comment]
I think querying those directories is a bit out-of-scope for raylib and it implies a good amount of platform-specific code (I did some of those queries on one of my tools using Win32 API, it was a pain). So, not plans to implement it for the moment.
