### ISSUE TITLE
[examples] `core_input_multitouch` example issues on Raspberry Pi

### ISSUE THREAD

**Issue by AndrewCapon** [raysan5/raylib#3336]
### Issue description

If you add one touch and then another touch, then release the first touch. Two touches are now being registered for the second touch.

This is a bit multi faceted.

When EV_REL or EV_ABS messages are received with one touch they will be on slot 0, if another touch is added then these messages stay on slot 0, if the original touch is then released the messages will start being received on slot 1.

In the EventThread for EV_REL and EV_ABS we have code like:
```
CORE.Input.Touch.position[0].x = CORE.Input.Mouse.currentPosition.x;
```

So even thought we are getting the messages on slot 1 which is updating `CORE.Input.Touch.position[1].x`, we also have code that is setting `CORE.Input.Touch.position[0].x`, so we get two touches with the same coordinates.

The other places where `CORE.Input.Touch.position[0].x` is found are:

'GetMouseX()' for 'PLATFORM_ANDROID'
'GetMouseY()' for 'PLATFORM_ANDROID'
'GetTouchX(void)' for 'PLATFORM_ANDROID' and 'PLATFORM_WEB'
'GetTouchY(void)' for 'PLATFORM_ANDROID' and 'PLATFORM_WEB'

These should possible be changed to use the index of the first valid touch and shouldn't just be overwriting index 0?

So as a quick test I just ifdefed the setting of index 0 out, the example still did not work.

The issue then was a simple one, the touches are updated by slot, GetTouchPointCount() returns the number of slots in use but they are not necessarily starting at index 0 and there also can be gaps, we could have slot 2 and slot 5 for instance depending on what fingers had been released.

The loops in the example all look like:
```
for (int i = 0; i < tCount; ++i) touchPositions[i] = GetTouchPosition(i);
``` 

Changing them to the following makes the example then work correctly:
```
for (int i = 0; i < MAX_TOUCH_POINTS; ++i) touchPositions[i] = GetTouchPosition(i);
```

I am happy to make some changes to the code and put in a PR, I thought the simplest solution is to keep track of the first touch slot in use and use that, what do you think?

Cheers

Andy

### Environment

Raspberry Pi, DRM

**Comment by ubkp** [comment]
@AndrewCapon Currently there's an effort to split `rcore` into submodules (as per https://github.com/raysan5/raylib/issues/3313). If you could hold this for a bit, I think it will be substantially easier to implement, review and test after the split.

**Comment by AndrewCapon** [comment]
Absolutely.

**Comment by raysan5** [comment]
@AndrewCapon `rcore` platform module has been already splitted, [`rcore_drm.c`](https://github.com/raysan5/raylib/blob/master/src/rcore_drm.c) is the RPI native mode. If you want to contribute you are welcome.

**Comment by raysan5** [comment]
As the input mechanisms are being redesign for `PLATFORM_DRM` I'm closing this issue.
