### ISSUE TITLE
[models] Adding color to drawMeshInstanced

### ISSUE THREAD

**Issue by khornel** [raysan5/raylib#3337]
### Issue description

GPU instancing doesn't seem super useful if you can't have some variation in each instance drawn, as you rarely just want a bunch of **exactly** the same thing on screen. I propose adding an optional color array parameter to the drawMeshInstanced function. The user can then decide whether they want to use it for color information or something else, like texture animation or texture atlas offsets.

### Code Example

I tried just hacking it in rmodels.c and it worked perfectly.

```C++
instanceColors = (float4*)RL_MALLOC(instances * sizeof(float4));

for (int i = 0; i < instances; i++) instanceColors[i] = ColorToFloatV(colors[i]);

rlEnableVertexArray(mesh.vaoId);

instancesVboId = rlLoadVertexBuffer(instanceColors, instances * sizeof(float4), false);

rlEnableVertexAttribute(material.shader.locs[SHADER_LOC_COLOR_DIFFUSE]);
rlSetVertexAttribute(material.shader.locs[SHADER_LOC_COLOR_DIFFUSE], 4, RL_FLOAT, 0, sizeof(Vector4), 0);
rlSetVertexAttributeDivisor(material.shader.locs[SHADER_LOC_COLOR_DIFFUSE], 1);

rlDisableVertexBuffer();
rlDisableVertexArray();
```

**Comment by raysan5** [comment]
@khornel This is a breaking change that I'd prefer to avoid, could you provide some use cases? also, beside instance colors, could be additional attributes required?

**Comment by raysan5** [comment]
> I ended up changing it so you supply an array of floats and a stride, to avoid having floats clamped and discretized when converting to color data. This also gives the user way more flexibility in what type of data to supply. Maybe it could be a DrawMeshInstancedEx call to avoid breaking compatibility and sticking to the existing convention.

I think this is a very good alternative and it sounds quite generic and flexible. Feel free to send a PR.

**Comment by raysan5** [comment]
It seems this new feature was not a priority but just for a very specific use case. Just closing this issue.
