### ISSUE TITLE
[core] Platforms split into separate modules: `PLATFORM_WEB`, `PLATFORM_DESKTOP` status

### ISSUE THREAD

**Issue by ubkp** [raysan5/raylib#3339]
Issue to more easily track `PLATFORM_WEB` and `PLATFORM_DESKTOP` status for:
- #3313 

### Modules checked status
| module | android | desktop (linux) | web | comment |
| --- | :---: | :---: | :---: | --- |
| `raylib` | :question: | :heavy_check_mark: | :heavy_check_mark: | - |
| `examples/audio` | :question: | :heavy_check_mark: | :heavy_check_mark: | - |
| `examples/core` | :question: | :heavy_check_mark: | :heavy_check_mark: | See note A |
| `examples/models` | :question: | :heavy_check_mark: | :heavy_check_mark: | See note A |
| `examples/others` | :question: | :heavy_check_mark: | :heavy_check_mark: | See note B |
| `examples/shaders` | :question: | :heavy_check_mark: | :heavy_check_mark: | - |
| `examples/shapes` | :question: | :heavy_check_mark: | :heavy_check_mark: | - |
| `examples/text` | :question: | :heavy_check_mark: | :heavy_check_mark: | - |
| `examples/textures` | :question: | :heavy_check_mark: | :heavy_check_mark: | - |

- A. For `PLATFORM_WEB` the `core_custom_frame_control`, `core_loading_thread`, `core_window_flags` and `models_skybox` examples compile but don't work. However, they also don't work on current master branch (https://github.com/raysan5/raylib/commit/c8a6093d52ff6bdd17f9df012f6666b74629f595).

- B. For `PLATFORM_WEB` the `raylib_opengl_interop` and `rlgl_standalone` examples are not compiling, but they are also not compiling on current master branch (https://github.com/raysan5/raylib/commit/c8a6093d52ff6bdd17f9df012f6666b74629f595). `rlgl_compute_shader` compiles on both, but doesn't work on either.

### Functions checked status
| function | core | android | desktop | web | comment |
| --- | :---: | :---: | :---: | :---: | --- |
| `InitGraphicsDevice` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetupViewport` | :heavy_check_mark: | - | - | - | - |
| `SetupFramebuffer` | :heavy_check_mark: | - | - | - | - |
| `InitTimer` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `InitWindow` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `WindowShouldClose` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `CloseWindow` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `IsWindowReady` | :heavy_check_mark: | - | - | - |  |
| `IsWindowFullscreen` | :heavy_check_mark: | - | - | - | - |
| `IsWindowHidden` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `IsWindowMinimized` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `IsWindowMaximized` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `IsWindowFocused` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `IsWindowResized` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `IsWindowState` | :heavy_check_mark: | - | - | - | - |
| `ToggleFullscreen` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `MaximizeWindow` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `MinimizeWindow` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `RestoreWindow` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `ToggleBorderlessWindowed` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowState` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `ClearWindowState` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowIcon` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowIcons` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowTitle` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowPosition` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowMonitor` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowMinSize` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowMaxSize` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowSize` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowOpacity` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetWindowFocused` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetWindowHandle` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetScreenWidth` | :heavy_check_mark: | - | - | - | - |
| `GetScreenHeight` | :heavy_check_mark: | - | - | - | - |
| `GetRenderWidth` | :heavy_check_mark: | - | - | - | - |
| `GetRenderHeight` | :heavy_check_mark: | - | - | - | - |
| `GetMonitorCount` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetCurrentMonitor` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMonitorPosition` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMonitorWidth` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMonitorHeight` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMonitorPhysicalWidth` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMonitorPhysicalHeight` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMonitorRefreshRate` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetWindowPosition` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetWindowScaleDPI` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMonitorName` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetClipboardText` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetClipboardText` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `EnableEventWaiting` | :heavy_check_mark: | - | - | - | - |
| `DisableEventWaiting` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `SwapScreenBuffer` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `PollInputEvents` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `WaitTime` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `ShowCursor` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `HideCursor` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `IsCursorHidden` | :heavy_check_mark: | - | - | - | - |
| `EnableCursor` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `DisableCursor` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `IsCursorOnScreen` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `ClearBackground` | :heavy_check_mark: | - | - | - | - |
| `BeginDrawing` | :heavy_check_mark: | - | - | - | - |
| `EndDrawing` | :heavy_check_mark: | - | - | - | - |
| `BeginMode2D` | :heavy_check_mark: | - | - | - | - |
| `EndMode2D` | :heavy_check_mark: | - | - | - | - |
| `BeginMode3D` | :heavy_check_mark: | - | - | - | - |
| `EndMode3D` | :heavy_check_mark: | - | - | - | - |
| `BeginTextureMode` | :heavy_check_mark: | - | - | - | - |
| `EndTextureMode` | :heavy_check_mark: | - | - | - | - |
| `BeginShaderMode` | :heavy_check_mark: | - | - | - | - |
| `EndShaderMode` | :heavy_check_mark: | - | - | - | - |
| `BeginBlendMode` | :heavy_check_mark: | - | - | - | - |
| `EndBlendMode` | :heavy_check_mark: | - | - | - | - |
| `BeginScissorMode` | :heavy_check_mark: | - | - | - | - |
| `EndScissorMode` | :heavy_check_mark: | - | - | - | - |
| `BeginVrStereoMode` | :heavy_check_mark: | - | - | - | - |
| `EndVrStereoMode` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `LoadVrStereoConfig` | :heavy_check_mark: | - | - | - | - |
| `UnloadVrStereoConfig` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `LoadShader` | :heavy_check_mark: | - | - | - | - |
| `LoadShaderFromMemory` | :heavy_check_mark: | - | - | - | - |
| `IsShaderReady` | :heavy_check_mark: | - | - | - | - |
| `UnloadShader` | :heavy_check_mark: | - | - | - | - |
| `GetShaderLocation` | :heavy_check_mark: | - | - | - | - |
| `GetShaderLocationAttrib` | :heavy_check_mark: | - | - | - | - |
| `SetShaderValue` | :heavy_check_mark: | - | - | - | - |
| `SetShaderValueV` | :heavy_check_mark: | - | - | - | - |
| `SetShaderValueMatrix` | :heavy_check_mark: | - | - | - | - |
| `SetShaderValueTexture` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `GetMouseRay` | :heavy_check_mark: | - | - | - | - |
| `GetCameraMatrix` | :heavy_check_mark: | - | - | - | - |
| `GetCameraMatrix2D` | :heavy_check_mark: | - | - | - | - |
| `GetWorldToScreen` | :heavy_check_mark: | - | - | - | - |
| `GetWorldToScreenEx` | :heavy_check_mark: | - | - | - | - |
| `GetWorldToScreen2D` | :heavy_check_mark: | - | - | - | - |
| `GetScreenToWorld2D` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `SetTargetFPS` | :heavy_check_mark: | - | - | - | - |
| `GetFPS`| :heavy_check_mark: | - | - | - | - |
| `GetFrameTime` | :heavy_check_mark: | - | - | - | - |
| `GetTime` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| - | core | android | desktop | web | comment |
| `SetConfigFlags` | :heavy_check_mark: | - | - | - | - |
| `TakeScreenshot` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetRandomValue` | :heavy_check_mark: | - | - | - | - |
| `SetRandomSeed` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `OpenURL` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| - | core | android | desktop | web | comment |
| `FileExists` | :heavy_check_mark: | - | - | - | - |
| `IsFileExtension` | :heavy_check_mark: | - | - | - | - |
| `DirectoryExists` | :heavy_check_mark: | - | - | - | - |
| `GetFileLength` | :heavy_check_mark: | - | - | - | - |
| `GetFileExtension` | :heavy_check_mark: | - | - | - | - |
| `GetFileName` | :heavy_check_mark: | - | - | - | - |
| `GetFileNameWithoutExt` | :heavy_check_mark: | - | - | - | - |
| `GetDirectoryPath` | :heavy_check_mark: | - | - | - | - |
| `GetPrevDirectoryPath` | :heavy_check_mark: | - | - | - | - |
| `GetWorkingDirectory` | :heavy_check_mark: | - | - | - | - |
| `GetApplicationDirectory` | :heavy_check_mark: | - | - | - | - |
| `LoadDirectoryFiles` | :heavy_check_mark: | - | - | - | - |
| `LoadDirectoryFilesEx` | :heavy_check_mark: | - | - | - | - |
| `UnloadDirectoryFiles` | :heavy_check_mark: | - | - | - | - |
| `ChangeDirectory` | :heavy_check_mark: | - | - | - | - |
| `IsPathFile` | :heavy_check_mark: | - | - | - | - |
| `IsFileDropped` | :heavy_check_mark: | - | - | - | - |
| `LoadDroppedFiles` | :heavy_check_mark: | - | - | - | - |
| `UnloadDroppedFiles` | :heavy_check_mark: | - | - | - | - |
| `GetFileModTime` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `ScanDirectoryFiles` | :heavy_check_mark: | - | - | - | - |
| `ScanDirectoryFilesRecursively` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `CompressData` | :heavy_check_mark: | - | - | - | - |
| `DecompressData` | :heavy_check_mark: | - | - | - | - |
| `EncodeDataBase64` | :heavy_check_mark: | - | - | - | - |
| `DecodeDataBase64` | :heavy_check_mark: | - | - | - | - |
| - | core | android | desktop | web | comment |
| `IsKeyPressed` | :heavy_check_mark: | - | - | - | - |
| `IsKeyDown` | :heavy_check_mark: | - | - | - | - |
| `IsKeyReleased` | :heavy_check_mark: | - | - | - | - |
| `IsKeyUp` | :heavy_check_mark: | - | - | - | - |
| `GetKeyPressed` | :heavy_check_mark: | - | - | - | - |
| `GetCharPressed` | :heavy_check_mark: | - | - | - | - |
| `SetExitKey` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| - | core | android | desktop | web | comment |
| `IsGamepadAvailable` | :heavy_check_mark: | - | - | - | - |
| `GetGamepadName` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetGamepadAxisCount` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetGamepadAxisMovement` | :heavy_check_mark: | - | - | - | - |
| `IsGamepadButtonPressed` | :heavy_check_mark: | - | - | - | - |
| `IsGamepadButtonDown` | :heavy_check_mark: | - | - | - | - |
| `IsGamepadButtonReleased` | :heavy_check_mark: | - | - | - | - |
| `IsGamepadButtonUp` | :heavy_check_mark: | - | - | - | - |
| `GetGamepadButtonPressed` | :heavy_check_mark: | - | - | - | - |
| `SetGamepadMappings` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| - | core | android | desktop | web | comment |
| `IsMouseButtonPressed` | :heavy_check_mark: | - | - | - | - |
| `IsMouseButtonDown` | :heavy_check_mark: | - | - | - | - |
| `IsMouseButtonReleased` | :heavy_check_mark: | - | - | - | - |
| `IsMouseButtonUp` | :heavy_check_mark: | - | - | - | - |
| `GetMouseX` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMouseY` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMousePosition` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMouseDelta` | :heavy_check_mark: | - | - | - | - |
| `SetMousePosition` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `SetMouseOffset` | :heavy_check_mark: | - | - | - | - |
| `SetMouseScale` | :heavy_check_mark: | - | - | - | - |
| `GetMouseWheelMove` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetMouseWheelMoveV` | :heavy_check_mark: | - | - | - | - |
| `SetMouseCursor` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| - | core | android | desktop | web | comment |
| `GetTouchX` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetTouchY` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetTouchPosition` | - | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | - |
| `GetTouchPointId` | :heavy_check_mark: | -  | - | - | - |
| `GetTouchPointCount` | :heavy_check_mark:  | - | - | - | - |

### Changelog
- #3329
- #3334
- #3338
- #3343
- #3345

### Environment
- Compiled `PLATFORM_DESKTOP` with `gcc` on Linux (Mint 21.1 64-bit). And tested it on Linux (Mint 21.1 64-bit).
- Compiled `PLATFORM_WEB` with `emscripten/emsdk` on Linux (Mint 21.1 64-bit). And tested it on Firefox (115.1.0esr 64-bit) and Chromium (115.0.5790.170 64-bit) both running on Linux (Mint 21.1 64-bit).

### Edits
**1, 2, 3, 4, 6, 8, 9, 11, 12, 13, 14, 15:** updated functions checked status.
**5, 7:** updated changelog.
**10:** formatting.
**16:** updated modules status and notes; formatting.
**17:** updated environemnt.

**Comment by ubkp** [comment]
@raysan5 When you can, could you please update the Wishlist (#2952) examples section with:
```
Issues with several examples not working on `PLATFORM_WEB`:

- [ ] **REVIEW: Example: `models_skybox`**. WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range _glDisableVertexAttribArray.
- [ ] **REVIEW: Example: `core_custom_frame_control`**.
- [ ] **REVIEW: Example: `core_loading_thread`**.
- [ ] **REVIEW: Example: `core_window_flags`**.
- [ ] **REVIEW: Example: `raylib_opengl_interop`**.
- [ ] **REVIEW: Example: `rlgl_standalone`**.
```
These examples are also not working for `PLATFORM_WEB` on current master branch (557aeff), so their issues are unrelated to the split.

**Comment by raysan5** [comment]
@ubkp done!

**Comment by raysan5** [comment]
Oh! thanks for the detailed functions status table!

**Comment by ubkp** [comment]
@raysan5 Thank you very much!

No problem. By the way, since I'm going through all functions, would you like me to also handle `rcore_desktop.c`? So you can be free to check other issues.

**Comment by raysan5** [comment]
@ubkp That would be great, thank you very much, I'm a bit busy this days. In any case, feel free to keep sending PRs for merging so I can pick up after some PR.

**Comment by ubkp** [comment]
@raysan5 Okay, I'm on it. :+1:

**Comment by ubkp** [comment]
Following @michaelfiber, I'm also closing this issue. As far as I could test `PLATFORM_WEB` and `PLATFORM_DESKTOP` are working correctly. Will reopen if necessary, but I think both are on a pretty good state.
