### ISSUE TITLE
[models] GLTF UV maps are loaded incorrectly

### ISSUE THREAD

**Issue by khornel** [raysan5/raylib#3340]
### Issue description

Currently each UV map from a GLTF file is allocated in memory and assigned to the first UV map of a mesh in the order they are loaded, and I don't think overwritten UV maps are freed from memory. You end up with the last UV map in a GLTF file being assigned to the first UV map of the mesh, which is the opposite of what I would expect.

I would propose loading the first UV map from the GLTF file to texcoords of the mesh and the second UV map to texcoords2, and then just skipping the rest.

### Code Example

https://github.com/raysan5/raylib/blob/557aeff253255a7ce2aac3b1872aeefba6ff2a51/src/rmodels.c#L5015C31-L5015C31

**Comment by dhairyagupta2603** [comment]
Could I take up this issue?

**Comment by raysan5** [comment]
@dhairyagupta2603 Any news on this issue? Did you take a look to it?

**Comment by raysan5** [comment]
> I would propose loading the first UV map from the GLTF file to texcoords of the mesh and the second UV map to texcoords2, and then just skipping the rest.

@khornel That approach sounds good to me, feel free to send a PR with the improvements.

**Comment by raysan5** [comment]
It seems there is no follow up on this improvement, closing it.
