### ISSUE TITLE
[rlgl] rlReadScreenPixels overrides alpha channel

### ISSUE THREAD

**Issue by hatkidchan** [raysan5/raylib#3341]
### Issue description

Image returned by `LoadImageFromScreen` (or by `rlReadScreenPixels`) has alpha channel set to 255.

Looking at the sources, it happens in rlgl.h:
https://github.com/raysan5/raylib/blob/557aeff253255a7ce2aac3b1872aeefba6ff2a51/src/rlgl.h#L3432-L3442
is there any reason to do so? I'm trying to render a transparent GIF and I kinda.. need the transparency. 

### Environment

```
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) HD Graphics 4600 (HSW GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 23.1.7-arch1.1
INFO:     > GLSL:     4.60
```

### Issue Screenshot

![rl-transparent](https://github.com/raysan5/raylib/assets/35804000/f992b705-e517-4b44-a2e6-88028e355612)
![image](https://github.com/raysan5/raylib/assets/35804000/a878e16e-881c-4e86-a3c1-1d97d917611e)

### Code Example

```c
// x-run: ~/scripts/runc.sh % ~/downloads/raylib-master/raylib-master/src/libraylib.a -lm
#include <raylib.h>

int main(void) {
  SetConfigFlags(FLAG_WINDOW_TRANSPARENT);
  InitWindow(320, 240, "transparent");

  while (!WindowShouldClose()) {
    BeginDrawing();
    ClearBackground(BLANK);
    DrawText("This image should have a transparent background", 32, 128, 8, WHITE);
    EndDrawing();
    if (IsKeyPressed(KEY_S)) {
      Image screen = LoadImageFromScreen();
      ExportImage(screen, "rl-transparent.png");
      UnloadImage(screen);
    }
  }
}
```

### Workaround
Using a RenderTexture as a temporary buffer helps, since it doesn't override the transparency
```c
// x-run: ~/scripts/runc.sh % ~/downloads/raylib-master/raylib-master/src/libraylib.a -lm
#include <raylib.h>

int main(void) {
  SetConfigFlags(FLAG_WINDOW_TRANSPARENT);
  InitWindow(320, 240, "transparent");

  RenderTexture2D rtex = LoadRenderTexture(320, 240);

  while (!WindowShouldClose()) {
    BeginDrawing();
    ClearBackground(BLANK);
    BeginTextureMode(rtex);
    {
      ClearBackground(BLANK);
      DrawText("This image should have a transparent background", 32, 128, 8, WHITE);
    }
    EndTextureMode();

    if (IsKeyPressed(KEY_S)) {
      Image screen = LoadImageFromTexture(rtex.texture);
      ImageFlipVertical(&screen);
      ExportImage(screen, "rl-transparent.png");
      UnloadImage(screen);
    }

    DrawTextureRec(rtex.texture, (Rectangle) { 0, 0, 320, -240}, (Vector2) { 0, 0 }, WHITE);

    EndDrawing();
  }
}
```

though I'd want to avoid that, since it's a bit ugly and I'd have to flip it manually, instead of relying on it being flipped already. Plus, I also just want to know why it's overwriting it in the first place

**Comment by raysan5** [comment]
Afaik, if alpha was not set to 255 for the main framebuffer, there were blending issues when trying to capture screen and drawing elements with some alpha applied.

I mean, elements with transparency are correctly blended with background color but returned screenshot did not considered it. That line was added to allow users to retrieve exactly what was seen draw on the screen with no surprises. I remember having some issues with that on the past.

I understand this approach could not be the best one for all situations.

**Comment by Julianiolo** [comment]
In general for rendering something (e.g. for outputting it to a file) it is probably a better idea to use a render texture, as you have more control over what is happening.

Btw, @raysan5, it may have been me that reported that problem? I'm not sure though. I told you about some problem with transparent windows and transparent object, but I don't think it involved screen capture?

**Comment by raysan5** [comment]
This issue was describted here: https://github.com/raysan5/raylib/issues/36.
