### ISSUE TITLE
[rlgl] HDR 32bit texture not loading on Android 

### ISSUE THREAD

**Issue by AnasASK** [raysan5/raylib#3346]
### Issue description

I enabled .hdr support from config.h and rebuilt raylib for android.

unfortunately all I get is black texture.

### Environment

Using raylib 4.5
my android specs:
>     Android 9
>     Vendor: ARM
>     Renderer: Mali-G72 MP3
>     Version: OpenGL ES 3.2

### Issue Screenshot

Here is a comparison on desktop vs android:
![Screenshot from 2023-09-23 23-27-27](https://github.com/raysan5/raylib/assets/11005460/f3c34668-9a07-451a-ac18-53c002750fa7)
![image](https://github.com/raysan5/raylib/assets/11005460/f16565e1-50c4-4807-be69-f159609628bd)

### Code Example

This is my code:

Use any 2k hdr image.
```c
Texture2D t = LoadTexture("buildings.hdr");
// later in the game loop..
DrawTexturePro(t, (Rectangle){0,0,2048,1024},(Rectangle){0,0,10,5}, (Vector2){0,0},0 , WHITE);
```

**Comment by raysan5** [comment]
raylib on Android uses by default OpenGL ES 2.0 and support for float textures depends on `GL_OES_texture_float` extension. It is [checked by `rlgl` on initialization](https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L2328) but maybe it does not detect it. It should be debugged.

**Comment by raysan5** [comment]
As noone is caring for this issue, I'm just closing it. Feel free to reopen if the program is debugged and more info is provided.
