### ISSUE TITLE
[core] Gamepad axis and buttons not recognized

### ISSUE THREAD

**Issue by glebov21** [raysan5/raylib#3356]
Game controller: Thrustmaster Hotas Warthog (throttle and joystick)

Windows core_input_gamepad example not recognize buttons and axis. But show controller name.
![image](https://github.com/raysan5/raylib/assets/693132/624335d3-eaa8-4edc-9a3a-8245aa710a01)

Web version working perfect.
![image](https://github.com/raysan5/raylib/assets/693132/58abf808-76af-4779-9a99-e1fe1715f7e7)

**Comment by glebov21** [comment]
Solved by using glfw functions directly.
For C# you can build raylib with external glfw:

Open project: raylib\projects\VS2019
Add AdditionalDependencies: glfw3.lib;glfw3dll.lib;glfw3_mt.lib; (download from official website)
remove file-link to rglfw.c
add PreprocessorDefinitions: GLFW_DLL


Or you can modify raylib project with external glfw functions

**Comment by glebov21** [comment]
Solved by using glfw functions directly.
For C# you can build raylib with external glfw:

Open project: raylib\projects\VS2019
Add AdditionalDependencies: glfw3.lib;glfw3dll.lib;glfw3_mt.lib; (download from official website)
remove file-link to rglfw.c
add PreprocessorDefinitions: GLFW_DLL


Or you can modify raylib project with external glfw functions

**Comment by SuperUserNameMan** [comment]
So, was it a Raylib bug or not ?

**Comment by glebov21** [comment]
> So, was it a Raylib bug or not ?

I think yes. Raylib can't work with new game controllers.

**Comment by SuperUserNameMan** [comment]
then why did you close this issue ?

**Comment by bztsrc** [comment]
Or, even simpler: replace [mappings.h](https://github.com/raysan5/raylib/blob/master/src/external/glfw/src/mappings.h) from the latest glfw's [mappings.h](https://github.com/glfw/glfw/blob/master/src/mappings.h), and compile raylib as usual. 

But I don't think using external glfw will work, it looks like the version in raylib has lot more controllers defined, 1499 records vs 934 records.

BTW the most up to date controller database can be found here: [gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt). This is a text file, so do a search and replace with your editor to add `"` at the beginning and `",` at the end of lines and then you can paste it into mappings.h, or run `make update_mappings` in glfw's repo.

The latest db has 1972 records (so about 1000 controllers more than the upstream glfw's version, and about 500 more than raylib's), chances are good your controller is already in it. But if not, then use a [mapping tool](https://github.com/gabomdq/SDL_GameControllerDB/tree/master#mapping-tools) to generate a db line specifically for your controller, and add that line to mappings.h.

**Comment by glebov21** [comment]
No, I need universal solution with custom controllers. I don't need rebuild every time when new controller on sale.

**Comment by raysan5** [comment]
I think @bztsrc solution is the best approach. No plans for other approaches.

**Comment by bztsrc** [comment]
> No, I need universal solution with custom controllers.

Yeah pal, we all do, but such a solution doesn't exists.

When your controller triggers an event, the low-level OS driver sends a bit-chunk to the application. Which bit corresponds to which button and axis differs for every controller (and for every OS), that's why you need a mapping. To make that bit-chunk universal you would have to convince Microsoft, Sony and all the other controller manufacturers to send a standardized bit-chunk, plus you'd have to rewrite all gamepad drivers for all OSes. Not going to happen any time soon.

Note: this has nothing to do with raylib. It is glfw that receives this bit-chunk and this mapping is implemented in glfw. [raylib just uses](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L5292) what glfw provides.

> I don't need rebuild every time when new controller on sale.

Yes, you do, having mappings.h in glfw means for every new controller you'll need a new line in this file, and you'll have to recompile glfw (be it the one shipped with raylib or an external dll doesn't matter). 

Cheers,
bzt

**Comment by glebov21** [comment]
> > No, I need universal solution with custom controllers.
> 
> Yeah pal, we all do, but such a solution doesn't exists.
> 
> When your controller triggers an event, the low-level OS driver sends a bit-chunk to the application. Which bit corresponds to which button and axis differs for every controller (and for every OS), that's why you need a mapping. To make that bit-chunk universal you would have to convince Microsoft, Sony and all the other controller manufacturers to send a standardized bit-chunk, plus you'd have to rewrite all gamepad drivers for all OSes. Not going to happen any time soon.
> 
> Note: this has nothing to do with raylib. It is glfw that receives this bit-chunk and this mapping is implemented in glfw. [raylib just uses](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L5292) what glfw provides.
> 
> > I don't need rebuild every time when new controller on sale.
> 
> Yes, you do, having mappings.h in glfw means for every new controller you'll need a new line in this file, and you'll have to recompile glfw (be it the one shipped with raylib or an external dll doesn't matter).
> 
> Cheers, bzt

Strange. I use glfwGetJoystickButtons and he return all button to me.
