### ISSUE TITLE
[utils] `LoadFileData()` segfaults when dataSize param is `NULL`

### ISSUE THREAD

**Issue by danielchasehooper** [raysan5/raylib#3365]
### Issue description

LoadFileData segfaults when dataSize param is NULL. It'd be more helpful if it printed an error message and then `abort()`'ed

### Environment

macOS 

### Code Example

```c
char *data = LoadFileData("file.txt", NULL);
```

**Comment by raysan5** [comment]
For most of the raylib functions is up to the user to validate the inputs, I raylib should consider all possible bad-use scenarios it would require reviewing most functions of the library and it will increase source-code complexity.

**Comment by raysan5** [comment]
It's up to the user to avoid this kind of bad-use cases, same issue will happen with most raylib functions receiving some pointer.

**Comment by vittorioromeo** [comment]
> It's up to the user to avoid this kind of bad-use cases, same issue will happen with most raylib functions receiving some pointer.

@raysan5: `raylib` should at the very least `assert`.
