### ISSUE TITLE
[core] Support pinch gestures

### ISSUE THREAD

**Issue by danielchasehooper** [raysan5/raylib#3369]
### Issue description

I'd really like to be able to detect and respond to pinch gestures made on the trackpad, and touch screens – both native and web.
I understand that glfw might not offer this, but you can work around it using code like the bit below.

### Environment

macOS, web, iOS 

### Code Example

my workaround for macOS. Still working on a workaround for web
```objc
#import <Foundation/Foundation.h>
#import <objc/runtime.h>
#import <Appkit/AppKit.h>

float magnification = 0; // can be read externally in main loop

@implementation NSWindow (PinchGestureSwizzle)

- (void)swizzled_sendEvent:(NSEvent *)event {
    if (event.type == NSEventTypeMagnify) {
        magnification = event.magnification;
    }
    
    // Call the original implementation
    [self swizzled_sendEvent:event];
}

@end

void EnableMagnificationEvents(void) { // called at the start of program
        Class class = [NSWindow class];
        Method originalMethod = class_getInstanceMethod(class, @selector(sendEvent:));
        Method swizzledMethod = class_getInstanceMethod(class, @selector(swizzled_sendEvent:));
        method_exchangeImplementations(originalMethod, swizzledMethod);
}

```

**Comment by raysan5** [comment]
It seems it has been in the works for some years now https://github.com/glfw/glfw/issues/90

**Comment by danielchasehooper** [comment]
Yeah I saw that. Doesn’t seem to be a priority for them 😝

**Comment by danielchasehooper** [comment]
A fix based on the code in my initial comment would allow raylib to move forward without waiting on a 10 year old issue to get resolved

**Comment by ubkp** [comment]
Sadly that's very platform specific.

**Comment by raysan5** [comment]
@danielchasehooper Sincerely I'm not sure how it can be addressed at raylib-level, feel free to send a PR if it can be somewhat integrated with raylib in a not-hacky way. Also note that recently SDL2 platform backend support has been added to raylib, not sure if it exposes this kind of functionality... but at the moment I don't know how should it be exposed by raylib.

**Comment by raysan5** [comment]
Probably this issue gets fixed with the new SDL backend.
