### ISSUE TITLE
[rlgl] Flickering when rendering 3d on Android

### ISSUE THREAD

**Issue by AnasASK** [raysan5/raylib#3373]
### Issue description

3d models flicker on android.

### Environment

Raylib 4.5
Android 9
Vendor: ARM
Renderer: Mali-G72 MP3
Version: OpenGL ES 3.2

### Issue Screenshot

https://github.com/raysan5/raylib/assets/11005460/467d1b35-fdb6-4906-b4c0-f32bbb595b85

### Code Example

I used this [example](https://github.com/raysan5/raylib/blob/master/examples/models/models_geometric_shapes.c) with slight edits. Any other example should work as well.

**Comment by AnasASK** [comment]
Ok I found the solution: simply increase the value of `RL_CULL_DISTANCE_NEAR` in `void BeginMode3D(Camera camera)`
I wish those values of near/far clipping weren't hard coded.

**Comment by JanHelbling** [comment]
> `RL_CULL_DISTANCE_NEAR`

Tell me your value!
