### ISSUE TITLE
[docs] Audio streams are poorly documented (and poorly understood)

### ISSUE THREAD

**Issue by 7ombie** [raysan5/raylib#3374]
There's currently only one example that really deals with raw audio and sample generation (the rest do playback). That example has multiple things going on, with large blocks commented out, and limited documentation. It's rated three stars for difficulty, but it should be a simple thing.

I'd recommend adding an example that just generates white noise on a mono stream, then editing the existing example to focus on one thing too.

Best.

---

UPDATE: I attempted to use raylib to generate a single channel of white noise, and have not been able to.

My C skills are weak, and I'm not experienced with raylib either, but I have been programming almost 15 years, and have implemented similar things in similar contexts. I also posted [the problem to StackOverflow][so] (with a short example that works for a few milliseconds, then breaks), and nobody there has been able to help.

Documentation for the `AudioStream` API is insufficient.

[so]: https://stackoverflow.com/questions/77230859/how-to-play-raw-audio-with-raylib

**Comment by ubkp** [comment]
@7ombie Documentation could always be improved, but, being a fairly direct C library (instead of an engine), it's, IMHO, expected that the developer will inspect the source as needed. Not only for understanding it's mechanics, but also to expand or reimplement, as needed.

Either way, what you describe is certainly possible with `raylib`. Take a look at the excellent `rFXGen`:
- https://raylibtech.itch.io/rfxgen
- https://github.com/raysan5/rfxgen

**Comment by 7ombie** [comment]
Thanks for replying. I appreciate it.

I don't doubt it's *possible*, but the claim is "*raylib: it just works*", while the reality is that the community can't figure out how to make the most elementary things work, as the example code for this feature sucks. I literally asked how to render random samples on a single channel, and nobody (on StackOverflow) knew how to do it.

I don't mean to vent my frustration at you. Thanks again for responding. All the best.

**Comment by ubkp** [comment]
@7ombie Don't worry, I understand. Just would like to point that:

1. I think a good part of the raylib community is on Discord. You could have more luck asking there.

2. A big part of raylib is user contributions, specially the examples. So YMMV on that regard, as usually is on open source projects.

3. I don't believe you'll find many (any?) open source project without considerable funding (and a dedicated team) that manages to keep a good documentation. Luckly raylib is fairly direct, so it's easy to inspect the code to see what's going on. But, being a C libray, I'm afraid C is required knowledge.

4. I think it's important to stress what raylib isn't: an engine. And what it is: a library that provides quite a list of tools, with which you can implement amazing things and learn a lot. But it's expected that you'll handle most of the work.
