### ISSUE TITLE
[core] `InitWindow()` memory leak?

### ISSUE THREAD

**Issue by LukeTrynchukSilverback** [raysan5/raylib#3375]
```c++
#include "raylib.h"

int main()
{
	InitWindow(800, 600, "Test");    //All memory leaks are from allocations made from this line
	while (!WindowShouldClose())
	{
		BeginDrawing();
		ClearBackground(RAYWHITE);
		EndDrawing();
	}

	CloseWindow();
	return 0;
}
```
The above program results in a number of memory leaks (approximately 1.2mb). 

Some important details:

```
- Using Raylib 4.5 (installed via vcpkg)
- AMD Ryzen 9 3900X
- NVIDIA GeForce RTX 3080
- Driver version 537.42
- OpenGL 4.6
- Windows x64 version 10.0.19045 Build 19045
```

---

Attached is the exported details from Deleaker in a .txt file. I've also attached a screen shot of what I see in Deleaker. 

I've included the details I receive from Deleaker because it gives me more concise details, however I can confirm that the information is consistent with what I am seeing when doing a `_CrtDumpMemoryLeaks()`.

![image_2023-10-03_221606731](https://github.com/raysan5/raylib/assets/36450322/bc63fa0b-17a2-4a33-84b6-8b3ace62b737)

[memory_leak_InitWindow.txt](https://github.com/raysan5/raylib/files/12798264/memory_leak_InitWindow.txt)

**Comment by LukeTrynchukSilverback** [comment]
I did the same test on Raylib 4.2 and had no memory leaks.

**Comment by raysan5** [comment]
@LukeTrynchukSilverback No idea where this leak comes from from the attached information. I'd need more detailed info to review it. If not possible, it could be a false-positive related to video driver.

**Comment by raysan5** [comment]
Also, it should be tested on latest raylib from GitHub master branch and not on raylib 4.5 that it's about 7 months old.

**Comment by raysan5** [comment]
No more info provided, closing the issue.

**Comment by ruffianeo** [comment]
I have a (admittedly stupid) test application which opens a window to see a recorded chess game. If I call that enough times (less than 137), my Common Lisp runs out of memory. Here the call stack:

Unhandled memory fault at #x7FC7324ACB20.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] Exit debugger, returning to top level.

Backtrace:
  0: ("bogus stack frame")
  1: ("foreign function: rlglInit")
  2: ("foreign function: InitWindow")
  3: (INIT-WINDOW 1024 1024 "Game - ElektroTeacher Resident vs Piotr Korhonen  [2024.09.18]")
      Locals:
        HEIGHT = 1024
        TITLE = "Game - ElektroTeacher Resident vs Piotr Korhonen  [2024.09.18]"
        WIDTH = 1024

Thus, as I see it, `InitWindow` always calls `rlglInit` from `Initwindow` instead of remembering it has been initialized before, due to prior calls of `InitWindow`.

This repeated calling of a InitWindow() is not a main use case, I presume, if you write a game, but if you use the library to view some graphical stuff on occasion from within an application, this is an issue.

raylib version I use is:
commit b07967993f6b13d5edb02c596cde652a3db139a1 (HEAD -> master, origin/master, origin/HEAD)
Author: Antonis Geralis <43617260+planetis-m@users.noreply.github.com>
Date:   Wed Dec 25 23:08:42 2024 +0200

    Update version number for the nim wrapper (#4638)

**Comment by asdqwe** [comment]
> Thus, as I see it, `InitWindow` always calls `rlglInit` from `Initwindow` instead of remembering it has been initialized before, due to prior calls of `InitWindow`.

@ruffianeo It probably should be paired with a [CloseWindow](https://github.com/raysan5/raylib/blob/2492dd3d0a69efe77185daf708f9f8aa458113a8/src/rcore.c#L734) (that would call [rlglClose](https://github.com/raysan5/raylib/blob/2492dd3d0a69efe77185daf708f9f8aa458113a8/src/rcore.c#L749C5-L749C14)) before calling [InitWindow](https://github.com/raysan5/raylib/blob/2492dd3d0a69efe77185daf708f9f8aa458113a8/src/rcore.c#L614) again. But, yeah, definitely wasn't meant for that use case.

**Comment by ruffianeo** [comment]
@asdqwe I do call CloseWindow each time. 

```
(defun view-game (game
                 &key
                   (window-width 1024)
                   (window-height 1024))
  (init-window
   window-width window-height
   (format nil "Game - ~a vs ~a  [~a]"
           (property game :tags :white)
           (property game :tags :black)
           (property game :tags :date)))
  (set-target-fps 60)
  (let* ((res-col (init-resource-collection))
         (action-top (- window-height 40))
         (model (init-view-game-resources game res-col window-width window-height action-top))
         (chess-board (property model :chess-board))
         (to-start-position-button (property model :to-start))
         (to-prev-position-button (property model :to-prev))
         (to-next-position-button (property model :to-next))
         (to-end-position-button (property model :to-end)))
    (loop
      while (not (window-should-close))
      do (progn
           (setf model (update model))
           (begin-drawing)
           (clear-background *back-color*)
           (render-visual chess-board)
           (render-visual to-start-position-button)
           (render-visual to-prev-position-button)
           (render-visual to-next-position-button)
           (render-visual to-end-position-button)
           (let ((current-ply (property model :current-ply))
                 (n-moves (length (property model :game :moves))))
             (when (< current-ply n-moves)
                (draw-text
                 (format nil "ply: ~a move: ~a"
                         (property model :current-ply)
                         (move-to-uci-move
                          (aref (property model :game :moves) current-ply)
                          (property (chess-board-current-position chess-board) :to-move)))
                 300 action-top 24 :WHITE)))
           (if (string= (property (chess-board-current-position chess-board)
                                  :to-move)
                        "w")
               (draw-circle
                (- window-width 25)
                (+ (visual-top chess-board)
                   (visual-height chess-board)
                   -20)
                10.0
                *square-color-light*)
               (draw-circle
                (- window-width 25)
                (+ (visual-top chess-board)
                   20)
                10.0
                *square-color-dark*))
           (end-drawing)))
    (uninit-resource-collection res-col))
  (close-window))
```

**Comment by asdqwe** [comment]
@ruffianeo I made this test case that will `InitWindow` and `CloseWindow` 1000 times:

``` c
#include "raylib.h"
int main(void) {

    for (int i = 0; i < 1000; i++) {

        InitWindow(800, 450, "test");
            SetTargetFPS(60);
            BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawText("TEST", 20, 20, 20, BLACK);
            EndDrawing();
        CloseWindow();
        TraceLog(LOG_INFO, "\n\nCOMPLETED %i\n", i);

    }
    return 0;
}
```
</details>

On `PLATFORM_DESKTOP_GLFW` the `GLFW` backend eventually broke on run 206 on `GLX` (OpenGL Extension to the X Window System) when it tried to:

```
WARNING: GLFW: Error: 65542 Description: GLX: No GLXFBConfigs returned
WARNING: GLFW: Error: 65545 Description: GLX: Failed to find a suitable GLXFBConfig
test: external/glfw/src/window.c:581: glfwGetWindowPos: Assertion `window != NULL' failed.
```

On `PLATFORM_DESKTOP_SDL` it completed the entire 1000 without a problem.

In conclusion, this is completely out of scope of raylib. On that use case, sooner or later, you'll either be hitting Backend limits, or OS/WM limits, or OpenGL/Driver limits.
