### ISSUE TITLE
[core] `SetMouseCursor` crashes on wayland

### ISSUE THREAD

**Issue by Zielin0** [raysan5/raylib#3376]
### Issue description

I made a simple example code where I check for hover, change the cursor to `MOUSE_CURSOR_POINTING_HAND`, and then return to the default. When I hover over the rectangle multiple times the app crashes and I get this error message: `X connection to :1 broken (explicit kill or server shutdown).`

### Environment

Arch Linux 6.5, Wayland, OpenGL 4.6

### Code Example

```c
Rectangle rect = CLITERAL(Rectangle){50, 50, 100, 100};
DrawRectangleRec(rect, RED);

if (CheckCollisionPointRec(GetMousePosition(), rect))
{
    SetMouseCursor(MOUSE_CURSOR_POINTING_HAND);
}
else
{
    SetMouseCursor(MOUSE_CURSOR_DEFAULT);
}
```

**Comment by ubkp** [comment]
@Zielin0 Unfortunately that could be a `GLFW` issue. `Wayland` will slowly become a problem for us while we depend on `GLFW`. In the meantime, my suggestion would be compiling for `X11`. `XWayland` will still be able to run it well enough.

**Comment by raysan5** [comment]
Definitely, out of scope of raylib.
