### ISSUE TITLE
[core] WaitTime sleeps for a very long time if the input is negative

### ISSUE THREAD

**Issue by AndreaBoroni** [raysan5/raylib#3377]
Since the input to the WaitTime is a `double` and it gets converted to `unsigned long` when passed into Sleep on Windows it underflows to a really big number thus stalling the application for a long period. There should mabye be a check at the beginning of the WaitTime function for returning if the value of `seconds` is negative.

**Comment by ubkp** [comment]
@AndreaBoroni Yeah, that's usually the problem of unsigned ([see](https://github.com/raysan5/raylib/issues/3168#issuecomment-1632375969)).

Either way, regarding the check, data validation is usually up to the user on raylib (reference https://github.com/raysan5/raylib/issues/3365#issuecomment-1743827668).

**Comment by AndreaBoroni** [comment]
Yeah indeed. The parameter to WaitTime is a float so one does not expect it to be casted to unsigned.

**Comment by ubkp** [comment]
@AndreaBoroni I've been trying to replicate this case ([L5123](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L5123)) here, but, to me (with `gcc` on Linux `Fedora 38 64-bit`), casting to `unsigned long` won't cause an underflow:
```
#include <stdio.h>

int main(void) {

    // This will underflow:
    unsigned long l1 = -1;
    printf("l1:%lu \n", l1);

    // But this won't:
    double d2 = -1.0;
    unsigned long l2 = (unsigned long)d2;
    printf("l2:%lu \n", l2);

    return 0;
}
```
```
l1:18446744073709551615 
l2:0 
```
Could you test that on Windows?

**Comment by AndreaBoroni** [comment]
On windows with the compiler that comes with raylib (mingw32) it does underflow on both cases:
`
unsigned long l1 = -1;
double d2 = -1.0;
unsigned long l2 = (unsigned long)d2;

`

![image](https://github.com/raysan5/raylib/assets/38136330/f8eb4263-18ce-4c9a-a377-c0661bc03241)

**Comment by ubkp** [comment]
@AndreaBoroni Thanks for testing.

Well, unless there is some other scenario that involuntarily causes an underflow  (aside from the user passing a negative WaitTime, that the user should not pass to begin with), I guess this falls into data validation being up to the user on raylib.

**Comment by orcmid** [comment]
@ubkp that's known as the perfect-programmer presumption.  The challenge is that the not-so-perfect programmer is unlikely to figure out what the imperfection is.

I much prefer soft-failing instead, which some of the raylib/glfw APIs do to avoid accessing through NULL pointers, other nasty things.  That sort of thing matters with regard to maintaining secure code as well.

**Comment by ubkp** [comment]
@orcmid These arguments usually achieve nothing, but, IMHO:

1. The no-seat-belt approach is one of the best things of raylib. It keeps code simple/direct and forces the user to a) be mindful of what he does, b) read the source code.

2. Attempting to handle all likely scenarios will balloon the source code to the point of unmaintainability. And even possibly enabling the user to be careless.

3. When something is critical and completely outside the control of the user, that probably could be handled. But, for example, passing a negative wait time (that's impossible to achieve) should be under the user responsability.

**Comment by raysan5** [comment]
@ubkp Completely agree with all your points. I don't like to bloat code with all kind of checks due to users missuses... 

Still, along the years several validation checks have been added to the library here and there, I can consider a one-line validation check in this case.
