### ISSUE TITLE
[core] raylib repo is tooooooooo large

### ISSUE THREAD

**Issue by blueloveTH** [raysan5/raylib#3383]
Well, current raylib's repo has a really big size.

When I do `git clone` via Github Desktop, it shows I am downloading `~400MB` data and it takes **several minutes** to complete the cloning, which is very inconvenient when setting raylib as a git submodule due to its large size.

Is there any idea to do some cleanup to make the repo lightweight?

**Comment by ubkp** [comment]
@blueloveTH Perhaps try the `--depth` parameter (doc: https://git-scm.com/docs/git-clone).

**Comment by blueloveTH** [comment]
> @blueloveTH Perhaps try the `--depth` parameter (doc: https://git-scm.com/docs/git-clone).

If I only clone "some depth" of raylib, can I still compile the full repo?

**Comment by ubkp** [comment]
@blueloveTH https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

**Comment by raysan5** [comment]
@blueloveTH Afaik, the contents of the repo are not that big, those `400MB` probably represent the 10 years of raylib github accumulated content. I don't know what could be done to reduce that number but just cloning the latest version in the repo avoiding all the history.

**Comment by blueloveTH** [comment]
Thanks @raysan5 @ubkp I will try your suggestions.

**Comment by 7ombie** [comment]
You can just download the repo as a ZIP file. If you're not working on raylib itself, you don't really need the full repo.

**Comment by jkaup** [comment]
> @blueloveTH Afaik, the contents of the repo are not that big, those `400MB` probably represent the 10 years of raylib github accumulated content. I don't know what could be done to reduce that number but just cloning the latest version in the repo avoiding all the history.

There's tools for that, such as BFG cleaner, which allow you to remove huge files entirely from the git repository history. But this needs to be done with caution and with care taken into not breaking older releases.

But it's something to consider if you ever want to drop support for old releases and clean up the repo to a much smaller size

**Comment by orcmid** [comment]
@blueloveTH @7ombie The source code of any release (e.g., 4.5.0) is around 60 MB unzipped.  I suggest you use that in your project, simply .gitignore it, and do all of your work with such a release version.  If you need a clone to work on raylib itself, say to offer a patch or just to keep track of what's happening, I suggest keeping a fork of raylib on GitHub and create any pull requests from there directly.  Cherry-pick files from the fork if you need to.
