### ISSUE TITLE
[build] Cannot build examples with zig 0.11.0, build.zig needs to be updated

### ISSUE THREAD

**Issue by purple4pur** [raysan5/raylib#3386]
### Issue description

I followed instructions in `examples` folder and built with command `zig build core`, but so many errors occurred.

### Environment

Windows 10 LTSC x64, raylib `4.5.0`, zig `0.11.0`

![image](https://github.com/raysan5/raylib/assets/49893724/6ec83906-b781-44a3-9465-bc6d398cbe33)

### Issue Screenshot

I tried some fixing and was stuck here...

![image](https://github.com/raysan5/raylib/assets/49893724/0388c0a5-ef08-4a9e-a8f5-cfefd4441dc9)
![image](https://github.com/raysan5/raylib/assets/49893724/595b4ca1-5e57-43a8-8ff7-1716a0750da8)
![image](https://github.com/raysan5/raylib/assets/49893724/189d2193-7be8-49f9-ba26-67699e2c43e8)
![image](https://github.com/raysan5/raylib/assets/49893724/7c0a7a6a-c5ea-4d9a-86c2-587867f58dfe)

**Comment by raysan5** [comment]
@purple4pur I'm afraid I don't maintain Zig build system, fee free to send a PR with required fixes.

**Comment by star-tek-mb** [comment]
Please use either zig master with raylib master, either find commit which will compile with zig 0.11.0.

raylib 4.5.0 compatible with zig 0.10.1 i think. But zig 0.10.1 has a lot of issues with C ABI compatibility.
