### ISSUE TITLE
[build] OS X has some absolutely bizarre resource loading issue

### ISSUE THREAD

**Issue by define-private-public** [raysan5/raylib#339]
I'm stumped by this.  I truly am.

So I'm working of my `cmake_test` branch in my fork of this repo, but it's typically up to date with `develop` of this.  On OS X, I went to go test some things, namely the games to see if anything else was broken like shown in #338.

So after checking out my branch, this is what I do:
1. `mkdir build`
2. `cd build`
3. `cmake ..`
4. `make -k`

Which should make a static raylib, the examples (all but those who's compilation fails), and all of the games.  I went to go try out one of the "complex," games that requires resources to load.  Let's take `skully_escape` for example:
1. `cd games/skully_escape`
2. `./skully_escape`

The stuff in `resources/` aren't loading.  There should be that logo at the intro screen and no music is playing.  This is what the debug output says:
```
INFO: Initializing raylib (v1.8.0)
INFO: Display device initialized successfully
INFO: Display size: 1280 x 1024
INFO: Render size: 1280 x 720
INFO: Screen size: 1280 x 720
INFO: Viewport offsets: 0, 0
INFO: GPU: Vendor:   Intel Inc.
INFO: GPU: Renderer: Intel HD Graphics 5000 OpenGL Engine
INFO: GPU: Version:  4.1 INTEL-10.25.17
INFO: GPU: GLSL:     4.10
INFO: Number of supported extensions: 45
INFO: [EXTENSION] DXT compressed textures supported
INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
INFO: [TEX ID 1] Texture created successfully (1x1)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [VSHDR ID 1] Vertex shader compiled successfully
INFO: [FSHDR ID 2] Fragment shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: [CPU] Default buffers initialized successfully (lines, triangles, quads)
INFO: [VAO ID 1] Default buffers VAO initialized successfully (lines)
INFO: [VAO ID 2] Default buffers VAO initialized successfully (triangles)
INFO: [VAO ID 3] Default buffers VAO initialized successfully (quads)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Audio device and context initialized successfully: Built-in Output
WARNING: [resources/audio/come_play_with_me.ogg] OGG audio file could not be opened
WARNING: [resources/textures/alagard.png] Image could not be loaded
WARNING: [resources/textures/alagard.png] SpriteFont could not be loaded, using default font
WARNING: [resources/textures/doors.png] Image could not be loaded
WARNING: Texture could not be created
WARNING: [resources/audio/door.ogg] OGG file could not be opened
INFO: Unloaded wave data from RAM
WARNING: [resources/audio/scream.ogg] OGG file could not be opened
INFO: Unloaded wave data from RAM
WARNING: [resources/textures/skully.png] Image could not be loaded
WARNING: Texture could not be created
WARNING: [resources/textures/skully_icon.png] Image could not be loaded
WARNING: Texture could not be created
WARNING: [resources/textures/skully_logo.png] Image could not be loaded
WARNING: Texture could not be created
INFO: Target time per frame: 16.667 milliseconds
INFO: [SND ID 0][BUFR ID 0] Unloaded sound data from RAM
INFO: [SND ID 0][BUFR ID 0] Unloaded sound data from RAM
INFO: [AUD ID 1699884915] Unloaded audio stream data
INFO: Audio device closed successfully
INFO: [TEX ID 2] Unloaded texture data from VRAM (GPU)
INFO: [TEX ID 1] Unloaded texture data (base white texture) from VRAM
INFO: Window closed successfully
```

Now, let's try doing this:
1. `mv skully_escape game`
2. `./game`

And voila!  Resources are loading, the logo is displayed, music is playing and all is right in the world.

Or we could do this:
1. `mv game skully_escape`
2. `cd ../`
3. `mv skully_escape/ skully_escape_game`
4. `cd skully_escape_game/`
5. `./skully_escape`

It works too.  This hasn't happened on Linux, and seems to effect the rest of the "complex," games.  I guess I could sum this up as **"On OS X you can't have your parent directory be the same name as your executable if you want to load resources."**

What. The. Hell. Is. Going. On.

**Comment by raysan5** [comment]
Issue is related (again) to paths, executable folder is not set as base path for resources loading.

Here it is current solution for this issue, implemented by an user... not sure if the best possible solution: https://github.com/raysan5/raylib/blob/master/examples/Makefile#L554

**Comment by define-private-public** [comment]
ಠ_ಠ

Best solution I can think of right now (for CMake that is) it to have a it check for the OS, and then prepend/append the string `game` at the end of the executable, and also to document this in the building docs.

Does that sound fine?

**Comment by raysan5** [comment]
Why prepend/append the string `game` at the end of the executable? Don't understand how that solves the path issue...

**Comment by define-private-public** [comment]
Yeah, it doesn't solve the underlying issue, but it makes the games run correctly for the moment.

**Comment by tazdij** [comment]
I have created a makefile which creates a bundle on Mac, it has worked for me, if you test it, please let me know if it works for you. It creates a bundle in a build folder just under the main raylib folder. https://bitbucket.org/midgetviking/raylib-project/src/c275fa4491e6d19d8f2f7daa9b88907896371f91/Makefile?at=default&fileviewer=file-view-default

**Comment by tazdij** [comment]
@define-private-public I really am no expert when it comes to OS X. As far as I understand and the way my modified Makefile works is: create a directory with the suffix .app inside this folder there is a specific structure which needs to be used. Inside of the .app folder there is a resources folder, OS X automatically uses this as the working dir for that application. Also all of the required .dylib, .so, and .framework files can be placed in the .app folder in a specific sub folder to avoid dependency issues. Your app in this bundle can carry with it everything it needs to run. There is also a place for icons and a plist file which provides information to OS X about how to display your app in the desktop GUI.

That is about all I know when it comes to app bundles.

**Comment by tazdij** [comment]
@define-private-public here is some documentation. https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1

**Comment by tazdij** [comment]
@define-private-public also I was wrong about placing . framework files in the app bundle.
