### ISSUE TITLE
[core] Fullscreen toggling and resolution

### ISSUE THREAD

**Issue by M374LX** [raysan5/raylib#3390]
### Issue description

A program using raylib might run in both windowed and fullscreen mode. For example, the window size might be 800x600 in windowed mode but the program might want use the current monitor resolution when in fullscreen.

This does not work, however:

```C
if (IsKeyPressed(KEY_F)) {
	int monitor = GetCurrentMonitor();
	SetWindowSize(GetMonitorWidth(monitor), GetMonitorHeight(monitor));
	ToggleFullscreen();
}
```

The reason is because ``SetWindowSize()`` simply calls ``glfwSetWindowSize()`` without updating ``CORE.Window.screen.width`` and ``CORE.Window.screen.height``. This causes ``ToggleFulscreen()`` to actually use the previous window size.

This is a possible workaround:

```C
if (IsKeyPressed(KEY_F)) {
	int monitor = GetCurrentMonitor();
	SetWindowSize(GetMonitorWidth(monitor), GetMonitorHeight(monitor));
	fullscreen_toggled = true;
}


BeginDrawing();
EndDrawing();

if (fullscreen_toggled) {
	ToggleFullscreen();
	fullscreen_toggled = false;
}
```

The examples above show how to toggle from windowed mode to fullscreen. When doing the opposite (changing to windowed mode), this also does not work:

```C
ToggleFullscreen();
SetWindowSize(800, 600);
```

### Environment

Linux

### Code Example

The same code examples given in https://github.com/raysan5/raylib/pull/3382#issuecomment-1751846459 apply to this issue.

**Comment by SoloByte** [comment]
I have the same issue and I am using pretty much the same workaround. (windows & macOS) So basically the window size should be [updated correctly when entering fullscreen](https://github.com/raysan5/raylib/pull/3382#issuecomment-1752156619).

**Comment by raysan5** [comment]
Just reviewed this issue and it worked as expected for me on Windows 10 x64, compiling with GCC and MSVC.

When calling `SetWindowSize()`, it calls `glfwSetWindowSize()` that automatically calls `WindowSizeCallback()` that starts with `SetupViewport()` to later update `CORE.Window.screen.width` and `CORE.Window.screen.height` with new size.

The only issue I detected is when exiting the full-screen mode calling `ToggleFullscreen()` again, the previous window screen size is not retrieved but it can be managed at user size and just `SetWindowSize()` again when exiting fullscreen mode.
