### ISSUE TITLE
[examples] [physac] physics demos broken on OS X

### ISSUE THREAD

**Issue by define-private-public** [raysan5/raylib#340]
`physac` doesn't seem to be working on OS X at all.  When I run the `physics_demo`, I can create new objects, but nothing happens to them (unless I reset them).  Trying to run other things like the `friction` one, the boxes don't fall at all.  They stay suspended in midair.  See this:

![raylib_physac_demo_opengl_33_mac_broken](https://user-images.githubusercontent.com/4551425/28757088-93bfbb94-7549-11e7-89b3-235be92d36d9.png)

**Comment by jamiltron** [comment]
I can confirm this is also happening for me.

**Comment by define-private-public** [comment]
Changes in this PR make it work:
https://github.com/raysan5/raylib/pull/342

**Comment by raysan5** [comment]
Just merged PR.

**Comment by define-private-public** [comment]
Tested it.  We good now.
