### ISSUE TITLE
[graphics] OpenGL 2.1 rendering broken on OS X

### ISSUE THREAD

**Issue by define-private-public** [raysan5/raylib#341]
- 3D models don't seem to be rendering
- text glyph transparency isn't right
- colors are off (e.g. green lines in physics demos become yellow)

E.g.:
![raylib_opengl_21_osx_broken](https://user-images.githubusercontent.com/4551425/28757105-ecce4bba-7549-11e7-8f16-f6ddbe9d54e9.png)

**Comment by raysan5** [comment]
Please, could you share the output trace log? in what GPU are you testing it?

It seems R and B channels are inverted and alpha not considered... probably related to base white texture loading or a shader problem...

**Comment by define-private-public** [comment]
I've got a Mac Mini, late 2014 model.  The GPU is a `Intel HD Graphics 5000 1536 MB`.  I'm running OS X 10.12.6.

Tracelog for OpenGL 2.1:
```
INFO: Initializing raylib (v1.8.0)
INFO: Display device initialized successfully
INFO: Display size: 1280 x 1024
INFO: Render size: 800 x 450
INFO: Screen size: 800 x 450
INFO: Viewport offsets: 0, 0
INFO: GPU: Vendor:   Intel Inc.
INFO: GPU: Renderer: Intel HD Graphics 5000 OpenGL Engine
INFO: GPU: Version:  2.1 INTEL-10.25.17
INFO: GPU: GLSL:     1.20
INFO: Number of supported extensions: 0
INFO: [TEX ID 1] Texture created successfully (1x1)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [VSHDR ID 1] Vertex shader compiled successfully
INFO: [FSHDR ID 2] Fragment shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: [CPU] Default buffers initialized successfully (lines, triangles, quads)
INFO: [VAO ID 0] Default buffers VAO initialized successfully (lines)
INFO: [VAO ID 0] Default buffers VAO initialized successfully (triangles)
INFO: [VAO ID 0] Default buffers VAO initialized successfully (quads)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Target time per frame: 16.667 milliseconds
```

And OpenGL 3.3 for reference:
```
INFO: Initializing raylib (v1.8.0)
INFO: Display device initialized successfully
INFO: Display size: 1280 x 1024
INFO: Render size: 800 x 450
INFO: Screen size: 800 x 450
INFO: Viewport offsets: 0, 0
INFO: GPU: Vendor:   Intel Inc.
INFO: GPU: Renderer: Intel HD Graphics 5000 OpenGL Engine
INFO: GPU: Version:  4.1 INTEL-10.25.17
INFO: GPU: GLSL:     4.10
INFO: Number of supported extensions: 45
INFO: [EXTENSION] DXT compressed textures supported
INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
INFO: [TEX ID 1] Texture created successfully (1x1)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [VSHDR ID 1] Vertex shader compiled successfully
INFO: [FSHDR ID 2] Fragment shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: [CPU] Default buffers initialized successfully (lines, triangles, quads)
INFO: [VAO ID 1] Default buffers VAO initialized successfully (lines)
INFO: [VAO ID 2] Default buffers VAO initialized successfully (triangles)
INFO: [VAO ID 3] Default buffers VAO initialized successfully (quads)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Target time per frame: 16.667 milliseconds
INFO: [TEX ID 2] Unloaded texture data from VRAM (GPU)
INFO: [TEX ID 1] Unloaded texture data (base white texture) from VRAM
INFO: Window closed successfully
```

Doesn't look out of the ordinary to me.

**Comment by raysan5** [comment]
After review, I noticed that OpenGL 2.1 is not properly supported on OSX. Just added a fallback to OpenGL 3.3 in case OpenGL 2.1 is chosen in OSX, in commit https://github.com/raysan5/raylib/commit/6369b47f1190c1106448383ec557b9bb9be3dfcc.

Just notice that in OpenGL 2.1 extensions are not loaded properly, also notice that driver returns a OpenGL 4.1 context when you request OpenGL 3.3.

Key functions to review are `rlgl`  [rlLoadExtensions()](https://github.com/raysan5/raylib/blob/develop/src/rlgl.c#L1294), in OSX extensions loading is ignored because [OpenGL 3.x header is used](https://github.com/raysan5/raylib/blob/develop/src/rlgl.c#L88). But there is no `gl2.h` header for OSX and OpenGL 2.1 extensions should be loaded manually (it could be done using `GLAD`).

Simplifying, support for OpenGL 2.1 could be added but it requires some extra work and testing that I feel doesn't worth. I know a fallback to OpenGL 3.3 in OSX is a nasty trick but it's the easiest solution right now...

**Comment by define-private-public** [comment]
I can go do that in the CMake file later tonight.  That's a really nasty thing.

**Comment by define-private-public** [comment]
Okay, on OS X, the CMake file forces OpenGL 3.3 now.

**Comment by BoltzmannEntropy** [comment]
Do this work with new M1 OSX?

**Comment by BoltzmannEntropy** [comment]
"_glad_glGetString", referenced from:
ld: symbol(s) not found for architecture arm64
