### ISSUE TITLE
[core] Gamepad accelerometer support

### ISSUE THREAD

**Issue by danielchasehooper** [raysan5/raylib#3412]
### Issue description

the gamepad API doesn't expose the gamepad accelerometer as an axis. I know glfw doesn't expose that functionality, but as an end user of *raylib* I don't care, and I'd still like to be able to use the accelerometer. 

glfw has an issue from 2015 about accelerometer input. 😢 https://github.com/glfw/glfw/issues/661

### Environment

macOS, ps4 controller

**Comment by ubkp** [comment]
> I know glfw doesn't expose that functionality, but as an end user of _raylib_ I don't care, and I'd still like to be able to use the accelerometer.

It's really unfortunate that the library is not a _service_. But, don't worry, you can still implement that yourself. It should be super easy, here's the [Linux Kernel driver](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-sony.c) just as a reference, not sure about mac tho. Good luck.

**Comment by raysan5** [comment]
I'm afraid this issue belongs to an external library. Feel free to open that issue on glfw repo.

**Comment by raysan5** [comment]
I'm reopening it for a while, in case anyone is willing to give it a try.

**Comment by varshneydevansh** [comment]
Can I look into this, but I have WindowsOS and WSL Ubuntu running in it? I also have another machine running Ubuntu. I do have one macOS instance running in WSL with QEMU.

**Comment by Peter0x44** [comment]
@varshneydevansh I can't tell if you actually had an intention to research this, you definitely don't need permission to look in to it.

Did you figure anything out? I would be interested to know.

**Comment by raysan5** [comment]
As expected, noone is willing to dig into those kind of platform issues, too much work and too much time... the magic of open source. Closing issue.

**Comment by midn1** [comment]
I had started working on a GLFW update around last year and got it working on Linux, along with gyroscope support (https://github.com/glfw/glfw/issues/661). Unfortunately, I still haven't received feedback from the maintainers on the API, so I am stuck waiting.
