### ISSUE TITLE
[feature] Simple Pixel Shader API (based on phenomenon-px).

### ISSUE THREAD

**Issue by 7ombie** [raysan5/raylib#3426]
In the early days of WebGL, there was [a tiny library called phenomenon-px][ppx], which describes itself as *the fastest way to create pixel shaders*, and it probably was.

The user provides their frag shader source, and the library runs it using a generic vert shader that just outputs a rectangle (as two triangles) to fit the buffer, so their frag shader’s main function gets called once for each pixel in the frame (returning its color).

The library also accepts a config for the uniforms, allowing the user to set the names, initial values and CPU types (on the GPU, the user just declares the uniforms in their shader). The library has an API for updating their values and sending them to the GPU.

Note: The library does not parse the shader source to validate uniforms (invalid declarations are easily debugged anyway). It just simplifies creating *valid* uniforms, mainly with regard to textures. OpenGL textures have a bunch of settings, each with a range of values, which are mostly mutually incompatible. In phenomenon-px, the user simply picks from a comprehensive set of valid uniform types.

I used phenomenon-px all the time for hobby stuff, and eventually implemented a WebGL 2 version (for my own use), which allowed the user (me) to call `render` when they wanted to (rather than require them to pass in a callback that gets invoked every frame). Other than that (and maybe allowing the user to provide an array of frag shaders, to be applied in order), the original API was pretty much perfect.

An OpenGL version seems like a perfect addition to raylib’s collection of optional libraries. It would be tiny (and dependency-free), with a clear, narrow scope, and it would make it easy for users to create custom shaders for anything 2D. It would be especially useful for custom filters, as well as emulating tile and sprite chips *et cetera*.

I understand raylib already has `rlgl`, but that has a much broader scope (which also makes it less approachable). This is purely for pixel shaders.

This is not something I could implement myself (in C) anytime soon, but thought it was worth bringing up as a feature request - food for thought at least.

\- best -

[ppx]: https://github.com/vaneenige/phenomenon-px

**Comment by ubkp** [comment]
@7ombie I'd argue against the addition of that feature. Some reasons:

1. It's very platform specific. Even if ported, would require some considerable changes just to enable its usage.

2. There's already support for custom shaders.

3. It makes something easier by having the library manage that for the user. The problem is that, on that direction, the library, trying to make everything easier, ends up having to manage everything, becoming an engine (instead of a library of a set of tools) and, eventually, becoming unmaintainable.

4. Shaders, like everything else, have a learning curve. Trying to manage that for the user, IMHO, would only make them more dependent on the library implementing something for them. And I'm afraid no matter how many options would be added, it would never be enough.

**Comment by 7ombie** [comment]
Looking at [the wiki page for Custom Shaders][wiki_shaders], at the very end, it say that the "user can load any custom shader using provided `Material` and `Shader` structs", which is followed by a code example:

``` c
Material material = { 0 };     // Empty material

material.shader = LoadShader("custom_shader.vs", "custom_shader.fs");

// Setup location points in case names are not predefined ones or more locations are required
// Use: GetShaderLocation() and SetShaderValue*() functions

material.maps[0].texture = LoadTexture("tex_albedo.png");
material.maps[1].texture = LoadTexture("tex_metalness.png");
material.maps[2].texture = LoadTexture("tex_normal.png");
```

It's not clear how I'd to get from this example to what I described above, but it looks like raylib already has a lot of the functionality it would need to implement a phenomenon-px-API.

[wiki_shaders]: https://github.com/raysan5/raylib/wiki/raylib-generic-uber-shader-and-custom-shaders

**Comment by ubkp** [comment]
@7ombie For references, take a look at the shader examples at https://github.com/raysan5/raylib/tree/master/examples/shaders.

**Comment by 7ombie** [comment]
@ubkp - Thanks for replying.

> 1. It's very platform specific. Even if ported, would require some considerable changes just to enable its usage.

That's true. You wouldn't generally use this for shipping something cross-platform. It's very helpful when you know which system you're targeting though.

> 2. There's already support for custom shaders.

True, but how would I use that API to run a pixel shader on a frame buffer with a couple of uniforms? Maybe that's simple, and I'm just missing something??

> 3. It makes something easier by having the library manage that for the user. The problem is that, on that direction, the library, trying to make everything easier, ends up having to manage everything, becoming an engine (instead of a library of a set of tools) and, eventually, becoming unmaintainable.

This is not true (here, at least). This has been implemented before (I've implemented it myself), and it is a very small library with a narrow scope. Once it's done, there're no features to add. You just run the shaders with an API for defining uniforms, uploading them to the CPU, and making render calls.

> 4. Shaders, like everything else, have a learning curve. Trying to manage that for the user, IMHO, would only make them more dependent on the library implementing something for them. And I'm afraid no matter how many options would be added, it would never be enough.

The user writes their own shader (well, the vert shader is generic, but that's three lines of code). The library just simplifies configuring OpenGL for one common case.

My first project was an old school, bitmapped textmode renderer, which could have easily been adapted to render tiles for a console emulator. It was about 15 lines of GLSL. I passed a few arrays of u8s in - a palette (that got converted to floats), a set of glyphs and the state of the screen (which were copied to the GPU as ints).

It's one of things that end up being simple, because it's low level. The library just simplifies configuration.

**Comment by 7ombie** [comment]
Just for reference, the entire API would look something like this (in pseudo-code, and ignoring the design details):

``` coffee
import frag

let config = new FragConfig()

config.set_dimensions(<width>, <height>)
config.load_shader(<path>)
config.init_shader(<source-string>)
config.init_primitive(<name-string>, <type>, <initial-value>)
config.init_texture(<name-string>, <gpu-type>, <cpu-type>, <array>, <array-length>)

let api = new Frag(config)

until WindowShouldClose()

    api.uniforms.<name>.value = <new-value>
    api.uniforms.<name>.upload()
    api.render()
```

**Comment by ubkp** [comment]
IMHO, this feature is a far too specific (and platform specific) to justify the amount of porting, changes and work to make it viable, let alone maintain it.

The custom shader support is already very permissive. Just pass to it whatever you want as a shader and/or build that shader however necessary inside the application logic. IMHO, the library should not have to manage that, at all.

**Comment by 7ombie** [comment]
The WebGL versions were tiny, but only supported one version of OpenGL. Maybe it would be much more work to do the same thing cross-platform. I don't know *how different* the different versions of OpenGL are.

It doesn't require much maintenance, as the entire vertex shader is one declaration, and one line of code in a main function, and the available uniforms are fixed, so nothing changes over time unless a new version of OpenGL lands. Even then, the vert shader is one line of code, and adding new uniforms is not much work.

I really think you're overestimating the scale of the feature, @ubkp. It's just a wrapper. Still, you may be right about the cross-platform side of things. That's where it could become more work than it's worth.

All the same, thanks for considering it. I appreciate your feedback.

**Comment by 7ombie** [comment]
UPDATE: I think I've found [an example of how to do this (using the existing API)][example]. I need to look at it a little closer, to it appears to do what I requested.

[example]: https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_multi_sample2d.c
