### ISSUE TITLE
[build] Examples built as shared libs, not executables.

### ISSUE THREAD

**Issue by JimmyJames707** [raysan5/raylib#343]
Hi,
 I just built this on Arch Linux and I was able to build the examples as well, however all the examples came out as shared libraries, not executables, which means I can't double click on them to make them run. Any ideas?

**Comment by define-private-public** [comment]
could you head over to my fork and try using my `cmake_test` branch.  Build steps should be:

1. `mkdir build`
2. `cd build`
3. `cmake ..`
4. `make -k`

Tell me how it goes.

**Comment by raysan5** [comment]
how are you building the examples? are you using Makefile?

**Comment by JimmyJames707** [comment]
@raysan5 
I'm building as per the instructions here:
https://github.com/raysan5/raylib/wiki/Compile-for-GNU-Linux

> 
> cd raylib/src/
> make PLATFORM=PLATFORM_DESKTOP
> Just move to folder raylib/examples/ and run:
> make PLATFORM=PLATFORM_DESKTOP

**Comment by JimmyJames707** [comment]
@define-private-public 
I can't see a cmake lists file in your fork.

**Comment by define-private-public** [comment]
Did you checkout my branch?

**Comment by JimmyJames707** [comment]
@define-private-public 

Okay I got it but its got two problems. I fixed the first but the second I haven't a clue.

> CMake Error in CMakeLists.txt:
>   No cmake_minimum_required command is present.  A line of code such as
> 
>     cmake_minimum_required(VERSION 3.8)
> 

Lots of these:
> /raylib-cmake_test/examples/others/standard_lighting.c:19:10: fatal error: raylib.h: No such file or directory
>  #include "raylib.h"

**Comment by define-private-public** [comment]
Are you following the steps that I outlined in the 2nd message of this ticket?  The paths don't look right.

**Comment by JimmyJames707** [comment]
>Are you following the steps that I outlined in the 2nd message of this ticket? The paths don't look right.

Yes. The other thing it didn't do is copy the external directory to the example's folder, like the original raylib makefile did. I had to copy it by hand.

**Comment by JimmyJames707** [comment]
Have you guys looked at scons? The Godot devs use it and can't praise it enough. 
https://godot.readthedocs.io/en/stable/development/compiling/introduction_to_the_buildsystem.html

I haven't tried scons myself, but did try cmake a while back and found it complicated, but then again I don't understand why build systems need to be complicated. The handmade hero guy did his in a couple of lines.

**Comment by define-private-public** [comment]
> Yes. The other thing it didn't do is copy the external directory to the example's folder, like the original raylib makefile did. I had to copy it by hand.

You shouldn't have to copy it.  Right now when you generate static or dynamic libraries, what builds the examples will be sure to look in the `build/release` folder for the libs.  I really don't know what to tell you.  I develop on an Ubuntu derivative.  I don't know if Arch does anything different when it comes to linking and whatnot.

> scons

Never heard of it.  I've been making some good progress on the CMake stuff.  If you want to try making a scons based build system, I'd be interested in seeing how it turned out.

**Comment by tmerr** [comment]
cmake build works for me on arch. when following @define-private-public's instructions, you have to put the `build` directory in `raylib/build` instead of `raylib/src/build`.

**Comment by JimmyJames707** [comment]
@tmerr
Thanks that worked. Unfortunately they are still created as shared libs. I can get them to run from the terminal, but they are not recognized as executable. Very strange.

**Comment by raysan5** [comment]
this issue is very weird...

So, generated binaries are are like `core_basic_window.so` or just `core_basic_window`? Maybe it's just a matter of how the file is interpreted by the OS...

**Comment by JimmyJames707** [comment]
@raysan5
Hi ray,
  Its generating files in the form core_basic_window. 

It looks like there is something has changed in Arch, as this guy is having the same problem I have.
https://forum.manjaro.org/t/positional-independent-executable/28356/4

**Comment by raysan5** [comment]
It seems to be an OS specific issue after the latest update... maybe some specific flag is required on compilation to avoid this issue?

Have you tried running the examples from command line?

**Comment by JimmyJames707** [comment]
Could be. I had a look around but the link I posted above, was the only one I could find where someone mentions this issue, so I don't have any ideas.

They work from the command line, but the file managers don't recognize them as executable, so its the only way they will ever run unfortunately.

Perhaps there is a rare combination things that are causing this issue on my machine, so I think I might try installing another distro.

**Comment by JimmyJames707** [comment]
@raysan5
I got it to work. I passed -no-pie to the CFLAGS

    ifeq ($(PLATFORM_OS),LINUX)
        CFLAGS = -O2 -s -Wall -std=c99 -D_DEFAULT_SOURCE -no-pie

I found a discussion on it here. I don't know what they mean by more secure though.

https://github.com/kubernetes/kubernetes/issues/39819

> 
> I believe I figured it out. As part of the GCC 6 release notes, they mention a new gcc compile time option --enable-default-pie which enables pie by default. Apparently it's a more secure default.
> 
> https://gcc.gnu.org/gcc-6/changes.html
> 
> Passing -no-pie to the failing GCC command fixes this issue so I suspect the gcc binary shipped with stretch was compiled with --enable-default-pie.

    endif

**Comment by raysan5** [comment]
Added compiler flag on commit https://github.com/raysan5/raylib/commit/93a4b5e851fba0bda4f188de21ac47ce9ad76589
