### ISSUE TITLE
Discord link is invalid O_o

### ISSUE THREAD

**Issue by Shpendicus** [raysan5/raylib#3430]
your current discord server link seems to be outdated. I was interessted in joining but i cant for some reason lol.

**Comment by ubkp** [comment]
@Shpendicus Tested here and both links (on the [README.md](https://github.com/raysan5/raylib/blob/master/README.md), and on [raylib.com](https://github.com/raysan5/raylib.com)), forwarded correctly to [https://discord.com/invite/raylib](https://discord.com/invite/raylib) for me.

**Comment by Shpendicus** [comment]
> @Shpendicus Tested here and both links (on the `README.md` [L22](https://github.com/raysan5/raylib/blob/master/README.md?plain=1&rgh-link-date=2023-10-16T13%3A13%3A54Z#L22), and on `raylib.com` [L39](https://github.com/raysan5/raylib.com/blob/master/index.html?rgh-link-date=2023-10-16T13%3A13%3A54Z#L39)), forwarded [discord.gg/raylib](https://discord.gg/raylib) correctly to [discord.com/invite/raylib](https://discord.com/invite/raylib) for me.
> 
> **Edit:** editing; added line marks.

somehow my connection broke, it works now, sry.. lol
