### ISSUE TITLE
Makefile.Android issue

### ISSUE THREAD

**Issue by Vankae21** [raysan5/raylib#3437]
I followed every instructions on raylib's official android build tutorial on windows. But there is some issue. I keep getting this error
![Screenshot 2023-10-18 110852](https://github.com/raysan5/raylib/assets/117633698/5a935aee-da48-4ad1-b4dd-050b26c71f0a)

makefile 371 line:
![Screenshot 2023-10-18 111021](https://github.com/raysan5/raylib/assets/117633698/7f9102da-1449-4509-b2e1-5dc960a90f70)

makefile.android compile_project_code line:
![Screenshot 2023-10-18 111525](https://github.com/raysan5/raylib/assets/117633698/e7c3e146-f5e0-464d-b68c-10d4f871a687)

I'd appreciate every one of your help

makefile:
[Makefile.txt](https://github.com/raysan5/raylib/files/12995796/Makefile.txt)
makefile.android:
[Makefile.Android.txt](https://github.com/raysan5/raylib/files/12995802/Makefile.Android.txt)

**Comment by raysan5** [comment]
@Vankae21 Unfortunately not enough information is provided to propoerly track the issue or gues what is the cause. As per the output, it seems the makefile call can not find the compiler. That's most probably some issue with paths (or multiple MinGW installations) on user side, not raylib related.
