### ISSUE TITLE
[build] Problem when trying to compile examples on Raspian and PI 3

### ISSUE THREAD

**Issue by ismyhc** [raysan5/raylib#344]
Im running the latest raspian os as of  8/19/2017

I've followed the steps here:

https://github.com/raysan5/raylib/wiki/Compile-for-Raspberry-Pi

Compiling raylib worked as far as I can tell, but when I try and run

`make PLATFORM=PLATFORM_RPI RAYLIB_PATH=..`

I get the error
`
pi@raspberrypi:~/Development/Tools/raylib/examples $ sudo make PLATFORM=PLATFORM_RPI RAYLIB_PATH=..
#gcc -o core/core_basic_window core/core_basic_window.c -O2 -s -Wall -std=gnu99 -fgnu89-inline -I. -I../release/rpi -I../src -I../src/external  -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/rpi -L../src  -L/opt/vc/lib -lraylib -lGLESv2 -lEGL -lpthread -lrt -lm -lbcm_host -lopenal -DPLATFORM_RPI 
/usr/bin/ld: cannot find -lGLESv2
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
Makefile:300: recipe for target 'core/core_basic_window' failed
make: *** [core/core_basic_window] Error 1
`

Anyone have any ideas?

**Comment by raysan5** [comment]
`RAYLIB_PATH` should point to the path where raylib is located, the folder that contains `src`, `examples`, `templates`...

Try running:

`make PLATFORM=PLATFORM_RPI RAYLIB_PATH=../..`

**Comment by ismyhc** [comment]
Ill try this when I get home, thanks! :)

**Comment by raysan5** [comment]
Hi @ismyhc! Did you tried this? Does it work?

I tried in a Raspberry Pi Zero W with Raspbian and it should work...

**Comment by raysan5** [comment]
@ismyhc, any news on this issue? did you try it? `Makefile` has changed a lot since last time...

**Comment by raysan5** [comment]
Just tested everything for raylib 1.8 and RPI compilation works fine.

**Comment by horseyhorsey** [comment]
Any idea to fix without editing the header files? Does the "RAYLIB_PATH" actually work?

![image](https://user-images.githubusercontent.com/5377332/90263166-2ef3df00-de47-11ea-8e1e-12bf627c88fa.png)
