### ISSUE TITLE
[rlgl] Undefined behavior when calling rlLoadTexture with NULL

### ISSUE THREAD

**Issue by Peter0x44** [raysan5/raylib#3440]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description
LoadRenderTexture calls rlLoadTexture with NULL

https://github.com/raysan5/raylib/blob/d0a265cee80056fc2727657f7580730374ac4772/src/rtextures.c#L3735

Later, rlLoadTexture copies the pointer, and then does pointer math on it
https://github.com/raysan5/raylib/blob/d0a265cee80056fc2727657f7580730374ac4772/src/rlgl.h#L3002-L3004

https://github.com/raysan5/raylib/blob/d0a265cee80056fc2727657f7580730374ac4772/src/rlgl.h#L3043

And does not check if it is NULL first, resulting in:
`rlgl.h:3044:52: runtime error: applying non-zero offset 400 to null pointer`
Before, there was first a check for:
`if (mipOffset > 0) dataPtr = (unsigned char*)data + mipOffset;`
https://github.com/raysan5/raylib/commit/eb461512a7191896acda33330e643b0dd60365b3

But then, in the next commit, it was removed
https://github.com/raysan5/raylib/commit/b3359276654c410033c8d194c0188d2257029f1d

### Code Example
```c
#include "raylib.h"

int main(void)
{
	InitWindow(100, 100, 0);
	LoadRenderTexture(10, 10);
}
```
I could not get gcc to reproduce the issue, but clang did
compile raylib with:
`make CC=clang CUSTOM_CFLAGS="-fsanitize=address,undefined -g3"`
then, compile the above code with:
`clang whatever.c -I raylib/src raylib/src/libraylib.a -fsanitize=address,undefined -g3`
running should result in:
```
rlgl.h:3044:52: runtime error: applying non-zero offset 400 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior rlgl.h:3044:52 in 
```

**Comment by raysan5** [comment]
@Peter0x44 thanks for pointing this issue, it has beeen actually reviewed multiple times, hopefully now it should work.
