### ISSUE TITLE
[core] AudioContext constructor exception when `InitAudioDevice()` is called on Web platform

### ISSUE THREAD

**Issue by Yrds** [raysan5/raylib#3441]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Hi, I'm testing raylib 4.6-dev to check audio improvements but I'm getting `AudioContext` error during runtime:

From firefox: 
`Uncaught DOMException: AudioContext constructor: Sample rate 0 is not in the range [8000, 192000]`

From chrome(chromium):
`Uncaught DOMException: Failed to construct 'AudioContext': The hardware sample rate provided (0) is outside the range [3000, 768000].`

I've tested the same code on 4.5 and worked both on desktop and web, but in 4.6 it only worked in desktop version.

### Environment

Archlinux 6.5.7-zen2-1-zen
graphic drivers: mesa 1:23.2.1-2
pipewire(with pipewire-pulse): pipewire-pulse 1:0.3.82

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example

It was a complete game but I was able to reproduce with this little snippet
```
#include "raylib.h"

#ifdef __EMSCRIPTEN__
#include "emscripten.h"
#endif

void frame() {
  BeginDrawing();
    ClearBackground(WHITE);
  EndDrawing();
}

int main(int argc, const char **argv) {

  InitWindow(800, 400, "Audio test");

  InitAudioDevice();

#ifdef __EMSCRIPTEN__
  emscripten_set_main_loop(&frame, 0, 1);
#else
  while (!WindowShouldClose()) {
    frame();
  }
#endif

  CloseWindow();

  return 0;
}

```

## Logs

Chromium logs when I was trying to run my game through 4.6: [chromium.log](https://github.com/raysan5/raylib/files/13032804/chromium.log)

**Comment by michaelfiber** [comment]
This is an issue in miniaudio.h.

A fix was pushed to miniaudio.h here: https://github.com/mackron/miniaudio/pull/752

**Comment by Yrds** [comment]
Setting `AUDIO_DEVICE_SAMPLE_RATE`  to 48000 worked! 

Guess I will keep this issue open to track and test case of a new version of miniaudio.h is merged so we can test again, without further configuration

**Comment by raysan5** [comment]
Updated miniaudio to latest dev branch, this issue should be fixed.
