### ISSUE TITLE
[gputex] Compressed DDS textures loading problems

### ISSUE THREAD

**Issue by JaanDev** [raysan5/raylib#3446]
### Issue description

Raylib fails to load specific compressed DDS texture files, resulting in crashing or rendering black textures (with no console output about it). The textures that i'm trying to load are valid as they can be opened in other programs. The textures still don't work even after opening them in an image editing program and resaving (with the same compression settings). So the issue seems to be in raylib itself.

After a bit of searching, i found [this](https://github.com/raysan5/raylib/blob/master/src/external/rl_gputex.h#L264) bit of code, which crashed the app when loading some textures. The code computes the `data_size` using some `header->pitch_or_linear_size` variable. After taking a look at the texture in the hex editor, it appears that `data_size` is equal to `0x400000 * 2 = 0x800000` (bc the texture has 12 > 1 mipmaps) which is bigger than the file itself (which is `0x5555F0`)! 

![image](https://github.com/raysan5/raylib/assets/67502867/aabd382c-a2fc-45b5-bd99-9a59f1a51d1b)
^ this is the `results in crashing but works after fixing the crash.dds` file from the archive below.

So i fixed it by doing this (0x80 = "DDS " 4 char code + sizeof(dds_header)):

![image](https://github.com/raysan5/raylib/assets/67502867/c96e2332-98a6-4221-9f6c-6ca24098f8c5)

Now no textures were crashing anymore, but some of them just appeared black (`results in crashing, black after fixing the crash.dds`), i have no idea why it may happen and how to fix it.

The raylib log says that everything is loaded successfully (with all textures) (i have a custom log callback):
```
[DEBUG] [RL] FILEIO: [...path...\forraylib\results in crashing, black after fixing the crash.dds] File loaded successfully
[DEBUG] [RL] IMAGE: Data loaded successfully (2048x1024 | DXT1_RGB | 12 mipmaps)
[DEBUG] [RL] TEXTURE: [ID 23] Texture loaded successfully (2048x1024 | DXT1_RGB | 12 mipmaps)
```

Here is an archive of the textures i've tested (check the file names): [forraylib.zip](https://github.com/raysan5/raylib/files/13056505/forraylib.zip)

### Environment

Windows 11, an nvidia videocard, OpenGL `3.3.0 NVIDIA 537.13`, GLSL `3.30 NVIDIA via Cg compiler`, raylib `5.0-dev` (latest commit)

### Issue Screenshot

Loading `results in crashing, black after fixing the crash.dds`:

![image](https://github.com/raysan5/raylib/assets/67502867/9bcbc1a8-a686-49e5-8d6b-cd38bd7fbc10)

Loading `results in crashing but works after fixing the crash.dds`:

![image](https://github.com/raysan5/raylib/assets/67502867/e305a2eb-c13c-4820-bdf2-736495a50d35)

### Code Example

```cpp
Mesh mesh  = {0};

// ... setting up mesh (vertices, normals, uvs, etc.), no issues here

UploadMesh(&mesh, false);
auto model = LoadModelFromMesh(mesh);
auto tex = LoadTexture("path to texture"); // FILEIO log says that the file is loaded successfully
model.materials[0].maps[MATERIAL_MAP_DIFFUSE].texture = tex;

// ... using the 'model' later:

DrawModel(model, {0, 0, 0}, 1.f, WHITE);
```

Thanks in advance! My discord if needed: jaan2897

**Comment by JaanDev** [comment]
Hm so the problem seems to be in mipmaps (lol). I've reexported the original texture (in dxt1) to dxt1, dxt3 and dxt5, and then again but this time without creating mipmaps, and the textures without mipmaps worked.

But i dont think this issue may be closed (as the original problem hasnt been solved yet and using textures with mips is important)
Here is the archive with all the textures (it may help with solving the issue ig): [textures.zip](https://github.com/raysan5/raylib/files/13057001/textures.zip)

**Comment by JaanDev** [comment]
I've managed to fix it so it always only loads 1 mipmap, here is the fix:
```cpp
int data_size = (header->pitch_or_linear_size < file_size - 0x80) ? header->pitch_or_linear_size : file_size - 0x80;
*mips = 1;
```
It should be [here](https://github.com/raysan5/raylib/blob/master/src/external/rl_gputex.h#L268) instead of the existing `data_size` definiton

**Comment by raysan5** [comment]
@JaanDev Feel free to send a PR with the fix.

In any case, DDS loading probably requires some more review, it has not been reviewed in some time.

**Comment by JaanDev** [comment]
Ok sure!

**Comment by raysan5** [comment]
I'm closing this issue with the fix but I take note of the improvement requirements.
