### ISSUE TITLE
[core] GetCurrentMonitor() inconsistency between GLFW and SDL

### ISSUE THREAD

**Issue by M374LX** [raysan5/raylib#3456]
### Issue description

When building raylib and running a program in windowed mode, ``GetCurrentMonitor()`` returns the monitor containing the window's top-left corner when using GLFW (PLATFORM_DESKTOP). When using SDL (PLATFORM_DESKTOP_SDL), however, it returns the monitor containing the center of the window.

Since raylib's SDL implementation of ``GetCurrentMonitor()`` just calls ``SDL_GetWindowDisplayIndex()``, this is expected, as this function from SDL really returns the monitor containing the center of the window, according to the [documentation](https://wiki.libsdl.org/SDL2/SDL_GetWindowDisplayIndex).

Does anyone agree with the idea of changing the behavior on the GLFW implementation so it returns the monitor containing the center of the window for consistency? I think this would also make problems like https://github.com/raysan5/raylib/pull/3391#issuecomment-1752211850 and https://github.com/raysan5/raylib/pull/3391#issuecomment-1762364369 less common.

### Environment

Linux (Xorg as display server and dwm as window manager).

### Code Example

```C
#include <raylib.h>
#include <stdio.h>

int main()
{
	char str[32];

	InitWindow(800, 600, "Test");

	while (!WindowShouldClose()) {
		sprintf(str, "Monitor: %d", GetCurrentMonitor());

		BeginDrawing();
		ClearBackground(GRAY);
		DrawText(str, 0, 64, 32, BLACK);
		EndDrawing();
	}

	CloseWindow();

	return 0;
}
```

**Comment by orcmid** [comment]
The GLFW delivery of (desktop) scaling information determines the current monitor (and its scaling) by determining which one the cursor is in.  There might need to be some harmonization with that.

**Comment by ubkp** [comment]
> Does anyone agree with the idea of changing the behavior on the GLFW implementation so it returns the monitor containing the center of the window for consistency?

IMHO, that's a good idea. Just need to add:
```
x+=(int)CORE.Window.screen.width/2;
y+=(int)CORE.Window.screen.height/2;
```
To [L758](https://github.com/raysan5/raylib/blob/b3028e4891083c077236df437011184b16b6d293/src/platforms/rcore_desktop.c#L758) on `rcore_desktop.c`. Please send a PR.

**Comment by raysan5** [comment]
> Does anyone agree with the idea of changing the behavior on the GLFW implementation so it returns the monitor containing the center of the window for consistency?

@M374LX @orcmid @ubkp It seems good to me, feel free to send a PR with the improvement! Thanks!
