### ISSUE TITLE
[core] SDL implementation ignores OpenGL version from make

### ISSUE THREAD

**Issue by M374LX** [raysan5/raylib#3457]
As seen in: 
https://github.com/raysan5/raylib/blob/b3028e4891083c077236df437011184b16b6d293/src/platforms/rcore_desktop_sdl.c#L1146-L1147
the SDL implementation will always use OpenGL 3.3. However, it is expected to use the version specified by the ``GRAPHICS`` variable when running ``make`` (example: ``make PLATFORM=PLATFORM_DESKTOP_SDL GRAPHICS=GRAPHICS_API_OPENGL_21``).

**Comment by raysan5** [comment]
Reviewed.
