### ISSUE TITLE
[rmodels] Feature request: failure condition for LoadModel()

### ISSUE THREAD

**Issue by Boyfinn** [raysan5/raylib#3459]
I want to support mesh generation with the macro `SUPPORT_MESH_GENERATION` set, But still be able to check if model has loaded successfully, like with `IsModelReady()`, which doesn't work since the failed mesh is set to a cube when `SUPPORT_MESH_GENERATION` is set.

I've considered doing a workaround by skipping the default cube generation. But then I'd have to include the modified library source in my project, which I'd rather not do.

**Comment by Boyfinn** [comment]
> @Boyfinn Not sure I understand.
> 
>     1. `SUPPORT_MESH_GENERATION` is already enabled by default on the `config.h` file ([L206](https://github.com/raysan5/raylib/blob/master/src/config.h#L206)).
> 
>     2. `IsModelReady()` _"is a very general model validation, many elements could be validated from a model..."_ ([L1119](https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L1119)), so it may, or may not, suit your use case.
> 
>     3. If you need some specific check, you probably could implement that inside your application logic, similar to `IsModelReady()` ([L1113-L1117](https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L1113-L1117)).
> 
>     4. Either way, I tested it right now with the `models/models_mesh_generation.c` [example](https://github.com/raysan5/raylib/blob/master/examples/models/models_mesh_generation.c), adding the following to [L48](https://github.com/raysan5/raylib/blob/master/examples/models/models_mesh_generation.c#L48):
> 
> 
> ```
> [...]
> models[8] = LoadModelFromMesh(GenMeshCustom());
> if (IsModelReady(models[8])) printf("model is ready\n");
> else printf("model is NOT ready\n");
> [...]
> ```
> 
> And it worked fine. Output:
> 
> ```
> [...]
> INFO: VAO: [ID 10] Mesh uploaded successfully to VRAM (GPU)
> model is ready
> INFO: TIMER: Target time per frame: 16.667 milliseconds
> [...]
> ```
I should maybe have specified that i use `LoadModel()`, as it generates a cube when it fails at loading a mesh when `SUPPORT_MESH_GENERATION` is set.

**Comment by raysan5** [comment]
@ubkp It was a fallback to somewhat show the model was not loaded correctly, it helped students and program did not crash on bad models. Drawing nothing was very confusing for them. Not sure what an alternative could be...

**Comment by Boyfinn** [comment]
Would it be possible to get some-kind of solution to this? I'm currently overriding the default cube generation, but this isn't ideal, since I have to include the library & changes in my project repo for it, which significantly complicates the build process when initially cloning the project onto a new device.

**Comment by ubkp** [comment]
@Boyfinn You could implement your own "customIsModelReady" inside your application, with `model.meshCount > 1`:
```
bool customIsModelReady(Model model)
{
    return ((model.meshes != NULL) &&           // Validate model contains some mesh
            (model.materials != NULL) &&        // Validate model contains some material (at least default one)
            (model.meshMaterial != NULL) &&     // Validate mesh-material linkage
            (model.meshCount > 1) &&            // Validate mesh count
            (model.materialCount > 0));         // Validate material count
}
```
Or without it:
```
bool customIsModelReady(Model model)
{
    return ((model.meshes != NULL) &&           // Validate model contains some mesh
            (model.materials != NULL) &&        // Validate model contains some material (at least default one)
            (model.meshMaterial != NULL) &&     // Validate mesh-material linkage
            (model.materialCount > 0));         // Validate material count
}
```
**Note:** the Model type is already provided by `raylib.h` ([L392-L405](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L392-L405)).

**Comment by AndrewHamel111** [comment]
> the failed mesh is set to a cube when SUPPORT_MESH_GENERATION is set.

I think you need to create your own model validation, similar to what @ubkp suggests. Your use case is _very_ specific to your implementation so changing Raylib to suit it seems inappropriate. In your case, when IsModelReady returns true, do a second check to see if
1. The model only contains _exactly_ one mesh and
2. That mesh is exactly the mesh which GenMeshCube creates

This is the simplest solution, since the only risk it introduces is if a model which is identical to the generated cube is used, it will be incorrectly determined to have failed to load. I assume this isn't a problem, as it seems unlikely.

**Comment by raysan5** [comment]
@AndrewHamel111 @ubkp I'm still thinking about the best approach to this issue... 

One option is adding a flag to support the falback mechanism but it will increase a bit the build complexity... but I understand that advance users probably want avoid that fallback and manage any issue themselfs with `IsModelReady()`...

`IsModelReady()` was added recently and I did not consider this situation... maybe I should just remove the fallback mechanism? with `IsModelReady()` available now it can be checked on potential crashing points, that, after all, was the reason for the fallback mechanism.

Removing the fallback will also simplify the code...

What do you think?

**Comment by ubkp** [comment]
@raysan5 If the fallback is not necessary then, IMHO, I think just a `TRACELOG(LOG_WARNING...` ([L1060](https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L1060)) on `LoadModel()` ([L1032](https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L1032)) would be enough.

**Comment by raysan5** [comment]
Removed cube mesh fallback, code simplified, hopefully it won't crash somewhere else (I did a quick review).

Now it's up to the user to deal with models not properly loaded.
