### ISSUE TITLE
GetGamepadName() not working after update to current commit, first since platform split.

### ISSUE THREAD

**Issue by TongueSurfer** [raysan5/raylib#3461]
### Issue description

After updating to latest commit for the first time since the platform split, GetGamepadName() returns an uninitialized value if the gamepad was connected before InitWindow() was called.  Calling the function on a reconnected gamepad works properly, returning the expected const char**

### Environment

Windows 10, VS 2022, OpenGL 3.3, Radeon 6500XT.

### Code Example

*After testing, it seems that replacing rcore_dexktop.c Line 1123:*

```
if (glfwJoystickPresent(i)) CORE.Input.Gamepad.ready[i] = true;
```

*with*

```
if (glfwJoystickPresent(i)) {
    CORE.Input.Gamepad.ready[i] = true;
    strcpy(CORE.Input.Gamepad.name[i], glfwGetJoystickName(i));
}
```

*solves the issue.*

**Comment by ubkp** [comment]
@TongueSurfer I think that calling `strcpy(CORE.Input.Gamepad.name[i], glfwGetJoystickName(i));` inside `PollInputEvents()` ([L1123](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L1123)) would be a bad idea as `PollInputEvents()` gets executed every frame, so it would be needlessly copying the names every frame.

I believe a better solution would be moving `GetGamepadName()` back to the `rcore_[platform].c` since the different platforms apparently have different methods to retrieve that data, e.g.:
- `GLFW`: `glfwGetJoystickName()`;
- `SDL`: `SDL_GameControllerName()`;
- `DRM`: `ioctl()`.

**Comment by TongueSurfer** [comment]
I agree; if it can be avoided, then assigning the names every frame is just wrong.  I didn't realize I was looking at something that happens every frame.  If moving the functions into the split platforms is an option, it's the way to go.

**Comment by raysan5** [comment]
Ouch! I merged the fix too fast! 

@ubkp is right, it could be too costly to retrieve it per-frame basis... still, I'm wondering if GLFW or SDL poll that data per frame, considering that any controller can be plugged/unplugged anytime...

But I also like the idea of keeping inputs as much platform-independant as possible... maybe that additional performance cost (one strcpy() call) worths it...

I'll think about it before applying any solution.

**Comment by ubkp** [comment]
> Those two cases work for `PLATFORM_DESKTOP` and `PLATFORM_WEB`, on `PLATFORM_DESKTOP_SDL` it can be processed through a [`SDL_Event`](https://wiki.libsdl.org/SDL2/SDL_JoyDeviceEvent) on event polling and `PLATFORM_DRM` processes gamepads in a separate thread, so they can just be updated there.

@raysan5 I was looking into that. And, as far as I could tell, the gamepad detection filling the gamepad name _should_ already be working as is right now:
1. On `rcore_desktop.c` (`GLFW`) we already setup a callback for it `glfwSetJoystickCallback(JoystickCallback);` ([L1536](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L1536));
2. And that callback `JoystickCallback` already handles copying the name to `CORE.Input.Gamepad.name[*]` ([L1783-L1794](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L1783-L1794)).
3. It _should_ be working, as it is exactly like the [documentation](https://www.glfw.org/docs/3.3/input_guide.html#joystick_event) mentions it, but I don't know why it's not working.

**Comment by raysan5** [comment]
@ubkp As per mi understanding, it does not work if the gamepad is already connected when the application starts, so the connect/disconnect event is not processed. It should be checked at `InitPlatform()`.

**Comment by ubkp** [comment]
@raysan5 Thanks for the answer! So I guess that if we call `glfwSetJoystickCallback(NULL);` on `InitPlatform()` here: [L1354](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L1354), perhaps the fix would be calling `glfwSetJoystickCallback(JoystickCallback);` in the end of `InitPlatform()` too?

**Note:** Unfortunately I don't have a joystick here, so I can't test it.

**Comment by TongueSurfer** [comment]
@raysan5 As @ubkp suggested, after testing (I have a joystick and 2 controllers connected), inserting
```
for (int i = 0; i < MAX_GAMEPADS; i++) {
    if (glfwJoystickPresent(i)) strcpy(CORE.Input.Gamepad.name[i], glfwGetJoystickName(i));
}
```

at line 1550 right before InitPlatform()'s end and its "Success" TRACELOG solves the problem; all controllers connected before initialization now report their name.  I think it's cleaner to have it there than behind an if() in PollInputEvents().

**Comment by raysan5** [comment]
@TongueSurfer @ubkp thanks for the review and sending the review! Merged!
