### ISSUE TITLE
[build] Segfault when running examples build with Makefile

### ISSUE THREAD

**Issue by omrisim210** [raysan5/raylib#347]
So I'm on Windows (sadly), trying to make a small game with Raylib.  
I copied the `simple_game` template and renamed it to my game's name, but I didn't actually change anything. I just want to see if it builds.    
Since the `simple_game` (and all of the more complex templates) have multiple files just using the `raylib-compile-execute` NPP script will fail, so I tried using the `raylib-makefile` script. I get a linker error:

```
> Choose compile options
-------------------------------
Set desired PLATFORM: DESKTOP, RPI, ANDROID, WEB
SET: PLATFORM = PLATFORM_DESKTOP
$(PLATFORM) = PLATFORM_DESKTOP

> Setup required Environment
-------------------------------------
SET: RAYLIB_PATH = C:\raylib
$(RAYLIB_PATH) = C:\raylib
ENV_SET: PATH=C:\raylib\MinGW\bin
$(SYS.PATH) = C:\raylib\MinGW\bin
CD: C:\raylib\doku
Current directory: C:\raylib\doku

> Execute makefile
-----------------------
mingw32-make PLATFORM=PLATFORM_DESKTOP -B
Process started >>>
gcc -c screens.c -O2 -s -Wall -std=c99 -Wl,-allow-multiple-definition -I. -IC:\raylib\raylib/release/win32/mingw32 -IC:\raylib\raylib/src -IC:\raylib\raylib/src/external  -IC:\raylib\raylib/src/external/glfw3/include -IC:\raylib\raylib/src/external/openal_soft/include -DPLATFORM_DESKTOP
gcc -o simple_game simple_game.c screens.o -O2 -s -Wall -std=c99 -Wl,-allow-multiple-definition -I. -IC:\raylib\raylib/release/win32/mingw32 -IC:\raylib\raylib/src -IC:\raylib\raylib/src/external  -IC:\raylib\raylib/src/external/glfw3/include -IC:\raylib\raylib/src/external/openal_soft/include -L. -LC:\raylib\raylib/release/win32/mingw32 -LC:\raylib\raylib/src  -LC:\raylib\raylib/src/external/glfw3/lib/win32 -LC:\raylib\raylib/src/external/openal_soft/lib/win32 -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -DPLATFORM_DESKTOP C:\raylib\raylib/src/resources -Wl,--subsystem,windows
C:\raylib\MinGW\bin/ld.exe: cannot find C:\raylib\raylib/src/resources: Permission denied
collect2.exe: error: ld returned 1 exit status
Makefile:227: recipe for target 'simple_game' failed
mingw32-make: *** [simple_game] Error 1
<<< Process finished. (Exit code 2)

> Reset Environment
--------------------------
ENV_UNSET: PATH
$(SYS.PATH) has been restored
================ READY ================
```

I don't think the resources directory is being used by anything.  
If I remove `$(RAYLIB_PATH)/src/resources` from `WINFLAGS` in the makefile I do get a (iconless) binary and when I try to run it segfaults.  
I know it segfaults because Git Bash displays `segmentation fault` before the executable crashes (can't see it in the task manager). I also tried running it from Powershell but that's even more useless because it doesn't show any errors and just allows it to silently crash.

I'm on Win10 32-bit with an Intel Core Duo E8200 and a Geforce GT 630 if it helps

**Comment by raysan5** [comment]
Hi @omrisim210, `resources` file is a no-extension file that contains the icon and some executable info, you can omit it. It's weird the segmentation fault...

Jut tried it on my side and it works ok. I'm on Windows 10 64-bit, Intel i5 and Intel HD Graphics.

Try removing the compilation parameter: `-Wl,--subsystem,windows`, recompile and launch from command line, it should show some log information, paste it here.

**Comment by omrisim210** [comment]
I removed the `-Wl,--subsystem,windows` part and grabbed the resources file from the master branch (I put it where the Makefile looks for it, in `raylib\raylib\src`).  
Now I get a binary with an icon but it crashes:

![image](https://user-images.githubusercontent.com/13455401/29787777-d6956c06-8c38-11e7-8a76-6905d7f223d0.png)

The error is the generic, useless Windows error. Git Bash still says it segfaulted.

**Comment by omrisim210** [comment]
The `basic_game` template with the `raylib_compile_execute` N++ script does work fine so I guess I'll use that (my game is small enough for it to be OK). The segfault is probably because of an issue in `simple_game`'s Makefile (perhaps it doesn't specify the correct flags) or the `.c` files (maybe they do something bad, can't be bothered to try and fix it).

**Comment by raysan5** [comment]
I've been checking the Makefiles and they work ok in my side...  

Where did you install raylib? Did you use `C:\raylib` path?

I've seen you are using a Windows version localized to a Unicode language (is it Thai?), maybe issue is related... have you launched other Makefiles from other projects using MinGW compiler? Do they work ok?

**Comment by omrisim210** [comment]
I installed Raylib in the default location (`C:\raylib`), and I didn't try
any other Makefiles, I'll try compiling the examples using the Makefile
tomorrow.

(BTW the language is Hebrew :P)

**Comment by omrisim210** [comment]
I forgot about this, sorry.

I opened up cmd, did `set PATH=C:\raylib\MinGW\bin;%PATH%` and then `cd`'d into `C:\raylib\raylib\examples`.  
I ran `mingw32-make` and everything compiled (some files had warnings but that's related to the code and not to the commands used for compiling).  
I then tried to double-click one of the binaries (`examples\audio\audio_module_playing.exe`) and it didn't appear to do anything. Ran it from cmd and it was the same. I then tried to run it from git bash and it said it segfaulted. I tried `examples\core\core_basic_window.exe` and the same thing happened. Same for `examples\text\text_bmfont_ttf.exe`.

**Comment by raysan5** [comment]
Weird... no clue on what could happen...

Did you manage to run any example ok? Do you have any antivirus installed and running?

**Comment by omrisim210** [comment]
I tried a few examples and they all segfault (I could hack together a
script for checking all of the examples), and I only have Windows Defender.

**Comment by raysan5** [comment]
New idea. Have you tried the Visual Studio 2015 project that is included with raylib? It should be in folder `C:\raylib\raylib\project\vs2015`. It comes with an example already setup... could you check it?

**Comment by omrisim210** [comment]
I don't have VS installed and would prefer not to install it, but if I do install it I will check out the VS project.

**Comment by raysan5** [comment]
Did you try launching the examples using Notepad++ script `raylib_compile_execute`?

Do they work that way? Reviewing the conversation I understand they should work, only Makefile building fails... is that right?

**Comment by omrisim210** [comment]
I tried a few. `models_heightmap`,  `models_billboard`, `text_input_box`, `textures_srcrec_dstrec`, `shaders_shapes_textures`, `standard_lighting`, `audio_sound_loading` and `core_3d_picking` all compiled fine. I also tried one of the physac ones but it complained about a missing pthreadGC DLL file or something and crashed my computer, I'll try compiling one of the physac ones again.

**Comment by raysan5** [comment]
That's ok, about physac examples, they require some additional linkage options: `-static -lpthread` to work properly.

Just thinking again about your issue, do you have any other development environment installed in your computer? For example code:blocks or similar...

**Comment by omrisim210** [comment]
I'll try installing a different IDE (perhaps I will try code::blocks) and see what the results are. (Will only be able to do this in a few days though, and I'm in the process of creating the ultimate Linux dev environment on a USB stick so I won't have to use Windows ever again)

**Comment by raysan5** [comment]
hahaha... ok, take your time! :D 

Let me know how it works on Linux!

**Comment by raysan5** [comment]
@omrisim210, any news on this issue? Did you try it with a new environment?
