### ISSUE TITLE
Update to miniaudio causes Assertion Failure when using CloseAudioDevice

### ISSUE THREAD

**Issue by EzzypooOfNazareth** [raysan5/raylib#3471]
Audio initialization is working fine, but when closing the audio device I get the following error:

`Assertion failed: ma_device_get_state(pDevice) == ma_device_state_starting` in miniaudio.h, line 40857. Seems to be happening after commit 77730c8, which updated the miniaudio version.

### Environment

Windows 10 using w64devkit and mingw makefiles

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/26283001/ef0de8e3-4e79-4d2d-82c5-8095a51b99b2)

### Code Example

```
#include "raylib.h"

int main() {
  InitWindow(512, 480, "Space Shooter Arcade");
  InitAudioDevice();

  while (!WindowShouldClose()) {
    BeginDrawing();
    ClearBackground(BLACK);

    EndDrawing();
  }

  CloseAudioDevice();
  CloseWindow();

  return 0;
}
```

**Comment by raysan5** [comment]
I updated to a dev version of `miniaudio`, it probably still requires some review... Maybe @mackron is already aware of this issue.

**Comment by mackron** [comment]
This is the first I've heard of this one. Is this happening every time with 100% reproducibility?

**Comment by raysan5** [comment]
@mackron I was able to reproduce it 100% with the raylib audio examples on Windows x64, MSVC compilation.

**Comment by mackron** [comment]
Thanks. I've pushed a potential fix to miniaudio's dev branch. Are you able to try that? Was a bug I introduced with an earlier change. You saved me from accidentally releasing that!

**Comment by raysan5** [comment]
@mackron Updated and tested! It works of for me on Windows x64, MSVC compiler
