### ISSUE TITLE
[rmodels] `tinyobj_loader_c.h` fails to load `.mtl` if `.obj` uses `\r\n` as EOL

### ISSUE THREAD

**Issue by SuperUserNameMan** [raysan5/raylib#3473]
Hello,

Before redirecting me to open an issue on [tinyobjloader-c](https://github.com/syoyo/tinyobjloader-c), please note that the version of `tinyobjloader-c` used by Raylib is outdated, and it can't be directly updated because of API changes.

So, either `rmodels.h` needs to be updated alongside `external/tinyobj_loader_c.h`, either Raylib keeps the outdated version of `tinyobj_loader_c.h` and we have to fix it ourselves.

---

**The bug :**

Not sure if it's directly related to #3398, but i've just found a bug in the (outdated) version of `tinyobj_loader_c.h` used by Raylib regarding the end of lines format used in the `.obj` and `.mtl` files.

I'm on Linux, and I exported my `.obj/.mtl` from Wings3D which (unexpectedly) uses the MS-Windows' `\r\n` end of line format.

It appears that this version of `tinyobj_loader_c.h` does not handle `\r\n` correctly.

The `filename` sent to [`tinyobj_parse_and_index_mtl_file()`](https://github.com/raysan5/raylib/blob/f721429f2584b2d2769c7031eb8823f4d768d979/src/external/tinyobj_loader_c.h#L1322C15-L1322C47) from [`tinyobj_parse_obj()`](https://github.com/raysan5/raylib/blob/f721429f2584b2d2769c7031eb8823f4d768d979/src/external/tinyobj_loader_c.h#L1322C15-L1322C47) will contains a `\r` as the last character (before the `\0`), which prevents the `.mtl` file from loading.

---

The obvious workaround is to convert `\r\n` to `\n` in my `.obj/.mtl` files.

---

**Edit : the quickfix i provided before this edit was not enough, there are other issues that leads to segfaults**

**Comment by SuperUserNameMan** [comment]
Ok, here is a better quick fix to be inserted here :

https://github.com/raysan5/raylib/blob/f721429f2584b2d2769c7031eb8823f4d768d979/src/external/tinyobj_loader_c.h#L1267-L1275 :

```C
    /* Fill line infos. */
    for (i = 0; i < end_idx; i++) {
      if (is_line_ending(buf, i, end_idx)) {
        line_infos[line_no].pos = prev_pos;
        line_infos[line_no].len = i - prev_pos;

// ---- QUICK BUG FIX : https://github.com/raysan5/raylib/issues/3473
        if ( i > 0 && buf[i-1] == '\r' ) line_infos[line_no].len--; 
// --------

        prev_pos = i + 1;
        line_no++;
      }
    }
```

**Comment by raysan5** [comment]
@SuperUserNameMan Actually, `tinyfiledialogs-c` library should be updated to latest stable version but in the meantime, feel free to send proposed fix as a PR for integration.

**Comment by raysan5** [comment]
@SuperUserNameMan Merged!
