### ISSUE TITLE
[core] (Feature request) Open file/directory picker window

### ISSUE THREAD

**Issue by michelelorusso05** [raysan5/raylib#3478]
Just as title says. It would be nice to have a simple and straightforward method to call to open a file picker dialog to ask the user for a file to load since as right now (4.5) we can only rely on GetDroppedFiles, something passed as command line arguments or to implement a file chooser of our own.

**Comment by raysan5** [comment]
@michelelorusso05 File dialogs is very platform-specific and out-of-scope for raylib. I recommend using [`tinifiledialogs`](https://sourceforge.net/projects/tinyfiledialogs/).
