### ISSUE TITLE
[raylib/rlgl] Allow setting active framebuffer to be a specific face of a cubemap

### ISSUE THREAD

**Issue by haedqu** [raysan5/raylib#3480]
I currently need to implement rendering to a cubemap in order to do omnidirectional shadow mapping but currently there does not appear to be any way of specifying which side to render to, neither in raylib or rlgl with functions like `BeginTextureMode()` or `rlEnableFramebuffer()`.  I think fastest solution to this is simply to expose an rlgl version of the opengl function `glFramebufferTexture2D(GL_FRAMEBUFFER, attachment, face, cubemap, 0)`.

```cpp
#include <raylib.h>
#include <rlgl.h>

int main()
{
    InitWindow();

    Texture depthCube = { 0 };

    depthCube.id = rlLoadFramebuffer(width, height);

    rlEnableFramebuffer(depthCube.id);

    depthCube.texture.id = rlLoadTexture(0, width, height, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 1);
    depthCube.texture.width = width;
    depthCube.texture.height = height;
    depthCube.texture.format = PIXELFORMAT_UNCOMPRESSED_R8G8B8A8;
    depthCube.texture.mipmaps = 1;

    depthCube.depth.id = rlLoadTextureDepth(width, height, false);
    depthCube.depth.width = width;
    depthCube.depth.height = height;
    depthCube.depth.format = 19;
    depthCube.depth.mipmaps = 1;

    for (int i = 0; i < 6; i++)
    {
        rlFramebufferAttach(depthCube.id, depthCube.texture.id, RL_ATTACHMENT_COLOR_CHANNEL0, RL_ATTACHMENT_CUBEMAP_POSITIVE_X + i, 0);
        rlFramebufferAttach(depthCube.id, depthCube.depth.id, RL_ATTACHMENT_DEPTH, RL_ATTACHMENT_CUBEMAP_POSITIVE_X + i, 0);
    }
    rlDisableFramebuffer();

    BeginDrawing();
    for (int i = 0; i < 6; i++)
    {
        // How do I make it so that I am rendering to the i-th side of the cubemap?
    }
    EndDrawing();
}
```

**Comment by raysan5** [comment]
@haedqu I'm afraid there is out-of-scope for raylib, exposing that API requires several additions and an increment in code affecting maintainability. Also, it is a very specific use case that probably most users won't need.

I recommend using OpenGL directly for this specific situation.

**Comment by haedqu** [comment]
@raysan5 Is being able to have shadows in a library in which one of the largest uses is making games really that specific of a use case? There already is a type called `TextureCubemap` so I feel like there already is a precedent in the library to implement this sort of thing. I'm asking because I think a few additions like this would make it quite trivial to do very good looking lighting and shadowing in raylib, just by making a few function calls and adding 3 sets of example shaders. I think 3d shadow mapping is kind of essential in most 3d games and putting it as an example instead would be quite strange since I believe this would make it the only one requiring under the hood opengl use.
