### ISSUE TITLE
[core] `PLATFORM_DRM` hang up on exit and mouse not working

### ISSUE THREAD

**Issue by ubkp** [raysan5/raylib#3482]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description
1. While testing `PLATFORM_DRM` on current master branch (975d415) I noticed the examples started to hang up on exit and the mouse input didn't appear to be working anymore.
2. Rolling back the commit history, it appears that the issue started on a0f00343. I'm investigating this further.

### Environment
Testing on Raspberry Pi 3 Model B 1.2 with Linux (Raspberry Pi OS 11 Bullseye 32-bit armhf).

### Code Example
Minimal reproduction code to test the issue:
```
~/raylib-master/src$ make PLATFORM=PLATFORM_DRM
[...]
~/raylib-master/src$ cd ../examples/
~/raylib-master/examples$ make PLATFORM=PLATFORM_DRM core
[...]
~/raylib-master/examples$ cd core/
~/raylib-master/examples/core$ ./core_2d_camera
```

**Comment by raysan5** [comment]
@ubkp I'm reviewing that commit but I can't spot any critical change, there was just a code reorganization and some comments added...

**Comment by ubkp** [comment]
@raysan5 Could you test the `core_input_mouse` example? On the Raspberry Pi here it's spamming the error:
```
ERROR: DISPLAY: drmModeSetCrtc() failed with result: -13`
```

**Comment by raysan5** [comment]
@ubkp I tested `core_input_mouse` on `PLATFORM_DESKTOP`, on Windows 10, x64, it works ok. I don't have an RPI setup at the moment...

**Comment by ubkp** [comment]
@raysan5 Thanks for testing!

It's working for me too on `PLATFORM_DESKTOP`, `PLATFORM_DESKTOP_SDL` and `PLATFORM_WEB`. It's just the `PLATFORM_DRM` that has this issue. But don't worry about it, I'll fix it. :+1:

**Comment by ubkp** [comment]
@raysan5 Found the issue! `InitTimer()` has be called before:
```
InitEvdevInput(); // Evdev inputs initialization
InitGamepad();    // Gamepad init
InitKeyboard();   // Keyboard init (stdin)
```
I'll send a PR with the fix shortly. :+1:

**Comment by raysan5** [comment]
@ubkp Oh! Good catch! Actually that `InitTimer()` probably requires some more redesign on the future, I just added an ugly check for `PLATFORM_DESKTOP_SDL` to avoid requiring the WinMM call to `timeBeginPeriod()` (and the `winmm.lib` linkage), I think timming is already managed by SDL internally.

Similar situation for `SetupFramebuffer()`, `PLATFORM_DESKTOP_SDL` does not requires it, SDL already takes care of framebuffer properly at initialization... actually `SetupFramebuffer()` maybe can be totally removed, it tries to setup a proper framebuffer considering display and adding black bars... it could be simplified and let the users manage it when really required.
