### ISSUE TITLE
[rmodels] `GetModelBoundingBox()` not updating after changing Model transform

### ISSUE THREAD

**Issue by Boyfinn** [raysan5/raylib#3485]
### Issue description
Calling GetModelBoundingBox() after applying a transform to a model doesn't update the model bounding box in any way.

### Environment

Platform: Win_x86-64 version: 22H2 build: 19045.3570
Compiler: MinGW-w64 version: 13.1.0
Library: Raylib-4.5.0

### Issue Screenshot
![fig0](https://github.com/raysan5/raylib/assets/33183150/b5b015d9-289a-4f97-8207-1b34699bc803)
Monkey head translated by: X=4.0f, Y=5.0f, Z=8.0f and rotated 90-degrees along Y-axis.
Monkey head respects model translation, and is drawn where it should be.
Bounding box (in red) is drawn as if the model would be at the world origin at 0-rotation.

### Code Example
```
Model mdl = LoadModel("examplePath/model.glb");

while(true)
{
	mdl.transform = _translatedTransformMatrix;
	BeginDrawing();

		ClearBackground(BLUE);

		BeginMode3D(camera);

			DrawModel(mdl, VEctor3Zero(), 1.0f, WHITE);
			DrawBoundingBox(GetModelBoundingBox(mdl), RED);

		EndMode3D();
	EndDrawing();
}
```
The translation gets applied to the Model, but the Model `BoundingBox ` doesn't update even when calling `GetModelBoundingBox()` every frame. I haven't yet tried if this applies to `GetMeshBoundingBox()` too.

**Comment by raysan5** [comment]
@Boyfinn Good catch, indeed this is not implemented and it should be reviewed.

**Comment by AndrewHamel111** [comment]
To update `GetModelBoundingBox()` to translate / scale the min and max of the bounds is trivial, I had it working on my end in 5 minutes. For the rotation transform however, It's clearly a different story. It's not the case that applying the same transform to the bounds will have the intended effect, and indeed if the model has _any rotation transform_ on it my code cripples the bounding box. Interested to see how it gets implemented.

**Comment by raysan5** [comment]
@AndrewHamel111 Oh, yeah, now I remember why it was not implemented, because rotation...

I'm afraid with current `BoundingBox` structure is not possible to get the proper transformed bounds. 

In any case, pushed a review to apply provided transform to `Vector3 min, max` with `Vector3Transform()` for a basic transformation (translate, scale).
