### ISSUE TITLE
[raudio] Switching audio output on windows crashes

### ISSUE THREAD

**Issue by jestarray** [raysan5/raylib#3489]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

*Briefly describe the issue you are experiencing (or the feature you want to see added to raylib). Tell us what you were trying to do and what happened instead. Remember, this is not the best place to ask questions. For questions, go to [raylib Discord server](https://discord.gg/raylib).*

### Environment

Windows 10

### Issue Screenshot

https://github.com/raysan5/raylib/assets/34615798/ded1538f-8285-431b-9a45-7db6db528d59

I am using rust bindings of raylib on 5.0 master but someone else confirmed the same for C++ as well. https://discord.com/channels/426912293134270465/427518168995725317/1168659928651669625

**Comment by JeffM2501** [comment]
It dies in the miniaudio worker thread, not raylib. Raylib can't fix this, it would have to be fixed on the miniaudio side. I recommend you report it there.

**Comment by JeffM2501** [comment]
![image](https://github.com/raysan5/raylib/assets/322174/0ff16dd9-73d4-443f-886b-a9f37549a3c1)

**Comment by raysan5** [comment]
As Jeff mentions, this is related to miniaudio, afaik, not much can be done on raylib side.
