### ISSUE TITLE
Compiled program hangs up on start.

### ISSUE THREAD

**Issue by BlackDiamondPL** [raysan5/raylib#350]
I have just installed raylib on my computer. Opened pre-configured Notepad++ and compiled example program. Nothing wrong with compile process. Program hangs up while running and then crashes.

###### Posting this issue here because i need to wait before i can post on forum.

Windows 7 64 bit
Full instalation (Using installer)

**Comment by raysan5** [comment]
Hi @BlackDiamondPL, thanks for reporting, this is the right place for issues.

Which example did you try? Does it start, I mean, do you see some window open?

What GPU has your system?

**Comment by BlackDiamondPL** [comment]
Example, the very first one. One that starts up when you first open up Notepad++.

No i just see process running in background and then "Program not responding".

No external GPU, Intel(R) HD Graphics and NVIDIA GeForce 315M (also not external).

**Comment by raysan5** [comment]
Coulkd you try removing the compilation parameter: `-Wl,--subsystem,windows`, recompile and launch from command line, it should show some log information, paste it here.

You can also try to run it directly from the folder, instead of Notepad++.

**Comment by BlackDiamondPL** [comment]
Notepad++  :
```
 Setup required Environment
-------------------------------------
SET: RAYLIB_DIR = C:\raylib
$(RAYLIB_DIR) = C:\raylib
ENV_SET: PATH=C:\raylib\MinGW\bin
$(SYS.PATH) = C:\raylib\MinGW\bin
CD: C:\raylib\raylib\examples\core
Current directory: C:\raylib\raylib\examples\core

NOTE: raylib uses OpenAL Soft library compiled statically and linked into the executable

> Cleaning latest build
---------------------------
cmd /c IF EXIST core_basic_window.exe del /F core_basic_window.exe
Process started >>>
<<< Process finished. (Exit code 0)

> Compiling program
-------------------------
gcc -o core_basic_window.exe core_basic_window.c -s C:\raylib\raylib\raylib_icon -Iexternal -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,-allow-multiple-definition
Process started >>>
<<< Process finished. (Exit code 0)

> Reset Environment
--------------------------
ENV_UNSET: PATH
$(SYS.PATH) has been restored

> Executing program
-------------------------
cmd /c IF EXIST core_basic_window.exe core_basic_window.exe
Process started >>>
<<< Process finished. (Exit code -1073741819)
```
Console (running from folder):
```
INFO: Initalizing raylib (v1.7.0)
WARNING: [GLFW3 Error] Code: 65543 Description: WGL: OpenGL profile requested bot WGL_ARB_create_context_profile in unavailable
```

**Comment by raysan5** [comment]
Ok, perfect. The issue is related to OpenGL version, your GPU doesn't support it.

You have two options:

 - Update graphic cards driver to latest (I checked your NVIDIA GPU and it supports up to OpenGL 4.1, raylib only requires OpenGL 3.3). But I think problem is related to Intel GPU...

 - Compile raylib to use OpenGL 1.1 instead of 3.3 (more limited, some features won't be available): https://github.com/raysan5/raylib/wiki/FAQ

**Comment by BlackDiamondPL** [comment]
Ok i am updating NVIDIA, but i am not sure it it will work. Intel is kinda primary driver on my computer and i can't udate it (Error). I think i am gonna check out what happens next.

**Comment by BlackDiamondPL** [comment]
So... NVIDIA done nothing. Searched for Intel drivers for my GPU chipset/CPU (i think everybody knows whats's up). Try no.2 :|

**Comment by raysan5** [comment]
Number 2 should work... ;)

**Comment by BlackDiamondPL** [comment]
Again failed. Need to set OpenGL to lower version :/.
##### Version of 2.1 OpenGL works. Good thing i am going to buy new computer this year. Maybe then it will work at most of it's abilities.

Thank you for help. 

If someone is also having this issue and needs link to Intel Graphics update (6.05.2015) : https://downloadcenter.intel.com/download/24971/Intel-HD-Graphics-Driver-for-Windows-7-8-64-bit?product=55627
Maybe it will help. NVIDIA... just search it, very easy to update.
