### ISSUE TITLE
[rcore] PlayAutomationEvent does not add key presses to the keyPressedQueue

### ISSUE THREAD

**Issue by AndreaBoroni** [raysan5/raylib#3504]
As the title says: `PlayAutomationEvent()` does not add key presses to the `keyPressedQueue`. So if you are polling input keys using `GetKeyPressed()` in a loop  you will get no keys. The change is minimal and amounts to checking in the switch statement the previous state of the key as done in 'KeyCallback()':
```
case INPUT_KEY_DOWN: { // param[0]: key
    CORE.Input.Keyboard.currentKeyState[event.params[0]] = true;
    if (CORE.Input.Keyboard.previousKeyState[event.params[0]] == false) {
        if (CORE.Input.Keyboard.keyPressedQueueCount < MAX_KEY_PRESSED_QUEUE) {
            // Add character to the queue
            CORE.Input.Keyboard.keyPressedQueue[CORE.Input.Keyboard.keyPressedQueueCount] = event.params[0];
            CORE.Input.Keyboard.keyPressedQueueCount++;
        }
    }
} break;
```
I tested this change locally on windows and it works in my game.

**Comment by raysan5** [comment]
@AndreaBoroni Oh, good catch! Feel free to send a PR with the addition!

**Comment by AndreaBoroni** [comment]
Made this PR: https://github.com/raysan5/raylib/pull/3505
