### ISSUE TITLE
[build] Support config header in `build.zig`

### ISSUE THREAD

**Issue by BeauSLM** [raysan5/raylib#3516]
Use `zig build`'s support for config headers.

https://github.com/ziglang/zig/blob/67709b638224ac03820226c6744d8b6ead59184c/lib/std/Build.zig#L738-L755

**Comment by raysan5** [comment]
@BeauSLM I'm afraid I don't maintain the Zig build system, feel free to send a PR with the required improvements or maybe point to some Zig developer that could work on this.

**Comment by Peter0x44** [comment]
@BeauSLM is this to replace config.h and allow those variables to be set from zig?

**Comment by BeauSLM** [comment]
My idea is to be able to set the variables from zig if building with zig, or using zig bindings.

**Comment by Peter0x44** [comment]
@BeauSLM okay, exactly what I was thinking then
Just making sure I understood, since I wasn't too clear from the detail provided

**Comment by raysan5** [comment]
I'm afraid I'm not maintaining the Zig build system, if anyone needs this feature, feel free to send a PR.
