### ISSUE TITLE
[audio] Cannot load sound or stream music

### ISSUE THREAD

**Issue by nicrf** [raysan5/raylib#352]
Hi,

I get a null pointer after loadsound on the fopen, I tried every path and a fopen_s. Can you help me ?

On VS 2015 Commuity, I use the vs sample. Win 7 and 10 x64.

**Comment by raysan5** [comment]
Could you provide more detail? Could you share the code that fails?

**Comment by nicrf** [comment]
Hi,

I use the sample of VS Project and I add two line : 
`

	InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");
	InitAudioDevice(); // FIrst line
	SetTargetFPS(60);

	Sound Logo = LoadSound("C:\\raylib\\raylib\\project\\vs2015\\Game\\resources\\Logo.wav"); //Second line` 

I tried many path (relative or absolute) and I get every time an error. I tried with a fopen_s and It retrun two.

`
char debugText[256];
	sprintf_s(debugText, sizeof(debugText),"C:\\raylib\\raylib\\project\\vs2015\\Game\\resources\\Logo.wav");
errno_t err = 0;
	err = fopen_s(&wavFile, debugText, "rb");

	Logo = LoadSound(debugText);
`

**Comment by raysan5** [comment]
Ok, it should work with a relative path (relative to position of generated .exe):

```c
Sound logo = LoadSound("resources/Logo.wav");      // Logo.wav is in resources folder
```
Did you tried raylib example: `C:\raylib\raylib\examples\audio\audio_sound_loading.c`

Maybe it's an issue with the `Logo.wav` file, please, could you share it for testing?

**Comment by nicrf** [comment]
Sorry, It was my fault, my wav file was not compatible with OpenAL, (header error) now I have transformed my file into OGG Vorbis format and it work with sound. But If I use in MusicStream, it does not work, see : 

https://i.imgur.com/pjtJI58.png

**Comment by raysan5** [comment]
To stream music data, buffers must be refilled every frame calling `UpdateMusicStream()`

Check [audio_music_stream](http://www.raylib.com/examples/web/audio/loader.html?name=audio_music_stream) example for reference.

**Comment by nicrf** [comment]
Thank you
