### ISSUE TITLE
[example] `core_automation_events` not working properly on Web

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#3521]
This is a difficult to track issue, I've been investigating it for several hours.

It seems the recording works as expected but the replay does not.

First approach was to the timming system, considering the asynchronous execution on Web, I tried refactoring code to avoid ASYNCIFY ([core_automation_events_web.c.md](https://github.com/raysan5/raylib/files/13322524/core_automation_events_web.c.md)) but it does not seem to be the issue. Also considering that events recording and playing is frames-based. The jump physics on the example confused me but trying just a simple right-left movement also fails.

Investigating a bit further, I noticed there was not call in `rcore_web` for `glfwPollEvents()`, that call on `rcore_desktop` is the one in charge of launching the callbacks that read the inputs. In web it seems is not needed because probably the input reading is also asynchronous, managed by the browser.

As there are no callbacks involved in the automation events process, the key states do not seem to be properly reseted (key_up event) and they are just fixed and played forever, that's my guess.

Thinking about possible approaches to this issue, maybe a separate keys reseting mechanism on automation events playing for web?

Help with this issue is really welcome!

**Comment by raysan5** [comment]
@ubkp Hi! As you were helping a lot lately with web platform, maybe you could take a look to this issue?

**Comment by ubkp** [comment]
@raysan5 Sure thing! I'll review it :+1:

**Comment by ubkp** [comment]
> It seems the recording works as expected but the replay does not.

@raysan5 I believe it's the opposite. On my tests here the problem appears to be the recording on `PLATFORM_WEB`. It's indeed not recording the `INPUT_KEY_UP` events, thus the generated "automation events" on `PLATFORM_WEB` don't match the input and end up "malfunctioning" and stuck on the last `INPUT_KEY_DOWN`.

If you generate a valid `automation.rae` (e.g.: from a `core_automation_events.c` compiled for `PLATFORM_DESKTOP`) and _file drop_ it on the browser's tab running `core_automation_events.html` compiled for `PLATFORM_WEB` it will play the `automation.rae` perfectly.

I've been trying to tweak this condition ([L3279](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L3279)) trying to see if it could also be made to handle the async nature of emscripten's `KeyCallback`, but I've been unsuccessful so far. I'll continue working on it during the weekend.

**Comment by raysan5** [comment]
@ubkp Good catch! I don't know how I missed it! Glad to know that it works as expected if provided the right list of automation events!

Another hot-spot where could be some issue is in the [`KeyCallback()`](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_web.c#L1047) where the up state should be registered... I also tracked down the callback call to [`library_glfw.js`](https://github.com/emscripten-core/emscripten/blob/main/src/library_glfw.js#L379) but I can't see any clear issue in there with the key state parameter...

**Comment by ubkp** [comment]
@raysan5 Finished reviewing `KeyCallback()` and `library_glfw.js`. I think those parts are indeed working correctly.

But I think I've found the issue: we're calling `RecordAutomationEvent()` after `PollInputEvents()` on `EndDrawing()` ([L890](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L890), [L932](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L932)). And `PollInputEvents()` resets the `previousKeyState` ([L570-L574](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_web.c#L570-L574)). So by the time `RecordAutomationEvent()` tries to check for `INPUT_KEY_UP` it's gone ([L3279](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L3279)).

If we move the `if (automationEventRecording) RecordAutomationEvent();` from after `PollInputEvents();` ([L931-L933](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L931-L933)) to before it (somewhere around here: [L889](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L889)) we can fix this issue. Tested this change successfully on `PLATFORM_WEB` and `PLATFORM_DESKTOP`.

What do you think?

**Comment by raysan5** [comment]
@ubkp oh! good catch! Actually, [look at this comment](https://github.com/raysan5/raylib/blob/4.6-dev/src/rcore.c#L2396) before the automation system redesign! 😆 

I got the same doubts about the right place to call it! I think moving it to [L867](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L867) should be ok!

**Comment by ubkp** [comment]
@raysan5 Haha :laughing: 

Awesome, I'll send the PR shortly. :+1:

**Comment by raysan5** [comment]
@ubkp thank you very much for reviewing this issue and finding the problem!
