### ISSUE TITLE
[textures] Image convolution with custom user supplied kernel

### ISSUE THREAD

**Issue by Kimo-s** [raysan5/raylib#3527]
Added the function `void ImageKernelConvolution(Image *image, float* karnel, int karenlWidth)` that does image convolution from a given user kernel defined as 1D array.

Image: Input image
karnel: pointer to1D float array for the kernel
karenlWidth: The width of the kernel matrix

The kernel matrix is only supported for square sized matrices.

Example results:
![Screenshot 2023-11-11 173011](https://github.com/raysan5/raylib/assets/35817819/4ab714d8-2126-4cdd-8f31-96d2264ef9e0)
From left to right: Sharpen kernel, right Sobel operator, Gaussian blur done 6 times, Original image

**Comment by raysan5** [comment]
I think discussion can follow on open PR, no need for an issue duplicate.
