### ISSUE TITLE
[core] Several issues with `TakeScreenshot()`

### ISSUE THREAD

**Issue by Lecrapouille** [raysan5/raylib#3530]
### Issue description

The `TakeScreenshot(const char *fileName)` has several issues:
- it modifies `fileName` and creates an invalid path when passed as absolute path. For example `/home/qq/MyGitHub/TimedPetriNetEditor-dev/foo.jpg` becomes `/home/qq/MyGitHub/TimedPetriNetEditor-dev//home/qq/MyGitHub/TimedPetriNetEditor-dev/foo.jpg`
- Displays "failure" then "success" message.
- The file is not created while said "success".
- This function currently returns no error code and can fail, we cannot know. It shall return an error code (in this case `failure`).
-  The `ExportImageToMemory` called by TakeScreenshot, calls too many times `IsFileExtension` where the extracted extension can be saved once in a local variable.
- `IsFileExtension` fails detecting the file extension for jpeg. The line
```
if (strcmp(fileExtLower, TextToLower(checkExts[i])) == 0)
```
fileExtLower contains ".jpg" but checkExts holds "."

### Environment

SHA1 f01d3db7398037ce4a60da4d4ea9582b07834f96
Debian 11.

### Issue Screenshot

```
/home/qq/MyGitHub/TimedPetriNetEditor-dev/foo.jpg
WARNING: FILEIO: [/home/qq/MyGitHub/TimedPetriNetEditor-dev//home/qq/MyGitHub/TimedPetriNetEditor-dev/foo.jpg] Failed to export image
INFO: SYSTEM: [/home/qq/MyGitHub/TimedPetriNetEditor-dev//home/qq/MyGitHub/TimedPetriNetEditor-dev/foo.jpg] Screenshot taken successfully
```

### Code Example

```
TakeScreenshot("/home/qq/MyGitHub/TimedPetriNetEditor-dev/foo.jpg");
```

**Comment by ubkp** [comment]
Tested `TakeScreenshot()` right now and it's working correctly for me. Code example:
```
#include "raylib.h"

int main(void) {
    InitWindow(800, 450, "test");
    SetTargetFPS(60);
    while (!WindowShouldClose()) {
        if (IsKeyPressed(KEY_ONE)) TakeScreenshot("test.jpg");

        BeginDrawing();
        ClearBackground(RAYWHITE);
        DrawText("Test", 20, 20, 20, BLACK);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```
Please note that for `jpg` support `#define SUPPORT_FILEFORMAT_JPG 1` must be enabled on the `config.h` file.

**Comment by raysan5** [comment]
Just reviewed some of the potential issues in commit https://github.com/raysan5/raylib/commit/4f67f5f1593ac7b97c7492e28b5f6703ee84ee26

About the additional points:

 > This function currently returns no error code and can fail, we cannot know. It shall return an error code (in this case failure).

No plans to redesign the function for a return value, `FileExists()` can be used to verify if it worked at user level.

 > The ExportImageToMemory called by TakeScreenshot, calls too many times IsFileExtension where the extracted extension can be saved once in a local variable.

I think it shouldn't be a problem, performance cost can be assumed for code simplicty.

 > `IsFileExtension` fails detecting the file extension for jpeg. The line

Mmmh, that's sttrange, it should be reviewed.

**Comment by Lecrapouille** [comment]
@ubkp 

> No plans to redesign the function for a return value, FileExists() can be used to verify if it worked at user level.

Ok but:
- you should update your API comment:
  - FileExists() should be called (while this is not robust to race condition, which is not my case here).
  - absolute path are not accepted.
  - where the screenshot is stored.
- fix the fake message `Screenshot taken successfully`

> Please note that for `jpg` support `#define SUPPORT_FILEFORMAT_JPG 1` must be enabled on the `config.h` file.

Thanks, I did not notice it was commented on the config.h file but probably set in my case because I'm using Makefile (not cmake) and I entered `IsFileExtension(fileName, ".jpg")` with my debugger. The test failed (again, I should test with file name instead of absolute path). I tried with .png extension I had the same issue (but again I tested with absolute path). I'll redo tests tonight.

> **Edit:** also note the parameter for `TakeScreenshot(const char *fileName)` is _fileName_ not _filePath_ ([L1077](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L1077)).

Yes, file name is only accepted. Sad ! Modifying the path passed in param, is my opinion, is a bad API idea, it shall not manage internally path but just focus taking a screenshot and saving at the exact given path  (1 function => 1 thing).

The user has to call a special function (ie CorePath) calling `strcpy(path, TextFormat("%s/%s", CORE.Storage.basePath, GetFileName(fileName)));` if he wishes. `if (!TakeScreenshot(CorePath("foo.jpg")) {`

In my case I'm using a file dialog giving me the full path. Therefore, I've to truncate the path to give it to TakeScreenShot and then move the file to the desired user path ;(

**Comment by ubkp** [comment]
@Lecrapouille I think you mentioned the wrong user. The reply is probably to @raysan5.

Either way, I think `TakeScreenshot()` is there mostly for convenience (@raysan5 please correct if I'm wrong). If you need a specific behavior from it, I'd suggest just implementing a `CustomTakeScreenshot()` on your application side, similar to `TakeScreenshot()` ([L1771-L1792](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L1771-L1792)). It's trivial to do since all elements you'd need are already exposed by `raylib.h`.
<br>

**Side-note:** The following is my _personal_ opinion. IMHO, no matter how many changes happen, `raylib` defaults will never match every possible use case, so siding with simplicity is probably the best case scenario for the library default. `raylib` is very easy to inspect and extend, so, IMHO, users should do that first when the default behavior does not match their need.

**Comment by raysan5** [comment]
@ubkp You are right. `TakeScreenshot()` was created for convenience and its code is simple enough (like most raylib functions) to allow users to customize/tweak raylib for their needs. Library is being improved as much as possible but it's impossible to cover all use cases and nuances for all platforms, it will only add complexity and maintenance burden to the library. About documenting functions, most functions are the documentation on itselfs, raylib is an open source project and users are able to check the code and how it works.

**Comment by Lecrapouille** [comment]
Ok I tried TakeScreenshot("foo.png") it works. I will use this as it. Thanks
