### ISSUE TITLE
[raudio] (Bug) Audio is cut and never resumes if Windows goes into sleep

### ISSUE THREAD

**Issue by michelelorusso05** [raysan5/raylib#3535]
I am using a custom AudioStream to play audio in my emulator. However, I noticed that if the computer goes in sleep mode while the emulator is running, once the computer has booted back up the program will have no audio whatsoever and there is no chance of it coming back; only closing and reopening the emulator works.

I am initializing a custom audio stream with ```LoadAudioStream()``` and then manipulating it by calling ```SetAudioStreamCallback()``` with a custom function that populates the audio frames.

Is there a function that lets me detect the standby state to close the stream and to open a new one? Or am I missing something?

**Comment by raysan5** [comment]
@michelelorusso05 It sounds like an issue with the device re-initialization after sleep, not sure if this scenario is contemplated by `miniaudio`... Maybe @mackron could provide more info?

**Comment by mackron** [comment]
This is related to this miniaudio issue: https://github.com/mackron/miniaudio/issues/717

If this is critical to you, consider adding `MA_NO_WASAPI` to your build settings. That will disable the WASAPI backend and force the DirectSound backend which I believe works. Alternatively, if there's a way for you to detect the computer going to sleep and waking up, you can manually handle this at a higher level than miniaudio and manually uninitialize and reinitialize miniaudio from there. This is not something I consider super high priority so it might be a while before I get to addressing this at the miniaudio level.

**Comment by raysan5** [comment]
@mackron thank you very much for the reply and the details on the issue.

@michelelorusso05 It seems this issue is related to `miniaudio` and low-priority, you can try the approach proposed or wait for a potential fix in the future. I'm closing the issue on raylib side.
