### ISSUE TITLE
BINDINGS.md wrong license for GForth binding.

### ISSUE THREAD

**Issue by jocerfranquiz** [raysan5/raylib#3545]
### Issue description

`BINDINGS.md` has an error. The **GForth** binding indicates that its license is **MIT**, but the project [https://github.com/ArnautDaniel/gforth-raylib](https://github.com/ArnautDaniel/gforth-raylib) doesn't have a license agreement. This means this person owns all the rights over the binding code and logo. It's not **public domain**.

**Comment by orcmid** [comment]
and **GForth** is GPL v3.  Users of this indirect use of GForth will need to be attentive to that no matter what the status of `gforth-raylib` is.

**Comment by jocerfranquiz** [comment]
Agree. One solution could be to send a message to the author's binding to consider adding the MIT license. Maybe he/she/them forgot that part.

Regardless, someone with credentials should correct the table. I don't see it necessary to create a PR for this IMO.

**Comment by raysan5** [comment]
Updated `BINDINGS.md` to reflect the unknown license.
