### ISSUE TITLE
[core] conflicting function names 

### ISSUE THREAD

**Issue by DevyDhanish** [raysan5/raylib#3549]
I encountered compilation errors while attempting to build raylib on my system. It seems there's a conflict arising due to conflicting types for functions like `CloseWindow` and `ShowCursor` between `winuser.h` and the declarations in `raylib.h`. The errors generated during the build process suggest redeclaration conflicts, specifically between the Windows API functions and raylib's declarations:

# Terminal Output
`In file included from c:\mingw\include\windows.h:48:0,
                 from D:/codes/raylib/src/raudio.c:136: 
c:\mingw\include\winuser.h:3519:25: error: conflicting types for 'CloseWindow'
 WINUSERAPI BOOL  WINAPI CloseWindow (HWND);
In file included from c:\mingw\include\windows.h:48:0,
                 from D:/codes/raylib/src/raudio.c:136:
c:\mingw\include\winuser.h:4280:23: error: conflicting types for 'ShowCursor'
 WINUSERAPI int WINAPI ShowCursor (BOOL);
In file included from D:/codes/raylib/src/raudio.c:75:0:
D:/codes/raylib/src/raylib.h:1004:12: note: previous declaration of 'ShowCursor' was here
 RLAPI void ShowCursor(void);`

# Screenshot
![image](https://github.com/raysan5/raylib/assets/105561827/88136646-eca9-453a-82e7-c1b85ff7679f)

#Environment
Platform: Desktop
Operating System: Windows 11 23H2
OpenGL version: 3.3

**Comment by raysan5** [comment]
Are you including windows.h in your code? Are you building with and old mingw version? Those conflics shouldn't be a problem.

**Comment by DevyDhanish** [comment]
No I was not using it in my project, I was just trying to compile the source code into the static library, i'm using the latest released version of mingw. I just switched from linux to windows. When I was on linux everything was working no issue there but with windows I get this error no matter how I compile it.

**Comment by raysan5** [comment]
@DevyDhanish I'm afraid I can't reproduce this issue. 

What version of MinGW/GCC are you using? You should be using this one: [w64devkit](https://github.com/skeeto/w64devkit).

What version of Windows are you using?

**Comment by DevyDhanish** [comment]
@raysan5 I'm using GCC 6.3.0, I'm 99% sure that this is a fault on my end because it was working before I formated my system. Let me try `w64devkit` i'll update.

**Comment by raysan5** [comment]
@DevyDhanish that's probably the issue, latest version is [GCC 13.2](https://gcc.gnu.org/gcc-13/changes.html).

**Comment by DevyDhanish** [comment]
@raysan5 OMG!!! All this time I was using sticks and stones against fully automated assault rifles 😭😭😭 thank you I'll fix them right now.
