### ISSUE TITLE
[raudio] Noises at the end of sounds if loading other resources before sound resources

### ISSUE THREAD

**Issue by Zapunidi** [raysan5/raylib#3554]
Every PlaySound() ends with a noise when I load Image resources before Sound resources. The noises are different for each resource load sequence. As far as I can tell, it's some other resource memory played. It doesn't happen when I load all resources after loading sound resources.

I reproduced the issue on an included example audio_mixed_processor.
**To reproduce** add `Image img = LoadImage("resources/fudesumi.png");` line between AttachAudioMixedProcessor and LoadMusicStream like this:
```
AttachAudioMixedProcessor(ProcessAudio);
Image img = LoadImage("resources/fudesumi.png");
Music music = LoadMusicStream("resources/country.mp3");
```
Then compile and run. Press space. You will hear the "tshht" sound in the end of coin.wav sound.

Test configuration:
raylib 5.0.
Linux Mint 21.2
OpenGL Version:  4.5 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
GLSL:     4.50
Sound backend:       miniaudio / PulseAudio

Full raylib log:
INFO: Initializing raylib 5.0
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 2560 x 1600
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 220
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Mesa
INFO:     > Renderer: llvmpipe (LLVM 15.0.7, 256 bits)
INFO:     > Version:  4.5 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
INFO:     > GLSL:     4.50
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / PulseAudio
INFO:     > Format:        32-bit IEEE Floating Point -> 16-bit Signed Integer
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   48000 -> 48000
INFO:     > Periods size:  3600
INFO: FILEIO: [resources/fudesumi.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (384x512 | R8G8B8A8 | 1 mipmaps)
INFO: STREAM: Initialized successfully (44100 Hz, 32 bit, Stereo)
INFO: FILEIO: [resources/country.mp3] Music file loaded successfully
INFO:     > Sample rate:   44100 Hz
INFO:     > Sample size:   32 bits
INFO:     > Channels:      2 (Stereo)
INFO:     > Total frames:  4128768
INFO: FILEIO: [resources/coin.wav] File loaded successfully
INFO: WAVE: Data loaded successfully (22050 Hz, 16 bit, 1 channels)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: STREAM: Unloaded audio stream data from RAM
INFO: AUDIO: Device closed successfully
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully

**Comment by raysan5** [comment]
Wow! This is a really strange issue! First idea is related to some issue with memory allocation but afaik that's properly managed... 🤔

It should be investigated, sounds like a complex issue to track...

**Comment by Zapunidi** [comment]
I am afraid that there is OS dependency. I just tried to reproduce the bug in Windows 10 (different hardware) and failed. So first question is whether you will be able to reproduce the problem yourself.
Web compilation also have no issues with sound.
The bug is present in Linux Mint 21.1 on different hardware.
I am going to test some other Linux systems I can reach and will come back with results.

**Comment by raysan5** [comment]
@Zapunidi As per the details and the provided log output, it seems the issue could be related to PulseAudio backend. Maybe @mackron is already aware of this potential issue.

**Comment by raysan5** [comment]
@Zapunidi @mackron Any updates on this issue?

**Comment by RadsammyT** [comment]
I wasn't able to reproduce the issue when compiling to GCC 13.2.1 (Fedora Linux 39, PulseAudio backend as well), even taking into account compiler optimization flags, and the image used (fudesumi.png and the audio_mixed_processor example img).

But its a different story if its compiled via TinyC Compiler, and this occurs even without the image.

(on `tcc version 0.9.28rc 2023-11-08 mob@be8f8947* (x86_64 Linux)` via args `tcc audio_mixed_processor.c -L/usr/local/share -lraylib -lm -b -o bin/out_tcc && bin/out_tcc`). 
![Screenshot_20231215_133953](https://github.com/raysan5/raylib/assets/32146976/a374ba28-d387-4a0e-9784-9bcce65ca846)
<details><summary> logs (without the extra image) </summary> 

```
 ❯ tcc audio_mixed_processor.c -L/usr/local/share -lraylib -lm -b -o bin/out_tcc && bin/out_tcc
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 2256 x 1504
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 228
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) Graphics (RPL-P)
INFO:     > Version:  4.6 (Core Profile) Mesa 23.2.1
INFO:     > GLSL:     4.60
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / PulseAudio
INFO:     > Format:        32-bit IEEE Floating Point -> 32-bit Signed Integer
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   48000 -> 48000
INFO:     > Periods size:  3600
INFO: STREAM: Initialized successfully (44100 Hz, 32 bit, Stereo)
INFO: FILEIO: [resources/country.mp3] Music file loaded successfully
INFO:     > Sample rate:   44100 Hz
INFO:     > Sample size:   32 bits
INFO:     > Channels:      2 (Stereo)
INFO:     > Total frames:  4128768
INFO: FILEIO: [resources/coin.wav] File loaded successfully
INFO: WAVE: Data loaded successfully (22050 Hz, 16 bit, 1 channels)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: STREAM: Unloaded audio stream data from RAM
INFO: AUDIO: Device closed successfully
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
```

</details>

Here, after the initial coin sound is played, two 'taps' (similar to what you'd hear if you tap on a microphone connected to a speaker) play shortly after, not the 'tshht' that Zapunidi described.

**Comment by mackron** [comment]
Does it happen if you remove the `ProcessAudio()` stuff and the music stream from the example? I.e. have it so it's only the coin sound. Just wondering if it could be narrowed down a bit to make it a bit easier to diagnose.

**Comment by RadsammyT** [comment]
@mackron 
> Does it happen if you remove the `ProcessAudio()` stuff and the music stream from the example? I.e. have it so it's only the coin sound. Just wondering if it could be narrowed down a bit to make it a bit easier to diagnose.

When compiling the below code to GCC, no. It does happen if its compiled to TCC (same version and similar args as above).

```
#include <raylib.h>

int main() {
	InitWindow(800, 400, "coin");
	InitAudioDevice();
	Sound coin = LoadSound("resources/coin.wav");
	while(!WindowShouldClose()) {
		if(IsKeyPressed(KEY_SPACE)) {
			PlaySound(coin);
		}
		BeginDrawing();
			ClearBackground(RAYWHITE);
			DrawText("Press space to get rich", 0, 0, 60, GRAY);
		EndDrawing();
	}
	UnloadSound(coin);
	return 0;
}

```

**Comment by mackron** [comment]
Raylib is using dr_wav to load wav files which is another one of my libraries. It might be worth me taking a look at that file.

**Comment by Zapunidi** [comment]
> @RadsammyT @mackron I think the problem is the `coin.wav` file itself.
> So I imported `coin.wav` on Audacity (2.4.2), did nothing to it and just re-exported it back. Tested and the bug was gone.
> 
> I guess it could just be the `coin.wav` being faulty. Was anyone able to reproduce it with any other file?

I confirm: bug is gone with recoding coin.wav in Audacity. I set the same encoding (8bit unsigned PCM) and got the same file size, but no bug with it.

I tried to find/confirm the corruption in wav file and used `ffmpeg -i coin.wav`
<details><summary>Output</summary>
<p>

[wav @ 0x55c11c78f5c0] **Packet corrupt** (stream = 0, dts = NOPTS).
[wav @ 0x55c11c78f5c0] Estimating **duration** from bitrate, this **may be inaccurate**
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'coin_orig.wav':
  Duration: 00:00:00.21, bitrate: 178 kb/s
  Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 22050 Hz, mono, u8, 176 kb/s

</p>
</details> 

After recoding I got normal output `ffmpeg -i coin_recoded.wav`
<details><summary>Output</summary>
<p>

Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'coin_good.wav':
  Duration: 00:00:00.21, bitrate: 178 kb/s
  Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 22050 Hz, mono, u8, 176 kb/s

</p>
</details>

So there is a problem with guessing the duration of corrupted wav files in dr_libs/dr_wav.
Also the coin.wav file should be replaced in raylib resources.

**Comment by Zapunidi** [comment]
> I guess it could just be the `coin.wav` being faulty. Was anyone able to reproduce it with any other file?

I scanned with ffprobe all audio files (wav/flac/ogg) in resource directory and found only buttonfx.wav with the same "corrupt" result.
It should be replaced too.

**Comment by hanaxar** [comment]
It seems https://github.com/raysan5/raylib/blob/master/examples/audio/resources/coin.wav has a corrupt header.
According to https://docs.fileformat.com/audio/wav/ bytes 5-8 of the header stores the size of file, and bytes 41-44 stores the size of data chunk. 

In the header of coin.wav these values are: 9508 bytes of filesize and 9464 bytes of data chunk. But the file is actually 4776 bytes.

I'm not sure but I assume dr_wav is allocating memory by scanning the header, so if the actual file size is smaller than the indicated, garbage in the memory gets played after the audio data.
It may be other way around if the actual file size is larger than the header info, resulting a segfault.
Maybe addional checks are needed.

**Comment by raysan5** [comment]
@mackron @Zapunidi @RadsammyT @hanaxar @ubkp Thank you very much for investigating this issue! Good catch! 

Actually, `coin.wav` and `buttonfx.wav` were generated using [rFXGen](https://raylibtech.itch.io/rfxgen) but maybe an old version not using `dr_wav` for export but a custom implementation... I'm not sure at the moment.

In any case, rFXGen uses [`ExportWave() -> drwav_write_pcm_frames()`](https://github.com/raysan5/raylib/blob/master/src/raudio.c#L1019) to export wave data, that its [generated on rFXGen](https://github.com/raysan5/rfxgen/blob/master/src/rfxgen.c#L594) using [`GenerateWave()`](https://github.com/raysan5/rfxgen/blob/master/src/rfxgen.h#L269).

Maybe the real issue is in `GenerateWave()` (`rfxgen.h`) or `ExportWave()` (`raudio.c`).

**Comment by raysan5** [comment]
Reviewed rFXGen output, everything seems correct now. Updated corrupted sounds in raylib.
