### ISSUE TITLE
[text] ImageDrawText & ImageDrawTextEx on Raspberry Pi doesn't draw text?

### ISSUE THREAD

**Issue by Persesus** [raysan5/raylib#356]
I just cannot get this to work at all, is this function broken or am I missing something?

```
#include "raylib.h"

int main()
{
	int screenWidth = 1024;
	int screenHeight = 600;

	SetConfigFlags(FLAG_FULLSCREEN_MODE | FLAG_MSAA_4X_HINT | FLAG_VSYNC_HINT);
	InitWindow(screenWidth, screenHeight, "Testing");
	SetTargetFPS(60);

	SpriteFont font30 = LoadSpriteFontEx("resources/segoeui.ttf", 40, 0, 0);
	GenTextureMipmaps(&font30.texture);

	Image image = LoadImage("resources/cat.png");
	ImageResize(&image, 640, 480);
	ImageDrawText(&image, (Vector2) { 100, 200 }, "Hello World!", 150, WHITE);
	ImageDrawTextEx(&image, (Vector2) { 100, 100 }, font30, "Hello World!", 150, 1, WHITE);
	Texture2D texture = LoadTextureFromImage(image);
	UnloadImage(image);

	while (!WindowShouldClose())
	{
		BeginDrawing();
		DrawTexture(texture, 0, 0, WHITE);
		DrawFPS(500, 10);
		EndDrawing();
	}

	TakeScreenshot("screenshot.png");

	UnloadSpriteFont(font30);
	UnloadTexture(texture);

	return 0;
}
```

The cat.png image is from the examples, textures, resources folder - the ttf I pulled from my windows fonts folder.

The font is rendered as rendered as garbage / weird blocks of white that don't resemble the text at all.
I have a screenshot but there appears to be no attach function here. But even the default font doesn't work either.

Any help would be much appreciated!
Regards

**Comment by Persesus** [comment]
![screenshot](https://user-images.githubusercontent.com/32237215/30785660-3dcf723e-a162-11e7-84a1-d61417ec7f17.png)

**Comment by raysan5** [comment]
Hi @Persesus, I'm looking into this issue... here my results (using `KAISG.ttf` font, available in text examples resources):

![screenshot000](https://user-images.githubusercontent.com/5766837/30786907-23535c42-a17e-11e7-8774-96ec57330a1a.png)

I noticed there is some problem with font base-line... need to review that!

About your screenshot, it seems at some point memory is corrupted and so text data is not rendered correctly... maybe at font loading... maybe is an issue with Raspberry Pi... I'll try to test it on my RPI Zero W in the following days...

**Comment by Persesus** [comment]
Thanks - any help is appreciated.

Anything I can check or test at my end?

Things I've noticed:
If I comment out any of the two imagedraw(ex) lines the drawfps is rendered fine as per your screenshot, but neither of the texts I was drawing are legible.

With both imagedraw(ex) all text becomes garbage.

Not using textures and drawing text directly to the screen, everything is great but for the amount I'm rendering it's too costly and fps is dropping. I'm hoping by rendering to textures and then rendering them it will give me the performance increase I need.

Hoping to do a sliding datagrid soon that will need clipping, I'm assuming the only way to do this is to render to a texture and then render part of that texture to the screen.

I've updated my Pi  - running 2017-06-21-raspbian-jessie-lite
Linux 00000000d9fdc1e 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
Hardware : BCM2835
Revision : a02082

Regards

**Comment by Persesus** [comment]
Update:

I started debugging how the draw works, I rendered the font texture to the screen and it drew ok - so I then copied the method that creates the image and inside ImageTextEx it creates an image (Line: 1065), I rendered this image to the screen and it was half the size of the original?? and I could see the garbage text I saw was the image from where the characters should be.

Right location, but from an image half the size?

I started looking inside "GetTextureData" I couldn't figure it out, the code is correct - so stabbing in the dark I changed the image format to see what happened and the text changed. 

Adding this code to line 543 of textures.c my ttf text works! well, the same as your screenshot with the baseline wrong.
`image.format = 2;`

This doesn't fix the default font thou, not an issue for me but it's a step closer.

I have no idea why the format isn't correct - nor what format 2 is, I think it's greyscale?

Now going to try and see if I can alter the baseline...

Regards,

**Comment by raysan5** [comment]
Hi @Persesus! Thanks for the tracking! Great info!

In raylib.h you have the defines:
```c
// Texture formats
// NOTE: Support depends on OpenGL version and platform
typedef enum {
    UNCOMPRESSED_GRAYSCALE = 1,     // 8 bit per pixel (no alpha)
    UNCOMPRESSED_GRAY_ALPHA,        // 16 bpp (2 channels)
    UNCOMPRESSED_R5G6B5,            // 16 bpp
    UNCOMPRESSED_R8G8B8,            // 24 bpp
    UNCOMPRESSED_R5G5B5A1,          // 16 bpp (1 bit alpha)
    UNCOMPRESSED_R4G4B4A4,          // 16 bpp (4 bit alpha)
    UNCOMPRESSED_R8G8B8A8,          // 32 bpp
    UNCOMPRESSED_R32G32B32,         // 32 bit per channel (float) - HDR
    COMPRESSED_DXT1_RGB,            // 4 bpp (no alpha)
    COMPRESSED_DXT1_RGBA,           // 4 bpp (1 bit alpha)
    COMPRESSED_DXT3_RGBA,           // 8 bpp
    COMPRESSED_DXT5_RGBA,           // 8 bpp
    COMPRESSED_ETC1_RGB,            // 4 bpp
    COMPRESSED_ETC2_RGB,            // 4 bpp
    COMPRESSED_ETC2_EAC_RGBA,       // 8 bpp
    COMPRESSED_PVRT_RGB,            // 4 bpp
    COMPRESSED_PVRT_RGBA,           // 4 bpp
    COMPRESSED_ASTC_4x4_RGBA,       // 8 bpp
    COMPRESSED_ASTC_8x8_RGBA        // 2 bpp
} TextureFormat;
```
image.format = 2 means `UNCOMPRESSED_GRAY_ALPHA`

It seems related to image format not being correct... I will review it...

By the way, are you using latest raylib version from [develop branch](https://github.com/raysan5/raylib/tree/develop)?

**Comment by Persesus** [comment]
I have the master checked out - I've just downloaded the develop branch and the format issue is there too.

Regards

**Comment by raysan5** [comment]
ok, just reviewing the code... 

In OpenGL ES 2.0 `glGetTexImage()` function is not available, so to retrieve texture data (VRAM -> RAM), it's required to render the texture in a framebuffer and `glReadPixels()` from framebuffer... that's what I'm doing.

The issue is: Framebuffer by default is configured as RGBA, so I force a retrieval image format of `UNCOMPRESSED_R8G8B8A8`, it should be ok but... it seems driver returns the data in the original format of the texture instead of the framebuffer rendered version, so `image.format = 2` make it work... but that's weird...

Need to investigate it more carefully.

**Comment by Persesus** [comment]
I unfortunately didn't get a great fix for the text baseline, I came up with this for ImageTextEx but it puts the characters on the bottom of the image - the text 'tails' are cut off.

 ```
for (int y = letterRec.y; y < (letterRec.y + letterRec.height); y++)
{
    for (int x = posX; x < (posX + letterRec.width); x++)
    {
        int yy = (font.baseSize + letterInfo.offsetY) * (int)imSize.x;
        pixels[yy + ((y - letterRec.y) * (int)imSize.x + x)] = fontPixels[y * font.texture.width + (x - posX + letterRec.x)];
    }
}
```
I couldn't find anything that said how high the tails were to create an offset. I did hack it a little further with:

```
CharInfo baseInfo = font.chars['|' - 32];
int oY = font.baseSize + baseInfo.offsetY - baseInfo.rec.height;
```

and using the info for the pipe symbol to create an offset, then changed the yy line to:

```
int yy = (font.baseSize + oY + letterInfo.offsetY) * (int)imSize.x;
```

I think I'll try windows to create the texture I'm looking for and then port it over to the Raspberry PI - I keep corrupting my fonts somehow...

Regards,

**Comment by raysan5** [comment]
Thanks for the effort! :D

I'll also try to look into it this week... I'm working on Android custom APK building pipeline and it's driving me crazy...

**Comment by raysan5** [comment]
![screenshot000](https://user-images.githubusercontent.com/5766837/31849740-e5776a24-b647-11e7-8c90-70c73ae4b4a2.png)

Been working a bit on this, two issues detected:
 - ISSUE 01: ImageTextEx() fails on getting text vertically-aligned on image
 - ISSUE 02: DrawTextEx() fails on drawing text y-position (vertical-offset applied)

Just attaching a testing sample: [textures_image_text.zip](https://github.com/raysan5/raylib/files/1403911/textures_image_text.zip)

**Comment by Persesus** [comment]
Hi,

Yeah I found similar issues, and the spacing between the letters go slightly out.
I have a tight deadline on what I'm writing at the moment, end of November - I do want to create a library of functions so I can learn more clever animations etc. for performance I think I have to make textures which text would be paramount.

This is a great library, although I'm not doing any 3d - the ability to draw and render screens on the Pi is fantastic. I have an app with dozens of screens, touch keyboard entry, up/down sliders, complex maths, tcp/ip networking, load cells, temperature monitoring, multiple rfid readers, analog inputs etc. Once finished I'll upload a video to show what can be achieved with your library. Pi turn on, to running the application is 4 seconds!

Good Work Boss.

**Comment by raysan5** [comment]
Hey @Persesus!

Thanks for the kind words! Eager to see your results with your app! It sounds great! :)

By the way, now that raylib 1.8 is out, I took some time to look into this issue more carefully... there were several things to review:

 - [x] `DrawTextEx()` not drawing in the correct screen position, too much y-offset was applied on drawing. After further investigation, it was related to font baseline (vertical font origin, base line of `A` capital letter), y-offset applied was relative to that point... now an absolute offset is calculated for every character. Corrected in commit https://github.com/raysan5/raylib/commit/cbe0dcedfe885b69be8a8310840724ae0118afb3

![screenshot000](https://user-images.githubusercontent.com/5766837/31971474-465884dc-b91c-11e7-9d20-f1be7dab956d.png)

 - [x] `ImageTextEx()` not generating the correct text image due to offsets (offsetX, offsetY, advanceX) not considered on image generation. Calculated `imSize` by `MeasureTextEx()` is correct, it just fails the text image generation, not "moving the pixels" the right way. Now, with absolute y-offset, it should be easier to correct this issue... Corrected on commit https://github.com/raysan5/raylib/commit/539a9ca50eda438df66e92327990b25e8c9c59fc

![screenshot000](https://user-images.githubusercontent.com/5766837/31972967-ac576bb6-b923-11e7-8182-766eb23f5bf1.png)

 - [ ] `GetTextureData()` does not return the expected texture format on RPI, RGBA format expected from OpenGL ES framebuffer but it seems original texture format is returned (GRAYSCALE)... maybe the graphic driver (Mesa?) is doing some magic... need to investigate it.

You can use develop branch for latest changes and additions.

**Comment by raysan5** [comment]
Investigated and tested `GetTextureData()` issue, corrected in commit https://github.com/raysan5/raylib/commit/415e7e972c920cbf3194c4dfbbfe402d7c4406c5

Still don't understand that behaviour... let's see if it breaks somewhere else (maybe Android platform?).

**Comment by colesnicov** [comment]
Hello in the folk. Please, how can I compute the resulting height and width of the text, for example `Hello World`?

I need to **place the text to the right side of the screen**, and I need to know its width..

**Comment by sjgunn** [comment]
I believe the function is called MeasureTextEx, it returns a vector2 where the x property will be the text width.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
