### ISSUE TITLE
[rcamera] 3D Camera control, gamepad detection blocks out mouse

### ISSUE THREAD

**Issue by AndrewECarlson** [raysan5/raylib#3563]
Please, before submitting a new issue verify and check:

 - [ x] I tested it on latest raylib version from master branch
 - [ x] I checked there is no similar issue already reported
 - [ x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [ x] My code has no errors or misuse of raylib

### Issue description

When testing out the example core_3d_camera_first_person, I can't move with WASD or change the camera angle with mouse. I can adjust the angle with the arrow keys and Q/E. I can change the camera mode with 1-4. Commenting out UpdateCamera and uncommenting the UpdateCameraPro section worked as a workaround. 

Digging in the code, it looks like its skipping over the if (!IsGamepadAvailable(0)) block in UpdateCamera. When checking the example core_input_gamepad_info, "Asus Keyboard" or sometimes "ELAN 1200 Touchpad" show up as a gamepad. This is an issue with my laptops drivers, but I can normally workaround it by using a USB mouse when issues come up. Verified that with godot, my touchpad gets recognized as a joystick too. However, on godot, I can still use WASD and my USB mouse.

May be an issue too specific to me, since I don't know how many other people have ghost joysticks, but I wanted to flag it to let you know.

### Environment

Arch linux, ASUS Strix laptop, ELAN1200 touchpad

**Comment by MagiRomanya** [comment]
I had the same problem in my ASUS ROG Zephyrus Laptop also running Arch Linux.
