### ISSUE TITLE
[rcore] `IsKeyPressed()` not working for some keys on RPI (`PLATFORM DRM`)

### ISSUE THREAD

**Issue by larry104** [raysan5/raylib#3569]
### Discussed in https://github.com/raysan5/raylib/discussions/3565

<div type='discussions-op-text'>

<sup>Originally posted by **larry104** November 22, 2023</sup>
I notices that the block of keys (insert, delete home, end, pup, pdown) are not working. IsKeyPressed is not getting any event for these keys (I tried different keyboards and started the application from ssh terminal vs native terminal no difference). All other keys are working fine. Does anyone have an idea what is going wrong ?</div>

**Comment by larry104** [comment]
Just to summarize: keys insert delete, home, end, page up, page down are not implemented in on the RPi (PLATFORM DRM in rcore_drm.c: 

https://github.com/raysan5/raylib/blob/a3a73b9332d0ca0d7ec81044edce31dd13d7c916/src/platforms/rcore_drm.c#L1333-L1375

only 3 byte and 5 byte scan codes for F keys and cursor keys are implemented:  here are the missing 4 byte codes:

insert
^[[2~    27 0033 0x1b
         91 0133 0x5b
         50 0062 0x32
        126 0176 0x7e

delete
^[[3~    27 0033 0x1b
         91 0133 0x5b
         51 0063 0x33
        126 0176 0x7e

home
^[[1~    27 0033 0x1b
         91 0133 0x5b
         49 0061 0x31
        126 0176 0x7e

end
^[[4~    27 0033 0x1b
         91 0133 0x5b
         52 0064 0x34
        126 0176 0x7e

page up
^[[5~    27 0033 0x1b
         91 0133 0x5b
         53 0065 0x35
        126 0176 0x7e

page down
^[[6~    27 0033 0x1b
         91 0133 0x5b
         54 0066 0x36
        126 0176 0x7e

**Comment by larry104** [comment]
It doesn't work with raylib 4.5 ... is that something which might have been fixed in 5.x ?. 

I tired from ssh shell as well as native shell. (bullseye, raspberry pi zero

`./raylibtest1
INFO: Initializing raylib 4.5
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
INFO: DISPLAY: Selected DRM connector mode 800x600 (800x600p@60)
INFO: DISPLAY: Upscaling required: Screen size (800x450) smaller than display size (800x600)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 800 x 600
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 150
INFO: GL: Supported extensions count: 52
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: VC4 V3D 2.1
INFO:     > Version:  OpenGL ES 2.0 Mesa 20.3.5
INFO:     > GLSL:     OpenGL ES GLSL ES 1.0.16
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: ETC1 compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
WARNING: RPI: Failed to open Gamepad device, no gamepad available
WARNING: RPI: Failed to change keyboard mode, an SSH keyboard is probably used
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
`

**Comment by raysan5** [comment]
I'm closing this issue, it seems it refers to an old raylib version.

**Comment by larry104** [comment]
I compiled the test case using the master branch 5.1.-dev and it still does not work for those keys. I added a log for the BACKSPACE key and that works fine:

./raylibtest1
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: NATIVE DRM
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
INFO: DISPLAY: Selected DRM connector mode 800x600 (800x600p@60)
INFO: DISPLAY: Upscaling required: Screen size (800x450) smaller than display size (800x600)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 800 x 600
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 150
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorWidth() not implemented on target platform
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorHeight() not implemented on target platform
WARNING: SetWindowPosition() not available on target platform
INFO: GL: Supported extensions count: 52
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: VC4 V3D 2.1
INFO:     > Version:  OpenGL ES 2.0 Mesa 20.3.5
INFO:     > GLSL:     OpenGL ES GLSL ES 1.0.16
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: ETC1 compressed textures supported
INFO: RPI: Opening keyboard device: /dev/input/event2
WARNING: RPI: Failed to open Gamepad device, no gamepad available
WARNING: RPI: Failed to change keyboard mode, an SSH keyboard is probably used
INFO: PLATFORM: DRM: Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: KEY_BACKSPACE
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully

**Comment by larry104** [comment]
This is super strange. I tested it on a RPi3 and RPi Zero and both don't work ... What locale do you have set on your RPi? I have no other idea why this does not work for these 6 keys

**Comment by larry104** [comment]
Keyboard is set correctly ... 
# KEYBOARD CONFIGURATION FILE
# Consult the keyboard(5) manual page.
XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""
BACKSPACE="guess"

**Comment by larry104** [comment]
I am fetching it with cmake but just to make sure ... I did exactly what you did and it does not work.  I even tried on bookworm . hmm

**Comment by larry104** [comment]
I just tried a different keyboard ... same exact issue ... and I added a control key BACKSPACE which works
the INFO message shows also correctly
INFO RPI: Opening keyboard device: /dev/input/event1

**Comment by larry104** [comment]
yes, I do. I boot directly into a terminal. 

It seems the code never enters the while loop in line https://github.com/raysan5/raylib/blob/811abcb19faba710839a254ee3781a8d0ab23337/src/platforms/rcore_drm.c#L1691

**Comment by larry104** [comment]
In my caser there are no prints happening ...  platform.keyboardFd is 8. 
![IMG_5479](https://github.com/raysan5/raylib/assets/2013720/9735d38f-ab54-42fb-9ef3-f2e2e56a0c91)

**Comment by raysan5** [comment]
> Side-note: I'm really not sure if the SSH input was ever meant to be actually fully supported, or just some shortcut for basic testing.

@ubkp I created it for my convenience when I implemented RPI support first time, definitely not a priority and probably useless at this point.

@larry104 Could you verify if `PollKeyboardEvents()` is actually called? I'm afraid some printf-debugging is required on your side...

**Comment by larry104** [comment]
Yes, PollKeyboardEvents() is called but 
https://github.com/raysan5/raylib/blob/811abcb19faba710839a254ee3781a8d0ab23337/src/platforms/rcore_drm.c#L1691
returns always -1 so it never enters the while loop

**Comment by raysan5** [comment]
@larry104 could it be related to some kind of security reason? did you try running the example as root?

**Comment by larry104** [comment]
I tried as root no difference ... what I don't understand why other keys work just these 6 not ... that is all really strange

**Comment by larry104** [comment]
turning that option off causes all sorts of errors in terms of missing libraries. Eventually it compiled but now the keyboard does not work at all anymore.

**Comment by larry104** [comment]
The version for bullseye and bookworm I installed were both the 32 bit light (with no desktop environment). Let me try tomorrow the same version you have.  I report back in the morning. Thanks a lot for all your help so far ... this is really a strange problem.

**Comment by larry104** [comment]
Since I did this test on a RPi Zero I used a USB hub. But, I tried it without the hub as well. I also tried swapping this standard Microsoft keyboard with a Bluetooth keyboard. Same issue. I can try to get some other keyboards as well but I'm not confident it solves the problem. It's a mystery ...

**Comment by raysan5** [comment]
this is a really strange issue...

**Comment by larry104** [comment]
I recompiled with SUPPORT_SSH_KEYBOARD_RPI disabled. There were no errors/warning during the compile. Now we are back to that no key at all works. What is super strange is I gave the code to a friend with a RPi 3 and he tested it but it was still based on the 4.5 version I was compiling against and he was having the same problems. That at least makes me believe it's not a HW problem.

**Comment by larry104** [comment]
Here might be the difference, can you try booting directly into CLI instead compiling it from X11?

**Comment by larry104** [comment]
wow, now I am literally going insane. I have no more ideas ... If you use the RPi Imager on Windows you can set locale, ssh, wifi etc. before you actually flash the image and this is what I did. Let me do it all over again and do it later from X11 .. I try one more time and then I buy a new RPi ;-)

**Comment by larry104** [comment]
I still used the Imager but didn't make any changes to settings ... flashing just done ...

**Comment by larry104** [comment]
ok ... that would really point to a HW issue. Let me finish that current setup and I try to find another keyboard, I think I have one more somewhere. If that doesn't work I order the latest RPi Zero 2 W.

**Comment by larry104** [comment]
oh wow ... this is awsome ... so I am not insane after all!!!!! Mine is a Microsoft Wired Keyboard 600 and the other one a Microsoft Wireless Desktop 900 Keyboard

**Comment by larry104** [comment]
I was about to say the same thing about MS ;-) Too bad I had two of them to test. Thank you so much for all your help to figure it out!!!! And people will find here now the best installation instructions of raylib on a RPi with bullseye or bookworm ;-)

**Comment by raysan5** [comment]
> But the input code I've been using doesn't have an issue with it because I poll all keyboard devices and combine their input into a single logical keyboard. But when I get back to working on the input stuff I'll be sure to see if my approach works here. It is possible I didn't test those keys because I don't press them a ton.

Oh! That sounds like a good approach. Please, let us know if you test it.... and feel free to open a PR for the inputs update when possible... ;)

**Comment by larry104** [comment]
btw/ I confirmed on my side I get the MS keyboard twice in /proc/bus/input/devices and I confirmed that my friend also had a MS keyboard. How are the odds having 3 MS keyboards ;-). I further confirm that my Logitech MS keyboard works without any problems.

**Comment by larry104** [comment]
@ubkp I found another issue with the keyboard. When using the keyboard through ssh the key repeat works without any problems. When using a keyboard connected directly to the RPi the key repeat does not work.
