### ISSUE TITLE
[rshapes] `CheckCollisionCircleRec` is inaccurate for very small rectangles

### ISSUE THREAD

**Issue by Chaosed0** [raysan5/raylib#3575]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

`CheckCollisionCircleRec` incorrectly reports that small rectangles with non-integral positions do not intersect passed circles.

For some reason, `CheckCollisionCircleRec` casts the `recCenterX` and `recCenterY` variables to `int`, causing the issue. I suspect it was caused by the solution to this issue some years ago: https://github.com/raysan5/raylib/issues/527

### Environment

Windows

### Code Example

```
#include "raylib.h"
#include "raymath.h"

int main(void)
{
	Rectangle smallRect = { 0.5, 0.5, 0.25, 0.5 };
	Rectangle largeRect = { 0.5, 0.5, 10, 10 };
	Vector2 origin = { 0.7, 0.7 };
	bool smallCollide = CheckCollisionCircleRec(origin, 0.25, smallRect);
	bool largeCollide = CheckCollisionCircleRec(origin, 0.25, largeRect);

        // This should print "1 1", but instead prints "0 1"
	printf("%d %d\n", smallCollide, largeCollide);

        // The remainder of the code is unnecessary, but shows that the circle does intersect the rectangle
	InitWindow(800, 600, "blep");

	Camera2D camera;
	camera.offset.x = 0;
	camera.offset.y = 0;
	camera.target.x = 0;
	camera.target.y = 0;
	camera.rotation = 0;
	camera.zoom = 100;

	SetTargetFPS(60);

	while (!WindowShouldClose())
	{
		BeginDrawing();

		ClearBackground(BLACK);

		BeginMode2D(camera);

		if (fmod(GetTime(), 4) < 2)
		{
			DrawRectangleRec(smallRect, YELLOW);
		}
		else
		{
			DrawRectangleRec(largeRect, WHITE);
		}

		DrawCircleV(origin, 0.25, BLUE);

		EndMode2D(camera);
		EndDrawing();
	}

	return 0;
}
```

**Comment by raysan5** [comment]
@ubkp I think that's a remanent of a very old implementation that used ints and it was never reviewed (because it was probably good enough for most cases).
