### ISSUE TITLE
Visual Studio 2022 and VS2019 dont find Raylib after uppdate

### ISSUE THREAD

**Issue by NightStalker1000** [raysan5/raylib#3577]
I did a update on Visual Studio 2019 and Visual Studio 2022. After that I have problem that Visual Studio dont find raylib.h. So I gave properies a path, se picture. I did use raylib 5.0 installer. It still dont work.

![FelPaFlip-001](https://github.com/raysan5/raylib/assets/151570689/c780e31e-e433-4fef-9f09-4ab88f82069a)
![FelPaFlip-002](https://github.com/raysan5/raylib/assets/151570689/eb2dbcf2-e878-4f90-8acf-6ff185eade42)
![FelPaFlip-003](https://github.com/raysan5/raylib/assets/151570689/36eecfbd-534d-42c3-bdb6-dab58af4a79f)

**Comment by Peter0x44** [comment]
The installer has nothing to do with visual studio. This is a support problem, not a library issue.
I suggest you use [game-premake](https://github.com/raylib-extras/game-premake). If you need more support for that join the raylib discord server or open a discussion.

**Comment by orcmid** [comment]
Also, there is no indication that `raylib.h` is not found.  The error messages are from the linker.  It means that the raylib modules are either not built or not found.

**Comment by raysan5** [comment]
@NightStalker1000 I just reviewed it and it works as expected for me. It seems a build configuration issue. Also, afaik, `main.cpp` is not part of raylib but an user file.

**Comment by NightStalker1000** [comment]
main.cpp is my kod, that Im trying to compile and get running. I also tested a raylib file that workt before,  Where do I find raylib moduls, or how do I build them.  I can build program in SDL2 without any problems.

**Comment by orcmid** [comment]
@NightStalker1000 
> Where do I find raylib moduls, or how do I build them.

I suggest you take this conversation onto the [raylib Discord server](https://discord.gg/raylib).  There needs to be more information for how you are attempting to build with Visual Studio and how you configure the dependency on the raylib source codes so that the modules are compiled on behalf of your program.
