### ISSUE TITLE
[rcore] `ShowCursor()` is not working properly

### ISSUE THREAD

**Issue by justgo97** [raysan5/raylib#3586]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

`ShowCursor` is not working properly, The cursor stays hidden.

### Environment

Platform: Windows 11 22H2 (64-bit)
IDE: Microsoft Visual Studio 2022
Raylib: 5.0 from vcpkg

### Code Example

```
#include "raylib.h"

int main()
{
    InitWindow(500, 500, "Cursor");

    HideCursor();
    ShowCursor();
    //EnableCursor(); // This works

    while(!WindowShouldClose()) {
        BeginDrawing();

        ClearBackground(DARKBLUE);

        EndDrawing();
    }

    CloseWindow();
    return 0;
}
```

**Comment by justgo97** [comment]
> @justgo97 @raysan5 Cross-compiled it here for Win64 using `Mingw`. Sent the `.exe` to a friend which tested it on `Windows 11 22H2` (64-bit). Everything worked correctly.

I'm using Microsoft Visual Studio 2022, But not sure if that makes a difference, I'm also on `Windows 11 22H2` (64-bit)

**Comment by justgo97** [comment]
Also I don't know if this matters in tackling down this issue but `EnableCursor` works properly.

**Comment by raysan5** [comment]
@justgo97 Tested building raylib and the example with `Microsoft Visual Studio 2022, Version 17.7.6` on `Windows 10 64bit` and it works ok. 

Also, a side note, the cursor is hidden only inside the window space, when you move it outside the window it is visible. `ShowCursor()` just makes it visible again inside the window.

**Comment by raysan5** [comment]
@justgo97 @ubkp Ok, I think I know where [could be the issue](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showcursor).

Are you including `windows.h` in some module? In what order are you linking the program libraries in Visual Studio?

Check in VS for your project: `Properties` > `Linker` > `Input` : `Additional Dependencies`

I got the following list in the following order:
```
raylib.lib;opengl32.lib;kernel32.lib;user32.lib;gdi32.lib;winmm.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;odbccp32.lib;%(AdditionalDependencies)
```

`raylib.lib` should be linked before `kernel32` and `user32.lib`.

**Comment by orcmid** [comment]
I compiled both of @justgo97 examples using raylib 5.1-dev, VS 2022 17.8.2 Build Tools, the x64 Developer Command Prompt, and the 
[VCrayApp-0.1.0 beta](https://orcmid.github.io/nfoTools/dev/D211101/e/) kit.  

I confirm that all works as expected with the cursor toggling only inside the app window and not impacted elsewhere on the Windows 10 display.
