### ISSUE TITLE
[release notes] Links in 5.0 release notes point to code on master branch, which means they aren't stable

### ISSUE THREAD

**Issue by aSemy** [raysan5/raylib#3589]
A lot (all?) of the links in the [5.0 release notes](https://github.com/raysan5/raylib/releases/tag/5.0) don't point to a stable version. For example, 

"A complete set of functions has been added [draw](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L1258)" -> 'draw' links to the master branch https://github.com/raysan5/raylib/blob/master/src/raylib.h#L1258 which no longer matches the intended location, which is https://github.com/raysan5/raylib/blob/5.0/src/raylib.h#L1258

Also at least one link doesn't work - `rshapes.h` 404s, should it be `rshapes.c`? https://github.com/raysan5/raylib/blob/5.0/src/rshapes.h

**Comment by raysan5** [comment]
@aSemy Thanks for reporting! Fixed!
