### ISSUE TITLE
How to import the compiled resource file？

### ISSUE THREAD

**Issue by HenYu-Yo** [raysan5/raylib#3592]
How do I use the `SetWindowIcon()` function to set the icon, I've compiled the resource file into a `.o` file

**Comment by Peter0x44** [comment]
This is not an issue, but a question that should probably be on the discord server or in discussions.
Anyway, the intended usage of SetWindowIcon is something like the following:
```c
Image icon = LoadImage("icon.png");
ImageFormat(&icon, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8);
SetWindowIcon(icon);
UnloadImage(icon);
```
If it's giving an icon to the executable itself, that's a different matter.
The question is very unclear, and probably shouldn't be discussed here anyway.
