### ISSUE TITLE
Raylib nesting practices and other syntax releated issues 

### ISSUE THREAD

**Issue by ColleagueRiley** [raysan5/raylib#3597]
I've been looking through some of the source code of Raylib and I've noticed that Raylib has some pretty poor nesting practices. As well as some other minor syntax related issues.

I would suggest Raylib tries to fix these issues because it would make the code far more readable. It would also make it far easier to write and add to code. 

For example there is a part in RText.c that looks like this

```c
if (fileData != NULL) {
  bool genFontChars = false;
  if (stbtt_InitFont(&fontInfo, (unsigned char *)fileData, 0)) {
    ...
  }
  else TRACELOG(LOG_WARNING, "FONT: Failed to process TTF font data");

  if (genFontChars) RL_FREE(fontChars);
}

return 
```

It can easily be reduced to 

```c
if (fileData != NULL || stbtt_InitFont(&fontInfo, (unsigned char *)fileData, 0) == 0) {
  TRACELOG(LOG_WARNING, "FONT: Failed to process TTF font data");  
  return;
}

...

if (genFontChars) 
  RL_FREE(fontChars);

return 
```

Notice how much more readable the second one would be. 
It does not cloud the important code up with if-statements and it gets all of the cases you don't want out of the way right away, so you don't have to even think them anymore.

I'm not sure if this impacts performance any. I'd assume the compiler would generate the same code for both. 
This is more of a syntax issue than anything else.

Another issue I would like to point out while I'm at it is the use of long one line statements such as 

`else if (ch != 32) chars[i].image.data = stbtt_GetCodepointSDF(&fontInfo, scaleFactor, ch, FONT_SDF_CHAR_PADDING, FONT_SDF_ON_EDGE_VALUE, FONT_SDF_PIXEL_DIST_SCALE, &chw, &chh, &chars[i].offsetX, &chars[i].offsetY);`

This is not readable.

```c
else if (ch != 32) 
    chars[i].image.data = stbtt_GetCodepointSDF(&fontInfo, scaleFactor, ch, FONT_SDF_CHAR_PADDING, FONT_SDF_ON_EDGE_VALUE, FONT_SDF_PIXEL_DIST_SCALE, &chw, &chh, &chars[i].offsetX, &chars[i].offsetY);
```

This is far more readable and clear. 

Also, the use of spaces for addition but not multiplication is a bit weird 

`((unsigned char *)atlas.data)[(offsetY + y)*atlas.width + (offsetX + x)] = ((unsigned char *)chars[i].image.data)[y*chars[i].image.width + x];`

It would be more clean and consistent if you added spaces for both.

**Comment by ColleagueRiley** [comment]
It would be easier to fix such bugs with the better style.

**Comment by ColleagueRiley** [comment]
I'm not necessarily suggesting a change in the full codebase. Just adding more rules to code written in the future. Parts with poor syntax can be rewritten as time goes on and when convenient. But, as I've shown with an example, it wouldn't be all that hard to do as you're making it out to be.

**Comment by Peter0x44** [comment]
I don't consider your first change more readable, the line is too long (87 characters).
Not to mention in raylib it's going to be indented one or two levels, so it's actually longer than that, probably wrapping on many editors.


As for "spaces around addition but not multiplication", I think that's a decent choice because when writing that out as math, you wouldn't even write * at all. It's just an attempt to give reading that code that "feel".

**Comment by ColleagueRiley** [comment]
I'm just listing problems I see in Raylib's syntax style. I am not trying to propose any specific solution. 
It's not my place to propose any specific changes. 

But, to me it is kinda sad to see a codebase written by a community of knowledgeable people that's written like this.

**Comment by Peter0x44** [comment]
None of what you pointed out is an "issue", just a formatting/syntax choice that doesn't match your preference/expectation.

**Comment by ColleagueRiley** [comment]
I think it is clear which code is clearer and thereby easier to read and manage.
