### ISSUE TITLE
[core] Problem with `IsMouseButtonUp` which always returns `true`

### ISSUE THREAD

**Issue by Bigfoot71** [raysan5/raylib#3606]
### Issue description

I noticed that the `IsMouseButtonUp` function always returns true with `PLATFORM_DESKTOP` on the master branch (https://github.com/raysan5/raylib/commit/984e83c2d0c6f75053a1ab533e12aece80e24b32).

### Environment

Linux Mint 21.2, 64-bit, Cinnamon

### Code Example

```c
#include "raylib.h"

int main(void)
{
    InitWindow(800, 450, "Button up test");

    while (!WindowShouldClose())
    {
        BeginDrawing();
        ClearBackground(WHITE);

        if (IsMouseButtonUp(MOUSE_LEFT_BUTTON))
        {
            DrawText("Button is UP", 10, 10, 20, BLACK);
        }
        else
        {
            DrawText("Button is DOWN", 10, 10, 20, BLACK);
        }

        EndDrawing();
    }

    CloseWindow();

    return 0;
}
```

**Edit**: Note that doing `if (!IsMouseButtonDown(MOUSE_BUTTON_LEFT))` works for me

**Comment by Minmoose** [comment]
As is so happens I was also looking into this, and just caught this as well I sent a PR #3609
