### ISSUE TITLE
Cheatsheet PDF link is broken

### ISSUE THREAD

**Issue by milen-prg** [raysan5/raylib#3607]
The link to new v.5.0 cheatsheet in PDF is broken:
[https://www.raylib.com/cheatsheet/raylib_cheatsheet_v5.0.pdf](https://www.raylib.com/cheatsheet/raylib_cheatsheet_v5.0.pdf)

**Comment by raysan5** [comment]
@milen-prg Yeah, I'm aware, feel free to send a PR.

**Comment by raysan5** [comment]
Added cheatshet.
