### ISSUE TITLE
[rcore] LoadRandomSequence doesn't work properly

### ISSUE THREAD

**Issue by vinnyhorgan** [raysan5/raylib#3612]
Hi, so i'm compiling a simple raylib program using MSVC, and i can't get the LoadRandomSequence function to work, this is the code:

    unsigned int count = 3; // Change the count as needed
    int min = 1; // Minimum value
    int max = 20; // Maximum value
    int* sequence = LoadRandomSequence(count, min, max);

    if (sequence != NULL) {
        for (unsigned int i = 0; i < count; ++i) {
            printf("%d ", sequence[i]);
        }
    }

When i launch the program it justs hangs, So i tried using a debugger and discovered i am using the new rprand module and it hangs in the function: rprand_load_sequence.

Thanks! Congratulations on the release, it's amazing.

**Comment by raysan5** [comment]
@vinnyhorgan Oh! Did you try debugging it? I use that function and afaik it works as expected for me...

**Comment by raysan5** [comment]
@vinnyhorgan @ubkp I reviewed more carefully the function and there was an issue with the generation. Fixed.
