### ISSUE TITLE
Can you provide a prefixed version of functions and structures?

### ISSUE THREAD

**Issue by huiseliming** [raysan5/raylib#3620]
I cannot include the header files of cef and reylib in a cpp file because the header file of cef depends on the definition in winuser but Raylib must define NOUSER to remove him.

I don't understand why structures and functions are not add prefixed with something like RL.

Macros can be used to enable/disable prefixed versions to maintain compatibility.

**Comment by huiseliming** [comment]
For example use this way
`#ifdef RAYLIB_USE_PREFIXED
void RLShowCursor();
    #ifndef RAYLIB_USE_REMOVE_NOT_PREFIXED
    void (*ShowCursor)() = RLShowCursor;
    #endif // USE_PREFIXED
#else
void ShowCursor();
#endif // USE_PREFIXED
`

**Comment by huiseliming** [comment]
void (*ShowCursor)()
这个定义仅定义在能让源文件不需要修改

**Comment by huiseliming** [comment]
// raylib.h file bg
```
typedef struct RLRectangle {
  float x;      // Rectangle top-left corner position x
  float y;      // Rectangle top-left corner position y
  float width;  // Rectangle width
  float height; // Rectangle height
} RLRectangle;

#ifndef RAYLIB_HIDE_NO_PREFIXED
typedef RLRectangle Rectangle;
#endif // RAYLIB_HIDE_NO_PREFIXED

void ShowCursor();

#ifdef RAYLIB_USE_PREFIXED
#include "prefixed.h"
#endif // DEBUG
```
// raylib.h file ed

// prefixed.h file bg
`GDAPP_API extern void (*RLShowCursor)();`
// prefixed.h file ed

// prefixed.cpp file bg
`void (*RLShowCursor)() = ShowCursor;`
// prefixed.h file ed

**Comment by raysan5** [comment]
Sorry, no plans to add prefuxes to raylib functions for now.
