### ISSUE TITLE
[build] Wrong CMake version mentioned in tag 5.0

### ISSUE THREAD

**Issue by borodin-devel** [raysan5/raylib#3639]
### Issue description

This is quite minor, but Raylib 5.0 still has wrong version mentioned in CMake. Literally spent half an hour thinking of wrong Cmake configuration, but config is simple enough to have errors in it.

### Environment

Raylib desktop, Windows 10, MSVC 19.38.33133.0, CMake 3.28.0

### Code Example

For Cmake code:

```
include(CMakePrintHelpers)
include(FetchContent)

# Include sub-projects.
FetchContent_Declare(
  raylib
  GIT_REPOSITORY https://github.com/raysan5/raylib.git
  GIT_TAG ae50bfa2cc569c0f8d5bc4315d39db64005b1b08 # <<<<<<<<<<<<<<<<<<<<<<<<< version 5.0
)

set(raylib_BUILD_EXAMPLES OFF CACHE BOOL "Build Raylib examples" FORCE)
set(raylib_BUILD_GAMES    OFF CACHE BOOL "Build Raylib games" FORCE)

FetchContent_MakeAvailable(raylib)

cmake_print_properties(TARGETS raylib
  PROPERTIES
    NAME
    TYPE
    VERSION
    SOVERSION
    C_STANDARD
    SOURCE_DIR
    BINARY_DIR
    INCLUDE_DIRECTORIES
    INTERFACE_INCLUDE_DIRECTORIES
    PUBLIC_HEADER
    COMPILE_DEFINITIONS
    INTERFACE_COMPILE_DEFINITIONS
    LINK_LIBRARIES
    INTERFACE_LINK_LIBRARIES
    MSVC_DEBUG_INFORMATION_FORMAT
)
```

It returns such output which is confusing:
```
[cmake] CMake version: 3.28.0
[cmake] -- The C compiler identification is MSVC 19.38.33133.0
[cmake] -- The CXX compiler identification is MSVC 19.38.33133.0
...
[cmake]  Properties for TARGET raylib:
[cmake]    raylib.NAME = "raylib"
[cmake]    raylib.TYPE = "STATIC_LIBRARY"
[cmake]    raylib.VERSION = "4.5.0" <<<<<<<<<<<<<<<<<<<<<<<<< confusion here
[cmake]    raylib.SOVERSION = "450"
[cmake]    raylib.C_STANDARD = "99"
...
```

Also please note that:
```
[cmake] CMake Deprecation Warning at out/build/x64-debug/_deps/raylib-src/CMakeLists.txt:1 (cmake_minimum_required):
[cmake]   Compatibility with CMake < 3.5 will be removed from a future version of
[cmake]   CMake.
[cmake] 
[cmake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
[cmake]   CMake that the project does not need compatibility with older versions.
```

**Comment by raysan5** [comment]
@borodin-devel It has already been reviewed on raylib repo master branch. I'm not re-tagging it.

Also, please note that I'm not the CMake maintainer, it was added by contributors and it's a build system I don't use neither maintain.

I'll keep this issue open for some days in case any CMake expert wants to review it.

**Comment by Peter0x44** [comment]
@borodin-devel simply "we" forgot to bump the number in the CMakeLists.txt before the release was tagged.
Unfortunate, but it is what it is. Next release should be correct 
Is this all you're addressing with the issue? If so, I don't see an acceptable way to change this that Ray would agree with, so it can be closed.

**Comment by raysan5** [comment]
@Peter0x44 What about the CMake version deprecation? Can it be reviewed?
```
[cmake] CMake Deprecation Warning at out/build/x64-debug/_deps/raylib-src/CMakeLists.txt:1 (cmake_minimum_required):
[cmake]   Compatibility with CMake < 3.5 will be removed from a future version of
[cmake]   CMake.
[cmake] 
[cmake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
[cmake]   CMake that the project does not need compatibility with older versions.
```

**Comment by Peter0x44** [comment]
@raysan5 changing the first line of CMakeLists.txt to require cmake 3.5 removes that warning for me. 
cmake 3.5 is from 2016 so I think bumping this shouldn't be an issue. I doubt anyone is testing older versions anyway, it's unlikely they even work.
I can submit a PR for that if it's desired.

**Comment by raysan5** [comment]
> I can submit a PR for that if it's desired.

@Peter0x44 no worries, I can just PR it myself, I'm working on it right now.

**Comment by Peter0x44** [comment]
@borodin-devel it would still be building 5.0, just cmake won't report it as such
which, could be confusing
Actually, some distro packages built with cmake have incorrectly named sos... including arch
https://archlinux.org/packages/extra/x86_64/raylib/
```
usr/lib/libraylib.so.4.5.0
usr/lib/libraylib.so.450
```
Fixing this would require re-tagging a release, but it won't matter to people who aren't using cmake. 
But, you can still use dlsym on raylibVersion if you really want to make sure which so version you have.
In static linking (majority of cases) it is mostly irrelevant.
Opening your raylib.h will also confirm the version you're using.
