### ISSUE TITLE
[rtext] Text input Unicode confusions

### ISSUE THREAD

**Issue by orcmid** [raysan5/raylib#3650]
### Issue description

 1. For Desktop,with GLFW, the `CharCallback` receives an **`unsigned int`** Unicode code-point value.  However, the `CORE.Input.Keyboard.charPressedQueue[ ]` is an array of plain **`int`** values.  Since GLFW effectively returns UTF-32, 32-bit code points and there are currently fewer than 32-bits used in the Unicode standard, there will likely be no conflict.  It should however, be made clear exactly what flavor of Unicode is being delivered.  (And that 32-bit or larger **int** representations are assumed.)

 2. However, in the case of `rcore_desktop_sdl.c` the `SDL_TEXTINPUT` event handling does two peculiar things.  The `event.text.text[0]` value is added to both `CORE.Input.Keyboard.keyPressedQueue[]` ***and*** `Core.Input.Keyboard.charPressedQueue[]`.  But (1) The value in text[0] is *not* a keycode, so anybody who thinks it is will have trouble.  And (2) the value returned in text[] is a null-terminated UTF8 string, so taking only text[0] will be incorrect when the UTF-8 for a single Unicode code point takes more than 1 byte.  (I have no idea why text[32] though.)
 
 PS: Backspacing through UTF8 is a non-trivial activity.

### Environment

This applies to Desktop compilations of raylib.  

### Code Example

This is an armchair report based on code inspection.  I did check GLFW and SDL2 documentation.

**Comment by orcmid** [comment]
I think the proper SDL2 solution would be to scan the `event.text.text[]` array and convert the UTF-8 into UTF-32 for inserting into the `Core.Input.Keyboard.charPressedQueue[]`.

 The tricky bits are ensuring there is enough room in the `charPressedQueue[ ]` and just dropping them if there isn't.  (That seems to be the default behavior in the GLFW case.)  I assume that there will not be more than one code-point's worth of UTF-8, but I am startled that they allowed for 31 bytes plus the `'/0'`.  For some languages, I can see that happening, so might as well handle the worst.

I have no suggestions on how to supply `CORE.Input.Keyboard.keyPressedQueue[]` in the SDL2 instance.   It looks like it should be empty and always return a 0 code.  If SDL2 is consuming the key codes, there may be not much to do about it.  At least in absolves the raylib app of having to cope with different keycode mappings :).

**Comment by raysan5** [comment]
@orcmid thank you very much for the implementations details! Definitely a point for review!

@ubkp Maybe `GetCodepointNext()` could be used to parse text? In any case raylib has several funtions to deal with codepoints/utf8.

**Comment by orcmid** [comment]
@raysan5 @ubkp 
I agree, `GetCodePointNext()` will be valuable in handling the UTF-8 to UTF-32 (codepoint) case in the SDL2 .

I dug around in the various text APIs and confirmed that
- `DrawTextCodepoint(s)` effectively take text as UTF-32
- `DrawText(Ex/Pro)`, and `ImageDrawText(Ex)` all process `text[]` as UTF-8.

And users of `GetCharNext()` will get a codepoint, and that's what it means when "Unicode" is described as the returned **int**.  So long as codepoint values are less than `128`, users can happily use them as if they are making ASCII/ISO646 C Language strings, operating in blissful ignorance until they can't.  I guess then it gets messy.

**Comment by orcmid** [comment]
> @orcmid @raysan5 Agreed, `GetCodepointNext()` is perfect. Since you're at it, please go ahead and send the PR. I won't be able to look at this until wednesday.

I think the larger question is what to do about `GetKeyPressed( )` for SDL2.  I will root around a little before trying anything.  I am not prepared to test with SDL2 though.

**Comment by orcmid** [comment]
I'm sorry, @ubkp.  Please stop telling me things are easy.  MingW, SDL2.  When I say I am not prepared to test with SDL2 I mean I do not want to invest the effort -- I have too many other things that I'm devoting my cycles too and I must keep my focus there.  Sorry to be abrupt.  I appreciate your work.  Going down those roads has no priority for me.

----

About `GetCharPressed( )`.   No matter what (desktop?) backend there is, we need to be clear that the result is what Ramon calls a "codepoint."  I don't think breaking that is cool.

There's a lot of code around where folks use `GetKeyPressed()`, a very different thing.  If there's no way that can work properly with SDL2, there needs to be a clean way to finesse it. 

It still looks like breaking changes.  On the other hand, if SDL2 delivers UTF8, odds are it handles keyboard mappings and more.  If AAA games use it, the odds are great.  But digging it out might defeat the simplified assumptions about keymapping labels for raylib.

My brain hearts and I have an early morning.  Ciao!

**Comment by raysan5** [comment]
@orcmid @ubkp I will review this issue myself as soon as possible.

**Comment by orcmid** [comment]
I thought I commented already.  I need to look at this in context (not DIFFs) and figure out what is happening here.  I don't think the keyPressed is about Unicode code points, so that needs to be clear.

Also, the SDL2 int array, text.txt[13], is 0-terminated UTF-8, and it might be for more than one code-point.

I will look more closely.
