### ISSUE TITLE
font above 127

### ISSUE THREAD

**Issue by wir19** [raysan5/raylib#3660]
I create image font
Font my = LoadFont("name.png");

I put more than '~' glyph. How I can connect my font to Polish language or how draw a character above 128 (byte) ?

DrawTextEx()
generate '?' glyph not my font

I use UTF8 how draw "Ą" glyph in string ?

**Comment by raysan5** [comment]
You should use `LoadFontEx()` and provide required codepoints. There is an example illustrating exactly that.

**Comment by wir19** [comment]
where is example LoadFontFromImage or Ex?
