### ISSUE TITLE
[rcore] Crash on ZMK keyboard input when building with Zig

### ISSUE THREAD

**Issue by Liam-Malone** [raysan5/raylib#3668]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

On my laptop, when using Zig to build, any input from my keyboard with ZMK firmware causes a crash with Illegal Instruction.
It seems that my keyboard is being handled as a `gamepad` input device.

The issue does not occur when building examples with make, nor does it occur when using my laptop's builtin keyboard, or an external TKL keyboard.

### Environment

Platform: DESKTOP (GLFW)
OS: Arch Linux

Startup Info Output:
```
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 230
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) Graphics (ADL GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 23.3.1-arch1.1
INFO:     > GLSL:     4.60
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/85955025/efb6fe11-d815-4180-9c92-b175d9dec111)

Screenshot is of debug info after hitting key, keyboard shows up under 'Gamepad' (name - "ZMK Project....").

### Code Example

```
#include "raylib.h"

int main(void)
{
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");
    while (!WindowShouldClose())
    {
        BeginDrawing();
        EndDrawing();
    }
    CloseWindow();

    return 0;
}
```

**Comment by raysan5** [comment]
@Liam-Malone It seems this issue is not directly related to raylib but an underlying platform library (maybe GLFW) or maybe Zig building. I'm afraid I'm not a Zig expert to know if it could be related to Zig itself.

**Comment by Liam-Malone** [comment]
Yeah, I'm not sure exactly what it is. I don't think it's a GLFW issue as I've been able to write and run programs with GLFW  (using zig as my build system) with no input issues from my keyboard.

I think the problem likely lies somewhere in the Zig building of Raylib/GLFW.

**Comment by Liam-Malone** [comment]
I did a little more experimenting, and it seems it was in fact a GLFW issue, that only surfaced when compiling with Zig's build system. The fix is simple (single line edit) and I've submitted a [pull request](https://github.com/glfw/glfw/pull/2455) to upstream.

**Comment by raysan5** [comment]
Nice! Thanks for further investigating this issue! I'm closing it.
