### ISSUE TITLE
how to persist a windows area?

### ISSUE THREAD

**Issue by cf-isys** [raysan5/raylib#368]
Hi,

I want to use your library for show text and graphics in my app. But I cannot draw all ever. Is possible update only a specific area of windows?

Thank you very much!

**Comment by raysan5** [comment]
Hi @cf-isys, what kind of app are you creating? Are you using raylib dev environment (Notepad++, MinGW)? In [raylib webpage](http://www.raylib.com/examples.html) there are a lot of code examples...

**Comment by raysan5** [comment]
Don't understand the issue, just closing it. Please, feel free to open it again if adding more detailed information.
