### ISSUE TITLE
[rcore] `DecompressData()` sometimes crash in debug mode

### ISSUE THREAD

**Issue by dbechrd** [raysan5/raylib#3683]
### Issue description

`DecompressData()` often asserts and causes debug builds to crash (unclear if the assert is a false positive or a real issue).

### Environment

Windows 11 x64

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/707367/745f63d2-93c9-42ee-9f0c-886ee53f1cc9)

### Code Example

```cpp
uint8_t data[]{ 1, 1, 1, 1, 1, 1, 1, 1 };

int deflated_bytes = 0;
int inflated_bytes = 0;

uint8_t *deflated = 0;
uint8_t *inflated = 0;

// HACK: All of these leak memory, don't use this code in real codebases
// buffers of size 1 - 4 bytes work fine
deflated = CompressData(data, 1, &deflated_bytes);
inflated = DecompressData(deflated, deflated_bytes, &inflated_bytes);
deflated = CompressData(data, 2, &deflated_bytes);
inflated = DecompressData(deflated, deflated_bytes, &inflated_bytes);
deflated = CompressData(data, 3, &deflated_bytes);
inflated = DecompressData(deflated, deflated_bytes, &inflated_bytes);
deflated = CompressData(data, 4, &deflated_bytes);
inflated = DecompressData(deflated, deflated_bytes, &inflated_bytes);

// buffers of size 5 - 8 bytes assert during DecompressData()
deflated = CompressData(data, 5, &deflated_bytes);
inflated = DecompressData(deflated, deflated_bytes, &inflated_bytes);
deflated = CompressData(data, 6, &deflated_bytes);
inflated = DecompressData(deflated, deflated_bytes, &inflated_bytes);
deflated = CompressData(data, 7, &deflated_bytes);
inflated = DecompressData(deflated, deflated_bytes, &inflated_bytes);
deflated = CompressData(data, 8, &deflated_bytes);
inflated = DecompressData(deflated, deflated_bytes, &inflated_bytes);
```

I upgraded Raylib to latest master and ran this test again, and 5-8 bytes still crashes.

The sinfl codebase isn't exactly the easiest thing to read. I tried stepping through this in the debugger but honestly didn't learn anything particularly interesting. I'm wondering if perhaps the buffer you send to sinfl has to be padded to match a certain block size or something.. but neither the Raylib docs nor the sinfl header say anything about any such constraints.

Or I'm just being dumb and there's a simple mistake in my code, but I don't see it atm.

**Comment by dbechrd** [comment]
FWIW, commenting out that assert and rebuilding raylib _seems_ to fix the issue, so maybe one of the sinfl maintainers just added a silly assert with no test coverage?

**Comment by raysan5** [comment]
@dbechrd Actually, this is a know issue with `sinfl` library (https://github.com/raysan5/raylib/issues/3349), for some specific situations when the compressed stream ending bits do not fit in the count, the debugger with ASAN complains... but the decompression process actually works as expected.

Probably those asserts could be commented and ignored.

**Comment by raysan5** [comment]
Asserts were commented and ignored.
