### ISSUE TITLE
[rcore] Support nested Scissor calls

### ISSUE THREAD

**Issue by dbechrd** [raysan5/raylib#3695]
Would be great if Raylib's `BeginScissorMode()`/`EndScissorMode()` supported nested calls. This is very common when trying to make UIs. It would also be nice if it took a Rectangle as a parameter, but that's not nearly as important.

I removed the DPI code from my version because I don't have access to `CORE`, but feel free to steal this code and put it in Raylib and re-add the DPI aware stuff:

```c
// NOTE: You'll probably want to use some Raylib/C data structure here.
std::stack<Rectangle> scissorStack{};

void PushScissorRect(const Rectangle &rect)
{
    rlDrawRenderBatchActive();

    if (scissorStack.empty()) {
        rlEnableScissorTest();
    }

    rlScissor(rect.x, GetRenderHeight() - (rect.y + rect.height), rect.width, rect.height);
    scissorStack.push(rect);
}

void PopScissorRect(void)
{
    rlDrawRenderBatchActive();

    scissorStack.pop();

    // Restore previous scissor rect
    if (!scissorStack.empty()) {
        Rectangle &rect = scissorStack.top();
        rlScissor(rect.x, GetRenderHeight() - (rect.y + rect.height), rect.width, rect.height);
    } else {
        rlDisableScissorTest();
    }
}
```

**Comment by raysan5** [comment]
@dbechrd I'm afraid this is not trivial in C and it requires some additional complexity to support this feature. Out of scope for now.

**Comment by dbechrd** [comment]
@raysan5 Could you be more specific? Both for my own implementation, but also in case someone wants to contribute a PR trying to solve this in the future. That would be helpful, thanks!

**Comment by raysan5** [comment]
```c
// NOTE: You'll probably want to use some Raylib/C data structure here.
std::stack<Rectangle> scissorStack{};
```

There is no raylib structure for this, just an array with all the additional involved logic or an additional custom structure. It implies additional level of complexity overall, to cover a specific use case that users requiring it can implement by themselfs for their specific needs.

**Comment by dbechrd** [comment]
@raysan5 I submitted a PR for this issue. Feel free to leave feedback there if there are any concerns. Thanks!

**Comment by raysan5** [comment]
@dbechrd Thanks for the effort but as I said it adds a level of complexity to code that I prefer to avoid. I can keep the PR open as a reference for users really requiring it but I'm not merging it.

**Comment by dbechrd** [comment]
That's unfortunate. It seems quite simple to me and it's necessary for any UI work. How are you handling scrolling in your own UI library without having a working scissor stack?

**Comment by raysan5** [comment]
> How are you handling scrolling in your own UI library without having a working scissor stack?

I use `BeginScissorMode()` and `EndScissorMode()`, personally I did not have the need for anything else...

 > I really hate having to maintain a fork of Raylib for basic features like this.

Sincerely, I don't think this is a basic feature that most users need. Actually in 10 years you are the first raylib user requiring it.

**Comment by dbechrd** [comment]
@raysan5 It's fine.. I reverted all of my code to the manual override. It's a bit messier, but whatevs. I do understand that supporting scissor could become complex, but considering you already support scissor, having a stack doesn't meaningfully change anything about the complexity (in fact, I would argue it's much easier to understand from a user standpoint when Raylib throws a clear error message rather than just scissoring the wrong region of the screen; even when the stack size is implicitly 1).

As for me being the first person to "need" it.. I don't think most users would "need" anything that gets added to new versions of Raylib. You can always make the argument that Raylib is a simple library that only does simple things, but that doesn't mean users wouldn't use this feature.

To make an accurate statement about needs, you would have to ask people who use BeginScissorMode(), rather than just assume based on the absence of someone previously having put the effort into coding a solution and submitting it as a PR.

Perhaps you should try adding scroll regions (e.g. multi-line textboxes) to your UI library, which themselves can exist in a scrolling panel (e.g. the editor, docked to the left of the screen). The box that we're typing these comments into right now is a scrolling textbox inside of a window with a scrollbar. Having two levels of scissor is a ubiquitous necessity in UI.

**Comment by dbechrd** [comment]
Here's a real screenshot from my Raylib app just for context, and to prove that I'm not trying to invent solutions to problems that I'm not actually having right now, lol:
![image](https://github.com/raysan5/raylib/assets/707367/5e93336f-3d6f-4bfd-9461-f290406a4613)

**Comment by raysan5** [comment]
@dbechrd Thank you very much for providing the additional information and your specific use case. It really adds context despite I still think it's not a critical feature for most users.

**Comment by dbechrd** [comment]
@raysan5 Sure thing! The post was a bit emotional so I tried to make it more objective for anyone reading who might be having the same issue in the future. My code both here, and in the PR, should be more than sufficient as an example should anyone else need build their own wrapper. Feel free to close this, or use the code in the future, or whatever. Both code snippets can be considered public domain.

Thanks again for creating and actively maintaining Raylib. It's not an easy task, and it's a wonderful tool. Perhaps I'll outgrow it one day, but for now, it still provides more than enough value to outweigh the annoyances. It's 99.999% more fun to interact with than the language itself (C++ in my case), so that's something worth praising for sure. :)

**Comment by raysan5** [comment]
@dbechrd Thank you very much for your kind words and for your comprehension.

**Comment by RudyFisher7** [comment]
I'm looking to have nested scroll panels as well. Is this possible without adding a scissor stack like what is shown here? Basically, is there a way to do this without changing rcore?

@raysan5 @dbechrd 

Thanks!

**Comment by bramtechs** [comment]
Sorry for replying to closed issues, but I also would like this feature to exist in core Raylib. Currently I need to draw my scroll panel content into a render texture first which isn't really a good solution.

**Comment by EzeAGB** [comment]
I also need this functionality. This should be part of Raylib.

**Comment by evanrinehart** [comment]
Would be nice. Recursion simplifies a lot of things
