### ISSUE TITLE
[build] Is it possible to get support for having the application minimize to the tray, with a tray menu?

### ISSUE THREAD

**Issue by ElfenSterben** [raysan5/raylib#3696]
Is it possible to get support for having the application minimize to the tray, with a tray menu? 
I tried use win32 api with include  window.h but it raise some errors like 
```c
In file included from C:/raylib/w64devkit/x86_64-w64-mingw32/include/windows.h:71,
                 from main.c:21:
C:/raylib/w64devkit/x86_64-w64-mingw32/include/wingdi.h:3158:28: error: 'Rectangle' redeclared as different kind of symbol
 3158 |   WINGDIAPI WINBOOL WINAPI Rectangle(HDC hdc,int left,int top,int right,int bottom);
```

**Comment by ElfenSterben** [comment]
> > Is it possible to get support for having the application minimize to the tray, with a tray menu?
> 
> @ElfenSterben Yeah, probably.
> 
> To workaround the `windows.h` issue, check [this answer](https://github.com/raysan5/raylib/issues/1217#issuecomment-618428626). IMHO, option 1 is the easiest one. Something similar is done to the `Sleep()`, `timeBeginPeriod()` and `timeEndPeriod()` functions (e.g. [here](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L475-L476) and [here](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L67-L69)).
> 
> **Edit:** editing.

i tired this way,but it still has other symbols redeclared like PlaySound

```
gcc -o game main2.c -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -s -O1 .\raylib/src/raylib.rc.data -Wl,--subsystem,windows -I. -I.\raylib/src -I.\raylib/src/external -L. -L.\raylib/src -L.\raylib/src -lraylib -lopengl32 -lgdi32 -lwinmm -DPLATFORM_DESKTOP
In file included from C:/raylib/w64devkit/x86_64-w64-mingw32/include/winnt.h:9,
                 from C:/raylib/w64devkit/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/raylib/w64devkit/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/raylib/w64devkit/x86_64-w64-mingw32/include/windows.h:69,
                 from main2.c:51:
.\raylib/src/raylib.h:1603:12: error: conflicting types for 'PlaySoundA'; have 'void(Sound)'  
 1603 | RLAPI void PlaySound(Sound sound);                                    // Play a sound 
      |            ^~~~~~~~~
In file included from C:/raylib/w64devkit/x86_64-w64-mingw32/include/mmsystem.h:30,
                 from C:/raylib/w64devkit/x86_64-w64-mingw32/include/windows.h:86:
C:/raylib/w64devkit/x86_64-w64-mingw32/include/playsoundapi.h:68:25: note: previous declaration of n of 'PlaySon of 'PlaySounn on of 'PlaySoundA' with type 'WINBOOL(const CHAR *, struct HINSTANCE__ *, DWORD)' {aka 'int(const char *, struct HINSTANCE__ *, long unsigned int)'}
   68 | WINMMAPI WINBOOL WINAPI PlaySoundA(LPCSTR pszSound, HMODULE hmod, DWORD fdwSound);
      |                         ^~~~~~~~~~
make[1]: *** [Makefile:378: game] Error 1
make[1]: Leaving directory 'C:/Users/es/projects/desktop-clock'
make: *** [Makefile:374: all] Error 2

```

finally, i wrote a file to use window.h, another file to use raylib.h, it works.

**Comment by ElfenSterben** [comment]
> @orcmid I use a similar approach with some of my tools, I got a `win32_utils.c` that includes `windows.h` and/or exposes required symbols.

it works. thank you

**Comment by ElfenSterben** [comment]
> @orcmid I use a similar approach with some of my tools, I got a `win32_utils.c` that includes `windows.h` and/or exposes required symbols.

maybe you cloud support a example about this

**Comment by orcmid** [comment]
@ElfenSterben (cc: @raysan5) 
> > @orcmid I use a similar approach with some of my tools, I got a `win32_utils.c` that includes `windows.h` and/or exposes required symbols.
> 
> maybe you cloud support a example about this

I am developing a small library utility, `nfoPixels` that uses exactly this technique to assist the executables of raylib desktop apps on Windows x64 to appear properly when installed on PCs with displays of different resolutions.  `nfoPixels.h` declares the API and is included in the raylib application. `nfoPixels.c` is compiled as part of the application, and `nfoPixels.c` has an `#include <windows.h>` for obtaining display characteristics and setting up the scale-adjustment functions that are defined for implementaiton of the API.  These happen independent of raylib altogether and can be used whether or not `InitWindow` has happened yet.

The interfaces defined in `nfoPixels.h` are platform-independent and there could be different `nfoPixels.c` for other platforms, probably using techniques similars to those that support the different backends for raylib 5.0.  I will allow for that.  I don't intend to go that far for `nfoPixels` 1.0.

I can provide a very small fragment as an example if that is actually needed.  This is not an unusual practice in development in C Language though.

**Comment by orcmid** [comment]
> @ElfenSterben (cc: @raysan5)
> I can provide a very small fragment as an example if that is actually needed. This is not an unusual practice in development in C Language though.

I created a demonstration at https://github.com/orcmid/rayLab/tree/main/myProjects/nfoPixels

The files that matter are `nfoPixels.h`, `nfoPixels.c` and demonstration `npxShow.c`.  The single command for compiling is at `mknpxShow.bat`.   The compilation is done with a Visual Studio Developer Command Prompt.  

This project folder is currently a scrap heap and I need to move the nfoPixel project to its own folder in my devKits.

I am still experimenting with the WIndows APIs for handling screen resolution, scaling and sizes.   When I am satisfied with what is available, I will complete the `nfoPixels.h` AP:I and `nfoPixels.c` implementation.   My goal is to include this in my 
[VCrayApp](https://orcmid.github.io/nfoTools/dev/D211101/) 1.0.0 release.  Meanwhile, I have much documentation to produce on several projects, especially
this one](https://orcmid.github.io/miser/) along with VCrayApp.
