### ISSUE TITLE
How chceck the Image are unload?

### ISSUE THREAD

**Issue by wir19** [raysan5/raylib#3703]
I need using this same Image variable twice.
How chcek: is my variable load or genImage or not?

```
#include "raylib.h"
#include "stdio.h"

int main(void)
{
 Image parrots;

 if( IsImageReady(parrots) ) printf("tak\n"); else printf("nie\n");

    parrots = GenImageColor(512, 384, (Color){ (unsigned char)GetRandomValue(100, 250), (unsigned char)GetRandomValue(50, 150), (unsigned char)GetRandomValue(10, 100), 255 });
 if( IsImageReady(parrots) ) printf("tak\n"); else printf("nie\n");
   
   UnloadImage(parrots);
 if( IsImageReady(parrots) ) printf("po unload tak\n"); else printf("po unload nie\n");

   parrots = LoadImage("raylib/examples/textures/resources/cat.png");
 if( IsImageReady(parrots) ) printf("po unload tak\n"); else printf("po unload nie\n");

   UnloadImage(parrots);
 if( IsImageReady(parrots) ) printf("po unload tak\n"); else printf("po unload nie\n");

return 0;
}

```
output:

```
nie
tak
po unload tak
INFO: FILEIO: [raylib/examples/textures/resources/cat.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (384x512 | R8G8B8 | 1 mipmaps)
po unload tak
po unload tak
```

meybe setup NULL image data pointer ?

**Comment by srem1** [comment]
image.data is a pointer
image is a copy

**Comment by raysan5** [comment]
> Actually, don't we have a memory leak problem here? Since Image image is passed by value to UnloadImage() when we RL_FREE() it, we're not freeing the actual image.data, but the copy. @raysan5 Please correct me if I'm wrong.

@ubkp Image is passed by value but `image.data` contains a valid address pointing to dynamically-allocated data so, data can be freed as expected... But the `Image` object passed by copy can not be internally modified, so, not only field values can't be reseted but neither the pointer address value.

It was designed this way for simplicty for users, minimizing as much as possible pointers usage... and expecting more advance users to deal with the consequences on users side.

The proper way to **reuse** most raylib variables based on structures that imply `Load*()`/`Unload*()` is:

```c
Image image = LoadImage("cat.png");  // image.data is dynamically allocated, pointer address set, image fields set, copy returned

UnloadImage(image); // image.data is correctly freed but no image fields can be modified due to dealing with a copy

//UnloadImage(image); // WARNING: Trying to free(image.data) already freed, address is valid but data has already been unloaded --> CRASH!

image = (Image){ 0 };  // Reset all fields manually at user side for image reuse

image = LoadImage("dog.png");  // New image loaded internally and copy returned
```

**Comment by raysan5** [comment]
@wir19 Answering to your original question:

After calling `UnloadImage(image)` just reset image internal data `image = (Image){ 0 }` if you are planning to reuse it. My recommendation is avoiding reusing per design if possible.
