### ISSUE TITLE
Resize without interpolation

### ISSUE THREAD

**Issue by srem1** [raysan5/raylib#3706]
I write pixel game (PixelArt). I must put my small sprite to big texture.
I'cant found any function to resize without algorithms Bicubic or Nearest-Neighbor.

I need simple convert one pixel to 4 or 9 or 16 etc.

```
#define RESIZE_2x2    2
#define RESIZE_3x3    3
#define RESIZE_4x4    4
.....
```

**Comment by raysan5** [comment]
To resize an image you should use `ImageResizeNN()`.
To draw a resized texture, you should `SetTextureFilter(texture, TEXTURE_FILTER_POINT)`.

**Comment by srem1** [comment]
this is not answer
meybe will be create new functions
