### ISSUE TITLE
[warning] stb_image_resize2.h

### ISSUE THREAD

**Issue by srem1** [raysan5/raylib#3707]
> In file included from rtextures.c:216:
> external/stb_image_resize2.h:2866:14: warning: ‘stbir__support_zero’ defined but not used [-Wunused-function]
>  2866 | static float stbir__support_zero(float s, void * user_data)
>       |              ^~~~~~~~~~~~~~~~~~~
> external/stb_image_resize2.h:2503:13: warning: ‘stbir_simd_memcpy’ defined but not used [-Wunused-function]
>  2503 | static void stbir_simd_memcpy( void * dest, void const * src, size_t bytes )
>       |             ^~~~~~~~~~~~~~~~~
> ar rcs ../src/libraylib.a rcore.o rshapes.o rtextures.o rtext.o utils.o rglfw.o rmodels.o raudio.o
> raylib static library generated (libraylib.a) in ../src!
>

**Comment by srem1** [comment]
I use 
-W -Wall -Werror -pedantic -pedantic-errors
and yse it harmless ;D

**Comment by raysan5** [comment]
@ubkp Thanks for the review! Note that I'm merging it for consistency with previous solutions but I'm not fully convinved if this is the best approach to deal with those warnings. I'm not a fan of `pragmas`, I got the feeling that they belong to build side and not code side, despite they are supported by most compilers...

At the moment they are just a few lines in a couple of files and don't seem to generate any issue (beside an aesthetic detriment), so, keeping them for now...
