### ISSUE TITLE
How using c code from  ExportFontAsCode()

### ISSUE THREAD

**Issue by srem1** [raysan5/raylib#3711]
How using file mojechar.c from  ExportFontAsCode(fo, "mojechar.c");

I get many errors like :  

> error: missing initializer for member ‘Image::width’ [-Werror=missing-field-initializers]
>   311 | };
>       | ^
> 

.....

> mojechar.h:311:1: error: missing initializer for member ‘Image::width’ [-Werror=missing-field-initializers]
> mojechar.h:311:1: error: missing initializer for member ‘Image::height’ [-Werror=missing-field-initializers]
> mojechar.h:311:1: error: missing initializer for member ‘Image::mipmaps’ [-Werror=missing-field-initializers]

.....

> error: invalid conversion from ‘const GlyphInfo*’ to ‘GlyphInfo*’ [-fpermissive]
>   335 |     font.glyphs = fontGlyphs_mojechar;
deleting 'const' etc.

meybe add .width = number in initialize structure ?
or add image record directly no {0} -> {0,0,0,0,0}

**Comment by raysan5** [comment]
@srem1 Issues are intended for raylib issues, not for questions about library usage. I recommend you use Discussions or Discord for this kind of questions.

**Comment by Peter0x44** [comment]
@srem1 are you using C? Do you observe those problems with it?

**Comment by bialystok** [comment]
I recomendet read issue

this is a bug
and solution

**Comment by orcmid** [comment]
@bialystok (cc: @Peter0x44)
> I recomendet read issue
> this is a bug and solution

Well, `Image::width` is not C Language, so this issue is misplaced.  Those error messages are not related to raylib itself, so it cannot be a raylib bug. 

There is a matter of initializer differences between C and C++ but raylib is C Language and must be compiled as such.  The header files are amenable for linking and run-time calling from C or C++.  But these errors are strictly on the C++ side.

**Comment by Peter0x44** [comment]
@orcmid they are warnings, promoted to errors (he chose to compile with -Werror)
The -fpermissive stuff are all errors, unless you specifically pass -fpermissive
It's not true the errors aren't related to raylib code. What is up for debate is whether it's raylib's problem. 
Try the following with GCC:
```cpp
typedef struct
{ int x, y; } test;

void t(void)
{
    test x = {0};
}
```
`g++ -Wall -Wextra test.cpp`

**Comment by orcmid** [comment]
@Peter0x44 I don't need to try that in any C++ compilation.  

I am looking at `rtext.c` in raylib 5.1-dev.  The first and only place there is generated code having an `={0}` initializer is in

``` 
    "// Font loading function: %s\n", fileNamePascal);
    "static Font LoadFont_%s(void)\n{\n", fileNamePascal);
    "    Font font = { 0 };\n\n");
    "    font.baseSize = %i;\n", font.baseSize);
    "    font.glyphCount = %i;\n", font.glyphCount);
    "    font.glyphPadding = %i;\n\n", font.glyphPadding);
```

All other cases are array or struct initializations where the values are enumerated completely in the initialization `{ ... }`.

The output array holds the bytes of a compressed data structure.  There will be a note about that in the code.

There is clearly not enough information to make sense of the original issue statement and I agree with it being closed.
