### ISSUE TITLE
[rtext] This font is missing glyphs

### ISSUE THREAD

**Issue by tromero** [raysan5/raylib#3717]
### Issue description

When I load the ttf for this pixel font (Little League by chevy ray) and draw text using it, a bunch of letters near the end of the alphabet go missing.

I tested about 11 different fonts and this is the only one that appears to have this issue.

In raylib it appears to act as if it's missing the last few lowercase letters? The font file contains upper and lowercase glyphs for all 26 letters, when I inspect it in Font Book on Mac.

Font file provided here for bug repro purposes only, do not redistribute:
[ChevyRay - Little League.ttf.zip](https://github.com/raysan5/raylib/files/13871623/ChevyRay.-.Little.League.ttf.zip)

### Environment

Emscripten web build, running in Brave browser (chrome, effectively) on an M2 Pro Mac Mini.
Also occurs on iOS Safari browser on iPhone.

### Issue Screenshot
![Screenshot 2024-01-09 at 1 16 10 AM](https://github.com/raysan5/raylib/assets/573471/fc53ce06-0577-4c0e-95f0-2e4f234729d7)

### Code Example

```
	font = LoadFontEx("resources/fonts/ChevyRay - Little League.ttf", 7, nullptr, 0);

	float y = 10;
	float verticalSpacing = tileset.font.baseSize * cameraZoom;
	float size = tileset.font.baseSize*cameraZoom;
	float spacing = 1.0f * cameraZoom;

	DrawTextEx(font, TextFormat("%2i FPS", GetFPS()), Vector2{10, y}, size, spacing, DARKGRAY);
	DrawTextEx(font, "Five big quacking zephyrs jolt my wax bed.", Vector2{10, y += verticalSpacing}, size, spacing, DARKGRAY);
	DrawTextEx(font, "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz", Vector2{10, y += verticalSpacing}, size, spacing, DARKGRAY);
	DrawTextEx(font, TextFormat("%2ix%2i", GetRenderWidth(), GetRenderHeight()), Vector2{10, y += verticalSpacing}, size, spacing, DARKGRAY);
	DrawTextEx(font, TextFormat("%0.1f DevicePixelRatio", devicePixelRatio), Vector2{10, y += verticalSpacing}, size, spacing, DARKGRAY);
	DrawTextEx(font, TextFormat("%0.1f Camera zoom", cameraZoom), Vector2{10, y += verticalSpacing}, size, spacing, DARKGRAY);
	DrawTextEx(font, "Sticky Chunks!!!", Vector2{10, y += verticalSpacing}, size, spacing, DARKGRAY);

```

**Comment by Moand97** [comment]
I have tried loading the font you uploaded in the same way and it only fails with the fontSize parameter at 7 of LoadFontEx. With 8, 16, 32 it works

With 7:
![image](https://github.com/raysan5/raylib/assets/53525849/63f619bc-7955-438e-9204-c5a8d5c8639e)

With other:
![image](https://github.com/raysan5/raylib/assets/53525849/f3594ede-9da1-482e-b93c-344a56308a1b)

**Comment by tromero** [comment]
Interesting, however because it’s a pixel font only loading it at the exact size will do as other sizes will make the text blurrier. I suppose I could load it at double-size and then draw at half size to work around the issue but it seems wasteful.

**Comment by raysan5** [comment]
@tromero It seems the issue could reside in rasterization library (`stb_truetype`) instead of raylib... but also, the pixel-fonts are intended to be loaded at the expected pixel-perfect size, afaik.

@Moand97 Thanks for the additional testing and info.

**Comment by orcmid** [comment]
@raylib
> @tromero It seems the issue could reside in rasterization library (`stb_truetype`) instead of raylib... but also, the pixel-fonts are intended to be loaded at the expected pixel-perfect size, afaik.

This is going to be a problem when the all-too-common display dpi scaling is adjusted for.  I suppose it will become necessary to encourage vector fonts (and kerning).

**Comment by tromero** [comment]
@raysan5 some more poking around confirmed the issue is in raylib's atlas packing, not stb truetype. From the log:

```
INFO: FILEIO: [resources/fonts/ChevyRay - Little League.ttf] File loaded successfully
StickyChunks.html:1 WARNING: FONT: Failed to package character (86)
StickyChunks.html:1 WARNING: FONT: Failed to package character (87)
StickyChunks.html:1 WARNING: FONT: Failed to package character (88)
StickyChunks.html:1 WARNING: FONT: Failed to package character (89)
StickyChunks.html:1 WARNING: FONT: Failed to package character (90)
StickyChunks.html:1 WARNING: FONT: Failed to package character (91)
StickyChunks.html:1 WARNING: FONT: Failed to package character (92)
StickyChunks.html:1 WARNING: FONT: Failed to package character (93)
StickyChunks.html:1 WARNING: FONT: Failed to package character (94)
StickyChunks.html:1 INFO: TEXTURE: [ID 30] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
StickyChunks.html:1 INFO: FONT: Data loaded successfully (7 pixel size | 95 glyphs)
```

It does occur in other fonts set to size 7 and even size 6 sometimes. Wider fonts lose more glyphs. This font size is just within the threshold where GenImageFontAtlas reduces the atlas size from 256 x 128 down to 128 x 128. 

Maybe the 1.2 padding factor on the area calculation isn't enough for atlases this small? Or maybe the current approximation of the atlas's total area is not accurate due to the glyph images being taller than fontSize. I can continue poking at it.

**Comment by orcmid** [comment]
@tromero 
> @orcmid what impact do you expect DPI scaling to have? I would not expect the library to load fonts at 2-3x the point size when running hi dpi. 

I do **not** expect the library to deal with display scaling automatically.  But if an app does scale itself for a different dpi (and/or user-set display scaling) it may not get great results when requesting greater text heights using raster fonts.

Problems with switching displays are uniformly tricky, because of changes in dpi and also resolution (i.e., screen dimensions in pixels).  If that is supported, it seems the app has a lot to deal with on the fly.  I don't believe what we're talking about here copes with that.

**Comment by tromero** [comment]
The padding calculation does indeed seem like an underestimate. it adds 4*padding to the width of each glyph, increasing the area by the red amount (80px), which is less than the green amount which is the actual area of the padding (144px)
![image](https://github.com/raysan5/raylib/assets/573471/300b2d8c-1746-44a0-b43f-b264d2080a62)

**Comment by tromero** [comment]
Resolved in PR 3719
