### ISSUE TITLE
[rtext] Line break spacing too small

### ISSUE THREAD

**Issue by xslendix** [raysan5/raylib#3718]
Please, before submitting a new issue verify and check:

 - [*] I tested it on latest raylib version from master branch
 - [*] I checked there is no similar issue already reported
 - [*] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [*] My code has no errors or misuse of raylib

### Issue description

I have loaded a system TTF font `/usr/share/fonts/TTF/DejaVuSans.ttf` like so: `m_font = LoadFontEx(m_config.font_path.c_str(), 256, nullptr, 0);`. For some reason, `MeasureTextEx` and `DrawTextEx` do not report correct results.

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*

```
Platform: Linux (Desktop)
OS: Artix GNU/Linux
INFO: GL: OpenGL device information:
INFO:     > Vendor:   AMD
INFO:     > Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 16.0.6, DRM 3.54, 6.6.9-artix1-1)
INFO:     > Version:  4.6 (Core Profile) Mesa 23.3.2-arch1.2
INFO:     > GLSL:     4.60
```

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/32436619/6d72db90-2347-4ead-90f7-b2d18ffc46dd)

### Code Example

```c
#include <raylib.h>
#include <stddef.h>

int main(void) {
  InitWindow(1280, 720, "example");
  Font font = LoadFontEx("/usr/share/fonts/TTF/DejaVuSans.ttf", 256, NULL, 0);
  for (;;) {
    BeginDrawing();
    ClearBackground(RAYWHITE);
    Vector2 pos = {0, 0};
    DrawTextEx(font, "line 1\nline2", pos, 64, 0, BLACK);
    EndDrawing();
  }
  return 0;
}
```

**Comment by xslendix** [comment]
I think it may not be taking `font.recs->height` into consideration in a formula

**Comment by tromero** [comment]
SetTextLineSpacing() - there's a global variable which is the source of your issue. You can work around it by manually setting the line spacing based on your font height. I of course don't think that's the right long-term solution for the health and usability of the library, line spacing should be a part of the font.
```
            // NOTE: Line spacing is a global variable, use SetTextLineSpacing() to setup
            textHeight += (float)textLineSpacing;
```

**Comment by xslendix** [comment]
Great workaround, thanks! Will keep this issue open though

**Comment by raysan5** [comment]
@tromero Afaik, line spacing is never provided in the font, it's managed by user, like the drawing font size.

In any case, `SetTextLineSpacing()` was added recently for convenience, before it was always harcoded to 1.5f font draw size.
