### ISSUE TITLE
[build] undefined reference to `glfwSetWindowMonitor`

### ISSUE THREAD

**Issue by Martinfx** [raysan5/raylib#372]
Hi i tested build on ubuntu but library have undefined references.
pc@m:~/raylib/examples$ make 
```
gcc -o core/core_basic_window core/core_basic_window.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -fgnu89-inline -Wno-missing-braces -no-pie -D_DEFAULT_SOURCE -I. -I../release/include -I../src -I../src/external -L. -L../release/libs/linux -L../src  -lraylib -lglfw3 -lGL -lopenal -lm -lpthread -ldl -lX11 -lXrandr -lXinerama -lXi -lXxf86vm -lXcursor -DPLATFORM_DESKTOP
../release/libs/linux/libraylib.a(core.o): In function `ToggleFullscreen':
core.c:(.text+0x5a85): undefined reference to `glfwSetWindowMonitor'
core.c:(.text+0x5aba): undefined reference to `glfwSetWindowMonitor'
../release/libs/linux/libraylib.a(core.o): In function `SetWindowIcon':
core.c:(.text+0x5b15): undefined reference to `glfwSetWindowIcon'
../release/libs/linux/libraylib.a(core.o): In function `SetWindowMonitor':
core.c:(.text+0x5bc1): undefined reference to `glfwSetWindowMonitor'
../release/libs/linux/libraylib.a(core.o): In function `SetWindowMinSize':
core.c:(.text+0x5c46): undefined reference to `glfwSetWindowSizeLimits'
collect2: error: ld returned 1 exit status
Makefile:314: recipe for target 'core/core_basic_window' failed
make: *** [core/core_basic_window] Error 1
```

**Comment by RDR8** [comment]
Are you using a shared or static GLFW? The -lnames are different.

**Comment by gen2brain** [comment]
@Martinfx glfwSetWindowMonitor was added in version 3.2 http://www.glfw.org/docs/latest/group__window.html#ga81c76c418af80a1cce7055bccb0ae0a7 . It seems you have older version.

**Comment by Martinfx** [comment]
I compiled as static
```
raylib library release path is ../release/libs/linux
ar rcs ../release/libs/linux/libraylib.a  rlgl.o  core.o  audio.o  shapes.o  models.o  textures.o  text.o  utils.o stb_vorbis.o
raylib static library generated (libraylib.a)!
expected OpenAL Soft static library linking
```

**Comment by Martinfx** [comment]
Last version glfw library on ubuntu 16.04 
```
libglfw3-dev/xenial,now 3.1.2-3 amd64 [installed]
portable library for OpenGL, window and input (development files)
```

**Comment by RDR8** [comment]
If you are using Ubuntu's GLFW, not only is it really old, it's a shared lib named libglfw.so, not libglfw3.a so look at line 208 of examples/Makefile. You could change -lglfw3 to -lglfw and see if the Ubuntu package works before compiling a static GLFW as per Ray's installation instructions .

**Comment by gen2brain** [comment]
@raysan5 Just an idea, but perhaps GLFW source can be bundled (header files are already in).  GLFW can be in single .c file, like this https://gist.github.com/gen2brain/9044abf3e824e63c2ed7d34f89836cd5 , I use something similar in Go bindings.

So one flag can be added in Makefile, if enabled just add one more single .c file, defines in CFLAGS and then there is no need to link to libglfw. Something like GLFW_LIBTYPE = BUNDLED .

**Comment by raysan5** [comment]
Hi @Martinfx, @gen2brain is right, `glfwSetWindowMonitor()` was added in version 3.2, as @RDR8 state, there are some inconsistencies on GLFW3 library naming: https://github.com/glfw/glfw/issues/1051

 @gen2brain, really like your idea of bundling GLFW library with raylib, that way that external dependency will be included with the library... after all, one of the goals of raylib is try to minimize external dependencies (at least in terms of forcing the user to deal with external packages).

How do you deal with OpenAL in Go? That's my eternal dependency...

**Comment by gen2brain** [comment]
@raysan5 I have no solution for OpenAL. On Linux it is easy to install and there are no problems with versions. On OS X system OpenAL is used so library can be used with just `go get` tool. On Windows i recommend MSYS2 because it can be easy installed with `pacman` tool. 

Perhaps similar can be done with OpenAL (to include .c files), but not sure about license. raylib can be used for some commercial project perhaps, in which case OpenAL should be shared. So far everything is zlib license, or public domain, except OpenAL.

**Comment by gen2brain** [comment]
@raysan5 btw, I added recently option to build binary without OpenAL , with `-tags noaudio`  audio* files are excluded from build, so OpenAL is not linked and audio functions are not available, e.g. for apps that don't need audio.

**Comment by raysan5** [comment]
> So far everything is zlib license, or public domain, except OpenAL.

I know, and this gives me many sleepless nights... just kidding...

The truth is that OpenAL Soft is quite easy to use and support most of the platforms out there but I've been looking for a proper replacement since the beginning of raylib (https://github.com/raysan5/raylib/issues/52). OpenAL Soft is also a very big dependency, can't understand that, it's even bigger than all raylib!

There are already two possible alternatives on my radar: [libsoundio](https://github.com/andrewrk/libsoundio) and [cubeb](https://github.com/kinetiknz/cubeb).

 - `libsoundio` does not support OpenSL ES (Android) and that's a problem but looks great.
 - `cubeb` supports audio but there is no documentation on the state of the library, it seems to be under development and not production ready.

**Comment by akosbalogh** [comment]
I'm making a docker file, for full support on Mac  (#370), using Ubuntu, @Martinfx could you manage to compile it without errors? Can you send be your setup? I'm getting the same errors, with both librarys (lglfw, lglfw3)

**Comment by Martinfx** [comment]
I built examples with lib  libglfw3-dev:amd64 (3.1.2-3) because i have less version library than need for build.
```
lol@m:~/raylib/examples$ make
gcc -o core/core_basic_window core/core_basic_window.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -fgnu89-inline -Wno-missing-braces -no-pie -D_DEFAULT_SOURCE -I. -I../release/include -I../src -I../src/external -L. -L../release/libs/linux -L../src  -lraylib -lglfw3 -lGL -lopenal -lm -lpthread -ldl -lX11 -lXrandr -lXinerama -lXi -lXxf86vm -lXcursor -DPLATFORM_DESKTOP
../release/libs/linux/libraylib.a(core.o): In function `ToggleFullscreen':
core.c:(.text+0x5a85): undefined reference to `glfwSetWindowMonitor'
core.c:(.text+0x5aba): undefined reference to `glfwSetWindowMonitor'
../release/libs/linux/libraylib.a(core.o): In function `SetWindowIcon':
core.c:(.text+0x5b15): undefined reference to `glfwSetWindowIcon'
../release/libs/linux/libraylib.a(core.o): In function `SetWindowMonitor':
core.c:(.text+0x5bc1): undefined reference to `glfwSetWindowMonitor'
../release/libs/linux/libraylib.a(core.o): In function `SetWindowMinSize':
core.c:(.text+0x5c46): undefined reference to `glfwSetWindowSizeLimits'
collect2: error: ld returned 1 exit status
Makefile:314: recipe for target 'core/core_basic_window' failed
```
make: *** [core/core_basic_window] Error 1

**Comment by akosbalogh** [comment]
I'm trying with debian, its package contains GLFW 3.2 but I get the same errors... 🤔 😕
