### ISSUE TITLE
[build] Conflicting “define” values

### ISSUE THREAD

**Issue by Oodini** [raysan5/raylib#3725]
### Issue description

raylib define A CMake variable named **PLATFORM**. This name is too generic, and may be in conflict with the client's CMakeLists.txt files.
I suggest to rename it **RAYLIB_PLATFORM**.

See https://discourse.cmake.org/t/conflicting-define-values/9825

**Comment by raysan5** [comment]
@Oodini I'm afraid that variable is used in all raylib build systems at the moment, changing it implies a lot of changes and and potential breaking build systems, no plans to change it for the moment.
