### ISSUE TITLE
[examples] Suggestion to add DOOM fire recreation example.

### ISSUE THREAD

**Issue by nart38** [raysan5/raylib#3726]
Recently, I recreated the DOOM fire effect and I would like to add it as an example. But before opening any PR I just wanted make sure you would want such example. If so please let me know and I will open a PR.

For context here is the original effect from doom:
<https://www.youtube.com/watch?v=YJB0gfP-GRY&t=10s>

Here is my code:
<https://github.com/nart38/raylib-playground/blob/main/doomfire.c>

And here is the result of this code:

![fire](https://github.com/raysan5/raylib/assets/33794024/26fa6a55-f4bf-426c-8256-2de805b23875)

**Comment by raysan5** [comment]
@nart38 Thanks for the offer, it looks great! But usually raylib examples try to showcase some of raylib's functionality; this examples seems more oriented to teach a specific fire-algorythm. 

Also note, the algorithm uses `DrawPixel()` that is very low-performant (drawing 1 quad per pixel), it would be nice if the same example used a shader instead...
