### ISSUE TITLE
[rtext] ExportFontAsCode() doesn't work without OpenGL context

### ISSUE THREAD

**Issue by Sot-Mits** [raysan5/raylib#3731]
- [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [X] My code has no errors or misuse of raylib

### Issue description

Whenever I try to export a font to code, the program I've written (attached below) segfaults if I don't do InitWindow() beforehand. Going into the functions with gdb I thikn this is because no OpenGL context has been initialised (sorry if that's the wrong terminology) and I would presume some bogus pointer accesses memory where it shouldn't.

### Environment

Debian 12.4 x86_64
OpenGL version 4.60
Mesa Intel(R) HD Graphics 520

### Code Example

```C
#include "raylib.h"
#include <stdio.h>

int main(int argc, char *argv[]) {
    // Check if a filename is provided as a command-line argument
    if (argc != 2) {
        printf("Usage: %s <filename>\n", argv[0]);
        return 1;
    }

    // Get the filename from the command-line argument
    const char *filename = argv[1]; // Use a pointer to the argument, not a single char
    const char *fontFilename = TextFormat("%s.ttf", filename);
    const char *headerFilename = TextFormat("%s.h", filename);

    // Load the font
    InitWindow(1, 1, "Font"); //Would not work without this line
    Font font = LoadFont(fontFilename);
    
    bool success = ExportFontAsCode(font, headerFilename);

    if (success) printf("Font exported successfully to %s\n", headerFilename);
    else printf("Error exporting font to %s\n", headerFilename);

    UnloadFont(font);

    return 0;
}
```

**Comment by raysan5** [comment]
@Sot-Mits @ubkp Yes, that's right and it is this way by design.
