### ISSUE TITLE
[build] Errors building on Visual Studio 2015

### ISSUE THREAD

**Issue by Phariax** [raysan5/raylib#374]
Hi guys, and sorry for my english.

I've downloaded raylib, and I would like to use it with Visual Studio 2015. I am newbie at programming, but I am learning for a while now. So my problem is, when I want to build the projects, I've got a bunch of errors. I suppose that errors occurs, because of two header files are missing, or cant read. This two are : Cannot open include file: 'AL/al.h': No such file or directory, and Cannot open include file: 'GLFW/glfw3.h': No such file or directory.

I've tried to going through the configure description (raylib/wiki/Create-Visual-Studio-Projectstep ) step by step. Sadly, without any success, the two errors still there. Can anybody help me?

When I am using notepad++ version, it is fine and cool. (unfortunately it has no stepping mode debugging feature, as far as I know.)

Thanks

Phar

**Comment by raysan5** [comment]
Have you tried the VS2015 solutions that come with raylib in folder `raylib/project/vs2015`?

**Comment by Phariax** [comment]
Thank you for faster, than light reply. :)

Yes, I did, and I tried it on my pc and on my laptop.

**Comment by raysan5** [comment]
It should be preconfigured to work... just checking it now.

**Comment by raysan5** [comment]
Ok, I see, try building in Release mode...

I got the same issue in Debug mode, don't know why... include paths are correctly defined but VS2015 does not find the headers... weird...

**Comment by raysan5** [comment]
ok... just found the issue... my fault, just configured paths for Release... >___<

**Comment by Phariax** [comment]
Yess, cool :) I mean you found the problem :)

**Comment by raysan5** [comment]
Issue corrected in commit https://github.com/raysan5/raylib/commit/ecf797cc7da985a6a4ebbd00b14b7056e582d714

**Comment by raysan5** [comment]
@Phariax could you try updating project include paths to point to `raylib/release/include` folder?

Just go to project **Properties** (right-mouse-click over project) and:

`Configuration Properties  >  C/C++  >  General  > Additional Include Directories`

There you have to set the correct include paths, be careful with selected **Configuration** to be **Debug**.

**Comment by Phariax** [comment]
I started to write another comment, but I'll do the change now, and I'll write soon.

**Comment by Phariax** [comment]
I made the changes.  Now the raylib project build is succeed (and the core_basic_window example as well), so that is ok. But now, If I want to run the basic window example, I'v got an error window "...it's not a valid win32 application." It is doesn't matter I am trying to run debug or release.  I have tried to rewrite the Additional include directories path both debug and release, but If I tried building in debug path, It is doesnt work, just like before...

I hope my english is clear enough to understand my comment.

**Comment by Phariax** [comment]
Ok, so I found the solution on the web. I had to set the project as a StartUp Project. After that I just restarted the Visual Studio and everything works fine. 

Thank you for your quick help,it is awesome,  and keep up the good work. 

Phar

**Comment by raysan5** [comment]
Glad to read you managed to get it working. Closing the issue.

**Comment by Kamelitoloveless** [comment]
Hi raysan5,
I stumble upon the same problem today with VS2019, why not set the project to be a StartUp Project when you release the file so it will not happens anymore? isn't it the right fix?
