### ISSUE TITLE
[rtext] `MeasureTextEx()` does not report correct height when using multi line string

### ISSUE THREAD

**Issue by karl-zylinski** [raysan5/raylib#3745]
### Issue description

When sending in a multi line string to `MeasureTextEx` it does not report the correct height. The text drawn by `DrawTextPro` will often be taller.

### Environment

Windows 10, GL3 (I guess), GTX 2080 Ti

### Issue Screenshot

Drawn multi line text with a dark background color, note that the dark background is less tall than the text:

![image](https://github.com/raysan5/raylib/assets/6352002/d7dcf3aa-86bc-4b55-a320-369ad4c50605)

### Code Example

```
Vector2 ts = MeasureTextEx(some_font, "hi\nho\nha", 20, 0)

text_r := Rectangle {
    0,0,
    ts.x,
    ts.y,
}

DrawRectangleRec(text_r, BLACK)
DrawTextPro(some_font, "hi\nho\nha", {0, 0}, {}, 0, 20, 0, WHITE)
```

I hand translated the code above from Odin to C, so I'm not sure it works out of the box. Also I use a custom font, I'm afraid I don't have time to setup test with non-custom font right.

**Comment by raysan5** [comment]
@karl-zylinski Excuse the late answer, I will try to review it asap. The line-break spacing support was added quite recently, are you using latest raylib version from GitHub master branch?

**Comment by raysan5** [comment]
@karl-zylinski This issue should be fixed with merged PR.
