### ISSUE TITLE
[rcore] VSync does not work on macOS

### ISSUE THREAD

**Issue by bossprocedure** [raysan5/raylib#3749]
### Issue description

VSync does not work on macOS.

This seems like an issue with GLFW (see [GLFW 2249](https://github.com/glfw/glfw/issues/2249) and [GLFW 2277](https://github.com/glfw/glfw/pull/2277)), relating to the removal of CVDisplayLink. Multiple hack-arounds can be found on their issue tracker, yet it seems that the overall effort has stalled.

The same issue was previously resolved in SDL and I have verified that the issue does not occur using SDL. (Any luck on SDL backend support on macOS? :)

Resorting to an uncapped frame rate (~3000 FPS) somewhat mitigates the issue, but there is still stutter about once a second and CPU melting.

### Environment

MacBook Air M1, macOS 14.2.1, Raylib 5.0.

### Issue Screenshot

N/A

### Code Example

Any of the official examples using animation.

**Comment by Peter0x44** [comment]
@bossprocedure are you saying you tried the raylib SDL backend support on Mac, or that you tried SDL2 on its own?
As far as I know, the SDL2 backend is supposed to work, you just need to provide SDL2 yourself.

**Comment by bossprocedure** [comment]
> @bossprocedure are you saying you tried the raylib SDL backend support on Mac, or that you tried SDL2 on its own? As far as I know, the SDL2 backend is supposed to work, you just need to provide SDL2 yourself.

I've tested on SDL2 (latest) independently of Raylib to verify that the issue was fixed in SDL.

The SDL backend for Raylib was only available for Linux last time I checked. Have tried to side-step `make` and hand-compile Raylib with SDL on macOS, but that resulted in an immediate crash.

**Comment by Peter0x44** [comment]
> The SDL backend for Raylib was only available for Linux last time I checked. 
Not true. It works on windows too, and probably Mac, since SDL is abstracting all those differences.
Maybe you were doing something wrong there.

**Comment by bossprocedure** [comment]
I'm basing the assumption on [this comment in rcore_desktop_sdl.c](https://github.com/raysan5/raylib/blob/ae50bfa2cc569c0f8d5bc4315d39db64005b1b08/src/platforms/rcore_desktop_sdl.c#L8) as well as getting stuck with make as follows:

```bash
src % mkdir -p ../src/external/SDL2
src % ln -s /opt/homebrew/include/SDL2 ../src/external/SDL2/include
src % make PLATFORM=DESKTOP_PLATFORM_SDL
gcc -c rcore.c -Wall -D_GNU_SOURCE -DDESKTOP_PLATFORM_SDL -D -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing  -std=c99 -I. 
In file included from <built-in>:419:
<command line>:3:9: error: macro name must be an identifier
#define -Wno-missing-braces 1
        ^
In file included from rcore.c:114:
./rlgl.h:3048:9: warning: variable 'mipOffset' set but not used [-Wunused-but-set-variable]
    int mipOffset = 0;          // Mipmap data offset, only used for tracelog
        ^
1 warning and 1 error generated.
make: *** [rcore.o] Error 1
```

Note that feeding it `PLATFORM=PLATFORM_DESKTOP_SDL" switches from `clang` (default compiler on macOS) to `gcc`, unlike running `make` without arguments. From what I could parse out of the Makefile, it did not appear to account for this setup properly. There will also be additional linker flags that need passing, but obviously not getting to that point in the build process.

**Comment by Peter0x44** [comment]
@bossprocedure how did you install SDL2? Is it through brew?

**Comment by bossprocedure** [comment]
> @bossprocedure how did you install SDL2? Is it through brew? Also the comment says "untested", not "unsupported". You can't test if you can't even compile.

Yes, through Homebrew. 

Of course, hence the side-note to enquire if this was on the menu or not. 

I'm happy to provide further information on SDL backend adventures on macOS if it's helpful to someone. Just let me know.

Either way the VSync issue persists with GLFW and it seems like there is little appetite to resolve the issue from what I can see on their tracker. :(

**Comment by Peter0x44** [comment]
@bossprocedure since you installed using brew, you can use pkg-config to find the raylib libs and headers
make the following changes to raylib's makefile:
```diff
-SDL_INCLUDE_PATH      ?= $(RAYLIB_SRC_PATH)/external/SDL2/include
-SDL_LIBRARY_PATH      ?= $(RAYLIB_SRC_PATH)/external/SDL2/lib
+SDL_INCLUDE_PATH      ?= $(shell pkg-config --cflags sdl2)
+SDL_LIBRARY_PATH      ?= $(shell pkg-config --libs sdl2)
-    INCLUDE_PATHS += -I$(SDL_INCLUDE_PATH)
+    INCLUDE_PATHS += $(SDL_INCLUDE_PATH)
-    LDFLAGS += -L$(SDL_LIBRARY_PATH)
+    LDFLAGS += $(SDL_LIBRARY_PATH)
```
Then build using `make` or `gmake`
you should then be able to build some code against it with:
`eval clang whatever.c -I path/to/raylib/src path/to/libraylib.a $(pkg-config --libs sdl2)`

**Comment by bossprocedure** [comment]
@Peter0x44 Thanks, that's useful. 

I've compiled and linked Raylib with SDL by hand previously. A simple test application using that crashed on startup and I backed out of my efforts at that point. Will give the above a spin to see if it makes a difference.

If there is appetite to get it working end-to-end on macOS, I'll assist with what I can. Should this be moved to a separate thread?

**Comment by raysan5** [comment]
It seems the original issue has changes or is not directly related to raylib but an underlying library.

**Comment by Peter0x44** [comment]
I think #3767 covers the issues with using SDL2 as a workaround

**Comment by 0xFFCarlo** [comment]
Still broken for me. It is a severe issue that vsync does not work on osx on the default backend. There is visible stutter on simple applications.
