### ISSUE TITLE
[text] Review LoadTTF() spritefont generation

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#375]
Right now using a basic font baking mechanism, no proper texture-packing just aligning characters one after the other, no sub-pixel oversampling for better font quality.

This function can be improved...

**Comment by raysan5** [comment]
Just for record, I've been working on this issue (along with SDF font generation) for some time now.

Current `LoadTTF()` implementation uses `stbtt_BakeFontBitmap()` from `stb_truetype` library. That function packs characters in an image, one after another. After that, texture is loaded from image and `font.chars` info data is filled. `LoadTTF()` is not versatile at all, neither optimum in packing terms, I needed something better.

After some time working in an improved implementation for **image font atlas generation**, I came to different approximations:

1. Generate Image font atlas but also fill `CharInfo *chars;` data in a single function (instead of just returning an *opaque* `Font` structure:
```c
Image GenImageFont(const char *fileName, int fontSize, int *fontChars, CharInfo *chars, int charsCount);
```
This method give us an `Image` font atlas and the `CharInfo` data separately that later can be used to fill `Font` data. It works ok but `Font` loading is a bit cumbersome and counter-intuitive:
```c
Font font = { 0 };
font.baseSize = 36;
font.charsCount = 96;
font.chars = (CharInfo *)malloc(font.charsCount*sizeof(CharInfo));
Image atlas = GenImageFont("fonts/Inconsolata.ttf", font.baseSize, NULL, font.chars, font.charsCount);
font.texture = LoadTextureFromImage(atlas);
```

2. Generate `CharInfo *chars` data from TTF file, store every character pixel data in a first pass (requires `CharInfo.data` added to `CharInfo` struct) . After that, use that data to generate the image font atlas:
```c
CharInfo *LoadFontData(const char *fileName, int fontSize, int *fontChars, int charsCount, bool sdf);
Image GenImageFontAtlas(CharInfo *chars, int charsCount, int fontSize, int packMethod);
```
I think those methods are more intuitive and give us more control over the full system, including packing mechanism inside `GenImageFontAtlas()`. `Font` loading is a bit more intuitive:
```c
Font font = { 0 };
font.baseSize = 36;
font.charsCount = 96;
font.chars = LoadFontData("fonts/Inconsolata.ttf", font.baseSize, NULL, font.charsCount, false);
Image atlas = GenImageFontAtlas(font.chars, font.charsCount, font.baseSize, 0);
font.texture = LoadTextureFromImage(atlas);
```
I keep thinking on this API improvement, really need a versatile and intuitive system for future related projects. Comments are welcome!

**Comment by raysan5** [comment]
Improvements implemented in commit https://github.com/raysan5/raylib/commit/75ba5aca551d2b16fa75ba31e616b009ac5dde6a

Still some things to review:
- SDF generation chars padding
- Image font packaging chars padding

**Comment by raysan5** [comment]
Reviewed on commit https://github.com/raysan5/raylib/commit/0e135118fd0edd3ef613cb28cb573d12916dca98.

For now I consider this implementation complete... only SDF example left. Working on it.

**Comment by iva0410217** [comment]
#401 .

**Comment by raysan5** [comment]
@iva0410217 why this issue is linked to 401?
