### ISSUE TITLE
[rcore] GetScreenWidth() and GetScreenHeight() do not return current values

### ISSUE THREAD

**Issue by Sqvid** [raysan5/raylib#3763]
Please, before submitting a new issue verify and check:

 - [X ] I tested it on latest raylib version from master branch
 - [X ] I checked there is no similar issue already reported
 - [ X] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [ ?] My code has no errors or misuse of raylib

### Issue description

From my understanding of the function descriptions in the raylib cheatsheet, I would assume GetScreenWidth() and similar functions would return up-to-date values for the window. However, it seems the values returned are those the window was initialised with in InitWindow().

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*
Platform: Desktop, Linux 6.6.11, OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.2, AMD Ryzen 7 7840HS w/ Radeon 780M Graphics

### Code Example

```C
#include <stdio.h>

#include "raylib.h"

int main(void) {
	SetTraceLogLevel(LOG_WARNING);

	InitWindow(10, 10, "Test");
	SetWindowSize(400, 400);

	printf("ScreenWidth: %d, ScreenHeight: %d\n", GetScreenWidth(), GetScreenHeight());
	printf("RenderWidth: %d, RenderHeight: %d\n", GetRenderWidth(), GetRenderHeight());

	CloseWindow();
	return 0;
}
```

output:

```
WARNING: GLFW: Error: 65539 Description: Invalid window hint 0x0002000D
ScreenWidth: 10, ScreenHeight: 10
RenderWidth: 10, RenderHeight: 10
```

**Comment by Sqvid** [comment]
I want to add that ```SetWindowState(FLAG_WINDOW_RESIZABLE);``` did not change the output. I verified that the flag was set correctly with ```IsWindowState(FLAG_WINDOW_RESIZABLE);```.

**Comment by raysan5** [comment]
@Sqvid I tested the example on Windows and it works as expected:

![image](https://github.com/raysan5/raylib/assets/5766837/60c77d33-2238-44e9-a41b-f7cfdc46aaed)

Looking at this line:

 > WARNING: GLFW: Error: 65539 Description: Invalid window hint 0x0002000D

It seems the issue is not directly related to raylib but [GLFW library](https://github.com/glfw/glfw) and the windowing system of your OS Linux 6.6.11. There is not much that can be done on raylib side, it should be reported to [GLFW](https://github.com/glfw/glfw).

**Comment by Sqvid** [comment]
Thank you for taking the time to look at my issue. I just  want to point out that this seems to effect Linux users across distros, using both Wayland and X11 (see #3764). If it is a glfw bug would you mind advising on how GLFW can be bypassed in favour of SDL? Thank you so much for your time, and this library.
