### ISSUE TITLE
Microscopic issue in comment causes tons of warnings when auto-generating docs in raylib-d

### ISSUE THREAD

**Issue by cdcrchrisparker** [raysan5/raylib#3765]
This is dumb, and doesn't really fit the template.  I discovered this while using raylib-d with the document generator.  E.g.:

dub build --build=docs

The issue?  A missing right paren on line 75 of rlgl.h

  #define RL_DEFAULT_SHADER_UNIFORM_NAME_NORMAL      "matNormal"         // normal matrix (transpose(inverse(matModelView))**)**

**Comment by raysan5** [comment]
@cdcrchrisparker Wow! What an issue! Reviewed!

**Comment by cdcrchrisparker** [comment]
If you happen to run the D Language document generator across the raylib-d, that missing paren caused hundreds of scary warnings, all for something inside a comment.  I know that was dumb - but at least it was an easy fix.  Thank you!
