### ISSUE TITLE
[rcore] Small issues on MacOS with SDL2

### ISSUE THREAD

**Issue by atticus5** [raysan5/raylib#3767]
### Issue description

When building raylib with SDL2 as backend I faced 2 issues:

1. The `InitPlatform()` method calls `SDL_Init(SDL_INIT_EVERYTHING)` which results in some SDL2 fatal [exceptions](https://stackoverflow.com/questions/58983341/addinstanceforfactory-halc-shelldriverplugin-errors-when-using-sdl2-with-xcode), which I cannot reproduce now, but I found that `SDL_Init(SDL_INIT_VIDEO)` works fine. I found something on the internet that the `SDL_INIT_AUDIO` is the issue, a subsystem which is included by `SDL_INIT_EVERYTHING`, but not actually needed for raylib.
2. Another error I caught was `Failed creating OpenGL context at version requested` because on Apple if you are using OpenGL 3.3 the `SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE)` is not called, even though for OpenGL 4.3 it is.
3. There is no automatic way of building with SDL2? The `PLATFORM` variable only supports `Desktop` which defaults to `GLFW`.

### Environment

MacOS Sonoma 14.1.1 M1,  OpenGL 3.3

**Comment by atticus5** [comment]
2. Is certainly a bug, in `GLFW` implementation, `rcore_desktop.c`, the call is not missing.

**Comment by raysan5** [comment]
@atticus5 Thanks for reporting! It has been reviewed 1. and 2. but about 3., `Makefile` supports PLATFORM=PLATFORM_DESKTOP_SDK.

**Comment by atticus5** [comment]
@raysan5 thank you, but I'm using CMake and GLFW is hardcoded:

https://github.com/raysan5/raylib/blob/7ec43022c177cbf00b27c9e9ab067bd6889957a4/cmake/LibraryConfigurations.cmake#L11

**Comment by raysan5** [comment]
@atticus5 Oh, I'm afraid I'm not the user neither maintainer of CMake build system. It was contributed by the community and I kept it for convenience but any expert on CMake should review and maintain it.
