### ISSUE TITLE
[graphics] Instancing online demo not working

### ISSUE THREAD

**Issue by RonenNess** [raysan5/raylib#3768]
### Issue description

The online instancing rendering demo doesn't work. Show blank scene.
Looks like its because the shaders are broken:
![image](https://github.com/raysan5/raylib/assets/3426999/c3223d95-3a3b-48a1-b9d0-a45b0133066f)

### Environment

Web example with Chrome / windows.

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/3426999/ea748403-097d-4c46-a84f-5ec429504f55)

### Code Example

The code from the demo:

[*Provide minimal reproduction code to test the issue. Please, format the code properly and try to keep it as simple as possible, just focusing on the experienced issue.*
](https://www.raylib.com/examples/shaders/loader.html?name=shaders_mesh_instancing)

**Comment by raysan5** [comment]
@RonenNess this is a known issue. Actually, if you try compiling and running it in a local server it should work as expected.
