### ISSUE TITLE
[textures] Support texture flip on X-Y

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#378]
One user asked for that feature, to support in an easy way texture flipping on X and Y... not sure how to implement it on easy way, probably `DrawTexture*()` functions should also be reviewed...

Right now it can be done with:
```c
// NOTE: Render texture y-flipped
DrawTextureRec(texture, (Rectangle){ 0, 0, texture.width, -texture.height }, (Vector2){ 0, 0 }, WHITE);
```
But this solution implements a nasty internal hack to make it simple for the user...

One possible solution was defining:
```c
Rectangle RectangleFlipX(Rectangle rec);    // Return a flipped-x rectangle
Rectangle RectangleFlipY(Rectangle rec);    // Return a flipped-y rectangle
```
But it seems to even complicate more the drawing than above option...

Another solution was adding more parameters to `DrawTexture*()` functions, but also makes everything more complex just for a side case usage... most user won't need to flip their textures...

Thinking about it.

**Comment by BlueRaccoon** [comment]
Perhaps a more general-purpose version of the "RectangleFlipX" definition might be something like:
```
Rectangle RectangleScale(Rectangle rec, float xscale, float yscale) { 
    return (Rectangle){rec.x, rec.y, rec.w*xscale, rec.h*yscale};
 }
```
It doesn't make the sprite-flipping process dramatically more simple, but it is a decent general-purpose rect-handling function. When I'm working with a spritesheet, it makes my sprite drawing function look something like this:
```
void DrawSprite( Vector2 pos, Rectangle spriteRec, bool flipx, bool flipy, Texture2D spriteAtlas) {
    DrawTextureRec(spriteAtlas, RectangleScale( spriteRec, flipx==true?-1:1, flipy==true?-1,1 ), pos, WHITE );
}
```
Dunno if that's helpful, but I do feel like (with DrawTextureRec and DrawTexturePro as the intended way to handle sprite animation) that most games will at some point require flipping a texture rectangle to mirror a sprite.

**Comment by SuicidalMK** [comment]
I'd prefer giving the Rectangle type two bools "FlipH" and "FlipV"

**Comment by raysan5** [comment]
For the moment I'll leave it as it is. None of the solutions fully convice me...

**Comment by heuripedes** [comment]
Suggestion:

Interpret negative size as a flip:

    // Draw normally
    DrawTexturePro(tex, sourceRect, destRect, origin, rotation, color);
    
    // Draw vertically and horizontally flipped
    destRect.width = -destRect.width;
    destRect.height = -destRect.height;
    DrawTexturePro(tex, sourceRect, destRect, origin, rotation, color);

**Comment by hbiblia** [comment]
Yo utilizo 2 variables flipH, flipV

```
width: this.width * clampNoZero(this.flipH, -1, 1),
height: this.height * clampNoZero(this.flipV, -1, 1)
```
