### ISSUE TITLE
[rmodels] [rlgl] `DrawMeshInstanced` does not work with default material/shader

### ISSUE THREAD

**Issue by Vlad-Zumer** [raysan5/raylib#3785]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Using the default material with `DrawMeshInstanced` causes all other draws (instanced or not) of that mesh to not show up.
Making a new mesh and drawing it (not instanced) with the same material will work.

### Environment

This would be a problem for all environments.

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/21068598/a8c18d1d-9ae1-4e1e-b3df-7db8e67838e3)

### Code Example

In the `examples\shaders\shaders_mesh_instancing.c` file, comment out line 88 (see below) to force the instances to use the default shader/material. 

```c
matInstances.shader = shader;
```
![image](https://github.com/raysan5/raylib/assets/21068598/6765388d-8a5b-4247-ba12-5dc6a83c558a)

### Possible solutions

This can be solved by either updating the default shader to use the `SHADER_LOC_MATRIX_MODEL` as well, or compute the transformations and send results in the `SHADER_LOC_VERTEX_POSITION`. Let me know which one you like more.

**Comment by raysan5** [comment]
@Vlad-Zumer I'm afraid this is the expected behaviour, the default shader is not intended for mesh instancing, a custom shader is required. Most users won't benefit from adding that extra data to default shader.

**Comment by Vlad-Zumer** [comment]
Can you add the bit about being expected behaviour to the FAQ please, as I'm sure I'm not the only one that has encountered this.
Also would you be ok with adding `LoadMaterialDefaultInstanced` API for a default instanced material. If so I will make a PR later on today.

**Comment by raysan5** [comment]
@Vlad-Zumer feel free to add the information to the FAQ, the Wiki is open for editing.

`LoadMaterialDefaultInstanced()` would require another internal specific shader and I prefer to avoid it, the example should cover that use case for users requiring it.
