### ISSUE TITLE
[rcore] `LoadRandomSequence()` doesn't work correctly

### ISSUE THREAD

**Issue by hdvpdrm** [raysan5/raylib#3794]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description
Function works fine, but it also generates values out of boundaries. I need to generate values between 0 and some positive value, but i suddenly got something like -28.

So i check if array pointer isn't NULL, then i just print first element and it's negative.

### Code Example
int* random_cells_ids = LoadRandomSequence(amount, 0, free_cells_size-1);
 if(random_cells_ids == NULL) return -1;

printf("%d",random_cells_ids[0]);

**Comment by raysan5** [comment]
@hdvpdrm I can't reproduce the issue. Are you calling `LoadRandomSequence()` after `InitWindow()`? `InitWindow()` setups the random seed, if not, you should call manually `SetRandomSeed()` before calling this function.

Also, make sure you are using latest raylib version from GitHub master branch, there was an issue with it on `raylib 5.0` release.

**Comment by hdvpdrm** [comment]
I use ```LoadRandomSequence()``` after ```InitWindow()```, yes. Also i set seed with time(NULL). And i use latest version. 5.0-1

**Comment by raysan5** [comment]
@hdvpdrm I'm afraid I can't reproduce. Please, could you provide a complete code sample using some fixed seed value that generates this issue?

**Comment by hdvpdrm** [comment]
That's the whole code. I don't think it's good idea to use some fixed seed, because it produces unique sequence and also it can produce sequence that contains 2 equal elements at least. I don't know anything about implementation, so i can't figure out what's the problem. I think i can use standard way. 
```
int generate_random_objects(int amount,Vector* robot_pos)
{
  Vector* free_cells = NULL;
  int free_cells_size = 0;
  if(compute_free_cells(&free_cells,&free_cells_size,robot_pos) == 0)
    {
      int* random_cells_ids = LoadRandomSequence(amount, 0, free_cells_size-1);
      if(random_cells_ids == NULL) return -1;

      int kitten_id = GetRandomValue(0,amount-1);
      for(int i = 0;i<amount;++i)
	{
	  int index = random_cells_ids[i];
	  if(index < 0) index*=-1;
	  int x = free_cells[index].x;
	  int y = free_cells[index].y;
	 
	  int rnd_ch_pos = GetRandomValue(0,CHARS_LEN-1);
	  map[y][x] = (int)_CHARS[rnd_ch_pos];
	  
	  if(kitten_id == i)
	    {
	      kitten_pos.x = x;
	      kitten_pos.y = y;
	      printf("kitten pos is: %d %d\n",x,y);
	    }
	}
      
      free(free_cells);
      UnloadRandomSequence(random_cells_ids);
      return 0;
    }
  free(free_cells);
  return -1;
}
```

**Comment by raysan5** [comment]
@hdvpdrm Sorry, but I can't reproduce the ussue for review with that code.

Please, could you provide a complete, short full example reproducing the issue? Please, understand that without it I can't do much to help.

**Comment by hdvpdrm** [comment]
Nevermind. I better write my own random generation based on std. 
Something like int((double(rand())/RAND_MAX)*n);
