### ISSUE TITLE
[rtextures] Failed to load image data

### ISSUE THREAD

**Issue by ahmedjacop68** [raysan5/raylib#3796]
I don't know what I'm doing wrong
**ERROR:**
INFO: FILEIO: [resources/bg.png] File loaded successfully
WARNING: IMAGE: Failed to load image data
**CODE:**
#include "raylib.h"
int main(void)
{
    InitWindow(800, 450, "Enter a Code");
    InitAudioDevice();

    Texture2D bg = LoadTexture("resources/bg.png");

    while (!WindowShouldClose())
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawTexture(bg, 0, 0, WHITE);
        EndDrawing();
    }
    UnloadTexture(bg);

    CloseWindow();

    return 0;
}

Pls help!

**Comment by raysan5** [comment]
@ahmedjacop68 Are you sure the `bg.png` file is actually a PNG image file? It could be somehow corrupted. In any case, this issue would be related to some of the underlying image loading libraries.

Please, could you attach the `bg.png` image for review?

**Comment by raysan5** [comment]
@ahmedjacop68 I'm afraid this image is not a PNG file but a renamed JPEG file.

**Comment by LilyHiragashi** [comment]
This absolutely saved me for what I'm working on, thanks for asking the question!

**Comment by ahmedjacop68** [comment]
2 years later huh LilyHiragashi......
