### ISSUE TITLE
[rxtextures] getting failed to load file when load textures

### ISSUE THREAD

**Issue by cofeek-codes** [raysan5/raylib#3801]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description
Getting `WARNING: FILEIO: Failed to open file index.js:1503:16
`
when loading texture
### Environment
[platform info](https://github.com/cofeek-codes/survivalist-web/blob/main/issue/platform.png)
### Issue Screenshot
[issue screenshot](https://github.com/cofeek-codes/survivalist-web/blob/main/issue/issue.png)
### Code Example

```c
#include <raylib.h>

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

int main() {
  // init
  InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "surviavalist");
  SetTargetFPS(60);

  // background
  Texture2D background1 = LoadTexture("assets/background/background_1.png");
  // background

  // init

  // game loop

  while (!WindowShouldClose()) {
    // update

    // update

    // draw
    BeginDrawing();
    DrawTexture(background1, 0, 0, WHITE);
    EndDrawing();
    // draw
  }

  // game loop

  // deinit
  UnloadTexture(background1);
  // deinit
  CloseWindow();

  return 0;
}
```

# Buld Script

```sh
#!/bin/bash

set -xe

mkdir -p build
cp -r -v --update src/assets/ build/
emcc -Wall -Wextra src/main.c -o build/index.html -I./lib/include -L./lib/lib -lraylib -lm -s USE_GLFW=3 -s ASYNCIFY --shell-file ./template/template.html 
```

# File Structure 

```
./
├── build.sh
├── issue
│   ├── issue.md
│   ├── issue.png
│   └── platform.png
├── lib
│   ├── include
│   │   ├── raylib.h
│   │   ├── raymath.h
│   │   └── rlgl.h
│   └── lib
│       └── libraylib.a
├── src
│   ├── assets
│   │   └── background
│   │       └── background_1.png
│   └── main.c
└── template
    └── template.html

Directories: 8, Files: 11, Symbolic Links: 0, Lines: 0

```

**Comment by raysan5** [comment]
When building for web with emscripten, you need to provide the assets that need to be embedded and available to the resulting output. You need to add to compile line: `--preload-file assets`:
```
emcc -Wall -Wextra src/main.c -o build/index.html -I./lib/include -L./lib/lib -lraylib -lm -s USE_GLFW=3 -s ASYNCIFY --shell-file ./template/template.html --preload-file assets
```

**Comment by cofeek-codes** [comment]
i did this (compile line now is `emcc -Wall -Wextra src/main.c -o build/index.html -I./lib/include -L./lib/lib -lraylib -lm -s USE_GLFW=3 -s ASYNCIFY --shell-file ./template/template.html --preload-file build/assets/
`) but the issue still persists

**Comment by raysan5** [comment]
@cofeek-codes The provided assets path is how it will be mapped internally for loading, in your case it should be remapped: `--preload-file build/assets@assets`

Also verify a `.data` file has been generated containing the assets (it should be exactly same size than assets directory).

**Comment by cofeek-codes** [comment]
updating build file with `--preload-file build/assets@assets` fixed the issue
