### ISSUE TITLE
[rtextures] Texture mode flips the Y axis by default

### ISSUE THREAD

**Issue by nawarian** [raysan5/raylib#3803]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [?] My code has no errors or misuse of raylib

### Issue description

Whenever I render my scene in texture mode and attempt to plot it using `DrawTexture()` the Y axis is flipped.

I was able to walk around the issue by using `DrawTexturePro()` with a negative height as described in #378 , but this seems to be a bug nonetheless and should be reported.

Thanks for the great work! I love raylib! <3

### Environment

I'm running a Ubuntu Linux 22.04.3 LTS 64-bit
Lib GLFW 3.3.6-1
Windowing system Wayland
Grpahics card Mesa Intel Xe Graphics (TGL GT2)

### Issue Screenshot

[Screencast from 19.02.2024 11:35:28.webm](https://github.com/raysan5/raylib/assets/3905582/7e82d89b-e498-4cfe-ba59-3fd5e362144b)

### Code Example

The code below switches to Texture mode upon pressing the `TAB` key

```
#include <raylib.h>

#define SWIDTH  800
#define SHEIGHT 600

void DrawStuff(void)
{
  ClearBackground(BLACK);
  DrawFPS(0, 0);

  DrawLine(100, 100, 200, 200, RED);
}

RenderTexture2D buff;
int main(void)
{
  InitWindow(SWIDTH, SHEIGHT, "BUG - Y Axis is flipped on texture mode");
  SetTargetFPS(120);

  buff = LoadRenderTexture(SWIDTH, SHEIGHT);
  while (!IsRenderTextureReady(buff));

  int enable_texture_mode = 0;
  while (!WindowShouldClose()) {
    if (IsKeyPressed(KEY_TAB)) {
      enable_texture_mode = !enable_texture_mode;
    }

    BeginDrawing();
      if (enable_texture_mode) {
        BeginTextureMode(buff);
          DrawStuff();
        EndTextureMode();

        DrawTexture(buff.texture, 0, 0, WHITE);
      } else {
        DrawStuff();
      }
    EndDrawing();
  }

  CloseWindow();
}
```

**Comment by raysan5** [comment]
@nawarian I'm afraid this is as-design. Changing that behaviour could be extremely difficult and annoying.

**Comment by brccabral** [comment]
My workaround was to create another render, I named **inverted**, and drawing all of `buff` into `inverted`, then, drawing the `inverted` in the main loop.

```c
#include <raylib.h>

#define SWIDTH 800
#define SHEIGHT 600

void DrawStuff(void)
{
    ClearBackground(BLACK);
    DrawFPS(0, 0);

    DrawLine(100, 100, 200, 200, RED);
}

RenderTexture2D buff;
RenderTexture2D inverted;
int main(void)
{
    InitWindow(SWIDTH, SHEIGHT, "BUG - Y Axis is flipped on texture mode");
    SetTargetFPS(120);

    buff = LoadRenderTexture(SWIDTH, SHEIGHT);
    while (!IsRenderTextureReady(buff))
        ;

    inverted = LoadRenderTexture(SWIDTH, SHEIGHT);
    while (!IsRenderTextureReady(inverted))
        ;

    int enable_texture_mode = 0;
    while (!WindowShouldClose())
    {
        if (IsKeyPressed(KEY_TAB))
        {
            enable_texture_mode = !enable_texture_mode;
        }

        BeginDrawing();
        if (enable_texture_mode)
        {
            BeginTextureMode(buff);
            DrawStuff();
            EndTextureMode();

            // draw all of buff into inverted will invert in the DrawTexture()
            BeginTextureMode(inverted);
            DrawTextureRec(buff.texture, {0, 0, SWIDTH, SHEIGHT}, {0, 0}, WHITE);
            EndTextureMode();

            // draw the inverted render
            DrawTexture(inverted.texture, 0, 0, WHITE);
        }
        else
        {
            DrawStuff();
        }
        DrawText(TextFormat("%b", enable_texture_mode), 100, 0, 20, GREEN);
        EndDrawing();
    }

    CloseWindow();
}
```

**Comment by SleepingNerd** [comment]
It's more efficient to just flip the rendered texture with  DrawTextureRec or DrawTexturePro by passing the source with a negative height or width (in this case height).

Example: DrawTextureRec(source_texture, (Rectangle){.x = 0, .y = 0, .width = screenWidth, .height = -screenHeight}, (Vector2){.x = 0, .y=0}, WHITE)
