### ISSUE TITLE
[rmodels] Blockbench's GLB/GLTF joint attribute data format not supported

### ISSUE THREAD

**Issue by MrScautHD** [raysan5/raylib#3807]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description
Hello!

Several users and I have noticed that Raylib does not support the data format exported by [Blockbench](https://www.blockbench.net/) for models. We would greatly appreciate it if support for this format could be added, as Blockbench is one of the most widely used model editors.

### Environment
Platform: Desktop (Windows 11)
OpenGL: 3.3.0
GPU: GTX 1080

### Issue Screenshot
![grafik](https://github.com/raysan5/raylib/assets/65916181/0b2d39b3-19a1-4843-9740-e08899096f73)
![grafik](https://github.com/raysan5/raylib/assets/65916181/fd8c4d4e-70c2-47dc-b622-2a41d316d00b)

**Comment by raysan5** [comment]
Issue seems related to https://github.com/raysan5/raylib/issues/3836
