### ISSUE TITLE
[rcore] GetFrameTime() Returns Large Time Spike On Second Frame After Input - MacOS

### ISSUE THREAD

**Issue by jalder89** [raysan5/raylib#3808]
## Issue Description
Calling GetFrameTime() after pressing an input for the first time results in a large frame time spike of ~300x-600x normal. 

During the main loop, I check for IsKeyDown(KEY_A) and print the frame time. The second frame after launching the build and pressing the input for the first time is always extremely high. This always occurs on the second frame after the input key is pressed for the first time. A future key press does not result in a time spike when triggered by an input.

### Issue Screenshot

<img width="422" alt="Screenshot 2024-02-20 at 11 02 41 PM" src="https://github.com/raysan5/raylib/assets/8131741/3275acc8-2a7b-4b32-ad20-4d86de1e5526">
<br>

### Use Case

I'm trying to setup deltaTime for working with object movements but the odd frame time spike is causing the object to appear to move instantly for a split second when the frame time spikes. 

I've removed all extra code except a View class I made to handle sizing the window. This code isn't called or accessed after the window is initialized. I simply initialize the window to a scaled view size and then start my main loop. The issue is always reproducible by checking for a key is pressed and then printing the frame time.

### Environment

MacOS 14.2.1 (23C71)
M3 Max - Metal 3
Raylib 5.0 - built from `raylib-master`

OpenGL extensions loaded successfully:
Supported extensions count: 43
OpenGL device information:
Vendor:   Apple
Renderer: Apple M3 Max
Version:  4.1 Metal - 88
GLSL:     4.10

<img width="574" alt="Screenshot 2024-02-20 at 11 12 19 PM" src="https://github.com/raysan5/raylib/assets/8131741/13b70300-0079-402e-bf3d-f28bfa270764">

### Code Example

Repo (src/main.cpp): https://github.com/jalder89/raylib-macos-template-arm-cpp/tree/frame-bug

```
#include <iostream>
#include <raylib.h>
#include <raymath.h>
#include "view.h"

int main()
{
    // Initial window viewport setup. Check View for scaling
    View Viewport;                          
    InitWindow(Viewport.Width, Viewport.Height, "A New Window");

    float deltaTime = 0.f;

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(RAYWHITE);

        deltaTime = GetFrameTime();

        if(IsKeyDown(KEY_A))
        {
            if(deltaTime > 0.002)
            {
                std::cout << "Frame Time Spike: " << deltaTime << std::endl;
            } else 
            {
                std::cout << "Frame Time: " << deltaTime << std::endl;
            }
        }

        EndDrawing();
    }
    
    CloseWindow();
    return 0;
}
```

**Comment by jalder89** [comment]
> The issue looks similar to one reported on #469. Check these comments: [#469 (comment)](https://github.com/raysan5/raylib/issues/469#issuecomment-1837568010) and [#469 (comment)](https://github.com/raysan5/raylib/issues/469#issuecomment-1879368677).

Thank you! I didn't see these in my initial search, but aased on this, I'm guessing it is somehow related to how the debugger hooks into the application and how GetFrameTime() tracks the delta between frames. People report that it only happens when debugging but not when running the build directly.

What is even weirder is that it only appears to be happening with GetFrameTime()

If I used SetTargetFPS and avoid fetching the frame time, the hitching goes away. So it must be something odd in the way the debugger and the GetFrameTime() implementation are interacting on MacOS, but I don't know nearly enough about the GetFrameTime implementation to understand how.

For simple 2D games, SetTargetFPS is probably an acceptable solution for debugging, but it ties game physics to the frame rate so not sure how well it would work on larger projects. 

Unfortunately, most comments I see regarding Mac issues equate to Mac basically being unsupported due to lack of resources. Understandable, I wish I had more of my own resources to provide.

**Comment by raysan5** [comment]
@jalder89 I'm afraid this issue could be related to system libraries or the underlying GLFW library, I can't do much to address it on raylib side.

**Comment by jalder89** [comment]
> @jalder89 I'm afraid this issue could be related to system libraries or the underlying GLFW library, I can't do much to address it on raylib side.

Would that only impact GetFrameTime() though? 

It seems odd that SetTargetFPS() works perfectly fine but GetFrameTime has a hitch. I would expect a lower level problem to impact all rendering, or am I mistaken?
