### ISSUE TITLE
[rlgl] Load one custom shader and one default shader in LoadShader()

### ISSUE THREAD

**Issue by nounoursheureux** [raysan5/raylib#381]
The title is not very clear, but what I'd like to be able to do is to call `LoadShader` with one NULL pointer and one valid path, and have it load the default shader for the NULL argument and load the shader at the given path.
An example: say I want to write a custom fragment shader but keep the default vertex shader, I could just write `LoadShader(NULL, "custom.fs")` and have it return a shader program that has the default vertex shader and my custom fragment shader.
Right now AFAIK I have to copy the default vertex shader and load it myself, it isn't a major annoyance but I think this can be improved :)
If you are okay with this proposition I think I can implement it myself and submit a PR.

**Comment by raysan5** [comment]
Shaders are usually loaded in pairs but supporting a default vertex/fragment shader could be considered... 

Checking the code is not a simple implementation because default vertex and fragment shaders are loaded in an isolated way to be linked in shader program and immediately deleted... Supporting that feature would require some modifications on several functions...

How would you do that? I think keeping the default VS/FS compiled ids is the way to go, just re-link in new program the already compiled default shaders in case of NULL.

**Comment by nounoursheureux** [comment]
Yup, since `LoadShaderProgram` deletes the shaders after loading I can only think of two options:
- don't use `LoadShaderProgram` in `LoadShaderDefault`, duplicate the code instead and just save the shaders instead of freeing them. Not very pretty, adds code duplication.
- just load the default shaders from source every time instead of saving the compiled ids. It is a bit wasteful, but not more than the current solution which is to copy the default shader into a file and load it.
I think the second option is reasonable even if not fully optimal. There is also a third option which is to reject this feature if you think it's too much of a hassle :)

**Comment by raysan5** [comment]
Thinking about two other options:

 - Creating new function to `LoadShaderPartial()` for vertex/fragment shader loading to also avoid duplicate code inside `LoadShaderProgram()`; modifying `LoadShaderProgram()` to recive already compiled vertex/fragment shaders ids. Review default shader loading from that point.

 - Just store vertex/fragment shader ids inside Shader struct.

**Comment by raysan5** [comment]
Thanks @nounoursheureux for the PR, I'll review some naming before closing this issue.

**Comment by raysan5** [comment]
Reviewed on commit https://github.com/raysan5/raylib/commit/09228752ce2695baf79cbc2edccc60fabb38f783
