### ISSUE TITLE
[core] Gamepad rumble with SDL2

### ISSUE THREAD

**Issue by GideonSerf** [raysan5/raylib#3815]
Could I add a method to support gamepad rumble? I saw issue https://github.com/raysan5/raylib/issues/3122, and while it's still not possible to add rumble support using GLFW, it would be possible to add it for SDL2 via https://wiki.libsdl.org/SDL2/SDL_JoystickRumble. 

The following function prototype could be used:
`void SetGamepadVibration(int gamepad, float leftMotor, float rightMotor, float durationMs)`.  With leftMotor and rightMotor being values between 0.0 and 1.0 and durationMs being a duration in milliseconds. When this function is called on a platform that doesn't support this function, `TRACELOG(LOG_WARNING, "GamepadSetVibration() not available on target platform");` could be called. I think as more platforms are added in the future, this could be a useful function to have.

**Comment by raysan5** [comment]
@GideonSerf Yes! That could be a good addition. But... if time is provided I imagine it would require some global variables to track time, if possible I'd keep it as `SetGamepadVibration(int gamepad, float leftMotor, float rightMotor)` letting the user to manage time and reset the vibration with `SetGamepadVibration(0, 0.0f, 0.0f)`.

**Comment by GideonSerf** [comment]
No I don't think it's an OS API. SDL seems to use a countdown timer to manage when the command to stop the rumble should be sent, as well as sending the rumble command periodically while it should be ongoing. Unfortunately SDL doesn't make it possible to call the function without a duration, but when you call SDL_JoystickRumble with the same vibration values it currently has, it just resets the countdown timer. So perhaps the rumble values can be stored in the Gamepad struct and then resent in PollInputEvents until both values are set to 0?

**Comment by raysan5** [comment]
> So perhaps the rumble values can be stored in the Gamepad struct and then resent in PollInputEvents until both values are set to 0?

I prefer to avoid that route and let the full time control to the user. If I understand correctly, calling `SDL_JoystickRumble()` twice with a `0` duration it just stops the rumble, right?

So, raylib can just define a `MAX_GAMEPAD_VIBRATION_TIME        2.0f     // Time in seconds` and let the user manage other timming by themselfs with:
```c
SetGamepadVibration(0, 0.5f, 0.5f);  // Start vibration

// User manages desired vibration time
timeCounter += GetFrameTime();

if (timeCounter >= vibrationTime) SetGamepadVibration(0, 0.0f, 0.0f);  // Stop vibration (it also stops automatically after `MAX_GAMEPAD_VIBRATION_TIME`)
```

So there is no need for raylib to manage it internally but still stops in case user forgets to stop it.
