### ISSUE TITLE
[build] [examples] `raylib_opengl_interop` linking issue on Windows

### ISSUE THREAD

**Issue by Pan-Shin-Z** [raysan5/raylib#3818]
### Issue description

Use Cmake to generate NMake makefiles to build shared library, and link error appeared when building.

### Environment

* Platform: desktop
* OS: windows 11 23H2
* OpenGL: version 3.3
* Under Visual Studio 2022 Developer PowerShell v17.9.1

### Issue Screenshot

![螢幕擷取畫面 2024-02-24 151834](https://github.com/raysan5/raylib/assets/118543966/cc0b5058-eaa1-48d3-a1b2-22753b3e6151)

![螢幕擷取畫面 2024-02-24 151944](https://github.com/raysan5/raylib/assets/118543966/605f796e-b72e-4ffd-8574-e82c03720910)

![螢幕擷取畫面 2024-02-24 152215](https://github.com/raysan5/raylib/assets/118543966/88b4f4fd-8904-48c7-8ef9-1dbf012a1574)

some translations:
* 無法解析的外部符號: unresolved external symbol
* 傳回碼: return code

**Comment by Sqvid** [comment]
This issue is caused by CMake not linking the math library (-lm) and OpenGL correctly. Another way to produce this error on Linux is to run `cmake -DPLATFORM=SDL`. Basically if the internal `glfw` is not used then there is an error.

**Comment by Peter0x44** [comment]
@Sqvid but in his example, I don't believe he is using an external GLFW. At least, nothing in the cmake configure line indicates as such. The issue you're reporting with SDL reporting some undefined math symbols seems real (I can reproduce it) but I think it's separate.

**Comment by Peter0x44** [comment]
Also note, there is a separate issue with rlgl_standalone.c not building with a shared lib, this applies to the Makefile too. Currently it only builds with a static lib, because the shared lib doesn't expose its glfw symbols anymore. I assume getting past this issue may run into the next.

@Pan-Shin-Z can you try compiling with `-DBUILD_EXAMPLES=No`?

**Comment by Pan-Shin-Z** [comment]
@Peter0x44 , thank you. It can be built successfully with `-DBUILD_EXAMPLES=NO`. 

Can you please elaborate on the reasons for the build failure of examples ? I don't quite understand this passage .
`Also note, there is a separate issue with rlgl_standalone.c not building with a shared lib, this applies to the Makefile too. Currently it only builds with a static lib, because the shared lib doesn't expose its glfw symbols anymore.`

**Comment by raysan5** [comment]
I think this example should not be included in the build systems. It's a special use case.

**Comment by Peter0x44** [comment]
@raysan5 then the Makefile shouldn't build it either

**Comment by raysan5** [comment]
> then the Makefile shouldn't build it either

@Peter0x44 Is it included in the Makefile??? Afaik, I never included it.

**Comment by Peter0x44** [comment]
@raysan5 it definitely is
https://github.com/raysan5/raylib/blob/c7b362d19dd32b00a0fce90bc9abe8afd3d4b754/examples/Makefile#L590

https://github.com/raysan5/raylib/blob/c7b362d19dd32b00a0fce90bc9abe8afd3d4b754/examples/Makefile#L262-L265
