### ISSUE TITLE
[core] Add the option to set the log level

### ISSUE THREAD

**Issue by nounoursheureux** [raysan5/raylib#383]
I think it would be useful to be able to restrict the logging by setting a log level, and any message that wants to be logged has to have an importance higher than the current log level. For example I am toying with shaders, and raylib prints a line every time I change a uniform (which happens a lot ^^ ). I would like to call something like `SetLogLevel(LOG_WARNING)` and be notified only of warnings and errors. So here is my proposal:
- Sort the `LogType` enum by order of importance: `LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR, LOG_OTHER`
- Implement a `SetLogLevel` functions that takes a `LogType` and sets the current `logLevel` (a global)
- In `TraceLog`, check if the level of the current message is equal or higher to the current `logLevel`. If yes, continue. If no, return (and execute `exit(1)` before that if the message is an error).

Do you think this would work / be a good idea ?

**Comment by raysan5** [comment]
Hi @nounoursheureux, I've been thinking about this addition... not sure if it's a good addition:

Most of the log types (`LOG_INFO`, `LOG_WARNING`, `LOG_ERROR`) should be displayed most of the time and `LOG_DEBUG` it's the only log type that should be selected by user or not... 

Maybe a better approximation could be using `SetTraceLog(int logFlags);`
```c
SetTraceLog(LOG_DEBUG | LOG_INFO | LOG_WARNING);  // Log flags?
```

Also log information should be reviewed (improved) and better categorized.

**Comment by qarlosh** [comment]
Removing the `#define SUPPORT_TRACELOG` from `utils.c` would help at least to decide at compile time if you want to enable or disable tracing using the `-DSUPPORT_TRACELOG` argument.
In my project I end with a lot of INFO logs from raylib, and this hinders the tracing of the rest of the program.

**Comment by raysan5** [comment]
Just added function `SetTraceLog()` on commit https://github.com/raysan5/raylib/commit/e517d8fd168b361719c214d57463ef3ee461d425 (notice I renamed it in the following commit, I think is clear this way). 

Now log level could be set at anytime using:
```c
SetTraceLog(LOG_INFO | LOG_WARNING);    // Enable INFO and WARNING log output messages
```
