### ISSUE TITLE
[rmodels] Review `LoadGLTF()`, boneId loading to fit into `unsigned char` data

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#3836]
glTF could provide joints data (`cgltf_attribute_type_joints`) in multiple formats, raylib only supports `model.meshes[].boneIds` as `unsigned char`. A conversion is required.

**Comment by x1nixmzeng** [comment]
I've hit this issue with some test models from the Adobe Mixamo service.

Any ideas on the intended fix? Just adding converters for incorrectly stored data `cgltf_component_type_r_16u` or looking to rewrite how raylib handles boneids?

**Comment by raysan5** [comment]
@x1nixmzeng I'm adding converters for incorrectly stored data, I'm not redesigning raylib to support more than 255 bone Ids.

**Comment by raysan5** [comment]
Reviewed JOINTS loading, per [glTF specs](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes-overview) only `vec4` and `u8`/`u16` formats should be supported.
