### ISSUE TITLE
[examples] camera example doesn't called SetRandomSeed

### ISSUE THREAD

**Issue by weskerfoot** [raysan5/raylib#3845]
If I'm not mistaken, the example code at https://github.com/raysan5/raylib/blob/master/examples/core/core_2d_camera.c should also call `SetRandomSeed` before running `GetRandomValue`. When I tried it everything was being put at the same position, but seeding the RNG fixed it.

**Comment by raysan5** [comment]
@weskerfoot `InitWindow()` already initializes random seed to current `time(NULL)`.
