### ISSUE TITLE
[audio] Replace OpenAL Soft audio library by mini_al

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#385]
Since the beginning of raylib I've been looking for a lightweight alternative library to [OpenAL Soft](https://github.com/kcat/openal-soft) (https://github.com/raysan5/raylib/issues/52) and finally, there seems to be a solid candidate for that: [mini_al](https://github.com/dr-soft/mini_al) by @dr-soft and proposed by @gen2brain (https://github.com/raysan5/raylib/issues/52#issuecomment-340394183).

Don't misundertood, **OpenAL Soft is great**, easy-to-use, lots of features... but it's also a big library, sometimes difficult to build, with not-really-zlib-compatible license (https://github.com/raysan5/raylib/issues/372#issuecomment-340219354)... and adds a big dependency to raylib. 

**One of the final goals for raylib is avoiding any external dependency, being a self contained library that you can download, compile and run in any platform.**

It seems **mini_al** fits perfectly on what I was looking for, actually, library is in active development and new features and platforms are being added. Additionally, @mackron started working on [mini_al support for raylib](https://github.com/mackron/raylib/commit/75433a670e0880c4d23d5178b073836de3628547) and also, @gen2brain started porting [mini-al to Go language](https://github.com/gen2brain/malgo), perfect for [raylib-go](https://github.com/gen2brain/raylib-go) binding. Also love [mini_al logo](https://camo.githubusercontent.com/a6cb4cd4f8848986914c8756dfab696017f695be/687474703a2f2f647265642e696f2f696d672f6d696e69616c5f776964652e706e67). :P

Many thanks to @mackron and @gen2brain for their help on this project!

**Comment by raysan5** [comment]
More issue discussion on mini-al github: https://github.com/dr-soft/mini_al/issues/3

**Comment by raysan5** [comment]
Replacement is almost complete, being tested in multiple platforms, but it is a really big library change so, thinking about some transition mechanism. 

Maybe supporting OpenAL Soft and mini_al for some time? Or just move fordward and remove OpenAL Soft completely on next raylib iteration? Thinking about it...

**Comment by minecraftlog21** [comment]
I'd say just make the transition completely, whats the point of having two different sound APIs if anyone needs OpenAl cant they just link in them selves.

**Comment by raysan5** [comment]
Before doing the transition I need to verify it works properly on all the platforms. OpenAL is quite an stablished library used for commercial games (proved to be stable) while mini_al is a brand new library still under development. I really like it but I need to test it carefully before a full replacement...

**Comment by raysan5** [comment]
`mini_al` implemented in PR https://github.com/raysan5/raylib/pull/413

**Comment by gen2brain** [comment]
On macOS you will want to define -DMAL_NO_COREAUDIO as that is not implemented yet, so it can fallback to OpenAL.

I only tested if lib and audio examples can be built with raylib-go, but I cannot test in vmware, OpenGL support in virtual machine is not good enough for GLFW to open window.

**Comment by gen2brain** [comment]
Also, there is no need to link to -framework OpenAL on macOS, it is dlopen-ed.

**Comment by mackron** [comment]
Defining MAL_NO_COREAUDIO isn't necessary - it's just placeholder. There shouldn't be anything there that breaks the build (correct me if I'm wrong!).

**Comment by gen2brain** [comment]
It failed to build, I don't have now the exact error, I will add it in couple of minutes here.

**Comment by gen2brain** [comment]
```
 github.com/gen2brain/raylib-go/raylib
In file included from mini_al.c:4:
../go/src/github.com/gen2brain/raylib-go/raylib/external/mini_al.h:2749:18: error: use of undeclared identifier 'mal_backend_coreaudio'
```

**Comment by mackron** [comment]
Oops. That will get fixed tonight when I get home. Thanks!

**Comment by raysan5** [comment]
Transition to `mini_al` has already been done but still keeping the `OpenAL Soft` backend for some platforms: HTML5 and OSX. Check commit https://github.com/raysan5/raylib/commit/61afd07bd7b3a96c6f0f460b668f52cf1a8bd90f

Also reviewed code formatting on [audio module](https://github.com/raysan5/raylib/blob/develop/src/audio.c). 

A more detailed review on new mini_al based audio implementation is required. I want to understand in detail how it works... Still a bit confussed about `AudioBuffer`, `AudioStream`, `Sound` and `Music`, probably those structures could be refactored...

**Comment by gen2brain** [comment]
I thought mini_al will fallback to OpenAL on OSX/macOS, there are maybe some issues with that?

Also, I played with emscripten recently and it seems it will use SDL anyway for main loop and probably some other things, so for HTML5 now it will use both SDL and OpenAL?

**Comment by raysan5** [comment]
Hi @gen2brain, mini_al fallback for OpenAL Soft seems not to work at the moment due to https://github.com/dr-soft/mini_al/issues/3#issuecomment-345402904. It was proposed to use SDL backend for audio but it implied a **4-9 MB** builds (includes all SDL library, completely overloading!) vs **1 MB** with current raylib OpenAL implementation.

Considering that current OpenAL Soft backend for emscripten does not require any special linkage (emscripten detects and uses it automatically), just enabled that option for HTML5.

As far as I know, raylib does not use SDL at all, it uses [GLFW emscripten implementation](https://github.com/kripken/emscripten/blob/incoming/src/library_glfw.js), more lightweight. Actually OpenAL Soft usage is just a [custom emscripten implementation](https://github.com/kripken/emscripten/blob/incoming/src/library_openal.js) to default browser Audio.

About OSX, I couldn't test it so, before enabling a library that I don't know if it works on that platform, I preferred to just leave the raylib OpenAL Soft backend for the moment.

**Comment by gen2brain** [comment]
Ok, I thought that main loop in emscripten (emulated/pseudo loop etc.) already uses SDL that comes with emscripten, not sure why I thought that.

**Comment by mackron** [comment]
> A more detailed review on new mini_al based audio implementation is required. I want to understand in detail how it works... Still a bit confussed about AudioBuffer, AudioStream, Sound and Music, probably those structures could be refactored...

I can help you out with that if you have any questions.

**Comment by raysan5** [comment]
Hi @mackron! Thanks for your help! I'll keep you updated! :)

**Comment by SethArchambault** [comment]
Hey I just tried out the develop branch today and I'm getting the same error as above:

````
Undefined symbols for architecture x86_64:
  "_mal_convert_frames", referenced from:
      _WaveFormat in libraylib.a(audio.o)
ld: symbol(s) not found for architecture x86_64
````

I figured it belongs here rather than it's own thread.. any solution?

**Comment by raysan5** [comment]
Hi @SethArchambault, just tested it and it works on my side...

Are you testing it on Windows 10? Compiling with MinGW?

**Comment by SethArchambault** [comment]
This is on MacOS Sierra

**Comment by raysan5** [comment]
Just did a quick review on commit https://github.com/raysan5/raylib/commit/7bf6becc94ee18f782e6ef176745bc8d50b19944

mini_al implementation just works great! As a side effect, executable size has been reduced from ~1.4MB to ~770KB when using audio, I love it!

**Comment by mackron** [comment]
Just a quick bug I noticed while scanning this code:

https://github.com/raysan5/raylib/blob/develop/src/audio.c#L636

The master volume is getting to to 1, but should be set to `volume`.

**Comment by raysan5** [comment]
Hey @mackron! Thank you very much for detecting that issue! Corrected in commit https://github.com/raysan5/raylib/commit/231a69417ab5a9627fc9972392e7146ddea07106
