### ISSUE TITLE
[build] Cannot use GLFW runtime platform detection

### ISSUE THREAD

**Issue by M374LX** [raysan5/raylib#3850]
The big new feature of GLFW 3.4 is runtime platform detection, which enables a single Linux executable to run on both X11 and Wayland. However, raylib cannot use this feature at the moment when built using the Makefile or Zig, although it works when raylib is built using CMake. 

The reason is because the Makefile and Zig use the file ``rglfw.c``, which is not used by CMake, and ``rglfw.c`` combines all of GLFW's source files needed for a single platform selected at build time into one file. However, it is not possible to include multiple platforms into a single source file because GLFW has some static functions with the same name in source files for different platforms. Moreover, GLFW expects the "null" platform to be always present but we cannot include it for the same reason.

Maybe we should get rid of ``rglfw.c`` and have the Makefile and Zig select the GLFW source files to be built.

This problem has been previously reported here: https://github.com/raysan5/raylib/pull/3827#issuecomment-1963041768.

**Comment by orcmid** [comment]
I am concerned that elimination of `rglfw.c` may create difficulties for desktop builds that now include it without using Make or CMake.  E.g., in `raylib/projects/scripts` and elsewhere, including simple builds of examples.

**Comment by M374LX** [comment]
It looks like modifying the bundled GLFW by adding platform-specific suffixes to the functions with conflicting names is an easier solution than removing ``rglfw.c``.

**Comment by raysan5** [comment]
I prefer to keep `rglfw.c`, it amalgamates all GLFW into a single module and it simplifies a lot compilation process.

In any case, how does CMake/GLFW resolve this same issue? Because build process is also supposed to compile and link all those symbols with the same name.

**Comment by M374LX** [comment]
When building with CMake, instead of using ``rglfw.c``, GLFW's ``CMakeLists.txt`` is included along with raylib's own ``CMakeLists.txt``, as seen in https://github.com/raysan5/raylib/blob/master/cmake/GlfwImport.cmake.

Anyway, keeping ``rglfw.c`` and just renaming GLFW's functions with conflicting names is indeed a simpler solution.
