### ISSUE TITLE
[rtextures] `LoadImageSvg()` doesn't work correctly

### ISSUE THREAD

**Issue by moanddev** [raysan5/raylib#3854]
### Issue description

I have found two different errors in the LoadImageSvg method, these are:

1. On Android it is not able to find the file located in the Assets folder of the project. As I have seen, this is because the FileExists method is called (as it fails, it is believed that the SVG image is given by text instead of a file) within LoadImageSvg, and this does not seem to work at all well for the platform .
<br/>![image](https://github.com/raysan5/raylib/assets/53525849/6ec99d91-0d9c-4e1c-a1be-cfb7eb60f737)
<br/>I understand that the ideal would be to modify the FileExists method so that it works well on Android. Although a quick fix in the LoadImageSvg method itself can be:

```c
int dataSize = 0;
unsigned char *fileData = LoadFileData(fileNameOrString, &dataSize);;

if (fileData != NULL)
{
    isSvgStringValid = true;
}
```

2. When using the LoadImageSvg method with an SVG image as text it crashes, specifically when using the nsvgParse method. Tested on Windows and Android with the same result.
<br/>This is one of the examples I have used:

```c
LoadImageSvg("<svg width=\"200\" height=\"200\" xmlns=\"http://www.w3.org/2000/svg\"><rect width=\"100\" height=\"100\" x=\"50\" y=\"50\" fill=\"red\" /></svg>", 400, 350);
```

### Environment

- **Operating System**: Android (version 10 physical and 14 emulated tested)
- **OpenGL**: 
         Vendor:   Qualcomm
         Renderer: Adreno (TM) 512
         Version:  OpenGL ES 3.2 V@415.0 (GIT@f2ab992, I401605978b, 1569657027) (Date:09/28/19)
         GLSL:     OpenGL ES GLSL ES 3.20

---

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

**Comment by raysan5** [comment]
@moanddev thanks for reporting. Did you try debugging the crash from point 2?

**Comment by moanddev** [comment]
I'm not really a C developer and I haven't been able to debug properly.

I have managed to locate the error by adding simple logs like:

![image](https://github.com/raysan5/raylib/assets/53525849/cd2acba0-b934-4271-887f-56fecb1003f2)

And the result is:

![image](https://github.com/raysan5/raylib/assets/53525849/5ceff9f8-7b1c-415c-8c76-728603643200)

Also try sending an input with \0 at the end because in the nanosvg method description they mention it (https://github.com/memononen/nanosvg/blob/93ce879dc4c04a3ef1758428ec80083c38610b1f/src/nanosvg.h#L172)

**Comment by raysan5** [comment]
As per the description, the issue could be at `nanosvg` side and not raylib, it should be addressed in base project.

**Comment by cattokomo** [comment]
Is this issue resolved in nanosvg repository?
