### ISSUE TITLE
[build] Linking glfw in ubuntu 17.10 - library name is glfw not glfw3

### ISSUE THREAD

**Issue by dbriemann** [raysan5/raylib#386]
I don't know if this was a change in the newest Ubuntu version but if you install the package `libglfw3` in 17.10 the library is called `glfw` instead of `glfw3`. 
That's causing all makefiles in the project to not work without fiddling. 

I don't know how this could be improved since most Linux distributions use glfw3 I guess?

**Comment by raysan5** [comment]
This is a known issue with GLFW3: https://github.com/glfw/glfw/issues/1051

As per https://github.com/raysan5/raylib/issues/377, I'm including GLFW3 sources with raylib to be compiled together, that way, that dependency issue will be removed in most platforms.

**Comment by dbriemann** [comment]
Ah OK I should have checked that before. Great to hear that you are already dealing with it. I don't think we need this issue then? I leave it to you to close it.
