### ISSUE TITLE
[rcore] HiDPI not working as expected on Wayland protocol

### ISSUE THREAD

**Issue by iongion** [raysan5/raylib#3872]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Something happened in this branch merge <https://github.com/raysan5/raylib/commit/190487383860c54d1746444f17b59c36decfca1e> that broke the HiDPI behavior in Linux environment, if I switch to previous commit, before the merge, all is proper <https://github.com/raysan5/raylib/commit/68b553cfc157a996e92da053d9e7b8beb92de0c0>

### Environment

- Operating System is Linux Ubuntu 22.04 running on Windows 11 WSL with `export LIBGL_ALWAYS_SOFTWARE=1` to avoid trouble with the Nvidia WSL drivers

### Issue Screenshot

1. Sample output on broken branch - it looks that something gets it to switch to wayland

```
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 3840 x 2160
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
WARNING: GLFW: Error: 65548 Description: Wayland: The platform does not provide the window position
WARNING: GLFW: Error: 65548 Description: Wayland: The platform does not provide the window position
WARNING: GLFW: Error: 65548 Description: Wayland: The platform does not support setting the window position
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 222
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Mesa
INFO:     > Renderer: llvmpipe (LLVM 15.0.7, 256 bits)
INFO:     > Version:  4.5 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
INFO:     > GLSL:     4.50
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GLFW platform: Wayland
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

This produces this image, when running the sample, which renders incorrectly, mouse events are also off

![image](https://github.com/raysan5/raylib/assets/867609/34a3c567-d369-4d62-b92a-702c287e16ba)

2. Sample output on the commit just before the master merge

- This ones appears not to switch to wayland and all is still ok

```
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 222
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Mesa
INFO:     > Renderer: llvmpipe (LLVM 15.0.7, 256 bits)
INFO:     > Version:  4.5 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
INFO:     > GLSL:     4.50
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GLFW platform: X11
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

This produces this image, when running the sample, which render properly

![image](https://github.com/raysan5/raylib/assets/867609/91665da7-a8b7-4989-965f-b49df5c7626c)

### Code Example

- Checkout and build the faulty version commit ID and run any of the default examples

**Comment by gen2brain** [comment]
This looks the same as the issue in raylib-go https://github.com/gen2brain/raylib-go/issues/354. With different compositors, it works but with Gnome/Mutter, it is like that (although I cannot reproduce it in VM with Gnome/Wayland). You can just use an X11 session, or compile with SDL, or try a different compositor, but it looks like it is specific to something in Gnome.

**Comment by gen2brain** [comment]
Just to add, before that commit, you were using X11 compatibility mode in Wayland, now you are using native Wayland mode. In raylib-go I added a build tag `x11` (i.e. I just don't define -D_GLFW_WAYLAND) for users who want to keep the old/compatibility behavior.

**Comment by SuperUserNameMan** [comment]
Could you please test this PR #4151 ?

**Comment by raysan5** [comment]
Wayland backend has been disabled by default due to multiple issues with it.

**Comment by zhaob1n** [comment]
Why is this issue closed? It's not solved after all. At least let's have an issue to track wayland support.

**Comment by casperbear** [comment]
@xcpky Most likely it was closed because multiple HDPI issues had been in open state for multiple platforms and recently, when some improvements were pushed (including by raysan5 if you check the commits), it was hard to review every detail/comment in every issue. If you have a reproducible HDPI bug with the latest raylib (built from master) then it's probably worth a try to open a new issue (for a specific platform / settings etc)

**Comment by zhaob1n** [comment]
> [@xcpky](https://github.com/xcpky) Most likely it was closed because multiple HDPI issues had been in open state for multiple platforms and recently, when some improvements were pushed (including by raysan5 if you check the commits), it was hard to review every detail/comment in every issue. If you have a reproducible HDPI bug with the latest raylib (built from master) then it's probably worth a try to open a new issue (for a specific platform / settings etc)

This issue is still reproducible with raylib built from master. I think we should reopen it,.
<img width="1200" height="675" alt="Image" src="https://github.com/user-attachments/assets/bbf7659f-1a71-4bd0-96cd-b61c10e1991f" />

**Comment by raysan5** [comment]
@xcpky afair, this issue is related to GLFW, an underlying library used by raylib. I reviewed HighDPI on all desktop platforms last Christmas and unfortunately there were several issues with Wayland backend that I was not able to solve on raylib side. Did you verify this issue is raylib-related? Could you verify that a glfw window does not present this issue?
