### ISSUE TITLE
[UWP] Support inputs on Universal Windows Platform

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#388]
A [experimental raylib project](https://github.com/raysan5/raylib/tree/testing_uwp/project/vs2015.UWP) has been created to support UWP (Win10 App, Windows Phone, Xobox One) using [ANGLE](https://github.com/Microsoft/angle) for graphics (OpenGL ES 2.0 to Direct3D 11 translation layer).

Project must be compiled as C++ despite using raylib as static C library. Graphic work great but the problem is Inputs and Audio support.

It seems that [mini_al](https://github.com/dr-soft/mini_al) library could take care of Audio in UWP (https://github.com/raysan5/raylib/issues/385) but no Input management functionality has been added yet, actually, don't know exactly how to do that...

Here some useful documentation:
https://docs.microsoft.com/en-us/windows/uwp/design/input/
https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-interactions
https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples

**Comment by raysan5** [comment]
Handmade Network user **SamNChiet** is already [working on it](https://raylib.handmade.network/forums/t/2675-raylib_1.8_released/2#13605).

**Comment by raysan5** [comment]
Hi @SamNChiet, any news on this feature? Did you work some more on it?

**Comment by SamNChiet** [comment]
Hello! Apologies for the delay, I was preoccupied with other obligations so hadn't been able to do much on raylib :(

Things are easier for me schedule-wise now, so I cleared some time and and as of this morning, keyboard input is functional! There's some pretty glaring structural issues related to the use of callbacks and I'll probably end up polling the input instead, but it works! I'll commit the changes to my repo in the meantime so you have at least something there.

After keyboard, I'm guessing my to-do list is something along the lines of:

- mouse
- touch gestures

Feel free to correct and change at will.
Cheers!

**Comment by raysan5** [comment]
Hey @SamNChiet! No worries, just take your time! :D

You're right with the plan, keyboard, mouse and touch. My main concern is how to integrate it on raylib, it probably requires separate .cpp files for inputs... 

Keep me updated!

**Comment by SamNChiet** [comment]
I just swapped the keyboard callbacks with a polling system and submitted a pull request which you can find [here](https://github.com/raysan5/raylib/pull/427)!

**Comment by raysan5** [comment]
Keyboard support implemented in PR https://github.com/raysan5/raylib/commit/f51dcd8bfa829f99f09ac42e07578b37787ef7de

**Comment by raysan5** [comment]
Keyboard review and mouse implemented in PR https://github.com/raysan5/raylib/pull/428

**Comment by raysan5** [comment]
Hi @SamNChiet! 

Just integrated UWP branch into develop branch in PR https://github.com/raysan5/raylib/commit/6f73008007893bb8d9c0c386b734e2c8332f83b2 and reviewed in commit https://github.com/raysan5/raylib/commit/8e0a277f7c89acc8758b667f6ff85f5a323fe89e

Please, from now on, continue your work on develop branch if possible.

**Comment by raysan5** [comment]
Keyboard, mouse and gamepad input are already working on UWP. Closing this issue for now.
