### ISSUE TITLE
[build] build.zig linux desktop compile fails with "Cannot disable Wayland and X11 at the same time"

### ISSUE THREAD

**Issue by SimonLSchlee** [raysan5/raylib#3882]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

The `build.zig` fails to compile for linux desktop.

To get it to compile I had to add `raylib.defineCMacro("_GLFW_X11", null);` to the build.zig for linux desktop,
without it I got `Cannot disable Wayland and X11 at the same time`,
activating Wayland gave me other compile errors so I didn't for now.

I am not sure whether these defines should be handled in the `build.zig` or not.

To fix the issue in SimonLSchlee/zigraylib (a raylib example for using raylib with zig) I added the define for `_GLFW_X11`
in this raylib fork https://github.com/SimonLSchlee/raylib/commit/66e2a58b20c81094f9219021ef98fd77189fee92

Here is the issue https://github.com/SimonLSchlee/zigraylib/issues/2 and the commit https://github.com/SimonLSchlee/zigraylib/commit/359cadbc3d479badf9ecf07339ee363d6ba4509d

On the raylib discord I got the info that something similar was done to fix compilation for `game-premake` here: https://github.com/raylib-extras/game-premake/commit/a67dab56658dbffd171c803fc36514dc0762e635
And that "The build.zig may need review for glfw 3.4"
https://discord.com/channels/426912293134270465/678183146419912704/1220839133237215372

I mainly open this issue here so that somebody who knows whether adding this define is the right thing to do,
can point us towards the right direction or say whether some other fix should be applied.

**Comment by echoptic** [comment]
Hello, tried using raylib with Zig today and I was able to make it work. Im using 0.12 master. Here are the steps:
1. Add raylib using the zig package manager: `zig fetch --save=raylib https://github.com/raysan5/raylib/archive/b905dafca038ca09e2b6d1e6eaf6f578b0bf0361.tar.gz`
2. Add this code in build.zig after `const exe = ...`:
```zig
    const raylib_dep = b.dependency("raylib", .{
        .target = target,
        .optimize = optimize,
    });

    var raylib = raylib_dep.artifact("raylib");
    raylib.defineCMacro("_GLFW_X11", null); // for wayland define `_GLFW_WAYLAND` instead
    exe.linkLibrary(raylib);
    exe.addIncludePath(raylib_dep.path("include"));
```

**Comment by raysan5** [comment]
I think this issue has been already addressed.
