### ISSUE TITLE
[rcore] *FromMemory() API or alternative mapping helper

### ISSUE THREAD

**Issue by Kruithne** [raysan5/raylib#3883]
Hello!

I've been using raylib for a 3D project but hit a small roadblock. All files for the project are memory-mapped and not available on disk, so functions that require an explicit file path such as `LoadModelAnimations` are not usable.

I noticed that in #1327 it was mentioned that you'd like to avoid adding more `Load*FromMemory()` functions, however there was talk of an alternative API such as `SetFileDataMapping` and `ClearFileDataMapping` which could internally map a memory address to a path which is then checked by these functions, with the last comment of "some other mechanism could be added in the future."

Since four years how now passed, is there any potential bandwidth for this being considered again? Or even another look at potentially introducing `Load*FromMemory()` variants. Currently it's a major blocker that a number of API functions require disk files for a project that deals explicitly with in-memory data.

Thank you!

**Comment by RobLoach** [comment]
It is possible to set the load/save file data callback...
``` c
RLAPI void SetLoadFileDataCallback(LoadFileDataCallback callback); // Set custom file binary data loader
RLAPI void SetSaveFileDataCallback(SaveFileDataCallback callback); // Set custom file binary data saver
```

Used them successfully in [raylib-physfs](https://github.com/RobLoach/raylib-physfs). Would like to see some of that capability expanded to functions that you mentioned. A workaround for it in the mean time would be to copy the associated methods and modify as needed.

**Comment by Kruithne** [comment]
> It is possible to set the load/save file data callback...
> 
> ```c
> RLAPI void SetLoadFileDataCallback(LoadFileDataCallback callback); // Set custom file binary data loader
> RLAPI void SetSaveFileDataCallback(SaveFileDataCallback callback); // Set custom file binary data saver
> ```
> 
> Used them successfully in [raylib-physfs](https://github.com/RobLoach/raylib-physfs). Would like to see some of that capability expanded to functions that you mentioned. A workaround for it in the mean time would be to copy the associated methods and modify as needed.

Oh, I hadn't spotted those functions, thanks for pointing them out! Would I be right in assuming that *all* functions in raylib that load files from disk can be intercepted with custom functionality via those callbacks? If so, that seems like it would solve the issue completely.

**Comment by RobLoach** [comment]
`LoadModelAnimations()` uses `LoadFileData()`, which calls the `LoadFileDataCallback` that you have set, yes.

**Comment by raysan5** [comment]
As comented, alternatives already exist to cover that use case.
