### ISSUE TITLE
[raudio] Failing to load a MP3-File causes a double free

### ISSUE THREAD

**Issue by FishingHacks** [raysan5/raylib#3889]
### Issue description

When using `LoadMusicStream()` on a file that is not valid mp3, raylib crashes with `free(): double free detected in tcache 2`.

I tried digging a bit deeper and upon further (tho not very detailed) inspection, i found out that `drmp3_init_file` closes the file if it could not successfully load ([`dr_mp3.h:3536`](https://github.com/raysan5/raylib/blob/master/src/external/dr_mp3.h#L3536)). `pclose` is later called again by `drmp3_uninit` ([`raudio.c:1448:54`](https://github.com/raysan5/raylib/blob/master/src/raudio.c#L1448)). `drmp3_uninit` seems to be causing the issue as removing it fixes it. I also noticed that `drmp3_uninit` calls `drmp3__free_from_callbacks`, but that shouldnt be called anyway because `drmp3_init_internal` calls it when it fails ([`dr_mp3.h:2854:9`](https://github.com/raysan5/raylib/blob/master/src/external/dr_mp3.h#L2854)).

### Environment

Platform: Desktop

### Code Example

```c
#include "raylib/src/raylib.h"
#include "stdio.h"

int main(void) {
    InitAudioDevice();
    if (!IsAudioDeviceReady()) {
        printf("couldn't initialize the audio device :notlikethis:");
        return -1;
    }

    Music stream = LoadMusicStream("music.mp3");

    PlayMusicStream(stream);

    while (IsMusicStreamPlaying(stream)) {
        UpdateMusicStream(stream);
    }

    UnloadMusicStream(stream);

    CloseAudioDevice();

    return 0;
}
```

**Comment by FishingHacks** [comment]
Checking other formats, the .wav format also has the same double free error message, so i suspect its the same issue with `drwav_uninit`. The QOA Format segfaults, i didn't investigate yet why tho

**Comment by RobLoach** [comment]
Able to reproduce a similar issue with the `audio_music_stream` example if you delete `resources/country.mp3`.

```
WARNING: FILEIO: [resources/country.mp3] Music file could not be opened
INFO: TIMER: Target time per frame: 33.333 milliseconds
audio_music_stream: /home/rob/Documents/raylib/src/external/dr_mp3.h:3775: drmp3_seek_to_start_of_stream: Assertion `pMP3 != ((void *)0)' failed.
Aborted (core dumped)
```

**Comment by raysan5** [comment]
@RobLoach @veins1 @FishingHacks I'm reviewing this issue but I can't reproduce it. Using raylib latest version from GitHub master branch. Please, could you provide some sample code/example to review it?

**Comment by sebatt90** [comment]
I tried replicating the issue. Editing line 1485 of `raudio.c` and removing the call to the function `drmp3_unit` fixed the issue:
```c
#if defined(SUPPORT_FILEFORMAT_MP3)
        else if (music.ctxType == MUSIC_AUDIO_MP3) { /*drmp3_uninit((drmp3 *)music.ctxData);*/ RL_FREE(music.ctxData); }
```
also, there's this problem also for wav files.

**Comment by FishingHacks** [comment]
Okay, sorry for the late reply, have been busy lately. The Pull Request #3966 seems to have fixed most issues, ogg, mp3, qoa, flac, xm and mod files seem to work. wav files are still broken. Taking a quick look at the pull request, it calls `drwav_uninit` if the initialization failed (see [`raudio.c:1351`](https://github.com/raysan5/raylib/blob/master/src/raudio.c#L1351)), but doesn't do the same thing for mp3 (see [`raudio.c:1399`](https://github.com/raysan5/raylib/blob/master/src/raudio.c#L1399)). I believe that this is the issue.

My code (main.c):
```c
#include "raylib.h"
#include "stdio.h"

int main(int argc, char **argv) {
    if (argc != 2) {
        printf("usage: main [file]");
        return -2;
    }

    InitAudioDevice();
    if (!IsAudioDeviceReady()) {
        printf("couldn't initialize the audio device");
        return -1;
    }

    Music stream = LoadMusicStream(argv[1]);

    PlayMusicStream(stream);

    while (IsMusicStreamPlaying(stream)) {
        UpdateMusicStream(stream);
    }

    UnloadMusicStream(stream);

    CloseAudioDevice();

    return 0;
}
```

I ran the following commands (assuming we start out in an empty directory with the above source in `main.c`):
```
$ sudo apt install build-essential git libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
$ git clone https://github.com/raysan5/raylib.git
$ cd raylib/src
$ make PLATFORM=PLATFORM_DESKTOP
$ cd ../../
$ gcc -o main main.c -I. -L. -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
$ touch test.flac test.mod test.mp3 test.ogg test.qoa test.wav test.xm
$ ./main test.flac
$ ./main test.mod
$ ./main test.mp3
$ ./main test.ogg
$ ./main test.qoa
$ ./main test.wav
$ ./main test.xm
```

**Comment by raysan5** [comment]
@FishingHacks @veins1 Thank you very much for reviewing this issue! Feel free to send a PR if you confirm removing `drwav_uninit` fixes the crash. Thanks! :)

**Comment by FishingHacks** [comment]
That did indeed fix the issue i was having, i created a pull request (#3986) to fix this

PS: Thanks for your incredible work on raylib

**Comment by raysan5** [comment]
@FishingHacks thank you very much for reviewing this issue! 😄

**Comment by FishingHacks** [comment]
no problem!
