### ISSUE TITLE
[rmodels] Support non-normalized GLTF vertex colors

### ISSUE THREAD

**Issue by ssoher** [raysan5/raylib#3890]
### Issue description

Blender exported gltf files have a different attribute format for vertex colors, thus they are not imported in Raylib. Instead a warning is given `WARNING: MODEL: [./asset/cube.glb] Color attribute data format not supported`.

Please use the attached archived glb file exported from Blender with default settings.

**How it's supposed to look:**

![image](https://github.com/raysan5/raylib/assets/4283979/e6f02b8c-c248-488c-91a7-b0a38833c4d1)
[gltf_cube_vertex_color.zip](https://github.com/raysan5/raylib/files/14806718/gltf_cube_vertex_color.zip)

**Comment by raysan5** [comment]
Implemented support for all glTF supported color vertex attribute data (vec3/vec4, u8, u16, f32)

**Comment by insomniacUNDERSCORElemon** [comment]
@raysan5 is loading vertex colors broken still on .obj files or is there something extra that needs to be done? 

It fails both with a material (displays gray) and no material (displays white), though I'd prefer no material if there was some way to make the default material load vertex colors properly (global glass/metal materials would be nice too, but that seems tricky).

**Comment by ssoher** [comment]
> @raysan5 is loading vertex colors broken still on .obj files or is there something extra that needs to be done?
> 
> It fails both with a material (displays gray) and no material (displays white), though I'd prefer no material if there was some way to make the default material load vertex colors properly (global glass/metal materials would be nice too, but that seems tricky).

obj specification does not include vertex colors, there are some obj flavors that support the `vc` tag but it's not a part of the standard, you'd be better off using a file format that includes it.

**Comment by insomniacUNDERSCORElemon** [comment]
The exports definitely have vertex color, but alright. The main reason I didn't want to use GLTF was the lack of scale factor in the Blender export that the OBJ exporter offers.
