### ISSUE TITLE
Raspberry Pi input system should be redesigned

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#39]
The way inputs (keyboard/mouse/gamepad) are managed on Raspberry Pi is far from ideal. Some keyboards don't work properly, mouse can be wrongly detected, no current gamepad support.

Related functions [core.c]:

    static void InitKeyboard(void);
    static void RestoreKeyboard(void);
    static void PollInputEvents(void);

    static void InitMouse(void);
    static void *MouseThread(void *arg);

    static void InitGamepad(void);

raylib design goal is to keep dependencies to the minimum so I decided to implement my own raw inputs reading mechanism on Rapsberry Pi; on other platforms I use GLFW3 that works flawlesly. This decision was taken to allow raylib to work on RPi without requiring X Window System.

Different systems were implemented for keyboard and mouse reading:

Keyboard data is read directly from standard input (`stdin`), keyboard settings and mode are reconfigured (`InitKeyboard()`) and then data is read as raw (`PollInputEvents()`); at exit keyboard settings are restored (`RestoreKeyboard()`). It was decided to be done this way (instead of reading events) to allow usage from SSH connection.

Mouse data is read from `DEFAULT_MOUSE_DEV`, currently `/dev/input/event1`, a new thread is created to keep reading mouse data independently of game loop (`MouseThread()`).

Gamepad data read is not implemented (`InitGamepad()`).

I think the system should be redesigned to use always `/dev/input/eventX` but detecting which devices are connected to the Raspberry Pi is another issue.

**Comment by raysan5** [comment]
Input system has been reviewed and redesigned. Gamepad support has been partially implemented but still requires some testing. Now raylib uses the old input event handlers:

- Keyboard:  Reconfigure and read `stdin` (standard input)
- Mouse: Read from `/dev/input/mouse0` (new thread)
- Gamepad: Read from `/dev/input/js0` (new thread)

Most changes implemented in commit https://github.com/raysan5/raylib/commit/98c60838fed28958519144840a21f012995d6799

RPI Input system now is functional but still has some issues and can be improved.

**Comment by Memorix101** [comment]
I want to add that when an input device lost connection the Pi build can't detect the input when it reconnected or a new one connected after launch of the application.

I think that's what you meant with :
> I think the system should be redesigned to use always /dev/input/eventX but detecting which devices are connected to the Raspberry Pi is another issue.
