### ISSUE TITLE
Not Build for Windows.

### ISSUE THREAD

**Issue by ElectroidDes** [raysan5/raylib#3903]
This idiot who is begging for donations  - named his functions that coincide with the names of the Windows functions and this stupid library is not built under Windows.
 He was a cretin from birth or was he hit on the head a lot?

**Comment by orcmid** [comment]
It is well-known that raylib is not meant to be compiled along with use of `windows.h`.  There are ways around that.

**Comment by thacuber2a03** [comment]
oh my god, chill

**Comment by realzvqle** [comment]
this is why github issues are useless and should be removed

people like this abuse it and insult people

**Comment by Neonberg** [comment]
Then make a better library

**Comment by Salakksson** [comment]
> This idiot who is begging for donations - named his functions that coincide with the names of the Windows functions and this stupid library is not built under Windows. He was a cretin from birth or was he hit on the head a lot?

what cretin is using windows.h with raylib though?

**Comment by MasterBroNetwork** [comment]
Issues are good when used properly, Any tool/system will inevitably be misused/abused.

> this is why github issues are useless and should be removed
> 
> people like this abuse it and insult people

**Comment by KoltPenny** [comment]
Must have been the eclipse.

**Comment by PalmDevs** [comment]
Restrict issue creation to contributors only 😄

**Comment by Krist15** [comment]
🤡

**Comment by serpatsama** [comment]
> Restrict issue creation to contributors only 😄

Ermmm that would defeat the whole purpose

**Comment by realzvqle** [comment]
> Restrict issue creation to contributors only 😄

indeed

**Comment by furtidev** [comment]
Please take a break and never return!

**Comment by PalmDevs** [comment]
> > Restrict issue creation to contributors only 😄
> 
> Ermmm that would defeat the whole purpose

Yeah, was kind of half joking 👍🏻

**Comment by xslendix** [comment]
what kind of cretin would try and build the project in an unsupported way documented and then make an issue insulting the creator of the library

**Comment by Rockdtben** [comment]
GitHub isnt your social media circle. No cap. Develop some rizz.
