### ISSUE TITLE
[build] Travis CI system fails on OSX compilation

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#391]
After adding GLFW3 library as an additional module ([rglfw](https://github.com/raysan5/raylib/blob/develop/src/rglfw.c)), Travis CI OSX compilation fails, maybe due to the inclusion of .m files and the requirement of clang compiler...

**Comment by raysan5** [comment]
@a3f, please, could you take a look to this issue?

**Comment by a3f** [comment]
GCC can compile Objective-C just fine, we just need to tell CMake what compiler it should be using (I use macOS as my daily OS, so feel free to ping me if I can help).

But I must say, I don't like this `rglfw.c` approach _at all_. It's prone to breaking (what if two files define the same symbol?), bloats application size, doesn't offer users the ability to update glfw without hassle and is a bad example to set for newbies that might look at the source code for learning purposes.

If you want to ship GLFW with raylib, I'd rather have it in a separate directory, be built normally with its own build script as part of the overall raylib build and then linked at the end.

I'll push a patch that fixes macOS compilation and removes GLFW download from the Travis CI Linux build.

**Comment by raysan5** [comment]
Many thanks @a3f for reviewing this issue! :)

`rglfw.c` module was proposed by @gen2brain and it seemed a good idea to me. Actually, raylib was using a quite old GLFW3 version (3.2.1) and it has problems on different platforms due to the different library namings. Compiling glfw together with raylib simplyfies building and removes external dependencies, that's an objective I looked for on raylib for long time.

I agree with your points and probably the current approach is not the best one but it was the easier to be integrated directly on raylib plain Makefile and avoid additional library linkage. I'll consider a better appoach if problems arise...
