### ISSUE TITLE
[raudio] Add a way to pass userdata into audio processors

### ISSUE THREAD

**Issue by Lucrecious** [raysan5/raylib#3911]
### Issue description

I'm trying to create a music app in raylib that processes different sounds while they are playing. The app adds sounds dynamically, and each of them might be processed with different settings. The issue is that when attaching an audio processor to an audio stream, the callback function has no access to user data. The parameters given to the AudioCallback don't have any identifiable data to identify "which" callback is being called.

It would be nice if there was some way of passing user data into these functions.

### Environment

All platforms.

### Issue Screenshot

N/A

### Code Example

Why not include an interface like this?

```
typedef void (*AudioCallbackEx)(void *bufferData, unsigned int frames, void *userdata);

void AttachAudioStreamProcessorEx(AudioStream stream, AudioCallbackEx callback, void *userdata);
void DetachAudioStreamProcessorEx(AudioStream stream, AudioCallbackEx callback, void *userdata);
```

I feel like I'm missing someone here but I feel like it'd be very useful to have userdata when getting callbacks from the audio processing.

**Edit:** I decided to fork raylib and build a version that simply allows `void *userdata` into the regular `AttachAudioStreamProcessor` it was really easy! The problem, of course, is that it breaks backwards compatibility and I can't really think of a way of implementing this in a good way without doing that.

So I'm not really sure if this will be possible until raylib 6.0 lol

**Comment by raysan5** [comment]
@Lucrecious Thanks for proposal but I'm afraid it's out of scope for now, that change would break the current API and probably most users do not have that special need. Forking and modifying raylib for the specific use case is the best path.

**Comment by sly-roccoon** [comment]
Being able to pass userdata is essential for raw audio processing of multiple audio streams, it would very much benefit audio/multimedia projects in raylib. it's current state is effectively unusable.

@Lucrecious were you successful in adding the userdata pointer in your fork?
