### ISSUE TITLE
[rmodels] Black GLB models

### ISSUE THREAD

**Issue by KotzaBoss** [raysan5/raylib#3933]
### Issue description

With latest raylib (2e774432090db1be697d2e4e5f49ea91ca038cd3) loaded GLB models are black. On the contrary before latest GLB changes (f6d85e5df70f13b1070d95d19b119c8686b770ae) the models were loaded with colors, though washed out.

### Environment

- OS: Linux
- KERNEL: 6.6.26-1-MANJARO x86_64
- CPU: 6-core AMD Ryzen 5 4600H with Radeon Graphics (-MT MCP-)
- GPU: GeForce RTX 3050 Mobile
- OpenGL:
  ```
  INFO: Platform backend: DESKTOP (GLFW)
  INFO: GLAD: OpenGL extensions loaded successfully
  INFO: GL: Supported extensions count: 235
  INFO: GL: OpenGL device information:
  INFO:     > Vendor:   AMD
  INFO:     > Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 16.0.6, DRM 3.54, 6.6.26-1-MANJARO)
  INFO:     > Version:  4.6 (Core Profile) Mesa 24.0.2-manjaro1.1
  INFO:     > GLSL:     4.60
  INFO: GL: VAO extension detected, VAO functions loaded successfully
  INFO: GL: NPOT textures extension detected, full NPOT textures supported
  INFO: GL: DXT compressed textures supported
  INFO: GL: ETC2/EAC compressed textures supported
  INFO: GLFW platform: X11
  ```

### Issue Screenshot

With latest (2e774432090db1be697d2e4e5f49ea91ca038cd3)
![image](https://github.com/raysan5/raylib/assets/69913906/7dd5327b-255f-4da7-bfc9-86acf051fede)

With previous (f6d85e5df70f13b1070d95d19b119c8686b770ae)
![image](https://github.com/raysan5/raylib/assets/69913906/35f35daf-538e-44ad-8a5b-05f4ffb603df)

### Code Example

Assets: [All.zip](https://github.com/raysan5/raylib/files/15092120/All.zip)

```c++
#include <raylib.h>

const char* const paths[] = {
    "./All/Broken_Traffic_Cone_002.glb",
    "./All/Crush_Barrier.glb",
    "./All/Road_Block.glb",
    "./All/Streetlights.glb",
    "./All/Water_Hydrant_001.glb",
};

#define sizeof_paths (sizeof(paths) / sizeof(paths[0]))

int main() {
    InitWindow(GetScreenWidth(), GetScreenHeight(), "Clip");

    Camera camera = { 0 };
    camera.position = (Vector3){ 0.0f, 20.0f, 20.0f };
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
    camera.fovy = 60.0f;
    camera.projection = CAMERA_PERSPECTIVE;

    SetTargetFPS(60);
    DisableCursor();

    Model models[sizeof_paths];
    for (int i = 0; i < sizeof_paths; ++i) {
        models[i] = LoadModel(paths[i]);
    }

    while (!WindowShouldClose()) {
        UpdateCamera(&camera, CAMERA_FIRST_PERSON);

        BeginDrawing();
        ClearBackground(GRAY);

        BeginMode3D(camera);
            DrawGrid(1000, 500);

            for (int i = 0; i < sizeof_paths; ++i) {
                DrawModel(models[i],
                        (Vector3){i * 10, 0, 0},
                        1.f,
                        WHITE
                    );
            }
        EndMode3D();

        EndDrawing();
    }

    for (int i = 0; i < sizeof_paths; ++i) {
        UnloadModel(models[i]);
    }

    CloseWindow();
}
```

**Comment by GuvaCode** [comment]
Hmm, I thought I made a mistake somewhere in the binding. The same problem is with gltf models that have textures. Sometimes artifacts also appear
![1](https://github.com/raysan5/raylib/assets/18312729/4c0bd4a5-4b0b-42e7-817c-8f8b34c2aa31)
![2](https://github.com/raysan5/raylib/assets/18312729/4323c59d-2317-4a6c-9445-c87998862173)
![3](https://github.com/raysan5/raylib/assets/18312729/23cc6c43-86e0-4fc3-9d89-ed7c854c1a19)

**Comment by raysan5** [comment]
@GuvaCode Did it work before the glTF update some days ago?

**Comment by raysan5** [comment]
@KotzaBoss @GuvaCode I'm trying to review this issue but I can't identify the commit where it was broken, please, could you provide more detailed information? Like the commit where this issue was introduced...

**Comment by KotzaBoss** [comment]
I went back on the commits one by one, i for me it breaks here 5cfcf13d4bc4723055f1d6b329148abb92b6b383

**Comment by raysan5** [comment]
Fixed on commit https://github.com/raysan5/raylib/commit/e47ebec66134800e734710038ea4e5f070f3ef06
