### ISSUE TITLE
[build] Unable to build a Mach-O universal binary with 2 architectures when building from source

### ISSUE THREAD

**Issue by zeusdeux** [raysan5/raylib#3934]
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on raylib version 5.0
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Hi folks! I am attempting to build raylib-5.0 from source and upon following the instructions in https://github.com/raysan5/raylib/wiki/Working-on-macOS#without-xcode---building-statically, I am unable to get a `Mach-O universal binary with 2 architectures` built. Instead the built `libraylib.a` is a `current ar archive`. Which even upon running `ranlib ./libraylib.a` doesn't give me a Mach-O universal binary.

### Environment

macos Ventura 13.6.3 on Intel x64 silicon

#### Locally built raylib
<img width="448" alt="image" src="https://github.com/raysan5/raylib/assets/635512/07eeafff-abc5-46d0-893d-bc8a09322d15">

#### Raylib prebuilt binary for osx
<img width="1563" alt="image" src="https://github.com/raysan5/raylib/assets/635512/68f5b5d5-1f52-43aa-93e0-0683f1ca67da">

### Code Example

1. Download the tarball or zip file of version 5.0 from releases
2. Unzip and cd into the `src/` folder
3. `export MACOSX_DEPLOYMENT_TARGET=13.6.3`
4. `make`

**Comment by zeusdeux** [comment]
Nvm, sorted. 
For anyone that runs into this — build libs for whatever set of platforms for macOS and run the libs together into `lipo -create`

**Comment by raysan5** [comment]
@zeusdeux Thanks for reporting! Actually, that's how it's done by the CD system: https://github.com/raysan5/raylib/blob/master/.github/workflows/macos.yml#L85

**Comment by zeusdeux** [comment]
@raysan5 Thank you for the quick response and this great set of modules!
Loved the interview with teej btw!
