### ISSUE TITLE
[Question] is Raylib compatible with smooth rendering ranging from 60 to 1.

### ISSUE THREAD

**Issue by ayoubelmhamdi** [raysan5/raylib#3936]
# Update
create a simple app, will use much CPU usage with `Raylib`، even when the applications appear to be doing minimal work.

My question is about how to achieve **smooth** `FPS`, ranging from `1` to `60`, without locking it at `60 FPS` every second, the usage of 60 fram per second is inefficient for non-gaming GUI applications.

I haven't found any sources discussing this situation. If there are any resources available, we would be eager to read them, because achieving smooth `FPS` with Raylib could be a game-changer.

Below is what I envision as an intuitive solution:

```c
#include "raylib.h"

int main(void) {
    InitWindow(400, 2
    InitWindow(400, 200, "Hello, Raylib!");

    SetMaxFPS{60);

    while {!WindowShouldRender()) {
        BeginSmoothFrame();
            DrawCircle(200, 100, 50, RED);
        EndSmoothFrame();
    }

    CloseWindow();
    return 0;
}
```

**Comment by raysan5** [comment]
@ayoubelmhamdi I'm afraid I don't understand this requirement. In any case, you can omit `SetTargetFPS()` usage an manage game timing yourself, here it is an example for a custom game loop: https://github.com/raysan5/raylib/blob/master/examples/core/core_custom_frame_control.c
