### ISSUE TITLE
Please help, permission denied in notepad++ while compiling and executing

### ISSUE THREAD

**Issue by Manopphysics** [raysan5/raylib#394]
this is the console
```
> Setup required Environment
-------------------------------------
SET: RAYLIB_DIR = C:\raylib
$(RAYLIB_DIR) = C:\raylib
ENV_SET: PATH=C:\raylib\MinGW\bin
$(SYS.PATH) = C:\raylib\MinGW\bin
CD: C:\raylib\raylib\examples\models
Current directory: C:\raylib\raylib\examples\models

NOTE: raylib uses OpenAL Soft library compiled statically and linked into the executable

> Cleaning latest build
---------------------------
cmd /c IF EXIST models_billboard.exe del /F models_billboard.exe
Process started >>>
<<< Process finished. (Exit code 0)

> Compiling program
-------------------------
gcc -o models_billboard.exe models_billboard.c -s C:\raylib\raylib\raylib_icon -Iexternal -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,-allow-multiple-definition -Wl,--subsystem,windows
Process started >>>
C:\raylib\MinGW\bin/ld.exe: cannot open output file models_billboard.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
<<< Process finished. (Exit code 1)

> Reset Environment
--------------------------
ENV_UNSET: PATH
$(SYS.PATH) has been restored

> Executing program
-------------------------
cmd /c IF EXIST models_billboard.exe models_billboard.exe
Process started >>>
Access is denied.
<<< Process finished. (Exit code 1)
================ READY ================
```

When i run any example or code the first time it works, but then the 2nd time it will never work

**Comment by raysan5** [comment]
It seems the program is still open in background, check the Windows Task Manager and look for your program, it should be there, close it.

Did you modify the code you're compiling? Could you share it? It seems program is not finishing correctly...

**Comment by Manopphysics** [comment]
Oh i did check in the task manager, theres no sign of the program opened, also when i close the program the console says exit succesfully

**Comment by raysan5** [comment]
Do you have any antivirus enabled? Maybe Avast?

**Comment by Manopphysics** [comment]
Yea, mcafee

**Comment by raysan5** [comment]
It could be related to the Antivirus, could you try disabling it and test again?

**Comment by Manopphysics** [comment]
sadly, it still shows the problem in the notepad++ console

> > Setup required Environment
-------------------------------------
SET: RAYLIB_DIR = C:\raylib
$(RAYLIB_DIR) = C:\raylib
ENV_SET: PATH=C:\raylib\MinGW\bin
$(SYS.PATH) = C:\raylib\MinGW\bin
CD: C:\Users\Manop\Documents\Visual Studio 2017\Projects\raylib\games
Current directory: C:\Users\Manop\Documents\Visual Studio 2017\Projects\raylib\games

NOTE: raylib uses OpenAL Soft library compiled statically and linked into the executable

> Cleaning latest build
---------------------------
cmd /c IF EXIST arkanoid.exe del /F arkanoid.exe
Process started >>>
C:\Users\Manop\Documents\Visual Studio 2017\Projects\raylib\games\arkanoid.exe
Access is denied.
<<< Process finished. (Exit code 0)

> Compiling program
-------------------------
gcc -o arkanoid.exe arkanoid.c -s C:\raylib\raylib\raylib_icon -Iexternal -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,-allow-multiple-definition -Wl,--subsystem,windows>

**Comment by raysan5** [comment]
Sorry, don't know why it happens, it seems some kind of system security issue... Maybe current user has some usage restrictions on the computer.

None of my students had this problem with latest raylib version, neither in the school or at home... :(

**Comment by raysan5** [comment]
Just closing this issue because it seems related to the environment and not the library code itself.

Please, feel free to continue discussion on raylib forum: http://forum.raylib.com/
