### ISSUE TITLE
[core] RPI Opengl - Wrong DRM connector?

### ISSUE THREAD

**Issue by colesnicov** [raysan5/raylib#3946]
### Issue description

I got have a same display and have has same the problem like his one: https://www.reddit.com/r/raylib/comments/ykmke0/raylib_on_1280x400_hdmi_screen_w_fbconrotate3/

When I run core_basic_window, everything is fine, well almost. I had to edit the examples, change the size (width) of the window in them from 800 px to a smaller one. My display is in a vertical position, so it is 400 px wide. when I try to create a window in the program that is larger than the screen resolution, instead of one window, 4 small ones are displayed, which in addition slowly disappear in black, and then only some text and letters are visible... <s>When I adjusted the window size to 400px, everything works.</s> When I adjusted the window size to 300px, so everything works. 

Here is the output at 300px width:

```
denis@raspberrypi:~/dev/raylib/examples $ ./core/core_basic_window 
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: NATIVE DRM
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
INFO: DISPLAY: Selected DRM connector mode 384x1280 (384x1280p@62)
INFO: DISPLAY: Upscaling required: Screen size (300x450) smaller than display size (384x1280)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 384 x 1280
INFO:     > Screen size:  300 x 450
INFO:     > Render size:  300 x 450
INFO:     > Viewport offsets: 0, 550
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorWidth() not implemented on target platform
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorHeight() not implemented on target platform
WARNING: SetWindowPosition() not available on target platform
INFO: GL: Supported extensions count: 59
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: VC4 V3D 2.1
INFO:     > Version:  OpenGL ES 2.0 Mesa 23.2.1-1~bpo12+rpt3
INFO:     > GLSL:     OpenGL ES GLSL ES 1.0.16
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC1 compressed textures supported
INFO: INPUT: Initialized input device /dev/input/event1 as keyboard
INFO: INPUT: Initialized input device /dev/input/event0 as mouse
WARNING: DRM: Failed to change keyboard mode, an SSH keyboard is probably used
INFO: PLATFORM: DRM: Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
```
 

But if I set the size to 400px, which is the physical resolution of my monitor, it's screwed, 
here is the output:

```
denis@raspberrypi:~/dev/raylib/examples $ ./core/core_basic_window 
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: NATIVE DRM
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
INFO: DISPLAY: Selected DRM connector mode 1280x720 (1280x720p@100)
INFO: DISPLAY: Upscaling required: Screen size (400x450) smaller than display size (1280x720)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1280 x 720
INFO:     > Screen size:  400 x 450
INFO:     > Render size:  400 x 450
INFO:     > Viewport offsets: 400, 0
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorWidth() not implemented on target platform
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorHeight() not implemented on target platform
WARNING: SetWindowPosition() not available on target platform
INFO: GL: Supported extensions count: 59
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: VC4 V3D 2.1
INFO:     > Version:  OpenGL ES 2.0 Mesa 23.2.1-1~bpo12+rpt3
INFO:     > GLSL:     OpenGL ES GLSL ES 1.0.16
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC1 compressed textures supported
INFO: INPUT: Initialized input device /dev/input/event1 as keyboard
INFO: INPUT: Initialized input device /dev/input/event0 as mouse
WARNING: DRM: Failed to change keyboard mode, an SSH keyboard is probably used
INFO: PLATFORM: DRM: Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
```

### Environment

Raspberry PI 2B, Raspberry OS LITE

### Code Example

I used sample examples. I just changed the width of the window from 800px to 400px or to 300px.

### Append

I checked it now. 400px doesn't work but 300px does. 

I'm wondering if it's not the fault of the 'underscan' (black border around the screen) that it detects wrongly? In `raspi-config => Display Options => D1 Underscan` I do not have compensation enabled.

P.S. https://www.reddit.com/r/raylib/comments/ykmke0/raylib_on_1280x400_hdmi_screen_w_fbconrotate3/   The file you refer to has already been edited a lot and I can't imagine what happened there.

**Comment by colesnicov** [comment]
Underscan is NOT that. Cause i've not installed X..

```
$sudo raspi-config 
/usr/bin/raspi-config: 428: xrandr: not found
/usr/bin/raspi-config: 457: xrandr: not found
/usr/bin/raspi-config: 460: xrandr: not found
/usr/bin/raspi-config: 461: xrandr: not found
sed: can't read /usr/share/dispsetup.sh: No such file or directory
```

**Comment by colesnicov** [comment]
I was wondering where is the *magic limit* beyond which it falls, it's 384px, everything above the **image is destroyed**. Because I don't have a desktop installed, I can't set the screen. Editing `underscan` in `config.txt` did not help. There are **16 pixels that are probably doing** something wrong somewhere. or I don't see.. Desktop OS detects the size well and displays the correct resolution....

**Comment by raysan5** [comment]
@colesnicov thanks for the detailed report! I'm afraid I don't know what causes this issue, maybe it could be related to the driver or the display supported resolutions... I neither have the means to reproduce or track the issue...
Please, let me know if you keep investigating it.
Maybe @michaelfiber knows what could happen...

**Comment by colesnicov** [comment]
@raysan5 

_Thanx. Sometimes, when the problem is unclear, a detailed analysis of the problem may be the only way to fix it..._

The link I wrote in the first comment, did you deal with a gentleman there, I mean **something similar?** _Which code/function in the code did you refer to?_ 

I honestly don't know how all these `DRM layers` and `layers` work, even though I've read about it. I have no idea about that. I know more about FreeRtos than about **Embedded Linux** :/  But I think you might have **the framebuffer trimming set up wrong?** 

Such things happened to me with (as an example) AVR + ssd1136 where I **wrote beyond the limits of the buffer** (physical display) and then **the pixels appeared differently on the display**..? Of course it was a mistake..

**Comment by michaelfiber** [comment]
```INFO: DISPLAY: Selected DRM connector mode 384x1280 (384x1280p@62)```

This line in the successful test means that this is one of the supported modes that was found.  It ends up all screwed up with the 400px size because it can't find a mode with a width that fits that.  raylib is depending on libdrm to provide a list of available connector modes and libdrm isn't finding one with a width of 400.  

You can use SetTraceLog to increase the logging to show you more output regarding what raylib is getting from DRM, including how many modes it is actually finding. It wouldn't shock me if it is only finding 1 mode (384x1280p@62).  

I don't know exactly how DRM figures out the modes, I *believe* it uses a formula and reads information off the device to determine what resolutions are supported. If that belief is true, then it's possible something about the drivers for this device don't play well with that formula.

**Comment by michaelfiber** [comment]
Actually it looks like the drm info should be coming from here: https://github.com/waveshare/linux-patch/blob/e9da5fc701b637f9379d89044005e3d15997802c/drivers/gpu/drm/panel/panel-waveshare-dsi.c#L98

And that looks correct...I guess?  Not sure what's happening but I do believe this could be outside the realm of raylib.

**Comment by colesnicov** [comment]
@michaelfiber 
>You can use SetTraceLog to increase the logging to show you more output regarding what raylib is getting from DRM, including how many modes it is actually finding. It wouldn't shock me if it is only finding 1 mode (384x1280p@62).


I set `SetTraceLogLevel(0);` and this what can i see:

```
denis@raspberrypi:~/dev/raylib/examples $ ./core/core_basic_window 
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: NATIVE DRM
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
TRACE: DISPLAY: Connectors found: 1
TRACE: DISPLAY: Connector index 0
TRACE: DISPLAY: Connector modes detected: 3
TRACE: DISPLAY: DRM mode connected
TRACE: DISPLAY: Searching exact connector mode for 384x450@60, selecting an interlaced mode is allowed: no
TRACE: DISPLAY: DRM Mode 0 400x1280@60 progressive
TRACE: DISPLAY: DRM Mode 1 1280x720@100 progressive
TRACE: DISPLAY: DRM Mode 2 384x1280@62 progressive
TRACE: DISPLAY: No DRM exact matching mode found
TRACE: DISPLAY: Searching nearest connector mode for 384x450@60, selecting an interlaced mode is allowed: no
TRACE: DISPLAY: DRM mode: 0 400x1280@60 progressive
TRACE: DISPLAY: DRM mode: 1 1280x720@100 progressive
TRACE: DISPLAY: DRM mode: 2 384x1280@62 progressive
INFO: DISPLAY: Selected DRM connector mode 384x1280 (384x1280p@62)
TRACE: DISPLAY: EGL configs available: 18
TRACE: DISPLAY: EGL matching configs available: 4
TRACE: DISPLAY: Using EGL config: 0
INFO: DISPLAY: Upscaling required: Screen size (384x450) smaller than display size (384x1280)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 384 x 1280
INFO:     > Screen size:  384 x 450
INFO:     > Render size:  384 x 450
INFO:     > Viewport offsets: 0, 830
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorWidth() not implemented on target platform
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorHeight() not implemented on target platform
WARNING: SetWindowPosition() not available on target platform
INFO: GL: Supported extensions count: 59
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: VC4 V3D 2.1
INFO:     > Version:  OpenGL ES 2.0 Mesa 23.2.1-1~bpo12+rpt3
INFO:     > GLSL:     OpenGL ES GLSL ES 1.0.16
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC1 compressed textures supported
INFO: INPUT: Initialized input device /dev/input/event1 as keyboard
INFO: INPUT: Initialized input device /dev/input/event0 as mouse
WARNING: DRM: Failed to change keyboard mode, an SSH keyboard is probably used
INFO: PLATFORM: DRM: Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
```

**Comment by colesnicov** [comment]
> Actually it looks like the drm info should be coming from here: https://github.com/waveshare/linux-patch/blob/e9da5fc701b637f9379d89044005e3d15997802c/drivers/gpu/drm/panel/panel-waveshare-dsi.c#L98
> 
> And that looks correct...I guess? Not sure what's happening but I do believe this could be outside the realm of raylib.

I don't develop on RPI, but for RPI (currently I'm testing, a little bit), so unfortunately I can't debug to see there. Laptop, I have a laptop for an incredible amount of money - I don't understand how it's possible, it doesn't cooperate with the HDMI output. Windows Yes, Ununtu No. ): So I can't even debug it on my laptop.

**Comment by colesnicov** [comment]
@michaelfiber maybe you're right. Maybe it's not LIBRAY's fault, but the waveshare adapter's fault. Only they (waveshare) don't have Issues enabled.

**Comment by colesnicov** [comment]
Sorry for 'spamming' but here is my config.txt:


```
denis@raspberrypi:~/dev/raylib/examples $ cat /boot/firmware/config.txt 
```

```
# For more options and information see
# http://rptl.io/configtxt
# Some settings may impact device functionality. See link above for details

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Additional overlays and parameters are documented
# /boot/firmware/overlays/README

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Automatically load initramfs files, if found
auto_initramfs=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

# Don't have the firmware create an initial video= setting in cmdline.txt.
# Use the kernel's default instead.
disable_fw_kms_setup=1

# Disable compensation for displays with overscan
disable_overscan=1

# Run as fast as firmware / board allows
arm_boost=1

# pokusil jsem se upravit rozdeleni pameti..
gpu_mem=128


[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[all]
hdmi_group=2
hdmi_mode=87
hdmi_timings=400 0 100 10 140 1280 10 20 20 2 0 0 0 60 0 43000000 3
display_rotate=3
```

**Comment by gabriel-marques** [comment]
Hello,

The problem is in the function `FindNearestConnectorMode()`  at line https://github.com/raysan5/raylib/blob/f1007554a0a8145060797c0aa8169bdaf2c1c6b8/src/platforms/rcore_drm.c#L1837-L1883

@colesnicov, you are trying to create a screen of 400x450 px but there is no exact matching DRM Mode for this resolution so we try to find the nearest matching resolution.

From the log you show, we can see that there is 3 DRM modes for your screen. 

- DRM Mode 0 400x1280@60 
- DRM Mode 1 1280x720@100
- DRM Mode 2 384x1280@62

So it starts a loop over all available DRM Modes and stores at the end of the first loop the mode 0 (the one you want) as the selected one.

Then it tests DRM Mode 1 and in order to know which DRM Mode is the nearest it does a substraction of all members (respectively : width, height and refresh rate).

So for DRM Mode 0 (selected Mode) we have:

selected nearest Width diff:  400  - 400 = 0
selected nearest Height diff: 1280 - 450 = 830

and for DRM Mode 1 we have:

new Width diff: 1280 - 400 = 880
new Height diff: 720 - 450 = 270

And if one of the new diff is smaller than nearest diff (270 < 830 in our case) it will change the nearest DRM Mode. So the new nearest DRM Mode is the 1. 

Then the upscaling will mess with the display I suppose.

Just to be sure, try to create a window of 400 x 1011 and the selected DRM Mode should be 400x1280

If you really want to have a resolution of 400x450, you will have to modifiy this function or to set the DRM Mode on the connector yourself. But still, it will upscale to the fullscreen anyway

**Comment by colesnicov** [comment]
That's exactly what I 'missed'.. That it takes up the _whole screen anyway_. I don't actually _create a window_, in this case, but **a canvas**... Okay, that would do, **I need it in full mode**, otherwise I don't need such a large display... So, no bad framebuffer, not that there isn't enough RAM, **just bad parameters I chose.**

> so in the future, in the case of DRM, choose the window size as close as possible to the screen size.
