### ISSUE TITLE
[core] rlImGUI needs a way to consume input

### ISSUE THREAD

**Issue by albertvaka** [raysan5/raylib#3953]
### Issue description

When you click inside an ImGui window, that click should be "consumed" by ImGUI and not delivered to the app (ie: `IsMouseButtonPressed()` should return `false` after that, `GetMousePosition()` should stop updating).

The current Raylib API doesn't allow this.

Corresponding issue in rlImGui: https://github.com/raylib-extras/rlImGui/issues/63

**Comment by raysan5** [comment]
@JeffM2501 you implemented rlImGUI example, did you find some way to address this issue?

**Comment by JeffM2501** [comment]
This is no how ImGui works. you are supposed to check ImGui if it wants the device input or not. The IO has want key and want mouse fields. If ImGui wants the device, it's your job not to check the underlying platform. It's not the job of rlImGui to change event states in the underlying platform. ImGui does not assume that the underlying platform even has events.
This is a user error issue not a missing feature in raylib.

**Comment by colesnicov** [comment]
@albertvaka I have a working version of rlImGui but I don't know if it suffers from this disease...
