### ISSUE TITLE
[rcore] Calls to GetRandomValue(min, max) will always return min, if not call to InitWindow()

### ISSUE THREAD

**Issue by ChinaBackGo** [raysan5/raylib#3954]
---

Please, before submitting a new issue verify and check:

 - [x ] I tested it on latest raylib version from master branch
 - [x ] I checked there is no similar issue already reported
 - [x ] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x ] My code has no errors or misuse of raylib

### Issue description

Multiple calls to GetRandomValue without a call to InitWindow() first will always yield the min value. For example: 

GetRandomValue(10, 100);
GetRandomValue(10, 100);
GetRandomValue(10, 100);
GetRandomValue(10, 100);

will always yield 10.

Expected behaviour even without setting the seed would yield a number other than 10.

### Environment

Windows 11

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/7291102/507a6c89-c813-44b4-85a4-b1b2dacb24b4)

### Code Example

```
#include "raylib.h"
#include "raymath.h"


int main() {
    
/*
const int screenWidth = 800;
const int screenHeight = 450;
InitWindow(screenWidth, screenHeight, "raylib [core] - GetRandomValue bug");
*/
    int rand = 0;
    for (int i = 0; i < 10; i++)
    {
        rand = GetRandomValue(10, 100);
        printf("Rand %d\n", rand);
    }

}
```

**Comment by raysan5** [comment]
@ChinaBackGo Fixed!
