### ISSUE TITLE
Maybe possibly Invalid Default Texture?

### ISSUE THREAD

**Issue by MicroRJ** [raysan5/raylib#3959]
https://github.com/raysan5/raylib/blob/f1007554a0a8145060797c0aa8169bdaf2c1c6b8/src/rshapes.c#L104

Is this code meant to reset the texture to the default texture loaded by? 

RLGL.State.defaultTextureId

or is the user expected to do so with rlGetTextureIdDefault()?

Thanks ray.

**Comment by colesnicov** [comment]
Are you looking at the documentation? 

This function https://github.com/raysan5/raylib/blob/f1007554a0a8145060797c0aa8169bdaf2c1c6b8/src/rshapes.c#L97 
In the case of an invalid texture, the function will load the default. In the case of an invalid texture, the function will load the default. RayLib does not return error codes, does not use enums. It has its default behavior defined, how it behaves in the event of a failure. In this function, it loads a default, mostly empty texture.


That's a constructor:

```
(Texture2D){ 1, 1, 1, 1, 7 }
```

create a new texture with `#ID 1`, `width 1`, `height 1`, `mipmap 1` and `format 7`.

**Comment by MicroRJ** [comment]
Thanks @colesnicov , so what I get from this is that the "default" texture as term is used here, does not refer to RLGL.State.defaultTextureId which is the actual default texture?

**Comment by colesnicov** [comment]
> Thanks @colesnicov , so what I get from this is that the "default" texture does not refer to RLGL.State.defaultTextureId which is the actual default texture.

_I don't see it now, really. I've been here for a few days. And I haven't looked into the source yet..._

 But I think `RLGL.State.defaultTextureId` is the texture **ID which can be '1' which is the texture ID** in this function:

> That's a constructor:
> ```
> (Texture2D){ 1, 1, 1, 1, 7 }
> ```
> create a new **texture with #ID 1**, width 1, height 1, mipmap 1 and format 7.

This means that it _can easily be the default texture_.

 It depends on the implementation. If the indexing starts with 0 or if it starts with 1 and 0 it means an error.. 

**Someone more knowledgeable has to answer.**

**Comment by colesnicov** [comment]
As you can see here : https://github.com/raysan5/raylib/issues/3962
> `UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable.`

Cite: `using zero texture because texture unloadable.`.

It seems that the texture with **ID 0 is the default texture** that is uploaded in case of failure? But in the function you pointed to, the ID of the texture **is set, in case it is faulty, to 1**. Which probably won't be the default texture. **Could it be a mistake? **

Hopefully @rayson5 will be surprised.

**Comment by raysan5** [comment]
@MicroRJ @colesnicov Texture ID 1 is a default internal raylib texture, a 1x1 pixel white texture (`RLGL.State.defaultTextureId`). [OpenGL does not support 0 as a valid texture Id](https://stackoverflow.com/questions/1108589/is-0-a-valid-opengl-texture-id).
