### ISSUE TITLE
[rcore] Replay record finish can't stop move (always keydown)

### ISSUE THREAD

**Issue by Angluca** [raysan5/raylib#3964]
[my test example](https://pixeller.codeberg.page/test/myapp2/)
You can test replay record , Replay finish must input move key(```A/D or LEFT/RIGHT```) if I want stop
This is I learning raylib ```core_automation_events``` example

And how to disable player keyboard input when I replay record time. T_T Sorry I'm newbie, Don't know more...

**Comment by raysan5** [comment]
@Angluca Thanks for reporting! At this moment it's not possible to disable user inputs from raylib but it could be a feature to consider... the only issue I see is how they could be enabled again if no inputs are processed? Maybe allowing a special key combination to re-enable...
About this issue, again, there is no mechanism on raylib exposed to users to reset key states, it is always processed internally. Some alternatives are being considered in that regards...

**Comment by raysan5** [comment]
Closing this issue, no mechanism is exposed at the moment to force/generate input events by user.
