### ISSUE TITLE
Deploy AppVeyor Windows artifacts to Github releases page

### ISSUE THREAD

**Issue by a3f** [raysan5/raylib#397]
While the Github release deployment [worked](https://github.com/raysan5/raylib/releases/tag/1.9.0-dev), AppVeyor bails with a HTTP 401 error.

The [documentation](https://www.appveyor.com/docs/deployment/github/#provider-settings) says:

> Repository name (repository) - Optional. Allows to deploy into repository other than project’s one. **_Note that if this repository is under another owner, GitHub authentication token should be generated under that owner too_**. Use owner/repo format.

So @raysan5, you'd have to do the following:

* Generate a new personal access token with only the scope `public_repo` checked at https://github.com/settings/tokens
* Get a secure key by pasting the access token into https://ci.appveyor.com/tools/encrypt
* Edit line 57 in `appveyor.yml` to `      secure: paste_your_64_character_long_secure_key`
* Edit `CMakeLists.txt` `PROJECT_VERSION` to `1.9.1-dev`?
* Push
* Delete the existing `1.9.0-dev` release on Github and create a `1.9.1-dev` release [1]
* ...
* Profit!

This will also fix the AppVeyor build error.

[1]: I screwed up a little, users who pulled the repository between UTC 21:36 and 22:03 will have a different `1.9.0-dev` tag than what's upstream. It shouldn't impact normal git usage, but to avoid mix-ups, I would say remove `1.9.0-dev` upstream and have a jump to `1.9.1-dev`.

**Comment by raysan5** [comment]
Done! Let's see the magic happening! :D

**Comment by a3f** [comment]
Looks good. Closing :)
