### ISSUE TITLE
[rcore] `ToggleFullscreen()` not working as expected with HighDPI mode enabled

### ISSUE THREAD

**Issue by fishbowlforever** [raysan5/raylib#3972]
when enabling the highDPI flag in raylib (SetConfigFlags(FLAG_WINDOW_HIGHDPI);) and using ToggleFullscreen(); the fullscreen Window is twice the size it should be and you only see the top left quarter of your software. Toggling again will half the window size each time you toggle fullscreen until the window is gone.

![image](https://github.com/raysan5/raylib/assets/139635661/4761be15-3f23-420d-b107-34389e32031d)

steps to repdroduce:
SetConfigFlags(FLAG_WINDOW_HIGHDPI); on a high dpi monitor
call ToggleFullscreen(); 

I am using Windows 11

**Comment by raysan5** [comment]
@fishbowlforever Thanks for reporting, could you reproduce this issue on Windows 10? It sounds like platform dependant...

In any case, I'm afraid I don't have a HighDPI monitor at the moment for testing on my side...

**Comment by M1NGS** [comment]
> @fishbowlforever Thanks for reporting, could you reproduce this issue on Windows 10? It sounds like platform dependant...
> 
> In any case, I'm afraid I don't have a HighDPI monitor at the moment for testing on my side...

set display scaling to 125% enough

**Comment by SoloByte** [comment]
I am experiencing the same issue as well. I made a simple raylib cs project to test all of the following things.

  
When in windowed mode the render size is 2x the screen size, which is correct for retina/high dpi screens. (dpi value shows up as 2, 2 as well)

Setting the high dpi config flag has no effect on my system. I have tested it without setting it and with setting it before & after InitWindow.


### There are 3 types of fullscreen mode:

- Fullscreen (normal Fullscreen Mode)
- Borderless Fullscreen (behaves like maximize window on macOS)
- MacOS Fullscreen (clicking green button top left corner)

  

### MacOS Fullscreen works almost correctly. 

1. DPI value is 1, 1 instead of 2, 2 but everything looks correctly. I don’t know if this is correct behavior because the macOS scaling factor for retina/ high dpi is always 2!
2. Screen size and render size are the same (dpi factor of 1, 1) but it renders over the entire screen

  <img width="1920" alt="macOS-fullscreen-mode" src="https://github.com/raysan5/raylib/assets/34277803/4e446a26-8a16-4e87-bda8-56bcadf30948">


### Borderless fullscreen behaves almost correctly as well.

1. Render Size is 2x of the screen size and values are correct for the monitor I am using (dpi factor is 2, 2)
2. Window is cut off at the top even though numbers are correct (looks more like a maximized window)
<img width="1920" alt="borderless-fullscreen-mode" src="https://github.com/raysan5/raylib/assets/34277803/1629139c-e12b-4880-a164-c1cf2ef88c93">


### Fullscreen is were things get complicated. 

1. To have fullscreen mode work at all the window size must be set to the current monitor size before enabling fullscreen. 
2. DPI value is suddenly 1, 1 instead of 2, 2 like with the macOS fullscreen mode but it looks wrong too.
3. It seems to only render a quarter of the screen
4. The screen size value is off, it should be the monitor size
5. Screen size and render size should be the same with a dpi factor of 1, 1 but screen size value is off (point 4)
<img width="1920" alt="fullscreen-mode" src="https://github.com/raysan5/raylib/assets/34277803/97c63851-b8d1-474d-a708-100dab36338b">

### Windowed Mode for comparison
<img width="817" alt="windowed-mode" src="https://github.com/raysan5/raylib/assets/34277803/f869cb70-7f23-4691-bc12-eefb46f16466">


**The good news is that all the fullscreen modes work & behave the same no matter what resolution I set in the macOS display settings**


Similar issues with fullscreen:

- Borderless fullscreen & fullscreen behave differently on macOS vs windows. (Borderless Fullscreen works flawless on windows and is my preferred fullscreen mode on windows, but it is more like maximize window on macOS; Fullscreen almost works on macOS because of the above issue, but on windows it takes a up to 1-2 seconds to apply with flickering and black screens in between)
- Borderless fullscreen remembers the previous window state and applies it correctly when exiting borderless fullscreen but normal fullscreen does not.

**Comment by SoloByte** [comment]
If I multiply the monitor size by 2 before entering fullscreen another weird thing happens...
```
var monitor = GetCurrentMonitor();
SetWindowSize(GetMonitorWidth(monitor) * 2, GetMonitorHeight(monitor) * 2);
ToggleFullscreen();
```

The monitor size should be 1920x1080 before entering fullscreen (my target resolution on a 4k monitor). If I multiply this by 2 I should get the 4k resolution and if I then set the window size to the 4k resolution and enter fullscreen (were the dpi value is suddenly 1) I expect those value:
- ScreenSize 4k
- RenderSize 4k (because dpi is 1)
- MonitorSize 4k (because dpi is 1)

Why is only width affect and height suddenly not? :)

![scaled-fullscreen](https://github.com/raysan5/raylib/assets/34277803/a50f6776-6042-4b8f-a725-4f719b469ae7)

**Comment by SoloByte** [comment]
## Windows

I have tested fullscreen & high dpi functionality on windows 11 with a 4k monitor as well. I have set the scaling to 200% in settings. I have also tested everything with the scaling set to 100%. If something is not clear or I did something wrong or missed a step, please feel free to correct me. 

  

### Windowed

- Screen Size: 800x800
- Render Size: 800x800
- Monitor Size: 3840x2160
- DPI: 2,2

  

### Maximized

- Screen Size: 3840x2019
- Render Size: 3840x2019
- Monitor Size: 3840x2160
- DPI: 2,2

  

### Borderless Fullscreen

- Screen Size: 3840x2160
- Render Size: 3840x2160
- Monitor Size: 3840x2160
- DPI: 2,2

  

### Fullscreen

- Screen Size: 3840x**2119 !!!**
- Render Size: 3840x2160
- Monitor Size: 3840x2160
- DPI: 2,2

  

  

#### I have tested everything with a 100% scaling on a 4k monitor as well. Everything works but it reported the exact same values as with a scaling of 200%.

  

### My findings:

- On Windows the dpi value is always correct. No matter the window mode it always reports the scaling set in the settings. On macOS it reports the correct value except in fullscreen mode were it always reports 1, 1.
- On windows the monitor size always reports the native resolution of the monitor independent of the system scaling. On macOS it DOES NOT behave this way. Most of the times it is the monitor resolution divided by the scaling or it something weird in the fullscreen modes.
- On windows & macOS the high dpi config flag had no impact on anything as far as I can tell. I have tested it without setting it, with setting it before & after init window, and with clearing it before & after init window. If I did something wrong or missed something please correct me.
- On windows the screen & render size are always the same even if there is dpi scaling. On macOS the render size is always multiplied by the dpi value.
- On windows the size of the window always covers the same area with the same size. Example: On a 4k monitor with scaling of 200% a window of the size 1920x1080 covered 1/4 of the screen. On a 4k monitor with scaling of 100% a window if the size 1920x1080 covered 1/4 of the screen as well. In my opinion that dpi scaling makes sense the a 1920x1080 window should cover the entire screen on a 4k monitor with scaling set to 200%.

  

### Screen Size, Render Size, Monitor Size

The following things are what I understand about screen size, monitor size, and render size. I do not know if I am correct at all. My main goal here is to figure out together what each of this numbers should represent independent of the the operating system.

1. Monitor Size should always report the native resolution of the monitor unaffected by any scaling ?
2. The dpi value should always report the dpi scaling of the system irregardless of the window mode. (windowed & fullscreen should report the same dpi value)?
3. The screen size should be the actual size of the window ? Does this mean it should be in native resolution or in scaled resolution? Should a window covering 1/4 of a 4k monitor with a dpi scale of 2 have a Screen Size of 1920x1080 or 960x540?
4. Should the render size always be the screen size x dpi factor? Or should they be the same? (which kinda makes no sense)

  

To me personally only Example A makes sense. (on all operating systems. I do not know how scaling works on windows but on macOS it can only be 1, 1 or 2, 2. There are other combinations possible as well not just the ones from example A & B but I didn’t want to write them all down ;)

  

### Example A

- 4k monitor
- Scaling Factor 200%
    - Windowed Mode
        - Screen Size 960x540 (covers 1/4 of the screen)
        - Render Size 1920x1080
        - Monitor Size 3840x2160
        - DPI 2, 2
    - Fullscreen Mode

        - Screen Size 1920x1080 (covers entire screen because it is fullscreen)
        - Render Size 3840x2160
        - Monitor Size 3840x2160
        - DPI 2, 2

- Scaling Factor 100%
    - Windowed Mode
        - Screen Size 1920x1080 (covers 1/4 of the screen)
        - Render Size 3840x2160
        - Monitor Size 3840x2160
        - DPI 2, 2
    - Fullscreen Mode
        - Screen Size 3840x2160 (covers entire screen because it is fullscreen)
        - Render Size 3840x2160
        - Monitor Size 3840x2160
        - DPI 2, 2

  

### Example B

- 4k monitor
- Scaling Factor 200%
    - Windowed Mode
        - Screen Size 1920x1080 (covers 1/4 of the screen)
        - Render Size 1920x1080
        - Monitor Size 3840x2160
        - DPI 2, 2
    - Fullscreen Mode

        - Screen Size 3840x2160 (covers entire screen because it is fullscreen)
        - Render Size 3840x2160
        - Monitor Size 3840x2160
        - DPI 2, 2

- Scaling Factor 100%
    - Windowed Mode
        - Screen Size 1920x1080 (covers 1/4 of the screen)
        - Render Size 3840x2160
        - Monitor Size 3840x2160
        - DPI 2, 2
    - Fullscreen Mode
        - Screen Size 3840x2160 (covers entire screen because it is fullscreen)
        - Render Size 3840x2160
        - Monitor Size 3840x2160
        - DPI 2, 2

**Comment by SoloByte** [comment]
@raysan5 If you need anything else just tell me. As mentioned above I can also put all my comments in a seperate issue. If needed I can also put a zip file here with the minimal project I used to test this (all raylib cs btw).

**Comment by SuperUserNameMan** [comment]
@SoloByte : could you share a code example ?

**Comment by SoloByte** [comment]
@SuperUserNameMan Here you go :) I am very interested in your results :D

## Minimal Reproduction Example
- I used raylib cs 6.1.1 (should be easy to rewrite for c raylib)
- tested it both on windows & macOS


[minimal-reproduction-raylib-fullscreen.txt](https://github.com/user-attachments/files/16127133/minimal-reproducion-raylib-fullscreen.txt)


```
using System.Numerics;
using Raylib_cs;
using static Raylib_cs.Raylib;
using Color = Raylib_cs.Color;


namespace FullscreenTest;

public static class Program
{
    public static void Main(string[] args)
    {
        var bgColor = Raylib.ColorBrightness(Raylib_cs.Color.DarkBlue, -0.5f);
        var test = new Test(800, 800, "Test", bgColor, 60);
        test.Run();
        
    }
}

public class FullscreenTest
{
    private Font fontDefault;
    public Color BackgroundColor;
    public float DeltaTime { get; private set; } = 0f;
    public Vector2 GetScreenSize() => new Vector2(GetScreenWidth(), GetScreenHeight());
    public Vector2 GetRenderSize() => new Vector2(GetRenderWidth(), GetRenderHeight());
    public Vector2 GetDPI() => GetWindowScaleDPI();
    public Vector2 GetMonitorSize()
    {
        var monitor = GetCurrentMonitor();
        return new Vector2(GetMonitorWidth(monitor), GetMonitorHeight(monitor));
    }
    
    
    private int prevFullscreenWidth = 0;
    private int prevFullscreenHeight = 0;
    private int prevFullscreenX = 0;
    private int prevFullscreenY = 0;
    
    public Test(int width, int height, string title, Color backgroundColor, int targetFramerate = 60)
    {
        Raylib.SetWindowState(ConfigFlags.Msaa4xHint);
        Raylib.InitWindow(width, height, title);
        Raylib.InitAudioDevice();
        Raylib.ClearWindowState(ConfigFlags.VSyncHint);
        Raylib.SetTargetFPS(targetFramerate);
        Raylib.SetWindowState(ConfigFlags.ResizableWindow);
        
        fontDefault = Raylib.GetFontDefault();
        BackgroundColor = backgroundColor;
    }
    public void Run()
    {
        StartApplication();
        
        //Main loop
        while (!Raylib.WindowShouldClose())
        {
            //Update
            var dt = Raylib.GetFrameTime();
            DeltaTime = dt;
            Update(dt);
            
            //Drawing
            Raylib.BeginDrawing();
            Raylib.ClearBackground(BackgroundColor);
            Draw();
            Raylib.EndDrawing();
        }
        
        //End
        CloseApplication();
        Raylib.CloseAudioDevice();
        Raylib.CloseWindow();
    }
    
    
    protected virtual void Update(float dt)
    {
        //I am not checking if fullscreen is already active when pressing borderless fullscreen and vice versa.
        
        //Fullscreen
        if (IsKeyPressed(KeyboardKey.F))
        {
            if (IsWindowFullscreen())
            {
                ToggleFullscreen();
                SetWindowSize(prevFullscreenWidth, prevFullscreenHeight);
                SetWindowPosition(prevFullscreenX, prevFullscreenY);
            }
            else
            {
                prevFullscreenWidth = GetScreenWidth();
                prevFullscreenHeight = GetScreenHeight();
                prevFullscreenX = (int)GetWindowPosition().X;
                prevFullscreenY = (int)GetWindowPosition().Y;
                var monitor = GetCurrentMonitor();
                SetWindowSize(GetMonitorWidth(monitor), GetMonitorHeight(monitor));
                ToggleFullscreen();
            }
            
        }
        
        //Borderless Fullscreen
        else if (IsKeyPressed(KeyboardKey.B))
        {
            ToggleBorderlessWindowed();
        }
    }

    protected virtual void Draw()
    {
        var size = GetScreenSize();
        var infoRect = new Rectangle(new(), size);
        
        //draw the border of the screen
        DrawRectangleLinesEx(infoRect, 4f, Color.Gray);
        
        //draw the text in the center
        DrawScreenInformation(infoRect, 50, Color.Lime);
    }
    
    protected virtual void StartApplication() { }
    protected virtual void CloseApplication() { }
    
    private void DrawScreenInformation(Rectangle rect, int fontSize, Color color)
    {
        var sw = GetScreenWidth();
        var sh = GetScreenHeight();

        var rw = GetRenderWidth();
        var rh = GetRenderHeight();

        var dpi = GetWindowScaleDPI();

        var monitor = GetCurrentMonitor();
        var mw = GetMonitorWidth(monitor);
        var mh = GetMonitorHeight(monitor);

        var text1 = $"Screen {sw}x{sh} | Render {rw}x{rh}";
        var text2 = $"Monitor {mw}x{mh} | DPI {dpi}";

        var textSize1 = MeasureTextEx(fontDefault, text1, fontSize, 1f);
        var textSize2 = MeasureTextEx(fontDefault, text2, fontSize, 1f);


        var width = rect.Size.X * 0.75f;
        if (textSize1.X > textSize2.X)
        {
            if (textSize1.X > width)
            {
                var f = width / textSize1.X;
                fontSize = (int)(fontSize * f);
                textSize1 = MeasureTextEx(fontDefault, text1, fontSize, 1f);
                textSize2 = MeasureTextEx(fontDefault, text2, fontSize, 1f);
            }
        }
        else
        {
            if (textSize2.X > width)
            {
                var f = width / textSize2.X;
                fontSize = (int)(fontSize * f);
                textSize1 = MeasureTextEx(fontDefault, text1, fontSize, 1f);
                textSize2 = MeasureTextEx(fontDefault, text2, fontSize, 1f);
            }
        }
        
       
        
        var rectCenter = rect.Position + (rect.Size / 2);
        var textPos1 = rectCenter - (textSize1 / 2);
        var textPos2 = rectCenter - (textSize2 / 2);
        DrawText(text1, (int)textPos1.X, (int)textPos1.Y, fontSize, color);
        DrawText(text2, (int)textPos2.X, (int)(textPos2.Y + textSize1.Y), fontSize, color);
    }
}
```

**Comment by SuperUserNameMan** [comment]
OMG ! Yuck ! C# ! I feel like someone barfed into my eyes X-(

I hope this is what you meant :

```C
#include "raylib.h"


void update();
void draw();

int main( int argc , char **argv )
{
    SetWindowState( FLAG_MSAA_4X_HINT );

    InitWindow( 800 , 800 , "Test" );

    ClearWindowState( FLAG_VSYNC_HINT );

    SetTargetFPS( 60 );

    SetWindowState( FLAG_WINDOW_RESIZABLE );

    while( ! WindowShouldClose() )
    {
        update();

        BeginDrawing();
        {
            ClearBackground( RAYWHITE );
            draw();
        }
        EndDrawing();
    }

    CloseWindow();
}

void update()
{
    // He said he does not check if fullscreen is already active 
    // when pressing borderless fullscreen and vice versa.

    static int prevFullscreenWidth = 0;
    static int prevFullscreenHeight = 0;
    static int prevFullscreenX = 0;
    static int prevFullscreenY = 0;

    // Fullscreen :
    if ( IsKeyPressed( KEY_F ) )
    {
        if ( IsWindowFullscreen() )
        {
            ToggleFullscreen();
            SetWindowSize( prevFullscreenWidth , prevFullscreenHeight );
            SetWindowPosition( prevFullscreenX , prevFullscreenY );
        }
        else
        {
            prevFullscreenWidth  = GetScreenWidth();
            prevFullscreenHeight = GetScreenHeight();

            prevFullscreenX = (int)GetWindowPosition().x;
            prevFullscreenY = (int)GetWindowPosition().y;

            int monitor = GetCurrentMonitor();

            SetWindowSize( GetMonitorWidth(monitor) , GetMonitorHeight(monitor) );

            ToggleFullscreen();
        }
    }
    else // Borderless Fullscreen :
    if ( IsKeyPressed( KEY_B ) )
    {
        ToggleBorderlessWindowed();
    }
}

void draw()
{
    int sw = GetScreenWidth();
    int sh = GetScreenHeight();

    int rw = GetRenderWidth();
    int rh = GetRenderHeight();

    Vector2 dpi = GetWindowScaleDPI();

    int monitor = GetCurrentMonitor();

    int mw = GetMonitorWidth( monitor );
    int mh = GetMonitorHeight( monitor );


    Rectangle infoRect = { 0.0 , 0.0 , sw , sh };

    // Draw the border of the screen :
    DrawRectangleLinesEx( infoRect , 4.0f , RED );

    // Draw the text NOT in the center :

    DrawText( TextFormat( "Screen : %d x %d" , sw , sh ) , 10 , 10 , 30 , BROWN );
    DrawText( TextFormat( "Render : %d x %d" , rw , rh ) , 10 , 40 , 30 , DARKGREEN );
    DrawText( TextFormat( "Monitor : %d x %d" , mw , mh ) , 10 , 70 , 30 , DARKBLUE );
    DrawText( TextFormat( "DPI : %f x %f" , dpi.x , dpi.y ) , 10 , 100 , 30 , BLACK );
}
```

**Comment by SuperUserNameMan** [comment]
I confirm there is ALSO multiple issues on Linux.

When `SetConfigFlags( FLAG_WINDOW_HIGHDPI )` is enabled :

-  `GetWindowScaleDPI()` returns `{ 1.145833 , 1.145833 }` despite my display scale is set to 100%.

- when toggling fullscreen, `GetRenderWidth()` and `GetRenderHeight()` still return 1920x1080, despite the render surface extends beyond the screen with an actual dimension of 2268 x 1237.

**Comment by SuperUserNameMan** [comment]
Edit : ok, i'm currently proceeeding to various test on a mode simplified example, because there seems to be many other issues related to both `ToggleFullscreen()` and `FLAG_WINDOW_HIGHDPI` also on Linux. (using GLFW backend)

**Comment by SuperUserNameMan** [comment]
Ok so if I replicated @fishbowlforever issue correctly, and if @fishbowlforever uses the GLFW backend, i think the culprit is here :

https://github.com/raysan5/raylib/blob/9764fef26260e6fcf671ddffb230360cc1efa1f8/src/platforms/rcore_desktop_glfw.c#L1670-L1682

I think that it is not required to divide by `windowScaleDPI` because GLFW already handles that with `glfwWindowHint(GLFW_SCALE_TO_MONITOR, GLFW_TRUE); ` set here :

https://github.com/raysan5/raylib/blob/9764fef26260e6fcf671ddffb230360cc1efa1f8/src/platforms/rcore_desktop_glfw.c#L1300-L1310

@fishbowlforever , can you recompile Raylib to test this fix on your Windows OS ?

In file `raylib/src/platforms/rcore_desktop_glfw.c`, you just have to replace line 1671 with a `if (0)` to disable the suspect branch.

```C
    // if ((CORE.Window.flags & FLAG_WINDOW_HIGHDPI) > 0)
    if (0)
    {
        Vector2 windowScaleDPI = GetWindowScaleDPI();

        CORE.Window.screen.width = (unsigned int)(width/windowScaleDPI.x);
        CORE.Window.screen.height = (unsigned int)(height/windowScaleDPI.y);
    }
    else
    {
        CORE.Window.screen.width = width;
        CORE.Window.screen.height = height;
    }
```

**Comment by fishbowlforever** [comment]
@SuperUserNameMan thanks a lot for your suggestion and research
I compiled RL with your suggestion like this:
![image](https://github.com/raysan5/raylib/assets/139635661/e19899fb-92f5-40dd-ad70-0bd8b48f9671)

Fullscreen works like a charm now!

The only issue left is that, when disabling Fullscreen, the window only displays the top left quarter of the screen. This does not increment to 4x, 8x, 16x, etc. like it previously did though.
![image](https://github.com/raysan5/raylib/assets/139635661/14d099c1-4fb3-4360-945f-2c5848f62d6a)

**Comment by SuperUserNameMan** [comment]
@fishbowlforever : Did you use the code example i provided ?
If not, could you please share a minimal code example of your own so i can see if there is something special that triggers this behavior ?

**Comment by SoloByte** [comment]
@SuperUserNameMan can confirm that disabling resizable flag before entering fullscreen helps & can´t test it on macOS because I am not set up for raylib development.

@raysan5 should I open new issues for the other problems I have found mention above?

**Comment by SuperUserNameMan** [comment]
@SoloByte : It change nothing for Macos. There should be no diff.

**Comment by raysan5** [comment]
@SoloByte @SuperUserNameMan Thank you very much for the extensive review of this issue, full-screen and high-dpi are big concerns on raylib that despite being reviewed many many times, still have issues, mostly platform and OS dependant...

 > @raysan5 should I open new issues for the other problems I have found mention above?

@SoloByte Yes, please, I think it would be easier to track the issues separately (despite being highly dependant). If you want I can also reopen this issue for reference.

**Comment by SoloByte** [comment]
@SuperUserNameMan @fishbowlforever 
I am currently investigating the fullscreen & borderless fullscreen issues. What I have found is that fullscreen mode sets the window size to the current screen size before entering fullscreen instead of setting it to the monitor size. (Borderless fullscreen sets the window size to the monitor size) Setting the window size calls the window resized callback and before fix #4143 it would then scale the current window size further down each time fullscreen is exited. 

I think this loop may also causes the issue that is still there with the 1/4 of the screen in the topleft. 

@raysan5 I will open a new issue for fullscreen / borderless fullscreen mode & 1 issue for the screen/render/monitor size confusion with the dpi scale ?

**Comment by SuperUserNameMan** [comment]
@SoloByte : if i deciphered your C# code example, it seems that you have enabled `ResizableWindow`. 
On my Linux tests, i found that enabling resizable window at the same time as using `ToggleFullscreen()` create some unexpected behaviors.
Could you try disabling `ResizableWindow` before any call to `ToggleFullscreen()` and tell me if it improves things ?

**Comment by raysan5** [comment]
Adding @JeffM2501 to the loop, I remember he had some ideas about `ToggleFullscreen()`/`ToggleFullscreenBorderless()`.

**Comment by raysan5** [comment]
@SoloByte I'm reopening to continue the dsicussion but feel free to open separate issues for related problems.

**Comment by SuperUserNameMan** [comment]
@SoloByte  :

> @SuperUserNameMan can confirm that disabling resizable flag before entering fullscreen helps & can´t test it on macOS because I am not set up for raylib development.

I've just noticed i misinterpreted your answer. 
Yes, disabling resizable flag before toggling to fullscreen should help too, and might have an effect on Macos too. 

However, did you recompile Raylib with the new patch #4143 that was merged a few minutes ago ?

**Comment by SoloByte** [comment]
@SuperUserNameMan I have not tested it with the new patch

**Comment by SuperUserNameMan** [comment]
> @SuperUserNameMan I have not tested it with the new patch

ok then, let's start again from a fresh code base then.

**Comment by SoloByte** [comment]
@SuperUserNameMan @fishbowlforever 

The window resize callback also calls [SetupViewport](https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/rcore.c#L3181C1-L3192C7) which introdues dpi scale again. I don‘t know if that causes any problems though.

> What I have found is that fullscreen mode sets the window size to the current screen size before entering fullscreen instead of setting it to the monitor size. (Borderless fullscreen sets the window size to the monitor size)
Setting the window size calls the window resized callback and before fix #4143 it would then scale the current window size further down each time fullscreen is exited.

**Comment by SoloByte** [comment]
> > @SuperUserNameMan I have not tested it with the new patch
> 
> ok then, let's start again from a fresh code base then.

I agree but just for clarification, I have tested it on macOS with the same project as above. The patch you did should not have affected macOS anyway, correct?

**Comment by fishbowlforever** [comment]
i don't know how far you are with everything and so on but i tested your provided code on win11 to the same results in case thats still useful:

![image](https://github.com/raysan5/raylib/assets/139635661/c80cfa39-918e-499c-8ade-fed3d980f3f0)

Fullscreen (F) works fantastically, but when disabling fullscreen for the first time, same issue happens as with my code.

**Comment by SuperUserNameMan** [comment]
Do you still use `FLAG_WINDOW_HIGHDPI` at the same time as `ToggleFullscreen()` ?

If yes, they are currently incompatible. 
You have to choose one or another, or replace `ToggleFullscreen()` with `ToggleBorderlessWindowed()`.

**Comment by SuperUserNameMan** [comment]
Could you please test this PR #4151 ?

**Comment by raysan5** [comment]
I'm currently redesigning `ToggleFullscreen()`/`ToggleWindowBorderless()` implementations and reviewing highDPI. I'll close this issue because there are already several issues related.
