### ISSUE TITLE
[rcore] Get keys that are pressed again, like chars

### ISSUE THREAD

**Issue by constantitus** [raysan5/raylib#3984]
### Feature request
I'm looking for a good way to get the keys that have been pressed again (repeated, like chars) on desktop.
The current way of achieving this for me is to loop through all the possible (or needed) keys and check them with IsKeyPressedRepeat(). It's a bit ugly.
I'm thinking something like `GetKeyPressedRepeat` could be added to rcore. Personally don't need to differentiate between keys that have been "just pressed" or "pressed again", but I could use it together with `GetKeyPressed`.

### Environment 
`PLATFORM_DESKTOP`, since `IsKeyPressedRepeat` is desktop only.

**Comment by raysan5** [comment]
@constantitus It has been already discussed in the past and there is no intention to add those functions for now. You should manage it at user level as you are doing, it's not ugly, it would be exactly the same done internally.
