### ISSUE TITLE
[physac] No CLOCK_MONOTONIC on macOS

### ISSUE THREAD

**Issue by a3f** [raysan5/raylib#399]
There's a `clock_get_time` function on macOS though, that uses Mach API for monotonic time.
Maybe raylib should export a GetTime function that uses `QueryPerformanceCounter` on Windows, `clock_gettime(CLOCK_MONOTONIC` on Linux/BSD and `clock_get_time` on macOS?

When this is implemented, adjust `examples/CMakeLists.txt` to build the `physac/` directory on macOS again.

**Comment by raysan5** [comment]
Right now time management on raylib for macOS is provided by GLFW3 but actually, I implemented a [`GetCurrentTime()`](https://github.com/raysan5/raylib/blob/develop/src/gestures.h#L518) on [gestures.h](https://github.com/raysan5/raylib/blob/develop/src/gestures.h) module.

I agree that function should be exposed by raylib to users.

Just implemented it on commit https://github.com/raysan5/raylib/commit/c9722161d11b250006f17de62dd9ff17e46aeed4

Need to review how to move it to `core` module...

**Comment by raysan5** [comment]
physac reviewed in commit https://github.com/raysan5/raylib/commit/f44dbf21cf4cb5e5f65be34c909192f03a5678c6

Also sent PR https://github.com/victorfisac/Physac/pull/32 to original project.
