### ISSUE TITLE
[rcore] Allow opening wayland layer surfaces with raylib

### ISSUE THREAD

**Issue by coffeeispower** [raysan5/raylib#4009]
### Issue description

I'm developing a project called [woomer](https://github.com/coffeeispower/woomer) which is a clone of [tsoding's boomer](https://github.com/tsoding/boomer) but for wayland using raylib, it allows you to zoom into your desktop using your mouse wheel and move around by dragging.

However i ran into a bit of an issue in coffeeispower/woomer#5 , which is that as it says in the issue, if you open woomer while having a fullscreen application, it makes the other application exit fullscreen mode because woomer is just a fullscreen window opened with raylib.

The solution to this is using [wayland layer surfaces](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) which are special windows that applications can open to make themselves part of the desktop like for example bars, menus, application launchers and etc, they're not tiled by tiling window managers, you can make them always appear on top of all applications and you can make them fullscreen without excluding normal windows.

I think we can probably use a config flag in SetConfigFlag, something like `SetConfigFlag(FLAG_OPEN_WAYLAND_LAYER)`

**Comment by raysan5** [comment]
@coffeeispower I'm afraid I try to avoid platform-specific code in the main raylib API but beside that, I don't know the complexity of implementing that kind of feature, raylib is not ready to support multi-window contexts.

Please, let me know if you further investigate this feature implementation.

**Comment by coffeeispower** [comment]
Well, i'm not asking to open multiple windows, what i'm asking is to be able to just change the way raylib opens the window, it's still a single window, just opened differently

**Comment by raysan5** [comment]
@coffeeispower What is the code complexity involved for this issue and how many users will really benefit from it? 
In any case, I recommend implementin this feature on user fork to cover the specific needs and after testing it can be considered for raylib.

**Comment by coffeeispower** [comment]
It's really not that complicated, i'm considering making a pull request if you would accept it.
The code complexity of it would just add a couple config flags, then pull the wayland surface handle from glfw and then use libwayland-client to convert it into a layer surface.

**Comment by coffeeispower** [comment]
About how many people will benefit from it is people who want to build widgets and parts of their wayland desktop using raylib, because raylib is a really good abstraction on top of opengl. Like a good use case would be to have a keybind on hyprland that opens a dashboard thingy with common actions, applications, system monitor and etc, if you could use raylib for that it would be kinda cool

**Comment by raysan5** [comment]
@coffeeispower If you implement it, feel free to send a PR for review but I can assure it will be accepted, but it will be reviewed.

**Comment by coffeeispower** [comment]
>  If you implement it, feel free to send a PR for review but I can assure it will be accepted

Cool! I'll do it when i can!
> but it will be reviewed

No problem, every PR has to be reviewed to match the standards of the project

**Comment by coffeeispower** [comment]
That was the worst jebait ever :skull:

**Comment by raysan5** [comment]
@coffeeispower Sorry, I did not pretend to create false expectations...

**Comment by Peter0x44** [comment]
>  The code complexity of it would just add a couple config flags, then pull the wayland surface handle from glfw and then use libwayland-client to convert it into a layer surface when opening the window. raylib already depends on libwayland-client indirectly because of glfw, so we're not going to add anymore dependencies if you're afraid of that.

We don't currently have any platform specific config flags. This feature sounds like it would be better suited for a user fork, but I'm not completely sure what is involved.

**Comment by davawen** [comment]
As someone making an application launcher with raylib (and hoping to make it wayland first), this feature would be really great!  
Of course, raysan decides what goes in, and if I have to use a user fork for it, I will.  
But, if the required code is not too complex and adds very little api surface, it would be a waste not to have it, given how useful it would be to anyone developing wayland widgets, as @coffeeispower said.

**Comment by raysan5** [comment]
@davawen if you really need it, feel free to implement it and send a PR for review.

**Comment by colesnicov** [comment]
**I agree. This functionality is essential!**

**Comment by nouritsu** [comment]
+1, I'm making a logout menu using raylib and looking to make it Wayland first. Looking at other applications like `wlogout` or `wleave`, they seem to be rendering on their own layers.

@raysan5 would it be possible to re-open this issue for better visibility?
