### ISSUE TITLE
[rtext] Issues about font loading

### ISSUE THREAD

**Issue by wangxun2008** [raysan5/raylib#4014]
### Issue description

When using the latest versions of raylib (including 5.0 and 5.1-dev), issues have been encountered when importing fonts. 
The problem arises when importing short string lengths at certain font sizes causing the last character of the string to potentially fail to import and leading to possible crashes. 
Current solutions include adding extra characters to the string and adjusting the font size.

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/88886127/07eed89b-409b-4959-b93f-4cb8dda30e13)

### Code Example

```
#include <raylib.h>
#include <bits/stdc++.h>
using namespace std;

int main() {
	
	InitWindow(800,600,"");
	int fileSize;
	unsigned char *fontFileData = LoadFileData("c:\\windows\\fonts\\simhei.ttf", &fileSize);
	int codepointsCount;
	int *codepoints=LoadCodepoints("head",&codepointsCount);
	Font font = LoadFontFromMemory(".ttf",fontFileData,fileSize,64,codepoints,codepointsCount);
	UnloadCodepoints(codepoints);
	SetTargetFPS(120);
	while (!WindowShouldClose()) {
		BeginDrawing();
		ClearBackground(WHITE);
		DrawTextEx(font,"head",(Vector2){50,50},64,5,RED);
		EndDrawing();
	}
	UnloadFont(font);
	UnloadFileData(fontFileData);
	return 0;
}
```

**Comment by wangxun2008** [comment]
> 您是否尝试打印生成的地图集以检查所需字符是否成功导出？`font.texture`
I have tried the official example ("raylib [text] example - Codepoints loading").  The final character doesn't seem to have been successfully exported.
![image](https://github.com/raysan5/raylib/assets/88886127/3fe43865-4814-41ea-bdde-4cf4ffe95c01)

**Comment by wangxun2008** [comment]
![image](https://github.com/raysan5/raylib/assets/88886127/73b05ba3-5678-4e53-a659-d09ec8f5e411)

This is another official example. issues arise when shortening the string length and adjusting the font size to 64.

**Comment by raysan5** [comment]
@wangxun2008 Thanks for sharing, the issue is actually on the algorithm that calculates the font texture atlas size required to fit all the glyphs. You can just [uncomment this line](https://github.com/raysan5/raylib/blob/master/src/rtext.c#L766), recompile raylib and it should work.
