### ISSUE TITLE
[build] Cross-compile toolchain for RPi seems to have broken the Makefile

### ISSUE THREAD

**Issue by AudioMorphology** [raysan5/raylib#402]
I've just re-compiuled Raylib on a new, clean install of rasbian Stretch, and there seem to be a few issues with the Makefile.

If you simple compile using 

make PLATFORM=PLATFORM_RPI 

Then it will fail saying C:/SysGCC/Raspberry/bin/arm-linux-gnueabihf-ar: command not found

This can be avoided by using the following instead:

make PLATFORM=PLATFORM_RPI  RPI_CROSS_COMPILE=NO 

but then it complains that it cannot find bcm_host.h and this is because the Include path is missing from the make file. In this section it is building the include path from the RPI_TOOLCHAIN_SYSROOT

    INCLUDE_PATHS += -I$(RPI_TOOLCHAIN_SYSROOT)/opt/vc/include
    INCLUDE_PATHS += -I$(RPI_TOOLCHAIN_SYSROOT)/opt/vc/include/interface/vmcs_h$
    INCLUDE_PATHS += -I$(RPI_TOOLCHAIN_SYSROOT)/opt/vc/include/interface/vcos/p$
    INCLUDE_PATHS += -I$(RPI_TOOLCHAIN_SYSROOT)/opt/vc/include/interface/vcos/p$

So I added the following:

    INCLUDE_PATHS += -I/opt/vc/include  

The build then completes OK, but what is probably required is not to simply presume that if PLATFORM=PLATFORM_RPI is specified, then the source is being cross-compiled under Windows but to take the opposite view - that it is being compiled natively on an RPi unless RPI_CROSS_COMPILE=YES is specified?

Richard

**Comment by raysan5** [comment]
Hi @AudioMorphology!

Are you using latest develop branch? It should be corrected there...

**Comment by AudioMorphology** [comment]
Ah. No, I was using the latest release branch. Sorry, I always forget to clone the Develop branch - I will try that. 

I will close this issue, and re-open it if necessary.

Richard
