### ISSUE TITLE
Cheatsheet Needs updated

### ISSUE THREAD

**Issue by 1NEGROUP** [raysan5/raylib#4023]
Cheatsheet has got at least one function that is incorrect, I have not come across others yet

This is the Function
void DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, float lineThick, Color color);
it should be
void DrawRectangleRoundedLinesEx(Rectangle rec, float roundness, int segments, float lineThick, Color color);
but the extended Function is not even Listed in the Cheatsheet.

I am Sorry If this is Not the Place to Post this But i Did Not Know where else to Post

**Comment by raysan5** [comment]
@1NEGROUP Usually, the cheatsheet is update on new raylib releases, it's been several months since latest release and some functions could have changed in that time.
