### ISSUE TITLE
DrawCylinder() draws overlapping geometry in certain cases

### ISSUE THREAD

**Issue by paulmelis** [raysan5/raylib#4024]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Depending on the number of `sides` passed to `DrawCylinder()` (and it looks like `DrawCylinderWires()` as well) too much geometry is drawn, in effect one angle step too many, leading to overlapping geometry  (or imprecisely placed) and z-fighting. This is noticeable when using a semi-transparent color.

Using the simple example below, with varying numbers of sides for the cylinder:

7 sides (incorrect)

![7-sides](https://github.com/raysan5/raylib/assets/1408287/26724c49-fc84-4a12-899c-40d79259b510)

8 sides (correct)

![8-sides](https://github.com/raysan5/raylib/assets/1408287/16f488dc-3174-46be-a1b0-184201fd29e9)

15 sides (correct)

![15-sides](https://github.com/raysan5/raylib/assets/1408287/4c1f3362-44b5-4ed3-b8e6-795b5d026712)

16 sides (incorrect)

![16-sides](https://github.com/raysan5/raylib/assets/1408287/476c97a2-7016-4e56-8af8-22dfc6ac08b3)

This seems to be caused by the integer math used in https://github.com/raysan5/raylib/blob/1344979c708bdf5000d8963d26d938ae4db5d771/src/rmodels.c#L520

The `rlVertex3f()` calls within the loop correctly use `360.0f/sides` for the angle step, but the (integer) base offset `i` is imprecise due to rounding.

### Environment

Arch Linux, GTX Titan V

### Issue Screenshot

See above

### Code Example

```
#include <stdlib.h>
#include "raylib.h"
#include "raymath.h"

int main(int argc, char *argv[])
{
    int sides = 16;
    if (--argc == 1) sides = atoi(argv[1]);

    InitWindow(800, 450, TextFormat("%i sides", sides));

    Camera camera = { 0 };
    // Top view (ortho)
    camera.position = (Vector3){ 0.0f, 3.0f, -3.0f }; // Camera position
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };     // Camera looking at point
    camera.up = (Vector3){ 0.0f, 0.0f, 1.0f };          // Camera up vector (rotation towards target)
    camera.projection = CAMERA_PERSPECTIVE;            // Camera mode type
    camera.fovy = 50.0f;                                 // Camera field-of-view Y (perspective); width (orthographic)

    while (!WindowShouldClose())
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);
            BeginMode3D(camera);
                DrawCylinder(Vector3Zero(), 1.0f, 1.0f, 1.0f, sides, (Color){0, 0, 255, 40});
            EndMode3D();
        EndDrawing();

        if (IsKeyPressed(KEY_S)) {
            TakeScreenshot(TextFormat("%i-sides.png", sides));
        }
    }

    CloseWindow();

    return 0;
}
```

**Comment by raysan5** [comment]
@paulmelis Oh! Good catch! Feel free to send a PR with the review!

**Comment by paulmelis** [comment]
With updated code e.g. 16 sides looks much better:

![16-sides](https://github.com/raysan5/raylib/assets/1408287/e1468428-a7d4-453a-a2d1-7c64af683c67)
