### ISSUE TITLE
[build] CMake error trying to build examples

### ISSUE THREAD

**Issue by sakunix** [raysan5/raylib#4032]
### Issue description

Trying to test the examples from the repository: https://github.com/raysan5/raylib/tree/master/examples

CMake Error at CMakeLists.txt:33 (add_if_flag_compiles):   No cmake_minimum_required command is present.  A line of code such as

### Environment

openSUSE TW, CMAKE 3.29.3, IDE Kdevelop

### Issue Screenshot
![imagen](https://github.com/raysan5/raylib/assets/22086570/b13c0e02-0577-4f2d-bcde-e94ea5619760)

### Code Example

does not have the line: cmake_minimum_required(VERSION 3.12)

**Comment by Peter0x44** [comment]
You are not supposed to invoke cmake directly on that directory, but rather the root, and use `-DBUILD_EXAMPLES=On`.
I think this is user error.

**Comment by raysan5** [comment]
@sakunix I'ma fraid I don't maintain the CMake build system, let's see if someone in the community could help on that.

**Comment by sakunix** [comment]
> You are not supposed to invoke cmake directly on that directory, but rather the root, and use `-DBUILD_EXAMPLES=On`. I think this is user error.

Thanks, in which line of the CMakeLists.txt file is that command inserted?

**Comment by sakunix** [comment]
The executables in the examples were created outside the directory where the code is.

![imagen](https://github.com/raysan5/raylib/assets/22086570/1db6023a-3293-46da-8558-ec4e75e80abe)

![imagen](https://github.com/raysan5/raylib/assets/22086570/2fbdb3ff-4ad6-420f-9888-358aab7020c1)

**Comment by Peter0x44** [comment]
@sakunix they get put in the directory you configured cmake in. That is normal, and expected.

**Comment by sakunix** [comment]
> @sakunix they get put in the directory you configured cmake in. That is normal, and expected.

Ok , thanks for the time, I'm new to cmake :D
