### ISSUE TITLE
[core] timing support

### ISSUE THREAD

**Issue by questor** [raysan5/raylib#404]
Hi,
for framerate-independent animations it would be great to have support for timing stuff (get current time in ms or something like that). There are already support-routines in core, but they're not exposed to the user.

**Comment by raysan5** [comment]
Yes, also related to https://github.com/raysan5/raylib/issues/399

Looking for best way to expose `GetCurrentTime()`, it depends on multiple platforms...

**Comment by raysan5** [comment]
`GetTime()` function exposed to user on commit https://github.com/raysan5/raylib/commit/5290390494c23055c689c183aea6d88039b0d5fb
