### ISSUE TITLE
[core] raylib-header and windows-header

### ISSUE THREAD

**Issue by questor** [raysan5/raylib#405]
when including the windows-headers and the raylib-headers I get multiple already defined symbols, "InitWindow", "CloseWindow" and "ShowCursor" (already defined in winuser.h). easiest would be to rename the raylib symbols to "InitRLWindow", "CloseRLWindow" and "ShowRLCursor", but I'm open to other suggestions, too.

**Comment by raysan5** [comment]
I know, it's a problem with windows header, I'm not renaming raylib functions because of that, you can include windows header in an independent module... or better avoid that infamous header just referencing required functions.
