### ISSUE TITLE
[rmodels] Supporting Blockbench

### ISSUE THREAD

**Issue by MrScautHD** [raysan5/raylib#4052]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Hello!
I tried the 5.1 with the new Model formats that are supported, and i saw blockbench models are very broken.
I hope you can fix that issue for blockbench models.

### Environment
Win-11, OpenGL-3.3

### Issue Screenshot
Raylib:
![image](https://github.com/raysan5/raylib/assets/65916181/7f2919dc-7796-4c67-ad68-f111f4618455)

How it should looks like:
![grafik](https://github.com/raysan5/raylib/assets/65916181/127f3147-977e-459b-b34e-2d9d2150f6b8)

**Comment by raysan5** [comment]
@MrScautHD Sincerely, I did not remember that format was even supposed to be supported and definitely not maintaining that implementation. If anyone is willing to review it, that will be welcome, if not, that format support will be removed from raylib.

**Comment by raysan5** [comment]
Blockbench models are not supported.

**Comment by MrScautHD** [comment]
> Blockbench models are not supported.

can you support it?

**Comment by raysan5** [comment]
@MrScautHD Sorry, no plans to support them.
