### ISSUE TITLE
[rtext] `TextSubText()` receives a length but scans forever for a null terminator

### ISSUE THREAD

**Issue by SpicerXD** [raysan5/raylib#4057]
Ran into this and was confused on why this is the behavior.
I would expect it to only scan for null up to the length ask for.
Not sure what it should do though if it doesn't encounter one.
Put null on the last character?

[Source](https://github.com/raysan5/raylib/blob/fffae1a975dbfff8e6c8ee37c989f5256debc90f/src/rtext.c#L1534)

**Comment by raysan5** [comment]
@SpicerXD I'm afraid I can't see the issue, it gets the textLength of provided text to verify the following parameters to not be out of that range, it's just a security check.

**Comment by raysan5** [comment]
Reviewed the function and I can't see the issue, please provided a more detailed description and an error code sample that illustrates the issue if it persists.

**Comment by sday-ssc** [comment]
Sorry, I'll be more clear.
TextSubText can be given a position and a length.
But it will first call TextLength on that source text. Which will scan for a null or segfault if it doesn't find one.
I think it'd be safer if the length check in TextSubText instead only checked for null up to position + length.
