### ISSUE TITLE
[texture] Minor issue with ImageDraw

### ISSUE THREAD

**Issue by BlueRaccoon** [raysan5/raylib#406]
I was using ImageDraw to make a kind of image-buffer for a tilemap, and I noticed that it uses the destination as an alpha mask (it does not modify destination alpha at all). This gave me trouble trying to use the function on a blank Image

I put in a fix, adding a line around 1035 of textures.c:
```
    for (int j = dstRec.y; j < (dstRec.y + dstRec.height); j++)
    {
        for (int i = dstRec.x; i < (dstRec.x + dstRec.width); i++)
        {
            // Alpha blending implementation
            dstCol = dstPixels[j*dst->width + i];
            srcCol = srcPixels[(j - dstRec.y)*dstRec.width + (i - dstRec.x)];

            dstCol.r = ((srcCol.a*(srcCol.r - dstCol.r)) >> 8) + dstCol.r;
            dstCol.g = ((srcCol.a*(srcCol.g - dstCol.g)) >> 8) + dstCol.g;
            dstCol.b = ((srcCol.a*(srcCol.b - dstCol.b)) >> 8) + dstCol.b;
            //@FIX: now accounts for source+destination alpha
            //	no longer uses destination as alpha mask
            dstCol.a = 255-(255-srcCol.a)*(255-dstCol.a)/255;
			
            dstPixels[j*dst->width + i] = dstCol;

            // TODO: Support other blending options
        }
    }
```

...unfortunately I'm very new with Github and open source projects and don't really know how to contribute, or if this is helpful.

**Comment by raysan5** [comment]
Hi @BlueRaccoon, thanks for the review.

I think I already reviewed this issue on raylib [develop branch](https://github.com/raysan5/raylib/tree/develop) of the project (that's the GitHub branch with latest improvements, enhacements and bug-corrections).

Current state of the function implements this: https://github.com/raysan5/raylib/blob/develop/src/textures.c#L1036

It was reviewed on commit https://github.com/raysan5/raylib/commit/539a9ca50eda438df66e92327990b25e8c9c59fc#diff-2b9ad86b4b0faabd6346b2799de91d35

Please, let me know if that works as expected...

**Comment by BlueRaccoon** [comment]
In fact it does work as advertised!
Also, GenImageColor on that same commit has just saved me an enormous headache.
Thanks for the response, I really enjoy the library. Doing my first actual multi-file C project right now, still navigating the waters.
