### ISSUE TITLE
[examples] Suggestion for improving the performance of the waving cubes sample

### ISSUE THREAD

**Issue by MahmoudFayed** [raysan5/raylib#4067]
Hello

While testing the performance of the waving cubes sample on my machine (using RayLib 2.5)

C version ---> 480 FPS
Python version ---> 84 FPS
Online (WebAssembly version from RayLib website) ---> 50 FPS

While our Ring programming language version (RingRayLib) was (42 FPS)
So, we did a little update by caching cubes colours in this version
https://github.com/ring-lang/ring/blob/master/samples/UsingRayLib/more/ex5_wavingcubes_withoutthreads.ring

So now we have
Ring 1.21 (32 bit) ---> 100 FPS
Ring 1.21 (64 bit) ---> 73 FPS

Suggestion: Applying the same idea in the RayLib (C Version) could increase the performance of the Online (WebAssembly version from RayLib website). 

Thanks!

**Comment by asdqwe** [comment]
Hello,

Why are you using Raylib **2.5**?

Best regards.

**Comment by MahmoudFayed** [comment]
We will update to a newer version in the next future

For now, RayLib 2.5 is already Amazing & powerful

**Comment by MahmoudFayed** [comment]
Hello

I did my tests again but using RayLib 5.0 and I am very happy with the performance improvements provided by RayLib

Using Ring 1.21 and RayLib 2.5 - 32 Bit --->   100 FPS 
Using Ring 1.21 and RayLib 2.5 - 64 Bit ---> 73 FPS

Using Ring 1.21 and RayLib 5.0 - 32 Bit --->   120 FPS   ---> EXTRA 20 FRAMES after updating RayLib version
Using Ring 1.21 and RayLib 5.0 - 64 Bit ---> 145 FPS ---> This is good that the 64bit version is faster 

Thanks

**Comment by raysan5** [comment]
Added note to the example.
