### ISSUE TITLE
[parser] No functions in the output from `raymath.h`

### ISSUE THREAD

**Issue by KislyjKisel** [raysan5/raylib#4083]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

`raylib_parser --input ../src/raymath.h` produces `raymath_api.txt` with `Functions found: 0`. It works as expected with `raylib.h`.

**Comment by Peter0x44** [comment]
Not a bug. Check what the makefile in parser/ does:

https://github.com/raysan5/raylib/blob/52f2a10db610d0e9f619fd7c521db08a876547d0/parser/Makefile#L18-L19

in particular:
`-d RMAPI`
You need to tell the parser which macro each line begins with.

Just run make in that directory if you want a setup that for sure works.

**Comment by KislyjKisel** [comment]
It works, thank you. Perhaps the command line [example](https://github.com/raysan5/raylib/blob/52f2a10db610d0e9f619fd7c521db08a876547d0/parser/raylib_parser.c#L1113-L1114) can be updated to include `-d RMAPI`?

**Comment by Peter0x44** [comment]
Nice catch, agreed.
That comment is definitely wrong. I'll handle it.
