### ISSUE TITLE
[core] `CloseWindow()` keeps an invisible window in dock, causing issues in input handling

### ISSUE THREAD

**Issue by rongcuid** [raysan5/raylib#4085]
Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

On Mac OS, after calling `CloseWindow`, an invisible, hanged window still appears (see https://github.com/glfw/glfw/issues/1766). This window still captures input events, which causes problems if a second window is to be opened.

### Environment

Mac OS 14.5 M2.

```
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Apple
INFO:     > Renderer: Apple M2
INFO:     > Version:  4.1 Metal - 88.1
INFO:     > GLSL:     4.10
```

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example

Reproduce:

```c
#include <unistd.h>
#include <raylib.h>

int main() {
	InitWindow(800, 600, "Issue");
	SetTargetFPS(60);
	while (!WindowShouldClose()) {
		BeginDrawing();
		ClearBackground(RAYWHITE);
		DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);
		EndDrawing();
	}
	CloseWindow();
	sleep(10);
	InitWindow(800, 600, "Issue");
	SetTargetFPS(60);
	while (!WindowShouldClose()) {
		BeginDrawing();
		ClearBackground(RAYWHITE);
		DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);
		EndDrawing();
	}
	CloseWindow();
	return 0;
}
```

Close the first window. Type random things before the second window appears: for best effect, include Esc. Second window opens and will freeze or close immediately.

## Suggestions

Since it's an upstream problem, is it possible to work around by draining the event queue on init/on close? Or perhaps use one of the workarounds in the GLFW issue (https://github.com/glfw/glfw/issues/1766#issuecomment-1372573552).

**Comment by asdqwe** [comment]
Hello,

If you mean directly from raylib, then I don't think so. I believe the input queue itself is managed by GLFW and just polled by raylib ([reference](https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_desktop.c#L1207-L1208)).

Try including `GLFW/glfw3.h` and calling `glfwPollEvents()` after `sleep()`, maybe that could work to empty the queue. Or try `PLATFORM_DESKTOP_SDL`.

Best regards.

**Comment by CrackedPixel** [comment]
Since the issue is in GLFW (the ticket you linked) we have to wait for them to fix it or use a different raylib core such as RGFW or SDL

**Comment by rongcuid** [comment]
I was thinking if raylib can call something right before initialize or terminate. Unfortunately I don't know enough about mac os to tell if it can be hacked around in raylib or not.

**Comment by raysan5** [comment]
I'm afraid this issue is out-of-scope of raylib but on its underlying library GLFW, anything added in raylib side would be just a patch to circunvent GLFW issue.

**Comment by raysolva** [comment]
> Since the issue is in GLFW (the ticket you linked) we have to wait for them to fix it or use a different raylib core such as RGFW or SDL.

I had no success with changing raylib core to RGFW, but have tried [RSGL](https://github.com/ColleagueRiley/RSGL) alone, which uses RGFW. Unfortunately, it seems like there is the same issue. After closing a window, it hangs, freezes, and shows not desirable behavior. 

If somebody interested, here is the code to reproduce the problem (based on `RSGL/examples/basics/text.c`): 
```
#define RSGL_IMPLEMENTATION
#include "RSGL.h"

int window_drawer__custom(void);

int main()
{
    window_drawer_custom();
    char input = '0';
    while(input!='q')
    {
        input = getchar();
        if ( (input != '\n') && input != EOF) { printf("input: %c\n", input); }
    }
    printf("finished. \n");
    return 0;
}

int window_drawer__custom(void) {
    RSGL_window* win = RSGL_createWindow("window 1", (RSGL_rect){500, 500, 500, 500}, RSGL_CENTER);

    RSGL_setFont(RSGL_loadFont("Super Easy.ttf"));
    
    for (;;) {
        RSGL_window_checkEvent(win);

        if (win->event.type == RGFW_quit)
            break;

        RSGL_drawText("Text example\nnewlines too", RSGL_CIRCLE(200, 200, 20), RSGL_RGB(255, 0, 0));
        RSGL_window_clear(win, RSGL_RGB(255, 255, 255));
    }
    
    // RSGL_window_close(win);
    printf("\nRSGL window_drawer__custom : done \n");
    
    return 0;
    }
```

When `// RSGL_window_close(win);` is uncommented, then window is normally closed, but application just finishes at that point, without going back to `main()`. 
While it stays commented, control goes back to `main()` from the function, but window stays hanging. 

So, switching to RSGL did not solve the problem, and I suppose raylib with RGFW under the hood won't do it either.

Don't know where to share that, hope it will save some time for somebody.

**Comment by ColleagueRiley** [comment]
@raysolva Could you move the issue to the RGFW repo?
