### ISSUE TITLE
[rcore] Add analogues of button press/release/down/up functions for gamepad axes

### ISSUE THREAD

**Issue by BanchouBoo** [raysan5/raylib#4091]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

A neat thing about Godot is that it lets you treat gamepad axes and buttons the same way. This means you can ask if a gamepad axis has been pressed or released or if it's being held down or not the same way you can with a button, and it also means you can ask for the value of a button (0 if it's not pressed, 1 if it is) the same way you can with an axis. The latter is obviously very trivial to implement on the user side as it just requires a simple wrapper function, but treating a gamepad axis like a button requires knowing it's previous state, so you have to track that for every axis and it becomes much more tedious to implement, so it'd be nice if it were raylib provided that functionality.

Here is a pseudo-code example for what an implementation of the idea might look like using pressed as an example.

```c
#define GAMEPAD_AXIS_POSITIVE  1.0
#define GAMEPAD_AXIS_NEGATIVE -1.0

bool IsGamepadAxisPressedInDirection(int gamepad, int axis, float threshold, float direction) {
    if (direction > 0) {
        if (previous_value < threshold && current_value >= threshold) {
            return true;
        }
    } else if (direction < 0) {
        if (previous_value > -threshold && current_value <= -threshold) {
            return true;
        }
    }
    return false;
}

bool IsGamepadAxisPressed(int gamepad, int axis, float threshold) {
    float direction = 0.0;
    if (current_value > 0) {
        direction = GAMEPAD_AXIS_POSITIVE;
    } else if (current_value < 0) {
        direction = GAMEPAD_AXIS_NEGATIVE;
    }
    return IsGamepadAxisPressedInDirection(gamepad, axis, threshold, direction);
}
```

**Comment by raysan5** [comment]
@BanchouBoo Thanks for the proposal but I prefer to keep that engine-functionality at a higher level, better on user side, than in the lower-level raylib.
