### ISSUE TITLE
[raymath] compilation issue

### ISSUE THREAD

**Issue by questor** [raysan5/raylib#411]
small compilation issue with raymath if you don't use the function declarations:
QuaternionNlerp is used (in line 1094) before it's a known function because it comes later in the source code (below, line 1123). moving the function above the first mentioned one fixes the compilation error.

**Comment by raysan5** [comment]
Good catch! Corrected in commit https://github.com/raysan5/raylib/commit/0cd327ccb253ef13a50ecf879f7bd9ebb8a7097f :)
