### ISSUE TITLE
Why mingw doesnt recognize raylib.h

### ISSUE THREAD

**Issue by JiteshTiwari10** [raysan5/raylib#4110]
gcc -o main.exe main.c function/function.c -s -static -Os -std=c99 -Wall -IC:\raylib\raylib\src -Iexternal -DPLATFORM_DESKTOP -LC:\raylib\raylib\lib -lraylib -lopengl32 -lgdi32 -lwinmm
Process started (PID=1744) >>>
function/function.c: In function 'IsMouseOverButton':
function/function.c:16:12: warning: 'Variable' may be used uninitialized in this function [-Wmaybe-uninitialized]
     return Variable;
            ^~~~~~~~
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lraylib
collect2.exe: error: ld returned 1 exit status

**Comment by raysan5** [comment]
That function does not seem to exist, you should review it.
