### ISSUE TITLE
Raylib macOS Monterey

### ISSUE THREAD

**Issue by ghostforest** [raysan5/raylib#4116]
Somehow this:

`#if defined(PLATFORM_DESKTOP)
    #define GLSL_VERSION            330
#else   // PLATFORM_ANDROID, PLATFORM_WEB
    #define GLSL_VERSION            100
#endif
`
Leads raylib to choose Version 100. I dont know why. 

Moreover these paths: "resources/shaders/glsl%i/grayscale.fs" from:

Shader shader = LoadShader(0, TextFormat("resources/shaders/glsl%i/grayscale.fs", GLSL_VERSION));

dont work on mac. I had to use absolute paths to make it work.

**Comment by raysan5** [comment]
@ghostforest how are you compiling it? are you setting the PLATFORM_DESKTOP flag? What is the working directory from which you are executing the app? I'm afraid those elements are up to the user, not raylib.
