### ISSUE TITLE
Nvidia gtx 1050 render performence is much slower than intel integrated graphics.

### ISSUE THREAD

**Issue by isubasinghe** [raysan5/raylib#412]
I am referring to the example which loads a terrain model from a heightmap png, I have found that the rendering which occurs on my intel integrated graphics is 2 times faster than the rendering on my gtx 1050. I have had no issues with my laptop prior to this, I use my laptop for gaming, and games run completely fine.

**Comment by raysan5** [comment]
Hi @isubasinghe, that's a very weird issue... please, could you provide more information?

When using GTX1050, is VSync activated in Graphic Card options?
What is the framerate in both cases, maybe 60 fps and 30 fps?
Are you setting a specific framerate with `SetTargetFPS()`?
What is the CPU performance you get in both cases?

I need some more info to track this issue...

**Comment by isubasinghe** [comment]
Ok this is very weird but now I am getting good performance on the gtx, way better than intel integrated. My laptop may just have needed a restart? 

That being said there is a another issue but i think it is small, compared to the is one anyway. 

On intel integrated graphics, the heightmap renders like this
![image](https://user-images.githubusercontent.com/28187128/33547603-b3a1efe2-d938-11e7-9978-2915986aa5a5.png)
However on nvidia it renders like this
![image](https://user-images.githubusercontent.com/28187128/33547635-cd1a6de6-d938-11e7-973e-e8bdbfa49271.png)

- Vsync is not enabled on code. I am unsure how to check Graphic card options.
- Irrelevant here but framerate is capped to 60 fps which intel and nvidia both meet.
- The cpu performance is about the same at 19%.



`

    int main()
    {
    int screenWidth = 1920;
    int screenHeight = 1080;

    InitWindow(screenWidth, screenHeight, "raylib [models] example - heightmap loading and drawing");

  
    Camera camera = {{ 18.0f, 16.0f, 18.0f }, { 0.0f, 0.0f, 0.0f }, { 0.0f, 1.0f, 0.0f }, 45.0f };

    Image image = LoadImage("resources/heightmap.png");            
    Texture2D texture = LoadTextureFromImage(image);                
    
    Mesh mesh = GenMeshHeightmap(image, (Vector3){ 16, 8, 16 });   
    Model model = LoadModelFromMesh(mesh);                        

    model.material.maps[MAP_DIFFUSE].texture = texture;             
    Vector3 mapPosition = { -8.0f, -2.0f, -8.0f };                 

    UnloadImage(image);                  
    
    SetCameraMode(camera, CAMERA_ORBITAL);  // Set an orbital camera mode

    SetTargetFPS(60);                     
  
    // Main game loop
    while (!WindowShouldClose())            // Detect window close button or ESC key
    {
 
        UpdateCamera(&camera);              // Update camera
 
   
        BeginDrawing();

            ClearBackground(RAYWHITE);

            Begin3dMode(camera);

                DrawModel(model, mapPosition, 1.0f, BROWN);

                DrawGrid(20, 1.0f);

            End3dMode();
            
            DrawTexture(texture, screenWidth - texture.width - 20, 20, WHITE);
            DrawRectangleLines(screenWidth - texture.width - 20, 20, texture.width, texture.height, GREEN);

            DrawFPS(10, 10);

        EndDrawing();
       
    }

    UnloadTexture(texture);   
    UnloadModel(model);        

    CloseWindow();              

    return 0;
}
`

**Comment by raysan5** [comment]
I see, thanks for the updated information! I already know what happens! Just remembered I got that same problem in the past... **which version of raylib are you using?** 

About the different framerates, that's related to `Sleep()` method granularity in Windows, depending on the system load, it can take longer than expected, capping your framerate to 30 fps, it's really a lottery. Just reviewed this issue several times, related on [this forum post](http://forum.raylib.com/index.php?p=/discussion/comment/251/#Comment_251) and timming system reviewed on commits https://github.com/raysan5/raylib/commit/d1c9afd1d8ae4ae3e075b117fff7a5a77f3c4d60, https://github.com/raysan5/raylib/commit/b5dd18a70c6c660c727fd1c18b13222678974a74 and https://github.com/raysan5/raylib/commit/83aba22e494ffbc78cb9cda6a8e39e82963026f4

How big is the map you're rendering?

The color issue is related to models diffuse color and shader location... actually it depends on the graphic card and the drivers behaviour, just noticed it some days ago and corrected on commit https://github.com/raysan5/raylib/commit/81518ccd130cf56c87e22800f80ffffacb2f39c3.

Please, could you try using [latest raylib develop branch](https://github.com/raysan5/raylib/tree/develop)? It should solve all those issues...

**Comment by isubasinghe** [comment]
@raysan5 I have no idea about the version I just cloned from github about 10 days ago. Ah yeah that makes, sense I had some issues with windows' sleep function before, I just assumed that there might be libraries that fixed this. Also the map I was rendering was a heightmap from a png pf size 256 x 256. Alright I will give the develop branch a shot. I will close this issue as well.
