### ISSUE TITLE
[raymath] Cannot include raymath.h in C++ source files

### ISSUE THREAD

**Issue by tomi716** [raysan5/raylib#4126]
### Issue description

Hi! I have noticed that raymath.h can not be included into C++ source files. 

raymath.h(2552,34): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
raymath.h(2553,34): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
raymath.h(2554,34): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax

I think the issue is caused because of the following lines of valid C, but invalid C++ syntax:
raymath.h:2552: float scalex = Vector3Length(**_(Vector3){ a, b, c }_**);

### Code Example

#include "raylib.h"

extern "C" {
	#include "raymath.h"
}

int main() {
	return 0;
}

**Comment by raysan5** [comment]
@tomi716 this issue is already being addressed by https://github.com/raysan5/raylib/pull/4125
