### ISSUE TITLE
RayCollision.distance from GetRayCollisionBox may be incorrect

### ISSUE THREAD

**Issue by casperbear** [raysan5/raylib#4131]
### Issue description

RayCollision object returned from GetRayCollisionBox contains incorrect distance value if Ray object passed to GetRayCollisionBox has direction value that is not normalized (i.e. Vector3Normalize wasn't applied to it).

I don't know if Ray.direction is supposed to be normalized for correct results of RayLib functions and haven't found it in any documentation.
If it is then it would make sense to expand struct comment

typedef struct Ray {
    Vector3 position;       // Ray position (origin)
    Vector3 direction;      // Ray direction (normalized)
} Ray;

If it's not, then there is a bug somewhere in GetRayCollisionBox.

using Vector3Normalize on the caller side solves the issue, it's just unclear if it's supposed approach
RayCollision rayCollision = GetRayCollisionBox(Ray{ projectile.position, Vector3Normalize(projectile.speed) }, boundingBox);

### Environment

Windows7, RayLib 5.0, Visual C++ 2019

### Code Example

```
#include <string>
#include "raylib.h"
#include "raymath.h"

int main(int argc, char* args[])
{
    InitWindow(800, 600, "GetRayCollisionBox");

    Ray ray1 = Ray{ Vector3{ 0.0f, 0.0f, 0.0f }, Vector3{ 1.0f, 0.0f, 0.0f } };
    Ray ray10 = Ray{ Vector3{ 0.0f, 0.0f, 0.0f }, Vector3{ 10.0f, 0.0f, 0.0f } };

    BoundingBox boundingBox = BoundingBox{ Vector3{ 19.0f, -1.0f, -1.0f}, Vector3{ 21.0f, 1.0f, 1.0f} };
    
    RayCollision rayCollision1 = GetRayCollisionBox(ray1, boundingBox);
    RayCollision rayCollision10 = GetRayCollisionBox(ray10, boundingBox);
    RayCollision rayCollision10N = GetRayCollisionBox(Ray{ ray10.position, Vector3Normalize(ray10.direction) }, boundingBox);

    printf("rayCollision1.distance: %f\n", rayCollision1.distance); // 19.000000
    printf("rayCollision10.distance: %f\n", rayCollision10.distance); // 1.900000 (may be incorrect)
    printf("rayCollision1N.distance: %f\n", rayCollision10N.distance); // 19.000000

    while (!WindowShouldClose())
    {
        BeginDrawing();
        ClearBackground(RAYWHITE);
        EndDrawing();
    }

    CloseWindow();

    return 0;
}
```

**Comment by raysan5** [comment]
@casperbear Please, could you provide an example illustrating this issue?

**Comment by casperbear** [comment]
@raysan5 added example cpp

**Comment by raysan5** [comment]
@casperbear Thanks for the example, I reviewed the issue and effectively the direction must be normalized.
