### ISSUE TITLE
[documentation] The Reddit badge in README.md displays "subreddit is private" even when it's not

### ISSUE THREAD

**Issue by ninadsachania** [raysan5/raylib#4133]
The Reddit badge in README.md displays "subreddit is private" even when it's not.

This may mislead newcomers.

Proof:

![image](https://github.com/raysan5/raylib/assets/22916974/76f94591-5542-4760-b33f-69e7c79b82ab)

**Comment by raysan5** [comment]
@ninadsachania I know but I don't know why or how to fix it, it seems it's related to reddit changes.

**Comment by ninadsachania** [comment]
@raysan5, I created this static badge that could work as a replacement:

[![Static Badge](https://img.shields.io/badge/-public-red?style=flat&logo=reddit&label=reddit%20r%2Fraylib)](https://www.reddit.com/r/raylib/)

Clicking on it takes you to the subreddit.

It does not have the live subscriber count, but atleast it does not mislead people.

If you like, I can create a PR for this.

**Comment by raysan5** [comment]
@ninadsachania Looks good! Feel free to send a PR.
