### ISSUE TITLE
[documentation] GetTime function is described as if it only returns full seconds, but it is not

### ISSUE THREAD

**Issue by itedya** [raysan5/raylib#4134]
### Issue description

Even though the `GetTime()` function returns double, the comment used for this function is slightly misleading (`Get elapsed time in seconds since InitWindow()`). It does not only return seconds, it returns fractions of the second as well.

This may seem like a really small thing, but when I started to look at problems with `time()` function in C, this function from raylib saved my next half an hour only because I tested if it really returns the fraction. I don't think everybody should check for this, it just should be written from the start.

### Environment

Not needed for this issue.

### Issue Screenshot

![image](https://github.com/raysan5/raylib/assets/69873350/c0eede82-4a84-4651-a779-a28b292af67d)

### Code Example

```c
TraceLog(LOG_INFO, "%f", GetTime());
```

**Comment by raysan5** [comment]
@itedya I think the description is correct, it refers to the base units returned.
