### ISSUE TITLE
[rlgl] Add unsigned int to rlSetUniform

### ISSUE THREAD

**Issue by spevnev** [raysan5/raylib#4137]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

`rlSetUniform` doesn't provide a way to set unsigned uniform, i.e. no way to call `glUniform1uiv`, `glUniform2uiv`, `glUniform3uiv`, `glUniform4uiv`.

### Environment

Computer shader with OpenGL4.3

**Comment by raysan5** [comment]
@spevnev Is this request intendedt to address a specific use-case? Or is it just for completion?
