### ISSUE TITLE
[rcore][DESKTOP_RGFW] `ToggleFullscreen()` and `ToggleBorderlessWindowed()` not working on Linux ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [raysan5/raylib#4140]
So i was testing the RGFW backend to compare with GLFW backend on my Linux, and found `ToggleFullscreen()` just does not work. 

The window is just moved to the top left corner without even resizing.

The console show : `WARNING: ToggleBorderlessWindowed() after window creation not available on target platform`

**Comment by ColleagueRiley** [comment]
This should be fixed by this PR https://github.com/raysan5/raylib/pull/4144

I'm pretty sure `ToggleFullscreen()` won't work properly unless you enable the allow resize flags (with raylib).
`SetConfigFlags(FLAG_WINDOW_RESIZABLE);`

**Comment by SuperUserNameMan** [comment]
> This should be fixed by this PR #4144
> 
> I'm pretty sure `ToggleFullscreen()` won't work properly unless you enable the allow resize flags (with raylib). `SetConfigFlags(FLAG_WINDOW_RESIZABLE);` (before the window is created)

Enabling `...RESIZEABLE` with `ToggleFullscreen` creates issues with the GLFW backend :-/

**Comment by ColleagueRiley** [comment]
I'm not sure how GLFW works, but RGFW allows resizing by default unless the RGFW_NO_RESIZE argument is passed to the createWindow function.
