### ISSUE TITLE
[rcore][DESKTOP_RGFW] `GetCurrentMonitor()` always returns `5`

### ISSUE THREAD

**Issue by SuperUserNameMan** [raysan5/raylib#4141]
On my Linux laptop without external display, it always return 5.

There might be a missing `break` in the `for` loop in the current implementation :

https://github.com/raysan5/raylib/blob/9764fef26260e6fcf671ddffb230360cc1efa1f8/src/platforms/rcore_desktop_rgfw.c#L567-L579

**Comment by ColleagueRiley** [comment]
This should be fixed by this PR https://github.com/raysan5/raylib/pull/4144
