### ISSUE TITLE
[rcore] Fullscreen & Borderless Fullscreen Problems

### ISSUE THREAD

**Issue by SoloByte** [raysan5/raylib#4145]
## Issue description
The current experience with fullscreen & borderless fullscreen is not great. Both modes have different issues on different operating systems and often have different screen / render / monitor values associated with them. My goal is to make them work consistent on all platforms.

@JeffM2501 any ideas are welcome :)

### Fullscreen Mode

- does not save window size, only window position 
- [resets window size to current window size instead of restoring previous window size](https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/platforms/rcore_desktop_glfw.c#L182C9-L182C170 "https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/platforms/rcore_desktop_glfw.c#L182C9-L182C170")
- sets window size to current screen size instead of setting it to monitor size
- it saves current window size, then sets window size to screen size which triggers resize callback 
- [This here is unnecessary because fullscreen is not possible](https://%20https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/platforms/rcore_desktop_glfw.c#L166C8-L166C132 "https://%20https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/platforms/rcore_desktop_glfw.c#L166C8-L166C132")
- vsync ?
- should apparently disable resizable window before entering fullscreen
  

### Borderless Fullscreen Mode

[Should be fixed with this.](https://github.com/raysan5/raylib/pull/4151)

- Saves window position & size correctly
- ~sets topmost flag & clears decorated flag but DOES NOT save the current flag state for restoring~
- sets window to monitor size
- ~clears topmost & sets decorated when exiting borderless fullscreen instead of restoring to previous values~
- ~there is no `IsWindowBorderlessFullscreen` (it is not really necessary but inconsistent)~

This is just what I found right now, I could be wrong about certain things and I probably also have missed some stuff.

Related Issues: 
- https://github.com/raysan5/raylib/issues/4147
- https://github.com/raysan5/raylib/issues/4146
- https://github.com/raysan5/raylib/issues/3972#issuecomment-2215478818
- https://github.com/raysan5/raylib/issues/4140
- https://github.com/raysan5/raylib/issues/3929

### Code Example

@SuperUserNameMan we can also add a new clean minimal project here

[c](https://github.com/raysan5/raylib/issues/3972#issuecomment-2214134664)
[c#](https://github.com/raysan5/raylib/issues/3972#issuecomment-2213800171)

**Comment by SuperUserNameMan** [comment]
## Borderless Fullscreen Mode
- [x] Saves window position & size correctly : **should be fixed by** #4151
- [x] sets topmost flag & clears decorated flag but DOES NOT save the current flag state for restoring **we got rid of that**
- [x] sets window to monitor size : **done i think**
- [x] clears topmost & sets decorated when exiting borderless fullscreen instead of restoring to previous values **got rid of that**
- [ ] there is no IsWindowBorderlessFullscreen (it is not really necessary but inconsistent) **what ???**

**Comment by SuperUserNameMan** [comment]
## Fullscreen Mode

- [ ] does not save window size, only window position 
    [resets window size to current window size instead of restoring previous window size](https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/platforms/rcore_desktop_glfw.c#L182C9-L182C170)
- [ ] sets window size to current screen size instead of setting it to monitor size
- [ ] it saves current window size, then sets window size to screen size which triggers resize callback 
 [This here is unnecessary because fullscreen is not possible](https://%20https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/platforms/rcore_desktop_glfw.c#L166C8-L166C132)
- [ ]  vsync ?
- [ ]  should apparently disable resizable window before entering fullscreen

**Comment by SoloByte** [comment]
> there is no IsWindowBorderlessFullscreen (it is not really necessary but inconsistent)


#### I dont know if this is relevant or needed?

---

> ## Fullscreen Mode
> * [ ]  does not save window size, only window position
> * [ ]  [resets window size to current window size instead of restoring previous window size](https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/platforms/rcore_desktop_glfw.c#L182C9-L182C170)
> * [ ]  sets window size to current screen size instead of setting it to monitor size
> * [ ]  it saves current window size, then sets window size to screen size which triggers resize callback
>   [This here is unnecessary because fullscreen is not possible](https://%20https://github.com/raysan5/raylib/blob/174313acbfa74d2a45fc0207f47ab00fbdb06050/src/platforms/rcore_desktop_glfw.c#L166C8-L166C132)
> * [ ]   vsync ?
> * [ ]   should apparently disable resizable window before entering fullscreen

Most of this is no longer relevant or needed when we simply rework `ToggleFullscreen() `to work exactly like your new `ToggleBorderlessWindow()` function with the only exception that instead of using videoMode->width/height we use the current screen size. 
This should fix:
- properly restoring the window when exiting fullscreen because now prev size & position are set correctly
- borderlessFullscreen does no longer need to update the prev values when we change from fullscreen to borderless fullscreen
- the new ToggleFullscreen() function does not need to update the prev values when we change from borderless fullscreen to fullscreen
---
I dont know about the resizable or vsync yet but it is not really important right now.
---
> * [ ]  sets window size to current screen size instead of setting it to monitor size
This is no longer relevant because it is the use case of the borderless fullscreen now

**Comment by SoloByte** [comment]
I would seperate the fullscreen stuff in 2 pull requests. 
- The first one is about fixing ToggleFullscreen() like I mentioned above.
- The second one would be about adding those 2 new functions

```c
void RestoreWindowWindowed()
{
    if(CORE.Window.fullscreen || CORE.Window.borderlessFullscreen)
    {
        // Return previous screen size and position
        int prevPosX = CORE.Window.previousPosition.x ;
        int prevPosY = CORE.Window.previousPosition.y ;
        int prevWidth = CORE.Window.previousScreen.width ;
        int prevHeight = CORE.Window.previousScreen.height ;
        glfwSetWindowMonitor(platform.handle, NULL, prevPosX , prevPosY, prevWidth, prevHeight, GLFW_DONT_CARE);

        // Let's not wait for GLFW to call WindowSizeCallback to update these values :
        CORE.Window.screen.width = prevWidth ;
        CORE.Window.screen.height = prevHeight ;

        // Refocus window
        glfwFocusWindow(platform.handle);

        CORE.Window.flags &= ~FLAG_FULLSCREEN_MODE;
    }
    else TRACELOG(LOG_WARNING, "GLFW: Fullscreen or Borderless Fullscreen are not active.");
    
}
void SetWindowFullscreen(int monitor, int x, int y, int w, int h, int refreshRate)
{
    if(CORE.Window.fullscreen) 
    {
        TRACELOG(LOG_WARNING, "GLFW: Fullscreen already enabled");
        return;
    }

    // Leave borderless fullscreen before attempting to set fullscreen mode and get screen position from it
    bool wasOnBorderlessFullscreen = false;
    if (CORE.Window.borderlessFullscreen)
    {
        CORE.Window.previousPosition = CORE.Window.position; // is this necessary? because previous position should be correct from enabled borderless fullscreen
        ToggleBorderlessWindowed(); //Could also use -> RestoreWindowedWindow()
        wasOnBorderlessFullscreen = true;
    }

  
    int monitorCount;
    GLFWmonitor **monitors = glfwGetMonitors(&monitorCount);

    if ((monitor >= 0) && (monitor < monitorCount))
    {
        // Store screen position and size
        // NOTE: If it was on borderless fullscreen, screen position & size was already stored, so skip setting it here
        if (!wasOnBorderlessFullscreen){
            glfwGetWindowPos(platform.handle, &CORE.Window.previousPosition.x, &CORE.Window.previousPosition.y);
            CORE.Window.previousScreen = CORE.Window.screen;
        } 

        glfwSetWindowMonitor(platform.handle, monitors[monitor], x, y, w, h, refreshRate);

        // Let's not wait for GLFW to call WindowSizeCallback to update these values :
        CORE.Window.screen.width = w ;
        CORE.Window.screen.height = h ;

        // Refocus window
        glfwFocusWindow(platform.handle);

        CORE.Window.flags |= FLAG_FULLSCREEN_MODE;
            
    }
    else TRACELOG(LOG_WARNING, "GLFW: Failed to find selected monitor");
}
```

**Comment by SuperUserNameMan** [comment]
@SoloByte : i think i found where the real problem was coming from, and it seems to have solved all the issues all at once.

However, i could not test on MacOS and Windows.

I'm going to push a new PR, and will need help with testing it all on these platforms.

**Comment by SoloByte** [comment]
Closed in favor of this [issue.](https://github.com/raysan5/raylib/issues/4215)
