### ISSUE TITLE
[rcore] SetMousePosition() & GetMouse...() stutter

### ISSUE THREAD

**Issue by Kabcorp** [raysan5/raylib#4155]
- [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [X] My code has no errors or misuse of raylib

### Issue description

*Forcing the mouse position then getting the delta of the mouse position is stuttering
If the game requires high precision mouse movements, using this approach results to an issue*

### Environment

*Windows x86_64 Mingw-w64*

### Issue Screenshot

![Image1](https://github.com/user-attachments/assets/e5c9d986-b526-4d16-830e-4a3de2b3510b)

### Code Example

```c
#include <raylib.h>

#define WIDTH  1024
#define HEIGHT 768
#define FPS    60

int main(int argc, char** argv)
{
  //Window init
  InitWindow(WIDTH, HEIGHT, "");
  SetTargetFPS(FPS);
  
  //Graph texture
  int GraphXpos=0;
  RenderTexture TexGraph=LoadRenderTexture(WIDTH, HEIGHT);
  
  while(!WindowShouldClose())
  {
    //Update graph texture
    BeginTextureMode(TexGraph);
        
        //MOUSE Y DELTA DETECTION
        int my=-(HEIGHT/2)+GetMouseY();
        SetMousePosition(WIDTH/2, HEIGHT/2);
    
    DrawRectangle(GraphXpos%WIDTH, 0, 2, HEIGHT, WHITE);
    DrawRectangle(GraphXpos%WIDTH, (HEIGHT/2)-my, 2, 2, BLACK);
    GraphXpos++;
    EndTextureMode();
    
    //Draw graph texture
    BeginDrawing();
    ClearBackground(WHITE);
    DrawTexture(TexGraph.texture, 0, 0, WHITE);
    DrawText("SetMousePosition() & GetMouse...() Issue\n"
    "This example draw the mouse Y difference\n"
    "You can clearly see that some values are dropped or pushed into a weird zone\n"
    "It seems to be frame-rate dependant (more FPS you have, more issues you have)", 2, 2, 20, BLACK);
    EndDrawing();
  }
  
  UnloadRenderTexture(TexGraph);
  CloseWindow();

  return 0;
}
```

**Comment by Kabcorp** [comment]
![image](https://github.com/user-attachments/assets/9b7eecc3-a0eb-44b1-b9ee-d0c92b091fd5)
It still have some small errors but maybe due to my hardware.
The problem was reduced by 95%

**Comment by Kabcorp** [comment]
I still have mouse stutter in my game tho.
Mouse deltas are not linear at a low speed.
I'll investigate more

**Comment by raysan5** [comment]
@Kabcorp I'm afraid this issue is out of raylib scope but the underlying system and platform libraries.

**Comment by Kabcorp** [comment]
I tried with RGLW backend, the problem disappeared.
