### ISSUE TITLE
[build] PLATFORM_RPI Complexity

### ISSUE THREAD

**Issue by RDR8** [raysan5/raylib#418]
Regarding the standard Makefile and Installation procedures, selection of OpenGL version requires changing top-level `PLATFORM`. Recent work to src/Makefile addresses some related underlying issues. Possibly consider `PLATFORM_RPI` as a case of `PLATFORM_OS=LINUX`. I know you preferred separating it out because of some OpenGL configuration but from my perspective those targets are mostly the same. Unsure of the consequences to other OpenGL or cross-compiler configuration. What's your opinion of defaulting to OpenGL 2.1 instead of OpenGLES? Since I work with desktop Linux regardless of the hardware, I prefer 2.1. As it is, with the two different top-level targets, it's not clear to me what would happen to Pi-specific configurations such as cross-compilation when targeting `PLATFORM_DESKTOP`. That said, I haven't had any problems with functionality.

**Comment by raysan5** [comment]
`PLATFORM_RPI` compiles raylib for RPI in native mode, not depending on X11 windowing (usual Linux window system), in that mode, the default Broadcomm OpenGL ES 2.0 driver is used getting **the best performance** for the system. This configuration is very useful for possible RPI embedded systems that require some graphics in native mode (not requiring DESKTOP usage or windowing). It works with any RPI version.

raylib can also be compiled for RPI Linux desktop environment just using `PLATFORM_DESKTOP` and forcing `GRAPHICS_API_OPENGL21`, that way it compiles as usual for Linux platform and uses the new OpenGL 2.1 driver (technically only available for RPI 2 and 3), but performance is way worse.

**Comment by RDR8** [comment]
I understand that priority. I think the legacy driver is still the default on Raspbian and is another reason to keep the current defaults. My primary issue is that, on the user side, it's not clear that one needs to be using the appropriate driver for the chosen API. ES apps don't seem to work with the OpenGL driver and vice versa. A new user might not know what is happening. May I add a note about driver/API selection to that part of the wiki?

I still think of the Pi as a special case of Linux whichever API is in use. Just my 2¢.
