### ISSUE TITLE
[textures] Large image sizes (8192 x 8192) overflows GetPixelDataSize()

### ISSUE THREAD

**Issue by noname22** [raysan5/raylib#4180]
### Issue description

When working with image sizes >= 8192 x 8192 raylib segfaults due to an overflow in GetPixelDataSize(), leading to a negative size.

Specifically this line:
`dataSize = width*height*bpp/8;  // Total data size in bytes`

With width and height 8192 and a bpp of 32, the resulting dataSize is -268435456.

In my particular case and code example it's ImageAlphaMask() that triggers the issue, but GetPixelDataSize() is used in multiple other image functions like ImageCopy(), etc.

Tested with latest master at the time of writing (`efce4d69ce913bca42289184b0bffe4339c0193f`)

### Environment

Not relevant, but:
* Windows 11 and WSL2 Ubuntu 22.04
* GeForce RTX 4090
* OpenGL 4.6

### Issue Screenshot

No screenshot.

### Code Example

```
#include "raylib.h"

int main(void)
{
    const int screenWidth = 1920;
    const int screenHeight = 1080;

    InitWindow(screenWidth, screenHeight, "raylib [textures] example - image drawing");

    SetTargetFPS(60);

    int w = 8192;
    Image image = GenImageColor(w, w, RED);
    Image alpha = GenImageColor(w, w, DARKGRAY);
    ImageAlphaMask(&image, alpha);

    Texture2D texture = LoadTextureFromImage(image);
    
    while (!WindowShouldClose())
    {
        BeginDrawing();
        ClearBackground(RAYWHITE);
        DrawTexture(texture, 0, 0, WHITE);
        EndDrawing();
    }

    return 0;
}
```

**Comment by StackAllocator** [comment]
Can you attach the image so I can reproduce it?

**Comment by noname22** [comment]
There is no image to attach. All you need is the code I provided.

**Comment by StackAllocator** [comment]
Yes, you're right.. Should've looked at the code. Sorry

**Comment by noname22** [comment]
No worries 🙂 

In theory the int should be able to hold a size to accommodate ~23k x 23k RGBA textures without signing it or promoting it to an int64_t (on platforms where int is 32bit, which is most of them). It's the multiplication by bpp that's screwing things up.

I guess the simplest fix would be to use an int64_t/long long, temporarily, while calculating and then casting it back to an int.

**Comment by noname22** [comment]
8192 x 8192 is hardly a humongous texture resolution. Imagine for instance a flight simulator.

Personally I was using it to generate a large image for a landscape which I then wanted to chunk before creating textures for it. Say an image that's 16384 x 16384, which is later chunked into 256 x 256 textures and height maps.

**Comment by StackAllocator** [comment]
Yes, you're right. I'm don't have much experience here. Can't help you further, sorry!

**Comment by noname22** [comment]
No worries. I can create a PR with a fix tomorrow.

**Comment by noname22** [comment]
PR: https://github.com/raysan5/raylib/pull/4206

**Comment by noname22** [comment]
Hmm, correct me if I'm wrong but doesn't your fix break any bpp that is less than 1 byte? (which is actually why I opted against it)

eg.
`case PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA: bpp = 2; break;`

then bytesPerPixel results in 0, leading to a zero size?

```
char bytesPerPixel = bpp/8;
dataSize = width*height*bytesPerPixel;
```

**Comment by noname22** [comment]
Sorry, forgot to mention who I am addressing but I'm talking to @raysan5 about the fix he committed to master.

**Comment by raysan5** [comment]
@noname22 oh! you are right! then it can be accomplished with a float and a cast
