### ISSUE TITLE
[build] next release version

### ISSUE THREAD

**Issue by sakgoyal** [raysan5/raylib#4195]
### Issue description

I know #3639 exists and fixed the issue of cmake complaining about the minimum cmake version, but I wanted to know what the next release of raylib would be so I can stop seeing this warning show up.

I am unsure if I can just directly use the master branch / specific commit hash instead of using the 5.0 release that fixes this. 

I understand this is very trivial, but its something I want to fix. 

### Environment
* Windows 10
* CPM package manager
* Cmake 3.36
* raylib 5.0

### Issue Screenshot
![image](https://github.com/user-attachments/assets/477e03c1-d434-4f7f-bef8-4db929bb617b)

**Comment by raysan5** [comment]
@sakgoyal Afaik, it's already fixed on master branch.

**Comment by sakgoyal** [comment]
Can I use the master branch without causing issues? im not sure how safe it is to use the master branch for my game

**Comment by raysan5** [comment]
@sakgoyal Master branch is stable, I use it on production for my tools.
