### ISSUE TITLE
[rcore] Provide FLAG_WINDOW_UNFOCUSED functionality for SDL backend 

### ISSUE THREAD

**Issue by ajitid** [raysan5/raylib#4198]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

I find FLAG_WINDOW_UNFOCUSED to be quite helpful during development. Especially when I am tweaking a value to see its affect on the output,  FLAG_WINDOW_UNFOCUSED ensures that my editor doesn't lose focus every time I make a change. This helps me avoid unnecessary Alt+Tab or Escape presses.

This becomes even more helpful when I am following a tutorial using a web browser, otherwise I have to do Alt+Tab switching between three windows. 
 
### Environment

Platform: Desktop Linux
OS: Fedora 40 with Gnome on Wayland

**Comment by asdqwe** [comment]
Hello,

I believe this should be requested at SDL instead. AFAIK, at the moment, it doesn't have the mechanism to allow it. So, implementing it cross-platform from scratch would require quite a bit of engineering.

For development on Linux, the same effect is usually achievable with the help of the Window Manager. E.g.: on Fluxbox there's `[FocusNewWindow] {bool}` ([doc](https://manpages.ubuntu.com/manpages/focal/en/man5/fluxbox-apps.5.html)). You'd have to check the documentation of the WM you're using to see if there's something similar available there.

Best regards.

**Comment by raysan5** [comment]
@asdqwe As per my understanding this feature is out of raylib domain at the moment and should be reported to SDL. Closing the issue here.
