### ISSUE TITLE
[Examples] Example "models_loading.c" does not build

### ISSUE THREAD

**Issue by randomouscrap98** [raysan5/raylib#4199]
- [NO] I tested it on latest raylib version from master branch - Tested on assumed latest release (5.0), not latest code from github
 - [YES] I checked there is no similar issue already reported - There are issues related to this specific example but not one for build errors
 - [YES] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [???] My code has no errors or misuse of raylib - It's the example code unmodified

### Issue description

I am trying to build the example [models_loading.c](https://github.com/raysan5/raylib/blob/master/examples/models/models_loading.c). I have built a few other examples without issue in my environment. This one throws a compiler error:

```
$ gcc models_loading.c -lraylib
models_loading.c: In function ‘main’:
models_loading.c:120:30: error: implicit declaration of function ‘GetScreenToWorldRay’; did you mean ‘GetScreenToWorld2D’? [-Wimplicit-function-declaration]
  120 |       if (GetRayCollisionBox(GetScreenToWorldRay(GetMousePosition(), camera),
      |                              ^~~~~~~~~~~~~~~~~~~
      |                              GetScreenToWorld2D
models_loading.c:120:30: error: incompatible type for argument 1 of ‘GetRayCollisionBox’
  120 |       if (GetRayCollisionBox(GetScreenToWorldRay(GetMousePosition(), camera),
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              |
      |                              int
In file included from models_loading.c:31:
/usr/include/raylib.h:1570:43: note: expected ‘Ray’ but argument is of type ‘int’
 1570 | RLAPI RayCollision GetRayCollisionBox(Ray ray, BoundingBox box);                                    // Get collision info between ray and box
      |                                       ~~~~^~~
```

### Environment

x86_64 linux, Arch, I assume gpu information is unnecessary since it's simply not compiling. I am using the raylib 5.0 release from the package manager.

I am aware that the issue template indicates I should be using the "latest code from master". If master and stable are compatible uh... maybe arch is using unstable branch idk? My `raylib.h` header indicates it is 5.0 from 2023 so I think it's latest stable. I also tried the code directly from the website example page, it is broken in the same manner as it seems it is the same code. 

### Code Example

It is the unmodified example as linked above.

**Comment by StackAllocator** [comment]
Hello, the` GetScreenToWorldRay()` function was first introduced on 03.04.2024.
On my guix machine I was able to reproduce the error using raylib 5.0 (not latest version).

However, when you build the upstream library, the example works as expected.
I build raylib statically and tried again and it works without any problem.
So you don't have the latest release installed and therefore the function can't be found in` rcore.c`.

Try building raylib statically and it should is going to work.

**Comment by randomouscrap98** [comment]
Is this intended though? Raylib's only documentation is its examples, and the examples don't work for the latest stable release. From what I'm reading here, it's intentional? What's the point of the stable release, then? Shouldn't the examples on the website perhaps point to the tag representing the stable release, if they're bound to break in the intervening time?

**Comment by StackAllocator** [comment]
@randomouscrap98 Yes, this is intentional. The raylib examples are always allowed to use the latetest release.
The last update from the raylib arch maintainer was on Nov. 19, 2023, 12:24 p.m..
The API can change in that period of time (even if backwards incompatible changes are made).
It's generally recommended to build raylib statically with every project such that you can use the latest features.

**Comment by randomouscrap98** [comment]
I see. Regardless of the feelings on the matter, the raylib resources are uneven then. The [cheatsheet](https://www.raylib.com/cheatsheet/cheatsheet.html) is for 5.0 and thus does not include this function. When I was trying to figure out what's wrong, I could not find this "new" function on the cheatsheet, even though the examples include it. As such, when someone is "trying to enjoy game programming", they are going to have an unfun time if they're trying to learn using the limited resources, as one assumes you are using latest stable (cheatsheet), and the other assumes you are using latest from github.

**Comment by StackAllocator** [comment]
I am pretty sure that this is also intended. The raylib cheatsheet is only a collection of the most popular functions used within the API. So the intended route is to look at the `raylib.h` file and use that as a documentation.
But since I'm not exactly sure, I'll leave this up to @raysan5 to further explain..

**Comment by randomouscrap98** [comment]
If it's intentional, it would be nice if it were indicated as such. The page for the cheatsheet does indicate that it's for 5.0 specifically, but nothing in the examples indicates that they are NOT for the latest stable. So someone trying to use all the resources on the website would not actually be able to, because they are technically "split" across two versions.

**Comment by raysan5** [comment]
> [NO] I tested it on latest raylib version from master branch - Tested on assumed latest release (5.0), not latest code from github

This is the issue. It is solved for next release.

**Comment by randomouscrap98** [comment]
It is unfortunate that you don't see how frustrating this is for newcomers. Oh well

**Comment by Fierelier** [comment]
@raysan5 It would be nice if you could add at least a notice to the top of the examples page, that links to stable examples, like https://github.com/raysan5/raylib/tree/5.0/examples, for 5.0.

I agree that it isn't intuitive to have the cheatsheet be for stable, and the examples not. Especially since people who actually work on raylib, and use unstable raylib, are more likely to pull the examples from their git clone anyways.

**Comment by raysan5** [comment]
@randomouscrap98 @Fierelier Updating everything for next release takes time. Please, remember this is an open source project maintained mostly by one person. If you think improvements can be done, you can send a PR and become owners and maintainers of your changes. Thanks for your comprehendion.
