### ISSUE TITLE
[WIP] [Examples] Update progress for v5.5

### ISSUE THREAD

**Issue by CrackedPixel** [raysan5/raylib#4208]
* All below Build/Works is for Desktop. Will probably add more columns to be explicit later
* **2024-08-03:** All builds are successful. Need to test if they work properly
* **2024-08-04** Tested Audio and Others
* **2024-08-04** Tested Text
* **2024-08-04** Tested Shapes
* **2024-08-04** Tested Models
* **2024-08-04** Tested Shaders
* **2024-08-05** Tested Textures
* **2024-08-05** Tested Core

## Audio
| Name                   | Build | Works | Notes              |
|------------------------|-------|-------|--------------------|
| audio_mixed_processor  |✅|✅| Visual "average volume" does not work. Fixed in https://github.com/raysan5/raylib/pull/4214 (merged)|
| audio_module_playing   |✅|✅|                    |
| audio_music_stream      |✅|✅|                    |
| audio_raw_stream           |✅|✅| PNG needs updated|
| audio_sound_loading     |✅|✅|                    |
| audio_sound_multi          |✅|✅|                    |
| audio_stream_effects     |✅|⚠️| Delay effect lowers volume -- intentional?|

## Core
| Name                           | Build | Works | Notes          |
|--------------------------------|-------|-------|--------------------|
| core_2d_camera                            |✅|✅|                    |
| core_2d_camera_mouse_zoom  |✅|✅| PNG needs updated|
| core_2d_camera_platformer       |✅|✅| Camera clamp to screen edge broken when going off map. I don't think it needs updated, though|
| core_2d_camera_split_screen     |✅|✅|                    |
| core_3d_camera_first_person     |✅|✅| Some camera modes do not support the controls shown on-screen. PNG needs updated. Being worked on in https://github.com/raysan5/raylib/pull/4221|
| core_3d_camera_free                   |✅|✅|                    |
| core_3d_camera_mode               |✅|✅|                    |
| core_3d_camera_split_screen     |✅|✅|                    |
| core_3d_picking                            |✅|✅| PNG needs updated. Maybe add something about how the red line is the ray? It's very confusing -- can discuss if needed|
| core_automation_events             |✅|✅|                    |
| core_basic_screen_manager       |✅|✅|                    |
| core_basic_window                       |✅|✅|                    |
| core_basic_window_web              |✅|✅|                    |
| core_custom_frame_control        |✅|✅|                    |
| core_custom_logging                   |✅|✅|                    |
| core_drop_files                                |✅|⚠️| Crashes when compiled for Wayland. X11 is fine. This is a GLFW issue|
| core_input_gamepad                    |✅|✅| PNG needs updated. Verified and fixed in https://github.com/raysan5/raylib/pull/4240/files |
| core_input_gamepad_info           |✅|✅| PNG needs updated. Verified and fixed in https://github.com/raysan5/raylib/pull/4241 (merged) |
| core_input_gestures                     |✅|✅|                    |
| core_input_gestures_web           |✅|✅|                    |
| core_input_keys                            |✅|✅|                    |
| core_input_mouse                        |✅|✅|  |
| core_input_mouse_wheel            |✅|✅|                    |
| core_input_multitouch                  |✅|✅| Verified on mobile by another user |
| core_loading_thread                     |✅|✅|                    |
| core_random_sequence              |✅|✅|                    |
| core_random_values                    |✅|✅|                    |
| core_scissor_test                           |✅|✅|                    |
| core_smooth_pixelperfect           |✅|✅|                    |
| core_storage_values                     |✅|✅|                    |
| core_vr_simulator                         |✅|✅|                    |
| core_window_flags                       |✅|✅|                    |
| core_window_letterbox                |✅|✅|                    |
| core_window_should_close         |✅|✅|                    |
| core_world_screen                       |✅|✅| PNG needs updated|

## Models
| Name                           | Build | Works | Notes              |
|--------------------------------|-------|-------|--------------------|
| models_animation                           |✅|✅|                    |
| models_billboard                             |✅|✅| PNG needs updated|
| models_bone_socket                       |✅|✅|                    |
| models_box_collisions                    |✅|✅| PNG needs updated. Changed in https://github.com/raysan5/raylib/pull/4224 (merged)|
| models_cubicmap                           |✅|✅|                    |
| models_draw_cube_texture           |✅|✅|                    |
| models_first_person_maze            |✅|✅|                    |
| models_geometric_shapes            |✅|✅|                    |
| models_heightmap                         |✅|✅|                    |
| models_loading                               |✅|✅|                    |
| models_loading_gltf                        |✅|✅|                    |
| models_loading_m3d                      |✅|✅| "C" to cycle anims but only 1 anim in file|
| models_loading_vox                        |✅|✅| PNG needs updated|
| models_mesh_generation              |✅|✅|                    |
| models_mesh_picking                    |✅|✅|                    |
| models_orthographic_projection  |✅|✅|                    |
| models_rlgl_solar_system              |✅|✅| PNG needs updated|
| models_skybox                                 |✅|✅| HDR also works|
| models_waving_cubes                    |✅|✅|                    |
| models_yaw_pitch_roll                     |✅|✅|                    |

## Others
| Name                           | Build | Works | Notes              |
|--------------------------------|-------|-------|--------------------|
| easings_testbed                     |✅|✅|                    |
| embedded_files_loading       |✅|✅|                    |
| raylib_opengl_interop           |✅|✅| PNG needs updated|
| raymath_vector_angle          |✅|✅| PNG needs updated due to Mode 1 changes|
| rlgl_compute_shader            |✅|❌| Stays black with brush. Logic and input works|
| rlgl_standalone                       |✅|✅|                    |

## Shaders
| Name                           | Build | Works | Notes              |
|--------------------------------|-------|-------|--------------------|
| shaders_basic_lighting          |✅|✅| PNG needs updated|
| shaders_basic_pbr                 |✅|✅| Car model is too small to see. Fixed in https://github.com/raysan5/raylib/pull/4225 (merged)|
| shaders_custom_uniform    |✅|✅|                    |
| shaders_deferred_render     |✅|⚠️| Lighting does not look correct|
| shaders_eratosthenes           |✅|✅|                    |
| shaders_fog                            |✅|✅|                    |
| shaders_hot_reloading          |✅|✅|                    |
| shaders_hybrid_render         |✅|✅| PNG needs updated. Suggest renaming window title to example name|
| shaders_julia_set                    |✅|✅|                    |
| shaders_lightmap                 |✅|✅|                    |
| shaders_mesh_instancing   |✅|✅| PNG needs updated|
| shaders_model_shader         |✅|✅| PNG needs updated|
| shaders_multi_sample2d      |✅|✅|                    |
| shaders_palette_switch         |✅|✅|                    |
| shaders_postprocessing       |✅|✅| Cross-hatching shader may be broken. Sobel has some glitches on the edges of the screen|
| shaders_raymarching           |✅|✅|                    |
| shaders_shadowmap            |✅|✅|                    |
| shaders_shapes_textures     |✅|✅|                    |
| shaders_simple_mask          |✅|✅|                    |
| shaders_spotlight                  |✅|✅|                    |
| shaders_texture_drawing     |✅|✅|                    |
| shaders_texture_outline       |✅|✅|                    |
| shaders_texture_tiling           |✅|✅|                    |
| shaders_texture_waves         |✅|✅|                    |
| shaders_write_depth             |✅|✅|                    |

## Shapes
| Name                               | Build | Works | Notes              |
|------------------------------------|-------|-------|--------------------|
| shapes_basic_shapes                         |✅|✅|                    |
| shapes_bouncing_ball                        |✅|✅| The "pause" is commented out. Fixed in https://github.com/raysan5/raylib/pull/4226|
| shapes_collision_area                         |✅|✅|                    |
| shapes_colors_palette                        |✅|✅|                    |
| shapes_draw_circle_sector                |✅|✅| Circle seems rotated 90*CW compared to PNG (with same settings). Settings values are not displayed compared to the PNG (angle etc) [Value display fixed in this PR](https://github.com/raysan5/raylib/pull/4211)|
| shapes_draw_rectangle_rounded    |✅|✅| Settings values are not displayed. Fixed in https://github.com/raysan5/raylib/pull/4211 (merged)|
| shapes_draw_ring                               |✅|✅| Settings values are not displayed. Fixed in https://github.com/raysan5/raylib/pull/4211 (merged)|
| shapes_easings_ball_anim                |✅|✅|                    |
| shapes_easings_box_anim                |✅|✅|                    |
| shapes_easings_rectangle_array     |✅|✅|                    |
| shapes_following_eyes                      |✅|✅|                    |
| shapes_lines_bezier                            |✅|✅|                    |
| shapes_logo_raylib                             |✅|✅|                    |
| shapes_logo_raylib_anim                  |✅|✅|                    |
| shapes_rectangle_scaling                  |✅|✅| |
| shapes_splines_drawing                    |✅|✅|                    |
| shapes_top_down_lights                   |✅|✅| Shadows do not update when moving the moveable light into a shadow area. Intentional?|

## Text
| Name                     | Build | Works | Notes              |
|--------------------------|-------|-------|--------------------|
| text_codepoints_loading  |✅|✅| There is a small square in the bottom right corner of the atlas (visible on all font atlas examples)|
| text_draw_3d                      |✅|✅| While this technically works as intended, i think it needs a review for UX|
| text_font_filters                  |✅|✅|                    |
| text_font_loading               |✅|✅|                    |
| text_font_sdf                        |✅|✅|                    |
| text_font_spritefont           |✅|✅|                    |
| text_format_text                  |✅|✅| |
| text_input_box                     |✅|✅| Low FPS limit has issues. Fixed in https://github.com/raysan5/raylib/pull/4229 (merged)|
| text_raylib_fonts                 |✅|✅|                    |
| text_rectangle_bounds      |✅|✅|                    |
| text_unicode                        |✅|✅|                    |
| text_writing_anim               |✅|✅| PNG needs updated. Rename "press space" to "hold space". Changed in https://github.com/raysan5/raylib/pull/4230 (merged)|

## Textures
| Name                         | Build | Works | Notes              |
|------------------------------|-------|-------|--------------------|
| textures_background_scrolling     |✅|✅|                    |
| textures_blend_modes                   |✅|✅|                    |
| textures_bunnymark                       |✅|✅|                    |
| textures_draw_tiled                         |✅|✅|                    |
| textures_fog_of_war                       |✅|✅| Has some texture wrap issue when player on an edge|
| textures_gif_player                         |✅|✅|                    |
| textures_image_channel                |✅|✅|                    |
| textures_image_drawing               |✅|✅|                    |
| textures_image_generation          |✅|✅|                    |
| textures_image_kernel                   |✅|✅|                    |
| textures_image_loading                 |✅|✅|                    |
| textures_image_processing           |✅|✅|                    |
| textures_image_rotate                   |✅|✅|                    |
| textures_image_text                       |✅|✅| PNG needs updated|
| textures_logo_raylib                        |✅|✅| Identical example to textures_image_loading|
| textures_mouse_painting              |✅|✅|  |
| textures_npatch_drawing              |✅|✅|                    |
| textures_particles_blending          |✅|✅|                    |
| textures_polygon                            |✅|✅|                    |
| textures_raw_data                          |✅|✅|                    |
| textures_sprite_anim                      |✅|✅|                    |
| textures_sprite_button                   |✅|✅|                    |
| textures_sprite_explosion              |✅|✅|                    |
| textures_srcrec_dstrec                    |✅|✅|                    |
| textures_svg_loading                     |✅|✅|                    |
| textures_textured_curve                 |✅|✅|                    |
| textures_to_image                           |✅|✅|                    |

## Misc Tasks
| Name                         | Notes              |
|------------------------------|--------------------|
| Update Makefile | Done in https://github.com/raysan5/raylib/pull/4209 |
| Update RLGL | Done in https://github.com/raysan5/raylib/pull/4238 (merged) |
| Add missing UnloadTexture() | Done in https://github.com/raysan5/raylib/pull/4234 (merged) |
| SetTargetFPS(60) | Done in https://github.com/raysan5/raylib/pull/4235 |

**Comment by CrackedPixel** [comment]
Examples needed an [updated Makefile](https://github.com/raysan5/raylib/pull/4209)

**Comment by raysan5** [comment]
@CrackedPixel Thanks for the review!

**Comment by CrackedPixel** [comment]
shapes_splines_drawing:

Is the bezier supposed to break like this when using hard angles?

![image](https://github.com/user-attachments/assets/cb18d89e-002f-4987-96c0-719bee883998)

**Comment by raysan5** [comment]
@CrackedPixel I'm afraid it is, there are no mittens or circle segments implemented/enabled, it will require a review of all spline drawing functions...

**Comment by asdqwe** [comment]
Hello,

> core_custom_frame_control 	✅ 	❌ 	I need to revisit this one -- it appears to be very broken. Had to end with SIGKILL

I believe this one requires recompiling raylib with `SUPPORT_CUSTOM_FRAME_CONTROL` just for it ([ref](https://github.com/raysan5/raylib/blob/master/src/config.h#L72)). Note that enabling that will break the other examples ([ref](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L897-L920)).

Best regards.

**Comment by CrackedPixel** [comment]
`core_automation_events`

When doing playback, it would be cool to instead have a "ghost" of the player doing the movements. This will make it easier for the user to watch and also not interrupt them (unless its desired to allow interrupting?)

I'm fine to implement this with approval

**Comment by CrackedPixel** [comment]
`core_drop_files`

This sometimes (maybe 80%) crashes on Linux with Wayland. X11 is perfectly fine. It's definitely some issue with GLFW so there is nothing to do

**Comment by CrackedPixel** [comment]
`core_input_gamepad` and `core_input_gamepad_info`

I think it would be good to have someone with an XBOX controller double-check these are working properly. I do not have one and it sort of worked but not how people probably expect lol

**Comment by CrackedPixel** [comment]
`shaders_postprocessing`

2 of the shaders look funky or have issues. Not a problem with raylib, though. Is it worth having someone redo them?

**Comment by CrackedPixel** [comment]
`text_codepoints_loading` and others that display a font atlas. There is a small square in the bottom right corner of the atlases. Is this expected behavior or should an issue be opened for it?

**Comment by CrackedPixel** [comment]
@raysan5 

Outstanding items:
- `audio_stream_effects`: Is it intentional that the delay lowers the volume, or should this be fixed?
- `core_input_gamepad` / `core_input_gamepad_info`: Someone with an XBOX controller should double check this
- `core_input_multitouch`: TBT on mobile 
- `rlgl_compute_shader`: Someone more experienced needs to look at this one. It's something in the shader, all of the other logic is working properly
- `shaders_deferred_render`: Someone more experienced needs to look at this one. The lighting is not correct
- PNGs need updated: Will be done in bulk via a single PR once the other things are merged in (so that the newer PNGs reflect the changes)

Everything else has a PR open to be fixed. Only 2 examples were broken, which is very good considering some are from raylib v1.0

**Comment by asdqwe** [comment]
Hello,

> `core_input_gamepad` / `core_input_gamepad_info`: Someone with an XBOX controller should double check this

Both examples correctly detect the Xbox controller and its buttons/analogs, but some (UI) fixes were required: #4240, #4241.

Best regards.

**Comment by CrackedPixel** [comment]
Outstanding items:
- `audio_stream_effects`: Is it intentional that the delay lowers the volume, or should this be fixed?
- `rlgl_compute_shader`: Someone more experienced needs to look at this one. It's something in the shader, all of the other logic is working properly
- `shaders_deferred_render`: Someone more experienced needs to look at this one. The lighting is not correct
- PNGs need updated: Will be done in bulk via a single PR once the other things are merged in (so that the newer PNGs reflect the changes)

**Comment by raysan5** [comment]
- `audio_stream_effects`: should be probably fixed.
 - `rlgl_compute_shader`: are you compiling raylib for OpenGL 4.3?
 - `shaders_deferred_render`: no idea...
 - PNGs: I prefer them being updated with the updated examples, not separately

**Comment by Peter0x44** [comment]
shaders_mesh_instancing only works for web if you compile raylib for OpenGL ES3 and compile with `-sFULL_ES3`. Instancing is a webgl2/gles3 feature.

**Comment by raysan5** [comment]
It seems most of the examples work as expected. I'm closing this issue, I think it's better to open separate issues for non-working examples.
