### ISSUE TITLE
[docs] Documentation inconsistently uses Camera/Camera3D.

### ISSUE THREAD

**Issue by Hex4dec** [raysan5/raylib#4218]
### Issue description

The documentation often interchangably uses Camera3D and Camera (noticable most in the cheatsheet) in parameters and comments.

### Environment

The [raylib cheatsheet](https://www.raylib.com/cheatsheet/cheatsheet.html).

**Comment by raysan5** [comment]
@Hex4dec well, actually they are the same. Originally there was only Camera and later was added Camera2D and an alias for Camera to Camera3D.

**Comment by raysan5** [comment]
Just reviewed `raylib.h`, that is used to generate the cheatsheet, and beside the type definition of Camera3D, everywhere else it's used `Camera`.
