### ISSUE TITLE
Truncating buffer in TextFormat might not work as intended 

### ISSUE THREAD

**Issue by RicoP** [raysan5/raylib#4222]
The following code 

https://github.com/raysan5/raylib/blob/97c02b2425225982da6f3569d50fb490fab53c10/src/rcore.c#L3664C1-L3677C1

assumes vsnprintf will always write into currentBuffer until it hits the maximum number of remaining bytes. However what when right there we have a "%f" and are in the process of formating a long float value? 

Like assuming our buffer has 6 remaining bytes. 

and we want to format it with 
`vsnprintf(buffer, 6, "Hello%f", 3.14159265359f); `

We would assume our buffer would look like that "Hello3" but that might not be the case. It's more likely that the buffer would contain "Hello?" with ? being whatever byte was there last time when we tried to format the string. I realize that we memset the memory with zero, but is the content of the sixth byte still guaranteed to be zero? 

I am just concerned that when we walk back 4 characters to attach "..." the preceding bytes might be garbled.

**Comment by asdqwe** [comment]
Hello,

> We would assume our buffer would look like that "Hello3"

AFAIK, we would assume the buffer would look like `Hello` (`Hello\0`) ([ref](https://linux.die.net/man/3/vsnprintf), [ref](https://cplusplus.com/reference/cstdio/vsnprintf/), [ref](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l?view=msvc-170)).

Best regards.

**Comment by RicoP** [comment]
OK. I wasn't too sure if this is well defined behavior in the C standard.

**Comment by asdqwe** [comment]
Hello,

Just beware that while `snprintf`/`vsnprintf` ouput is null terminated, other functions like `strcpy`/`strncpy`/etc are not.

Best regards.

**Comment by RicoP** [comment]
Ok closing this issue
