### ISSUE TITLE
[rcore] Can't compile PLATFORM=PLATFORM_DRM GRAPHICS=GRAPHICS_API_OPENGL_21

### ISSUE THREAD

**Issue by EvilTrev** [raysan5/raylib#4236]
I'm building on a raspberry pi 3 with pretty much the latest everything and all known apt-get packages (that I'm aware of). I have no issues compiling with ```make PLATFORM=PLATFORM_DRM``` but ```make PLATFORM=PLATFORM_DRM GRAPHICS=GRAPHICS_API_OPENGL_21``` fails with endless EGL issues, implicit function declarations, EGLAPIENTRYP issues etc. I'll dig a little further, but I just wanted to verify first that the graphics and platform combo is supposed? (Not using X)

A few example errors from the build:

```
/usr/include/EGL/egl.h:106:21: error: expected ‘)’ before ‘*’ token
  106 | typedef EGLBoolean (EGLAPIENTRYP PFNEGLCHOOSECONFIGPROC) (EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config);
```
```
In file included from platforms/rcore_drm.c:72:
/usr/include/EGL/egl.h:131:31: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘eglChooseConfig’
  131 | EGLAPI EGLBoolean EGLAPIENTRY eglChooseConfig (EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config);
```
```
platforms/rcore_drm.c:548:5: error: implicit declaration of function ‘eglSwapBuffers’; did you mean ‘glMapBuffer’? [-Werror=implicit-function-declaration]
  548 |     eglSwapBuffers(platform.device, platform.surface);
      |     ^~~~~~~~~~~~~~
      |     glMapBuffer
```

**Comment by EvilTrev** [comment]
Looks like GRAPHICS_API_OPENGL_21 might be desktop only on Pi? GRAPHICS_API_OPENGL_ES2 does compile, but that's probably the default? What combination would I need to support shader version 120 on a Pi 3 without X? Or is this in the config of the device itself? I know older OS versions had to have the gpu enabled for certain configs... my startup shows "Vc4 v3d" version 2.1, which should support ES 2.1 #version 120?

```
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: VC4 V3D 2.1
INFO:     > Version:  OpenGL ES 2.0 Mesa 23.2.1-1~bpo12+rpt3
INFO:     > GLSL:     OpenGL ES GLSL ES 1.0.16

WARNING: SHADER: [ID 4] Compile error: 0:1(10): error: GLSL 1.20 is not supported. Supported versions are: 1.00 >
```

**Comment by asdqwe** [comment]
Hello,

AFAIK, `PLATFORM_DRM` (aka "native mode") uses only OpenGL ES. While `PLATFORM_DESKTOP` (aka "X11 mode") uses only OpenGL. There's an entry about this on the [wiki](https://github.com/raysan5/raylib/wiki/Working-on-Raspberry-Pi#supported-opengl-backends) (Note: the old `PLATFORM_RPI` was removed around raylib 5.0).

Regarding the OpenGL ES version, try compiling with (untested, don't have my Raspberry Pi around):
```
make PLATFORM=PLATFORM_DRM GRAPHICS=GRAPHICS_API_OPENGL_ES2
```

Best regards.

**Comment by raysan5** [comment]
Yeap, `PLATFORM_DRM` only supports `GRAPHICS_API_OPENGL_ES2`
