### ISSUE TITLE
[rtextures] Add different wrap modes for NPatches

### ISSUE THREAD

**Issue by Aurora2500** [raysan5/raylib#4250]
Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [ ] My code has no errors or misuse of raylib

### Issue description

The current NPatch implementation only stretches the image. There are cases where a repeated mode would be more appropiate, like for the UI element I have attached, where the dotted lines would be better repeated to fit the size with as many dots, rather than stretch a fixed number of dots.

### Issue Screenshot

![image](https://github.com/user-attachments/assets/eea87475-7e3d-45e5-9e80-86e2c6bf1c52)

**Comment by raysan5** [comment]
@Aurora2500 Agree, but I'm afraid it implies a level of complexity to be implemented, not trivial. Feel free to work on it if you want.

**Comment by raysan5** [comment]
No answer so I assume nobody is going to work on this feature. Closing.
