### ISSUE TITLE
Porting GUI toolkit from X11 to raylib

### ISSUE THREAD

**Issue by Symbian9** [raysan5/raylib#426]
Is it possible port GUI toolkit from X11 to `raylib`?

For example, here is `mlib` GUI toolkit written in C ontop of X11

- https://github.com/Symbian9/azpainter/tree/master/mlib

**Comment by raysan5** [comment]
not sure if its possible... mlib seems to be a big library... in any case, it would require a lot of work...

personally, I use [raygui](https://github.com/raysan5/raygui) for my tools, it's a simple immediate mode GUI based on raylib, no dependencies...

**Comment by Symbian9** [comment]
> I use raygui for my tools, it's a simple immediate mode GUI based on raylib, no dependencies...

But its look like depend on IMGUI, isn't?
> raygui is a simple and easy-to-use IMGUI header-only library.

**Comment by Symbian9** [comment]
Here is minimal demo app based on `mlib` -- theme editor for mlib-based apps

- Website - http://azsky2.html.xdomain.jp/linux/mthemeeditor.html
  - Sources (BSD-3) http://azsky2.html.xdomain.jp/linux/file/mthemeeditor-1.0.0.tar.xz

![mThemeEditor](http://azsky2.html.xdomain.jp/linux/img/mthemeeditor.png)

**Comment by raysan5** [comment]
Some controls are not available in raygui just yet, in the project description you can see available controls...
[rFXGen tool](https://github.com/raysan5/rfxgen) has been created with raylib and raygui.

I also have a theme editor called [rGuiStyler](https://github.com/raysan5/raygui/tree/master/tools/rGuiStyler) but it's being updated, raygui has been completely reviewed lately... still working on it...
