### ISSUE TITLE
[cmake] can't set config.h defines through cmake with CUSTOMIZE_BUILD=ON

### ISSUE THREAD

**Issue by VRichardJP** [raysan5/raylib#4260]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

https://github.com/raysan5/raylib/pull/4044 introduced a way for CMake users to change config.h defines from CMake. However, it seems to me this only works with `SUPPORT_` flags (e.g. `SUPPORT_MODULE_RSHAPES`), not with values (e.g. `RL_CULL_DISTANCE_NEAR=10000.0`).

For example when I import and build raylib with the following snippet:

```cmake
include(FetchContent)

set(CUSTOMIZE_BUILD ON)
set(RL_CULL_DISTANCE_NEAR 0.001)
set(RL_CULL_DISTANCE_FAR 10000.0)

FetchContent_Declare(
  raylib
  GIT_REPOSITORY https://github.com/raysan5/raylib
  GIT_TAG 308b77cd42c42406a3bd4eac250761476ff0407e #5.0
  GIT_SHALLOW 1
)
FetchContent_MakeAvailable(raylib)
```

I see the `RL_CULL_DISTANCE_NEAR` and `RL_CULL_DISTANCE_FAR` are set to their default config.h values instead of the one I want. For example, this is what my `compile_commands.json` file looks like (with `-DCMAKE_EXPORT_COMPILE_COMMANDS=1`):

```json
{
  "directory": "/m3d/build",
  "command": "/usr/bin/cc -DAUDIO_DEVICE_CHANNELS=2 -DAUDIO_DEVICE_FORMAT=ma_format_f32 -DAUDIO_DEVICE_SAMPLE_RATE=0 -DEXTERNAL_CONFIG_FLAGS -DGRAPHICS_API_OPENGL_43 -DMAX_AUDIO_BUFFER_POOL_CHANNELS=16 -DMAX_AUTOMATION_EVENTS=16384 -DMAX_CHAR_PRESSED_QUEUE=16 -DMAX_DECOMPRESSION_SIZE=64 -DMAX_FILEPATH_CAPACITY=8192 -DMAX_FILEPATH_LENGTH=4096 -DMAX_GAMEPADS=4 -DMAX_GAMEPAD_AXIS=8 -DMAX_GAMEPAD_BUTTONS=32 -DMAX_GAMEPAD_VIBRATION_TIME=2.0f -DMAX_KEYBOARD_KEYS=512 -DMAX_KEY_PRESSED_QUEUE=16 -DMAX_MATERIAL_MAPS=12 -DMAX_MESH_VERTEX_BUFFERS=7 -DMAX_MOUSE_BUTTONS=8 -DMAX_TEXTSPLIT_COUNT=128 -DMAX_TEXT_BUFFER_LENGTH=1024 -DMAX_TOUCH_POINTS=8 -DMAX_TRACELOG_MSG_LENGTH=256 -DPLATFORM_DESKTOP -DRL_CULL_DISTANCE_FAR=1000.0 -DRL_CULL_DISTANCE_NEAR=0.01 -DRL_DEFAULT_BATCH_BUFFERS=1 -DRL_DEFAULT_BATCH_DRAWCALLS=256 -DRL_DEFAULT_BATCH_MAX_TEXTURE_UNITS=4 -DRL_DEFAULT_SHADER_ATTRIB_LOCATION_COLOR=3 -DRL_DEFAULT_SHADER_ATTRIB_LOCATION_NORMAL=2 -DRL_DEFAULT_SHADER_ATTRIB_LOCATION_POSITION=0 -DRL_DEFAULT_SHADER_ATTRIB_LOCATION_TANGENT=4 -DRL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD2=5 -DRL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD=1 -DRL_DEFAULT_SHADER_ATTRIB_NAME_COLOR=\\\"vertexColor\\\" -DRL_DEFAULT_SHADER_ATTRIB_NAME_NORMAL=\\\"vertexNormal\\\" -DRL_DEFAULT_SHADER_ATTRIB_NAME_POSITION=\\\"vertexPosition\\\" -DRL_DEFAULT_SHADER_ATTRIB_NAME_TANGENT=\\\"vertexTangent\\\" -DRL_DEFAULT_SHADER_ATTRIB_NAME_TEXCOORD2=\\\"vertexTexCoord2\\\" -DRL_DEFAULT_SHADER_ATTRIB_NAME_TEXCOORD=\\\"vertexTexCoord\\\" -DRL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE0=\\\"texture0\\\" -DRL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE1=\\\"texture1\\\" -DRL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE2=\\\"texture2\\\" -DRL_DEFAULT_SHADER_UNIFORM_NAME_COLOR=\\\"colDiffuse\\\" -DRL_DEFAULT_SHADER_UNIFORM_NAME_MODEL=\\\"matModel\\\" -DRL_DEFAULT_SHADER_UNIFORM_NAME_MVP=\\\"mvp\\\" -DRL_DEFAULT_SHADER_UNIFORM_NAME_NORMAL=\\\"matNormal\\\" -DRL_DEFAULT_SHADER_UNIFORM_NAME_PROJECTION=\\\"matProjection\\\" -DRL_DEFAULT_SHADER_UNIFORM_NAME_VIEW=\\\"matView\\\" -DRL_MAX_MATRIX_STACK_SIZE=32 -DRL_MAX_SHADER_LOCATIONS=32 -DSPLINE_SEGMENT_DIVISIONS=24 -DSUPPORT_AUTOMATION_EVENTS -DSUPPORT_CAMERA_SYSTEM -DSUPPORT_COMPRESSION_API -DSUPPORT_DEFAULT_FONT -DSUPPORT_FILEFORMAT_DDS -DSUPPORT_FILEFORMAT_FNT -DSUPPORT_FILEFORMAT_GIF -DSUPPORT_FILEFORMAT_GLTF -DSUPPORT_FILEFORMAT_IQM -DSUPPORT_FILEFORMAT_M3D -DSUPPORT_FILEFORMAT_MOD -DSUPPORT_FILEFORMAT_MP3 -DSUPPORT_FILEFORMAT_MTL -DSUPPORT_FILEFORMAT_OBJ -DSUPPORT_FILEFORMAT_OGG -DSUPPORT_FILEFORMAT_PNG -DSUPPORT_FILEFORMAT_QOA -DSUPPORT_FILEFORMAT_QOI -DSUPPORT_FILEFORMAT_TTF -DSUPPORT_FILEFORMAT_VOX -DSUPPORT_FILEFORMAT_WAV -DSUPPORT_FILEFORMAT_XM -DSUPPORT_FONT_ATLAS_WHITE_REC -DSUPPORT_GESTURES_SYSTEM -DSUPPORT_GIF_RECORDING -DSUPPORT_IMAGE_EXPORT -DSUPPORT_IMAGE_GENERATION -DSUPPORT_IMAGE_MANIPULATION -DSUPPORT_MESH_GENERATION -DSUPPORT_MODULE_RAUDIO -DSUPPORT_MODULE_RMODELS -DSUPPORT_MODULE_RSHAPES -DSUPPORT_MODULE_RTEXT -DSUPPORT_MODULE_RTEXTURES -DSUPPORT_MOUSE_GESTURES -DSUPPORT_PARTIALBUSY_WAIT_LOOP -DSUPPORT_QUADS_DRAW_MODE -DSUPPORT_RPRAND_GENERATOR -DSUPPORT_SCREEN_CAPTURE -DSUPPORT_SSH_KEYBOARD_RPI -DSUPPORT_STANDARD_FILEIO -DSUPPORT_TEXT_MANIPULATION -DSUPPORT_TRACELOG -DSUPPORT_WINMM_HIGHRES_TIMER -I/m3d/build/_deps/raylib-src/src -isystem /m3d/build/_deps/raylib-src/src/external/glfw/include -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith  -O2 -g -DNDEBUG -fdiagnostics-color=always -std=gnu99 -o _deps/raylib-build/raylib/CMakeFiles/raylib.dir/rshapes.c.o -c /m3d/build/_deps/raylib-src/src/rshapes.c",
  "file": "/m3d/build/_deps/raylib-src/src/rshapes.c"
},
```

As you can see, I get `-DRL_CULL_DISTANCE_FAR=1000.0 -DRL_CULL_DISTANCE_NEAR=0.01` which are the default values.

### Environment

CMake

### Issue Screenshot

N/A

### Code Example

N/A

**Comment by raysan5** [comment]
@VRichardJP I'm afraid I don't maintain the CMake build system, let's see if some user could provide a solution... Maybe @Peter0x44 could take a look or provide more info on this topic.

**Comment by Peter0x44** [comment]
I checked 5.0 and it doesn't expose this either, it isn't a regression.

**Comment by Peter0x44** [comment]
> https://github.com/raysan5/raylib/pull/4044 introduced a way for CMake users to change config.h defines from CMake.

To be clear, it didn't "introduce" it, it just changed how it works to parse the file with a regex to expose the options instead of hardcoding each one as was done before.
This needed two "truth sources" that had to be kept in sync if flags were added/removed or had their defaults changed.

**Comment by Peter0x44** [comment]
I did find a (suboptimal) workaround.
> target_compile_definitions(raylib PUBLIC RL_CULL_DISTANCE_NEAR=5)
Putting this after add_subdirectory of raylib works fine.
I do get this warning:
```
<command-line>: warning: "RL_CULL_DISTANCE_NEAR" redefined
<command-line>: note: this is the location of the previous definition
```
But it is okay, because the last -D is what gcc will select.
I'm still unsure if anything should be done from CMake's end.

**Comment by HarryDC** [comment]
One of the ways to accomplish this via cmake is via [`configure_file`](https://cmake.org/cmake/help/latest/command/configure_file.html) so, create a `config.h.in` with the appropriate values as placeholders e.g. `#cmakedefine RL_CULL_DISTANCE_NEAR`, on the configure step this file would be filled with the values from cmake, i'm not sure if this is compatible with all the other ways that `raylib` can be used. E.g. i don't know for example if it would overwrite an existing `config.h` in the same place that's there for compatibility with other methods of building

**Comment by raysan5** [comment]
Personally, i'm not addressing this feature. I recommend using the raylib provided `config.h` file for the specific project needs. If any expert on CMake finds a better way to address it, feel free to send a PR for review.
