### ISSUE TITLE
[rcore] INPUT_MOUSE_WHEEL_MOTION events aren't replayed correctly

### ISSUE THREAD

**Issue by RMcTn** [raysan5/raylib#4263]
### Issue description
In the `core_automation_events` example, the camera zoom can be changed by scrolling the mouse wheel. Recording mouse wheel events and then replaying them does not change the camera zoom.
### Environment
Platform - DESKTOP (GLFW) / WEB
Operating System - macOS 14.5
OpenGL version - 4.1 Metal

### Issue Screenshot
https://github.com/user-attachments/assets/f66fa2c1-4cdb-4c31-9462-f4f832d026cf

### Code Example
Using the `core_automation_events` example either through the web (https://www.raylib.com/examples/core/loader.html?name=core_automation_events) or desktop:
- Start recording inputs
- Scroll the mouse wheel (Camera zoom should change)
- Stop recording inputs
- Replay inputs (Camera zoom won't change)

**Comment by raysan5** [comment]
@RMcTn Fixed.
