### ISSUE TITLE
[rcore] Tint Alpha not applied to texture when using BLEND_ALPHA_PREMULTIPLY

### ISSUE THREAD

**Issue by AITYunivers** [raysan5/raylib#4269]
Please, before submitting a new issue verify and check:

 - ☑️ I tested it on latest raylib version from master branch
 - ☑️ I checked there is no similar issue already reported
 - ☑️ I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - ☑️ My code has no errors or misuse of raylib

### Issue description

When using an alpha of any value in a DrawTexture call's tint while the blend mode for premultiplied alpha is enabled, the alpha will not be applied to the image, even if it's 0.

### Issue Screenshot

Left is with Premultiplied Alpha on with a tint of (255, 255, 255, 105) (Issue)
Middle is with Premultiplied Alpha off with a tint of (255, 255, 255, 105)
Right is with Premultiplied Alpha on with a tint of WHITE with a shader multiplying the color.rgba by 105

![image](https://github.com/user-attachments/assets/1ac7b238-5737-421f-8882-621fad5495c9)

### Code Example

```c
BeginBlendMode(BLEND_ALPHA_PREMULTIPLY);
    DrawTexture(texture, posX, posY, (Color){ 255, 255, 255, 105 });
EndBlendMode();
```

**Comment by AITYunivers** [comment]
@veins1 What you do and "don't" want to do with premultiplied alphas doesn't change anything. You should still be able to use the tint properly.

**Comment by AITYunivers** [comment]
@veins1 That's the complete opposite of what premultiplied alpha is.

![Screenshot_20240819-205030_Google.jpg](https://github.com/user-attachments/assets/5cb58237-febf-4208-8fdc-8593e1b1bc4d)

**Comment by AITYunivers** [comment]
What's your problem man? Lol. It's not unreasonable to expect the tint alpha to change the image's alpha, and it's not impossible to do. It shouldn't effect most if not all projects, and it's a normal thing you'd find in any game engine or rendering framework with premultiplied alpha and color tints. It's logically expected behaviour vs your flawed logic's behaviour. Ray said he'd make the choice himself in a few months so there's no use arguing over this.

**Comment by AITYunivers** [comment]
I should add on that I'm fine with it like, not multiplying the color.rgb by tint.a, that's just what I know game engines I've used have done it when you look into the code. But it should most definitely be multiplying color.a by tint.a. Which is the main issue here. If a color has 0 alpha, you 100% should not be seeing that image.

**Comment by raysan5** [comment]
@AITYunivers sincerely, I don't know how it can be addressed, what is your proposed solution? I agree with @veins1 in the mentioned points.

**Comment by AITYunivers** [comment]
@raysan5 Not really too sure how OpenGL works. But doesn't Raylib have a default fragment shader? Can't you incorporate it into that? Also it could just be a flag in ConfigFlags or a #define. I don't know how you'd do it in compatibility for OpenGL 1.1 though, since iirc that doesn't have fragment shaders.

**Comment by raysan5** [comment]
@AITYunivers If I modify the default shader it would affect all the drawn elements in all cases, I'm afraid I can't do that.

**Comment by AITYunivers** [comment]
@raysan5 Can't you just check the Blend Mode? That solves the second issue, and by correlation the first issue.

**Comment by raysan5** [comment]
@AITYunivers What do you mean? The blend mode is setup at OpenGL level, afaik, not much options to consider premultiplied textures in there but feel free to investigate that possibility...

**Comment by AITYunivers** [comment]
@raysan5 The textures are premultiplied on render, right? Do you not store the blend mode from BeginBlendMode?

**Comment by raysan5** [comment]
@AITYunivers Yes but I'm afraid I can't predict if the provided texture by user has alpha premultiplied or not, so I can't apply a solution. What if the provided texture for blending has no premultiplied alpha? If considering the texture as premultiplied it wouldn't work as expected for those cases.

I'm closing this issue because I can't see a way to address it but, please, if you can find a solution feel free to send a Pull-Request for review.

**Comment by AITYunivers** [comment]
Textures don't just... have premultiplied alpha, that's not how this works.

Premultiplied Alpha is only applied when the blending mode is enabled, and it's applied by OpenGL, not the user. Premultiplied Alpha multiplies the color by the alpha when rendered with the blend mode enabled, it's nothing the user does with their texture.

Raylib has full knowledge of when a texture is going to be drawn with or without premultiplied alpha.

**Comment by raysan5** [comment]
@AITYunivers Sincerely, no idea how to address this issue. Feel free to send a PR to review.
