### ISSUE TITLE
[rtext] LoadFontEx does not set dont size correctly

### ISSUE THREAD

**Issue by lvntky** [raysan5/raylib#4281]
### Issue description

When I try to load a font using the LoadFontEx function with raylib, no matter how much I set the font size, it is set to 10. This problem is solved when I manually give the font size to the DrawTextEx function, but font.baseSize is always set to 10 pixels.

### Environment

OS: Arch Linux x86_64
Kernel: 6.10.6-arch1-1
GPU: NVIDIA GeForce GTX 1050 Ti

### Issue Screenshot
![raylib_issue](https://github.com/user-attachments/assets/ba50dbd1-ad40-464e-aef4-a2fce19171ed)

### Code Example
```c
Font gohu_font = LoadFontEx("/home/levent/Projects/c6502/resources/gohu.ttf", 604, 0, 2500);
    SetTextLineSpacing(16);         // Set line spacing for multiline text (when line breaks are included '\n')

    printf("base font size: %d\n", gohu_font.baseSize);
    // Main emulation loop
    while (!WindowShouldClose()) {
        // Draw
        BeginDrawing();
        ClearBackground(BLACK);
        //DrawText("c6502 Emulator and Debugger", 0, 0, 20, LIGHTGRAY);
        DrawTextEx(gohu_font, "c6502 Emulator & Debugger", (Vector2){100.0f, 10.0f}, 32, 2, LIGHTGRAY);
        EndDrawing();

```

**Comment by raysan5** [comment]
@lvntky Actually it reports the size of the default font fallback because it failed at finding the provided .ttf path.
