### ISSUE TITLE
[shapes] DrawPoly() drawing behind QUADS

### ISSUE THREAD

**Issue by dginu85** [raysan5/raylib#429]
Hi nice people, I have a problem.
I print a texture as a background, and then I try to print a polygon.
But the polygon is printed under the texture.
Is it a bug?
```c
BeginDrawing();
ClearBackground({ 0,0,0,0 });
DrawTexture(BACKGROUND, 0, 0, WHITE);
DrawPoly({ GetMouseX(), GetMouseY() }, 4, 80, 0, { 255,0,0,255 });
EndDrawing();
```

**Comment by raysan5** [comment]
Ouch... that issue again... more [info here](https://github.com/raysan5/raylib/wiki/raylib-internal-buffers-(2D-vs-3D)).

`DrawPoly()` uses TRIANGLES, and QUADS are always drawn in front of TRIANGLES by library design. I have to review that, it's a known issue. Could you use rectangles in the meantime?

**Comment by dginu85** [comment]
Hello, thanks for your reply.
I use the rectangles, but I wanted to use this function to smooth the corners.
I wait for the solution.

Thank you.

**Comment by raysan5** [comment]
Corrected with commit https://github.com/raysan5/raylib/commit/8d81b6e4e40ea8ad01acea8bfbda38840eb7027f
