### ISSUE TITLE
[build] Add an option to `build.zig` to support different `rcore` platforms

### ISSUE THREAD

**Issue by Not-Nik** [raysan5/raylib#4299]
The `build.zig` script currently doesn't provide an option to switch between the different desktop platform implementations.

I would add one myself, but I lack time to create and test that functionality.

ref: Not-Nik/raylib-zig#143

**Comment by raysan5** [comment]
@Not-Nik I'm afraid I don't maintain the zig build system, let's see if someone wants to take care of it in a couple of weeks or this issue will be closed...

**Comment by raysan5** [comment]
I'm closing this issue due to being a specific feature-request for `build.zig`, any Zig user on this need, feel free to send a PR.
