### ISSUE TITLE
[core] void InitWindow(int width, int height, void *data);  C++ compilation

### ISSUE THREAD

**Issue by tristonl** [raysan5/raylib#430]
In the latest dev branch today G++ Compilation fails (the C version works) at:
core_basic_window.cpp:31:78: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
  InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");

It works if I use a non const char:
char title[] = "Test Title";
InitWindow(screenWidth, screenHeight, title);

It was working 2day ago. I think it's because this was removed from raylib.h in dev ~Line 675
InitWindow(int width, int height, const char *title); 

Master branch is working with:  ~Line 715
#if defined(PLATFORM_ANDROID)
RLAPI void InitWindow(int width, int height, void *state);        // Initialize Android activity
#elif defined(PLATFORM_DESKTOP) || defined(PLATFORM_RPI) || defined(PLATFORM_WEB)
RLAPI void InitWindow(int width, int height, const char *title);  // Initialize window and OpenGL context
#endif

**Comment by raysan5** [comment]
Hi @tristonl, did you managed to solve this issue?

**Comment by tristonl** [comment]
Yes. I just did converted the const string to a non-const char for the 3rd arg  
char text[65];   strncpy(text, title_.c_str(), sizeof(text));   text[65]='\0';
InitWindow(width_, height_, text);

I realize the dev branch is experimental so i was jumping the gun a bit :)

**Comment by raysan5** [comment]
Ok, I see. In any case, thanks for reporting it!
