### ISSUE TITLE
Debugger isn't working (mac, nvim)

### ISSUE THREAD

**Issue by Woit** [raysan5/raylib#4301]
https://github.com/raysan5/raylib/blob/5f49ec3d6448502d798d4d404e08e354ec48012a/projects/scripts/build-osx.sh#L145

Hey!

Im using mac m1/neovim/codelldb for debug a game, which is builded with this lines. For some reason (im not yet found why) if cc command is splitted for cc -c and cc -o, compiler didn't produce .dSYM folder/files, which is required for debug. Even if -g flag and -O0 exists. I solve it by merging this two commands into one loooong line. Maybe it will help to someone.

**Comment by raysan5** [comment]
It seems this issue is out of scope of raylib...
