### ISSUE TITLE
[base] Add support for Meson Build System.

### ISSUE THREAD

**Issue by Universal-Flare** [raysan5/raylib#4303]
Meson support needs to be officially added.

**Comment by raysan5** [comment]
nope, it is not needed.

**Comment by Universal-Flare** [comment]
why not tho?

**Comment by Universal-Flare** [comment]
atleast how could i use it with meson ?

**Comment by gen2brain** [comment]
@Universal-Flare The build system officially maintained is `Makefile`, the simplest and works everywhere. The community contributed to and maintains the `CMake`, and there is also `build.zig`, again community maintained. Asking that someone adds something you want is not how things works, so either you contribute and create a `meson.build` that may or may not be accepted or you do it in your project. Asking how to use raylib with meson seems like you don't have a clue how meson works but you just want it for some reason. Of course, such issues will be discarded. Also, not a good choice of words with `it needs`, it doesn't need to be added, it is just something you would like to have.

**Comment by Universal-Flare** [comment]
ok..

**Comment by Universal-Flare** [comment]
also, the cmake module doesn't work ad it just shows a bunch of undefined raylib function errors and not found GLFW functions as far as I tested
