### ISSUE TITLE
GenImagePerlinNoise does not support passing x/y origin

### ISSUE THREAD

**Issue by Gamerfiend** [raysan5/raylib#431]
Current implementation of function does not allow passing an x and y origin coordinates, therefore an image of the same size and scale will always produce the same generated image.

**Comment by raysan5** [comment]
Hi @Gamerfiend, just answered you on Gitter, using function scale factor you can control noise scale, try using values from 1.0f to 16.0f.

**Comment by raysan5** [comment]
Support for offset added in commit https://github.com/raysan5/raylib/commit/c8e97df233f50b0bc1cba07e014aca93c5c0f15c

**Comment by Gamerfiend** [comment]
Thank you!
