### ISSUE TITLE
[rtexture] Drawing texture with negative width or height draws nothing

### ISSUE THREAD

**Issue by lxmcf** [raysan5/raylib#4316]
### Issue description

When drawing a sprite with a negative value on only 1 axis; the sprite will not be rendered.

When using a negative value on the x and y axis, will render as expected, code example should have expected behaviour of the image only being flipped on the xaxis.

### Environment

Fedora Workstation 40, OpenGL 4.6, Intel ADL Gt2 and rx7900xt GPU tested.

### Issue Screenshot

![image](https://github.com/user-attachments/assets/d0f5055f-5313-461e-91ad-964efa524747)

### Code Example
```c
#include <raylib.h>

int main () {
    InitWindow (640, 360, "Hello World");

    Texture2D texture = LoadTexture ("image.png");

    while (!WindowShouldClose ()) {
        BeginDrawing ();
        ClearBackground (SKYBLUE);

        Rectangle source = {
            .x      = 0,
            .y      = 0,
            .width  = (float)texture.width,
            .height = (float)texture.height,
        };

        Rectangle destination = {
            .x      = 320,
            .y      = 180,
            .width  = -(float)texture.width,
            .height = (float)texture.height,
        };

        DrawTexturePro (texture, source, destination, CLITERAL (Vector2){0, 0}, 0, WHITE);
        EndDrawing ();
    }

    UnloadTexture (texture);

    CloseWindow ();
}
```

**Comment by raysan5** [comment]
@lxmcf Yes, this is the expected behaviour. Destination width/height can not be negative. Added an additional check.
