### ISSUE TITLE
[rmodels] .mtl texture file does not automatically apply to .obj model file when displayed.

### ISSUE THREAD

**Issue by Haysher** [raysan5/raylib#4322]
.mtl file does not automatically work when using a .obj file 

`
#include "raylib.h"

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - 3d camera mode");

    // Define the camera to look into our 3d world
    Camera3D camera = { 0 };
    camera.position = { 0.0f, 10.0f, 10.0f };           // Camera position
    camera.target = { 0.0f, 0.0f, 0.0f };               // Camera looking at point
    camera.up = { 0.0f, 1.0f, 0.0f };                   // Camera up vector (rotation towards target)
    camera.fovy = 45.0f;                                // Camera field-of-view Y
    camera.projection = CAMERA_PERSPECTIVE;             // Camera mode type
    Model ChessBoard = LoadModel("C:/Chess assets/ChessBoard.obj");

    Vector3 boardPosition = { 0.0f, 0.0f, 0.0f };

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        // TODO: Update your variables here
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

        ClearBackground(RAYWHITE);

        BeginMode3D(camera);

        DrawModel(ChessBoard, boardPosition, 10, WHITE);

        DrawGrid(10, 1.0f);

        EndMode3D();

        DrawText("Welcome to the third dimension!", 10, 40, 20, DARKGRAY);

        DrawFPS(10, 10);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
`

**Comment by raysan5** [comment]
@Haysher Please, could you post the output log? It seems the issue is related to the provided model path, it's not recommended to use full-paths on your application.

**Comment by Haysher** [comment]
Yes, I will do that.

**Comment by Haysher** [comment]
![image](https://github.com/user-attachments/assets/257ee0bd-1f3f-44b5-8621-c33ecec2a1f5)

**Comment by Haysher** [comment]
I moved the files into the folder with the code and it still doesn't work.

**Comment by raysan5** [comment]
@Haysher Per the image, I'm afraid you are using raylib 4.5, obj and materials loading has been greatly improved since that version, you should use latest raylib 5.5-dev from github master brach.
