### ISSUE TITLE
[rcore] Parser - invalid raylib_api.json

### ISSUE THREAD

**Issue by Leopotam** [raysan5/raylib#4323]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Paser generates invalid json api file after commit #16e9317220bcede380873d2000c1ccd5062e3f07 by @foxblock  - `"`-quotes should be backslashed:
```json
"Load directory filepaths with extension filtering and recursive directory scan. Use "/DIR" in the filter string to include directories in the result",
```
`"/DIR"` should be `\"/DIR\"`

**Comment by raysan5** [comment]
@Leopotam Good catch, actually that keyword should be reviewed...

**Comment by Leopotam** [comment]
@raysan5 can be fast fixed in this way:
```c
static char *EscapeBackslashes(char *text)
{
    static char buffer[256] = {0};

    int count = 0;

    for (int i = 0; (text[i] != '\0') && (i < 255); i++, count++)
    {
        // start of fix.
        if (text[i] == '"')
        {
            buffer[count] = '\\';
            count++;
        }
        // end of fix.
        buffer[count] = text[i];

        if (text[i] == '\\')
        {
            buffer[count + 1] = '\\';
            count++;
        }
    }

    buffer[count] = '\0';

    return buffer;
}
```

**Comment by Leopotam** [comment]
Maybe, buffer size should be increased too (up to 512), for new poetry in api comments.

**Comment by raysan5** [comment]
@Leopotam Reviewed required tag and buffer size.

**Comment by Leopotam** [comment]
issue not solved - problem in api parser, that doesnt generate proper json file for description field that contains quotes (`"`).

**Comment by raysan5** [comment]
@Leopotam Thanks for leting me know! Could you send a PR reviewing the issue?

**Comment by raysan5** [comment]
Never mind, fixed it. Let me know if now it works, please!

**Comment by Leopotam** [comment]
> Probably replacing the double quoates by simple quotes ' would be enough.

it works now, but only before next commit with comment that contains `"`. what about suggestion above with patching `EscapeBackslashes()` function?

**Comment by raysan5** [comment]
@Leopotam I prefer to avoid more code to maintain.

**Comment by Leopotam** [comment]
i see, then better to drop builtin parser and write proper one by myself. thanks for fast fix of `raylib.h`, issue solved.

**Comment by raysan5** [comment]
> @raysan5 i see, then better to drop builtin parser and write proper one by myself.

Sure! That's the spirit of open source! 👍😄
