### ISSUE TITLE
[rmodels] .obj file wont render in properly with the corresponding .mtl file. 

### ISSUE THREAD

**Issue by Haysher** [raysan5/raylib#4324]
I tried using raylib 5.0 (on msvc) instead of raylib 4.5 (which i used previously when i had the same issue) but it still didnt fix it.

`#include "raylib.h"

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - 3d camera mode");

    // Define the camera to look into our 3d world
    Camera3D camera = { 0 };
    camera.position = { 0.0f, 10.0f, 10.0f };               // Camera position
    camera.target = { 0.0f, 1.0f, 0.0f };                   // Camera looking at point
    camera.up = { 0.0f, 1.0f, 0.0f };                       // Camera up vector (rotation towards target)
    camera.fovy = 45.0f;                                    // Camera field-of-view Y
    camera.projection = CAMERA_PERSPECTIVE;                 // Camera mode type
    Model ChessBoard = LoadModel("Assets/ChessBoard.obj");

    Vector3 boardPosition = { 0.0f, 2.0f, 0.0f };

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        // TODO: Update your variables here
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

        ClearBackground(RAYWHITE);

        BeginMode3D(camera);

        DrawModel(ChessBoard, boardPosition, 10, RED);

        DrawGrid(10, 1.0f);

        EndMode3D();

        DrawText("Welcome to the third dimension!", 10, 40, 20, DARKGRAY);

        DrawFPS(10, 10);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;

}`

terminal:
![image](https://github.com/user-attachments/assets/b8041671-1b84-4b14-86bd-886242b0f846)

**Comment by Haysher** [comment]
is this because of lighting or is it because the .mtl file isnt loading.

**Comment by raysan5** [comment]
@Haysher raylib 5.0 is almost one year old, you should use latest raylib 5.5-dev from GitHub master branch. It needs to be compiled by sources.

Obj and mtl loading has already been reviewed there.

**Comment by Haysher** [comment]
Yes I did but I couldn't figure out how to use the version.

**Comment by Haysher** [comment]
How do I compile it?

**Comment by raysan5** [comment]
@Haysher you got some info on the Wiki: https://github.com/raysan5/raylib/wiki/Working-on-Windows

Also for other platforms
