### ISSUE TITLE
[rmodels] OBJ model texture not loaded

### ISSUE THREAD

**Issue by Haysher** [raysan5/raylib#4328]
Models load in correctly but without textures.

`

#include "raylib.h"
//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - 3d camera mode");

    // Define the camera to look into our 3d world
    Camera3D camera = { 0 };
    camera.position = (Vector3){ 0.0f, 10.0f, 10.0f };               // Camera position
    camera.target = (Vector3){ 0.0f, 1.0f, 0.0f };                   // Camera looking at point
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };                       // Camera up vector (rotation towards target)
    camera.fovy = 45.0f;                                    // Camera field-of-view Y
    camera.projection = CAMERA_PERSPECTIVE;                 // Camera mode type
    Model ChessBoard = LoadModel("resources/Chessboard.obj");

    Vector3 boardPosition = { 0.0f, 2.0f, 0.0f };

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        // TODO: Update your variables here
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

        ClearBackground(RAYWHITE);

        BeginMode3D(camera);

        DrawModel(ChessBoard, boardPosition, 10, WHITE);
        

        DrawGrid(10, 1.0f);

        EndMode3D();

        DrawText("Welcome to the third dimension!", 10, 40, 20, DARKGRAY);

        DrawFPS(10, 10);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadModel(ChessBoard);
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}`

![image](https://github.com/user-attachments/assets/02b1e551-1790-4ced-808c-43d0f8e34cd6)

**Comment by raysan5** [comment]
@Haysher Please, could you provide the used resources (.obj, .mtl, .png) for testing?

**Comment by raysan5** [comment]
Can not test.

**Comment by Haysher** [comment]
i forgot about this
