### ISSUE TITLE
[rcore] GIF recording depends on GetFrameTime()

### ISSUE THREAD

**Issue by infdivzero** [raysan5/raylib#4339]
If CUSTOM_FRAME_CONTROL is defined, CORE.Time.frame isn't updated and GetFrameTime() returns 0. In EndDrawing(), the GIF recorder calls GetFrameTime() and will never add GIF frames to the recording. UpdateCamera() also requires GetFrameTime().

I have a few ideas:
1. Split out the gif recorder code. For example, the EndDrawing() code that updates the GIF could be called UpdateRecording(float deltaTime, ...).
2. Allow GetFrameTime() to be overridden somehow, such as a callback, macro, or through static linking with a function defined in the application code. The last one seems hacky.
3. Make ``CoreData CORE`` extern and define CoreData in a header, exposing CORE.Time.frame.

**Comment by raysan5** [comment]
@infdivzero None of the proposed solution seems good enough, just adding code complexity to address a very specific use-case.
`CUSTOM_FRAME_CONTROL` is intended for advance use case, users on that situation could easely adapt raylib for their specific needs.
