### ISSUE TITLE
RAYGUI : Undefined Reference and Double Defined Errors

### ISSUE THREAD

**Issue by Universal-Flare** [raysan5/raylib#4345]
Please, before submitting a new issue verify and check:

 - [yes] I tested it on latest raylib version from master branch
 - [yes] I checked there is no similar issue already reported
 - [yes] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [yes] My code has no errors or misuse of raylib

### Issue description
It shows the error of Double Definitions which are defined in both raylib and raygui.
Without ``` #define RAYGUI_IMPLEMENTATION ``` at the top of the code, it shows an undefined reference error when run.

### Environment
OS: Windows 11
OpenGL: Same from Raylib Default
Build System: Meson

### Code Example
```
#include "raylib.h"

#define RAYGUI_IMPLEMENTATION
#include "raygui.h"

int main() {

    int screenWidth = 800;
    int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "");
    SetTargetFPS(60);

    bool BOXActive = true;

    Rectangle layoutRecs[1] = {
        (Rectangle){ 352, 64, 512, 408 },
    };

    while (!WindowShouldClose()) {

            ClearBackground(GetColor(GuiGetStyle(DEFAULT, BACKGROUND_COLOR)));

            if (BOXActive) {
                BOXActive = !GuiWindowBox(layoutRecs[0], "BOX_NAME");
            }

        EndDrawing();
    }

    CloseWindow();
};
```

**Comment by asdqwe** [comment]
> Build System: Meson

Meson is not supported.

Everything is working correctly on raylib ([0573ef0](https://github.com/raysan5/raylib/tree/0573ef03820f0948b38d52236d15c2f18c871cc7)) and raygui ([1e03efc](https://github.com/raysan5/raygui/tree/1e03efca48c50c5ea4b4a053d5bf04bad58d3e43)):

```
$ unzip raylib-master.zip
$ cd raylib-master/src/
raylib-master/src$ make PLATFORM=PLATFORM_DESKTOP
raylib-master/src$ cd ../examples/
raylib-master/examples$ sed -n '16,25p' shapes/shapes_draw_circle_sector.c
#include <raylib.h>

#define RAYGUI_IMPLEMENTATION
#include "raygui.h"                 // Required for GUI controls

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
int main(void)
{
raylib-master/examples$ make PLATFORM=PLATFORM_DESKTOP shapes/shapes_draw_circle_sector
raylib-master/examples$ ./shapes/shapes_draw_circle_sector 
INFO: Initializing raylib 5.5-dev
INFO: Platform backend: DESKTOP (GLFW)
...
INFO: Window closed successfully
```

**Comment by Universal-Flare** [comment]
Raylib Works perfectly fine with meson as I am using the CMake Module

**Comment by Universal-Flare** [comment]
sorry, accidentally clicked the wrong button

**Comment by Universal-Flare** [comment]
As i was saying, the raygui.h file for that code in my project does not work and give those errors.
I thought it was because of the first inititalisation of the functions but i was wrong

**Comment by raysan5** [comment]
@Universal-Flare I'm afraid I can't reproduce, it could be related to the build system used.
