### ISSUE TITLE
[rmodels] Errors during LoadMesh on MacOS

### ISSUE THREAD

**Issue by TillWege** [raysan5/raylib#4346]
### Issue description

Since #4321 uploading Meshes on MacOS will randomly fail and cause the running program to crash.

### Environment

- MacBook Pro M1 16gb running MacOS 15

### Issue Screenshot

<img width="631" alt="image" src="https://github.com/user-attachments/assets/64f448c8-1f09-4fe0-b210-af3921eb5b7a">

### Code Example

```c++
#define MODEL_FOLDER "models/"

int main()
{
	const int screenWidth = 1280;
	const int screenHeight = 720;

	InitWindow(screenWidth, screenHeight, "Window");

	std::vector<Model> models;

	for (const auto& entry : std::filesystem::directory_iterator(MODEL_FOLDER)) {
		std::string path = entry.path().string();
		std::string fileName = entry.path().filename().string();
		if (IsFileExtension(fileName.c_str(), ".obj")) {
			Model model = LoadModel(path.c_str());
			models.push_back(model);
		}
	}
}
```

Running this leads to it crashing within the first ~4 models it tries to load. It doesn't seem to change whether its .obj or .gltf files.

**Comment by JeffM2501** [comment]
It's possible that the mac may only support 8 VBOs, the code should check GL for the max and not try to load them all if possible.
We may need to tie the GPU skinning feature to a flag that apple platforms do not set, or perhaps remove one of the other less used VBOs

**Comment by deDug** [comment]
This could be the same problem as https://github.com/raysan5/raylib/issues/4343 where loading mesh a bad define means the wrong amount of memory is allocated for VBo indices. 
You could try changing `MAX_MESH_VERTEX_BUFFERS` in `config.h` to 9 and see if that fixes it.

**Comment by TillWege** [comment]
Yeah you seem to be right. When I change it to 7 the crash doesnt appear.

**Comment by JeffM2501** [comment]
I just tested on an intel mac, and can verify that yes, the mac only supports 8 VBOs. 
We will have to not support GPU meshes on the mac, and move those buffers to the end.
This includes meshes that don't even use animations, the change to use 9 VBOs just strait up breaks meshes on Mac OS.

**Comment by JeffM2501** [comment]
PR https://github.com/raysan5/raylib/pull/4348 should disable this feature for MacOS

**Comment by stevegwh** [comment]
@raysan5 @JeffM2501 Not sure if this is the place to put this but: GPU Skinning (#4321) works fine for me on macOS (Sonoma 14.6.1) (M1 MacBook Air 2020) after changing "MAX_MESH_VERTEX_BUFFERS" to 9 in config.h. This is using the example and model from "models_gpu_skinning.c" (I'll include it below, also). So, at least on my machine, macOS does support GPU skinning and all other models also load fine.

I'm happy to test more things out if you want. 
```
// models_gpu_skinning.c

#include "raylib.h"

#include "raymath.h"

#if defined(PLATFORM_DESKTOP)
    #define GLSL_VERSION            330
#else   // PLATFORM_ANDROID, PLATFORM_WEB
    #define GLSL_VERSION            100
#endif

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [models] example - GPU skinning");

    // Define the camera to look into our 3d world
    Camera camera = { 0 };
    camera.position = (Vector3){ 5.0f, 5.0f, 5.0f }; // Camera position
    camera.target = (Vector3){ 0.0f, 2.0f, 0.0f };  // Camera looking at point
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };      // Camera up vector (rotation towards target)
    camera.fovy = 45.0f;                            // Camera field-of-view Y
    camera.projection = CAMERA_PERSPECTIVE;         // Camera projection type

    // Load gltf model
    Model characterModel = LoadModel("resources/models/gltf/greenman.glb"); // Load character model
    
    // Load skinning shader
    Shader skinningShader = LoadShader(TextFormat("resources/shaders/glsl%i/skinning.vs", GLSL_VERSION),
                                       TextFormat("resources/shaders/glsl%i/skinning.fs", GLSL_VERSION));
    
    characterModel.materials[1].shader = skinningShader;
    
    // Load gltf model animations
    int animsCount = 0;
    unsigned int animIndex = 0;
    unsigned int animCurrentFrame = 0;
    ModelAnimation *modelAnimations = LoadModelAnimations("resources/models/gltf/greenman.glb", &animsCount);

    Vector3 position = { 0.0f, 0.0f, 0.0f }; // Set model position

    DisableCursor();                    // Limit cursor to relative movement inside the window

    SetTargetFPS(60);                   // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())        // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        UpdateCamera(&camera, CAMERA_THIRD_PERSON);
        
        // Select current animation
        if (IsKeyPressed(KEY_T)) animIndex = (animIndex + 1)%animsCount;
        else if (IsKeyPressed(KEY_G)) animIndex = (animIndex + animsCount - 1)%animsCount;

        // Update model animation
        ModelAnimation anim = modelAnimations[animIndex];
        animCurrentFrame = (animCurrentFrame + 1)%anim.frameCount;
        UpdateModelAnimationBoneMatrices(characterModel, anim, animCurrentFrame);
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            BeginMode3D(camera);
            
                // Draw character
                characterModel.transform = MatrixTranslate(position.x, position.y, position.z);
                UpdateModelAnimationBoneMatrices(characterModel, anim, animCurrentFrame);
                DrawMesh(characterModel.meshes[0], characterModel.materials[1], characterModel.transform);

                DrawGrid(10, 1.0f);
            EndMode3D();

            DrawText("Use the T/G to switch animation", 10, 10, 20, GRAY);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadModelAnimations(modelAnimations, animsCount);
    UnloadModel(characterModel);         // Unload character model and meshes/material
    UnloadShader(skinningShader);
    
    CloseWindow();              // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by JeffM2501** [comment]
> @raysan5 @JeffM2501 Not sure if this is the place to put this but: GPU Skinning (#4321) works fine for me on macOS (Sonoma 14.6.1) (M1 MacBook Air 2020) after changing "MAX_MESH_VERTEX_BUFFERS" to 9 in config.h. This is using the example and model from "models_gpu_skinning.c" (I'll include it below, also). So, at least on my machine, macOS seems to support GPU skinning and all other models that I have tried load fine. Unless I've misunderstood, something.

> ```
I'm going to try this with the config fix and see if that is the issue.

**Comment by stevegwh** [comment]
@JeffM2501 Cool. You can see here for more info: #4349 
Especially, HarryDC's comment (can't tag him, for some reason): "This is the model i used to check, the issue is most likely a MAX_MESH_VERTEX_BUFFERS definition in config.h line 231 that is 7, whereas the value needs to be 9 as defined in line 123 in rmodels.c"

Once I changed MAX_MESH_VERTEX_BUFFERS to 9 in config.h, models loaded fine and I've been using GPU skinning on macOS without issue since then.

**Comment by JeffM2501** [comment]
Yeah that was the issue, it does work on the mac. I have summited PR#4353 that should get it all in line.
