### ISSUE TITLE
[rmodels] Loading various models causes MSVC Heapcheck to fail on unload

### ISSUE THREAD

**Issue by HarryDC** [raysan5/raylib#4349]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

Using Microsoft Visual Studio and a debug build, when i load various models from the Kenney Hex set in both `.obj` and `.glb` format, runtime issues a warning about a Heap Corruption at the `UnloadModel()` call, the same models work fine using v5.0. This even happens when just LoadModel()/UnloadModel() is used without drawing. 

After using `git bisect` from the current main as of today back to v5.0 the offending commit was labeled as 86ead962633f5ee819829550dc8acdd9cd07f667 (Optional GPU Skinning)

### Environment

Windows 11, MSVC 

### Issue Screenshot
![image](https://github.com/user-attachments/assets/c88e19e6-db2d-4e7a-bcb8-b4a00e027225)

![image](https://github.com/user-attachments/assets/b9dc2b06-782d-4193-94cd-0f6849eb6dd1)

### Code Example

...
    model = LoadModel("resources/obj/dirt.obj");
    UnloadModel(model);
...

**Comment by HarryDC** [comment]
[dirt.zip](https://github.com/user-attachments/files/17182436/dirt.zip)

This is the model i used to check, the issue is most likely a `MAX_MESH_VERTEX_BUFFERS` definition in config.h line 231 that is 7, whereas the value needs to be 9 as defined in line 123 in rmodels.c

**Comment by stevegwh** [comment]
Can confirm this seems to occur on macOS with clang, too. I checked out the "Optional GPU Skinning" (86ead96) commit today and encountered the same error with "MAX_MESH_VERTEX_BUFFERS" likely being the culprit. Changing "MAX_MESH_VERTEX_BUFFERS" to "9" in config.h as suggested stopped the error.

**Comment by raysan5** [comment]
@stevegwh Thanks for finding the issue, it should be fixed now.
