### ISSUE TITLE
[all] Add overloads with primitive types to reduce overhead for bindings

### ISSUE THREAD

**Issue by Odex64** [raysan5/raylib#4350]
**Disclaimer:** this is a mess.

### What's wrong with raylib and their bindings
raylib currently provides several functions that accept or return custom structs, which can introduce marshalling costs for binding authors when working with languages outside of C. In fact, some bindings (at least for C#) provide low level access to raylib's function in order to not impact too much the performance.

Also, this will also constraint binding authors to follow raylib's structs. If we want to add additional properties to a struct we should create wrapper classes which will introduce additional overhead.

### A possible solution
Ideally, to reduce this overhead and provide better performance and flexibility, raylib should provide overloads that use only primitive types as parameters or return values instead of raylib's own structs. For example if a function returns a struct, we should accept the struct's primitive data as pointers to avoid marshalling overhead, similarly, if a function accepts a struct we should pass that struct's individual primitive types.

### Benefits:
1. **Performance Improvement:** By using primitive types, marshalling costs are eliminated, resulting in faster cross-language interactions.
2. **Flexibility for Bindings Authors:** This approach allows bindings authors to wrap the primitive values into their own classes or structs, potentially adding additional functionality or fitting them into language-specific paradigms.
3. **Maintainability:** This would allow bindings to stay lightweight and modular without forcing the usage of raylib's predefined struct layouts.

### Example:
Instead of:
```c
void DrawRectangleRec(Rectangle rec, Color color);
```

Provide an overload:
```c
void DrawRectangleRecRaw(float x, float y, float width, float height, int r, int g, int b, int a);
```

---

This approach is more flexible and allows developers to handle their own struct definitions, reducing the dependency on raylib's specific structs while maintaining full compatibility with raylib's API.

Let me know your thoughts or concerns regarding this proposal.

**Comment by raysan5** [comment]
@Odex64 I'm afraid it would imply adding many many function alternatives. Incrementing the maintenance cost and the overall complexity. I prefer to avoid that.
