### ISSUE TITLE
[core] "Closest fullscreen videomode" warning is unavoidable

### ISSUE THREAD

**Issue by Brian-ED** [raysan5/raylib#4355]
I think this LOG_WARNING should be a LOG_INFO
https://github.com/raysan5/raylib/blob/0573ef03820f0948b38d52236d15c2f18c871cc7/src/platforms/rcore_desktop_glfw.c#L1450

because there isn't a way to disable this warning if you start your window with full screen like so:
```
SetConfigFlags(2);
InitWindow(0,0,"name");
```

### Environment
Desktop, Linux mint, OpenGL version 4.6.

### Code Example
```c
#include "raylib.h"
int main ()
{
    SetTraceLogLevel(LOG_WARNING);
    SetConfigFlags(FLAG_FULLSCREEN_MODE);
    InitWindow(0, 0, "");
    CloseWindow();
    return 0;
}
```
Running gives the warning `WARNING: SYSTEM: Closest fullscreen videomode: 1920 x 1080`.

**Comment by raysan5** [comment]
@Brian-ED Yeah, I agree, it seems more an info message than a warning...
