### ISSUE TITLE
[textures] ImageDraw() uses alpha value of destination image for whole resulting image

### ISSUE THREAD

**Issue by srseil** [raysan5/raylib#436]
The function `void ImageDraw(Image *dst, Image src, Rectangle srcRec, Rectangle dstRec);` uses the alpha value of the `dst` Image for the whole resulting image and ignores the alpha value of the `src` Image.

Consider the following code:
```
Color dst_col = (Color) {255, 255, 255, 100};
Color src_col = (Color) {255, 0, 0, 255};
Image dst = GenImageGradientV(1024, 1024, dst_col, dst_col);
Image src = GenImageGradientV(512, 512, src_col, src_col);
ImageDraw(&dst, src, (Rectangle) {0, 0, 512, 512}, (Rectangle) {0, 0, 512, 512});
```

The red image drawn on top of the semi-transparent white one will have the same alpha value (100) as the background image.

**Comment by raysan5** [comment]
Hi @srseil! 

Thanks for reporting this issue, I will review current alpha blending maths...

**Comment by raysan5** [comment]
Just tried reviewing alpha blending in commit https://github.com/raysan5/raylib/commit/533780aadf1ba1b553ef69f191171f6a528ae894 but I'm not sure what value assign to destination.alpha after doing pre-multiplied maths...

Any help on this?

**Comment by raysan5** [comment]
Just noticed this change breaks text drawing on image...

**Comment by raysan5** [comment]
Corrected on commit https://github.com/raysan5/raylib/commit/c51203ae7e7aefac5fa95097d424aefdbe9c759c
