### ISSUE TITLE
When I change the window size with the mouse cursor, the cycle stops working.

### ISSUE THREAD

**Issue by ElectroidDes1** [raysan5/raylib#4361]
Why when changing the window(Windows10) size with the mouse cursor - the rendering cycle is interrupted and does not work?

```
 void render_loop()
{

 while (!WindowShouldClose())
    {
        std::cout<<"while" << std::endl;  //when I change the window size with the mouse cursor, the cycle stops working.

        BeginDrawing();
        ClearBackground(background_color);
        EndDrawing();
    }



    CloseWindow();    
}
```

**Comment by asdqwe** [comment]
Try reviewing your application logic. Everything appears to be working correctly here (Linux). Example:
```
#include "raylib.h"
int main(void) {
    SetConfigFlags(FLAG_WINDOW_RESIZABLE);
    InitWindow(800, 450, "test");
    SetTargetFPS(60);
    while (!WindowShouldClose()) {
        BeginDrawing();
        DrawText( TextFormat("elapsed time: %f", GetTime()), 20, 20, 20, BLACK);
        DrawText( TextFormat("window size: %i x %i", GetScreenWidth(), GetScreenHeight()), 20, 60, 20, BLACK);
        ClearBackground(RAYWHITE);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```

**Comment by ElectroidDes1** [comment]
> #include "raylib.h"
> int main(void) {
>     SetConfigFlags(FLAG_WINDOW_RESIZABLE);
>     InitWindow(800, 450, "test");
>     SetTargetFPS(60);
>     while (!WindowShouldClose()) {
>         BeginDrawing();
>         DrawText( TextFormat("elapsed time: %f", GetTime()), 20, 20, 20, BLACK);
>         DrawText( TextFormat("window size: %i x %i", GetScreenWidth(), GetScreenHeight()), 20, 60, 20, BLACK);
>         ClearBackground(RAYWHITE);
>         EndDrawing();
>     }
>     CloseWindow();
>     return 0;
> }

#include "raylib.h"
int main(void) {
    SetConfigFlags(FLAG_WINDOW_RESIZABLE);
    InitWindow(800, 450, "test");
    SetTargetFPS(60);
    while (!WindowShouldClose()) 
{

 std::cout<<"while" << std::endl;  //!!!!!when I change the window size with the mouse cursor, the cycle stops working.
        BeginDrawing();
        DrawText( TextFormat("elapsed time: %f", GetTime()), 20, 20, 20, BLACK);
        DrawText( TextFormat("window size: %i x %i", GetScreenWidth(), GetScreenHeight()), 20, 60, 20, BLACK);
        ClearBackground(RAYWHITE);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}

**Comment by asdqwe** [comment]
I can't replicate this issue. Everything appears to be working correctly here:

https://github.com/user-attachments/assets/06689505-1f32-49f3-ab21-2c5e4245bb90

**Comment by jamesl-github** [comment]
guessing its a MS Windows thing --
I know the same thing happens when using SDL2 and I think it also happens
with SFML
here's SDL having the same problem
https://github.com/libsdl-org/SDL/issues/1059

there's a whole discussion on SDL and thread blocking events and resizing
over here
https://stackoverflow.com/questions/32294913/getting-continuous-window-resize-event-in-sdl-2

I think SDL2 has added some events to catch the window resize events and so
some repainting, but very few of the examples you see on the web show them

**Comment by raysan5** [comment]
I'm afraid this is the expected behaviour despite not being the desirable one, as commented it depends on the low-level API for Windows management and probably the OS itself.

**Comment by ElectroidDes1** [comment]
> I'm afraid this is the expected behaviour despite not being the desirable one, as commented it depends on the low-level API for Windows management and probably the OS itself.

but in the native WinApi window - this doesn't seem to happen.

**Comment by raysan5** [comment]
@ElectroidDes1 did you try if it happens with GLFW and SDL that are some of the underlying raylib libraries for window management?

**Comment by jamesl-github** [comment]
same with SDL3 

should say "Left!"   but it stops redrawing while resizing with the mouse 
once resizing is done "Left!" appears correctly 
[https://imgur.com/a/rCt1q6o](url)

`
//Using SDL 3.1.3 Stable ABI Preview
// https://github.com/libsdl-org/SDL/releases/tag/preview-3.1.3 

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

//Screen dimension constants
const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 480;

//The window we'll be rendering to
SDL_Window* gWindow = NULL;

//The window renderer
SDL_Renderer* gRenderer = NULL;

//Current displayed texture
SDL_Texture* gTexture = NULL;

int main( int argc, char* args[] )
{
    
    if( ! SDL_CreateWindowAndRenderer( "SDL Tutorial", SCREEN_WIDTH, SCREEN_HEIGHT, SDL_WINDOW_RESIZABLE, &gWindow, &gRenderer ) )
    {
        SDL_Log( "Renderer could not be created! SDL Error: %s\n", SDL_GetError() );
        exit(1);
    }
    
    SDL_Surface* loadedSurface = SDL_LoadBMP( "left.bmp" );
    if( loadedSurface == NULL )
    {
        SDL_Log( "Unable to load image %s! SDL Error: %s\n", "left.bmp", SDL_GetError() );
        exit(2);
    }
    else
    {
        //Create texture from surface pixels
        gTexture = SDL_CreateTextureFromSurface( gRenderer, loadedSurface );
        if( gTexture == NULL )
        {
            SDL_Log( "Unable to create texture from %s! SDL Error: %s\n", "left.bmp", SDL_GetError() );
            exit(3);
        }
        //Get rid of old loaded surface
        SDL_DestroySurface( loadedSurface );
    }
    //Initialize renderer color
    SDL_SetRenderDrawColor( gRenderer, 0xFF, 0x00, 0x00, 0xFF );
    
    //Main loop flag
    bool quit = false;
    
    //Event handler
    SDL_Event e;
    
    //While application is running
    while( !quit )
    {
        //Handle events on queue
        while( SDL_PollEvent( &e ) != 0 )
        {
            //User requests quit
            if( e.type == SDL_EVENT_QUIT )
            {
                quit = true;
            }
            else if( e.type == SDL_EVENT_KEY_DOWN )
            {
                switch( e.key.key )
                {
                    case SDLK_ESCAPE:
                        quit = true;
                    break;
                        
                    default:
                        quit = true;
                    break;
                }
            }
        }
        
        //Clear screen
        SDL_RenderClear( gRenderer );
        
        //Render texture to screen
        SDL_RenderTexture( gRenderer, gTexture, NULL, NULL );
        
        //Update screen
        SDL_RenderPresent( gRenderer );
    }
    
    //Free loaded image
    SDL_DestroyTexture( gTexture );
    gTexture = NULL;
    //Destroy window
    SDL_DestroyRenderer( gRenderer );
    SDL_DestroyWindow( gWindow );
    gWindow = NULL;
    gRenderer = NULL;
    
    //Quit SDL subsystems
    SDL_Quit();
}
`
