### ISSUE TITLE
[compile] Having trouble implementing external library

### ISSUE THREAD

**Issue by iancarnation** [raysan5/raylib#437]
Hi There!

I have a student interested in loading string data from a text file, so I thought I'd introduce her to JSON and look for a little library to parse that in C. I found [json.h](https://github.com/sheredom/json.h) from stb's [single_file_libs](https://github.com/nothings/single_file_libs) list.

It is just a header and c file, and I found some other questions and Issues related to libraries where people were instructed to 'put the files in the right directory,' but I have yet to succeed myself.

Things I attempted with a modified core_basic_window example file:
* put files in same directory as program
* put files in 'src/external' and included header
* edit src Makefile to mimic usage of stb_vorbis library, compile src, compile project
* tried ```#include "external/json.h"``` instead of ```#include "json.h"``` in my program 
* tried compiling program in 'games' folder (compiling the whole directory) and it seemed to be skipped

When I compile+execute, i get a "json.h: No such file or directory"

I know this is more of an issue with me being a compiling noob, but I would appreciate any guidance. 

Thank you for raylib, it is a great learning tool!

**Comment by iancarnation** [comment]
In my brain-scrambled state I totally neglected the forum at raylib.com. Apologies if this is a more appropriate question there, happy to migrate and you can delete this Issue.

**Comment by RDR8** [comment]
This may not be exactly what you need, but for me, example programs need to be invoked from within the directory containing the executable. If I invoke with a path like examples/audio/audio_module_playing, the sound resources don't load. Instead, it's cd audio; ./audio_module_playing that works. HTH

**Comment by raysan5** [comment]
Hi @iancarnation! I understand you're using Notepad++ script to compile, right?
Just copy `json.h` and `json.c` into same folder as your `modified_core_basic_window.c` folder and modify the Notepad++ compiling script `raylib_compile_execute` compile line:
```
gcc -o $(NAME_PART).exe $(FILE_NAME) json.c $(RAYLIB_DIR)\raylib\raylib_icon -I. -Iexternal -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,-allow-multiple-definition -Wl,--subsystem,windows
```
Basically, just added `json.c` to compilation process.

Using compiler parameters: `-I<include_path>`, `-L<library_path>`  and `-l<library_to_link>` you define where to look for `.h` includes and `.a` libraries for linkage but if you just want to add a `.c` file to compilation you can just add it to compile line after other `.c` files you compile.

Please, let me know if it works!

**Comment by iancarnation** [comment]
Thanks Ray!

I ended up making it work by adding the compiled ```.o``` file to the line, based on a forum answer I found:
```gcc -o $(NAME_PART).exe $(FILE_NAME) json.o -s $(RAYLIB_DIR)\raylib\raylib_icon -Iexternal -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,-allow-multiple-definition -Wl,--subsystem,windows```

The compile line you gave me also works, which I presume is because the ```.o``` file contains the ```.c``` file in some sense?? This is a good opportunity for me to figure out how all these code files interact with the compiler!

Let's pretend I wanted this to be accessible to any of my raylib projects, without copying the ```.c``` file around. I noticed that the stb_vorbis ```.c``` and ```.h``` files are in 'external,' and I see the ```stb_vorbis.o``` usage in the raylib src Makefile:
```
# Define all object files required with a wildcard
# The wildcard takes all files that finish with ".c",
# and replaces extentions with ".o", that are the object files
OBJS = $(patsubst %.c, %.o, $(wildcard *.c))
OBJS += stb_vorbis.o
```
and
```
# Compile stb_vorbis library
stb_vorbis.o: external/stb_vorbis.c external/stb_vorbis.h
	$(CC) -c $< $(CFLAGS) $(INCLUDE_PATHS) -D$(PLATFORM)
```
I also found these in the raylib_source_compile script:
```gcc -O2 -c external/stb_vorbis.c -Wall -I.```
```ar rcs libraylib.a core.o rlgl.o shapes.o textures.o text.o models.o audio.o stb_vorbis.o utils.o```
Would I approach the integration of this json library the same way? I've attempted to duplicate all above commands for the json files, and recompiled raylib, but in my program I get a "no json.h file" error, or other errors if I don't include json.h, so I haven't figured it out yet. 

Thank you in advance if you are able to provide guidance, I am trying to learn about the gcc commands and all the linkage business, but it is challenging :)

**Comment by a3f** [comment]
Why do you want to include the JSON library and parsing code into raylib? You can build a library out of raylib (or just install it from your package manager, if you are on SUSE or macOS) and link against that.

No need to change files in raylib. Am I missing something?

**Comment by raysan5** [comment]
> The compile line you gave me also works, which I presume is because the .o file contains the .c file in some sense?? This is a good opportunity for me to figure out how all these code files interact with the compiler!

`gcc.exe` translates `.c` text files (with a kind-of human readable language) to `.o` files, a binary file with intructions (0s and 1s) that computers can understand. Multiple `.o` files could be combined into a `.exe` executable file... or combined into a `.a` file (a programming library), fo example: `libraylib.a`.

Compiler can process multiple `.c` files at the same time to generate a `.exe`. A part of that, compiler could also be configured with extra parameters (`-std=c99`, `-Wall`, `-Wl,-allow-multiple-definition`, `-Wl,--subsystem,windows`...) to behave in a specific way. [More info here!](https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Option-Summary.html#Option-Summary)

**Comment by iancarnation** [comment]
Thanks for the info @raysan5 :)

Hello @a3f , I don't really need to integrate it, I was just curious how that process would work for my general edification :) Just trying to wrap my head around how raylib is set up :)

**Comment by nezvers** [comment]
I've been trying this for some time and can't get it working in npp.
`echo > Setup required Environment
echo -------------------------------------
SET RAYLIB_PATH=C:\raylib\raylib
SET COMPILER_PATH=C:\raylib\mingw\bin
ENV_SET PATH=$(COMPILER_PATH)
SET CC=gcc
SET CFLAGS=$(RAYLIB_PATH)\src\raylib.rc.data -s -static -Os -std=c99 -Wall -Iexternal -DPLATFORM_DESKTOP
SET LDFLAGS=-lraylib -lopengl32 -lgdi32 -lwinmm
cd $(CURRENT_DIRECTORY)
echo
echo > Clean latest build
echo ------------------------
cmd /c IF EXIST $(NAME_PART).exe del /F $(NAME_PART).exe
echo
echo > Saving Current File
echo -------------------------
npp_save
echo
echo > Compile program
echo -----------------------
$(CC) -o $(NAME_PART).exe **game.c** $(FILE_NAME) $(CFLAGS) $(LDFLAGS)
echo
echo > Reset Environment
echo --------------------------
ENV_UNSET PATH
echo
echo > Execute program
echo -----------------------
cmd /c IF EXIST $(NAME_PART).exe $(NAME_PART).exe`
