### ISSUE TITLE
[rcore] Overview of Wayland, Xwayland and X11 support on Linux

### ISSUE THREAD

**Issue by asdqwe** [raysan5/raylib#4371]
> [!NOTE]
> \- This post contains my opinions and observations, YMMV.
> \- Posting as an issue because it's a recurrent subject, but feel free to close this.

### Context:
1. [Many Linux distributions](https://en.wikipedia.org/wiki/Wayland_(protocol)#Desktop_Linux_distributions) are undergoing a migration from the [X Window System (X11)](https://en.wikipedia.org/wiki/X_Window_System) to the [Wayland communication protocol](https://en.wikipedia.org/wiki/Wayland_(protocol)).
2. However, a series of issues are emerging due to the architectural differences between both systems. E.g.: Wayland transfering some window control (like positioning) from the application to the window manager.
3. These architectural choices make Wayland diverge from how other desktop operating systems handle windows.
4. Since supporting Wayland requires rebuilding all graphical applications for it, [Xwayland](https://wayland.freedesktop.org/xserver.html) was provided as a backward compatibility solution to run X clients under Wayland.

### Native Wayland limitations on GLFW:
Referencing the [GLFW documentation](https://www.glfw.org/docs/latest/group__window.html):

| GLFW function: | Wayland limitation: | Use in raylib: |
| :--- | :--- | :--- |
| `glfwSetWindowIcon` | _"Wayland: There is no existing protocol to change an icon, the window will thus inherit the one defined in the application's desktop file. This function will emit GLFW_FEATURE_UNAVAILABLE."_ | `SetWindowIcon` |
| `glfwGetWindowPos` | _"Wayland: There is no way for an application to retrieve the global position of its windows. This function will emit GLFW_FEATURE_UNAVAILABLE."_ | `GetCurrentMonitor`<br>`GetWindowPosition` |
| `glfwSetWindowPos` | _"Wayland: There is no way for an application to set the global position of its windows. This function will emit GLFW_FEATURE_UNAVAILABLE."_ | `ToggleBorderlessWindowed`<br>`SetWindowPosition`<br>`SetWindowMonitor` |
| `glfwSetWindowSizeLimits` | _"Wayland: The size limits will not be applied until the window is actually resized, either by the user or by the compositor."_ | `SetWindowMinSize`<br>`SetWindowMaxSize` |
| `glfwSetWindowAspectRatio` | _"Wayland: The aspect ratio will not be applied until the window is actually resized, either by the user or by the compositor."_ | Not used. |
| `glfwSetWindowOpacity` | _"Wayland: There is no way to set an opacity factor for a window. This function will emit GLFW_FEATURE_UNAVAILABLE."_ | `SetWindowOpacity` |
| `glfwIconifyWindow` | _"Wayland: Once a window is iconified, glfwRestoreWindow won’t be able to restore it. This is a design decision of the xdg-shell protocol."_ | `MinimizeWindow` |
| `glfwShowWindow` | _"Wayland: Because Wayland wants every frame of the desktop to be complete, this function does not immediately make the window visible. Instead it will become visible the next time the window framebuffer is updated after this call."_ | `ClearWindowState` |
| `glfwFocusWindow` | _"Wayland: The compositor will likely ignore focus requests unless another window created by the same application already has input focus."_ | `ToggleBorderlessWindowed`<br>`SetWindowFocused` |
| `glfwSetWindowMonitor` | _"Wayland: The desired window position is ignored, as there is no way for an application to set this property."_ | `ToggleFullscreen` |
| `glfwGetWindowAttrib` | _"Wayland: The Wayland protocol provides no way to check whether a window is iconfied, so GLFW_ICONIFIED always returns GLFW_FALSE."_ | Not used on the limitation context. |
| `glfwSetWindowAttrib` | _"Wayland: The GLFW_FLOATING window attribute is not supported. Setting this will emit GLFW_FEATURE_UNAVAILABLE."_ | `InitPlatform`<br>`ToggleBorderlessWindowed`<br>`SetWindowState`<br>`ClearWindowState` |
| `glfwSetWindowPosCallback` | _"Wayland: This callback will never be called, as there is no way for an application to know its global position."_ | `WindowPosCallback` |

These limitations can be tested with:
```
#include "raylib.h"
int main(void) {
    InitWindow(800, 450, "test");
    SetTargetFPS(60);
    Image red = GenImageColor(16, 16, RED);
    while (!WindowShouldClose()) {

        if(IsKeyPressed(KEY_R)) { SetWindowState(FLAG_WINDOW_RESIZABLE); TraceLog(LOG_INFO, "[R] SetWindowState(FLAG_WINDOW_RESIZABLE)"); }
        if(IsKeyPressed(KEY_E)) { ClearWindowState(FLAG_WINDOW_RESIZABLE); TraceLog(LOG_INFO, "[E] ClearWindowState(FLAG_WINDOW_RESIZABLE)"); }
        if(IsKeyPressed(KEY_H)) { SetWindowState(FLAG_WINDOW_HIDDEN); TraceLog(LOG_INFO, "[H] SetWindowState(FLAG_WINDOW_HIDDEN)"); }
        if(IsKeyPressed(KEY_J)) { ClearWindowState(FLAG_WINDOW_HIDDEN); TraceLog(LOG_INFO, "[J] ClearWindowState(FLAG_WINDOW_HIDDEN)"); }
        if(IsKeyPressed(KEY_T)) { SetWindowState(FLAG_WINDOW_TOPMOST); TraceLog(LOG_INFO, "[T] SetWindowState(FLAG_WINDOW_TOPMOST)"); }
        if(IsKeyPressed(KEY_Y)) { ClearWindowState(FLAG_WINDOW_TOPMOST); TraceLog(LOG_INFO, "[Y] ClearWindowState(FLAG_WINDOW_TOPMOST)"); }
        if(IsKeyPressed(KEY_NINE)) { SetWindowMaxSize(900, 600); TraceLog(LOG_INFO, "[9] SetWindowMaxSize(900, 600)"); }
        if(IsKeyPressed(KEY_ZERO)) { SetWindowMinSize(300, 200); TraceLog(LOG_INFO, "[0] SetWindowMinSize(300, 200)"); }
        if(IsKeyPressed(KEY_M)) { MinimizeWindow(); TraceLog(LOG_INFO, "[M] MinimizeWindow()"); }
        if(IsKeyPressed(KEY_F)) { ToggleFullscreen(); TraceLog(LOG_INFO, "[F] ToggleFullscreen()"); }
        if(IsKeyPressed(KEY_G)) { ToggleBorderlessWindowed(); TraceLog(LOG_INFO, "[G] ToggleBorderlessWindowed()"); }
        if(IsKeyPressed(KEY_P)) { SetWindowPosition(100, 100); TraceLog(LOG_INFO, "[P] SetWindowPosition(100, 100)"); }
        if(IsKeyPressed(KEY_O)) { SetWindowOpacity(0.5f); TraceLog(LOG_INFO, "[O] SetWindowOpacity(0.5f)"); }
        if(IsKeyPressed(KEY_I)) { SetWindowIcon(red); TraceLog(LOG_INFO, "[I] SetWindowIcon(red)"); }
        if(IsKeyPressed(KEY_U)) { SetWindowFocused(); TraceLog(LOG_INFO, "[U] SetWindowFocused()"); }
        if(IsKeyPressed(KEY_ONE)) { if (GetMonitorCount() > 0) { SetWindowMonitor(0); TraceLog(LOG_INFO, "[1] SetWindowMonitor(0), if available"); } }
        if(IsKeyPressed(KEY_TWO)) { if (GetMonitorCount() > 1) { SetWindowMonitor(1); TraceLog(LOG_INFO, "[2] SetWindowMonitor(1), if available"); } }

        BeginDrawing();
        ClearBackground(RAYWHITE);
        DrawText(TextFormat("current monitor: %i", GetCurrentMonitor()), 20, 20, 20, BLACK);
        DrawText(TextFormat("(monitor count: %i)", GetMonitorCount()), 220, 20, 20, BLACK);
        DrawText(TextFormat("window position: %.1f, %.1f", GetWindowPosition().x, GetWindowPosition().y), 20, 50, 20, BLACK);
        DrawText(TextFormat("window size: %i, %i", GetScreenWidth(), GetScreenHeight()), 20, 80, 20, BLACK);
        DrawText("[R] Set FLAG_WINDOW_RESIZABLE", 20, 120, 20, ORANGE);
        DrawText("[E] Clear FLAG_WINDOW_RESIZABLE", 20, 150, 20, ORANGE);
        DrawText("[H] Set FLAG_WINDOW_HIDDEN", 20, 190, 20, RED);
        DrawText("[J] Clear FLAG_WINDOW_HIDDEN", 20, 220, 20, RED);
        DrawText("[T] Set FLAG_WINDOW_TOPMOST", 20, 260, 20, GREEN);
        DrawText("[Y] Clear FLAG_WINDOW_TOPMOST", 20, 290, 20, GREEN);
        DrawText("[9] SetWindowMaxSize(900, 600)", 20, 330, 20, BLUE);
        DrawText("[0] SetWindowMinSize(300, 200)", 20, 360, 20, BLUE);
        DrawText("[M] MinimizeWindow()", 420, 80, 20, VIOLET);
        DrawText("[F] ToggleFullscreen()", 420, 120, 20, BEIGE);
        DrawText("[G] ToggleBorderlessWindowed()", 420, 150, 20, BEIGE);
        DrawText("[P] SetWindowPosition(100, 100)", 420, 190, 20, MAROON);
        DrawText("[O] SetWindowOpacity(0.5f)", 420, 220, 20, MAROON);
        DrawText("[I] SetWindowIcon(red)", 420, 260, 20, DARKGREEN);
        DrawText("[U] SetWindowFocused()", 420, 290, 20, DARKGREEN);
        DrawText("[1] SetWindowMonitor(0), if available", 420, 330, 20, DARKBLUE);
        DrawText("[2] SetWindowMonitor(1), if available", 420, 360, 20, DARKBLUE);
        EndDrawing();
    }
    UnloadImage(red);
    CloseWindow();
    return 0;
}
```

### Arguments in favor of supporting (or migrating to) Wayland:
1. The major distros [already migrated to it](https://en.wikipedia.org/wiki/Wayland_(protocol)#Desktop_Linux_distributions). And although [some reverted it in the past](https://ubuntu.com/blog/bionic-beaver-18-04-lts-to-use-xorg-by-default), that's unlikely to happen again since Xwayland (more or less) has been able to hold things together for X11 support.
2. It's usually easier to start migrating earlier (while X11 and Xwayland are actively maintained and there are no deadlines), than having to rush later if X11 or Xwayland ever get suddenly dropped.
3. X11 is an old and large codebase that is not always easy to work with. It also was never designed to do everything we need it for these days (e.g.: forwarding).
4. X11 will eventually (even likely) get phased out, so we may not actually have a choice on the long term.
5. Wayland is more likely to get improvements and new features over time.

### Arguments in favor of staying with X11 (or Xwayland):
1. The distros migration to Wayland was premature. Wayland doesn't appear to be complete or stable enough for widespread usage.
2. Although there's valid reasons for some of their architectural decisions, it causes more problems than it solves.
3. Despite many distros pushing Wayland, they don't actually have any power. If most application devs don't want (or bother) to support Wayland, it's the distros that will end up with less software available. So Wayland will either have to give up (and return positioning control to the applications) or keep supporting Xwayland.
4. X11 isn't perfect, but isn't broken. Don't fix what isn't broken.
5. With Wayland giving the window manager control over positioniong, applications now depend on every window manager doing their jobs right.
6. There are no outstanding new features on Wayland that justify the lost funcionality and amount of workaround necessary to support with it.

### Conclusion:
Developers that want to support Linux now have to decide between:
1. Implementing substancial changes to the applications operation to conform with native Wayland.
2. Continuing to use X11 through Xwayland expecting that it will be maintained on the long term.
3. Support both systems in parallel, despite incompatible window handling behaviors.

My two cents:

4. Supporting (as much as possible of) Wayland would require rewriting a good part of rcore, increasing complexity and forcing unnecessary changes on other platforms that have nothing to do with this.
5. My suggestion would be _"3. Support both systems in parallel, despite incompatible window handling behaviors."_. Where X11 behavior is kept as standard/default and Wayland idiosyncrasies either don't get supported at all or get just basic support.
6. Despite being a Linux-only user myself, Linux doesn't have a large enough userbase to justify this amount of workaround.
7. #4369 is probably the way to go.

**Comment by planetis-m** [comment]
Also raylib is broken on Wayland with fractional scaling, ie the window appears as a black rectangle with a smaller portion at the bottom displaying the contents.

**Comment by raysan5** [comment]
@asdqwe Thank you very much for the super-detailed report about Wayland status on Linux, a really great and  instructive read. Now it's easier to take a decision on this change and yeah, I agree that #4369 is the way to go for now. Thanks!

**Comment by asdqwe** [comment]
@raysan5 You're welcome. Closing the issue as completed.
