### ISSUE TITLE
[physac] How to add physac.h reference to Visual Studio project

### ISSUE THREAD

**Issue by victorfisac** [raysan5/raylib#438]
I have opened the VS2015 project that comes with raylib and replaced code in core_basic_window.c and core_basic_window.cpp by physac_demo.c code (keeping cpp parameters of main(...) function).

When including "physac.h" in code, it is not recognized by VS. I have added 'C:/raylib/raylib/src/' path to 'Additional includes' in the settings of the solution but it doesn't work...

What is the correct way to add 'physac.h' or other library to the VS project?
PS: I suppose that recompile raylib.dll including physac.h is an alternative...

**Comment by raysan5** [comment]
Hi @victorfisac! Just drag&drop `physac.h` into `core_basic_window` project. It should work.

**Comment by victorfisac** [comment]
Ok! Thanks :D I haven't used it for a long time...
