### ISSUE TITLE
[rshapes] `DrawRectangleLines()` misalignment

### ISSUE THREAD

**Issue by XeroOl** [raysan5/raylib#4386]
- [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [X] My code has no errors or misuse of raylib

I expected the DrawRectangleLines function to draw a closed rectangle, but it seems to have coordinates wrong, because it didn't exactly draw a rectangle.

![image](https://github.com/user-attachments/assets/d3203188-4c72-44c8-981b-3557138b1049)

### Environment

Raylib Desktop. Arch Linux.
AMD Radeon RX 6950 XT
GPU Says it supports OpenGL 4.6, Not sure how to check which one raylib is using.

### Code Example
```c
#include "raylib.h"
int main(void) {
  InitWindow(640, 480, "game");
  SetTargetFPS(60);
  while (!WindowShouldClose()) {
    BeginDrawing();
      Camera2D camera = {};
      camera.zoom = 8.0;
      BeginMode2D(camera);  // large zoom to make the problem clear
        DrawRectangleLines(10, 10, 20, 20, WHITE);  // draw a rectangle outline
      EndMode2D();
    EndDrawing();
  }
  CloseWindow();
  return 0;
}
```

**Comment by casperbear** [comment]
There are two ways of drawing rectangle lines in OpenGL and Raysan5 is choosing between them. RayLib 5 implemented one way, RayLib master another. Both ways may produce visual inaccuracies depending on situation and GPU driver, plus the first way is slower.
If you are using RayLib master and see visual artifacts, try re-implementing the first way from RayLib 5 and see if it work for you.
```
void DrawRectangleFrame(int posX, int posY, int width, int height, int thickness, Color color)
{
    // Based on https://github.com/raysan5/raylib/blob/29ce13b77736f4eb2fa6018d9c164d76c4df54bc/src/rshapes.c#L811

    DrawRectangle(posX, posY, width, thickness, color);
    DrawRectangle(posX + width - thickness, posY + thickness, thickness, height - 2 * thickness, color);
    DrawRectangle(posX, posY + height - thickness, width, thickness, color);
    DrawRectangle(posX, posY + thickness, thickness, height - 2 * thickness, color);
}
```

**Comment by raysan5** [comment]
Actually this issue is still being reviewed, there is also another open issue and an open PR...

**Comment by raysan5** [comment]
Fixed
