### ISSUE TITLE
[core] Implement orthographic projection for 3D camera

### ISSUE THREAD

**Issue by srseil** [raysan5/raylib#439]
I need an orthographic projection for the game I am currently working on, and as far as I can see this functionality is currently not exposed through the API. I think it would be useful to have this integrated in the current camera system. There could be a separate member in the `Camera` struct to set the projection, defaulting to perspective. Something along those lines.

**Comment by raysan5** [comment]
Don't know if that's what you mean but, have you checked [core_2d_camera](https://github.com/raysan5/raylib/blob/master/examples/core/core_2d_camera.c) example?

Also, maybe related, you can check example [core_world_screen](https://github.com/raysan5/raylib/blob/master/examples/core/core_world_screen.c) example.

**Comment by victorfisac** [comment]
@raysan5 I think he wants a 3d camera but orthographic (discarding multiplying projection matrix). It is useful to make a make like Monument Valley where you need a 3d point of view but orthographic.

Camera2D is not prepared for 3d models drawing.

**Comment by Gamerfiend** [comment]
I second this, and am working on it myself but I haven't gotten very far as I'm a novice graphics programmer. Here is the difference @raysan5 

[http://db-in.com/images/projection_example.gif](url)

**Comment by raysan5** [comment]
@victorfisac thanks for the clarification! You're all right, I'll add support for orthographic projection. 

Need to look for the best way to do that.

**Comment by victorfisac** [comment]
@raysan5 Camera struct can implement this feature with an enum. Also, maybe the first result is not as expected and you have to implement a 'size' field to scale all drawn vertices; Unity has this in Camera component (with a value of '5' by default).

**Comment by raysan5** [comment]
Hi @victorfisac! Thanks for the recommendation! Need to evaluate other options but it sounds lika a good solution to me...

**Comment by raysan5** [comment]
Implemented in PR https://github.com/raysan5/raylib/pull/513
