### ISSUE TITLE
[core] Window with game appears after long time

### ISSUE THREAD

**Issue by MrKermit1** [raysan5/raylib#4396]
Hi, Recently I wanted to some things in my raylib project in Visual Studio (this is IDE which Im currently using) and I noticed that all my raylib projects are opening window after pretty a lot of time. At the beggining of running I see only console with data what was loaded and after 15-30 sec. finnaly the window shows up. Anyone know why is this happening and why all of sudden my all raylib projects have this strange kind of behavior?

**Comment by Peter0x44** [comment]
Usually this is hanging when glfw is running the gamepad init.
Can you break and see what is running during the long pause?

**Comment by MrKermit1** [comment]
@Peter0x44 
The story with the gamepad is interesting because I recently bought a steering wheel for my PC, and maybe the drivers did something strange. The issue appears even in simple programs that only display a white screen, so I don't know what I can break. I uninstalled the steering wheel drivers, but the problem still persists. I tried to run my SDL2 projects and they have same problem so I think that problem may be caused by some OpenGL things or something like that.

**Comment by Peter0x44** [comment]
@MrKermit1 it would be best if you could break in the debugger during the pause to see what is running. But if SDL2 reproduces the same it might be a system issue and not really a raylib one.

**Comment by raysan5** [comment]
@MrKermit1 @Peter0x44 It seems this issue is really difficult to reproduce and could be hardware related, it should be debugged to detect what is the function that hangs the system so long... In any case, it seems out of the scope of raylib...
