### ISSUE TITLE
[Gamepad] Remove default gamepad axis deadzone on MacOS/GLFW

### ISSUE THREAD

**Issue by dmg46664** [raysan5/raylib#4405]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

> Edit: The following sentence isn't relevant as it was misdiagnosed: Raylib expects a [compile time constant to set the deadzone](https://github.com/raysan5/raylib/blob/110ee74875412beb41ffb53330b47ec9cb052b2d/src/external/RGFW.h#L5665)

Raylib does not appear to have an API to set the deadzone of a controller, yet it exists and is defaulted on the GLFW backend on MacOS.

This should be up to the user in game as
1. Gamepads with [HALL-effect sensors](https://www.youtube.com/watch?v=oAsrLxaAkY0) may have zero drift, and users will be hamstrung by arbitrary drift. This may be needed for FPSs and simulator games requiring precision control.
2. Users with older potentiometer controllers may have larger drift amounts that need to be manually set.

In order to accommodate this an API is required for setting the dead-zone independently for each controller axis, of each gamepad.

In addition hard coding this requires recompilation of the library if used by JS, Python or other scripting wrapper (I'm using [Vybe](https://github.com/pfeodrippe/vybe)), preventing the wrapper from hosting "it just works out the box" compiled version of Raylib in their library. 

Solutions in ascending order of difficulty:
1. A stepping stone solution would simply be to default it 0.0 which would allow all games to handle this in game code. Solves for wrappers.
2. An API that allows settings a single setting across all controller axis in game.
3. An API that allows setting for each hardware axis independently for each controller (this properly models reality of user's controllers).

No expectations, just posting to start a discussion. Thanks for the library :-)

### Environment

Platform backend: DESKTOP (GLFW) on MacOS

### Issue Screenshot

N/A

### Code Example

In issue description.

**Comment by dmg46664** [comment]
@Peter0x44 Thanks for your response.
Apologies, I'm busy working out how the whole thing is put together. 

I didn't realise that Raylib had different backends.
I see that I'm using `INFO: Platform backend: DESKTOP (GLFW)` on MacOS.
And I'm doing
```
(vr.c/get-gamepad-axis-movement 0 (raylib/GAMEPAD_AXIS_LEFT_X))
```

which would be calling the native

```
GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_X)
```

I can see the deadzone behaviour anywhere on both the X and Y axis (not just around 0,0). I've just misdiagnosed where exactly the problem stems from. Thank you for your tip re SDL.

**Comment by Peter0x44** [comment]
If you are using glfw, you are not using the code you linked, and it isn't relevant.

**Comment by dmg46664** [comment]
Thanks @Peter0x44. I've updated the issue that the problem exists despite the misdiagnosed code.

**Comment by asdqwe** [comment]
@dmg46664 Are you experiencing:

**A**: drifting on the analog sticks at all times during any movement?
or **B**: drifting on the analog sticks just when they are resting?

If it's **B**, then individual deadzones are usually trivial to implement on the client side.
<details>
<summary>Here's an example:</summary>

```
#include "raylib.h"
int main(void) {
    InitWindow(400, 300, "test");
    SetTargetFPS(60);

    // Set axis deadzones:
    int dz = 0;
    float laxdz = 0.5f;
    float laydz = 0.5f;
    float raxdz = 0.5f;
    float raydz = 0.5f;

    while (!WindowShouldClose()) {

        // Toggle deadzone: [gamepad button A]
        if (IsGamepadButtonPressed(0, GAMEPAD_BUTTON_RIGHT_FACE_DOWN)) { dz = !dz; }

        // Get axis values:
        float lax = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_X);
        float lay = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_Y);
        float rax = GetGamepadAxisMovement(0, GAMEPAD_AXIS_RIGHT_X);
        float ray = GetGamepadAxisMovement(0, GAMEPAD_AXIS_RIGHT_Y);

        // Calculate deadzones:
        if (dz) {
            if (lax > -laxdz && lax < laxdz) { lax = 0.0f; }
            if (lay > -laydz && lay < laydz) { lay = 0.0f; }
            if (rax > -raxdz && rax < raxdz) { rax = 0.0f; }
            if (ray > -raydz && ray < raydz) { ray = 0.0f; }
        }

        BeginDrawing();
        ClearBackground(RAYWHITE);

        DrawCircle(100, 80, 50, LIGHTGRAY);
        if (dz) { DrawEllipse(100, 80, 50*laxdz, 50*laydz, BLACK); }
        DrawCircle(100+(int)(lax*50), 80+(int)(lay*50), 5, RED);
        DrawText(TextFormat("LAX %f", lax), 30, 140, 20, BLACK);
        DrawText(TextFormat("LAY %f", lay), 30, 160, 20, BLACK);

        DrawCircle(300, 80, 50, LIGHTGRAY);
        if (dz) { DrawEllipse(300, 80, 50*raxdz, 50*raydz, BLACK); }
        DrawCircle(300+(int)(rax*50), 80+(int)(ray*50), 5, BLUE);
        DrawText(TextFormat("RAX %f", rax), 230, 140, 20, BLACK);
        DrawText(TextFormat("RAY %f", ray), 230, 160, 20, BLACK);

        DrawText("Toggle deadzone:\n[gamepad button A]", 30, 220, 20, BLACK);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```
![img](https://github.com/user-attachments/assets/61b4d049-5d28-4b24-a3b9-255371e3adba)
</details>

Do you mean you would like that :arrow_up: baked into the library?

**Comment by dmg46664** [comment]
Thanks for the code snippet @asdqwe .
If I comment out the section

```
// Calculate deadzones:
        /* if (dz) { */
        /*     if (lax > -laxdz && lax < laxdz) { lax = 0.0f; } */
        /*     if (lay > -laydz && lay < laydz) { lay = 0.0f; } */
        /*     if (rax > -raxdz && rax < raxdz) { rax = 0.0f; } */
        /*     if (ray > -raydz && ray < raydz) { ray = 0.0f; } */
        /* } */
```

There is _still_ a deadzone being applied to the controller input! 
No such deadzone exists if I check with https://hardwaretester.com/gamepad

I agree that if I wanted to increase the deadzone, such client code is sufficient and I wouldn't request it being added.

**Comment by dmg46664** [comment]
Renamed issue now that I know that a default deadzone wasn't intentional.

**Comment by asdqwe** [comment]
@dmg46664 Then I'm afraid this is either an upstream MacOS issue or GLFW issue because raylib isn't changing the gamepad axis inputs at all (as you can see on: [rcore_android](https://github.com/raysan5/raylib/blob/b2dca724c7c5a9720dc789cc39529a9341bcbbfb/src/platforms/rcore_android.c#L1142-L1153), [rcore_desktop_glfw](https://github.com/raysan5/raylib/blob/b2dca724c7c5a9720dc789cc39529a9341bcbbfb/src/platforms/rcore_desktop_glfw.c#L1212), [rcore_desktop_sdl](https://github.com/raysan5/raylib/blob/b2dca724c7c5a9720dc789cc39529a9341bcbbfb/src/platforms/rcore_desktop_sdl.c#L1387-L1389), [rcore_drm](https://github.com/raysan5/raylib/blob/b2dca724c7c5a9720dc789cc39529a9341bcbbfb/src/platforms/rcore_drm.c#L1676-L1677), [rcore_web](https://github.com/raysan5/raylib/blob/b2dca724c7c5a9720dc789cc39529a9341bcbbfb/src/platforms/rcore_web.c#L1060)).

AFAIK, GLFW doesn't apply any kind of deadzone since the 3.3 release ([quote](https://www.glfw.org/docs/3.3/news.html#xinput_deadzone_33): _"GLFW no longer applies any deadzone to the input state received from the XInput API. This was never done for any other platform joystick API so this change makes the behavior more consistent but you will need to apply your own deadzone if desired."_).

**Comment by asdqwe** [comment]
@dmg46664 What other libraries/stack are you using?

**Comment by asdqwe** [comment]
@dmg46664 Yeah, you're right. Never noticed that before. Good catch!

**Comment by dmg46664** [comment]
Whoop! 🦸‍♂️  At least I'm not going mad re testing!
Don't mind if you want to default it, but there must be a means of disabling it. Ideally at runtime. This goes back to my original suggestions.

Also it's bad as implemented, because this will affect the whole axis! Not only around the origin, which I think is the way it's usually done in games (could be wrong).

**Comment by asdqwe** [comment]
@dmg46664 Agreed. Could you please test if this (https://github.com/asdqwe/raylib-fork/tree/fix-gamepad-deadzone) ([diff](https://github.com/raysan5/raylib/compare/master...asdqwe:raylib-fork:fix-gamepad-deadzone)) solves it for you?

**Comment by asdqwe** [comment]
@dmg46664 Uhn, got it, I can move it to `CORE` so it can be edit it at runtime. However most configurations at the moment expect customizing the defines on the `config.h` file. So I don't know if that would be approved/merge. Give me a minute to create another branch here.

**Comment by dmg46664** [comment]
@asdqwe Great thanks. I think it's better to get this right and deal with objections than get the easy fix through that isn't ideal... because then it becomes unlikely to get a better fix revisited.

**Comment by dmg46664** [comment]
Like I said, if it's about the simplest thing, then remove the deadzone entirely (like GLFW does).

**Comment by asdqwe** [comment]
@dmg46664 Done. There there are two branches:
1. https://github.com/asdqwe/raylib-fork/tree/fix-gamepad-deadzone-static fix it with a `config.h` `#define`;
2. https://github.com/asdqwe/raylib-fork/tree/fix-gamepad-deadzone-runtime fix it with a `CORE` editable at runtime.
<br>

> Now I have to figure out how to build raylib...

Download the fork-branch, e.g. https://github.com/asdqwe/raylib-fork/tree/fix-gamepad-deadzone-runtime (`Code Button` > `Download ZIP`). Then unpack it and compile it:
```
unzip raylib-fork-fix-gamepad-deadzone-runtime.zip
cd raylib-fork-fix-gamepad-deadzone-runtime/src/
make PLATFORM=PLATFORM_DESKTOP_GLFW
```

Edit/replace the content of `raylib-fork-fix-gamepad-deadzone-runtime/examples/core/core_basic_window.c` with this:
```
#include "raylib.h"
int main(void) {
    InitWindow(400, 300, "test");
    SetTargetFPS(60);

    // Control the deadzone here:
    SetGamepadDeadzone(0.001f);

    while (!WindowShouldClose()) {

        // Get axis values:
        float lax = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_X);
        float lay = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_Y);
        float rax = GetGamepadAxisMovement(0, GAMEPAD_AXIS_RIGHT_X);
        float ray = GetGamepadAxisMovement(0, GAMEPAD_AXIS_RIGHT_Y);

        BeginDrawing();
        ClearBackground(RAYWHITE);

        DrawCircle(100, 80, 50, LIGHTGRAY);
        DrawCircle(100+(int)(lax*50), 80+(int)(lay*50), 5, RED);
        DrawText(TextFormat("LAX %f", lax), 30, 140, 20, BLACK);
        DrawText(TextFormat("LAY %f", lay), 30, 160, 20, BLACK);

        DrawCircle(300, 80, 50, LIGHTGRAY);
        DrawCircle(300+(int)(rax*50), 80+(int)(ray*50), 5, BLUE);
        DrawText(TextFormat("RAX %f", rax), 230, 140, 20, BLACK);
        DrawText(TextFormat("RAY %f", ray), 230, 160, 20, BLACK);

        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```

Then compile it:
```
cd ../examples/
make PLATFORM=PLATFORM_DESKTOP_GLFW core/core_basic_window
```

Then run the compiled new binary created inside `raylib-fork-fix-gamepad-deadzone-runtime/examples/core/`.

**Comment by dmg46664** [comment]
@asdqwe The runtime version seems to work perfectly from what I can tell. Tested at 0.00 and other values.
Obviously it's possible to do a whole lot more like calibrate to an actual spot etc etc. However at least now it's entirely possible to do this in client code, and the code is in a better state than when we started.
Much obliged.

**Comment by asdqwe** [comment]
@dmg46664 No problem. Glad it worked. I'll send the PR for review. :+1:

**Comment by raysan5** [comment]
@dmg46664 @asdqwe I prefer to remove the deadzone correction from raylib internals and let user manage it on user side. Solving it on user side requires adding a new global and a new function, I prefer to avoid it if it can be managed on user side.

**Comment by dmg46664** [comment]
Hi @raysan5 . Pleased to meet you.

> Like I said, if it's about the simplest thing, then remove the deadzone entirely (like GLFW does).

I wrote this above which I imagine is in complete accordance with what you mean. 👍

**Comment by asdqwe** [comment]
@raysan5 @dmg46664 I've updated #4420 accordingly.

**Comment by dmg46664** [comment]
Your efforts @asdqwe have been amazing 👏

**Comment by asdqwe** [comment]
@dmg46664 Glad to help. Credits to you for finding and figuring out this issue. :+1:
