### ISSUE TITLE
[rmodels] GPU Skinning Example GLSL 100 Shaders Do Not Compile

### ISSUE THREAD

**Issue by dontpanic5** [raysan5/raylib#4412]
### Issue description

The GLSL 100 shaders do not compile in a web build. The errors are:
WARNING: SHADER: [ID 21] Failed to compile vertex shader code
game.html:1 WARNING: SHADER: [ID 21] Compile error: ERROR: 0:3: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:4: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:5: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:6: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:7: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:14: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:15: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:25: '1.0f' : Floating-point suffix unsupported prior to GLSL ES 3.00
game.html:1 ERROR: 0:25: '1.0f' : syntax error
game.html:1 
game.html:1 WARNING: SHADER: [ID 22] Failed to compile fragment shader code
game.html:1 WARNING: SHADER: [ID 22] Compile error: ERROR: 0:4: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:4: '' : No precision specified for (float)
game.html:1 ERROR: 0:5: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:5: '' : No precision specified for (float)
game.html:1 ERROR: 0:8: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
game.html:1 ERROR: 0:8: '' : No precision specified for (float)
game.html:1 ERROR: 0:11: '' : No precision specified for (float)
game.html:1 ERROR: 0:15: '' : No precision specified for (float)
game.html:1 ERROR: 0:15: 'texture' : no matching overloaded function found
game.html:1 ERROR: 0:15: '=' : dimension mismatch
game.html:1 ERROR: 0:15: '=' : cannot convert from 'const mediump float' to '4-component vector of float'

I've reproduced this with my own project as well as the example c code.
It does work if you build for WebGL2.0 and modify the GLSL 330 shaders to be GLSL 300 es conforming. But the GLSL 100 shaders don't work with WebGL1.0 or WebGL2.0.

### Environment

Web platform. Windows 11 OS. WebGL1.0 and WebGL2.0. Integrated graphics Intel GPU.

### Issue Screenshot

![image](https://github.com/user-attachments/assets/6b79b832-9a9a-49e7-bbd0-9d49cd55585d)

### Code Example

Reproducible in the example code.

**Comment by raysan5** [comment]
@dontpanic5 Just reviewed the shader to work for GLSL100, please, could you test it?

Note that I limited `MAX_BONE_NUM` to 64, it could be required to be reduced to 32.

**Comment by dontpanic5** [comment]
Closer! But still a few errors.

```
WARNING: SHADER: [ID 21] Failed to compile vertex shader code
game.html:1 WARNING: SHADER: [ID 21] Compile error: ERROR: 0:28: '1.0f' : Floating-point suffix unsupported prior to GLSL ES 3.00
game.html:1 ERROR: 0:28: '1.0f' : syntax error
game.html:1 
game.html:1 WARNING: SHADER: [ID 22] Failed to compile fragment shader code
game.html:1 WARNING: SHADER: [ID 22] Compile error: ERROR: 0:16: 'texture' : no matching overloaded function found
game.html:1 ERROR: 0:16: '=' : dimension mismatch
game.html:1 ERROR: 0:16: '=' : cannot convert from 'const mediump float' to 'mediump 4-component vector of float'
```

**Comment by raysan5** [comment]
@dontpanic5 please, could you try it again?

**Comment by dontpanic5** [comment]
btw, I saw you changed the glsl 330 fragment shader. I tested that change in my personal game and gpu skinning still looks good on desktop.

**Comment by raysan5** [comment]
fixed.
