### ISSUE TITLE
Move day-to-day development to master branch

### ISSUE THREAD

**Issue by a3f** [raysan5/raylib#443]
Just a thought: people have often to be reminded to use the `develop` branch instead of `master`, so maybe it makes sense to branch off `master` as `master-1.8` and merge `develop` into `master` and start using `master` instead of `develop`.

[Wireshark](https://wireshark.org) does it like this:

* All new commits are _rebased_ unto `master`. This removes the merge commit and keeps commit history linear. Patch discussion is linked in the commit message. On Github we could use the squash button for pull requests, to automatically add a reference to the pull request and git rid of the merge commit (and manually rewrite commit message, if need be)
* Version of master is odd. `README` links to where the most recent stable version can be downloaded, which is even
* When a new stable version is due to come out, `master` is branched off as the next even version, e.g. `master-1.8`. This branch only gets bug fixes if required

Downside is occasional breakage for unexpecting people. Upside is they get the newest version and can report those breakages. Thoughts?

<s>Also, is there a way to alias `develop` and `master`, so people don't need to update their tracking branches?</s>

**Comment by raysan5** [comment]
Need to think about it. 

`develop` branch is changing a lot and despite trying to keep it stable, it could be broken, also, it's not tested on most platforms... `master` contains latest raylib release, tested and stable for most of the platforms...

Now, some things change, the continuous integration system builds raylib automatically for multiple configurations, that's amazing and assures some stability for develop branch... Maybe it's time to review branch workflow as proposed.

**Comment by a3f** [comment]
But being broken is _good_. With the increasing number of binary packages available (whether uploaded manually here, built by CI or in third-party package managers), users don't have to build raylib, except if they need the newest version. And if that version is broken, they are able to report it sooner.

Users that want to build a stable version just need to checkout the most recent release and build it themselves.

**Comment by raysan5** [comment]
Hi @a3f, I decided to close develop branch and move development to master branch as proposed.

My main concern is all the places (documentation, forums, gitter...) that link to develop branch files, did you investigate what happens to those links, is there any alias possibility? links get broken?

**Comment by a3f** [comment]
I think there isn't. Maybe merge develop into master, delete files in develop and a last commit with a `README` that says 
> Development moved to master branch, please updating tracking branches and documentation

**Comment by raysan5** [comment]
After lot of thinking and [some reading](https://softwareengineering.stackexchange.com/questions/312022/the-trend-of-the-develop-branch-going-away), just deleted develop branch: https://github.com/raysan5/raylib/pull/474#event-1480330270

Let's see what happens from now on.
