### ISSUE TITLE
[rmodels] New feature idea: Animation speed

### ISSUE THREAD

**Issue by TokyoSU** [raysan5/raylib#4442]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [X] My code has no errors or misuse of raylib

### Issue description

Being able to use an animation speed possibly 0-1 float that slow or speed down animation regardless of the frame count.

### Environment

All.

### Issue Screenshot

None

### Code Example

UpdateModelAnimation(model, anim[0], frame); <- frame should be float 0-1, in case it's 0.5f, it should be in the middle of animation.
With this, we could also use deltaTime.

Currently, we need to use frame in integer:
```
if (frame >= frameEnd)
    frame = 0;
frame++;
```

**Comment by CodingMadness** [comment]
absolutely, this should be in it.

**Comment by raysan5** [comment]
Thanks for reporting, added reference to https://github.com/raysan5/raylib/issues/4426. I'm closing this issue.
