### ISSUE TITLE
[raymath] `MatrixDecompose()` sometimes gives incorrect results when combining scale and rotation

### ISSUE THREAD

**Issue by waveydave** [raysan5/raylib#4454]
### Issue description

MatrixDecompose seems to return incorrect scale and rotation information, for certain ranges of values. (I'm currently only concerned with z-rotations, so that is all I've been testing.)

### Environment

PC, Windows 11

### Code Example

Tested against latest master, b8c0842.

```
#include <raylib.h>
#include <raymath.h>

// parameters: z-rotation angle and scale
void test_decompose_rotz(float in_angle, float sx, float sy, float sz) {
    // Create the tranformation matrix
    Matrix m = MatrixScale(sx, sy, sz);

    // EDIT: my original implementation was incorrect (see discussion below)
    // m = MatrixMultiply(m, MatrixRotateZ(in_angle));
    // FIX:
    m = MatrixMultiply(MatrixRotateZ(in_angle), m);

    // Extract the scale and rotation info
    Vector3 translation, scale;
    Quaternion rotation;
    MatrixDecompose(m, &translation, &rotation, &scale);
    Vector3 axis;
    float out_angle;
    QuaternionToAxisAngle(rotation, &axis, &out_angle);
    out_angle = copysignf(out_angle, axis.z);

    // Check it matches the inputs
    if (FloatEquals(in_angle, out_angle) && FloatEquals(sx, scale.x) &&
        FloatEquals(sy, scale.y) && FloatEquals(sz, scale.z)) {
        TraceLog(LOG_INFO, "Pass: angle %.2f, scale(%.2f, %.2f, %.2f)", in_angle, sx, sy, sz);
    } else {
        TraceLog(LOG_ERROR, "Fail: angle %.2f, scale(%.2f, %.2f, %.2f) -> angle %.2f, scale(%.2f, %.2f, %.2f)",
                 in_angle, sx, sy, sz, out_angle, scale.x, scale.y, scale.z);
    }
}

int main ()
{
    test_decompose_rotz(0.5, 1, 1, 1); // pass
    test_decompose_rotz(2.5, 1, 1, 1); // pass
    test_decompose_rotz(0.5, 3, 3, 5); // pass
    test_decompose_rotz(2.5, 3, 3, 5); // fail -> angle 0.66, scale(3.00, 3.00, 5.00)
    test_decompose_rotz(0.5, 3, 4, 5); // pass (NB my original test showed this as failing, see FIX above)
    test_decompose_rotz(2.5, 3, 4, 5); // fail -> angle 1.42, scale(3.00, 4.00, 5.00)
    return 0;
}
```

### Background

Apologies in advance for any mistakes in this issue - I've only started using raylib recently, so it's very possible I've misunderstood something somewhere!

I'm not very good with matrix maths, so my first task was to wrap up what I needed behind some APIs, which is where I noticed this. For a 2D scene, I'm trying to build trees of objects to transform as one, like a scene-tree type thing, and needed to decompose the transform matrices to calculate the parameters for DrawTexturePro. (Would a DrawTexture function which took a transformation matrix directly be feasible I wonder? There's probably more complexity to it than I know about though!)

I do have a fix for MatrixDecompose locally, but it is just a copy I made of a similar function from a different framework - I don't know what the policy about that would be, but I don't want to potentially taint the codebase or any fixes for this issue. (If it would be helpful, let me know and I'll point to it, it's MIT licesnsed.)

**Comment by raysan5** [comment]
@waveydave Afaik, there are multiple possible results to matrix decomposition, so changing result to other approach could not work for other use cases. Provided implementation is verified to work with glTF animation system, so better not to change it.

**Comment by raysan5** [comment]
@waveydave `MatrixDecompose()` is used in `LoadGLTF()` function in `rmodels` module: https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L5791

It's used on animations loading. You can test/debug its functionality in [`models_loading_gltf`](https://github.com/raysan5/raylib/blob/master/examples/models/models_loading_gltf.c) example.

**Comment by waveydave** [comment]
@raysan5 Thanks - I've just tried it with and without my update, and all the animations in the example look the same to me.

In case it's helpful in diagnosing the issue, my locally updated function is copied from Monogame ([here](https://github.com/MonoGame/MonoGame/blob/8a21b20fdfd7a2d36fd52be73d93984e7469bc01/MonoGame.Framework/Matrix.cs#L1476)):

```
RMAPI void MatrixDecompose(Matrix mat, Vector3 *translation, Quaternion *rotation, Vector3 *scale)
{
    // Extract translation.
    translation->x = mat.m12;
    translation->y = mat.m13;
    translation->z = mat.m14;

    float xs = (mat.m0 * mat.m1 * mat.m2 * mat.m3) < 0 ? -1 : 1;
    float ys = (mat.m4 * mat.m5 * mat.m6 * mat.m7) < 0 ? -1 : 1;
    float zs = (mat.m8 * mat.m9 * mat.m10 * mat.m11) < 0 ? -1 : 1;
    float scalex = xs * sqrt(mat.m0 * mat.m0 + mat.m1 * mat.m1 + mat.m2 * mat.m2);
    float scaley = ys * sqrt(mat.m4 * mat.m4 + mat.m5 * mat.m5 + mat.m6 * mat.m6);
    float scalez = zs * sqrt(mat.m8 * mat.m8 + mat.m9 * mat.m9 + mat.m10 * mat.m10);

    *scale = (Vector3){scalex, scaley, scalez};

    if (scalex == 0 || scaley == 0 || scalez == 0) {
        *rotation = QuaternionIdentity();
    } else {
        Matrix clone =
            {mat.m0 / scalex, mat.m4 / scaley, mat.m8 / scalez, 0,
             mat.m1 / scalex, mat.m5 / scaley, mat.m9 / scalez, 0,
             mat.m2 / scalex, mat.m6 / scaley, mat.m10 / scalez, 0,
             0, 0, 0, 1};

        // Extract rotation
        *rotation = QuaternionFromMatrix(clone);
    }
}
```

**Comment by raysan5** [comment]
@waveydave What Matrix conventions use MonoGame? Note that [raymath Matrix conventions](https://github.com/raysan5/raylib/blob/master/src/raymath.h#L6) could influence the results.

**Comment by waveydave** [comment]
@raysan5 Good point! Monogame is row-major, I think, which seems to be different to raylib. Apologies for not catching this.

So as far as I understand my test code in the initial post is incorrect for raylib - I think I'm doing the matrix multiplication the wrong way around when constructing the transform. Maybe it should instead be this:

'''
    // Create the transformation matrix
    Matrix m = MatrixScale(sx, sy, sz);
    m = MatrixMultiply(MatrixRotateZ(in_angle), m);
'''

Is this the correct way to do it (assuming I want to scale before rotating)?

If so, only one of the tests above now fails:

'''
    test_decompose_rotz(0.5, 1, 1, 1); // pass
    test_decompose_rotz(2.5, 1, 1, 1); // pass
    test_decompose_rotz(0.5, 3, 3, 5); // pass
    test_decompose_rotz(2.5, 3, 3, 5); // fail -> angle 0.66, scale(3.00, 3.00, 5.00)
    test_decompose_rotz(0.5, 3, 4, 5); // pass
'''

**Comment by waveydave** [comment]
@raysan5 I think this is a potential fix - it passes the tests and the models_loading_gltf example still works correctly.

Adjust the part of `MatrixDecompose` [which removes the scale](https://github.com/raysan5/raylib/blob/6028052c7eb0a0702423f8a4b0625bca1ad5b731/src/raymath.h#L2567) to:

```
    // Remove scale from the matrix if it is not close to zero
    Matrix clone = mat;
    if (!FloatEquals(det, 0))
    {
        clone.m0 /= s.x;
        clone.m1 /= s.x;
        clone.m2 /= s.x;
        clone.m4 /= s.y;
        clone.m5 /= s.y;
        clone.m6 /= s.y;
        clone.m8 /= s.z;
        clone.m9 /= s.z;
        clone.m10 /= s.z;

        // Extract rotation
        *rotation = QuaternionFromMatrix(clone);
    }
    else
    {
        // Set to identity if close to zero
        *rotation = QuaternionIdentity();
    }
```

**Comment by raysan5** [comment]
@waveydave I'm afraid I'm not experienced enough with those maths to confirm everything is perfect but if you did the tests and everything still works as expected, that's good for me. Feel free to send a PR!
