### ISSUE TITLE
[games] Move games to independent repos

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#446]
With the years I have accumulated some raylib games in [raylib/games](https://github.com/raysan5/raylib/tree/develop/games) folder, most of those games a product of GameJams.

Probably those games should be moved to independent repos. What do you think?

**Comment by victorfisac** [comment]
I think those games are not quite complex to move them to independent repos. In my opinion, this 'games' folder can be considered as a raylib showcase (not templates, not examples)...

**Comment by RDR8** [comment]
I think it's good to have fun examples to look at and tinker/play with but maybe you don't need so many. Traditional examples like pang/snake/etc... might be good to keep. If you wanted to keep one of the larger games, Skully Escape was fun.

If you separate them all out but don't promote them, people might overlook them altogether. For example, who's using https://github.com/raysan5/challenges ?

**Comment by raysan5** [comment]
ok, leaving games in their folder for now. Also useful to keep all raylib related data together.

@RDR8, about raysan5/challenges, that's specific material for a University course I taught and I preferred to keep it separate from raylib.
