### ISSUE TITLE
Proposal to implement Vulkan backend 

### ISSUE THREAD

**Issue by platonvin** [raysan5/raylib#4467]
Hey,

I’d like to add a Vulkan backend for raylib to improve performance, but i have a few questions before starting

Proof of my experience with Vulkan (one of my projects): [Lum](https://github.com/platonvin/lum)

### 1) Why Vulkan cant be added through `rlgl`

raylib’s rendering currently relies on `rlgl`, which follows an old (2.x) OpenGL model. This design limits Vulkan capabilities because it doesn’t align with Vulkan’s approach to rendering

Instead of modifying `rlgl`, i propose a separate Vulkan-specific implementation. However, i’m unsure of the best way to integrate this into the existing project structure (see Point 3)

*if it was possible to achieve Vulkan performance with an old OpenGL API, Vulkan wouldn’t exist, and vendors would have simply improved OpenGL*

### 2) Does raylib need Vulkan? 

It’s worth considering whether Vulkan is really necessary for raylib. Vulkan can improve CPU side, but it doesn’t automatically boost GPU performance

For instance, raylib could improve GPU performance by using SDFs to draw primitives, which reduces triangle count (to just 2), adds perfect anti-aliasing (example of this approach can be seen in [Circuli Bellum](https://github.com/platonvin/Circuli-Bellum)  (see [`sdf_functions.glsl`](https://github.com/platonvin/Circuli-Bellum/tree/master/shaders/common/sdf_functions.glsl) and [`visual.hpp`](https://github.com/platonvin/Circuli-Bellum/blob/master/src/visual.hpp) / [`visual.cpp`](https://github.com/platonvin/Circuli-Bellum/blob/master/src/visual.cpp))), and is not dependent on GAPI

To better assess if Vulkan is worth it, it would help to profile complex raylib applications. Could you suggest any projects to profile?

Also, Vulkan is not easy to compile for web (practically impossible) and Apple (there is MoltenVK, but i do not own any Apple devices to test it)

### 3) Build system complexity 

IMHO current build system is too complex and i had troubles figuring it out. I think it could be simplified, which also might help with integrating Vulkan  

&nbsp;  
Looking forward to your thoughts

**Comment by raysan5** [comment]
@platonvin I'm afraid it has already been discussed many times. I think raylib does not need Vulkan. Main reason: maintainability.
