### ISSUE TITLE
pthreadGC-3.dll not found

### ISSUE THREAD

**Issue by Geams** [raysan5/raylib#449]
When trying to run some examples, e.g. physics_demo.c I get the error message
"pthreadGC-3.dll not found " (the file exists under MinGW\bin)
OS: Windows 10 Pro 64 Bit
I am using Notepad++ and MinGW that came with the raylib 1.8 Windows Installer
I am new to c programming.

**Comment by victorfisac** [comment]
You have to add these lines to your compilation code:
`-static -lpthread`

In the examples header comments, there is an example of compilation code:
`gcc -o $(NAME_PART).exe $(FILE_NAME) -s $(RAYLIB_DIR)\raylib\raylib_icon -static -lraylib -lpthread -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,--subsystem,windows -Wl,-allow-multiple-definition`

**Comment by Geams** [comment]
I am sorry, I overlooked that header comment.
The example works now, thanks a lot.
I am also trying to load images in the background like with libgdx's AssetManager while displaying a progress bar but I haven't found an example for that so far.
I like raylib a lot, it looks to be perfect for c programming newbies like me who want to get away from Java (libgdx).

**Comment by raysan5** [comment]
Hi @Geams! Nice to read you managed to run physac examples!

 > I am also trying to load images in the background like with libgdx's AssetManager while displaying a progress bar but I haven't found an example for that so far.

I did one example showing how to do taht in one of my classes... I'll try to find and upload it.
