### ISSUE TITLE
[build] Wayland game crashes with `EGL: Library not found`

### ISSUE THREAD

**Issue by nikita-skakun** [raysan5/raylib#4497]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

I have been using raylib in my game project for a couble of months now, and it successfully built and run on Wayland + NixOS. In the past couple of days something changed, that is causing the error below. Compiling without external GLFW doesn't result in the crash but incorrectly assumes I am using a 4K screen. I have tried rolling back raylib to v5.0, but that didn't help, so I assume it has something to do with my system. I have also tried rolling back my GPU drivers, but it still produced the crash.

### Environment

```
# uname -a
Linux desktop 6.11.5-zen1 #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980 x86_64 GNU/Linux

#glxinfo | grep NVIDIA
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 560.35.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 560.35.03
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 560.35.03
```

### Issue Screenshot

```
INFO: Initializing raylib 5.5
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: SYSTEM: Closest fullscreen videomode: 2560 x 1440
WARNING: GLFW: Error: 65542 Description: EGL: Library not found
WARNING: GLFW: Failed to initialize Window
fish: Job 1, './game' terminated by signal SIGSEGV (Address boundary error)
```

### Code Example

The game project can be found at: https://github.com/nikita-skakun/celestium

**Comment by gen2brain** [comment]
GLFW will use runtime linking (i.e. `dlopen`) to load some libraries, in your case it cannot find `libEGL.so.1`. As you are using NixOS which is famous for its unusual file system layout it has something to do with that.

**Comment by diniamo** [comment]
Opened NixOS/nixpkgs#357732

**Comment by diniamo** [comment]
A fix has been merged, we may want to close this issue.

**Comment by raysan5** [comment]
@diniamo thanks for the follow up!
