### ISSUE TITLE
[rshapes] Rlgl.SetLineWidth makes ellipses draw weird above 3

### ISSUE THREAD

**Issue by Shadowblitz16** [raysan5/raylib#4498]
Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description
I can't test with latest due to using the cs version.
Rlgl.SetLineWidth makes ellipses have inconsistencies in the corners

### Environment
![image](https://github.com/user-attachments/assets/93404ded-c53b-491d-a227-d1cf99bdcd52)

### Issue Screenshot
![image](https://github.com/user-attachments/assets/f6be5ad0-6e3e-48ef-8a8e-7e7938d47b42)

### Code Example
I am using C# version but here it is anyways...
[Terraria.zip](https://github.com/user-attachments/files/17783743/Terraria.zip)

**Comment by raysan5** [comment]
@Shadowblitz16  I'm afraid issue should be reported for the C version, C# bindings could be outdated.
