### ISSUE TITLE
raylib.h missing KEY_DELETE

### ISSUE THREAD

**Issue by DYSEQTA** [raysan5/raylib#450]
KEY_DELETE does not appear in raylib.h along with all the other key definitions.
Experimentation shows that the Delete key is returned from the GetKeyPressed() function as integer value 261 therefore in raylib.h there should be a line after #define KEY_BACKSPACE 259 which reads #define KEY_DELETE 261

**Comment by raysan5** [comment]
Hi @DYSEQTA! 

Thanks for pointing it, just added some missing keys defines in commit  https://github.com/raysan5/raylib/commit/44c95af463945023e0359790a69d2a991ef7185e
