### ISSUE TITLE
[rlgl] Setting sampler2D uniforms

### ISSUE THREAD

**Issue by TheLumaio** [raysan5/raylib#451]
I feel like this would be important for screenspace effects like ssao that require noise, depth, or normal textures. Currently I can't seem to even force it using gl functions but that may be due to my very limited opengl knowledge. Would you consider this or is it too far outside the scope of raylib?

**Comment by raysan5** [comment]
This issue is related to https://github.com/raysan5/raylib/issues/390

Actually, raylib is prepared to use custom shaders with custom uniforms in an easy way but I admit that provided examples are quite poor and don't illustrate usage of this functionality... Need to work on that!

I'll try to prepare a sample on that ASAP.

**Comment by raysan5** [comment]
Closing this issue. Usage example is provided in #390.

Still, more examples on shaders are required...

**Comment by TheLumaio** [comment]
That covers the way models handle multiple textures in shaders but not how to do it outside of that such as screen space effects that require multiple textures passed to a shader that's applied to a framebuffer. I found a solution and should have closed this myself earlier. I'll put it on gist and link it here if you like.

**Comment by raysan5** [comment]
Hey @TheLumaio, you're right. Actually, you can accomplish that using several `RenderTexture2D target;` You can render to `target.texture` with `BeginTextureMode()/EndTextureMode()` and then use `target.texture` as sampler2D for following drawing passes.

**Comment by pery77** [comment]
Hi, I need pass an additional texture to a shader, but I don't now how to do.
It is not for a model shader.

This is my simple shader:

#version 330

// Input vertex attributes (from vertex shader)
in vec2 fragTexCoord;
in vec4 fragColor;

// Input uniform values
uniform sampler2D texture0;
uniform sampler2D additionalTexture;

// Output fragment color
out vec4 finalColor;

void main()
{
    vec4 color = texture(texture0, fragTexCoord.xy);
    vec4 additional = texture(additionalTexture, fragTexCoord.xy); // I'm not sure about this coords...

    finalColor = color + additional ;
}

And this is my code:

	int Loc= GetShaderLocation(myShader, "additionalTexture");
	Texture2D addTex= LoadTexture("../Assets/water.png");

//Now I need pass addTex to myShader but how???
	SetShaderValue(myShader, ...

Thanks

**Comment by Nv7-GitHub** [comment]
I also have the same question as @pery77 , did you figure it out?

**Comment by chriscamacho** [comment]
have a look at the examples for example(!) shaders_multi_sample2 is using an extra texture texBlue. also as ray said https://github.com/raysan5/raylib/issues/390 gives a clear example
