### ISSUE TITLE
[build] Examples should build without the project being installed

### ISSUE THREAD

**Issue by yurivict** [raysan5/raylib#452]
Currently, it doesn't find the header and the library.
I tried to create a FreeBSD port option that would have built and installed examples, but with the current setup this is impossible.

**Comment by a3f** [comment]
Is CMake an option? You could build the `develop` branch with

https://github.com/raysan5/raylib/blob/d1ef6869a9e9404ce7039ddddad8fa35240d4f42/.travis.yml#L40

**Comment by raysan5** [comment]
Sorry, don't understand this issue, you mean adding [FreeBSD in release folder](https://github.com/raysan5/raylib/tree/develop/release)?

**Comment by yurivict** [comment]
No. Currently examples fail when raylib isn't installed.

**Comment by raysan5** [comment]
> Currently examples fail when raylib isn't installed.

Is it not the expected behaviour? I mean, raylib examples require the library to be installed to be compiled. Excuse me if I'm missing the point...

**Comment by yurivict** [comment]
What I meant is that examples should build as part of the project using locally built library.
For example, if I would like the port to install examples, they should be built as part of the project, and then installed. Currently it expects that the library is installed before it can build examples.

**Comment by RDR8** [comment]
Maybe take at look at #464 and see if it could be tweaked for FreeBSD.

**Comment by RDR8** [comment]
#480 is more progressive. It solves:

>What I meant is that examples should build as part of the project using the locally built library.
For example, if I would like the port to install examples, they should be built as part of the project, and then installed. Currently it expects that the library is installed before it can build examples.

**Comment by raysan5** [comment]
Just closing this issue. Please, feel free to reopen it if still not correct.
