### ISSUE TITLE
[examples] Failing `shaders_custom_uniform` example on MacOS

### ISSUE THREAD

**Issue by woollybah** [raysan5/raylib#4527]
While updating my language bindings for raylib 5.5, I found that `shaders_custom_uniform` example had an error at runtime.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [ ] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [ ] My code has no errors or misuse of raylib

### Issue description

I get an error at runtime when attempting to compile the `swirl.fs` glsl330 shader :

```
WARNING: SHADER: [ID 4] Failed to compile fragment shader code
WARNING: SHADER: [ID 4] Compile error: ERROR: 0:44: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:46: Use of undeclared identifier 'color'
```

It appears that the already deprecated `texture2D` function may no longer exist on MacOS.

Changing the shader to use the `texture` function instead, appears to have resolved this issue for me, and the example now works as expected.

You may want to update all of the glsl330 shaders to use `texture` instead of `texture2D` ?

### Environment

MacOS 15.1

INFO: GL: OpenGL device information:
INFO:     > Vendor:   Apple
INFO:     > Renderer: Apple M4 Max
INFO:     > Version:  4.1 Metal - 89.3
INFO:     > GLSL:     4.10

Latest github raylib source.

### Issue Screenshot

```
WARNING: SHADER: [ID 4] Failed to compile fragment shader code
WARNING: SHADER: [ID 4] Compile error: ERROR: 0:44: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:46: Use of undeclared identifier 'color'
```

### Code Example

Shaders example :  `shaders_custom_uniform.c`

**Comment by raysan5** [comment]
Good catch! Just reviewed it and a couple other shaders with the same issue!
