### ISSUE TITLE
[raylib] Update Version Information now that post-5.5 commits are happening

### ISSUE THREAD

**Issue by orcmid** [raysan5/raylib#4528]
The version information in `raylib.h` and elsewhere needs to be updated to indicate "-dev" of whatever the next anticipated release is.  It is currently set for "5.5" with no "-dev" suffix.

**Comment by raysan5** [comment]
@orcmid Thanks! Updated: https://github.com/raysan5/raylib/commit/50a2afff9ebf4f76c61fcf84c046586c9e9b6355
