### ISSUE TITLE
[rtext] `DrawTextCodepoint()` doesn't check if font is valid, which causes SIGSEGV

### ISSUE THREAD

**Issue by DenizBasgoren** [raysan5/raylib#4529]
### Issue description

Calling DrawTextCodepoint (and other functions working on fonts, I assume) with an invalid Font structure causes SIGSEGV, presumably due to the following line in the GetGlyphIndex function:

`if ((index == 0) && (font.glyphs[0].value != codepoint)) index = fallbackIndex;`

Causing this SIGSEGV is easy, as LoadFont doesn't indicate that it failed with an error, and IsFontValid is not used in the examples after loading fonts.

Possible solutions:
1. DrawTextCodepoint and similar functions call IsFontValid instead of assuming that font is valid.
2. DrawTextCodepoint and similar functions check font.glyphCount>0 instead of assuming that font is valid.
3. A boolean flag called isValid is added to the Font structure, indicating that the font is valid, and functions like DrawTextCodepoint check it each time they're called.
4. LoadFont returns an int which indicates that loading the font failed.
5. IsFontValid is shown in all examples. 

### Environment

Linux 6.11

### Issue Screenshot

-

### Code Example

```c
int main(void) {
    Font font = LoadFont("font.ttf"); // a non-existent font
    printf("Glyph count = %d\n", font.glyphCount); // 0
    InitWindow(800, 600, "title");
    while (!WindowShouldClose()) {
        BeginDrawing();
            DrawTextCodepoint(
                font,
                'a',
                (Vector2){100,100},
                100,
                GREEN
            );
        EndDrawing();
    }
}
```

**Comment by raysan5** [comment]
@DenizBasgoren thanks for reporting, fixed!
