### ISSUE TITLE
[build] Please allow to use the pre-installed external glfw

### ISSUE THREAD

**Issue by yurivict** [raysan5/raylib#453]

**Comment by yurivict** [comment]
There is also no need for ```find_package(OpenGL REQUIRED)``` when external ```glfw``` package is used.

**Comment by a3f** [comment]
You may now pass `-DWITH_SYSTEM_GLFW=ON` to CMake.

**Comment by raysan5** [comment]
Current already Makefile allows [using external GLFW](https://github.com/raysan5/raylib/blob/develop/src/Makefile#L62).

**Comment by raysan5** [comment]
@a3f would it be possible to rename option to `USE_EXTERNAL_GLFW` for consistency with current Makefile?

**Comment by raysan5** [comment]
Thanks @a3f!

**Comment by raysan5** [comment]
Could  this bug be closed?

**Comment by Martinfx** [comment]
yes
