### ISSUE TITLE
[build] Missing -o option for object files in Makefile

### ISSUE THREAD

**Issue by xroberx** [raysan5/raylib#4532]
Hi there!

I use the zig cc compiler to cross-compile raylib for Windows on Linux and, if not specified, it outputs object files with .obj extension instead of .o. Since the Makefile expects object files to end in .o, compilation fails. This is fixed by adding the -o option to the module targets in the Makefile. 

Before:
```
# Compile core module
rcore.o : rcore.c raylib.h rlgl.h utils.h raymath.h rcamera.h rgestures.h
    $(CC) -c $< $(CFLAGS) $(INCLUDE_PATHS)

```
After:
```
# Compile core module
rcore.o : rcore.c raylib.h rlgl.h utils.h raymath.h rcamera.h rgestures.h
    $(CC) -c $< -o $@ $(CFLAGS) $(INCLUDE_PATHS)

```

**Comment by raysan5** [comment]
@xroberx It works perfectly on the other platforms without the -o, so I prefer not to change it to support a specific use case, `zig cc` should support the standard conventions.

**Comment by xroberx** [comment]
@raysan5 I think it is good practice to use the -o option anyway, what are your objections against it?

**Comment by raysan5** [comment]
@xroberx that current implementation works in all tested platforms.

**Comment by xroberx** [comment]
@raysan5 Ok, it's a shame though, because zig cc is such a great tool for cross-compiling :( Let me know if you change your mind, I created a pull request.
