### ISSUE TITLE
[raudio] No sound

### ISSUE THREAD

**Issue by exformation** [raysan5/raylib#4533]
Issue: Device initializes successfully, no errors building/running, and the examples show that the song is progressing, but there is no audio. 

Potential Solution: I have a hunch raudio is using the wrong device? I've had this issue with some games, where I would hear no audio unless I changed to `PipeWire Sound Server`:  
![image](https://github.com/user-attachments/assets/dc0ba395-c0af-48c9-9f14-96ca37b6229d)  

I don't see any options for interacting with the audio devices on the cheatsheet, so not sure how to experiment with that. I'm guessing I'd have to dig into miniaudio?

**Comment by exformation** [comment]
Never mind. I switched back to PulseAudio and still have the issue, so it isn't a PipeWire thing. Raylib audio just doesn't show up anywhere in my system as a sound output, while other programs do.

**Comment by exformation** [comment]
I've confirmed that:
- Playing audio with other audio libraries like pygame works fine. 
- It isn't an issue with the headphones. 
- Switching to and from PipeWire/PulseAudio doesn't matter. 
- Tags 4.0 to master branch don't work, so if it's a raudio issue, it's been around a while. 

All other programs and audio libraries I've tried work fine, but I still feel like my computer might just be cursed in some way. I'm not really sure how to investigate this more. Tempted to just re-image ...

**Comment by Peter0x44** [comment]
Are you using Nix OS?

**Comment by exformation** [comment]
> Are you using Nix OS?
Yep

**Comment by exformation** [comment]
YES. Mentioning that made me take another look at my nix shell and compare it to one I used for bevy. I needed this: 
```
LD_LIBRARY_PATH = lib.makeLibraryPath buildInputs;
```

**Comment by decromo** [comment]
THANK YOU, I would've lost so many hours before thinking that it was a dynamic library issue (some logging from miniaudio would've been helpful...)
For reference, instead of using `LD_LIBRARY_PATH` you could link alsa at compile-time with `-lasound` (provided of course that alsa itself is available in your derivation/shell/environment).
_(also isn't it weird that nix-ld doesn't pick it up?)_
