### ISSUE TITLE
LoadTexture in separate thread

### ISSUE THREAD

**Issue by Geams** [raysan5/raylib#454]
I am trying to load game assets in a separate thread while displaying a message or progressbar to the user.
The following code doesn't work:
<pre>INFO: [hero.png] Image loaded successfully (50x100)
WARNING: Texture could not be created</pre>
<pre>
#include "raylib.h"
 #include <pthread.h>
 Texture2D spriteSheet;
 int state = 0;
 void *loadAssets(){
     spriteSheet = LoadTexture("hero.png");
     state = 1;
 }
 int main(){
    InitWindow(1280,720,"Title");
    pthread_t threadId;
    pthread_create(&threadId, NULL, loadAssets,NULL);  
    SetTargetFPS(60);
     while (!WindowShouldClose()){
        BeginDrawing();
        ClearBackground(RAYWHITE);
        switch(state){
            case 0:
                DrawText("Loading", 640, 360, 32, BLACK);
                break;
            case 1:
                DrawTexture(spriteSheet,0,0,WHITE);
                break;
        }
        EndDrawing();
     }
    UnloadTexture(spriteSheet);
    CloseWindow();
 }
</pre>

**Comment by TheLumaio** [comment]
There's already an issue for this #448. The new thread doesn't have an opengl context and therefore cannot load textures. There are a few ways around this one of which has an entire wiki pageon the khronos wiki, https://www.khronos.org/opengl/wiki/OpenGL_and_multithreading
