### ISSUE TITLE
[rcore] Setting the camera's up to the Z-axis flips the X-axis

### ISSUE THREAD

**Issue by BionicRabbit3** [raysan5/raylib#4552]
### Issue description

For some reason setting a `Camera3D`'s `up` to `(0, 0, 1)` makes the x-axis go from right to left.
This in turn makes all the graphics being drawn flipped horizontally.

### Environment

Tested on raylib 5.5 desktop, on Windows 11.

### Code Example

```c
#include "raylib.h"

int main(void)
{
    const int screenWidth = 640;
    const int screenHeight = 480;

    InitWindow(screenWidth, screenHeight, "Demo");

    Camera camera = {0};
    camera.position = (Vector3) { 0.0f, 10.0f, 0.0f }; // Look from positive-Y
    camera.target = (Vector3) { 0.0f, 0.0f, 0.0f };    // to the center
    camera.up = (Vector3) { 0.0f, 0.0f, 1.0f };        // with Z being up.
    camera.fovy = 45.0f;
    camera.projection = CAMERA_PERSPECTIVE;

    SetTargetFPS(60);

    while (!WindowShouldClose())
    {
        BeginDrawing();

            ClearBackground(RAYWHITE);

            BeginMode3D(camera);

                Vector3 start = { 0.0f, 0.0f, 0.0f };
                Vector3 end = { 5.0f, 0.0f, 0.0f }; // Draw a line from the center to positive X.
                DrawLine3D(start, end, RED);

            EndMode3D();

        EndDrawing();
    }

    CloseWindow();

    return 0;
}
```

### Code Example Screenshot

![actual](https://github.com/user-attachments/assets/512f24d0-3611-40c1-bab6-d7493805aa48)

### Expected Behavior

![expected](https://github.com/user-attachments/assets/a6f33a6f-5070-49db-889e-53c8ddc93d3c)

**Comment by raysan5** [comment]
@BionicRabbit3 I think it is related to raylib intermal maths coordinates conventions, trying to address it could potentially break many other things.

**Comment by BionicRabbit3** [comment]
Oh wow really?
What can I do about it then?
(Maybe a way to set the view matrix of the camera manually instead of position/target/up?)
