### ISSUE TITLE
[parser] Double quotes in function comments produce invalid JSON

### ISSUE THREAD

**Issue by chrisws** [raysan5/raylib#4558]
The comment text for function `GetKeyName` contains a double quote. 

```
// Get name of a QWERTY key on the current keyboard layout (eg returns string "q" for KEY_A on an AZERTY keyboard)
```

This causes the resulting file `parser/output/raylib_api.json` to become invalid (for the JSON parser I'm using for my project at least). To fix, either:

1. Write the comment with single quotes, eg `'q'`
2. In the comments parser, escape any double quotes, eg `""q""`
3. In the comments parser, convert any double quotes in comments to single quotes.

**Comment by raysan5** [comment]
@chrisws Thanks for reporting, reviewed!
