### ISSUE TITLE
[build] Could you please make a release?

### ISSUE THREAD

**Issue by yurivict** [raysan5/raylib#457]
I am trying to create a FreeBSD port, but I don't want to use the 'develop' branch.
In the other bug reports you said that you've fixed things, but all fixes are in the 'develop' branch.

**Comment by raysan5** [comment]
Hi @yurivict, I'm preparing a new small release for FreeBSD, just a couple of changes pending:  https://github.com/raysan5/raylib/issues/401#issuecomment-362897467

**Comment by raysan5** [comment]
new release with raylib v1.9.4-dev launched

Latest develop changes have been integrated into master branch

**Comment by raysan5** [comment]
Could  this bug be closed?

**Comment by Martinfx** [comment]
yes
