### ISSUE TITLE
[build] Compile error for Android (compile_project_class)

### ISSUE THREAD

**Issue by tonghoameo** [raysan5/raylib#4571]
![Screenshot_2024-12-03_16_34_21](https://github.com/user-attachments/assets/df8e4004-e74d-4368-9fbb-e9030862a250)
Anyone see it like me?????

**Comment by raysan5** [comment]
It seems it could be related to the version of Android SDK/NDK being used or the targeting Android version. Maybe @Bigfoot71 could help with this one.

**Comment by Bigfoot71** [comment]
@tonghoameo Could you provide more context about where you are encountering this error?

It seems you are using the [raylib-game-template](https://github.com/raysan5/raylib-game-template) and the error indicates a macro redefinition in a source file : `#define __ANDROID__ 30`

However, I cannot find any occurrence of this macro in either `raylib` or the template project.

And it seems I can’t test this template on Linux (which you also appear to be using) without modifying it, as its Makefile for Android appears to only be usable on Windows.

**Comment by tonghoameo** [comment]
> @tonghoameo Could you provide more context about where you are encountering this error?
> 
> It seems you are using the [raylib-game-template](https://github.com/raysan5/raylib-game-template) and the error indicates a macro redefinition in a source file : `#define __ANDROID__ 30`
> 
> However, I cannot find any occurrence of these ~macro~ definitions in either `raylib` or the template project.
> 
> And it seems I can’t test this template on Linux (which you also appear to be using) without modifying it, as its Makefile for Android appears to only be usable on Windows.
> 
> Wait, excuse me, this actually seems to be just a warning without further consequences, as the end of your output is: ![image](https://private-user-images.githubusercontent.com/90587919/398253366-bda0e88b-0f4a-4216-a75f-433be7dc3f38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzODcxMTMsIm5iZiI6MTczNTM4NjgxMywicGF0aCI6Ii85MDU4NzkxOS8zOTgyNTMzNjYtYmRhMGU4OGItMGY0YS00MjE2LWE3NWYtNDMzYmU3ZGMzZjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDExNTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YmJjOWRiOTE3NTFkNGJmMzkyNjkwZTUzM2RmMzM5MDM2OTc0NDY3NDgyYmM1OTQ3MjlmYzljYmUxNmY1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GbNK7qMp3Ply9SnVr5XD0kjW86jx9UceOEzahindUnU)
> 
> **Have you started making your own modifications to the [Makefile.Android](https://github.com/raysan5/raylib-game-template/blob/main/src/Makefile.Android) from the template to make it work on Linux?**

**Comment by tonghoameo** [comment]
Thank so much, i got it.
