### ISSUE TITLE
[rcore] rres support broken in raylib 5.5 -> project build fails

### ISSUE THREAD

**Issue by zapposh** [raysan5/raylib#4573]
Platform: Windows 11
Version: raylib 5.5 (itch.io installer release)

Project was building fine using raylib 5.0 and rres.
Upgrading to version 5.5 broke the game build, which throws the following error:
conflicting types for 'ComputeMD5'; have 'unsigned int *(const unsigned char *, int)'

![image](https://github.com/user-attachments/assets/23f5704b-ca2f-490d-8e34-1ca71306e66b)

**Comment by iulian3144** [comment]
`ComputeMD5` was added in [361b0e85](https://github.com/raysan5/raylib/commit/361b0e85c10fb20e69c35d0304d64d891a8964f2).
This makes raylib v5.5 incompatible with the current version of rres.

It doesn't look like rres is kept up to date to follow the latest raylib developments.

In any case, I would either report this to rres or just create a PR to fix this specific issue.

**Comment by raysan5** [comment]
Reviewed.
