### ISSUE TITLE
[rmodels] Potential problem with transforming normals during animations

### ISSUE THREAD

**Issue by Bigfoot71** [raysan5/raylib#4581]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [ ] My code has no errors or misuse of raylib

### Issue description

There seems to be a potential error in the normal transformation process within the `UpdateModelAnimation()` function. I noticed that the shading looked strange when using my lighting shader during an animation, which led me to suspect the normals were being handled incorrectly. After some investigation, I checked the code responsible for transforming the normals in [rmodels.c:2358](https://github.com/raysan5/raylib/blob/master/src/rmodels.c#L2358):

```c
// Normals processing
// NOTE: We use meshes.baseNormals (default normal) to calculate meshes.normals (animated normals)
if (mesh.normals != nullptr) {
    animNormal = (Vector3){ mesh.normals[vCounter], mesh.normals[vCounter + 1], mesh.normals[vCounter + 2] };
    animNormal = Vector3Transform(animNormal, surface.mesh.boneMatrices[boneId]);
    mesh.animNormals[vCounter] += animNormal.x * boneWeight;
    mesh.animNormals[vCounter + 1] += animNormal.y * boneWeight;
    mesh.animNormals[vCounter + 2] += animNormal.z * boneWeight;
}
```

I observed that the normals are being transformed like this:
```c
animNormal = Vector3Transform(animNormal, surface.mesh.boneMatrices[boneId]);
```

But shouldn’t we be transforming the normals using only the rotational part of the matrix, by obtaining the inverse transpose? 
```c
animNormal = Vector3Transform(animNormal, MatrixTranspose(MatrixInvert(surface.mesh.boneMatrices[boneId])));
```

Or maybe I’m missing something else to properly solve this issue, which could explain why the function was written this way.

---

Here’s an example with the current function (look at the robot's hands):
<img src="https://github.com/user-attachments/assets/e95b5dd6-e1b4-4158-a3ec-549a292cab77" width="500" />

And here’s an example with the inverse-transpose transformation applied:
<img src="https://github.com/user-attachments/assets/90899a63-cdaf-40cf-be8c-44dc5b9caaf8" width="500" />

**Comment by Bigfoot71** [comment]
Sorry for the title, I'm tired :fearful:

**Comment by raysan5** [comment]
> But shouldn’t we be transforming the normals using only the rotational part of the matrix, by obtaining the inverse transpose?

@Bigfoot71 Interesting... sincerely, I don't know... but it seems to work ok with the transform... could you test with some other models to confirm the issue?

**Comment by Kirandeep-Singh-Khehra** [comment]
I have also faced similar issue with Mixamo y bot it was working before but then i updated to raylib5 or 5.5(can't recall) and messed up normals. I thought it was issue with model.

![screenshot000](https://github.com/user-attachments/assets/3b418b4c-3131-444c-a234-922f888dad32)

it looks like normals are overrotated or bone rotation have also brightens the part.
i am using UpdateModelAnimation() to update animation and lighting.vs and fs from raylib examples.

**Comment by Bigfoot71** [comment]
I just tested with a new model, and there is indeed an issue with the transformation of normals in the original function. Moreover, there seem to be additional animation problems...

Here it is with the current function:

https://github.com/user-attachments/assets/35e6b980-ad9e-42a2-808a-e4ab5ebeec73

Here it is with my quick fix:

https://github.com/user-attachments/assets/70fba5d5-b42b-4013-88e2-2c56da591533

Here is the original model:
https://sketchfab.com/3d-models/animated-old-chest-4477ee9446b34d8e857906816ca5245a

**Comment by raysan5** [comment]
@Bigfoot71 Ok, I see. Please, could you send a PR with the fix?
