### ISSUE TITLE
Raylib 5.5 Poor Performance on 6700XT RayLib 4.5  5 times better result

### ISSUE THREAD

**Issue by cjdaylight** [raysan5/raylib#4592]
I am using 6700xt 
I Loaded Heavy Model Contains 8 Million Vertices.
in Raylib 5.5 it is gives me 200 fps
in RayLib 4.5 it is gives me 1000 fps 
something is wrong I think it is bug
Code is official model loading code 
I am loading model and rendering 
Meshes Are Same and OpenGL Version 3.3

**Comment by raysan5** [comment]
@cjdaylight I'm afraid not much can be done with provided information. Please, follow issues required template and privide a complete exampke for testing and review.
