### ISSUE TITLE
Poor Performance after update

### ISSUE THREAD

**Issue by cjdaylight** [raysan5/raylib#4593]
-  I tested it on latest raylib version from master branch Yes I do
 - I checked there is no similar issue already reported Yes I do (I Posted Last Night but seems not made it)
 - I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki) Yep
 - My code has no errors or misuse of raylib Code is Offical code so yes

### Poor Performance on Raylib 5.5

*When I update Raylib 5.5 performance decreased greatly on Raylib 4.5 1200 - 1000 fps on Raylib 5.5 only 200 I dont know why and how but what I noticed is z fighting happens with mesh maybe mesh is uploaded to gpu 2 times .*

### Environment

*Platform: Desktop
Operating System: Windows 10 
OpenGL:  version 3.3
GPU:  AMD 6700XT.*

### Code Example

*https://www.raylib.com/examples/models/loader.html?name=models_loading*

**Comment by cjdaylight** [comment]
1 Model loading.c Yes but only difference I change object
2 I compile my self it is working in my local Desktop
3 No Vsync Disabled
4 .obj

**Comment by asdqwe** [comment]
If you expect help, you'll have to answer these questions more clearly. Half of the answers are missing and please use punctuation.

1. So, you're compiling [models/models_loading.c](https://github.com/raysan5/raylib/blob/master/examples/models/models_loading.c) yourself for `PLATFORM_DESKTOP` on Windows, correct?
2. The **only** change you made to it was the loaded file path at [Line 49](https://github.com/raysan5/raylib/blob/b747eeefa4542cb1737997498991273d7a559d3f/examples/models/models_loading.c#L49), correct? Anything else?
3. And you are checking the FPS with the [in-example FPS display](https://github.com/raysan5/raylib/blob/b747eeefa4542cb1737997498991273d7a559d3f/examples/models/models_loading.c#L138), correct?

**Comment by cjdaylight** [comment]
1 Yes I am Even Compiled RayLib My self
2 Yes only line 49
3 Yes My Fps Low on 5.5 High on 5.5 I Also tried 1.0.4 1.8, 2.0 2.5 3.0 3.5 4.0 4.5
The results are 1.0.4 and 5.5 Worst Performance Others Are almost same.
 in 1.8 best cpu ussage Gpu result allmost same
 after 3.5 Cpu Ussage bit higher
 
 in short words I make Identical test both 4.5 5.5
 and 5.5 Perform bad.
 cpu usage not high not cpu bottleneck
 GPU Ussage both 100%

**Comment by raysan5** [comment]
@cjdaylight please, could you share two videos of the same example, one using raylib 4.5 and one using raylib 5.5, showing the FPS counter difference? Also, if you are using some .obj model for the test and it is free, please, could you share it?

**Comment by asdqwe** [comment]
> 2 Yes only line 49

If only that Line 49 was changed, then the framerate should have stayed at 60 fps due to the `SetTargetFPS(60);` from [Line 64](https://github.com/raysan5/raylib/blob/b747eeefa4542cb1737997498991273d7a559d3f/examples/models/models_loading.c#L64). To completely unlock the framerate you'll have to call `ClearWindowState(FLAG_VSYNC_HINT);` and `SetTargetFPS(0);`.

Please test this example:
```
#include "raylib.h"
int main(void) {
    InitWindow(800, 450, "test");

    ClearWindowState(FLAG_VSYNC_HINT); // Disable vsync
    SetTargetFPS(0);                   // Unlock framerate

    Model model = LoadModel("resources/models/obj/castle.obj");
    Texture2D texture = LoadTexture("resources/models/obj/castle_diffuse.png");
    model.materials[0].maps[MATERIAL_MAP_DIFFUSE].texture = texture;

    Camera camera = { 0 };
    camera.position = (Vector3){ 50.0f, 50.0f, 50.0f };
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
    camera.fovy = 45.0f;
    camera.projection = CAMERA_PERSPECTIVE;
    DisableCursor();

    while (!WindowShouldClose()) {
        UpdateCamera(&camera, CAMERA_FREE);
        BeginDrawing();
            ClearBackground(RAYWHITE);
            BeginMode3D(camera);
                DrawModel(model, (Vector3){ 0.0f, 0.0f, 0.0f }, 1.0f, WHITE);
            EndMode3D();
            DrawFPS(20, 20);
        EndDrawing();
    }

    UnloadTexture(texture);
    UnloadModel(model);
    CloseWindow();
    return 0;
}
```
<br>

@raysan5 There appears to be a VAO warning tho:
```
[...]
INFO: FILEIO: [resources/models/obj/castle.obj] Text file loaded successfully
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
WARNING: VAO: [ID 2] Trying to re-load an already loaded mesh
[...]
```

**Comment by cjdaylight** [comment]
Video of The bug


as you can see I used same project and result is different
also yes 
INFO: FILEIO: [resources/models/obj/castle.obj] Text file loaded successfully
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
WARNING: VAO: [ID 2] Trying to re-load an already loaded mesh
I noticed that to but I forgot to type here sorry.
by the way  I think default camera far and near is bad. because these flickering is not normal.
anyway I hope We can solve this bug




https://github.com/user-attachments/assets/087edbc9-41e5-41b1-9480-9f44b09bce56

**Comment by asdqwe** [comment]
1. Setting `SetTargetFPS(0)` or `SetTargetFPS(100000000)` does **not** disable `vysnc`.
2. Your framerate is limited at 90 fps probably because `vsync` is on and that's likely the monitor/resolution frequency in use.
3. Test raylib 5.5 again but add `ClearWindowState(FLAG_VSYNC_HINT);` after `InitWindow()` to **disable** `vsync`.
4. Also, the `LoadModel()` call on raylib 5.5 is using scale `1.0f`, while the other is using scale `2.0f`.
5. Both tests are also using very different textures.

Unless there's something else, doesn't look like there's anything seriously wrong/broken with raylib 5.5.

**Comment by cjdaylight** [comment]
My monitor is 260 hz

**Comment by asdqwe** [comment]
Took a look at the VAO warning and it's just this:
https://github.com/raysan5/raylib/blob/b747eeefa4542cb1737997498991273d7a559d3f/src/rmodels.c#L1256-L1258

Since the mesh is already on the GPU, it does an early return. So, nothing there really.

**Comment by raysan5** [comment]
I'm afraid there is not much to do with provided information.
