### ISSUE TITLE
[rlgl] Compile error for Android with OpenGL ES 3

### ISSUE THREAD

**Issue by Bigfoot71** [raysan5/raylib#4604]
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

I tried to build raylib for Android with the flag `GRAPHICS_API_OPENGL_ES3`, but I got this error:
```console
ld.lld: error: undefined symbol: glDrawBuffersEXT
```

For the line [1915 (rlgl.h)](https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L1915):
```c
#if defined(GRAPHICS_API_OPENGL_ES3)
            glDrawBuffersEXT(count, buffers);      ///< L1915
#else
            glDrawBuffers(count, buffers);
#endif
```

I simply replaced `glDrawBuffersEXT` with `glDrawBuffers`, just like the line below, and the compilation succeeded and everything works as expected.

Is there a reason to use `glDrawBuffersEXT` here? Because it seems to me that this is an extension for OpenGL ES 2 originally, am I wrong?

**Comment by Bigfoot71** [comment]
Sorry, I really have a problem with titles :skull:

**Comment by Bigfoot71** [comment]
To elaborate on what I was thinking -> https://registry.khronos.org/OpenGL/extensions/EXT/EXT_draw_buffers.txt

It does seem that this is an extension for OpenGL ES 2.0, inspired by the features of OpenGL ES 3.0, unless I missed something.

**Comment by asdqwe** [comment]
You're correct, that `#if` is (very) wrong.
`OpenGL ES1` and `OpenGL ES2` should use `glDrawBuffersEXT()`.
`Open GL ES3` and `OpenGL 2.0` to `OpenGL 4.5` should use `glDrawBuffers()`
Refs: [1](https://emscripten.org/docs/optimizing/Optimizing-WebGL.html#migrating-to-webgl-2), [2](https://registry.khronos.org/OpenGL-Refpages/es3.0/), [3](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDrawBuffers.xhtml).

**Comment by Bigfoot71** [comment]
Well, given the conditions at the top of the function, it seems that we just need to remove the extra `#if defined(GRAPHICS_API_OPENGL_ES3)` without causing any issues

**Comment by asdqwe** [comment]
Yup.

I was going to suggest replacing it with `GRAPHICS_API_OPENGL_ES2`, but them I saw [this](https://github.com/raysan5/raylib/blob/93a1e75741175b9a2136593064b3714e79a363e2/src/rlgl.h#L188-L191).
So, yeah, I think it's indeed safer to just delete it.

**Comment by raysan5** [comment]
@Bigfoot71 @asdqwe thanks for reporting and investigating this issue, definitely `glDrawBuffersEXT()` belongs to OpenGL ES 2.0, requiring [`EXT_draw_buffers` extension](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_draw_buffers.txt). OpenGL ES 3.0 supports `glDrawBuffers()` natively.

That code was added recently to support deferred rendering but not extensively tested on all platforms. Also saw the `RLGL_RENDER_TEXTURES_HINT` that I didn't remember it was added, probably as part of the full new system.

The code should probably test for OpenGL ES 2.0 but that option is not considered in the first place, it could imply additional functions and extensions in other places. So, current PR should be ok for current use case.

About the *Framebuffer has incomplete attachment* issue, did you verify you are compiling for OpenGL ES 3.0 and `RLGL_RENDER_TEXTURES_HINT` is enabled?

**Comment by asdqwe** [comment]
> So, current PR should be ok for current use case.

@raysan5 @Bigfoot71 I was going to mention that on the #4605 PR. I've tested with `GRAPHICS_API_OPENGL_33` and `rlActiveDrawBuffers` it's working properly, so, regarding the `glDrawBuffers` scope, it should satisfy `OpenGL ES3`.

Compiling for `GRAPHICS=GRAPHICS_API_OPENGL_ES3` and then compiling the shader examples will both succeed. However, upon execution, all shader examples break due to shader compatibility issues. So, the state of `GRAPHICS_API_OPENGL_ES3` would be a different (much larger scope) issue.

> and `RLGL_RENDER_TEXTURES_HINT` is enabled?

It should be enabled by default ([ref](https://github.com/raysan5/raylib/blob/d0504800d2c5a5e722a65a9023ddadca17f930bc/src/rlgl.h#L193-L195)).

**Comment by Bigfoot71** [comment]
@raysan5 @asdqwe I found the issue with incomplete framebuffer attachments in [shaders/shaders_deferred_render.c](https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_deferred_render.c) for OpenGL ES 3. This happens because, in the example, we create a texture with the `RGB32F` format, which uses three 32-bit floating-point components [L100](https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_deferred_render.c#L100):
```c
// Since we are storing position and normal data in these textures, 
// we need to use a floating point format.
gBuffer.positionTexture = rlLoadTexture(NULL, screenWidth, screenHeight, RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32, 1);
gBuffer.normalTexture = rlLoadTexture(NULL, screenWidth, screenHeight, RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32, 1);
```

A format that does not appear to be supported in ES 3.0 ([source](https://registry.khronos.org/OpenGL/specs/es/3.0/es_spec_3.0.pdf#page=144&zoom=100,-339,746)):
<img src="https://github.com/user-attachments/assets/9154c71e-0908-4860-9907-210f8aeb48eb" alt="Image Example" width="325" height="397">

Simply replacing `RL_PIXELFORMAT_RGB32F` with `RGBA32F` made the example work with ES 3.2 for me.  
It is worth noting that `RGB16F` also works.

**Comment by raysan5** [comment]
@Bigfoot71 Wow! Good catch! And actually very weird that `RGB32F` is not supported! Feel free to send a PR to update it... and also adding a comment on that line for future users to be aware!
