### ISSUE TITLE
how to make  animation transitions smooth

### ISSUE THREAD

**Issue by WOLFxxxxxx** [raysan5/raylib#4608]
![IMG_٢٠٢٤١٢١٦_٢٣١٥٢٣](https://github.com/user-attachments/assets/973cf955-743e-4382-b8f0-ffe2f182717b)

**Comment by asdqwe** [comment]
Please try to keep the issues for raylib issues/bugs.
Also please use the search function, there are two PRs ([1](https://github.com/raysan5/raylib/pull/4578), [2](https://github.com/raysan5/raylib/pull/4602)) and a discussion ([3](https://github.com/raysan5/raylib/discussions/4606)) regarding this topic.

**Comment by orcmid** [comment]
What is the issue?

If this is a request for help or advice on `tweening in animations, please go to the raylib Discord channel.

You can also move this #4608 to Discussions.  My sense is that the Discord is preferable.  See the raylib README for the link under "contact and networks" near the end.

**Comment by raysan5** [comment]
redundant issue and not following issues template
