### ISSUE TITLE
[build] Don't hardcode raylib version

### ISSUE THREAD

**Issue by a3f** [raysan5/raylib#461]
(Suggestion prompted by #459)

* Every build, check if git is available
    * **It isn't**: Fallback to a hardcoded numerical value in file `VERSION` and append `-unknown`
    * **It is**: Use `git describe --tags --dirty` as version
         * This returns `1.9.3-dev` or if there are commits since the tag, it appends a commit id after the tag, e.g. `1.9.3-dev-1-g0edaecf` or `1.9.3-dev-1-g0edaecf-dirty` if there were uncommited changes.
         * Save result of `git describe --tags --abbrev=0` to `VERSION` file
* Pass version as `RAYLIB_VERSION` macro to build process.
* Define `RAYLIB_VERSION_MAJOR`, `RAYLIB_VERSION_MINOR`, `RAYLIB_VERSION_REVISION` in `raylib.h`
* Export `const char *RaylibGetVersionString(void)` from library which returns `RAYLIB_VERSION` at build-time
* Export `void RaylibGetVersion(int *major, int *minor, int *revision)`
* Because suffixes aren't always expected, embed only numerical version (e.g. `1.9.3` without the `-dev`) in pkg-config and shared libraries.
* `VERSION` file is updated on every build, but there are no actual change unless there's a new tag.

For the `RAYLIB_VERSION_*` macros, while easy to implement in CMake, will probably have to be shelled out in the Makefiles. Maybe provide a `mkversion.bat` and `mkversion.sh` that update a `raylib.h.in` accordingly.

**Comment by a3f** [comment]
Small problem: We do development in the `develop` branch, but tag the master branch merge commit, so `git describe --tags` won't see it… (Of couse, #443 would fix that :-)

**Comment by RDR8** [comment]
Can you just grab the version from raylib.h instead of adding a new file?

**Comment by a3f** [comment]
Ye, that could work too.

**Comment by raysan5** [comment]
I'd prefer to keep it as simpler as possible.

 > Pass version as RAYLIB_VERSION macro to build process.

That seems a simple enough option to start with.

**Comment by raysan5** [comment]
Added `RAYLIB_VERSION` to config.h on commit https://github.com/raysan5/raylib/commit/8e44f7b3c7362ca03f408b711a9baea41640ceac

**Comment by raysan5** [comment]
Closing this issue.
