### ISSUE TITLE
[rcore] Can't take screenshots in fullscreen

### ISSUE THREAD

**Issue by Volcanic-Penguin** [raysan5/raylib#4614]
### Issue description

If my game is running in fullscreen and I press the PrintScreen key, it will take a screenshot of whatever was on my screen before running the game. Taking screenshots in windowed mode works fine. 

### Environment

Raylib 5.0 with Rust (raylib-rs)
Windows 10
Platform backend: DESKTOP (GLFW)
Renderer: Intel(R) HD Graphics 530

### Issue Screenshot

Windowed Screenshot:

![2024-12-18 (2)](https://github.com/user-attachments/assets/a7e5ef6a-45b7-4f12-87c2-a247bda2839a)

Fullscreen Screenshot:

![2024-12-18](https://github.com/user-attachments/assets/32e1d4a8-1c2f-41fb-aa61-0819e66fa7b1)

### Code Example

I believe all you need is to run `ToggleFullscreen()`

**Comment by raysan5** [comment]
I'm afraid this is the expected behavious, `PrintScr` is managed by the OS to get the screen but when you `ToggleFullscreen()` you change to application excusive mode, so afaik, the OS has no control of the screen any more. As al alternative, use `ToggleBorderlessWindowed()`.
