### ISSUE TITLE
[build] Provide pre-configured projects for common IDEs

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#466]
Prepare several pre-configured projects for common development environments avaliable in the different OS, similar to the already provided solutions for VS2015 and VS2017. The proposed IDEs would be:

- [x] Visual Studio 2015 (`Windows`) -> *raylib/projects/VS2015*
- [x] Visual Studio 2017 (`Windows`) -> *raylib/projects/VS2017*
- [x] Visual Studio Code (`Linux`, `Windows`, `macOS`) -> *raylib/projects/VSCode*
- [x] Geany (`Linux`, `Windows`, `macOS`) -> *raylib/projects/Geany*
- [x] Code::Blocks (`Linux`, `Windows`, `macOS`) -> *raylib/projects/CodeBlocks*
- [x] GNOME Builder (`Linux`) -> *raylib/projects/Builder*
- [ ] KDevelop (`Linux`, `Windows`, `macOS`) -> *raylib/projects/KDevelop*

Provided projects should be configured to compile raylib library (static/dynamic) and a simple example (i.e. `core_basic_window.c`).

**Comment by OvermindDL1** [comment]
KDevelop is a significantly better C/C++ IDE for linux than about anything else listed there (and I think it has a windows port as well but it's still in-dev).  It's native format is just cmake files though (it makes a secondary file for holding workspace settings but that's fairly useless overall).  Code::Blocks is fairly bad considering what is available nowadays, and isn't Geany basically a glorified text editor?  Never heard of GNOME Builder though...  ^.^;

**Comment by RDR8** [comment]
YIf you there are people who would benifit, you're welcome to support it. The more the merrier, just follow the naming convention. Code::Blocks is driven by requests on the forum and elsewhere. Geany isn't too different from Gedit or Kate. Like them, it has plugins to expose a terminal, version control, gdb, scripting support and various other low-level tools. It's included in Raspbian, is available everywhere else I've looked and runs well on every machine and DE I've tried. It is kind of boring but gets the job done in a clear way.

Builder is nice if you're on GNOME. Both GNOME and KDE are too heavy for some kinds of machines raylib runs on, though that is no reason to not support them. If you have a sensible config for KDevelop, it should be just a drop-in PR, though I won't speak for Ray.

**Comment by raysan5** [comment]
Thanks @OvermindDL1 for the point, just added KDevelop to list.

**Comment by RDR8** [comment]
Cool, I didn't know that. I do really like the KDE interface in general and remember being a little bothered by QtCreators unique interface. I did like the documentation viewer and analysis tools but didn't stick around. I don't have any projects complex enough to really use an advanced IDE but I do learn quite a bit by looking at the tools they include. When I have a machine with enough RAM, I'll give it a try. Thanks!

**Comment by OvermindDL1** [comment]
> You mean the extra apps like QtDesigner and stuff?

Indeed, it is fairly easy to accidentally load them...  ^.^;

> Cmake is a litterbug too.

No it's not?  It keeps **everything** in it's build directory (which, in my opinion, should never ever *ever* be in-source, even KDevelop defaults it to being a dedicated subdirectory).  o.O?

**Comment by RDR8** [comment]
I don't know enough to have made that general statement. I probably wasn't using it correctly, I just remember new files all over the tree.

**Comment by OvermindDL1** [comment]
> I just remember new files all over the tree.

Yeesh, yeah that is *absolutely* not right.  If you see any project of who's build does that when you are not doing an in-source build (again, *never* recommended to do in-source builds, always do out-of-source builds), definitely file a bug report to them (and probably point them to [The Hitchhiker’s Guide to the CMake](https://cgold.readthedocs.io/en/latest/) (made by one of the big CMake people, in addition to the official CMake docs of course)...).

**Comment by jubalh** [comment]
Should this be done to master or develop branch?

**Comment by jubalh** [comment]
Builder is done in https://github.com/raysan5/raylib/pull/470

**Comment by RDR8** [comment]
Hey! I just came back to this yesterday. I have Geany configured for some common scenarios but I'm still not sure how to cause specific files, i.e. raylib.h, to open automatically as you have notepad++ doing. I guess something is better than nothing so I'll get cracking.

**Comment by jubalh** [comment]
>  i.e. raylib.h, to open automatically as you have notepad++ doing.

Never used Geany so a very uninformed note here: are you sure it *can* do this? If yes, maybe you need `ctags` for this to work?

**Comment by RDR8** [comment]
I thought it would be simpler. A .geany project file keeps a list of open files in a raw string format like %2Fhome%2Fraylib%2Fsrc%2Fraylib.h . Not sure how to get our relative paths parsed so Geany can find the files. If there is an expansion mechanism, I haven't found it. There are several external methods to tweak the environment during `make install` or some other `target` but obviously I want to get the most out the project file first.

On the plus side, custom Build Menu commands embedded in the project file CAN find the source tree. This is where the practical customizations happen. We can create project-global or filetype-specific commands. Deciding what to put here is the fun part. I could make a [Start] button to open the initial environment but I want it auto, you know?

**Comment by raysan5** [comment]
Just created the required folders for the different IDEs that can be supported in commit https://github.com/raysan5/raylib/commit/8ae8d3ac782825d732a0680bd1ad80db420718a9

Please, feel free to add your project related files to those folders! :)

**Comment by raysan5** [comment]
Hey @RDR8! What's your progress with Geany project files? Could you send a PR?

**Comment by liamkennedy89** [comment]
Hey @raysan5 . I'm attempting to set up Visual Studio Code with raylib at the moment with the aim of getting in a PR. Any tips on fixing the error 'The code execution cannot proceed because libwinpthread-1.dll was not found. Reinstalling the program may fix this problem'? 

happens when I try: 
C:\raylib\mingw\bin\gcc.exe -o hi.exe hi.c C:\raylib\raylib\raylib.rc.o -s -O2 -std=c99 -Wall -lraylib -lopengl32 -lgdi32 -Iexternal -I../../src -L../../src -Wl,--subsystem,windows

**Comment by raysan5** [comment]
@liamkennedy89 It seems `C:\raylib\mingw\bin` is not properly set in the path, `gcc.exe` could require of other programs/libraries in the same folder that, depending the working directory where you launch GCC, those programs/libraries are not found.

Just make sure `C:\raylib\mingw\bin` is on the path.

**Comment by liamkennedy89** [comment]
Ah, I was hoping to not have to add mingw bin to my envrionment vars path as I don't have to do this for notepad++ to build raylib games

**Comment by monsterbrain** [comment]
I'm trying to run a sample code in VScode.

mingw32-make game
```
mingw32-make[1]: Entering directory 'C:/Users/fr-2097/Downloads/VSCode'
gcc -o game  -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Wl,--subsystem,windows -I. -IC:/raylib/raylib/release/include -IC:/raylib/raylib/src -IC:/raylib/raylib/src/external C:/raylib/raylib/raylib.rc.o -L. -LC:/raylib/raylib/release/libs/win32/mingw32 -LC:/raylib/raylib/src
-lraylib -lopengl32 -lgdi32 -DPLATFORM_DESKTOP
**gcc: fatal error: -fuse-linker-plugin, but liblto_plugin-0.dll not found**
```
compilation terminated.

This is running fine in Notepad++ though ...

**Comment by raysan5** [comment]
@monsterbrain This issue has already been tracked separately on https://github.com/raysan5/raylib/issues/691.

Just added Geany project template for Windows.

Closing this issue for now.
