### ISSUE TITLE
[build] CMake: install raylib-config.cmake

### ISSUE THREAD

**Issue by a3f** [raysan5/raylib#471]
We already install a `raylib.pc` file for pkg-config, but we probably should also install a `raylib-config.cmake`, so dependent CMake projects can use it.

Documentation: https://cmake.org/cmake/help/git-master/manual/cmake-packages.7.html#creating-packages

**Comment by raysan5** [comment]
Could it be `raylibConfig.cmake` for library naming consistency? Or the requirement for that kind of file is starting with capital letter?

**Comment by a3f** [comment]
It's a convention, but CMake also accepts `raylib-config.cmake`.

**Comment by raysan5** [comment]
ok, I prefer this option, I always name files in lower-case convention...

**Comment by a3f** [comment]
The `CMakeLists.txt` in `examples/` and `games/` have the `build/` directory hardcoded, which kinda defeats the purpose of doing out-of-tree builds. That should probably be fixed too...
The `link_libraries_to_executable` function in `cmake/utils.cmake` is a hack that should be got rid off as well.

**Comment by raysan5** [comment]
@a3f what's the state of this issue? could it be closed?

**Comment by a3f** [comment]
We don't yet provide a `raylib-config.cmake`. I think we should and I
suspect it can be used internally for the examples and games as well to
make our CMake setup easier to maintain (In particular, it would make the
`link_libraries_to_executable` hack in `cmake/utils.cmake` obsolete).

I would leave this issue open till someone implements it...
