### ISSUE TITLE
[build] Some build issues

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#476]
Hi,

I just updated C sources in raylib-go and am having some troubles with building:
```
# github.com/gen2brain/raylib-go/raylib
rlgl.c: In function ‘rlSetDebugMarker’:
rlgl.c:1327:5: warning: implicit declaration of function ‘glInsertEventMarkerEXT’ [-Wimplicit-function-declaration]
     if (debugMarkerSupported) glInsertEventMarkerEXT(0, text);
     ^
# github.com/gen2brain/raylib-go/raylib
/tmp/go-build618852479/github.com/gen2brain/raylib-go/raylib/_obj/rlgl.o: In function `rlSetDebugMarker':
raylib/rlgl.c:1327: undefined reference to `glInsertEventMarkerEXT'
collect2: error: ld returned 1 exit status
```

For now I just commented that line to be able to build, as I understand it is related to GPU debugging. It happens in both Linux and Windows (verified in travis and appveyor). I saw some commit for macOS, where `glext.h` is included but that didn't help in my case.

I am currently working on old laptop that only supports OpenGL 2.0, so I must build for opengl11, it fails to build with this error:
```
# github.com/gen2brain/raylib-go/raylib
/home/milann/golang/src/github.com/gen2brain/raylib-go/raylib/rlgl.c: In function 'rlLoadTexture':
/home/milann/golang/src/github.com/gen2brain/raylib-go/raylib/rlgl.c:1447:9: warning: implicit declaration of function 'GetGlFormats' [-Wimplicit-function-declaration]
         GetGlFormats(format, &glInternalFormat, &glFormat, &glType);
         ^
# github.com/gen2brain/raylib-go/raylib
/tmp/go-build936522564/github.com/gen2brain/raylib-go/raylib/_obj/rlgl.o: In function `rlLoadTexture':
/home/milann/golang/src/github.com/gen2brain/raylib-go/raylib/rlgl.c:1447: undefined reference to `GetGlFormats'
/tmp/go-build936522564/github.com/gen2brain/raylib-go/raylib/_obj/rlgl.o: In function `rlUpdateTexture':
/home/milann/golang/src/github.com/gen2brain/raylib-go/raylib/rlgl.c:1531: undefined reference to `GetGlFormats'
/tmp/go-build936522564/github.com/gen2brain/raylib-go/raylib/_obj/rlgl.o: In function `rlReadTexturePixels':
/home/milann/golang/src/github.com/gen2brain/raylib-go/raylib/rlgl.c:2163: undefined reference to `GetGlFormats'
collect2: error: ld returned 1 exit status
```

If I build for opengl22 or opengl33 then it builds, but of course it cannot InitWindow then.

**Comment by a3f** [comment]
CI here doesn't report any problems, could you check if you are missing any packages?

**Comment by gen2brain** [comment]
I didn't changed anything in travis/appveyor, raylib-go has simple rules there. As I understand no new deps are added recently, in Linux that could be related to mesa I guess, but it also failed in Windows.

Here are the build logs from history:
https://ci.appveyor.com/project/gen2brain/raylib-go/build/78
https://travis-ci.org/gen2brain/raylib-go/builds/344527178

**Comment by gen2brain** [comment]
Maybe you can also try to build in travis with GRAPHICS_API_OPENGL_11 (related to second error, GetGlFormats), I guess OPENGL_11 is usually not tested often.

**Comment by raysan5** [comment]
I'm with it, yes, it fails on `GRAPHICS_API_OPENGL_11` due to `GetGlFormats()` not exposed... commit coming in a minute.

About `glInsertEventMarkerEXT()` it was an addition from an external PR... I'm not a big fan of specific extensions...

**Comment by gen2brain** [comment]
I just grepped for glInsertEventMarkerExt in my includes, here are the results:
```
thinkpad /usr/include/GL # grep -R glInsertEventMarkerEXT
glext.h:GLAPI void APIENTRY glInsertEventMarkerEXT (GLsizei length, const GLchar *marker);
gl_mangle.h:#define glInsertEventMarkerEXT		MANGLE(InsertEventMarkerEXT)
glew.h:#define glInsertEventMarkerEXT GLEW_GET_FUN(__glewInsertEventMarkerEXT)
```

As I wrote, I tried to include glext.h in rlgl.c and it didn't help, maybe I didn't try at correct place.

**Comment by raysan5** [comment]
Compilation for OpenGL 1.1 reviewed on commit https://github.com/raysan5/raylib/commit/326fe09777b4b72358bad3e5ae272084bd1732a5

**Comment by raysan5** [comment]
About `glInsertEventMarkerEXT()`, what compiler and version are you using on Windows?

I can consider just removing that functionality from raylib...

**Comment by gen2brain** [comment]
Not sure about the version appveyor is using, it is i686-w64-mingw32-gcc from msys64. I just tried and I can build raylib on my laptop without that error, it fails only with raylib-go. Maybe I miss some recently added flag, will need to check that.

**Comment by gen2brain** [comment]
I missed to update `glad.h` in external, now everything builds fine.
