### ISSUE TITLE
[core] ShowCursor/HideCursor and Wayland

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#477]
Build for Wayland will fail currently because those functions call some X11 functions for cursor. As before I solved it with adding  `#if defined(__linux__) && defined(_GLFW_X11)`  here https://github.com/gen2brain/raylib-go/blob/master/raylib/core.c#L755 and here https://github.com/gen2brain/raylib-go/blob/master/raylib/core.c#L768 .

Is this still necessary, can glfw do that alone maybe, without those X function?

**Comment by raysan5** [comment]
Not sure if this is still required on latest GLFW, in the meantime, just added proposed correction in commit https://github.com/raysan5/raylib/commit/cd5e2e0f17f87fc7c5794327bba1b384758f4937

**Comment by raysan5** [comment]
Just updated GLFW in commit https://github.com/raysan5/raylib/commit/3b4a64f2d612c4ed6e04c8d18bd0f2dcf2a24ec1 and also removed possible useless code in commit https://github.com/raysan5/raylib/commit/85850a955a1c3d6e51f919385679ea9ba4d6a864

This needs to be tested.

**Comment by gen2brain** [comment]
I tested in X11 and ShowCursor/HideCursor works as expected.
