### ISSUE TITLE
[build] -fgnu89-inline 

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#478]
Go recently blacklisted all CFLAGS and now allows only flags that are whitelisted, see https://github.com/gen2brain/raylib-go/issues/32 . I did remove that flag and it does build without it, but I am not sure what are the consequences.

If this is a must I can probably open issue with them, to try to also whitelist `-fgnu89-inline`.

**Comment by raysan5** [comment]
Right now I can not remember what was the use for that flag... actually, I think it came from a PR from someone...

**Comment by gen2brain** [comment]
Ok, if it is not that important and it builds fine, I will just leave it removed then.

Thanks.

**Comment by a3f** [comment]
I think we should remove it in raylib too. It might lead to build errors down the road, as MSVC doesn't use the gnu89 inline definition. If we got any `extern inline`s, they should be replaced by plain `inline`s and vice versa.

**Comment by raysan5** [comment]
Flag removed in commit https://github.com/raysan5/raylib/commit/97bf2706c497f90ea4e3ead4e69819bc7a1f6083

**Comment by raysan5** [comment]
About `extern inline`, it's just used in [raymath.h](https://github.com/raysan5/raylib/blob/master/src/raymath.h). It should be reviewed just there...

**Comment by a3f** [comment]
The problem with `static inline` is possible duplication of out-of-line functions, so we want `raymath.h` to have inline definitions and one source file to have the only out of line definitions. With C99 inline semantics that means:

- `raymath.h` has plain `inline` definitions of the functions
- `core.c` or some other `.c` file has all prototypes with `extern` in front of them.

e.g.
`raymath.h`:
```
inline float Clamp(float value, float min, float max) 
{
    const float res = value < min ? min : value;
    return res > max ? max : res;
}
```
`core.c`:
```
#include <raymath.h>
extern float Clamp(float value, float min, float max);
```

**Comment by raysan5** [comment]
Closing this issue, just need to review raymath.h, already a PR waiting and a related issue (https://github.com/raysan5/raylib/issues/498)
