### ISSUE TITLE
Move `<raylib.h>` to `<raylib/raylib.h>`

### ISSUE THREAD

**Issue by a3f** [raysan5/raylib#481]
To have a place to install all the other headers too, like `raymath.h` and `raygui.h`.

**Comment by a3f** [comment]
For now we can still provide a `<raylib.h>` that just `#include <raylib/raylib.h>` if backwards compatibility is a concern (I would just get rid of it).

**Comment by RDR8** [comment]
I agree. We can use whatever name you like. I chose raysan5 because raylib is not raygui is not raylib-lua etc.

**Comment by raysan5** [comment]
I prefer to keep <raylib.h> only, the other libraries don't have to be raylib related.

**Comment by a3f** [comment]
I don't mind. But currently the Makefiles install to `<raysan5/raylib.h>`, so either Makefile or CMake needs to change.

**Comment by RDR8** [comment]
It's really just a convenience. I don't believe it's necessary but it simplifies uninstallation of the bundle of headers I'm throwing in. Once I repair the uninstall target, I won't be affected either way. Just seemed like a good idea at the time.

**Comment by a3f** [comment]
Do we need an uninstall target? Why doesn't the use just use checkinstall?

**Comment by a3f** [comment]
Point is, I think, if we have two build systems, programs should compile with each unmodified and this includes the same default installation paths and header locations for both.

**Comment by RDR8** [comment]
I don't know. It's a common .PHONY that provides a useful function? Unfamiliar with checkinstall.

> Point is, I think, if we have two build systems, programs should compile with each unmodified and this includes the same default installation paths and header locations for both.

How about `RAYLIB_INSTALL_PATH = /usr/local/lib` and `RAYLIB_H_INSTALL_PATH = /usr/local/include/raylib`? It's Ray's name so whatever he wants is great for me.

**Comment by raysan5** [comment]
Asked on the PR, agree with `RAYLIB_INSTALL_PATH = /usr/local/lib` 

About header, why not just using `RAYLIB_H_INSTALL_PATH = /usr/local/include`?

**Comment by a3f** [comment]
Example: User has system-provided raylib, e.g. `zypper install raylib`. User wants new shiny raylib, so they uses Makefile with DESTDIR to compile to a user-defined location. User wants to uninstall. uninstall target defaults to `/usr/local/lib` and deletes system raylib.

For an uninstall target, you need to keep a manifest with the files installed. checkinstall does that. make shouldn't IMHO.

**Comment by RDR8** [comment]
I can work with /usr/local/include. I got greedy with the source during the install target to enable the independent behavior described on the PR and needed to bundle everything for quick and dirty uninstall. Whatever convenience comes from have these related things compartmentalized is just a nice side effect.

The manifest is explicit in the target. It might be nice to abstract it out but that enhancement is a little beyond me right now.
