### ISSUE TITLE
core_basic_window.c doesn't work

### ISSUE THREAD

**Issue by DERPNYS** [raysan5/raylib#483]
Hello!
Today I tried to install raylib 1.8 but couldn't success. When I tried to compile and run an example, it showed me "Raylib.cbp has stopped working". So I tried to execute Raylib.exe and it said that "Couldn't exec because libgcc_s_dw2-1.dll is missing" and when I tried to download that DLL and put it in the same directory, it didn't work. 

Someone told me to try running "core_basic_window.c" in Notepad++ (the one installed with raylib 1.8) and when I try to execute it, it shows a "Run" window where I have to introduce the directory of a ".exe" file. I saw some videos on YouTube where people just tried to run this example and their "Run" window looked more like a compiler than mine. Also I couldn't find "raylib_compile_execute".

How can I solve this?

Thank you!

**Comment by raysan5** [comment]
It could happen that you have multiple versions of MinGW and/or Notepad++ installed. For example, if you installed Code:Blocks, it comes with its own MinGW version, that gets included in environment PATH.

My recommendation is to review if you have multiple MinGW/Notepad installations and then delete current C:\raylib directory and install it again.

**Comment by DERPNYS** [comment]
I removed the current version of MinGW that got installed with Code::Blocks and also removed the raylib folder. Then, Code::Blocks didn't detect me any compiler (that proves I didn't have any version of MinGW) and installed raylib again, giving the directory of the MinGW of raylib in Code::Blocks in Settings, Compiler. Although that, I'm still getting "Raylib.exe has stopped working". The code is alright and got no errors during the compilation but the problem comes when I try to run it.

**Comment by raysan5** [comment]
what is the graphic card you have on your computer? is it an old computer?

**Comment by DERPNYS** [comment]
Intel HD Graphics 4000 1536 MB. I'm using Windows 7 as a virtual machine (original system is macOS). 
<img width="404" alt="captura de pantalla 2018-02-28 a las 0 25 22" src="https://user-images.githubusercontent.com/36776985/36761105-e7122f68-1c1d-11e8-9e63-a7c7b3bac8b3.png">

**Comment by DERPNYS** [comment]
I could "kinda" make it. I installed the raylib 1.2.2 (since 1.3 didn't work for me) and in the notepad++ executed "raylib_compile_execute" and it worked. Everything okay. Now, when I try to compile any file on Code::Blocks I got this:

<img width="1144" alt="captura de pantalla 2018-03-02 a las 0 08 29" src="https://user-images.githubusercontent.com/36776985/36874872-e0d5f288-1dad-11e8-94a8-588b8c060417.png">

What can I do?

**Comment by raysan5** [comment]
ok, it seems it could be related to virtual machine/Windows 7 drivers not supporting latest OpenGL 3.3 implementation, raylib 1.2.2 was the last release to be compiled by default to use OpenGL 1.1, instead of OpenGL 3.3.

To try to solve that, install again latest raylib version and [follow these instructions](https://github.com/raysan5/raylib/wiki/FAQ#can-i-run-raylib-in-my-old-pc).

**Comment by a3f** [comment]
I'd like to note that raylib can run natively on macOS. It's even available over brew (`brew install --HEAD raylib`).

**Comment by DERPNYS** [comment]
I know but the compiler and the other libraries I'm using work better with Windows

**Comment by DERPNYS** [comment]
@raysan5 I followed your instructions and it worked on Notepad++ with OpenGL 1.1 but when I try to open my project on Code::Blocks (that worked on another computer with raylib) I still get those errors (https://user-images.githubusercontent.com/36776985/36874872-e0d5f288-1dad-11e8-94a8-588b8c060417.png)

**Comment by a3f** [comment]
If you comment out that line, does it work?

**Comment by DERPNYS** [comment]
@a3f nope. Tried to install newest version and to follow the instructions of raylib and as I coulnd't select OpenGL version in Raylib 1.8, I installed back again the 1.2.2 and configure it (with OpenGL 1.1) and now I get these errors in my project:
<img width="609" alt="captura de pantalla 2018-03-10 a las 0 18 38" src="https://user-images.githubusercontent.com/36776985/37234551-c1350f80-23f8-11e8-8b9b-fa1180ad25a7.png">

**Comment by a3f** [comment]
When you remove the enum bool definition line, do you get other errors? What do they say?

**Comment by DERPNYS** [comment]
@a3f Tbh I got the same error in the same line. That's one of the weirdest things I've seen. And if I leave some blank lines (for example, moving that line in 182 leaving 181 blank) it still notices me an error in the line 181.

**Comment by a3f** [comment]
Save raylib.h and restart Code::Blocks?

**Comment by DERPNYS** [comment]
@a3f Did it and got again those errors:

> 
![image](https://user-images.githubusercontent.com/36776985/37234776-202dc6fc-23fa-11e8-9687-c2c7a9eff2d9.png)


>

**Comment by a3f** [comment]
In order to build libraylib.dll, you need to link against `opengl32` and `gdi32`. See https://stackoverflow.com/questions/5862757/how-do-i-link-to-a-library-with-codeblocks for more information.

You don't have to build raylib though. You could just use a binary release (like the one included with the Notepad++ setup) and add that as library to your game project.

**Comment by DERPNYS** [comment]
@a3f You're probably god in the earth. Haha thank you! It's already solved that! I linked opengl32 and gdi32 as you said and now it works great! Thank you so much, really apreciate! And thanks to @raysan5 too!

**Comment by a3f** [comment]
Have fun! :)
