### ISSUE TITLE
Dual inclusion of raylib.h

### ISSUE THREAD

**Issue by RDR8** [raysan5/raylib#484]
This isn't necessarily an issue. I just wanted to summarize a couple of things here. 

Currently there are two versions of raylib.h available to the examples at compile time. The older version is found at `release/include/raylib.h` alongside `release/libs/linux/libraylib.a` . I believe the purpose of these and some other object files is to enable immediate interaction with the examples _without_ building libraylib locally. Additionally, a more current version is available at `src/raylib.h`. This is the one that is built against when making raylib. The difference is in the definition of `GenImagePerlinNoise`. The actual function isn't relevant here, and with proper use, this isn't a serious problem. It's actually useful for inspecting the inner workings of the toolchain.

The problems occurring with `RAYLIB_LIBTYPE=SHARED` have, I think, been sorted out in #480 by addressing the precedence of `INCLUDE_PATHS` components within `examples/Makefile`.

On the `RAYLIB_LIBTYPE=STATIC` side, there is still one case where it is problem. If someone fails to `src/$ make clean` the provided `release/libs/linux/libraylib.a` before `src/$ make`, libraylib.a will compile but the conflict of objects/headers? throws an immediate error on `GenImagePerlinNoise` in the same `examples/textures/textures_image_generation` compilation step that was showing the precedence issue with `RAYLIB_LIBTYPE=SHARED` in `examples/Makefile`. The easiest solution is to just tell everyone `make clean` up front. There is now a visual message suggesting to do so during plain ole `src/$ make`, also in PR480.

I'm not suggesting that the files should match. I'm sure there are good reasons for having a seperate release/ "package" and I would not have been able to diagnose these issues without the errors exposed here. Anyway, just pointing this out because I love to read my own stuff. ;^)

**Comment by raysan5** [comment]
I need to update `release/` libs at some point, now that we only have a single `master` branch they should be latest stable version all the time...

**Comment by RDR8** [comment]
If it's just a matter of copying src/raylib.h to release/include/raylib.h and rebuilding libraylib.a, I can put it in #480.
