### ISSUE TITLE
[raymath] API inconsistencies

### ISSUE THREAD

**Issue by egonelbre** [raysan5/raylib#498]
Currently there are few functions in raymath that look inconsistent with the rest of the API. Most of the API is built around the idea of returning a new Vector, Matrix or Quaternion. However some of the functions modify the input instead.

I'm aware that I could write my own functions to do that, but thought maybe some other people are affected as well. Similarly, not sure whether this improvement is worth breaking the API.

An example _(Note: [original code](https://github.com/egonelbre/hexapod/blob/master/cmd/hexapod-simulator/robot.go#L317) was using raylib-go, so sorry for any C errors)_:

```c
auto hingePointMin = (Vector3){20, 0, 0};
auto hingePointZero = (Vector3){20, 0, 0};
auto hingePointMax = (Vector3){20, 0, 0};

Vector3Transform(&hingePointMin, MatrixMultiply(transform, MatrixRotateZ(hinge->Zero+hinge->Range.Min)));
Vector3Transform(&hingePointZero, MatrixMultiply(transform, MatrixRotateZ(hinge->Zero)));
Vector3Transform(&hingePointMax, MatrixMultiply(transform, MatrixRotateZ(hinge->Zero+hinge->Range.Max)));

DrawLine3D(hingeCenter, hingePointMin, Red);
DrawLine3D(hingeCenter, hingePointZero, Green);
DrawLine3D(hingeCenter, hingePointMax, Blue);
```

Which could be:

```c
DrawLine3D(hingeCenter, 
	Vector3Transform((Vector3){20, 0, 0},
		MatrixMultiply(transform, MatrixRotateZ(hinge->Zero+hinge->Range.Min))), 
	Red);
DrawLine3D(hingeCenter, 
	Vector3Transform((Vector3){20, 0, 0},
		MatrixMultiply(transform, MatrixRotateZ(hinge->Zero+hinge->Range.Center))), 
	Green);
DrawLine3D(hingeCenter, 
	Vector3Transform((Vector3){20, 0, 0},
		MatrixMultiply(transform, MatrixRotateZ(hinge->Zero+hinge->Range.Max))), 
	Blue);
```

Specific functions that look like that in raymath:

```c
RMDEF void Vector2Scale(Vector2 *v, float scale);
RMDEF void Vector2Negate(Vector2 *v);
RMDEF void Vector2Divide(Vector2 *v, float div);
RMDEF void Vector2Normalize(Vector2 *v);

RMDEF void Vector3Scale(Vector3 *v, float scale);
RMDEF void Vector3Negate(Vector3 *v);
RMDEF void Vector3Normalize(Vector3 *v);
RMDEF void Vector3Transform(Vector3 *v, Matrix mat);

RMDEF void MatrixTranspose(Matrix *mat);
RMDEF void MatrixInvert(Matrix *mat);
RMDEF void MatrixNormalize(Matrix *mat);

RMDEF void QuaternionNormalize(Quaternion *q);
RMDEF void QuaternionInvert(Quaternion *quat);
RMDEF void QuaternionTransform(Quaternion *q, Matrix mat);
```

There of course are few functions that have multiple out parameters, so not sure what to do about those.

**Comment by raysan5** [comment]
Hi @egonelbre! Thanks for the review!

I defined some functions that way for convenience but I agree it breaks consistency with other functions. It also requires some changes all around the code... 

raymath is [already being reviewed](https://github.com/raysan5/raylib/pull/482)... Maybe it's a good time to change that for the upcoming raylib v2.0?

@a3f, what do you think?

**Comment by a3f** [comment]
> Maybe it's a good time to change that for the upcoming raylib v2.0?

I agree.

**Comment by raysan5** [comment]
Complete review of raymath implemented in commit https://github.com/raysan5/raylib/commit/61e0e4b4f37cc66135445bc87af7c92399fa69ee

It could possible break some examples... need to review that.

**Comment by egonelbre** [comment]
I took a quick skim... and is keeping the statements on multiple lines intentional?

For example:

```
// 1.
result.normal = Vector3CrossProduct(edge1, edge2);
result.normal = Vector3Normalize(result.normal); 

// 2.
Vector3 axis = (Vector3){ x, y, z };
axis = Vector3Normalize(axis);
matRotation = MatrixRotate(axis, angleDeg*DEG2RAD);
```

Instead of:

```
// 1.
result.normal = Vector3Normalize(Vector3CrossProduct(edge1, edge2));

// 2.1
Vector3 axis = Vector3Normalize((Vector3){ x, y, z });
matRotation = MatrixRotate(axis, angleDeg*DEG2RAD);

// 2.2
matRotation = MatrixRotate(
	Vector3Normalize((Vector3){ x, y, z }),
	angleDeg*DEG2RAD);
```

**Comment by raysan5** [comment]
> is keeping the statements on multiple lines intentional?

No, just the result of a quick editing... your approximation looks better!

**Comment by raysan5** [comment]
Reviewed in commit https://github.com/raysan5/raylib/commit/375adf86a61be8f3b23c253672dfd3c8df805784
