### ISSUE TITLE
[core] File extension case sensitivity

### ISSUE THREAD

**Issue by TakoNekko** [raysan5/raylib#499]
On Windows file systems, file names are usually treated as case-insensitive. `IsFileExtension` could use `stricmp` instead of `strcmp` in the Windows build. Although, I think this function, like Unix's `strcasecmp`, may be non-standard and/or non-portable.

**Comment by a3f** [comment]
Sounds good to me. Would you like to submit a pull request for it? (add a `static my_stricmp(const char *, const char*)` and adjust `IsFileExtension` to use it. You may think of a better name than `my_stricmp`...).

**Comment by raysan5** [comment]
I prefer to include all the required code in the same function, I try to avoid any additional function if possible.

**Comment by TakoNekko** [comment]
I was pointing at this function particularly, but any file name (i.e., title and extension) comparison on Windows should be case insensitive.

Anyway, this is quite ugly but you could try this...

```
bool IsFileExtension(const char *fileName, const char *ext)
{
    bool result = false;
    const char *fileExt;
    
    if ((fileExt = strrchr(fileName, '.')) != NULL)
    {
    #if defined(_WIN32)
        const int fileExtLen = MultiByteToWideChar (CP_UTF8, MB_ERR_INVALID_CHARS, fileExt, -1, NULL, 0);
        const int extLen = MultiByteToWideChar (CP_UTF8, MB_ERR_INVALID_CHARS, ext, -1, NULL, 0);
		
        if (fileExtLen == 0 || extLen == 0)
        {
            goto fallback;
        }
		
        wchar_t *fileExtW = (wchar_t*)malloc(fileExtLen * sizeof(wchar_t));
        wchar_t *extW = (wchar_t*)malloc(extLen * sizeof(wchar_t));
		
        if (fileExtW == NULL || extW == NULL)
        {
            if (fileExtW != NULL) free (fileExtW);
            if (extW != NULL) free (extW);
			
            goto fallback;
        }
		
        MultiByteToWideChar (CP_UTF8, MB_ERR_INVALID_CHARS, fileExt, -1, fileExtW, fileExtLen);
        MultiByteToWideChar (CP_UTF8, MB_ERR_INVALID_CHARS, ext, -1, extW, extLen);

        if (lstrcmpi(fileExtW, extW) == 0) result = true;
		
        free (fileExtW);
        free (extW);
		
        return result;
    fallback:
    #endif
        if (strcmp(fileExt, ext) == 0) result = true;
    }

    return result;
}
```

**Comment by a3f** [comment]
@TakoNekko If we do this, I think it should behave the same on all platforms for consistency. Also why not compare the UTF-8 strings directly, without UTF-16 conversion?
@raysan5 I believe it can be useful elsewhere, so makes sense to have it as separate function.

**Comment by TakoNekko** [comment]
@a3f The macro `lstrcmpi` expands to `lstrcmpiW` if the preprocessor definition `UNICODE` is defined, and to `lstrcmpiW` otherwise. `lstrcmpiA` works with narrow strings (ANSI, not UTF-8), while `lstrcmpiW` works with wide strings (UTF-16).

`lstrcmpiA` can be used directly if support for international languages in file names is not a requirement.

```
bool IsFileExtension(const char *fileName, const char *ext)
{
    bool result = false;
    const char *fileExt;
    
    if ((fileExt = strrchr(fileName, '.')) != NULL)
    {
    #if defined(_WIN32)
        #if defined(UNICODE)
            const int fileExtLen = MultiByteToWideChar (CP_UTF8, MB_ERR_INVALID_CHARS, fileExt, -1, NULL, 0);
            const int extLen = MultiByteToWideChar (CP_UTF8, MB_ERR_INVALID_CHARS, ext, -1, NULL, 0);

            if (fileExtLen == 0 || extLen == 0)
            {
                goto fallback;
            }

            wchar_t *fileExtW = (wchar_t*)malloc(fileExtLen * sizeof(wchar_t));
            wchar_t *extW = (wchar_t*)malloc(extLen * sizeof(wchar_t));

            if (fileExtW == NULL || extW == NULL)
            {
                if (fileExtW != NULL) free (fileExtW);
                if (extW != NULL) free (extW);

                goto fallback;
            }

            MultiByteToWideChar (CP_UTF8, MB_ERR_INVALID_CHARS, fileExt, -1, fileExtW, fileExtLen);
            MultiByteToWideChar (CP_UTF8, MB_ERR_INVALID_CHARS, ext, -1, extW, extLen);

            if (lstrcmpiW(fileExtW, extW) == 0) result = true;

            free (fileExtW);
            free (extW);

            return result;
        fallback:
        #else
            if (lstrcmpiA(fileExt, ext) == 0) result = true;
        #endif
    #endif
        if (strcmp(fileExt, ext) == 0) result = true;
    }

    return result;
}
```

**Comment by raysan5** [comment]
Wow... what a piece of code... do we really need to consider UTF8?

I always try to keep things as simple as posible, despite losing some functionality or performance... I mean, I understand we are supposed to consider all possible situations and try to preview user missuses... but I'd go for a simpler solution to this specific case:

```c
    if ((fileExt = strrchr(fileName, '.')) != NULL)
    {
        result = true;
        int extLen = strlen(ext);
        for (int i = 0; i < extLen; i++)
        {
            if (fileExt[i] != tolower(ext[i]))
            {
                result = false;
                break;
            }
        }
    }
```

**Comment by TakoNekko** [comment]
I think this is good enough for comparing file extensions since they're usually made of 0-9 digits and a-z letters!

Should there be a length comparison as well? (i.e., `if (strlen (fileExt) == extLen)`), otherwise `"name.mdl"` will match `".md"`, for example.

**Comment by raysan5** [comment]
Hey @TakoNekko! Good catch! I'll update it asap!

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/raylib/commit/9318dc98ce647acd9a718243555996618e95b959
