### ISSUE TITLE
It looks like there is a typo in shader location point type

### ISSUE THREAD

**Issue by MrOneTwo** [raysan5/raylib#501]
Shouldn't it be *LOC_MAP_OCCLUSION* (typos in rlgl.h and raylib.h)?

https://github.com/raysan5/raylib/blob/df50eada531b54d6771eff81cbe140f9453d54d9/src/rlgl.h#L324

https://github.com/raysan5/raylib/blob/df50eada531b54d6771eff81cbe140f9453d54d9/src/raylib.h#L564

**Comment by victorfisac** [comment]
@MrOneTwo yes...

![giphy](https://user-images.githubusercontent.com/10688349/37251799-f2fdb3cc-2516-11e8-861a-379d4f938850.gif)

**Comment by raysan5** [comment]
Ouch... corrected in commit https://github.com/raysan5/raylib/commit/a0127d83002c2462bc4e83715c1dcb0bf99796ca :P

**Comment by MrOneTwo** [comment]
Aaaaaaand you just broke the pbr example :D 

https://github.com/raysan5/raylib/blob/8bc2813b0cbb016206708c41762a2fe3f01d5a13/examples/models/models_material_pbr.c#L116

**Comment by raysan5** [comment]
hahahaha... ok... corrected in commit https://github.com/raysan5/raylib/commit/d6c1159fce69c556fefebb945fd857b3c761bfab
