### ISSUE TITLE
[models] 3d Model (obj) in RPI not draw!

### ISSUE THREAD

**Issue by dginu85** [raysan5/raylib#502]
Hello,
In RPI Draw 3D model WORK?
I try load 3D model, draw only grid and gizmo.

```
InitWindow(screenWidth,screenHeight ,"test");

	SetTargetFPS(60);

	Camera camera = { { 3.0f, 3.0f, 3.0f }, { 0.0f, 1.5f, 0.0f }, { 0.0f, 1.0f, 0.0f }, 45.0f };
	Model dwarf = LoadModel("assets/modelli/auto.obj");             
	Texture2D texture = LoadTexture("assets/modelli/auto.png");  
	dwarf.material.maps[MAP_DIFFUSE].texture = texture;
	Vector3 position = { 0.0f, 0.0f, 0.0f }; 
	
	for (;;) {
		BeginDrawing();
		ClearBackground(RAYWHITE);
		Begin3dMode(camera);
		DrawModel(dwarf, position, 2.0f, WHITE);
		DrawGrid(10, 1.0f); 
		DrawGizmo(position); 
		End3dMode();
		
		EndDrawing();

		
	}
```

**Comment by raysan5** [comment]
Actually, it should work ok...

What version of RPI are you using? 
Working on desktop or native mode? 
What version of raylib? Using latest master branch? 

I think I solved that issue on RPI I while ago... I remember it was related with Raspbian Stretch, latest OpenGL driver and a lack of location points initialization in raylib... it was corrected.

**Comment by dginu85** [comment]
I use RPI3 in frame buffer
use latest master branch and work fine.
only 3D model not draw...
the grid and box draw
![snapshot](https://user-images.githubusercontent.com/4887152/37314240-568f5ca0-2653-11e8-90f4-48e55563e3b8.png)

**Comment by dginu85** [comment]
in raspbian (minibian) all updated...
not work, i have same problem.
![snapshot](https://user-images.githubusercontent.com/4887152/37316354-d0041304-265e-11e8-9e9a-04325a4aa395.png)

**Comment by dginu85** [comment]
I do not know if this is a problem. If it does not find the file it does not draw the rest in 3D mode.
![snapshot](https://user-images.githubusercontent.com/4887152/37316448-6fe42e54-265f-11e8-8777-e267a92f9f6d.png)

**Comment by raysan5** [comment]
Most probably related to shader locations on model drawing, need to review it.

**Comment by dginu85** [comment]
are you referring to the complete disappearance of the 3D level? or to the model.

**Comment by dginu85** [comment]
Anyway, I could not make the model draw, do you have a solution for me?

**Comment by raysan5** [comment]
Just tried latest raylib version on Raspberry Pi 3, Raspbian Stretch, native mode, and it works ok.
