### ISSUE TITLE
[build] Add Travis CI Android Build

### ISSUE THREAD

**Issue by a3f** [raysan5/raylib#507]
I haven't written Android apps before, so would be nice if someone would volunteer for this. I can assist. :)
We use CMake for building on CI. I am not sure if our CMake setup supports Android, so that might need some work too.

Resources: https://github.com/raysan5/raylib/wiki/Compile-for-Android

**Comment by raysan5** [comment]
Current [raylib src Makefile](https://github.com/raysan5/raylib/blob/master/src/Makefile) can easily build raylib for Android just passing `PLATFORM_ANDROID`, but Android NDK toolchain [must be available](https://github.com/raysan5/raylib/blob/master/src/Makefile#L163).

Main issue with Android building comes when trying to generate the APK, just setup my own pipeline based in a [plain Makefile](https://github.com/raysan5/raylib/blob/master/templates/advance_game/Makefile.Android). If `PLATFORM_ANDROID` #ifdefinifion is removed from examples, then I could setup Android APK building for examples... it would be amazing.

**Comment by a3f** [comment]
> move emscripten logic inside raylib

This should be possible, if there is a way to explicitly yield control back to the emscripten "runtime", e.g. an `emscripten_yield_till_next_frame`. If there is, we could call it in `EndDrawing` instead of waiting till frame time elapses. Do you know any (preferably, graphic) programs that don't use `emscripten_set_main_loop`, which one could study?

**Comment by raysan5** [comment]
@gen2brain you're right! just saw it some days ago, but it seems interpreted code is way more slow, it needs to be tested...

**Comment by raysan5** [comment]
@a3f Android NDK r17 has just [been released](https://developer.android.com/ndk/downloads/), I'm preparing an standalone toolchain to use with raylib, I'm using Windows 32bit version, could it be used on Travis CI? Or does it require a Linux-based standalone toolchain?

**Comment by raysan5** [comment]
Updated Android build pipeline (Makefile) for ARM64 (now it's default) and API level 21 (minimum required for ARM64). Also using Clang and standalone toolchain. Changes implemented in commit https://github.com/raysan5/raylib/commit/fb4265f64659a50a5a86f9f283e7468b7998c60f

When trying to compile shared library, I got the following error:
```
C:/android_toolchain_arm64_api21/bin/aarch64-linux-android-clang -shared -o ../release/libs/android/arm64-v8a/libraylib.2.0.0.so core.o rlgl.o shapes.o textures.o text.o models.o utils.o audio.o stb_vorbis.o mini_al.o -Wl,-soname,libraylib..so -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -u ANativeActivity_onCreate -L. -Lsrc -L../release/libs/android/arm64-v8a -llog -landroid -lEGL -lGLESv2 -lOpenSLES -latomic -lc -lm
core.o: In function `android_main':
core.c:(.text.android_main+0x4c): undefined reference to `main'
clang60.exe: error: linker command failed with exit code 1 (use -v to see invocation)
```

Updated Android standalone toolchain for ARM64 and API21 with CLang using Android NDK r17 attached to [release 2.0.0-rc1](https://github.com/raysan5/raylib/releases/tag/2.0.0-rc1) (I know, not the best place, just a quick solution to share it).

**Comment by a3f** [comment]
> undefined reference to `main'
Adding `LDFLAGS=-Wl,--unresolved-symbols=ignore-in-shared-libs` should solve this

I will look into adding an Android build configuration.

**Comment by raysan5** [comment]
Solved with `LDFLAGS += -Wl,-undefined,dynamic_lookup`, testing 64bit arm building (it becomes mandatory for Android apps on 2019).

**Comment by a3f** [comment]
> LDFLAGS += -Wl,-undefined,dynamic_lookup

Removing `-Wl,--no-undefined` would suffice as well.

**Comment by a3f** [comment]
Travis CI seems to start 4 jobs in parallel, but AppVeyor runs them serially, thus when given the choice, testing in Travis CI seems the better choice, so I added a new Android AArch64 target there.

**Comment by raysan5** [comment]
Hi @a3f! Thanks for your work on this issue!

I'm testing it on Android device and despite building correctly, the APK doesn't seem to work on my phone, it shows an arquitecture missmatch issue (I'll post it later). I verified my Android phone CPU and it's an arm64-v8a. I keep working on it.
