### ISSUE TITLE
[build] Linking glfw3 Fails in Arch Linux

### ISSUE THREAD

**Issue by CaptainKraft** [raysan5/raylib#512]
I had to change `-lglfw3` to `-lglfw` in the Makefile that is in the games directory in order to build the example games.

**Comment by raysan5** [comment]
Actually, linking with GLFW is not required any more, in current raylib version (master branch) GLFW is embbedded in raylib as an additional module. You can remove linkage with this library as well as any OpenAL linkage reference.

**Comment by CaptainKraft** [comment]
Either way, I have to manually edit the Makefile so that it will build. Will the linking to GLFW in the Makefile be removed in subsequent releases?

**Comment by raysan5** [comment]
> Will the linking to GLFW in the Makefile be removed in subsequent releases?

That's the idea.

**Comment by raysan5** [comment]
Updated Makefiles on commit https://github.com/raysan5/raylib/commit/322cebcbaffca15f5a9117127c51ae47ba00a249.
