### ISSUE TITLE
[core] Inconsistency in naming 3D/2D vs 3d/2d

### ISSUE THREAD

**Issue by autious** [raysan5/raylib#515]
There is some irregularity in the naming of some functions regarding the capitalization in 3D and 2D.

DrawLine3D()
DrawCircle3D()
Begin3dMode()
Begin2dMode()
End3dMode()
End2dMode()

Additionally there is the Texture2D and Camera2D structs.

I would suggest making them all upper case.

Usually i wouldn't make a point out of it (because it's of very little consequence) but considering that the next major update will be breaking the API/ABI it might be a good time to bring it up. It would also make memorizing the API marginally easier.

**Comment by raysan5** [comment]
Just thinking about naming again... maybe I should replace those `Begin*() / End*()`functions by:
```c
void BeginCamera3D(Camera camera);
void EndCamera3D(void);
void BeginCamera2D(Camera2D camera);
void EndCamera2D(void);
```
What do you think?

**Comment by autious** [comment]
It's hard to say, i think mode might be clearer, as it implies something greater than just a camera.

It's not obvious to a beginner that a rendering stack would necessitate a camera before geometry, but mode might be "big" and abstract enough.

I'm not sure i'm the right person to evaluate this, as i'm already damaged from years of graphics programming.

**Comment by raysan5** [comment]
Keep thinking in the best way to address this inconsistency...

First of all, `Camera` type should be renamed to `Camera3D` for consistency.

And not sure about `BeginMode*()`:
```c
void BeginMode3D(Camera3D camera);
void EndMode3D(void);
void BeginMode2D(Camera2D camera);
void EndMode2D(void);
```
or
```c
void BeginCamera3D(Camera3D camera);
void EndCamera3D(void);
void BeginCamera2D(Camera2D camera);
void EndCamera2D(void);
```
Agree that `Mode` implies something greater... but we're just changing `Camera` related transformations. I'll ask students for their opinion, let's see what is clearer for them...

Any opinion on this topic is welcome, that's a breaking change!

Also thinking about renaming `SpriteFont` type (XNA) to simply `Font` (Unity), what do you think?

**Comment by autious** [comment]
If the "Begin" indeed only really means pushing the camera transformations to some kind of stack or state, then changing the name to Camera would make sense. But then you're potentially limiting the meaning in future development.

From a users perspective i feel that BeginDraw3D() might be semantically closer to what the user is trying to achieve with the function call.

Simplifying SpriteFont to Font could also make sense, unless there are any plans of using the specificity by adding another type of Font object, which i suspect isn't the case. But it could also just be a case of unnecessary change, i don't see it fixing debt, adding value of fixing a problem. In practice it'll only slightly add to the labour of fixing documentation and porting existing projects.

**Comment by raysan5** [comment]
Naming updated in commit https://github.com/raysan5/raylib/commit/6045062a05a0cc5bd654ad2c2e7d88f94579cd73

- Renamed Begin3dMode() --> BeginMode3D()
- Renamed Begin2dMode() --> BeginMode2D()
- Renamed End3dMode() --> EndMode3D()
- Renamed End2dMode() --> EndMode2D()

I decided that naming because is the closest to actual implementation.
