### ISSUE TITLE
[3d math] rlVertex and useTempBuffer

### ISSUE THREAD

**Issue by questor** [raysan5/raylib#519]
Hi,
what is the rational to use "useTempBuffer" in rlVertex3f and rlEnd? The way it's currently implemented the behavior is rather unexpected, it's ignoring my custom set model-matrix when I use it in the following way:
rlBegin
loop(100 times):
------rlPushMatrix (in ModelViewMode)
------rlTranslate(...)
------rlVertex3f(here the vertex is only recorded into an extra buffer)
------rlPopMatrix
rlEnd (here the current matrix-stack element is used which is not what is intended by ignoring the extra translate matrix)

workaround would be to move rlBegin and rlEnd into the loop, but why is not the current matrix used directly in the rlVertex3f call in the first place?

**Comment by questor** [comment]
never mind, workaround works. it's only a bit misleading that your opengl-wrapper does not work the way opengl1 was working. If you're learning it's okay, but if you are used to the old opengl behavior your sometimes surprised how your wrapper handles some things....

**Comment by raysan5** [comment]
Hey @questor, rlgl is not directly mapped to OpenGL in usage terms, when I designed it I tried to do it the more intuitive as possible for students but probably some decisions taken at that time (4 years ago) were not the best ones.

**Comment by questor** [comment]
sorry, didn't want to sound harsh, but I've found that you had compile-switches for ogl1.1 and ogl4 and assumed the ogl4-emulation tries to be an accurate emulation of the ogl1.1 which it is not. and hence the confusion :)
