### ISSUE TITLE
[core] Don't quit on escape key press

### ISSUE THREAD

**Issue by Lisoph** [raysan5/raylib#520]
Currently the Escape key is being eaten by raylib's keyboard input handling. Raylib doesn't pass the key on to user code and always (hardcoded) quit's the main loop when the key was pressed. [Source](https://github.com/raysan5/raylib/blob/fe1c04d1b8732dcf461ad2c62d2fcc61fe5b149c/src/core.c#L2772).

This is bad because it renders the escape key completely inaccessible for games written with raylib. Usability for things like menus suffers.

I believe eating the escape key should be an opt-in, specified via a new config flag (`FLAG_ESCAPE_QUIT`).

Thoughts?

**Comment by raysan5** [comment]
This issue was addressed with the addition of:
```c
void SetExitKey(int key);                               // Set a custom key to exit program (default is ESC)
```

**Comment by TheLumaio** [comment]
As an addition to this, I think there should be an option to disable the screenshot key without having to edit raylib every update to remove it manually.

**Comment by Lisoph** [comment]
> `void SetExitKey(int key);`

Ah thanks. I was already suspicious such a function would exist, due to the existence of the `exitKey` variable, but I missed it.

> As an addition to this, I think there should be an option to disable the screenshot key without having to edit raylib every update to remove it manually.

I agree.

**Comment by raysan5** [comment]
Actually, I like the screenshot feature... do you mean just set the desired key like exitKey?

Automatic GIF recording (yes, that option exists, CTRL+F12), could be disabled recompiling the library without a specific FLAG ([SUPPORT_GIF_RECORDING](https://github.com/raysan5/raylib/blob/master/src/core.c#L53)), maybe something similar for screenshots will be ok?

**Comment by raysan5** [comment]
`SUPPORT_SCREEN_CAPTURE` implemented in commit https://github.com/raysan5/raylib/commit/ca5f7ebd102656f8451a4cf99638bb94c9d00264

**Comment by dbechrd** [comment]
There doesn't seem to be a way to disable the exit key entirely. There should be a KEY_NONE enum to completely disable this feature.

I want to have Escape be a modal key. I.e. when in-game chat or inventory is open, Escape should close the chat/inventory. If in-game chat isn't open, Escape closes the window. There's no way to do this if Raylib internally does key processing before it gets to my app. :(

**Comment by raysan5** [comment]
@dbechrd `SetExitKey(0)` should work.

**Comment by dbechrd** [comment]
> @dbechrd `SetExitKey(0)` should work.

I assumed the enum started at 0 and that would be the same as `KEY_APOSTROPHE`, but I see now that’s not the case! Will try this tomorrow thanks. 🙏🏼

**Comment by chriscamacho** [comment]
so did I I think at one point I've even used 

    #define KEY_INVALID 163

which also works for camera keys...

**Comment by chriscamacho** [comment]
@raysan5 might it be worth adding 

    #define KEY_INVALID 0 

to raylib ?

**Comment by dbechrd** [comment]
IMO, `KEY_NONE` (or “empty” or “null”) is more semantically correct in this case since we’re intentionally saying “unbind this event” rather than “invalid key code”.

**Comment by raysan5** [comment]
@dbechrd @chriscamacho Actually, following standard ASCII code names / Unicode, it should be `KEY_NULL`. Just added it.

**Comment by EduardoLemos567** [comment]
Since searching for reason brought me here, not sure if its intended, but it only works if SetExitKey is called after InitWindow (just tested on C# version). 
I was putting before InitWindow, like SetTraceLogCallback, but actually only works if called after InitWindow.
