### ISSUE TITLE
[core] GetFrameTime() makes big jump at second call

### ISSUE THREAD

**Issue by srseil** [raysan5/raylib#523]
The first time I call `GetFrameTime()` the result is 0. The second time the result makes a big jump of up to a second. After the second call, the delta times are correct again.

I checked the timings against `gettimeofday()`. The left value is from `GetFrameTime()` and the right value in parentheses is calculated from `gettimeofday()`:

```
0.000000 (0.000002000)
1.019494 (0.005463000)
0.016669 (0.016669001)
0.016670 (0.016669001)
0.016669 (0.016669001)
0.016670 (0.016670000)
0.016669 (0.016667999)
0.016669 (0.016671000)
0.016669 (0.016669001)
0.016669 (0.016669001)
```

I am not sure where `GetFrameTime()` starts to count, but as the result of the first call to it always seems to be 0, I assume that it only starts counting from the first call onwards.

**Comment by raysan5** [comment]
First frameTime measure is taken at the end of first frame, when `EndDrawing()` is called, previously it's 0. That's the expected behaviour. Just in case, I reseted initial values for involved variables in commit https://github.com/raysan5/raylib/commit/54e24d905aabd0d084a924b66b8437428e436bf2

**Comment by srseil** [comment]
I see, thank you for the clarification.

The problem I face is that the game makes a skip of about half a second when I run it. That means what I am being shown essentially starts at 0.5 seconds in and not from the very beginning. With a finished game this doesn't matter much to me, since I will never be put straight into the gameplay, but for testing it is a bit annoying because I am constantly missing the first 30 frames or so.

To circumvent this I would have to initialize the timer myself just before the start of my game loop (I saw that this is currently being done in `InitWindow()`). Or I simply make my own timer.
