### ISSUE TITLE
[build] Raspberry Pi build fails: "undefined reference to `IsFileDropped'/`GetDroppedFiles'/`ClearDroppedFiles'"

### ISSUE THREAD

**Issue by PaulSlocum** [raysan5/raylib#526]
Here's the command line session:

**pi@raspberrypi:/clocks $ git clone https://github.com/raysan5/raylib.git**
Cloning into 'raylib'...
remote: Counting objects: 13665, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13665 (delta 3), reused 7 (delta 3), pack-reused 13651
Receiving objects: 100% (13665/13665), 220.22 MiB | 7.55 MiB/s, done.
Resolving deltas: 100% (9365/9365), done.
Checking connectivity... done.
Checking out files: 100% (770/770), done.
**pi@raspberrypi:/clocks $  sudo apt-get install libopenal1 libopenal-dev**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenal-dev is already the newest version.
libopenal1 is already the newest version.
libopenal1 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 110 not upgraded.
**pi@raspberrypi:/clocks $ cd raylib/
pi@raspberrypi:/clocks/raylib $ cd examples/
pi@raspberrypi:/clocks/raylib/examples $ make PLATFORM=PLATFORM_RPI**
gcc -o core/core_basic_window core/core_basic_window.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -std=gnu99 -I. -I../release/include -I../src -I../src/external -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/libs/rpi -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
gcc -o core/core_input_keys core/core_input_keys.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -std=gnu99 -I. -I../release/include -I../src -I../src/external -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/libs/rpi -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
gcc -o core/core_input_mouse core/core_input_mouse.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -std=gnu99 -I. -I../release/include -I../src -I../src/external -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/libs/rpi -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
gcc -o core/core_mouse_wheel core/core_mouse_wheel.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -std=gnu99 -I. -I../release/include -I../src -I../src/external -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/libs/rpi -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
gcc -o core/core_input_gamepad core/core_input_gamepad.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -std=gnu99 -I. -I../release/include -I../src -I../src/external -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/libs/rpi -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
gcc -o core/core_random_values core/core_random_values.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -std=gnu99 -I. -I../release/include -I../src -I../src/external -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/libs/rpi -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
gcc -o core/core_color_select core/core_color_select.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -std=gnu99 -I. -I../release/include -I../src -I../src/external -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/libs/rpi -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
gcc -o core/core_drop_files core/core_drop_files.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -std=gnu99 -I. -I../release/include -I../src -I../src/external -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -L. -L../release/libs/rpi -L../src -L/opt/vc/lib -lraylib -lbrcmGLESv2 -lbrcmEGL -lpthread -lrt -lm -lbcm_host -ldl -DPLATFORM_RPI
/tmp/ccMdWg4P.o: In function `main':
core_drop_files.c:(.text+0x3c): undefined reference to `IsFileDropped'
core_drop_files.c:(.text+0x4c): undefined reference to `GetDroppedFiles'
core_drop_files.c:(.text+0x1c8): undefined reference to `ClearDroppedFiles'
collect2: error: ld returned 1 exit status
Makefile:421: recipe for target 'core/core_drop_files' failed
make:  [core/core_drop_files] Error 1
**pi@raspberrypi:/clocks/raylib/examples $**

**Comment by raysan5** [comment]
Ouch! You're right, those functions are not available on RPI... actually that example shouldn't be compiled on RPI.

**Comment by raysan5** [comment]
Exposed symbols on RPI, despite file-dropping not being functional on RPI native screen rendering. Implemented in commit https://github.com/raysan5/raylib/commit/ada6668b2458f0e58e588611b2e0d70a90970827.
