### ISSUE TITLE
[textures] DrawTextureEx() is not sub-pixel precise

### ISSUE THREAD

**Issue by dbriemann** [raysan5/raylib#527]
As you can see here: https://github.com/raysan5/raylib/blob/c51203ae7e7aefac5fa95097d424aefdbe9c759c/src/textures.c#L2023 the drawing of textures is not sub-pixel precise, It is just casted to an int. So a moving sprite "jumps" from pixel to pixel.

Some kind of sub-pixel rendering or anti-aliasing here would be good!

**Comment by sherjilozair** [comment]
Antialiasing tends to produce blurry graphics and harm pixel art aesthetics, though. Maybe this feature should only be optional. IMO, jumping from one pixel to another is okay. For instance, check [this](https://mattmakesgames.tumblr.com/post/127890619821/towerfall-physics) for how in Towerfall, the characters move 1 pixel at a time. There's no sub-pixel movement.

**Comment by dbriemann** [comment]
You are right it depends on the use case. And maybe it isn't even needed. I compared the movement of a sprite to the movement of a circle (with DrawCircleV), both use float coordinates. The movement of the circle is smoother. Now the only difference is that DrawCircleV directly calls rlVertex2f which takes float values whereas DrawTexturePro (which is called by all DrawTexture functions) expects a rectangle (int values).

I think that the DrawTexture functions should skip rectangles in favor of Vector2s, so the float values are not touched before being passed to OpenGL.

And for the record. This is the kind of jumpy movement I mean:

![orbiteer-jumpy](https://user-images.githubusercontent.com/791374/39509783-c528b934-4de7-11e8-9d2d-d177efd7fe92.gif)

It should be smooth. You can also observe similar problems in the core/camera2d example, especially when zooming out and moving the block continuously.

**Comment by sherjilozair** [comment]
I think 1 is probably the best among these. Those (like me) who want integer-precision can just make sure all their floats are integers.

**Comment by egonelbre** [comment]
+1 for using floats in rectangle. Also add function `Rectangle RectangleSnap(r Rectangle, snap int)` (or some other name). This would make life easier with snapping to those who need it.

Getting pixel-art aesthetic right would need some better solution anyways. Currently with high-resolution displays you need to change the snapping amount and adjust them to match image scaling. More likely you will need to snap every 4px or more to make the "pixel-art" look right. Also, don't forget about the moving Camera2D.

**Comment by sherjilozair** [comment]
I think the best way to support pixel art graphics is to have virtual canvases. That is, have a virtual screen of size (320, 180), where all the pixels are drawn. Then each pixel in this virtual buffer is drawn scaled up to draw on 16:9 screens. This way, the physics code does not need to deal with anything other than a (320, 180) screen, but the display can do any 16:9 screen or even 16:10 with letterboxing.

Currently, in raylib, I have to pass in a scale parameter to every DrawTexture call and multiply my position vectors as well, which imo is not very convenient. A virtual canvas would be a nice feature.

**Comment by raysan5** [comment]
@sherjilozair @egonelbre thank you very much for your feedback! I think I'll go for 1.

@sherjilozair virtual canvas has already been available in raylib for some time, it can be accomplished with a RenderTarget2D. You can see create a 320x180 target to render to and then use that texture to draw to fullscreen. Some reference could be found [here](https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_custom_uniform.c), despite using same size for target and screen. Mouse input could be scaled with [SetMouseScale()](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L812).

One usage example could be found on my tool [rFXGen](https://raysan5.itch.io/rfxgen), it has a button to scale window to double size... while internal render size keeps being original size.

**Comment by raysan5** [comment]
Implemented proposed solution 1. in commit https://github.com/raysan5/raylib/commit/6324697ffd7fd410274599457dd9f85119510898

This change is more critical than I expected, it could break some things... let's see...

**Comment by raysan5** [comment]
Just note here that changing `Rectangle` parameters to float is breaking several raylib examples, including all based on `RenderTexture2D`, related to drawing...

**Comment by Aegel5** [comment]
Hello. Is it necessary to turn on sub-pixel precise somehow? I tried two functions - `DrawTexture` with rounding and `DrawTextureEx`, both produce absolutely the same effect - the texture is always displayed by pixel grid. As a result, the movement is jerky and not smooth.
