### ISSUE TITLE
[gestures] Review time measuring system on Windows

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#53]
`gestures` module is designed to be used as standalone (as much as posible). Time measuring is required for TAP_TIMEOUT and when possible a high-resolution timer should be used.

Related functions [gestures.c]:

    static double GetCurrentTime();
    static void ProcessMotionEvent(GestureEvent event);

On Linux based systems (Linux, RaspberryPi, Android), `clock_gettime()` function included in `time.h` is used for time measurement. On Windows we can use `GetSystemTimePreciseAsFileTime()` inluded in `windows.h`. The problem appears when including `windows.h`, some of its symbols conflict with raylib ones: `Rectangle`, `CloseWindow()`, `ShowCursor()`.

Anyone knows an alternative for time measument in Windows that doesn't involve including `windows.h`? If not, is it possible to avoid symbols conflicts?

**Comment by ghassanpl** [comment]
On Windows it's best to use QueryPerformanceCounter for a high resolution clock. You don't have to include windows.h, just predeclare the function:

    int __stdcall QueryPerformanceCounter(unsigned long long int *lpPerformanceCount);

You'd need to divide the returned value by the result of QueryPerformanceFrequency to get time in seconds.

**Comment by raysan5** [comment]
Thank you very much for your help! :D

**Comment by raysan5** [comment]
Tested and working. Merged in commit https://github.com/raysan5/raylib/commit/5dbb93dbb476c35d8f8aab24d9c3507640b171e8
