### ISSUE TITLE
design logo for raylib

### ISSUE THREAD

**Issue by harunbadilli** [raysan5/raylib#532]
I designed a logo for raylib. I think this logo is more stylish and more flashy than before. I've made it more noticeable by using the initials of the application. I can send files in any size and format. I hope you like it.

![1](https://user-images.githubusercontent.com/34319922/39678443-b971e3a2-5195-11e8-960a-2eaf3209f9a8.png)
![2](https://user-images.githubusercontent.com/34319922/39678444-b99ab69c-5195-11e8-8659-1c9abf9be179.png)
![3](https://user-images.githubusercontent.com/34319922/39678445-b9c6414a-5195-11e8-91a5-496e5bca9781.png)

**Comment by raysan5** [comment]
Hi @harunbadilli, thank you very much for the effort but I like current logo. No plans to change it.
