### ISSUE TITLE
SavePNG on Android

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#533]
SavePNG is already guarded in implementation https://github.com/raysan5/raylib/blob/master/src/utils.c#L159 , so it should be removed from here https://github.com/raysan5/raylib/blob/master/src/utils.h#L61 as it breaks Android build in ExportImage function.

**Comment by raysan5** [comment]
Thanks for pointing it @gen2brain, define removed in commit https://github.com/raysan5/raylib/commit/3a803ac95ea979727e77dea29daccabfd350e057
