### ISSUE TITLE
[models] Loading 3D models?

### ISSUE THREAD

**Issue by tanner00** [raysan5/raylib#534]
I'm totally new to 3D, but when loading models other than the dwarf examples I get black and white triangles indicating polygons but not the actual textures (the shape of the model is right). You say you use this to teach; do you have any tutorials?

**Comment by TheLumaio** [comment]
Can you provide what code you're using? You may need to load a texture. Also models need to be triangulated when exporting because raylib doesn't do that automatically.

**Comment by raysan5** [comment]
Hi @tanner-backup-github, I usually use the provided examples as the base to explaining the concepts I teach. I understand that looking to examples directly with no proper explanation could not be enough in some cases despite trying to make the examples as self-explicative as possible.

For models loading you can check [models_obj_loading](https://github.com/raysan5/raylib/blob/master/examples/models/models_obj_loading.c) example. Current [OBJ loader](https://github.com/raysan5/raylib/blob/master/src/models.c#L2222) only supports triangle meshes...

**Comment by diclophis** [comment]
I am also seeing this issue on OSX whereby the model loaded is only showing half the triangles in black and white.

**Comment by raysan5** [comment]
that's because it defines faces as quads instead of triangles, raylib only supports triangle faces.

**Comment by diclophis** [comment]
@raysan5 thanks for the quick reply, can confirm this was the issue... very excited to get started on my project now that i figured this out!

**Comment by JoaquinDelgadoCarrascal** [comment]
Hi, I am trying to load a 3d model to later animated it, but when I execute the code, it is loading a default cube.
I know that the model is well created so I don't know what is exactly the problem. Here I put my code if anyone have any idea :).

`#include <raylib.h>
#include <math.h>

int main(void)
{
    int screenWidth = 800;
    int screenHeight = 600;

    InitWindow(screenWidth, screenHeight, "3D TEST");
    SetTargetFPS(60);

    /* CAMERA VARS */
    Camera3D camera = (Camera3D){(Vector3){-5, 8, -5}, (Vector3){0, 2, 0}, (Vector3){0, 2, 0}, 45, CAMERA_PERSPECTIVE};

    float cam_radius = 15;
    float cam_angle = 1.57;
    
    Model model_test = LoadModel("assets/bomb.iqm");

    unsigned int animsCount = 0;
    ModelAnimation *anims = LoadModelAnimations("assets/bombAnim.iqm", &animsCount);
    int animFrameCounter = 0;

    SetCameraMode(camera, CAMERA_CUSTOM);

    while (!WindowShouldClose())
    {
        if (IsKeyDown('Q'))
            cam_angle += 0.02;
        if (IsKeyDown('E'))
            cam_angle -= 0.02;
        camera.position.x = cam_radius * cos(cam_angle);
        camera.position.z = cam_radius * sin(cam_angle);

        if (IsKeyDown(KEY_SPACE))
        {
            UpdateModelAnimation(model_test, anims[0], animFrameCounter);
            animFrameCounter++;
            if (animFrameCounter >= anims[0].frameCount) animFrameCounter = 0;
        }
        BeginDrawing();
        ClearBackground(BLACK);
        BeginMode3D(camera);
        DrawModel(model_test, (Vector3){0, 1, 0}, 1, WHITE);
        DrawGrid(15, 1.0);
        EndMode3D();
        DrawFPS(10, 10);
        EndDrawing();
    }
    for (unsigned int i = 0; i < animsCount; i++) UnloadModelAnimation(anims[i]);
    RL_FREE(anims);
    UnloadModel(model_test);
    CloseWindow();
    return 0;
}`
