### ISSUE TITLE
[build] Test Wayland in Travis

### ISSUE THREAD

**Issue by gen2brain** [raysan5/raylib#536]
I think that every time I updated GLFW, wayland build was broken, and new protocol files (.c/.h) generated with wayland-scanner needed to be included. It would be good to test build in travis, but I am not sure if it can be just new matrix with some env in .travis.yml, something like that.

I tested in latest Ubuntu and there `apt-get install libgl1-mesa-dev libwayland-dev libxkbcommon-dev` is enough, and I also added this symlink `ln -sf /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1.0.0 /usr/lib/x86_64-linux-gnu/libwayland-egl.so`

For Ubuntu 14, that version is used in CI, `libwayland-egl1-mesa-lts-xenial` must also be included, and again, I had to make a symlink, not sure why just so.1.0.0 is installed without any symlink.

Also, for latest GLFW I had to generate and include more .c files, see https://github.com/gen2brain/raylib-go/blob/master/raylib/cgo_linux.go#L19 (current raylib misses just wayland-idle-inhibit but after you update GLFW more are needed).

I updated GLFW because of this commit, it sounds bad https://github.com/glfw/glfw/commit/8b9221d845e4ae9b314f07375cc3a520ba8d98d7

**Comment by a3f** [comment]
I copied over the Travis CI configuration that GLFW itself uses for wayland, but building the examples fails. Could you take a look?

**Comment by a3f** [comment]
I've updated GLFW and added two Linux configurations to Travis CI: 
* X11+external GLFW
* Wayland+in-tree GLFW.

I didn't have to fixup any symlinks manually.

**Comment by a3f** [comment]
I reverted 2d6fb5c628068757387525e190c3afdbe33ae9c6, because some of my Alien::raylib tests failed. Reopenning this issue as a reminder till it's sorted out...
