### ISSUE TITLE
[rlua] Add LUA support for scripting

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#54]
Add a simple an intuitive wrapper to LUA scripting language.

This issue is just a desired feature and it has not been developed yet (I mean, deciding how to implement it). Any help on developing it is highly appreciated!

A draft concept for possible function signature could be:

    void *ExecuteLuaScript(const char *name, int numParams, ...)

The idea is just call Lua script with required params and get a return value. Don't worry about setting up Lua state and libraries or data push/pop.

It's been more than 10 years since the last time I used Lua and I need some refresh on how it works...

**Comment by ghassanpl** [comment]
I've pushed preliminary Lua support into my develop branch at https://github.com/ghassanpl/raylib/tree/develop

It's not really well documented (although most functions do what you expect). I've ported raylib, utils and raymath, with small exceptions. 

https://github.com/ghassanpl/raylib/blob/develop/raylib/test.lua has the Flappy Jetpack game (https://kurnic.wordpress.com/portfolio/flappy-jetpack/) ported to Lua as a test file. It works fine as far as I can tell.

Again, this is just an early alpha. Much testing is needed to see if everything works properly, as well as a lot of cleanup and documentation.

**Comment by JaredSartin** [comment]
Ooh. I know what I'm doing this weekend!

**Comment by ghassanpl** [comment]
@JaredSartin No problem, keep in mind that due to my nuclear hatred of git I'm pushing all my personal changes to a single branch to avoid problems, so there might be some other features in the latest commit of my branch. The latest Lua commit is cd84b7527a548fa6858671693cf0a1e38f1aa9bd at the moment. Sorry about the confusion.

**Comment by raysan5** [comment]
Wow! It's amazing! I have no words... really impressed...  :D

**Comment by ghassanpl** [comment]
I kinda sorta don't really have time to test the Lua port properly, I'm afraid :( (Or maybe I just don't know how to test it well :P) So I'd appreciate some feedback.

**Comment by raysan5** [comment]
Ok, I'll try to port the examples collection to lua and check if everything works ok; for all the other systems I do this way. Usually I test single functions independently with a basic window and then I integrate them in a bigger example.

Again, congrats for your work, it's amazing!

**Comment by ghassanpl** [comment]
While compiling on emscripten I found some things that needed fixing in the Lua implementation; I've pushed them to my develop branch (along with some other changes). It's a bit of a mess right now, sorry about that.

**Comment by kd7tck** [comment]
I really like the example given at: http://github.com/BrettRToomey/Blog-Examples/tree/master/Lua53Embed

It allows for a hooked event from the lua script to be called every tick.
Sure would be nice if that kind of functionality could be built into ExecuteLuaScript.

I hope the system doesn't just run a series of scripts and that's it. Might be better if you could load Lua scripts as a series of modules, that can execute in any order you see fit from the C side. Then a table can be passed back and forth between modules, filled with globals and hooks. A series of params is just annoying for programming, tables are easier to work with.

**Comment by raysan5** [comment]
Hi @ghassanpl ! 

I'm working hard towards raylib v1.4 milestone and I would like to include your LUA module implementation.

Don't know what's the state of the module but it would be great to be have it in raylib.

Please, could you make a pull-request to develop branch?

**Comment by ghassanpl** [comment]
My Lua module hasn't been update for a long time, you'll have to give me some time to bring it up to feature parity with the develop branch :)

**Comment by raysan5** [comment]
Hey @ghassanpl !

Please, don't worry, take your time! Still working on some issues on develop branch and there is not a planned release date, it could be two weeks or a month... 

No plan to add new functions, just review gestures module, redesign RPI inputs system and review the new structs (Light, Materials, Physics, Rigidbody, Colliders, ...). :)

**Comment by JaredSartin** [comment]
This was removed from 1.5 milestone? :( ok

**Comment by ghassanpl** [comment]
This is completely my fault and I apologize profusely. I haven't had much time (mostly due to personal stuff) to work on this. Also, I generated most of the code using a custom tool, and fixed problems by hand, so synchronizing it with the latest version of the lib would be a massive pain. I'm not that good at undirected work, so if anyone wants to take over, or tell me what to do, that would be great. Soryy again.

**Comment by raysan5** [comment]
Hi @JaredSartin! raylib 1.5 represents a really big update for the library with the addition of a materials system and Oculus Rift support (that implied a lot of internal redesign). To add lua support, it's better to work over a stable version, so I was waiting for 1.5 release before coming back to this issue. 

Hey @ghassanpl! No need to apologize, it's perfectly comprensible! I'll try to take a look to what you have and add the useful parts to raylib for future development. Anyway, many thanks for your contribution.

**Comment by JaredSartin** [comment]
Awesome. Thanks for the updates - it makes sense as to the current status
and upcoming features.
On Thu, Jun 16, 2016 at 05:01 Ray <notifications@github.com> wrote:

> Hi @JaredSartin <https://github.com/JaredSartin>! raylib 1.5 represents a
> really big update for the library with the addition of a materials system
> and Oculus Rift support (that implied a lot of internal redesign). To add
> lua support, it's better to work over a stable version, so I was waiting
> for 1.5 release before coming back to this issue.
>
> Hey @ghassanpl <https://github.com/ghassanpl>! No need to apologize, it's
> perfectly comprensible! I'll try to take a look to what you have and add
> the useful parts to raylib for future development. Anyway, many thanks for
> your contribution.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/raysan5/raylib/issues/54#issuecomment-226465052>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAnZXFD77mcoUdEXDAatHXPcaoSvnNz1ks5qMTr3gaJpZM4F85YG>
> .
>
-- 
Jared Sartin
*Mobile *(269) 364-1735 | *Twitter* @JaredSartin
<http://twitter.com/JaredSartin>
*Website* <http://jared.sart.in/>

**Comment by raysan5** [comment]
New module created: [rlua](https://github.com/raysan5/raylib/blob/develop/src/rlua.h) - A raylib 1.6 Lua binding (header-only, view [example](https://github.com/raysan5/raylib/blob/develop/examples/rlua_execute_file.c) for usage)

A preliminary working version has been uploaded at commit https://github.com/raysan5/raylib/commit/735968e68543bb5141122f181608d0d7ada9a3be

Still some work required, lots of `TODO` splitted around the code...

**Comment by raysan5** [comment]
Closing this issue and continue development on new Issue thread: https://github.com/raysan5/raylib/issues/171
