### ISSUE TITLE
Unrecognized flag "-no-pie"

### ISSUE THREAD

**Issue by Murii** [raysan5/raylib#540]
Hello. I tried to compile the examples folder using: make PLATFORM=PLATFORM_DESKTOP (I'm running Debian) and gcc complains about "-no-pie" flag. After removing it (line 218) I could compile the project just fine.

**Comment by a3f** [comment]
Could you paste the output of `gcc -Q -v`?

**Comment by Murii** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10+deb8u1' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10+deb8u1)

**Comment by a3f** [comment]
Looks like `-no-pie` was added in GCC 6.1.0: https://github.com/gcc-mirror/gcc/commit/e9abca4f4a48fa8b1fd9778f6a3cd748e099e3bb.

Found this on [SO](https://stackoverflow.com/a/46493456/1257035):
> With only -no-pie, (but still -fpie) compiler-generated code (from C or C++ sources) will be slightly slower and larger than necessary, but will still be linked into a position-dependent executable which won't benefit from ASLR. 

So apparently, `-no-pie` did actually hamper performance so far. Either we add `-fno-pie` (and check for >gcc6.1) as well or remove the flag. I'd be in favor of removing it altogether.
