### ISSUE TITLE
[text] Fonts example do not work (most of them)

### ISSUE THREAD

**Issue by Murii** [raysan5/raylib#541]
* text_ttf_loading
* text_bmfont_unordered
* text_bmfont_ttf

^ Show only the shape of the font with a color inside (this leads me to think that there's a problem regarding the opengl 2.1 shader)

http://pasteall.org/pic/9db4a3b47cfbcf228e758dba59121f22

**Comment by raysan5** [comment]
Hi @Murii, thanks for the report!

Are you compiling latest version from master branch? 
Did you compile for OpenGL 2.1 graphic backend? Or using default 3.3 backend?

It seems related to ttf loading, used shader is the same as the other text.

**Comment by Murii** [comment]
Hello @raysan5 ! 
I got the latest version from the master branch. 
I opted for OpenGL 2.1 as graphic backend. The default backend gave me this error when running any example: "GLX: Failed to create context: GLXBadFBConfig" (My GPU is Intel HD Graphics 3000)

**Comment by raysan5** [comment]
After about 3 hours trying to understand what failed, I found the solution... I love OpenGL... it makes my life really enjoyable... >__<

Corrected on commit https://github.com/raysan5/raylib/commit/3b70b66a089ed48b99305ce058a4bbde4a0bc3b4
