### ISSUE TITLE
Bindings to Lisp.

### ISSUE THREAD

**Issue by ghost** [raysan5/raylib#543]
Hey! I own a small (fast and useful) Lisp like language called Aria,https://github.com/Murii/AriaLisp. I was thinking in porting all modules of raylib to it. 
My question is: Do you want me to update this thread with pictures and such as I port functions or post a link when everything is done?

Here's a small example (picking colors is not supported yet): 
```cl 
(do 
    (= window-w 800 window-h 600)
    (InitWindow window-w window-h "Hello Aria")
    (SetTargetFPS 60)

    (loop (not (WindowShouldClose))
        (BeginDrawing)
        (ClearBackground)

        (DrawRectangle 200 200 50 50)
        (DrawText "Hello World!" 20 120 40)

        (EndDrawing))
    (CloseWindow)
)
```

**Comment by raysan5** [comment]
Hi @Murii! That's amazing!

You can keep us updated in this thread! It's great to see the dev process evolution! :)

Just to follow convention with other bindings like [`raylib-lua`](https://github.com/raysan5/raylib-lua) or [`raylib-go`](https://github.com/gen2brain/raylib-go), 
could it be named `raylib-aria`?

**Comment by Murii** [comment]
@raysan5 
Sure, that's how it's named :)

**Comment by raysan5** [comment]
Just closing for now, users has quit github so it won't be able to provide updates...
