### ISSUE TITLE
ASTC 8x8 support broken

### ISSUE THREAD

**Issue by timkerchmar** [raysan5/raylib#544]
This line:

https://github.com/raysan5/raylib/blob/eed170f85217b38bd0ff8091325dcaf06fd61608/src/textures.c#L2677

Should contain this constant: COMPRESSED_ASTC_8x8_RGBA

**Comment by raysan5** [comment]
Hi @timkerchmar! Thank you very much for reporting this issue! Corrected in commit https://github.com/raysan5/raylib/commit/bb43755a9df89fab3018c5684d9a38ae5b52397b
