### ISSUE TITLE
[text] Latin Character Question - Urgent!!!

### ISSUE THREAD

**Issue by cf-isys** [raysan5/raylib#549]
Hi, 
I need use the latin character (á é í ó ú) use the windows segoeui.ttf, how to make this? When I put this character display space.

Is very important for me have the answer.

thanks,

**Comment by OvermindDL1** [comment]
> I need use the latin character (á é í ó ú) use the windows segoeui.ttf, how to make this? When I put this character display space.

Quick question first, 'where' are you putting those in?  Do note that they should not be in the source code as the C++ standard only defines the non-extended ASCII range as properly compatible (though 'most', though not microsoft's compilers will implement unicode properly with special switches).

**Comment by cf-isys** [comment]
Sorry, I test this in windows and Linux. in both SO have the same result. I use the TTF SpriteFont example and replace the text by this

const char msg[ 50 ] = "TTF [áéíóú] SpriteFont";
// TTF SpriteFont loading with custom generation parameters
SpriteFont font = LoadSpriteFontEx( "segoeui.ttf", 96, 0, 0 );

What is wrong??

**Comment by raysan5** [comment]
@cf-isys does the font include those characters? I presume yes...

Use the function `LoadSpriteFontEx()` instead of `LoadSpriteFont()`:
```c
// Load 255 characters from TTF font (including Latin)
SpriteFont font = LoadSpriteFontEx("segoeui.ttf", 32, 255, NULL);
```
It should work ok.

**Comment by OvermindDL1** [comment]
> const char msg[ 50 ] = "TTF [áéíóú] SpriteFont";

Even if the font does include those character, don't do this code.  The `áéíóú` part in the string may do *very* surprising code (including potentially even spaces, nothing, garbage, or just about anything at all) depending on the compiler and compiler settings, it is Undefined Behaviour in C++ as it falls out of the restricted ASCII range.

In general, text that is display to end users should probably support localization and all as well, thus using something like the gettext library, which means text is stored in external files, thus there is no issue in those cases.

In reality those 'specific' character will likely work (as most compilers support the extended ascii range without issue) but once you start using other forms of unicode things are near guaranteed to break in surprising ways, so this specific issue is probably just not loading the correct characters from the font file as @raysan5 said.  But still, don't put anything but the lower ascii set in C/C++ source files.

**Comment by cf-isys** [comment]
Dear RaySan

Thanks for your answer, but not work!


`    InitWindow( screenWidth, screenHeight, "raylib [text] example - ttf loading" );
    const char msg[ 50 ] = "TTF [áéíóú] SpriteFont";
    // NOTE: Textures/Fonts MUST be loaded after Window initialization (OpenGL context is required)
    // TTF SpriteFont loading with custom generation parameters
    SpriteFont font = LoadSpriteFontEx( "segoeui.ttf", 32, 255, NULL );`


I am using the last stable raylib v1.8.0 

Another idea? Please!!!!

**Comment by OvermindDL1** [comment]
> How would you like to display a text containing these characters within the code? Can you give me an example?

I don't know raylib's way as I tend to prefer raw calls and libraries, but traditionally I'd use gettext, load the text via gettext (internationalized), look up the unicode in my SDF fonts (I tend not to like ttf files as their quality in rendering is pretty poor unless they are a perfect pixel match, which is almost never because of DPI screen changes and all such, plus zooming and rotation and so forth), then render those SDF glyphs via my SDF shader.  All of that is of course wrapped up into function like `renderKeyText("test-string", mat, clip);`.

**Comment by cf-isys** [comment]
I found the answer, and is this:

    int totalChars = 255;
    int *defaultFontChars = (int *)malloc( totalChars * sizeof( int ) );
    for ( int i = 0; i < 256; i++ ) defaultFontChars[ i ] = i;
    
    char msg[ 256 ] = "TTF [áéíóú] SpriteFont";
    // NOTE: Textures/Fonts MUST be loaded after Window initialization (OpenGL context is required)
    // TTF SpriteFont loading with custom generation parameters
    SpriteFont font = LoadSpriteFontEx( "segoeui.ttf", 32, totalChars, defaultFontChars );

**Comment by raysan5** [comment]
Actually, my solution should work same way... maybe I reviewed it for raylib 2.0 and it's not available on 1.8.

@OvermindDL1, just adding SDF font support on version 2.0, also thinking about adding full Unicode support, now it supports chars from 128>255 if provided as UTF8 but not the best approach (internally hardcoded).

**Comment by raysan5** [comment]
@OvermindDL1 For the moment, I'm using single-channel SDF, I know it's not the best solution but it's the one provided by [stb_truetype](https://github.com/nothings/stb/blob/master/stb_truetype.h) library.

A better solution would be using a multi-channel SDF implementation MSDF, [Viktor Chlumský](https://github.com/Chlumsky/msdfgen) has a nice implementation and also an interesting [thesis paper](https://dspace.cvut.cz/bitstream/handle/10467/62770/F8-DP-2015-Chlumsky-Viktor-thesis.pdf) about it... but it requires too much work for now. Probably stb_truetype will support it at some point.

About Unicode, I'm looking for the best way to implement it (in terms of font drawing). Now passed strings are expected to be UTF8 (that's a good requirement) and are processed (supporting range from 32 to 255). Plan is converting UTF8 strings to Unicode in real-time for drawing; actually, it's the same as now but supporting a widder range of characters (up to 4 bytes).

**Comment by raysan5** [comment]
In any case, just closing this issue for now.

**Comment by OvermindDL1** [comment]
Oh hey that's cool.  I based my work on Valve's original SDF implementation (which was 2 channel) and modified it over time so I've not seen how any auto-generators work.  I do know that converting from TTF/OTF/etc to SDF (dual or single channel) has never been very good and manual SDF creation/touch-ups has always been required thus far to look great, but if they manage to get the auto-generator to work then that would be awesome (and save me time)!
