### ISSUE TITLE
[core] Allow using custom windowing/input system

### ISSUE THREAD

**Issue by cl9x** [raysan5/raylib#554]
I'm looking through raylib.h, and it looks that all of the declarations unrelated to platform and window management can work in stand-alone mode used by [this example](https://github.com/raysan5/raylib/blob/master/examples/others/rlgl_standalone.c). This would make supporting new platforms (i.e. iOS, or an alternative window manager such as Wayland ) or embedding Raylib into an existing project much easier without needing to modify raylib.h itself.

**Comment by raysan5** [comment]
hi @cl9x! Sorry, I don't understand exactly what you mean with stand-alone mode, do you mean header-only library? Wayland is already supported by raylib. It can also be added to an existing project without modyfing `raylib.h`...

Sorry, I clearly didn't understand the proposed enhacement...

**Comment by cl9x** [comment]
Hi. Please see [this example](https://github.com/raysan5/raylib/blob/master/examples/others/rlgl_standalone.c) that I specifically mentioned. In this example, you are using a stand-alone mode for rlgl.h.

I am requesting a similar stand-alone mode for raylib.h. This way, it is possible to load models and textures, display text, and other things using my own window/platform specific code which is different from what is in core.c

Unfortunately, the GLFW Wayland support is specific to desktops, whereas I am working with a Wayland client designed for touch screen.

**Comment by raysan5** [comment]
ok, so, if I understand correctly, your proposal is a version of raylib with no platform windowing/input code. That functionality should be provided by the user.

I could think about it but definetely no priority right now.

**Comment by raysan5** [comment]
Supporting an external Window/Input system requires rewritting full [core](https://github.com/raysan5/raylib/blob/master/src/core.c) module functionality. Out of scope for the moment. Closing the issue.

**Comment by Ev1lT3rm1nal** [comment]
Any updates? @raysan5

**Comment by raysan5** [comment]
@Ev1lT3rm1nal not really.
