### ISSUE TITLE
Exporting the project?

### ISSUE THREAD

**Issue by DERPNYS** [raysan5/raylib#562]
Hello. When I compile the project using C::B (in the debug mode), I get an .exe file on the "Debug" folder in the project but when I try to open that .exe it says that "Couldn't exec because libgcc_s_dw2-1.dll is missing". 

So how can I make it to export my project and be able to open it in another computer?

Thanks.

**Comment by a3f** [comment]
This is a compiler (GCC), not a raylib issue. GCC groups some helper functions into libgcc, e.g. 64-bit division if the host CPU ISA doesn't natively support it.

Add `-static-libgcc` to the linker flags dialog in Code::Blocks to instruct GCC to include the library with the exe.

**Comment by raysan5** [comment]
Hey @a3f! Thank you very much for the answer! By the way, could you take a look to Travis CI? It seems there is some issue with glfw headers... About examples compilation issue of LoadFontEx(), I'm taking a look.

Closing this issue.

**Comment by a3f** [comment]
> It seems there is some issue with glfw headers...

Ah, I missed that. I've commented on #558, which I suspect to be the culprit.
