### ISSUE TITLE
Raylib not executing!!!

### ISSUE THREAD

**Issue by mattackerplus** [raysan5/raylib#564]
Please help!!!

I really love this library because I'm a fan of C, and I've been making a game in it for the past 2 weeks. I had to reset my computer recently because of a little problem and when I tried to run the project I was working on it refused at first giving the exit code concerned with an outdated gpu i sorted that out then when i tried to run it after fixing that little problem it gave me yet another with the exit code 255. 

It just plain refuses to execute the file, please do help me for I love using raylib and if you need anymore info please do say so.

Oh yeah Raysan is awesome and I really appreciate everything he has done.

**Comment by mattackerplus** [comment]
I solved that problem using https://github.com/raysan5/raylib/wiki/FAQ, and I'm using a intel g33, I've always been using it and my raylib is 1.8, yes I did try it but no luck and here's the output:

> Setup required Environment
-------------------------------------
SET: RAYLIB_DIR = C:\raylib
$(RAYLIB_DIR) = C:\raylib
ENV_SET: PATH=C:\raylib\MinGW\bin
$(SYS.PATH) = C:\raylib\MinGW\bin
CD: C:\raylib\raylib\examples\core
Current directory: C:\raylib\raylib\examples\core

NOTE: raylib uses OpenAL Soft library compiled statically and linked into the executable

> Cleaning latest build
---------------------------
cmd /c IF EXIST core_basic_window.exe del /F core_basic_window.exe
Process started >>>
<<< Process finished. (Exit code 0)

> Compiling program
-------------------------
gcc -o core_basic_window.exe core_basic_window.c -s C:\raylib\raylib\raylib_icon -Iexternal -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,-allow-multiple-definition -Wl,--subsystem,windows
Process started >>>
<<< Process finished. (Exit code 0)

> Reset Environment
--------------------------
ENV_UNSET: PATH
$(SYS.PATH) has been restored

> Executing program
-------------------------
cmd /c IF EXIST core_basic_window.exe core_basic_window.exe
Process started >>>
<<< Process finished. (Exit code 255)
================ READY ================

Thanks for the swift response!

**Comment by raysan5** [comment]
Sorry, I need the output console info of the program executing. Try removing `-Wl,--subsystem,windows` parameter from compilation and execute `core_basic_window.exe` from command line.

**Comment by mattackerplus** [comment]
Just seems to crash after I do that,sorry I believe I'm failing to properly follow instructions.

**Comment by raysan5** [comment]
On this compilation line:
```
gcc -o core_basic_window.exe core_basic_window.c -s C:\raylib\raylib\raylib_icon -Iexternal -lraylib -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,-allow-multiple-definition -Wl,--subsystem,windows
```
Just remove `-Wl,--subsystem,windows`.

And them execute a `cmd` (the console black screen) and launch `core_basic_window.exe` program.

Please, let me know if you manage to get it.

**Comment by mattackerplus** [comment]
Here:
'gcc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by raysan5** [comment]
You need to edit the Notepad++ `raylib_compile_execute`.

**Comment by mattackerplus** [comment]
In what way exactly?

**Comment by raysan5** [comment]
when you press F6 on Notepad++, the window that appears contains a text script, just read it, look for `-Wl,--subsystem,windows` and delete that part.

**Comment by mattackerplus** [comment]
![image](https://user-images.githubusercontent.com/38685135/42228493-689a1f5e-7ee4-11e8-8c82-84f227f16b3a.png)

**Comment by mattackerplus** [comment]
That's all it does now

**Comment by raysan5** [comment]
did you try running core_basic_window.exe directly from the command line (the ms-dos black window)?

**Comment by mattackerplus** [comment]
![image](https://user-images.githubusercontent.com/38685135/42245096-d252b68a-7f17-11e8-8c55-a6cf8a463e3f.png)

**Comment by mattackerplus** [comment]
Still no luck :(

**Comment by raysan5** [comment]
ok, try running `core_basic_window.exe` directly from the command line (the ms-dos black window), not the compilation line.

**Comment by mattackerplus** [comment]
![image](https://user-images.githubusercontent.com/38685135/42292927-6cf7a588-7fd6-11e8-8f9e-336d75eec7a4.png)

**Comment by mattackerplus** [comment]
But I though I had fixed this problem

**Comment by raysan5** [comment]
just closing this issue.

**Comment by yoel123** [comment]
i have the same problem
