### ISSUE TITLE
[core] Support gamepad inputs for Android devices

### ISSUE THREAD

**Issue by SethArchambault** [raysan5/raylib#567]
I got the simple app template working on Android, but if I press any gamepad button, I get a segfault:

```
V/threaded_app(12555): New input event: type=1
V/threaded_app(12555): New input event: type=1
F/libc    (12555): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1b in tid 12574 (om.seth.project)
I/libc    (12555): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
```

I've used asserts to try and locate the source of the error, but it seems like it's trying to jump to some part of the application that doesn't exist when a button is pressed, because I can't get an assert to be hit after loading, and before the crash.. Any clues here? 

I'm working on getting the output to not be suppressed, but unsure how to use:

```
prctl(PR_SET_DUMPABLE, 1)
```

Thanks!

**Comment by raysan5** [comment]
Gamepad on Android? What device? Probably not implemented... but shouldn't be difficult...

**Comment by raysan5** [comment]
ok, just checked raylib sources and also push a related commit here: https://github.com/raysan5/raylib/commit/1f1d8eeeeb5aa34cfa41784c88cdce11fa525fa1
Right now gamepad support is not implemented, it's not difficult to support it, just need to check input state and pressed buttons/asix but it will require some work.

I leave this issue open in the meantime.

**Comment by SethArchambault** [comment]
K I've gotta take a break, but here's what I see so far.

``` 
line 3080
static int32_t AndroidInputCallback(struct android_app *app, AInputEvent *event)
```

Probably this line is breaking:
```
 gestureEvent.pointerId[0] = AMotionEvent_getPointerId(event, 0);
```

definition:
```
int32_t AMotionEvent_getPointerId(
  const AInputEvent *motion_event,
  size_t pointer_index
)
```

I suspect we'll need to getsource and then depending upon what that returns, we'll handle the type of input in it's own way:

```
int32_t AInputEvent_getSource(
  const AInputEvent *event
)
```
These are the options
```
AINPUT_SOURCE_ANY                   any
AINPUT_SOURCE_BLUETOOTH_STYLUS      bluetooth stylus
AINPUT_SOURCE_DPAD                  dpad
AINPUT_SOURCE_GAMEPAD               gamepad
AINPUT_SOURCE_JOYSTICK              joystick
AINPUT_SOURCE_KEYBOARD              keyboard
AINPUT_SOURCE_MOUSE                 mouse
AINPUT_SOURCE_MOUSE_RELATIVE        mouse relative
AINPUT_SOURCE_ROTARY_ENCODER        rotary encoder
AINPUT_SOURCE_STYLUS                stylus
AINPUT_SOURCE_TOUCHPAD              touchpad
AINPUT_SOURCE_TOUCHSCREEN           touchscreen
AINPUT_SOURCE_TOUCH_NAVIGATION      navigation
AINPUT_SOURCE_TRACKBALL             trackball
AINPUT_SOURCE_UNKNOWN               unknown 
```

Could be off completely, but that's what I see so far!  I'll get back into this later.

**Comment by raysan5** [comment]
Hey @SethArchambault! 

You're probably right! I implemented that function some years ago and it's mostly uncomplete. The truth is that I don't know of many people using raylib for Android besides me and some of my students, and just for simple games, none of them published comercially.

Any feedback is really welcome!

**Comment by SethArchambault** [comment]
@raysan5 

K, I'm digging into this now, and my journey has started with rebuilding the latest raylib. I've noticed a change in the Makefile though - removal of support for 32 bit devices (armeabi-v7a being replaced by arm64-v8a), is this something I should be concerned about? 

I saw this note in here:
"Starting at 2019 using ARM64 is mandatory for published apps"
Looking into that, I see that Google is not going to allow 32 bit apps on their store in 2019, is that why it's being dropped here?
I just bought a Fire HD 8 a few months ago for the purpose of deploying a video game project (the form factor and cost makes it ideal) so I'll be using 32 bit stuff for the foreseeable future.

Will Raylib be workable with 32 bit in the future? Or is there a phase out planned?

I'm going to make edits to get the 32 bit version working again - let me know if you'd like me to push those up. 

Thanks!

**Comment by SethArchambault** [comment]
Update: Got the makefile working with 32 bit builds

**Comment by raysan5** [comment]
Hey @SethArchambault!

Just removed support for 32bit ARM for the upcoming raylib 2.0 because in 2019 64bit building would became mandatory. Actually, Fire HD 8 has a MediaTek MT8163V/B **64bit** quad-core CPU.

In any case, nice to see to get it working with 32bit again, I imagine it was an easy change. Do you think of any good reason to re-integrate that option into raylib?

**Comment by SethArchambault** [comment]
Ha, you're right!  My mistake.. 

Hmm.. I would say there are two potential use cases: demos and "arcades".
I have one use case that is directly relevant to me!  Amazon's Fire stick is 32 bit only ([according to wikipedia](https://en.wikipedia.org/wiki/Amazon_Fire_TV#Models)) and is a essentially a $40 android computer, that plugs directly into the dv port of any tv.  This degree of portability probably makes it ideal for demoing a game - you can firestick in a pocket and just plug it in wherever. 

This kind of versatility is especially useful if you want to set up a small arcade with multiple machines - with older equipment the price might not be so high. This is part of intention..

However, I'm sure there are tradeoffs that need to be made that I'm not aware of - are there parts of the code that become easier to maintain if 32 bit support is removed?  If it's just the Makefile that changes, maybe just have a Makefile_32bit file that people can use if they choose to build it at 32 bits, to avoid multiple if statements?

**Comment by SethArchambault** [comment]
Got it working and created a pull request!  Let me know your thoughts..

**Comment by raysan5** [comment]
@SethArchambault just reviewed your PR in commit https://github.com/raysan5/raylib/commit/c6d188a09a9a82653027476690a69c28e8545e48

I'm afraid that shouldn't be the right way to support Gamepad on Android devices, despite I understand it works and I integrated your changes.

It seems it uses KEY input but registered as TYPE_MOTION input, that's weird. What kinf of gamepad are you using? is it a gamepad connected by USB?

Well, in any case, I'll leave the issue open for further investigation...

**Comment by SethArchambault** [comment]
Cool cool - It's a 8bitdo gamepad SNES classic style, Bluetooth controller.

**Comment by SethArchambault** [comment]
Heads up - I noticed when I did a recent pull that the "return 0;" was removed and replaced by some code that tests whether there between 1-4 points (to get around the getPoints issue)
I don't think this will prevent a crash though - using the gamepad getPoints seems to return how many buttons your press (Sometimes). For instance, I found that jamming down 3 buttons at once, the pointer count is 3, which would then crash this.

Anyways, I'll dig into it more later.. Thanks!

**Comment by SethArchambault** [comment]
K, found a warning message that spams the output if I use any of the new GAMEPAD_ANDROID enums

```
WARNING: [GLFW3 Error] Code: 65539 Decription: Invalid key 22
```

This issue is here:
```
./external/glfw/src/input.c:584:        _glfwInputError(GLFW_INVALID_ENUM, "Invalid key %i", key);
./external/glfw/src/input.c:601:        _glfwInputError(GLFW_INVALID_ENUM, "Invalid key %i", key);
```

GLFW doesn't believe that there can be a key less that GLFW_KEY_SPACE or greater than GLFW_KEY_LAST:

```
if (key < GLFW_KEY_SPACE || key > GLFW_KEY_LAST)
```

These are defined in ./external/glfw/include/GLFW/glfw3.h:
```
./external/glfw/include/GLFW/glfw3.h:360:#define GLFW_KEY_SPACE              32
./external/glfw/include/GLFW/glfw3.h:483:#define GLFW_KEY_LAST               GLFW_KEY_MENU
./external/glfw/include/GLFW/glfw3.h:481:#define GLFW_KEY_MENU               348
```

So this is trivial to change (Though it's not completely clear to me why glfw should be checking for a range of valid key codes, given that this range could change based on other files) - however, I can't understand raylib's build process well enough to get it to pull my change, somehow it's still using an old compiled version because the change doesn't show up.. 

I'll tackle this later!

**Comment by SethArchambault** [comment]
Nevermind! Just needed to run make clean.. Pull Request created!

**Comment by raysan5** [comment]
That's very weird, GLFW is not used on Android platform.

On the other side, a gamepad device should not generate key inputs, it should generate joystick/gamepad button inputs instead. Maybe there is so issue with the driver...

I think the right solution for this issue is just using, as proposed at the beginning, `AInputEvent_getSource` to discretize the input source.

**Comment by DevJac** [comment]
Hope this is on topic: Are the android DPAD's buttons or an axis? Probably buttons?
As a specific example, is `#define GAMEPAD_ANDROID_DPAD_UP        19` from `raylib.h` a button or an axis?

**Comment by raysan5** [comment]
@DevJac not tested it personally, maybe it depends on the attached gamepad.

**Comment by raysan5** [comment]
After some more investigation, I [found](https://developer.android.com/training/game-controllers/controller-input):
 > At the system level, Android reports input event codes from game controllers as Android key codes and axis values.

So, gamepad inputs on Android are processed as key inputs. 

Still thinking gamepad on Android requires some review... but I'll close this issue for now.
