### ISSUE TITLE
MatrixLookAt() unexpected results

### ISSUE THREAD

**Issue by NuklearBomb** [raysan5/raylib#574]
I've been porting some code to `raymath` and I'm getting some unexpected results:
```
MatrixLookAt()
-1    0     0   -0
 0    1     0    0
 0    0    -1    0
 0    0   -35    1
```
```
bx::mtxLookAt()
 1    0     0    0
 0    1     0    0
 0    0     1    0
 0    0    35    1
```
```
Matrix view=MatrixLookAt((Vector3){0,0,-35},(Vector3){0,0,0},(Vector3){0,1,0});
printf("%f %f %f %f\n",view.m0,view.m1,view.m2,view.m3);
printf("%f %f %f %f\n",view.m4,view.m5,view.m6,view.m7);
printf("%f %f %f %f\n",view.m8,view.m9,view.m10,view.m11);
printf("%f %f %f %f\n",view.m12,view.m13,view.m14,view.m15);
```
Could this be a handedness thing? How does `raymath` handle handedness? Please excuse my ignorance; 3D math has never been my strong point and a nudge in the right direction would be very much appreciated! Thank you!

**Edit**
With some further digging, I have found that modifying this line in the `MatrixLookAt()` function from this
```
Vector3 z = Vector3Subtract(eye, target);
```
to this
```
Vector3 z = Vector3Subtract(target, eye);
```
produces the desired matrix. I don't think this is a problem with `raymath`, so could it be that I'm using the function wrong? I'll keep this post updated in case I find a solution.

**Comment by NuklearBomb** [comment]
Closing issue. I had to use raymath's `MatrixPerspective()` function instead of mixing library functions.

**Comment by raysan5** [comment]
`raymath` uses a right handed, column major 4x4 matrix style defined as:
```c
typedef struct Matrix {
        float m0, m4, m8, m12;
        float m1, m5, m9, m13;
        float m2, m6, m10, m14;
        float m3, m7, m11, m15;
} Matrix;
```
Actually, it's consistent all over the library and it should be aligned with GLM maths, one user just replaced GLM library by `raymath` and send some consistency corrections.
