### ISSUE TITLE
Help to tell any sample for paint app on canvas/webgl?

### ISSUE THREAD

**Issue by nvcken** [raysan5/raylib#580]

**Comment by nvcken** [comment]
sorry, is it possible to use raylib to make web paint app (mobile browser almost ) and does it support fallback to Canvas API if WebGL is not available ? Many thanks

**Comment by raysan5** [comment]
Well, I think so. You can use raylib to create a web painting app... but I haven't tried it, depending on your requirements it could take a lot of work.

raylib on web only uses WebGL, no fallback to Canvas API.

**Comment by egonelbre** [comment]
The easiest starting point would be:
1. record points, for what the mouse is doing when a button is pressed
2. use DrawPolyEx to draw that information

Then the next step from that would be to:
1. record points
2. draw lines to an image (see bresenhams line drawing)
3. UpdateTexture
4. draw the texture to screen

**Comment by raysan5** [comment]
Just closing this issue...
