### ISSUE TITLE
SetColor function

### ISSUE THREAD

**Issue by r00ster91** [raysan5/raylib#581]
What about rather having one `SetColor` function where you can set the current color for all the things that you draw instead of having a color argument at the end of for example nearly every function in [shapes](http://www.raylib.com/cheatsheet/cheatsheet.html#shapes)? I think that would be way better and less to type.

I know that would be a big breaking change but I think it's worth it.

I would be willing to begin working on it.

**Comment by raysan5** [comment]
sorry @r00ster91, no plans to change that behaviour right now. I like to keep functions as self-contained as possible instead of depending on global variables.
