### ISSUE TITLE
[models] Functionality request: Rendering triangles in 3D

### ISSUE THREAD

**Issue by SolarLune** [raysan5/raylib#582]
Hey, there! I was thinking about 3D in raylib some more, and I came to realize that there was no method for drawing triangles - I was wondering why that is?

**Comment by egonelbre** [comment]
There are `DrawPolyEx` and `LoadModelFromMesh`. You can see `GenMesh*` functions how to construct a `Mesh` (e.g. https://github.com/raysan5/raylib/blob/master/src/models.c#L692)

**Comment by SolarLune** [comment]
Hey, perfect! Thanks for the answers~! Completely missed DrawPolyEx, and didn't think about constructing a mesh myself and then creating a model from it!

**Comment by SolarLune** [comment]
Yo, I'm sorry, but it looks like the DrawPoly functions are for 2D, not 3D. Creating a mesh / model is OK, but that seems like a lot of work to just draw a triangle or two, depending on the application.

Reopening this for now~

**Comment by egonelbre** [comment]
Maybe instead of just triangle in 3D, make it GenMeshPoly for creating planar polygon? It would be consistent with the 2D version.

**Comment by raysan5** [comment]
@egonelbre @SolarLune Added `GenMeshPoly()` in commit https://github.com/raysan5/raylib/commit/7d81e673ed7f399305ae12f69267190ade93064d
