### ISSUE TITLE
raylib 2.0 build problem

### ISSUE THREAD

**Issue by jubalh** [raysan5/raylib#584]
Compiling raylib 2.0 release with:
```
%cmake \
     -DPLATFORM=PLATFORM_DESKTOP \                                                                                                                                                          
     -DSHARED=ON
```

I get:
```
[    6s] /home/abuild/rpmbuild/BUILD/raylib-2.0.0/src/core.c: In function 'InitGraphicsDevice':
[    6s] /home/abuild/rpmbuild/BUILD/raylib-2.0.0/src/core.c:1920:63: error: 'GLFW_TRANSPARENT_FRAMEBUFFER' undeclared (first use in this function); did you mean 'GL_READ_FRAMEBUFFER'?      
[    6s]      if (configFlags & FLAG_WINDOW_TRANSPARENT) glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);     // Transparent framebuffer                                              
[    6s]                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                          
[    6s]                                                                GL_READ_FRAMEBUFFER
```

Not sure why. Is it still trying to use the system version of glfw? With 2.0-rc1 it worked.

**Comment by raysan5** [comment]
It seems it uses system version of GLFW instead of provided one... it's weird... Is system glfw headers in your path?

**Comment by a3f** [comment]
Use `-DPLATFORM=Desktop` instead. If `-DPLATFORM=PLATFORM_DESKTOP` worked before, then it was by chance. From [the wiki article](https://github.com/raysan5/raylib/wiki/CMake-Build-Options):

| **Option**                        | **Description**                                           | Possible Values (first is default)|
|:-----------------------------:|:-----------------------------------------------------:|:------------:|
|`PLATFORM`                     | Platform to build for. | **`Desktop`** `Web` `Android` `Raspberry Pi`|

**Comment by jubalh** [comment]
Thanks @a3f, that helped.
