### ISSUE TITLE
[core] Replace #defines by enum typed

### ISSUE THREAD

**Issue by elfring** [raysan5/raylib#585]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
- [KEY_…](https://github.com/raysan5/raylib/blob/0c631e6b5a917f2d94669d91750e93ac8c960a0d/src/raylib.h#L101)
- [RL_TEXTURE_…](https://github.com/raysan5/raylib/blob/103044926bc904a11c145f1d12cf22001a2c085b/src/rlgl.h#L116)

**Comment by elfring** [comment]
* Are enumeration identifiers better usable for software debugging than these preprocessor symbols?
* How do you think about to provide further reusable data types?

**Comment by a3f** [comment]
One nice thing about using enums is that the compiler can statically check all possible values are accounted for in switch statements. This is not only useful in raylib, but for user code as well.

> Are enumeration identifiers better usable for software debugging than these preprocessor symbols?

You can include information about debug symbols with `gcc -g3`, but if your print an `int`, he compiler won't tell you that corresponds to `MACRO` unlike an `enum`.

**Comment by raysan5** [comment]
Thanks for the point @a3f, yes, some defines could be turned into enums.

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/raylib/commit/5086c60e2f3f7d70365e36af390e993fc62a2d1b.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/raysan5/raylib/commit/5086c60e2f3f7d70365e36af390e993fc62a2d1b "Replaced #defines by enums").

**Comment by elfring** [comment]
Can [any more enumerations](https://github.com/raysan5/raylib/blob/8b75a1a990baa6f4cbd0ad0b5dfc06ef6448ac89/src/rlgl.h#L117 "Update candidate") become helpful?
