### ISSUE TITLE
[build] Error compiling raylib examples in macOS 10.13 using clang 9.1.0

### ISSUE THREAD

**Issue by pamarcos** [raysan5/raylib#588]
I faced the following issue when compiling raylib in macOS 10.13.6 using clang 9.1.0:

```
cmake -H. -Bbuild -GNinja
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /usr/local/Cellar/ccache/3.4.2/libexec/cc
-- Check for working C compiler: /usr/local/Cellar/ccache/3.4.2/libexec/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Cellar/ccache/3.4.2/libexec/c++
-- Check for working CXX compiler: /usr/local/Cellar/ccache/3.4.2/libexec/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_THOSE_TOGGLES
-- Performing Test COMPILER_HAS_THOSE_TOGGLES - Success
-- Testing if -Werror=pointer-arith can be used -- compiles
-- Testing if -Werror=implicit-function-declaration can be used -- compiles
-- Testing if -fno-strict-aliasing can be used -- compiles
-- Testing if file system supports symlinks
-- Testing if file system supports symlinks -- supported
-- Setting build type to 'Debug' as none was specified.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
-- Using Cocoa for window creation
-- Compiling with the flags:
--   PLATFORM=PLATFORM_DESKTOP
--   GRAPHICS=GRAPHICS_API_OPENGL_33
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - found
-- Looking for QueryPerformanceCounter
-- Looking for QueryPerformanceCounter - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/pablo/Repos/raylib/build
```
```
cmake --build build
...
/usr/local/Cellar/ccache/3.4.2/libexec/cc -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith  -g -Wl,-search_paths_first -Wl,-headerpad_max_install_names  examples/CMakeFiles/rlgl_standalone.dir/others/rlgl_standalone.c.o  -o examples/rlgl_standalone  release/libraylib.a -F/System/Library/Frameworks -framework OpenGL -framework OpenGL release/external/glfw/src/libglfw3.a -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo && :
FAILED: examples/rlgl_standalone
duplicate symbol _rlLoadIdentity in:
    examples/CMakeFiles/rlgl_standalone.dir/others/rlgl_standalone.c.o
    release/libraylib.a(core.c.o)
duplicate symbol _IsVrSimulatorReady in:
    examples/CMakeFiles/rlgl_standalone.dir/others/rlgl_standalone.c.o
    release/libraylib.a(core.c.o)
duplicate symbol _rlPopMatrix in:
    examples/CMakeFiles/rlgl_standalone.dir/others/rlgl_standalone.c.o
    release/libraylib.a(core.c.o)
duplicate symbol _rlPushMatrix in:
    examples/CMakeFiles/rlgl_standalone.dir/others/rlgl_standalone.c.o
    release/libraylib.a(core.c.o)
...
```
The compiler call uses ccache, but it will end up calling this one:
```
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Long story short, the linker complains about duplicate symbols. Which is understandable taking into account that `rlgl_standalone.c` defines the following to include the `rlgl` implementation, which is already into the static library `libraylib.a` (since `core.c` also defines `RLGL_IMPLEMENTATION`).

```
#define RLGL_IMPLEMENTATION
#define RLGL_STANDALONE
#include "rlgl.h"               // OpenGL 1.1 immediate-mode style coding
```

I wonder why none of the ther OS-compiler combinations complain about the same. Commenting out the `#define RLGL_IMPLEMENTATION` in `rlgl_standalone.c` can be used as a workaround for now, but that's not the proper fix.

You should be able to reproduce the same issue if you specify in your `.travis.yml` a newer toolchain for macOS. Check out https://docs.travis-ci.com/user/reference/osx#OS-X-Version. `osx_image: xcode9.4` is the one that should give you the same results I have.

**Comment by a3f** [comment]
> You should be able to reproduce the same issue if you specify in your .travis.yml a newer toolchain for macOS. Check out https://docs.travis-ci.com/user/reference/osx#OS-X-Version. osx_image: xcode9.4 is the one that should give you the same results I have.

I did that here: https://travis-ci.org/a3f/raylib/jobs/407514783, but didn't get any build errors.

> I wonder why none of the ther OS-compiler combinations complain about the same.

The ability to provide own definitions for symbols in libraries later on on the command-line is usual for UNIX linkers.

> Commenting out the #define RLGL_IMPLEMENTATION in rlgl_standalone.c can be used as a workaround for now, but that's not the proper fix.

Ye, proper fix would be not linking against raylib at all.

**Comment by pamarcos** [comment]
>I did that here: https://travis-ci.org/a3f/raylib/jobs/407514783, but didn't get any build errors.

Thanks for the quick response. I just tried configuring the project using `-DMACOS_FATLIB=ON -DSTATIC=ON -DSHARED=ON -DBUILD_EXAMPLES=ON -DBUILD_GAMES=ON` just as Travis CI and it works. The issue seems to pop up whenever you remove the `-DSHARED=ON` part. So, it seems creating just the static version is the one that fails, at least to me. 

Can you try removing the `-DSHARED=ON` part to see whether the issue is reproduced in Travis?

**Comment by pamarcos** [comment]
I'm trying to submit a PR to fix the compilation of the HTML5 examples using CMake and it also complains trying to link `rlgl_standalone`. Check it out: https://travis-ci.org/raysan5/raylib/jobs/407748248

```
[ 59%] Linking C executable rlgl_standalone.html
cd /src/build/examples && /opt/cmake/bin/cmake -E cmake_link_script CMakeFiles/rlgl_standalone.html.dir/link.txt --verbose=1
/usr/local/bin/emcc  -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith  -Os -s USE_GLFW=3 -s ASSERTIONS=1 -s WASM=1 -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1 --shell-file /src/templates/web_shell/shell.html -g   CMakeFiles/rlgl_standalone.html.dir/others/rlgl_standalone.c.o  -o rlgl_standalone.html -Wl,-rpath,/src/build/release -rdynamic ../release/libraylib.so.2.0.0 
error: Linking globals named 'rlMatrixMode': symbol multiply defined!
ERROR:root:Failed to run llvm optimizations: 
examples/CMakeFiles/rlgl_standalone.html.dir/build.make:95: recipe for target 'examples/rlgl_standalone.html' failed
make[2]: *** [examples/rlgl_standalone.html] Error 1
```

**Comment by a3f** [comment]
> I thought that was only true for shared libs

You're right. I missed that this is about static libraries.

Hmm, I guess #471 could make this easier to fix, because it gets rid of `link_libraries_to_executable`...

An easy way out could either be:

- Always build static and shared libraries
- Remove `rlgl_standalone` from being built as part of the examples...

**Comment by raysan5** [comment]
I think `rlgl_standalone` should better be removed from examples, it's a special use case, not raylib dependant.

**Comment by a3f** [comment]
I added a new Xcode (9.4.1) macOS configuration in b7d8c62bfd2e985bcf53baec770a9392fe63ebfc for which I disabled the shared build in order to catch such problems in future.
I removed `rlgl_standalone` from the buildable examples.

**Comment by pamarcos** [comment]
Nice, thank you both for your support 👍
