### ISSUE TITLE
[rlgl] API functions for binding shader textures

### ISSUE THREAD

**Issue by TheLumaio** [raysan5/raylib#594]
The ability to bind multiple textures to shaders would be an extremely useful feature, especially for post processing shaders that require noise.

**Comment by TheLumaio** [comment]
That looks like it's just for rendering models though, not screen space effects. Unless I'm missing something.
something like this is what I mean:
```C
BeginTextureMode(screenspace_texture);
// the entire scene, ui, etc
EndTextureMode();

BeginShaderMode(screenspace_shader);
// bind some noise texture to screenspace_shader
// bind some other effect texture to screenspace_shader
// draw screenspace_texture
EndShaderMode();
```

**Comment by raysan5** [comment]
Related to this issue, `SetShaderValue()` has been simplified on commits https://github.com/raysan5/raylib/commit/55f8dbc755c2e31d2112e71439fef0d31e8090a6 and https://github.com/raysan5/raylib/commit/64fd131ed584d063e4f1ee63050d19ca8413a32a.

**Comment by raysan5** [comment]
Related issue pop-up. When using `BeginShaderMode() / EndShaderMode()` combined with shapes/textures drawing, `DrawBuffersDefault()` only **activates** and **binds** 1 texture channel. If current shader requires more than 1 texture, it is not passed.

Some function is required to pass additional `sampler2D` texture to the shader... not that trivial... Shader location can be checked to set uniform but active texture id should be manually passed by the user...

Need some time to figured it out...

**Comment by raysan5** [comment]
As stated in the last post, supporting multiple shader textures for default shader and current batching system would imply redesigning it... at the moment that's out of scope.

Still, multiple shader textures are supported for custom models drawing. `SetShaderValueTexture()` was added in commit https://github.com/raysan5/raylib/commit/9282b8ba83909b353fd34a9f584597338c1928bd for convenience.

**Comment by Louis-DR** [comment]
Small question, can you then only pass sampler2d for 3d models ? I wrote a color swap shader with a texture as a swatch (red and green components of texture0 used to index the swap swatch sampler2d texture). I'm trying to use SetShaderValueTexture but it doesn't seem to work. Is there any way to make it work ? (I'm half way overhauling to switch to raylib)

**Comment by raysan5** [comment]
@Louis-DR `Model` structure contains `meshes` that actually can be any kind of data, 2d or 3d. Just need to fill the structures with the desired data and set the shader with all the texture sampler2d required.

**Comment by Louis-DR** [comment]
@raysan5 Thank you very much ! I made it work with Meshes. If anyone is struggling, here it is :
```
Model model = LoadModelFromMesh(GenMeshPlane(1, 1, 1, 1));
Texture texture0 = LoadTexture("texture0.png");
Texture texture1 = LoadTexture("texture1.png");
model.materials[0].maps[0].texture = texture0;
model.materials[0].maps[1].texture = texture1;
model.materials[0].shader = LoadShader(0,"color_swap.fs");
```
And they are then available as `texture0` and `texture1` in the fragment shader.
It's unfortunate that it is that inconvenient, as it requires switching the whole pipeline to use 3D cameras, models etc. Also, the material shader is applied after the texture filter, instead of before, which can cause problem if your shader works with original pixel colors or if it works on edges. I guess it's a niche problem and can be worked around so it's no big deal.
