### ISSUE TITLE
[core] Support redirecting TraceLog to custom logging system

### ISSUE THREAD

**Issue by pamarcos** [raysan5/raylib#595]
As a user, I'd like to have full control of the logging system. e.g. I may want to log in both console and file. Or use my own format with timestamp, thread id, etc.

At the moment, `TraceLog` simply logs the `msgType` (aka `INFO`, `ERROR`, etc) + the text. While I could implement my own logging system for my stuff, raylib would still output everything just to the console. I'd like to sink everything raylib has to say into my own logging mechanism.

To do such thing, the easiest way I can think is using a callback (if previously set) that `TraceLog` calls instead of using its own implementation.

I have created a possible solution in ~15LOC in `utils.c`. The usage from the user point of view would be as follows:

```
void logCustom(int msgType, const char *text, ...)
{
    va_list args;
    va_start(args, text);
    vprintf(text, args);
    printf("\n");
    va_end(args);
}

 int main()
 {
    SetTraceLogCallback(logCustom);
...
```

**Comment by raysan5** [comment]
Just for reference, I've checked [current Android log data redirection](https://github.com/raysan5/raylib/blob/master/src/utils.c#L126)... it just uses [Android log system](https://developer.android.com/ndk/reference/group/logging), but this system does not offer any redirection mechanism like the proposed one...

My main concern was callback usage... but I imagine it's ok... any opinions in the room?

**Comment by a3f** [comment]
> To do such thing, the easiest way I can think is using a callback (if previously set) that TraceLog calls instead of using its own implementation.

Sounds good to me.

**Comment by a3f** [comment]
Closed with #597.

**Comment by raysan5** [comment]
thanks, I still want ti review some formating details on the PR...

**Comment by a3f** [comment]
Ah, sorry for the premature merge...

**Comment by raysan5** [comment]
hahaha... no worries! :D
