### ISSUE TITLE
[models] Support multiple Mesh/Materials for one Model?

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#596]
Working on models animation I noticed `IQM` model format could provide multiple separate meshes in one model, also, every `Mesh` could have its own `Material`.

`OBJ` file format also could contain multiple meshes with custom material per mesh...

I'm considering the option to support multiple `Mesh`/`Materials` for a single `Model`, it will require some code changes and it would add some complexity to `Model` struct.

What do you thing? Does it worth it?

**Comment by TheLumaio** [comment]
Definitely worth it. It can be a lot easier to manage models in modeling programs if you keep different parts separate and prevents having to do the extra step of grouping them together before exporting.
Also this would make exporting entire scenes or game maps as a single model a lot easier.

**Comment by raysan5** [comment]
Ok, this new feature requires some work... `struct Model`should be redesigned.

Current `Model` struct:
```c
typedef struct Model {
    Mesh mesh;              // Vertex data buffers (RAM and VRAM)
    Matrix transform;       // Local transform matrix
    Material material;      // Shader and textures data
} Model;
```
New model struct, multiple meshes supported and also animated data:
```c
typedef struct Model {
    Matrix transform;       // Local transform matrix
    
    int meshCount;          // Number of meshes
    Mesh *meshes;           // Meshes array

    int materialCount;      // Number of materials
    Material *materials;    // Materials array
    
    int *meshMaterialIds;   // Mesh materials ids

    // Animation required data
    int jointCount;         // Number of joints (and keyposes)
    Joint *joints;          // Mesh joints (bones)
    Pose *poses;         // Mesh key-poses by joint
} Model;
```
Animation data requires adding the following structs:
```c
typedef struct Joint {
    unsigned char name[JOINT_NAME_LENGTH];
    int parent;
} Joint;

typedef struct Pose {
    Vector3 translation;
    Quaternion rotation;
    Vector3 scale;
} Pose;
```
Those structs are taken from IQM loader example and represent `Bones` and `Transform` for each bone, maybe it could be simplified and renamed for consistency with future animated formats...

One possible redesign/rename (not sure if I'm mixing data):
```c
typedef struct Bone {
    unsigned char name[JOINT_NAME_LENGTH];
    Transform pose;
    int parent;
} Bone;

typedef struct Transform {
    Vector3 translation;
    Quaternion rotation;
    Vector3 scale;
} Transform ;
```

**What do you think? Any expert on animated models that could provide some feedback?**

**Comment by culacant** [comment]
As in discord, my 0.02.
One advantage of this would be that raylib seems to play nicer with one big mesh than with multiple smaller meshes. It should also keep API changes to a minimum since your meshes still only have one big array of vertex data.
The big disadvantage is that its pretty ugly.
```c
typedef struct Model {
    Mesh mesh;              // Vertex data buffers (RAM and VRAM)
    Matrix transform;       // Local transform matrix
    int materialCount;
    Material *material;      // Shader and textures data
    int meshCount;   
    Part *parts;                // prolly needs a rename
} Model;
```
The part array would contain the first vertex of the mesh and the number of vertices in the mesh part, aswel as the material id.
```c
typedef struct Part {
    unsigned int offset;
    unsigned int count;
    int Material;
} Part;
```
And then in rlDrawMesh you would draw 1 part at a time and switch between the materials with glBindTexture.

Other than that the bone struct should be fine, from my decidedly non-expert point of view.

**Comment by raysan5** [comment]
Working on this issue in commit https://github.com/raysan5/raylib/commit/a643dc4ca016ce5791608852ab1357f2d94ebe9b and following ones...

**Comment by raysan5** [comment]
`Model` struct and required functions have already been adapted to support multiple meshes and multiple materials, now work resides in `LoadOBJ()`, `LoadIQM()` and `LoadGLTF()` functions to properly populate its data to new `Model`struct.

I'm closing this issue for now.
