### ISSUE TITLE
[BINDING] raylib-Ruby

### ISSUE THREAD

**Issue by D3nX** [raysan5/raylib#598]
Hello guy ! 
I'm currently working on raylib binding for Ruby (using [ffi](https://github.com/ffi/ffi))

Actually, the 3D FPS example, and some 2D others examples (I mean raylib example) works pretty well in ruby, I will (I hope) soon open a Github, and let you test & use raylib with ruby !

I'm just a bit scared about porting the audio lib, so I will do that in last I think...

(PS: You can see the screenshot of the lib working on the raylib discord server ;) )

**Comment by raysan5** [comment]
hey @D3nX! what's the state of this binding? 

I already added the link to [raylib-Ruby](https://github.com/D3nX/raylib-ruby-ffi) in the [CONTRIBUTING](https://github.com/raysan5/raylib/blob/master/CONTRIBUTING.md) file.

**Comment by D3nX** [comment]
Hey @raysan5 !
Okay, so let me explain. I'm myself of some projects at the moment and I think I launched too much stuff at the same time... One one hand my two youtubes channel, and on the other hand my personnal projects adding to that my awful new high school which take me so much time and stress... That's why I don't frequently post updates about the binding itself, still I made some progress since (drag & drop have been added not a long time ago) and some other features.. But still I don't yet release what I've done since because I don't implemented a lot of stuff and they may not be ready.

But of course I don't stop working on ! It will just take more time than expected... Sorry for that :( But another things that slow down me, is that I definitively need a 32 and 64 bit dll of it and also a dll that contains all audio functions, but I need to figure out how to build them... Thank you for your comprehension ^^

**Comment by raysan5** [comment]
Hey @D3nX! No stress and no worries! Take all the time your need! :D

**Comment by raysan5** [comment]
@D3nX If you don't mind, just closing this issue. I'll try to give more visibility to the bindings listing them in raylib webpage!
