### ISSUE TITLE
Typo on cheatsheet: "Timming"

### ISSUE THREAD

**Issue by DevJac** [raysan5/raylib#600]
The cheatsheet at http://www.raylib.com/cheatsheet/cheatsheet.html says `// Timming-related functions`. This is a typo, "Timming" should have only one "m". The correct spelling is "Timing".

**Comment by raysan5** [comment]
Corrected on commit https://github.com/raysan5/raylib/commit/0cf92c59d7d91aa3d1906fe7b85c3078e4520845 and https://github.com/raysan5/raylib.com/commit/730072ca6ec9b363eae2058456ba9b25f4b352d3
