### ISSUE TITLE
[build] Incorrect CMake config causes example to fail to compile

### ISSUE THREAD

**Issue by ethan-tqa** [raysan5/raylib#606]
Tested with MSVC 2017 internal CMake support, all examples would fail to compile due to them being unable to locate raylib.h. This one additional line will fix the problem:
`include_directories("../release/include")`
when added to examples/CMakeLists.txt

**Comment by a3f** [comment]
Could you submit a PR?

**Comment by ethan-tqa** [comment]
Come to think of it, that is not neccessary the right solution. Why not just reference the header from souce folder? The problem may come when user uses standalone CMake but specify custom build output folder.

**Comment by a3f** [comment]
> The problem may come when user uses standalone CMake but specify custom build output folder.

Ye, that the `build` directory is hardcoded is unfortunate. #471 could fix that...

**Comment by a3f** [comment]
I will merge #608 soon that should fix this problem by removing the hardcoded paths. Please test and report if it fixes your issue

**Comment by ethan-tqa** [comment]
Hey there, it appears to have solved the issue after I pulled the newest commit

**Comment by a3f** [comment]
:)
