### ISSUE TITLE
Typo in cheatsheet: SetCameraMode has no return value

### ISSUE THREAD

**Issue by DevJac** [raysan5/raylib#611]
Just a small omission I noticed.

In the cheatsheet there is the following line: `SetCameraMode(Camera camera, int mode);`

Notice that the line does not specify the return type of `SetCamerMode`.

Is the source for the cheatsheet available anywhere? If so I can fix things like this myself and just submit pull requests?

**Comment by raysan5** [comment]
hey! thanks for pointing this issue! Corrected in commit https://github.com/raysan5/raylib.com/commit/69605647b65ee3dab54bc5dc09a62c6bf9422631

Just in case, for future issues or webpage improvements (probably required), webpage is available here: https://github.com/raysan5/raylib.com
