### ISSUE TITLE
[BINDING] Python3 binding for raylib: raylibpy

### ISSUE THREAD

**Issue by overdev** [raysan5/raylib#614]
Hi,

as I mentioned in the raylib forum a few day ago (80'sJay username), I'm trying to write a Python3.3+ (written in Python 3.7) binding for raylib 2.0:

[raylibpy](https://github.com/overdev/raylibpy)

The binding is done with ctypes. I would prefer Cython if knew how to use it properly.

It is very rough at the moment: type convertions need to be refined, test is non existent (currently I have only an old Windows laptop that has incomplete OpenGL 3.3 support (shame on me), so some advanced features of raylib are beyound its capabilities). I'll be translating the examples and templates in the next days as a preliminary test of the binding.

**The package is very far from being production ready**, so there's no `pip -m install raylibpy` command available yet. Also, the `setup.py` _may require_ some ajustements here and there for the installation to run error free.

For those interested in giving any feedback on MacOS and Linux systems, I can't be grateful enough.

Hope you guys find it useful.

**Comment by raysan5** [comment]
That's great @overdev! We will keep an eye on it! :D

**Comment by raysan5** [comment]
hey @overdev! what's the state of this binding? Is it completely functional?

I already added the link to [raylib-pi](https://github.com/overdev/raylib-py) in the [CONTRIBUTING](https://github.com/raysan5/raylib/blob/master/CONTRIBUTING.md) file.

**Comment by overdev** [comment]
I'm still not able to test 100% of the library, but the single issue I got so far was related to a integration confusion I made (wich I fixed already). I'm relying more on user feedback than on my onw use of the library, but all the features my notebook suports are working as expected (I'm not very proud of myself by saying this, but... :cry:).

In the Python Package Archive, raylib-py has 1.5k downloads in this first month (20 downloads per month at best); you can check the numbers on [PePy website](https://pepy.tech/project/raylib-py). I believe people are still getting familiar to raylib-py: this might explain the low feedback or maybe is too soon.

**Comment by raysan5** [comment]
@overdev I'm closing this issue. Just created a set of icons for icon, [raylib-py.zip](https://github.com/raysan5/raylib/files/2715252/raylib-py.zip). Hope you like them! :)

![raylib-py_256x256](https://user-images.githubusercontent.com/5766837/50522075-5c044a00-0ac9-11e9-8db1-3e28b3ccffe3.png)
