### ISSUE TITLE
templates not compiling

### ISSUE THREAD

**Issue by novemberisms** [raysan5/raylib#617]
I can't get the sample templates to compile. Specifically the standard game template. I haven't tried the others yet. On notepad++ when I hit F6 while the standard_game.c is open, I choose raylib_compile_execute but it fails. What should I do?

**Comment by raysan5** [comment]
choose raylib_makefile script. some templates require compiling multiple files and use a Makefile build system, a bit mote complex than compiling just one .c

**Comment by novemberisms** [comment]
Thanks a lot! I can't believe it's that simple!

Can you enlighten me on something? When I try running the makefile on notepad++ everything works fine. But when I try using VSCode and using the terminal there to run `mingw32-make` it works for a bit, but then gives me the error `rlgl.c: undefined reference to __ms_vprintf`. Why is it different based on which text editor I use, and how can I get VSCode to work?

You're amazing btw. Keep up the great work.

**Comment by raysan5** [comment]
sorry, don't know why it happens, I didn't use the VSVode template... seems related to MSVC standard C library but don't know...

**Comment by raysan5** [comment]
Closing this issue.
