### ISSUE TITLE
[build] Use CMake standard variables?

### ISSUE THREAD

**Issue by QuLogic** [raysan5/raylib#626]
Can [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) be used instead of `SHARED`/`STATIC`?

And possibly `WITH_PIC` could be replaced by [`CMAKE_POSITION_INDEPENDENT_CODE`](https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html).

**Comment by raysan5** [comment]
I think it's a good idea to use standard naming variables for CMake.

Probably @a3f could take a look to this issue.

**Comment by a3f** [comment]
I think there's value in allowing shared as well as static builds in the same run and would rather keep it this way. Feel free to open a PR about adding `BUILD_SHARED_LIBS` as an alias for `SHARED` though.

`MAKE_POSITION_INDEPENDENT_CODE` should work already, doesn't it?

**Comment by raysan5** [comment]
@QuLogic could you send a PR with @a3f proposed improvement?

**Comment by a3f** [comment]
`CMAKE_POSITION_INDEPENDENT_CODE` seems to be working as expected.
`BUILD_SHARED_LIBS` can now be used as well to build either static or shared library.
I am keeping `SHARED` and `STATIC` so that building both in the same go is still possible.

**Comment by QuLogic** [comment]
BTW, with respect to building both: https://youtu.be/sBP17HQAQjk?t=488
