### ISSUE TITLE
[core] Missing key definitions for plus/minus keys?

### ISSUE THREAD

**Issue by justinclift** [raysan5/raylib#627]
Trying out the Go binding for raylib, and hit the problem of there being no definitions for the plus/minus keys on the keypad.

https://github.com/raysan5/raylib/blob/506b7b8d7c2e367d61ee92a77b54fb115a566173/src/raylib.h#L104-L182

It turns out they're not here either. :wink:

I can make a PR adding them (here, then in raylib-go), but I'm not sure where the numeric values are coming from.  They don't seem to be keyboard scan codes, which was my first thought.

Ideas? :smile:

**Comment by justinclift** [comment]
Ahhhh, glfw looks to be the source:
```
$ grep -ri "KEY_SPACE" *
external/glfw/include/GLFW/glfw3.h:#define GLFW_KEY_SPACE              32
external/glfw/src/cocoa_init.m:    _glfw.ns.keycodes[0x31] = GLFW_KEY_SPACE;
external/glfw/src/mir_init.c:    _glfw.mir.keycodes[KEY_SPACE]      = GLFW_KEY_SPACE;
external/glfw/src/input.c:    if (key < GLFW_KEY_SPACE || key > GLFW_KEY_LAST)
external/glfw/src/input.c:    if (key < GLFW_KEY_SPACE || key > GLFW_KEY_LAST)
external/glfw/src/wl_init.c:    _glfw.wl.keycodes[KEY_SPACE]      = GLFW_KEY_SPACE;
external/glfw/src/win32_init.c:    _glfw.win32.keycodes[0x039] = GLFW_KEY_SPACE;
external/glfw/src/win32_init.c:    for (key = GLFW_KEY_SPACE;  key <= GLFW_KEY_LAST;  key++)
external/glfw/src/x11_init.c:        case XK_space:          return GLFW_KEY_SPACE;
raylib.h:#define KEY_SPACE            32
```

So, further looking shows this:

#### external/glfw/src/x11_init.c:
```
        case XK_KP_Subtract:    return GLFW_KEY_KP_SUBTRACT;
        case XK_KP_Add:         return GLFW_KEY_KP_ADD;
        ...
        case XK_minus:          return GLFW_KEY_MINUS;
        case XK_equal:          return GLFW_KEY_EQUAL;
```

and:

#### external/glfw/include/GLFW/glfw3.h
```
#define GLFW_KEY_MINUS              45  /* - */
...
#define GLFW_KEY_EQUAL              61  /* = */
...
#define GLFW_KEY_KP_SUBTRACT        333
#define GLFW_KEY_KP_ADD             334
```

I'll make a PR with something suitable. :smile:

**Comment by raysan5** [comment]
Hi @justinclift! Thanks for checking this issue!

Key definitions come from [GLFW](http://www.glfw.org/docs/latest/group__keys.html).

**Comment by raysan5** [comment]
Close with PR #628.
