### ISSUE TITLE
[models] Feature request: Support import of Collada

### ISSUE THREAD

**Issue by justinclift** [raysan5/raylib#630]
Looking at the file formats presently supported for loading objects, it seems to be .obj and maybe some .mtl in there too.

If people are wondering what other file formats would be useful... then [Collada](https://en.wikipedia.org/wiki/COLLADA) might be useful.  Models in Collada format can contain additional info - eg [physics](https://en.wikipedia.org/wiki/COLLADA#Physics) - for the pieces, which could be useful for kinematics/animation (#560).

**Comment by justinclift** [comment]
Ahh, there's already mention of it in https://github.com/raysan5/raylib/issues/560#issuecomment-406982970, but as DAE instead.  Oh well. :wink:

**Comment by raysan5** [comment]
@justinclift supporting additional model formats is welcome but unfortunately most popular formats are quite bloated and complex to read, usually requiring bloated libraries or sdks to read them...

Despite that, it would be great to support at least FBX format if there was a simple single-file header-only C library... but as far as I know there us only a C++ library...
