### ISSUE TITLE
NppExec Scripts not saving on execute

### ISSUE THREAD

**Issue by zrobotics** [raysan5/raylib#632]
Didn't want to open as a PR, as this is more of a workflow issue and not a bug. The provided scripts do not save before compiling, which not only requires extra keystrokes to save the file but can cause confusion when forgetting to save the file before compiling. I realize that NppExec has an option to save all files, but I've always found this to be a very dangerous option. Since the current scripts already overwrite an existing executable, I see no reason the scripts should not save the file in case the user has unsaved changes. This can be accomplished by appending:
```
echo > Saving Current File
echo -------------------------------------
npp_save
echo
```
to the script `raylib/projects/Notepad++/npes_saved.txt`, which is consistent w/ the rest of the script's output. I only changed `basic_c_compilation` and `raylib_compile_execute`, since it didn't seem necessary when building the entire library source and creating makefiles.
[npes_saved.txt](https://github.com/raysan5/raylib/files/2303663/npes_saved.txt)

**Comment by raysan5** [comment]
Improvement added in commit https://github.com/raysan5/raylib/commit/a2de3d99e0897ccd3fa087a6e676a3e07cf1e3a6, it would be ready on next release!
