### ISSUE TITLE
[core] `GetFileName` and `GetDirectoryPath` do not support Unix paths

### ISSUE THREAD

**Issue by dtcristo** [raysan5/raylib#634]
When using Unix style paths with `GetFileName` we get incorrect results, and in the case of `GetDirectoryPath` we get a SIGSEGV crash.

After looking at the source I noticed you're doing a search through the string for `\` characters used on Windows. Is it possible to check `defined(_WIN32)` and use the current functionality, but on other platforms search for `/` instead?

Also, the crash in `GetDirectoryPath` will also occur when there are no slashes in the provided path.

Below is example code demonstrating the issue and the crash:
```c
#include <stdio.h>
#include "raylib.h"

int main()
{
    const char *fileName = GetFileName("C:\\hello\\test.c");
    printf(fileName);
    printf("\n");
    // Prints: test.c

    const char *fileNameUnix = GetFileName("/hello/test.c");
    printf(fileNameUnix);
    printf("\n");
    // Prints: /hello/test.c
    // Should print: test.c (on Unix platforms)

    const char *directory = GetDirectoryPath("C:\\hello\\test.c");
    printf(directory);
    printf("\n");
    // Prints: C:\hello

    const char *directoryUnix = GetDirectoryPath("/hello/test.c");
    // Program crashes here with:
    // terminated by signal SIGSEGV (Address boundary error)
    printf(directoryUnix);
    printf("\n");
    // Should print: /hello (on Unix platforms)

    return 0;
}
```

**Comment by a3f** [comment]
I wouldn't make slash support conditional on `!defined(_WIN32)`. Just support both, so the user doesn't have to worry about it.
