### ISSUE TITLE
Garbled text output when unloding font

### ISSUE THREAD

**Issue by FrankRuben** [raysan5/raylib#638]
Hi,

I'm trying to cobble together a minimal (Gambit-) Scheme binding for raylib. (Version used: Git clone from last week, according to `CHANGELOG`: "Release: raylib 2.0 (July 2018)"; running on "Linux 4.4.0-131-generic #157-Ubuntu SMP x86_64 GNU/Linux".) Because of some limitation of the FFI, I tried to load fonts into a stack and to just unlock each font after use. Running this approach I found that any text drawn with a font that is unloaded during the program run looks garbled - meaning that the text output is missing pixels.

In order to simplify reproduction, I wrote the small test program in C appended below, which is showing the same behaviour. To reproduce:

- Running the program without an argument will not unload the font, and the text on the 3rd line is shown just fine - as it's happening for the first two lines.
- Running the program with at least one argument (any value) will unload the font, and now the 3rd line will miss pixels.

Is this the expected behaviour and do I have to avoid unloading fonts during program run or what would I have to do.

Thanks in advance - and btw thanks for that great library! -,
    Frank

- Compiled using:  `gcc -o test_unloadfont test_unloadfont.c -s -I$HOME/localsrc/raylib/src/ -L$HOME/localsrc/raylib/release/libs/linux -lraylib -lGL -lm -lpthread -ldl -lrt -lX11`
- Run using: `LD_LIBRARY_PATH=$HOME/localsrc/raylib/release/libs/linux ./test_unloadfont [arg]` 

``` C
#include <unistd.h>
#include <raylib.h>

void main(int argc, char *argv[]) {
  InitWindow(400, 400, "test_unloadfont");
  SetTargetFPS(60);

  Font fix_font = LoadFont("/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf");
  for (int i = 0; i < 5 && WindowShouldClose() == false; i++) {
    BeginDrawing();
    ClearBackground(GetColor(0xFEFEFEFF));
    DrawText("DrawText", 20, 20, 20, GetColor(0xFF0000FF));
    {
      Vector2 position = { (float)20, (float)50 };
      DrawTextEx(fix_font, "DrawTextEx: fix_font", position, 20, 2, GetColor(0x00FFFFFF));
    } {
      Font dyn_font = LoadFont("/usr/share/fonts/truetype/ubuntu-font-family/UbuntuMono-B.ttf");
      Vector2 position = { (float)20, (float)70 };
      DrawTextEx(dyn_font, "DrawTextEx: dyn_font", position, 20, 2, GetColor(0x0000FFFF));
      if (argc > 1) UnloadFont(dyn_font);
    }
    EndDrawing();
    sleep(5);
  }
  UnloadFont(fix_font);
  CloseWindow();
}
```

**Comment by raysan5** [comment]
Hi @FrankRuben, it's expected behaviour, actually it's a miracle that something is drawn on screen because all drawing actually happens inside EndDrawing(), all you do before is registering data to draw and textures to use, so, on real drawing, there is not font texture available!

My recommendation would be loading all required fonts at beginning and don't unload them until the end... there are other ways to manage content inside while loop but require some more work...

**Comment by FrankRuben** [comment]
Thanks for the quick reply - that explains the behaviour; the garbled output might be caused by not all memory is overridden after being freed. I'll change my font-handling accordingly - and will spend some more time reading the docs instead of taking the high-road by just reading available sources ;)
