### ISSUE TITLE
GL_SELECT

### ISSUE THREAD

**Issue by dmalves** [raysan5/raylib#64]
Is i possible to select a 3d  object (a cube for example) using GL_SELECT mode?

**Comment by raysan5** [comment]
Hello @dmalves,

GL_SELECT method for object picking is very old and deprecated in newer OpenGL versions. It could even be possible that some new graphic cards don't support that functionality at all. So, that functionality is not available in raylib and won't be added using GL_SELECT.

A newer picking method is being developed but, unfortunately, it's not working yet. You can see the related issue https://github.com/raysan5/raylib/issues/35
