### ISSUE TITLE
[build] x86 Android

### ISSUE THREAD

**Issue by alexevane** [raysan5/raylib#640]
Hi, Would love to see this framework support for x86 for android soon. 

I've been tried with difficulties and no success.

**Comment by raysan5** [comment]
No plans for the moment but let's see in a future...

What platforms use Android x86? It seems there isn't lots of devices supporting this arquitecture...

**Comment by a3f** [comment]
> I've been tried with difficulties and no success.

What did you try? What were the problems?

**Comment by alexevane** [comment]
First thing. 
static void SwapBuffers(void);     in core.c will conflict 

> core.c:371:13: error: conflicting types for 'SwapBuffers'
 static void SwapBuffers(void);                          // Copy back buffer to
front buffers
             ^
In file included from D:/MinGW/mingw32/i686-w64-mingw32/include/windows.h:71:0,
                 from H:/sdk/android_toolchain_x86_API21/sysroot/usr/include/EGL
/eglplatform.h:74,
                 from H:/sdk/android_toolchain_x86_API21/sysroot/usr/include/EGL
/egl.h:39,
                 from rlgl.h:588,
                 from core.c:99:
D:/MinGW/mingw32/i686-w64-mingw32/include/wingdi.h:4186:28: note: previous decla
ration of 'SwapBuffers' was here
   WINGDIAPI WINBOOL WINAPI SwapBuffers(HDC);
                            ^
core.c:422:20: warning: 'Sleep' redeclared without dllimport attribute: previous
 dllimport ignored [-Wattributes]
     void __stdcall Sleep(unsigned long msTimeout);      // Required for Wait()
                    ^

**Comment by alexevane** [comment]
I created tool chain for x86 and try to build raylib from src folder 


First thing. 
static void SwapBuffers(void);     in core.c will conflict 

> core.c:371:13: error: conflicting types for 'SwapBuffers'
 static void SwapBuffers(void);                          // Copy back buffer to
front buffers
             ^
In file included from C:/mingw32/i686-w64-mingw32/include/windows.h:71:0,
                 from E:/android_toolchain_x86_API21/sysroot/usr/include/EGL
/eglplatform.h:74,
                 from E:/android_toolchain_x86_API21/sysroot/usr/include/EGL
/egl.h:39,
                 from rlgl.h:588,
                 from core.c:99:
C:/mingw32/i686-w64-mingw32/include/wingdi.h:4186:28: note: previous decla
ration of 'SwapBuffers' was here
   WINGDIAPI WINBOOL WINAPI SwapBuffers(HDC);
                            ^
core.c:422:20: warning: 'Sleep' redeclared without dllimport attribute: previous
 dllimport ignored [-Wattributes]
     void __stdcall Sleep(unsigned long msTimeout);      // Required for Wait()
                    ^

**Comment by a3f** [comment]
Something is probably defining `_WIN32`, which shouldn't be the case on Android. Try to find out where it's coming from.

**Comment by raysan5** [comment]
No plans to support Android x86.
