### ISSUE TITLE
[build] "Undefined symbols for architecture x86_64" Using Atom Text Editor

### ISSUE THREAD

**Issue by z0di4cdev** [raysan5/raylib#642]
I tried running one of the example programs in Atom text editor with the gpp-compiler. I am on Mac-OS. Thank you for your help.
EDIT:

My error is:

Undefined symbols for architecture x86_64:
"_BeginDrawing", referenced from:
_main in Game-1b838e.o
"_ClearBackground", referenced from:
_main in Game-1b838e.o
"_CloseWindow", referenced from:
_main in Game-1b838e.o
"_DrawText", referenced from:
_main in Game-1b838e.o
"_EndDrawing", referenced from:
_main in Game-1b838e.o
"_InitWindow", referenced from:
_main in Game-1b838e.o
"_SetTargetFPS", referenced from:
_main in Game-1b838e.o
"_WindowShouldClose", referenced from:
_main in Game-1b838e.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by raysan5** [comment]
Which are the undefined symbols? I need more info please!

**Comment by TheLumaio** [comment]
This is unrelated to raylib.
You need to link the library and all the system dependencies. Also be sure you're using a version of the library built for whatever architecture your compiler supports.

**Comment by raysan5** [comment]
Thanks for the point @TheLumaio. Closing the issue.
