### ISSUE TITLE
RPi installation instructions need updating.

### ISSUE THREAD

**Issue by carlsmith** [raysan5/raylib#643]
Using Stretch on a RPi 3B+, I cloned this repo, changed the working directory to `raylib/src` and ran `make PLATFORM=PLATFORM_RPI`. This was the error message:

``` plain
In file included from external/mini_al.h:8894:28: fatal error: alsa/asoundlib.h: No such file or directory...
```

I fixed it by running `sudo apt-get install libasound-dev`, then carrying on with the instructions in the wiki. However, `apt-get` selected `libasound2-dev` automatically, so the command should be `sudo apt-get install libasound2-dev`.

After that, everything seems fine. I built and ran the `core_2d_camera` and `core_basic_window` examples without any trouble at least.

I haven't updated the wiki, just incase I didn't understand something (this is all new to me).

**Comment by raysan5** [comment]
Hey @carlsmith! Thanks for reporting!

Including @mackron to be aware of this issue.

**Comment by mackron** [comment]
Darn, I was debugging stuff and accidentally left that #include in there. That's my bad. mini_al does not depend on ALSA development packages so no need to update the wiki. Instead I've pushed a fix to the master branch of mini_al. @raysan5 you can go ahead and copy that over (I figure that will be easier than doing a pull request).

**Comment by raysan5** [comment]
Thanks for the update @mackron. Already updated mini_al on raylib in commit https://github.com/raysan5/raylib/commit/5b09630d45ec5bfaa301c5dc0f27c0d44f57bbb8.

**Comment by carlsmith** [comment]
Thanks guys. Nice one.
