### ISSUE TITLE
[core] Android - How to write to SD Card

### ISSUE THREAD

**Issue by SethArchambault** [raysan5/raylib#644]
Related to #636

I'm trying to write a file on Android, and it sounds like I need to write to the external SD card for this (which is fine because this is for a game that I'm setting up on a single device). Some sources are saying I should just be able to write to the sd card at "/sdcard/" but it's not succeeding. Any idea how I can do this? I imagine if I want to get the folder, I'll need to access the internal data of utils.c, which I'm not sure I can do with editing source code..

**Comment by raysan5** [comment]
I haven't tried it myself but it seems the answer is [here](https://stackoverflow.com/questions/1992953/file-operations-in-android-ndk) and [here](https://stackoverflow.com/questions/41739926/android-jni-saving-to-sd-card).

It could just be a matter of permissions when generating the .APK. You should add the following line in `AndroidManifest.xml`:
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
That is automatically generated [here](https://github.com/raysan5/raylib/blob/master/templates/advance_game/Makefile.Android#L202). And proposed line should be added right after [this one](https://github.com/raysan5/raylib/blob/master/templates/advance_game/Makefile.Android#L207).

After that, just use the regular `fopen()` and `fclose()`, NOT the `android_fopen()` equivalent!

Please, let me know if it works! :)

**Comment by SethArchambault** [comment]
Cool, I did this, but it was still not working.  I decided to pop into adb shell found that the folder was indeed /sdcard/, and I manually created the file that I was trying to create. After I did that, everything worked! So maybe it was some kind of permission issue regarding file creation? 

Thanks!

**Comment by raysan5** [comment]
@SethArchambault Thanks for the feedback! Mmmh... 

Actually, the `AndroidManifest.xml` proposed line is supposed give the required permission... ok, [not really](https://developer.android.com/guide/topics/manifest/uses-permission-element)...

[Here](https://stackoverflow.com/questions/4731314/write-file-to-location-other-than-sdcard-using-android-ndk) some more relevant info. I'll keep investigating...
