### ISSUE TITLE
Default Font Name?

### ISSUE THREAD

**Issue by siavashserver** [raysan5/raylib#645]
Hello! I'd like to use the default font outside raylib and friends, and I was wondering if it does have a name and/or there is a standalone version of it accessible. I came along `text.c` after searching through assets and source codes, where the default font atlas is generated using some sorcery on the fly.

Thanks!

**Comment by raysan5** [comment]
Actually, raylib default font was mostly edited by me manually, don't remember exactly the font it was based on... I think it could be [this one](https://www.dafont.com/es/pixel-square.font) but as far as I remember I always worked directly with the image, also added the latin characters by hand.

Pixel data is embedded in the code and default font is generated at initialization.

In raylib webpage I use [this one](https://www.dafont.com/es/grixel-acme-9.font) that is pretty similar.

Why do you need it?

**Comment by siavashserver** [comment]
That reply was really fast :D I want to create geometry from characters and use them in 3D GUI elements. I'm currently slapping together something similar to yours in *PyxelEdit* to use in *Blender* later. I hope it's okay by you.

Thank you very much for help!

**Comment by raysan5** [comment]
Maybe you can take a look to [this code example](https://www.raylib.com/examples/web/models/loader.html?name=models_cubicmap), I'm doing something similar by code. I use one image to generate a 3D map. Mmmh... maybe I could also add 3D text generation as an option... ;)

You can use my font or any similar one, no problem.

**Comment by siavashserver** [comment]
That's a neat demo, thanks for sharing. It's amazing to see what web browsers are capable of these days 👍

**Comment by SzieberthAdam** [comment]
Thanks raysan5!

Here is it in PNG:

![tmp2mxn3f4k](https://user-images.githubusercontent.com/1587268/75831296-6ef06980-5db3-11ea-805d-5703f4690aae.png)

Please refer to `text.c` source for more info.
