### ISSUE TITLE
Remove RACIST/SEXIST/ABLEIST/SEMITIST slurs from source, now!

### ISSUE THREAD

**Issue by M-BoloDyebambewe** [raysan5/raylib#647]
Although I don't intend on using this software, I did take a look just to see what the students you 'teach' with this might find. Overall, here are the, frankly **horrible**, words and phrases that I found after just _two nights_ of searching through the code:

- 4 instances of the word **crazy**, which is INCREDIBLY offensive to aneurotypical and neuroasensial folks. Remove NOW
- 2 instances of the word **dumb**, which is offensive to the above, but also to people with MENTAL-DEVELOPMENTAL DISABILITIES. That's right, this is insulting to people with _mental difficulties_.
- 2 instances of the word **silly**, which is just as offensive to people with mental difficulties, as well as marginalized women
- 16(!) instances of the word **blac**klist! This is **UNNACEPTABLE**, bordering on full-fash. Replace with donotacceptlist immediately!
- **25** instances of the number 88, and 18 instances of the number 14. I am sure that you are all aware of the meanings of both of these numbers (14 being a **nazi** number, and 88 being also a **nazi** number)
- 120 instances of the word **master**, it being _EXTREMELY_ derogatory towards african americans, being victims of the oppresion brought upon them by _whites_ during the **slave** trade, as well as to women, who are victims of the sexual _slavery_ trade
- 11 results for OK, representing the hand sign 👌, which represents _white power_ (replace with 'okay'). 

All of these are a clear violation of the code of conduct, and I really hope that the person responsible will be ejected as soon as possible, as this kind of behaviour is unacceptable. I mean really? Are you kidding me?

**Comment by a3f** [comment]
heh.
