### ISSUE TITLE
remove racist maintainer

### ISSUE THREAD

**Issue by M-BoloDyebambewe** [raysan5/raylib#648]
I spent about an hour writing up a comprehensive list of terms in the code that should be removed due to violations of the code of conduct, and a maintainer by the name of @a3f instantly closed the issue. Does he have a problem with his privilege? Pretty sure that's against the CoC, too.

**Comment by M-BoloDyebambewe** [comment]
Might be because my ethnic minority status makes him angry

**Comment by sam0x17** [comment]
this guy trolls lots of repos, the maintainer isn't racist

**Comment by M-BoloDyebambewe** [comment]
> this guy trolls lots of repos, the maintainer isn't racist

Coming from a cishet white man. Typical.

**Comment by Sija** [comment]
Sockpuppets at work, please ban and move along.

**Comment by M-BoloDyebambewe** [comment]
> Sockpuppets at work, please ban and move along.

go away reactionary

**Comment by victorfisac** [comment]
@M-BoloDyebambewe buy a friend

**Comment by flamendless** [comment]
@M-BoloDyebambewe  what do you want? Do you want black colored text to be white since black texts are also a form of racism?

**Comment by raysan5** [comment]
Please, calm down, stop playing this game.

@M-BoloDyebambewe Many thanks for your efforts reviewing the repo. Please, feel free to send a pull-request with the appropiate changes, I'll review it.

In the meantime, I'm closing this flaming issue.
