### ISSUE TITLE
1488 found in the source code

### ISSUE THREAD

**Issue by slammerhammer** [raysan5/raylib#649]
is this some kind of joke? why are there nazis sneaking propaganda into the source code. this needs to be removed immediately. i am very offended by this especially because i am of jewish decent. https://github.com/raysan5/raylib/blob/dbfd8d713f10008b9e80940cc8825a0300c47325/examples/models/resources/plane.obj#L7038

**Comment by M-BoloDyebambewe** [comment]
Fucking disgusting. This is an obvious CoC violation
