### ISSUE TITLE
Store multisampling in FBO

### ISSUE THREAD

**Issue by victorfisac** [raysan5/raylib#65]
When using post-production shaders, the multisampling is not stored in FBO so the multisampling hint "SetConfigFlags()" doesn't make any difference...

I found some threads by the Internet about this issue:

- https://www.opengl.org/discussion_boards/showthread.php/167446-Multisample-FBO-and-render-to-depth-texture

- http://stackoverflow.com/questions/20482851/how-to-use-multisampling-with-opengl-fbos

I tryed making some lines of code but anything worked (any difference or "frame buffer object couldn't be created"...).

The same when compiling for web.

**Comment by raysan5** [comment]
Hello @victorfisac ,

`SetConfigFlags(FLAG_MSAA_4X_HINT)` tryes to setup multisampling on main framebuffer, it depends on OpenGL version (> 3.0) and hardware support ([ARB_multisample extension](https://www.opengl.org/registry/specs/ARB/multisample.txt)). Setting multisampling on FBO requires manual setup; the default FBO used for post-processing effects has no multisampling enabled, it will be consume too much resources, specially for embeded and low-end devices.

If you desire to implement an antialiasing algorythm to your post-produced image, my recomendation is using [FXAA antialiasing](https://en.wikipedia.org/wiki/Fast_approximate_anti-aliasing). It can be directly implemented on the fragment shader and it's very fast. You can find more information here:

http://www.kotaku.com.au/2011/12/what-is-fxaa/
http://www.geeks3d.com/20110405/fxaa-fast-approximate-anti-aliasing-demo-glsl-opengl-test-radeon-geforce/

**Comment by victorfisac** [comment]
Found a working FXAA fragment shader! Here is an adapted to raylib version: http://pastebin.com/ZE6w1LKi (changed to version 330 and changed var names to fragTexCoord and fragColor. The shader just needs the screen resolution to work.

Source: https://www.opengl.org/discussion_boards/showthread.php/184192-GLSL-FXAA-rendering-off-screen

I think maybe it can be optimized a little bit... not sure. Tested with shaders_custom_uniform.c and dwarf model, nice result! :D

**Comment by raysan5** [comment]
Thanks @victorfisac! FXAA fragment shader will be added to raylib shaders collection on next version!
