### ISSUE TITLE
[build] XCode 10

### ISSUE THREAD

**Issue by fabslab** [raysan5/raylib#651]
As of XCode 10 it no longer builds 32-bit applications.
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035631
> The macOS 10.14 SDK no longer contains support for compiling 32-bit applications. If developers need to compile for i386, Xcode 9.4 or earlier is required. (39858111)

After creating the raylib binary compiled with the command `make PLATFORM=PLATFORM_DESKTOP` as per the instructions on https://github.com/raysan5/raylib/wiki/Working-on-macOS I get the following error when building my game (that uses the raylib binary) in XCode 10:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Full log attached:
[log.txt](https://github.com/raysan5/raylib/files/2430936/log.txt)

Edit: I think the issue is not that it the library is built only for 32-bit (the makefile seems to build a "fat binary" that supports both?) but perhaps the issue is that the mac 10.14 SDK that is part of XCode 10 has a different API for the x86_64 architecture?

**Comment by fabslab** [comment]
I could just be missing how to build the raylib library for x86_64, is there a flag I can pass to do that on mac?

**Comment by a3f** [comment]
The _CF Prefix hints that CoreFoundation.framework is missing. You need `-framework IOKit -framework CoreFoundation -framework CoreVideo`. There should be some list where you can add it in the XCode project settings.

**Comment by fabslab** [comment]
Thanks for the hint, I managed to get it to build now by adding more dependencies, this is the full list
![screen shot 2018-09-29 at 8 07 50 pm](https://user-images.githubusercontent.com/1302888/46252836-690a9200-c423-11e8-82cc-e7fff812155f.png)
