### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jubalh** [raysan5/raylib#660]
When building with CMake I get:

```
cmake -DSHARED=ON -DSTATIC=ON -DBUILD_SHARED_LIBS=ON -DOpenGL_GL_PREFERENCE=GLVND ..                                                 :(
-- Testing if -Werror=pointer-arith can be used -- compiles
-- Testing if -Werror=implicit-function-declaration can be used -- compiles
-- Testing if -fno-strict-aliasing can be used -- compiles
-- Testing if file system supports symlinks
-- Testing if file system supports symlinks -- supported
-- Using raylib's GLFW
-- Using X11 for window creation
-- Audio Backend: mini_al
CMake Error at src/CMakeLists.txt:138 (if):
  if given arguments:

    "AND" "NOT" "" "STREQUAL" "GRAPHICS_API_OPENGL_33"

  Unknown arguments specified
```

Also when -DOPENGL_VERSION=3.3 is passed.

**Comment by raysan5** [comment]
I think you should pass at build time: `-DGRAPHICS_API_OPENGL_33`

**Comment by raysan5** [comment]
Default raylib build system is plain `Makefile`, I support it and it's always available for all systems.

**Comment by jubalh** [comment]
> Default raylib build system is plain Makefile, I support it and it's always available for all systems.

Ok, very good :)

**Comment by a3f** [comment]
I don't know if `-DOpenGL_GL_PREFERENCE=GLVND` works are you'd expect, but it shouldn't have broken the build. I pushed a fix for that. Thanks for the report!

If you'd like to set an OpenGL version, you had the syntax right, e.g. `-DOPENGL_VERSION=3.3`

> **BUILD_SHARED_LIBS**
> If present and true, this will cause all libraries to be built shared.

Also `-DBUILD_SHARED_LIBS=ON` is the same as specifying `-DSHARED=ON -DSTATIC=OFF` and combining it with `-DSTATIC=ON` doesn't make sense.

#626 raised the issue that `BUILD_SHARED_LIBS` is the standard CMake way to configure for shared libraries. It doesn't have a provision for indicating that the user wants _both_ shared and static libraries. That's what `STATIC` and `-SHARED` are for.

**Comment by jubalh** [comment]
> I don't know if -DOpenGL_GL_PREFERENCE=GLVND would work as you'd expect, but it shouldn't have broken the build. I pushed a fix for that. Thanks for the report!

Solved :) Now everything works, thank you!

> Also -DBUILD_SHARED_LIBS=ON is the same as specifying -DSHARED=ON -DSTATIC=OFF and combining it with -DSTATIC=ON doesn't make sense.

This was after trying out different things from the wiki to see if it changes something.
