### ISSUE TITLE
OSX glfw window blank until re-positioned

### ISSUE THREAD

**Issue by diclophis** [raysan5/raylib#665]
I noticed the same issue here: https://github.com/faiface/pixel/issues/140 is present in this project... I figured I might open this ticket so anyone searching for things like, blank window osx glfw might find this article and know that the current workaround is moving the window by 1px on init...

```
SetWindowPosition((GetMonitorWidth() - GetScreenWidth())/2, ((GetMonitorHeight() - GetScreenHeight())/2)+1);
```

Is what I rigged up...

Please close this issue if you feel it is not relevant.

**Comment by a3f** [comment]
Do you have the newest `master` checked out? #655 ought to fix that.

**Comment by diclophis** [comment]
Shoot, looking now it does look like I am on an older build of raylib, let me double check a newer tag, i am pretty sure it will fix my issue.

**Comment by a3f** [comment]
@diclophis Did you have time to check whether the issue still exists?

**Comment by diclophis** [comment]
@a3f yea it looks like the fix is good, thanks again for the heads up.

Side note, I have been enjoying using this framework and integrating it with `mruby` here: https://github.com/diclophis/kit1zx

I am building out a wrapper to hopefully take advantage of some of the DSL like abilities of ruby, crossed with the lightweight nature of this framework to produce small demo/art like applications

```
class SimpleCube < GameLoop
  def play
    size = 1.0
    cube = Cube.new(size, size, size, 1.0)

    lookat(1, 10.0, 5.0, 10.0, 1.0, 1.0, 1.0, 60.0)

    main_loop { |gtdt|
      global_time, delta_time = gtdt

      drawmode {
        threed {
          draw_grid(33, size * 2.0)
          cube.deltap(Math.sin(global_time), 1.0, 1.0)
          cube.draw(true)
        }

        twod {
          cube.label(global_time.to_i.to_s)
        }
      }
    }
  end
end

SimpleCube.new("simple_cube", 512, 512, 0).play
```

To produce...

<img width="624" alt="screen shot 2018-10-17 at 8 27 31 pm" src="https://user-images.githubusercontent.com/10122/47129841-d6078f80-d24b-11e8-8ec3-688dc48d85aa.png">
