### ISSUE TITLE
[core] RaspberryPi Mouse/Touch devices are hardcoded

### ISSUE THREAD

**Issue by Berni8k** [raysan5/raylib#666]
The issue relates to this part of code(and is present in the current master branch):
https://github.com/raysan5/raylib/blob/2.0.0/src/core.c#L202

**ISSUE EXPLANATION:**
It hardcodes the mouse input to device "/dev/input/mouse0" and touch to "/dev/input/event4". In typical raspberry pi use cases this works fine. Any USB mouse simply becomes "mouse0" and works, if you have multiple mice then only one of them will work (But lets face it nobody does that)

The issue becomes when a touchscreen is introduced. In many cases the touchscreen acts much like a mouse and sets itself up as the next available "mouse<N>" and "event<N>" devices. When there is no mouse connected it will grab "mouse0". In some cases this is good because the touchscreen now works, however some touchscreens fire off strange events in there "mouse<N>" device. For example the official RaspberryPi 7inch touch display has drivers baked into the kernel that grab "mouse0" and only sends what raylib detects as "IsMousePressed()" upon touching it. However if there is a USB mouse plugged in at boot this forces the touchscreen to obtain "mouse2" and "event2" where raylib ignores it. If you plug in the mouse after boot then the USB mouse gets "mouse2" and is ignored by raylib.

So what i am trying to say is that input devices on a RaspberryPi can appear is unpredictable order and can be pretty difficult to move around reliably. The usual behavior of a linux desktop environments is to grab input from all mouse devices (even ones that suddenly pop up as the desktop is running)

**PROPOSED FIX:**
Quick fix:
Add a extra feature to the raylib API that allows the user application to tell raylib what device to use at run time, rather than needing the raylib library to be recompiled.

Fancy fix:
Have raylib on initialization detect all present "/dev/input/mouse<N>" and "/dev/input/event<N>" devices. Possibly look at some flags inside to determine if the device is a touchscreen.

Testing this does require some hardware so if the developers want it, i could write my own fix and submit the changes.

**Comment by a3f** [comment]
>Quick fix:
>Add a extra feature to the raylib API that allows the user application to tell raylib what device to use at run time, rather than needing the raylib library to be recompiled.

>Fancy fix:
>Have raylib on initialization detect all present "/dev/input/mouse" and "/dev/input/event" devices. Possibly look at some flags inside to determine if the device is a touchscreen.

Both sound good to me. How about:

```
void InitTouchMultiple(struct pollfd *fds, nfds_t nfds, int timeout_ms)
{
    /* arrange for poll(2) to be called with the parameters here */
}
void InitTouch(void)
{
    struct pollfd *fds;
    nfds_t count = get_array_of_all_appropriate_input_devices(&fds);
    InitTouchMultiple(fds, count, -1);
}
```

**Comment by raysan5** [comment]
@Berni8k you can go for the fixes! Sounds good to me!

**Comment by Berni8k** [comment]
@raysan5 @a3f 
I have looked into the details of how the linux input event system (evdev) works and it looks like there will be some significant changes to make it feature complete, so i think i should explain my battle plan first.

1) All "mouseN" devices have an accompanied "eventN" device, however the "mouseN" device has no support for the scroll wheel or a large number of mouse buttons while "eventN" supports it just fine (mouse devices are just for backwards compatibility with old linux software), because of this i would abandon reading from "mouseN" and read from "eventN" for both mouse and touch. As such i would combine code from _InitTouch()_  into _InitMouse()_ and same with _TouchThread()_ 

2) The new _InitMouse()_ would scan for all devices named "event*" and open them in a separate _MouseThread()_ and in raylib tradition print the names of the devices to debug output along the way.

3) New _InitMouseEx(char* devices)_ function that takes a semicolon separated list of "eventN" devices. This kills all existing _MouseThread()_ and respawns them from the given list. This lets the user override the default behaviors of binding all available event devices. Or simply pass it a null string to rescan for new devices and add them all (Allows for hotplug if the user detects something new)

4) The worker thread _MouseThread()_ gets modified to parse the event stream. Existing _TouchThread()_ can already recognize events sent by USB mice(Apart from clicks). So only thing that needs to be added is the scroll wheel event and touchscreen multitouch events (Both 10 point multitouch screens i tested give them but with normal X Y events of the first point too).

5) Touch might need value scaling in some cases. I get perfect pixel coordinates out of the official Raspberry Pi 7 inch display (Using FT5406 chipset). However on a USB touchscreen with the Ilitek chipset i get very large X Y numbers (~16000x9000) out of the event device. Inside of X11 desktop the Ilitek touchscreen maps correctly to the pixels however, i have yet to discover where the desktop environment gets the correct scaling factors (No manual calibration was done to it).

So with these changes the RaspberryPi version of raylib should be fully feature complete in terms of input compared to its other platforms. Any suggestions are welcome as i have not implemented any of this yet.

**Comment by raysan5** [comment]
It sounds like a plan for me! Go for it!

It was quite long ago when I implemented input system for RPI so it would be great to have a full review.

**Comment by williamfjm** [comment]
hello Im here because raysan5 told me about this thread, and I had a similar problem, not the same but related.

Im working with ELO screen and when reading the mouse I had erratic reading problems, the library was not functional. But I found that this screen creates a device js0 in dev / input, I found that this is a joystick and voila! , raylib supports this function.

         yy = GetGamepadAxisMovement (0,1);
         xx = GetGamepadAxisMovement (0,0);

with these two instructions you have the position x, and with values between -1 and 1 in the two axes with a resolution of 0.000001, after that you just have to pass the scale to pixels.

raylib is great !!!

I hope this is helpful for someone.

**Comment by Berni8k** [comment]
@raysan5 
Will do, i did end up reading a lot of the existing code to understand how raylib deals with input under the hood.

@williamfjm 
Ah interesting. Does that touchscreen also create a "input/event" and "input/mouse" and did it work correctly as a mouse in the desktop environment? I suppose for these cases it would be possible to have InitMouseEx(char* devices) also accept "input/js" devices. That way raylib wont automatically grab them as a mouse on startup but the user can still make it do so. Such functionality could be useful if someone wants to use an actual gamepad to drive a mouse around.

**Comment by Berni8k** [comment]
Fixed in my commit

**Comment by colesnicov** [comment]
Hi @raysan5, It's like Stan by Eminem, write 20 times in 1 day... 
Hi @Berni8k ,

I'm trying to get touch on the screen working as I don't have a mouse. But it can not be. Basic things like pick, scroll yes, but zoom and span not. So I try to get it working according to the wiki, 


```
sudo TSLIB_FBDEVICE=/dev/fb0 TSLIB_TSDEVICE=/dev/input/event3 TSLIB_CALIBFILE=/etc/pointercal TSLIB_CONFFILE=/etc/ts.conf TSLIB_PLUGINDIR=/usr/local/lib/ts ts_uinput -v -d
```

And I get an answer:
```
/dev/input/event6
```

But when I try to run the example https://github.com/raysan5/raylib/blob/master/examples/core/core_3d_picking.c, I get an error:

```
denis@raspberrypi:~/dev/raylib/examples $ ./core/core_3d_picking 
INFO: Initializing raylib 5.1-dev
INFO: Platform backend: NATIVE DRM
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
INFO: DISPLAY: Selected DRM connector mode 384x1280 (384x1280p@62)
INFO: DISPLAY: Upscaling required: Screen size (384x450) smaller than display size (384x1280)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 384 x 1280
INFO:     > Screen size:  384 x 450
INFO:     > Render size:  384 x 450
INFO:     > Viewport offsets: 0, 830
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorWidth() not implemented on target platform
WARNING: GetCurrentMonitor() not implemented on target platform
WARNING: GetMonitorHeight() not implemented on target platform
WARNING: SetWindowPosition() not available on target platform
INFO: GL: Supported extensions count: 59
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Broadcom
INFO:     > Renderer: VC4 V3D 2.1
INFO:     > Version:  OpenGL ES 2.0 Mesa 23.2.1-1~bpo12+rpt3
INFO:     > GLSL:     OpenGL ES GLSL ES 1.0.16
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC1 compressed textures supported
INFO: INPUT: Initialized input device /dev/input/event0 as keyboard
INFO: INPUT: Initialized input device /dev/input/event3 as mouse
INFO: INPUT: Initialized input device /dev/input/event6 as mouse
WARNING: DRM: Failed to change keyboard mode, an SSH keyboard is probably used
INFO: PLATFORM: DRM: Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
```


Several input devices that look like a mouse are detected
```
INFO: INPUT: Initialized input device /dev/input/event3 as mouse
INFO: INPUT: Initialized input device /dev/input/event6 as mouse
```

**And it is do not work.**
