### ISSUE TITLE
Build error on Mac with master

### ISSUE THREAD

**Issue by fabslab** [raysan5/raylib#667]
Cloning master and running `make PLATFORM=PLATFORM_DESKTOP` on Mac currently results in:
```
clang -c core.c -O1 -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -Werror=implicit-function-declaration -DUSE_OPENAL_BACKEND -I. -Iexternal -Iexternal/glfw/include -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
In file included from core.c:131:
external/dirent.h:63:10: fatal error: 'io.h' file not found
#include <io.h>         /* _findfirst and _findnext set errno iff they r...
         ^~~~~~
1 error generated.
make: *** [core.o] Error 1
```

**Comment by dj0nes** [comment]
Same. 

I'm running MacOS Mojave, have Xcode, xcode tools installed with `xcode-select --install`, and installed the system headers using 

`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

as suggested in [this post](https://stackoverflow.com/a/52530212).

Any ideas? I am new to the C ecosystem.

**Comment by raysan5** [comment]
Hey! Actually, `external/dirent.h` include should only be included if compiling with MSVC compiler, it's not required in any other case... it seems checking macros are not working properly, don't know why...

As a temporary solution, you can just remove the include.

**Comment by jubalh** [comment]
The same happens on linux.

This is because of the -I option in the Makefile.

`external/dirent.h` is only included in the C file if MSCV, but `INCLUDE_PATHS = -I. -Iexternal -Iexternal/glfw/include` in the Makefile makes the compiler build everything nevertheless.

**Comment by dj0nes** [comment]
Removing `-Iexternal` from [this line](https://github.com/raysan5/raylib/blob/master/src/Makefile#L362) of the makefile works for me. I can compile and run raylib programs after.

I'd be happy to submit a PR putting that include behind a platform flag, if that sounds correct.

Side note: Running `make` does give a ton of "X is deprecated: first deprecated in macOS 10.14 - OpenGL API deprecated" warnings, as well as some unused functions and variables.

**Comment by a3f** [comment]
> Side note: Running make does give a ton of "X is deprecated: first deprecated in macOS 10.14 - OpenGL API deprecated" warnings

You can include a suppression for that in your PR if you like. Here's how I deal with it in CMake:

https://github.com/raysan5/raylib/blob/a56b3c21942737208a4f54f869b239b1d293cb00/src/CMakeLists.txt#L76-L79

**Comment by raysan5** [comment]
@dj0nes I think removing `-Iexternal` should be enough. You can send a PR with that change if you want.

About OpenGL, well, Apple deprecated the API so, at some point, raylib won't support macOS.

**Comment by dj0nes** [comment]
Master can now be built properly on mac. This can be closed!

**Comment by raysan5** [comment]
Closing this issue.
