### ISSUE TITLE
[textures] Raspberry Pi 3 B UnloadRenderTexture is removing textures that do not belong to this function

### ISSUE THREAD

**Issue by sabadyCZ** [raysan5/raylib#670]
I found that UnloadRenderTexture function is removing textures that do not belong to the function. So I can't remove render textures at runtime if some other textures was created before.

**Example**
I created one texture with ID 3. A moment later I created three RenderTexture2D variables and remove the last one by UnloadRenderTexture. Render texture is gone, BUT the texture with ID 3 too.

**Example code:**
```C++
InitWindow(screenWidth, screenHeight, "RenderTarget test");
Texture myTexture = LoadTexture("materials/wireBackground.png"); // Load texture with ID 3

RenderTexture2D renderTex1 = LoadRenderTexture(400,400);
RenderTexture2D renderTex2 = LoadRenderTexture(400,400); 
RenderTexture2D renderTex3 = LoadRenderTexture(400,400); // It's here 3 times because we need frame buffer with ID 3
UnloadRenderTexture(renderTex3); // Here the myTexture was also removed
  	
while (!WindowShouldClose())
{
	BeginDrawing();		
		DrawTexture(myTexture,0,0,WHITE); // Nothing is drawing
	EndDrawing();
}
```

**Comment by raysan5** [comment]
Thanks for reporting @sabadyCZ!

I've investigated this I pushed a possible solution in commit https://github.com/raysan5/raylib/commit/16914dfaa2e663b7c862be51b80ce8ea28399c55

In RPI FBO depth is a glRenderBuffer instead of a glTexture but it was being disposed as a glTexture... Maybe that was the issue... Please, let me know if it works!

**Comment by sabadyCZ** [comment]
Ok thank you!

I updated repository after long time, but compilation of my project ends up with fatal error.
**Console log:**
```../raylib/src/external/dirent.h:63:84: fatal error: io.h: Not found```
I found out that dirent.h file was added for VS studio on Windows, so maybe that is the problem.

**Comment by raysan5** [comment]
Ouch! Just introduced that library some weeks ago for MSVC compilation and it's resulting in lots of issues...

But compiling for PLATFORM_RPI it should happen... Just pushed commit https://github.com/raysan5/raylib/commit/161b18edea6649a108ef3f7aa37464688adcba07. Please, could you verify if it works now?

**Comment by sabadyCZ** [comment]
Ok, it works ONLY if I don't have `#include <dirent.h>` (because I need this library) somewhere in my project, but on the other hand the functions like _opendir_, _readdir_ from this library can not be found now `error: opendir was not declared in this scope`.

If I understand correctly somehow `#include <dirent.h>` in my project is refering on `src/external/dirent.h` file where `io.h` can't be found. So the problem is _maybe_ in this commit 6e4bd60978d880d57808317e0890f14614dcc215. I haven't found the solution yet...

**Comment by sabadyCZ** [comment]
I forgot to say that this problem doesn't have anything to do with the UnloadRenderTexture function.
