### ISSUE TITLE
[rlgl] Is there any plans for `glScissor()`?

### ISSUE THREAD

**Issue by overdev** [raysan5/raylib#677]
Hi, @raysan5.

A few months ago, after the NPatch PR, I started to work on a new feature request that would add 2 more functions:
`BeginClipRec(Rectangle rec)` and `EndClipRec()`. The idea behind these functions is to provide way to call glScissor() in a nested fashion.

The code I wrote compiled without complaints but, strangely enough, nothing happens when the functions are called, I mean, no clip area is set (LOL).

Now that I finally accepted my defeat (how dramatic), the only thing I can do is ask: Do you have any plan for `glScissor()`?

**Comment by raysan5** [comment]
Hi @overdev! Thanks for the efforts on this feature!

Actually, multiple users asked for it in the past but I never add it... still considering to what extend it is required or not...

In any case, I imagine you enabled it (`glEnable(GL_SCISSOR_TEST)`) before using `glScissor()`, right?

**Comment by overdev** [comment]
Yeah, I enabled `GL_SCISSOR_TEST`. I'm not sure about the inverted y axis, have to check it.

I believe the advantage of `glScissor` over other ways of achieving the same effect (render targets and so on) is that the coordinate system doesn't change. It also way more easy to understand and to use.

I would really appreciate if you, at some point in the very near future, decide to add it.

Cheers.

**Comment by raysan5** [comment]
@overdev I managed to get `glScissor()` working, there were a couple of details that probably you didn't considered and related to how raylib works internally.

Actual drawing is not launched until `EndDrawing()` so, if you call `BeginClipRec()` and `EndClipRec()` before calling `EndDrawing()` nothing changes for the actual drawing operation.

Also, there could be some [flickering issues](http://anirudhsasikumar.net/blog/2006.03.04.html) if nothing is drawn in the backbuffer before drawing clipped data.

Also, scissor rectangle refers to bottom-left corner.

Here it is a dirty hack to check it and get it working, I'll try to find a better solution.
```c
BeginDrawing();
    SetScissorRectangle(0, 0, screenWidth, screenHeight);
    ClearBackground(RED);  // Drawing operation to clear backbuffer to color
    
    EndMode2D();   // HACK: Forces drawing operation to occur
            
    SetScissorRectangle(0, 0, 400, 200);   // Scissor rec, refers to bottom-left corner
    ClearBackground(RAYWHITE);

    // Draw everything you want in the clipped rectangle

EndDrawing();   // Force drawing and swap buffers
```

**Comment by overdev** [comment]
Oh, I thought this would be something easy and simple to implement :sweat_smile:.

In fact, I remember reading some coments on the source code about changes being made only after EndMode2D is called. I didn't paid attention! Shame on me...

Isn't the buffer copy solution presented in the blog post a little too much? Well, if the solution is not simple and cheap (as I believed it was), maybe you're right on not bother with it.

**Comment by raysan5** [comment]
Feature implemented in commit https://github.com/raysan5/raylib/commit/4008a075a857f7674fe82331dae2636fc593dade. :)
