### ISSUE TITLE
[core] Support for waiting on events rather than tight polling loop

### ISSUE THREAD

**Issue by JamesDunne** [raysan5/raylib#679]
Can raylib support a wait-for-events model in contrast to a tight loop polling for events and rendering at a target fps? This would lighten up resource utilization on embedded platforms like the Raspberry Pi as well as ease power consumption in general. It's not for every scenario of course but it would be a nice option to have.

**Comment by raysan5** [comment]
Just implemented a wait-for-events (only desktop platforms) in commit https://github.com/raysan5/raylib/commit/0f6f326a868f6c970de066e71d74e81f54347085. Not much tested but seems to work ok.

Just note that raylib should be re-compiled enabling `SUPPORT_EVENTS_WAITING` flag. Please, let me know if it works ok.

**Comment by JamesDunne** [comment]
Wow you're fast! I'll take a look later tonight when I get some free time. Thanks!

**Comment by raysan5** [comment]
As a side note, Raspberry Pi does not support this feature at this moment in native mode; inputs are processed in a second thread at higher speed, it would be possible to wait for input events but it won't stop screen drawing in main thread... well, drawing can also avoid `SUPPORT_BUSY_WAIT_LOOP` for performance improvement...

Just closing this issue for now...

**Comment by raysan5** [comment]
Hey @JamesDunne! Yeah, you're right, most probably the `O_NONBLOCK` comes for the initial implementation when no threads were used... don't remember...

Now I don't have much time to look into it but if you tested it and works, it'd great if you send a PR with the changes.

**Comment by raysan5** [comment]
Hi @JamesDunne, did you work further on this? Could you send a PR or share a code snippet for review?

**Comment by JamesDunne** [comment]
Sorry, no I haven't had time to dedicate to this lately.

**Comment by raysan5** [comment]
Closing this issue for now.

**Comment by javierecf** [comment]
Hi quick question, is SUPPORT_EVENTS_WAITING still a valid option in config.h ? I can't seem to find it in v5
