### ISSUE TITLE
[core] Support multiple window layers

### ISSUE THREAD

**Issue by Fohlen** [raysan5/raylib#682]
Hello there @raysan5 
First of all, this library is amazing and by far the best library I have seen!

I was interested whether it would be possible to get more low level support to the underlaying OpenGL frame. The use case is the following: imagine it would be possible to add transparent layers on top of the main layer. These layers could then be filled by another program (e.g https://github.com/zserge/webview). This would allow for a modular composition of raylab with any other tool. My end goal here would be to add GUI functionality to raylib, preferably with HTML/CSS.
Let me know if you think this is feasible (so I might check out the source) and if this is a thing you would want to support with raylib.

**Comment by raysan5** [comment]
Hi @Fohlen, not sure if I understood it correctly... 

About layers, you can use a `RenderTexture` on raylib, to render whathever you want to a texture (it could be a transparent texture) and later draw that texture as a new layer. I think it covers the requested feature.

To add GUI functionality, I already provide [raygui library](https://github.com/raysan5/raygui); it works very good for small tools and it's also extremely efficient.
