### ISSUE TITLE
[textures] Draw texture with wrap options

### ISSUE THREAD

**Issue by anatagawa** [raysan5/raylib#684]
It's quite useful in 2D to have a display function, that we can repeat the texture to form a large image, like big background in plaformer level , to use only one texture.

You can find this into:
- Construct 2 with `TiledBackground`
- Love2D with `Quad`
- Unity with `Sprite Tiled Mode`

Maybe a feature for 2D, with in example `DrawTextureQuad()`

**Comment by raysan5** [comment]
`DrawTextureQuad()` added in commit. Please, let me know how it works!

**Comment by ubaidseth** [comment]
Would love to see a working example of DrawTextureQuad(). Can't seem to make it work for me :(

**Comment by Boyfinn** [comment]
> `DrawTextureQuad()` added in commit [414c3ee](https://github.com/raysan5/raylib/commit/414c3ee1f97c2c939d68b1b99a72feec1e29112a). Please, let me know how it works!

What happened to this feature? Did it get merged with a new definition?

**Comment by raysan5** [comment]
@Boyfinn it was removed later on due to the lack of flexibility, use rlgl directly if you need advance quad support.
