### ISSUE TITLE
Unsafe OpenURL()

### ISSUE THREAD

**Issue by jubalh** [raysan5/raylib#686]
Unfortunately `OpenURL()` can still be misused.
If we call the function with our own string all is fine, but if we let a user input an URL to open there is a risk.
A user could could craft the string to already contain the quoting and then run another command afterwards resulting in:

```
OpenURL("https://www.raylib.com/' ; 'rm -rf /");
```

For this reason we should only call this function if we control the string given (for opening our game website) or we need to parse the URL and escape the quotes.

**Comment by raysan5** [comment]
Added small security check in commit https://github.com/raysan5/raylib/commit/618f220851570f2bb9ea0bb354a65e92c6d06968

**Comment by jubalh** [comment]
A solution would be to replace all `'` in the URL. Then all the characters like '&' etc would be okay to use because they would be part of the URL and one could not end it and add another command after the call of `xdg-open` (etc.)

**Comment by jubalh** [comment]
I think it's good like this.
