### ISSUE TITLE
[core] Calling SetWindowIcon() many times causes "double free or corruption"

### ISSUE THREAD

**Issue by DevJac** [raysan5/raylib#689]
I'm working on some Haskell bindings to raylib. I'm not an expert at C or Haskell, but I think this is a bug within raylib itself.
Here is a function I invoke from Haskell:
```
void WrappedSetWindowIcon(Image *image) {
  // I'm just going to ignore the image argument, because it might be messed up.
  // It might point to garbage. Let's just rule it out.

  Image icon = LoadImage("test_data/raylib_16x16.png");
  printf("Icon loaded\n");
  for(int a = 0; a < 5000; a++) {
    printf("Inside C loop: %i\n", a);
    SetWindowIcon(icon);
  }
}
```
(The Haskell FFI only works with primitive types and pointers, so that's why I have this wrapper function.)
The functions argument, `Image *image`, is a pointer coming from Haskell; it is a pointer to an image loaded by `LoadImage`. As you can see in the comment, I ignored this pointer to rule out any weirdness with it.
The rest of the function is just plain C / raylib. Below is the console output when I invoke this function:
```
Icon loaded
Inside C loop: 0
Inside C loop: 1
Inside C loop: 2
Inside C loop: 3
Inside C loop: 4
Inside C loop: 5
Inside C loop: 6
Inside C loop: 7
Inside C loop: 8
Inside C loop: 9
Inside C loop: 10
Inside C loop: 11
Inside C loop: 12
Inside C loop: 13
Inside C loop: 14
Inside C loop: 15
double free or corruption (!prev)
terminated by signal SIGABRT (Abort)
```
The program sometimes goes a different number of loop iterations before failing.
I wonder if this bug has gone unnoticed because the more common use-case of setting the window icon only once seems to work.
I am using raylib 2.0.0, not master.

**Comment by DevJac** [comment]
Actually, in another circumstance I wasn't able to reproduce this bug, so I don't think it's a problem with raylib anymore.

**Comment by DevJac** [comment]
Actually, I changed my mind again. The following function produces the error:
```
void CTest(void) {
  InitWindow(500, 500, "SetIconTest");
  for (int i = 0; i < 10000; i++) {
    printf("Loop iteration: %i\n", i);
    Image icon = LoadImage("test_data/raylib_16x16.png");
    SetWindowIcon(icon);
    UnloadImage(icon); // This problem only happens if you call UnloadImage
  }
}
```
(I tried that function, except without the `UnloadImage` and it was working. That is what prompted me to close the issue. Then I realized I wasn't calling UnloadImage like I should have been, and when I added `UnloadImage` I started seeing the same problem in this plain C function.)

**Comment by raysan5** [comment]
Hi @DevJac, I've been checking this issue. Just pushed commit https://github.com/raysan5/raylib/commit/c8385aba83438d5e1df0ce6d18f844c81e06857d for testing... but I'm afraid issue is internal from `GLFW3` library instead of raylib... Image data provided to the function is copied internally, so, it should be completely safe to unload image data...

**Comment by raysan5** [comment]
Hey @DevJac! I look into this issue more carefully and did some tests. I works ok on my side (Windows 10), no memory leak detected.
