### ISSUE TITLE
[audio] Failing to initialize audio context on web

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#690]
When trying to run raylib audio example on web, being compiled with latest Emscripten SDK 1.38.19, audio context initialization fails.

This issue appeared after removing the old OpenAL backend from `audio.c` module on commit https://github.com/raysan5/raylib/commit/c2aa1fed7b4b75c9bb560ffb9ff6cd8c99d7dd41.

@mackron any idea about it? Maybe I'm missing some compilation flag? Everything seems to compile ok, it just fails on runtime at audio device initialization.

**Comment by raysan5** [comment]
@mackron Thanks for the super-fast response! Tested it and now I get:
```
Initializing SDL audio threw an exception: "Unsupported audio callback buffer size 0!"! Continuing without audio.
ERROR: Failed to open SDL device
```

**Comment by mackron** [comment]
That's probably related to this issue: https://github.com/dr-soft/mini_al/issues/33

If you haven't updated for a while, go ahead and update mini_al and see how you go. That issue had another issue where the latency was too high. Let me know if you get that issue and I'll need to play around with the default device config for Emscripten.

**Comment by raysan5** [comment]
Thanks for the info. I'm testing it tomorrow morning.

**Comment by raysan5** [comment]
Ok, it works now but there is some audio cracking on playing.

**Comment by mackron** [comment]
Buffer too small maybe? Try something like this and see how you go:
```
#ifdef __EMSCRIPTEN__
deviceConfig.bufferSizeInFrames = 4096; // <-- Play around with this or bufferSizeInMilliseconds.
#endif
```
I definitely had it working glitch free with a buffer size of 2048.

**Comment by mackron** [comment]
Also, is this happening on all browsers?

**Comment by mackron** [comment]
@raysan5 did you get a chance to take a look at this? I'm going to organise a new release for mini_al soon and just wanted to check whether or not I need to do a bug fix for this.

**Comment by raysan5** [comment]
Hey @mackron! Yes, tried it up to `8192` buffer size but kept getting the same audio cracking... ot sure if I did it correctly, just added that line on `InitAudioDevice()`, after `mal_device_config_init()`.

I'll try to take a closer look and do some more tests today.

**Comment by mackron** [comment]
I pushed an update to mini_al's dev branch that adds some additional debug output for the SDL backend. Are you able to give that a got and post the output. Just a warning, though, it'll spam a bunch of messages from the callback thread. I only need to see the first few.

By the way, if you're not already, can you try passing "-s USE_SDL=2" on the command line and see if that makes a difference? If you are already using that, could you try removing it if possible? It's weird because I'm not seeing any obvious issues that would cause this...

**Comment by raysan5** [comment]
Hey @mackron! Good and bad news!

Bad news first: after the fix, cracking continues...
Good news: using `-s USE_SDL=2` solves the problem and **audio works perfectly**.

About sound cracking issue, I uploaded a [sample here](https://www.raylib.com/examples/web/audio/loader.html?name=audio_music_stream_test).

**Comment by mackron** [comment]
That's weird... This doesn't feel right because the two different versions share a lot of code. Are you running an up-to-date version of Emscripten? I doubt this is the issue, but just to eliminate it as a possibility, are you able to update Emscripten and try again? I've tried it on all the major browsers so that can be eliminated.

In any case, it's not the biggest problem in the world - I can just drop support for SDL1 for Emscripten and force users to use `-s USE_SDL=2`. In the (hopefully) not too distant future I'm going to be adding a WebAssembly backend which will provide a first class backend for Emscripten rather than hacking it in with SDL.

**Comment by raysan5** [comment]
I'm using latest Emscripten `sdk-1.38.20-64bit`. 

I imagine you mean `WebAudio` backend, that would be great! It seems Emscripten officially only supports a [custom OpenAL port](https://kripken.github.io/emscripten-site/docs/porting/Audio.html) but latency is quite high. Is it possible to enable that backend with mini_al?

In the meantime, I'll use SDL2... but I don't like having to embedd all the SDL2 library just for audio...

**Comment by mackron** [comment]
By WebAssembly I mean it'll output WebAssembly code directly and use the Web Audio API (or whatever is most appropriate).

I'm dropping the OpenAL backend from mini_al soon - probably the next major version. So no, I'm not going to spend time supporting that. What's the size difference in the output between SDL1 and SDL2? I would think Emscripten would be smart enough to only include code that's actually used (i.e. only audio related stuff).

**Comment by raysan5** [comment]
Actually, I'm already compiling to WebAssembly, latest Emscripten compiles to it automatically, you can disable this behaviour using `-s WASM=0`. As far as I know, WebAudio is the only alternative for audio on web... all available library ports (OpenAL, SDL, SoLoud...) translate to WebAudio code.

I support the idea of removing OpenAL backend.

About sizes, it's quite curious size difference of generated .js and .wasm files:
 - SDL1: 597KB (.js) + 288KB (.wasm) = **885KB**
 - SDL2: 353KB (.js) + 792KB (.wasm) = **1145KB**
 - No Audio: 309KB (.js) + 127KB (.wasm) = **436KB**

It seems that, with SDL2, more code could be generated as WebAssembly in comparison to SDL1, so, despite being bigger, is not that bigger. On SDL1, more code is in JavaScript form... maybe that's related to the audio cracking... but I'm afraid I don't know how code is chosen to be compiled as Wasm or left as JS. Without enabling WASM, generated .js file is around **3MB**.

**Comment by mackron** [comment]
Yeah I'm thinking I might drop support for SDL1 entirely (for all platforms) and force Emscripten builds to use `-s USE_SDL=2`. It's not the end of the world if the command line is slightly more complicated and the final build adds a few hundred KB to the output size for the next few weeks until I can get the WebAssembly backend in.

Oh and by the way, I'm also looking at dropping the SDL2 backend once the WebAssembly backend has stabilized.

**Comment by mackron** [comment]
So I ended up dropping support for SDL 1.2 right now and have bumped the version and pushed to master.

**Comment by raysan5** [comment]
Nice to read you removed SDL 1.2!

About SDL2 backend, I was investigating yesterday about it... is it supported by `mini_al` in all platforms? which backends support? same backends as mini_al? I also think it could be a bit redundant using mini_al. 

I mean, why using `mini_al -> SDL -> <platform_audio_default_backend>` if it could be `mini_al ->  <platform_audio_default_backend>` directly?

Just in case, a couple of useful links: [SDL sources](http://hg.libsdl.org/SDL/file/default/include/SDL_audio.h) and [SDL WebAudio implementation](https://github.com/kripken/emscripten/blob/incoming/src/library_sdl.js#L1062).

**Comment by mackron** [comment]
SDL was added specifically for Emscripten, hence why I'm probably going to be removing it once I get a first-class backend for Emscripten up and running. It works on all platforms, but is set to the lowest priority which means it'll rarely get used in practice (except with Emscripten of course). SDL supports more backends than mini_al (we'll catch up!), but from memory I think a lot of them are pretty obscure and, I'm guessing, exist mainly for legacy purposes. Indeed, I think SDL2 actually have an Emscripten-specific backend similar to what I'm planning.
