### ISSUE TITLE
[build] VSCode project template does not work on Windows platform

### ISSUE THREAD

**Issue by EtianAM** [raysan5/raylib#691]
**Hi, I'm new in C programming, I recently found this library, but I don't like the text editor provided by the installer, so I decided to use some template that are in the folder 'Projects', I try with Sublime Text 3 and it doesn't work, now I'm trying to use VSCode, I follow the instructions of the wiki but as soon as I click on 'Debug' - 'Start Debugging', I get the following log:**

>\> Executing task in folder (Project folder): C:/raylib/mingw/bin/mingw32-make.exe RAYLIB_PATH=C:/raylib/raylib <
>
>mingw32-make game
>mingw32-make[1]: Entering directory '(Project Directory)'
gcc -o game  -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Wl,--subsystem,windows -I. -IC:/raylib/raylib/release/include -IC:/raylib/raylib/src -IC:/raylib/raylib/src/external C:/raylib/raylib/raylib.rc.o -L. -LC:/raylib/raylib/release/libs/win32/mingw32 -LC:/raylib/raylib/src  -lraylib -lopengl32 -lgdi32 -DPLATFORM_DESKTOP
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../libmingw32.a(main.o):(.text.startup+0xa0): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
Makefile:312: recipe for target 'game' failed
mingw32-make[1]: *** [game] Error 1
mingw32-make[1]: Leaving directory '(Project Directory)'
mingw32-make.exe: *** [Makefile:308: all] Error 2
The terminal process terminated with exit code: 2
>
>Terminal will be reused by tasks, press any key to close it.

**I haven't been able to do anything since there's...
Pd: This text was translated by an internet translator, so it's possible that it's misspelled.**

**Thanks**

**Comment by raysan5** [comment]
Thanks for reporting @EtianAM, also tried it myself and got same error.

Unfortunately, I'm not the one that configured VSCode project. Let's wait for someone that could take a look into this issue.

**Comment by EtianAM** [comment]
Thanks.

**Comment by raysan5** [comment]
Just been trying to get it working, found multiple errors related to pre-defined paths...
Corrected some paths to work for me on Windows on commit https://github.com/raysan5/raylib/commit/98fee844d1794465d5b327e60b85a5030a8bea62 but that's not a good solution... 

I need more time to learn how VSCode json configuration files work to come to a proper build-pipeline solution.

**Comment by raysan5** [comment]
Just to clarify, current solution works. No plans to review VSCode template again at least after Christmas.

You can use current master branch in the meantime.
