### ISSUE TITLE
[Build] VS Code Configuration improvements - Some Path issues

### ISSUE THREAD

**Issue by monsterbrain** [raysan5/raylib#694]
Hi,

   I've installed the 2.0.0 release, using the installer. NPP build is working fine.

   I'm not an expert in config files. But it took me a while to setup the vscode example to get it to working.

Here's some issues I encountered and how I solved them. Maybe It's helpful for someone who's having issues. (Maybe add a bit detailed config tutorial on the **[wiki page - using vscode for raylib](https://github.com/raysan5/raylib/wiki/Using-raylib-in-VSCode)**, would be helpful)

The raylib that got installed has **mingw folder** instead of **mingw32 folder**. So in the **MAKE_FILE** I changed

`export PATH := C:/raylib/mingw32/bin:$(PATH) to export PATH := C:/raylib/mingw/bin:$(PATH)`

also in **c_cpp_properties.json** file

`LDFLAGS += $(RAYLIB_PATH)/raylib.rc.data`
also the **raylib.rc.data** file was missing. So I downloaded from github and added manually.

Build Debug is now working. But Build release is not working. Will post more details once I search for some solutions.

Let me know if I misunderstood or done something in the wrong way.

**Comment by raysan5** [comment]
@monsterbrain Thanks for reporting!

You should use github raylib master branch, it has latest updated code, installer is a bit outdated right now.

About Wiki, you can add more details, it's open to edit for everyone. Just take a bit of care... :P

**Comment by monsterbrain** [comment]
I'm not an expert, but I'll try and let you know.

**Comment by monsterbrain** [comment]
I've added some Wiki Modifications for the VSCode Page. Please check and let me know any changes you think I missed.  I'll try to write a tutorial soon.

**Comment by raysan5** [comment]
@monsterbrain thanks for the Wiki review! Look good to me! 👍
