### ISSUE TITLE
[rlgl] Broken examples for Raspberry Pi

### ISSUE THREAD

**Issue by Berni8k** [raysan5/raylib#701]
The following examples have issues in the current master branch of raylib:
- textures_image_processing.c (Image is missing or white)
- textures_particles_blending.c (Text appears missing, depends on blend mode too)
- textures_raw_data.c (Missing image and glitch in text)
- textures_rectangle.c (Glitched animated image, appears as moving white blobs)
- textures_srcrec_dstrec.c (Missing text in corner)
- textures_to_image.c (Glitched image shows, This seamed to be broken for past >80 commits tho)
- models_yaw_pitch_roll.c (Glicthed 2D textures, they appear to be a character set image instead of the texture)
- shaders_shapes_texture.c (Missing shapes and image)
- text_bmfont_tff.c (Sprite font is cut off)
- text_sprite_fonts.c (Glicthed text)

A lot of these appear to be some sort of 2D texture problem. I have not checked every single example so there could be more.

**Comment by raysan5** [comment]
Wow, so many broken examples... definetely, there is some problem with textures... :(

Thanks for reporting @Berni8k!

**Comment by raysan5** [comment]
Most broken examples should work ok after commit https://github.com/raysan5/raylib/commit/db96cf4a8ba87f10c3f0bb1043f846f2233dba03.

I'll review some more examples to confirm...
