### ISSUE TITLE
[rlgl] Support OpenGL ES through ANGLE on Windows desktop platform

### ISSUE THREAD

**Issue by msmshazan** [raysan5/raylib#704]
Add Support for ANGLE renderer on Win32 platform

**Comment by raysan5** [comment]
I've been working on this for some hours today and I got to the conclusion it doesn't worth it.

If anyone want to keep working on it or just try it, here are some tips:

  1. Some [background info](https://www.saschawillems.de/?page_id=1822).
  2. GLFW works ok for GLES context initialization, just need to define:
```c
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
    glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API);

    // Here we choose context creation API, it can be:
    // - GLFW_NATIVE_CONTEXT_API: Uses native OS API
    //       WGL on Windows, GLX on Linux, CGL on OSX
    //       Requires XXX_EXT_create_context_es2_profile
    // - GLFW_EGL_CONTEXT_API: Uses generic EGL API: Suitable for ANGLE
    glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_NATIVE_CONTEXT_API);
```
   3. After requesting and obtaining the OpenGL ES 2.0 context, required extensions/function pointers should be loaded. [glad](https://github.com/Dav1dde/glad) could be used for that.
   4. Now it comes compilation time, right linkage libraries should be provided:
       - Using `GLFW_NATIVE_CONTEXT_API`: theorically linking with default system OpenGL library `-lopengl32` should be enough if required function pointers have already been loaded.
       - Using `GLFW_EGL_CONTEXT_API` (ANGLE): you should link against ANGLE libs `libEGL.lib` and `libGLESv2.lib`, those libraries should be [compiled from source](https://github.com/google/angle) using desired compiler and configuration (STATIC/SHARED). Oh, [ANGLE OpenGL headers](https://github.com/google/angle/tree/master/include) should be available around...

When trying it with raylib I found some issues, implemented [some required tweaks](https://github.com/raysan5/raylib/commit/47358fe5ce50a7dfae2db6cd3c3d86ad93eec152) but some other weird issues pop up and I left it, concluding it doesn't worth it.

To anyone that wants to get it working:
 - [rlgl] Include `<EGL/egl.h>` avoiding any conflicts with raylib, probably `rlgl` should be moved to a self-contained module (.c).
 - [rlgl] `rlglInit()` make sure OpenGL ES extensions are loaded properly.
 - Download and compile `ANGLE` from sources.
 - Link user program against `ANGLE` provided `libEGL.lib` and `libGLESv2.lib`.

**Comment by raysan5** [comment]
Great addition @msmshazan! Thank you very much to take the time and effort to look into this and get a working solution! :)

I think we can finally close this issue!
