### ISSUE TITLE
Possible regression in DrawRectanglePro

### ISSUE THREAD

**Issue by heuripedes** [raysan5/raylib#705]
Commit e340517a735c9a563b39e24809b2f214ece991ad introduced a change to `DrawRectanglePro()` that breaks the rotation behavior we have in the current stable (2.0.0).

The code bellow renders two rectangles and a green ball, the red rectangle is supposed to "follow" the white one but rotate as the movement speed varies and this is what happens when `STABLE_RAYLIB=1` but if you set it to `0` the red rectangle rotates around the top left corner instead.

```c++
#include "raylib.h"
#define STABLE_RAYLIB 1
int main() {
    InitWindow(640, 480, "test");
    SetTargetFPS(60);

    Vector2 speed = {1, -10};
    float gravity = 0.2;

    int x = 0, y = 400;

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(BLACK);

        x++;
        if (x > 640)
          x = 0;

        y += speed.y;
        speed.y += gravity;

        if (y > 400)
          speed.y = -10;

        float angleDeg = atan2f(speed.y, speed.x) * RAD2DEG;

        Rectangle r{(float)x, (float)y, 30, 10};

        DrawRectangleRec(r, RAYWHITE);
#if STABLE_RAYLIB
        DrawRectanglePro(r, {0, 0}, angleDeg, RED);
#else
        Color colors[] = {RED, RED, RED, RED};
        DrawRectanglePro(r, {0, 0}, angleDeg, colors);
#endif
        DrawCircle(x, y, 5, GREEN);

        EndDrawing();
    }
}
```

**Comment by heuripedes** [comment]
Comparison with `DrawTexturePro()` with the same same rect, angle and origin. The car and the red rectangle get perfectly aligned at angle 0, but as soon as I walk over a slope they get like in the picture.

![texturepro](https://user-images.githubusercontent.com/59172/50426496-c5881c80-086d-11e9-9bcc-78686e1122cd.png)

**Comment by raysan5** [comment]
Just reviewed `DrawRectanglePro()`on commit https://github.com/raysan5/raylib/commit/9a8320c52bf179633c33f16d4f0adbf57f820b1b.

I decided to return to old implementation... I don't like the Color[] array thingie.
