### ISSUE TITLE
[build] Cannot find libraylib.so.2

### ISSUE THREAD

**Issue by Michael-Bianconi** [raysan5/raylib#706]
After installing raylib on GNU Linux, I'm unable to run the examples. After compiling them and running them, it says

`error while loading shared libraries: libraylib.so.2: cannot open shared object file: no such file or directory`

This happens when installing either via make or cmake. The file does exist in usr/local/lib.

**Comment by raysan5** [comment]
Does the file exist in `raylib/src` directory? Is it generated successfully?

**Comment by jubalh** [comment]
@Michael-Bianconi which distro are you running? Which commands do you run to build and install? How do you compile your program?

**Comment by gen2brain** [comment]
@Michael-Bianconi you probably don't have /usr/local/lib in ld.so, you can add e.g. local.conf file in /etc/ld.so.conf.d and inside file add `/usr/local/lib` , after that one `ldconfig` and it should be ok.

**Comment by Michael-Bianconi** [comment]
@raysan5 

> Does the file exist in `raylib/src` directory? Is it generated successfully?

It does _not_ exist in raylib/src.

@jubalh 
> @Michael-Bianconi which distro are you running? Which commands do you run to build and install? How do you compile your program?

I'm running Ubuntu 18.04.1 LTS. I'm building via:

`raylib/src$ sudo make clean
raylib/src$ sudo make PLATFORM=PLATFORM_DESKTOP
raylib/src$ sudo make install`

If I run it with
`raylib/src$ sudo make install RAYLIB_LIBTYPE=SHARED`
it throws an error saying libraylib.so.2.0.0 not found.

Alternatively, if I use cmake
`raylib/build$ cmake -DSTATIC=ON -DSHARED=ON ..
raylib/build$ sudo make clean
raylib/build$ sudo make
raylib/build$ sudo make install
raylib/examples$ make core/core_basic_window PLATFORM=PLATFORM_DESKTOP -B`
I get the libraylib.so.2 not found error.

**Comment by Michael-Bianconi** [comment]
Issue solved

I manually deleted libraylib.so.2 from usr/local/lib and it solved the problem for some reason.

**Comment by Grinshpon** [comment]
I had the same problem but with libraylib.so.301. Deleting it also made it work but I feel like there's still an underlying problem that needs to be addressed

**Comment by SirLorrence** [comment]
the same issue but with libraylib.so.400 on version v4.0.0

**Comment by wwesleyaraujo** [comment]
Don't forget run: $ sudo ldconfig

**Comment by abhinav-0401** [comment]
i am experiencing the same issue with libraylib.so.4.2.0, after compiling with cmake

what is the underlying issue?

**Comment by Samarth13Dev** [comment]
> Don't forget run: $ sudo ldconfig

@wwesleyaraujo 

It fixed the problem. Thanks!

**Comment by renzo70** [comment]
> Don't forget run: $ sudo ldconfig

I'am using Ubuntu 20.04 and it fixed the problem.

**Comment by renzo70** [comment]
> Don't forget run: $ sudo ldconfig

I'am using Ubuntu 20.04 and executing it after installation fixed the problem.

**Comment by DavySalgado** [comment]
> Don't forget run: $ sudo ldconfig

Porra wesley, vlwww sksksksksksk. Esqueci total, tava com a porcaria de um pc novo e viajei. Vlwwww irmão
