### ISSUE TITLE
[platform_web] `emscripten_set_main_loop_timing` when building the game for web

### ISSUE THREAD

**Issue by tahmidsadik112** [raysan5/raylib#709]
I am trying to build this [example](https://github.com/raysan5/raylib/blob/master/examples/core/core_basic_window_web.c) for web with emscripten and it's compiling fine. But when I open the html file I get this error
`emscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up.`
But the main function contains a call to the `emscripten_set_main_loop`
```
InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");
emscripten_set_main_loop(UpdateDrawFrame, 30, 1);
CloseWindow();
```

I am using 
OS: Mac OS Mojave 10.14.2
Raylib: Version 2.0
Emscripten Version 1.38.21

Please help! I must be missing something.

**Comment by raysan5** [comment]
That's weird... probably a stupid question but, are you defining `PLATFORM_WEB` on compilation? It should be defined manually...

In any case, I'm testing several things on web right now and I'll take a closer look.

**Comment by raysan5** [comment]
Just tried with latest raylib version and it works ok for me. Be careful with space between `-D $(PLATFORM)`, it should be `-DPLATFORM_WEB` or just try `#define PLATFORM_WEB` at the beggining of the code file, to make sure it picks the define.

**Comment by raysan5** [comment]
@tahmidsadik112 Did you try recompiling latest raylib version from GitHub?

**Comment by raysan5** [comment]
Just tested it again to make sure it works. Closing this issue.

**Comment by raysan5** [comment]
Ok, I think I didn't understood this issue first time. The issue does not block web example from running (or it shouldn't) it's only a kind-of-warning because we are trying to change timming behaviour before `emscripten_set_main_loop`. 

Issue corrected on commit https://github.com/raysan5/raylib/commit/0bacc978c39a234da4a2b73ce3cb5b43e072a103.

**Comment by tahmidsadik112** [comment]
Sorry for replying so late. I got kinda busy with day job, holiday and all that.
As you suggested I tried to remove the whitespace between `-D $(PLATFORM)`, but the same runtime error was thrown.
> @tahmidsadik112 Did you try recompiling latest raylib version from GitHub?
No but I am gonna do that soon and let you know.

**Comment by tahmidsadik112** [comment]
@raysan5 I just cloned the project and build everything. Now the game is loading without any issue. Thanks a lot!

**Comment by tahmidsadik112** [comment]
@raysan5 There's not enough information in the wiki about how to build for mac os, specially when targeting html5. The wiki should be updated and I might be able to help if needed.

**Comment by raysan5** [comment]
Thanks @tahmidsadik112, Wiki is open for edition, feel free to update it, you're welcome. :)
