### ISSUE TITLE
[core] FPS drop on Raspberry Pi

### ISSUE THREAD

**Issue by Morvs** [raysan5/raylib#712]
I'm working on a little application to be run on a Raspberry Pi 3 which is written in C++. The program is basically only moving the camera over some images(roughly 2000x2000 each). I had this working fluid with 60 FPS before I started experimenting with raylib-py and trying to do it in Python but the binding seems to have flaws on the Raspberry Pi(displays nothing or triangle mess if you're lucky). I flashed a fresh raspbian and started working again on the C++ version, only that I now found it to be stuttering and having less than 60 FPS. It starts with 60 but as soon as I move a bit it goes down to 45 and then down to 30.
This is valid for the current development state(2.3-dev).

It's fine for 2.0.0 release version which I will, and should anyway, use from now on. But something along the way broke the performance on the Raspberry Pi.

If I can give you any more relevant info, give me a hint on what you need.

**Comment by Morvs** [comment]
I'm only drawing textures and some debug text with the default font.
I'm running in native mode on the Pi. 

The drop also occurs heavily if I'm not moving the camera but zooming it out to fit the texture into the resolution

I will try to create a small sample without my stuff and only the basic thing that is needed(draw textures, move camera).

**Comment by Morvs** [comment]
So I got the example going. Seems it's not the textures but the drawn text.
Example code is attached. Commenting the DrawText commands in keeps the FPS going but when they're executed it drop the FPS the same way as in my application.

[raylib_issue.zip](https://github.com/raysan5/raylib/files/2724007/raylib_issue.zip)

**Comment by raysan5** [comment]
I won't have access to my RPI until next Monday but, could you try to draw text using this:
```c
DrawText(TextFormat("%f", camera.offset.x), 0, 16, 16, RED);
```

**Comment by Morvs** [comment]
TextFormat doesn't change it, sadly.

What's even more weird is that if I swap the DrawFPS command for a DrawText(TextFormat("%d", GetFPS()),...) the FPS stay up, even with the other text calls. I'm slightly confused.

**Comment by raysan5** [comment]
mmmmh... are you diagnosting the frames drop by the number written by `DrawFPS()` or you really noticed some slow-down in the program? Could you try drawing some animated element (a ping-pong ball) and check if it slows-down? Maybe issue is related to `DrawFPS()`...

**Comment by Morvs** [comment]
No, my program seemed to be choppy when moving the camera and therefore I added the DrawFPS command to check if the FPS really dropped or if it's another issue. I removed the DrawFPS command and recompiled but it's still choppy. I now added the DrawText(GetFPS()....) method instead of DrawFPS and it also shows decreasing FPS, so it seems to be real.

With 2.0.0 it's buttery smooth at 60 FPS. I'm somewhat prone to noticing hickups and stuttering in general so that's the first thing that I noticed when compiling it again with this version for the raspi.

**Comment by raysan5** [comment]
ok. It's weird that it only happens on text drawing... 

Did you try compiling examples as C instead of C++?

**Comment by Morvs** [comment]
Tested the example as C program, no change. Sorry :<

Commenting those two commands also doesn't change a thing. Still dips down to 43-45 FPS. It's completely strange overall, I move the camera a few pixel and the FPS drop that way. 

Also to verify I removed the text drawings from my original program and it's smooth afterwards, just like with 2.0.0.

**Comment by raysan5** [comment]
ok, thank you very much for reporting and all your tests.

Also tested on desktop and analyzed frame drawing with RenderDoc but all looks fine. Text drawing only adds and additional draw call... it's only 3 draw calls... RPI should be able to manage several hundred draw calls with no frame drop.

I'll try to take a closer look to this issue next week with my RPI.

**Comment by raysan5** [comment]
Could you try a couple of additional tests?

One test, replace:
```c
Texture2D tex = LoadTexture("data/0.png");
Texture2D tex2 = LoadTexture("data/1.png");
```
by
```c
Image imData0 = GenImageGradientH(2000, 2000, RED, GREEN);
Image imData1 = GenImageGradientH(2000, 2000, GREEN, BLUE);
    
Texture2D tex = LoadTextureFromImage(imData0);
Texture2D tex2 = LoadTextureFromImage(imData1);
    
UnloadImage(imData0);
UnloadImage(imData1);
```
Another test: Try with images sized at `2048 pixels` instead of `2000 pixels`.

**Comment by raysan5** [comment]
(adding full code example without dependencies for convenience)
```c
#include "raylib.h"

int main() 
{
    SetConfigFlags(FLAG_VSYNC_HINT);
    InitWindow(1920, 1080, "Test");
    SetTargetFPS(60);

    Camera2D camera;
    camera.offset = (Vector2){ 0, 0};
    camera.target = (Vector2){ 960, 540};
    camera.zoom = 1;
    camera.rotation = 0;

    Image imData0 = GenImageGradientH(2000, 2000, RED, GREEN);
    Image imData1 = GenImageGradientH(2000, 2000, GREEN, BLUE);
    
    Texture2D tex = LoadTextureFromImage(imData0);
    Texture2D tex2 = LoadTextureFromImage(imData1);
    
    UnloadImage(imData0);
    UnloadImage(imData1);

    Vector2 texPosition = (Vector2){0, 0};
    Vector2 texPosition2 = (Vector2){2000, 0};

    while (!WindowShouldClose()) 
    {
        camera.offset.x += 0.5f;

        if (IsKeyDown(KEY_LEFT)) camera.offset.x -= 10;
        else if (IsKeyDown(KEY_RIGHT)) camera.offset.x += 10;

        BeginDrawing();

            ClearBackground(BLACK);

            BeginMode2D(camera);

                DrawTextureV(tex, texPosition, WHITE);
                DrawTextureV(tex2, texPosition2, WHITE);

            EndMode2D();

            DrawFPS(0, 0);

            // Comment these in and FPS should be fine
            DrawText(TextFormat("%f", camera.offset.x), 20, 20, 20, BLACK);
            DrawText(TextFormat("%f", camera.offset.y), 20, 40, 20, BLACK);
            DrawText(TextFormat("%f", camera.target.x), 20, 60, 20, BLACK);
            DrawText(TextFormat("%f", camera.target.y), 20, 80, 20, BLACK);
        EndDrawing();
    }

    UnloadTexture(tex);
    UnloadTexture(tex2);
    
    CloseWindow();

    return 0;
}
```

**Comment by raysan5** [comment]
Tested this issue a bit further. It seems raylib is hitting a slow path when using `BeginMode2D()/EndMode2D()`, if commenting it, program runs smoothly. It's very difficult to find the slow path we hit, it depends on the black magic the Broadcom driver does (running in native mode).

When we begin/end 2D camera mode, draw calls processing is forced, so, using it results in:
```c
BeginDrawing();
    ClearBackground(BLACK);
    BeginMode2D(camera);     // DRAWS PROCESSING: no draws
        DrawTextureV(tex, texPosition, WHITE);
        DrawTextureV(tex2, texPosition2, WHITE);
    EndMode2D();             // DRAWS PROCESSING: 2 draws (one per texture)
    DrawFPS(0, 0);
    DrawText(TextFormat("%f", camera.offset.x), 20, 20, 20, BLACK);
    DrawText(TextFormat("%f", camera.offset.y), 20, 40, 20, BLACK);
    DrawText(TextFormat("%f", camera.target.x), 20, 60, 20, BLACK);
    DrawText(TextFormat("%f", camera.target.y), 20, 80, 20, BLACK);
EndDrawing();                // DRAWS PROCESSING: 1 draw (default text texture)
```

It seems we are hitting the RPI limits with this sample... As a detail, also note that maximum texture size supported by RPI is 2048x2048.

It would be great to test this issue with new desktop GL driver, maybe it improves performance.

**Comment by Skabunkel** [comment]
@Morvs  Do you know if you update your raylib version when you reinstalled the pi?

**Comment by raysan5** [comment]
Just closing this issue... lot of investigation has been put on it and it seems it's out-of-scope of raylib...
