### ISSUE TITLE
[core] Running a raylib application could breaks other running applications

### ISSUE THREAD

**Issue by Morvs** [raysan5/raylib#713]
Running my application using either statically or dynamically linked raylib causes other programs like nano or apt to crash. nano crashes with "SIGTERM or SIGHUP". apt just aborts right away when asking the "Proceed to install [y/N]" question.
The application using raylib continues to work after the first start.

Happens on raspbian stretch.
uname -a:

> Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

Can anyone else confirm this? This problem is consistent for multiple raspbian installations and is valid for 2.0.0 release as well as 2.3-dev. I don't know who the bad boy is in this case, raylib or raspbian itself, and don't know what to look for exactly.

**Comment by raysan5** [comment]
Are you running both programs in native mode at the same time? Running though SSH?

No previous report but it could be related to raylib reconfiguring raw keyboard input...

**Comment by Morvs** [comment]
It's the same application mentioned in the other issue and it's only running once at a time.

It occurs without SSH and with SSH, doesn't matter.

What I forgot to mention: It's "fixed" when using a new shell.

**Comment by raysan5** [comment]
Does it happen with a simple raylib example?

**Comment by raysan5** [comment]
Most probably related to keyboard input mode...

**Comment by Morvs** [comment]
So it's related to raylib? You don't seem to be very excited about that ;-)

If I can do anything else to help, tell me. I'm happy to help if I can.

**Comment by raysan5** [comment]
Thank you very much @Morvs, I was working long time on RPI keyboard input system trying to find the best approach and, unfortunately, doesn't seem to work properly (not only this issue but also https://github.com/raysan5/raylib/issues/379). It seems it requires a major redesign... falling back to the standard `input_event` mechanism.

**Comment by Berni8k** [comment]
Hmm.. in that case maybe i should not have left the old STDIN keyboard methods in when moving to the new keyboard method in #785 

It possibly has to do with changing modes on STDIN to get a more direct keyboard input, perhaps this leaves the console window in a weird state.

Even if i don't manage to reproduce the issue i think it might be a good idea to simplify the STDIN keyboard method to only listen to STDIN and not attempt to reconfigure it into any special modes. For keyboards physicaly connected to the Pi the new evdev method works better and SSH consoles (where evdev does not work) fail to switch modes anyway so we might as well just use STDIN in its default mode.

@raysan5 Do you agree with this change?

**Comment by raysan5** [comment]
> It possibly has to do with changing modes on STDIN to get a more direct keyboard input, perhaps this leaves the console window in a weird state.

Yeah, that's it, running a raylib program reconfigures STDIN for it... and other programs running in background, it could also derive into some weird behaviour...

I think there is no alternative for it, listening to STDIN in a passive way requires reconfiguring it, in any other case (i.e. `getchar()`) end-line is required to send data.

I'd keep current implementation and let the user choose under it's own risk. By default, now it uses `evdev`, most users shouldn't have problems with that.

**Comment by ePirat** [comment]
I am experiencing the same issue using raylib git f37e55a77bd6177dbaea4d7f484961c09104e104 on Raspbian Stretch Lite (without X11).

**Comment by alanbork** [comment]
in case it's unclear: this is still an issue, it has not been fixed.
