### ISSUE TITLE
[rlgl] Drawcall not called after surpassing hardcoded spritebatch limit

### ISSUE THREAD

**Issue by Yatima1460** [raysan5/raylib#714]
if GRID_SIZE is set to 90 everything is drawn properly
if GRID_SIZE is set to 91, everything breaks, probably because it's surpassing the 8192 hardcoded spritebatch limit
https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L107

it seems that a draw call is not performed when 8192 is surpassed

```C
BeginMode2D(camera);

const int GRID_SIZE = 90;
const int TILE_SIZE = 16;

Vector2 ptemp = { 0 };

for (int x = 0; x < GRID_SIZE; x++)
{
	for (int y = 0; y < GRID_SIZE; y++)
	{
		ptemp.x = camera.offset.x + x * TILE_SIZE;
		ptemp.y = camera.offset.y + y * TILE_SIZE;
		DrawTextureRec(t, (Rectangle) { 0, 0, TILE_SIZE, TILE_SIZE}, ptemp, WHITE);
	}
}
EndMode2D();
```

**Comment by Yatima1460** [comment]
OK I did some tests:

with the last stable release 2.0.0 the spritebatch limit draw call **is broken**
with the last dev release 2.3-dev everything works

It should be written as a big warning that the spritebatch is broken in the 2.0.0 release!!!

**Comment by raysan5** [comment]
Hey! Thanks for confirmation! :)

Actually, there could always be things broken... so I try to keep improving the library! 

In any case, I'm planning a new release soon, probably **raylib 2.5**.
