### ISSUE TITLE
[core] Aspect ratio is broken when drawing in 3d mode inside a RenderTexture2D

### ISSUE THREAD

**Issue by anatagawa** [raysan5/raylib#716]
I use a RenderTexture2D to draw sphere and sprite at the same time.

    BeginTextureMode(frameBuffer);
    {
        ClearBackground(BLANK);
        DrawTexture(bg, 0, 0, WHITE);
        BeginMode3D(camera);
        {
            DrawSphereWires( sphereCenter1, 16, 8, 8,  (Color){80,104,155,255} );
            DrawSphereWires( sphereCenter2, 16, 8, 8,  (Color){80,104,155,255} );
            DrawSphereWires( sphereCenter3, 16, 8, 8,  (Color){80,104,155,255} );
        }
        EndMode3D();
        
        DrawTexturePro( ball,
            (Rectangle) {0,0,30,30},
            (Rectangle) {320+cos(2*sine)*192, 240+sin(2*sine)*192,30,30},
            (Vector2) { 15, 15},
            0, WHITE
       );
    }
    EndTextureMode();

All is correct.

![](http://screens.anatagawa.fr/screen_2019-01-04_10-46-16.png)

But if i resize window and RenderTexture , i get this

![](http://screens.anatagawa.fr/screen_2019-01-04_10-47-16.png)

The problem is : BeginMode3D()/EndMode3D() use screen size ratio instead of RenderTexture

**Comment by raysan5** [comment]
@anatagawa This issue should be corrected with commit https://github.com/raysan5/raylib/commit/c200642887a8a5a4fd38168aee224dc9fc9906ab. Please, let me know if it works.

**Comment by anatagawa** [comment]
nice, it works fine now, thks :)

**Comment by raysan5** [comment]
Nice! Closing the issue! :)
