### ISSUE TITLE
[build] ShowWindow() function breaks 64bit builds (symbol collision)

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#720]
`ShowWindow()` collides with a symbol inside `libuser32` but build works ok for most of the platforms, including Windows 32 bit... but it fails on `raylib.dll` generation for Windows 64 bit (MinGW and MSVC).

Error is on the linker and here I list both linker lines for convenience.

### MinGW 
*Linking 32 bit - SUCCESS -*
```
C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\gcc.exe  -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith -m32 -g -m32 -shared -o libraylib.dll -Wl,--out-implib,libraylib.dll.a -Wl,--major-image-version,2,--minor-image-version,0 -Wl,--whole-archive CMakeFiles\raylib.dir/objects.a -Wl,--no-whole-archive @CMakeFiles\raylib.dir\linklibs.rsp
```
*Linking 64 bit - ERROR -*
```
C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin\gcc.exe  -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith -m64 -g -m64 -shared -o libraylib.dll -Wl,--out-implib,libraylib.dll.a -Wl,--major-image-version,2,--minor-image-version,0 -Wl,--whole-archive CMakeFiles\raylib.dir/objects.a -Wl,--no-whole-archive @CMakeFiles\raylib.dir\linklibs.rsp

C:/mingw-w64/x86_64-6.3.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libuser32.a(dwres00675.o):(.text+0x0): multiple definition of `ShowWindow'
CMakeFiles\raylib.dir/objects.a(core.c.obj):C:/projects/raylib/src/core.c:840: first defined here
```
With MinGW, both lines are pretty similar, the only different is `-m32` vs `-m64`.

### MSVC
*Linking 32 bit - SUCCESS -*
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\projects\raylib\build\release\Debug\raylib.dll" /INCREMENTAL /NOLOGO /LIBPATH:"C:\Tools\vcpkg\installed\x86-windows\debug\lib" /LIBPATH:"C:\Tools\vcpkg\installed\x86-windows\debug\lib\manual-link" external\glfw\src\Debug\glfw3.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/projects/raylib/build/release/Debug/raylib.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/projects/raylib/build/release/Debug/raylib.lib" /MACHINE:X86 /SAFESEH  /machine:X86 /DLL ...
```
*Linking 64 bit - ERROR -*
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\projects\raylib\build\release\Debug\raylib.dll" /INCREMENTAL /NOLOGO /LIBPATH:"C:\Tools\vcpkg\installed\x64-windows\debug\lib" /LIBPATH:"C:\Tools\vcpkg\installed\x64-windows\debug\lib\manual-link" external\glfw\src\Debug\glfw3.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/projects/raylib/build/release/Debug/raylib.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/projects/raylib/build/release/Debug/raylib.lib" /MACHINE:X64  /machine:x64 /DLL ...
```
With MSVC the notable linking differences are `/MACHINE:X86` vs `/MACHINE:X64` and the usage of linker parameter `/SAFESEH` on 32bit, more info about it [here](https://docs.microsoft.com/en-us/cpp/build/reference/safeseh-image-has-safe-exception-handlers?view=vs-2017).

Don't know how to solve this issue... if possible to solve.

**Comment by a3f** [comment]
My suggestion: Call it `UnhideWindow` instead.

---

Sidenote: We already have a very basic "link simple application against raylib and see if it crashes"-test for some targets in the `.travis.yml`. If someone feels like it, they could duplicate it for AppVeyor/Windows. Would've caught this issue in CI.

**Comment by raysan5** [comment]
@a3f Yeah, renaming it is the quick solution... I just would like to understand why it fails on 64 bit Window specifically while it compiles ok on other configurations...

**Comment by raysan5** [comment]
I think I found the answer! After some checking, I found `ShowWindow()` is called internally by window initialization function (through GLFW library) while `ShowCursor()` is never used because it is indirectly set using `window->cursorMode`.

As proposed, I renamed `ShowWindow()` to `UnhideWindow()`. I don't like it but it's ok.

**Comment by a3f** [comment]
Oh, makes sense. Thanks!
