### ISSUE TITLE
[rlgl] Review/redesign GenTexture*() functions

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#721]
rlgl includes a set of functions to generate multiple textures useful for PBR rendering:
```c
// Texture maps generation (PBR)
// NOTE: Required shaders should be provided
TextureCubemap GenTextureCubemap(Shader shader, Texture2D panorama, int size);       // Generate cubemap (6 faces) from equirectangular (panorama) texture
TextureCubemap GenTextureIrradiance(Shader shader, TextureCubemap cubemap, int size);   // Generate irradiance cubemap using cubemap texture
TextureCubemap GenTexturePrefilter(Shader shader, TextureCubemap cubemap, int size);    // Generate prefilter texture using cubemap data
Texture2D GenTextureBRDF(Shader shader, int size);                  // Generate a generic BRDF texture
```
Those functions should be redesigned, basically, they generate Cubemap textures using a specific shader, that has to be externally provided and match internal implementation... nonsense!

Redesign would consist in exposing properly `FBO functionality` and `Cubemap textures` functionality, to let the user create the required PBR textures by themselfs.

Some ideas to improve FBO functionality:
```c
// Improved FBO generation function to allow selecting the attached color buffer pixel format 
// and the depth buffer type (Renderbuffer or Texture) and size
// NOTE: Be careful on supported pixel formats...
RenderTexture rlLoadRenderTexture(int width, int height, int colorFormat, int depthBits, bool useDepthTexture);
// Attach/detach color buffer texture to an FBO (returns previous attachment)
Texture2D rlAttachRenderTexture(RenderTexture target, Texture2D texture);
```

Some idea to support cubemap textures:
```c
// Actually, a cubemap could have same properties as a Texture2D
typedef TextureCubemap Texture2D;

// Cubemap texture generation... that should be filled later!
TextureCubemap cubemap = LoadTextureCubemap(int size, int format, bool genMipmaps);
```

Any ideas on this line?

**Comment by raysan5** [comment]
`LoadTextureCubemap()` implemented on commit https://github.com/raysan5/raylib/commit/fce48e85f441215192d188011b48a0f35828e4b3

Redesigned `rlLoadRenderTexture()` in commit https://github.com/raysan5/raylib/commit/db56d432e4812f9b21f3548108fb4f1963a81ff5

`GenTexture*()` functions require additional functionality to combine fbo with cubemap textures.

**Comment by raysan5** [comment]
`rlgl` framebuffer loading and tex-attaching mechanism have been redesigned.

All `GenTexture*()` functions have been reviewed and redesigned (and actually, simplified) with a more consistent implementations, using `rlgl` new functions for framebuffer management.

Still some points left:

 - Using internal batch system vs using raw OpenGL drawing (`GenDrawCube()`). glActiveTexture() / glBindTexture() is required on drawing raw and the `rlgl` alternative (`rlEnableTexture()`) is required when drawing with batch system but we need to be very careful with the order of the calls to enable/disable texture because it internally deals with the batch system limits.
 - Shaders should be provided to the functions, that's not portable at all, it must be avoided... probably those functions should be taken out of raylib and moved to example code...

**Comment by chriscamacho** [comment]
```
models/models_skybox.c:65:66: error: incompatible types when assigning to type 'Texture2D' {aka 'Texture'} from type 'int'
models/models_skybox.c:105:82: error: incompatible types when assigning to type 'Texture2D' {aka 'Texture'} from type 'int'
  105 |                         skybox.materials[0].maps[MATERIAL_MAP_CUBEMAP].texture = rlGenTextureCubemap(shdrCubemap, panorama, 1024, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8);
```

**Comment by raysan5** [comment]
@chriscamacho https://github.com/raysan5/raylib/commit/51f3129c5dfa4be70787fa9c4473335252abffcd

**Comment by chriscamacho** [comment]
close ! :smiley: 
```
INFO: VAO: [ID 2] Unloaded vertex array data from VRAM (GPU)
free(): double free detected in tcache 2
Aborted
```
is there a raylib build flag to enable instrumentation ? makes stuff like this a lot easier to track down
