### ISSUE TITLE
[core] Broken touch input for web demos

### ISSUE THREAD

**Issue by Ronsor** [raysan5/raylib#726]
On an iPad, touch input doesn't work for the examples on the site that use the mouse. The examples otherwise run fine.

**Comment by raysan5** [comment]
Actually, web demos do not support touch input on mouse click. I mean, touch logic is separate from mouse logic and examples do not use touch...

In any case, this could be a feature to add.

**Comment by raysan5** [comment]
Related commit: https://github.com/raysan5/raylib/commit/f28c1ef6759c587c205cdf239a06ac8b2ccac963.

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/raylib/commit/954f029118260dce867c1bf6ff3948ca6a6bee85.
