### ISSUE TITLE
[build] CloseWindow() linker error in MSVC with 64-bit builds (symbol collision)

### ISSUE THREAD

**Issue by dextorious** [raysan5/raylib#729]
I'm new to raylib, but I suspect this is essentially the same issue as https://github.com/raysan5/raylib/issues/720. Pulling the latest master commit as of this writing and compiling the included VS2017 project works after manually deleting `audio.c` from the project (since the examples don't require it anyway). However, compiling the same solution in x64 mode fails with `CloseWindow already defined in user32.lib(USER32.dll)`. Is another rename in order here?

Edit: just to confirm the obvious, manually renaming CloseWindow() to any non-colliding name resolves the issue and leads to working examples.

**Comment by raysan5** [comment]
Just for reference, here it is the list of potentially colliding symbols, thanks `windows.h`!
```c
libuser32     -->   ShowWindow(), ShowCursor(), CloseWindow()
libgdi32      -->   Rectangle

// Specific usage cases
libwinmm      -->   PlaySound()
libkernel32   -->   LoadResource(), LoadModule()
```

**Comment by dextorious** [comment]
It seems you are correct, though I'm not sure how I managed to pollute the namespace with the `windows.h` imports. Either way, making a clean example from scratch and only including raylib works without any conflicts. Apologies for wasting your time, this issue is resolved.
