### ISSUE TITLE
UV mapped textures

### ISSUE THREAD

**Issue by astlin** [raysan5/raylib#739]
Hi. Is there any way to draw model (cube) with UV mapped texture? My problem is that my game's world is built with procedural generated blocks and textures generated on-the-fly. So I need the planes of cube mesh to be textured with specific image, for example top plane with texture A, bottom with texture B and sides with texture C. I can join A, B and C textures into UV mapped texture but how can I draw model with it? If I attach texture with material.maps[MAP_DIFFUSE].texture then all planes of the mesh are textured with the same image.

**Comment by raysan5** [comment]
Hi @astlin, I'm afraid you should build the cube model manually directly defining the vertex position coordinates and texture coordinates to fit your needs.

Just check [GenMeshCube()](https://github.com/raysan5/raylib/blob/master/src/models.c#L921) for reference.
