### ISSUE TITLE
Android Pause/Resume

### ISSUE THREAD

**Issue by dmalves** [raysan5/raylib#74]
Hi,

How can I handle Pause/Resume on android devices?

**Comment by victorfisac** [comment]
If you are looking for pause game loop cycle when pressing Home button or similar, the game loop is automatically paused and resumed when losing and recoverying focus in app.

Otherwise, if you are looking for pause your gameplay you should create a variable to determine if the game is paused and execute all your gameplay logic if it's false or your pause logic (continue/exit buttons, menu animations) if it is true. You must add an input check to switch on/off the pause state.

Here is an example. Press android back button to pause and resume the "gameplay" (convert it to .c and test :D)

[android_pause_example.txt](https://github.com/raysan5/raylib/files/89391/android_pause_example.txt)

I hope it helps you!

**Comment by raysan5** [comment]
Just posting @victorfisac code directly for convenience:

```c
#include "raylib.h"

//----------------------------------------------------------------------------------
// Android Main entry point
//----------------------------------------------------------------------------------
void android_main(struct android_app *app)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, app);
    
    // TODO: Initialize all required variables and load all required data here!

    int framesCounter = 0;          // Used to count frames
    bool paused = false;             // Pause state
    
    SetTargetFPS(60);               // Not required on Android, already locked to 60 fps
    //--------------------------------------------------------------------------------------
    
    // Main game loop
    while (!WindowShouldClose())    // Detect window close button
    {
        // Update
        //----------------------------------------------------------------------------------
        
        // Switch pause state by pressing android back physic button
        if (IsButtonPressed(ANDROID_BACK)) paused = !paused;
        
        if (paused)
        {
            // Pause behaviour
            // ...
        }
        else
        {
            // Gameplay behaviour
            framesCounter++;
        }
        //----------------------------------------------------------------------------------
        
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
        
            ClearBackground(RAYWHITE);
            
            if (paused) DrawText("GAME PAUSED", 10, 10, 20, BLACK);
            
            DrawText(FormatText("Current frame: %i", framesCounter), screenWidth / 2 - 185, screenHeight / 2 - 20, 40, BLACK);
        
        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    
    // TODO: Unload all loaded data (textures, fonts, audio) here!
    
    CloseWindow();          // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
}
```

**Comment by dmalves** [comment]
I dont know if that is the best option. The game app could go to background
for other reasons beside the backbutton (antivirus kicking in, for
example). SDL2 is a C library too, and it can handle pause/resume events
Android platform. I am sending this message from my phone, so It is hard to
point it out on git, but I saw something related to pause/resume on raylib
with no usage example so far and it got me curious as I wanto to use raylib
to develop casual android games.

**Comment by dmalves** [comment]
One more point. When the app pause it should save its state to a file and
load it back when resumed. Android could kill your app after a resume and
your app should be able to recover for death when android resumes it. This
is the whole porpose of the pause/resume scheme. Your app should look
always alive to the user,  even when the system needs to free resources
because the new foreground app(yours is on background) needs a lot of
memory and it is cpu hangry.
Em 13/01/2016 22:25, "tcl super dude" <tcleval@gmail.com> escreveu:

> I dont know if that is the best option. The game app could go to
> background for other reasons beside the backbutton (antivirus kicking in,
> for example). SDL2 is a C library too, and it can handle pause/resume
> events Android platform. I am sending this message from my phone, so It is
> hard to point it out on git, but I saw something related to pause/resume on
> raylib with no usage example so far and it got me curious as I wanto to use
> raylib to develop casual android games.
>

**Comment by dmalves** [comment]
looks like the answer is here http://developer.android.com/intl/pt-br/reference/android/app/NativeActivity.html

**Comment by raysan5** [comment]
Hi @dmalves, thanks for the point and for the link (actually, that's the base code I used to implement raylib's Android support).

SDL2 manages Android activity in a different way than raylib (using the JNI Java wrapper layer); raylib uses the android_native_app_glue module provided with NDK (like in the example you link). Both ways can be used to handle activity events but on SDL2 they are more exposed to the user and raylib manage them internally: https://github.com/raysan5/raylib/blob/develop/src/core.c#L1612

Most of the events are handled to avoid application break (including context lose) but it's true that some side cases are not handled like antivirus kicking in or system resource-freeing decisions... that's a point to work on... 

But raylib is intended for small-simple games and I think that side-cases are not a big handicap; I mean, if application is lost, it can be just restarted (most games work that way). Most of the time, a raylib app will look alive to the user.

**Comment by dmalves** [comment]
@raysan5 , nice! I was just looking around main repository :-) Well, I was thinking about a simple callback scheme only available for the android port and it could fit what you have on the repository already. When AndroidCommandCallback is called and APP_CMD_RESUME branch is executed a callback function set by the library user would be called.The user should write a function that could receive userData:

app->userData; 

so AndroidCommandCallback would call user function and pass userData. userData could be a structure that could hold bothe real user data and raylib data, in case raylib needs to pass some data to AndroidCommandCallback. Something like:

app->userData->data for raylib user
app->userData->internal for raylib usage

 I'll look around the following days what can be done without changing what is already in place too much.

Anyway thx for your time and congratulations! your library is sweet ;-)

**Comment by raysan5** [comment]
Hi @dmalves , it sound great to me. Please, let me know when you got it! :)
