### ISSUE TITLE
How can I make .exe file for distribution using raylib notepad++?

### ISSUE THREAD

**Issue by MakerOfWidows** [raysan5/raylib#745]
#include "raylib.h"

int main()
{
    int screenWidth = 1920;
    int screenHeight = 1080;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");
    
    SetTargetFPS(60);
 
    while (!WindowShouldClose()) 
    {
        BeginDrawing();

            ClearBackground(RAYWHITE);

            DrawText("Congrats! You created your first window!", 190, 200, 20, MAROON);

        EndDrawing();
    }
-   
    CloseWindow();        // Close window and OpenGL context

    return 0;
}

Say this is the default code in the framework. How can i make .exe file for distribution? Brief explanation would be nice.

**Comment by jubalh** [comment]
You compile it.

**Comment by MakerOfWidows** [comment]
> You compile it.
F6 would help me compile and execute the program. But i want to create an .exe for it which option should i select.

**Comment by MakerOfWidows** [comment]
oh thanks man. Can someone tell me where can i get good tutorial on raylib?

**Comment by raysan5** [comment]
Closing this issue. @MakerOfWidows you should check the examples carefully, they are as tutorials.
