### ISSUE TITLE
Is there a way to change the default icon for the Raylib .exe for distribution?

### ISSUE THREAD

**Issue by MakerOfWidows** [raysan5/raylib#746]
Hi, I'm new to this framework and an average C++ programmer and have searched this question a lot but not found any good article. If anyone could just help with this question?

**Comment by raysan5** [comment]
Hi @MakerOfWidows, raylib compilation uses a [custom resource file](https://github.com/raysan5/raylib/blob/master/src/raylib.rc), compiled with [windres](http://www.mingw.org/wiki/MS_resource_compiler) into `raylib.rc.data` to be linked on your program compilation. You can just replace that to provide your own. 

Just as a side note, you can ask this kind of questions on [raylib Discord](https://discord.gg/VkzNHUE) server.

**Comment by MakerOfWidows** [comment]
thanks
