### ISSUE TITLE
models_yaw_pitch_roll example is broken

### ISSUE THREAD

**Issue by yashrk** [raysan5/raylib#750]
A plane model in `models_yaw_pitch_roll` example is stretched horizontally.

Working example (commit fef7bbb4): 
![image](https://user-images.githubusercontent.com/7109285/52600567-14fdc880-2e6d-11e9-9b7c-2240dfde6883.png)

Broken example (current master branch):
![image](https://user-images.githubusercontent.com/7109285/52600613-424a7680-2e6d-11e9-9eac-081e7e15a5d5.png)

It's probably an effect of the [commit `c200642`](https://github.com/raysan5/raylib/commit/c200642887a8a5a4fd38168aee224dc9fc9906ab), at least `git bisect` points it as a first bad commit:
```
c200642887a8a5a4fd38168aee224dc9fc9906ab is the first bad commit
commit c200642887a8a5a4fd38168aee224dc9fc9906ab
Author: Ray <raysan5@gmail.com>
Date:   Mon Feb 4 17:10:12 2019 +0100

    Review issue with aspect ratio...
    
    ...while using a RenderTexture combined with 3d mode

:040000 040000 9cfd7aab730f2c5aebba07797346a4cda643204f 566be52e9d9eb2c3448003a9603e18a4d76ad3f2 M      src
```

**Comment by raysan5** [comment]
Corrected in commit https://github.com/raysan5/raylib/commit/981be58d0330657d9f7533aec8185b6b743d6405.
