### ISSUE TITLE
[shaders] Simple bright model texture shader mode

### ISSUE THREAD

**Issue by diclophis** [raysan5/raylib#751]
Hello,

Is there a simple mode of rendering a 3d model where by the texture is rendered as bright as the pixels in the source uv map? Ideally without any lighting configuration... and mostly none/pre-computed shadows in the texture map.

See example look below

![flat-shade-pre-computed-shadow](https://user-images.githubusercontent.com/10122/52679208-2c7a9700-2ee9-11e9-9052-5a0bc4a9ccc9.png)

**Comment by SolarLune** [comment]
The above example has lighting and shadows on it.

**Comment by diclophis** [comment]
Yes, my understanding is that I would pre-compute the the light/dark parts on the texture map? or is there perhaps a simple lighting setup that would let me just flat-shade my models and then get this simple example?

**Comment by raysan5** [comment]
As @SolarLune state, this is not a simple lighting configuration... but it can be accomplished with a shader... one example would be great... is this a voxels model?

**Comment by diclophis** [comment]
The model is styled like "voxels" but it is a normal/simple texture-mapped .obj model.

I guess what I need is some guidance / pointers on what the simplest lighting setup would be to texture mapped objs as "flatly" as possible (as in, i don't really want any shadow fall off or anything, nor do i want ssao).

I have seen alot of games with this aesthetic and I was wondering how it might be accomplished in raylib.... I think other gamedevs call it like "playstation 1" style, or i have also see the color brightness and flatness in other "voxel" style things.

**Comment by diclophis** [comment]
Maybe the real question I have is, what is the simplest type of shader / light configuration do I need to be able to render simple flat colored models... maybe I should ditch the texture uvs and just use color vertex information?

**Comment by diclophis** [comment]
I know it must be something beyond the default setup because if I render a spinning cube model without wireframe, you dont see each face distinctly, it just looks like a flat morphing square like shape...

**Comment by raysan5** [comment]
@diclophis Actually, that's the default shader, just coloring the vertex and assigning a texture if provided, no lighting calculations done in the shader. You'd need a custom shader using the vertex normals and some additional parameters to calculate basic lighting. A couple of lighting tutorials [here](http://www.opengl-tutorial.org/beginners-tutorials/tutorial-8-basic-shading/) and [here](https://www.tomdalling.com/blog/modern-opengl/06-diffuse-point-lighting/).

raylib includes a [standard_lighting.c](https://github.com/raysan5/raylib/blob/master/examples/others/standard_lighting.c) example but I'm afraid it's partially broken at the moment.

Just closing this issue for now.
