### ISSUE TITLE
[textures] Disabling image export in config.h fails to compile

### ISSUE THREAD

**Issue by neonmoe** [raysan5/raylib#752]
I noticed that if I comment out the line following line in config.h, the compilation will fail with multiple undefined references in the ExportImage function.
```c
#define SUPPORT_IMAGE_EXPORT        1
```

After further investigation, a similar problem arises when disabling the following:
- SUPPORT_FILEFORMAT_KTX
- SUPPORT_IMAGE_MANIPULATION
- SUPPORT_IMAGE_GENERATION
- SUPPORT_MESH_GENERATION

Are these just wip, or am I missing something?

I could write a PR for these as I'll be writing a fix for myself in any case. If that's desired, should the relevant functions (eg. ExportImage) be completely removed when compiled with these settings off, or should the functions just not do anything?

**Comment by raysan5** [comment]
@neonmoe Thanks for reporting! It shouldn't fail but in the last months raylib has changed a lot and those flags were not tested. A PR is welcome. About ExportImage() it should be available but just enable supported file formats.
