### ISSUE TITLE
[core] GIF recording path not correct on Linux

### ISSUE THREAD

**Issue by Demizdor** [raysan5/raylib#754]
raylib wants to save the recorded GIF in `/screenrecXXX.gif` but since that is the root directory it can't.

Changing this [line](https://github.com/raysan5/raylib/blob/981be58d0330657d9f7533aec8185b6b743d6405/src/core.c#L3283) to `strcpy(path, TextFormat("./screenrec%03i.gif", screenshotCounter));` will fix the problem and the GIF will be saved in the current directory as intended ;)

**Comment by raysan5** [comment]
Reviewed in commit https://github.com/raysan5/raylib/commit/bc86b0f78b3f901ddc688f55915d260359f0da15
