### ISSUE TITLE
[Improvement] Raw key reads for RPI

### ISSUE THREAD

**Issue by DarkElvenAngel** [raysan5/raylib#756]
In regards to issue #379 and possibly #713

I have rewritten Raylib keyboard routines to read from the input/event rather that the STDIN I would very much like to submit this code for review, however I am unsure as to how one does this.

Do I post it here in the issue or some other way?

My changes were all made to core.c

**Comment by Demizdor** [comment]
Hi there! 
The best way is to [fork](https://help.github.com/articles/fork-a-repo/) the raylib repository. Just read the link i provided it has all the info you want.
I'm new to github myself, if you need further help fell free to ask.

Have a great day!

**Comment by raysan5** [comment]
@DarkElvenAngel thanks for the review! @Demizdor thanks for the answer! :)

**Comment by DarkElvenAngel** [comment]
Great thanks @Demizdor for the information.
