### ISSUE TITLE
[models] Support glTF file-format models loading

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#759]
To support this amazing new standard file-format proposed by [Khronos Group](https://www.khronos.org/gltf/), recently a new plain-c single-file header-only library has appeared: [cgltf](https://github.com/jkuhlmann/cgltf).

This library can parse glTF file-format and provide all the information contained, raylib can add support to that data *just* mapping parsed `cgltf_data` to `Mesh` or `Model` structures. A [note has been left in code](https://github.com/raysan5/raylib/blob/master/src/models.c#L2787) for that implementation.

But first, multi-mesh per-model support should be implemented...

**Comment by raysan5** [comment]
raylib Model/Mesh/Material structs are ready to support most of glTF data provided but the format is quite complex and moving `cgltf` parsed data to raylib structs could take some work...

**Comment by wbrbr** [comment]
I'm working on this ! I got it working for simple models, however glTF is pretty flexible (allows for indexed and unindexed meshes, integer/float texture coordinates, multiple primitives per mesh, ...) and my code makes lots of assumptions right now. I'll try to finish it in the next days/weeks.
![screenshot000](https://user-images.githubusercontent.com/6280095/57694746-d84c9380-764c-11e9-9bf3-f79435331a97.png)

**Comment by raysan5** [comment]
Hey @wbrbr! Nice work! Feel free to send a PR despite support is not fully complete! :D 

That's a great raylib addition!

**Comment by raysan5** [comment]
Support added by @wbrbr in commit https://github.com/raysan5/raylib/pull/842! Thank you very much! 👍 

For future reference, just  note that there are some restrictions listed in the PR. Probably this implementation could be extended in a future to support more material maps (PBR) and also animated models!
