### ISSUE TITLE
[text] Memory leak  when unloading fonts.

### ISSUE THREAD

**Issue by Skabunkel** [raysan5/raylib#764]
williamfj on discord noted that when loading and unloading fonts, we do not dispose of all the memory.

Using the example text_bmfont_ttf.c 
and changing the load statment `LoadFont("resources/pixantiqua.ttf"); ` into
```cpp    
while (true)
{
    Font fontTtf = LoadFont("resources/pixantiqua.ttf");  // TTF font
    GenTextureMipmaps(&fontTtf.texture);
    UnloadFont(fontTtf);
}
```
we can se that UnloadFont seems to not be disposing of all the data.

![memory each step](https://user-images.githubusercontent.com/9131566/53291725-2bcee400-37b8-11e9-8926-8ba0988f31fc.png)

**Comment by Skabunkel** [comment]
Currently debugging the issue, Not entirely sure but seems to come from, though my debugger tells me it is STBTT_malloc in stb_truetype.h:3573.

src\external\ stb_truetype.h

**Comment by Skabunkel** [comment]
I'll expand the suggestion since it seems to be the best suggestion right now.


- LoadFont() - Line 278 (Raylib)
- LoadFontEx() - Line 310 (Raylib)
- LoadFontData() - Line 512 (Raylib)
- stbtt_GetCodepointBitmap() - Line 3630 (stb_truetype) 
- stbtt_GetCodepointBitmapSubpixel() - Line 3615 (stb_truetype) 
- stbtt_GetGlyphBitmapSubpixel() - Line 3573 (stb_truetype)

**Comment by Skabunkel** [comment]
Probabel fix is to use `stbtt_FreeBitmap` defined just above `stbtt_GetGlyphBitmapSubpixel`

**Comment by Skabunkel** [comment]
Another source might be 
- LoadFontData() - Line 498 (Raylib/text.c)

**Comment by Skabunkel** [comment]
Freeing the `font.chars[i].data` befor freeing `font.chars` resulted in a return of 30,07KB

- 30,07KB // Free char.Data
- 3,38KB // Freeing chars
Total of 33,45 KB freed, 6,16KB less then what was allocated.

**Comment by Skabunkel** [comment]
Reading what `stbtt_FreeBitmap` does it is unessesary in this case. (If you know better tell me so)
free does the trick just fine.

I can have a quick fix if so desired, however there is still data somewhere that is not deleted, the debugger isn't sure where it is tough. So it is going to requier more digging.

**Comment by Skabunkel** [comment]
Pull request #766

**Comment by Skabunkel** [comment]
![capture](https://user-images.githubusercontent.com/9131566/53293069-6131fc80-37cd-11e9-9f63-f4f264668199.PNG)

**Comment by raysan5** [comment]
@Skabunkel Nice work! Thank you very much! Keep me updated if you got more info on the lost bytes!

**Comment by Skabunkel** [comment]
Running a few cycles and watching the memory, it seems the remaining objects are stack frames. I'm, unsure where they are allocated, tough the ide tells me they are external frames.

**Comment by Skabunkel** [comment]
If this is the case it should be nothing to worrie about, and the reason i see them i the ide is because they are just expanding the heap by random allocation.

Though i will be running the suggested program above for 1hour nonstop to see if there is a diffrence.

**Comment by Skabunkel** [comment]
10 minutes process is holding steady at 37.1-35.7 MB

**Comment by raysan5** [comment]
nice! :D

**Comment by Skabunkel** [comment]
1h in process is holding steady at 35.5-36.8 MB, seems that there is no more memory to free, is just the debuggers profiler playing tricks on me.
Ex.
![memorys](https://user-images.githubusercontent.com/9131566/53299887-a6434680-3840-11e9-8bfc-b6bda7ed7e3b.PNG)

This seems bad, but it's just the area being watched by the debugger increasing and and nothing more.

So this issue is solved.
