### ISSUE TITLE
On Raspbian with Kernel 4.19: failed to add service - already in use?

### ISSUE THREAD

**Issue by pixelogik** [raysan5/raylib#771]
After updating to the newest kernel I can't start any of the examples. 

Console message is

INFO: Initializing raylib 2.4-dev
* failed to add service - already in use?

Does anybody have an idea on this?

**Comment by raysan5** [comment]
Are you compiling raylib/examples for native RPI or Linux Desktop? What OpenGL driver did you enabled? native or desktop?

**Comment by pixelogik** [comment]
@raysan5 I compiled the library for native RPI. After selecting "Legacy Non-GL Desktop Driver" it works btw. Seems to be a common issue with the new kernel and OpenGL hardware acceleration? 

Before the kernel update it worked nicely with the "GL (full KMS)" option.

**Comment by raysan5** [comment]
@pixelogik Yes, actually I was aware of this issue.

**Comment by DarkElvenAngel** [comment]
@pixelogik what kernel version are you running that's giving this issue?
