### ISSUE TITLE
Doesn't compile simple_game for android

### ISSUE THREAD

**Issue by protondev** [raysan5/raylib#774]
```
C:\Users\Mercury\raylib\raylib\templates\simple_game>C:\MinGW\bin\mingw32-make PLATFORM=PLATFORM_ANDROID

mingw32-make -f Makefile.Android
mingw32-make[1]: Entering directory 'C:/Users/Mercury/raylib/raylib/templates/si
mple_game'
if not exist android.simple_game mkdir android.simple_game
/usr/bin/sh: -c: line 1: syntax error: unexpected end of file
Makefile.Android:142: recipe for target 'create_temp_project_dirs' failed
mingw32-make[1]: *** [create_temp_project_dirs] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/Mercury/raylib/raylib/templates/sim
ple_game'
Makefile:293: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by raysan5** [comment]
@protondev Are you launching Makefile from a DOS window?

**Comment by protondev** [comment]
Yes.

6 Mart 2019 Çarşamba tarihinde Ray <notifications@github.com> yazdı:

**Comment by raysan5** [comment]
Reviewed build paths in commit https://github.com/raysan5/raylib/commit/0bbf857b00ab111749aa7ae22d942108ef06455f

Just tested and seems to work ok, just make sure to build raylib Android library before building game and library libraylib.a is generated in raylib/src directory.

**Comment by rmn20** [comment]
I had a similar issue, it was because mingw32-make used bash instead of cmd. SHELL=cmd helped.
