### ISSUE TITLE
No release folder

### ISSUE THREAD

**Issue by StaRT1337** [raysan5/raylib#776]
Hello, whenever I install raylib, there is no release folder inside raylib. I am running Windows 10.

**Comment by raysan5** [comment]
Yes, it's expected to be that way. I was changed some time ago.

**Comment by somerandomdev49** [comment]
So how would you follow tutorials on VS2017? It depends on the `releases` folder :(

**Comment by raysan5** [comment]
@somerandomdev49 which tutorials? Provided VS2017 solutions compile raylib and generate required directories automatically.
