### ISSUE TITLE
suggested functions

### ISSUE THREAD

**Issue by williamfjm** [raysan5/raylib#777]
hello I am writing this thread at the suggestion of raylib, in the community that uses this library in Discord, I proposed the following functions.

1.The PollInputEvents () function is only executed by redrawing a scene, but it loads the machine, in my case I needed to redraw in case of an event. For that I had to make it visible from the outside.

`RLAPI void events_new(void); `
in raylib.h
and
```
void events_new(void){
    PollInputEvents();              // Poll user events
}
```
in core.c

2. TakeScreenshot goes through memory not volatil.y in my case that is a problem because I'm working on raspberry and the sd has problems with writing, if they are too many.so I create a function that returns an image in ram.

```
Image TakeScreenshotImage (void)
{
#if defined (PLATFORM_DESKTOP) || defined (PLATFORM_RPI)
    unsigned char * imgData = rlReadScreenPixels (renderWidth, renderHeight);

    Image image = {imgData, renderWidth, renderHeight, 1, UNCOMPRESSED_R8G8B8A8};
   TraceLog (LOG_INFO, "Exported image");
return image;
    
#endif
}
```
3. This function is very specific, but maybe someone else could be useful. I needed to create a transparency in the image that I obtained with the previous function, a cut that should disappear. 

```
void ImageCrop_negative(Image *image, Rectangle crop)
{
    // Security checks to make sure cropping rectangle is inside margins
    if ((crop.x + crop.width) > image->width)
    {
        crop.width = image->width - crop.x;
        TraceLog(LOG_WARNING, "Crop rectangle width out of bounds, rescaled crop width: %i", crop.width);
    }

    if ((crop.y + crop.height) > image->height)
    {
        crop.height = image->height - crop.y;
        TraceLog(LOG_WARNING, "Crop rectangle height out of bounds, rescaled crop height: %i", crop.height);
    }

    if ((crop.x < image->width) && (crop.y < image->height))
    {
        // Start the cropping process
        Color *pixels = GetImageData(*image);   // Get data as Color pixels array
       // Color *cropPixels = (Color *)malloc((int)image->width*(int)image->height*sizeof(Color));
        for (int j = (int)crop.y; j < (int)(crop.y + crop.height); j++)
        {
            for (int i = (int)crop.x; i < (int)(crop.x + crop.width); i++)
            {
                pixels[j*image->width + i] = BLANK;
            }
        }


        // printf("cortados----------------%d\r\n",t);
        int format = image->format;

        UnloadImage(*image);

        *image = LoadImageEx(pixels, (int)image->width, (int)image->height);

        //free(cropPixels);
        free(pixels);
        // Reformat 32bit RGBA image to original format
        ImageFormat(image, format);
    }
    else
    {
        TraceLog(LOG_WARNING, "Image can not be cropped, crop rectangle out of bounds");
    }
}

```

**Comment by raysan5** [comment]
Hi @williamfjm, thanks for the suggested functions! Some quick answers:

1. raylib already provides `SUPPORT_EVENTS_WAITING` compile flag to wait for events instead of events polling every frame. Not sure about the need of exposing that function.

2. Good idea. I'll redesign it and expose some kind of `ImageScreenshot()`.

3. I think you can already do the same just using `ImageDrawRectangle()`

**Comment by williamfjm** [comment]
It was my fault I did not read the documentation well, and I did not know that compilation flag.

and I never thought about the transparent rectangle ... I think it would be more efficient than the function that I modified.

I hope the second function is useful for someone else

thanks raysan.

**Comment by raysan5** [comment]
Implemented `GetScreenData()` on commit https://github.com/raysan5/raylib/commit/f02a0334d8f86277916c52b274a0c7c21b6b9cd0.

This function is name-consistent with `GetTextureData()`.
