### ISSUE TITLE
Using a package manager breaks the current documentation.

### ISSUE THREAD

**Issue by carlsmith** [raysan5/raylib#778]
I'm on OS X, and being able to install raylib with `brew` is nice and convenient, but the raylib wiki assumes you have access to the scripts and examples bundled with the library.

I previously used raylib on Linux, where I cloned the repo from GitHub, so the library was available in my home directory, making it easy to access the bundled files.

When using `brew` on OS X, are we supposed to just use raylib from the directory `brew` puts it in (`/usr/local/Cellar/raylib/2.0.0`), or am I missing something?

Either way, the OS X wiki page should probably be updated to explain how to use raylib once `brew install raylib` has finished.

P.S. Is there a current raylib tutorial, or is it better to start by reading the examples?

**Comment by Leinnan** [comment]
Trying to use it same way as on Linux dindt work out?

**Comment by carlsmith** [comment]
I was really just wondering if that's correct.

It's easy enough to navigate to the system directory that `brew` puts raylib in, but it seems awkward to use a library that way (on Mac or Linux). Scripts will normally live somewhere in the home directory if we're supposed to execute them directly.

I'll personally create an IPython `ray` command or something for myself, no problem. I just wondered if I'd misunderstood something.

**Comment by carlsmith** [comment]
I've opened a similar, broader issue (#780) that makes this one pretty much redundant, so will close it now.

Thanks for your help @Leinnan.
