### ISSUE TITLE
[build] VSCode can't start executable after compiling

### ISSUE THREAD

**Issue by BenTearzz** [raysan5/raylib#781]
So, I followed the ["Using raylib in VSCode"](https://github.com/raysan5/raylib/wiki/Using-raylib-in-VSCode) guide. When launching the "Debug" run task. It successfully outputs an executable called `game.exe`, but when launching, it's trying to launch `main.exe`. So it gives the error `main` is not an executable.

This is what it runs:
`gcc -o game main.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Wl,--subsystem,windows -I. -IC:/raylib/raylib/release/include -IC:/raylib/raylib/src -IC:/raylib/raylib/src/external C:/raylib/raylib/raylib.rc.data -L. -LC:/raylib/raylib/release/libs/win32/mingw32 -LC:/raylib/raylib/src  -lraylib -lopengl32 -lgdi32 -DPLATFORM_DESKTOP`

Oh, it also seems that `C:/raylib/raylib/raylib.rc.data` doesn't actually exist, so that also returns an error each time.

**Comment by BenTearzz** [comment]
Now it doesn't even generate the executable anymore. This is the error I'm getting. (I haven't changed any files)
`gcc: error: C:/raylib/raylib/raylib.rc.data: No such file or directory`

**Comment by raysan5** [comment]
Unfortunately, I'm not giving support for VSCode. Closing this issue.
