### ISSUE TITLE
Raylib won't make after I  type in the necessary commands

### ISSUE THREAD

**Issue by sbarton19** [raysan5/raylib#782]
I type in  `make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_21`
in my raspberry pi terminal and nothing happens. It comes up with an error message saying:
`In file included from external/glfw/src/internal.h:187:0,
                 from external/glfw/src/context.c:28,
                 from rglfw.c:54:
external/glfw/src/x11_platform.h:33:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
compilation terminated.
Makefile:499: recipe for target 'rglfw.o' failed
make: *** [rglfw.o] Error 1
`

**Comment by raysan5** [comment]
Do you have `Xlib.h` library installed in the system? It seems a user missing library issue.
