### ISSUE TITLE
[build] Better web building instructions

### ISSUE THREAD

**Issue by valtsu41** [raysan5/raylib#784]
In my opinion the wiki tutorial to build for web is too focused on Windows, could Linux and macOS instructions be added too?

**Comment by raysan5** [comment]
@valtsu41 Unfortunately I don't use those platforms but Wiki is open for edit, feel free to include additional information for those platforms.

**Comment by valtsu41** [comment]
Another question I have to ask, is there no support for building web apps on raspberry pi?

**Comment by raysan5** [comment]
I don't know if emscripten is available for RPI processor...

**Comment by valtsu41** [comment]
Well, i tried and managed to install it as a debian package, but when I `make` it says `emcc` is not a command, even I can run it from terminal myself...

**Comment by raysan5** [comment]
then maybe it's a path issue, not properly configured.

**Comment by valtsu41** [comment]
Ok I managed to build emscripten from source and then install raylib by copy-pasting the makefile instructions.
