### ISSUE TITLE
[core] Motion controls do not work in CAMERA_THIRD_PERSON mode

### ISSUE THREAD

**Issue by lenormf** [raysan5/raylib#790]
Hitting the motion keys in third person mode is a no-op.

I reckon the values set by the code that handles motion in the following block:

https://github.com/raysan5/raylib/blob/c200642887a8a5a4fd38168aee224dc9fc9906ab/src/camera.h#L402,L414

are then being overridden by the following bit:

https://github.com/raysan5/raylib/blob/c200642887a8a5a4fd38168aee224dc9fc9906ab/src/camera.h#L471,L474

**Comment by raysan5** [comment]
Issue reviewed on commit https://github.com/raysan5/raylib/commit/cc1dd6b410ca8c6ba2b9dd1a923c7740034cd1d9
