### ISSUE TITLE
[core] GLFW can not initialize requested OpenGL 3.3 context

### ISSUE THREAD

**Issue by Yzubi** [raysan5/raylib#796]
Os: Lubuntu 18.10 32-bit
```

./light_my_ritual 
INFO: Initializing raylib 2.5-dev
WARNING: [GLFW3 Error] Code: 65543 Decription: GLX: Failed to create context: GLXBadFBConfig
WARNING: GLFW Failed to initialize Window
INFO: Audio device initialized successfully
INFO: Audio backend: miniaudio / PulseAudio
INFO: Audio format: 32-bit IEEE Floating Point -> 16-bit Signed Integer
INFO: Audio channels: 2 -> 2
INFO: Audio sample rate: 44100 -> 48000
INFO: Audio buffer size: 1440
INFO: [resources/lights_map.png] Image loaded successfully (128x72)
INFO: [resources/font_arcadian.png] Image loaded successfully (512x512)
Segmentation fault (core dumped)
```

**Comment by raysan5** [comment]
It seems OpenGL context can not be created... are you using an old device? Does your GPU support OpenGL 3.3? did you update GPU drivers?

**Comment by Yzubi** [comment]
I'ts an really old IBM x60s laptop, it don't support opengl 3.3.

```
glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 Mesa 18.2.2
```

**Comment by raysan5** [comment]
That's what I thought... then you should recompile raylib for OpenGL 1.1 or OpenGL 2.1, those options are available to run raylib on old devices.

**Comment by Yzubi** [comment]
How do that on Linux? Only found this link, that uses a Notepad++ script: https://github.com/raysan5/raylib/wiki/FAQ

**Comment by raysan5** [comment]
@Yzubi you can do it with provided Makefile on `raylib/src` directory. From shell just execute:
```
raylib/src/> make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_21 -B
```
`libraylib.a` should be generated on the same directory, you need to copy it on system libraries path.

**Comment by Yzubi** [comment]
Thanks! It worked! :)

**Comment by arydevy** [comment]
It dosent work for me i have opengl2.1

**Comment by arydevy** [comment]
@raysan5

**Comment by raysan5** [comment]
@arydevy did you recompile raylib for OpenGL 2.1? Maybe your system does not support some OPenGL 2.1 features... You can also try recompiling for OpenGL 1.1.

**Comment by arydevy** [comment]
> @arydevy did you recompile raylib for OpenGL 2.1? Maybe your system does not support some OPenGL 2.1 features... You can also try recompiling for OpenGL 1.1.

i tryed your command @raysan5 an on other linux distro it worked perfctrly (manjaro) now i use linux 
mint

**Comment by arydevy** [comment]
i also tried 11 ant it dosent work

**Comment by yamunan-bitset** [comment]
Another thing you can do is
```
    export MESA_GLSL_VERSION_OVERRIDE=330
    export MESA_GL_VERSION_OVERRIDE=3.3
```
This overrides your GL versions to 3.3. You can also use this for many other programs that need a higher OpenGL version.

**Comment by vinnyhorgan** [comment]
Thanks a lot Ray! I didn't realize the default build was for OpenGL 3...
