### ISSUE TITLE
[shapes] DrawPolyEx() Only first three and last two vertices render properly

### ISSUE THREAD

**Issue by RaySoyama** [raysan5/raylib#797]
Example Code
	
```cpp
Vector2 testPoly [10] =
{
	{0,0},   //these render properly
	{0,100},
	{75,50},

	{150,100},//These freak out
	{225,50},
	{300,100},
	{375,50},
	{450,100},

	{600,100},  //These render properly
	{600,0}
};
//...... update & draw

DrawPolyEx(testPoly,10,LIGHTGRAY);

```
pink dots represents what the polygon should look like

![image](https://user-images.githubusercontent.com/42445829/56062780-6bc73780-5d22-11e9-8dc8-52516543dc21.png)

**Comment by jamesl-github** [comment]
doesn't that array have 10 elements ?
what if you change the 8 to a 10 ? 
DrawPolyEx(testPoly,10,LIGHTGRAY);

**Comment by RaySoyama** [comment]
Woops, you're right, they should be a 10. The issue still persists though

**Comment by RaySoyama** [comment]
Woops, you're right, they should be a 10. The issue still persists though

**Comment by raysan5** [comment]
Ok, checked it. `DrawPolyEx()` not expected to be used in that way... it is designed to draw triangles from a center point (first provided point) to the next 2 points. Triangle after triangle... but always considering first point as one of the triangle vertex. Here an explanatory image:

![drawpoly_issue](https://user-images.githubusercontent.com/5766837/56079121-5f111500-5df0-11e9-8224-166438b4d35d.png)

Note that third triangle drawn just draws over second triangle.

Solution: Don't use `DrawPolyEx()`. Just define all required triangles one by one into a `Vector2` array (3 vertex by triangle) and draw them using `DrawTriangle()`.
