### ISSUE TITLE
How to Display text and image over running video ?

### ISSUE THREAD

**Issue by superuser789** [raysan5/raylib#804]
Hi.
I  am working on creating some gui for RPi3 without X11.  I want to display text & image over mpv which is running a video. mpv has been built following this [guide](https://www.raspberrypi.org/forums/viewtopic.php?t=199775) .
I tried to use ` FLAG_WINDOW_TRANSPARENT=16` in make command i.e.  while playing video using mpv , I  built core_basic_window.c example using ` make core/core_basic_window PLATFORM=PLATFORM_RPI  FLAG_WINDOW_TRANSPARENT=16`. But same white window is displayed covering running video.
 
I want to make just text and image appearing over video while video is still visible in the background.
 Could you guide me how to achieve it.

Thanks

**Comment by raysan5** [comment]
Sorry @superuser789, it seems EGL does not support a transparent framebuffer on native mode. Actually tried to add it to raylib some time ago and I couldn't. Here it is the [relevant code part](https://github.com/raysan5/raylib/blob/master/src/core.c#L2557), in case you want to do some investigation on the subject.
