### ISSUE TITLE
[audio] Update miniaudio (PulseAudio backend is broken)

### ISSUE THREAD

**Issue by iskolbin** [raysan5/raylib#806]
Hi, tried master branch audio examples on Ubuntu 18.04, they are not working. No sound/music + CloseAudioDevice function blocks application. As I understand this is due to the bug in miniaudio PulseAudio backend 'cos after disabling it and falling back to ALSA everything works fine. After updating miniaudio to 0.9.2 PulseAudio works ok.

**Comment by raysan5** [comment]
Updated miniaudio to 0.9.3 in commit https://github.com/raysan5/raylib/commit/c7907a203b8bdc3027fc9b01c9780acc640794cd
