### ISSUE TITLE
[rlgl] feature req: two sided materials.

### ISSUE THREAD

**Issue by sanderboer** [raysan5/raylib#811]
Hi,

I just commented out the call to glEnable(GL_CULL_FACE) in rlgl.h to enable me to write a basic double sided shader using if(!gl_FrontFace){color=another_color;)

To me and my use case for raylib, the option for double sided materials would be welcomed.
I can imagine that the lowest hanging fruit is a compile switch (#define BACKFACE_CULL_OFF) to a full-fledged implementation in an ubershader type of situation.

Are there plans for this type of situation ?

thanks.
Sander

**Comment by raysan5** [comment]
@sanderboer Some other users already asked for that function, I'll try to expose it in some way to main raylib API.

**Comment by raysan5** [comment]
Added `rlEnableBackfaceCulling()` and `rlDisableBackfaceCulling()` on commit https://github.com/raysan5/raylib/commit/7c10f971c1f8edfc65b074aceec7c3a0696c9b87.

Those functions should be called through `rlgl`.
