### ISSUE TITLE
[core] HiDPI Windows display renders small in lower-left quadrant

### ISSUE THREAD

**Issue by hotdiggitydoddo** [raysan5/raylib#814]
I made a small demo with a ball that bounces off the walls of the game window.  I've set the window to be 1280x720.

With line 2361 commented out in core.c, everything is small: the window, the ball - but the demo behaves correctly:
![image](https://user-images.githubusercontent.com/2938036/56641119-768aa200-6629-11e9-827f-148b54ba0b99.png)

When I uncomment line 2361, the window is the correct size but the ball still renders small and only wants to move in the lower-left quandrant of the window, bouncing off an invisible wall on top and right:

![image](https://user-images.githubusercontent.com/2938036/56640990-27447180-6629-11e9-8143-5467f987b7af.png)

For what it's worth, everything works perfectly on my Macbook Pro Retina.

**Comment by raysan5** [comment]
Hi @hotdiggitydoddo, I'm aware of this issue. Latest GLFW implemented some functions to deal with it but it requires some work:

Monitor scaling factor can be obtained with `glfwGetWindowContentScale()` but that factos should be applied to full content drawing and inputs... that's not trivial...

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/raylib/commit/bb2841a26d2c118b2febfc02c6cab7f7b2791893.

**Comment by hotdiggitydoddo** [comment]
Unfortunately, the issue has returned with the latest commits on master as of now (3e0e910).  The only difference this time around is that by default, the window behaves perfectly but is just very small.  The same can be said about all the examples.  Tied specifically to Windows HiDPI it seems.  I notice that the width and height returned in the GLFWvidmode object (core.c, line 2386) are reporting 2x the size than they are when I run the code on MacOS.

**Comment by raysan5** [comment]
Did you activate `SUPPORT_HIGH_DPI` flag in [config.h](https://github.com/raysan5/raylib/blob/master/src/config.h#L54), disabled by default?

**Comment by hotdiggitydoddo** [comment]
false alarm, amigo. =)  I neglected to generate the VS sln myself on download and used VS default one.

**Comment by xdrie** [comment]
@raysan5 why is HIDPI disabled by default? i don't see a reason to not just enable the support by default?

**Comment by raysan5** [comment]
@xdrie because it does not fully work on some platforms (macOS) and I prefered to stay with a fully working solution by default.
