### ISSUE TITLE
[core] How to display smaller window in raspberry pi ?

### ISSUE THREAD

**Issue by superuser789** [raysan5/raylib#816]
Hi,
I have created a gui menu for raspberry pi 3 using raylib running on Raspbian Stretch Lite . Whatever height and width I set in  InitWindow function. Gui window takes up the whole screen. I want to display the window, smaller in size.
e.g.  on  setting width as 600 & height as 300,  I get this output :
```
INFO: UPSCALING: Required screen size: 600 x 300 -> Display size: 1360 x 768
INFO: Display device initialized successfully
INFO: Display size: 1360 x 768
INFO: Render size: 600 x 339
INFO: Screen size: 600 x 300
```
Please guide me.

Thanks & Regards

**Comment by raysan5** [comment]
If you're running your program in native mode (no XWindow), I'm afraid that's not possible.
