### ISSUE TITLE
[Build] cannot find -lraylib

### ISSUE THREAD

**Issue by Tetat-Chulchue** [raysan5/raylib#818]
Here is the error message

> Executing task: C:/raylib/mingw/bin/mingw32-make.exe RAYLIB_PATH=C:/raylib/raylib <

```
mingw32-make game
mingw32-make[1]: Entering directory 'c:/Users/jobja/Desktop/Project/it-metroidvania'
gcc -o game main.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces -Wl,--subsystem,windows -I. -IC:/raylib/raylib/release/include -IC:/raylib/raylib/src -IC:/raylib/raylib/src/external C:/raylib/raylib/raylib.rc.data -L. -LC:/raylib/raylib/release/libs/win32/mingw32 -LC:/raylib/raylib/src  -lraylib -lopengl32 -lgdi32 -DPLATFORM_DESKTOP
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lraylib
collect2.exe: error: ld returned 1 exit status
Makefile:314: recipe for target 'game' failed
mingw32-make[1]: *** [game] Error 1
mingw32-make[1]: Leaving directory 'c:/Users/jobja/Desktop/Project/it-metroidvania'
mingw32-make.exe: *** [Makefile:310: all] Error 2
The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.


```
By the way I'm using VSCode 

Thank in advance.

**Comment by a3f** [comment]
Are you using the [VSCode Project template](https://github.com/raysan5/raylib/tree/master/projects/VSCode)? Do you have raylib built in `C:/raylib/raylib/src`?

**Comment by Tetat-Chulchue** [comment]
Yes, I'm using the VSCode Project template. I don't sure that I have  raylib built in `C:/raylib/raylib/src`

But I use the raylib_installer_v2.0

**Comment by a3f** [comment]
Where did the installer install raylib too? Can you search there for a `libraylib.a`?

**Comment by Tetat-Chulchue** [comment]
It install directly to my C drive. here is my path to raylib folder `C:\raylib`.
I searched and I dont found a `libraylib.a`.

**Comment by a3f** [comment]
Umm, that's strange, not even a `raylib.a`? Well, @raysan5 can surely help. I haven't used the installer myself so far.

**Comment by Tetat-Chulchue** [comment]
Thank for answering me anyway.

**Comment by raysan5** [comment]
@Tetat-Chulchue Installer is quite outdated, VSCode template from installer could also be broken.

You should try to use latest raylib from GitHub.

**Comment by Tetat-Chulchue** [comment]
Thank! I'll give it a try.

**Comment by Eddippla** [comment]
I am also having this issue, it would be great if someone could help me. I made my own project from scratch, with this tutorial:
https://www.youtube.com/watch?v=HPDLTQ4J_zQ, I am not sure how to fix this.

**Comment by thatpersonthatw** [comment]
Hey, I too am also having this problem. I have raylib 4.2.0 installed.

**Comment by mziskandar** [comment]
Hello.
In my case  (msys2), there's "libraylib.dll.a". I'm using "-lraylib.dll" instead of "-lraylib".
