### ISSUE TITLE
[text] MeasureTextEx with non baseSize font size will give the wrong result

### ISSUE THREAD

**Issue by olafurw** [raysan5/raylib#825]
So if I setup a simple test case of a bit of text, measure how long that text is and then draw a line under it to match the length, it will match correctly if I use the font's `.baseSize` but if I use any other font size, it will not match. Here in the example I am using a font size of 15 and the Windows Font Consolas.

```cpp
while (!WindowShouldClose())
{
	BeginDrawing();
	ClearBackground(PINK);

	const char* text = "Hello world, I am text that is pretty long";
	const int textWidth = MeasureTextEx(fontRegular, text, 15, 1).x;
	DrawTextEx(fontRegular, text, Vector2{0, 0}, 15, 1, Color{ 0, 0, 0, 255 });
	DrawRectangle(0, 18, textWidth, 2, Color{ 255, 255, 255, 255 });

	EndDrawing();
}
```
![image](https://user-images.githubusercontent.com/103783/57137703-f1358900-6db0-11e9-93b7-9e7ce70f67e3.png)

**Comment by olafurw** [comment]
Here is another test that shows that this might be a rounding issue.

```cpp
int main(int argc, char* argv[])
{
	InitWindow(screenWidth, screenHeight, "q-n-a");

	SetTargetFPS(60);

	Font fontRegular = LoadFont("consola.ttf");
	SetTextureFilter(fontRegular.texture, FILTER_BILINEAR);

	float size = 15;

	while (!WindowShouldClose())
	{
		BeginDrawing();
		ClearBackground(PINK);

		const char* text = "Hello world, I am text aaaa";
		const int textWidth = MeasureTextEx(fontRegular, text, size, 1).x;
		DrawTextEx(fontRegular, text, Vector2{ 0, 0 }, size, 1, Color{ 0, 0, 0, 255 });
		DrawRectangle(0, 18, textWidth, 2, Color{ 255, 255, 255, 255 });

		DrawTextEx(fontRegular, TextFormat("%d", textWidth), Vector2{ 0, 40 }, 20, 1, Color{ 0, 0, 0, 255 });
		DrawTextEx(fontRegular, TextFormat("%.2f", size), Vector2{ 0, 65 }, 20, 1, Color{ 0, 0, 0, 255 });

		size += 0.03f;

		if (size >= 34)
		{
			size = 15;
		}

		EndDrawing();
	}

	UnloadFont(fontRegular);

	CloseWindow();
	return 0;
}
```

![raylibfont](https://user-images.githubusercontent.com/103783/57142951-08c73e80-6dbe-11e9-8d37-15726307bc08.gif)

**Comment by raysan5** [comment]
@olafurw nice, thank you very much for the tests!

**Comment by raysan5** [comment]
@olafurw It should be corrected with commit https://github.com/raysan5/raylib/commit/528e164ac5e1a4ecca404c7f54e98325a55b959f. Please, let me know if it works now.

**Comment by olafurw** [comment]
Confirmed. Works beautifully.
