### ISSUE TITLE
[core] Mouse position reports incorrect values on macOS

### ISSUE THREAD

**Issue by prime31** [raysan5/raylib#826]
It seems the GetMousePosition is reporting mouse coordinates that are half of the actual mouse position on macOS. Tested with version 2.5.

```c
DrawText(TextFormat("Mouse: %.1f, %.1f", GetMousePosition().x, GetMousePosition().y), 400, 10, 20, RED);
DrawText(TextFormat("Screen Size: %i, %i", screenWidth, screenHeight), 400, 30, 20, RED);
```

![mousepos](https://user-images.githubusercontent.com/60377/57174631-aa6a8200-6df6-11e9-9362-57832ae6db37.gif)

**Comment by a3f** [comment]
Can you try current master? Especially https://github.com/raysan5/raylib/commit/f44888e466ad63eccec229bdcc091f8f7e2f629e looks like it could be addressing this.

**Comment by prime31** [comment]
Switched to master (and ensured I have the changes from f44888e) and I'm still seeing the same thing.

**Comment by prime31** [comment]
So, if Im following correctly, Core.c around line 2911 ends up setting the mouseScale to 0.5:

```
#if defined(PLATFORM_DESKTOP) && defined(SUPPORT_HIGH_DPI)
    glfwGetFramebufferSize(window, &fbWidth, &fbHeight);

    // Screen scaling matrix is required in case desired screen area is different than display area
    screenScaling = MatrixScale((float)fbWidth/screenWidth, (float)fbHeight/screenHeight, 1.0f);
    SetMouseScale((float)screenWidth/fbWidth, (float)screenHeight/fbHeight);
#endif
```

On a related sidenote, is there any good reason to not just use a standard size framebuffer and scale it? Seems like a lot of extra pixels to try to fill as the default settings.

**Comment by raysan5** [comment]
@prime31 thanks for reporting. Could you try commenting `SUPPORT_HIGH_DPI` [here](https://github.com/raysan5/raylib/blob/master/src/core.c#L135), it is forced on macOS.

 > On a related sidenote, is there any good reason to not just use a standard size framebuffer and scale it? Seems like a lot of extra pixels to try to fill as the default settings.

Yeah, we are processing extra pixels but scaling the window-system-provided default framebuffer is not possible (as far as I know), it will require using a RenderTexture (fbo) and it will require redesigning how raylib works...

**Comment by prime31** [comment]
Commenting out `SUPPORT_HIGH_DPI` seems to do the trick.

**Comment by raysan5** [comment]
@prime31 what macOS version are you using and what device? did you configure something in the system for high-DPI display?

Commenting `SUPPORT_HIGH_DPI` completely disables High-DPI...

**Comment by prime31** [comment]
I’m using a 2018 MacBook Pro running the latest build of Mojave. Nothing special configured with regard to high DPI. SDL seems to work fine for me. I have no GLFW experience though so no idea what it could be there.

**Comment by gianlucagiorgolo** [comment]
I get the same kind of behavior on a macOS High Sierra (similarly with no special DPI configuration)

**Comment by kstarzyk** [comment]
Same issue on MBP 2016 with Mojave

**Comment by sirscriptalot** [comment]
Ran into this issue myself, the work around I implemented was setting the mouse scale before querying for the mouse position: `SetMouseScale(1.0, 1.0);`

**Comment by raysan5** [comment]
Implemented a possible solution on commit https://github.com/raysan5/raylib/commit/f346c672fb411b33dc065188ef0d2f107ce55040.

But I also updated GLFW to latest version that maybe also deals with this issue.

Feel free to reopen or leave your comments if you test it!

**Comment by G3bE** [comment]
Fix works on 2013 Macbook Air MacOS Catalina 10.15.1

**Comment by raysan5** [comment]
@G3bE nice! Thanks for the feedback! :)

**Comment by louisgjohnson** [comment]
Had the same issue, fixed by `SetMouseScale(1.0, 1.0)` I'm using the rust raylib package so I'm not sure if its up to date with master

**Comment by dhharris** [comment]
Not sure if this is related, but I've been having difficulty mapping mouse position to the actual position on screen. I have the camera set up to point at the character, but I am seeing different results for the mouse position compared to the camera position when I click the character.

**Comment by G3bE** [comment]
As long as you're on raylib version 2.6.0 this shouldn't be related and if you're using homebrew to install raylib and keep your packages up-to-date this should be the case

**Comment by dhharris** [comment]
@G3bE I am using the latest master of raylib

**Comment by G3bE** [comment]
If you're on master your problem is not related to this issue. If you need help feel free to ask on the [discord](https://discord.gg/mzCY3wN)
