### ISSUE TITLE
[examples] core_loading_thread is racy and broken

### ISSUE THREAD

**Issue by a3f** [raysan5/raylib#827]
https://github.com/raysan5/raylib/blob/0fe409bfa9ce86aaf2ca19f76c7a452739aff6f1/examples/core/core_loading_thread.c#L21-L24

A plain `bool` (or any plain data type for that matter) can't be used for inter-thread synchronization. 

https://github.com/raysan5/raylib/blob/0fe409bfa9ce86aaf2ca19f76c7a452739aff6f1/examples/core/core_loading_thread.c#L113-L133

* The compiler has all the right to optimize an `if (dataLoaded)` into an `if (false)`, because it doesn't need to be aware that `LoadDataThread` can execute concurrently to the `main` function containing the `if (dataLoaded)`.

* The compiler has all the right to reorder `dataLoaded` and move it above the loop, because there's no barrier enforcing the order of writes.

Likewise the processor can reorder the accesses as well.

The best course of action seems to me is to use C11 atomics. Using GCC builtins or mutexes (or even worse open coding atomic using `volatile` and memory barries) isn't what I would suggest to beginners. Another solution would be using semaphores, but they're now deprecated on macOS.

The problem with C11 atomics is that raylib only requires C99, but I think for example code using C11 is fine, if there are no good alternatives.

**Comment by a3f** [comment]
I've settled on fixing the race by using C11 atomics and pushed a fix for this issue.

**Comment by raysan5** [comment]
Thanks for the fix @a3f, I'm not used to multi-threading and that solution worked for me in the past. Thank you very much for the detailed explanation! :D

**Comment by beetaa** [comment]
@raysan5 when compiling examples for desktop (win11, mingw64), all goes well using `c99`, but when compiling examples for html5 using `c99`,  `core_loading_thread` problem appears. version of raylib is `4.50-dev` 

![image](https://user-images.githubusercontent.com/5688224/199927619-2b651743-367b-4ad0-8d3f-64ad55b063cb.png)

I tried the use `c11` for compiling:

![image](https://user-images.githubusercontent.com/5688224/199928362-1ef399df-63b8-47a0-8a01-6fc2ee3738f6.png)

but the problem still there. I google and found [this article](https://groups.google.com/g/emscripten-discuss/c/G4nwFprZFYo?pli=1).

**Comment by planetis-m** [comment]
This example is still broken, for one the thread is leaked on exit. And reading the dataProgress variable leads to a data race.
