### ISSUE TITLE
[example/others][make] binaries/executables are not generated 

### ISSUE THREAD

**Issue by RowV** [raysan5/raylib#829]
I am working on Raspberry Pi 3 and able to build examples from the _examples_ folder except for _others_ and _network_ there are no executables inside these directories. I am not sure whether these examples are in development phase and are incomplete. I am using `make PLATFORM=PLATFORM_RPI` to build the examples.

**Comment by raysan5** [comment]
That's designed this way. `network` module is still on development and `others` examples could have specific needs or not depend directly on raylib, only on some of its modules (i.e `raudio`or `rlgl`modules).

Just reviewed the folder and removed non-working example `standard_lighting` and moved `bunnymark` to `textures_bunnymark`.
