### ISSUE TITLE
Setup Visual Studio

### ISSUE THREAD

**Issue by FFXV** [raysan5/raylib#830]
Hi there,

I am running the preconfigured examples with Visual Studio 2017 after having executed "raylib_installer_v2.0.exe" (raylib v2.0.0), and the compiler says the following: 
cannot open source file "raylib.h"
identifier "RAYWHITE" is undefined
identifier "MAROON" is undefined
Cannot open include file 'raylib.h': No such file or directory

I have also tried the step for step instruction (https://github.com/raysan5/raylib/wiki/Create-Visual-Studio-Project) but have no clue where raylib.lib is located or how I could create it.

Thanks for any help.

Anna

**Comment by raysan5** [comment]
Are you using latest raylib from github? or are you using the installer version?

**Comment by FFXV** [comment]
Thanks for your quick reply.
I am using the installer version (cf. edited issue).

**Comment by raysan5** [comment]
You should try with latest raylib from GitHub, the one you're using is almost one year old. 

Closing the issue in the meantime.

**Comment by gavriil07** [comment]
@FFXV check out this : [VS raylib tutorial](https://www.youtube.com/watch?v=JE7F7DLEjbo)
