### ISSUE TITLE
[build] Building VS2017 solution from master fails

### ISSUE THREAD

**Issue by olafurw** [raysan5/raylib#831]
Complains about "unresolved external symbol _timeBeginPeriod"

Seems that winmm.lib is missing from the libraries. I added it and it builds correctly.

**Comment by raysan5** [comment]
yeah, I know, please, could you send a PR? I don't know where I need to add them on the CMake pipeline...

**Comment by raysan5** [comment]
I misunderstood the issue, I'll correct it later today...

**Comment by raysan5** [comment]
Added in commit https://github.com/raysan5/raylib/commit/561c486ceb2d1563fbcd0bec60a1f1d9e94cb7c0.
