### ISSUE TITLE
raylib cheat sheet offline download

### ISSUE THREAD

**Issue by QuantumSno** [raysan5/raylib#834]
### Issue description
Lets get a downloadable version of the cheat sheet so that we can have an offline copy for those who work on the go. If we could get this in some standard file types, say PDF, Word, and maybe Pages for our mac users that would be good.

**Comment by Rover656** [comment]
There is one already available. See here: https://github.com/raysan5/raylib.com/blob/master/cheatsheet/raylib_cheatsheet.pdf

**Comment by raysan5** [comment]
@QuantumSno @Rover656 Added 2 hours ago in commit https://github.com/raysan5/raylib.com/commit/8968a408cf84bb7fdaa5cb42e63acc05b741ef52#diff-6e5537031c9ce6c01fe2299800afca02. :P

**Comment by marc9323** [comment]
> There is one already available. See here: https://github.com/raysan5/raylib.com/blob/master/cheatsheet/raylib_cheatsheet.pdf

That is a dead link.

**Comment by avelican** [comment]
@marc9323 https://github.com/raysan5/raylib.com/blob/master/cheatsheet/raylib_cheatsheet_v5.0.pdf
