### ISSUE TITLE
[models][RPi] Segfault when unloading obj file (Exiting the program)

### ISSUE THREAD

**Issue by RowV** [raysan5/raylib#836]
### Issue description

I have made low poly scooter model in Blender 2.8 which is then exported as OBJ file and loaded using  `examples/models/model_obj_loading.c` provided in Raylib repo. Now when I run the program it runs perfectly renders the obj model properly, but I get segmentation fault when esc button is pressed for terminating the program, specifically it occurs when unloading the model. 
Apparently segfault seems to occur when the OBJ file is made from multiple objects in Blender. But I don't get segfault at exit, if each part of scooter viz. handle, body, seat, wheels etc. are joined (Ctrl+J) as one single object before exporting as obj.
*NOTE: I am using same texture image png file for both obj file*

I have attached source and resources [here](
https://drive.google.com/drive/folders/1NGMMzrWuFxeGqlLgLBucvawbswcOGh9s?usp=sharing
)

### Environment

- Platform : Raspberry Pi 3B+
- Operating System : Raspbian GNU/Linux 9 (stretch)
- OpenGL version   : OpenGLES 2.0

### Issue Screenshot
Following is  screen shot of segfault at exit when vespa1.obj 
![Selection_007](https://user-images.githubusercontent.com/23165822/57772836-26889200-7734-11e9-9025-324ec6fc4fea.png)
Following is  screen shot when vespaJoined.obj file is loaded NO segfault when exiting
![Selection_008](https://user-images.githubusercontent.com/23165822/57774406-0f4ba380-7738-11e9-87d2-4ebdabc9f0ea.png)

### Code Example

```
#include "raylib.h"

int main()
{
    // Initialization
    //--------------------------------------------------------------------------------------
    int screenWidth = 800;
    int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [models] example - obj model loading");

    // Define the camera to look into our 3d world
    Camera camera = { 0 };
    camera.position = (Vector3){ -8.0f, 2.0f, 8.0f };    // Camera position
    camera.target = (Vector3){ 0.0f, 2.5f, 0.0f };      // Camera looking at point
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };          // Camera up vector (rotation towards target)
    camera.fovy = 45.0f;                                // Camera field-of-view Y
    camera.type = CAMERA_PERSPECTIVE;                   // Camera mode type

    Model model_bike = LoadModel("resources/vespa1.obj");                 // Load OBJ model_bike
    Texture2D texture = LoadTexture("resources/vespa1.png"); // Load model_bike texture
    model_bike.materials[0].maps[MAP_DIFFUSE].texture = texture;                 // Set map diffuse texture
    Vector3 position = { 0.0f, 0.0f, 0.0f };                                // Set model position

    SetTargetFPS(60);   // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        //...
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            BeginMode3D(camera);

                DrawModel(model_bike, position, 1.0f, WHITE);   // Draw 3d model with texture

                DrawGrid(10, 1.0f);         // Draw a grid

                DrawGizmo(position);        // Draw gizmo

            EndMode3D();

            DrawText("(c) Castle 3D model by Alberto Cano", screenWidth - 200, screenHeight - 20, 10, GRAY);

            DrawFPS(10, 10);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    UnloadTexture(texture);     // Unload texture
    UnloadModel(model_bike);         // Unload model

    CloseWindow();              // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}
```

**Comment by raysan5** [comment]
@RowV Thanks for the detailed report! I'll look into it as soon as possible.

**Comment by raysan5** [comment]
Issue corrected on commit https://github.com/raysan5/raylib/commit/5a1a0a34923fa8ecfcd5d45717b7db63f630b2a7.

Multi-mesh loading is not properly implemented just yet. Current implementation loads all objects in a single mesh.
