### ISSUE TITLE
[raudio] .XM music files doesn't restart when stop->play

### ISSUE THREAD

**Issue by selimanac** [raysan5/raylib#843]
When a music stops It should restart on play. But it is not working for .xm module files. It is just pausing the music.
Looks like it is not available [in source](https://github.com/raysan5/raylib/blob/c1594fa445d038e40bae22eb69dfa04cc406aca4/src/raudio.c#L1338) or am I missing something?

**Comment by raysan5** [comment]
@selimanac are you using latest raylib from github? Despite that comment, XM music should loop.

**Comment by selimanac** [comment]
@raysan5  I'm not using raylib completely. I'm using raudio + miniaudio and mod+xm jars within the other [game engine ](https://twitter.com/selimanac/status/1129666597130559488) for playing .mod and .xm files. Yes, I'm using latest from 'master branch'. And yes it is perfectly looping but I'm talking about stoping and playing again using `StopMusicStream` -> `PlayMusicStream`
Thank you

**Comment by raysan5** [comment]
oh, ok, yeah, that's an issue to review
