### ISSUE TITLE
Cheatsheet shows a color function that doesn't exist in v2.0 header file

### ISSUE THREAD

**Issue by Fib100** [raysan5/raylib#844]
The [cheatsheet](https://www.raylib.com/cheatsheet/cheatsheet.html) shows a color function `Color ColorFromHSV(Vector3 hsv); ` but it does not exist in the v2.0 header file.

Is it a new function for v2.5? Should it just get removed from the cheatsheet?

**Comment by mikaelssen** [comment]
[Header Position](https://github.com/raysan5/raylib/blob/c1594fa445d038e40bae22eb69dfa04cc406aca4/src/raylib.h#L922)

Seems to exist in the newest source, and v2.0 is outdated, compile from master branch and you'll pretty much be on v2.5. 👍

**Comment by raysan5** [comment]
@mikaelssen you're right.

**Comment by Fib100** [comment]
@mikaelssen Thanks for the clarification. I'm the type of person who likes to wait for the thoroughly tested stable releases though. Is there a v2.0 cheatsheet I could reference instead?

**Comment by mikaelssen** [comment]
> @mikaelssen Thanks for the clarification. I'm the type of person who likes to wait for the thoroughly tested stable releases though. Is there a v2.0 cheatsheet I could reference instead?

Sorry, It seems that ray updated it on the github page, [Git](https://github.com/raysan5/raylib.com/tree/master/cheatsheet) So all i can say is check out the commit history unfortantly. so there's no pure sheet unless he kept a PDF or something.  [Waybackmachine](https://web.archive.org/web/20180328121023/https://www.raylib.com/cheatsheet/cheatsheet.html)
