### ISSUE TITLE
[models] Terminal hangs when running models_animation example

### ISSUE THREAD

**Issue by RowV** [raysan5/raylib#845]
### Issue description

When executing *models_animation* terminal is completely freezing and I have to kill process using external task manager to gain back the control of the terminal. Also no render window is created and I cannot debug it in GDB either.

### Environment
Platform : Raspberry Pi 3B+
Operating System : Raspbian GNU/Linux 9 (stretch)
OpenGL version : OpenGLES 2.0

### Terminal Output
```
pi@raspberrypi:~/Raylib/examples/models $ ./models_animation 
INFO: Initializing raylib 2.5-dev
INFO: UPSCALING: Required screen size: 800 x 450 -> Display size: 800 x 480
INFO: Display device initialized successfully
INFO: Display size: 800 x 480
INFO: Render size: 800 x 480
INFO: Screen size: 800 x 450
INFO: Viewport offsets: 0, 30
INFO: GPU: Vendor:   Broadcom
INFO: GPU: Renderer: VideoCore IV HW
INFO: GPU: Version:  OpenGL ES 2.0
INFO: GPU: GLSL:     OpenGL ES GLSL ES 1.00
INFO: Number of supported extensions: 13
WARNING: [EXTENSION] VAO extension not found, VAO usage not supported
INFO: [EXTENSION] NPOT textures extension detected, full NPOT textures supported
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: Internal buffers initialized successfully (CPU)
INFO: Internal buffers uploaded successfully (GPU)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Opening input device [/dev/input/event1] (mouse gamepad keyboard )
INFO: Opening input device [/dev/input/event0] (mouse )
WARNING: Could not change keyboard mode (SSH keyboard?)
WARNING: Gamepad device could not be opened, no gamepad available
Killed
```

**Comment by raysan5** [comment]
@RowV thanks for reporting. Actually, that keyboard behaviour should be changed to avoid that kind of system blocking issues. I'll check it out.

Also, if you're checking the examples on Raspberry Pi, it would be very useful to get a list with all the examples not working properly. No worries about the issue formating, just getting the list with a one-line comment would be super-useful.

**Comment by RowV** [comment]
@raysan5 I will create list in two days.

**Comment by raysan5** [comment]
@RowV nice! thank you very much!

**Comment by wbrbr** [comment]
This example was buggy (see #848 ) so this may not be because of the RPi. @RowV could you try again when #849 is merged ?

**Comment by raysan5** [comment]
@RowV I changed keyboard input behaviour on commit https://github.com/raysan5/raylib/commit/b1806f660070ec5b54fe20bd266f8b33b3c3bc13, it should prevent system from blocking if program is does not exit properly.

**Comment by RowV** [comment]
@raysan5 Now the render window is rendering properly, but when I hit SPACE nothing happens in render but space character gets typed in terminal. Also now I cannot exit program properly when hitting ESC button, I have to type CTRL+C to terminate. This thing happens on both SSH keyboard as well as USB keyboard connected to RPi3

**Comment by RowV** [comment]
> @raysan5 Now the render window is rendering properly, but when I hit SPACE nothing happens in render but space character gets typed in terminal. Also now I **cannot exit program properly** when hitting ESC button, I have to type CTRL+C to terminate. This thing happens on both SSH keyboard as well as USB keyboard connected to RPi3
Here is the terminal log message:
```
pi@raspberrypi:~/Raylib/examples/models $ ./models_animation 
INFO: Initializing raylib 2.5-dev
INFO: UPSCALING: Required screen size: 800 x 450 -> Display size: 800 x 480
INFO: Display device initialized successfully
INFO: Display size: 800 x 480
INFO: Render size: 800 x 480
INFO: Screen size: 800 x 450
INFO: Viewport offsets: 0, 30
INFO: GPU: Vendor:   Broadcom
INFO: GPU: Renderer: VideoCore IV HW
INFO: GPU: Version:  OpenGL ES 2.0
INFO: GPU: GLSL:     OpenGL ES GLSL ES 1.00
INFO: Number of supported extensions: 13
WARNING: [EXTENSION] VAO extension not found, VAO usage not supported
INFO: [EXTENSION] NPOT textures extension detected, full NPOT textures supported
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: Internal buffers initialized successfully (CPU)
INFO: Internal buffers uploaded successfully (GPU)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Opening input device [/dev/input/event4] (mouse gamepad keyboard )
INFO: Opening input device [/dev/input/event1] (keyboard )
INFO: Opening input device [/dev/input/event0] (mouse )
WARNING: Gamepad device could not be opened, no gamepad available
INFO: [VBOs] Mesh uploaded successfully to VRAM (GPU)
WARNING: [resources/guy/guy.iqm] No materials can be loaded, default to white material
INFO: [resources/guy/guytex.png] Image loaded successfully (1024x1024)
INFO: [TEX ID 3] Texture created successfully (1024x1024 - 1 mipmaps)
WARNING: More than 1 animation in file, only the first one will be loaded
INFO: Target time per frame: 16.667 milliseconds
                                                ^[^[^[^[^[^C

**Comment by raysan5** [comment]
Probably related to #884 and #863. Some changes implemented, please could you try it again?

**Comment by RowV** [comment]
> Probably related to #884 and #863. Some changes implemented, please could you try it again?

It working great both on physical keyboard as well as SSH

**Comment by raysan5** [comment]
@RowV nice! Closing the issue! :)
