### ISSUE TITLE
[examples] raylib 2.5 Raspberry Pi examples review

### ISSUE THREAD

**Issue by RowV** [raysan5/raylib#851]
Here are two lists of raylib/examples having problems on Raspberry Pi 3
### Environment
 * Platform : Raspberry Pi 3B+
 * Operating System : Raspbian GNU/Linux 9 (stretch)
 * OpenGL version : OpenGLES 2.0

**Following is the list of examples with rendering issues:**

|Example Name| Problem Description |
|--|--|
|❗️audio_module_playing| Weird noise at the end when audio file loops back to beginning |
|❗️audio_raw_stream | When frequency is changed the render window has some parts of old sine waves of previous frequencies.<br> Also change the instruction displayed on render window to *"Hold LEFT_BUTTON and drag up and down to change frequency"* | 
|✔core_input_gestures| Only DRAG type of gesture is detected. <br>Confine mouse pointer within gesture test area or show the mouse pointer|
|✔core_loading_thread| Loading stops halfway|
|✔core_storage_values | Fails to load stored data when SPACE key is pressed|
|✔core_vr_simulator| Screen size is fixed to 1080 x 600 <br>`const int screenWidth = 1080;` <br> `const int screenHeight = 600;` <br> If render window size is small then left eye section render is bigger than right one.|
|models_obj_viewer| **alt + mouse_wheel_pressed** not rotating the model <br> **alt + ctrl + mouse_pressed** smooth zoom is not happening|
|models_materials_pbr<br> models_skybox  | Seg fault before render anything, **see [Issue #839](https://github.com/raysan5/raylib/issues/839#issue-444941520)**|
|shaders_postprocessing| Only a part (top part of the castle) of cross hatching is rendered, rest is not rendered. Other post-processing shaders are working fine|
|shaders_texture_drawing<br>shaders_raymarching<br>shaders_palette_switch<br>shaders_julia_set<br>shaders_eratosthenes | Fragment shader requires to be adapted for OpenGL ES 2.0|
|✔textures_bunnymark|Nothing is rendered just white screen , but instruction text is rendered, no errors in terminal logs as well.|

**Following are the list of examples which WORK PROPERLY but some minor changes are required:**

|Example Name| Suggested Edit  |
|--|--|
|✔core_3d_picking | Invisible mouse pointer, makes it difficult to pick a mesh|
|✔core_window_letterbox|Misleading instruction on screen, says *You can resize the window, and see screen scaling* but example only changes the rectangle color when SPACE key is pressed| 
|✔physics_shatter| Invisible mouse pointer, difficult to shatter the shape|
|✔shapes_draw_circle_sector<br>✔shapes_draw_rectangle_rounded <br>✔shapes_draw_ring <br> ✔shapes_lines_bezier <br> ✔shapes_rectangle_scaling | Invisible mouse pointer, difficult to change gui sliders|
|✔text_bmfont_ttf | Change onscreen instruction "Press SPACE to use TTF generated font" to "**Hold** SPACE to use TTF generated font"|
|✔text_font_sdf | Change onscreen instruction "PRESS SPACE to USE SDF FONT VERSION!" to "**HOLD** SPACE to USE SDF FONT VERSION!"|
|✔text_unicode | Invisible mouse pointer, make it visible for better navigation|

**Comment by raysan5** [comment]
@RowV Great report! Thank you very much for taking the effort to test all the examples! 

I understand you're testing them on native mode, right? Mouse not drawing is because of that, I think I can find a solution... Mouse wheel is not supported on native mode...

About shaders issues, most of them are not adapted for GLSL100, it requires some work.

**Comment by raysan5** [comment]
Adding reference to related issue: https://github.com/raysan5/raylib/issues/847

`models` and `shader` issues are common in Web and Raspberry Pi.

**Comment by RowV** [comment]
> @RowV Great report! Thank you very much for taking the effort to test all the examples!

Thank you.

> I understand you're testing them on native mode, right? 

Yes, native mode only.

>Mouse not drawing is because of that, I think I can find a solution... Mouse wheel is not supported on native mode...

By mouse wheel you meant middle click? Because mouse wheel scroll works.

> About shaders issues, most of them are not adapted for GLSL100, it requires some work.

Okay.

**Comment by raysan5** [comment]
Some comments tweaks on commit https://github.com/raysan5/raylib/commit/434e460c18e7e47e154aff42196a3456aacd9e1c.

I'll update main post examples with ✔ as long I keep reviewing the examples...

**Comment by RowV** [comment]
@raysan5 : You forgot to edit instruction text in `audio_raw_stream` see the first table. Everything else is good.

**Comment by raysan5** [comment]
Some fixes implemted in commit https://github.com/raysan5/raylib/commit/3db13edd898adcd41aa0768e2e707256687a90ac.

Note main issue description has been edited properly.

**Comment by raysan5** [comment]
- `core_vr_simulator` shader reviewed in commit https://github.com/raysan5/raylib/commit/20257f3e49a25430912330caa98e06b81b4276b3.
 - `models_obj_viewer` inputs work when not using `SUPPORT_SSH_KEYBOARD_RPI`
 - `audio_raw_stream` could be confusing, that example requires review.
 - `audio_module_playing` issue is multiplatform and related how data is send for processing. `raudio` module is being completely reviewed recently.

**Comment by raysan5** [comment]
Just reviewed several shaders on commit https://github.com/raysan5/raylib/commit/3aad221b1edb096e28111f2fd487addc7a4d5789.

Some shaders like `eratosthenes.fs` and `raymarching.fs` are limited by RPI GPU capabilities.

About the pending examples for review:

 - `models_obj_viewer` : Keyboard/Mouse inputs on RPI require some redesign so it's not directly an example issue but a input review.
 - `models_materials_pbr` : PBR support must be completely reviewed for OpenGL ES, current implementation use features not directly available in OpenGL ES.
 - `models_skybox` : Also related current implementation...

I'm closing this issue for now!
