### ISSUE TITLE
[core] Option to keep window running while it minimized

### ISSUE THREAD

**Issue by nxrighthere** [raysan5/raylib#860]
### Issue description

[This](https://github.com/raysan5/raylib/blob/31bcaffd7d11c9b24776facb527e20eb5e0030c6/src/core.c#L751) hardcoded condition prevents running application's logic while the window is minimized. An option should be exposed to make this condition optional.

### Environment

Windows 10.

**Comment by raysan5** [comment]
I'm trying to add a FLAG but it requires some changes... at some point I though using an `unsigned char` for Window flags was more than enough... 😞

**Comment by nxrighthere** [comment]
Well, I would suggest you introduce `RAYLIB_DEPRECATED` constant, slightly change enumerations, structures, and function declarations (adding an appropriate name prefix) and move forward.

By the way `GetMatrixModelview()` isn't a prototype, `void` is missed.

**Comment by raysan5** [comment]
@nxrighthere I'd just change the `unsigned char` by `unsigned int` and never look back.

By the way, did you try commenting `glfwWaitEvents()` line? does it work as expected? I'm just trying it does not seem to work properly... 

Thanks for the `GetMatrixModelview()` just updating it!

**Comment by nxrighthere** [comment]
> By the way, did you try commenting glfwWaitEvents() line? does it work as expected? I'm just trying it does not seem to work properly...

It seems that it works fine for me, what problem you encountered? Maybe I just didn't notice that.

**Comment by raysan5** [comment]
Ok, reviewed, now it seems to work. Implemented in commit https://github.com/raysan5/raylib/commit/dccd61bef9074bea715e8afb29b2043b4f4b66a3.

Please, let me know if it works.

**Comment by nxrighthere** [comment]
Nice, thanks. 👍
