### ISSUE TITLE
Doesnt compile on windows

### ISSUE THREAD

**Issue by rt974** [raysan5/raylib#861]
Windows 10.

Downloaded the 2.5 release, none of the versions work. Bat files have wrong paths pointing to c:/github.

None of the project files compile on visual studio 2017,  Tried using cmake on git version, tried the release version, same.

Bindings looks incomplete and outdated. Well good luck with your project, i'll try again in 10 years.

**Comment by raysan5** [comment]
I'm sorry to read this, I really put a lot of effort trying to make building as easy as possible.

In any case, raylib is an open-source project an improvements are welcome.

**Comment by pipagerardo** [comment]
¡Jodo como se las gastan algunos! Compilada raylib 2.5 Desktop sin problemas en Windows 10 usando msys2 tanto con el compilador Mingw como con Clang modificando el makefile para clang y llvm-ar. También la he compilado directamente usando Code::Blocks creándome mi propio proyecto. Lo único que se me está resistiendo es la compilación en la plataforma UWP, ahí si que me salen errores sobre todo por duplicación de estructuras como rectangle, headers y gaitas varias. Siento no escribir en inglés, soy un auténtico ceporro. Seguiré insistiendo sobre la compilación en UWP pues estoy muy interesado en crear cosillas para XBOX ONE. Un saludo.

**Comment by pipagerardo** [comment]
He bajado he instalado msys2 "http://www.msys2.org/"
Luego se ejecuta la consola "msys2.exe" y se instala lo siguiente:
pacman -Sy pacman	Actualizar el gestor de paquetes
pacman -Syu		        Actualizar todos los paquetes
pacman -Su		        Si necesistas cerrar MSYS2 porque se quede pillado
pacman -S make		Instalar el make para linux

Compilador de 64 bits:
pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-make
pacman -S mingw-w64-x86_64-clang mingw-w64-x86_64-clang-analyzer mingw-w64-x86_64-clang-tools-extra mingw-w64-x86_64-compiler-rt mingw-w64-x86_64-libblocksruntime

Compilador de 32 bits:
pacman -S mingw-w64-i686-gcc mingw-w64-i686-gcc-libs mingw-w64-i686-make 
pacman -S mingw-w64-i686-clang mingw-w64-i686-clang-analyzer mingw-w64-x86_64-clang-tools-extra mingw-w64-x86_64-compiler-rt mingw-w64-x86_64-libblocksruntime

Ahora para Compilar Raylib solo hay que descomprimir raylib en la carpeta home correspondiente.
Ejecutamos  "mingw32.exe" o "mingw64.exe" según queramos 32 o 64 bits

cd /home
cd raylib/src
make

Para usar clang hay que modificar el makefile:
Esto:
	# CC = gcc
	# AR = ar
Por esto:
	CC = clang
	AR = llvm-ar

Listo...

**Comment by jubalh** [comment]
Another way to do this is to install Linux subsystem for Windows. Install openSUSE. `zypper in raylib` and use it.

**Comment by raysan5** [comment]
@pipagerardo @jubalh Thanks for anwering.

I can understand the frustration when something doesn't work as expected at a first try... unfortunately in the software world that's too common... feel that frustration too many times... I created raylib and tried hard to make it simple and easy-to-use to avoid that... but I can not control all the use cases... 

Just closing this issue.

**Comment by hbiblia** [comment]
@rt974 solo instale **raylib_installer_v2.5.exe** y llame a note++ desde el menú de inicio

**Comment by AregevDev** [comment]
Raylib compiles well for me...
I am on Visual Studio 2019, all I do is clone the repo, checkout on the 0.2.5 tag

Then I run in powershell
`mkdir build`
`cd build`
`cmake ..`
`cmake --build . --target Release`

And done, now you can go to build/Release and you can find your binaries there
