### ISSUE TITLE
[core] Keyboard input system not working properly

### ISSUE THREAD

**Issue by DarkElvenAngel** [raysan5/raylib#863]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

The input system is not working all key presses are echoed to the terminal the only way to terminate the program is with Ctrl+C 

My older build is not affected by this error.

### Environment

Raspberry Pi Native mode

### Issue Screenshot

![out](https://user-images.githubusercontent.com/28216652/58891392-67802080-86ba-11e9-8705-a848adb69e2f.png)

### Code Example

This was a fresh rebuild of the main branch version 2.5 all examples are affected.

**Comment by raysan5** [comment]
Sorry, it was caused by commenting `stdin` keyboard reading... Please, could you try uncommenting `#define SUPPORT_SSH_KEYBOARD_RPI` on `config.h`?

**Comment by raysan5** [comment]
While investigating why this happens, just reactivated `stdin` redirect code: https://github.com/raysan5/raylib/commit/6f9c176d939c8035b0f14836de80e916826c0325

**Comment by DarkElvenAngel** [comment]
That's working now, the output to the console is the same but now we have successfully uploading output and the examples exit cleanly.

What does this flag do?

**Comment by raysan5** [comment]
@DarkElvenAngel Right now two keyboard input systems coexist in the Raspberry Pi: one reconfigures standard system input to read keycodes (that could be dangerous), the second one just reads pre-processed keyboard inputs using `evdev` system library on a second thread. First one supports SSH inputs but it's dangerous, second ones requires super-user rights and it was added lately.

I should remove first mechanism but I just disabled with a flag for the moment, second mechanism should be the standard.

**Comment by DarkElvenAngel** [comment]
I was running the example from the root user both before and after enabling that flag.  If that helps with the investigation of this issue.

@raysan5 so using the library as I have it compiled now is not recommended/dangerous (potentially)?

**Comment by raysan5** [comment]
@DarkElvenAngel It has been this way since the beginning, second mechanism was added some weeks ago.

It's potentially dangerous in the sense that it locks the device if programs does not exit properly. Also, if you have another program running in background it could make it crash when running raylib example (due to the stdin reconfiguration). For those reasons, second mechanism was added...

**Comment by DarkElvenAngel** [comment]
So I have been digging about in this issue and I can confirm that the keys are being read using the debug tracelog. However there go to a buffer but you don't seem to access it from anywhere.

Also I don't see any code telling the terminal to suppress signals or echoing.

I'm seeing that if you dump the values directly in to 
currentKeyState [keycode] =event.value;
if (event.value == 1) lastKeyPressed = keycode;

This enables basic keyboard to work but not [Esc] to close the program or any other special Keys to function.  I had a pull request some time ago that use the raw input driver over this evdev driver I'm attempting to merge it back in and see if I can restore full functionality.

**Comment by raysan5** [comment]
@DarkElvenAngel Thnak you very much for looking into this issue.

The idea is replacing previous input modes by the new `evdev` option (but leaving previous method available with a flag). `evdev` should take care of keyboard, mouse and gamepad.

**Comment by DarkElvenAngel** [comment]
Evdev is working perfectly the problem lies in the buffer it uses for key events.  There is no code that reads from this buffer. 

Bypassing the buffer is working.

I've also added an initializer that will surpress echoing keys to the terminal and block Ctrl C and Ctrl Z signals.

My changes restore operation but don't fix buffer issue only bypass it.  For my use case as Gui frontend mostly controlled by CEC inputs this isn't an issue.

I can try to post a pull request maybe someone else can sort out the buffer. I simply don't have much time to work on projects sadly.

**Comment by raysan5** [comment]
@DarkElvenAngel After your patch, could we close this issue?

**Comment by DarkElvenAngel** [comment]
@raysan5 Yes I've closed it I believe that the issue is resolved.
