### ISSUE TITLE
[core] Ability to switch from 2D to 3D Camera and vice versa

### ISSUE THREAD

**Issue by nicholassimon** [raysan5/raylib#868]
Not sure if it is possible, cannot seem to work it out, is there a way to switch from a 2D Camera to a 3D Camera without closing the window?

When I try and implement a 3D Camera in a 2D Window absolutely nothing happens, just wondering if it is possible at all and how?
Thanks, otherwise Raylib is amazing, keep up the good work, have been using it with Go and am very impressed

**Comment by raysan5** [comment]
Hi @nicholassimon! You can check `models_orthographic_projection` example, that example toggles between a 3D perspective projection and a 2D orthographic projection, not sure if that's what you are looking for.

**Comment by nicholassimon** [comment]
Thanks for getting back to me, will take a look this evening and let you know. Appreciate it and great work.

**Comment by nicholassimon** [comment]
Hi again, took a look at that but is not what I mean. I am messing around with a game design and want to be able to switch from Camera2D to Camera3D and back again. So have a 2D game map and when there is a fight between the player and the enemy then switch to a 3D Camera for the fight. Once the fight is over then switch back to the Camera 2D. Would I need to close the window each time or is it possible to end the Camera2D start the Camera3D in the same window? (not sure if that makes sense)

**Comment by raysan5** [comment]
Ok, I understand and that can be done with no problem, it depends on user code and how you manage game scenes, raylib is able to draw 2D and 3D together or separately.

Check `raylib/templates/simple_game`, when drawing the current screen (LOGO, TITLE, MENU, GAMEPLAY, BATTLE...) just draw 2D or 3D accordingly.

I'm closing this issue.
