### ISSUE TITLE
[examples] Add simple lighting shader

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#877]
The only lighting example (models_material_pbr) is by its very nature quite complex, it would be very useful to include a very simple lighting example, showing just a single point light source with ambient lighting.  I'd suggest animating the light source so it orbits around 2 or three spinning meshes.

This should give a good base for someone wanting to experiment with adding their own simple shaders...

**Comment by raysan5** [comment]
Contrbutions are welcome! :D

**Comment by chriscamacho** [comment]
I may end up doing just that if I can figure out whats going on with the pbr example...

**Comment by chriscamacho** [comment]
I have something working, except the way ambient lighting is working looks wrong, I'd need a tiny bit of help to finish it....

**Comment by raysan5** [comment]
Thanks @chriscamacho! Example added in commit https://github.com/raysan5/raylib/commit/81d8302d538d117277e1cfa3aa088d4d51937533.

Despite it works great, `rlighting` module does not convince me, I think it requires some review.
