### ISSUE TITLE
[rlgl] Shader behaves strangely on a ClockworkPi GameShell

### ISSUE THREAD

**Issue by ArcOfDream** [raysan5/raylib#878]
### Issue description

 When testing the palette switch example with the version 120 shaders (This device does not support GL3.3), there seem to be only two colors displayed. Additionally, those drawn elements pop on top of everything else.

So far this works well with the GL 2.1 API set (sans this issue), as I haven't had luck with making it compile under the ES2 API.

### Environment

*Platform* - ClockworkPi OS (Debian 9 base)
*OpenGL* - Used 2.1 profile here, which seemed to have worked fine for most of other demos until shaders were tested.
*GPU* - This runs on an Allwinner R16 chip, which has a Mali 400 MP2 GPU that supports GLES 2.0 

### Issue Screenshot

![IMG_20190610_125835](https://user-images.githubusercontent.com/8292849/59191652-69e1ef00-8b80-11e9-9e57-34b2734c11ff.jpg)
(out of 8, only two colors are visible)

### Code Example

Palette Switch example, modified to use glsl120 shaders. By default they don't compile correctly, which can be fixed by correcting the `texture` call in `palette_switch.fs` into `texture2D`.

**Comment by raysan5** [comment]
@ArcOfDream thanks for reporting! I didn't know about ClockworkPi device, looks great! 😄

palette switch shader neither works on glsl 100, I have to review it!

**Comment by raysan5** [comment]
I'm closing this issue because that shader should already be reviewed per #851.
