### ISSUE TITLE
[build] symbols stripped even in debug mode for examples

### ISSUE THREAD

**Issue by DanRosenfeld** [raysan5/raylib#880]
When performing a debug build of the examples, symbols are stripped. I've only confirmed this on Raspberry Pi (Raspbian).

Specifically, I use:

` make PLATFORM=PLATFORM_RPI BUILD_MODE=DEBUG`

but the resulting executables do not have symbols, as confirmed by:

` nm -a -C <exe>`

The makefile include the -s option in CFLAGS. Removing this fixes the problem. Presumably this flag should only be used for RELEASE builds.

### Environment
Raspbian Stretch Lite, 4.14 kernel
pulled latest from master before build

**Comment by raysan5** [comment]
Ouch! Good catch @DanRosenfeld! I'll review it!

**Comment by raysan5** [comment]
Reviewed in commit https://github.com/raysan5/raylib/commit/55380f84895327a7238e85292ae1a6a453309413.
