### ISSUE TITLE
[core] Note All Functions Available using Golang / GO 

### ISSUE THREAD

**Issue by nicholassimon** [raysan5/raylib#881]
Hi again, just wondering I am new to using Raylib (only a month or two) and am very impressed. However I have noticed that not all features are available using Go (Golang) I am using this https://github.com/gen2brain/raylib-go

However I cannot for instance use DrawTextRec as it is not available it seems in the Go bindings. How does that work? Will they be updated? Was just wondering, though can understand it may be someone else's work.
 _void DrawTextRec(Font font, const char *text, Rectangle rec, float fontSize, float spacing, bool wordWrap, Color tint);_ 

Otherwise really enjoying learning it, it is very fun to use.

![golang](https://user-images.githubusercontent.com/33998213/59271738-a67f1a80-8c54-11e9-9e1e-5c1c0b4975c3.png)

**Comment by raysan5** [comment]
@nicholassimon Sorry, I'm not the creator or maintainer of raylib-go, please report to https://github.com/gen2brain/raylib-go
