### ISSUE TITLE
Compiled Files being listed as trojan

### ISSUE THREAD

**Issue by 28202** [raysan5/raylib#882]
After compilation of a any raylib file if scanned by an antivirus it returns Trojan.

OS:
Windows
Anti Virus:
Malware bytes
Windows Defender

Raylib version 2.5

For virus total results:
https://imgur.com/a/3l9gsE4

Any code appears to return issue

**Comment by raysan5** [comment]
Most probably a false positive. In any case, it's an open-source project, if you find malicius code, please report.
