### ISSUE TITLE
Let CC in src/Makefile be optional

### ISSUE THREAD

**Issue by ryobg** [raysan5/raylib#883]
I think the CC flag in the Makefile should be assigned to GCC only if not defined:
https://github.com/raysan5/raylib/blob/baf7d7d19ad8d6bfbfc201169e4ed4f49a9576a6/src/Makefile#L210
i.e. can go as `CC ?= gcc`

I'm cross-compiling with MinGW (under WSL), hence different driver is needed (e.g. `x86_64-w64-mingw32-gcc`) also maybe remove the comment above that it will work with C++, it does not because there are too many errors (involving casts mostly) :P

**Comment by raysan5** [comment]
Done in commit https://github.com/raysan5/raylib/commit/266df463ccfe7fb3b993e69047d0a4d816d78bf8.

**Comment by ryobg** [comment]
Gracias!
