### ISSUE TITLE
[models] `#if defined` is wrong, and when corrected, ignored

### ISSUE THREAD

**Issue by jeangit** [raysan5/raylib#884]
OS : Linux with gcc 8.3 and cmake 3.14.5

In `models.c` , there is a define for testing inclusion or not of IQM format.

At first, it is wrongly defined:

```
#if defined(SUPPORT_FILEFORMAT_GLTF)                                                           
  static Model LoadIQM(const char *fileName);     // Load IQM mesh data                         
#endif
``` 
It should be `#if defined(SUPPORT_FILEFORMAT_IQM)`.

When corrected, this part of code is never compiled.
I've checked with the insertion of `#error never reached!` inside the block. The error is never raised when compiling.

I'm using this command for generating makefile: `cmake -DSHARED=ON -DSTATIC=ON ..`

`SUPPORT_FILEFORMAT_IQM` is ON by default , as we can see in the `CMakeCache.txt`

```
build$ grep -i iqm CMakeCache.txt
//Support loading IQM file format
SUPPORT_FILEFORMAT_IQM:BOOL=ON
```

The `SUPPORT_FILEFORMAT_IQM`is not present in generated Makefile. I cannot help you with that, as i've no idea on how cmake do its stuff.

**Comment by raysan5** [comment]
Corrected issue on commit https://github.com/raysan5/raylib/commit/9609ebf49aad406e77ca3fd599cd3d23836d63ce and commit https://github.com/raysan5/raylib/commit/a43d49ed72f41dddb5e71c26aa981076fe26f1f5. It should work now.
