### ISSUE TITLE
[suggestion] Responsive Containers Possible?

### ISSUE THREAD

**Issue by nicholassimon** [raysan5/raylib#885]
Hi again, not an issue just an idea. I was messing around with RSS feeds and trying to display the text (which can be varying lengths) in textboxes using Raylib.

However this is quite difficult as there does not appear to be any kind of responsive container, ie. a textbox which will change in size dependent on the length of text so that it is not cut off. In CSS this is done with sizes in % as opposed to pixels as well as properties like justify text.

The Raylib Example TEXT > RECTANGLE BOUNDS is basically what I mean, if something was like this was created a Raylib function it would be great. For example if you are getting unknown text length from RSS you then use the function to create a responsive text box which will automatically adjust to whatever length the text is.

Just an idea

**Comment by raysan5** [comment]
As per mi understanding, what you ask for is `DrawTextRec()` that was implemented in raylib 2.5.

Closing issue.
