### ISSUE TITLE
[raygui] Information text box

### ISSUE THREAD

**Issue by nicholassimon** [raysan5/raylib#886]
Another quick question is there a function for an informational text box in RayGui, I could not find one. Not a label, though let's say I wanted to make a window pop up with a paragraph of text, is this possible?

There might already be this feature, though am not sure, if you take a look at the image.
![Untitled 1](https://user-images.githubusercontent.com/33998213/59346066-bf013a80-8d11-11e9-80c1-f83a7d9f24c7.png)

**Comment by raysan5** [comment]
Yes, you can use `GuiMessageBox()`.
