### ISSUE TITLE
[models] GetCollision* doesn't signal no collision

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#887]
It is quite possible that a ray collision could return 0,0,0 (if you very carefully pointed the ray!) this means there is no actual way to tell if the ray completely misses the target...

My initial thought was a Vector3 of nan could be returned but that might break existing code using GetCollision (possibly?)

Knowing if a ray completely misses is definitely useful.

**Comment by raysan5** [comment]
`GetCollisionRay*()` returns `RayHitInfo.hit` boolean to identify is there was a collision.
