### ISSUE TITLE
[core] OpenGL ES extensions recorded incorrectly

### ISSUE THREAD

**Issue by DanRosenfeld** [raysan5/raylib#888]
### Issue description

The GL_OES_compressed_ETC1_RGB8_texture extension is not being reported by raylib on the Raspberry Pi, even though the pi's OpenGL ES implementation supports it.

I can see that glGetString(GL_EXTENSIONS)  [here in rlgl.h](https://github.com/raysan5/raylib/blob/498c172d8e8f35def505045970a6adf50730c392/src/rlgl.h#L1524) is returning a string that includes "GL_OES_compressed_ETC1_RGB8_texture". 

The problem seems to be that the dup string, from which the extension string is tokenized, is [freed ](https://github.com/raysan5/raylib/blob/498c172d8e8f35def505045970a6adf50730c392/src/rlgl.h#L1544) while elements of extList still have pointers into the now-deallocated string.

The free() call seems to mark the beginning of the freed memory, and that marker garbles the start of the extension string, causing the first element ("GL_OES_compressed_ETC1_RGB8_texture", as it turns out) to be missed. It's just luck that the rest the string is preserved for as long as needed by the parsing code.

I've confirmed that commented out the RL_FREE call "fixes" this problem, but obviously this isn't a solution. I didn't immediately see a trivial/not-ugly fix.

### Environment
Raspbian Stretch Lite, 4.14 kernel, full Open GL *not* enabled.

**Comment by raysan5** [comment]
Ouch! Good catch! Yes you're right! No worries, I can review that part of the code!

**Comment by DanRosenfeld** [comment]
Terrific--thanks!

**Comment by raysan5** [comment]
@DanRosenfeld Code reviewed on commit https://github.com/raysan5/raylib/commit/a386cedae6ddb1bc844ee3eea80a61066ba4105d.

Please, let me know if it works, I haven't tested it on the RPI.

**Comment by raysan5** [comment]
Closing this issue, please reopen if problem persist.

**Comment by raysan5** [comment]
Reviewed again in commit https://github.com/raysan5/raylib/commit/a727f5768f6e588d45e47dd26da9af82597ba1d3.
