### ISSUE TITLE
[core] segfault at CloseWindow

### ISSUE THREAD

**Issue by stpaul** [raysan5/raylib#889]
### Issue description

I found an issue in pthread_join / core.c which leads to segfault when I close the window.
Call pthread_join after checking eventWorkers[i].threadId > 0 and gamepadThreadId could avoid the issue.
Normally, the pthread_join returns just error but I got segfault... :(

// ----- Core.c
```
for (int i = 0; i < sizeof(eventWorkers)/sizeof(InputEventWorker); ++i)
    {
        if (eventWorkers[i].threadId == 0)
        {
            pthread_join(eventWorkers[i].threadId, NULL);
        }
    }
    pthread_join(gamepadThreadId, NULL);
```
 
### Environment

Raspberry PI 3. Linux kernel 4.9.79

**Comment by raysan5** [comment]
Hey @stpaul! Thanks for reporting! Could you send a Pull Request with the fix?

**Comment by stpaul** [comment]
Hi @raysan5 ,
I'm sorry that I could not send a pull request because the network limitation in this Country where I live.
How can I do for the others?
Thanks.

**Comment by raysan5** [comment]
Ok @stpaul, no worries. 

Please, could you share the correct code to replace? Thanks!

**Comment by stpaul** [comment]
Hi @raysan5 ,

Sure, and thank you again for your great work... :)

```
#if defined(PLATFORM_RPI)
    // Wait for mouse and gamepad threads to finish before closing
    // NOTE: Those threads should already have finished at this point
    // because they are controlled by windowShouldClose variable

    windowShouldClose = true;   // Added to force threads to exit when the close window is called

    for (int i = 0; i < sizeof(eventWorkers)/sizeof(InputEventWorker); ++i)
    {
        if (eventWorkers[i].threadId)
        {
            pthread_join(eventWorkers[i].threadId, NULL);
        }
    }

    if(gamepadThreadId)
        pthread_join(gamepadThreadId, NULL);
#endif
```

**Comment by raysan5** [comment]
Thanks @stpaul! Correction implemented in commit https://github.com/raysan5/raylib/commit/721d18589fc0f6caf1785a682b3c10adbfaf7402. :)

PLease, let me know if it works!

**Comment by stpaul** [comment]
It works 👍 
Thank you so much... 😄
