### ISSUE TITLE
[examples] Some new examples proposed

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#890]
Here it is a small list of new examples that I think could be interesting for raylib. If anyone wants to work on any of them, please, make sure to follow [examples_template](https://github.com/raysan5/raylib/blob/master/examples/examples_template.c). Please, try to make examples a bit appealing for the user! :)

 - [x] `core_scissor_test` : Functionality was added in `raylib 2.5` but no usage example provided yet.
 - [ ] `textures_cubemap` : Functionality was added in `raylib 2.5` but no usage example provided yet. [LoadTextureCubemap()](https://github.com/raysan5/raylib/blob/master/src/textures.c#L1192) processes an input image (multiple layouts supported)  and returns a cubemap texture... some additional function could be needed to draw the `TextureCubemap`...
 - [x]  `textures_mouse_painting` : Canvas painting demo with mouse, for example LMB to paint and RMB to erase, with some basic color selection options.
 - [x] `shaders_basic_lighting` : Basic phong lighting samples, this one is almost ready to be added! (https://github.com/raysan5/raylib/commit/81d8302d538d117277e1cfa3aa088d4d51937533)
 - [x] `shaders_fog_effect` : Basic fog (configurable?) using a shader, it can be combined with a heightmap for usage (https://github.com/raysan5/raylib/commit/4b79f63d07ca81c180ce9d021b2d5fa6cb6af401).

Alternatively, there are several examples that require some review, view #847 and #851.

**Comment by chriscamacho** [comment]
scissor mode would be more useful if the view port could be changed too, however this impacts functions like GetMouseRay which currently assume a fullscreen viewport...

**Comment by raysan5** [comment]
@ChrisDill reviewed your examples on commit https://github.com/raysan5/raylib/commit/602d2a65dd628ea75801c79bfdf960b081696e34. Take a look! ;)

**Comment by chriscamacho** [comment]
gaaah if statements without braces.... @raysan5 they hurt my eyes :-p

**Comment by ChrisDill** [comment]
@raysan5 Thanks! The changes look really good! :)

**Comment by raysan5** [comment]
Closing this issue for now.
