### ISSUE TITLE
[shapes] DrawPolyEx / DrawPolyExLines missing from header but present in cheatsheet

### ISSUE THREAD

**Issue by arvyy** [raysan5/raylib#894]
Latest version 2.5 -- the functions seem missing in header (control+f https://github.com/raysan5/raylib/blob/master/src/raylib.h), but present in the cheatsheet (https://www.raylib.com/cheatsheet/cheatsheet.html)

**Comment by raysan5** [comment]
Those functions were a bit confusing and they were renamed to `DrawTriangleFan()` and `DrawLineStrip()`. It was a last-minute change...

I updated the web cheatsheet.
