### ISSUE TITLE
[build]  Cmake with Draylib_USE_STATIC_LIBS=ON is looking for the wrong static file

### ISSUE THREAD

**Issue by I3uckwheat** [raysan5/raylib#899]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When attempting to build a raylib project installed with `cmake` using `cmake -Draylib_USE_STATIC_LIBS=ON ..` from a build directory, raylib's build script fails to find the proper `libraylib` file, It is looking for `libraylib_static.a` but `libraylib.a` is what the file is called. 

```
CMake Error at /usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find raylib (missing: raylib_LIBRARY) (Required is at least
  version "2.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/lib/cmake/raylib/raylib-config.cmake:47 (find_package_handle_standard_args)
  CMakeLists.txt:1 (find_package)
```

This can be fixed by symbolically linking `libraylib.a` to `libraylib_static.a`

### Environment

Xubuntu 18.04 LTS on a fresh install of raylib

### Issue Screenshot

![image](https://user-images.githubusercontent.com/4411701/60406284-b070ab00-9b7a-11e9-9461-7b2059fc75d4.png)
![image](https://user-images.githubusercontent.com/4411701/60406313-d0a06a00-9b7a-11e9-9bc5-afa85979f10d.png)

### Reproduction

* Follow these directions here on this page
![image](https://user-images.githubusercontent.com/4411701/60406380-1f4e0400-9b7b-11e9-9561-2ac2b370d506.png)
https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux

* Create a new directory in your home directory
* Copy a raylib example to a file in the directory you just created
* create a new CMakeLists.txt file with the following contents

```cmake
find_package(raylib 2.0 REQUIRED)

add_executable(hello hello.cpp)
target_link_libraries(hello raylib -lGLU -lrt -lm -ldl -lX11 -lpthread -lxcb -lXau -lXdmcp)
```

* run `mkdir build && cd build`
* run `cmake -Draylib_USE_STATIC_LIBS=ON ..`

**Comment by I3uckwheat** [comment]
To anybody looking for a fix:

`sudo ln -s /usr/local/lib/libraylib.a /usr/local/lib/libraylib_static.a`

**Comment by raysan5** [comment]
@a3f could you take a look to this issue? Thanks!

**Comment by a3f** [comment]
@I3uckwheat Should be fixed now. I think you need to pass `-static` as well to be guaranteed static raylib linkage. If you want a static raylib, but other dynamic dependencies, there might be further changes needed. PRs are welcome.

**Comment by I3uckwheat** [comment]
@a3f Thank you, everything seems to work too.
