### ISSUE TITLE
[models] DrawModel() does not use current matrix from rlPushMatrix()

### ISSUE THREAD

**Issue by aldrinmartoq** [raysan5/raylib#901]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Hey, thanks for raylib.

I have modified the models_rlgl_solary_system.c example to include 9 planets and the moon, all the rlPushMatrix()/rlPopMatrix() stuff worked pretty well.

Then I created a new version that uses a sphere.OBJ Model + textures, but DrawModel() does not support the current matrix from rlPushMatrix(). Can we improve DrawModel() so it support rlPushMatrix?

### Environment

Latest macOS (Mojave 10.14.5) on a Macbook retina, tested on current raylib master branche and raylib-2.5.0 from homebrew.

### Issue Screenshot

Working version, uses DrawSphere from example:
<img width="1136" alt="2019-06-30 01 22 33 pm" src="https://user-images.githubusercontent.com/388475/60410256-634e0280-9b95-11e9-8973-4cac7a8d708a.png">

NOT working version, uses DrawModel:
<img width="1092" alt="2019-06-30 01 25 45 pm" src="https://user-images.githubusercontent.com/388475/60410258-6ba63d80-9b95-11e9-83df-0f2375535222.png">

### Code Example

Please check PR #900, the files are:

https://github.com/aldrinmartoq/raylib/blob/solar-system-examples/examples/models/models_solar_system.c
and

https://github.com/aldrinmartoq/raylib/blob/solar-system-examples/examples/models/models_rlgl_full_solar_system.c

Thanks!

**Comment by raysan5** [comment]
I tried to implement it on commit https://github.com/raysan5/raylib/commit/8e870f0edad29400092c6c120d19d44981e99670. No success. :(

Matrices are driving me crazy, spend more than two hours trying to  figure it out. Just check commented line:
```c
for (int i = stackCounter; i > 0; i--) matStackTransform = MatrixMultiply(stack[i], matStackTransform);
```
If uncommenting, it partially works but then all planets move to Earth position... any expert on matrices in the room? Probably I'm missing something...

**Comment by Ushio** [comment]
@raysan5 
Hi, it rlDrawMesh needs *transformMatrix*

```
Matrix matModelView = MatrixMultiply(transform, MatrixMultiply(transformMatrix, modelview));
```

And I got the following image by models_solar_system.c

![raylib  models  example - solar system 2019-11-12 22 05 28](https://user-images.githubusercontent.com/1667893/68674123-93240280-0598-11ea-9ace-0b4f9ba13b3f.png)

But current glPushMatrix, glPopMatrix, glRotatef...etc has some different behavior from original OpenGL. This fact will create a large visual difference when using GRAPHICS_API_OPENGL_11
For example, the original OpenGL has multiple matrix stack for each state GL_PROJECTION, GL_MODELVIEW, GL_TEXTURE.

I hope that it is a good match for the original OpenGL behavior. 
If one does that rlgl will become quite easy to understand and very useful backend I think.

**Comment by raysan5** [comment]
@Ushio thanks for the solution! 😄

About missing stacks, I just considered MODELVIEW for being the most used one...

**Comment by Ushio** [comment]
Yeah, I thought too. but rlPushMatrix switch the currentMatrix pointer to transformMatrix.
The matrix don't exist in th original OpenGL. I don't think it is a good behavior.

**Comment by raysan5** [comment]
@Ushio yeah, I see... do you have some idea to fix it in an easy way? At least a partial fix...

**Comment by Ushio** [comment]
@raysan5 
I'd like to start thinking about the fix. I guess it is possible without a large fix. But I'm afraid of the side effects. It'd be better to keep working examples, core code and user code etc...

**Comment by raysan5** [comment]
@Ushio for the moment, just implemented your fix in commit https://github.com/raysan5/raylib/commit/97abaff4c5daad57c50822fb15b790a7241c7775.

Thank you very much! :D

**Comment by Ushio** [comment]
@raysan5 Sounds good. Thanks! :)

**Comment by raysan5** [comment]
Issue is solved, closing it.

**Comment by sakurawald** [comment]
> For example, the original OpenGL has multiple matrix stack for each state GL_PROJECTION, GL_MODELVIEW, GL_TEXTURE.

That's true. I spend much more time understanding how the matrix stack works in raylib. If we use separate matrix stacks, it will be much clearer.
