### ISSUE TITLE
[core] GetWorldToScreen() does not support current matrix from rlPushMatrix()

### ISSUE THREAD

**Issue by aldrinmartoq** [raysan5/raylib#902]
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Ok, now I've got two issues with GetWorldToScreen() with my modified example models_rlgl_full_solar_system.c:

A. Maybe related to #901, GetWorldToScreen also doesn't support the current matrix from rlPushMatrix(). This means that we cannot put a label above a planet without replicating rlPushMatrix functionality.
B. When zooming in, all planet labels began to disappear, but suddenly there is a point when GetWorldToScreen show planet labels AGAIN. That point is when the designated point in space is "behind us". In my opinion, that information is incorrect.

### Environment

Latest macOS (Mojave 10.14.5) on a Macbook retina, tested on current raylib master branche and raylib-2.5.0 from homebrew.

### Issue Screenshot

For A., just check that labels do not respect the rlPushMatrix transformation, particularly the "moon" label appears close to the sun instead to earth.
<img width="1092" alt="2019-07-01 12 29 35 am" src="https://user-images.githubusercontent.com/388475/60410653-5500e600-9b97-11e9-8117-107018e8f4a6.png">

To replicate B., just zoom in with the mouse until the labels disappear and then appear again. Use ALT+MOUSE2 to confirm that planet labels appear when the designated point is behind (just look around in 360º).
<img width="1092" alt="2019-07-01 12 30 12 am" src="https://user-images.githubusercontent.com/388475/60410671-6649f280-9b97-11e9-8b06-79a00a56ae52.png">

<img width="1092" alt="2019-07-01 12 30 38 am" src="https://user-images.githubusercontent.com/388475/60410685-75c93b80-9b97-11e9-8447-8532d6bda412.png">

### Code Example

Please check PR #900, particularly:
https://github.com/aldrinmartoq/raylib/blob/solar-system-examples/examples/models/models_rlgl_full_solar_system.c

Thank you very much.

**Comment by raysan5** [comment]
Out of scope for the moment.
