### ISSUE TITLE
[text.] LoadFontEx Latin Character - Urgent!!!

### ISSUE THREAD

**Issue by cf-isys** [raysan5/raylib#905]
### Issue description

I am test the new versión 2.5.0 and the text function not show Latin Character (áéíóúñ). With the versión 1.8 you tell me that use this:

```
#define FONT_TOTAL_CHARS    255
int defaultFontChars[ FONT_TOTAL_CHARS + 1 ];
char msg[ 256 ] = " Ññ Esta terminal está fuera de servicio ";
SpriteFont font = LoadSpriteFontEx( "segoeui.ttf", 32, FONT_TOTAL_CHARS, defaultFontChars );
```
now I replace whit this 

```
#define FONT_TOTAL_CHARS    255
int defaultFontChars[ FONT_TOTAL_CHARS + 1 ];
char msg[ 256 ] = " Ññ Esta terminal está fuera de servicio ";
Font font = LoadFontEx( "segoeui.ttf", 32, &defaultFontChars, FONT_TOTAL_CHARS  );
```

But not work!!!!

![image](https://user-images.githubusercontent.com/9347170/61000671-4f906200-a334-11e9-8825-3ce98f584abc.png)

Can you help me please!

Thank you very much!!!!

**Comment by raysan5** [comment]
@cf-isys yes, that behaviour just changed to support full Unicode charset, just save the .c code file containing that string as UTF8, that should work.

**Comment by raysan5** [comment]
@cf-isys Just reviewed this issue and did some tests, it works ok. Just three things to check:

1. Code file should be saved as UTF-8
2. Make sure your font supports Latin glyphs
3. Use: `LoadFontEx( "segoeui.ttf", 32, 0, FONT_TOTAL_CHARS);`

Note that third parameter is used to provide requested characters list (as codepoints). If you just pass NULL (0), then it generates consecutive characters from 0 to `FONT_TOTAL_CHARS`.

**Comment by cf-isys** [comment]
Dear,

I check the file format and using UTF8 Without BOM work Fine!!!!

Thank you very much!!!

Good Job!!!

Saludos/Regards

[cid:image017.png@01D53757.AC4B34F0]
Carlos A. Fernández

Director, Integrisys S.A.






M
+54.9.261.5136.993
P
+54.11.6009.7700
W
www.integri-sys.com<http://www.integri-sys.com>
A
Pringles 432, C1183AEH, Bs. As., Argentina







[cid:image018.png@01D53757.AC4B34F0]<http://www.tu-id.com/>  [Marketing personal y movil] <http://www.imarketingmovil.com/>   [cid:image020.png@01D53757.AC4B34F0] <https://www.mifare.net/the-nxp-mifare-team-welcomes-integrisys/>
[Resultado de imagen para linkedin logo]<https://www.linkedin.com/company/integrisys-s-a->   [84B1269E] <https://twitter.com/AIntegrisys?lang=es>    [E77CAC5C] <https://www.instagram.com/integrisys/?hl=es-la>    [97783ECA] <https://www.facebook.com/Integrisys-2169753356572514/>



De: Ray <notifications@github.com>
Enviado el: miércoles, 10 de julio de 2019 19:25
Para: raysan5/raylib <raylib@noreply.github.com>
CC: Carlos A. Fernández <carlos.fernandez@integri-sys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [raysan5/raylib] [text.] LoadFontEx Latin Character - Urgent!!! (#905)


@cf-isys<https://github.com/cf-isys> Just reviewed this issue and did some tests, it works ok. Just three things to check:

  1.  Code file should be saved as UTF-8
  2.  Make sure your font supports Latin glyphs
  3.  Use: LoadFontEx( "segoeui.ttf", 32, 0, FONT_TOTAL_CHARS);

Note that third parameter is used to provide requested characters list (as codepoints). If you just pass NULL (0), then it generates consecutive characters from 0 to FONT_TOTAL_CHARS.

**Comment by cf-isys** [comment]
Dear

I have another problem.. I test my application with the new 2.5 lib (before I use 1.8) and I see that the fonts have a offset to down. See the comparation of 2 screen

Why is this?

Thanks


[cid:image001.png@01D53B17.1CD64A30]

Saludos/Regards

[cid:image017.png@01D53B17.1DFC7AB0]
Carlos A. Fernández

Director, Integrisys S.A.






M
+54.9.261.5136.993
P
+54.11.6009.7700
W
www.integri-sys.com<http://www.integri-sys.com>
A
Pringles 432, C1183AEH, Bs. As., Argentina







[cid:image018.png@01D53B17.1DFC7AB0]<http://www.tu-id.com/>  [Marketing personal y movil] <http://www.imarketingmovil.com/>   [cid:image020.png@01D53B17.1DFC7AB0] <https://www.mifare.net/the-nxp-mifare-team-welcomes-integrisys/>
[Resultado de imagen para linkedin logo]<https://www.linkedin.com/company/integrisys-s-a->   [84B1269E] <https://twitter.com/AIntegrisys?lang=es>    [E77CAC5C] <https://www.instagram.com/integrisys/?hl=es-la>    [97783ECA] <https://www.facebook.com/Integrisys-2169753356572514/>



De: Carlos A. Fernández
Enviado el: miércoles, 10 de julio de 2019 19:43
Para: raysan5/raylib <reply@reply.github.com>; raysan5/raylib <raylib@noreply.github.com>
CC: Mention <mention@noreply.github.com>
Asunto: RE: [raysan5/raylib] [text.] LoadFontEx Latin Character - Urgent!!! (#905)

Dear,

I check the file format and using UTF8 Without BOM work Fine!!!!

Thank you very much!!!

Good Job!!!

Saludos/Regards

[cid:image026.png@01D53B17.1CD64A30]
Carlos A. Fernández

Director, Integrisys S.A.






M
+54.9.261.5136.993
P
+54.11.6009.7700
W
www.integri-sys.com<http://www.integri-sys.com>
A
Pringles 432, C1183AEH, Bs. As., Argentina







[cid:image027.png@01D53B17.1CD64A30]<http://www.tu-id.com/> [Marketing personal y movil] <http://www.imarketingmovil.com/>   [cid:image029.png@01D53B17.1CD64A30] <https://www.mifare.net/the-nxp-mifare-team-welcomes-integrisys/>
[Resultado de imagen para linkedin logo]<https://www.linkedin.com/company/integrisys-s-a->   [84B1269E] <https://twitter.com/AIntegrisys?lang=es>    [E77CAC5C] <https://www.instagram.com/integrisys/?hl=es-la>    [97783ECA] <https://www.facebook.com/Integrisys-2169753356572514/>



De: Ray <notifications@github.com<mailto:notifications@github.com>>
Enviado el: miércoles, 10 de julio de 2019 19:25
Para: raysan5/raylib <raylib@noreply.github.com<mailto:raylib@noreply.github.com>>
CC: Carlos A. Fernández <carlos.fernandez@integri-sys.com<mailto:carlos.fernandez@integri-sys.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Asunto: Re: [raysan5/raylib] [text.] LoadFontEx Latin Character - Urgent!!! (#905)


@cf-isys<https://github.com/cf-isys> Just reviewed this issue and did some tests, it works ok. Just three things to check:

  1.  Code file should be saved as UTF-8
  2.  Make sure your font supports Latin glyphs
  3.  Use: LoadFontEx( "segoeui.ttf", 32, 0, FONT_TOTAL_CHARS);

Note that third parameter is used to provide requested characters list (as codepoints). If you just pass NULL (0), then it generates consecutive characters from 0 to FONT_TOTAL_CHARS.

**Comment by raysan5** [comment]
@cf-isys sorry, I can see any images. Please, could you review your message to remove mailing information? It makes it a bit complicate to read and focus.
