### ISSUE TITLE
Remove or replace Contributor Covenant as CoC

### ISSUE THREAD

**Issue by DingumBoingum** [raysan5/raylib#906]
The CC is an _explicitly_ political document, as admitted by its author: https://twitter.com/coralineada/status/1041465346656530432?lang=en
Who has also boasted about driving people from open source projects such as linux: https://twitter.com/CoralineAda/status/1041441155874009093
It is also ambigious and prone to abuse, as seen during the Linux debacle.

I think this is reason enough to remove it or replace it with a  better and less ambiguous CoC, such as the Ruby Community Conduct Guidelines, or GNU Kind Communications Guidelines.

**Comment by DingumBoingum** [comment]
Some suggested CoC's:
https://www.gnu.org/philosophy/kind-communication.html
https://www.ruby-lang.org/en/conduct/
https://kde.org/code-of-conduct/

**Comment by DingumBoingum** [comment]
Articles dissecting the CoC and why it is in general a bad document:
https://medium.com/@infiltrator7n/deconstructing-coraline-ada-ehmke-s-contributor-covenant-and-why-it-s-foolish-801e1564afe4
https://www.allegro.cc/forums/thread/616388

**Comment by raysan5** [comment]
I have checked my **[+220 starred repositories](https://github.com/raysan5?tab=stars)**, all of them are projects that I follow and I respect. Most of them have no `CODE_OF_CONDUCT`.

Actually, **only 8 projects** include a CoC document. Most relevant ones:

 - [GB Studio](https://github.com/chrismaltby/gb-studio) - Uses Contributor Covenant [template 1.4](https://github.com/chrismaltby/gb-studio/blob/develop/CODE_OF_CONDUCT.md)
 - [openFrameworks](https://github.com/openframeworks/openFrameworks) - Uses [custom CoC](https://github.com/openframeworks/openFrameworks/blob/master/CODE_OF_CONDUCT.md)
 - [TIC-80](https://github.com/nesbox/TIC-80) - Uses Contributor Covenant [template 1.4](https://github.com/nesbox/TIC-80/blob/master/CODE_OF_CONDUCT.md)
 - [Aseprite](https://github.com/aseprite/aseprite) - Uses Contributor Covenant [template 1.2.0](https://github.com/aseprite/aseprite/blob/master/CODE_OF_CONDUCT.md)
 - [ScreenToGif](https://github.com/NickeManarin/ScreenToGif) - Uses Contributor Covenant [template 1.4](https://github.com/NickeManarin/ScreenToGif/blob/master/CODE_OF_CONDUCT.md)

As result of this investigation, I decided to remove (maybe temporarily, maybe definitely) the `CODE_OF_CONDUCT` document from raylib repository.

**Comment by raysan5** [comment]
CoC removed on commit https://github.com/raysan5/raylib/commit/24566c0cf3356fcd1af87e7e1a1fb2abbe73fcc4.
