### ISSUE TITLE
[Texture] Texture recycling

### ISSUE THREAD

**Issue by DarkElvenAngel** [raysan5/raylib#907]
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

I'm currently test an application that will display a group of textures as a slideshow.  I've noticed in the trace log that as I'm recycling textures ( ie unloading the old one and loading a new one ) that the texture indexes are incrementing and not being reused.  This will be a problem when I reach MAXINT, the application is meant to run indefinitely.  My concern is if rollover happens it will overwrite other textures not used in the slideshow.

### Environment

The Application is running on RPI Native mode

### Issue Screenshot

Output wise every thing looks okay

### Code Example

```
void LoadSlide(bool Buffer, const char *filename)
 {
 static bool loaded[2] = {0,0};
 if (loaded[Buffer] == 0) printf ("NO UNLOAD NEEDED\n");
 else UnloadTexture (SlideBuffer[Buffer]);
 SlideBuffer[Buffer] = LoadTexture(TextFormat("/%s/%s",ASSET_PATH,filename));
 loaded[Buffer] = 1;
 }
```

**Comment by raysan5** [comment]
@DarkElvenAngel I'm afraid that could be platform dependant, I mean, GL drivers decides how to assign/re-assign texture IDs.

AFAIK, I can't control that.

**Comment by DarkElvenAngel** [comment]
@raysan5 Thanks for that information it's good to know.  I doubt it will be a problem doing the math it will take a very long time to use enough textures to cause a rollover.
