### ISSUE TITLE
[text] DrawTextEx position change from 1.8 to 2.5

### ISSUE THREAD

**Issue by cf-isys** [raysan5/raylib#908]
Hi, 
I am test my application with your new versión 2.5 and I see that the fonts have a offset to down on Y position. Why is this? What change?

**Comment by raysan5** [comment]
@cf-isys Please, could you provide some screenshot with the issue?

**Comment by cf-isys** [comment]
![text](https://user-images.githubusercontent.com/9347170/61236948-aa98cf00-a70f-11e9-8fa8-b68a485b1c6a.png)

**Comment by cf-isys** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/9347170/61237071-f9466900-a70f-11e9-9525-39b2eb10e339.jpg)

**Comment by raysan5** [comment]
That's weird... Please, could you provide this example with the font used?

**Comment by cf-isys** [comment]
Attach the example code. You 2 horizontal lines, yellow and red. In version 1.8 the text in yellow are print in the yellow line. The yellow line is the botton of text. Now not work same that 1.8.

Why?


`
#include "raylib.h"
#include "stdio.h"

#define TEXT_POSITION_LINE_TIME_PIXEL              56  
#define TEXT_POSITION_LINE_DATE_PIXEL              80  
#define TEXT_POSITION_LINE_1_PIXEL                 205 
#define TEXT_POSITION_LINE_2_PIXEL                 275 
#define TEXT_POSITION_LINE_STATUS_PIXEL            370 
#define TEXT_POSITION_LINE_FOOTER_PIXEL            475 


int main()
{
    int screenWidth = 800;
    int screenHeight = 480;
    Vector2 v2FontPosition;


    InitWindow( screenWidth, screenHeight, "raylib [text] example - ttf loading" );
    SetTargetFPS( 60 );

    Font font = LoadFontEx( "segoeui.ttf", 32, 0, 255 );
    GenTextureMipmaps( &font.texture );
    SetTextureFilter( font.texture, FILTER_TRILINEAR );


    BeginDrawing();

    ClearBackground( CLITERAL{ 0, 140, 204, 255 } );

    DrawLine( 0, 20, 800, 20, LIGHTGRAY );
    DrawLine( 0, TEXT_POSITION_LINE_TIME_PIXEL, 800, TEXT_POSITION_LINE_TIME_PIXEL, YELLOW );
    DrawLine( 0, TEXT_POSITION_LINE_DATE_PIXEL, 800, TEXT_POSITION_LINE_DATE_PIXEL, RED );
    //DrawLine( 0, TEXT_POSITION_LINE_1_PIXEL, 800, TEXT_POSITION_LINE_1_PIXEL, LIGHTGRAY );
    //DrawLine( 0, TEXT_POSITION_LINE_2_PIXEL, 800, TEXT_POSITION_LINE_2_PIXEL, LIGHTGRAY );
    //DrawLine( 0, TEXT_POSITION_LINE_STATUS_PIXEL, 800, TEXT_POSITION_LINE_STATUS_PIXEL, LIGHTGRAY );
    //DrawLine( 0, TEXT_POSITION_LINE_FOOTER_PIXEL, 800, TEXT_POSITION_LINE_FOOTER_PIXEL, LIGHTGRAY );
    DrawLine( 780, 0, 780, 480, LIGHTGRAY );
    DrawLine( 20, 0, 20, 480, LIGHTGRAY );


    v2FontPosition.x = 20;
    v2FontPosition.y = TEXT_POSITION_LINE_TIME_PIXEL;
    DrawTextEx( font, "12:04", v2FontPosition, 66, 0, YELLOW );

    v2FontPosition.y = TEXT_POSITION_LINE_DATE_PIXEL;
    DrawTextEx( font, "Lunes 15 de Julio", v2FontPosition, 33, 0, RED );


    EndDrawing();


    while (!WindowShouldClose())
    {


    }


    UnloadFont( font );
    ClearDroppedFiles();
    CloseWindow();


    return 0;
}`

**Comment by cf-isys** [comment]
you can see this example?

**Comment by raysan5** [comment]
I tested it on Windows with latest raylib version from GitHub and it works as expected.

**Comment by cf-isys** [comment]
Can you send me a picture for see and project for my test. Please

Saludos/Regards

[cid:image017.png@01D53BE2.A910DD00]
Carlos A. Fernández

Director, Integrisys S.A.






M
+54.9.261.5136.993
P
+54.11.6009.7700
W
www.integri-sys.com<http://www.integri-sys.com>
A
Pringles 432, C1183AEH, Bs. As., Argentina







[cid:image018.png@01D53BE2.A910DD00]<http://www.tu-id.com/>  [Marketing personal y movil] <http://www.imarketingmovil.com/>   [cid:image020.png@01D53BE2.A910DD00] <https://www.mifare.net/the-nxp-mifare-team-welcomes-integrisys/>
[Resultado de imagen para linkedin logo]<https://www.linkedin.com/company/integrisys-s-a->   [84B1269E] <https://twitter.com/AIntegrisys?lang=es>    [E77CAC5C] <https://www.instagram.com/integrisys/?hl=es-la>    [97783ECA] <https://www.facebook.com/Integrisys-2169753356572514/>



De: Ray <notifications@github.com>
Enviado el: martes, 16 de julio de 2019 14:26
Para: raysan5/raylib <raylib@noreply.github.com>
CC: Carlos A. Fernández <carlos.fernandez@integri-sys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [raysan5/raylib] [text] DrawTextEx position change from 1.8 to 2.5 (#908)


I tested it on Windows with latest raylib version from GitHub and it works as expected.

**Comment by raysan5** [comment]
You can see in the image that font texture is generated properly and every character rectangle is drawn in the right place, I highlighted `L` letter rectangle for comparison. Hour text is moved down due to rectangle scaling, as expected.

![screenshot000](https://user-images.githubusercontent.com/5766837/61318201-cf22a300-a804-11e9-8438-473bf83e604e.png)

Code:
```c
#include "raylib.h"
#include "stdio.h"

#define TEXT_POSITION_LINE_TIME_PIXEL 56
#define TEXT_POSITION_LINE_DATE_PIXEL 80
#define TEXT_POSITION_LINE_1_PIXEL 205
#define TEXT_POSITION_LINE_2_PIXEL 275
#define TEXT_POSITION_LINE_STATUS_PIXEL 370
#define TEXT_POSITION_LINE_FOOTER_PIXEL 475

int main()
{
    int screenWidth = 800;
    int screenHeight = 480;
    //Vector2 v2FontPosition = { 0 };

    InitWindow(screenWidth, screenHeight, "raylib [text] example - ttf loading");
    SetTargetFPS(60);

    Font font = LoadFontEx("segoeui.ttf", 32, 0, 255);
    GenTextureMipmaps(&font.texture);
    SetTextureFilter(font.texture, FILTER_TRILINEAR);

    while (!WindowShouldClose())
    {
        BeginDrawing();

        ClearBackground(CLITERAL{ 0, 140, 204, 255 });

        //DrawLine(0, 20, 800, 20, LIGHTGRAY);
        DrawLine(0, TEXT_POSITION_LINE_TIME_PIXEL, 800, TEXT_POSITION_LINE_TIME_PIXEL, YELLOW);
        DrawLine(0, TEXT_POSITION_LINE_DATE_PIXEL, 800, TEXT_POSITION_LINE_DATE_PIXEL, RED);
        //DrawLine(0, TEXT_POSITION_LINE_1_PIXEL, 800, TEXT_POSITION_LINE_1_PIXEL, LIGHTGRAY);
        //DrawLine(0, TEXT_POSITION_LINE_2_PIXEL, 800, TEXT_POSITION_LINE_2_PIXEL, LIGHTGRAY);
        //DrawLine(0, TEXT_POSITION_LINE_STATUS_PIXEL, 800, TEXT_POSITION_LINE_STATUS_PIXEL, LIGHTGRAY);
        //DrawLine(0, TEXT_POSITION_LINE_FOOTER_PIXEL, 800, TEXT_POSITION_LINE_FOOTER_PIXEL, LIGHTGRAY);
        //DrawLine(780, 0, 780, 480, LIGHTGRAY);
        //DrawLine(20, 0, 20, 480, LIGHTGRAY);

        //v2FontPosition.x = 20;
        //v2FontPosition.y = TEXT_POSITION_LINE_TIME_PIXEL;
        DrawTextEx(font, "12:04", (Vector2){ 20, TEXT_POSITION_LINE_TIME_PIXEL }, 64, 0, YELLOW);

        //v2FontPosition.y = TEXT_POSITION_LINE_DATE_PIXEL;
        DrawTextEx(font, "Lunes 15 de Julio", (Vector2){ 20, TEXT_POSITION_LINE_DATE_PIXEL }, 32, 0, RED);
        
        DrawTexture(font.texture, 240, 150, WHITE);
        for (int i = 0; i < font.charsCount; i++) 
        {
            DrawRectangleLines(240 + font.chars[i].rec.x, 
                               150 + font.chars[i].rec.y - font.chars[i].offsetY, 
                               font.chars[i].rec.width, font.baseSize, (font.chars[i].value == (int)'L')? RED : BLACK);
        }

        EndDrawing();
    }

    UnloadFont(font);
    ClearDroppedFiles();
    CloseWindow();

    return 0;
}
```

**Comment by cf-isys** [comment]
In your picture the hour text is not place over the yellow line, and the same with the date text.

If you compile this example with the 1.8 version the hour is place in the yellow line.

Question:

  1.  When you say in the DrawTextEx that put the text in X = 56, you use the top or bottom of character for printing?
  2.  In your picture, why the c d e character is not align of bottom?

Thanks



Saludos/Regards

[cid:image017.png@01D53BE9.4C12B1D0]
Carlos A. Fernández

Director, Integrisys S.A.






M
+54.9.261.5136.993
P
+54.11.6009.7700
W
www.integri-sys.com<http://www.integri-sys.com>
A
Pringles 432, C1183AEH, Bs. As., Argentina







[cid:image018.png@01D53BE9.4C12B1D0]<http://www.tu-id.com/>  [Marketing personal y movil] <http://www.imarketingmovil.com/>   [cid:image020.png@01D53BE9.4C12B1D0] <https://www.mifare.net/the-nxp-mifare-team-welcomes-integrisys/>
[Resultado de imagen para linkedin logo]<https://www.linkedin.com/company/integrisys-s-a->   [84B1269E] <https://twitter.com/AIntegrisys?lang=es>    [E77CAC5C] <https://www.instagram.com/integrisys/?hl=es-la>    [97783ECA] <https://www.facebook.com/Integrisys-2169753356572514/>



De: Ray <notifications@github.com>
Enviado el: martes, 16 de julio de 2019 15:07
Para: raysan5/raylib <raylib@noreply.github.com>
CC: Carlos A. Fernández <carlos.fernandez@integri-sys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [raysan5/raylib] [text] DrawTextEx position change from 1.8 to 2.5 (#908)


You can see in the image that font texture is generated properly and every character rectangle is drawn in the right place, I highlighted L letter rectangle for comparison. Hour text is moved down due to rectangle scaling, as expected.

[screenshot000]<https://user-images.githubusercontent.com/5766837/61318201-cf22a300-a804-11e9-8438-473bf83e604e.png>

Code:

#include "raylib.h"

#include "stdio.h"



#define TEXT_POSITION_LINE_TIME_PIXEL 56

#define TEXT_POSITION_LINE_DATE_PIXEL 80

#define TEXT_POSITION_LINE_1_PIXEL 205

#define TEXT_POSITION_LINE_2_PIXEL 275

#define TEXT_POSITION_LINE_STATUS_PIXEL 370

#define TEXT_POSITION_LINE_FOOTER_PIXEL 475



int main()

{

    int screenWidth = 800;

    int screenHeight = 480;

    //Vector2 v2FontPosition = { 0 };



    InitWindow(screenWidth, screenHeight, "raylib [text] example - ttf loading");

    SetTargetFPS(60);



    Font font = LoadFontEx("segoeui.ttf", 32, 0, 255);

    GenTextureMipmaps(&font.texture);

    SetTextureFilter(font.texture, FILTER_TRILINEAR);



    while (!WindowShouldClose())

    {

        BeginDrawing();



        ClearBackground(CLITERAL{ 0, 140, 204, 255 });



        //DrawLine(0, 20, 800, 20, LIGHTGRAY);

        DrawLine(0, TEXT_POSITION_LINE_TIME_PIXEL, 800, TEXT_POSITION_LINE_TIME_PIXEL, YELLOW);

        DrawLine(0, TEXT_POSITION_LINE_DATE_PIXEL, 800, TEXT_POSITION_LINE_DATE_PIXEL, RED);

        //DrawLine(0, TEXT_POSITION_LINE_1_PIXEL, 800, TEXT_POSITION_LINE_1_PIXEL, LIGHTGRAY);

        //DrawLine(0, TEXT_POSITION_LINE_2_PIXEL, 800, TEXT_POSITION_LINE_2_PIXEL, LIGHTGRAY);

        //DrawLine(0, TEXT_POSITION_LINE_STATUS_PIXEL, 800, TEXT_POSITION_LINE_STATUS_PIXEL, LIGHTGRAY);

        //DrawLine(0, TEXT_POSITION_LINE_FOOTER_PIXEL, 800, TEXT_POSITION_LINE_FOOTER_PIXEL, LIGHTGRAY);

        //DrawLine(780, 0, 780, 480, LIGHTGRAY);

        //DrawLine(20, 0, 20, 480, LIGHTGRAY);



        //v2FontPosition.x = 20;

        //v2FontPosition.y = TEXT_POSITION_LINE_TIME_PIXEL;

        DrawTextEx(font, "12:04", (Vector2){ 20, TEXT_POSITION_LINE_TIME_PIXEL }, 64, 0, YELLOW);



        //v2FontPosition.y = TEXT_POSITION_LINE_DATE_PIXEL;

        DrawTextEx(font, "Lunes 15 de Julio", (Vector2){ 20, TEXT_POSITION_LINE_DATE_PIXEL }, 32, 0, RED);



        DrawTexture(font.texture, 240, 150, WHITE);

        for (int i = 0; i < font.charsCount; i++)

        {

            DrawRectangleLines(240 + font.chars[i].rec.x,

                               150 + font.chars[i].rec.y - font.chars[i].offsetY,

                               font.chars[i].rec.width, font.baseSize, (font.chars[i].value == (int)'L')? RED : BLACK);

        }



        EndDrawing();

    }



    UnloadFont(font);

    ClearDroppedFiles();

    CloseWindow();



    return 0;

}

**Comment by raysan5** [comment]
Answering your questions:

 > 1.  When you say in the DrawTextEx that put the text in X = 56, you use the top or bottom of character for printing?

Always refers to the top-left corner of the rectangle of the first character.

 > 2.  In your picture, why the c d e character is not align of bottom?

Because generated font texture characters are not aligned to base, an additional offsetY is provided for correct alignment on drawing.

**Comment by cf-isys** [comment]
Ok, thanks!!!

Good Job!!!


Saludos/Regards

[cid:image017.png@01D53BEB.E2D4D510]
Carlos A. Fernández

Director, Integrisys S.A.






M
+54.9.261.5136.993
P
+54.11.6009.7700
W
www.integri-sys.com<http://www.integri-sys.com>
A
Pringles 432, C1183AEH, Bs. As., Argentina







[cid:image018.png@01D53BEB.E2D4D510]<http://www.tu-id.com/>  [Marketing personal y movil] <http://www.imarketingmovil.com/>   [cid:image020.png@01D53BEB.E2D4D510] <https://www.mifare.net/the-nxp-mifare-team-welcomes-integrisys/>
[Resultado de imagen para linkedin logo]<https://www.linkedin.com/company/integrisys-s-a->   [84B1269E] <https://twitter.com/AIntegrisys?lang=es>    [E77CAC5C] <https://www.instagram.com/integrisys/?hl=es-la>    [97783ECA] <https://www.facebook.com/Integrisys-2169753356572514/>



De: Ray <notifications@github.com>
Enviado el: martes, 16 de julio de 2019 15:32
Para: raysan5/raylib <raylib@noreply.github.com>
CC: Carlos A. Fernández <carlos.fernandez@integri-sys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [raysan5/raylib] [text] DrawTextEx position change from 1.8 to 2.5 (#908)


Answering your questions:

  1.  When you say in the DrawTextEx that put the text in X = 56, you use the top or bottom of character for printing?

Always refers to the top-left corner of the rectangle of the first character.

  1.  In your picture, why the c d e character is not align of bottom?

Because generated font texture characters are not aligned to base, an additional offsetY is provided for correct alignment on drawing.
