### ISSUE TITLE
Is it possible to use Dear ImGui library with raylib 2.5?

### ISSUE THREAD

**Issue by eliukblau** [raysan5/raylib#909]
I know raygui exists, but would it be possible to use Dear ImGui in a simple way with raylib 2.5? How could it be achieved?

https://github.com/ocornut/imgui

Thanks @raysan5 for all your work! 👍 
(Saludos de un colega que también habla español :D)

**Comment by raysan5** [comment]
@eliukblau I'm convinced that it's possible but I haven't looked into it...

Just keep in mind that `Dear ImGui` is C++ while raylib is C, so tools developed will be C++.

Mantenme informado si lo pruebas! :)

**Comment by raysan5** [comment]
Closing this issue.

**Comment by osom8979** [comment]
You can use imgui's imgui_impl_opengl3.h example.

However, imgui must be rendered just before ```SwapBuffers_()``` in ```EndDrawing()```.

Sample code is in my repository:
https://github.com/osom8979/tbag/blob/master/libtbag/ray/RayGui.cpp

**Comment by hesa2020** [comment]
> You can use imgui's imgui_impl_opengl3.h example.
> 
> However, imgui must be rendered just before `SwapBuffers_()` in `EndDrawing()`.
> 
> Sample code is in my repository: https://github.com/osom8979/tbag/blob/master/libtbag/ray/RayGui.cpp

For those looking for it, here is the file he was talking about:
https://github.com/osom8979/tbag/blob/7f35d1c4e704ac316fcdde0cf9d4e41bd7e401dc/libtbag/ray/RayGui.cpp
