### ISSUE TITLE
[physac] Redesign physics module (simplify)

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#91]
Physics module requires some redesign. It could be simplified for easier usage.

Proposed solution consist of keeping an internal physic objects pool and just update them all every frame (it also allows to move physics to a separate thread in the future).

Possible struct for PhysicObject:
```c
typedef struct PhysicObject {
    unsigned int id;
    Transform transform;
    Collider collider;
    Rigidbody rigidbody;
    bool enabled;
} PhysicObject;
```

Some posible functions:
```c
void InitPhysics(void);          // Create pointers array to store physic objects
void ClosePhysics(void);         // Unload physic objects
void UpdatePhysics(void);        // Go through physic objects list and update them
PhysicObject *LoadPhysicObject(void);     // Create a new physic object and put into the internal list
```

Usage example:
```c
PhysicObject *player = LoadPhysicObject();
player.transform.position = (Vector2){ 100, 100 };
```

**Comment by victorfisac** [comment]
I'm working on that. The current physics pipeline uses the next steps:

- Apply velocity.
- Update position.
- Check collision -> if true, reset to previous position and previous velocity (before changes).

So a grounded physic object will always be overlapping and fixing its position... But there is an accuracy issue. If the physic object has high velocity and after a frame it has moved 30 pixels and overlaps the ground, it will return back 30 pixels so it will keep floating in the air.

I think a possible solution is call UpdatePhysics() a number of times per frame and divide the velocity increase by its number so it will make little steps and if it collides with ground, it will just return back a couple of pixels and will be grounded so close to the ground collider. **Do you think it is a good practice?** I think Unity uses a similar workflow but improved to changes how many times UpdatePhysics() needs to be called based on the current fps...

**Comment by raysan5** [comment]
The solution to that problem would be calling UpdatePhysics() in a second thread, independently of game update-draw loop and consequently at a higher call-rate. That's the way I think Unity works.

This issue will require some thinking...

**Comment by raysan5** [comment]
Just for tracking:

Physics module update 01: https://github.com/raysan5/raylib/commit/893facdf6d81a430f5291407afac0e70627d0f0d
Physics module update 02: https://github.com/raysan5/raylib/commit/d0e26247f4e4edd4492611dc52cc964bbafefe27

**Comment by raysan5** [comment]
Redesign completed with commit https://github.com/raysan5/raylib/commit/db3dd9d200f0c70538960c61ce43c00bfd4a2182
