### ISSUE TITLE
[models] Grid not rendered with resolution 0, 0

### ISSUE THREAD

**Issue by r00ster91** [raysan5/raylib#912]
- [ ] I tested it on latest raylib version from master branch (I might try that later but that could be a bit difficult for me on Windows)
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

The below code is supposed to render a grid but it doesn't render anything. The screen is just fully white. But when I replace `0, 0` by `1920, 1080` (my screen resolution), it works as expected.

### Environment

Operating System: Microsoft Windows 10
OpenGL® API Version: 4.6
GPU details:
* GPU Vendor:   ATI Technologies Inc.
* GPU Renderer: AMD Radeon(TM) RX Vega 10 Graphics
* GPU Version:  3.3.13558 Core Profile Context 26.20.11015.5009

### Issue Screenshot

It's just a completely white screen.

### Code Example

```c
#include "raylib.h"

int main() {
  SetConfigFlags(FLAG_FULLSCREEN_MODE);

  InitWindow(0, 0, "Title");

  Camera3D camera;
  camera.position = (Vector3){5.0f, 4.0f, 5.0f};
  camera.target = (Vector3){0.0f, 0.0f, 0.0f};
  camera.up = (Vector3){0.0f, 2.0f, 0.0f};
  camera.fovy = 90.0f;
  camera.type = CAMERA_PERSPECTIVE;

  SetTargetFPS(60);

  while (!WindowShouldClose()) {
    BeginDrawing();
      ClearBackground(WHITE);

      BeginMode3D(camera);
        DrawGrid(10, 1.0f);
      EndMode3D();
    EndDrawing();
  }

  CloseWindow();

  return 0;
}
```

**Comment by raysan5** [comment]
@r00ster91 Issue corrected on commit https://github.com/raysan5/raylib/commit/bc3983a3dd48fc72f84ecb19e2f3bc50423c777a.

Please, could you verify? :)

**Comment by r00ster91** [comment]
Yep, that fixed it. Thank you.
