### ISSUE TITLE
[Models] Drawing over 8189 billboards causes weird rendering issue

### ISSUE THREAD

**Issue by DingumBoingum** [raysan5/raylib#913]
### Issue description

Drawing 8190 billboards causes a weird graphics glitch to occur where everything is drawn in a thin line in the upper left corner of the screen.

### Issue Screenshot

![Screenshot at 2019-07-20 23-43-48](https://user-images.githubusercontent.com/52864059/61584496-05d02480-ab49-11e9-8da0-ebcee4c8feb4.png)

**Comment by raysan5** [comment]
Issue corrected on commit https://github.com/raysan5/raylib/commit/4b2f6b2b5f5b3432e41c5e30e985bc716870f892.

**Comment by raysan5** [comment]
Closing this issue. Feel free to reopen it if problem persists.
