### ISSUE TITLE
[build] Can't build on VSCode

### ISSUE THREAD

**Issue by liamsain** [raysan5/raylib#921]
Please, before submitting a new issue verify and check:

 - [ x] I tested it on latest raylib version from master branch
 - [x ] I checked there is no similar issue already reported
 - [ x] My code has no errors or misuse of raylib

### Issue description
Followed all the steps to get Raylib working with VSCode, when I try to build I get the following in the terminal:
> Executing task in folder VSCode: C:/raylib/mingw/bin/mingw32-make.exe RAYLIB_PATH=C:/raylib/raylib <

mingw32-make game
mingw32-make[1]: Entering directory 'c:/Dev/games/VSCode'
gcc -o game main.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces C:/raylib/raylib/raylib.rc.data -Wl,--subsystem,windows
-I. -IC:/raylib/raylib/src -IC:/raylib/raylib/src/external -L. -LC:/raylib/raylib/src -LC:/raylib/raylib/src -lraylib -lopengl32 -lgdi32 -lwinmm -DPLATFORM_DESKTOP
gcc: error: C:/raylib/raylib/raylib.rc.data: No such file or directory
mingw32-make[1]: *** [Makefile:370: game] Error 1
mingw32-make[1]: Leaving directory 'c:/Dev/games/VSCode'
mingw32-make.exe: *** [Makefile:366: all] Error 2
The terminal process command 'C:/raylib/mingw/bin/mingw32-make.exe RAYLIB_PATH=C:/raylib/raylib' failed to launch (exit code: 2)

### Environment
Windows 10
*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*

### Issue Screenshot

*If possible, provide a screenshot that illustrates the issue. Usually an image is better than a thousand words.*

### Code Example

*Provide minimal reproduction code to test the issue. Please, format the code properly and try to keep it as simple as possible, just focusing on the experienced issue.*

**Comment by raysan5** [comment]
@liamsain this issue was already corrected, are you using latest raylib from GitHub master branch (not the installer one)?

**Comment by liamsain** [comment]
Hi. I'm using raylib_installer_2.5.mingw.exe, found in github releases. 
I'll have a go at cloning the repo now

**Comment by liamsain** [comment]
That's working, thankyou
