### ISSUE TITLE
[camera] 3D camera not working correctly (maths)

### ISSUE THREAD

**Issue by Dacode45** [raysan5/raylib#924]
So I have my camera at 0,0,0 pointing to  a unit cube at 0,0,10 and the cube doesn't render on my mac. Ive found weirder versions of this bug, but this is the simplest I can replicate.
https://pastebin.com/FTRGTAQR

**Comment by raysan5** [comment]
Issue is related to camera matrix maths, probably hitting some division by 0...

Using `camera.position = (Vector3){0.001f, 0.0f, 0.0f};`, it works ok.

**Comment by yummydev** [comment]
So how do I fix this without checking that values are non zero every frame?

**Comment by raysan5** [comment]
@yummydev I don't know, that module should be reviewed. Contributors are welcome!

**Comment by Ushio** [comment]
@raysan5 
Hi, I also curious about the issue.
So I create the fix.

https://github.com/raysan5/raylib/pull/1013

**Comment by raysan5** [comment]
@Ushio thank you very much for the fix!
