### ISSUE TITLE
[camera] Implement touch-based camera controls (zoom, pan, rotate)

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#93]
It could be very useful to have touch-based camera controls for platforms like Android or HTML5.

Probably dependant on [gestures] module. Requires some analysis...

**Comment by raysan5** [comment]
Camera system has been redesigned to accomodate this feature... unfortunately, current implementation based on Euler angles (two-planes angles to define camera rotation, XZ-XY) is not the most comfortable to add this feature... camera system should be completely redone using quaternions...

Still, looking how to implement it in current camera system...

**Comment by raysan5** [comment]
Closing this old issue. It's more a specific example implementation, using current [gestures](https://github.com/raysan5/raylib/blob/master/src/gestures.h) system, than a feature to be added to raylib internals.

**Comment by colesnicov** [comment]
> Closing this old issue. It's more a specific example implementation, using current [gestures](https://github.com/raysan5/raylib/blob/master/src/gestures.h) system, than a feature to be added to raylib internals.

Gestures does not work on RPI 2B. Also does not work propperly raygui https://github.com/raysan5/raygui/issues/401

**Comment by colesnicov** [comment]
It is necessary to make the necessary settings according to the https://github.com/raysan5/raylib/wiki/Install-and-configure-Touchscreen-Drivers-(RPi)

**Comment by raysan5** [comment]
@colesnicov Did gestures and raygui itneraction worked properly after the settings?

**Comment by colesnicov** [comment]
Yes. But it has some ailments, I think I noticed something. I will let you know.
