### ISSUE TITLE
[Texture] GetPixelDataSize returns wrong values for compressed textures

### ISSUE THREAD

**Issue by Shndlr** [raysan5/raylib#934]
### Issue description

In `textures.c`, function `GetPixelDataSize` returns values less than the required for textures with small dimensions (such as mipmaps). For DXT1 textures the minimum number that the function should return is 8. For DXT3 and DXT5 the minimum is 16.

**Comment by raysan5** [comment]
Most texture compression formats work on 4x4 pixel blocks, just wondering how `(width < 4) || (height < 4)` is managed, are those small blocks populated with black pixels?

Just reviewed it on commit https://github.com/raysan5/raylib/commit/c629b16ebce5c8e7b2d8e2a3e842b069965bd6be
