### ISSUE TITLE
DrawTriangle requires points to be in specific order

### ISSUE THREAD

**Issue by sh4mbler** [raysan5/raylib#941]
This is not really a bug but more of an observation.
It seems the first three Vector2 arguments for DrawTriangle has to be input in counter clockwise order or nothing will be drawn. So this will draw a blue triangle:
DrawTriangle( (Vector2) { 0, 0 }, (Vector2) { 0, 100 }, (Vector2) { 100, 100 }, BLUE );
But this will not:
DrawTriangle( (Vector2) { 0, 0 }, (Vector2) { 100, 100 }, (Vector2) { 0, 100 }, BLUE );
DrawTriangleFan() behaves in the same way.
Maybe I'm missing some technical reason for this?
It's not something that has to be fixed but maybe it could be noted on the cheatsheet since it took a while to figure out what I was doing wrong?
This is in the latest build.

**Comment by raysan5** [comment]
@sh4mbler yeah, that's it... added comments on the functions to note it, also on raylib header.

Comments added in commit https://github.com/raysan5/raylib/commit/cef1e6e2e2a015d56b3018465f9094887ff94bdd
