### ISSUE TITLE
[audio] Music struct requires being updated inside functions

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#942]
Some weeks ago `raudio` module was completely reviewed and `Music` struct redesigned, it was changed from an opaque pointer to a public struct, like all the other structs available in raylib.

It was long time I wanted to do this change, not only to expose functions parameters or make its bindings easier but also to make it consistent with all the other structures in raylib. Most raylib functions receive data by value, it was a design decision and I try to stuck to it.

Unfortunately, `Music` struct includes `sampleLeft` parameter that requires being updated as long music is being played.

Functions that update `sampleLeft` parameter:
```c
void UpdateMusicStream(Music music);      // Updates buffers for music streaming
void StopMusicStream(Music music);        // Stop music playing
```
Here we have two possible solutions:
1. Require those functions to receive `music`by reference:
```c
void UpdateMusicStream(Music *music);     // Updates buffers for music streaming
void StopMusicStream(Music *music);       // Stop music playing
```
This change will break all code-bases using previous versions of raylib... I use to review functions without worrying much about "small" breaks but in this case I think it really affects simplicity and ease-of-use...

2. Move `sampleLeft` somewhere else.
`Music` struct includes `stream.buffer` pointer that it's actually the audio buffer containing and processing the data to be played, maybe `samplesProcessed` could be moved there... I need to investigate that `AudioBuffer` more in depth...

Feedback and opinions are welcome!

**Comment by chriscamacho** [comment]
Music is highlevel, samples and audio buffers are lower level, so even if samples left is only used when an audio buffer is playing music (as opposed to samples and effects) I think it makes sense to put it in the audio buffer, and it will mean that you don't have to break the API.

Where sampleleft needs to be accessed, will there need to be extra API calls to access this, or will audiobuffer struct become public ?

**Comment by RobLoach** [comment]
One of raylib's benefits is the simplicity of its API. Which option would keep the API simple to use? Bindings can fix/update as needed.

Makes sense to have `Update` use pointers, similar with `UpdateCamera(Camera *camera)`. If `sampleLeft` moved elsewhere, that'd be cool too.

**Comment by a3f** [comment]
I haven't looked, but does user code mess with Music's contents? If not, we could do `typedef struct Music Music[1]`. Maintains source level compatibility, but each use of Music turns into a &Music.

(IMHO, I don't think passing `struct`s by value is something that should be encouraged anyway, but I just wanted to note this as an extra possibility)

**Comment by raysan5** [comment]
@a3f Actually, that was the previous implementation of `Music` (as a pointer), changed it for consistency with all other raylib functions where, despite unpopular, I pass data usually by value.

**Comment by raysan5** [comment]
`Music` struct reviewed on commit https://github.com/raysan5/raylib/commit/fc95ceadf0143ad6c0f720d26bb28a45889f86d1.

Some issue now with looping and it seems there is some inconsistency with frames vs samples.

**Comment by raysan5** [comment]
After some testing it seems it works ok.
