### ISSUE TITLE
[model] address always evaluates to true (warning)

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#943]
```
models.c:3425:59: warning: address of array
      'data->materials[i].pbr_metallic_roughness.base_color_factor' will always
      evaluate to 'true' [-Wpointer-bool-conversion]
            if (data->materials[i].pbr_metallic_roughness.base_color_factor)

```
Not really sure how to handle this to be sure, but it looks like it might not work as intended....

**Comment by Gamerfiend** [comment]
Hmm... kind of a strange warning. The `data` pointer is the gltf data parsed, so it shouldn't actually always be true.. but perhaps it shouldn't be evaluated that way. If that material didn't exist, then would it be "" or null?

**Comment by a3f** [comment]
> Not really sure how to handle this to be sure, but it looks like it might not work as intended....

Remove the condition and run the if clause unconditionally.

> Hmm... kind of a strange warning. The data pointer is the gltf data parsed, so it shouldn't actually always be true..

It's not about `data`, but about the `.base_color_factor` member that's an array and thus always unequal to `NULL`.

**Comment by chriscamacho** [comment]
>   It's not about data, but about the .base_color_factor member that's an array and thus always unequal to NULL.
Which is exactly why I reported this issue this is likely not the intention ...

**Comment by a3f** [comment]
@chriscamacho Can you make a pull request?

**Comment by chriscamacho** [comment]
no, I'm not sure of the intention of the code concerned.

**Comment by Gamerfiend** [comment]
@chriscamacho I'm working with the LoadGLTF function already, so don't worry about it :) It will be awhile before a pull request is out though.. My first goal is to fully support loading materials, since it only loads diffuse/albedo right now.

**Comment by raysan5** [comment]
Just reviewed this detail.
