### ISSUE TITLE
[core] Is it possible to open Android's keyboard?

### ISSUE THREAD

**Issue by xzebra** [raysan5/raylib#948]
I have created a TextField component and I was wondering if I could use it in Android. I've found in the documentation that there is some kind of keyboard events handling, but I can't see anything related to opening it for input.

**Comment by raysan5** [comment]
@xzebra It's possible but I haven't tested it... I found [ANativeActivity_showSoftInput()](https://developer.android.com/ndk/reference/group/native-activity#anativeactivity_showsoftinput) function in the Android NDK documentation.

**Comment by raysan5** [comment]
Another link that can be useful: https://github.com/googlesamples/android-ndk/pull/137, but it uses the JNI interface.

**Comment by raysan5** [comment]
As long as this is not a raylib issue (maybe a future enhacement) and question has been answered, I'm closing the issue.
