### ISSUE TITLE
BeginScissorMode bug?

### ISSUE THREAD

**Issue by hbiblia** [raysan5/raylib#952]
`BeginScissorMode , EndScissorMode`

Saben si existe algún error con BeginScissorMode? El problema que tengo es que cuando cambio el tamaño de la ventana BeginScissorMode queda en el mismo lugar como si nunca hubiese maximizado la ventana.

![image (1)](https://user-images.githubusercontent.com/1939353/63658053-8f40cb00-c775-11e9-85c1-99de95fb3d7c.jpg)

```
    BeginScissorMode(250, 50, GetScreenWidth(), GetScreenHeight()-50);
      ....
    EndScissorMode();
```

Ahora mismo como esto tiene problema estoy utilizando un **RenderTexture2D** que funciona bien.

**Comment by hbiblia** [comment]
```
void BeginScissorMode(int x, int y, int width, int height)
{
    rlglDraw();             // Force drawing elements

    glEnable(GL_SCISSOR_TEST);
    glScissor(x, **framebufferHeight** - (y + height), width, height);
}

Parece que **framebufferHeight** no se esta actualizando

```

```
void BeginScissorMode(int x, int y, int width, int height)
{
    rlglDraw();             // Force drawing elements

    glEnable(GL_SCISSOR_TEST);
    glScissor(x, **GetScreenHeight()** - (y + height), width, height);
}
```
Cuando cambio la variable por **GetScreenHeight** todo funciona bien

**Comment by raysan5** [comment]
Issue reviewed on commit https://github.com/raysan5/raylib/commit/addbd88833ffc9a2bd1fe33a83e683245324abd0. It should be ok now.
