### ISSUE TITLE
[core] Changing display mode at run-time

### ISSUE THREAD

**Issue by MasterZean** [raysan5/raylib#959]
### Issue description

Hello!

I'm trying to fully support the capabilities of the user's monitor: this means displaying all video modes (potentially with raygui) and allowing the user to switch to these.

As a start I only tried switching to full-screen and controlling v-sync at run-time. This is problematic.

#### 1
There is no way to control v-sync? Had to use glfwSwapInterval.

#### 2
Starting with the application in a window, you can switch v-sync with glfwSwapInterval, keys Alt-F1.

Starting the application in fullscreen, v-sync is locked to your initial v-sync setting from SetConfigFlags and glfwSwapInterval has no effect. In the attached code, set "fullscreen" to true and then switching glfwSwapInterval will do nothing.

#### 3

ToggleFullscreen when switching from windowed to full-screen will not respect current screen refresh-rate. Example: 144 Hz monitor, set from Windows to 60/85/120 Hz. Full-screen mode will be randomly 60 or 144Hz, never 85 or 120. Might behave differently if application started in window or full-screen mode.

Current monitor refresh rate should probably be queried when going full-screen and passed in to glfwSetWindowMonitor.

Thee are no issues with window mode because glfwSetWindowMonitor will ignore refresh rate in non full-screen mode

#### 4
ToggleFullscreen when going from window to full-screen and back will kill window position and decorations, even though glfw documentation says:

> glfwSetWindowMonitor 
> When a window transitions from full screen to windowed mode, this function restores any previous window settings such as whether it is decorated, floating, resizable, has size or aspect ratio limits, etc.

#### 5
This is more like personal preference, but SetConfigFlags is a bit awkward and under-powered. Setting and getting all parameters individually, or as a structure would be preferred. And things like ToggleFullscreen should update these parameters and be retrievable though API.

And maybe support for retrieving and setting display modes? core.c already does this but there is no public API.

### Environment

Windows 10, Raylib 2.5, OpenGl 3.3, integrated video card (this is intentional; it is a best practice to test hardware support and performance on the weakest hardware; the issue reproduces perfectly on powerful GPUs).

### Code Example

    #include "raylib.h"

    int main(void)
    {
        // Initialization
        //--------------------------------------------------------------------------------------
        const int screenWidth = 1280;
        const int screenHeight = 720;
        
        bool fullscreen = false;
        bool vsync = false;
        
        int flags = 0;
        if (fullscreen)
            flags |= FLAG_FULLSCREEN_MODE;
        if (vsync)
            flags |= FLAG_VSYNC_HINT;
        
        SetConfigFlags(flags);
        
        InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");

        //SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
        //--------------------------------------------------------------------------------------

        // Main game loop
        while (!WindowShouldClose())    // Detect window close button or ESC key
        {
            // Update
            //----------------------------------------------------------------------------------
            // TODO: Update your variables here
            //----------------------------------------------------------------------------------
            if ((IsKeyDown(KEY_LEFT_ALT) || IsKeyDown(KEY_RIGHT_ALT)) && IsKeyPressed(KEY_ENTER)) {
                fullscreen = !fullscreen;
                ToggleFullscreen();
            }
             if ((IsKeyDown(KEY_LEFT_ALT) || IsKeyDown(KEY_RIGHT_ALT)) && IsKeyPressed(KEY_F1)) {
                vsync = !vsync;
                glfwSwapInterval(vsync ? 1 : 0);
            }
            // Draw
            //----------------------------------------------------------------------------------
            BeginDrawing();

                ClearBackground(RAYWHITE);

                DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);

            EndDrawing();
            //----------------------------------------------------------------------------------
        }

        // De-Initialization
        //--------------------------------------------------------------------------------------
        CloseWindow();        // Close window and OpenGL context
        //--------------------------------------------------------------------------------------

        return 0;
    }

**Comment by MasterZean** [comment]
Potential solution to problem 2:

A. Call glfwSwapInterval before glfwSwapBuffers.

I have no idea why glfwSwapInterval is reset or has no effect, but this worked for me:

    static void SwapBuffers(void)
    {
    #if defined(PLATFORM_DESKTOP) || defined(PLATFORM_WEB)
        if ((configFlags & FLAG_VSYNC_HINT) != lastVsync) {
            lastVsync = configFlags & FLAG_VSYNC_HINT;
            glfwSwapInterval(lastVsync ? 1 : 0);
        }
        glfwSwapBuffers(window);
    #endif

I added the protection against calling glfwSwapInterval every frame because I do not know the performance impact of this.

Using this fix, the user must call SetConfigFlags to toggle vsync on or off.

Which lead nicely into problem 5, a better configuration API? Maybe for 2.6?

B. Build GLFW3 with GLFW_USE_DWM_SWAP_INTERVAL flag, but I need to look more into this. There are potential jitter problems with this? Wouldn't recommend for now.

**Comment by raysan5** [comment]
@MasterZean Thanks for the detailed report!

Proposed solution looks ok to me, you can send a PR.

**Comment by MasterZean** [comment]
I'm on it! Never done a PR before...

On the other hand, I'm testing a fix for issue 3.

**Comment by raysan5** [comment]
@MasterZean No worries, take your time. :)

**Comment by MasterZean** [comment]
A very strange thing happened: my fix no longer works reliably under all combinations. Strange thing is that I have a compiled lib that when linked against works, but no longer have the original sources. I'm not about to decompile the lib...

One thing that works consistently is calling glfwSwapInterval every frame without any logic to prevent multiple calls. Probably this won't have much if any performance impact but would have preferred to call it only when needed.

I also have potential fixes to the other issues, including window decorations.

No PR yet.

Main reason is that I still need a couple of days of testing.

Secondary reason is that Git is not very intuitive for me. It is complaining about detached HEAD and even though I pushed branches, can't see them on my GitHub fork...

**Comment by MasterZean** [comment]
I did something: new PR?

**Comment by raysan5** [comment]
@MasterZean yes, you can send a new PR, I think commit accumulate to already open PR.

**Comment by raysan5** [comment]
Integrated and reviewed PR.
