### ISSUE TITLE
[core] Get window position

### ISSUE THREAD

**Issue by Eduarch42** [raysan5/raylib#961]
Hey!
Raylib is awesome, I just have a quick question.
Is there a way to get the position of the window in the monitor, I see there is one to set the position, but not to what I'm looking for.
Thanks :smiley:

**Comment by raysan5** [comment]
@Eduarch42 Actually, it's not exposed... why do you need it?

**Comment by Eduarch42** [comment]
Thanks for answering, i see that glfw does have a get window position, but it is not exposed in raylib. I think this may be useful for new types of graphical experiments, for example: Im trying to develop an experiment, were if you move the window, the camera moves at the same type. This "feature" could open new possibilities, and it is not a big change. I could help in implement it.

**Comment by raysan5** [comment]
Implemented in commit https://github.com/raysan5/raylib/commit/0a2177b4bc387951e69a2259f3cd78714d18de38.

Please, keep me updated on your progress, your use case sounds quite interesting! :)

**Comment by Eduarch42** [comment]
Thanks a lot, I'll sure keep you updated!
