### ISSUE TITLE
[examples] 2D camera example not working properly

### ISSUE THREAD

**Issue by DGMexe** [raysan5/raylib#965]
The existing one is not working on VS2017 C++. It compiles, but camera works badly.

**Comment by raysan5** [comment]
@DGMexe which one is not working? they work ok for me...

**Comment by kbitGit** [comment]
Not OP, but at least for me, the core_2d_camera example is not working.

The camera doesn't follow the player like in the web example.
![image](https://user-images.githubusercontent.com/15912312/65006973-f67d1580-d904-11e9-9b3d-7a6047a9891e.png)

The rotation seems to work
![image](https://user-images.githubusercontent.com/15912312/65007006-101e5d00-d905-11e9-99cf-da337e762ff5.png)


I tried with the release version and the current master branch
OS: Linux(Fedora 30)
G++ Version: 9.2.1

**Comment by DGMexe** [comment]
> 
> 
> Not OP, but at least for me, the core_2d_camera example is not working.
> 
> The camera doesn't follow the player like in the web example.
> ![image](https://user-images.githubusercontent.com/15912312/65006973-f67d1580-d904-11e9-9b3d-7a6047a9891e.png)
> 
> The rotation seems to work
> ![image](https://user-images.githubusercontent.com/15912312/65007006-101e5d00-d905-11e9-99cf-da337e762ff5.png)
> 
> I tried with the release version and the current master branch
> OS: Linux(Fedora 30)
> G++ Version: 9.2.1
Same thing happens to me.
OS: Windows 8.1

**Comment by raysan5** [comment]
@DGMexe are you using latest raylib version from github? Could you try with latest raylib and example from github? It was modified recently...

**Comment by DGMexe** [comment]
> 
> 
> @DGMexe are you using latest raylib version from github? Could you try with latest raylib and example from github? It was modified recently...

I'm using raylib 2.5 probably from here https://raysan5.itch.io/raylib so I think it's the recent version. Maybe i got it wrong but I see this example on github and it was modified a month ago. "This example has been created using raylib 1.5 (www.raylib.com)"  Also I'm in C++, and it's in C, so (Vector) gives me an error so I use Vector instead.

**Comment by raysan5** [comment]
@DGMexe latest raylib version is the 2.6-dev, it should be manually compiled from github.

**Comment by raysan5** [comment]
Retested examples, they work ok for me with latest raylib from github.

**Comment by pirey** [comment]
@raysan5 i can't find the `2.6-dev` branch / tag that you mentioned.

**Comment by raysan5** [comment]
@pirey it's the master branch, no release yet.
