### ISSUE TITLE
[core] AZERTY Keyboard mapping

### ISSUE THREAD

**Issue by Aghathis** [raysan5/raylib#974]
Test on Raylib 2.5 on windows

On a Raylib website Exemple on keyboard event when you use the method 
IsKeyDown(char)
passing 'A' will wait 'Q' to be pressed ('Z' -> 'W' etc...) 

Raylib seems to doesn't support different Keyboard Layout

**Comment by raysan5** [comment]
@Aghathis raylib uses internally GLFW to manage keyboard inputs. [Here a related question](https://stackoverflow.com/questions/31228979/azerty-keycode-with-glfw3).

Did you try passing `KEY_A` and `KEY_Z`?

**Comment by raysan5** [comment]
No answer, closing.
