### ISSUE TITLE
Raspberry Pi: Red square in the middle of the screen

### ISSUE THREAD

**Issue by piotrek-szczygiel** [raysan5/raylib#984]
Notice: I tested it on Windows and Linux and the bug on this platforms doesn't exist.

Every raylib example has red square in the middle of the screen.
This happens only on the native Raspberry Pi compilation and looks something like this: https://i.imgur.com/xInWfOr.jpg

Could this be a cursor? I tried turning cursor off but it didn't help.
I tested it without desktop environment and with LXDE and the red square was present on both.

**Comment by piotrek-szczygiel** [comment]
Maybe it has something to do with:
`#define SUPPORT_MOUSE_CURSOR_RPI`

But i didn't enable it anywhere.

**Comment by piotrek-szczygiel** [comment]
Fixed it by removing these lines and recompiling the library: https://github.com/raysan5/raylib/blob/master/src/core.c#L1205-L1209

Still, does anyone have any idea why the mouse is not working for me?
The cursor was so annoying, because it was static in the middle of the screen.
Im using the DietPi distribution, maybe it is causing the problem?

**Comment by Ggcpp** [comment]
For those who have the same problem, in "raylib/src/core.c" file, just remove these lines:
`#if defined(PLATFORM_RPI) && defined(SUPPORT_MOUSE_CURSOR_RPI)`
`// On RPI native mode we have no system mouse cursor, so,`
`// we draw a small rectangle for user reference`
`DrawRectangle(CORE.Input.Mouse.position.x, CORE.Input.Mouse.position.y, 3, 3, MAROON);`
`#endif`
and recompile the library.
