### ISSUE TITLE
[models] LoadAnimation failing (bug)

### ISSUE THREAD

**Issue by NedKJaims** [raysan5/raylib#988]
[model.zip](https://github.com/raysan5/raylib/files/3745759/model.zip)

When loading the animation of an IQM model, it does not respond and consumes a lot of memory around 1034MB.
When you load the model without the animations, it can be drawn and also load the bones (it works normal).

### Environment
Windows 10, OpenGL 3.3, Intel(R) HD Graphics 4400, Raylib 2.5

**Comment by raysan5** [comment]
@NedKJaims Excuse the late response. Please, could you test it with latest raylib from github master branch?

**Comment by NedKJaims** [comment]
![image](https://user-images.githubusercontent.com/47610687/69600490-6d561f00-0fd6-11ea-823e-f473204679ab.png)
No problem, I already compiled with the master branch, it doesn't give me an error anymore and it doesn't consume me much memory; The strange thing is that it loads the model and the bones but the animations. I am using an iqm converter for blender, but I don't know exactly what the error is :(

**Comment by raysan5** [comment]
Closing the issue for now.
