### ISSUE TITLE
[audio] Playing only half of module (bug)

### ISSUE THREAD

**Issue by tpanj** [raysan5/raylib#989]
- [X] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description
After simple playing example `audio_module_playing` realizing that only half of music module is playing (30s). Original module in sources resources/mini1111.xm is 62 seconds long. 

When changing examples/audio/audio_module_playing to play old module:

    Music music = LoadMusicStream("resources/chiptun1.mod");

Realized that GetMusicTimeLength(music) returns 3.78 
but should be 7.56 (Total samples/Sample rate)

INFO: [resources/chiptun1.mod] Music file successfully loaded:
INFO:    Total samples: 363007
INFO:    Sample rate: 48000 Hz
INFO:    Sample size: 16 bits
INFO:    Channels: 2 (Stereo)

### Environment
Linux

**Comment by raysan5** [comment]
@tpanj Thanks for reporting, yes, I verified the issue, I'll review it asap.
