### ISSUE TITLE
[core] ClearDirectoryFiles memory leak

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#991]
Please, before submitting a new issue verify and check:

 - [x ] I tested it on latest raylib version from master branch
 - [x ] I checked there is no similar issue already reported
 - [x ] My code has no errors or misuse of raylib

### Issue description

When getting directory files you allocate all the possible elements
in ClearDirectoryFiles
        //for (int i = 0; i < dirFilesCount; i++) RL_FREE(dirFilesPath[i]); <-- old behaviour
        for (int i = 0; i < MAX_DIRECTORY_FILES; i++) RL_FREE(dirFilesPath[i]);

### Environment

Linux

### Issue Screenshot

N/A

### Code Example
see issue description

**Comment by raysan5** [comment]
@chriscamacho thanks! :D
