### ISSUE TITLE
[audio] memory leak with multi channel sound

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#993]
Please, before submitting a new issue verify and check:

 - [x ] I tested it on latest raylib version from master branch
 - [x ] I checked there is no similar issue already reported
 - [x ] My code has no errors or misuse of raylib

### Issue description
There is a small amount of memory in the buffer of each channel closing the pools should look like this:
// Close the audio buffers pool
static void CloseAudioBufferPool()
{
    for (int i = 0; i < MAX_AUDIO_BUFFER_POOL_CHANNELS; i++) {
       RL_FREE(audioBufferPool[i]->buffer);  <--- additional code
       RL_FREE(audioBufferPool[i]);
    }
}

### Environment

Linux

### Issue Screenshot

N/A

### Code Example

see above

**Comment by raysan5** [comment]
@chriscamacho thanks! :D
