### ISSUE TITLE
[core] seg fault ClearDirectoryFiles

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#994]
You need to guard the Free as the first time its called it tries free(0) !
```
    if (dirFilesCount >0) {
        for (int i = 0; i < MAX_DIRECTORY_FILES; i++) RL_FREE(dirFilesPath[i]);

        RL_FREE(dirFilesPath);
    }
    dirFilesCount = 0;
```

**Comment by raysan5** [comment]
thanks @chriscamacho! it should be ok now...

**Comment by chriscamacho** [comment]
your fix didn't seem to do the trick, seg fault again but this time on the second call....

**Comment by chriscamacho** [comment]
either check dirFilesCount or make sure you NULL dirFilesPath ....!

**Comment by raysan5** [comment]
oh, ok, I understand now!
